### ISSUE TITLE
Alternate view inflation

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#1000]
I was thinking about #988 and the diversion I started in https://github.com/MvvmCross/MvvmCross/issues/994#issuecomment-99086405 ...

I'm wondering if we could achieve our layout binding in an alternate way by providing our own implementation of ```ContextWrapper``` and ```LayoutInflater``` like Calligraphy does.  We would attach this ```MvxContextWrapper``` in ```Activity.AttachBaseContext```  We could then wire up the binding like in https://github.com/MvvmCross/MvvmCross/blob/15d9e2469c6ce0a10f77a218f30761e5f694f2dd/Cirrious/Cirrious.MvvmCross.Binding.Droid/Binders/MvxBindingLayoutInflatorFactory.cs#L67 in our Inflater's ```OnCreateView``` after the factories have inflated their views.  I THINK (unverified) that would allow any attached ```LayoutInflater.Factory``` to run unlike now (we would basically do the binding magic after the factories have given us their view) and then for setups like AppCompat we could do away with the custom ```MvxAndroidViewFactory``` that's needed for material design.

It would also be passed to any attached fragments so I don't think we would need to do anything additional to support them.

Thoughts?  Is this reasonable/possible?

**Comment by slodge** [comment]
Any links into the source code for "like Calligraphy does"? I've no idea what this means - sorry :)

The original code was written to work with Android 1.6 through to 2.2 (the tip at the time)... it was the best place I could find to hook into the `attrs` and get the binding out. If there are other ways, then I'm happy to consider them

> Thoughts?

Might be "breaking" to lose some of the "abbreviation" code - so I guess we'd have to keep our inflator as well.

> Is this reasonable/possible?

No idea without trying it...

**Comment by cjlotz** [comment]
Just a possible alternative to consider for the layout inflating.  Why not define a simple interface, say ```IAppCompat``` that gives access to the ```AppCompatDelegate```.   If the context for inflation implements the interface, use the AppCompatDelegate to do the inflation using the Android Support Library code.  If the view returned from the inflation is ```null```, only then delegate to the base class to do the ```View``` inflation.  Something like the following perhaps:  

```
   public class AppCompatViewFactory : MvxAndroidViewFactory
    {
        public override View CreateView(View parent, string name, Context context, IAttributeSet attrs)
        {
            IAppCompat compat = context as IAppCompat;
            if (compat != null)
            {
                View view = compat.CompatDelegate.CreateView(parent, name, context, attrs);
                if (view != null)
                    return view;
            }
            return base.CreateView(parent, name, context, attrs);
        }
    }
```

This does require inheriting from ```AppCompatActivity``` or alternatively delegating to an internal instance of the ```AppCompatDelegate``` in the existing Mvx base class view infrastructure.

**Comment by kjeremy** [comment]
You can find Calligraphy [here](https://github.com/chrisjenx/Calligraphy).

I think that the factories are usually the correct way to handle custom layouts but after reading the docs they look to be more for inflating some things but not everything.  With AppCompat for instance they only inflate some widgets and if they don't recognize one they fall back to the next factory in the chain.

@cjlotz I thought of something like that but was hoping for a more general solution.

I haven't had time to take a crack at this yet but hopefully can try something out later this week.

**Comment by promontis** [comment]
Offtopic: Whoohoo... issue 1000 :) lol

**Comment by kjeremy** [comment]
So I have an implementation that does this.  It's a work in progress and the commits are ugly but it works.  I need to refactor some stuff and untangle but It's currently at https://github.com/kjeremy/MvvmCross/tree/inflation-fixes if anyone wants to try it.  Using this branch I can omit the gist at https://gist.github.com/kjeremy/5b76cb2eb82ff6caa046 for AppCompat views.

**Comment by kjeremy** [comment]
I'll submit a PR once it's in better shape
