### ISSUE TITLE
Throwing exception in Init() method isn't reported

### ISSUE THREAD

**Issue by SimonSimCity** [MvvmCross/MvvmCross#1006]
When I call an exception in an `Init()` method of a ViewModel, it seems like that exception never is reported anywhere ... Or am I just missing a subscription to an MvvmCross internal exception handler?

**Comment by slodge** [comment]
Linked to https://github.com/MvvmCross/MvvmCross/issues/837 ? There was even a test in the pull...https://github.com/MvvmCross/MvvmCross/pull/838/files

**Comment by SimonSimCity** [comment]
@slodge I tried it in my codebase and all exceptions are swallowed ... Is there a good way somehow to test where that exception was swallowed? Would be happy to have more to debug ... but just having the project as DLL makes it hard :wink:.

Can I just load this as project, remove the DLL, loaded in that project and take this as project-dependency? Will try that soon ...

**Comment by martijn00** [comment]
Linked to https://github.com/MvvmCross/MvvmCross/issues/1309

**Comment by SimonSimCity** [comment]
Ok, I reserved some time today to get deeper into this one.

As written in the docs (https://github.com/MvvmCross/MvvmCross/wiki/View-Model-Lifecycle#2-init), the `Init()` method is part of the lifecycle of a ViewModel and is called in https://github.com/MvvmCross/MvvmCross/blob/3c735adc534a5df2d4730e9d58a08f7863c30cee/MvvmCross/Core/Core/ViewModels/MvxDefaultViewModelLocator.cs#L48 that again calls my method here: https://github.com/MvvmCross/MvvmCross/blob/3c735adc534a5df2d4730e9d58a08f7863c30cee/MvvmCross/Core/Core/ViewModels/MvxViewModelExtensions.cs#L55

But at the end, all comes down to that I had a message-signature, that allowed me to return a `Task` and use the method as an _async_ method.

Of that, I finally learned how bad it is to either have a method, that returns `void` in an async method or how equally bad it is of me to call an async method but neither awaiting it nor doing something with the returned `Task`.

Here's a very short, but very good blog-post on it: http://www.axilis.com/2015/07/27/async-exception-handling-in-c/

**What we should do:**

Check if the response, given by the invoked method, is awaitable (f.e. by casting to Task), start logging the error-messages, or even better: inform the programmer by a warning, that those methods shouldn't return anything awaitable, but handle all possible exceptions within themselves and return void.

@martijn00 Am I missing something out here, or would that solve the problem - or at least inform the developer about it?

**Comment by promontis** [comment]
I think this would be a good candidate for a Roslyn validation rule. I however wouldn't start logging error-messages or inform programmers with a warning... programmers should know by now how to use async; this thing has been addresses in too many blogpost over the last years.

**Comment by willsb** [comment]
Me and @azchohfi will create this analyzer, just wait for the PR

**Comment by martijn00** [comment]
Use the new MvxNavigationService for async navigate which will throw errors.
