### ISSUE TITLE
SQLiteNet can't handle ConvertChecked

### ISSUE THREAD

**Issue by benhaben** [MvvmCross/MvvmCross#1008]
ConvertChecked will cause CompileExpr  throw new NotSupportedException("Cannot compile: " + expr.NodeType.ToString());

You can find the issue in the Plugins/Cirrious/Sqlite/Cirrious.MvvmCross.Plugins.Sqlite/SharedFile/SQLiteNet.cs

**Comment by slodge** [comment]
Compiling is definitely going to be tricky on jit-free iOS and Mac

I guess this is just not supported.

**Comment by benhaben** [comment]
Ok, Thank you!!
