### ISSUE TITLE
Windows 10 UWP (Universal Windows Platform) apps 

### ISSUE THREAD

**Issue by jonstoneman** [MvvmCross/MvvmCross#1009]
Opening this to coordinate efforts in adding support for UWP apps.  I've not looked at the platform in detail and not at all with regards to Mvx but shall be doing so soon.  Has anyone else had a play yet?

**Comment by ryanherman** [comment]
Yes, got my project to compile using MvvmCross 3.5.1 and my own Bindingex that was a Windows Phone 8.1 PCL.

**Comment by jonstoneman** [comment]
So WindowsCommon is pretty much compatible with WUP then?  I wasn't expecting it to be that easy! :)

**Comment by ryanherman** [comment]
Lets just say, it compiled but I didn't spend much time to get further than that.  The only major changes that were announced at Build 2015 is that the HardwareBackButton is not supported, you need to put assembly definitions if you want to use them.

**Comment by jonstoneman** [comment]
OK, I'll try to find some time over the next week or so to give it a go and find what other problems there are.

**Comment by CuriousCurmudgeon** [comment]
I can confirm that things have been surprisingly smooth so far. I had to tweak how I usually do navigation, but otherwise, everything is status quo.

**Comment by j-hayes** [comment]
I will also be doing some testing of this in the coming weeks. I will report back anything I find.

**Comment by ryanherman** [comment]
I notice an issues with Mvx.LazyConstructAndRegisterSingleton and getting an error saying 
System.TypeLoadException: Method 'get_DefaultProxy' in type 'Incroud.Mobile.Plugins.DeviceInfo.UWP.DeviceInfoPlugin' from assembly 'Incroud.Mobile.Plugins.DeviceInfo.UWP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. at Incroud.Mobile.UWP.Setup.InitializeContainers() at Incroud.Mobile.UWP.Setup.CreateApp() at Cirrious.MvvmCross.Platform.MvxSetup.CreateAndInitializeApp(IMvxPluginManager pluginManager) at Cirrious.MvvmCross.Platform.MvxSetup.Initialize
on
        public IWebProxy DefaultProxy => WebRequest.DefaultWebProxy;
Yet I have the implementation.

**Comment by Suthahar** [comment]
Hi,
I ma facing issue with Mvvmcross integration UWP app .can you please let me know if you have best solution 
I have posted issue in the below url 

https://github.com/MvvmCross/MvvmCross/issues/1066

Thanks

**Comment by azzlack** [comment]
Any news on this? The `Page` class that `MvxWindowsPage` derives from is the old version, not the Windows 10 one. Or is there a way to make it load the correct one?

**Comment by Cheesebaron** [comment]
I haven't installed Windows 10 yet, too many unresolved privacy issues. I don't want MS to breathe down my neck all the time.

**Comment by ryanherman** [comment]
Install in a VM?

**Comment by NPadrutt** [comment]
I installed the v4 beta 2 in a solution with an Android and a UWP project. In the Android project it works so far, but in the windows project there is no symbol for the setup found (I tried MvxWindowsSetup and MvxStoreSetup). It seems like an issue with the references. But when I try to add it manually it states that the reference already exists. Do I have to do something different for a Windows project?

**Comment by Cheesebaron** [comment]
Symbols are pushed to symbolsources.org every time we push NuGet packages:

See http://www.symbolsource.org/Public/Home/VisualStudio for setting it up.

**Comment by NPadrutt** [comment]
Sorry, I wrote a complete nonsense.. It cannot resolve the type of namespace. As if there is a reference missing.

**Comment by NPadrutt** [comment]
I guess I figured it out. I installed the the NuGet Package MvvmCross.HotTuna.MvvmCross. I removed everything and added MvvmCross.HotTuna.MvvmCrossLibraries in v4.0.0.0-beta1 what will add the other package as well. beta2 seems to make some issues so far..
