### ISSUE TITLE
Move support fragments library (Cirrious.MvvmCross.Droid.Fragging) to MvvmCross-AndroidSupport

### ISSUE THREAD

**Issue by jamie94bc** [MvvmCross/MvvmCross#1011]
Since we decided components dependent on the Android support library should be moved to a separate repository, shouldn't we do the same with fragments?

**Comment by Cheesebaron** [comment]
I would say yes. I would also say that we move forward and push everything that has to do with `Fragment` is strictly dependent on support packages, meaning no "FullFragging". This will streamline behavior and possibilities between platforms.

**Comment by kjeremy** [comment]
Should we align these with the Android support packages like ```MvvmCross-AndroidSupport.V7```, ```MvvmCross.AndroidSupport.RecyclerView``` (etc.) or something like that?

**Comment by jamie94bc** [comment]
I think `Cirrious.MvvmCross.Droid.Support.RecyclerView` would be better naming (considering we may want to support API 21 recycler view)?

I don't think we should me mimicking the support libraries namespaces exactly though :-1:

**Comment by martijn00** [comment]
Thanks, this is done now.
