### ISSUE TITLE
App size is too large

### ISSUE THREAD

**Issue by benhaben** [MvvmCross/MvvmCross#1014]
I use MvvmCross 3.2 to develop iOS and android app, but my iOS app size is 59m now,  it is very big because i will develop more feature in my app. Could you tell me how to reduce the size.

**Comment by slodge** [comment]
Take a look in the package - work out where the size is.

**Comment by slodge** [comment]
For other "how do I?" please use StackOverflow or some other forum - I do try to keep this Issues list for Mvx bugs and issues rather than for app questions. Thanks :+1:

**Comment by benhaben** [comment]
Thank you !
