### ISSUE TITLE
How to share a ViewModel? Add the Fragment parameter to OnFragmentChanging() event?

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross#1015]
I want to share one of my ViewModel across multiple fragments, so I removed the  [MvxOwnedViewModelFragment] attribute from all the fragments, but I was wondering how am I supposed to set the ViewModel for those fragments...

Since the fragments gets instantiated inside the ShowFragment()
https://github.com/MvvmCross/MvvmCross/blob/2b1e44e5837acb7e4f9c12019df0369abf33e384/Cirrious/Cirrious.MvvmCross.Droid.Fragging/MvxCachingFragmentActivity.cs#L213
And they gets resumed just after the transaction has been commited, I added a Fragment parameter to the OnFragmentChanging() event:
https://github.com/MvvmCross/MvvmCross/blob/2b1e44e5837acb7e4f9c12019df0369abf33e384/Cirrious/Cirrious.MvvmCross.Droid.Fragging/MvxCachingFragmentActivity.cs#L255
So, I can set their ViewModel by overriding the OnFragmentChanging event...

Does exists a better approach that doesn't involve modifying the current mvvmcross code?

**Comment by Cheesebaron** [comment]
You have the transaction, that should be enough?

**Comment by IlSocio** [comment]
Actually, given the transaction I don't know how to retrieve the fragment(s) involved... It doesn't seems to be possible to me, but it would be perfect, do you have any further suggestion Tomasz?

**Comment by martijn00** [comment]
Does https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/86 fix it for you?

**Comment by IlSocio** [comment]
Indeed, it does ;)
By handling OnFragmentCreated() we can now set the ViewModel before the transaction gets commited...
Nice work!
