### ISSUE TITLE
SaveState and RestoreState not being called for iOS applications  

### ISSUE THREAD

**Issue by sisterray** [MvvmCross/MvvmCross#1016]
I am writing a multi-platform application which will be run on iOS and Android. However I have an issue when the app going into the background on an iOS app. The SaveState and RestoreState methods are not being called for the iOS application. It works for Android.

Is this the expected behaviour for iOS? If so would it be possible to explain why so I can implement my own solution. I've scoured the web for some information about this but have come up short

I am using v3.5.0 of MvvmCross

**Comment by slodge** [comment]
I don't believe there's any state saving/restoring implemented for iOS.
Android and Windows are different to iOS - they provide "platform level presenters" which restore the application state (e.g. they restore main frame and the navigation back stack).
On iOS it's left for the application developer to do this themselves - depending on what the application structure is. (Also, on iOS the application "tombstoning" cycle feels very different to Android and Windows - iOS feels less aggressive about it's culling)
I doubt there's a "one size fits all" solution for all iOS apps - it would depend a lot on their presenters, but 'd be happy to see some example samples or recipes contributed about how to handle saving/restoring.

**Comment by sisterray** [comment]
Thanks for the clarification. I'll have a think about how I solve this.

I guess this issue can now be closed since this is expected behaviour
