### ISSUE TITLE
Windows Phone 8.1 back navigation issue

### ISSUE THREAD

**Issue by PelleRavn** [MvvmCross/MvvmCross#1018]
Hi

I'm pretty new to Windows Phone development, so it might just be me, who doesn't understand some basic practices of Windows Phone.
I started on a very basic app, that uses native Windows Phone screens and element. And at some point I pressed the hardware back button on the phone, and expected to go a step back in view. But what happened was it put the app in the background and exited to the home screen.
I though that I had messed up some settings somewhere, but then I tried to create a completely new project with just the basic elements from MvvmCross hot tuna, and 2 very simple view models. - And the same happens here.

Am I completely wrong, that this is unexpected behavior from the default installation of MvvmCross?
I am aware that I could write a custom presenter, but this is basic Windows Phone navigation, and I don't think I have to write one myself, to get this behavior by default. - And I'm not skilled enough in Windows Phone to actually know how this should be done right.

I've looked around the web, and found this solution: http://danielhindrikes.se/windows-phone/handle-windows-phone-back-button-pressed-when-using-mvvm/
But this results in a warning from the current presenter, saying "*Ignoring close for viewmodel - rootframe's current page is not the view for the requested viewmodel*". It does, however, go "a step back", but it creates a new view model, instead of using the old one.

I added the sample project here, but to recreate: Make a simple solution with a core and Windows Phone app, and navigate from one view model to another, and then press the back button.
https://www.dropbox.com/s/4j226obw4w88b2l/NavigationTest.zip?dl=0

Can someone here tell if I'm completely wrong about this, or if this is a bug (since it behaves the way I expect it to in the video tutorials)?

Thanks.

**Comment by Cheesebaron** [comment]
Might be related to: https://github.com/MvvmCross/MvvmCross/pull/760

**Comment by PelleRavn** [comment]
@Cheesebaron I think you might be right (I was thinking of linking to it, but it escaped my mind).
Although, that issue is about caching views/VMs, and (from what I read) have the correct behavior of going back, but just with a new VM. The issue I'm posting, is that it's "missing" the navigation back step logic competently from a new, fresh, project.

**Comment by promontis** [comment]
@PelleRavn @Cheesebaron It is definitely related! I've seen this behavior as well if you do not use NavigationHelper. I'll try to reproduce it with a normal Windows Phone app, to see what the behavior without MVVMCross is

**Comment by PelleRavn** [comment]
@promontis I think you would get the same behavior with a normal Windows Phone app, if you remove the NavigationHelper from the project.
But the thing is, you are required to remove it, by the To-Do guide in MvvmCross:
```
5. For Windows 8.1 - Add a views folder and a view based on the BasicPage template
  - In the .xaml.cs - remove public NavigationHelper NavigationHelper and all referencing code
  - In the .xaml.cs - remove the OnNavigatedTo and OnNavigatedFrom handlers
```
That's why I expect MvvmCross to handle this for me, since I have to remove only thing that otherwise would help me just a bit (if you look away from the fact that nothing will work, if the NavigationHelper code stays in the code-behind file).

**Comment by promontis** [comment]
@PelleRavn Ah, if that's the case, then you should definitely use the NavigationHelper and the to-do guide in MvvmCross should be updated! I did update the tutorial in the wiki.

**Comment by PelleRavn** [comment]
@promontis Okay, so, I got a solution that works, that combines use of the NavigationHelper, and the ```NavigationCacheMode = NavigationCacheMode.Required;``` parameter added on each code-behind file.

One thing is, that the two overwritten methods in each code-behind view ```OnNavigatedTo()``` and ```OnNavigatedFrom()``` needs to call their base-class for MvvmCross to function properly.

I still think that the logic from the NavigationHelper class (as a part of the view class), and an option to enable/disable navigation caching application-wide (maybe in the App.xaml.cs file at setup point), should find it's way to the MvvmCross Windows Phone/Common core, so I don't have to add that much duplicated code in every single code-behind file. I'm not well known in Windows Phone/Common and MvvmCross Core at this time to add this myself, but if I do at some point, I will make a pull request for this.

Correct me if it's nonsense what I just said, or I'm doing this completely wrong.

**Comment by promontis** [comment]
@PelleRavn Nice! I don't know if we should enable/disable navigation caching application-wide. This could be harmfull. I think we should follow WP guidelines. 

For the duplicate code, you could add a base class yourself and have each view you make, inherit from that baseview. In that base view you could add the code to always enable navigation caching (but I don't recommend that... set it in each xaml file). I do recommend that you implement the navigation methods needed for the NavigationHelper class in there.  

@Cheesebaron @slodge What do you think? Should we move the NavigationHelper method implementations in the MvvmCross base view class?

**Comment by CuriousCurmudgeon** [comment]
NavigationHelper is useful, but the navigation pattern changed slightly (yet again) for Windows 10. All Windows 10 platforms now handle navigation the same way. For phone, this means that the HardwareButtons.BackPressed event that NavigationHelper wires up no longer exists. Instead, all platforms use SystemNavigationManager.BackRequested. Overall, this is an improvement, but I'm not sure how MvvmCross should handle it.

**Comment by PelleRavn** [comment]
@CuriousCurmudgeon That's interesting, thanks for adding that - Will note that for when Windows 10 is launched.

**Comment by Cheesebaron** [comment]
I ended up doing something like this: https://gist.github.com/Cheesebaron/3d33daf4b76dc091e26e I mimics some of the stuff NavigationHelper does, the suspension stuff is already in MvvmCross. This could probably be expanded a bit to work in Store apps as this only works for Phone projects.

**Comment by tsan** [comment]
Hi,

I have the same problem. There is a solution for this now?
I tried the different solution, but nothing work.

I follow _ Windows Store UI.txt, try the BaseView.cs, so the different solution.

@PelleRavn What did you use for work your project? 

Thanks

**Comment by PelleRavn** [comment]
I ended up making a base class that gave me the handles for LoadState and SaveState and could override the methods for each view-class if I needed it to save or load the state.
I could then enable and disabled the cache mode for each view, in the constructor, with ```NavigationCacheMode = NavigationCacheMode.Disabled;```.

But I will say, that for the most part, I would prefer to save the information (state) for the view somewere, and then re-make the view, if I needed to. But I think that would be different for each project, if I preferred to do it that way.

Hope it helps you.
Where's the base class I made (looks a lot like the one you get in a new view):
```
public abstract class BaseView : MvxWindowsPage
    {
        private NavigationHelper navigationHelper;

        public BaseView()
        {
            this.navigationHelper = new NavigationHelper(this);
            this.navigationHelper.LoadState += this.NavigationHelper_LoadState;
            this.navigationHelper.SaveState += this.NavigationHelper_SaveState;
        }


        /// <summary>
        /// Gets the <see cref="NavigationHelper"/> associated with this <see cref="Page"/>.
        /// </summary>
        public NavigationHelper NavigationHelper
        {
            get { return this.navigationHelper; }
        }

        /// <summary>
        /// Populates the page with content passed during navigation.  Any saved state is also
        /// provided when recreating a page from a prior session.
        /// </summary>
        /// <param name="sender">
        /// The source of the event; typically <see cref="NavigationHelper"/>
        /// </param>
        /// <param name="e">Event data that provides both the navigation parameter passed to
        /// <see cref="Frame.Navigate(Type, Object)"/> when this page was initially requested and
        /// a dictionary of state preserved by this page during an earlier
        /// session.  The state will be null the first time a page is visited.</param>
        protected virtual void NavigationHelper_LoadState(object sender, LoadStateEventArgs e)
        {
        }

        /// <summary>
        /// Preserves state associated with this page in case the application is suspended or the
        /// page is discarded from the navigation cache.  Values must conform to the serialization
        /// requirements of <see cref="SuspensionManager.SessionState"/>.
        /// </summary>
        /// <param name="sender">The source of the event; typically <see cref="NavigationHelper"/></param>
        /// <param name="e">Event data that provides an empty dictionary to be populated with
        /// serializable state.</param>
        protected virtual void NavigationHelper_SaveState(object sender, SaveStateEventArgs e)
        {
        }

        #region NavigationHelper registration

        /// <summary>
        /// The methods provided in this section are simply used to allow
        /// NavigationHelper to respond to the page's navigation methods.
        /// <para>
        /// Page specific logic should be placed in event handlers for the  
        /// <see cref="NavigationHelper.LoadState"/>
        /// and <see cref="NavigationHelper.SaveState"/>.
        /// The navigation parameter is available in the LoadState method 
        /// in addition to page state preserved during an earlier session.
        /// </para>
        /// </summary>
        /// <param name="e">Provides data for navigation methods and event
        /// handlers that cannot cancel the navigation request.</param>
        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
            this.navigationHelper.OnNavigatedTo(e);
        }

        protected override void OnNavigatedFrom(NavigationEventArgs e)
        {
            base.OnNavigatedFrom(e);
            this.navigationHelper.OnNavigatedFrom(e);
        }

        #endregion
    }
```
