### ISSUE TITLE
Is there any binding option to bind a control's value to a property?

### ISSUE THREAD

**Issue by Binjaaa** [MvvmCross/MvvmCross#1021]
I have a cross-platform solution and one of my project is Android with the use of MvvmCross.
The case is simple as a needle. I have a TextView (aka Label) and a slider control and i need to display the actual value of the slider in the label with the given format. ( for example converter ).

Is there any or quite similar solution to a xaml-style bind?
Thank's in advance!

**Comment by kjeremy** [comment]
In the future please ask on StackOverflow. however...

Here's a snippet that I use.  My ViewModel has a MapInitialZoom integer.  Seekbar just happens to be a value converter I use to adjust between the min and max

```
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:MvxBind="Text Format('Zoom Level {0}', MapInitialZoom)" />
    <SeekBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:max="21"
        app:MvxBind="Progress Seekbar(MapInitialZoom, 1)" />
```

So really you can do:


```
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:MvxBind="Text SomeValue" />
    <SeekBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:max="21"
        app:MvxBind="Progress SomeValue" />
```

**Comment by kjeremy** [comment]
Apparently I can't close issues that I don't open.  Can someone do this?
