### ISSUE TITLE
NuGet unable to install MvvmCross.HotTuna.MvvmCrossLibraries in VS2015 RC

### ISSUE THREAD

**Issue by rubenvb** [MvvmCross/MvvmCross#1023]
The command returns an error (it's in Dutch here, so can't helpfully copy-paste) about Lucene.Net:

    Lucene.Net, Version=3.0.3.0, Culture=neutral, PublicKeyToken=85089178b9ac3181

How can I solve this? Searching for Lucene.net, I only find version 2.9.2.2, which probably won't work.

**Comment by Cheesebaron** [comment]
Ehm... Lucene is not a dependency of MvvmCrossLibraries nuget.

**Comment by rubenvb** [comment]
You're right. A VS2015 repair installs did the trick. Something was incredibly messed up on my end. Sorry for the noise and keep up the good work!
