### ISSUE TITLE
Add ability to request current device location with async API

### ISSUE THREAD

**Issue by SlyNet** [MvvmCross/MvvmCross#1024]
Currently IMvxGeoLocationWatcher doesn't provide a method like

```
CancellationTokenSource source = new CancellationTokenSource();
source.CancelAfter(TimeSpan.FromSeconds(30));
var location = await watcher.GetCurrentLocationAsync(source.Token);
```

If its possible it'd be really nice to have

**Comment by jamie94bc** [comment]
You mean `IMvxLocationWatcher` (that has replaced `IMvxGeoLocationWatcher`)?

Seems like a nice idea (although I'm not sure how fitting it is with the current API), perhaps two overloads - one with a `CancellationToken` and one with a `TimeSpan` to reduce code duplication that would be required in your example?

Feel free to submit a PR and we can review :smile:

**Comment by Cheesebaron** [comment]
I think this is an issue for github.com/MvvmCross/MvvmCross-Plugins
