### ISSUE TITLE
ArgumentNullException with Email plugin

### ISSUE THREAD

**Issue by scastria** [MvvmCross/MvvmCross#1025]
When using the email plugin to compose an email on Android running API 22, I get a null exception:
`[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.ArgumentNullException: Argument cannot be null.
[MonoDroid] Parameter name: source
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00078>
[MonoDroid] at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) <IL 0x00006, 0x0006b>
[MonoDroid] at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.733388bc-5729-4689-a56e-04f5f15132af (intptr,intptr) <IL 0x00011, 0x0003b>
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable
`

Looking at the source of the email plugin, I notice it was changed on March 11 by Dragon160 to use StartActivityForResult instead of StartActivity.  I also noticed that since MvvmCross is still based on Gingerbread, the signature for StartActivityForResult is different from the current version of Xamarin.Android targetting Android version 5.0.
I don't know what is causing the exception, but if I copy the source from the email plugin into my app code and fix the StartActivityForResult arguments to match my target Android version of 5.0, the compose email task starts working.

**Comment by scastria** [comment]
After debugging more closely, it is a simple null pointer exception on this line in the email plugin:
`            var attachmentList = attachments as IList<EmailAttachment> ?? attachments.ToList();
`

If attachments is null, then this line results in a null pointer exception.  And perhaps attachments will be null for most uses of this plugin.

It looks like the workaround is to use the "Ex" flavor of the interface so that I can submit an empty list for attachments instead of a null pointer.

**Comment by Cheesebaron** [comment]
There are already two pulls fixing this: https://github.com/MvvmCross/MvvmCross/pull/1010 and https://github.com/MvvmCross/MvvmCross/pull/1019

**Comment by scastria** [comment]
Sorry, I checked the Issues list but didn't check pulls.  Thanks for the quick response.
