### ISSUE TITLE
Android GroupItemTemplate instead of MvxGroupItemTemplate attribute for MvxExpandableListView

### ISSUE THREAD

**Issue by ljeancler** [MvvmCross/MvvmCross#1029]
I'm testing the new MvxExpandableListView in MvvmCross 3.5.1 and I was wondering why the group item template is named "GroupItemTemplate" instead of "MvxGroupItemTemplate" like the "old naming convention" used for Android Mvx controls (Mvx prefix) ?

It maybe a stupid question, but I'm so "Mvxed" that I first wrote my axml with MvxGroupItemTemplate and had to search why the build of my app failed...

Wrong, obsolete MvxBindingAttributes ? No wrong name, my bad : I was expecting "MvxGroupItemTemplate".

No offense but Android attributes naming convention for Mvx controls seems inconsistant.

And btw, thank's you all for the MvxExpandableListView, great work !

Regards,

Laurent

**Comment by Cheesebaron** [comment]
Make a Pull Request fixing this.

**Comment by ljeancler** [comment]
Done : https://github.com/MvvmCross/MvvmCross/pull/1031

**Comment by martijn00** [comment]
Thanks!

**Comment by srianbury** [comment]
I followed this (https://stackoverflow.com/questions/31455861/using-mvxexpandablelistview) to get my ExpandableListView working some what.  My MvxExpandableListView has its item source bound to a List.  The List has a description and a submenu list.  The list_assignment_header shows my headers (bound to the description) but the program crashes when I try to click on a header.  Any ideas on how to fix this?
