### ISSUE TITLE
Cannot convert lambda expression to type 'string' because it is not a delegate type

### ISSUE THREAD

**Issue by BrunoVT1992** [MvvmCross/MvvmCross#1034]
I get this error in my binding: "Cannot convert lambda expression to type 'string' because it is not a delegate type". This ahppen on this line of code: "bindings.Bind(userNameTextView).For(x => x.Layer.BorderColor).To(x => x.LoginError).OneWay();".

using System;
using System.Drawing;
using Foundation;
using UIKit;
using CoreGraphics;
using Cirrious.MvvmCross.Touch.Views;
using MvvmCross_POC.Shared.ViewModels;
using Cirrious.MvvmCross.Binding.BindingContext;
using MvvmCross_POC.iOS.Converters;
using System.Linq;

namespace MvvmCross_POC.iOS.Views
{
    public partial class LoginViewController : MvxViewController
    {
        public override void ViewDidLoad()
        {
            this.Title = "login";

            this.View.BackgroundColor = UIColor.White;

            var loginView = new UIView(){
                Frame = new RectangleF((float)this.View.Bounds.Width / 4, (float)this.View.Bounds.Height / 4, (float)this.View.Bounds.Width / 2, (float)this.View.Bounds.Height / 2)
            };

            var userNameTextView = new UITextView()
            {
                Frame = new RectangleF(0, 0, (float)loginView.Bounds.Width, 30),
                AutoresizingMask = UIViewAutoresizing.FlexibleWidth
            };
            userNameTextView.Layer.BorderColor = UIColor.LightGray.CGColor;
            userNameTextView.Layer.BorderWidth = 1;
            userNameTextView.Layer.CornerRadius = 5;

            var passwordTextView = new UITextView()
            {
                Frame = new RectangleF(0, 50, (float)loginView.Bounds.Width, 30),
                SecureTextEntry = true,
                AutoresizingMask = UIViewAutoresizing.FlexibleWidth
            };
            passwordTextView.Layer.BorderColor = UIColor.LightGray.CGColor;
            passwordTextView.Layer.BorderWidth = 1;
            passwordTextView.Layer.CornerRadius = 5;

            var loginButton = new UIButton() {
                Frame = new RectangleF((float)(loginView.Bounds.Width / 2) - 50, 100, 100, 30)
            };
            loginButton.SetTitle("Login", UIControlState.Normal);

            loginView.AddSubviews(userNameTextView, passwordTextView, loginButton);
            
            this.View.AddSubview(loginView);

            var bindings = this.CreateBindingSet<LoginViewController, LoginViewModel>();
            bindings.Bind(userNameTextView).For(x => x.Text).To(x => x.UserName).OneWayToSource();
            bindings.Bind(userNameTextView).For(x => x.Layer.BorderColor).To(x => x.LoginError).OneWay();
            bindings.Bind(passwordTextView).For(x => x.Text).To(x => x.Password).OneWayToSource();
            bindings.Bind(loginButton).For("TouchUpInside").To(x => x.LoginCommand);
            bindings.Apply();

            base.ViewDidLoad();
        }
    }
}

**Comment by Cheesebaron** [comment]
Please ask questions like these on StackOverflow. We try to keep github for actual issues.

You can obviously not bind LoginError, to a Color without a converter of some sort.

**Comment by slodge** [comment]
and you'll need to only do one hop in the `For` like:

             .Bind(userNameTextView.Layer).For(x => x.BorderColor)

Might be better off doing some custom binding

**Comment by BrunoVT1992** [comment]
http://stackoverflow.com/questions/30938794/mvvmcross-cannot-convert-lambda-expression-to-type-string-because-it-is-not-a
