### ISSUE TITLE
Use of First() in Get<T>

### ISSUE THREAD

**Issue by gabrieligbastos** [MvvmCross/MvvmCross#1038]
Hi,

Not sure if it is an issue or I'm using wrong.
But in the Shared files, in the Get<T> methods, you are using:

        public T Get<T>(object pk) where T : new()
        {
            var map = GetMapping(typeof (T));
            return Query<T>(map.GetByPrimaryKeySql, pk).First();
        }

The first() in the query. But, for example, i'm using the Get method to check if the object exists. When it does not exist, it throws an exception. Should not use FirstOrDefault() instead of First()?

**Comment by lothrop** [comment]
How about using `public T Find<T>(object pk) where T : new()`?
