### ISSUE TITLE
MvvmCross as a Code-Aware Library with Roslyn Code Analyzers

### ISSUE THREAD

**Issue by Stephanvs** [MvvmCross/MvvmCross#1040]
Hi guys,

I've been kind of investigating and writing a sample Code Analyzer and Code Fix Provider with the new .NET Compiler Platform (Roslyn). After watching [this talk](https://channel9.msdn.com/Events/Build/2015/3-725) by Dustin Campbell, I was inspired to try and write one myself. I did and wrote about it on [my blog](http://stephanvs.com/mvvmcross-as-a-code-aware-library-through-code-analyzers/), for detecting this

```csharp
class FirstView : Activity
{
    public new FirstViewModel ViewModel { get { return base.ViewModel as FirstViewModel; } }
}
```

and transforming it into this

```csharp
class FirstView : Activity<FirstViewModel>
{
}
```

It's just one simple example I could think of myself, but I guess there are many more places where MvvmCross has a _certain way of doing things_ that can be detected, where we can provide guidance for developers and push them in the right direction (pit of success).

I'm really curious to find out what you think about it and if you maybe have any ideas on what other kinds of analyzers we can come up with?

**Comment by Cheesebaron** [comment]
Cool stuff! Did you tweet about it, would happily retweet!

**Comment by Stephanvs** [comment]
Also tweeted about it indeed, https://twitter.com/Stephanvs/status/614182596323475456. RT would be much appreciated. :angel:

**Comment by Dexyon** [comment]
Cool initiative! I was thinking of how we could use the analytics of the compiler to create a call-graph to visualise the viewmodel navigation.

**Comment by martijn00** [comment]
Let's keep this issue open for a bit. If you have any proposals for new Code Analyzers drop them here!
