### ISSUE TITLE
iOS: Replacing an image using MvxImageViewLoader fails ...

### ISSUE THREAD

**Issue by SimonSimCity** [MvvmCross/MvvmCross#1041]
Since updating to the latest Alpha, I get the following warning in the output:

> 2015-06-26 09:23:57.425 BMMUIiOS[16211:2637202] mvx: Error:  20,25 UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.

The code triggering it is a binding inside a table view cell, using `MvxImageViewLoader` to dynamically set an image using a value converter.

The code in my table view cell looks like this:

    public partial class TrackTableViewCell : MvxTableViewCell
    {
        public static readonly UINib Nib = UINib.FromName("TrackTableViewCell", NSBundle.MainBundle);
        public static readonly NSString Key = new NSString("TrackTableViewCell");

        private readonly MvxImageViewLoader typeImageViewLoader;

        public TrackTableViewCell(IntPtr handle)
            : base(handle)
        {
            typeImageViewLoader = new MvxImageViewLoader(() => TypeImage);

            this.DelayBind(() =>
            {
                var set = this.CreateBindingSet<TrackTableViewCell, CellWrapperViewModel<Track>>();
                set.Bind(typeImageViewLoader).To(vm => vm.Item.Subtype).WithConversion("TrackTypeToImage");
                set.Apply();
            });
        }

        public static TrackTableViewCell Create()
        {
            return (TrackTableViewCell)Nib.Instantiate(null, null)[0];
        }
    }

The value converter always returns a string like `res:icon_category_audio.png`. I verified that this image is visible when using the last stable version of MvvmCross.

I'm currently looking into that issue, but you're probably getting far easier to the fix than I :wink:

Today I tried it by using the master and I ended up with this message:

> 2015-06-26 08:40:02.873 BMMUIiOS[16129:2630120] MvxBind: Warning:  13,70 Failed to create target binding for binding ImageUrl for Selected

**Comment by SimonSimCity** [comment]
I now got some time to write down a test repository. You can test the bug here: https://github.com/SimonSimCity/MvvmCrossImageBug

This repository includes MvvmCross as submodule - so depending on your GIT client, you may have to initialize the submodule by hand :wink:

Here I again get the message, referenced at the top. I guess I just had some problems why I got the other error message ...

**Comment by Cheesebaron** [comment]
Thanks, I will have a look at this later today.

**Comment by Cheesebaron** [comment]
Creating a new alpha build today. Thanks for the repro sample, made it a lot easier to debug :+1:

**Comment by SimonSimCity** [comment]
Thanks for that quick response. As I now know how, I'll reference to a test-project when running into the next bug :wink:
