### ISSUE TITLE
IMvxAndroidCurrentTopActivity > Activity = null during Fragment.OnCreate()

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross#1044]
Hello everyone, 
I think I just found an issue in MVVMCross Fragments and unfortunately, after spending some time on it, I wasn't able to fix it on my own... 

When the "Developers Options > Don't keep activities" flag is set and the Activity is brought back from background to foreground, in the "Fragment > OnCreate()" the IMvxAndroidCurrentTopActivity.Activity should point to the current activity, but it returns null instead :(

As my understanding, it happens because the LifeTimeMonitor.OnCreate() is called only after the Activity.OnCreate() has been completed.
So, when the Fragment.OnCreate() gets called, the LifeTimeMonitor.Activity is still null.
The LifeTimeMonitor.OnCreate() should be called after the Activity.OnCreate and before the Fragment.OnCreate()
But I don't know how to properly fix it...

Above all, the issue affects the ViewModel side, because since all the CIRS event are called during the View.OnCreate(), it is impossible to safely use any Gui service from a ViewModel during the CIRS...

Did anyone already face such issue?
Marco.

**Comment by Cheesebaron** [comment]
Why can't you use the Activity property on the Fragment itself?

**Comment by IlSocio** [comment]
Because I'm showing a ProgressDialog from the ViewModel, during the ViewModel.OnStart()

**Comment by IlSocio** [comment]
As very ugly workaround, I used this code in my fragment class:
```        public override void OnAttach(Android.App.Activity activity)
        {
            base.OnAttach(activity);
            IMvxAndroidActivityLifetimeListener list = Mvx.Resolve<IMvxAndroidActivityLifetimeListener>();
            list.OnStart(activity);
        }
```

**Comment by Cheesebaron** [comment]
I think we could do what @jamesmontemagno's Permission plugin does with top activity, by hooking into the events in Application on Android. I think this would be a better way to get current top Activity persistently.

**Comment by kjeremy** [comment]
Does that work with multiwindow?

**Comment by Cheesebaron** [comment]
@kjeremy Not sure. Will need investigation. Does multi window work with multiple windows from the same app? I don't have a Nougat device currently (stupid slow manufacturers...), so no idea how exactly it works.

**Comment by jamesmontemagno** [comment]
I am pretty sure it will because it sets it on the start/stop. There is only one activity at a given time. Although not tested.
