### ISSUE TITLE
Using multiple MvxRadioGroup bindings in a view only causes the first to be bound

### ISSUE THREAD

**Issue by andyci** [MvvmCross/MvvmCross#1045]
I've created an example using the latest binaries from the trunk:

https://github.com/andyci/MvvmCross-RadioGroupBindingIssue

This was working in 3.5.1 so I suspect it may have something to do with the layout inflater changes?

**Comment by andyci** [comment]
0acfee77dce2f3057d6be4ab85440bcda8030621 has caused this.
@kjeremy is this something wrong with the MvxRadioGroup view?

**Comment by Cheesebaron** [comment]
There were some fixes for bindings, which didn't make it into alpha1. Please try alpha2, which was released earlier today.

**Comment by andyci** [comment]
Sorry should have been more clear- I am compiling from the trunk as it is today

**Comment by andyci** [comment]
I then reverted 0acfee77dce2f3057d6be4ab85440bcda8030621 in my local copy and the bindings now work correctly

**Comment by kjeremy** [comment]
@andyci How does this manifest itself?  I can click on the radio buttons and they say "1" and "2".  Is that the correct behavior?

**Comment by andyci** [comment]
Yes if you look into the layout file you will see there is a second radiogroup which never appears.  This worked fine in 3.5.1

**Comment by kjeremy** [comment]
Crazy.  I don't see how the layout inflater could have made a difference.  Do you have an idea or hint about how the commit causes the issue?  I don't see anything special about `MvxRadioGroup` or `RadioButton`

**Comment by kjeremy** [comment]
Ok I found the issue. I'm not handling nested binding contexts.

**Comment by andyci** [comment]
Great work!
