### ISSUE TITLE
MvxBind Error, MissingMethodException when trying to filter List

### ISSUE THREAD

**Issue by xplatsolutions** [MvvmCross/MvvmCross#1046]
I am using MvvmCross version 3.5.0 and binding. I want to filter a list in Android and iOS. In iOS it is working as expected but in Android I get the application output below.

The exception is thrown when I type a letter in the SearchView.

    MvxBind:Error: 11.97 Problem seen during binding execution for binding ItemsSource for FieldNotes - problem TargetInvocationException: Exception has been thrown by the target of an invocation.
    	  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00062] in <filename unknown>:0 
      at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
      at Cirrious.MvvmCross.Binding.Bindings.Target.MvxPropertyInfoTargetBinding.SetValueImpl (System.Object target, System.Object value) [0x0000d] in <filename unknown>:0 
      at Cirrious.MvvmCross.Binding.Bindings.Target.MvxConvertingTargetBinding.SetValue (System.Object value) [0x00089] in <filename unknown>:0 
      at Cirrious.MvvmCross.Binding.Bindings.MvxFullBinding.UpdateTargetFromSource (System.Object value) [0x00023] in <filename unknown>:0 
    InnerException was MissingMethodException: No constructor found for GTas.Mobile.Core.Droid.Util.WrappingList`1[[GTas.Mobile.Application.DTO.FieldNoteDTO, GTas.Mobile.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]::.ctor(System.Collections.ObjectModel.ObservableCollection`1[GTas.Mobile.Application.DTO.FieldNoteDTO], System.Action`1[GTas.Mobile.Application.DTO.FieldNoteDTO])
    	  at System.Activator.CreateInstance (System.Type type, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00113] in <filename unknown>:0 
      at System.Activator.CreateInstance (System.Type type, System.Object[] args, System.Object[] activationAttributes) [0x00007] in <filename unknown>:0 
      at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <filename unknown>:0 
      at GTas.Mobile.Phone.Droid.Views.MvxSwipeListView.set_ItemsSource (IEnumerable value) [0x00088] in /Users/gtas_user/Documents/Project/GTas.Mobile.Phone.Droid/Views/MvxSwipeListView.cs:106 
      at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

My ViewModel related properties and methods.

    

    private IList<FieldNoteDTO> _fieldNotes;
    public IList<FieldNoteDTO> FieldNotes
    {
        get
        {
			if (string.IsNullOrEmpty(_filterText))
			{
				return _fieldNotes;
			}

			return FilterNotes(_filterText);
        }
        set
        {
            _fieldNotes = value;
            RaisePropertyChanged(() => FieldNotes);
        }
    }

    private string _filterText;
	public string FilterText
	{
		get { return _filterText; }
		set
		{
			_filterText = value;
			RaisePropertyChanged(() => FilterText);
			RaisePropertyChanged(() => FieldNotes);
		}
	}

    private ObservableCollection<FieldNoteDTO> FilterNotes(string filterText)
	{
		string filterTextLowerCase = filterText.ToLowerInvariant();
		var filtered = _fieldNotes.Where(fieldNote =>
			fieldNote.Note.ToLowerInvariant().Contains(filterTextLowerCase) ||
			fieldNote.Title.ToLowerInvariant().Contains(filterTextLowerCase));
		return new ObservableCollection<FieldNoteDTO>(filtered);
	}

The FieldNoteDTO.

        public class FieldNoteDTO : BaseDTO
        {
            private Guid _id;
            private string _title;
            private string _note;
    
            public Guid Id
            {
                get { return _id; }
                set
                {
                    _id = value;
                    OnPropertyChanged();
                }
            }
    
            public string Title
            {
                get { return _title; }
                set
                {
                    _title = value;
                    OnPropertyChanged();
                }
            }
    
            public string Note
            {
                get { return _note; }
                set
                {
                    _note = value;
                    OnPropertyChanged();
                }
            }
        }

The MvxSwipeListView and SearchView.

        GTas.Mobile.Phone.Droid.Views.MvxSwipeListView
                    android:id="@+id/List_FieldNotes_Edit"
                    android:layout_width="fill_parent"
                    android:layout_height="fill_parent"
                    local:swipeFrontView="@+id/front"
                    local:swipeBackView="@+id/back"
                    local:swipeCloseAllItemsWhenMoveList="true"
                    local:swipeMode="both"
                    local:swipeActionRight="reveal"
                    local:swipeActionLeft="reveal"
                    local:swipeOpenOnLongPress="false"
                    local:MvxItemTemplate="@layout/orderfieldnotelistrowedit"
                    local:MvxBind="DeleteCommand DeleteFieldNoteCommand; ItemsSource FieldNotes; ItemClick ShowFieldNoteDetailCommand" />
    
    <SearchView
            android:id="@+id/FieldNotesSearchView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

SearchView code to invoke when text is changed.

    _searchView.QueryTextChange += (object sender, SearchView.QueryTextChangeEventArgs e) => { 
    					OrderFieldNoteListViewModel.FilterText = e.NewText; 
    				};

I see the problem appears in the WrappingList class that I have in the project.

        public class WrappingList<T> : IList<WrappingList<T>.Wrapped>
    	{
    		public class Wrapped
    		{
    			public IMvxCommand DeleteCommand { get; set; }
    			public T TheItem { get; set; }
    		}
    
    		private readonly List<T> _realList;
    		private readonly Action<T> _realAction;
    
    		public WrappingList(List<T> realList, Action<T> realAction)
    		{
    			_realList = realList;
    			_realAction = realAction;
    		}
    
    		private Wrapped Wrap(T item)
    		{
    			return new Wrapped()
    			{
    				DeleteCommand = new MvxCommand(() => _realAction(item)),
    				TheItem = item
    			};
    		}
    
    		#region Implemented Methods
    
    		public int Count
    		{
    			get { return _realList.Count; }
    		}
    
    		public WrappingList<T>.Wrapped this[int index]
    		{
    			get
    			{
    				return Wrap(_realList[index]);
    			}
    			set
    			{
    				throw new NotImplementedException();
    			}
    		}
    
    		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    		{
    			return GetEnumerator();
    		}
    
    		public IEnumerator<WrappingList<T>.Wrapped> GetEnumerator()
    		{
    			return _realList.Select(Wrap).GetEnumerator();
    		}
    
    		#endregion
    
    		#region NotImplemented Methods
    
    		public int IndexOf(WrappingList<T>.Wrapped item)
    		{
    			throw new NotImplementedException();
    		}
    
    		public void Insert(int index, WrappingList<T>.Wrapped item)
    		{
    			throw new NotImplementedException();
    		}
    
    		public void RemoveAt(int index)
    		{
    			throw new NotImplementedException();
    		}
    
    		public void Add(WrappingList<T>.Wrapped item)
    		{
    			throw new NotImplementedException();
    		}
    
    		public void Clear()
    		{
    			throw new NotImplementedException();
    		}
    
    		public bool Contains(WrappingList<T>.Wrapped item)
    		{
    			throw new NotImplementedException();
    		}
    
    		public void CopyTo(WrappingList<T>.Wrapped[] array, int arrayIndex)
    		{
    			throw new NotImplementedException();
    		}
    
    		public bool IsReadOnly
    		{
    			get { throw new NotImplementedException(); }
    		}
    
    		public bool Remove(WrappingList<T>.Wrapped item)
    		{
    			throw new NotImplementedException();
    		}
    
    		#endregion
    	}

So what kind of constructor do I need to have in the WrappingList to make this work appropriately?

**Comment by Cheesebaron** [comment]
What version?

**Comment by xplatsolutions** [comment]
Updated the question, version 3.5.0

**Comment by xplatsolutions** [comment]
Changing FilterNotes method to this worked. I'm not so sure if it is an MvvmCross issue though, will check the WrappingList and let you know, but it seems that the ObservableCollection<T> type and databinding was not functioning correctly, although it is an IList.

**Comment by martijn00** [comment]
@xplatsolutions Did you check this?

**Comment by xplatsolutions** [comment]
@martijn00 I just left it as IList to continue working, it has to do with the WrappingList implementation which I don't own and not possible to change or refactor right now, we should close this, shouldn't be MvvmCros related bug.
