### ISSUE TITLE
File plugin: Getting "Cannot access the file... because it is being used by another process" while trying to READ it

### ISSUE THREAD

**Issue by JanZeman** [MvvmCross/MvvmCross#1050]
Hello,

in WPF subsystem (MvxWpfFileStore, TryReadBinaryFile) I am getting "Cannot access the file... because it is being used by another process" despite the fact that I am trying only to read the file. It is true in my example that there is another process involved but in the current process I only need to READ the file.

The solution is very simple - a oneliner. However to achieve it against MvvmCross Nuget I had to do a bit of ugly wiring in my project and would much better prefer if I can remove it again with the future MvvmCross Nuget package.

Not being expert in this area I want to discuss it first. What worked for me was the modification of the method TryReadFileCommon where I changed 

using (var fileStream = File.Open(path1))

into

using (var fileStream = File.Open(path1, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))

Inspiration links:
http://stackoverflow.com/questions/897796/how-do-i-open-an-already-opened-file-with-a-net-streamreader
http://stackoverflow.com/questions/12942717/read-log-file-being-used-by-another-process

I can try my own fork and pull request but want to discuss first possible disadvantages.

Best regards
Jan

**Comment by martijn00** [comment]
Yes it indeed seems that your fix makes sense. I would say that if you make a PR we will look at it and if no comments against it are giving we can bring it into the next release which is 3.5.2

**Comment by JanZeman** [comment]
Cool, thanks for such a quick reply. I'll do it. What date is a rough estimation for 3.5.2 release?

**Comment by martijn00** [comment]
Not sure yet. We put out some Alpha versions already, now we are testing if everything still works, makes some fixes, and after that a beta version would follow. If no issue's come up then there will be a new stable release.

**Comment by JanZeman** [comment]
OK, my PR is here: https://github.com/MvvmCross/MvvmCross/pull/1051. Please read my comment there - I could imagine bit larger changes but wanted to make it as simple as possible in this round...

**Comment by martijn00** [comment]
Thanks! PR is merged in.
