### ISSUE TITLE
Remove NuSpec dependency MvvmCross.HotTuna.CrossCore -> PortableSupport

### ISSUE THREAD

**Issue by PeterBurke** [MvvmCross/MvvmCross#1053]
The [NuSpec](https://github.com/MvvmCross/MvvmCross/blob/3.5/nuspec/MvvmCross.HotTuna.CrossCore.3.0.1.nuspec) of MvvmCross.HotTuna.CrossCore currently has a dependency on MvvMCross.PortableSupport.

**This is a deep legacy that is ripe for removal.**

In the MvvMCross.PortableSupport NuSpec nothing in fact gets downloaded or linked except in the PCL project.

That PCL however simply downloads a file named "-.-" that seems to have been put there to stop NuGet complaining. **However there is a new version of NuGet in VS 2015 that exceptions complaining that the downloaded NuGet package is empty.**

## PROOF ##

The [NuSpec](https://github.com/MvvmCross/MvvmCross/blob/3.5/nuspec/MvvmCross.PortableSupport.3.0.1.nuspec) for PortableSupport used to at least link to some real assemblies in projects other than the PCL. However those links have subsequently been commented out:

```
<!-- PCL -->
<file src="_._" target="lib\portable-win+net45+wp8+win8+wpa81\_._" />

<!-- droid -->
<!-- removed
<file src="..\bin\Release\Mvx\Droid\System.Net.dll" target="lib\MonoAndroid\System.Net.dll" />
<file src="..\bin\Release\Mvx\Droid\System.Windows.dll" target="lib\MonoAndroid\System.Windows.dll" />
<file src="..\bin\Release\Mvx\Droid\System.Xml.Serialization.dll" target="lib\MonoAndroid\System.Xml.Serialization.dll" />
-->

<!-- mac -->
<!--
<file src="..\bin\Release\Mvx\Mac\System.Windows.dll" target="lib\MonoMac\System.Windows.dll" />
-->
```

So in the dependency in HotTuna.CrossCore on this PortableSupport package is now completely redundant, but was not always so.

I note that prior to commenting out the Droid and Mac sections, NuSpec would have for those targets linked in some additional assemblies. I have looked into those assemblies and almost all of them contain redirects: a redirection to a standard .NET assembly, redirects are a way to allow anyone still referencing PortableSupport to be redirected to a standard .NET assembly.

PortableSupport today is mostly redirects. One assembly "System.Windows" presumably used in WPF also contains some code System.ComponentModel, System.Windows.Input (ICommand). But the above NuSpec even before sections were commented out made no reference to this target.

**Comment by martijn00** [comment]
It seems logical what you write. Go ahead and make a PR for this and we will review it and merge it in if no problems are found.

**Comment by slodge** [comment]
Nuke it!

**Comment by Cheesebaron** [comment]
I will unlist all versions of this. It will still be possible to install from nuget, but you wont be able to find it by searching for it.

**Comment by jbeckton** [comment]
I am trying to get started with MVVMCross but I am having a hard time figuring out which packages to load into my project. If there is reason to keep the older packages then kindly update their descriptions instructing us which ones are preferred.

**Comment by PeterBurke** [comment]
Hi J

Can you give me some background:
- What version of Visual Studio are you on, 2013 / 2015?
- Are you using Xamarin to cross-develop targeting: iOS, Android, Windows Phone, Windows Store
- Maybe you could be targeting the Mac, or legacy Windows WPF?

Please understand that MvvMCross has grown to support many different platforms and it is not so easy to simplify it. The one thing you need to understand though about MvvMCross and this applies to all NuGet packages is that NuGet packages can have dependencies on other packages.

So typically you start by installing just one package, and during the install it will also install the dependencies.

So if you are targeting Xamarin to cross-development you only need to install as described [here](https://www.nuget.org/packages/MvvmCross/) and you get the very latest MvvMCross and all its dependencies.

However if you look for MvvMCross in visual studio using Tools -> "NuGet Package Manager" -> "Manage Nuget Packages for Solution ..." and you search for "MvvMCross" yes you will have a very long list of packages to choose from.

This is because of the MvvMCross dependencies and also because MvvMcross has a big library of plugins that add value to MvvMCross. For example if in your App you need to send a text message to another mobile there is a plugin for that.

Yes it would be nice to improve "Manage Nuget Packages for Solution ..." but that project is owned by Microsoft.

**Comment by PeterBurke** [comment]
Thanks Martijn & Tomasz. I have created a pull request and previously Stuart gave the go ahead. One of you should do the pull as I do not have write access. Access the pull [here](https://github.com/MvvmCross/MvvmCross/pull/1054).
