### ISSUE TITLE
View namespace abbreviations not working in 3.5.2 alpha

### ISSUE THREAD

**Issue by gshackles** [MvvmCross/MvvmCross#1057]
View namespace abbreviations are not working properly in the latest 3.5.2 alpha. In our apps we have the following:

```
protected override IDictionary<string, string> ViewNamespaceAbbreviations
{
    get
    {
        var abbrevs = base.ViewNamespaceAbbreviations;

        abbrevs["controls"] = "AppCoreUI.Droid.Controls";

        return abbrevs;
    }
}
```

When we try to use that in our AXML, we get an error saying it can't find our views. Things work properly if we specify the full namespace in the AXML file.

**Comment by martijn00** [comment]
@kjeremy do you have any idea's on this?

**Comment by kjeremy** [comment]
Since nothing else is handling creating the view It should be inflated by the AndroidViewFactory here:
https://github.com/MvvmCross/MvvmCross/blob/55f0a42916d9c647aa0ac69380fc17ab9f220a19/Cirrious/Cirrious.MvvmCross.Binding.Droid/Views/MvxLayoutInflater.cs#L146

as that's the part that should be using the custom namespaces.

**Comment by Cheesebaron** [comment]
I also have this issue. Removing Mvx abbreviation from `Mvx.MvxListView` or `Mvx.MvxImageView` funnily works. As soon as adding that abbreviation it explodes.

**Comment by kjeremy** [comment]
I tracked this down last night.  It's failing in createviewinternal in the
private factory.  I need to add a call to the androidviewfactory
somewhere.  Maybe I can just replace createview with that but I'm not sure
yet.  I can't debug it by stepping through with this version of xamarin.

**Comment by Cheesebaron** [comment]
Seems to be fixed in #1064 could someone else test this as well?

**Comment by Dexyon** [comment]
@Cheesebaron  I wil try to do some extra testing later tonight.

**Comment by kjeremy** [comment]
I tested this with #1064 and it worked.
