### ISSUE TITLE
MvxImageLoader / DownloadCache doesn't make images appear correctly in cells (iOS)

### ISSUE THREAD

**Issue by PelleRavn** [MvvmCross/MvvmCross#1058]
Hi

First of all, I know there have already been other issues about the MvxImageLoader/DownloadCache recently, but I'm not quite sure if this problem is the same (and therefore resolved), but I'll post this anyway.

There seem to be a issue with the MvxImageLoader in Cells (CollectionViewCell and TableViewCell) on iOS. If there is many object in the list, and they all have a image URL to show, the image loader doesn't always return a show the view properly. In the app I'm developing, it happens if there is more than 4 images on the screen (collection view), if there's less, no problems - In the case, it means there is no problem on a 3,5" screen, but happens a lot on bigger screens, and bigger, the more this issue happens.

So, the real app I'm doing this in, show the issue like this:
https://www.dropbox.com/s/570jepv0wbylhwv/Screenshot%202015-07-12%2016.35.59.png?dl=0
The first 2-4 images doesn't always appear on screen, until the cell disappear from the screen, and appears again, then the images load fine.

I've setup a sample project to show this.
https://www.dropbox.com/s/wztbks9zj41n2pp/CollectionTest.zip?dl=0
To reproduce:
- Launch the app on either the simulator or a device.
- Let the app load the first images
- Press the 'Reload' button multiple times, and you will see "black images appears"
- Scroll down the list, and you will see it can happen more depending on how many pictures are shown.
(To see both CollectionView and TableView behaving like this, change the startup viewmodel (in FirstViewModel and SecondViewModel))

I know this way of showing it, is a little "unintended behaviour" and/or a corner case - But it shows the issue I'm having in my project, even without reloading the cells like crazy.

It's tested on the recent 3.5.1. I noticed that there were some changes related to issue #1041, and therefore I tried running this on the 4.0.0-alpha, but there are other issues (maybe something new, that I'm not aware of), that makes the cells never appear, so I can't confirm is this issue have been corrected already.

I got a crash on a device once, by tapping extremely fast, so this might be unrelated to anything, but I just wanna add the stack trace anyway, it may be possible to contain pointers to where this happens:
https://www.dropbox.com/s/dgqmmvcj9ja7lgn/CollectionTestCrash.txt?dl=0

This is kinda a showstopper for the app I'm doing, that the first visible images doesn't show up, and can't seem go get around it easily.

**Comment by Cheesebaron** [comment]
I think this is fixed in the latest alpha.

**Comment by PelleRavn** [comment]
Meaning that I have to wait for 4.0 to be completed to get this fix for a stable release?

**Comment by Cheesebaron** [comment]
You don't **have** to. It is entirely **your** decision isn't it?

You have access to the source, you have the means to build it and modify it and do whatever you want with the code. Just because someone on the Internet says that something is stable, it does not necessarily mean it is.

Also keep in mind the MS-PL license MvvmCross uses clearly states no warranties are made which should keep you even more on your toes.

**Comment by PelleRavn** [comment]
Think I may have sounded a little too negativ in my question, since I'm getting this reaction - Sorry about that.
My question may have been more a "Is 4.0 the next release, or is there a minor 3.5.x release in the pipeline in the near future, since it's added to a '3.5.2 milestone'?"

**Comment by Cheesebaron** [comment]
3.5.2 is 4.0.0 We have decided to bump the version number because of a multitude of new and breaking changes.
