### ISSUE TITLE
Fatal signal 11 (SIGSEGV) during startup

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#1067]
I am rarely observing "random" crashes during Mvvm Cross initialization while debugging after updating to Mvvm Cross 3.5.1.  This problem is happening on the AT&T SAMSUNG-SGH-I547 device running Android version 4.1.2.  I've been running the program on this device for several months but the problem only showed up a few days after updating to Mvvm Cross 3.5.1 via NuGet.

Here is the stack trace:
```
07-15 12:09:22.056 E/        (30071): <s3dReadConfigFile:75>: Can't open file for reading
07-15 12:09:22.056 I/mvx     (30071):   0.67 Ensuring Plugin is loaded for Cirrious.MvvmCross.Plugins.DownloadCache.PluginLoader
[0:] 
mvx:Diagnostic:  0.67 Ensuring Plugin is loaded for Cirrious.MvvmCross.Plugins.DownloadCache.PluginLoader
[0:] mvx:Diagnostic:  0.67 Ensuring Plugin is loaded for Cirrious.MvvmCross.Plugins.DownloadCache.PluginLoader
**07-15 12:09:22.086 I/mono-stdout(30071): mvx:Diagnostic:  0.67 Ensuring Plugin is loaded for Cirrious.MvvmCross.Plugins.DownloadCache.PluginLoader
[0:] 
07-15 12:09:22.096 I/mvx     (30071):   0.70 Loading plugin assembly: Cirrious.MvvmCross.Plugins.DownloadCache.Droid.dll
07-15 12:09:22.096 E/mono-rt (30071): Stacktrace:
07-15 12:09:22.096 E/mono-rt (30071): 
mvx:Diagnostic:  0.70 Loading plugin assembly: Cirrious.MvvmCross.Plugins.DownloadCache.Droid.dll
07-15 12:09:22.096 E/mono-rt (30071): 
07-15 12:09:22.096 E/mono-rt (30071): Attempting native Android stacktrace:
07-15 12:09:22.096 E/mono-rt (30071): 
07-15 12:09:22.096 I/mono-stdout(30071): mvx:Diagnostic:  0.70 Loading plugin assembly: Cirrious.MvvmCross.Plugins.DownloadCache.Droid.dll
07-15 12:09:22.106 E/mono-rt (30071):   at ???+262148 [0x40004]
07-15 12:09:22.106 E/mono-rt (30071):   at sem_post+82 [0x401103e3]
07-15 12:09:22.106 E/mono-rt (30071): 
07-15 12:09:22.106 E/mono-rt (30071): =================================================================
07-15 12:09:22.106 E/mono-rt (30071): Got a SIGSEGV while executing native code. This usually indicates
07-15 12:09:22.106 E/mono-rt (30071): a fatal error in the mono runtime or one of the native libraries 
07-15 12:09:22.106 E/mono-rt (30071): used by your application.
07-15 12:09:22.106 E/mono-rt (30071): =================================================================
07-15 12:09:22.106 E/mono-rt (30071): 
07-15 12:09:22.106 F/libc    (30071): Fatal signal 11 (SIGSEGV) at 0x00040004 (code=1), thread 30071 (rcules.dispatch)**
```

**Comment by Cheesebaron** [comment]
What version of Xamarin.Android are you on?

**Comment by tbalcom** [comment]
The Xamarin.Android version I am using is 5.1.4.16.  I am using Xamarin version 3.11.666.0.

**Comment by Cheesebaron** [comment]
Strange. I cannot reproduce this on any of my devices. Maybe you are mixing old assemblies with new and it blows up? There were major changes in Xamarin.Android 5 and I am pretty sure MvvmCross was built against a stable version of Xamarin.Android 4.x which might be what causes these problems. Not sure. The stack trace gives nothing to chase.

**Comment by tbalcom** [comment]
The project did start out life using the Ninja Coder Visual Studio Extension while MvvmCross 3.5 was the current version in NuGet, and was updated to 3.5.1 via NuGet.  Everything is up to date according to the Update-Package NuGet console command.  Do you know how I could identify if I'm mixing old and new assemblies?  When I go to the references in Visual Studio it always lists the version number as 1.0.0.0.  

In the PCL Core project I have a reference to Cirrious.CrossCore with Specific Version=False while all other MvvmCross related assembly references have Specific Version=True.  Is that something that should be investigated?

**Comment by Cheesebaron** [comment]
Open up the csproj files and verify the paths to the DLL files.

**Comment by pkl728** [comment]
I recently ran into a problem like that… I would recommend going and getting rid of all of your specific version tags, clean the solution, close the solution and then reopen the solution.

 

You’ll then want to investigate your project files to see if there are any oddities (like references to both MvvmCross 3.5.0 AND 3.5.1 and those kinds of things.

**Comment by tbalcom** [comment]
Thanks for all of the help everyone.  I've made the recommended changes. I'll keep an eye on this problem and let you know if it happens again.  By the very nature of the problem it may take a few days before I see the crash again if it still happens.
