### ISSUE TITLE
Bring back FullFragging

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#1070]
Please bring back `FullFragging`.  This is a huge breaking change from 3.5.x and since fragments are natively supported in Android we should continue to support them too (most other libraries support both).

Using the support library as our only option for fragments means:
  1. We get hit by the startActivityForResult bug.
  2.  On API 11+ we lose `Animator` support (have to use `Animation`).
  3.  Any library we use that involves third-party fragments have to provide support versions.
  4.  I'm lazy and don't want to rewrite my app to use `Support` everywhere.

**Comment by nextmunich** [comment]
+1 on this one

**Comment by SeeD-Seifer** [comment]
+1. We are using FullFragging. Would be great to have it in 4.x

**Comment by martijn00** [comment]
I've made a PR to address this: https://github.com/MvvmCross/MvvmCross/pull/1071
