### ISSUE TITLE
Fix SQLite nuspecs

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1072]
I have no idea how the SQLite plugin works. There are two nuspecs. One that has a package uploaded to NuGet, which clealy says **(OLD VERSION)** and tells the user to use `Cirrious.MvvmCross.Community.Plugins.Sqlite` instead. Problem is that that package does not exist...

The other nuspec does not work because a `tools` folder is missing along with nuget refusing to create the package because of some invalid characters in the `<references>` section in the metadata.

It would be really nice if someone with knowledge about these packages and how the whole thing is pieced together would help fix these nuspecs... Until then I am not putting up new versions of the SQLite plugin.

**Comment by jamie94bc** [comment]
I'm not familiar with nuspecs but the SQLite plugin now lives in this [repository](https://github.com/MvvmCross/MvvmCross-SQLite) and [NuGet package](https://www.nuget.org/packages/MvvmCross.Community.Plugin.Sqlite/).

**Comment by Cheesebaron** [comment]
Ooook. I'll update that repo then :+1: 

Not sure how I missed it :cold_sweat:

**Comment by martijn00** [comment]
Updated nuspec in https://github.com/MvvmCross/MvvmCross-SQLite/pull/48

**Comment by martijn00** [comment]
Fix with using https://github.com/MvvmCross/MvvmCross-Plugins/tree/master/SQLite-PCL
