### ISSUE TITLE
Could not load signature of Cirrious.CrossCore.Droid.Views.MvxEventSourceActivity

### ISSUE THREAD

**Issue by descorp** [MvvmCross/MvvmCross#1076]
After updatind Xamarin up to 3.11.666 I get this issue on both Visual Studio and Xamarin Studio.

Build goes smooth, but during app initiation comes this error:

Could not load signature of Cirrious.CrossCore.Droid.Views.MvxEventSourceActivity:add_CreateWillBeCalled due to: Could not load file or assembly or one of its dependencies.

Cause :
```
Cannot convert instance argument type 
'System.EventHandler<Cirrious.CrossCore.Core.MvxValueEventArgs<Android.OS.Bundle>> [mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]' 
to 'System.EventHandler<Cirrious.CrossCore.Core.MvxValueEventArgs<Android.OS.Bundle>> [System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]'
```

In a same way I have about 63 error of a conflicts between System.Object from a different assemblies versions ..

**Comment by descorp** [comment]
Xamarin downgrade solved problem

**Comment by ilfat** [comment]
Hi! Wich version of Xamarin should I downgrade?

**Comment by Cheesebaron** [comment]
3.11.590 works fine here haven't tried the newer 3.11.666 yet. Might do an upgrade today to see what happens.

**Comment by ilfat** [comment]
3.11.590 works fine

**Comment by descorp** [comment]
Hi @ilfat 
Yes, Xamarin.Android version is a show-stopper. Just downgrade to previous one will serve.

@Cheesebaron 
I tried to use pre-release nugets but for some reason I couldn't update all of them using neather nuget console in VS 13, nor Xamarin Studion - there were lots of errors during update and some of references sill remains 3.5.1. (Cirrious.MvvmCross is I'm not mistaken). It gave no result after all.

**Comment by Cheesebaron** [comment]
Just retry the update of the packages
