### ISSUE TITLE
Windows Phone 8.1 ViewModel Property is Null

### ISSUE THREAD

**Issue by jwiemann** [MvvmCross/MvvmCross#1078]
After calling the View Constructor with its InitializeComponent() function the ViewModel property is still null.
Sometimes it is not null, but I can not figure out a pattern.

- The View is derived from MvxWindowsPage
- The Model is derived from MvxViewModel
- The ViewModel is called by ShowViewModel<MapViewModel>() (Even the initial View has this bug)

No solution yet:
http://stackoverflow.com/questions/27950225/windows-phone-8-1-mvvmcross-viewmodel-is-null

Thanks for your support!

**Comment by Cheesebaron** [comment]
The `ViewModel` gets populated in `OnNavigatedTo()` remember to call its base if you are overriding the method.

**Comment by jwiemann** [comment]
I am not overriding this method:

namespace s2.befit.Mobile.Windows.Views
{
    using System;

    using Cirrious.MvvmCross.WindowsCommon.Views;

    using s2.befit.Logic.Mobile.ViewModels;

    public sealed partial class MapView : MvxWindowsPage
    {

        public MapView()
        {
            InitializeComponent();

            if (ViewModel == null)
            {
                throw new NullReferenceException("Viewmodel is somehow NULL!");
            }
        }


        /// <summary>
        /// Viewmodel of the View.
        /// </summary>
        public new MapViewModel ViewModel
        {
            get
            {
                return (MapViewModel)base.ViewModel;
            }
            set
            {
                base.ViewModel = value;
            }
        }

    }
}

this is all I do..

**Comment by Cheesebaron** [comment]
Yes... The `ViewModel` is `null` in the constructor. As I said it is populated in `OnNavigatedTo`
