### ISSUE TITLE
Nuget 3.5.2-alpha2 DLL mismatch problem

### ISSUE THREAD

**Issue by borrrden** [MvvmCross/MvvmCross#1080]
When I try to build with 3.5.1 everything works alright, but when I upgrade to 3.5.2-alpha2 (Necessitated by the forms presenter classes) Android stops building correctly and gives several of the following messages:

>Error XA4204: Unable to resolve interface type 'Cirrious.MvvmCross.Binding.Droid.Views.IMvxLayoutInflater'. Are you missing an assembly reference? (XA4204)

**Comment by borrrden** [comment]
I guess the problem is a missing package for MvvmCrossLibraries 3.5.2-alpha2.  When I upgraded everything to 4.0.0-alpha9 the problem went away.

**Comment by martijn00** [comment]
Yes those fixes are in the 4.0.0 branch.
