### ISSUE TITLE
Manually mapping views with viewmodels

### ISSUE THREAD

**Issue by dazinator** [MvvmCross/MvvmCross#1083]
Hello,

I am using the latest MVVMCross published NuGet packages (v3.5.1)

I have an issue where when I call `ShowViewModel<HomeViewModel>();` from my `AppStart` object, it doesn't resolve / navigate to the HomeView.

In order to rectify this, I thought I would try and manually hardcode this mapping. I read the following [artcile](http://slodge.blogspot.co.uk/2013/01/overriding-view-lookup-convention-used.html) which talks about overriding  `GetViewModelViewLookup()` from the `Setup` class. 

My setup class looks like this:

```
public class Setup
         : MvxAndroidSetup
    {

 public Setup(Context applicationContext)
            : base(applicationContext)
        {
        }

        protected override IMvxApplication CreateApp()
        {
            return new NoSplashScreenApp();
        }

}
```

There doesn't appear to be any GetViewModelViewLookup() method for me to override.

Can someone point me in the right direction with how to manually take control of view / view model mapping?

**Comment by dbeattie71** [comment]
I think you can manually map views with viewmodels in InitializeViewLookup(), overridden in setup.cs.

**Comment by dazinator** [comment]
Ok - will take a look. Cheers

**Comment by cyrilcathala** [comment]
A better way is to use the `[MvxViewFor]` attribute. Check that : http://slodge.blogspot.fr/2013/03/conventional-views-from-badge-winning.html
