### ISSUE TITLE
MvxWindowsCommonBlockingFileStore.GetFilesIn(path) output does not include full path

### ISSUE THREAD

**Issue by tekkies** [MvvmCross/MvvmCross#1086]
MvxWpfFileStore.GetFilesIn(path) does seem to include full paths.
MvxWindowsCommonBlockingFileStore.GetFilesIn(path) seems to gives a list of file names only.

I've not checked any other platforms.

v3.5.1

**Comment by Cheesebaron** [comment]
As discussed on JabbR, we should probably make these methods behave the same.

**Comment by tekkies** [comment]
Created tests in a branch to reproduce/demonstrate the problem https://github.com/tekkies/MvvmCross/tree/plugin-platform-tests

**Comment by tekkies** [comment]
I've suggested a fix in branch https://github.com/tekkies/MvvmCross/tree/issue-1086
I've also merged the fix into the test branch https://github.com/tekkies/MvvmCross/tree/plugin-platform-tests

Should I issue a pull request at this point?

**Comment by martijn00** [comment]
Yes a pull request would be good!
