### ISSUE TITLE
MvxWindowsStoreFileStore.EnsureFolderExists() fails for absolute path

### ISSUE THREAD

**Issue by tekkies** [MvvmCross/MvvmCross#1104]
It seems that if you pass in an absolute path to EnsureFolderExists() on the WindowsStore platform, e.g. 

    C:\Users\ipfreely\AppData\Local\Packages\d3845326-8ab2-4492-bd70-c883bbb68059_w6z2bdsx51h7r\LocalState\b43840fd-a1a9-4348-82e2-6c6214cd83d7

then `System.IO.FileNotFoundException` is thrown.

This can be demonstrated if you run the test `TestEnsureFolderExists_AbsolutePath()` from `MvvmCross.Plugins.Test.WindowsStore.csproj` in 
https://github.com/tekkies/MvvmCross/tree/plugin-platform-tests

For comparison it works fine if run in the context of `MvvmCross.Plugins.Test.Wpf.csproj`

**Comment by martijn00** [comment]
Can you make a PR to fix this?

**Comment by tekkies** [comment]
See what I can do

**Comment by tekkies** [comment]
I've created the PR (from my older branch) - if I can get the latest 4.0 to build (having some fun & games), I'll merge there and submit a new PR.

**Comment by martijn00** [comment]
You can also update this PR.

**Comment by tekkies** [comment]
I don't seem to be able to point this pull request at the branch with the new fix (https://github.com/tekkies/MvvmCross/tree/issue-1104b) - I could force push the changes over this branch or create new PR.
