### ISSUE TITLE
Could you add XML comments to classes and methods within Cirrious.MvvmCross?

### ISSUE THREAD

**Issue by xperiandri** [MvvmCross/MvvmCross#1108]
Could you add XML comments to classes and methods within Cirrious.MvvmCross?
So beginners can quickly get used to how MvvmCross works.

**Comment by martijn00** [comment]
There is quite some code in MvvmCross and to make comments on all of it might take a lot of time. Feel free to open a pull request to fix this! Other then that you can check the examples available and all the tutorials.

**Comment by Dexyon** [comment]
@xperiandri Is there anything you need to know then? Maybe it is easier to ask that question instead of a generic 'please add stuff'.

**Comment by xperiandri** [comment]
I don't think so.
So as a beginner to MvvmCross I open sources to understand how it works and what I see is no single line of XML comments anywhere!

Then I search in the internet how to do navigation and found https://github.com/MvvmCross/MvvmCross/wiki/ViewModel--to-ViewModel-navigation
Good.
So I write ShowViewModel<RoomsViewModel>() and see 3 overloads where no one parameter is described.

**Comment by xperiandri** [comment]
And now I understand that I will stuck at every next step because nothing explained :(

**Comment by slodge** [comment]
Nope - you'll fly because you are intelligent and because comments like `viewModelType - the type of view model to show` wouldn't have helped you in any meaningful way.

IMO - comments in code can deliver results and are really worth it for big stable commercial libraries, but they require a really significant effort to write and maintain, they discourage and hinder rapid, iterative development, they get broken by refactoring tools and... they very quickly become lies.  For open source users also have the great benefits of community assistance and the source code!

For this project, I always felt it was much better to instead invest the effort to make the method and parameter names good, to add some user docs and tutorials when I could.

Now back to lurking for me :)

**Comment by xperiandri** [comment]
OK.
Where would you suggest to find answers to such questions:
* what are presentationBundle and what requestedBy in ShowViewModel method?
* how to handle back stack navigation? Is it possible to check if I can go back in ViewModel?
* how to read parameter in navigated to ViewModel that was passed on navigation. And in general a lifecycle of ViewModel.
* how to save and read state and when does it happen?
* how to implement non linear navigation when root frame is placed into some chrome and you can open a few views of the same type and switch between them.

Do you have any schemes that explain how does it work?
I understand Prism at it is a small abstraction over Windows Runtime.
And I understand that handling completely different platforms required much bigger abstraction. However MvvmCross is huge!

**Comment by martijn00** [comment]
You need to make some effort yourself to get into MvvmCross. As you say it is a huge framework, but there are lots of examples and tutorials available. Also we answer questions on StackOverflow and have a [Jabbr channel](https://jabbr.net/#/rooms/mvvmcross).

If you want to know for example something about lifecycles and backstack check the Android example which handles that here: https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/master/Samples

**Comment by slodge** [comment]
Was https://github.com/MvvmCross/MvvmCross/wiki/ViewModel--to-ViewModel-navigation really that hard to read?

**Comment by slodge** [comment]
Oops - hit close by accident.... sorry!

**Comment by slodge** [comment]
When you get somewhere I would also love to see you come back and add Xml comments would help with those questions - please do prove me wrong and teach me to be better - it's another one of the fab things about open source :)

**Comment by xperiandri** [comment]
I am really sorry for forcing you commenting a lot here, because I haven't read navigation tutorial to the end. :)
Will read carefully and back.

**Comment by Dexyon** [comment]
As mentioned by @martijn00  and @slodge. If you have any questions left, please ask (rather on SO or the jabbr channel). But try to look up some tutorials and blogs. There are many many many of those out there who blog about MvvmCross. 

And as mentioned by @slodge try understanding the names etc, most of them are meaningful and if you want to know a really specific thing. It's open source. Try reading the code and you can always come back and ask us :)

**Comment by xperiandri** [comment]
Is design time data used only on Windows platform?
Can I check for design time in a MvxViewModel?
