### ISSUE TITLE
Object stored in PageStackEntry.Parameter has changed from MvxViewModelRequest to String

### ISSUE THREAD

**Issue by Petezah** [MvvmCross/MvvmCross#1111]
I'm not sure if this is a breaking change or a bug, but I noticed this in our view presenter code that expects the object coming back from the Windows.UI.Xaml.Navigation.PageStackEntry.Parameter to be a MvxViewModelRequest.  It is a System.String in 3.5.1.  I rolled us back to 3.5.0, and it is again a MvxViewModelRequest, as we expect.

If this is an intentional breaking change, feel free to close "won't fix".  It seemed like an odd change to me; so I thought it prudent to flag it here.

**Comment by martijn00** [comment]
Could you try 4.0.0 to see how that one behaves?

**Comment by martijn00** [comment]
@Petezah Any news on this?

**Comment by Petezah** [comment]
Sorry for the delay; I've been swamped this month.  Yes, I just took a look at the behavior of 4.0.0 beta 3, and Parameters is a String with that version also.

**Comment by martijn00** [comment]
Could you find out where in the code this has changed?

**Comment by Petezah** [comment]
I finally was able to get back to this.  It seems like this is fixed now.  I'm going to do more self-test today, but I'm using 4.1.4 now, and it seems to do what we expect again.

**Comment by Petezah** [comment]
I was wrong.  This happens with 4.2.2.  I think we were somehow still using the old version of MvvmCross possibly, and that was why it wasn't reproing.  What I did find was this: even when I override my setup class's CreateNavigationSerializer to return a MvxStringDictionaryNavigationSerializer (which contains a MvxViewModelRequestCustomTextSerializer that does what we want), apparently that serializer is never called, and I still get the serialized string back in my Parameters object.  I might enlist and mess around with the MvvmCross code later, but for now, I've put a workaround in my code in the one place we use the Parameters object.
