### ISSUE TITLE
VS2015 NuGet Installation Failure for Xamarin.Android project: MvvmCross.PortableSupport 3.5.1.

### ISSUE THREAD

**Issue by C0D3Name** [MvvmCross/MvvmCross#1113]
I received the following error when attempting to reference MvvmCross.HotTuna.MvvmCrossLibraries (Latest Stable Build) using NuGet PM in a new VS2015 Xamarin.Android project:

"Could not install package 'MvvmCross.PortableSupport 3.5.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.1', but the package does not contain any assembly references or content files that are compatible with that framework."

The solution's PCL was able to install the package.
Work-around: Open solution in Xamarin Studio and add the NuGet reference there.

I found a related issue on StackExchange at https://stackoverflow.com/questions/30148092/adding-mvvmcross-nuget-package-to-xamarin-ios-fails-on-vs2015-rc

**Comment by Cheesebaron** [comment]
Complain to MS about their new NuGet version.

**Comment by martijn00** [comment]
Workaround available here: http://forums.xamarin.com/discussion/comment/147377/#Comment_147377
