### ISSUE TITLE
Android EditText binding failure

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#1114]
I have found a certain workflow that results in the Android EditText binding only working if the EditText doesn't have an android:id specified in the XML.  When this happens the ViewModel property holds the correct value but the EditText on the screen is empty.  Could you please take a look?  The question has been on stackoverflow for several days: http://stackoverflow.com/q/32122966/186046.

**Comment by tbalcom** [comment]
This problem can be observed when the "Do not keep activities" developer setting is enabled.  If I turn that developer setting off then it works as expected with or without an android:id.  Starting the ZXing.Net.Mobile scanner starts an activity. Does this sound like an MvvmCross or ZXing issue?

**Comment by martijn00** [comment]
Since this works in our app and loads of the samples in MvvmCross-Tutorials i guess this might be a ZXing issue. Let us know if you find more in the future.

**Comment by m-mccool** [comment]
I am finding the same issue. It only worked when the EditText is not assigned an android id

**Comment by Cheesebaron** [comment]
Make a repro sample and open a new issue. Don't vamp year old issues.
