### ISSUE TITLE
Unnecessary permissions exist in Android FullFragging AssemblyInfo.cs

### ISSUE THREAD

**Issue by ppanda15** [MvvmCross/MvvmCross#1115]
According to Xamarin issue http://forums.xamarin.com/discussion/16197/stuck-manifest-permissions. The old version Xamarin AssemblyInfo.cs template contains these two lines

[assembly: UsesPermission(Android.Manifest.Permission.Internet)]
[assembly: UsesPermission(Android.Manifest.Permission.WriteExternalStorage)]

In this case, these two lines exist in Cirrious.MvvmCross.Droid.FullFragging/Properties/AssemblyInfo.cs which should be removed. Otherwise, all Android apps that use fullfragging will have Write_External_Permission. This affect a lots on Android 6 which allowed user to disable each permission in each app. Users might confuse why their application needs write external storage permission.

**Comment by Cheesebaron** [comment]
Make a pull request.

**Comment by ppanda15** [comment]
Thank you! :)
