### ISSUE TITLE
Can resources now be embedded in class libraries?

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#112]
This has been discussed before - http://mono-for-android.1047100.n5.nabble.com/Resources-in-Class-Library-project-td5658638.html

And it seems like this might be becoming real - https://github.com/atsushieno/MonoDroid.Dialog/commit/2c7c5daf83e33b3a19d60400437cc5cd4655cee7

If it is, then:

- move the MvxBinding xml files into the class library :)
- move the CrossUI (Dialog) xml files into the class library :)

**Comment by Cheesebaron** [comment]
The MvxBinding Attributes already have been included in the binding library. CrossUI also include its own sources. Closing.
