### ISSUE TITLE
MvxListView binding doesn't work

### ISSUE THREAD

**Issue by NPadrutt** [MvvmCross/MvvmCross#1120]
Hi

I have this layout:

    <cirrious.mvvmcross.binding.droid.views.MvxListView
          xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:local="http://schemas.android.com/apk/res-auto"
          android:id="@+id/accountList"
          android:layout_width="fill_parent"
          android:layout_height="fill_parent"
          android:orientation="vertical"
          local:MvxItemTemplate="@layout/accountlistitem"
          local:MvxBind="ItemsSource AllAccounts" />

The layout is loaded in the fragment with this code:

    public new AccountListViewModel ViewModel
        {
            get { return (AccountListViewModel)base.ViewModel; }
            set { base.ViewModel = value; }
        }

        public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
        {
            var ignore = base.OnCreateView(inflater, container, savedInstanceState);
            var view = this.BindingInflate(Resource.Layout.AccountListLayout, null);

            //TODO: Move this to binding
            var list = view.FindViewById<MvxListView>(Resource.Id.accountList);
            list.ItemsSource = ViewModel.AllAccounts;

            return view;
        }

And in my ViewModel:

        public ObservableCollection<Account> AllAccounts
        {
            get { return accountRepository.Data; }
            set { accountRepository.Data = value; }
        }

This won't work and won't show any data. But when I add the following lines to the fragment my data is displayed properly:

            var list = view.FindViewById<MvxListView>(Resource.Id.accountList);
            list.ItemsSource = ViewModel.AllAccounts;

In another example this worked without any problems. Is here a bug or do I miss something?

Thanks

**Comment by Cheesebaron** [comment]
I don't see a RaiseNotifyPropertyChanged on `AllAccounts` where do you notify that the collection has been set?

**Comment by NPadrutt** [comment]
I implement it via fody. but even when I call RaisePropertyChanged(); explicit it doesn't work. alright. The reason I placed it here is that the code is form an existing and working app of mine who is on the latest stable version. And since no binding at all works at the moment, I thought this might be an issue.

**Comment by martijn00** [comment]
You might want to take a look at this Sample: https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/master/Samples

The bindings work there, so i think there is some difference in your code then. I you figure out where, we could look into why it worked before.

**Comment by Cheesebaron** [comment]
[**@NPadrutt**](https://github.com/NPadrutt) commented on [Aug 28, 2015, 11:22 AM GMT+2](https://github.com/MvvmCross/MvvmCross/issues/1120#issuecomment-135708847 "2015-08-28T09:22:58Z - Replied by Github Comment Enhancer"):
> I implement it via fody. but even when I call RaisePropertyChanged(); explicit it doesn't work. alright. The reason I placed it here is that the code is form an existing and working app of mine who is on the latest stable version. And since no binding at all works at the moment, I thought this might be an issue.

Well problem is that you don't provide a reproducible sample, so I would not consider it as an issue.

**Comment by NPadrutt** [comment]
@Cheesebaron you've right. Sorry for that. I asked the question on StackOverflow.
The repo is ipen source ([link](https://github.com/NPadrutt/MoneyManager). But you'll be right that it will be something with my code. So I will try to find the issue with the sampls @martijn00  (thanks for them =) ) and StackOverflow.
