### ISSUE TITLE
Nuget Install Error VS2015, Windows10, PCL, Uwp, Droid and iOS Project

### ISSUE THREAD

**Issue by wenyonk** [MvvmCross/MvvmCross#1130]
![2015-09-10_21-07-46](https://cloud.githubusercontent.com/assets/3248973/9804864/292564b8-5800-11e5-83ac-38c8f9ce95ab.png)
Nuget Package Manager 3.0.0

Error		Could not find a part of the path 'C:\Users\Ken\.nuget\packages\MvvmCross.HotTuna.StarterPack\4.0.0-beta3\content\portable-win%2Bnet45%2Bwp8%2Bwin8%2Bwpa81\ViewModels\FirstViewModel.cs.pp'.	

Same Error for 4.0.0-beta2

Able to install Newtonsoft.Json

**Comment by martijn00** [comment]
Nuget 3.0 doesn't allow package content anymore. You can install all the other packages.
