### ISSUE TITLE
Problem to link assemblies of MvxFileDownloadCache with iOS 9 SDK

### ISSUE THREAD

**Issue by cristianomad** [MvvmCross/MvvmCross#1135]
When I try do compile my app with "Link All Assemblies", this error appears.

> /Users/MyAppFolder/MyApp.iOS/MTOUCH: Error MT2001: Could not link assemblies. Reason: Can't not find the nested type '<<.ctor>b__2c>d__34' in 'Cirrious.MvvmCross.Plugins.DownloadCache.MvxFileDownloadCache/Timer/<>c__DisplayClass2f (MT2001) (MyApp.iOS)

Using: 
OSX Yosemite 10.10.5
iOS 9 SDK
Xamarin Studio 5.9.7
Xamarin.iOS 9.0.1.18
XCode 7

Threads opened about this problem:
https://forums.xamarin.com/discussion/50777/build-error-mtouch-mt2001-on-os-x-el-capitan-gm-with-xamarin-alpha-release

https://bugzilla.xamarin.com/show_bug.cgi?id=33124#c5

**Comment by martijn00** [comment]
This will be fixed in an upcoming Xamarin release.

**Comment by paddylov** [comment]
hi @martijn00 ,  Do you have any idea of the release date?

**Comment by martijn00** [comment]
No this is managed by Xamarin themselfs.
