### ISSUE TITLE
Add more async support

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#1136]
I think some parts could support async await to get a better performance. As this could be breaking i would suggest to do this in the 4.0 release.

Some thoughts from the past: https://github.com/MvvmCross/MvvmCross/issues/488

**Comment by jamie94bc** [comment]
I think view models could benefit from exposing `StartAsync` (returning `Task`, not `async void`) but I don't think we'd want to wait for it to complete in [IMvxViewModelLocator](https://github.com/MvvmCross/MvvmCross/blob/4.0/Cirrious/Cirrious.MvvmCross/ViewModels/MvxDefaultViewModelLocator.cs)?

We could keep `Init` synchronous and make `Start` async if we were enforcing a pattern such as:

```c#
private int? _id;

public void Init(NavObject navObject) {
    _id = navObject.Id;
}

public async Task StartAsync() {
    if (_id.HasValue) {
        Item = await Repoistory.GetAsync(_id.Value);
    }
}
```

Or we could make both async, ensuring that `StartAsync` isn't called until `InitAsync` completes.

In terms of perceived performance, we'd probably want to call `StartAsync` after the view model has been assigned to the view?

Were there any other specific areas you had in mind @martijn00?

**Comment by martijn00** [comment]
I was thinking like @Cheesebaron said in Jabbr:

I wonder if we take https://github.com/MvvmCross/MvvmCross/blob/4.0/Cirrious/Cirrious.MvvmCross/Platform/MvxSetup.cs and make everything async in there, if that speeds up the startup process.

I would go for full async with your init proposal.

**Comment by willsb** [comment]
@martijn00 What is the way to benchmark the speed of startup? Will a simple stopwatch suffice? I could give it a shot on this one :)

**Comment by martijn00** [comment]
@willsb  I currently don't have anything to benchmark this with. Maybe you could use something like the Xamarin Profiler?

**Comment by roubachof** [comment]
after digging a while the async/await initialization, it seems to me that we shouldn't give the async responsability to the framework . When doing so (async Task Start() on MvxViewModel), it drips on methods that shouldn't handle async

like this one:

MvxCachingFragmentActivity
=> protected override void OnPostCreate(Bundle savedInstanceState(edited)

I guess it's better to let the dev handle the async loading ​*apart*​ from the mvvmcross framework
saying this, we should make a post in the docs to help the dev loads its data asynchronously.

We could let Stephen Cleary speaks for ourselves:

Async Data Loading
https://msdn.microsoft.com/en-us/magazine/dn605875.aspx

Async Commands
https://msdn.microsoft.com/en-us/magazine/dn630647.aspx

Async OOP in constructors
http://blog.stephencleary.com/2013/01/async-oop-2-constructors.html

**Comment by nmilcoff** [comment]
#1370 is part of this

**Comment by OlexaLe** [comment]
Hey guys, I'd love to help with this task. What is the current status? Does anyone work on this?

**Comment by martijn00** [comment]
The current work is done in https://github.com/MvvmCross/MvvmCross/tree/speedystartup

What i think is best for now is to introduce this as much as possible in small changes so we can check and test this easily. It might be good to just look at that branch but start off clean and try to add some more async along the way.

**Comment by Cheesebaron** [comment]
So there are a couple of different aspects to this.

- [ ] Make startup parallel using Tasks
- [ ] Improving MvxAsyncCommand to allow cancellation etc
- [ ] Ensuring the new InitializeAsync method in ViewModels is called correctly, perhaps adding Cancellation when Close is called before InitializeAsync finishes

**Comment by nickrandolph** [comment]
@martijn00 @Cheesebaron there are a bunch of PRs in the 6, 6.1 and 6.2 timeframes that address this issue. Are we ok to close this issue as it's being addressed elsewhere?

**Comment by nickrandolph** [comment]
@Cheesebaron @nmilcoff @martijn00 thoughts on whether we can go ahead and close this issue since we now have async throughout the navigation flow?
