### ISSUE TITLE
Update "ViewModel to ViewModel Navigation" article alternatives to pages

### ISSUE THREAD

**Issue by vvolkgang** [MvvmCross/MvvmCross#1140]
The ["What do you mean by pages"](https://github.com/MvvmCross/MvvmCross/wiki/ViewModel--to-ViewModel-navigation/90d7c29ffc6927f733fa4aa6050fe2ec00fe41bb#what-do-we-mean-by-page) part and the last topic refer to a blogpost made by @slodge in 2013. Since then a lot have changed, in MvvmCross core and additional support. 

As someone that recently went through the pain of filtering what's still relevant and what's not, I think it would benefit all if this info was updated. 

On this note, I just noticed this while searching for information about MvxBundle + ShowViewModel PresentationBundle, in order to know the proper way to inform my `MvxCachingFragmentActivity` presenter that I need some backstack management, which would go well along with this article or a different one focusing on more advanced scenarios and use cases.

Some useful and recent links about Android navigation drawer implementation:
- [Xam.NavDrawer](https://github.com/jamesmontemagno/Xam.NavDrawer/) by @jamesmontemagno 
- [MvvmCross Android support](https://github.com/MvvmCross/MvvmCross-AndroidSupport) by @martijn00

**Comment by martijn00** [comment]
This is a more general documentation problem we are working on for 5.0
