### ISSUE TITLE
Plugins on UWP app tries to load the *.WindowsUWP (but almost none exist)

### ISSUE THREAD

**Issue by azchohfi** [MvvmCross/MvvmCross#1142]
When, for example, I try to use the Location plugin in a UWP app (using latest alpha build, beta3) it tries to load MvvmCross.Plugins.Location.WindowsUWP but there is no such class.
For most (if not all) cases, the win81 version is the right one to use for UWP.

Should there be UWP specific versions for all plugins or should the framework be smart to load the win81 version?

I think this is what's needed to be changed to fix this:
https://github.com/MvvmCross/MvvmCross/blob/4.0/CrossCore/Cirrious.CrossCore/Plugins/MvxFilePluginManager.cs#L80
But it may be more complicated... Maybe a fallback system? Tried to load the UWP version, and if it fails, load win81?

**Comment by Cheesebaron** [comment]
We should probably add `WindowsCommon` there as well: https://github.com/MvvmCross/MvvmCross/blob/4.0/Cirrious/Cirrious.MvvmCross.WindowsUWP/Platform/MvxWindowsSetup.cs#L65

**Comment by NPadrutt** [comment]
Might this be the reason for this issue:
http://stackoverflow.com/questions/32537942/mvvm-cross-could-not-load-plugin-assembly-for-type-mvvmcross-plugins-email-plugi/32541289#32541289 or is this not related?

**Comment by azchohfi** [comment]
Yes, @NPadrutt, I think it's the same error.

**Comment by azchohfi** [comment]
@Cheesebaron, will this fix the bug?

**Comment by azchohfi** [comment]
Wow, I'm an idiot... The fix is quite simple... I'll submit a PR for this.

**Comment by Cheesebaron** [comment]
Merged
