### ISSUE TITLE
Documentation Wrong step for android setup: adding an xml file defining the binding attributes.

### ISSUE THREAD

**Issue by ofirgeller** [MvvmCross/MvvmCross#1144]
Adding the file prevents the build as the values are defined somewhere else. If I am understanding this correctly all that needs to be done is for the paragraph to be deleted.

Section to delete:
https://github.com/MvvmCross/MvvmCross/wiki/Tip-Calc-A-Xamarin.Android-UI-project#add-the-mvvmcross-android-binding-resource-file

File:
https://github.com/MvvmCross/MvvmCross/blob/v3/Cirrious/Cirrious.MvvmCross.Binding.Droid/ResourcesToCopy/MvxBindingAttributes.xml

**Comment by Cheesebaron** [comment]
Then delete it?

**Comment by ofirgeller** [comment]
I have never contributed to this project before.
I would like to get someone to confirm that I'm right about this before i
jump in with a pull request.
Makes sense?

**Comment by martijn00** [comment]
Yes it makes sense. We would accept a PR for this.

**Comment by Stephanvs** [comment]
Docs have been updated: https://github.com/MvvmCross/MvvmCross/wiki/Tip-Calc-A-Xamarin.Android-UI-project/_compare/3026d01%5E...3026d01
