### ISSUE TITLE
MvxValueConverter with NativeColor expression returns string in iOS

### ISSUE THREAD

**Issue by gtas-verisk** [MvvmCross/MvvmCross#1149]
I have a converter.

```
public class DueDateHighlighterConverter : MvxValueConverter<DateTime, MvxColor>
    {
		protected override MvxColor Convert(DateTime value, Type targetType, object parameter, CultureInfo culture)
        {
            int days = (value - DateTime.Today).Days;
			MvxColor color = MvxColors.Black;

            if (days <= -1)
            {
				color = MvxColors.Red;
            }
			else if (days <= 7 && days >= 0)
            {
				color = MvxColors.Green;
            }
            
			return color;
        }
    }
```

In the iOS cell constructor.
```
public OrderListViewCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => 
				{
					var set = this.CreateBindingSet<OrderListViewCell, OrderDTO>();

					set.Bind(Date).For(p => p.TextColor).SourceDescribed("If ((Stage == 'Field'), NativeColor(DueDateHighlighter(DueDate)), NativeColor('Black'))");

					set.Apply();
				});
		}
```

The result is a string ARGB representation.

![screen shot 2015-09-30 at 2 19 44 pm](https://cloud.githubusercontent.com/assets/14896282/10202133/6a30c772-677d-11e5-9b50-89e3fbb3c909.png)

**Comment by lothrop** [comment]
Does this happen with a value converter that converts directly to UIColor?

**Comment by Stephanvs** [comment]
I think you have to call `.ToNative()` extension method in the Convert method on the result.

So it would become:

`return color.ToNative();`

Although I might be confusing another framework now?

**Comment by martijn00** [comment]
@Stephanvs isn't that for Splat?

**Comment by Stephanvs** [comment]
You're right, I think I'm confusing frameworks here :ghost:

**Comment by slodge** [comment]
Use the https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/Color/MvvmCross.Plugins.Color/MvxColorValueConverter.cs base class

**Comment by mvanbeusekom** [comment]
As suggested by Stuart Lodge, simply derive from the MvxColorValueConverter base class will solve your problem.

If you really want to do it yourself you could use the following code:

    public class DueDateHighlighterConverter : MvxValueConverter<DateTime, MvxColor>
    {
        private IMvxNativeColor NativeColor => _nativeColor ?? (_nativeColor = Mvx.Resolve<IMvxNativeColor>());

        protected override MvxColor Convert(DateTime value, Type targetType, object parameter, CultureInfo culture)
        {
            int days = (value - DateTime.Today).Days;
            MvxColor color = MvxColors.Black;

            if (days <= -1)
            {
                color = MvxColors.Red;
            }
            else if (days <= 7 && days >= 0)
            {
                color = MvxColors.Green;
            }

            return NativeColor.ToNative(color);
        }
    }
