### ISSUE TITLE
ValueConverter registration doesn't work anymore in v4.0 beta 3

### ISSUE THREAD

**Issue by roubachof** [MvvmCross/MvvmCross#1154]
I try to register my value converter in Setup.cs, but none of the 3 suggested methods are working:

``` csharp

// Method 1
protected override List<Assembly> ValueConverterAssemblies
{
    get
    {
        var toReturn = base.ValueConverterAssemblies;
        toReturn.Add(typeof(FavoriteDrawableValueConverter).Assembly);
        return toReturn;
    }
}

// Method 2
public class Converters
{
    // this converter will be registered with name "TheLength"
    public readonly FavoriteDrawableValueConverter FavoriteDrawable = new FavoriteDrawableValueConverter();
}

protected override List<Type> ValueConverterHolders
{
    get
    {
        var toReturn = base.ValueConverterHolders;
        toReturn.Add(typeof(Converters));
        return toReturn;
    }
}

// Method 3
protected override void FillValueConverters(IMvxValueConverterRegistry registry)
{
    registry.AddOrOverwrite("FavoriteDrawable", new FavoriteDrawableValueConverter());
}
```

If I put breakpoints in those methods, they are never hit.
And I get the following error in runtime:

```
Failed to find combiner or converter for FavoriteDrawable
```

Finally I had it working by specifying it manually in LastChance:

``` csharp
protected override void InitializeLastChance()
{
    base.InitializeLastChance();
    var registry = Mvx.Resolve<IMvxValueConverterRegistry>();
    registry.AddOrOverwrite("FavoriteDrawable", new FavoriteDrawableValueConverter());
}
```

**Comment by Cheesebaron** [comment]
On what platform is this?

**Comment by roubachof** [comment]
Android.

**Comment by roubachof** [comment]
I think to know where it's coming from.
I use a different IoC Provider:

Setup.cs
```csharp
        protected override IMvxIoCProvider CreateIocProvider()
        {            
            return new NinjectMvxIocProvider();
        }
```

But it doesn't seem to register all Mvx components.
For example IMvxMessenger is never registered either.
I put a checkpoint on the method which should register IMvxMessenger:

NinjectMvxIocProvider.cs
```csharp
        public void RegisterSingleton<TInterface>(TInterface theObject) where TInterface : class
        {
            kernel.Bind<TInterface>().ToConstant(theObject).InSingletonScope();
        }
```

But it's never called.

**Comment by Cheesebaron** [comment]
That is strange as IoC is one of the first things to be created when Initializing.

Are you sure stuff are registered as Singleton? What does you App class look like?

**Comment by slodge** [comment]
Where's the source for `NinjectMvxIocProvider`?

Does it fire the `CallbackWhenRegistered` callbacks https://github.com/MvvmCross/MvvmCross/blob/0be52390b80a2a742f815d02beb64afac8d9a7bd/CrossCore/Cirrious.CrossCore/IoC/IMvxIoCProvider.cs#L65

**Comment by roubachof** [comment]
```CallbackWhenRegistered``` is indeed fired.

Here is the gist : [https://gist.github.com/roubachof/2ce930aac4ddcfcf13df](https://gist.github.com/roubachof/2ce930aac4ddcfcf13df)

**Comment by Cheesebaron** [comment]
What happens if you use `RegiterAsSingleton()` instead of Lazy?

**Comment by slodge** [comment]
Your gist shows the callback methods as empty <= that is the problem. You were just lucky anything worked in old versions...

**Comment by roubachof** [comment]
Ok. Then what should I put in those callbacks ?

**Comment by roubachof** [comment]
I'm sorry to bring that again but, what should we put in the callback methods to make a custom IoC container work ?
