### ISSUE TITLE
File Plugin: GetSize(), GetListWriteTimeUtc()

### ISSUE THREAD

**Issue by tekkies** [MvvmCross/MvvmCross#1155]
It would be useful to have some file metadata methods in the file plugin, e.g.
- GetSize(string path)
- GetLastWriteTimeUtc(string path)

**Comment by Cheesebaron** [comment]
If you have the courage to implement it, a pull request would be much appreciated.

**Comment by tekkies** [comment]
Now I got my mac mini build box, I'll see if I can sort it.

**Comment by promontis** [comment]
@tekkies are you using a service for the build box? Or just within your home network?

**Comment by tekkies** [comment]
I have a mac mini under my desk at work.

**Comment by willsb** [comment]
This was closed by #1827
