### ISSUE TITLE
Improve MvxViewModelViewLookupBuilder error output

### ISSUE THREAD

**Issue by vvolkgang** [MvvmCross/MvvmCross#1159]
Messed things up while swapping nugets for the source code projects I needed and got some nasty Linq exception [here](https://github.com/MvvmCross/MvvmCross/blob/0be52390b80a2a742f815d02beb64afac8d9a7bd/Cirrious/Cirrious.MvvmCross/ViewModels/MvxViewModelViewLookupBuilder.cs#L26). 

> The classes in the module cannot be loaded.

This can be bulletproofed by at least giving a hint to what happened or what "modules" couldn't be loaded. Might be an improvement on #246.

**Comment by martijn00** [comment]
This should be better with the new `IMvxLog`. Please open again when still seeing this.
