### ISSUE TITLE
Sharing code across Apple platforms

### ISSUE THREAD

**Issue by Stephanvs** [MvvmCross/MvvmCross#1166]
Investigate code sharing options for Apple platforms using the newly mentioned nuget packages on [Xamarin forums](http://forums.xamarin.com/discussion/55255/sharing-code-across-apple-platforms).

This should also ease the addition of other platforms such as tvOS as mentioned in #1153 

:sparkles: :rainbow:

**Comment by martijn00** [comment]
This is not actively support by Xamarin.
