### ISSUE TITLE
Android - ViewType not found when using fully qualified name in .axml file

### ISSUE THREAD

**Issue by rebutl** [MvvmCross/MvvmCross#1173]
When defining a layout which includes a custom Android control we have seen issues with binding when using the fully qualified name of the control. For example, including a custom view like this

```
<CustomFontTextView .... />
```

works fine, but using

```
    <MyApplication.Views.CustomFontTextView .../>
```

Results in errors like below.

 4.51 View type not found - md564db1fd02b4446a65276c1959f13a32a.CustomFontTextView
MvxBind:Error:  4.51 View type not found - md564db1fd02b4446a65276c1959f13a32a.CustomFontTextView
[0:] MvxBind:Error:  4.51 View type not found - md564db1fd02b4446a65276c1959f13a32a.CustomFontTextView
MvxBind:Error:  4.51 View type not found - md564db1fd02b4446a65276c1959f13a32a.CustomFontTextView
JNI RegisterNativeMethods: attempt to register 0 native methods for md564db1fd02b4446a65276c1959f13a32a.CustomFontTextView

**Comment by Cheesebaron** [comment]
You have not registered your custom view, this is why you get that md5 sum infront of the name. This is not a MvvmCross specific issue.

But to answer either specify it without fully qualifying it. Or if you want to fully qualify it use the
