### ISSUE TITLE
Problem creating target binding for CompoundButton

### ISSUE THREAD

**Issue by joashmusyoka** [MvvmCross/MvvmCross#1174]
I have the following Switch

```xml
<Switch
        android:id="@+id/enableExtensiveLogging"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/android_toolbar"
        android:text="Allow Extensive Logging?"
        android:layout_alignParentRight="true"
        android:layout_marginBottom="@dimen/margin_default_large"
        local:MvxBind="Checked AlloweExtendedLogging; Text CheckedText" />
```

And in Setup.cs I have

```c#
protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            base.FillTargetFactories(registry);
            registry.RegisterFactory(new MvxSimplePropertyInfoTargetBindingFactory(typeof(MvxCompoundButtonCheckedTargetBinding), typeof(CompoundButton), "Checked"));
        }
```

When the app starts I get in the Android Log an exception that:

> Problem creating target binding for CompoundButton - exception System.MissingMethodException: No constructor found for Cirrious.MvvmCross.Binding.Droid.Target.MvxCompoundButtonCheckedTargetBinding::.ctor(Android.Widget.Switch, System.Reflection.MonoProperty)

How should I use the MvxCompoundButtonCheckedTargetBinding

**Comment by joashmusyoka** [comment]
I have xamarin linking turned on

**Comment by Cheesebaron** [comment]
You don't need to manually register the TargetBinding for CompoundButton. It already happens on setup: https://github.com/MvvmCross/MvvmCross/blob/4.0/Cirrious/Cirrious.MvvmCross.Binding.Droid/MvxAndroidBindingBuilder.cs#L95

**Comment by joashmusyoka** [comment]
@Cheesebaron Thanks for the prompt answer.

I have removed the override for FillTargetFactories from Setup.cs but I am still observing the same log and binding for checked state is not working.

**Comment by Cheesebaron** [comment]
Do you hit any breakpoints if you set them inside of the target?

**Comment by joashmusyoka** [comment]
This is part of my ViewModel:

```c#
public bool AlloweExtendedLogging
        {
            get
            {
                return this.alloweExtendedLogging;
            }

            set
            {
                this.SetProperty(ref this.alloweExtendedLogging, value, () => this.AlloweExtendedLogging);
                if (value)
                {
                    this.CheckedText = "Extended Logging Enabled";
                }
                else
                {
                    this.CheckedText = "Extended Logging Disabled";
                }
            }
        }
```

When I step through the setter, AlloweExtendedLogging becomes true but the button does not check its state.

Also I am using MvxAppCompatActivity in case that matters. I am refactoring an app that is already in production and it already used AppCompatActivity.

**Comment by Cheesebaron** [comment]
What does `this.SetProperty(ref this.alloweExtendedLogging, value, () => this.AlloweExtendedLogging);` do?

**Comment by joashmusyoka** [comment]
Its from a BaseViewModel that I inherit from.

```c#
protected void SetProperty<T>(
            ref T backingStore,
            T value,
            Expression<Func<T>> property)
        {
            if (Equals(backingStore, value))
            {
                return;
            }

            backingStore = value;

            this.RaisePropertyChanged(property);
        }
```

A common place for setting the value and firing the property changed event.

**Comment by Cheesebaron** [comment]
Hmm this is strange. Even if you are using AppCompat and it would be using SwitchCompat behind your back it should work as both Switch and SwitchCompat inherit from the same CompoundButton.

Do other bindings work?

**Comment by joashmusyoka** [comment]
Yes. I even tried binding the enabled state of the Switch, using the same AllowExtendedLogging and it worked just fine.
![extended logging](https://cloud.githubusercontent.com/assets/10183041/11179545/30386644-8c65-11e5-8edb-ad498e55da6e.PNG)

As you can see, the text on the button already says extended logging enabled but the button is not checked.

**Comment by joashmusyoka** [comment]
It always throws this error:

### Problem creating target binding for CompoundButton - exception System.MissingMethodException: No constructor found for Cirrious.MvvmCross.Binding.Droid.Target.MvxCompoundButtonCheckedTargetBinding::.ctor(Android.Widget.Switch, System.Reflection.MonoProperty)

into the logger. Seems it's trying to instantiate using a switch instead of a CompundButton object.

**Comment by Cheesebaron** [comment]
That is strange because there is a [ctor looking like this](https://github.com/MvvmCross/MvvmCross/blob/4.0/Cirrious/Cirrious.MvvmCross.Binding.Droid/Target/MvxCompoundButtonCheckedTargetBinding.cs#L20):

    public MvxCompoundButtonCheckedTargetBinding(object target, PropertyInfo targetPropertyInfo)

**Comment by Cheesebaron** [comment]
Can you make a reproducible sample?

**Comment by joashmusyoka** [comment]
I will be happy to do that. What do i need to do/submit. any guideline?

**Comment by Cheesebaron** [comment]
Just create a new repo with a sample app

**Comment by joashmusyoka** [comment]
ok. will do that and link back. thanks for your time

**Comment by joashmusyoka** [comment]
In the process of creating a reproducible sample and realized that if i use MvxActivity instead of MvxAppCompatActivity, the binding is working.

**Comment by joashmusyoka** [comment]
@Cheesebaron I have created a sample but the binding works on the sample and not my main project. Even with the AppCompat

**Comment by joashmusyoka** [comment]
Could it be because in the project I am navigating to the activity using normal android intents and in the sample I am MvvmCross navigation mechanism?

**Comment by Cheesebaron** [comment]
Yes

**Comment by joashmusyoka** [comment]
I have sorted the issue as follows:

Under project properties, -> Android Options in the Packaging tab. DO NOT check 'Use Shared Runtime'

In LinkerConfiguration.xml Add
```xml
  <assembly fullname="Cirrious.MvvmCross.Binding.Droid">
    <type fullname="Cirrious.MvvmCross.Binding.Droid.Target.MvxCompoundButtonCheckedTargetBinding">
      <method name=".ctor" />
    </type>
  </assembly>
```

Clean and rebuild.

**Comment by Cheesebaron** [comment]
Well if you use your own Intent you will probably need to instantiate the VM yourself.
