### ISSUE TITLE
ReloadFromBundle not called

### ISSUE THREAD

**Issue by dazinator** [MvvmCross/MvvmCross#1177]
I am having an issue on Android, with ReloadFromBundle() not being called on my view model when screen orientation is changed and android decides to re-create the view.

This is with latest stable release of MvvmCross (version 3.5.1)

I have simple view:

``` csharp
 [Activity(Label = "Sync Screen")]
    public class SyncView : MvxActivity<SyncViewModel>
    {

}
```

And a ViewModel

``` csharp
       protected override void SaveStateToBundle(IMvxBundle bundle)
        {
            //base.SaveStateToBundle(bundle);
            bundle.Data.Add("Something", "blah");            
        }

       protected override void ReloadFromBundle(IMvxBundle state)
        {
           if (state.Data.ContainsKey("Something"))
            {
                var data = state.Data["Something"];               
            }
            base.ReloadFromBundle(state);
        }
```

Now - when I change orientation of the screen, `SaveStateToBundle` get's invoked. 
The screen is then recreated (i.e OnCreate() get's called on the Activity).
OnStart() get's called on my ViewModel
but ReloadFromBundle() never get's called on my ViewModel..

Any ideas?

**Comment by martijn00** [comment]
Use the MvxCachingFragmentActivity from MvvmCross 4.0

**Comment by dazinator** [comment]
but isn't mvx 4 still in pre-release? I'd prefer to stick with a stable release.. in which case a hotfix would seem in order for this release if this is indeed a problem?

**Comment by martijn00** [comment]
4.0 is currently in beta, but it is stable enough to use in production. This is not really a problem of MvvmCross Activity, but rather of Android itself. The MvxCachingFragmentActivity tries to solve this problem manually.

**Comment by dazinator** [comment]
Thanks martin,

I'm a little worried about how big of an upgrade process it would be to go from 3.5.1 to 4. It's a new major version which would seem to imply that there are going to be breaking / non backwards compatible changes (atleast that's the correct inference from a semver versioning perspective!).

The documentation for the lifecycle in v3 suggest this should work: https://github.com/MvvmCross/MvvmCross/wiki/View-Model-Lifecycle

If we are saying I am not doing something stupid (which wouldn't be the first time..) and there is a fundamental reason why this doesn't work in v3, then the documentation for v3 that I have linked above would seem to.. very misleading. Really it should reloading state is not supported in v3 on Android?

All that said, I will give upgrading to 4 a go if you think that's my easiest path to a resolution :)

**Comment by martijn00** [comment]
Some things indeed break, but in general it should be pretty easy to update.

**Comment by dazinator** [comment]
Hmm.. I just managed to fix this quite simply in v3.

I added this to my Base Actvitiy:

```

        protected override void OnRestoreInstanceState(Bundle savedInstanceState)
        {

            IMvxSavedStateConverter converter;
            if (!Mvx.TryResolve(out converter))
            {
                MvxTrace.Warning("Saved state converter not available - saving state will be hard");
            }
            else
            {
                if (savedInstanceState != null)
                {
                    var mvxBundle = converter.Read(savedInstanceState);
                    this.ViewModel.ReloadState(mvxBundle);
                }
            }

            base.OnRestoreInstanceState(savedInstanceState);

        }

```

**Comment by dazinator** [comment]
Thanks for your help @martijn00  - I am going to stick with the above workaround for the present and I will look into upgrading to v4 once a stable release is out.

I do find it odd that in `MvxEventSourceActivity` in v3, it handles all the important lifecycle methods, except for `OnRestoreInstanceState` - it's like it's either been deliberately removed for some reason, or it was never implemented. Implementing it in my base activity instead, and invoking the respective `ReloadState` on the view model seems to have solved my immediate problem, and I am hoping it hasn't introduced anything detrimental - will see with time.

**Comment by henrikstromberg** [comment]
I have the same bug the method is not called   ReloadFromBundle (IMvxBundle state) so I tryed to use the method on the Activity but that is not called either
protected override void OnRestoreInstanceState (Bundle savedInstanceState)

I use the latest version 4 release is there any other way to detect when navigation back to an activity.
I call Close(this) on my ViewModel to navigate back

is there anu

**Comment by roubachof** [comment]
I have a similar issue: when calling close on a child ViewModel, the Init method of the parent view model is called instead of ReloadState: http://stackoverflow.com/questions/34952174/isnt-reloadstate-method-conflicts-with-init-on-mvxviewmodel.
But it's more a AndroidSupport issue. I will open an issue on this.
