### ISSUE TITLE
Mvvmcross 4 SQLite plugin iOS build error

### ISSUE THREAD

**Issue by woody1987** [MvvmCross/MvvmCross#1181]
mvvmcross 4 sqlite beta6 causes a build error on my iOS app (Android unaffected)

`MTOUCH: error MT2002: Failed to resolve assembly: 'SQLite.Net.Platform.XamarinIOS, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'`

My packages.config:

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Cirrious.FluentLayout" version="2.0.0" targetFramework="xamarinios1" />
  <package id="HtmlAgilityPack" version="1.4.9" targetFramework="xamarinios10" />
  <package id="MvvmCross" version="4.0.0-beta5" targetFramework="xamarinios1" />
  <package id="MvvmCross.HotTuna.Binding" version="4.0.0-beta5" targetFramework="xamarinios1" />
  <package id="MvvmCross.HotTuna.CrossCore" version="4.0.0-beta5" targetFramework="xamarinios1" />
  <package id="MvvmCross.HotTuna.MvvmCrossLibraries" version="4.0.0-beta5" targetFramework="xamarinios1" />
  <package id="MvvmCross.HotTuna.Plugin.File" version="4.0.0-beta5" targetFramework="xamarinios1" />
  <package id="MvvmCross.HotTuna.Plugin.Location" version="4.0.0-beta5" targetFramework="xamarinios1" />
  <package id="MvvmCross.HotTuna.Plugin.Messenger" version="4.0.0-beta5" targetFramework="xamarinios1" />
  <package id="MvvmCross.HotTuna.Plugin.SQLitePCL" version="4.0.0-beta6" targetFramework="xamarinios1" />
  <package id="MvvmCross.HotTuna.StarterPack" version="4.0.0-beta5" targetFramework="xamarinios1" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="xamarinios10" />
  <package id="SharpZipLib.Portable" version="0.86.0.0003" targetFramework="xamarinios10" />
  <package id="SQLite.Net.Async-PCL" version="3.1.1" targetFramework="xamarinios1" />
  <package id="SQLite.Net.Core-PCL" version="3.1.1" targetFramework="xamarinios1" />
  <package id="SQLite.Net-PCL" version="3.1.1" targetFramework="xamarinios1" />
</packages>`

I have tried downgrading to earlier betas of the plugin which use version 3.0.5 of the sqlite.net packages but they same error occurs, though it complains about version 3.0.5 not 3.1.0.0

**Comment by Cheesebaron** [comment]
Probably related to: https://github.com/oysteinkrog/SQLite.Net-PCL/issues/234

**Comment by woody1987** [comment]
Yep, I saw that but there's no solution given. The suggestions of uninstalling and reinstalling aren't working.

**Comment by woody1987** [comment]
I've managed to solve this issue, well a work around at any rate. 

I downloaded the SQLite.Net src from https://github.com/oysteinkrog/SQLite.Net-PCL

Compiled the SQLite.Net.Platform.XamarinIOS project and added a reference to the resulting SQLite.Net.Platform.XamarinIOS.dll

**Comment by SeeD-Seifer** [comment]
I had the same issue after updated to new beta packages.
The thing is for some reason `SQLite.Net.Platform.XamarinIOS` library is almost for sure is not referenced by default.

To fix the error, open you `Project.iOS.csproj` file in editor and ensure that library referenced:

```xml
    <Reference Include="SQLite.Net.Platform.XamarinIOS">
      <HintPath>..\packages\SQLite.Net-PCL.3.1.1\lib\monotouch\SQLite.Net.Platform.XamarinIOS.dll</HintPath>
    </Reference>
```

**Comment by woody1987** [comment]
Ah, didn't realise it was actually already in the package. That's much simpler!

**Comment by ggirard07** [comment]
Not sure it is the same issue. Based on the error message I am reproducing in my app, it looks like we attempt to load the Classic API assembly whereas we should be loading the Unified version.
Just took a quick look at https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/SQLite-PCL/MvvmCross.Plugins.Sqlite.iOS/MvvmCross.Plugins.Sqlite.iOS.csproj and the project GUID used is the Classic API one (https://developer.xamarin.com/guides/cross-platform/macios/updating_ios_apps/).
We should either update it for the unified API or add a new implementation to the plugin for Unified if we need to support both.

I didn't have more time to investigate it today, I will do tomorrow and PR if my speculation was correct :)

**Comment by Cheesebaron** [comment]
Please reopen the issue if you believe this still is a problem.
