### ISSUE TITLE
UWP back button visibility suggestion

### ISSUE THREAD

**Issue by Depechie** [MvvmCross/MvvmCross#1183]
While creating win 10 UWP apps, it's possible to show an optional build in back button, cfr reference https://msdn.microsoft.com/en-us/library/windows/apps/mt465734.aspx ( device: PC, Laptop, Tablet )

This is easily triggered by using a property on the SystemNavigationManager cfr reference 
https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.core.systemnavigationmanager.appviewbackbuttonvisibility

Could this be added in MvvmCross so that we can toggle it? My guess would be somewhere on the MvxWindowsViewPresenter? Any thoughts?

**Comment by martijn00** [comment]
@Stephanvs maybe something for you if you have time?

**Comment by auspex-nl** [comment]
Also see this blog post: http://www.wintellect.com/devcenter/jprosise/handling-the-back-button-in-windows-10-uwp-apps

If you use the code in that post and put it in your App.xaml.cs, the back button does in fact work as intended (in a small app using only 2 viewmodels/views). I'm not sure if it will work correctly with more complicated navigation methods and/or views though.

**Comment by duglah** [comment]
Implemented back button visibility and BackRequest event handling in pr #2165
