### ISSUE TITLE
4.0 beta 5 - Cirrious.MvvmCross.Binding.Droid is not referenced/does not exist

### ISSUE THREAD

**Issue by robertbaker** [MvvmCross/MvvmCross#1185]
```
Severity	Code	Description	Project	File	Line
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Cirrious.MvvmCross.Binding.Droid, Version=4.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Cirrious.MvvmCross.Binding.Droid.dll'
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()	OpSuitePOS.Droid		

```

Just started a Xamarin 4 PCL project, android API 4.3 (18). 

It also didn't generate the MvxBindingAttributes.xml

**Comment by martijn00** [comment]
MvxBindingAttributes is not needed anymore. Other then that this error doesn't mean much to me. Please explain more what you are doing.

**Comment by robertbaker** [comment]
I'm using 4.0.0 b5. Following the tip calc guide. I have a pcl project with
xamarin forms but I'm trying to learn what I need to do to get sqlite
working.

**Comment by robertbaker** [comment]
@martijn00 Is 4.0 beta good enough to use at this point? Seems like I'm getting compiler errors following the sample about missing/unknown classes.

**Comment by SeeD-Seifer** [comment]
@robertbaker not sure about sample issue, but we are using it and going to ship new versions of both iOS and Android apps to the store today.

But it took some time to migrate from v3.5 to v4.0 because of different compile issues.

**Comment by martijn00** [comment]
@robertbaker Yes it is good enough to use in production currently. There is some stuff that changed in regards to the samples, but we are working on fixing that!

**Comment by robertbaker** [comment]
@martijn00 thanks. Trying to convice the boss and the team to use this framework. We are starting on our first xamarin app. Could you give me a few reasons why we should use this over just xamarin forms?

**Comment by martijn00** [comment]
There are some many things you do wrong when starting to develop apps. I would recommend to hire some dudes with strong Xamarin skills to set up things right.

Other then that you could combine Xamarin.Forms with MvvmCross: https://github.com/MvvmCross/MvvmCross-Forms

Reasons to work or not to work with Forms are available in all kind blogs on Google. Personally i think that you can offer the best user experience using native Xamarin (with MvvmCross)
