### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1190]
I'd like all these things to happen eventually:

* [x] Removal of HotTuna from all NuGet ID's
* [x] Removal of HotTuna from all namespaces
* [x] Removal of Cirrious from all namespaces
* [ ] Change license headers to better attribute the entire team
* [x] Make sure, descriptions of old NuGet Packages get updated to inform about the new (and hopefully final) IDs

**Comment by bspinner** [comment]
- [ ] Make sure, descriptions of old NuGet Packages get updated to inform about the new (and hopefully final) IDs

**Comment by robertbaker** [comment]
+1

Should be done for the v4 release. Also update the SqlLite plugin section on the doc to reference the new plugin, not the deprecated one.

**Comment by martijn00** [comment]
I've already done the name change for Plugins, Android-Support and Forms, now only the main repo remains.

**Comment by robertbaker** [comment]
@martijn00 Keeping the nuget package id's with Cirrous and HotTuna makes things harder and a bit confusing when searching for mvvmcross packages.

If the namespaces changed anyway, the users on v3 would need to do a bit of work anyway to upgrade to v4. At least if the id's change now it makes things easier going forward.

**Comment by lothrop** [comment]
I also think this should all be in the 4.0.0 release.

**Comment by MKuckert** [comment]
Will you replace the old NuGet packages? Or create some new ones with the updated id?

**Comment by martijn00** [comment]
I am not totally sure, but i thought that deleting or replacing existing nuget packages with new packages with another ID is not possible. The main disadvantage will then be that no existing MvvmCross user ever will see the update button in VS or XS. If we keep the ID for the nugets, but we change the namespace, users will see a compile error after building, and see that they need to reference a new namespace.

**Comment by MKuckert** [comment]
Sounds like the old packages should at least get an update to inform existing users about the changes and provide them with a link to a migration guide. If updating to a newer id is not possible.

**Comment by bspinner** [comment]
@MKuckert Try reading the whole thread before answering, especially the first post :stuck_out_tongue_closed_eyes:

**Comment by MKuckert** [comment]
Sure read that. Just wanted to understand the process and give my 50 cents about the migration though.

**Comment by Cheesebaron** [comment]
The old ones can't and won't go away. NuGet only supports unlisting packages, which means you cannot search for them. However, you can still install them and restore them in your projects, only through the command line.

So all current alpha and beta packages will be unlisted, and all the last stable packages will be marked as **old**.

We should of course notify developers on twitter and the blog and make some docs on how they should upgrade.

**Comment by martijn00** [comment]
Ok, that sounds like a plan! I can make the nuspec and namespace changes. Are there any volunteers to update the documentation on the [new website](https://mvvmcross.readme.io/docs) that we will launch together with 4.0?

**Comment by bspinner** [comment]
@MKuckert No offense intended. :smile: 
@martijn00 @Cheesebaron hm, would a migration script be feasible? We'd need a list what needs to be done, first of course...

**Comment by jonstoneman** [comment]
It's been a while since I've found time for Mvx but I'll commit to bringing TipCalc up to date and in-line with these changes.

@martijn00 I'll do at least some of the other documentation on that site as well.

**Comment by martijn00** [comment]
@jonstoneman The samples now have a new home in the [samples repo](https://github.com/MvvmCross/MvvmCross-Samples). The TipCalc currently is in the old folder, but can be moved to the root after updating. The same is for the other samples, most of them are broken and need some small fixes.

**Comment by jonstoneman** [comment]
@martijn00 Are you able to give me edit permissions on readme.io?

**Comment by promontis** [comment]
@jonstoneman Got an email address?

**Comment by martijn00** [comment]
@jonstoneman @promontis Everyone with a normal Readme account should be able to edit files, and submit them for review. Would that work?

**Comment by jonstoneman** [comment]
That would be fine actually.  Would be nice to have some reviews happening.  :+1:

**Comment by robertbaker** [comment]
Should add documentation updates/cleanup to this list.

**Comment by taspeotis** [comment]
For your consideration:

As far as the old NuGet packages go you can replace them with "shell" packages. E.g. MvvmCross.HotTuna.Core can get its own v4 package with *no assemblies* but a dependency to MvvmCross.Core v4. 

That way you get an in-place upgrade (at the expense of broken namespaces).

**Comment by djrocksmith** [comment]
I'm starting on this refactor task

**Comment by martijn00** [comment]
@djrocksmith I already did start on this some days ago, but it is quite some work. See my branch: https://github.com/martijn00/MvvmCross/tree/restructure

I think it might be better to open a branch for this in the main repo so everyone can contribute on that.

**Comment by lothrop** [comment]
Can you push your branch to here?

**Comment by martijn00** [comment]
Sure.

**Comment by martijn00** [comment]
@lothrop  Here you go: https://github.com/MvvmCross/MvvmCross/tree/restructure

**Comment by djrocksmith** [comment]
Thanks @martijn00 I'll work from that also

**Comment by martijn00** [comment]
@djrocksmith most things seem to work now with your PR. Only some Mac and Windows issue's remaining.

**Comment by martijn00** [comment]
I think we also need to remove the non-unified ios and mac projects. They are anyways not supported by Apple or Xamarin anymore.

**Comment by lothrop** [comment]
@martijn00 I'll do that.

**Comment by lothrop** [comment]
I already removed non-unified iOS for the 3.5 release. I'll remove the non-unified Xamarin.Mac projects. I suppose MonoMac (non-Xamarin) should stay?

**Comment by Cheesebaron** [comment]
I have no idea whether MonoMac or Xamarin.Mac solutions work. It seems to build but...

**Comment by martijn00** [comment]
What benefit has MonoMac?

**Comment by martijn00** [comment]
The other solution files should also be cleaned. The MvvmCross_All.sln contains the new proposed structure.

**Comment by lothrop** [comment]
The benefit of MonoMac is that it doesn't need a Xamarin license, though it is not as well looked after. You could also theoretically still use non-unified Xamarin.Mac since you don't have to go through the app store on Mac. That's why there are currently three options in MvvmCross. I think we can at least drop Xamarin.Mac non-unified, though, perhaps even MonoMac.

**Comment by martijn00** [comment]
I think this would be the right time to drop some stuff. Go for it!

**Comment by lothrop** [comment]
So I'll leave only Xamarin.Mac Unified. I'll rename that to Mac, which is already the only one referenced in `MvvmCross_All.sln`. Or does that cause too much confusion?

**Comment by martijn00** [comment]
Yeah go for the rename. We already break things.

**Comment by lothrop** [comment]
I made the changes in #1198 and am merging that into the `restructure` branch.

**Comment by martijn00** [comment]
@lothrop I think the Mac projects can stay in the same solution. They don't cause any extra trouble, right?

**Comment by lothrop** [comment]
Not that I can tell. They just don't load on Windows. I can recreate them as soon as someone complains.

**Comment by lothrop** [comment]
The nuspec directory contains some files that reference old MvvmCross versions. Are they still needed?

**Comment by Cheesebaron** [comment]
https://github.com/MvvmCross/MvvmCross/blob/4.0/nuspec/pack.ps1 these are used.

**Comment by lothrop** [comment]
Fixed in #1201.

**Comment by lothrop** [comment]
It seems the `.Touch` ending for iOS projects may confuse people new to Xamarin.iOS. How about we (I) rename those to `.iOS`?

**Comment by martijn00** [comment]
Won't that give conflicts with the global iOS namespace? Otherwise it seems good to me.

**Comment by lothrop** [comment]
@martijn00 I'm not aware of a global `iOS` namespace. The `MonoTouch` namespace was dropped completely with the switch to Unified API. See #1204.

**Comment by martijn00** [comment]
Great work with those latest changes! @lothrop 

About the license headers: are they necessary at all?
When looking at other OSS projects i don't see them using it either.

**Comment by lothrop** [comment]
Still have to test if any of it makes sense.

I would get rid of the headers. I just corrected a few with outdated information. Some files already don't have headers.

**Comment by martijn00** [comment]
I was trying to remove the headers with resharper last night, but i can't get a proper search pattern working. Does anyone have idea's how to do this?

**Comment by Cheesebaron** [comment]
License headers are needed for the actual file to be licensed. Other project which don't use them simply don't have their files licensed.

**Comment by martijn00** [comment]
Alright, so you are saying we should add the license header to where it is missing? Do you have any idea what should be changed in the content of it?

**Comment by Cheesebaron** [comment]
Would like instead of having it saying:

Stuart Lodge, Project Lead

say

MvvmCross team

maybe also refer to a contributors file or similar.

I hope that is ok with @slodge, we should of course make sure that everyone who contributes gets credit for that. I think we have discussed this before @martijn00. If I remember the conclusion of that discussion correctly we decided to invite people into the contributors group here in this GitHub team. Maybe for offline reading, we should have an actual file which is updated with new names once in a while?

**Comment by martijn00** [comment]
Yeah sounds good! We indeed discussed the contributors before, and made the group on github to give a bit of credit. Maintaining an offline list sounds painful, so i would suggest putting in a link to the group.

**Comment by Cheesebaron** [comment]
It is just when looking at the header, and pointing it to a Contributors.md file it would be nice to have people listed there. Sure we could say that the most recently updated list can be found by looking at the GitHub team.

**Comment by Stephanvs** [comment]
Hm I think there should be a way to generate a contributors list. At least I know that github supports retrieving them through the API.

**Comment by lothrop** [comment]
That would probably feasible as be part of the planned CI.

**Comment by taspeotis** [comment]
I just upgraded our projects to MvvmCross 4.0.0-beta8. The whole process took about two hours (mostly uninstalling/reinstalling NuGet packages x 3 projects and then R# ALT+ENTER'ing the right namespaces).

At the end it worked straight away.

For everybody working on this: thanks for the commitment to MvvmCross.

**Comment by Dexyon** [comment]
@taspeotis Good to hear!

**Comment by jonstoneman** [comment]
The TipCalc code has been updated in my fork although I've got a problem with the iOS project.  Not looked into it yet and it might be a problem with my Mac but will get that sorted and add a UWP project.  Once that's done, should it be moved from the OldSamples directory into the root of the samples project?  

I might actually rebuild it from scratch at that point to get rid of any legacy code from the countless Mvx, VS and Xamarin upgrades it's been through.

**Comment by martijn00** [comment]
Yes once it is up to date, the sample should be moved to the root.

**Comment by jonstoneman** [comment]
OK, will-do.. I'll hopefully get to look at it again tomorrow/next week.

**Comment by jonstoneman** [comment]
I've started updating the docs but when adding an image the upload image button does nothing.  Could whoever reviews the changes please insert the images where I've added placeholder text please?

[ios-screenshots.zip](https://github.com/MvvmCross/MvvmCross/files/93441/ios-screenshots.zip)

**Comment by Cheesebaron** [comment]
I've merged your changes, but it is not clear where to add the images...

**Comment by Cheesebaron** [comment]
I can't add pictures to docs either, so will probably just upload them on imgur and add them that way

**Comment by jonstoneman** [comment]
Sorry, I should probably have mentioned the format I'd used.  :)

I'm finding the "suggest edits" method a bit difficult as I can't see changes I've previously suggested or easily make additional changes until they've been merged.  I also can't edit the sidebar links, which I actually want to do now to make UWP the first Windows project.  Can I get permissions please?

**Comment by martijn00** [comment]
@jonstoneman I could add you. The only problem i have with adding other users is, that there is not really a permissions system, so when you get rights you should only change content and not settings.

**Comment by jonstoneman** [comment]
Heh - I'll be careful...  :)

**Comment by martijn00** [comment]
I need your email address to add you @jonstoneman

**Comment by jonstoneman** [comment]
The new [TipCalc solution](https://github.com/MvvmCross/MvvmCross-Samples/pull/6) is ready, docs need some more work.

@martijn00: I emailed you my readme.io address - ping me at jon at stoneman.me.uk if you didn't get it.. ta!

**Comment by jonstoneman** [comment]
I've added the UWP docs, reordered and done a general tidy up.  I've also added a new page explaining how to get strongly typed ViewModels since the tutorial now uses naming convensions for linking Views with ViewModels.  It would be great if someone could review - aside from any corrections it would be good to know about any new features which the tutorial should take advantage of...
