### ISSUE TITLE
Question: Tear down application programatically for Component/Integrationtests?

### ISSUE THREAD

**Issue by GibSral** [MvvmCross/MvvmCross#1191]
I am using SpecFlow to test the behaviour of my app. I want to close the app after each testcase/scenario and recreate it before every testcase/scenario. At the moment i let the app run until after the last test and reset everything manually after each testcase/scenario, but this is error-prone.
Is it possible to close the app programatically?

Thx in advance
Lars

**Comment by Cheesebaron** [comment]
Please use StackOverflow for questions. We try keeping GitHub for issues only.
