### ISSUE TITLE
MvvmCross team meeting at Evolve 2016

### ISSUE THREAD

**Issue by lothrop** [MvvmCross/MvvmCross#1197]
I'm interested in organizing a discussion on MvvmCross at Evolve in April 2016 in Orlando. It would be nice to have contributors meet there for the first time. We could also invite people from Xamarin. Do you think it's a good idea and which topics should we put on the agenda, apart from the future of MvvmCross?

@slodge, will you be heading to Orlando, too?

**Comment by martijn00** [comment]
Nice idea! I'm in!

**Comment by azchohfi** [comment]
My plane tickets are bought! Count me in!

**Comment by gshackles** [comment]
Absolutely

**Comment by smstuebe** [comment]
+1

**Comment by fcaico** [comment]
I'll be there

**Comment by lothrop** [comment]
I'll try to get a room either from Xamarin or the hotel.

**Comment by Cheesebaron** [comment]
I should be there.

**Comment by slodge** [comment]
Just back from Xmas skiing :) 

Sadly won't be heading to Florida.... But getting much mobile work in at the moment and my liver is also maxed out after skiing :) 

But v v v v v impressed that the cheese has a passport!  Have a beer for me -  I know it'll be awesome!

**Comment by Cheesebaron** [comment]
@slodge actually, I don't. I am in the middle of getting one though. Have some trouble with it as all of the sudden they don't believe I am a Polish citizen. So now I have to fill out loads of papers and have them make a confirmation. Then I can get a passport. It kind of seems like they just want to milk people from their $$$$

**Comment by djrocksmith** [comment]
I'll try to attend.

**Comment by Stephanvs** [comment]
I won't be able to attend but I'd :heart: it if somebody would record it, and put it online afterwards..

**Comment by lothrop** [comment]
@slodge How about we schedule a time of day where you can join remotely?

**Comment by mohibsheth** [comment]
:+1: to recording

**Comment by Ericslnl** [comment]
Great plan! Im in also!

**Comment by JelleDamen** [comment]
I'm in as well!

**Comment by bspinner** [comment]
Won't be there, but great idea!

**Comment by lothrop** [comment]
So we've got a place to meet near the Darwin lounge. Now we need to think about what to talk about. I think it would be nice to have someone tell us what's new in MvvmCross 4.0. And how about a success story? We might also prepare a roadmap and discuss it.

**Comment by fuzzybinary** [comment]
Count 2 from my company in as well.

**Comment by smstuebe** [comment]
Just an idea:
What do you think about creating some stickers of the new Mvx logo to show our MvxLove!? I'd order some on stickermule. But the smallest amount you can order is 50. So it would be nice if you'd agree to participate in the costs (~1€ / sticker).

**Comment by gshackles** [comment]
@smstuebe We were actually just talking about that this morning in the Slack channel :smile: We'll make this happen

**Comment by Ericslnl** [comment]
@lothrop Great plan to have some kind of talk also, @martijn00 and I already made a recent presentation about MvvmCross 4.0 which we can extend. Which success story should we add? And which client logo's should we add to a reference page? The roadmap is also a great idea!

**Comment by martijn00** [comment]
Yes i can do the MvvmCross talk based on what i will present on Xamarin university and add some more inside details to that. https://university.xamarin.com/guestlectures/starting-a-xamarin-project-with-mvvmcross-40

**Comment by AlecDTucker** [comment]
This sounds great - I'm keen to attend (although I haven't contributed). It'll be very interesting to hear about success stories for future reference.

**Comment by Ericslnl** [comment]
We are almost there! After next week we will be meeting @ Evolve! It might be a good idea to plan this MvvmCross meetup on the Sunday before the training sessions! Xamarin will fill our evening schedules for the whole week with dinners & events. Who will be in for the Sunday? @martijn00, me and more colleagues will be available for sure!

**Comment by robertbaker** [comment]
Argh, wish I could go.

**Comment by azchohfi** [comment]
I'll arrive on Tuesday, so Thursday is the best day for me, because  Wednesday we'll be at Universal.

**Comment by gshackles** [comment]
I'll be getting in Sunday night

**Comment by lothrop** [comment]
It seems we're getting a Birds of a Feather slot. I hope to find out more soon.

**Comment by fuzzybinary** [comment]
Yeah, two people from our company would love to come to a gathering, but we're getting in just for the conference Tuesday night.

**Comment by lothrop** [comment]
It'll most likely take place on Wednesday at noon in the Darwin lounge. They say we have 15-30 minutes but the next event is at 1 pm, so we can take longer, if needed. Don't want people to miss lunch, though... There is a monitor there we can connect to to show something.

**Comment by lothrop** [comment]
I've changed it to Thursday, 8 am, as there is an invitation-only lunch on Wednesday.

**Comment by martijn00** [comment]
We've created a Meetup group for this. Please join at: http://www.meetup.com/MvvmCross-Evolve-Meetup/

**Comment by lothrop** [comment]
Also, there will be a less formal get-together on Monday evening, for those attending training: http://www.meetup.com/MvvmCross-Evolve-Meetup/events/230568255/
