### ISSUE TITLE
MvxCommand(async () => await ...) blocking UI

### ISSUE THREAD

**Issue by Johan-dutoit** [MvvmCross/MvvmCross#1215]
I have a ViewModel with the following code 

     public IMvxCommand LoginCommand => new MvxCommand(async () => await LoginClicked());

     private async Task LoginClicked()
     {
         //.....
     }

Which has a couple of seconds (depending on how old the device is) delay once I click on the button, ultimately blocking the UI. (I have tried the above written in multiple ways).  

However when I change the code to the following, then there are absolutely no delays.

    public IMvxCommand LoginCommand => new MvxCommand(LoginClicked);

    private void LoginClicked()
    {
        Task.Run(async () => await Login());
    }

Obviously I prefer the above option, but it causes bad user experience.  I have only had the option to try this on Xamarin.Android so far, will shortly test it on iOS and WP.

using 
1. MVVMCross 4.0.0-beta7
2. Latest Xamarin
3. VS2015.1
4. Android 5.1

**Comment by martijn00** [comment]
Why not use `MvxAsyncCommand` ?

**Comment by Johan-dutoit** [comment]
That would be because I havent RTFM!  I'll report back!

**Comment by Johan-dutoit** [comment]
Sadly the performance is the same as the first example
       public IMvxCommand LoginCommand => new MvxAsyncCommand(LoginClicked);

However, it's faster the 2nd time round, so seems like something is initializing and blocking the UI before starting a new thread/running in the background.

**Comment by martijn00** [comment]
Can you look into the [source](https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Core/Core/ViewModels/MvxAsyncCommand.cs) to see if you can find the cause?

**Comment by Johan-dutoit** [comment]
I added the source to my project and stepped through the code, to see what was taking long and I found the following.

It seems the below code is actually executed on the main thread instead of new/background thread.

      protected override Task ExecuteAsyncImpl(object parameter)
      {
            return this._execute(this.CancelToken);
      }

**Comment by Johan-dutoit** [comment]
Changing it to something as ugly as this

    protected override async Task ExecuteAsyncImpl(object parameter)
    {
        await Task.Run(async () => await this._execute(this.CancelToken));
    }

Provides the experience I require.  Obviously this isn't a perfect solution, but rather a way to see if that is actually the problem.

**Comment by lothrop** [comment]
What's the content of your `LoginClicked()` method? Can you post the line containing the `await`?

**Comment by andyci** [comment]
Are you not missing .ConfigureAwait(true)?

**Comment by lothrop** [comment]
@andyci No, `true` is the default and it should actually be `.ConfigureAwait(false)`. The problem seems to be that the method doesn't do anything asynchronous. Just decorating it with `async` won't make the method run in the background.

**Comment by lothrop** [comment]
See http://kerry.lothrop.de/async-keyword/.

**Comment by Johan-dutoit** [comment]
My method definitely does aync code, makes a web request.

**Comment by lothrop** [comment]
What does the first line containing `await` look like?

**Comment by Johan-dutoit** [comment]
var result = await client.PostAsync(url, content)

**Comment by lothrop** [comment]
What is `client`? `HttpClient`? `ModernHttpClient`?

**Comment by lothrop** [comment]
Can you replace your method's content with `await Task.Delay(TimeSpan.FromSeconds(5)).ConfigureAwait(false);` and see if it still blocks?

**Comment by Johan-dutoit** [comment]
It is `ModernHttpClient`.  

So I changed it to
    `public IMvxCommand LoginCommand => new MvxAsyncCommand(LoginAsync);`

and

    private async Task LoginAsync()
    {
            IsLoading = true;

            await Task.Delay(TimeSpan.FromSeconds(5)).ConfigureAwait(false);

            IsLoading = false;
    }

And the block is still there, but way shorter.  I just have a progress bar's visibility bound to the `IsLoading`.

**Comment by lothrop** [comment]
If you're using setting the `IsLoading` after the `await` you need to drop the `.ConfigureAwait(false)`.

**Comment by Johan-dutoit** [comment]
I've tried it both ways.  Are you able to reproduce it on your end?

**Comment by lothrop** [comment]
No. Which behavior are you seeing? How do you notice the UI is freezing? I'm supposing `IsLoading` is reflected in the UI? How long does it take for `IsLoading` to change?

**Comment by Johan-dutoit** [comment]
`IsLoading` just changes the visibility of a progress bar, but I removed that and just permanently displayed the progress bar (its a circle on android that keeps turning), when I click the login button, it stops turning (still visible), the button keeps it's active state (read highlighted) and then after a couple of seconds, it starts spinning again and the button is no longer active.

**Comment by lothrop** [comment]
Your use case is a very typical one and works in typical projects. I'm afraid I can't help without access to your project's code.

**Comment by Johan-dutoit** [comment]
What I can do is, is attempt to create a repro project and won't mind sharing that.

**Comment by suranyig** [comment]
Same problem here in my Xamarin.Forms project. The freezing occurs only in Android app, iOS works as expected. Decorating command execute code with await Task.Run(async ( )=> { ... }); helped me.

**Comment by Cheesebaron** [comment]
@suranyig if you have a sample that can reproduce this issue, please open a _new_ issue with details.
