### ISSUE TITLE
NotifyPropertyChanged on MvxAdapter is not marshalled to MainThread

### ISSUE THREAD

**Issue by CSkoubo** [MvvmCross/MvvmCross#1217]
For instance adding items to an observable collection on another thread. NotifyPropertyChanged will be called on incorrect thread.

```
[mvx] 123.11 Exception masked during Adapter RealNotifyDataSetChanged AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views.
[mvx] 	  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <filename unknown>:0 
[mvx]   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod) [0x00083] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1010 
[mvx]   at Android.Widget.BaseAdapter.NotifyDataSetChanged () [0x00058] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Widget.BaseAdapter.cs:345 
[mvx]   at Cirrious.MvvmCross.Binding.Droid.Views.MvxAdapter.RealNotifyDataSetChanged () [0x00000] in <filename unknown>:0 
[mvx]   --- End of managed exception stack trace ---
[mvx] android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
[mvx] 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6334)
[mvx] 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:873)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.support.v4.widget.DrawerLayout.requestLayout(DrawerLayout.java:1115)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
[mvx] 	at android.view.View.requestLayout(View.java:16754)
[mvx] 	at android.widget.AbsListView.requestLayout(AbsListView.java:1959)
[mvx] 	at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:814)
[mvx] 	at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6612)
[mvx] 	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
[mvx] 	at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
[mvx] 	at md595f4b8ab717b9da13f11267a86077f20.AwaitableOkHttp_OkTaskCallback.n_onResponse(Native Method)
[mvx] 	at md595f4b8ab717b9da13f11267a86077f20.AwaitableOkHttp_OkTaskCallback.onResponse(AwaitableOkHttp_OkTaskCallback.java:38)
[mvx] 	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
[mvx] 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
[mvx] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
[mvx] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
[mvx] 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by martijn00** [comment]
I've seen this a couple of times in my own apps. It might need some fixing.

**Comment by roubachof** [comment]
yup, i've experienced a lot of these too...
this could be linked to this: http://stackoverflow.com/questions/25416700/exceptions-while-using-mvxadapter

**Comment by martijn00** [comment]
Can you make a pull request for this?

**Comment by roubachof** [comment]
To tackle this, based on SO answer, we would need to dispose subscribed tokens when swaping MvxAdapter.
Basically we would add an "UnsubscribeFromItemSource()" method on MvxAdapter and MvxRecyclerAdapter.
Then, in the setter of MvxListView and MvxRecyclerView, before replacing the default adapter with the new one, we could call defaultAdapter.UnsubscribeFromItemSource().
I could do a pull request, but I have no sample code to validate against...

**Comment by martijn00** [comment]
If you do a PR i am sure some other people could give it a try!

**Comment by Cheesebaron** [comment]
I made a PR, now people can try ;)

**Comment by roubachof** [comment]
The issue mentioned by the SO thread is not really the same.
It's an event leak, when switching from an adapter to another, the old adapter continue to subscribe to the NotifyCollectionChanged event...

**Comment by slodge** [comment]
Y - @roubachof - separate issue - that one just suggests `null`-setting the `ItemsSource` on `existing` in https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Binding/Droid/Views/MvxListView.cs#L59 (for this one I've commented on the PR...)

**Comment by roubachof** [comment]
@slodge : but the old adapter will still be listening to the current item source https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Binding/Droid/Views/MvxAdapter.cs#L144 (even if its a weak reference, till the next GC, we're likely to have an exception when [NotifyDataSetChanged](https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Binding/Droid/Views/MvxAdapter.cs#L151) will be called)

**Comment by slodge** [comment]
... which is why setting it to null would help... look up to what would happen - line 131...

**Comment by martijn00** [comment]
This should probably also be fixed here: https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.RecyclerView/MvxRecyclerView.cs#L62

**Comment by roubachof** [comment]
@slodge ooh now I see...

**Comment by roubachof** [comment]
according to @slodge (http://goo.gl/0nW0L6) the view model should be responsible for raising collection changed events on the ui thread. 
A more descriptive warning has been added to help out the developer: 
https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Binding/Droid/Views/MvxAdapter.cs#L173
Maybe we should close this issue.

**Comment by Cheesebaron** [comment]
See https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues/125
