### ISSUE TITLE
MvvmCross Starter 4 Beta 8 - LinkerPleaseInclude use C# 6 String Interpolation

### ISSUE THREAD

**Issue by SergioZgz** [MvvmCross/MvvmCross#1221]
Hi guys :)

I have a very small problem with MvvmCross beta 8 (I dont know if in earlier this bug exists).

Using MvvmCross starter on droid project, add a LinkerPleaseInclude which use String Interpolation and when open that project on normal (not Roslyn) Xamarin Studio on windows this throw an error.

I fixed it changing string interpolation to non c# 6 "method" but maybe you could fix that.

If you think that this is not a bug just tell me and I close it. No problem :)

And thanks for doing MvvmCross ;)

**Comment by martijn00** [comment]
There is a bug in Xamarin Studio on Windows where this doesn't work correctly. If you update to the latest beta of Xamarin studio it will work again.

**Comment by SergioZgz** [comment]
Ok :+1:
