### ISSUE TITLE
Support for generic MvxAdapter<T>

### ISSUE THREAD

**Issue by joashmusyoka** [MvvmCross/MvvmCross#1222]
I am converting a listview that I had written earlier but my adapter is generic and so unable to extend MvxAdapter since it does not allow a type parameter.

Thanks.

**Comment by joashmusyoka** [comment]
I guess I should just create a new Adapater<T> and implements IMvxAdapter

**Comment by martijn00** [comment]
Maybe you could do something like the generics we have for MvxActivity: https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Droid/Droid/Views/MvxActivity.cs#L83

If you could add that to the current code and make a PR we would be happy to pull it in.

**Comment by joashmusyoka** [comment]
I will do something about it. Thanks.

On Thu, Feb 18, 2016 at 1:15 PM, Martijn van Dijk <notifications@github.com>
wrote:

> Maybe you could do something like the generics we have for MvxActivity:
> https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Droid/Droid/Views/MvxActivity.cs#L83
>
> If you could add that to the current code and make a PR we would be happy
> to pull it in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MvvmCross/MvvmCross/issues/1222#issuecomment-185638997>
> .
>



-- 
Kind Regards,
Musyoka.
