### ISSUE TITLE
UWP ShowViewModel Too Early

### ISSUE THREAD

**Issue by CalebMorris** [MvvmCross/MvvmCross#1223]
Hello, I am currently trying to create a UWP extension of a MvvmCross application that already exists.

I've noticed a bug on the UWP side that is kind of frustrating.
When attempting to use `ShowViewModel` too early UWP will just silently consume the request and trace it as if the transition actually occurred, but never actually transitions.
A simple example would be using `ShowViewModel` inside the constructor of another `ViewModel`. On iOS and Android this causes and immediate transition. UWP however never transitions.

I extended the sample TipCalculator project to demonstrate the problem.
https://github.com/CalebMorris/MvvmCross-Samples/tree/UWP_Constructor_Example
To see the expected behavior run the Android project and note that it transitions directly to the new "Test" view.
While on UWP the transition doesn't occur until the button I added is pressed.

If you wish to log against actual transitions vs Mvx tracing, you can attach a method to `rootFrame.Navigating` inside of `App.xaml.cs`.

Any help in rectifying this problem or a possible workaround would be greatly appreciated.

**Comment by Cheesebaron** [comment]
Don't do navigation in your ctor is the best solution.

**Comment by Stephanvs** [comment]
Consider calling ShowViewModel in a Init method

**Comment by Cheesebaron** [comment]
I would even say that using ShowViewModel is behavior and should actually happen in a Command.

**Comment by CalebMorris** [comment]
It is the same behavior if you wrap the `ShowViewModel` in a command (shows is able to execute and executes).
Same behavior inside of `Start` as well as `InitFromBundle`.
@Stephanvs For `Init` were you referring to `InitFromBundle` or another method?

**Comment by dersia** [comment]
Hi I ran into the same issue. @Cheesebaron There is a valid case for this, I have for example an ExtendedSplashScreen and am doing a lot of init stuff and afterwards I would like to transit to the chosen Page.

Did you find some workaround?

**Comment by alexsorokoletov** [comment]
Probably related to the problem we got on UWP (http://stackoverflow.com/questions/15739996/frame-navigation-in-xaml-return-false)
```
var result = RootFrame.Navigate(viewType, requestText); //Frame won't allow serialization of it's nav-state if it gets a non-simple type as a nav param
if (!result)
{
    MvxTrace.Trace("Navigation didn't work, probably you are inside OnNavigatedTo http://stackoverflow.com/a/15743739/883738");
    CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () => RootFrame.Navigate(viewType, requestText));
}

```

Not the best solution cause in this case crash during navigation is not being handled.
