### ISSUE TITLE
Support of converter chaining with fluent binding

### ISSUE THREAD

**Issue by bspinner** [MvvmCross/MvvmCross#1226]
There's no support of converter chaining with fluent binding.

~~I'm going to implement it~~ (edit: ouch). First idea that came to mind (all parameters left out for clarity; they should stay the same):

``` csharp
set.Bind().WithConversion().WithConversion();
```

First obvious problem: how to handle fallback values? Normally one could do

``` csharp
set.Bind().WithConversion().WithFallback()
```

Will it be sufficient to accept only one fallback per binding, so one converter fails we'll use that general fallback value OR do we need support for something like this:

``` csharp
set.Bind().WithConversion().WithFallback().WithConversion().WithConversion().WithFallback()?
```

edit: just reread the docs. [According to them](https://github.com/MvvmCross/MvvmCross/wiki/Value-Converters#valueconverters-and-fallbackvalues), one general `WithFallback` should be sufficient?

And: anyone having a distaste for/completely against this? why?

**Comment by MKuckert** [comment]
+1

**Comment by Cheesebaron** [comment]
As I said on Slack, I think it is an interesting proposition. Although, I don't see a lot of use for it. I don't mind a PR for this.

Maybe first think of what kind of situations this would be useful in. Usually I use ValueConverters to convert to a platform specific value, rest is simply up to the ViewModel.

So I guess I am a bit skeptic, but not against it.

**Comment by PelleRavn** [comment]
+1
I agree that there isn't much cases where it would be needed. But I have though about it a few times, where it would have been nice to have. So, can't argue against the possibility to do it, in rare cases.

**Comment by bspinner** [comment]
Indeed, it'll be rarely needed (therefore it's not implemented yet, I guess). Depends a bit on code style, too (e.g. I've never needed ValueCombiners like `If` and `And` and try to avoid them).

One could argue that by enabling converter chaining new people using Mvx could be more easily blundered into misusing converters for logic that should be in viewmodels...? Hmhm.

**Comment by azchohfi** [comment]
+1 to this!
Imagine, for example, a string format converter chained to a ToUpper converter. I would use this. Many times I had to make a custom converter specific for only one use case.

**Comment by bspinner** [comment]
One thing I don't like about this: it's breaking the current fluent-syntax.
Though one can call all fluent methods multiple times, all of them don't add anything up or similar, but overwrite everything the previous call would have done.

For example `Bind().To().To()` won't lead to a double binding, instead the first `To()`-call won't have any effect. Same with `For()`, `WithFallback()` etc. So a method like `WithConverter*s*` may be wise instead of changing the behaviour of `WithConverter`...

@lothrop Any ideas on this?

**Comment by MKuckert** [comment]
Or add an AndWithConversion method...
Maybe the binding should not be changed at all and a ChainedConverter with the specified behavior should be written instead.

**Comment by bspinner** [comment]
`AndWithConversion` would allow only one additional Converter, not "infinite".

**Comment by lothrop** [comment]
I've had a project where the ViewModel just contained legacy models and I had to do a lot of adaptions when binding. It's not optimal since you'll have to implement this logic for each platform.

I like multiple `WithConversion()` instead of a `WithConversions(params)`. Any idea how this would work with declarative bindings?

**Comment by bspinner** [comment]
@lothrop By "declarative bindings" you mean those like in android? Should be already possible:
https://stackoverflow.com/questions/18019042/is-chaining-converters-possible-in-mvvmcross

**Comment by cfin-mt** [comment]
Has this been implemented yet? I just tried it and it built fine but did not seem to apply the converters correctly.

**Comment by bspinner** [comment]
@cfin-mt Nope, sorry. Back then I solved it with a proper property in the viewmodel and went on with other stuff.
By now I'm skeptic whether we should implement this at all.

**Comment by nickrandolph** [comment]
@bspinner any further thoughts on whether we should continue work on this?

**Comment by bspinner** [comment]
At this point of time I'd say we can scrap this idea.
Haven't need it since back then.

Worst case could be people starting to use this in cases where a better prepared property would have been the better choice. 

So: close this. :)

**Comment by nickrandolph** [comment]
If someone wants to take charge of this feature we can reopen this issue - closing for now.

**Comment by Oleh-Kosiakov** [comment]
Just though it won't be bad idea in case if we need to use some built-in value converters like "Visibility".
For example for toggling visibility of two items on the view, something like:

bs.Bind(inetConnectedIcon).For(v => v.Visibility).To(vm => vm.IsConnected).WithConvervsion("Visibility");
bs.Bind(inetDisconnectedIcon).For(v => v.Visibility).To(vm => vm.IsConnected).WithConversion("BoolInverter).**WithOneMoreConvervsion("Visibility");**
