### ISSUE TITLE
Possible bug with ImageView droid binding.

### ISSUE THREAD

**Issue by robertbaker** [MvvmCross/MvvmCross#1227]
https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Binding/Droid/MvxAndroidBindingBuilder.cs

Shouldn't `registry.RegisterCustomBindingFactory<ImageView>` be `registry.RegisterCustomBindingFactory<MvxImageView>` instead?

Same thing goes for MvxAutoComplete.

**Comment by robertbaker** [comment]
Same goes for AutoCompleteTextView.

**Comment by lothrop** [comment]
Does this cause any problems? If I look at https://github.com/MvvmCross/MvvmCross/blob/f7fcf18d960f578b851837f2aaaeb4d0e3b72364/MvvmCross/Binding/Droid/Target/MvxImageViewBitmapTargetBinding.cs the constructor takes `ImageView` and not just `MvxImageView`.
