### ISSUE TITLE
Links in ReadMe do not work

### ISSUE THREAD

**Issue by DavePilks** [MvvmCross/MvvmCross#1233]
Hi

Small issue. The links in the ReadMe point to www.mvvmcross.com and this doesnt work. It needs to be changed to mvvmcross.com. The same applies for the Docs

**Comment by PelleRavn** [comment]
I was about to post the same issue. My suggestion would have been to add www. to the host, so people won't think the domain doesn't work, since www. is still a pretty common way go to a domain.

**Comment by Cheesebaron** [comment]
@slodge can you make www. redirect to the naked one?

**Comment by martijn00** [comment]
Fixed by Stuart now.
