### ISSUE TITLE
No suitable method found to override

### ISSUE THREAD

**Issue by joashmusyoka** [MvvmCross/MvvmCross#1235]
I have the following piece of code where I want to create a value converter for visibility=hidden/visible instead of the default gone/visible.

``` c#
/// <summary>
    /// This is a value converter that puts a view into visible/invisible state instead of the default visible/gone
    /// </summary>
    public class VisibleInvisibleValueConverter : MvxValueConverter<bool, ViewStates>
    {
        protected override ViewStates Convert(bool value, Type targetType, object parameter, CultureInfo culture)
        {
            return value ? ViewStates.Visible : ViewStates.Invisible;
        }

        protected override bool ConvertBack(ViewStates value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value == ViewStates.Visible)
            {
                return true;
            }

            return false;
        }
    }
```

This seems to work on my machine but fails on our jenkins build server with message no suitable method to override.

I have tried many things with no success. What could I be doing wrong?

**Comment by joashmusyoka** [comment]
I do have another value converter in the core project which works well and does not throw that error on the build server

**Comment by JelleDamen** [comment]
Could you maybe provide some build error logs?

**Comment by joashmusyoka** [comment]
"E:\Jenkins\jobs\SalesForce App 1.14 Release - OnCommit\workspace\xamarin\MK.Solar\MK.Solar.csproj" (Clean;Rebuild;SignAndroidPackage;ExecuteStyleCop target) (1) ->
(CoreCompile target) -> 
  ValueConverters\VisibleInvisibleValueConverter.cs(13,39): error CS0115: 'MK.Solar.ValueConverters.VisibleInvisibleValueConverter.Convert(bool, System.Type, object, System.Globalization.CultureInfo)': no suitable method found to override [E:\Jenkins\jobs\SalesForce App 1.14 Release - OnCommit\workspace\xamarin\MK.Solar\MK.Solar.csproj]
  ValueConverters\VisibleInvisibleValueConverter.cs(18,33): error CS0115: 'MK.Solar.ValueConverters.VisibleInvisibleValueConverter.ConvertBack(Android.Views.ViewStates, System.Type, object, System.Globalization.CultureInfo)': no suitable method found to override [E:\Jenkins\jobs\SalesForce App 1.14 Release - OnCommit\workspace\xamarin\MK.Solar\MK.Solar.csproj]

    125 Warning(s)
    2 Error(s)

Time Elapsed 00:00:54.28
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure
Skipped archiving because build is not successful

**Comment by joashmusyoka** [comment]
That is the part that specifies the failure

**Comment by JelleDamen** [comment]
I don't see it. :(

**Comment by Cheesebaron** [comment]
Why don't you use the converter MvvmCross provides in the Visibility Plugin?

**Comment by SeeD-Seifer** [comment]
@Cheesebaron I believe he needs a converter to switch Visible/Invisible rather then Visible/Gone.

@joashmusyoka 
Have you recently migrated from one MvvmCross version to another? (you can try to delete **packages** folder locally to be sure no old packages referenced by mistake)
Do you have any other Converter in the Droid project?
Have you tried to comment Convert/ConvertBack methods? (just to check is the project compelling in that case)

I do have absolutely insane command line build error which happens randomly (including Jenkins), but for big iOS project (which complains about XIB files). I just add "empty" change to the file and make a new build.

**Comment by joashmusyoka** [comment]
Yes, I do have another converter in the droid project and it fails with the same message on Jenkins.

What baffles me is the fact that it works on my local machine. Could it be the version of xamarin.android?? On my machine its 4 and 3 on Jenkins.

I think I will read up the visibility plugin and try that.

**Comment by SeeD-Seifer** [comment]
@joashmusyoka These are two things I would do in your case:
1. Clone fresh project into another folder
2. Make a build from command line

If that works, then probably there are differences in environment (or not ;)

**Comment by joashmusyoka** [comment]
I had to move the converter to the core by creating my own android view states enum. And it works

**Comment by SeeD-Seifer** [comment]
just in case - this is not a proper solution

**Comment by joashmusyoka** [comment]
Of course it would fail if android changed the values of their view state enums. It's compromise ffor now

**Comment by joashmusyoka** [comment]
I also upgraded MVVM to the latest but that did not solve the problem and indeed I started getting linking errors so I went back and did as above

**Comment by SeeD-Seifer** [comment]
I just mean - this just a workaround to avoid actual bug fix (which is awful, indeed).

I have at least 3 Android specific converters, that should be in platform project. There could be a time, when you need Android converter too. And it probably won't compile by the same reason as now.

**Comment by joashmusyoka** [comment]
Yeah, so I have decided to keep the issue open until a proper soln is found

**Comment by joashmusyoka** [comment]
When I get some spare time I will do a small project to reproduce the problem.

**Comment by sumitmpathak** [comment]
I am too facing this issue, I don't know why but I update my Xamarin version to 4.2.0.695 and Xamarin Android is 7.0.1.2 
The error in all the Converter files that: 
> ValueConverters.abcValueConverter.Convert(int, System.Type, object, System.Globalization.CultureInfo)': no suitable method found to override
Can you please help me, I am struggling from last 2 days

**Comment by nmilcoff** [comment]
Closing this issue, as the last comment was added more than 1 year ago, and there's no enough information to say this is related to MvvmCross.
