### ISSUE TITLE
Shouldn't MvxWrappingCommand implement IMvxCommand?

### ISSUE THREAD

**Issue by willsb** [MvvmCross/MvvmCross#1240]
Since the parameter used in the call to `Execute(object parameter)` [is ignored anyway](https://github.com/MvvmCross/MvvmCross/blob/f7fcf18d960f578b851837f2aaaeb4d0e3b72364/MvvmCross/Core/Binding/ValueConverters/MvxWrappingCommand.cs#L60-L62), wouldn't it be good to have `MvxWrappingCommand` implementing IMvxCommand so we can call `Execute()` instead of `Execute(null)`? 

I can make a PR myself if this sounds like a good idea

**Comment by martijn00** [comment]
Sounds like an idea! I'll take a look at it if you make a PR.

**Comment by Stephanvs** [comment]
Maybe an idea to just make the argument optional rather than implementing a new class, that way it doesn't break any existing code, and it is easier to discover.

So you could just change the method signature to:

`public void Execute(object parameter = null)`

**Comment by willsb** [comment]
Excelent idea, @Stephanvs :)
