### ISSUE TITLE
Please make Close(IMvxViewModel viewModel) virtual in MvxFragmentCompatActivity class

### ISSUE THREAD

**Issue by AmandaUrsula** [MvvmCross/MvvmCross#1248]
Hi

Please can you make the  Close(IMvxViewModel viewModel) method virtual in MvxFragmentCompatActivity class so that it can be overridden to handle Close() called from the ViewModel .

**Comment by Cheesebaron** [comment]
This belongs in: https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues
