### ISSUE TITLE
Error inflating class Mvx.MvxListView

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross#1250]
After upgrading to MvvmCross version 4 I get the above error when inflating a view from a fragment. 

"Binary XML file line#1: Error inflating class Mvx.MvxListView". Didn't find class "Mvx.MvxListView on path...

I'm not quite sure how to proceed?

The fragment interits from MvxFragment (in MvvmCross.Droid.Support.V7.Fragging.Fragments).

The activity inherits from AppCompatActivity (in Android.Support.V7.App).

Minimum Android version is set to Android 2.3.

Target Android version is set to Android 5.0.

Any help would be appreciated.

Regards,
Erik

**Comment by Cheesebaron** [comment]
Yeah, someone broke Abbreviations, so use the fully qualified name for MvxListView.

**Comment by martijn00** [comment]
Or register it in the setup.cs in the AndroidViewAssemblies.

**Comment by erviem99** [comment]
I couldn't make it work in setup.cs so I used the fully qualified name instead.

But for some reason it appears that databinding is not working.

Neither for MvxListView nor the EditText I have on the same fragment.

I know you have made a lot of changes to fragments in v4 so maby I'm missing something else as well?

**Comment by Cheesebaron** [comment]
Can't reproduce your issue from: "But for some reason it appears that databinding is not working."

**Comment by CSkoubo** [comment]
Are you using the correct libs? We had similar issues in our project after upgrading. But we were referencing some wrong library - the correct one: MvvmCross.Droid.Support.V7.Fragging

**Comment by erviem99** [comment]
It appears that my activity should inherit from MvxAppCompatActivity instead of AppCompatActivity. I missed that one because it was in a different package from the rest of the fragging stuff on Nuget.

After this change databinding started working again and my fix in setup.cs also started working.

Thanks a lot for your help :-)
