### ISSUE TITLE
Mvx Resolve faile on Windows 10 ( UWP ) project.

### ISSUE THREAD

**Issue by RichieZhuang** [MvvmCross/MvvmCross#1255]
To help us fix your issue, please provide the information in the below template. 

Below is my repo Url.
https://github.com/EvaRichie/MySimpleMvvmCross

### Steps to reproduce

1. use the PCL project as core with .net 4 and xamarin on visual studio 2015 community version.

2. install MvvmCross 4.0 on nuget and add UWP ( 10586 version ).

3. converter code show below

```
var visibility = value == true ? MvxVisibility.Visible : MvxVisibility.Collapsed;
var nativeVisbility = Mvx.Resolve<IMvxNativeVisibility>();
return nativeVisbility.ToNative(visibility);
```

Mvx.Resolve can not resolve the native visibility but the same code works on wpf project.

### Expected behavior
Should convert to Windows.UI.Xaml.Visibility on UWP project.

### Actual behavior
Can`t convert to native project type ( Aka can`t resolve success. )

### Configuration

**Version:** 4.0.0

**Platform:** Windows UWP

**Comment by Cheesebaron** [comment]
Which Visibility plugin is loaded in your platform specific project? Does it have the bootstrap file installed?

**Comment by RichieZhuang** [comment]
Hello, thanks for response. i use the "MvvmCross.Plugin.Visibility": "4.0.0" but no bootstrap file installed.

**Comment by Cheesebaron** [comment]
OK so the problem is the missing bootstrap. It is what tells MvvmCross where to look for Interface implementations from Plugins.

So either do something like this in your Setup.cs file in a InitializeLastChance:

```
protected override void InitializeLastChance()
{
        base.InitializeLastChance();
        Mvx.RegisterSingleton<IMvxNativeVisibility>(new MvxWinRTVisibility());
}
```

Or you can add a bootstrap file with the following contents:

```
using MvvmCross.Platform.Plugins;

namespace $rootnamespace$.Bootstrap
{
    public class VisibilityPluginBootstrap
        : MvxPluginBootstrapAction<MvvmCross.Plugins.Visibility.PluginLoader>
    {
    }
}
```

Remember to replace `$rootnamespace$` with your namespace.

**Comment by RichieZhuang** [comment]
Thanks, my main problem is solved. but there`s second problem i faced with! the view-model with interface on constructor will fail to navigate.
