### ISSUE TITLE
[UWP] SplitView Navigation

### ISSUE THREAD

**Issue by domedellolio** [MvvmCross/MvvmCross#1257]
Hi guys, 
I'm using the splitview control in a windows universal application.
I've integrated the mvvm code (v 4.0.0)  as well explained here:
https://github.com/Depechie/MvvmCrossUWPSplitView

Everything works fine except for an aspect:
- back navigation within splitview 

Specifically, ShowViewModel method does not create an entry on a backstack when MvxWindowsMultiRegionViewPresenter is in action.
As a result, navigating from page A (home) to page B, within a splitview, and then clicking the back button the user exits from the app.

Last, we found same behavior in Android with MvxFragmentsPresent class.

Any idea? suggestion?

Platform: Android/Windows UWP

Thanks

**Comment by domedellolio** [comment]
Guys,
any clues?

**Comment by martijn00** [comment]
Some work on the example for this has been done in https://github.com/MvvmCross/MvvmCross-Samples/pull/32 Otherwise maybe @Stephanvs knows about this.

**Comment by martijn00** [comment]
A fix for closing views is added here: https://github.com/MvvmCross/MvvmCross/pull/1323

**Comment by domedellolio** [comment]
Hi @martijn00 I think that #1323 does not resolve the issue I explained

**Comment by ruudkobes** [comment]
It sounds like you're not handling the backrequested event in the view which contains the SplitView.
Do you have something like the code below in that view?

https://github.com/Depechie/MvvmCrossUWPSplitView/blob/master/MvvmCrossUWP.Win/Views/FirstView.xaml.cs#L37-L47
