### ISSUE TITLE
[UWP]Plugins PictureChooser PluginLoader can`t load

### ISSUE THREAD

**Issue by RichieZhuang** [MvvmCross/MvvmCross#1258]
Below is my repo Url.
https://github.com/EvaRichie/MySimpleMvvmCross

### Steps to reproduce

1.
Create core and UWP project and use nuget to install MvvM.Cross.Plugins.PictureChooser on both project.
2.
Manually add bootstrap cs file with code below.
```
public class PictureChooserPluginBootstrap
        : MvxPluginBootstrapAction<MvvmCross.Plugins.PictureChooser.PluginLoader>
    {
    }
```
3.
In app.xaml.cs file setup object can`t initialized! Throw could not load assembly for type MvvmCross.Plugins.PictureChooser.PluginLoader with MvxException.

### Expected behavior
Can load plugin.

### Actual behavior
Exception throw in setup object with initialize method.

### Configuration

**Version:** 4.0.0

**Platform:** Windows UWP

**Comment by Cheesebaron** [comment]
I don't see any PictureChooserPluginBootstrap class in your repo

**Comment by RichieZhuang** [comment]
Sorry i`m push to my repo yet. Please try again this time.

**Comment by martijn00** [comment]
Can you open this in the plugins repo? https://github.com/MvvmCross/MvvmCross-Plugins
