### ISSUE TITLE
Missing stylable field MvxExpandableListView_GroupItemTemplate

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#1265]
### Sample Repository

https://github.com/tbalcom/MvxBindingAttributes

### Steps to reproduce

1. Create a new Xamarin Blank App (Native Portable) Profile 111 solution.

2. Add MvvmCross Starter pack via NuGet.

3. Compile & run the Android program.  Observe error: Missing stylable field MvxExpandableListView_GroupItemTemplate at startup.

### Expected behavior
There should not be an error at program startup.

### Actual behavior
There is an error at program startup.

### Configuration

**Version:** 4.0.0

**Platform:** Android L.

**Comment by tbalcom** [comment]
I've also asked about this on Stackoverflow.  There is some more information available here: http://stackoverflow.com/questions/35899314/missing-stylable-field-mvxexpandablelistview-groupitemtemplate

**Comment by Cheesebaron** [comment]
![capture](https://cloud.githubusercontent.com/assets/249719/13945818/a1554eaa-f010-11e5-9acd-4e2500510894.PNG)

I can't reproduce.

**Comment by Dexyon** [comment]
@tbalcom @Cheesebaron  I have had the same problem this morning. I posted the solution (for now) on SO.

**Comment by Cheesebaron** [comment]
The problem must be that Xamarin Studio does not update the Resource.Designer.cs file properly or something. Works perfectly fine in Visual Studio latest stable Xamarin.

**Comment by tbalcom** [comment]
This issue is not resolved.  @Cheesebaron this is not a compiler error, but an `Mvx.Error` that shows up in Logcat when you run the Droid application.  I'm not using Xamarin Studio so I don't know where the idea that it's a Xamarin Studio issue is coming from.

**Comment by tbalcom** [comment]
Why does the MvvmCross 4.0 SQLite plugin define resources for MvvmCross?  You can see here the SQLite plugin is also defining the `MvxExpandableListView_MvxGroupItemTemplate` resource [here](https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/SQLite-PCL/MvvmCross.Plugins.Sqlite.Droid/Resources/Resource.Designer.cs#L122).  The demo solution doesn't make use of the SQLite plugin, so this doesn't explain the problem. This is just something I've noticed that seems very odd.

**Comment by Cheesebaron** [comment]
They are there because there is a reference to the Bindings.Droid project. It shouldn't actually be needed but is probably a leftover from something.
