### ISSUE TITLE
Mvvmcross picture chooser ios issue

### ISSUE THREAD

**Issue by vinodh06** [MvvmCross/MvvmCross#1275]
Hi,
I have implemented picture chooser in my iOS project.When i choose image from phone for first time it works and after that it doesn't set/bind the image to imageview.It shows warning as "MvxImagePickerTask called when task already active[0:] ".
Please help me to fix the problem.
Thanks.

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template. Closing it for now until actual details are provided.
