### ISSUE TITLE
Suggestion for a Mac presenter for MvvmCross

### ISSUE THREAD

**Issue by PelleRavn** [MvvmCross/MvvmCross#1278]
Hi peeps

Since Xamarin recently launched a new price model on their products, and therefore made the Mac platform easier to develop for (looking at a price-point perspective), I started looking into MvvmCross on the Mac platform. I've dove some development on the Mac previously, with "normal" Objective-C/Xcode, so I kinda knew the platform.
There were some things that was pretty confusing in the to-do to make MvvmCross work, but that's for another issue, another time.

So, I started making some tests to see how it functioned, and got stuck pretty fast, when I got to use the "Close(this)" method in the ViewModel, because it did nothing but tell me "Sorry - don't know how to close a view!".
After looking into the code, I totally get why it didn't: Nothing was implemented.
https://github.com/MvvmCross/MvvmCross/blob/f7fcf18d960f578b851837f2aaaeb4d0e3b72364/MvvmCross/Mac/Mac/Views/Presenters/MvxMacViewPresenter.cs#L107

Okay, so I decided to make my own presenter to make development a little easier, with some basic navigation stuff (changing the way it presents a View Controller, and how to "Close" it again, and go back to the previous View Controller) so it kinda behaves like the way iOS (, Android and Windows Phone) handles navigation with a "NavigationController". One thing lead to another, and extended it to support new windows, Modals and Sheets.

It's now at a point, were it works pretty well (still a prototype/work-in-progress though), and could actually be useful as a "basic navigation presenter" in a new Mac application, that are already known from MvvmCross on other platforms.

So I wanted to get your opinion on this. Is it actually useful? And is it useful to the MvvmCross framework for the Mac platform?
It might not the all of the currently implemented features that goes for the main repo (maybe only a subset of them) depending on your feedback.
If it turns out to be useful, I'll gladly keep working on it, to make it PR ready, when it's closer to finished and tested.

I created a Github repo with a demo to show how it behaves, and to see the code for the presenter: https://github.com/PelleRavn/MvvmCrossMacPresenterDemo
(The presenter: https://github.com/PelleRavn/MvvmCrossMacPresenterDemo/blob/master/MvxTest.Mac/MvxPrototypeMacViewPresenter.cs)

Few disclaimers on the demo:
1. It's a prototype. There might be bugs, and there may be use cases I haven't though of yet, that should be handled
2. It's not perfectly written at this state. Optimizations and memory leaks may be there for fixing
3. The iOS and Android projects in there for no good reason, so you can ignore them. Was only to make sure I didn't conflicted with anything

Thanks.

**Comment by martijn00** [comment]
I think it would be good to replace the current presenter with yours! Maybe @lothrop has an opinion on this, since i think they used it in a project.

**Comment by lothrop** [comment]
I'd be happy about a pull request. We haven't used Xamarin.Mac with MvvmCross yet.
