### ISSUE TITLE
StarterPack for Android doesn't include mipmap/icon

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#1282]
To help us fix your issue, please provide the information in the below template. 
### Steps to reproduce
1. Create a new Android project
2. Add MvvmCross.StarterPack nuget package
3.  Delete the default Activity from Xamarin.
4. Build.
### Expected behavior

Successful build
### Actual behavior

There's an error:

```
1>C:\Projects\EugsClient\EugsClient.Android\obj\Debug\android\manifest\AndroidManifest.xml(8): error APT0000: No resource found that matches the given name (at 'icon' with value '@mipmap/icon').
```

The mipmap icon is not included in the starter pack.

``` csharp
[Activity(
        Label = "EugsClient.Android"
        , MainLauncher = true
        , Icon = "@mipmap/icon" // **RIGHT HERE**
        , Theme = "@style/Theme.Splash"
        , NoHistory = true
        , ScreenOrientation = ScreenOrientation.Portrait)]
    public class SplashScreen : MvxSplashScreenActivity
    {
        public SplashScreen()
            : base(Resource.Layout.SplashScreen)
        {
        }
    }
```
### Configuration

**Version:** 4.0.0

**Platform:** Android

**Comment by martijn00** [comment]
What version of XS or VS are you on? In the newer version of them a mipmap is used instead of a drawable, which is why we switched this. See https://github.com/MvvmCross/MvvmCross/pull/1236

**Comment by kjeremy** [comment]
Latest xamarin stable. Vs 2015 update 2.

**Comment by martijn00** [comment]
And you get a drawable instead of a `mipmap` icon?

**Comment by kjeremy** [comment]
Correct.

**Comment by kjeremy** [comment]
My guess is this is a difference with XS vs VS.

**Comment by kjeremy** [comment]
I filed a bug with Xamarin about the difference between their XS and VS templates.  See https://bugzilla.xamarin.com/show_bug.cgi?id=40168

**Comment by lothrop** [comment]
Should we close this?

**Comment by kjeremy** [comment]
I don't think so.  The starter pack still fails under VS.

**Comment by alvidaIsHere** [comment]
still having this error with VS2015 update3

**Comment by Cheesebaron** [comment]
I don't think the Starter Pack should continue to live on. Instead people should use the Xamarin Studio and Visual Studio templates that @jimbobbennett made. Content in NuGet packages is strange.

**Comment by JorgeMadson** [comment]
I still getting this error.
There are two errors in AndroidManifest.xml
To fix one i had to go to Android Properties > Android Manifest > Application Icon > Change it to @drawable/Icon.
But still getting other error on the activity android icon ("@mipmap/icon")

**Comment by balazsbonis** [comment]
I was also getting this exact same error message, but managed to get around it by manually creating a folder called mipmap-hdpi under the Android project's Resources folder, and moving the Icon.png file there from drawable.

I don't know if I'm going to break something down line making such rabid moves.

**Comment by kjeremy** [comment]
The issue is that xs generates the mipmap but vs does not. This is a
discrepancy in the xamarin Android templates.  If you are building with vs
just change mipmap to drawable and it will work.

**Comment by Beniamin-Lucaciu-Eklos** [comment]
each mipmap- YYYYhdpi/Icon.png missing this image ! search for it on github for it.

**Comment by martijn00** [comment]
Nuget doesn't support files/content anymore.
