### ISSUE TITLE
Failed to resolve System.Boolean

### ISSUE THREAD

**Issue by joashmusyoka** [MvvmCross/MvvmCross#1289]
I upgraded MvvMcross Nugets to 4.1.0 and now I am getting the following error:

C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1502,5): error MSB4018: Xamarin.Android.XamarinAndroidException: error XA2006: Refere
nce to metadata item 'System.Boolean Android.OS.BaseBundle::GetBoolean(System.String,System.Boolean)' (defined in 'MvvmCross.Droid.Support.V7.Fragging, Version=1.0
.0.0, Culture=neutral, PublicKeyToken=null') from 'MvvmCross.Droid.Support.V7.Fragging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolve
d. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Boolean Android.OS.BaseBundle::GetBoolean(System.String,System.Boolean)

Not sure if its an MvvmCross issue or a Xamarin.Android platform problem

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template. Closing it for now until actual details are provided.

**Comment by KevinPou** [comment]
I am running in the same issue with the Droid.Shared app. I see the TargetFramework is set to v.6.0 in the project. Issue is not many devices support this API level. I have an app which ran API 21 and 22 and after upgrading to MVVMCross v.4 I was getting the same errors. Now my customer requires an older tablet which stands around API 21 (Android v.5.0) and I can't build against it :(
