### ISSUE TITLE
iOS EntryElement binding problem (revised)

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross#1291]
Assigning the EntryElement.Value (from CrossUI.iOS.Dialog.Elements) property directly will not trigger an update in the viewmodel.
### Steps to reproduce
1. Create a new empty iPhone project in Visual Studio 2015 Community Edition 
2. Add Nuget package MvvmCross.StarterPack 4.1.0 to main project and Core project
3. Add Nuget package MvvmCross.Dialog to main project
4. Change Setup class to inherit from MvxIosDialogSetup
5. Create a new FirstView class that inherits from MvxDialogViewController
6. Add a Root to the new view that has a EntryElement and a StringElement and bind the two to the viewmodel's Hello property
7. Add a NavigationItem button that assigns the EntryElement.Value property when Clicked
### Expected behavior

When the button is clicked the text in both the EntryElement and the StringElement should change to the assigned value
### Actual behavior

Only the text in the EntryElement is changed
### Configuration

**Version:** 4.1.0

**Platform:** iOS 9.3

I have attached a small git repo to demonstrate the problem here: https://github.com/erviem99/MvvmCrossBindingDemo

**Comment by kjeremy** [comment]
CrossUI has been removed as of 41f191574d11e6e1a664336e7108cfa1e59a4383
