### ISSUE TITLE
continuous integration and pre-release builds

### ISSUE THREAD

**Issue by ghuntley** [MvvmCross/MvvmCross#1301]
When https://github.com/reactiveui/ReactiveUI/pull/1092 closes it would be kinda neat to rip out the CICD pipeline from ReactiveUI and implement it here in MvvmCross. Assign this issue to @ghuntley

**Comment by mufid** [comment]
Any update on this?

**Comment by Cheesebaron** [comment]
I've talked to the Bitrise guys, they only support Android and iOS currently and they didn't say much about adding support for more platforms in the future. They say their stuff is best with creating apk/ipa's as outcome of the build and not dll's as we do now. They are looking into our current build issues on their system. I showed them at Evolve the errors we get etc.

**Comment by ghuntley** [comment]
RxUI is going down the path of Bitrise for testharness (android, ios) to running unit tests and AppVeyor for building _everything_. It's the only way to do packaging in a sane maner. @mufid I'd love to rip the RxUI pipeline out of there and implement here - you just have to wait a little longer.

**Comment by ferrydeboer** [comment]
Since Tamarin support TeamCity also maybe http://codebetter.com/codebetter-ci/ is worth considering. While TC imo offers most flexibility it does require more effort setting it up. I personally still prefer this over a simple setup where you have much less control over the quality.

**Comment by ghuntley** [comment]
Not that keen on CodeBetter. The complexity isn't with the vendor of CI
services, it's with just how hard it is to target this many platforms and
package put the end results. Additionally the only way to do proper
validation is release builds on physical devices as the linker does not run
on iOS simulator etc.

**Comment by ferrydeboer** [comment]
Do you mean that because Bitrise has the infra in place to (amongst others) build on iOS it takes away a lot of the complexity for setting up the pipeline?

**Comment by ghuntley** [comment]
@ferrydeboer unless builds are done on a single worker then packaging up the artifacts becomes fragile/difficult. BitRise is perfect for running the Android, Mac and iOS test harnesses to validate unit tests but not useful for packaging as it cannot target WPA/WPF/UWP. AppVeyor is perfect for packaging but cannot run the Mac/iOS test harnesses.

The RxUI PR was merged today, the project now has continuous builds to MyGet which means Mvx draws near - want to polish up the script some more first before proceeding.

**Comment by ghuntley** [comment]
RxUI (and MvvmCross) blocked/waiting for https://twitter.com/IfErrThrowBrick/status/764188808627625984 to be promoted from Alpha to Stable channel.

![](https://developer.xamarin.com/releases/vs/xamarin.vs_4/xamarin.vs_4.2/xamarinmac.png)

**Comment by ktngoykalolo** [comment]
Hello I see this thing is marked up for grabs. what are the requirements for the CI pipeline exactly ?

**Comment by Cheesebaron** [comment]
In short: Build all repositories and produce releasable NuGet packages.

**Comment by ktngoykalolo** [comment]
is there a specific tool that you guys want to use ?

**Comment by Cheesebaron** [comment]
Well if you are going to build Xamarin.Mac the MvvmCross projects only build on Mac currently. So preferably somewhere, where you can provide your own build agents.

Going to look into Mobile Center from MS soon. In general most CI systems work fine.

As for build scripts, Cake or Fake would be great.

Although, I would maybe wait a bit till we have discussed #1500

**Comment by ktngoykalolo** [comment]
yes, Mobile Center might be a good option.

**Comment by Cheesebaron** [comment]
Hmm looks like Mobile Center is mainly for Apps and not libraries which produce nuget packages, similar to what Bitrise does.

**Comment by ktngoykalolo** [comment]
and what about VS Team Services ?

**Comment by Cheesebaron** [comment]
VSTS, TeamCity, Jenkins, Bamboo all green from here. I can provide a couple of build agents if needed.

**Comment by ktngoykalolo** [comment]
nice then.

**Comment by ghuntley** [comment]
I'd encourage you to look at the ReactiveUI CI scripts as it will save you a heap of time. Contains build, automatic versioning,  release workflow, release notes generation etc. 

Additionally use AppVeyor which now works for all platforms as long as you are generating a MSIL.

Right now the core problem that needs solving is how to automatically release mvvmcross on every commit to MyGet across multiple repos. My vote is to merge all repos back into single repos and throw away the notion of plugins being a separate unit. It's just mvvmcross; a change to core is a new alpha, so is to the plugins.

**Comment by ktngoykalolo** [comment]
I will look into ReactiveUI. I saw the discussion about merging all of the repos, I am leaning more towards keeping all of the repos separate.

**Comment by ghuntley** [comment]
The key is to treat everything as a collective releasable unit that shares the same version and that version is pinned. if the decision is made to keep everything as separate repos then I suppose you could achieve the later by adjusting the bootstrap to clone all repos and any commit in any upstream repo triggers build of everything.

**Comment by ktngoykalolo** [comment]
yes indeed. if you merge all the repos, aren't they going to get too big ?

**Comment by ghuntley** [comment]
No, that's not a valid reason for not merging. Technicality Git can handle repos in the many GB size.

**Comment by kjeremy** [comment]
I wouldn't worry about the size so much.  The one big issue I see with merging everything into one repo is that a critical commit to fix a crash in the file download plugin causes a new release of **everything**.  Still that may not be a big deal if we have a CI system set up.

**Comment by ktngoykalolo** [comment]
no but the nuget packages resulting from that repos ? the binaries themselves

**Comment by ghuntley** [comment]
@kjeremy treat mvvmcross for that it is. Ruby on rails.a single commit to plugins should yield a new release. That release should constrain all dependencies or nuget packages to that particular version. This will make your life as an open source maintainer so much better. Now a release doesn't have to be released on nuget. ResctiveUI uses gitflow without support branches. Just develop and master. When a commit lands on develop that's a new release to myget. Every now and then the core group decides to do a pull request from develop to master and that tags the repo and triggers a release to nuget.

**Comment by ktngoykalolo** [comment]
nice approach

**Comment by kjeremy** [comment]
@ghuntley Right.  I don't think my concern is that big of a deal once we have a working CI system.

**Comment by ghuntley** [comment]
Agreed. When the product is versioned as a collective unit the question of which version are you running becomes a single answer. Tell the consumer to upgrade to latest version of the product (not product plus add-in plus Android support ugh) managing versioning of  dependencies sucks for the maintainer and is equally confusing for consumers who lack the project domain knowledge. 

Happy to jump on a video chat and share experiences. I've spent the last 8 months mulling over and implementing  this stuff. Lot's of failure on the way to success. It seems simple at first but it's not. Lot's of little subtleties such as amount of platforms, some platforms only build on certain CI hosts, versioning, release workflow, issue mgmt and PR approvals.

**Comment by Cheesebaron** [comment]
> no I mean the nuget packages resulting from that repos ? the binaries themselves

No nothing will change in how the NuGet packages are released.

**Comment by Cheesebaron** [comment]
CI is up and running

**Comment by ghuntley** [comment]
Nice.

**Comment by Dexyon** [comment]
@Cheesebaron Nice work !

**Comment by Cheesebaron** [comment]
CI build now dumps NuGets on MyGet for the develop branch here: https://www.myget.org/F/mvvmcross/api/v2

**Comment by Cheesebaron** [comment]
Now we only need it to make Git Releases.
