### ISSUE TITLE
Improvement to pass Complex Dto between ViewModels

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross#1302]
I just created these extensions methods which allows me to easily pass any serializable dto between ViewModels...
```

public static class MvxBundle_Extension
    {
        public static void Write(this IMvxBundle bundle, string paramName, object obj)
        {
            IMvxJsonConverter serializer;
            if (!Mvx.TryResolve(out serializer))
            {
                Mvx.Trace("Could not resolve IMvxJsonConverter, it is going to be hard to initialize with custom object");
                return;
            }
            string json = serializer.SerializeObject(obj);
            bundle.Data.Add(paramName, json);
        }

        public static T Read<T>(this IMvxBundle bundle, string paramName)
        {
            IMvxJsonConverter serializer;
            if (!Mvx.TryResolve(out serializer))
            {
                Mvx.Trace("Could not resolve IMvxJsonConverter, it is going to be hard to initialize with custom object");
                return default(T);
            }
            string json = "";
            bundle.Data.TryGetValue(paramName, out json);
            return serializer.DeserializeObject<T>(json);
        }
    }
```

I'm wondering, why MvvmCross doesn't currently provide something similar to these methods?
Maybe, there is some serious drawback in this approach, which I'm not aware of... 

Using these extensions, I can pass easily pass lists and other complex dto to another viewmodel by writing it to the bundle...
```
List<Guid> list;
... // add items to the list... 
bundle.Write("dto1", list);
ShowViewModel<TestViewModel>(bundle);
...

```
And eventually, read it back...
```
        protected override void InitFromBundle(IMvxBundle parameters)
        {
            base.InitFromBundle(parameters);
            List<Guid> list = parameters.Read<List<Guid>>("dto1");
        }



```

**Comment by martijn00** [comment]
This is already possible: https://github.com/MvvmCross/MvvmCross/pull/1284

I appreciate the effort to write this down!

**Comment by IlSocio** [comment]
Cool! Thanks Martijn, I'll take a look!

**Comment by IlSocio** [comment]
Hi Martin... Eventually I took some time to look at the new ViewModel<TInit>

Imho it worths to include the extensions methods too.
The ViewModel<TInit> implementation allows you to pass only 1 single complex parameter.

Using the extension methods, you can pass multiple complex parameters among with any other simple parameter.
And both the simple and complex parameters can be written and read using the very same syntax.
bundle.Write("param1", veryComplexDto);
bundle.Write("param2", true);
bundle.Write("param3", anotherComplexDto);
