### ISSUE TITLE
MvxTapGestureRecognizerBehaviour with CancelsTouchesInView

### ISSUE THREAD

**Issue by promontis** [MvvmCross/MvvmCross#1303]
Currently using the MvxTapGestureRecognizerBehaviour by use of:

`bindingSet.Bind(tagField.Tap()).For(tap => tap.Command).To(vm => vm.ShareWithCommand);`

The extension method Tap() has two optional parameters, namely:
1. numberOfTapsRequired
2. numberOfTouchesRequired

I would like to suggest to add a parameter for the CancelsTouchesInView property the underlying UITapGestureRecognizer has. Also optional with a default value of True (which is the default value for UITapGestureRecognizer as well). 

Anyone that objects to this suggestion?

**Comment by martijn00** [comment]
Thanks!
