### ISSUE TITLE
System.InvalidCastException on Android

### ISSUE THREAD

**Issue by SOFSPEEL** [MvvmCross/MvvmCross#1305]
My Android App is crashing in the field as follows, our crash reporting AppTelligent tool dumps the following stack.

0   System.InvalidCastException: Specified cast is not valid.
1   at .System.InvalidCastException : Specified cast is not valid.()
2   at . at ACS.FundRaising.Android.MainActivity.get_ViewModel () [0x00006] in <filename unknown>:0 ()
3   at . at ACS.FundRaising.Android
.MainActivity.OnResume () [0x00006] in <filename unknown>:0 ()
4   at . at Android.App.Activity.n_OnResume (IntPtr jnienv, IntPtr native__this) [0x00009] in <filename unknown>:0 ()
5   at . at (wrapper dynamic-method) System.Object:0f33e485-66a7-4a1f-a4cf-43d220427f7e (intptr,intptr)()

Note that the get_ViewModel code is standard Mvx boilerplate as follows:
<img width="468" alt="2016-04-24_1850" src="https://cloud.githubusercontent.com/assets/1612646/14772025/bf1d7c12-0a4d-11e6-85dd-f5c8f059ccd3.png">

Note too that the above crash not only happens onResume as shown above, but there are variants of this crash OnPause, OnStart, etc.

This crash I believe only started when we upgraded to MVVMCross 4.0 

My experience with weird crashes like this one, is that they occur then an activity is tombstoned (i.e. when the activity is saved away and then later restored because of memory pressure but I have no real evidence that this is the case for this particular crash so I thought I'd just throw it out there.

One other thing, since this only occurs on MainActivity,which "is a" MvxAppCompatibilityActivity I thought I'd list the ways that MainActivity is brought to life:

<img width="606" alt="2016-04-24_1905" src="https://cloud.githubusercontent.com/assets/1612646/14772152/971c9ee4-0a4f-11e6-8432-643ab759d82b.png">

<img width="492" alt="2016-04-24_1904" src="https://cloud.githubusercontent.com/assets/1612646/14772145/714ea798-0a4f-11e6-8c7e-660a656b6faa.png">
### Steps to reproduce

So far I have not been able to reproduce, but its definitely happening in the field per our crash reports, about 10 of them total.
### Expected behavior

Shouldn't crash.
### Actual behavior

Crashes.
### Configuration

**Version:** 4.0.0

**Platform:** Android

**Comment by SOFSPEEL** [comment]
For completeness thought I'd add this too:

<img width="424" alt="2016-04-24_1911" src="https://cloud.githubusercontent.com/assets/1612646/14772220/77a361be-0a50-11e6-96ad-ef550244bcad.png">

**Comment by Dexyon** [comment]
I don't have any problems with this. But we only see a portion of your code. It is hard to evaluatie based upon some screenshot.

First question. Why do you do the casting yourself? And not use the typed MvxViewModel<T> instead?
Other question. Can you see that type the ViewModel is before it crashes?

**Comment by SOFSPEEL** [comment]
Answer to first question: Although I agree with you that the typed view model is more elegant you do realize that the typed view model does result in the **exact** same code for the VM get and set. See MvxMvxAppCompatActivity code below.

Second question answered: We can't see the type of the VM before it crashes, because this only happens in the field, so its not like I can breakpoint there before the crash occurs. Having said that you did give me an idea, which is I can have AppTeligent lay down a breadcrumb on the VM get, to determine the type of the base.ViewModel, that will probably help in debugging this further. That of course will take a full release cycle (i.e. publishing the app again, etc.) before this problem can be figured out.

As for the lack of code I supplied, is because the crash involves a small set of code. Literally, all we're doing is a ViewModel.Blah in OnResume, and then we get that crash stack. That code works 99% of the time, but in some cases on deployed Android app's in the play store (i.e. I used the term field above) that unexplainable InvalidCastException occurs.

 
![2016-04-25_0705](https://cloud.githubusercontent.com/assets/1612646/14786549/4645154a-0ab4-11e6-8884-bdcc0e0f4cc8.png)

**Comment by Cheesebaron** [comment]
Have never seen this in any of my apps. I can't reproduce this on my end either. I have no idea what is going on.

**Comment by tbalcom** [comment]
I've recently observed the same error.  The problem was first encountered after releasing the first version of the app built from MvvmCross 4.x.  The new version has been in production for a week but this exception has only happened 3 times across all users.

The stack trace:
```
System.InvalidCastException
Specified cast is not valid.
  at (wrapper castclass) System.Object:__castclass_with_cache (object,intptr,intptr)
  at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatActivity`1[TViewModel].get_ViewModel () [0x00006] in <filename unknown>:0 
  at Dispatch.Droid.Views.BaseView`1[T].OnAttachedToWindow () [0x00030] in <filename unknown>:0 
  at Android.App.Activity.n_OnAttachedToWindow (IntPtr jnienv, IntPtr native__this) [0x00009] in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:562b2fdc-d138-432a-9d7e-1469a49fa042 (intptr,intptr)
```

The BaseView class looks like this:
```public abstract class BaseView<T> : MvxAppCompatActivity<T> where T : BaseViewModel```

The BaseViewModel class looks like this:
```public class BaseViewModel : MvxViewModel```

I'm doing some pretty standard Toolbar stuff in `BaseView.OnAttachedToWindow`:
```
public override void OnAttachedToWindow()
{
    base.OnAttachedToWindow();
    var toolbar = FindViewById<Android.Support.V7.Widget.Toolbar>(Resource.Id.toolbar);
    if (toolbar != null)
    {
        SetSupportActionBar(toolbar);
        SupportActionBar.SetDisplayHomeAsUpEnabled(SetDisplayHomeAsUpEnabled);
        if (!string.IsNullOrEmpty(ViewModel.Title))
            SupportActionBar.Title = ViewModel.Title;
        if (!string.IsNullOrEmpty(ViewModel.Subtitle))
            SupportActionBar.Subtitle = ViewModel.Subtitle;
        _titleToken = ViewModel.WeakSubscribe(() => ViewModel.Title, OnTitleChanged);
        _subTitleToken = ViewModel.WeakSubscribe(() => ViewModel.Subtitle, OnSubtitleChanged);
    }
}
```

**Comment by Cheesebaron** [comment]
Not sure how to fix this issue at all. Maybe involving someone from Xamarin which knows about this stuff could help? Maybe it is a bug in Mono?

**Comment by kjeremy** [comment]
Since it's crashing in get_ViewModel which (is virtual?) you may need to implement the JNI ctor in your activity or something.

**Comment by SOFSPEEL** [comment]
I am the original filer of this bug, and have now collected extra information from the live app, thru AppTeligent (formerly Crittercism).

The instrumented code now reveals that in crash scenarios MainActivity's VM is FundraisingViewModel instead of MainViewModel.

So I can confirm that in my code I'm **never** explicitly setting MainActivity.ViewModel. So then the question is how is the wrong VM getting set there? Which leads me to the following question. In my Custom Android ViewPresenter, I have the following code, to cleartop of MainActivity. I'm wondering if this code could somehow possibly lead to the wrong ViewModel on the MainActivity. 

            var intent = new Intent(Activity, typeof(MainActivity));
            intent.AddFlags(ActivityFlags.ClearTop);
            Activity.StartActivity(intent);

This is the output from the instrumented code in a crash:
![image](https://cloud.githubusercontent.com/assets/1612646/15748246/f441393e-2892-11e6-959e-3fcd466ab235.png)

This is the new instrumented code:
![image](https://cloud.githubusercontent.com/assets/1612646/15748286/2e40ccd0-2893-11e6-97b7-7c21cc807fb4.png)

**Comment by kjeremy** [comment]
Please post your activity, viewmodel and presenter code or put a repro case on github that we can get at.  Right now we don't have enough code to help you.  I suspect you're doing something odd in your custom presenter.  Simply calling `Activity.StartActivity` won't be enough but we can't tell you without your activity, viewmodel and presenter code.

**Comment by alexsorokoletov** [comment]
I am seeing same crash in production in one of our apps. We're using 4.4.0 and I also have no idea how we can track the error since we can't reproduce it in dev.

Happens on Samsung with 4.4.4 and on Xiaomi Redmi 2 with 5.0.2

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.InvalidCastException: Specified cast is not valid.
  at (wrapper castclass) System.Object:__castclass_with_cache (object,intptr,intptr)
  at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatActivity`1[TViewModel].get_ViewModel () <0x59988420 + 0x00033> in <filename unknown>:0 
  at *.SDK.Core.Android.BaseActivity`1[TViewModel].get_Context () <0x599883e0 + 0x00013> in <filename unknown>:0 
  at *.SDK.Core.Android.BaseActivity`1[TViewModel].OnCreate (Android.OS.Bundle bundle) <0x58aff9d0 + 0x0004f> in <filename unknown>:0 
  at *.App.Android.Views.ProfileView.OnCreate (Android.OS.Bundle bundle) <0x5ee9c338 + 0x0001b> in <filename unknown>:0 
  at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) <0x58aff578 + 0x0005b> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:b0a226ab-d8eb-43a9-823d-df4318bf99ed (intptr,intptr,intptr)
	at *.app.android.views.ProfileView.n_onCreate(Native Method)
	at *.app.android.views.ProfileView.onCreate(ProfileView.java:33)
	at android.app.Activity.performCreate(Activity.java:5447)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
	at android.app.ActivityThread.access$800(ActivityThread.java:166)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)

```
Nothing really fancy in the code:
ProfileView
```
 public class ProfileView : BaseAppActivity<ProfileViewModel>
 {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            SetContentView(Resource.Layout.ProfileView);
            Title = string.Format("{0} | {1}", Title, Context.Version);
        }
...
 }
```
BaseAppActivity: BaseActivity
```
...
        protected override void OnCreate(Bundle bundle)
        {
            SupportRequestWindowFeature((int)WindowFeatures.IndeterminateProgress);
            base.OnCreate(bundle);
            RegisterBaseViewReceiver();

            if (Context != null)
                Context.OnLoaded();
        }
...
```
And BaseActivity
```
public class BaseActivity<TViewModel> : MvxAppCompatActivity<TViewModel>
        where TViewModel : BaseViewModel
    {
        public TViewModel Context
        {
            get
            {
                return (TViewModel)base.ViewModel;
            }
        }
...
   }
```

**Comment by kjeremy** [comment]
If you can only reproduce it in release mode then I would advise checking
your linker settings.

**Comment by alexsorokoletov** [comment]
@kjeremy good advice, however, how linker can produce a problem that leads to invalid cast? :) Usually it's member missing or something like that.

**Comment by ilber** [comment]
Same issue in our app too. This is a very annoying crash that happens randomly to our users. Any idea from you guys on how to solve or circumvent this problem?

**Comment by Cheesebaron** [comment]
This hasn't been possible for any of us to reproduce. If someone can come up with a repro sample, we are happy to solve this issue.

Please open a new issue with such reproduction steps and we will look at it.
