### ISSUE TITLE
IoC doesn't support transparent proxies on Xamarin.Android

### ISSUE THREAD

**Issue by yallie** [MvvmCross/MvvmCross#1308]
Hi, I'm using transparent proxies in my MvvmCross application on Android.
Some of my services are in fact transparent proxies doing remote calls:

```c#
Mvx.RegisterSingleton(interfaceType, () =>
{
	var connection = Mvx.Resolve<IConnection>();
	return connection.CreateProxy(interfaceType);
});
```
It worked fine in MvvmCross 3.0.13, but when I updated the project
to MvvmCross 4.1.4, service resolution doesn't work anymore.

On Mono, transparent proxies always report their type as MarshalByRefObject.
As a result, type.IsInstanceOfType(proxy) check always returns false — see
[MvxSimpleIoCContainer.cs, line 448](https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Platform/Platform/IoC/MvxSimpleIoCContainer.cs#L448). And so IoC reports an error:

>Resolver returned object type MarshalByRefObject which does not support interface IMyService.

I need a way to override or to bypass this check for MarshalByRefObjects.
As far as I know, the only way to check whether a Mono's transparent proxy
implements an interface is like this:

```c#
var typedProxy = transparentProxy as IMyService;
if (typedProxy == null)
    throw new MvxException("Resolver returned invalid service"...);
```

Mono runtime obviously has more information on the proxy that Reflection provides,
so "as" operator works fine, but [type.IsAssignableFrom(proxy.GetType())](https://github.com/MvvmCross/MvvmCross/blob/4.0/CrossUI/CrossUI.Core/ReflectionExtensions.cs#L44) fails.

### Steps to reproduce
1. Clone and build my sample solution: [MvvmCrossIocProxy](https://github.com/yallie/MvvmCrossIocTransparentProxy)
2. Run WindowsConsoleApp on Windows. Service resolution works fine.
3. Run AndroidApp on Android. Same service resolution code fails.

### Expected behavior
IoC should return a singleton object registered for the given interface, be it a simple class or a transparent proxy created at runtime.

### Actual behavior
IoC throws an MvxException: Resolver returned object type MarshalByRefObject...

### Configuration

**Version:** 4.1.4
**Platform:** Android

**Comment by thefex** [comment]
My personal opinion: MvvmCross IoC is good for simple things. How about changing your IoC provider to for example Ninject?

**Comment by yallie** [comment]
Thanks for the suggestion! But I'd like to stick with as few dependencies as possible.

We don't need any cool features like filters and interceptors from IoC, so Ninject would be an overkill for our application.

We're indeed quite happy with the built-in Mvx IoC. It's just a little type safety check introduced between v3 and v4 that broke things apart. Hope it won't be too hard to fix or to work around.

**Comment by martijn00** [comment]
@yallie Can you submit a pull request for this? It seems you already are quite into this problem, and would be great if you make a fix!

**Comment by yallie** [comment]
@martijn00 Sorry for my late reply! Here you are: #1325

**Comment by martijn00** [comment]
Thanks for the pull request!
