### ISSUE TITLE
MvxWindowsViewPresenter swallowing exceptions thrown in Init

### ISSUE THREAD

**Issue by shemseddine** [MvvmCross/MvvmCross#1309]
In the viewmodel when throwing an unhandled exception in the Init() function, it is swallowed by the ViewPresenter. Which means I'm unable to handle any of the exceptions globally using my own exception handling methods.
### Configuration

**Version:** 3.5.1

**Platform:** WPF

**Comment by thefex** [comment]
Update MvvmCross to most recent 4.x and check does problem still exist.

**Comment by nmilcoff** [comment]
Can this issue be closed now that we have a brand new ViewPresenter for WPF? (#2124)
