### ISSUE TITLE
MvxCachingFragmentCompatActivity not finding registered fragments

### ISSUE THREAD

**Issue by Johan-dutoit** [MvvmCross/MvvmCross#1311]
### Expected behavior
Automatic registration of fragments should work when using `MvxCachingFragmentCompatActivity`

### Actual behavior
Automatic registration of fragments does not work when using `MvxCachingFragmentCompatActivity`

**Version:** 4.1.4
**Platform:** Android Support

Repro project: [AppCompantFragmentsRepro.zip](https://github.com/MvvmCross/MvvmCross/files/240618/AppCompantFragmentsRepro.zip)

```
public class MainActivity : MvxCachingFragmentCompatActivity<MainViewModel>
{ ...  }

[MvxFragment(typeof(MainViewModel), Resource.Id.main_content)]
[Register("appcompantfragmentsrepro.fragments.MyFragment")]
public class MyFragment : MvxFragment<TabViewModel>
{ ... }

```

**Comment by thefex** [comment]
Auto-Registration does not work only on ShowFragment.

**Comment by grahampett** [comment]
Don't call ShowFragment directly - you should use ShowViewModel with the fragment's view model and let the framework handle loading the required activity and the fragment. In your repo, just change the AppStart.Start to call ShowViewModel<TabViewModel>() instead of ShowViewModel<MainViewModel>() and remove the call to ShowFragment from the activity.

**Comment by thefex** [comment]
First of all: issue should be moved to MvvmCross.SupportLibrary
Second: if @grahampett is right we should make ShowFragment internal and call that by wrapper class in Shared Logic (by using [AssemblyVisibleTo...] attribute)

**Comment by grahampett** [comment]
Making it internal wouldn't help - it's currently protected so it can be overridden in derived classes if required, but in this case it was being called from the derived activity instead.

**Comment by Johan-dutoit** [comment]
Is it really a train smash using ShowFragment from an activity?  This is platform specific after all.

**Comment by grahampett** [comment]
MvvmCross uses view-model first navigation. What you're trying to do by calling ShowFragment directly is akin to view-first navigation, which I don't think is really supported. I can't see how the View Model would be created in this case, for example. Calling ShowViewModel will create the view model and then create the activities/fragments as required to display it.

**Comment by grahampett** [comment]
In any case, ShowFragment is an implementation detail of the class that assumes the fragment has already been created and is in the cache. The public method Show is what gets called from the framework to show a fragment, and this deals with the registration in the cache.

**Comment by thefex** [comment]
@grahampett it will prevent MvvmCross users for calling this method

**Comment by grahampett** [comment]
@thefex if you just make it internal then you also prevent MvvmCross users from overriding this method, which is undesirable as it's clearly been designed to be overridden by consumers that want to change the behaviour - like most of MvvmCross has. If you make it protected internal then you don't prevent derived classes from calling the method as was done in this case and you make it callable from elsewhere in MvvmCross code.

**Comment by martijn00** [comment]
Please discuss in https://github.com/MvvmCross/MvvmCross-AndroidSupport
