### ISSUE TITLE
Support URL based navigation

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1315]
In order to improve deep linking into MvvmCross applications, it would be very nice with URL based navigation.

I suggest that we create a new Attribute that you can use for ViewModels or maybe for the Page/ViewController/Activity (not sure yet) like:

```
[MvxUrl("whatever")]
public class WhateverViewModel : MvxViewModel
```

Then when someone visits the Url: _http://my.app/whatever_ it will navigate to that ViewModel.

Additionally, if you have a hierarchy of some sort like _http://my.app/one/two/three_ it should create some kind of index to know what should happen when you navigate back in the application. So, from that particular Url, when navigating back you would go three, two and then one.

I would suspect that this would include extending current presenters or make a new one which supports this.
Xamarin.Forms recently added support for this. Currently it seems like you just add a name to the Page and register URLs in the entry point of that Forms application to which URLs you want to support in the app.

Any thoughts on this?

**Comment by modplug** [comment]
This could probably be used for navigating from 3d-touch shortcuts on iOS as well.

**Comment by Johan-dutoit** [comment]
Should the url define the hierarchy? (maybe as a default yes)

`ie.  http://my.app.com/cheese/1231/reviews`
the 1231 (id of the cheese)  portion of the url should not be considered for the back.

perhaps

```
[MvxUrl(http://my.app.com/cheese/1231/reviews, CheeseViewModel)] //Params of ViewModels
public ReviewViewModel...
```

**Comment by charri** [comment]
Our team created something like you're describing in a previous project.

We found that adding an assembly attribute (compared to class attribute) is about 3x faster (as you don't have to loop through all the classes with reflection).

Example:
```
[assembly: Routing(typeof (FlightViewModel), @"foo://flights/(?<index>0|1)")]
[assembly: Routing(typeof(FlightRoutingFacade), @"foo://flight/\?id=(?<id>\d{8}[A-Z0-9]{2,3}\d{2,5})$")]
[assembly: Routing(typeof(FlightRoutingFacade), @"foo://flight/\?id=(?<id>\d{8}[A-Z0-9]{2,3}\d{2,5})&update=(?<update>true|false)$")]
```

As you can see from the code we added regex support for providing parameters for the Init method (+ resharper attributes to get those fancy highlightings). Our routing service also supports multiple Urls per ViewModel. Furthermore, we had an issue that we had a url for two different detail views (depending on the context of the id), so we create "RoutingFacades" that would return the desired ViewModel - maybe a bit of an overkill for what you want to accomplish here. The example would also work with http.

Our solution is composed of:
* Routing Attribute (ViewModel/Facade, URI regex)
* RoutingFacades are constructed via Mvx.IocConstruct so we can profit from dependency injection
* RoutingService, registered as a singleton, uses IMvxViewDispatcher to show the viewmodels
* Necessary additions to Android (Activity.OnNewIntent) + iOS (AppDelegate.OpenUrl)

What we also used it for:
* Registered a custom scheme (i.e. "foo") to our app so we could directly open a deeplink from our mobile website
* Push-Messages: Depending on the status of the app we would pass the url as the Notification Parameter, so when the app started we knew where we were going 

What we didn't implement:
* In Android you should specify the deeplink base per Activity so the system knows which activity to start (https://developer.android.com/training/app-indexing/deep-linking.html) - we only had one activity as we used fragments (FullFraging Support ftw :+1:) for everything else.
* Only tested in Android + iOS

If this is anything on the lines of what you are looking for, I am sure I could whip together a sample.

**Comment by SimonSimCity** [comment]
@charri As I'm also looking forward to an integration like this, I guess it would be quite interesting to see it implemented. Your implementation doesn't sound like you cut of a lot of the MvvmCross functionality to get it going. So, at least I would be interested to take a look at it and understand how it could be implemented.

I also have the use-case, that I have to present views differently based on where the user comes from.

**Comment by modplug** [comment]
@charri How is the whipping of the sample coming together? :)

**Comment by charri** [comment]
Code can be found here: https://github.com/charri/MvvmCross-Routing (Code, Example(s), Tests)

Tested for Android + iOS.

While I was creating the demo, I wrapped everything into a plugin. If there are no objections I'll create a nuget package and publish it by the end of the week. I think for MvvmCross 5.0 it would, however, make more sense to directly integrate this (or something similar) into the core. As there are a few things a user would have to copy&paste into Activities and AppDelegates to use deeplink from outside the app.

**Comment by Cheesebaron** [comment]
I'll look through the code, so far it looks promising. We'd like to integrate it into the core so we can keep the copying of code down.

Thanks for the work put into this.

**Comment by Johan-dutoit** [comment]
Just an FYI, 

On Android, OnNewIntent isn't called when the app is killed/not running.
So this would need to be handled in the base activities.

**Comment by charri** [comment]
good catch! forgot about that one. I'll update the documentation asap

**Comment by martijn00** [comment]
@charri Would it be possible to make a PR integrating your current code into MvvmCross? We could take it from there, and improve where possible.

**Comment by m-mccool** [comment]
@charri Does your plugin cover the scenario @Cheesebaron wrote about

> Additionally, if you have a hierarchy of some sort like http://my.app/one/two/three it should create some kind of index to know what should happen when you navigate back in the application.
