### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by vonovak** [MvvmCross/MvvmCross#1318]
hello, the [website ](http://mvvmcross.com) is down for a couple of days, any plans on going online again?

**Comment by Cheesebaron** [comment]
Use mvvmcross.readme.io while we get our DNS sorted.

**Comment by vonovak** [comment]
Would be nice to mention in the readme, for a newcomer this is quite puzzling.

**Comment by Cheesebaron** [comment]
Thanks, I've updated the readme.
