### ISSUE TITLE
Support bind iOS NSLayoutConstraint Constant

### ISSUE THREAD

**Issue by KanLei** [MvvmCross/MvvmCross#1326]
Currently 
 `set.Bind(ScrollBannerHeightConstraint).For(c => c.Constant).To("If(Urls.Count > 0, 128, 0)");` 
will cause exception
 `problem ArgumentException: Object of type 'System.Int64' cannot be converted to type 'System.nfloat'`.

can we support this
 `set.Bind(ScrollBannerHeightConstraint).For(c => c.Constant).To("If(Urls.Count > 0, 128f, 0f)");`

**Comment by munkii** [comment]
Take a look at Cirrious.FluentLayout (https://github.com/FluentLayout/). The UpdateConstraintsView in the samples will be of most interest.

**Comment by KanLei** [comment]
@munkii Thanks, I will have a look.
