### ISSUE TITLE
MvxAndroidTask defined twice

### ISSUE THREAD

**Issue by ggirard07** [MvvmCross/MvvmCross#1327]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

### Steps to reproduce

1. Create a new Android project with an empty class

2. Change the empty class to inherit from MvxAndroidTask

3. Click the automated error resolution lamp to be proposed with a list of possible reference

### Expected behavior
There should be only one MvxAndroidTask available

### Actual behavior
There is currently 2 MvxAndroidTask implementations:

- `MvvmCross.Droid.Platform.MvxAndroidTask` ([Defined here](https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Droid/Droid/Platform/MvxAndroidTask.cs))
- `MvvmCross.Platform.Droid.Platform.MvxAndroidTask` ([Defined here](https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Platform/Droid/Platform/MvxAndroidTask.cs))

### Remarks
Is there any reason to keep 2 separate implementation to maintain?
Is it an acceptable breaking change for you to delete on of this implementation?

Based on my observation, the proper implementation seems to be `MvvmCross.Platform.Droid.Platform.MvxAndroidTask`, as for all others platform this is were the `MvxThePlatformTask` class is defined.

My concern is that there is no direct reference to any of this class directly from the MvvmCross project. I am aware about at least one in MvvmCross-Plugins defined [here](https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/Email/MvvmCross.Plugins.Email.Droid/MvxComposeEmailTask.cs), which also reference `MvvmCross.Platform.Droid.Platform.MvxAndroidTask`. I am not well aware about the whole MvvmCross infrastructure and possible implication...

I also haven't  check if there are any other dup in those namespaces.

### Configuration

**Version:** 4.1.0
**Platform:** Android

**Comment by Cheesebaron** [comment]
Thanks for reporting this. I think it is a mistake that they are both places. It shouldn't be necessary to have two identical implementations.
