### ISSUE TITLE
SuspensionManager failed when migrating to UWP

### ISSUE THREAD

**Issue by LitaoShen** [MvvmCross/MvvmCross#1328]
To help us fix your issue, please provide the information in the below template. 

> Note: I cannot post my project here but I can paste some code here. I have frame defined using weakreference
> `private List<WeakReference<IMvxWindowsFrame>> _registeredFrames = new List<WeakReference<IMvxWindowsFrame>>();` and I register using singleton `Mvx.RegisterSingleton<IMvxSuspensionManager>(new AWSuspensionManager());`
### Steps to reproduce

1.Suspend and shutdown
1. Resume
### Expected behavior

The app should come back and stay in the page when it was suspended and terminated. It works for WP8.1 but failed in UWP, the _registeredFrames some how has count=0 when try to save states. 
### Actual behavior

White screen
### Configuration

**Version:** 4.0.0

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by martijn00** [comment]
Can you provide a sample repo so we can try to reproduce this?
