### ISSUE TITLE
Create Visual Studio and Xamarin Studio project templates

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1329]
To ease creating a new MvvmCross project it would be really awesome just using an online template in VS or XS which creates a new solution with everything set up ready for you to work on.

So a template that looks something like:

Core
Droid
iOS
Store 8.1 (Windows Phone + Windows)
WPF
UWP

**Comment by jimbobbennett** [comment]
I'm starting to take a look at the VS templates

**Comment by CherechesC** [comment]
If you are interested, I have already created something like this for Xamarin Forms( only for iOS, Android and UWP).
You can have a look at it here: https://github.com/CherechesC/XamFormsMvxTemplate

**Comment by jimbobbennett** [comment]
@CherechesC - thanks, will take a look.

**Comment by vvolkgang** [comment]
Supporting (as in, upgrading stuff, etc.) VS templates is a *major pain in the ass*. I do this for a project in my company and I regret every line I have to change in a text editor. I usually just clone a base working project (which can be easily updated) and rename stuff.

That being said, instead of the template, what I propose is a sample with all the boilerplate stuff done and scripts to rename things.

**Comment by jimbobbennett** [comment]
VS template is done:

https://github.com/jimbobbennett/MvvmCross-VisualStudioAddIn

VSIX is available as a preview release:

https://github.com/jimbobbennett/MvvmCross-VisualStudioAddIn/releases

Can someone review it and if it's ok let me know how I can transfer the repo over to the MVVMCross repos.

**Comment by benhysell** [comment]
Everyone, you may want to check out NinjaCoderForMvvmCross

[https://visualstudiogallery.msdn.microsoft.com/e66eddef-d1b7-452d-94db-0689ae2d114b](https://visualstudiogallery.msdn.microsoft.com/e66eddef-d1b7-452d-94db-0689ae2d114b)

[https://github.com/asudbury/NinjaCoderForMvvmCross](https://github.com/asudbury/NinjaCoderForMvvmCross)

I've been using this for a few years, it "just works" when setting up a new project, adding all the nuget packages, project links, adding View Models, etc.

**Comment by lothrop** [comment]
I was just going to recommend @asudbury's NinjaCoder, too.

**Comment by Cheesebaron** [comment]
That doesn't solve templates in Xamarin Studio. Also NinjaCoder does much, much more than just providing startup templates.

**Comment by jimbobbennett** [comment]
The VSIX I've created just creates a solution that has an iOS, Android UWP, Win 8.1, Win Phone 8.1 and WPF project that does the same as the starter pack - simple app, Hello MVVMCross in a text box and label.

I've also started on a Xamarin Studio add-in, but it's slow going as there is not much documentation.

**Comment by pocheshire** [comment]
@jimbobbennett 
all useful documentation links:

- [MonoDevelop articles](www.monodevelop.com/developers/articles) 
- [MoboDevelop API overview](www.monodevelop.com/developers/articles/api-overview)
- [Extending Xamarin Studio with Add-Ins](http://developer.xamarin.com/guides/cross-platform/getting_started/extending_xamarin_studio_with_addins/)
- but most useful for me was [D Add-In for MonoDevelop](https://github.com/aBothe/Mono-D)

Starting next week, I can help with the development, if you upload a project on GitHub

**Comment by jimbobbennett** [comment]
@pocheshire Thanks for those links, found a few useful ones myself that have got me going. I've almost got the 'droid and Core working.  Just got an issue with png files being screwed up.

Code is at https://github.com/jimbobbennett/MVVMCross.XSAddIn

Will keep on chipping away at it and see how far I get.

**Comment by jimbobbennett** [comment]
Xamarin Studio add-in first cut done.  It supports iOS and Android only so far.  The code and a pre-release mpack is on my github.  

https://github.com/jimbobbennett/MVVMCross.XSAddIn

Let me know any feedback.  I can hand the repo over if you want it, and will try to get it in the add-ins gallery soon.

**Comment by opcodewriter** [comment]
@jimbobbennett Hi! You mentioned you found few useful links yourself, do you mind sharing those? 
I'm trying to learn how to create project templates too..
Thanks!

**Comment by martijn00** [comment]
Thanks @jimbobbennett ! I think we can close this isse since the add-in is in the gallery!

**Comment by jimbobbennett** [comment]
VS add-in now available in the gallery.

https://visualstudiogallery.msdn.microsoft.com/96b3d919-0277-4f63-92a3-a7bf3e7cd384?SRC=Home

Do you want me to transfer ownership of my repos?  If so what do I need to do?
