### ISSUE TITLE
Consider more binding extensions... possibly Automated Form Validation?

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#133]
AutoValidating errors and having some way to show that would be uber cool....

See some notes on http://msdn.microsoft.com/en-us/library/cc189022%28v=VS.95%29.aspx

**Comment by nmilcoff** [comment]
This feature request sounds like a huge amount of new code to add and maintain (what about validation rules? should it cover all form widgets?). 

Since we've deprecated AutoView, I think we should close it, unless someone has an idea of how to get this in...

**Comment by softlion** [comment]
Yes have an implemented idea. More to come on a pr.
