### ISSUE TITLE
Wpf multiwindow support

### ISSUE THREAD

**Issue by TopBaJLbD** [MvvmCross/MvvmCross#1340]
Hi. It is possible to create dialog manager or ShowDialog/ShowWindow method in WPF implementation. If I release it as service then method ShowViewModel change view in Main window. I'm understand, that I can use ContentPresenter e.t.c. to change view in my dialog window, but I want to use framework methods.

Thank you.

### Configuration

**Version:** 4.0.0

**Platform:** WPF

**Comment by martijn00** [comment]
This is really up to the presenter you use. It is easy to create your own presenter to add support for this use case. You are welcome to contribute that back with a pull request!
