### ISSUE TITLE
Using MvxFragmentsPresenter MvxFragment doesn't close at vm Close(this)

### ISSUE THREAD

**Issue by fedotovsi** [MvvmCross/MvvmCross#1341]
Using MvxFragmentsPresenter in Droid application on fragment viewmodel executing Close(this) doesn't make anything.
I had a look to source code, so it closes only activities.
Viewmodel is abstract part of .Core and it shouldn't depend on how it implemented on specific platform is it activity or fragment, so it seems strange that method Close do nothing if it's a fragment.

Conditions to reproduce:
MainView : MvxCachingFragmentCompatActivity<MainViewModel>{}

[MvxFragment(typeof(MainViewModel), Resource.Id.main_content_frame)]
[Register("talecom.wdlive.selwood.device.droid.views.DashboardFragment")]
DashboardFragment : MvxFragment<DashboardViewModel>{}

### Steps to reproduce

1. Execute Close(this) in DashboardViewModel 

### Expected behavior
Dashboard fragment is replaced by previous fragment, I guess,  or maybe by previous activity I think it depends on situation. ViewModel is disposed 

### Actual behavior
Nothing happens

### Configuration

**Version:** 4.1.4

**Platform:** Android

**Comment by martijn00** [comment]
This should work, see the implementation here: https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Droid/FullFragging/Caching/MvxCachingFragmentActivity.cs#L443

Are you overriding Close in your activity, so the base doesn't get called?

**Comment by fedotovsi** [comment]
No, I suppose to call Close in .Core project not in .Droid proj
my all logic regarding navigation is in .Core proj, but this is located in Activity
so I call MvxNavigatingObject.Close and happens nothing.

**Comment by martijn00** [comment]
Can you provide a sample so we can reproduce this?

**Comment by fedotovsi** [comment]
yes, I expected this bug will work on any situation I was wondering when in your example XPlatformMenus it worked, almost. So finally I found an example: in XPlatformMenus sample changed command GoToInfoCommand in HomeViewModel to Close(this), so something like this:
HomeViewModel :
public MvxCommand GoToInfoCommand
        {
            get
            {
                return new MvxCommand(() =>
                {
                    Close(this);
                    //ShowViewModel<InfoViewModel>()
                });
            }
        }
I guess STR are 1.execute ShowViewModel from host so MainViewModel in our case and after this on this ChildViewModel execute Close(this).
So since I have all navigation in MainViewModel Close doesn't work for me, in  XPlatformMenus sample it's done with help MenuViewModel and Close method works properly in this case.

**Comment by Cybrosys** [comment]
Got the same problem here. Got a MvxCachingFragmentCompatActivity that gets instantiated when I call ShowViewModel<DemoFragmentViewModel>, along with the DemoFragment. Calling Close(this) from inside DemoFragmentViewModel does not Finish the MvxCachingFragmentCompatActivity.

Maybe I'm missing something? Should I override some method in the Activity or Fragment that will get called when the DemoFragmentViewModel's Close(this) method gets called, and then call Finish on the Activity?

**Comment by fedotovsi** [comment]
I don't need to Close Activity, I want to close Fragment and back to previous.
I have a lot of fragments within one activity, so one can be shown after another.

**Comment by martijn00** [comment]
@Cybrosys I've made a fix for your problem. This will be in the next release.
