### ISSUE TITLE
Xamarin Android Tip Calculator

### ISSUE THREAD

**Issue by luis-ramirez** [MvvmCross/MvvmCross#1347]
I trying to make your tutorial of xamarin android "Tip Calculator" and I getting this error when try to install mvvm cross

Install-Package MvvmCross.HotTuna.MvvmCrossLibraries

<img width="1364" alt="screen shot 2016-06-05 at 3 04 54 pm" src="https://cloud.githubusercontent.com/assets/6517152/15807533/e754e9d4-2b2e-11e6-9851-b2927488ad57.png">

**Enviroment**

Visual Studio 2015 with Update 2

**Comment by Cheesebaron** [comment]
We've removed HotTuna from the package names.

**Comment by lothrop** [comment]
As per https://mvvmcross.com/docs/upgrade-to-mvvmcross-40, you should be installing `MvvmCross.Core`. Also, it seems you're using an old tutorial. The new one is here: https://mvvmcross.com/docs/a-xamarinandroid-ui-project

**Comment by luis-ramirez** [comment]
So, then, remove it from github documentation

**Comment by lothrop** [comment]
@Cheesebaron @martijn00 Is there a reason for still keeping the old docs on Github?

**Comment by martijn00** [comment]
Not really except for that some stackoverflow issue's or other threads link to the docs.

**Comment by Cheesebaron** [comment]
We should just nuke them and link to mvvmcross.com
