### ISSUE TITLE
MvxSetToNullAfterBindingAttribute only works for MvxPropertyInfoTargetBinding

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#1358]
Do we need to copy the `Dispose` logic from `MvxPropertyInfoTargetBinding` to other binding target types so that all properties with `MvxSetToNullAfterBindingAttribute` get set to `null` on dispose?

**Comment by Cheesebaron** [comment]
I don't think it is super helpful to use `MvxPropertyInfoTargetBinding` and `MvxSetToNullAfterBindingAttribute`. Sure bindings that rely on an ItemsSource are a good place for using it. However, most of the other require you to unsubscribe from subscribed events anyways. What the two above do is just set things to null when disposing.

**Comment by kjeremy** [comment]
Wait it's NOT useful to use them?  I believe `MvxSetToNullAfterBindingAttribute` showed up during the fix for #17

**Comment by Cheesebaron** [comment]
It is useful only in bindings which bind to a Property.

**Comment by nickrandolph** [comment]
@kjeremy is this issue still relevant? If so, what action needs to be taken?
