### ISSUE TITLE
Android: "Method 'Array.Empty' not found" after upgrading to MvvmCross 4.2.0 

### ISSUE THREAD

**Issue by Noires** [MvvmCross/MvvmCross#1363]
After upgrading to the newest release, the error described in issue #1330 reappeared. Appears again in the splashscreen in the OnCreate though with following error now:

```
06-13 15:44:18.618 I/MonoDroid(26531): UNHANDLED EXCEPTION:
06-13 15:44:18.621 I/MonoDroid(26531): System.MissingMethodException: Method 'Array.Empty' not found.
06-13 15:44:18.621 I/MonoDroid(26531):   at Mobile.AndroidApp.Activitys.SplashScreen.OnCreate (Android.OS.Bundle bundle) [0x00008] in W:\AppPath\SplashScreen.cs:26 
06-13 15:44:18.621 I/MonoDroid(26531):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) [0x00011] in /Users/builder/data/lanes/3236/ee215fc9/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.App.Activity.cs:2857 
06-13 15:44:18.621 I/MonoDroid(26531):   at (wrapper dynamic-method) System.Object:7418e7cb-55a1-4069-925f-b552b65f53a2 (intptr,intptr,intptr)
06-13 15:44:18.637 W/art     (26531): JNI RegisterNativeMethods: attempt to register 0 native methods for md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable
An unhandled exception occured.

06-13 15:44:19.908 E/mono    (26531): 
06-13 15:44:19.908 E/mono    (26531): Unhandled Exception:
06-13 15:44:19.908 E/mono    (26531): System.MissingMethodException: Method 'Array.Empty' not found.
06-13 15:44:19.908 E/mono    (26531):   at (wrapper dynamic-method) System.Object:7418e7cb-55a1-4069-925f-b552b65f53a2 (intptr,intptr,intptr)
06-13 15:44:19.908 E/mono    (26531):   at (wrapper native-to-managed) System.Object:7418e7cb-55a1-4069-925f-b552b65f53a2 (intptr,intptr,intptr)
06-13 15:44:19.908 E/mono-rt (26531): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Array.Empty' not found.
06-13 15:44:19.908 E/mono-rt (26531):   at (wrapper dynamic-method) System.Object:7418e7cb-55a1-4069-925f-b552b65f53a2 (intptr,intptr,intptr)
06-13 15:44:19.908 E/mono-rt (26531):   at (wrapper native-to-managed) System.Object:7418e7cb-55a1-4069-925f-b552b65f53a2 (intptr,intptr,intptr)
referenceTable GDEF length=670 1
referenceTable GSUB length=7202 1
referenceTable GPOS length=24560 1
```

### Configuration

**Version:** 4.2.0

**Platform:** Android/Xamarin

**Comment by martijn00** [comment]
You need to update to the latest stable version of Xamarin.

**Comment by Cheesebaron** [comment]
Try nuking bin and obj folders

**Comment by Noires** [comment]
Yeah deleted the bin and obj folders. Just didnt realize there was actually a new Xamarin update since iam sitting behind a proxy. Thanks!

**Comment by fugaku** [comment]
Working on local build, but failed on Visual Studio Online Build Services

> 2016-07-03T10:29:47.5154734Z ##[error]C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1473,5): Error MSB4018: The "LinkAssemblies" task failed unexpectedly.
2016-07-03T10:29:47.5164730Z Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item '!!0[] System.Array::Empty()' (defined in 'MvvmCross.Droid.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') from 'MvvmCross.Droid.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve !!0[] System.Array::Empty()
2016-07-03T10:29:47.5164730Z    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
2016-07-03T10:29:47.5174731Z    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
2016-07-03T10:29:47.5174731Z    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
2016-07-03T10:29:47.5184736Z    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
2016-07-03T10:29:47.5184736Z    at Mono.Linker.Steps.MarkStep.ProcessQueue()
2016-07-03T10:29:47.5194732Z    at Mono.Linker.Steps.MarkStep.Process()
2016-07-03T10:29:47.5624733Z    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
2016-07-03T10:29:47.5964717Z    at Mono.Linker.Pipeline.Process(LinkContext context)
2016-07-03T10:29:47.5964717Z    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
2016-07-03T10:29:47.5974732Z    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
2016-07-03T10:29:47.5974732Z    --- End of inner exception stack trace ---
2016-07-03T10:29:47.5974732Z    at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
2016-07-03T10:29:47.5984737Z    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
2016-07-03T10:29:47.5984737Z    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2016-07-03T10:29:47.5994730Z    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by thomas-lebrun** [comment]
I have a similar issue when building my Xamarin.Android application using Visual Studio Team Services ==>  Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item '!!0[] System.Array::Empty()' (defined in 'MvvmCross.Droid.Support.V7.RecyclerView, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') from 'MvvmCross.Droid.Support.V7.RecyclerView, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve !!0[] System.Array::Empty()

Any ideas ?

Thanks!

**Comment by Cheesebaron** [comment]
What version is VSTS running of Xamarin?

**Comment by fugaku** [comment]
It's online version

**Comment by thomas-lebrun** [comment]
Not sure how/where I can find that information... I guess this is the latest version

**Comment by thomas-lebrun** [comment]
I've noticed that just added this piece of code in LinkerPleaseInclude:

public void Include(Array array)
{
    array = Array.Empty<object>();
}

Throws "'Array' does not contain a definition for 'Empty'"....

**Comment by Cheesebaron** [comment]
Well we are not using that code either in the code it complains about: https://github.com/MvvmCross/MvvmCross-AndroidSupport/search?utf8=%E2%9C%93&q=Empty

I suspect VSTS is running an old version which causes issues with MvvmCross.

**Comment by thomas-lebrun** [comment]
After using ILSpy to decompile MvvmCross.Droid.Support.V7.RecyclerView, I've found this: 

if (this._itemClick != null)
{
	MvxTrace.Warning("Changing ItemClick may cause inconsistencies where some items still call the old command.", Array.Empty<object>());
}

The Array.Empty piece of code is here but I can't find it on the source on Github...
https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.RecyclerView/MvxRecyclerAdapter.cs#L71

**Comment by Cheesebaron** [comment]
I'd guess that `params object[] args` might be translated into `Array.Empty()` when compiled and the args are not set.

Why there is a difference between Xamarin versions I dunno, might be a change in mono.

I can only say that it works fine when using latest _stable_ version of Xamarin tools, and you should ensure that is what you are compiling with.

How you get that version info out of the hosted build agent I dunno. The log might reveal some version info. Maybe you can add stuff to your csproj files which dumps the versions in the log.

**Comment by thomas-lebrun** [comment]
Here is the content/version of the hosted build agent:

https://www.visualstudio.com/en-us/docs/build/agents/hosted-pool

◦Xamarin for Visual Studio 4.0.3.214
◦Xamarin Studio 5.10.2.56


Thanks,

**Comment by kjeremy** [comment]
That looks old.  Latest stable of Xamarin for VS is 4.1.something.

**Comment by Cheesebaron** [comment]
That is ancient. Marking this as wont-fix, complain to MS to fix their build environment.
