### ISSUE TITLE
4.2.0 Starter package installs 4.1.4

### ISSUE THREAD

**Issue by smstuebe** [MvvmCross/MvvmCross#1367]
### Steps to reproduce

1. Install-Package MvvmCross.StarterPack -Version 4.2.0

### Expected behavior
MvvmCross 4.2.0 packages are installed.

### Actual behavior
MvvmCross 4.1.4 packages are installed.

**Is this a mistake or intentionally?**

**Comment by Cheesebaron** [comment]
Probably a mistake when I updated dependencies in the nuspecs.
