### ISSUE TITLE
MyGet Nuget feed

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1369]
I as thinking of making a more frequently updated NuGet feed using myget. Here we could push a nightly or even a per build NuGet package release on this feed only, so it doesn't interfere with the more stable one of the official NuGet source.

Do you think that would be useful?

**Comment by kjeremy** [comment]
So much yes

**Comment by mvanbeusekom** [comment]
I would really love to have this feature, it will make it so much easier to quickly startup a test application to test new features.

Also makes it possible to find potential issues with NuGet packages a lot faster (hopefully before they go into production as being stable)

**Comment by Cheesebaron** [comment]
We are waiting for the Xamarin.Mac stuff for Windows to hit stable, it is currently in beta

**Comment by Cheesebaron** [comment]
This is done! Feed can be found here: https://www.myget.org/F/mvvmcross/api/v2
