### ISSUE TITLE
ViewModel is null in fragment if the fragment's MvxFragmentAttribute.IsCacheableFragment is set to false

### ISSUE THREAD

**Issue by Cybrosys** [MvvmCross/MvvmCross#1371]
### Steps to reproduce
1. Call `ShowViewModel<FragmentViewModel>` from another ViewModel.
### Expected behavior

The Fragment gets its ViewModel set to an instance of FragmentViewModel
### Actual behavior

ViewModel property of the Fragment is null.
### Configuration

The activity inherits from MvxCachingFragmentCompatActivity.

**Version:** 4.2.0

**Platform:** Android

**Comment by Cheesebaron** [comment]
Kind of sounds like this is by design, doesn't it?

**Comment by Cybrosys** [comment]
Edited my post, the TViewModel information on the ShowViewModel call did not get rendered out. I don't think that calling ShowViewModel on a fragment's view model should result in the fragment not getting an instance of the requested view model.

**Comment by tiftof** [comment]
@Cheesebaron I'm not sure why this is by design? I would expect the ViewModel being created by MvvmCross each time ShowViewModel is called. The ViewModel will not be cached and not be reused every time you navigate again to this fragment.

**Comment by Nickolas-** [comment]
The problem is beacuse of
[this peace of code](https://github.com/MvvmCross/MvvmCross/blob/c6b3976e3025464005adb97df258c959a106d74a/MvvmCross/Droid/FullFragging/Fragments/MvxBindingFragmentAdapter.cs#L44-L45)

If fragment is not cacheable , it will not create request

**Comment by tfonfara** [comment]
I agree with @tiftof and @Nickolas-, my research came to the same result. In previous version 3.5.1 the `MvxOwnedViewModelFragment` attribute helped to avoid the `return` without further impact like caching. Maybe it's an option to bring back this attribute like
```
if (!FragmentView.GetType().IsFragmentCacheable(Fragment.Activity.GetType()) &&
    !FragmentView.GetType().IsOwnedViewModelFragment())
                return;
```

**Comment by erviem99** [comment]
I too have run into problems with this "feature". I wonder what the recommended approach is when IsCacheableFragment is set to false? A null ViewModel does not seem usefull in any instance.
