### ISSUE TITLE
if MvxSimpleWpfViewPresenter then MvxMultiRegionWindowsViewPresenter (UWP)

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#1372]
For consistency, perhaps MvxMultiRegionWindowsViewPresenter rather than MvxWindowsMultiRegionViewPresenter. The reason this is coming up is I am working on MvxMultiRegionWpfPresenter using a similar model to UWP's.

**Comment by kjeremy** [comment]
@tofutim Do you have a good `MvxMultiRegionWpfPresenter` that would be worth sharing with everyone?

**Comment by tofutim** [comment]
I don't think so, but I might have one in the next couple weeks.

**Comment by tofutim** [comment]
I'm wrong, I do have something. Take a look at the sample from

https://github.com/MvvmCross/MvvmCross-Samples/tree/master/XPlatformMenus/XPlatformMenus.WPF/Views

**Comment by nmilcoff** [comment]
There is a new single UWP ViewPresenter (#2366)
