### ISSUE TITLE
Fragment viewmodel life-cycle events are not called if viewmodel has saved state and calling ShowViewModel<FragmentViewModel>(data) with data

### ISSUE THREAD

**Issue by Cybrosys** [MvvmCross/MvvmCross#1373]
I have three activities and one fragment.
1. MainActivity
2. FragmentHostActivity with a Fragment
3. DetailActivity
### Steps to reproduce
1. Navigate from Main to Host with `ShowViewModel<FragmentViewModel>(data)`.
2. Navigate to Detail from Host (will cause 2 calls to SaveState on FragmentViewModel to occur).
3. Navigate back to Host from Detail, then call Finish on Host.
4. Navigate from Main to host with `ShowViewModel<FragmentViewModel>(data)`.
### Expected behavior

FragmentViewModel Init, ReloadState and Start is called with the **data**.
### Actual behavior

Init, ReloadState and Start is NOT called, the fragment gets the previous view model that was in memory.
### Configuration

**Version:** 4.2.0 with Shared, not FullFragging (what's the difference?) Your sample uses Shared and not FullFragging.

**Platform:** Android

**Comment by slava-v** [comment]
I have the same behavior. Fragment once cached, doesn't launch it's ViewModel lifecycle when Attached second time.

Is there any workaround this ?

**Comment by Cybrosys** [comment]
I stopped using the fragment host activity and mvx fragments. I'm using the normal fragments with minimal code to get layout inflation and bindings working. Loading the fragments manually inside the activity, in other words i'm not using viewmodel navigation to show the fragments. In essence i'm treating them as user controls.
