### ISSUE TITLE
MvvmCross.Tests nuget can't be added to a PCL project

### ISSUE THREAD

**Issue by vvolkgang** [MvvmCross/MvvmCross#1375]
`MvvmCross.Tests` nuget is only configured to be used in a `Console Application`, while a nUnit based test suit only needs to be a Portable Class Library (which is actually what the old documentation references [here](https://github.com/MvvmCross/MvvmCross/wiki/Testing#creating-a-test-assembly) ). 

Adding the .dll to a PCL works.

I'm unable to PR this currently but we might just need to change the [.nuspec]() to have:

```
<!-- PCL -->
<file src="..\bin\Release\Mvx\Console\MvvmCross.Test.Core.MvvmCross.Test.Core.dll" target="lib\portable-net45+win+wpa81+wp80" />
<file src="..\bin\Release\Mvx\Console\MvvmCross.Test.Core.MvvmCross.Test.Core.pdb" target="lib\portable-net45+win+wpa81+wp80" />
```
### Steps to reproduce
1. Create a `Class Library (Portable)`
2. Add `MvvmCross.Tests` nuget
### Expected behavior

Nuget would be added to a PCL project.
### Actual behavior

Error, output will say `MvvmCross.Tests doesn't support .NETPortable,Version=v4.5,Profile=Profile259`

**Version:** 4.2.0

**Platform:** PCL

**Comment by vvolkgang** [comment]
The initial reason for this might have been Moq not supporting anything that can't `Reflection.Emit`. That being said, Mvx doesn't use any of that.

Src: http://stackoverflow.com/a/12119025

**Comment by martijn00** [comment]
https://github.com/MvvmCross/MvvmCross/issues/523 is related
