### ISSUE TITLE
MvvmCross Unity3d ugui

### ISSUE THREAD

**Issue by navek** [MvvmCross/MvvmCross#1380]
It's a little port of the MvvmCross Ngui Library done by yuewah.
### Expected behavior

Doing all binding in a viewModels. Bind Text, Commands, ObservableCollection, ByteArrays to create image.
### Actual behavior

Bind Text, Commands, 
### Configuration

**Version:** 2.0.0

**Platform:** Unity3d ugui

**Comment by Cheesebaron** [comment]
What is this?
