### ISSUE TITLE
Bulk Registration by Convention work not correctly

### ISSUE THREAD

**Issue by Pashcal** [MvvmCross/MvvmCross#1381]
If we have two or more services with same interface in inheritance, "Bulk Registration by Convention" for initial interface register last implementation of inheritance services.
### Example

We have `public class BaseService : IBaseService` and `public class CouponService : BaseService, ICouponService`
So `Mvx.Resolve<IBaseService>()` return `CouponService`.
### Configuration

**Version:** 4.2.0

**Platform:** iOS

**Comment by Cheesebaron** [comment]
Why is this wrong? What did you expect?
