### ISSUE TITLE
Bindings project does not build on MAC

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1385]
Bindings project does not build on Mac because of hard reference to `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\System.Collections.Concurrent.dll`

**Comment by SimonSimCity** [comment]
I suggest we should announce another release. Because of the static reference here, you can't install this version on OS X (probably also other systems - like when having the `Program Files (x86)` folder on a different partition).
