### ISSUE TITLE
A standardized way of doing vm -> view communication

### ISSUE THREAD

**Issue by modplug** [MvvmCross/MvvmCross#1386]
I often find it challenging of doing vm -> view communication (animations, dialogs and such) the right way with MvvmCross. 

There are many ways to achieve this but I think we as a community should strive to make this as standard as possible and an integral part of the framework. I've been watching the ReactiveUI community for a while and they share a lot of the same ideas as MvvmCross. I came across this article / snippet from ReactiveUI which caught my attention:

http://docs.reactiveui.net/en/user-guide/interactions/index.html

Let me hear your thoughts on this

**Comment by slodge** [comment]
I did code this once http://stackoverflow.com/a/22640623 ... :)

**Comment by mvanbeusekom** [comment]
@Cheesebaron or @martijn00, I think this issue can be closed since Stuart provided a good standard solution already integrated in Mvx

**Comment by Cheesebaron** [comment]
MvxInteraction is already there. Closing.
