### ISSUE TITLE
Can't update MvvmCross.Binding to 4.2.1 on OS X

### ISSUE THREAD

**Issue by SimonSimCity** [MvvmCross/MvvmCross#1387]
When trying to update  the nuget-packages to 4.2.1, I get the following error on the binding-package:

```
Updating MvvmCross.Binding...
Attempting to resolve dependency 'MvvmCross.Core (≥ 4.2.1)'.
Attempting to resolve dependency 'MvvmCross.Platform (≥ 4.2.1)'.
Attempting to resolve dependency 'System.Collections.Concurrent (≥ 4.0.12)'.
'System.Collections.Concurrent' already has a dependency defined for 'System.Runtime'.
Downloading System.Collections.Concurrent 4.0.12...
'System.Collections.Concurrent' already has a dependency defined for 'System.Runtime'.

**Comment by SimonSimCity** [comment]
I guess this is somehow related to #1385 ...

**Comment by martijn00** [comment]
Use a Nuget client which supports the new dependency systems.

**Comment by Cheesebaron** [comment]
System.Collections.Concurrent requires a recent version of NuGet package manager to install. Update it.

As for Xamarin.Studio, if you are using that, this will only work for a newer Alpha version, which allegedly supports this. Complain to Xamarin that NuGet package manager has been neglected in Xamarin.Studio, it is not our fault it sucks.

**Comment by SimonSimCity** [comment]
I've already updated. Isn't NuGet `3.3.0.212` good enough?

**Comment by drungrin** [comment]
There is no System.Collections.Concurrent for profile 259.

You should fix the MvvmCross.Binding for that profile.

On profile 111 it works fine. Sticking on 4.2.0 for now.

**Comment by petermajor** [comment]
Using a version of nuget which isn't supported by Xamarin Studio (unless you're on alpha) really limits the amount of people who can use this release...

It kinda reminds me of the release you guys did a little while back that would only compile if you were on a beta version of mono...

Did this change really need to be done right now?

**Comment by Cheesebaron** [comment]
@petermajor: Yes. Otherwise we couldn't release because the project couldn't build.

Also, Xamarin Studio has had its NuGet package manager neglected for ages, we can't wait around till someone at Xamarin gets the time to work on it.

**Comment by drungrin** [comment]
The pcl issue I mentioned happened within visual studio 2015, latest nuget. It doesn't install on pcl259.

Enviado do Outlook Mobile




On Thu, Jul 7, 2016 at 5:26 AM -0300, "Tomasz Cielecki" <notifications@github.com> wrote:












@petermajor: Yes. Otherwise we couldn't release because the project couldn't build.



Also, Xamarin Studio has had its NuGet package manager neglected for ages, we can't wait around till someone at Xamarin gets the time to work on it.

**Comment by kjeremy** [comment]
@drungrin Right because 259 supports silverlight.  Since MvvmCross doesn't anymore you need to remove silverlight from your profile.

**Comment by drungrin** [comment]
And some wiki entries, like 

https://github.com/MvvmCross/MvvmCross/wiki/Tip-Calc---The-Core-Project

which explicitly states about the profile 259.

**Comment by ernesto** [comment]
No one have idea for stable xamarin studio nuget System.Collections.Concurrent issue? Using alpha software is very danger for real world applications.

**Comment by Cheesebaron** [comment]
@drungrin the statement about Profile 259 is from September 2014. Things have changed a lot since then.
