### ISSUE TITLE
MVVMCross 4.2.1 System.Collections.Concurrent and PCL Issue

### ISSUE THREAD

**Issue by Noires** [MvvmCross/MvvmCross#1388]
Basically since 4.2.1 the Systems.Collections.Concurrent which got added doesnt fit to my core library, since it is an PCL.

> 
> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Could not install package 'System.Collections.Concurrent 4.0.12'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

**Version:** 4.2.1

**Comment by Cheesebaron** [comment]
Change the target to something less insane?

**Comment by Noires** [comment]
Changed it now.

Though the insane settings were based on https://github.com/MvvmCross/MvvmCross/wiki/Tip-Calc---The-Core-Project . So probably have to adjust that then.

**Comment by Cheesebaron** [comment]
Feel free to do so. Will make an announcement about Silverlight being phased out.

**Comment by Noires** [comment]
Could you give me an appropriate Target Setting for this?
With another profile i seem not be able to install the framework anymore, since the Profile is not 259 (Dependency).

**Comment by Cheesebaron** [comment]
Profile 7 works fine

**Comment by Noires** [comment]
Thanks! Though reverted back for now, since just had warnings for conflicts between assemblies, will postpone it for now.

**Comment by Cheesebaron** [comment]
Fixed in 4.2.2
