### ISSUE TITLE
After upgrade from 4.1.6 to 4.2.1 can't build UWP project

### ISSUE THREAD

**Issue by UnderHeavyDevelopment** [MvvmCross/MvvmCross#1391]
After **upgrade from 4.1.6 to 4.2.1** I can't build **Windows UWP** project with **PCL targeted for portable45-net45+win8**.

### Steps to reproduce

1. In **Nuget**, select MvvmCross packages and click **Update**
2. Delete **C:\Users\username\ .nuget** directory (steps 3. and 4. are optional)
3. In Visual Studio, right click on UWP project and select **"Restore Nuget packages"**
4. **Rebuild** solution

### Expected behavior
No errors after rebuild.

### Actual behavior
Following errors after build:
```
Payload contains two or more files with the same destination path 'Microsoft.Win32.Primitives.dll'. Source files: 
C:\Users\username\.nuget\packages\Microsoft.Win32.Primitives\4.0.0\lib\dotnet\Microsoft.Win32.Primitives.dll
C:\Users\username\.nuget\packages\runtime.win.Microsoft.Win32.Primitives\4.0.1\runtimes\win\lib\netstandard1.3\Microsoft.Win32.Primitives.dll (1, 1)

Payload contains two or more files with the same destination path 'System.Diagnostics.Tools.dll'. Source files: 
C:\Users\username\.nuget\packages\runtime.any.System.Diagnostics.Tools\4.0.1\lib\netcore50\System.Diagnostics.Tools.dll
C:\Users\username\.nuget\packages\System.Diagnostics.Tools\4.0.0\lib\netcore50\System.Diagnostics.Tools.dll (1, 1)

Payload contains two or more files with the same destination path 'System.Globalization.Calendars.dll'. Source files: 
C:\Users\username\.nuget\packages\runtime.any.System.Globalization.Calendars\4.0.1\lib\netcore50\System.Globalization.Calendars.dll
C:\Users\username\.nuget\packages\System.Globalization.Calendars\4.0.0\lib\netcore50\System.Globalization.Calendars.dll (1, 1)

Payload contains two or more files with the same destination path 'System.Threading.Timer.dll'. Source files: 
C:\Users\username\.nuget\packages\runtime.any.System.Threading.Timer\4.0.1\lib\netcore50\System.Threading.Timer.dll
C:\Users\username\.nuget\packages\System.Threading.Timer\4.0.0\lib\netcore50\System.Threading.Timer.dll (1, 1)

Payload contains two or more files with the same destination path 'System.Net.Sockets.dll'. Source files: 
C:\Users\username\.nuget\packages\runtime.win.System.Net.Sockets\4.1.0\runtimes\win\lib\netcore50\System.Net.Sockets.dll
C:\Users\username\.nuget\packages\System.Net.Sockets\4.0.0\lib\netcore50\System.Net.Sockets.dll (1, 1)`
```

### Configuration

**Version:** 4.2.1
**Platform:** Windows UWP, PCL (portable45-net45+win8)
**Packages being updated:** MvvmCross, MvvmCross.Binding, MvvmCross.Core, MvvmCross.Platform
**Nuget version:** 3.4.4.1321

**Comment by MartinZikmund** [comment]
I have faced the same issue, only downgrade to 4.2.0 helped.

**Comment by Cheesebaron** [comment]
I think the problem lies in System.Collections.Concurrent, as it pulls in a lot of dependencies.

What happens if you create a new UWP project and reference that nuget? I can't currently test myself as I am not near a Windows machine currently. Can check later tomorrow though.

**Comment by UnderHeavyDevelopment** [comment]
I created **new UWP project (no PCL)**.
Nuget upgrade of MvvmCross to 4.2.1 in this case gives me the following error:
```
Restoring packages for 'App2'.
Restoring packages for C:\App2\project.json...
Version conflict detected for System.Collections. 
 App2 (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> System.Net.Sockets (>= 4.0.0) -> runtime.win.System.Net.Sockets (>= 4.1.0) -> System.Collections (>= 4.0.11) 
 App2 (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-arm (>= 1.0.0) -> System.Collections (= 4.0.10).
Package restore failed for 'App2'.
```
Then during the build (after clean & restore nuget packages), I get the same errors as in issue description.

**Comment by UnderHeavyDevelopment** [comment]
Bringing problem to its most, I distilled these two situations:
(perform on a clean UWP solution)

1. When installing **MvvmCross** (main package) there is a Nuget error:
```
Restoring packages for 'test'.
Restoring packages for C:\test\project.json...
Version conflict detected for System.Collections. 
 test (>= 1.0.0) -> MvvmCross (>= 4.2.1) -> MvvmCross.Binding (>= 4.2.1) -> System.Collections.Concurrent (>= 4.0.12) -> System.Collections (>= 4.0.11) 
 test (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-arm (>= 1.0.0) -> System.Collections (= 4.0.10).
Package restore failed for 'test'.
Package restore failed. Rolling back package changes for 'test'.
========== Finished ==========
```


2. When installing **MvvmCross.Bindings** there is a Nuget error:
```
Restoring packages for 'test'.
Restoring packages for C:\test\project.json...
Version conflict detected for System.Collections. 
 test (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> System.Net.Sockets (>= 4.0.0) -> runtime.win.System.Net.Sockets (>= 4.1.0) -> System.Collections (>= 4.0.11) 
 test (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-arm (>= 1.0.0) -> System.Collections (= 4.0.10).
Package restore failed for 'test'.
Package restore failed. Rolling back package changes for 'test'.
========== Finished ==========
```

**MvvmCross.Core and MvvmCross.Platform installs with no errors.**

**Solution:**
Please notice, this errors are with project that targets **Microsoft.NETCore.UniversalWindowsPlatform v5.0.0**. When I've updated to **Microsoft.NETCore.UniversalWindowsPlatform v5.1.0** (which in fact I had visible in nuget update day later than MvvmCross update) than I can install MvvmCross v4.2.1 and build.

**Comment by Cheesebaron** [comment]
The problem seems to be with the System.Collections.Concurrent package. I've sent a message to the nuget package owners of System.Collections.Concurrent to see if they have any suggestions.

**Comment by ericstj** [comment]
So the errors about a specific version you're seeing with Microsoft.NETCore.UniversalWindowsPlatform 5.0.0: System.Collections (**=** 4.0.10) were addressed with the update to Microsoft.NETCore.UniversalWindowsPlatform 5.1.0.  Still with this set of packages there are issues consuming the latest CoreFx packages due to changes we had to make to support cross-platform .NET Core.  Those were all addressed with Microsoft.NETCore.UniversalWindowsPlatform 5.2.0, but we had to temporarily unlist that package to fix some issues (https://github.com/dotnet/corefx/issues/9743 and https://github.com/dotnet/corefx/issues/9711).  We're working on updates and expect a new version to be out shortly.

If you'd like to test out our internal build of these updates you can pick up Microsoft.NETCore.UniversalWindowsPlatform 5.2.1 from https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.

**Comment by Cheesebaron** [comment]
@ericstj Thanks for the reply. We might look into removing this dependency temporarily until you get it fixed in UniversalWindowsPlatform and released to stable. This package also causes other issues with Xamarin.Studio as the stable version does not use NuGet >=2.12 and it doesn't install nicely.

**Comment by Cheesebaron** [comment]
We've removed the dependency on that NuGet. Try again with latest NuGet 4.2.2
