### ISSUE TITLE
New MvxListView bindings not working since last xamarin update

### ISSUE THREAD

**Issue by osc117** [MvvmCross/MvvmCross#1395]
Hello,

Since last xamarin stable update i can't create any new MvxListView  binding in my xamarin android - mvvmcross project. All bindings done before this update still works. If i create a copy paste one of my working MvxListView, the old one will keep working as usual, but the new one will be empty (displayed but no child elements). My app does not crash at any moment.

If i try to bind any kind of collection to a MvxListView or MvxLinearLayout, nothing happens. When i try to interact with the view supposed to contains my collection, the output says :`AbsListView(26069): Intent to operate on non-exist data, childcount=0, mFirstPosition=0, mItemCount=0, adapter count=0, mAdapter=md5bf0126c95bf9fc0db24c02c9adb4cfa7.MvxAdapter@3fbd5398, action=1, mActivePointerId=0, mScrollY=0, this=mvvmcross.binding.droid.views.MvxListView{12a517f1 V.ED.VC. ........ 15,15-196,912}`

I tried registering a new custom binding on a view inheriting from MvxListView as a workaround, but the code in my MvxAndroidTargetBinding is never reached.
Yet inside Setup.cs the registry.RegisterFactory is reached.

I encountered this problem on Mvvmcross 4.2.1 first, so i updated it to 4.2.2 but the bug still occurs. I guess i will have to downgrade Xamarin to work out this, but i would like to know if anyone else met this behaviour and fixed it before doing so.
### Expected behavior

Should be able to bind ObservableCollection<T>, List<T> to MvxListView
### Actual behavior

Can't bind ObservableCollection or List to MvxListView or MvxLinearLayout, or custom view inheriting from them. Can't register new MvxCustomBindingFactory.
### Configuration

Windows 10, Visual Studio 2015 Community

**Version:** 4.2.2

**Platform:** Android

**Comment by kjeremy** [comment]
Can you give us a sample program? Did you delete your bin and obj
directories after upgrading?

**Comment by osc117** [comment]
Yep i deleted the folders. I posted a some code on stackoverflow : http://stackoverflow.com/questions/38332069/mvvmcross-xamarin-cannot-create-any-mvxlistview-anymore
i don't believe i would be able to reproduce this bug on a brand new project, as there would be lot more people complaining that me if anyone had the impossibility to use binding on MvxListViews since last update

**Comment by martijn00** [comment]
Can't reproduce this. Please provide a reproduction sample on Github so we can look into this.
