### ISSUE TITLE
MvvmCross.Platform.Exceptions.MvxException: You must call EnsureLoaded on the File plugin before using the DownloadCache

### ISSUE THREAD

**Issue by foxanna** [MvvmCross/MvvmCross#1399]
### Steps to reproduce

I create a new Touch project with MvvmCross referenced. 
I add references to MvvmCross.Plugins.File and MvvmCross.Plugins.DownloadCache plugins. FilePluginBootstrap and DownloadCachePluginBootstrap classes are created. 

### Actual behavior

When I run this empty app I receive MvvmCross.Platform.Exceptions.MvxException: You must call EnsureLoaded on the File plugin before using the DownloadCache.
If I use this answer http://stackoverflow.com/a/38232077/2452764 exception changes to MvvmCross.Platform.Exceptions.MvxException: Could not find plugin loader for type MvvmCross.Plugins.File.PluginLoader.

### Configuration

**Version:** This problem was introduced around version 4.2.1.

**Platform:** iOS

**Comment by tbalcom** [comment]
There is already an incident for this issue in the Plugins repository.  Some workarounds are presented there.  Please see https://github.com/MvvmCross/MvvmCross-Plugins/issues/119.

**Comment by foxanna** [comment]
Thanks, Trevor! Sorry for bothering.
