### ISSUE TITLE
Mvx.Trace crashes app when logging JSON

### ISSUE THREAD

**Issue by alexsorokoletov** [MvvmCross/MvvmCross#1400]
### Steps to reproduce
1. 

```
 var someJson = JsonConvert.SerializeObject(ViewModel); //could be even new object();
 Mvx.Trace(someJson);
```
### Expected behavior

MvxTrace should be able to trace JSON to the console without any exceptions, even handled.
### Actual behavior

App is crashing on iOS. App throws handled exception on Android
<img width="690" alt="screenshot 2016-07-18 12 44 15" src="https://cloud.githubusercontent.com/assets/1788581/16923100/8cb51eb6-4ce6-11e6-83a5-5c1fb229e9d5.png">

Callstack:

```
System.Text.StringBuilder.FormatError() in /Users/builder/data/lanes/3339/39ebb778/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/text/stringbuilder.cs:1321
System.Text.StringBuilder.AppendFormatHelper(System.Globalization.CultureInfo provider, string format, System.ParamsArray args) in /Users/builder/data/lanes/3339/39ebb778/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/text/stringbuilder.cs:1371
string.FormatHelper(System.Globalization.CultureInfo provider, string format, System.ParamsArray args) in /Users/builder/data/lanes/3339/39ebb778/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/string.cs:2979
string.Format(System.Globalization.CultureInfo provider, string format, object[] args) in /Users/builder/data/lanes/3339/39ebb778/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/string.cs:2972
System.IO.TextWriter.WriteLine(string format, object[] arg) in /Users/builder/data/lanes/3339/39ebb778/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/io/textwriter.cs:544
System.IO.TextWriter.SyncTextWriter.WriteLine(string format, object[] arg) in /Users/builder/data/lanes/3339/39ebb778/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/io/textwriter.cs:873
System.Console.WriteLine(string format, object[] arg) in /Users/builder/data/lanes/3339/39ebb778/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/corlib/System/Console.cs:470
MvvmCross.iOS.Platform.MvxDebugTrace.Trace(MvvmCross.Platform.Platform.MvxTraceLevel level, string tag, string message, object[] args) in D:\git\MvvmCross\MvvmCross\iOS\iOS\Platform\MvxDebugTrace.cs:28
MvvmCross.Platform.Platform.MvxTrace.MvvmCross.Platform.Platform.IMvxTrace.Trace(MvvmCross.Platform.Platform.MvxTraceLevel level, string tag, string message, object[] args) in D:\git\MvvmCross\MvvmCross\Platform\Platform\Platform\MvxTrace.cs:141
MvvmCross.Platform.Platform.MvxTrace.TaggedTrace(MvvmCross.Platform.Platform.MvxTraceLevel level, string tag, string message, object[] args) in D:\git\MvvmCross\MvvmCross\Platform\Platform\Platform\MvxTrace.cs:38
MvvmCross.Platform.Mvx.TaggedTrace(MvvmCross.Platform.Platform.MvxTraceLevel level, string tag, string message, object[] args) in D:\git\MvvmCross\MvvmCross\Platform\Platform\Mvx.cs:188
```

We're using a custom trace class to handle this problem with following code. It's better than anything but still this _handled_ exception disturbs during debugging.
<img width="747" alt="screenshot 2016-07-18 12 51 04" src="https://cloud.githubusercontent.com/assets/1788581/16923134/b77ba5c0-4ce6-11e6-9ca2-da2c269683b6.png">
### Configuration

**Version:** 4.2.0 and higher, can be reproduced on 3.5 and up.

**Platform:** iOS/Android
I assume platforms WPF/Windows Store/Windows Phone Store/Windows UWP have same problem as well.

**Comment by kjeremy** [comment]
Version 4.0.0 means what exactly?  Are you on the latest MvvmCross and the latest STABLE Xamarin?

**Comment by alexsorokoletov** [comment]
On 3.5 and up to the latest

**Comment by kjeremy** [comment]
And latest Xamarin stable?  You can absolutely reproduce this on Android as well?

This sounds really suspicious.  I've used `Mvx.Trace` with JSON before and I don't see this problem.  Are you sure all of your nuget packages (including `Newtonsoft.Json`) are up to date?  Also: if you switched nuget packages did you delete your `bin` and `obj` directories and uninstall/reinstall your app?  I've seen issues like this before that have been a result of Xamarin not updating things properly.

**Comment by alexsorokoletov** [comment]
@kjeremy Android doesn't crash the app but still throws an exception that is later handled. As I wrote it's disturbing during development.
Here is a repro project.
https://github.com/alexsorokoletov/MvvmCross-Samples/tree/dev-json-issue/TipCalc

**Comment by flyingxu** [comment]
I had this issue before. This is not a Mvx.Trace issue, actually it's related to StringBuilder. See the source code at
[https://referencesource.microsoft.com/#mscorlib/system/text/stringbuilder.cs,1369](https://referencesource.microsoft.com/#mscorlib/system/text/stringbuilder.cs,1369)

It has special case for `{` and `}` which are also in a json string. 

I don't know which exact pattern of json string (I'm guessing the `{...{...` pattern) leads to the issue, but the work around is to use this line during output json string:

    Mvx.Trace(json.Replace("{", "{{").Replace("}", "}}"));
