### ISSUE TITLE
Bug MasterDetail duplicate lines top

### ISSUE THREAD

**Issue by moreirawebmaster** [MvvmCross/MvvmCross#1401]
When viewing a page layout Master Page doubles the line at the top of the devices, also doubling toolbaritens

### Steps to reproduce

1. Create xaml with MasterDetailPage

2. Execute in iOS, Android, Win

3. Verify in top two lines

### Expected behavior
Correct the duplicate rows in master-detail layout

### Actual behavior
Duplicate line up master detail.

### Configuration

**Version:** 4.2.2

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

![masterdetail](https://cloud.githubusercontent.com/assets/1142139/16970944/0db0d81a-4df6-11e6-9e7a-e4c5fe425f56.png)

**Comment by Cheesebaron** [comment]
Please produce some proper reproduction steps.

**Comment by moreirawebmaster** [comment]
Steps to reproduce

Create xaml with MasterDetailPage

Execute in iOS, Android, Win

Verify in top two lines
