### ISSUE TITLE
WeakSubcribe an EventHandler without EventArgs?

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross#1402]
I'm using a library which exposes an event defined as:
`event EventHandler ScanTimeoutElapsed;`
I need to weaksubscribe this event, but it seems to me that the MvxWeakEventSubscription class works only with events defined as:
`event EventHandler<TEventArgs>`

Is there a way to weaksubscribe this kind of events? 
Or I'm forced to create a new version of the MvxWeakEventSubscription class?

**Comment by Cheesebaron** [comment]
For that I usually Rx.Net

**Comment by kjeremy** [comment]
I have an implementation of this in my [weak-subscribe](/kjeremy/mvvmcross/tree/weak-subscribe) branch.  I'll merge it eventually but you should be able to grab the file and extension methods and use them yourself.

**Comment by IlSocio** [comment]
Thanks to both of you :)
