### ISSUE TITLE
Seems there is no way to refresh the MvxPageViewController with new data

### ISSUE THREAD

**Issue by chrilith** [MvvmCross/MvvmCross#1403]
Hi @scastria,

This controller is really nice but I didn't found a way to refresh data or invalidate the cache dictionary.

Let's say you have a list of page data which is empty at startup, then you load REST data and update your list. The page view should update accordingly, which mean clear the current page view state and use the new data from the list.

Looking at the code, I don't see ho to perform this.

Is it possible or is this an issue?

Thanks!

**Comment by scastria** [comment]
If I remember correctly, I did not code in that feature.  I created this out of my need which did not require changing the pages during runtime.  sorry.

**Comment by chrilith** [comment]
OK but can you consider adding this feature?

Also the caching system is interesting but should not be the default behavior. Imagine if you have 50 images in a page view, you should really not want to cache everything. Caching should be up to the developer and not forced to a specific implementation.

I think this should be as generic as possible. What is your thought on this?

Thanks!
Chris

**Comment by scastria** [comment]
I agree.  Unfortunately, I just do not have the time to do it.  I would be happy to review a pull request if you want to make the change, though.

**Comment by chrilith** [comment]
OK np. Will have some questions to fully understand your code. First, what is the initial purpose of `NavigateToViewModel()` and is there any reason why it id not used in `InitializePaging()` using `defaultVM`?

**Comment by scastria** [comment]
I think my intent of NavigateToViewModel was to allow the caller to specify a ViewModel to navigate to instead of specifying a ViewController.  Maybe if you had a Command in some VM somewhere that wanted to switch current pages, it could do so by specifying another VM since a VM should not know about the View.  However, since the NavigateToViewModel is on the View (MvxPageViewController), maybe my intent doesn't makes sense.

No reason why I didn't use it in InitializePaging on the defaultVM.  I could have.  I guess I missed it.

**Comment by chrilith** [comment]
OK @scastria thanks for clarifying things. I haven't tested this method but I really think it make sense in the logic of your implementation.

Thanks again.

**Comment by nickrandolph** [comment]
@chrilith has this issue been resolved?

**Comment by chrilith** [comment]
Hi @nickrandolph,

Well since #1675 hasn't been merge I guess it is no,t unless there is a new implementation in 5.x or current 6.x.

I must admit that I currently haven't time to check all this.
I'll be able to check everyhing only after we plan to migrate to latest version of MvvmCross which may not arise before the end of this year :(
