### ISSUE TITLE
Bug MasterDetail duplicate toolbar

### ISSUE THREAD

**Issue by moreirawebmaster** [MvvmCross/MvvmCross#1406]
When viewing a page layout Master Page doubles the line at the top of the devices, also doubling toolbaritens.

Please VERIFY;

issue closed #1401

Steps to reproduce

Create xaml with MasterDetailPage

Execute in iOS, Android, Win

Verify in top two lines

Expected behavior

Correct the duplicate rows in master-detail layout

Actual behavior

Duplicate line up master detail.

Configuration

Version: 4.2.2

Platform: iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by Cheesebaron** [comment]
This issue belongs in the Samples repository. Please reopen there.
