### ISSUE TITLE
Reloading the Main Activity : Navigation Stops working

### ISSUE THREAD

**Issue by glalwani2** [MvvmCross/MvvmCross#1408]
Hi All,

In my main activity I want to reload the activity as I want the app to reload since the user is logging in.
I dont know if thats a good idea but when I am validating the user credentials and calling these lines of code in my main activity.

```
var viewGroup = (ViewGroup)((ViewGroup)FindViewById(Android.Resource.Id.Content)).GetChildAt(0);
viewGroup.RemoveAllViews();
Finish();
StartActivity(Intent);
```

WHat happens is that the screen flashes and the activity is loaded again from scratch(that doesnt not look mature). The problem is the app works fine but the navigation stops working when I call

`ShowViewModel(SomeViewModel);`

I know I am doing something wrong, or may be not following the best practise here. My only intent is to reload the application setting the flags and load the users profile making the user feel as if the user was already logged in.

**Version:** 4.1.4

**Platform:** Xamarin Android

**Comment by hakim-ali** [comment]
ShowViewModel(SomeViewModel); stop working in my project, after updating to Version: 4.2.2

**Comment by Cheesebaron** [comment]
Doesn't sound like the best solution. Rather you should just load the next activity logged in and clear the backstack instead. That would be a much cleaner approach.
