### ISSUE TITLE
Updating From 4.1 to 4.2.2 breaks UITableViewAutomaticDimension

### ISSUE THREAD

**Issue by yairsz** [MvvmCross/MvvmCross#1409]
After updating nuget packages from MVVMCross 4.1 to 4.2.2 the functionality of UITableViewAutomaticDimension is broken, there was absolutely no code changes on my end. I'm investigating but wanted to post this issue to see if anyone else has run into this yet

**Comment by yairsz** [comment]
In the blog [post](https://mvvmcross.com/blog/mvvmcross-42) for the 4.2 release there is a comment about an update to the binding context.

I managed to patch the issue by registering the old context in Setup.cs with:
```
protected override void InitializeLastChance()
{
    base.InitializeLastChance();
    Mvx.RegisterType<IMvxBindingContext, MvxBindingContext>();
}
```

However this points to a deeper issue in the binding context update.

If anybody can take a look at this it would be great. Thank you!

**Comment by softlion** [comment]
Hi, cCould you provide a sample project demonstrating the issue ?

**Comment by softlion** [comment]
The new context binder does most of its work in a worker threads. This greatly improves latencies of binding in lists and collections, which became all smooth on my app instead of being choppy. Maybe your cell is not completly bound when its size is computed by the tableview.

A repro project would be perfect as i don't have much time creating repros.

**Comment by Cheesebaron** [comment]
A reproduction sample would be very appreciated :)

**Comment by yairsz** [comment]
Hello guys, thanks for your replies.
I created a [repository ](https://github.com/yairsz/UITableViewBugDemo) with a project where I'll try to reproduce this issue. Unfortunately I can't post the actual project where I'm having the issue.
So far in this demo project I haven't been able to reproduce the problem, it seems that the automatic dimension feature is working for both binding contexts. However there's a lot more going on in the original project. I will try to find and isolate the issue if I can. If I can't I'll close this issue.

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/1442
