### ISSUE TITLE
Close(this) is not working for Theme.Dialog on configuration change

### ISSUE THREAD

**Issue by DummyCo** [MvvmCross/MvvmCross#1411]
### Steps to reproduce
1. Call new activity with **android:style/Theme.Dialog** theme from existing one via **ShowViewModel**.
2. Change screen orientation
3. Try to close topmost activity via **Close(this)** call on related ViewModel

Sample:
https://github.com/DummyCo/VmCloseIssueSample
### Actual behavior

Nothing happens
### Configuration

**Version:** 4.2.2

**Platform:** Android

**Comment by nmilcoff** [comment]
Closing this issue as deprecated, since MvvmCross 5.2 introduced a new ViewPresenter (and your issue should be solved in it). 

Please open a new issue if this is still a problem for you.
