### ISSUE TITLE
Decimal zero not correctly interpreted when used as part of boolean expression

### ISSUE THREAD

**Issue by HEBOS** [MvvmCross/MvvmCross#1418]
## Steps to reproduce

1.
Create binding something like:
MvxBind="If(MyProperty==0,'Is zero',,'Isnt zero')"

### Expected behavior
We should get "Is zero" statement.
Should we specifiy 0.0 or 0m or anything else.

Later, I tried different approach:
a) created property called EmptyDecimal using:

public decimal EmptyDecimal { get; private set; } = 0;

then in my axml used:
MvxBind="If(MyProperty==EmptyDecimal,'Is zero',,'Isnt zero')"

and voila it is working, but it is really silly solution.

### Actual behavior
You will get "Isnt zero" statement.

### Configuration

**Version:** 4.2.3

**Platform:** Android

**Comment by kjeremy** [comment]
Is there an exception being thrown?  Anything in the logs?

**Comment by HEBOS** [comment]
Nothing

**Comment by Cheesebaron** [comment]
Does it work if you change to `double` or `float`?

**Comment by HEBOS** [comment]
Float works as expected, only decimal type fails.

**Comment by Cheesebaron** [comment]
And is this only on Android or does this also happen on other platforms?

**Comment by HEBOS** [comment]
Don't know. We use Android only.

**Comment by Cheesebaron** [comment]
OK, thanks, just making sure I test on the correct platform :)

**Comment by Cheesebaron** [comment]
Just made a small test where I added the following props in my VM:

    public double Doub => 0.0;
    public float Flot => 0.0f;
    public decimal Dec => 0.0m;

Then used following binding expressions:

    Text If(Doub==0,'Double Is Zero','Double Not Zero')
    Text If(Flot==0,'Float Is Zero','Float Not Zero')
    Text If(Dec==0,'Decimal Is Zero','Decimal Not Zero')

As you describe, decimal comparison shows "Decimal Not Zero". Looking through the binding combiners, there doesn't seem to anything for decimals for equality comparisons: https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Core/Binding/Combiners/VeryExperimental/MvxEqualToValueCombiner.cs

**Comment by HEBOS** [comment]
Great.
It means the implementation"object, object" has been choosen, so that is why if we compare two properties, both having zero as value, comparison works as expected.
I believe CLI is interpreting (hardcoded right side of expression in axml) zero as int, or long, and that is why comparison fails.
I see that in MvvmCross mostly double is implemented, and I is not easy to add support for decimal, so for now the workaround is:
- having one fixed property on every viewmodel that is initialized always with zero decimal for example **private DecimalZero {get; private set;} = 0;**
- in AXML use
**local:MvxBind="Text If(MyProperty==DecimalZero, 'true','false')"**
Other, perhabs better workaround is to create **DecimalCastValueConverter** that returns decimals so that we can use syntax:
**local:MvxBind="Text If(MyProperty==DecimalCast(0), 'true','false')"**
I hope that MvvmCross team will reconcider to implement decimal also.

**Comment by Cheesebaron** [comment]
Pull requests are welcome

**Comment by willsb** [comment]
@Cheesebaron Are there any known problems that prevent the implementation of `CombineDecimalAndX`? It sounds like a more reasonable solution than a `DecimalCastConverter`. Also, I can implement this one :)

**Comment by Cheesebaron** [comment]
I don't think there should be any problems with this. Not that I am aware of.

**Comment by HEBOS** [comment]
willsb,
if you implement CombineDecimalAndX in MvxEqualToValueCombiner you should also implement it in:
MvxGreaterThanOrEqualToValueCombiner
MvxGreaterThanValueCombiner
MvxLessThanOrEqualToValueCombiner
MvxLessThanValueCombiner
MvxNotEqualToPairwiseValueCombiner
