### ISSUE TITLE
MvxTaskBasedBindingContext issue with dynamic cell's height in iOS

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#1423]
The datacontext of each cell is set by MvxListView when it dequeues a cell. The datacontext setter (which is a MvxTaskBasedBindingContext ) triggers OnDataContextChange which sets the DataContext of each registered cell binding asynchronously. 
The cell may not know its height fast enough for autoheight to work. This is an issue in iOS when using dynamic cell's heights, where a cell can have an invalid height. And on Android when scrolling fast down or up where there may be some jump artifacts. 

DataContext setter in
https://github.com/MvvmCross/MvvmCross/blob/master/MvvmCross/Core/Binding/BindingContext/MvxTaskBasedBindingContext.cs

GetCell in
https://github.com/MvvmCross/MvvmCross/blob/master/MvvmCross/Binding/iOS/Views/MvxBaseTableViewSource.cs

A solution would be to create a new SynchronousDataContext property, and use this in MvxListView to set the DataContext instead of the original interface. Another solution would be to have a SetDataContextAsync() method and wait for this async task in MvxListView when iOS asks for the cell's height. The second one will have the best performances, as it let the task run between calls to GetCell and GetCellHeight.

**Comment by softlion** [comment]
Note that you can easily switch to the legacy binding context, see the instructions there:

https://mvvmcross.com/v3.2/blog/mvvmcross-42

**Comment by PelleRavn** [comment]
@softlion For some reason (meaning, I haven't found the reason yet), the fix for going back to the legacy binding context doesn't work for 4.3.0, so the issue you are mentioning happens no matter if you use MvxTaskBasedBindingContext or just MvxBindingContext.

**Comment by MarcBruins** [comment]
I'm busy trying to fix this issue but i don't have a good enough understanding what goes on right now. Love some help (i'm on slack). Already made some changes and added a test project: https://github.com/MarcBruins/MvvmCross/tree/feature/dynamicheightios

**Comment by softlion** [comment]
Marc i just reviewed and answered you on slack. Seems very good. Simply remember that you will never achieve 60fps in your list because of this code. Maybe add a small comment over it to explain the case. You'll need to do the same change in collection views.

**Comment by PelleRavn** [comment]
So, now that it's closed should we open a new issue for collection views as @softlion mentioned?

> You'll need to do the same change in collection views.

**Comment by martijn00** [comment]
Yes! Please do! I think @MarcBruins had some concerns on that.

**Comment by MarcBruins** [comment]
PelleRavn, auto resizing collection view is tricky to implement from my understanding and it's difficult to check if it is actually autoresizing. So please do create another issue because i think this is not so easy to fix. Furthermore the Android artefacts should be addressed to, but i don't know what the problem there is exactly. However the fix the PR used could be used there as well.

**Comment by jernelson7** [comment]
I am facing the same issue binding other properties to a custom cell with text/images/etc. The cell's LayoutSubviews is invoked before the bindings have been applied with the new DataContext.

**Comment by softlion** [comment]
I suppose this should also be set in MvxTableViewCell and MvxCollectionViewCell

            if (BindingContext is MvxTaskBasedBindingContext taskBasedBindingContext)
            {
                //Suppose we always use automatic dimension
                taskBasedBindingContext.RunSynchronously = true;
            }

**Comment by nmilcoff** [comment]
@softlion I think so, yes! Can you please open a new issue for that? And a PR would be great, if you don't mind 🙂
