### ISSUE TITLE
MvvmCross initialization support for IntentService, BroadcastReceiver

### ISSUE THREAD

**Issue by thefex** [MvvmCross/MvvmCross#1425]
Currently MvvmCross officially does not support IntentService and BroadcastReceivers.
IntentService and BroadcastReceiver can be created/launched when application is not running (in killing phase).
That makes custom IntentService/BroadcastReceiver **MIGHT** crash application when IntentService/BroadcastReceiver is triggered while app is not running - MvvmCross setup is not initialized therefore calls like Mvx.Resolve<.> does not work.

**Comment by kjeremy** [comment]
Do this:

```
var setupSingleton = MvxAndroidSetupSingleton.EnsureSingletonAvailable(this.ApplicationContext);
setupSingleton.EnsureInitialized();
```

**Comment by thefex** [comment]
I know that :) I just think this needs to be standarized. PR gonna arrive in 5 minutes

**Comment by kjeremy** [comment]
Ahh I thought it was a complaint.  PRs are awesome :)

**Comment by thefex** [comment]
People should start use MvxIntentService/MvxBroadcastReceiver - that should fix initialization problems.

**Comment by vvolkgang** [comment]
@thefex also happens on other platforms / contexts and something similar is required. In a Console App I'm currently doing this:
```
MvvmCross.Platform.IoC.MvxSimpleIoCContainer.Initialize();
new App().Initialize();
```
Setups IoC and registers everything I
