### ISSUE TITLE
Crash when rehydrating an activity on Android 2.3.3

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [MvvmCross/MvvmCross#1431]
Hi Guys,

Sorry to paste another old version support ticket. I have a crash when resuming a killed activity on Gingerbread. I think I have tracked down the issue and it should be an easy fix.

https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Droid/Shared/Caching/FragmentCacheConfiguration.cs

Line 79 of FragmentCacheConfiguration is: 
var jsonSerializedMvxCachedFragmentInfosToRestore = savedInstanceState.GetString(SavedFragmentCacheConfiguration, string.Empty);

The two-parameter version of GetString was only added in API 12. I get a 
--- End of managed Java.Lang.LinkageError stack trace ---
java.lang.NoSuchMethodError: getString

I should fix this myself and submit it but I haven't done any contribution to open source projects before and i'm up against it time wise now. I think I can just get around it for now by implementing my own IFragmentCacheConfiguration and I could submit that to you guys later, but thought I would leave this here for reference.

ref: http://stackoverflow.com/questions/11110423/nosuchmethoderror-bundle-getstring

Stack trace:
`
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<02ac62c3fdaf441e9ee685b96b58e01f>:0 Java.Interop.JniEnvironment.InstanceMethods.GetMethodID(JniObjectReference type, string name, string signature)<73799bd7c7d240a593c179aa25d95da8>:0 Java.Interop.JniType.GetInstanceMethod(string name, string signature)<73799bd7c7d240a593c179aa25d95da8>:0 Java.Interop.JniPeerMembers.JniInstanceMethods.GetMethodInfo(string encodedMember)<73799bd7c7d240a593c179aa25d95da8>:0 Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractObjectMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<73799bd7c7d240a593c179aa25d95da8>:0 Android.OS.Bundle.GetString(string key, string defaultValue)<57cd949090814c899fef02a7093a0e49>:0 MvvmCross.Droid.Shared.Caching.FragmentCacheConfiguration<TSerializableMvxCachedFragmentInfo>.RestoreCacheConfiguration(Bundle savedInstanceState, IMvxJsonConverter serializer)<5c30ca2740474a4caba948f65c45bca4>:0 MvvmCross.Droid.Support.V7.AppCompat.MvxCachingFragmentCompatActivity.OnCreate(Bundle bundle)<bb699048950d4b7a866f0fb9cdbc113a>:0 MyApp.Droid.Library.Activities.NavigatingCompatActivity.OnCreate(Bundle bundle)<084e8f50ab1c4571bc7ed0dbd177d292>:0 MyApp.Droid.Library.Activities.LoginActivity.OnCreate(Bundle bundle)<084e8f50ab1c4571bc7ed0dbd177d292>:0 Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)<013f8eacb1954462a2f9d5f677673fee>:0 at (wrapper dynamic-method) System.Object:93d6b6f7-e9e4-4878-aa14-38510af4e53b (intptr,intptr,intptr) --- End of managed Java.Lang.LinkageError stack trace --- java.lang.NoSuchMethodError: getString md523ad908f92b2244901ec22e48c58badc.LoginActivity.n_onCreate(Native Method) at md523ad908f92b2244901ec22e48c58badc.LoginActivity.onCreate(LoginActivity.java:29) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675) at android.app.ActivityThread.access$1500(ActivityThread.java:121) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:130) at android.app.ActivityThread.main(ActivityThread.java:3768) java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:507) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) dalvik.system.NativeStart.main(Native Method)
`

Cheers :)

**Comment by RyanBuzzInteractive** [comment]
ref: http://stackoverflow.com/questions/11110423/nosuchmethoderror-bundle-getstring

**Comment by RyanBuzzInteractive** [comment]
`System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<02ac62c3fdaf441e9ee685b96b58e01f>:0
Java.Interop.JniEnvironment.InstanceMethods.GetMethodID(JniObjectReference type, string name, string signature)<73799bd7c7d240a593c179aa25d95da8>:0
Java.Interop.JniType.GetInstanceMethod(string name, string signature)<73799bd7c7d240a593c179aa25d95da8>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.GetMethodInfo(string encodedMember)<73799bd7c7d240a593c179aa25d95da8>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractObjectMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<73799bd7c7d240a593c179aa25d95da8>:0
Android.OS.Bundle.GetString(string key, string defaultValue)<57cd949090814c899fef02a7093a0e49>:0
MvvmCross.Droid.Shared.Caching.FragmentCacheConfiguration<TSerializableMvxCachedFragmentInfo>.RestoreCacheConfiguration(Bundle savedInstanceState, IMvxJsonConverter serializer)<5c30ca2740474a4caba948f65c45bca4>:0
MvvmCross.Droid.Support.V7.AppCompat.MvxCachingFragmentCompatActivity.OnCreate(Bundle bundle)<bb699048950d4b7a866f0fb9cdbc113a>:0
MyApp.Droid.Library.Activities.NavigatingCompatActivity.OnCreate(Bundle bundle)<084e8f50ab1c4571bc7ed0dbd177d292>:0
MyApp.Droid.Library.Activities.LoginActivity.OnCreate(Bundle bundle)<084e8f50ab1c4571bc7ed0dbd177d292>:0
Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)<013f8eacb1954462a2f9d5f677673fee>:0
at (wrapper dynamic-method) System.Object:93d6b6f7-e9e4-4878-aa14-38510af4e53b (intptr,intptr,intptr)
--- End of managed Java.Lang.LinkageError stack trace ---
java.lang.NoSuchMethodError: getString
md523ad908f92b2244901ec22e48c58badc.LoginActivity.n_onCreate(Native Method)
at md523ad908f92b2244901ec22e48c58badc.LoginActivity.onCreate(LoginActivity.java:29)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
at android.app.ActivityThread.access$1500(ActivityThread.java:121)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3768)
java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
dalvik.system.NativeStart.main(Native Method)`

**Comment by Cheesebaron** [comment]
Please. Instead of making new comments edit your opening post. What you are doing here is spamming us.

**Comment by RyanBuzzInteractive** [comment]
Sorry, I didn't realise.
