### ISSUE TITLE
Add PreserveAttribute on classes known to always be used

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1432]
When using Full Linking a lot of stuff is stripped away from MvvmCross having the developer to track down everything and added loads of entries to LinkerPleaseInclude or excluding assemblies from linking.

Adding `[Preserve]` on classes which are known to always be used would be a great help.

**Comment by willsb** [comment]
This is awesome! I have a default string of excluded assemblies that I always include in every project, so this is something I'd like to work on. 

Plugins could also benefit from this. In the case of plugins, I believe every class can be Preserved. Regarding MvvmCross, I'll draft a list of classes that should be preserved.

**Comment by azchohfi** [comment]
Since almost everything on MVX can be replaced, I'm still not sure how this list is going to be even possible... Really not sure if this should be done. Maybe something added to LinkerPleaseInclude.cs?

**Comment by kjeremy** [comment]
I think a lot of it can be done though.  User controls, widgets base
classes, MvxActivity/MvxFragment and their attributes, all of the binding
machinery etc.

**Comment by willsb** [comment]
As weird as it may sound, I have a reasonably large project where absolutely nothing in the Core project crashed when I used the "Link All Assemblies" flag without the "Ignore Assemblies" string. The Plugins were the only problem.
