### ISSUE TITLE
ActionBar title stay black with Theme Material.Light.DarkActionBar

### ISSUE THREAD

**Issue by viniciusmaia** [MvvmCross/MvvmCross#1440]
I'm tried to use MvxActivity with theme @android:style/Theme.Material.Light.DarkActionBar and the ActioBar title is always black. I tried many things to solve that, but nothing works. I had to use MvxAppCompatActivity with Theme.AppCompat.Light.DarkActionBar to have white text in Action Bar title.

Version: I tested with versions 4.2.0 and 4.3.0

Platform:Android

**Comment by Cheesebaron** [comment]
This is not a MvvmCross issue. MvvmCross does nothing actively to change styles on your Toolbar.

**Comment by viniciusmaia** [comment]
But I tested with MvvmCross and without MvvmCross and this issue occurs only when I'm used MvxActivity. I tested with the Activity that is generated by xamarin when a android project is created and just add MvvmCross to my project, extended MainActivity from MvxActivity and the issue occurr. After, I change the base class to Activity and works.

**Comment by Cheesebaron** [comment]
Will reopen if you provide a repro sample

**Comment by kjeremy** [comment]
This may have something to do with our layout inflater factory and
interaction with
https://github.com/android/platform_frameworks_support/blob/432f3317f8a9b8cf98277938ea5df4021e983055/v7/appcompat/src/android/support/v7/app/AppCompatViewInflater.java
where inherited theme contexts only work when inflating inside
AppCompatViewInflater.
