### ISSUE TITLE
Calling ShowViewModel on activity, does not show child fragment

### ISSUE THREAD

**Issue by dot-ly** [MvvmCross/MvvmCross#1441]
Following the MvvmCross sample here [https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/master/Samples](url)

I am trying to show an activity, that contains a fragment. When I call ShowVIewModel on the Activity, I see the activity, without the fragment. 

But if I call ShowViewModel, the Activity AND the Fragment are created. 

Does this mean, in order to show a fragment I need to call ShowViewModel on the fragment and not on the parent activity?  surly I should be able to call ShowViewModel on the activity and have that create the fragment. 

Sorry if i'm missing something here.

Thanks

**Comment by martijn00** [comment]
You indeed need to call ShowViewModel on the fragment. MvvmCross will handle the parent. This is more a StackOverflow question. Please open one there if you need more information.
