### ISSUE TITLE
MvxDialogViewController does not Dispose after assigning the Root element

### ISSUE THREAD

**Issue by mrodriguez-rts** [MvvmCross/MvvmCross#1445]
To help us fix your issue, please provide the information in the below template. 
### Steps to reproduce
1. Set up a basic project with two view controllers FirstViewController and SecondViewController.  SecondViewController should be a subclass of MvxDialogViewController.
2. Configure FirstViewController to push SecondViewController (modal or push, it doesn't matter)
3. In SecondViewController, assign Root. `Root = new RootElement();` is enough.  Add the override for Dispose and set a breakpoint within it.
4. Run the app and navigate to SecondViewController then navigate back.
### Expected behavior

Dismissing SecondViewController should cause its Dispose method to be called.
### Actual behavior

Dispose/Finalize never get called.

I've managed to work around this issue by adding `TableView.Source = null;` in ViewDidDisappear.  The Dispose method is invoked shortly after SecondViewController is dismissed.
### Configuration

**Version:** 4.3.0

**Platform:** iOS 9.3

**Comment by Cheesebaron** [comment]
Dialogs have been removed.
