### ISSUE TITLE
Apps based on MvvmCross 4.3 crash right after started in iOS 10 emulator

### ISSUE THREAD

**Issue by teddymacn** [MvvmCross/MvvmCross#1452]
Hi Guys,

I'm using VS2015 and latest version of Xamarin SDK: Xamarin.VisualStudio_4.2.0.695. At Mac side, I have OSX 10.11.6 and Xcode8 and MonoFramework-MDK-4.6.0.245 + xamarin.ios-10.0.0.6.

When I try to run or debug any MvvmCross based app in an VS iOS 10 emulator, it simply crash right after app started, no log I could see in VS console or debug windows.

At the same time, any other iOS apps using Xamarin official template or the Prism iOS template just worked fine. So I think it should be a bug of MvvmCross, but I have no clue how to figure out the root problem.

### Steps to reproduce

1. Create a simply MvvmCross Forms app with the latest version of VS2015 MvvmCross Xamarin Forms template;

2. Target an iOS 10 emulator and try to debug the iOS app;

3. It crashes right after app started;

### Expected behavior
It should just work as expected.

### Actual behavior
Just crash right after started the app for debugging in any iOS 10 emulator.

### Configuration

**Version:** 4.3.0

**Platform:** iOS

**Comment by Cheesebaron** [comment]
Can you please check the device event log if something is present there?

**Comment by teddymacn** [comment]
@Cheesebaron, thx for quick response, below is the full system.log for a crash. I delete the system.log of the device and started a app debugging from VS2015 targetting a iOS 10 iPhone 6s emulator:

Oct  7 15:27:12 Teddys-Mac CoreSimulatorBridge[13852]: Pasteboard change listener callback port <NSMachPort: 0x7fa4b15053e0> registered
Oct  7 15:27:12 Teddys-Mac CoreSimulatorBridge[13852]: Requesting installation of file:///Users/teddy/Library/Caches/Xamarin/mtbs/builds/MvvmCrossForms1.iOS/d30baecc0b8e3cfba4c6728594c0d58e/bin/iPhoneSimulator/Debug/XamFormsMvxTemplateiOS.app with options: {
	    CFBundleIdentifier = "com.companyname.MvvmCrossForms1.iOS";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/teddy/Library/Developer/CoreSimulator/Devices/C48840E1-FB3E-4170-9362-A3D01B772475/data";
	}
Oct  7 15:27:12 Teddys-Mac installd[13838]: 0x70000021d000 -[MIClientConnection _doInstallationForURL:withOptions:completion:]: Install of "/Users/teddy/Library/Caches/Xamarin/mtbs/builds/MvvmCrossForms1.iOS/d30baecc0b8e3cfba4c6728594c0d58e/bin/iPhoneSimulator/Debug/XamFormsMvxTemplateiOS.app" type Developer (LSInstallType = (null)) requested by CoreSimulatorBridge (pid 13852)
Oct  7 15:27:12 Teddys-Mac installd[13838]: 0x70000021d000 MDMCreateDeltaDirectory: calling MDMDirectoryDiff with:
	state->old_bundle: /Users/teddy/Library/Developer/CoreSimulator/Devices/C48840E1-FB3E-4170-9362-A3D01B772475/data/Containers/Bundle/Application/0065B02E-016E-43E3-8950-33D2DB65B3C8/XamFormsMvxTemplateiOS.app
	state->new_bundle: /Users/teddy/Library/Caches/Xamarin/mtbs/builds/MvvmCrossForms1.iOS/d30baecc0b8e3cfba4c6728594c0d58e/bin/iPhoneSimulator/Debug/XamFormsMvxTemplateiOS.app
	state->dst_bundle: /Users/teddy/Library/Developer/CoreSimulator/Devices/C48840E1-FB3E-4170-9362-A3D01B772475/data/Library/Caches/com.apple.mobile.installd.staging/temp.GplK5f/extracted/Payload//XamFormsMvxTemplateiOS.app, binaryDiff flag: FALSE
		dst_ipa: /Users/teddy/Library/Developer/CoreSimulator/Devices/C48840E1-FB3E-4170-9362-A3D01B772475/data/Library/Caches/com.apple.mobile.installd.staging/temp.GplK5f/extracted
Oct  7 15:27:12 Teddys-Mac installd[13838]: 0x700000117000 __MDMDirectoryDiff_block_invoke.37: calling writeDictToFile with: /Users/teddy/Library/Developer/CoreSimulator/Devices/C48840E1-FB3E-4170-9362-A3D01B772475/data/Library/Caches/com.apple.mobile.installd.staging/temp.GplK5f/extracted/ManifestCache.plist
Oct  7 15:27:12 Teddys-Mac installd[13838]: 0x700000117000 writeDictToFile: ==== Successfully wrote Manifest cache to /Users/teddy/Library/Developer/CoreSimulator/Devices/C48840E1-FB3E-4170-9362-A3D01B772475/data/Library/Caches/com.apple.mobile.installd.staging/temp.GplK5f/extracted/ManifestCache.plist
Oct  7 15:27:12 Teddys-Mac installd[13838]: 0x70000021d000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundlePatch ID=com.companyname.MvvmCrossForms1.iOS; Version=1.0, ShortVersion=1.0>
Oct  7 15:27:12 Teddys-Mac installd[13838]: 0x70000021d000 -[MIInstallableBundlePatch applyPatchWithError:]: Attempting patch update of com.companyname.MvvmCrossForms1.iOS from 1.0 (1.0) to 1.0 (1.0)
Oct  7 15:27:13 Teddys-Mac syslogd[13828]: Disabling module com.apple.appinstallation writes to /var/mobile/Library/Logs/CrashReporter/DiagnosticLogs/AppInstallation/AppInstallation.log following 6 failures (Operation Failed)
Oct  7 15:27:13 Teddys-Mac installd[13838]: 0x70000021d000 -[MIInstallableBundle _refreshUUIDForContainer:withError:]: Data container for com.companyname.MvvmCrossForms1.iOS is now at /Users/teddy/Library/Developer/CoreSimulator/Devices/C48840E1-FB3E-4170-9362-A3D01B772475/data/Containers/Data/Application/3B55E06B-742B-4389-8B4B-8A531DCF0B5F
Oct  7 15:27:13 Teddys-Mac installd[13838]: 0x70000021d000 -[MIContainer makeContainerLiveReplacingContainer:reason:withError:]: Made container live for com.companyname.MvvmCrossForms1.iOS at /Users/teddy/Library/Developer/CoreSimulator/Devices/C48840E1-FB3E-4170-9362-A3D01B772475/data/Containers/Bundle/Application/F0095AD3-35D1-44AE-95E1-25E3557AB5BE
Oct  7 15:27:13 Teddys-Mac installd[13838]: 0x70000021d000 -[MIInstaller performInstallationWithError:]: Install Successful; Staging: 0.06s; Waiting: 0.00s; Preflight/Patch: 0.20s, Verifying: 0.03s; Overall: 0.69s
Oct  7 15:27:13 Teddys-Mac com.apple.CallKit.CallDirectory[13914]: [Default] Unable to initialize CXCallDirectoryStore for reading and writing: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “CallDirectory” in the folder “Library”." UserInfo={NSFilePath=/var/mobile/Library/CallDirectory, NSUnderlyingError=0x7ff70150d450 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
Oct  7 15:27:13 Teddys-Mac callservicesd[13899]: [Default] Error synchronizing call directory extensions: Error Domain=com.apple.CallKit.error.calldirectorymanager Code=0 "(null)"
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.mobilemail
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] throwing out icon because it isn't visible in the model : node=<SBApplicationIcon: 0x6080001c6540; nodeID: 'com.apple.camera'> com.apple.camera
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.mobiletimer
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.weather
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.mobilenotes
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.stocks
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.videos
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.iBooks
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.MobileStore
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.AppStore
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.Home
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.facetime
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.calculator
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.podcasts
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.compass
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.tips
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.VoiceMemos
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.mobileme.fmf1
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.mobileme.fmip1
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.mobilephone
Oct  7 15:27:13 Teddys-Mac SpringBoard[13843]: [Common] could not find icon for representation -> com.apple.Music
Oct  7 15:27:16 Teddys-Mac CoreSimulatorBridge[13852]: Requesting launch of com.companyname.MvvmCrossForms1.iOS with options: {
	    arguments =     (
	        "-monodevelop-port",
	        54705
	    );
	    environment =     {
	        "DYLD_INSERT_LIBRARIES" = "/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/monotouch-fixes.dylib";
	    };
	}
Oct  7 15:27:16 Teddys-Mac CoreSimulatorBridge[13852]: [Common] [FBSSystemService][0x6da4] Sending request to open "com.companyname.MvvmCrossForms1.iOS"
Oct  7 15:27:17 Teddys-Mac CoreSimulatorBridge[13852]: [Common] [FBSSystemService][0x6da4] Request successful: <FBSProcessHandle: 0x7fa4b150b070; XamFormsMvxTemp:13930; valid: YES>
Oct  7 15:27:37 Teddys-Mac SpringBoard[13843]: [Watchdog] [com.companyname.MvvmCrossForms1.iOS] Provision violated for watchdog process-launch: <FBSProcessResourceProvision: 0x60000052d660; allowance: <FBSProcessResourceAllowance; type: realTime; timeValue: 20.0s; unitCount: 1>; violated: YES>
Oct  7 15:27:37 Teddys-Mac com.apple.CoreSimulator.SimDevice.C48840E1-FB3E-4170-9362-A3D01B772475.launchd_sim[13826] (UIKitApplication:com.companyname.MvvmCrossForms1.iOS[0x245e][13930]): Service exited due to Killed: 9
Oct  7 15:27:37 Teddys-Mac assertiond[13847]: notify_suspend_pid() failed with error 7
Oct  7 15:27:53 Teddys-Mac cfprefsd[13857]: [User Defaults Daemon] attempt to write to a container /var/Managed Preferences/mobile that does not yet exist. Using client-provided container path without resolving symlinks.
Oct  7 15:27:53 Teddys-Mac geod[13864]: [] nw_host_stats_add_src recv too small, received 24, expected 28
Oct  7 15:27:53 Teddys-Mac geod[13864]: [] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
Oct  7 15:27:53 Teddys-Mac geod[13864]: [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.1.8
	    0   libsystem_network.dylib             0x0000000105fd980e __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x0000000106173194 nw_socket_add_input_handler + 3002
	    2   libnetwork.dylib                    0x0000000106150db8 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x000000010614fdd5 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x000000010614eb34 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x0000000106169d11 nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x0000000106169740 nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x0000000106181003 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x000000
Oct  7 15:28:33 Teddys-Mac routined[13832]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104

**Comment by teddymacn** [comment]
Hi Guys,

I got some progress on this. After I deleted all the previous deployed apps in this emulator, the debugging of MvvmCrossForm app in this emulator magically began to work. Still don't know why. But worthy to try if someone else meets the same problem.

Teddy

**Comment by martijn00** [comment]
Let's close this for now. I've seen apps without MvvmCross crash on iOS10 on first start. Removing indeed fixed it.
