### ISSUE TITLE
Cancel method declaration missing in IMvxAsyncCommand

### ISSUE THREAD

**Issue by thebigbadorg** [MvvmCross/MvvmCross#1454]
The `IMvxAsyncCommand` interface does not provide a `Cancel()` method.

The `MvxAsyncCommand` and `MvxAsyncCommand<T>` classes are designed to support cancelling a running command execution.
They support this behavior with the method `public void Cancel()`, implemented in their respective base classes `MvxAsyncCommandBase` and `MvxAsyncCommandBase<T>`.

It appears to me, that it has been forgotten to declare this method in the `IMvxAsyncCommand` interface, because without it, it is not possible to cancel a command execution in a clean way while using the interface. If the interface is not being used, their will be the usual unit testing headaches.

I am using a workaround so far (`IMvxAsyncCommand` derived interface implemented in `MvxAsyncCommand` derived class), but framework support for this would be better.

To support his. just change the current implementation of

``` c#
public interface IMvxAsyncCommand : IMvxCommand
{
    Task ExecuteAsync(object parameter = null);
}
```

to

``` c#
public interface IMvxAsyncCommand : IMvxCommand
{
    Task ExecuteAsync(object parameter = null);
    void Cancel();
}
```

**Comment by martijn00** [comment]
Good one! I've added this in https://github.com/MvvmCross/MvvmCross/pull/1455
