### ISSUE TITLE
Add MVVMCross ObservableCollection

### ISSUE THREAD

**Issue by chrislamont** [MvvmCross/MvvmCross#1456]
I have a class inheriting from ObservableCollection. 

This loses some functionality, specifically the ability to RaisePropertyChanged.

Would it be beneficial/possible to implement this within MVVMCross

**Comment by kjeremy** [comment]
Post this on StackOverflow with some code.

**Comment by martijn00** [comment]
I get the idea, and this would be useful for many users. We could add things like `AddRange` to our MvxObservableCollection, and implement `MvxNotifyPropertyChanged` instead of the default one. The question is if we want this in this repo.

**Comment by SeeD-Seifer** [comment]
There was a try once https://github.com/MvvmCross/MvvmCross/pull/212 :)

**Comment by kjeremy** [comment]
@martijn00 I think I misunderstood the issue when I closed this so feel free to reopen if you want.  If we want something like this (I'm not convinced but then again the description on this issue is pretty vague) we should add a way to suppress change notification.

**Comment by martijn00** [comment]
That try actually looks promising! I think we could try to get this in again for 5.0
