### ISSUE TITLE
MvxRegion, with and without for the same page

### ISSUE THREAD

**Issue by Naografix** [MvvmCross/MvvmCross#1457]
Hello

I'm working in Xamarin UWP and I have a View which be used by two differents way.
My view is called : MainView

My MainView can be used by my FrameView (with Frame) and WITHOUT Frame.

**MainView**

```
[MvxRegion("MainContent")]
public sealed partial class MainView : MvxWindowsPage
{ 
    public MainView()
    {
        InitializeComponent(); 
    } 
}
```

**FrameView have SplitView with Frame** 

```
<SplitView.Content>
    <Frame x:Name="MainContent">
        <Frame.ContentTransitions>
            <TransitionCollection>
                <NavigationThemeTransition>
                    <NavigationThemeTransition.DefaultNavigationTransitionInfo>
                        <EntranceNavigationTransitionInfo />
                    </NavigationThemeTransition.DefaultNavigationTransitionInfo>
                </NavigationThemeTransition>
            </TransitionCollection>
        </Frame.ContentTransitions>
    </Frame>
</SplitView.Content>
```

HomeView with 2 buttons :

One which switch to the MainView.
And an other which switch to the FrameView which display MainView with a burger menu.

In fact, in my HomeView i have two button, when i clic on the first, i go to the MainView with ShowViewModel<>.
But when i clic on the second, i need to display my View in Frame (because my FrameView have a Burger menu.

And when i click on the first i have this error :

ShowViewModel< MainViewModel >(); -> Region 'MainContent' not found in view 'UWP.Views.MainView'

Thanks

**Comment by Naografix** [comment]
Updated

**Comment by nickrandolph** [comment]
@Naografix can I ask you to reproduce this using the playground UWP sample and submit as a PR. We can assist with finding a resolution

**Comment by martijn00** [comment]
This works different now with the new presenters. Please open a new issue if there are problems.
