### ISSUE TITLE
Potential deadlock in MvxAndroidSetupSingleton

### ISSUE THREAD

**Issue by Nickolas-** [MvvmCross/MvvmCross#1472]
Hello everyone, 
There a problem with inner lock in 

```
ThreadPool.QueueUserWorkItem(ignored =>
                    {
                        this._setup.InitializeSecondary();
                        lock (LockObject)
                        {
                            IsInitialisedTaskCompletionSource.SetResult(true);
                            this._initialized = true;
                            var dispatcher = Mvx.GetSingleton<IMvxMainThreadDispatcher>();
                            dispatcher.RequestMainThreadAction(() =>
                            {
                                this._currentSplashScreen?.InitializationComplete();
                            });
                        }
                    });
```

And with 

```
            lock (LockObject)
            {
                if (this._initialized)
                    return;

                if (IsInitialisedTaskCompletionSource != null)
                {
                    Mvx.Trace("EnsureInitialized has already been called so now waiting for completion");
                    IsInitialisedTaskCompletionSource.Task.Wait();
                }
                else
                {
                    IsInitialisedTaskCompletionSource = new TaskCompletionSource<bool>();
                    this._setup.Initialize();
                    this._initialized = true;

                    if (this._currentSplashScreen != null)
                    {
                        Mvx.Warning("Current splash screen not null during direct initialization - not sure this should ever happen!");
                        var dispatcher = Mvx.GetSingleton<IMvxMainThreadDispatcher>();
                        dispatcher.RequestMainThreadAction(() =>
                        {
                            this._currentSplashScreen?.InitializationComplete();
                        });
                    }

                    IsInitialisedTaskCompletionSource.SetResult(true);
                }
            }

```

in EnsureInitialized method.

 When application init from splashscreen UI thread locked it. Then it will take new thread from thread pool and will intialize secondary and in this time UI thread unlock lock because it will go out from scope of InitializeFromSplashScreen. Everything good here , nothing locked right now. But if in exact same some one (BroadcastRecevier) start EnsureInitialized method , it will lock it by UI thread again and wait until worker thread finished his job in initalized secondary and in that time secondary will finished his work and wait until lock released  by UI thread and this moment we will have deadlock.
### Expected behavior

Remove splash and show some VM
### Actual behavior

Deadlock
### Configuration

**Version:** 4.3.0

**Platform:**Android

**Comment by kjeremy** [comment]
I don't really understand your description.  Can you be more explicity about where the deadlock is?

Do you have a PR for this?  Maybe we need to use a `SemaphoreSlim` and "unlock" it in the various paths instead of one giant mutex.

**Comment by Nickolas-** [comment]
No I don't have a project for this.

1. Start up UI thread lock InitializeFromSplashScreen method.
2. Then take a worker thread from background.
3. Unlock lock InitializeFromSplashScreen.
4. Worker thread doing work in InitializeSecondary().
5. Then UI thread again Lock in method EnsureInitialized and Wait while worker doing InitializeSecondary(). 
6. After worker thread finished he wait until Lock will be released. 
7. Deadlock.

**Comment by Nickolas-** [comment]
Guys, any feedback about this bug ? Maybe I need more detailed answer to you with some screen examples?

**Comment by andyci** [comment]
I'll take a look at this over the next couple of days

**Comment by TamasRusvai** [comment]
Hello, is this merged?

**Comment by vatsalyagoel** [comment]
Hi,
Will this fix be available in 5.x or only in 6.0?

**Comment by nickrandolph** [comment]
At the moment all work is being focussed on v6, so at this stage it'll only be fixed in v6.

**Comment by vatsalyagoel** [comment]
@nickrandolph I'll investigate and check if this fix solves my issue. The described solution and issue is exactly what I'm experiencing

**Comment by martijn00** [comment]
Please reopen this if it still is an issue on 6.0.
