### ISSUE TITLE
Support for Tizen?

### ISSUE THREAD

**Issue by mufid** [MvvmCross/MvvmCross#1488]
So now [Samsung/TIZEN phone support .NET platform](https://developer.tizen.org/development/preview). Will Tizen be in MvvmCross roadmap?

**Comment by Cheesebaron** [comment]
Worth investigating. I don't own any Tizen devices though.

**Comment by tofutim** [comment]
Also curious about this.

**Comment by ghuntley** [comment]
@mufid can you organise for some test devices to be delivered to my house? /cc @Cheesebaron

**Comment by smstuebe** [comment]
@ghuntley I wanted to organize a .Net enabled Tizen device for some investigation. This is what I got:

> "Hello, we (Tizen's Xamarin.forms team) are discussing and going to decide which packaing (app or preinstalled) to go. And current status is only Tizen TV emulator is available (no actual device to test yet) However, there will be Xamarin.Forms running TV devices in this year as announced (please refer to Tizen's .NET and Xamarin related articles). So we are working hard to make it. Thanks."
