### ISSUE TITLE
Implement INotifyPropertyChanging in MvvmCross

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#1489]
* [ ] Implement `INotifyPropertyChanging` in places where we currently implement `INotifyPropertyChanged` (where that makes sense).
* [ ] Allow bindings for `INotifyPropertyChanging`.
* [ ] Update weak subscriptions to support `INotifyPropertyChanging`.

**Comment by Cheesebaron** [comment]
Affirmative. However, this way we need to update bindings to make use of this, no? We are only listening to INotifyPropertyChanged currently.

**Comment by kjeremy** [comment]
We will definitely need to do something with the bindings.  I think a good first step would be to implement the interface for view models though.  That would give us `INotifyPropertyChanging` for XAML at least.

The TargetBindings might be annoying though.  I've never used `INotifyPropertyChanging` for targets in two-way bindings.  Is it even possible?

**Comment by Cheesebaron** [comment]
Does INotifyPropertyChanging work with Xamarin.Forms?

**Comment by kjeremy** [comment]
A quick search of `INotifyPropertyChanging` in the Xamarin.Forms repo suggests that they do not.

**Comment by Cheesebaron** [comment]
Just so I understand this correctly. We are not removing INotifyPropertyChanged in place of INotifyPropertyChanging? INotifyPropertyChanging is just called prior to the property being manipulated, after that operation is done you call INotifyPropertyChanged, right?

**Comment by kjeremy** [comment]
Yes.  The flow is something like the following pseudo code.

```
public void SetProperty<T>(ref T property, T value, string propertyName)
{
    if (Equals(property, value))
         return;

    // Notify that the property is changing...
    PropertyChanging?.Invoke(this, propertyName);

    property = value;

    // Continue on with INotifyPropertyChanged
    PropertyChanged?.Invoke(this, propertyName);
}
```

**Comment by Cheesebaron** [comment]
Alright. Makes sense. Reminds me of KVO on iOS, willChangeValueForKey and didChangeValueForKey.

I guess this is great in cases where you want to have undo/redo logic in place. Can't see much else to use this for.

**Comment by kjeremy** [comment]
I think it's mostly for heavy (long / synchronous) operations when a value
changes so you can notify the user or cancel an operation or something.  I
agree it's not useful very often.

**Comment by nickrandolph** [comment]
@martijn00 @Cheesebaron I think this is actually a great idea, even if it's only to add the INotifyPropertyChanging interface. I'm thinking of adding this to 6.2?
