### ISSUE TITLE
loading views and view models from different assemblies

### ISSUE THREAD

**Issue by raV720** [MvvmCross/MvvmCross#1490]
The problem in details is described here:

http://stackoverflow.com/questions/39044800/mvvmcross-loading-views-and-view-models-from-different-assemblies

Git with source: https://bitbucket.org/equo/mvvmcross_test.git

### Expected behavior
MVVMCROSS should be able to link View and ViewModel by naming convention.

### Actual behavior
MVVMCROSS does not link View and ViewModel by naming convention when are in separate assemblies.

### Configuration

**Version:** 4.4

**Platform:** Windows Store (other patforms not tested)

**Comment by Cheesebaron** [comment]
This is related to Forms. The issue should be in the MvvmCross-Forms repo.
