### ISSUE TITLE
Top-level platform pages are blank

### ISSUE THREAD

**Issue by breyed** [MvvmCross/MvvmCross#1492]
From https://mvvmcross.com/, if you click on any of the **Platform** links, e.g. [Xamarin.Android](https://mvvmcross.com/docs/xamarinandroid), you get a page with no body content.

**Comment by martijn00** [comment]
Feel free to contribute to the content over there.

**Comment by breyed** [comment]
Sorry, but I don't know the MvvmCross project well enough to contribute. I was just looking at the home page to get a first-time overview. I was surprised to see so many dead links right on the project home page. It makes the project seem incomplete or not maintained. It is really the intention to link blank pages right from the home page in the hopes that someone fills them in?
