### ISSUE TITLE
MvxImageView crashes app after garbage collection

### ISSUE THREAD

**Issue by jooni91** [MvvmCross/MvvmCross#1493]
Git sample: https://github.com/jooni91/SetImageBugSample/tree/master/mvvmcross_bug_test

So my app crashes when setting a image to a MvxImageView after garbage collection. This is a issue of local resources. I've tested this with local images and with images from url's. You can find the exception and a better description of this from my question I've posted on Stackoverflow a few weeks ago [here](http://stackoverflow.com/questions/40288300/setimagebitmap-on-imageview-crashes-app-after-garbage-collection).

In my sample I am calling GC.Collect() very frequently and I added 3 MvxImageViews in order to get the bug reproduced. In normal circumstances this crash occurs very randomly, so to get the crash reproduced I had to call the GC.Collect() manually.

### Steps to reproduce

1. Navigate to second page

2. Navigate back to first page

3. Navigate again to second page

4. Repeat the steps until the app crashes, if navigating fast the app crashes mostly on first try.

### Expected behavior
The app should not crash and load the page and the images with the MvxImageView normally.

### Actual behavior
The app crashes when SetImageBitmap() is called after garbage collection.

### Configuration

**Version:** 4.4

**Platform:** Android

**Comment by Cheesebaron** [comment]
Thanks! We'll have a look 👍

**Comment by Cheesebaron** [comment]
This is strange. I can reproduce your issue just fine. One thing that makes me wonder what exactly causes this crash is that we do check whether the `Handle` of the `ImageView` is not `IntPtr.Zero` before we attempt to set the `Bitmap`, we also ensure that the `Bitmap` itself hasn't been recycled too.

Will see if we can do a bit more guarding against this.

**Comment by jooni91** [comment]
Yes I looked into the source and was confused too. Could it be that the GC manages to run after that if statement? Hope you find a solution for this. Would be nice to get an update soon, because my workaround for this issue is far from nice at the moment :D

**Comment by Cheesebaron** [comment]
Added a bit extra guarding in SetImageBitmap:

```
if (Context == null) return;
if (Context.Handle == IntPtr.Zero) return;
var activity = Context as Activity;
if (activity != null)
{
    if (activity.IsFinishing) return;
    if (activity.IsDestroyed) return;
}
```

Now that doesn't crash. However, in your sample it leads to only 1 or 2 of the 3 images appearing.

Kind of sounds to me like the wrong Context is used when binding, which is from the previous Activity and that eventually gets killed off...

**Comment by Cheesebaron** [comment]
Using the old Binding Context doesn't seem to have this issue.

This is definitely related to the MvxTaskBasedBinding doing something wrong. @softlion could we do something about this to make sure we are trying to bind using the correct context?

**Comment by kjeremy** [comment]
Did `RunSynchronously`  make a difference?  I do think we probably need to lock that action or use a cancellation token during dispose just in case.

**Comment by kjeremy** [comment]
@Cheesebaron which case are you hitting in that `Context` guard above that makes it not crash?

**Comment by jooni91** [comment]
Hi! Anything new on this issue?

**Comment by Cheesebaron** [comment]
I think this is a general threading issue. Really hard to figure out why this is happening. If you want something working _now_ try FFImageLoading instead.

**Comment by Cybrosys** [comment]
A bit late to the party, but just experienced this myself, any progress on this?

I have a mater-detail setup, two activites. Going from the first to the second works a couple of times, then the app crashes complaining about a null reference in the first activity's onCreate method. The second activity is the one that loads an image from local storage.

**Comment by kenkosmowski** [comment]
Hey. Any workarounds for that besides using FFImageLoading?

**Comment by Cybrosys** [comment]
My workaround is only to use the ImageUrl property for http paths. For local and embedded resources I'm using the inherited method SetImageURI.

Why? Well, I've only had it crash when using local images, not http, but that might just have been a coincidence...

**Comment by stevecluk** [comment]
Was this crash reproducible on hardware or "only" the emulator?  I've seen the crash on the X86 emulator, but not _yet_ seen it on physical devices (that are arm-based if that helps), and it happened a lot on the emulator (every few mins).

The Xamarin bug jooni had reported (https://bugzilla.xamarin.com/show_bug.cgi?id=46041) refers to the OS as PC Windows so hoping it's an emulator issue unless others have seen it out in the wild...

**Comment by nmilcoff** [comment]
MvxImageView was removed in #2706. Marking this as deprecated.
