### ISSUE TITLE
Update MvvmCross.Starterpack to reflect the new TextView binding.

### ISSUE THREAD

**Issue by JimWilcox3** [MvvmCross/MvvmCross#1499]
Apparently MvvmCross for Android now uses the AfterTextChanged event rather than the TextChanged event for data binding.  The LinkerPleaseInclude.,cs on the Starter Pack still references TextChanged.

### Steps to reproduce

1.  Install MvvmCross.StarterPack.

2.  Bind a TextView to a field in the ViewModel

3.  Compile in release build.

### Expected behavior
Changes on the screen should update the assigned property in the ViewModel.

### Actual behavior
In a debug build, it works fine.  In a release build it doesn't.

### Configuration

**Version:** 4.4.0

**Platform:** Android

**Comment by Cheesebaron** [comment]
Already fixed: https://github.com/MvvmCross/MvvmCross/commit/3fb34c5df072a43e907dd264c3ae666826346682
