### ISSUE TITLE
Fix references in sub projects

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1506]
Now we've moved the sub repo's into the main repo, we need to fix all the references to not use nugets.

- [x] Fix all the references #1507
- [x] Fix output paths
- [x] Fix nuspecs
- [x] Fix nuget content

**Comment by kjeremy** [comment]
The references that do use nuget (like Android support) are pointed at the
wrong package directory.  They need to point one level up. IE
`../../packages`

**Comment by martijn00** [comment]
@kjeremy Yeah, that's leftover from moving them from the root to a subfolder.

**Comment by martijn00** [comment]
I've added some tasks in this issue to track what we still need to do.

**Comment by kjeremy** [comment]
I'm still having issues with Support.Design.  For some reason it's not resolving Mono.Android and the nuget package references.

**Comment by kjeremy** [comment]
@Cheesebaron I believe you have completed this?

**Comment by martijn00** [comment]
This is not complete yet. The nuspecs needs to be fixed, and i think not all outputs are correct yet.

**Comment by Cheesebaron** [comment]
Yeah, nugets need to be fixed with correct paths. I think I fixed it for some of them.
