### ISSUE TITLE
Cannot/how to set LayoutManager for children RecyclerViews bound with local:MvxItemTemplate - XML local:layoutManager does not work

### ISSUE THREAD

**Issue by batrand** [MvvmCross/MvvmCross#1512]
Git repository: [BitBucket](https://bitbucket.org/batrand/mvxbug_nesteditemrecycler)
Screenshot: 

![screenshot](https://i.imgur.com/6tJYcjc.png "screenshot")

### Steps to reproduce

(ViewModel is FirstViewModel)

1. In FirstView.axml add an MvxRecyclerView with 
```
local:MvxItemTemplate="@layout/item_card" 
local:MvxBind="ItemsSource Cards"
local:layoutManager="android.support.v7.widget.LinearLayoutManager"
android:orientation="vertical"
```

2. In item_card.axml create a CardView that contains another MvxRecyclerView with 
```
local:MvxItemTemplate="@layout/item_card_rec" 
local:MvxBind="ItemsSource Members"
local:layoutManager="android.support.v7.widget.LinearLayoutManager"
android:orientation="horizontal"
```

3. In item_card_rec.axml create a Button with 
`local:MvxBind="Text Name"`

### Expected behavior
The buttons inside each Card should span horizontally and scrollable, like the first card.

### Actual behavior
The buttons are stacked vertically, and cannot scroll inside the Card.

### Configuration

**Version:** 4.4.0

**Platform:** Android

### Comments

[RecyclerViews have XML attributes for declaring LayoutManager in XML](https://stackoverflow.com/questions/35679776/how-to-set-recyclerview-applayoutmanager-from-xml#35680716).  What is interesting is that while the local:layoutManager does not work for MvxRecyclerView, the main RecyclerView that contains the Cards themselves is still functioning as expected despite having the layout manager setting code in FirstView.cs commented out.

For the first sample Card to work, I had to set its LayoutManager in FirstView.cs manually. I don't know how to do that for items inflated from MvxItemTemplate in code, and the XML attribute route does not work, as have demonstrated above. 

Removing the sample card's LayoutManager setting code in FirstView.cs and the RecyclerView inside the Card would still scroll, albeit vertically.

**Problem/TL;DR**: 

- RecyclerView inside CardView inside RecyclerView needs a LayoutManager set to work as expected. 
- That CardView is inflated by local:MvxItemTemplate from AXML.
- I don't know how to set LayoutManager for views inflated by MvvmCross from MvxItemTemplate.
- RecyclerViews are supposed to have a local:layoutManager and android:orientation for setting its LayoutManager in AXML but MvxRecyclerView does not seem to be aware of these attributes.

**Comment by Cheesebaron** [comment]
So I guess the problem is because of this line: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.V7.RecyclerView/MvxRecyclerView.cs#L35

It explicitly sets a LinearLayoutManager withouth taking the attributes into account.

**Comment by kjeremy** [comment]
The code to create the layout manager via attributes is private.  See https://github.com/android/platform_frameworks_support/blob/3619a79ce14c2d0d1e0c528ce1941c07796ce2fb/v7/recyclerview/src/android/support/v7/widget/RecyclerView.java#L566

`createLayoutManager` is called in the constructor.  @batrand: The fix may be as simple as wrapping the line that @Cheesebaron suggested in a `null` check on the layout manager.

**Comment by batrand** [comment]
@kjeremy what do you mean by "on the layout manager"? I don't understand that. I tried
````
if(GetLayoutManager() != null) 
    SetLayoutManager(new LinearLayoutManager(context)); 
````
but that changed nothing; the buttons are still stacked vertically and the XML attributes remain ignored. Do we have to reimplement `createLayoutManager` ourselves?

For the time being, for my use case, I hard-coded an MvxRecyclerView subclass to `SetLayoutManager(new LinearLayoutManager(context) { Orientation = Horizontal });` and it works.

**Comment by Cheesebaron** [comment]
It should be

```
if(GetLayoutManager() == null) 
    SetLayoutManager(new LinearLayoutManager(context)); 
```

**Comment by batrand** [comment]
I tried that in an MvxRecyclerView subclass, but it does not work.
