### ISSUE TITLE
cant get connection

### ISSUE THREAD

**Issue by PereAlmendro** [MvvmCross/MvvmCross#1513]
```
public class service
	{
                string DBNAME="DBname.db3";
		readonly IMvxSqliteConnectionFactory _sqliteConnectionFactory;
                SQLiteConnection dbCon;
                public service()
		{
			createDatabase();
		}
		private void createDatabase()
		{
			dbCon = _sqliteConnectionFactory.GetConnection(DBNAME);  //crash here
			dbCon.CreateTable<table>();
		}
}
```

Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.

using mvvmcross 4.4.0 without xamarin.Forms
I'm forgetting something ?

**Comment by Cheesebaron** [comment]
You forgot to set `_sqliteConnectionFactory` to an instance?

**Comment by PereAlmendro** [comment]
in the docs i see that i have to have to inject the factory in my class through the constructor or through property injection. i want to do it through property injection, but i don't know how to "inject through property"

**Comment by Cheesebaron** [comment]
First of all you need a property and not a member variable. Second of all you need to tell the IoC that you want Property Injection. This is done by overriding `CreateIocOptions` and providing the appropriate options for the IoC. It is all in the docs. https://github.com/MvvmCross/MvvmCross/wiki/Service-Location-and-Inversion-of-Control#what-if-i-want-to-use-property-injection-as-an-ioc-mechanism
