### ISSUE TITLE
ItemAppearing Event Starts onLoad list view insted of on item appear

### ISSUE THREAD

**Issue by PereAlmendro** [MvvmCross/MvvmCross#1533]
i'm on mvvmcross 4.4.0 is there any workaround for a infinite scroll that not implies ItemAppearing event ?

**Comment by Cheesebaron** [comment]
Sorry, it is unclear what you are asking here. Is there a bug you want to report? What workaround do you want?

**Comment by PereAlmendro** [comment]
`local:MvxBind="ItemAppearing loadMore"` -- 

this should run loadMore loadMore command each time an element of the MvxListView appears on screen right?. I think there's a bug, as loadMore command runs when MvxListView loads

**Comment by martijn00** [comment]
Look into this: https://www.sequence.co.uk/news/sequence-contributes-infinite-scroll-plugin-for-mvvmcross-and-xamarin

https://www.nuget.org/packages/Sequence.Plugins.InfiniteScroll/

**Comment by PereAlmendro** [comment]
Thank you @martijn00 i've found that too, but i dont think this issue has to be closed...... ItemAppearing still not working.... or maybe i dont understand the utility of ItemAppearing. well anyway , thanks
