### ISSUE TITLE
Android Activity with initially enabled EditText causes System.Environment.Exit() call to hang

### ISSUE THREAD

**Issue by lauxjpn** [MvvmCross/MvvmCross#1538]
If you create an `MvxActivity` derived Activity and let it load an initially enabled `EditText` (either from a layout xml file or from code, either implicitly or explicitly enabled), calling `System.Environment.Exit()` afterwards will result in the application to hang indefinitely.
If the `EditText` has been initially disabled, `System.Environment.Exit()` will work just fine. Also, changing the enabled/disabled state at a later time has no impact on the outcome.
It does not matter, if the EditText is bound to anything in the ViewModel or not. It just has to exist.

**How to recreate the issue:**
I created a [test project](https://github.com/lauxjpn/ExitTest02) to show the problem. After the app has loaded in the debugger, use the back button to call `System.Environment.Exit()`. The call will hang.
In `ExitTest02.Droid\Resources\layout\activity_some.xml:12` change `android:enabled="true"` to `android:enabled="false"`. Run the app again and use the back button to call `System.Environment.Exit()`. This time it works.

**Comment by kjeremy** [comment]
Does it happen with a non-Mvx activity? Does being in or out of the
debugger make a difference?

**Comment by lauxjpn** [comment]
> Does it happen with a non-Mvx activity?
No, this issue does not occur with a vanilla Android `Activity` or `AppCompatActivity`. I uploaded the [as expectedly working test case](https://github.com/lauxjpn/ExitTest01) to show that.
> Does being in or out of the debugger make a difference?
No, the System.Environment.Exit() call hangs regardless of a debugger being attached or not.

**Comment by kjeremy** [comment]
Can you access the threads window and see what's happening? If you call
Java's process.exit do you see the same thing?

**Comment by lauxjpn** [comment]
> Can you access the threads window and see what's happening?

![threads](https://cloud.githubusercontent.com/assets/14178357/21283176/d1c7ff34-c430-11e6-86e8-1a5b6b6acd98.png)

> Java's process.exit do you see the same thing?

Interestingly, `Java.Lang.JavaSystem.Exit()` is working just fine.

**Comment by kjeremy** [comment]
Filed a bug here: https://bugzilla.xamarin.com/show_bug.cgi?id=51421

**Comment by nickrandolph** [comment]
@lauxjpn @kjeremy is this still an issue? and is it an issue related to MVX?

**Comment by kjeremy** [comment]
It was reported to xamarin.  I'll see if I can dig up the bug.  I do not
believe it was fixed.
