### ISSUE TITLE
iOS crash/ <unknown> <0xffffffff>/ Foundation.NSObject.ReleaseManagedRef /Foundation.NSObject/NSObject_Disposer.Drain

### ISSUE THREAD

**Issue by slown1** [MvvmCross/MvvmCross#1539]
Here is a minimal repo in which the problem can be reproduced:
[https://github.com/slown1/MvvmCross-Crash](https://github.com/slown1/MvvmCross-Crash)

I am using the latest stable MvvmCross and Xamarin tools.

### Steps to reproduce
You can see in the screencasts above:
Steps: 
     Press on the button on the main screen
     Press the select all people toggle
     Go back
     Expand the menu
     Tap on shift templates
     Close
     Go to Home
     Tap on another Menu item 
     Go to Home
     Press on the button on the main screen 
     [By now it should how crashed]

NOTE: If you use the simulator, the menu part breaks directly...
            If you use a read device the choose people part breaks after you access it the second time.
            It seems sometimes, that it confuses the correct view controller to show even though the MvxRequest has the correct view model. It breaks because of this with crashes like:
            Could not cast VC1 to VC2, missing outlet and if just dies. The screencasts are self explanatory.

[stacktrace-useful-3.txt](https://github.com/MvvmCross/MvvmCross/files/660431/stacktrace-useful-3.txt)
[stacktrace-useful-2.txt](https://github.com/MvvmCross/MvvmCross/files/660432/stacktrace-useful-2.txt)
[Stack-trace-useful1.txt](https://github.com/MvvmCross/MvvmCross/files/660433/Stack-trace-useful1.txt)
[stacktrace-useful-5.txt](https://github.com/MvvmCross/MvvmCross/files/660434/stacktrace-useful-5.txt)

https://www.screencast.com/t/ykWYoQ4zeCu

### Expected behavior
It should not break

### Actual behavior
See screencast attached above.

### Configuration

**Version:** 4.4

**Platform:** iOS

I am using XamarinSideBar from the support repo.

**Comment by Cheesebaron** [comment]
So first of all. This isn't a MVP, you have loads of code that fetches things from a Web API models etc. What I was looking for when I told you I wanted a MVP, was the minimal amount of code to reproduce this problem, which this obviously is not.

Anyways, I don't understand your usage of the Hamburger menu. When you navigate to an item in the menu, you entirely disregard the center panel and navigate away from it. This is not a good usage of a flat navigation pattern which the Hamburger menu's usually impose.

I did actually find the issue with your app, which lies in your Base*ViewController classes. They don't seem to implement the constructors properly. By simply removing all your Base classes and using what Mvx provides I don't see any crashes anymore.

**Comment by slown1** [comment]
Thank you @Cheesebaron for your time. It seems that added the :base(Handle) solved everything. I will test more just to make sure and then I will come back if need - I hope not.

You may consider the problem solved if I don't say anything until tomorrow.

Thank you so much again.
