### ISSUE TITLE
Binding to Realm IList issue

### ISSUE THREAD

**Issue by batrand** [MvvmCross/MvvmCross#1545]
Git: [Bitbucket](https://bitbucket.org/batrand/mvxbug_realmbinding).

### Steps to reproduce

1. Create model with a dynamic Realm link
````
        public class ModelContainer : RealmObject
	{
		public IList<Model> Models { get; }
	}
````
2. Initiate Realm data in view model
````
                public FirstViewModel()
		{
			Init();
		}

		public void Init()
		{
			var realm = Realm.GetInstance();
			if (realm.All<ModelContainer>().Any() && realm.All<Model>().Any())
			{
				Container = realm.All<ModelContainer>().First();
				return;
			}

			realm.Write(() =>
			{
				var container = new ModelContainer();
				realm.Add(container);

				var model1 = new Model { Name = "One", IsSelected = false };
				//...
				var model6 = new Model { Name = "Six", IsSelected = false };

				realm.Add(model1);
				//...
				realm.Add(model6);

				container.Models.Add(model1);
				//...
				container.Models.Add(model6);

				Init();
			});
		}
````

3. Create a CollectionView in FirstView and a CollectionCell, set up accordingly.

````
        public FirstView() : base("FirstView", null)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = this.CreateBindingSet<FirstView, FirstViewModel>();
            set.Bind(Label).To(vm => vm.Hello);
            set.Bind(TextField).To(vm => vm.Hello);
            set.Apply();

			CollectionView.SetCollectionViewLayout(new UIKit.UICollectionViewFlowLayout
			{
				ItemSize = new CoreGraphics.CGSize(100, 100),
				ScrollDirection = UIKit.UICollectionViewScrollDirection.Horizontal
			}, true);

			CollectionView.RegisterNibForCell(CollectionCell.Nib, CollectionCell.Key);
			var collectionSource = new MvxCollectionViewSource(CollectionView, CollectionCell.Key);
			CollectionView.Source = collectionSource;

			var bindings = this.CreateBindingSet<FirstView, FirstViewModel>();
			bindings.Bind(collectionSource).To(vm => vm.Container.Models);
			bindings.Apply();

			CollectionView.ReloadData();
        }
    }

public partial class CollectionCell : MvxCollectionViewCell
	{
		public static readonly NSString Key = new NSString("CollectionCell");
		public static readonly UINib Nib;

		static CollectionCell()
		{
			Nib = UINib.FromName("CollectionCell", NSBundle.MainBundle);
		}

		protected CollectionCell(IntPtr handle) : base(handle)
		{
			this.DelayBind(() =>
			{
				var bindings = this.CreateBindingSet<CollectionCell, Model>();
				bindings.Bind(Button).For("Title").To(m => m.Name);
				bindings.Bind(Switch).For(s => s.On).To(m => m.IsSelected);
				bindings.Apply();

				Switch.Enabled = false;
			});
		}
	}
````

4. Try scrolling the collection view all the way to the right and then back to the left.

### Expected behavior
The switch states and button titles should remain as they are

### Actual behavior
Switch states and button titles are as they should be, but once they go out of bounds and back again, switches are all set to false and the buttons all lose their titles.

### Remarks
I've tried binding to a normal non-Realm list and it works as expected. This only happens when it's a dynamic Realm list.

### Configuration

**Version:** 4.4

**Platform:** iOS

**Comment by batrand** [comment]
For the record, Realm IList binding works in Android XML as expected, so I have not re-created all the things for that platform in the above repo.

**Comment by UKDeveloper99** [comment]
Got the exact same issue as this guy, dequeuing a cell that has already been created and calls DelayBind breaks when the DataSource is a Realm IList. A reload of the CollectionView will also trigger the same behaviour. It seems the DataContext is lost somehow.

**Comment by kjeremy** [comment]
Is it that the `DataContext` is being set to `null`?

You also have two `CreateBindingSet<FirstView, FirstViewModel>()`.  What if you only create one binding set?

**Comment by UKDeveloper99** [comment]
Well I can't speak for this guys code, but I'm fairly certain my binding code is correct. I just fixed the issue by subclassing MvxCollectionViewSourceAnimated and overriding this method and inserting a null check where the data context is set.

```
			public override UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
			{
				var item = this.GetItemAt(indexPath);
				var cell = this.GetOrCreateCellFor(collectionView, indexPath, item);

				var bindable = cell as IMvxDataConsumer;
				if (bindable != null)
				{
					if (bindable.DataContext == null)
						bindable.DataContext = item;
				}
				return cell;
			}
```

So the data context is only ever set once. I'm not sure if this is correct however, can datacontext change for an item?

**Comment by UKDeveloper99** [comment]
FYI Realm IList's are live containers that directly reflect the data in the Realm database. So when you persist new data to the Realm database it will also be reflected in the UI data if you consume the Realm IList from your UI.

**Comment by kjeremy** [comment]
I'm not familiar with the IOS stuff as much but a general rule for databinding is that `DataContext` is allowed to change and you should expect it to.  It is `IMvxBindingContexts` that do not change as they listen for changes to the `DataContext`.

I would see if you can figure out where the `DataContext` is getting set to `null`.  Maybe you can use inheritance and break points for that.  It's also possible that the `INotifyCollectionChanged` listener that you are probably hitting isn't implemented correctly.

**Comment by UKDeveloper99** [comment]
I've got an inherited class currently so I can inspect values etc. At the moment I'm using the same `GetCell ` logic as the base class. I've checked the value of `item` as it set for the second time, for example scrolling up and down, dequeues a cell that previously existed. The value isn't null. I think something more strange is occurring probably related to the object being a RealmObject. I'll dig a bit further.

**Comment by UKDeveloper99** [comment]
I've confirmed this, setting the DataContext for a second time breaks the bindings, I have a UILabel and a UIImageView set with MvxImageViewLoader(). The picture disappears and the label value becomes null. Even though the value item is **not** null. It contains the exact same data as before.

**Comment by kjeremy** [comment]
If you use an object for a `DataContext` that is NOT a realm object does it work?  I'm finding it odd that setting a new data context causes problems... that shouldn't happen at all.  I'm also wondering if realm uses `WeakReference` magic and that's things are disappearing somehow...

I think we need a reproducible test case and someone who is familiar with the iOS stuff.

**Comment by UKDeveloper99** [comment]
I just checked it with a plain POCO class, **not** a `RealmObject` and it works without issue. So clearly the issue is Related to the class being a `RealmObject`.

**Comment by nirinchev** [comment]
@UKDeveloper99 can you post the implementation of `this.GetOrCreateCellFor(...)`? It definitely feels like the `DataContext` should change for each dequeued cell, otherwise you'll end up with cells showing incorrect information.

**Comment by UKDeveloper99** [comment]
@nirinchev Apologies for the confusion, when I added that code I was naively masking the issue, the same issue exists when I haven't modified anything directly, with the current build for MvvmCross, here is the implementation of `this.GetOrCreateCellFor(...)` directly from the MvvmCross library.
```
        protected virtual UICollectionViewCell GetOrCreateCellFor(UICollectionView collectionView, NSIndexPath indexPath,
                                                                  object item)
        {
            return (UICollectionViewCell)collectionView.DequeueReusableCell(this.DefaultCellIdentifier, indexPath);
}
```

You can find the relevant code in this Collection View Source file here:
https://github.com/MvvmCross/MvvmCross/blob/8a824c797747f74716fc64c2fd0e8765c29b16ab/MvvmCross/Binding/iOS/Views/MvxBaseCollectionViewSource.cs 
that is the base class for the CollectionViewSource you should also take a look at MvxCollectionViewSource and MvxCollectionViewSourceAnimated in the same directory.

The issue disappears completely if you use a simple IList<POCO> collection, the issue occurs when you databind to a live collection, either a RealmObject IList (to-many) or a I assume any IQueryable cast to IRealmCollection as I was getting the same issue when databinding to an IRealmCollection.

**Comment by batrand** [comment]
I'm sorry, the BitBucket link in the original post was faulty; somehow GitHub interprets a link without "http://" prefix as part of GitHub, therefore linking to a nonexistent page. I've edited the link in the original post.

The bug is reproducible; you simply swap IList<RealmObject> for an IList<> with regular C# objects and the issue will disappear. You can check the linked repo out.

**Comment by UKDeveloper99** [comment]
Great saves me the effort. @nirinchev test project! Cheers.

**Comment by Cheesebaron** [comment]
Seems to me that you have an infinite loop in your sample. Calling Init over and over again.

**Comment by batrand** [comment]
I've left work so I don't have access to my Mac, but the Init() method is only called in the ViewModel constructor. Does that mean the constructor itself is in a loop?

**Comment by Cheesebaron** [comment]
It is also called in the realm.Write block and Init is also called by the MvvmCross framework. However it is the realm.Write block that would be looping it.

**Comment by batrand** [comment]
Ah I remember what I did now. That was for first time launches. The Init() code will check if there are ModelContainer and Model instances already stored in the database. If there are then it will load them into the Container property and then stop. If not, it will continue down the code to put the instances into the database, and then call Init() again so that the previous block which would initiate the Container initialization code, and then stop. Basically it should loop exactly once on first launch and never again.

I will debug this on Monday when I have a Mac available.

But in the meantime, you should be able to see the issue as described in my original post despite . Try launching it in the simulator, and see the Models with their checkboxes reflecting their IsSelected state. Scroll past them and back again and you will see all the views disappear.

For now, if you are willing, try this. First try the current code in the simulator despite the loop, the bug should appear as described. Then try changing the classes from RealmObject to pure C#, and the bug should disappear. I'll do this on Monday and push to the repo when I can get to my Mac, but you can try it in the meantime:

1. Remove `: RealmObject` from Model.cs and ModelContainer.cs.
2. Change Init() to this:

```
public void Init()
{
	var model1 = new Model { Name = "One", IsSelected = false };
	var model2 = new Model { Name = "Two", IsSelected = true };
	var model3 = new Model { Name = "Three", IsSelected = true };
	var model4 = new Model { Name = "Four", IsSelected = false };
	var model5 = new Model { Name = "Five", IsSelected = true };
	var model6 = new Model { Name = "Six", IsSelected = false };

	var container = new ModelContainer();
	container.Models.Add(model1);
	container.Models.Add(model2);
	container.Models.Add(model3);
	container.Models.Add(model4);
	container.Models.Add(model5);
	container.Models.Add(model6);

	Container = container;
}
```

After this, retry in the simulator. The bug should disappear.

**Comment by UKDeveloper99** [comment]
I decided to knock up my own test case project as well which should help you guys. I've gone with a slightly different approach to @batrand I've added a core pcl library with some data models and services to better replicate how a real project might look. I also added copies of the `MvxCollectionViewSource` classes from Github so you can step through the code in the project. Simply scroll up and down a few times on device or simulator to see the bindings break when the cells are dequeued again.
See the TODO item in the Tasks browser for a good place to breakpoint.

Project: [MvxCollectionViewTestCase](https://github.com/UKDeveloper99/MvxCollectionViewTestCase)
@nirinchev @kjeremy  @Cheesebaron 

Cheers.

**Comment by UKDeveloper99** [comment]
One interesting observation, if you use the exact same setup with an MvxStandardTableViewSource the issue doesn't occur when cells are dequeued. So I think it's safe to assume the issue is specific to MvxCollectionView.

**Comment by Nickolas-** [comment]
Hi everybody, so I a little bit dig binding and found problem with Realm, when we try to get value from `Model` it give us exception because we try to access RealmObject from incorrect thread on property.

<img width="1004" alt="screen shot 2017-03-11 at 12 14 47 am" src="https://cloud.githubusercontent.com/assets/8171424/23815357/86541b44-05f0-11e7-997b-a7affb0bd69a.png">

And it give us UnsetValue , that's why you getting default values on targets.

**Comment by nirinchev** [comment]
Thanks for looking into that - I'm not familiar with MVX, but I'll assume if you're getting that exception, you're not doing any marshaling to the thread where the binding was created on? Is there a way to control on which thread binding setters/getters will be executed?

**Comment by Nickolas-** [comment]
You can change just on old MvxBindingContext that running all synchronous 
https://mvvmcross.com/blog/mvvmcross-42

**Comment by kjeremy** [comment]
Should we just remove the task based bindings or switch the default back to
the UI thread? We've had a number of issues with the task based bindings.

**Comment by UKDeveloper99** [comment]
Interesting, are there any major drawbacks to not being able to use the task based bindings? What about @nirinchev 's suggestion of marshaling the changes back to the original thread?

**Comment by nirinchev** [comment]
I imagine that would be hard if the original thread doesn't have a synchronization context (i.e. most likely, a threadpool one). If it has one, in 99% of the cases, it'll be the UI thread. As I said, I'm not familiar with MVX, so can't really say what's the best way to work around this, but Realm does expect that all reading/writing from/to Realm objects will happen on the original thread (we might relax that requirement in the future by tying a Realm to a synchronization context rather than a thread, so if MVX would provide a custom synchronization context, that could probably work, but that's far in the future).

**Comment by Nickolas-** [comment]
We didn't know on what task will be execute first time binding. Yes we can create some TaskScheduler that will do a job on the same thread, but problem will be even if we get RealmObject in ViewModel from async operation and then try to bind it.

**Comment by nirinchev** [comment]
Is there a way to force Mvx data bindings to at least execute on the UI thread? I imagine in 99% of the cases, the binding setup will happen on the UI thread, so realm objects will be bound to that.

**Comment by Nickolas-** [comment]
As I reply previous , you can use old 

protected override void InitializeLastChance()
{
    base.InitializeLastChance();
    Mvx.RegisterType<IMvxBindingContext, MvxBindingContext>();
}

This will be triggered on UI tread

**Comment by UKDeveloper99** [comment]
My project is working with the above, so aside from not getting _any_ benefits of `MvxTaskBasedBindingContext` it's resolved as far as I'm concerned. I'm not familiar with the workings of the task based bindings. But as @kjeremy indicated there has been issues with it. Maybe it needs revisiting, cheers.

**Comment by batrand** [comment]
FYI I've tried @Nickolas- 's solution in my project and the test project and it works as expected.

**Comment by jimespen** [comment]
I tried @Nickolas-'s solution as well, but it didn't work. I'm using a custom cell that inherits from MvxTableViewCell with an MvxSimpleTableViewSource as the source for my TableView. In my cell, I have two UIImageViews and two UILabels. The UILabels and one or both UIImageViews may sometimes disappear or reset their states when the cells go out of bounds and back again, identical to @batrand's scenario.

Realm version: 1.3.0 (preview, since [v1.2.0 crashes the app when scrolling the list](https://github.com/realm/realm-dotnet/issues/1339))
Latest version of Xamarin Studio and Xamarin iOS
MvvmCross version: 4.4.0

**Comment by UKDeveloper99** [comment]
@jimespen I've got the same tooling versions as you and I'm not experiencing any issues like that on my projects? What does your code look like for retrieving objects from the Realm, the one you bind to?

**Comment by jimespen** [comment]
@UKDeveloper99 In my ViewModel, I have these properties:
```
List<InfoItem> _infoItems;
public List<InfoItem> InfoItems
{
    get { return _infoItems; }
    set { _infoItems = value; RaisePropertyChanged(() => InfoItems); }
}

public Category Category { get; set; }
```
and in the Init()-method:
```
var realm = Realm.GetInstance();
Category = realm.All<Category>().First(c => c.Id == param);

InfoItems = _apiService.GetInfoItemsForSelectedCategory(Category.Id)
                           .Where(i => !string.IsNullOrEmpty(i.Name))
                           .OrderBy(i => i.Name)
                           .ToList();
```
Binding in the View:
```
var set = this.CreateBindingSet<InfoItemsView, InfoItemsViewModel>();
set.Bind(source).To(vm => vm.InfoItems);
set.Bind(source).For(s => s.SelectionChangedCommand).To(vm => vm.ReadDocumentCommand);
set.Apply();
```
And finally, the MvxTableViewCell binding:
```
 var set = this.CreateBindingSet<InfoItemCollectionCell, InfoItem>();
                set.Bind(hasBeenRead).To(vm => vm.HasBeenRead);
                set.Bind(fileExtension).To(vm => vm.FileExtension);
                set.Bind(updated).To(vm => vm.UpdatedAt);
                set.Bind(itemName).To(vm => vm.Name);
                set.Apply();
```

**Comment by UKDeveloper99** [comment]
Well first off you should bind to an `IList` rather than a `List`. Either that or an `IRealmCollection`. There's a Realm extension method to cast a query to that type `AsRealmCollection()`. Also don't call `ToList()` on the query. Try those changes see if that makes a difference.

**Comment by jimespen** [comment]
I tried all of your suggestions, @UKDeveloper99, but there's no difference in how the tableView behaves.

**Comment by UKDeveloper99** [comment]
Possibly try an `MvxStandardTableViewSource` instead, it's hard to say what the issue might be without looking at the project. If you definitely registered the old binding context in `InitializeLastChance` it should work. I've double checked mine and it's working fine with the same versions you have. Can I see this function `_apiService.GetInfoItemsForSelectedCategory(Category.Id)` ?

**Comment by jimespen** [comment]
Sure. Here it is after trying to use IRealmCollection rather than IList:
```
public IRealmCollection<InfoItem> GetInfoItemsForSelectedCategory(int categoryId)
        {
            var realm = Realm.GetInstance();
            var items = realm.All<InfoItem>()
                                .Where(i => i.CategoryId == categoryId)
                                .AsRealmCollection();

            return items;
        }
```
I actually used `MvxStandardTableViewSource`previously, before any design decisions about the list was taken (after reading [this StackOverflow post](https://stackoverflow.com/questions/16986207/what-class-to-inherit-from-for-bound-table-source)). The problem is that I can't use customs cells with that, as my options for binding are limited to `TitleText`, `DetailsText` etc. like this: `var source = new MvxStandardTableViewSource(tableView, "TitleText Name");`. But yes, using `MvxStandardTableViewSource` does work, as the binding to the `Name` property does not disappear when scrolling the list.

I registered the old binding context as suggested in the iOS project's `Setup` class (which inherits from `MvxIosSetup`.

**Comment by Cheesebaron** [comment]
The UIImageViews which disappear, how do they get their data? Is it a url from the realm object, or is it an actual image blob?

**Comment by jimespen** [comment]
They are images from the Asset Catalog, so they are initialised like this `UIImageView icon = new UIImageView(UIImage.FromBundle("paper"));`. Their visibility is dependant upon the binding in `MvxTableViewCell`:

`set.Bind(hasBeenRead).To(vm => vm.HasBeenRead);`
 `set.Bind(fileExtension).To(vm => vm.FileExtension);`

**Comment by UKDeveloper99** [comment]
I normally just make my own table source and inherit from `MvxTableViewSource` then override `GetOrCreateCellFor` then you can dequeue reusable cells by their cell identifier. Try removing your visibility binding for the image view for the time being. Maybe the code is working incorrectly.

One question, in your cell class you are doing `set.Bind(hasBeenRead)` etc. Where are these variables coming from? Can you paste the whole cell class, something doesn't seem right to me.

**Comment by jimespen** [comment]
Yeah, I also tried rolling my own table source at first:

```
public class InfoItemsTableSource : MvxTableViewSource
{
        static readonly NSString InfoItemCellIdentifier = new NSString("InfoItemCollectionCell");

        public InfoItemsTableSource(UITableView tableView) : base(tableView)
        {
            tableView.RegisterNibForCellReuse(UINib.FromName("InfoItemCollectionCell", NSBundle.MainBundle), InfoItemCellIdentifier);
        }

        public override nint NumberOfSections(UITableView tableView)
        {
            return 1;
        }

        protected override UITableViewCell GetOrCreateCellFor(UITableView tableView, NSIndexPath indexPath, object item)
        {
            return TableView.DequeueReusableCell(InfoItemCellIdentifier, indexPath);
        }
}
```

The variables are properties on the `InfoItem`class, which contains data about a particular document in the table view. An "InfoItem" is a deserialised JSON-object that comes from a backend:
```
public class InfoItem : RealmObject
{
        [PrimaryKey]
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string FileGuid { get; set; }
        public string Title { get; set; }
        public string FileExtension { get; set; }
        public DateTimeOffset UpdatedAt { get; set; }
        public bool HasBeenRead { get; set; }

        public InfoItem() { }

        public InfoItem(int id, string name, int categoryId, string fileGuid, string title, string fileExtension, DateTimeOffset updatedAt, bool hasBeenRead)
        {
            Id = id;
            Name = name;
            CategoryId = categoryId;
            FileGuid = fileGuid;
            Title = title;
            FileExtension = fileExtension;
            UpdatedAt = updatedAt;
            HasBeenRead = hasBeenRead;
        }

        public override int GetHashCode()
        {
            return string.Format("{0}.{1}.{2}.{3}.{4}", Id, Name, FileGuid, Title, FileExtension).GetHashCode();
        }
}
```
The idea is to show a dot next to items (i.e. documents) which have not been read since they were downloaded to the device as well as having their `Name` property in bold (items are only downloaded if they don't already exists on the device, or if the hash codes don't match). Now, when a user taps an item to read the document, the `InfoItem` gets updated in Realm in a write transaction where its `HasBeenRead`property gets set to true, and then a message (`InfoItemsRefreshedMessage`) is published using IMvxMessenger, allowing the list to update itself.

@UKDeveloper99 I understand completely. I must admit that my custom cell is not ideal. Since I'm unable to bind a boolean or other primitives (I also tried object boxing and various other methods which didn't amount to much), I eventually created two UILabels (`hasBeenRead` and `fileExtension`) just so that I could bind the Text properties to the `InfoItem` properties in the custom cell:

```
public partial class InfoItemCollectionCell : MvxTableViewCell
{
        public static readonly UINib Nib = UINib.FromName("InfoItemCollectionCell", NSBundle.MainBundle);
        public static readonly NSString Key = new NSString("InfoItemCollectionCell");

        MvxSubscriptionToken _token;

        public InfoItemCollectionCell(IntPtr handle) : base(handle)
        {
            var messenger = Mvx.Resolve<IMvxMessenger>();
            _token = messenger.SubscribeOnMainThread<InfoItemsRefreshedMessage>(OnInfoItemsRefreshedMessage);
            CreateLayout();
            InitializeBindings();
        }

        UIImageView dot;
        UIImageView icon;
        UILabel itemName;
        UILabel fileExtension;
        UILabel updated;
        UILabel hasBeenRead;

        void CreateLayout()
        {
            const int offsetStart = 50;
            Accessory = UITableViewCellAccessory.DisclosureIndicator;
            hasBeenRead = new UILabel();
            fileExtension = new UILabel();

            icon = new UIImageView(UIImage.FromBundle("paper"));
            icon.Frame = new RectangleF(offsetStart, 15, 60, 70);
            icon.Opaque = true;

            itemName = new UILabel(new RectangleF(offsetStart + 85, 30, (float)UIScreen.MainScreen.Bounds.Right - 265, 40));
            itemName.AdjustsFontSizeToFitWidth = true;
            itemName.Lines = 0;
            itemName.Font = UIFontExtensions.avinorFontMediumOfSize(20);
            itemName.Opaque = true;

            updated = new UILabel(new RectangleF(offsetStart + 86, 55, 115, 40));
            updated.LineBreakMode = UILineBreakMode.TailTruncation;
            updated.Font = UIFontExtensions.avinorFontMediumOfSize(10);
            updated.Opaque = true;

            dot = new UIImageView(UIImage.FromBundle("dot.png"));
            dot.Frame = new Rectangle(20, 45, 15, 15);
            dot.Opaque = true;

            ContentView.AddSubview(icon);
            ContentView.AddSubview(itemName);
            ContentView.AddSubview(updated);
        }

        void InitializeBindings()
        {
            this.DelayBind(() =>
            {
                var set = this.CreateBindingSet<InfoItemCollectionCell, InfoItem>();
                set.Bind(hasBeenRead).To(vm => vm.HasBeenRead);
                set.Bind(fileExtension).To(vm => vm.FileExtension);
                set.Bind(updated).To(vm => vm.UpdatedAt);
                set.Bind(itemName).To(vm => vm.Name);
                set.Apply();
            });
        }

        void OnInfoItemsRefreshedMessage(InfoItemsRefreshedMessage obj)
        {
            UpdateFileIcon();
            StyleCell();
        }

        void StyleCell()
        {
            if (hasBeenRead.Text == "False")
            {
                ContentView.AddSubview(dot);
                itemName.Font = UIFontExtensions.avinorFontBoldOfSize(20);
            }
            else
            {
                dot.RemoveFromSuperview();
                itemName.Font = UIFontExtensions.avinorFontMediumOfSize(20);
            }
        }

        void UpdateFileIcon()
        {
            switch (fileExtension.Text)
            {
                case ".pdf":
                    icon.Image = UIImage.FromBundle("pdf");
                    break;
                case ".jpeg":
                case ".jpg":
                    icon.Image = UIImage.FromBundle("jpg");
                    break;
                case ".png":
                    icon.Image = UIImage.FromBundle("png");
                    break;
                case ".doc":
                case ".docx":
                    icon.Image = UIImage.FromBundle("word");
                    break;
                case ".xlsx":
                case ".xls":
                    icon.Image = UIImage.FromBundle("excel");
                    break;
                default:
                    icon.Image = UIImage.FromBundle("paper");
                    break;
            }
        }
}
```
The `InfoItemsReadyMessage` get published from the corresponding view model when it has gathered all `InfoItems` for that particular category, and the `OnInfoItemsRefreshedMessage` updates the cells accordingly. Again, this isn't exactly ideal, but even when using an `MvxStandardTableViewSource` the `TitleText Name` binding would sometimes fail when scrolling the list, which is why I started to google this issue in the first place.

**Comment by UKDeveloper99** [comment]
You said the image views disappear, but you haven't binded anything to the image views? That must be a separate isssue. Definitely not Realm related. Why are you using a Nib rather than a reusable cell from the storyboard?

**Comment by jimespen** [comment]
@UKDeveloper99 Well, they don't really disappear, they get their states reset so that the default image is displayed (which makes sense considering the cells are to be reused). I'm sorry if I gave the impression that the problem with the UIImageViews is a Realm issue, I was just trying to give enough context. The main issue is with the UILabels which are bound to the model like so
```
set.Bind(updated).To(vm => vm.UpdatedAt);
set.Bind(itemName).To(vm => vm.Name);
```
When the cells go out of bounds and gets recycled, the text on the UILabels may disappear, or they contain the text of the cells that went out of bounds.

To give an example, let's say I have a list of perhaps 10-15 items ("SomeDocument1", "SomeDocument2" etc). The design of the list allows for 10 items to be shown at any time, and when I scroll down to view the last 5, the text on the first 5 that were recycled shows up on some the bottom 5 cells ("SomeDocument15", "SomeDocument1", " "), or the text does not show up at all.

When I first encountered this issue using my own  table source, I tried following [Thomas Hanning's blog](http://www.thomashanning.com/the-most-common-mistake-in-using-uitableview/). When that didn't help, I tried using an `MvxSimpleTableViewSource`. I then went back to using an `MvxStandardTableViewSource` to see if the problem was with the custom cell, but I faced the same issue using that as well. But as mentioned above, `MvxStandardTableViewSource` now works with
```
protected override void InitializeLastChance()
        {
            base.InitializeLastChance();
            Mvx.RegisterType<IMvxBindingContext, MvxBindingContext>();
        }
```
in the `Setup` class of my iOS project.

I don't really have a good reason for using Nibs, I just tend to not use storyboards at all and develop the UI programmatically.

**Comment by jimespen** [comment]
@UKDeveloper99 It works now with using either an `IList` or an `RealmCollection`, even though nothing else has changed in the code base since yesterday (which leaves me a bit confounded. I presume it might be because of your original suggestion of using `IList` and not calling `ToList()` in the query?). The text on the two UILabels gets set correctly for reused cells. The states of the UIImageViews are purely my own faulty implementation.

**Comment by Cheesebaron** [comment]
Please open a new issue if you believe this still is a problem.
