### ISSUE TITLE
Incorrect width with wrap_content

### ISSUE THREAD

**Issue by gaminn** [MvvmCross/MvvmCross#1546]
Hi,
I have several views with android:layout_width="wrap_content", e.g.

```
          <TextView
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              app:MvxBind="Text BatteryLevelText" />
```

BatteryLevelText is "100 %" but only "1" is displayed from it. The view has enough space to display the whole text. If I replace my TextView with

```
          <TextView
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:text="100 %" />
```
Then 100 % is displayed, so the problem lays in MvxBind. Also, if I set android:layout_width="40dp" then 100 % is displayed even with MvxBind.

**Comment by kjeremy** [comment]
Can you do the following for me:  Create a class `MyTextViewTargetBinding` inheriting from https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Binding/Droid/Target/MvxTextViewTextTargetBinding.cs and override `SetValueImpl`.  Then in your Setup's `FillTargetFactories` add the following after the call to `base.FillTargetFactories` : 
```csharp
registry.RegisterCustomBindingFactory<TextView>("Text", textView => new MyTextViewTargetBinding(textView));
```

Put a breakpoint in `SetValueImpl` and see what text is coming through and then go up the callstack and see if we're doing something stupid.

**Comment by gaminn** [comment]
Hi,
can you please provide some details on FillTargetFactories? This is my setup.cs:

`public class Setup : MvxAndroidSetup
    {
        public Setup(Context applicationContext)
            : base(applicationContext)
        {
        }

        protected override IMvxApplication CreateApp()
        {
            return new App();
        }
    }`

There is no FillTargetFactories.

**Comment by Cheesebaron** [comment]
Override the method.
