### ISSUE TITLE
[Proposal] Strongly typed MvvmCross code based binding properties

### ISSUE THREAD

**Issue by Plac3hold3r** [MvvmCross/MvvmCross#1557]
Include an additional option than literal strings for MvvmCross defined custom bindings. The functionality to define a binding via its string name to remain as is, so no functionally is lost and fully backwards supported. Just expose the MvvmCross custom binding properties in a strongly typed manner. Will affect both MvvmCross platform custom bindings and plugins custom bindings.

## Objectives

* Increase the discoverability of custom binding that MvvmCross provides (Including via Plugins)

  * Expose custom binding properties that are available directly from the MvvmCross API. No need to search docs/wiki/github source

* Compile time/intellisense checking over the current runtime execution exceptions approach

  * Speed up development time by preventing invalid binding property name via offering a type safe convention

## Idea 1 - Compile time constants

Expose the string name literals as compile time constants.

### Proposed Example (Uses iOS platform as example, but would be the same across platforms)

**MvvmCross changes**

Move string literals to public accessible constants.

Proposed naming convention {Base control type}{Binding description/event}.

```
namespace MvvmCross.Binding.iOS
{
    public static class IOSPropertyBinding
    {
        public const string UILabelText = "Text";
        public const string UIViewTap = "Tap";
    }

    public class MvxIosBindingBuilder : MvxBindingBuilder
    {
        protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            base.FillTargetFactories(registry);

            registry.RegisterCustomBindingFactory<UILabel>(
                IOSPropertyBinding.UILabelText,
                view => new MvxUILabelTextTargetBinding(view));

            registry.RegisterCustomBindingFactory<UIView>(
                IOSPropertyBinding.UIViewTap,
                view => new MvxUIViewTapTargetBinding(view));
        }
    }
}
```

**Developer Usage**

```
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS;

...

var labelButton = new UILabel());

var bindingSet = this.CreateBindingSet<HomeViewController, HomeViewModel>();
bindingSet.Bind(labelButton).For(IOSPropertyBinding.UIViewTap).To(vm => vm.NextCommand);
bindingSet.Bind(labelButton).For(IOSPropertyBinding.UILabelText).To(vm => vm.NextLabel);
bindingSet.Apply();
```

### Advantages

* Straightforward to implement
* Can include additional comments for developer to see via intellisense if needs be

### Disadvantages

* Require the developer to resolve an additional namespace
* Does not check whether the binding is possible against the specified control type, i.e. TouchUpInside binding works against UIControl inheritance and not a UIView.

## Idea 2 - Extension methods

C# does not currently, nor will it in the medium-term offer support for property extensions ([See comment by Mads Torgersen, search "we had a"](https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/)). Therefore, the I believe the only option we have is via extension methods.

Extension methods can be used to return the custom binding name and additionally be used to restrict bindings against only allowed base types.

**MvvmCross changes**

Expose public extension methods. Note additional work will need to be done inside MvxPropertyExpressionParser to properly handle the extension methods (May need some help figuring out how best to do this).

```
namespace MvvmCross.Binding.iOS
{
    internal static class IOSPropertyBinding
    {
        public const string UILabelText = "Text";
        public const string UIViewTap = "Tap";
    }

    public static class IOSPropertyBindingExtensions
    {
        public static string BindingUILabelText(this UILabel label)
        {
            return IOSPropertyBinding.UILabelText;
        }

        public static string BindingUIViewTap(this UIView view)
        {
            return IOSPropertyBinding.UIViewTap;
        }
    }

    public class MvxIosBindingBuilder : MvxBindingBuilder
    {
        protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            base.FillTargetFactories(registry);

            registry.RegisterCustomBindingFactory<UILabel>(
                IOSPropertyBinding.UILabelText,
                view => new MvxUILabelTextTargetBinding(view));

            registry.RegisterCustomBindingFactory<UIView>(
                IOSPropertyBinding.UIViewTap,
                view => new MvxUIViewTapTargetBinding(view));
        }
    }
}
```

**Developer Usage**

```
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS;

...

var labelButton = new UILabel();

var bindingSet = this.CreateBindingSet<HomeViewController, HomeViewModel>();
bindingSet.Bind(labelButton).For(c => c.BindingUILabelText()).To(vm => vm.NextLabel);
bindingSet.Bind(labelButton).For(c => c.BindingUIViewTap()).To(vm => vm.NextCommand);
bindingSet.Apply();
```

### Advantages

* Can include additional comments for developer to see via intellisense if needs be
* Checks whether the binding is possible against the specified control base type, i.e. TouchUpInside binding works against UIControl inheritance and not a UIView.

### Disadvantages

* Require the developer to resolve an additional namespace
* More extensive changes need to be made to cater for the extension methods inside MvxPropertyExpressionParser

## Idea n<sup>th</sup> - ???

Any other ideas are welcome!

#### Additional nice to haves

* I'm not sure if it is something we would want to explore, but it would be nice to have a shared namespace. That way the developers would not need to resolve multiple namespaces when using bindings from plugins + the core platform bindings.

**Comment by Cheesebaron** [comment]
I don't understand what you are trying to achieve here. Binding are already strongly typed. Taking one of your examples:

     bindingSet.Bind(labelButton).For(c => c.Text).To(vm => vm.NextLabel);

How is this not strongly typed?

**Comment by Plac3hold3r** [comment]
Sure, Text is perhaps a bad example to include here for the purpose of demonstrating as there is an equivalent native property. It is meant more for the custom bindings that do not have equivalent native properties that we can use is a type safe manner. For example the "Tap" custom binding, which is based on an event.

**Comment by Cheesebaron** [comment]
So I guess what you are asking is a way to easily discover TargetBindings for a given control, that does not use the public properties the View exposes?

**Comment by Plac3hold3r** [comment]
@Cheesebaron that is correct. I think the extension methods would offer the best value as they would only work against controls with the corresponding base type to the TargetBindings.

**Comment by martijn00** [comment]
@Plac3hold3r Could you make a PR implementing the extension methods?
