### ISSUE TITLE
Error XA4204: Unable to resolve interface type 'Android.Gms.Common.Apis.GoogleApiClient/IConnectionCallbacks'.

### ISSUE THREAD

**Issue by njale** [MvvmCross/MvvmCross#1558]
### Steps to reproduce

Create an Android MvvmCross app and add reference to plugin "Location Fused". Update all libraries to newest version and compile

### Expected behavior
   Should compile without error message. Note the non-fused Location-plugin does not produce this error.

### Actual behavior
   Compiles with error message:
   Error XA4204: Unable to resolve interface type 'Android.Gms.Common.Apis.GoogleApiClient/IConnectionCallbacks'.

### Configuration
**Version:** 4.4.0

**Platform:** 
   Android 7.0 Nougat - built in Visual Studio 2015 Update 3, Xamarin 7.0.2.42

**Comment by Cheesebaron** [comment]
The problem is probably that you are mixing versions of Play Services components.

4.4.0 is built against an older version that is stable currently, so it needs a new build and release.

**Comment by njale** [comment]
That is possible. I have only tried building with newest Play Services components, but a comment on the same issue at https://forums.xamarin.com/discussion/85207/build-time-error-on-xamarin-on-macosx-for-android-api-24-target-framework-7-0?   indicates that this is not the case:

      "I have tried almost everything I can think of, retargeted frameworks, downgraded versions, upgraded versions, nothing seems to help."

**Comment by Cheesebaron** [comment]
I've released a pre-release version of the Fused plugin which depends on the newer version of GoogleApiClient. I've verified, it works with that.

**Comment by njale** [comment]
Good work. Appreciated

**Comment by weitzhandler** [comment]
How can I figure out which version of Google Play Services is mapped to each XF version?

**Comment by Cheesebaron** [comment]
Just look at the dependencies for the nuget package @weitzhandler

**Comment by weitzhandler** [comment]
@Cheesebaron 
Thanks for your reply, looks like the dependencies all match. Am I missing something?

I've posted my question [here](https://stackoverflow.com/questions/52721291/unable-to-resolve-interface-type-android-gms-maps-googlemap-ioncameramoveliste).
