### ISSUE TITLE
Allow Views to take over presentation by implementing IMvxViewDispatcher

### ISSUE THREAD

**Issue by fuzzybinary** [MvvmCross/MvvmCross#1559]
We found on our last project that for complicated view transitions and hierarchies, that relying on a global IMvxViewPresenter that has no reference to the ViewModel/View requesting the change becomes increasingly difficult.  In most cases, the platform specific view has a better idea of how to perform the platform specific presentation of a ViewModel.

Because of that, we'd like to suggest a minor change to MvxNavigatingObject to make it's ViewDispatcher property public, so that Views, if they need to, can override IMvxViewDispatcher and set the property.  Change would be this line:

```
protected IMvxViewDispatcher ViewDispatcher => (IMvxViewDispatcher)base.Dispatcher;
```

to this:
```
        private IMvxViewDispatcher _ViewDispatcher;
        public IMvxViewDispatcher ViewDispatcher
        {
            get
            {
                return _ViewDispatcher ?? (IMvxViewDispatcher)base.Dispatcher;
            }
            set
            {
                _ViewDispatcher = value;
            }
        }
```

**Comment by kjeremy** [comment]
Interesting.  Can you post an example of how to use this?

**Comment by fuzzybinary** [comment]
Yeah, here's a repo with an example of a modal dialog, which was probably one of our more annoying things we had to combat in our presenter
https://github.com/fuzzybinary/ViewPresenterExample

In both iOS and Android the pattern for getting back a result from a dialog is well established (using StartActivityForResult in Android and using the Delegation pattern in iOS).  However doing this with Presenters in MVX requires hacks like holding on to the last presented view controller in the presenter (which is potentially error prone).

This sampel also shows how presentations that are more "regular" could go through a default presenter if special handling on the view weren't required.

Other examples where we had significant trouble: Split views (especially with multitasking on iPads) and fragments that contain fragments on Android.

**Comment by Cheesebaron** [comment]
For dialogs and similar concepts I would use `IMvxInteraction` and keep the implementation details out of the ViewModel as much as possible. Meaning, the ViewModel only sees that Interaction which has some callbacks with data.

Then the View itself can do anything when this Interaction triggers. This could be display a modal dialog (you should probably look into using a Fragment for this, instead of spinning up a new Activity), then invoke the callback when the user returns from the dialog.

**Comment by fuzzybinary** [comment]
I used the single dialog example because it's the simplest one to do quickly. In reality, we had instances where starting an Activity was be the correct choice for getting data form the user and returning it to the calling parent.

The idea here is we *are* trying to keep complicated view presentation details out of the ViewModel. In this example the ViewModel just knows it needs to present another ViewModel as part of the logic. The View can then decide (in complex situations) how that VM gets presented.

So here's a more complex example which is easilly dealt with given this patch, and incredibly complicated using MvxInteractions or a Presenter.  

We have a "workflow" view that has a different presentation on Tablet / Handset, but relies on the same VMs to do their work.  It's a step by step flow that has a parent VM, a VM for each step of the workflow, and a summary VM. On Handset, the summary VM shows at the end, and you can jump back to any previous step, wheras on Tablet the summary is always shown in a split view and you can tap on any step to jump back in the flow.  When this is all done and confirmed, we dismiss the parent VM of all of this and return the results to the caller (similar to StartActivityForResult, but hacked in).

There were all sorts of benefits to this VM structure, including the ability to do iPad multitasking and reusing step VMs and Views across multiple different workflows.

The presenter logic for this was incredibly complex, and I'm not sure I could see IMvxInteraction being usable for this.  In reality having the parent view pared with the parent VM handle this presentation logic feels like the correct choice.

**Comment by nickrandolph** [comment]
@martijn00 I think that the changes in 6/6.1 to make the presenter and dispatchers more extensible should provide enough scope to cover the requirements of this issue? 
@fuzzybinary how would you feel about us closing this issue, or do you still feel there is more to be done?

**Comment by fuzzybinary** [comment]
I'm goint to pull @biscuitehh into the conversation since he's been actively working on that codebase and has performed upgrades to the 6.0 line recently. He'll be able to say if the new presenter changes have addressed our issues.

**Comment by fuzzybinary** [comment]
Closing this as stale.
