### ISSUE TITLE
Navigation Page shows foreign language "Zuruck".  How do I fix or override this?

### ISSUE THREAD

**Issue by devgig** [MvvmCross/MvvmCross#1561]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1.  call ShowViewModel<myviewmodel>() in iOS

2.

3.

### Expected behavior
Navigation back to original has English text.

### Actual behavior
Navigation back has text "Zuruck".  Not for sure how to override this.

### Configuration

**Version:** 4.x

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by Cheesebaron** [comment]
Is the language of the device german? The back button is very much dependent on this.

**Comment by devgig** [comment]
Fertig for DatePicker and Zuruck for Back.  I think it is German.  How to I change this?  The setting on the iOS emulator are English.

**Comment by devgig** [comment]
Fertig is Completed in German.  Need English

**Comment by mvanbeusekom** [comment]
Are there any culture settings set in your project (something similar as described in this post maybe)? 

Can you make a small reproducible project you can share here?

**Comment by devgig** [comment]
This was buried in my Info.plist

 <key>CFBundleLocalizations</key>
  <array>
    <string>de</string>
  </array>

This came from the MVVMCross Template that is out there.  

https://marketplace.visualstudio.com/items?itemName=CristianChereches.XamarinFormswithMvvmCrossSolutionTemplate

**Comment by devgig** [comment]
Issue Solved
