### ISSUE TITLE
[AndroidSupport] FAB AutoHide behavior - same support for new BottomBar

### ISSUE THREAD

**Issue by thefex** [MvvmCross/MvvmCross#1563]
Coming with new Android BottomNavigationView there is a pattern where scroll/hide should show/hide Bottom bar. 
We already have support for auto-hide FloatingActionButton CoordinatorLayout.Behavior but it can't be used for BottomNavigationView.

I will push fix in few minutes.

**Comment by thefex** [comment]
Autohide behavior supports arbitrary views now.
Sample usage with BottomNavigationBar:
`  <android.support.design.widget.BottomNavigationView
    android:id="@+id/bottom_navigation"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom"
    design:itemBackground="@color/primary"
    design:itemIconTint="#FFFFFF"
    design:itemTextColor="#FFFFFF"
    android:background="@color/grayBackgroundColor"

     local:layout_behavior="@string/view_scroll_translation_autohide_behavior" />`

**Comment by martijn00** [comment]
This will break again when we update to v25.1 i think: https://github.com/ianhanniballake/cheesesquare/commit/5a5c3b29ae684e3a840b095bfca8d90a5a79af46

**Comment by thefex** [comment]
Still works on v25.1 though. I use same behavior I have pushed in app which use v25 prerelease.
