### ISSUE TITLE
Exception Thrown in view model async Init method not propagated

### ISSUE THREAD

**Issue by RoryDaBreaker** [MvvmCross/MvvmCross#1569]
Hello,
i'm facing an issue that i can reproduce everytime, it about exception in view model life cycle.
### Steps to reproduce

1. Call ShowViewModel method from vm A

`ShowViewModel<B>()`

2. B is a view model with an async init method (async task)
3. In this init method, an exception could be thrown

```
public async Task InitAsync(IMvxBundle parameters) {

   var result = await AnyAsyncMethod();
   if(result == null){
   throw new Exception(".....");
   }
}
```

4. Create a custom WpfPresenter class that overrides Show method
```
        public override void Show(MvxViewModelRequest request)
        {
            try
            {
                var loader = Mvx.Resolve<IMvxSimpleWpfViewLoader>();
                var view = loader.CreateView(request);
                this.Present(view);
            }
            catch (Exception exception)
            {
               // do somthing 
            }
        }
```

### Expected behavior
In our case we expect the exception is propagated until we decide to catch it (eg. in the Show method of a custom WpfPresenter).

### Actual behavior
If the view model init method is synchronous the exception is caught while it is "swollowed" if the init method is Async.

### Configuration

**Version:** 4.2.2

**Platform:** WPF

**Comment by kjeremy** [comment]
Can you reproduce this in 4.4.0?

**Comment by RoryDaBreaker** [comment]
Yes, just tired right now. and it doesn't work.

**Comment by Cheesebaron** [comment]
The problem here is that technically the Task is called as void:

https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/Core/ViewModels/MvxViewModelExtensions.cs#L39

Not sure if we can do anything here. Probably. This is a bug indeed.

**Comment by RoryDaBreaker** [comment]
Fine,
When you say "not sure if we can do anything", does it mean this bug is not planned to be fixed ?
In this case, we should probably change our approach in exception management. 
Anyway,thanks for your support.

**Comment by Cheesebaron** [comment]
I've marked it up for grabs so anyone can make a fix for it. It is not that we don't want this bug fixed. 

Your best bet is to handle the exception in your Init method, instead of letting it bubble out and be swallowed.

Issue here is that Init is invoked through reflection, I guess wrapping the lined I linked to in a try/catch might help. Not sure.

**Comment by nmilcoff** [comment]
Related to / same as #1006

**Comment by martijn00** [comment]
Use the new MvxNavigationService for async navigate which will throw errors.
