### ISSUE TITLE
Nuspec PCL profiles?

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1572]
I noticed, currently our nuspecs are throwing our PCL files into portable-net45+win+wpa81+wp80 when packing up NuGets, which is probably file. However, we don't have win, wpa81 or wp80 projects anymore.

So I guess we are more or less ready to switch to .NETStandard 2.0 when the tooling is ready?

**Comment by ghuntley** [comment]
The combination of the targets is what defines the contract number. For example dropping win, wpa81 and co from the folder name changes the pcl #. Keep them as is and then change when doing your netstandard conversion.
