### ISSUE TITLE
Android projects have specific Compile version set

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1573]
Most Android projects in MvvmCross have a specific Compile version set. Most are set to API24. Is there a reason to set a specific one, instead of just using latest?

AppVeyor VS2017 image does not have API 24 installed and fails because of that.

**Comment by ghuntley** [comment]
Cheese; steal the reactiveui bootstrap.ps1. it has the solution to your needs re API 24.

**Comment by Cheesebaron** [comment]
The bootstrap.ps1 doesn't seem to be used. But rather the contents of the appveyor.yml which installs API24. Going to try that.

**Comment by martijn00** [comment]
We use v24 because that is needed for Android Support libraries.

**Comment by Cheesebaron** [comment]
We can't just use latest and greatest always? They do need specific version?

**Comment by martijn00** [comment]
They need v24 or higher. As on a normal Appveyor machine is the case only v23 and some lower are installed. This enforces the correct version to be used.

**Comment by Cheesebaron** [comment]
OK. Makes sense now. Thank you for the explanation 😄
