### ISSUE TITLE
JASidePanels Slide Menu iOS Native Library Crash only on device

### ISSUE THREAD

**Issue by angelopolotto** [MvvmCross/MvvmCross#1577]
I tried to use JASidePanel, but its crashes on device. I thought that is a problem in the link configuration, so, I changed it but the problem was not solved.
 
> Note: I flowed this example to create my project, but I using Xib file to create the login design screen: https://github.com/MvvmCross/MvvmCross-Samples/tree/master/XPlatformMenus

### Steps to reproduce

1. Create a new MvvmCross project flowing the example XPlatformsMenus.

2. Update the MvvmCross packages.

3. Change the LoginView to a Xib ViewController.

4. Deploy the application on device (I using iPhone 5c in my tests).

### Expected behavior
The application deploys without crashes on devices.

### Actual behavior
The application deploys on iPhone Simulator, but crashes on devices.

### Configuration (Tool/Version)

* Xamarin.iOS: 10.3.1,
* XCode: 8.2,
* MvvmCross: 4.4.0,
* MvvmCross.iOS.Support: 4.4.0,
* MvvmCross.iOS.Support.JASidePanels: 4.4.0,
* iPhone 5c: iOS 10.2

**Platform:** iOS.

![The exception 1](https://cloud.githubusercontent.com/assets/3145741/22296708/3adb4f9a-e302-11e6-8615-ae8bcb6142f9.png)

![The exception 2](https://cloud.githubusercontent.com/assets/3145741/22296740/4882e8e2-e302-11e6-8d34-3783ef8a5f68.png)

![The exception 3](https://cloud.githubusercontent.com/assets/3145741/22296796/6c9c6e06-e302-11e6-9b78-22cbff2d3fe4.png)

![Project build configuration](https://cloud.githubusercontent.com/assets/3145741/22296806/76468734-e302-11e6-94c4-3d2b710b9171.png)

**Comment by Cheesebaron** [comment]
Provide a reproducible sample and we'll take a look.

**Comment by angelopolotto** [comment]
I created a project with a reproducible error that can be found in my gitHub:

https://github.com/angelopolotto/XMenuTestJASidePanels

Deploy the application on device to get the error.

**Comment by Cheesebaron** [comment]
Hmm. Strange. What I gather from the crash is that it cannot find the ObserveValue method which responds to one of the observers set when setting a ViewController in JASidePanels. Not sure exactly why this is, but could be due to how the JASidePanels.dll which someone, dunno who, made and we are using with the JASidePanels stuff.

@martijn00 do you know where this comes from? Maybe it needs to be recompiled or something.

**Comment by angelopolotto** [comment]
@Cheesebaron I found these projects: https://github.com/gotosleep/JASidePanels and https://components.xamarin.com/view/jasidepanels . Are these projects?

**Comment by martijn00** [comment]
I have no idea. I usually use the SideBar menu. Maybe @jamsoft knows?

**Comment by jonathan-jd4software** [comment]
@angelopolotto @Cheesebaron @martijn00  I have stumbled onto the same issue, is there any progress on tying down the issue in the JASidePanels.  Or a you suggesting that I need to rewrite to use SideBar?  Thanks

**Comment by Cheesebaron** [comment]
We dont have the source for JASidePanels, I don't know where it comes from.

**Comment by jonathan-jd4software** [comment]
@Cheesebaron In that case, a re-write it is

**Comment by angelopolotto** [comment]
@jonathan-jd4software I solve my problem replacing the JASidePanels with SideBar (https://github.com/MvvmCross/MvvmCross/tree/develop/MvvmCross-iOSSupport/MvvmCross.iOS.Support.XamarinSidebar). 
I followed this example: https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/iOS-Support/XamarinSidebar .

**Comment by martijn00** [comment]
Removed in 5.0. See https://github.com/MvvmCross/MvvmCross/pull/1684
