### ISSUE TITLE
Add Preserve attribute to all bindings 

### ISSUE THREAD

**Issue by Nickolas-** [MvvmCross/MvvmCross#1578]
Hi everybody, do you have in plan in nearest future add Preserve attribute for all bindings ? 
There always troubles with "Linker All".

**Comment by Cheesebaron** [comment]
Don't think that will happen. Adjust your LinkerPleaseInclude file.

Adding Preserve attribute to all bindings, will just increase app size and people _will_ blame MvvmCross.
