### ISSUE TITLE
Telerik 2017 R1 for Xamarin.Forms Android incompatible with MvvmCross

### ISSUE THREAD

**Issue by Anil86** [MvvmCross/MvvmCross#1579]
### Steps to reproduce

1. Create a [MvvmCross Xamarin Forms sample project](https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Forms/Example002XAML) as per MvvmCross Xamarin.Forms sample.

2. [Add reference](http://docs.telerik.com/devtools/xamarin/controls/listview/getting-started/listview-getting-started-required-assemblies) to Telerik libraries.

3. [Register Renderer](http://docs.telerik.com/devtools/xamarin/controls/listview/getting-started/listview-getting-started-register-renderer)

4. Build project

### Expected behavior
Project builds successfully.

### Actual behavior
Build fails with following errors:

![image](https://cloud.githubusercontent.com/assets/12828168/22321765/56f0a7be-e3bd-11e6-9359-cddafeca73bf.png)

![image](https://cloud.githubusercontent.com/assets/12828168/22321788/85a4f8bc-e3bd-11e6-89cf-b3cf4e065807.png)

### Configuration

**Version:** 4.4.0

**Platform:** 
Android/Xamarin.Forms
Visual Studio 2015 update 3

**Comment by Cheesebaron** [comment]
The _only_ thing MvvmCross.Forms.Presenters does is to add Presenter class to instantiate Views and ViewModels and tie them together, _nothing_ else.

We don't actively do anything to prevent 3rd party UI libraries such as Telerik's to function.

The errors look like you are missing a bunch of files. Or maybe you are building with wrong targets.

Provide a minimal reproducible sample and we can look at it.

**Comment by Anil86** [comment]
@Cheesebaron  This is a [sample](https://github.com/Anil86/MvvmCrossTelerikCompat) which orchestrates MvvmCross-Telerik incompatibility bug.

Few observations:

- Before adding Telerik references, projects builds fine
- Problem doesn't occur in iOS & UWP.

**Comment by Anil86** [comment]
After following Telerik's Samples, I made following changes:

- Added reference to Telerik's SideDrawer (although I'm using RadListView, it somehow has dependency on SideDrawer)
- Initialized TelerikForms from Android (wasn't mentioned in Telerik's docs)

Project builds successfully now.
