### ISSUE TITLE
TestProjects\Forms\Example001XAML\Example001XAML.sln does not compile

### ISSUE THREAD

**Issue by ehuna** [MvvmCross/MvvmCross#1580]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1.  Get the latest MvvmCroos/Xamarin Forms samples from https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Forms

2.  In VS open Example001XAML\Example001XAML.sln and attempt to Compile

3.  Attempt to compile and get errors related to nuget packages missing.

### Expected behavior
The projects are currently referencing the nuget packages in 

  `'..\..\..\packages'`

but a developer interested in only the Xamarin Forms samples should be able to compile the sample solutions on their own.

### Actual behavior
The sample solutions and projects should compile when you get the latest from github.

### Configuration
Not relevant

**Version:** 4.x (latest)
**Platform:** PCL/iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

### Possible Solution
The nuget packages are restored under ..\packages. so changing the projects to reference the nuget packages on ..\packages instead of ..\..\..\packages. 

I can make these changes and make a pull request.

Alternatively, if you want to keep these projects to quickly test changes to compiled MVVMCross and and Presenters - then maybe we should create a separate set of sample projects and solutions?

**Comment by Cheesebaron** [comment]
Yeah those examples are probably derped. If you feel like it, fix them and make a PR 😄

**Comment by ehuna** [comment]
Awesome, working on it, I should have a PR this weekend.
