### ISSUE TITLE
Virtualize MvxExpandableListAdapter methods

### ISSUE THREAD

**Issue by viniciusmaia** [MvvmCross/MvvmCross#1582]
Please, in futre versions of MvvmCross, change the MvxExpandableListAdapter methods to enable that methods be overwriten, because I had situations that I needed override GetChildView method and had problems.

**Comment by kjeremy** [comment]
Can you submit a PR?

**Comment by viniciusmaia** [comment]
What is PR? I'm sorry, my english is very limited.

**Comment by kjeremy** [comment]
Make a pull request with the changes you want and submit it.
