### ISSUE TITLE
Toolbar Search Binding

### ISSUE THREAD

**Issue by tstivers1990** [MvvmCross/MvvmCross#1584]
### Steps to reproduce

I'm following the linked article below to create a SearchView within a Toolbar acting as the title/action bar. I've looked pretty extensively through the samples and Google attempting to find an example of the correct way to implement this functionality, with no luck. I can't seem to find anything that gives me an indication of how to go about this. So I'm posting here.

https://social.technet.microsoft.com/wiki/contents/articles/34853.xamarin-using-searchview-in-toolbar.aspx

### Expected behavior
I'm attempting to bind using the following modifications to the `/menu/itemSearch.xml` file. This does not work, as the menu is expanded at run-time and I'm assuming either something needs to be done to cause the bindings to actually take effect, or this needs to be done differently in order to work with MvvmCross.

```XAML
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto">
 
    <item android:id="@+id/search"
        android:icon="@drawable/Search"
        android:title="search"
        app:showAsAction="ifRoom|withText"
        app:actionViewClass="android.support.v7.widget.SearchView"
        local:MvxBind="Query SearchQuery;SearchClick SearchClickCommand"/>
             
    </menu>
```

### Actual behavior
Binding does not work on the `Query` property or the `SearchClick` event.

### Configuration

**Version:** 4.x

**Platform:** Android

**Comment by kjeremy** [comment]
Unfortunately we can't bind to menus.  If you want to do implement this you will need to find a way to replace `MenuInflater` with some sort of `MvxMenuInflater` that does the exact same thing as `MenuInflater` but knows about `BindingContexts`.
