### ISSUE TITLE
How to hide all XamarinSidebar menu on page ? (iOS) 

### ISSUE THREAD

**Issue by artmon** [MvvmCross/MvvmCross#1585]
I did only two changes in MvvmCross.iOS.Support.XamarinSidebarSample.iOS and 
MvvmCross.iOS.Support.XamarinSidebarSample.Core
1. Comment in AppStart line:
 `//ShowViewModel<RightPanelViewModel>();`
2. Change arguments in attribute MvxPanelPresentation on CenterPanelView
`    [MvxPanelPresentation(MvxPanelEnum.None, MvxPanelHintType.ResetRoot, true)]
`
MvxPanelEnum.Center to  MvxPanelEnum.None

and I want to hide all menu, right and left on current page, but if I pull the right edge i see the left menu. How I can fully hide menu ?

### Configuration

**Version:** Last, 4.4 or 5

**Platform:** iOS

**Comment by Cheesebaron** [comment]
Github is for issues only, please use Slack og Stackoverflow for questions.

**Comment by fryette** [comment]
@Cheesebaron but really, how?????
Spend 2 hours and cannot found any documentation
