### ISSUE TITLE
Android Tabs Example

### ISSUE THREAD

**Issue by mtaulbee** [MvvmCross/MvvmCross#1586]
I've been looking for a good example on how to use tabs for Android with MvvmCross, and I've yet to find one. I've attempted to use a MvxTabFragmentActivity, but when I call the ShowViewModel<> function it fails and states that it is not a IMvxFragmentView. I know this is a bit vague, but does anyone have any ideas?

**Comment by Cheesebaron** [comment]
Please use Slack or StackOverflow for questions. Github is meant to be used for bugs and feature requests.

**Comment by mtaulbee** [comment]
Will do, thanks chief.
