### ISSUE TITLE
MvxAsyncCommand inconsistencies on Android

### ISSUE THREAD

**Issue by mgj** [MvvmCross/MvvmCross#1589]
Im sorry, not exactly a standalone repo, but the "Playground" project in this is very minimal and shows the issue: https://github.com/mgj/MvvmCross-Plugins

### Steps to reproduce

1. Create a View (Android) and ViewModel. 

2. Create a button and bind it to a MvxAsyncCommand which looks like this: https://github.com/mgj/MvvmCross-Plugins/blob/33386e2153ee53de983907ec437759e24428fbd3/Playground.Core/ViewModels/FirstViewModel.cs#L60

3. Click the button multiple times and observe that the button becomes gray and un-clickable.

OBS! The command i linked to calls a service that does stuff with a TaskCompletionSource but the issue is resolved completely by using `new MvxCommand(async () => await DoShowListCommandAsync("MyTitle"));` instead of MvxAsyncCommand

### Expected behavior
The button should remain clickable

### Actual behavior
The button becomes gray and un-clickable

### Configuration

**Version:** 4.4.0

**Platform:** Android

**Comment by mgj** [comment]
If instead of binding the button i manually call .Execute() on the command i get the following output:

MvxAsyncCommand : execute ignored, already running.

**Comment by Cheesebaron** [comment]
I have seen this too. It appears as if either. 

1. the mechanism that checks whether the Task is done is doing something wrong
2. something blocks the Task from returning to context and the command never finishes

**Comment by mgj** [comment]
In this case it was 2, helps to use TaskCompletionSource correctly :P

**Comment by agat366** [comment]
Not sure why the issue is closed. It seems to be still actual by these days.

**Comment by Cheesebaron** [comment]
@agat366 maybe because the author fixed _his_ issue with code deadlocking trying to return to the context it came from. Back navigation not working is a _different_ thing.
