### ISSUE TITLE
Custom font not working with MvxAppCompatActivity

### ISSUE THREAD

**Issue by cfl777** [MvvmCross/MvvmCross#1592]
Hi,

I need to use custom font for an massive Android project. For this I installed the Xamarin component called,
CallygraphyXamarin. This component works correctly for normal activities which inherit from Activity/AppCompatActivity, but doesn't work for MvxAppCompatActivity.

 Mvx and Calligraphy doesn't seem to mix well, because they both have custom Inflaters.

Two possible solutions have been suggested, but both are tedious:
https://forums.xamarin.com/discussion/88209/callygraphyxamarin-not-working-in-mvxappcompatactivity

@Cheesebaron mentioned the possibility of adding TypeFace bindings as a solution. That would be amazing!! 

Thanks

**Comment by kjeremy** [comment]
I think the easiest solution would be adding `TypeFace` bindings.  I have an idea on how to dump the `MvxLayoutInflater` and make things simpler in this regard but I just haven't had the time to delve into it yet.

**Comment by cfl777** [comment]
@kjeremy That does seem like the easiest solution. 
Thank you Jeremy! really appreciate your help. 

When you get it working, will it be part of the new v5, or be released before that?

**Comment by Cheesebaron** [comment]
If you haven't already seen this: http://smstuebe.de/2017/02/12/mvvmcross-calligraphy/
