### ISSUE TITLE
Improving MvxTargetBindingFactoryRegistry

### ISSUE THREAD

**Issue by Nickolas-** [MvvmCross/MvvmCross#1594]
Hi everybody.

What do you think about change MvxTargetBindingFactoryRegistry method 

`priavte static string GenerateKey(Type type, string name)`

to

`private static int GenerateKey (Type type, string name)`

and use there just GetHashCode and not allocate each time strings?  In my case when you need to create a lot of target bindings it allocate for about 40 mb memory.

**Version:** 4.4.0

**Platform:** Core

**Comment by kjeremy** [comment]
Please submit a pull request for this.
