### ISSUE TITLE
Add id parameter to MvxTabPresentation

### ISSUE THREAD

**Issue by MarcBruins** [MvvmCross/MvvmCross#1614]
For Xamarin UITest we would like to set a "Accessibility identifier" on a tab bar menu item so we can safely navigate to another menu item. Currently this is not supported in the MvxTabPresentation. Ah solution would be something like this:

` [MvxTabPresentation(MvxTabPresentationMode.Tab, "News", "MY_ID", "ic_reorder_36pt", true)] 
`

This is feature request for the iOS MvxTabPresentation and not a bug.

**Comment by Cheesebaron** [comment]
I think we should simply have a default which generates it from the name. So in your case: NewsTab. Then also have an option to set your own.

Not sure if we need to do anything about cleaning the name when assigning to Accessibility ID.

**Comment by MarcBruins** [comment]
That sounds like a better solution @Cheesebaron
