### ISSUE TITLE
MvxUIDatePickerDateTargetBinding should not set default date to DateTime.Now if MaximumDate < Now

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#1618]
File: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Binding/iOS/Target/MvxUIDatePickerDateTargetBinding.cs

Line 31:

      if (value == null)
               value = DateTime.UtcNow;

Instead should check if UIDatePicker.MaximumDate is set and < at now

**Comment by softlion** [comment]
Something like this.
I don't like static either, but there is no way to specify a default date for a specific instance of a target binding in the actual framework. Something like WithConversion([some class instance]) would be a good idea.

        public static DateTime DefaultDate { get; set; } = DateTime.Now;

        protected override object MakeSafeValue(object value)
        {
            var date = (DateTime)(value ?? DefaultDate);

            if (View.MaximumDate!=null && date > (DateTime) View.MaximumDate)
                date = (DateTime) View.MaximumDate;
            else if(View.MinimumDate!=null && date < (DateTime)View.MinimumDate)
                date = (DateTime)View.MinimumDate;

            return (NSDate)date;
        }

**Comment by martijn00** [comment]
Can you make a PR?
