### ISSUE TITLE
MvxCachingFragmentStatePagerAdapter and app Backgrounding results in a null ViewModel

### ISSUE THREAD

**Issue by simon-wainy** [MvvmCross/MvvmCross#1623]
### Steps to reproduce

1. Using the sample at MvvmCross-Samples/XPlatformMenus/

2. Deploy the app to an Android device with Limit Background Processes set to 1 at the most

3. Run up the App, select the View Pager example from the menu

4. Send the app to the background, load a different app, then go back into it again to ensure it has been backgrounded

### Expected behavior
I would expect that the View Pager fragment would re-appear on the Tab that was selected prior to backgrounding

### Actual behavior
There is a null reference error returned due to the following code in RecyclerViewFragment.OnCreateView:
```
_itemSelectedToken = ViewModel.WeakSubscribe(() => ViewModel.SelectedItem,
(sender, args) =>
{
    if (ViewModel.SelectedItem != null)
        Toast.MakeText(Activity,
        string.Format("Selected: {0}", ViewModel.SelectedItem.Title),
        ToastLength.Short).Show();
});
```
The issue is that the ViewModel has not been restored and is null.

The reason I came across this issue is that i am using the MvxCachingFragmentStatePagerAdapter in my own application but rather than initialising the FragmentInfo with the Type of ViewModel:

`new MvxCachingFragmentStatePagerAdapter.FragmentInfo("RecyclerView 1", typeof(RecyclerViewFragment), typeof(RecyclerViewModel))`

 I am using the same model for each FragmentInfo:

`new MvxCachingFragmentStatePagerAdapter.FragmentInfo("RecyclerView 1", typeof(RecyclerViewFragment), ViewModel)`

This results in the same behaviour - a null ViewModel upon app restore from backgrounding

### Configuration

**Version:** 4.4

**Platform:** Android

**Comment by nickrandolph** [comment]
@simon-wainy would you be able to validate this bug against 6.0 please, and confirm that you still need this issue resolved.

**Comment by nmilcoff** [comment]
@simon-wainy unfortunately this is not really an issue.

By default, MvvmCross assumes you will have a different ViewModel instance for each Fragment in the ViewPager. Having one ViewModel per View is a convention the framework has.

I would suggest you apply a different technique to share that model, or otherwise maybe extend `MvxCachingFragmentStatePagerAdapter` to manage your scenario (which won't be a dead easy task, as it inviolves tombstoning!)
