### ISSUE TITLE
MvxFileStore FullPath Customization

### ISSUE THREAD

**Issue by danieleardissone** [MvvmCross/MvvmCross#1630]
Hello,
I have an issue with the File Plugin.
In MVVMCross 3.5 I was able to customize the FullPath property of MvxFileStore with a different path instead of the default one; I created my implementation of that class and overrided that property.
Something like this:

```
internal class CustomMvxAndroidFileStore : MvxFileStore
{
    private Context _context;

    private Context Context
    {
        get
        {
            if (_context == null)
            {
                _context = Mvx.Resolve<IMvxAndroidGlobals>().ApplicationContext;
            }
            return _context;
        }
    }

    protected override string FullPath(string path)
    {
        return Path.Combine(Context.FilesDir.Path, path);
    }
}
```

Now in MVVMCross 4 MvxFileStore doesn't exist anymore.
In my Android project I tried to create a custom class like I did in MVVMCross 3.5; I extended MvxAndroidFileStore and implemented IMvxFileStore interface instead of MvxFileStore, then I injected this new class during Setup. Every time I resolve this class it's not my version (CustomMvxAndroidFileStore) like I expect, but it's the standard MvxAndroidFileStore.
It seems like I am forced to use default MvxAndroidFileStore.

So, how can I change the default save path of the MVVMCross File Plugin?
Thank you.

**Comment by mvanbeusekom** [comment]
Which method (in the Setup) do you use to inject your CustomMvxAndroidFileStore?

**Comment by danieleardissone** [comment]
I tried the classic registration type

`Mvx.RegisterType<IMvxFileStore, CustomMvxAndroidFileStore>();`

and then in my ViewModel constructor

```
private IMvxFileStore _fileStore;
public MenuViewModel (IMvxFileStore fileStore) : base ()
{
    _fileStore = fileStore;
} 
```

or I tried also to register a CustomMvxAndroidFileStore instance as a singleton which implements IMvxFileStore using

`Mvx.RegisterSingleton<IMvxFileStore>(new CustomMvxAndroidFileStore());`

and then in my ViewModel

`var fileStore = Mvx.GetSingleton<IMvxFileStore>();`

In both cases the variables `_fileStore` or `fileStore` are type of `MvxAndroidFileStore` and not of my custom version. I'm not really able to understand this behavior.

**Comment by mvanbeusekom** [comment]
In which method do you do the registration?

**Comment by danieleardissone** [comment]
Yes, I did the registration in InitializeFirstChance method.
My whole process is:

1) Create my implementation of MvxAndroidFileStore

```
public class CustomMvxAndroidFileStore : MvxAndroidFileStore
    {
        public CustomMvxAndroidFileStore()
        {

        }

	private Context _context;

	private Context Context
	{
		get
		{
			if (_context == null)
			{
				_context = Mvx.Resolve<IMvxAndroidGlobals>().ApplicationContext;
			}
			return _context;
		}
	}

	protected override string FullPath(string path)
	{
		return Path.Combine(Context.FilesDir.Path, path);
	}

	private bool PathIsAbsolute(string path)
	{
		return path.StartsWith("/");
	}
}
```

2) Register it in the Setup class

```
protected override void InitializeFirstChance()
{
        base.InitializeFirstChance();
        Mvx.RegisterType<IMvxFileStore, CustomMvxAndroidFileStore>();
}
```

3) Get it in MyViewModel constructor

```
private readonly IMvxFileStore _fileStore;
public MyViewModel (IMvxFileStore fileStore)
{
	_fileStore = fileStore;
}
```

4) Use it in the method I need

```
private void SaveFileToLocal(byte[] data, string path)
{
        _fileStore.WriteFile(path, data);
}
```

I think this process should be correct but in debug mode _fileStore is always MvxAndroidFileStore 

![screenshot 48](https://cloud.githubusercontent.com/assets/20296719/23355841/e1ad7192-fcd7-11e6-89de-3a026fcd185f.jpg)

and my file was not written in the path I expected, of coure.
The MVVMCross version is 4.4.0.

**Comment by Cheesebaron** [comment]
InitializeFirstChance is way too early. This happens _before_ plugins are loaded. Which means your registration gets overwritten.

**Comment by mvanbeusekom** [comment]
In that case try registration in the `InitializeLastChange` method (on a side note, the [MvvmCross documentation](https://github.com/MvvmCross/MvvmCross/wiki/service-location-and-inversion-of-control) currently mentions the use of the `InitializeFirstChange` method, that is why I suggested it).

**Comment by danieleardissone** [comment]
Registrating the class in `InitializeLastChance` solved the issue.
Thanks @Cheesebaron and @mvanbeusekom for your support.

**Comment by Cheesebaron** [comment]
This change you are doing to the FilePlugin, is this something we could do with a  `IMvxPluginConfiguration`? What you are requesting is to set the base path?

**Comment by danieleardissone** [comment]
Yes, I need to change the `FullPath` property in order to save some files into a specific path and not in the default one, `Context.FilesDir`.
My approach is working now, but if you can make a configuration for that I think it could be useful :)
