### ISSUE TITLE
MvxStringToTypeParser doesn't support decimal.

### ISSUE THREAD

**Issue by Pashcal** [MvvmCross/MvvmCross#1635]
We work with prices and try to use IMvxBundle, but we can't use base Read method, cause MvxStringToTypeParser can't parse string to decimal.

PS. May be would be better to use json inside IMvxBundle?

**Comment by kjeremy** [comment]
Is this similar to #564 ?

**Comment by nmilcoff** [comment]
This was appearently fixed in #2171. Please reopen if the solution doesn't work for you.
