### ISSUE TITLE
MvxCachingFragmentCompatActivity Documentation on how to use it

### ISSUE THREAD

**Issue by m-mccool** [MvvmCross/MvvmCross#1636]
Hi,

Is there any documentation on how to use the MvxCachingFragmentCompatActivity. 
For example

- What features does it provide?
- How is it supposed to work?
- What does a developer have to do to make it work?

I'm really stuck on this, but I don't want to say there is a bug when I'm not sure what it is supposed to be doing. I need to know whether it is going to fulfil my need of restoring my navigation stack (fragments and view models) when my single activity is destroyed.

At the moment I am getting strange behaviour,

- Cannot close fragment from it's own ViewModel
- View models seem not to be recreated, or the binding between fragment and view model is not restored when going forward and back in the hierarchy.
    
I've tried to debug it to figure it out, but without any idea of what it is supposed to do it's proving futile.

Normally I would not raise an issue like this, but I need to solve an issue quickly. So apologies in advance.

**Comment by Cheesebaron** [comment]
Github issues are only for _issues_. Please use StackOverflow or Slack for questions such as these. If you have an actual bug you want to report, please do that and fill out the issue template.

**Comment by m-mccool** [comment]
http://stackoverflow.com/questions/42510837/understanding-of-mvxcachingfragmentcompatactivity
