### ISSUE TITLE
New RecyclerView Grouping crash on Clear/Insert sequence

### ISSUE THREAD

**Issue by thefex** [MvvmCross/MvvmCross#1640]
New RecyclerView Grouping feature crashes when ObservableCollection is Cleared and then some items are inserted.
It crashes with RecyclerView viewholder incosistency.
Preparing fix.

**Comment by thefex** [comment]
I have implemented support for Group Child collection INotifyCollectionChanged event supports (add/remove/reset) - dynamic group childs collection.

Turns out that crashes was not a bug in grouping implementation.
Support Library RecyclerView has crash bug - https://code.google.com/p/android/issues/detail?id=77846#c10. It says it's fixed - bullshit (check comments). That bug have crashed my app when I was using grouping. I think it has showed with grouping because there are a lot of Insert/Remove sequence operations.

I will push dynamic child support + crash workaround in a moment.

**Comment by thefex** [comment]
Pushed pull request with RecyclerView crashes.
I will add INotifyCollectionChanged of Group Child collection in separate issue.

**Comment by Nickolas-** [comment]
Hi got the same exceptions , but the problem was with not properly dispatching event. Did you check it ?

**Comment by thefex** [comment]
it's not an issue with "event dispatching". It 's just crash with normal ObservableCollection - easy to reproduce when a lot of Remove/Insert sequence calls are made.
Check google issue I have mentioned.

**Comment by Nickolas-** [comment]
Are you using MvxObservableCollection ? I guess you dispatching event not on UI thread.

**Comment by kjeremy** [comment]
I would definitely make sure you are doing everything on the UI thread.

**Comment by thefex** [comment]
I am using RX and I do the thing on UI thread. Well if it was UI thread issue the exception would not be IndexOfOutBoundsException + it would always crash (it does not always crash, just sometimes when Clear + Add is called).

**Comment by Nickolas-** [comment]
ObservableCollection not thread safe, so maybe you are invoking insert , remove from different thread that can cause this issues.

**Comment by thefex** [comment]
I don't, I use RX DynamicData and I always, explictly specify that things related to collection modification should be invoked on Current SynchronizationContext which is in fact UI thread.

**Comment by thefex** [comment]
I guess I have to implement reproduction sample so you will start to believe that something it's fucked with recyclerview. Will do it and ping you back - but not earlier than on weekend

**Comment by kjeremy** [comment]
Thanks! A reproduction case would be great.

**Comment by Nickolas-** [comment]
if you have a test project , I could take a look , what's happening.
