### ISSUE TITLE
JsonLocalization plugin can't load resources with dash ( - ) in path

### ISSUE THREAD

**Issue by LeRondPoint** [MvvmCross/MvvmCross#1645]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Try to load a resource with a "-" in the path
2. FAIL

### Expected behavior
When embedding resources, dashes are replaced with underscores.  The plugin doesn't replace the dashes when trying to load embedded Json files.  This is unfortunate because ISO languages have a dash in them...

### Actual behavior

    private string GetTextFromEmbeddedResource(string namespaceKey, string resourcePath)
    {
      string name = namespaceKey + "." + resourcePath.Replace("/", ".");
...

Becomes 

    private string GetTextFromEmbeddedResource(string namespaceKey, string resourcePath)
    {
      string name = namespaceKey + "." + resourcePath.Replace("/", ".").Replace("-", "_");
...

### Configuration

**Version:** 4.4

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by jz5** [comment]
To add ```.Replace("-", "_")``` isn't enough.

Folder path of  ```resourcePath``` is renamed. Filename isn't renamed.
And replaced character isn't only '-'.
(https://msdn.microsoft.com/en-us/library/ms145952.aspx)

My approach is the following.

```C#
var path = namespaceKey + "." + resourcePath.Replace("/", ".");
```
to
```C#
var names = resourcePath.Split('/');
var list = names.Take(names.Count() - 1).Select(name =>
{
    if (name == string.Empty) return "_";

    var builder = new System.Text.StringBuilder();
    if ('0' <= name[0] && name[0] <= '9')
    {
        builder.Append('_');
    }
    foreach (var c in name)
    {
        builder.Append(invalidChars.Contains(c) ? '_' : c);
    }
    return builder.ToString();

}).ToList();
list.Add(names.Last());
var path = namespaceKey + "." + string.Join(".", list);
```
and
```C#
private static readonly HashSet<char> invalidChars = new HashSet<char>() { ' ', '\u00A0', '.', ',', ';', '|', '~', '@', '#', '%', '^', '&', '*', '+', '-', '/', '\\', '<', '>', '?', '[', ']', '(', ')', '{', '}', '"', '\'', ':', '!' };
```

**Comment by LeRondPoint** [comment]
Yeah indeed, thanks for the official documentation.  @martijn00 can you assign this bug to me?

**Comment by LeRondPoint** [comment]
@jz5 There were a couple of mistakes in your solution, which I fixed with a different implementation.  I'm also not exactly sure how tyo handle the double slash case.  Should "abc//def" return "abc.def" or "abc._.def"?

**Comment by jz5** [comment]
@LeRondPoint It seems that "//" is same "/". So "abc//def" return "abc.def".

**Comment by LeRondPoint** [comment]
Thanks for trying before I had the time, will push my changes right away

**Comment by LeRondPoint** [comment]
https://github.com/MvvmCross/MvvmCross/pull/1929
