### ISSUE TITLE
InfoWindowClick does not work with ShowViewModel

### ISSUE THREAD

**Issue by texas16** [MvvmCross/MvvmCross#1647]
(http://stackoverflow.com/questions/42728757/markerclick-works-but-infowindowclick-does-not-open-viewmodel) 

### Configuration

**Version:** 4.x

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by Cheesebaron** [comment]
Closing this, no information provided.
