### ISSUE TITLE
VeeThree - View level long click support

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#165]
would be nice to support View.LongClick (not to be confused with ListItemLongClick)

see http://stackoverflow.com/questions/14926889/mvvmcross-custom-binding-to-eventhandler

**Comment by ilfat** [comment]
So how to use it?:)

**Comment by ilfat** [comment]
local:MvxBind="LongClick MyButtonLongClick" okay...

**Comment by jamie94bc** [comment]
@ilfat in future please use StackOverflow for questions such as these :+1:
