### ISSUE TITLE
Visual Studio 2017 Xamarin can't install nuget package MvvmCross.Plugin.DownloadCache plugin

### ISSUE THREAD

**Issue by IvanZaporozhchenko** [MvvmCross/MvvmCross#1652]
I have installed Visual Studio 2017. I try to create application using mvvm cross. I sucessfully added mvvm cross library, but when I try to install MvvmCross.Plugin.DownloadCache package I got this:
"Could not install package 'Xamarin.Android.Support.Compat 24.2.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

### Steps to reproduce

1. Install VS 2017

2. Create Native Cross-Plaform App

3.Install Mvvm Cross DownloadCache library for Droid project

### Expected behavior
Plugin should installed correctly

### Actual behavior
Plugin is not installed

### Configuration

**Version:** 4.4

**Platform:**Android

**Comment by Cheesebaron** [comment]
This doesn't have anything to do with MvvmCross. Your targets are simply wrong.

**Comment by IvanZaporozhchenko** [comment]
Sorry for bothering. Installing Android API 7.0 solved my issue
