### ISSUE TITLE
FusedLocationHandler crashing with MvxException: SERVICE_MISSING

### ISSUE THREAD

**Issue by SOFSPEEL** [MvvmCross/MvvmCross#1669]
Our crash reporting system occasionally sees the following crash on field devices:

	MvvmCross.Platform.Exceptions.MvxException: SERVICE_MISSING
1	at .MvvmCross.Platform.Exceptions.MvxException : SERVICE_MISSING()
2	at . at MvvmCross.Plugins.Location.Fused.Droid.FusedLocationHandler.EnsureGooglePlayServiceAvailable (Android.Content.Context context) [0x0002e] in <7bf094c6050c41f2b80aa223107331e1>:0 ()
3	at . at MvvmCross.Plugins.Location.Fused.Droid.FusedLocationHandler..ctor (MvvmCross.Plugins.Location.Fused.Droid.MvxAndroidFusedLocationWatcher owner, Android.Content.Context context) [0x0000d] in <7bf094c6050c41f2b80aa223107331e1>:0 ()
4	at . at MvvmCross.Plugins.Location.Fused.Droid.MvxAndroidFusedLocationWatcher.PlatformSpecificStart (MvvmCross.Plugins.Location.MvxLocationOptions options) [0x00010] in <7bf094c6050c41f2b80aa223107331e1>:0 ()
5	at . at MvvmCross.Plugins.Location.MvxLocationWatcher.Start (MvvmCross.Plugins.Location.MvxLocationOptions options, System.Action`1[T] success, System.Action`1[T] error) [0x0001a] in <1078b1c244034921a312c92d3d8be56a>:0 ()
6	at . at ACS.FundRaising.Services.LocationService.Start () [0x0001d] in <99abd5c0b0eb48b18f27ab797454277f>:0 ()
7	at . at ACS.FundRaising.ViewModels.Registration.FindEventsViewModel+<KickOfLocationServiceAsync>c__async2.MoveNext () [0x000a5] in <99abd5c0b0eb48b18f27ab797454277f>:0 ()
8	at .--- End of stack trace from previous location where exception was thrown ---()
9	at . at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
10	at . at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
11	at . at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
12	at . at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
13	at . at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
14	at . at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<ExecuteConcurrentAsync>d__17.MoveNext () [0x0013a] in <69bce0378e8e413982d3b552d7e387a8>:0 ()
15	at .--- End of stack trace from previous location where exception was thrown ---()
16	at . at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
17	at . at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
18	at . at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
19	at . at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
20	at . at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
21	at . at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<ExecuteAsync>d__16.MoveNext () [0x00088] in <69bce0378e8e413982d3b552d7e387a8>:0 ()
22	at .--- End of stack trace from previous location where exception was thrown ---()
23	at . at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
24	at . at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
25	at . at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
26	at . at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
27	at . at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
28	at . at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<Execute>d__14.MoveNext () [0x00073] in <69bce0378e8e413982d3b552d7e387a8>:0 ()
29	at .--- End of stack trace from previous location where exception was thrown ---()
30	at . at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
31	at . at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <07c3d7a06e084fedbb8a66bf5b55411f>:0 ()
32	at . at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <33f57c9e23d243a993c2ebf00a8b5edf>:0 ()
33	at . at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <33f57c9e23d243a993c2ebf00a8b5edf>:0 ()
34	at . at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <33f57c9e23d243a993c2ebf00a8b5edf>:0 ()
35	at . at (wrapper dynamic-method) System.Object:f80ffdb8-4379-4c5e-8709-f4bce775a773 (intptr,intptr)()

The following shows the device this occurred on, and OS the device was running
![image](https://cloud.githubusercontent.com/assets/1612646/24515319/20c0a3f6-152c-11e7-89e0-e05d2f0f0a1a.png)

### Expected behavior
Shouldn't crash

### Actual behavior
Crashes

### Configuration

**Version:** 4.4

**Platform:** Android

**Comment by Cheesebaron** [comment]
Looking at the code: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-Plugins/Location/MvvmCross.Plugins.Location.Fused.Droid/FusedLocationHandler.cs#L101

This happens because Google Play Services claims that the Play Service is missing. https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability.html#isGooglePlayServicesAvailable(android.content.Context)

> Verifies that Google Play services is installed and enabled on this device, and that the version installed on this device is no older than the one required by this client.

Make sure that the device in question has Play Services installed, up to date and enabled.

It crashes only because you are not catching the exception. However, since this is a Plugin, this would happen when it is initialized, probably making you unable to catch this exception at all, because all this happens behind your back.

The least we can do is to move the Initialization and checking for Play services into start and do that if `_client` is null. Then you can catch the exception when calling `Start()`, instead of crashing hard.

Thanks for reporting this.
