### ISSUE TITLE
Cleanup: Obsolete MvxFormFactorSpecificAttribute

### ISSUE THREAD

**Issue by nmilcoff** [MvvmCross/MvvmCross#1670]
I might be wrong, but it seems to me there are some classes out there about the iOS platform that are obsolete:

- [MvxFormFactorSpecificAttribute](https://github.com/MvvmCross/MvvmCross/blob/8a824c797747f74716fc64c2fd0e8765c29b16ab/MvvmCross/iOS/iOS/Views/MvxFormFactorSpecificAttribute.cs): This one went obsolete when all apps migrated to iOS Universal, take a look at [this PR](https://github.com/MvvmCross/MvvmCross/pull/916)
- [IMvxIosPlatformProperties](https://github.com/MvvmCross/MvvmCross/blob/8a824c797747f74716fc64c2fd0e8765c29b16ab/MvvmCross/iOS/iOS/Platform/IMvxIosPlatformProperties.cs) 
- [MvxIosPlatformProperties](https://github.com/MvvmCross/MvvmCross/blob/8a824c797747f74716fc64c2fd0e8765c29b16ab/MvvmCross/iOS/iOS/Platform/MvxIosPlatformProperties.cs)
-  [MvxIosDisplayDensity](https://github.com/MvvmCross/MvvmCross/blob/8a824c797747f74716fc64c2fd0e8765c29b16ab/MvvmCross/iOS/iOS/Platform/MvxIosDisplayDensity.cs)
- [MvxIosFormFactor](https://github.com/MvvmCross/MvvmCross/blob/8a824c797747f74716fc64c2fd0e8765c29b16ab/MvvmCross/iOS/iOS/Platform/MvxIosFormFactor.cs)

These are marked as obsolete, and there are some plugins to grab this info, like [this one](https://github.com/Cheesebaron/Cheesebaron.MvxPlugins/tree/master/DeviceInfo).

**Comment by martijn00** [comment]
Can you make a PR to remove those and clean it up? As this might be breaking it would be good to do for 5.0.
