### ISSUE TITLE
MvvmCross.Plugins.File MvxFileStore read using full path

### ISSUE THREAD

**Issue by darrencl** [MvvmCross/MvvmCross#1673]
### Steps to reproduce

1. Create `OpenReadFullPath(string fullPath)` method

### Expected behavior
I need to the option to use full path in `MvxFileStore`  instead of always using the default. Now, I only need `OpenRead` to read full path.

### Actual behavior
Now, the plugin always add its default path (base path) to the beginning of supplied path.

### Configuration

**Version:** 4.4

**Platform:** Android

**Comment by martijn00** [comment]
Can you make a PR to fix this?
