### ISSUE TITLE
Registering services in InitializeFirstChance not working as expected

### ISSUE THREAD

**Issue by UKDeveloper99** [MvvmCross/MvvmCross#1676]
So either I'm misusing the software or I'm experiencing broken behavior.  I have a particular service that **has** to be created and started in InitializeFirstChance() before certain MvvmCross setup code has kicked off. So I register my service using `Mvx.RegisterSingleton<IRepositoryService>(new RepositoryService());` However this service is part of a recursive tree of services (using the IoC parameter injection). The root service of this service tree I also need to create at the beginning of the app and I register this root service in InitializeLastChance(). I use `			Mvx.ConstructAndRegisterSingleton<IDataSyncingService, DataSyncingService>();`. So this goes through all the service constructors in the tree either resolving them or initializing them. Now when it gets to the last service, my repository service. It should resolve the one I registered in InitializeFirstChance() but it doesn't it recreates it, so I now have 2 instances of repository service, the other one is probably floating around in memory somewhere. 
So I did a bit of testing and digging and it seems like any service registered as a singleton in InitializeFirstChance() can't be accessed later. If I register a service there and then put an Mvx.Resolve<>() for that service in InitializeLastChance(); it just tries to recreate the service rather than giving me the singleton instance that it should be giving me.
So if I move my IRepository registration to App.cs `Initialize()` it works fine. It's obviously an issue with registering services in InitializeFirstChance().

Am I misusing or misunderstanding something here?

### Steps to reproduce

1. Register a service in `InitializeFirstChance()` using `Mvx.RegisterSingleton<>(..);`

2. Attempt to resolve that service in `InitializeLastChance()`

### Expected behavior
Should resolve the service singleton that was registered.

### Actual behavior
Recreates (initializes) the service using the first constructor in the service.

### Configuration

**Version:** 4.4.0

**Platform:** Xamarin.iOS

**Comment by Cheesebaron** [comment]
`ConstructAndRegisterSingleton` just does:

    var ioc = MvxSingleton<IMvxIoCProvider>.Instance;
    ioc.RegisterSingleton<TInterface>(IocConstruct<TType>());

Reading your looooong textual description, what I gather is. You get:

    Mvx.RegisterSingleton<IRepositoryService>(new RepositoryService());
    // Mvx does its stuff here...
    Mvx.ConstructAndRegisterSingleton<IDataSyncingService, DataSyncingService>();

Then in some ViewModel or whatever you do `Mvx.Resolve<IDataSycingService>()` or get it through the Ctor through injection.

And when you subsequently call `Mvx.Resolve<IDataSyncingService>()` it gives you a new instance? Which you check how? Just a breakpoint in the ctor of that service?

**Comment by UKDeveloper99** [comment]
I like long descriptions, if I describe the same issue in several different ways one of them might make sense :)

My point is `Mvx.ConstructAndRegisterSingleton<IDataSyncingService, DataSyncingService>();` behaves differently depending on whether I have called `Mvx.RegisterSingleton<IRepositoryService>(new RepositoryService());` in `InitializeFirstChance()` **or** either in `app.Initialize()` / `InitializeLastChance()`. 
Because IRepositoryService is part of the dependency tree for IDataSyncingService when it gets to the service in the tree that injects IRepositoryService in to the ctor. It will either inject a new instance of IRepositoryService in the constructor or the singleton instance that I registered previously.  Dependent on where I register IRepositoryService; i.e. the former or the latter as described above.
If I have previously registered the IRepositoryService, I would expect it to always use the existing singleton instance.

**Comment by Cheesebaron** [comment]
Please make a concise example of what you are doing. It is unclear to me from all the filler words you are adding to your answers what is going on. The details get drowned.

Even better make a small reproduction repository with what I need to do in order to reproduce.

**Comment by UKDeveloper99** [comment]
I'm explaining it perfectly clearly I don't see what you're having difficulty understanding. If you register a singleton in `InitializeFirstChance()` then call `Mvx.Resolve<>(..)` for that same singleton in `InitializeLastChance()`. You will get an mvx exception that the singleton can't be found. Try it yourself. If you're still having difficulty understanding that I shall put together a reproduction case for you.

p.s. I don't like your sarcastic unprofessional tone that I've observed in this thread and half the other posts you've ever written on the internet. Maybe you want to rethink your attitude.

**Comment by Cheesebaron** [comment]
You were explaining it perfectly clearly, so _you_ understood it.

Please make a repro.

P.S. None of my answers have been sarcastic, at least I don't think they were. Nor was my intention to make sarcastic answers. Please point out exactly where things went south, so I can learn and improve on future answers.

**Comment by UKDeveloper99** [comment]
The fact you didn't think they were sarcastic or condescending is a perfect example of why it would be a futile endeavor for me to explain to you why they were. That's all I have to say on the matter.

I'll make a repro when I get a minute.

**Comment by Cheesebaron** [comment]
> It is unclear to me from all the filler words you are adding to your answers what is going on. The details get drowned.

I only see these two sentences which just point out the obvious about your comments. Too many words, too few concise examples not making yourself clear to me.

Let me quote Mark Twain: "If I Had More Time, I Would Have Written a Shorter Letter".

**Comment by UKDeveloper99** [comment]
Well I'm sorry if the summary in the 2nd to last post was too complex for you to follow. Here's a code sample to get you started.

```
		protected override void InitializeFirstChance()
		{
			base.InitializeFirstChance();
			
			// New instance here
			Mvx.RegisterSingleton<IRepositoryService>(new RepositoryService());
		}

		protected override void InitializeLastChance()
		{
			// Exception here
			var repositoryService = Mvx.Resolve<IRepositoryService>();
		}
```

**Comment by Cheesebaron** [comment]
That examples shows nothing that does not work.

    public interface IRepositoryService
    {
    }

    public class RepositoryService : IRepositoryService
    {
    }

+ your example. Works fine.

**Comment by UKDeveloper99** [comment]
Please breakpoint in the constructor of RepositoryService. If it's not being called twice I shall attempt to reproduce.

**Comment by Cheesebaron** [comment]
Ctor only gets called once.

**Comment by UKDeveloper99** [comment]
Strange that's not the behavior I'm experiencing. I shall attempt to reproduce then.

**Comment by UKDeveloper99** [comment]
Yeah exactly! Normally I use that default behavior. But there are certain circumstances where I need to service to be available immediately. 

FYI I just put that code above in to a random empty test project I have floating around and the constructor is being called twice. So I'll wrap that up in to a github project and link it when I get a moment.
Cheers.

**Comment by Cheesebaron** [comment]
That would make sense. `InitializeFirstChance` happens before `App.Initialize` gets called. Hence, your registration will get overridden. 

You can exclude stuff from the `CreatableTypes` registration:

    .Except<IRepositoryService>()

**Comment by UKDeveloper99** [comment]
Perfect, I'll try that.

**Comment by UKDeveloper99** [comment]
That's fixed the original issue. Thank you. I shall close the issue.
