### ISSUE TITLE
Sample Forms projects on older versions of MvvmCross and Xamarin.Forms

### ISSUE THREAD

**Issue by ehuna** [MvvmCross/MvvmCross#1679]
### Steps to reproduce

1.  Look the latest Forms examples from https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Forms/Example001CSharp/

2.  Notice that in https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Forms/Example001CSharp/Example/packages.config

The nuget package version are 'Xamarin.Forms' version '2.2.0.31' and 'MvvmCross*' version '4.1.5'

### Expected behavior
I see the latest 'MvvmCross*' nuget packages are '4.4.0' (https://www.nuget.org/packages/MvvmCross/)
and the latest 'Xamarin.Forms*' nuget packages are '2.3.4.224' (just released, with among other things a bindable picker, https://www.nuget.org/packages/Xamarin.Forms/)

Do you think  MvvmCross v4.4.0 works with Xamarin.Forms v2.3.4.224?

Once I get confirmation I can work on upgrading the sample projects.

Thanks,
Emmanuel

**Comment by ehuna** [comment]
@martijn00 do you know by any chance if the latest Xamarin Forms and MvvmCross packages would work?  Or what are the latest versions you think work?

Thanks,
Emmanuel

**Comment by martijn00** [comment]
The latest should work, but those samples should be based on a reference so we can debug, and not on a nuget package.

**Comment by ehuna** [comment]
ah got it

Any plans for having samples somewhere with the latest?

I can help if you provide direction.

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/1745
