### ISSUE TITLE
Master detail - working xamarin forms example

### ISSUE THREAD

**Issue by mdonogma** [MvvmCross/MvvmCross#1681]
Been trying to locate a working Xamarin forms MVVMCross example demonstrating master detail in action.

Logged an issue in original MVVMCross Forms repository which did not resolved. Commands in detail page viewmodels still do not fire.
https://github.com/MvvmCross/MvvmCross-Forms/issues/63

It is essential I get something functional we can move forward with.

any direction would be appreciated

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/1745
