### ISSUE TITLE
Remove JASidePanels

### ISSUE THREAD

**Issue by MarcBruins** [MvvmCross/MvvmCross#1682]
Should we remove  the JASidePanels implementation? It is a wrapper around another package which we don't control with some issues in there. When someone ask about a hamburger menu in MvvmCross i always say that they need to use XamarinSideBar and not JASidePanels. XamarinSideBar gets updated regularly in MvvmCross and JASidepanels does not. Furthermore the same look that JASidePanels has (the topbar) can be easily implemented for XamarinSideBar as wel. So there are no benefits at all in using JASidepanels.

**Comment by kjeremy** [comment]
I vote to kill it.  It's fairly easy to implement this on your own if need be.

**Comment by JelleDamen** [comment]
I agree, and while we're removing things. Can we also remove the default "Menu" menu that is automatically added: https://github.com/MvvmCross/MvvmCross/blob/8db8bf50c21afcf47b4ccb1d3bc19c570db06347/MvvmCross-iOSSupport/MvvmCross.iOS.Support.XamarinSidebar/Hints/MvxSidebarResetRootPresentationHint.cs#L32

**Comment by kjeremy** [comment]
Make some PRs

**Comment by mvanbeusekom** [comment]
You also have my vote, since it is a bit buggy (I have received several complaints and instructed people to move to Xamarin Sidebar)

Although I would like to note that JASidePanels (if working) should support more advanced Master-Detail functionality (Xamarin Sidebar basically just implements a fly-out menu).

**Comment by mvanbeusekom** [comment]
@JelleDamen I will have a look at the default "Menu" menu button. This could be a but in the Xamarin Sidebar implementation.
