### ISSUE TITLE
Master Detail Example Project Doesn't Compile with Latest MvvmCross Nuget Packages

### ISSUE THREAD

**Issue by foehammer88** [MvvmCross/MvvmCross#1699]
Trying to get the Master-Detail Example project working, to see if I can implement the Master-Detail architecture in my app.

### Steps to reproduce

1. Get the latest MvvmCross git repository and open the TestProjects\Forms\MasterDetail\MasterDetailExample.Core project.

2. Install the latest Nuget packages for MvvmCross, MvvmCross.Forms.Presenter, and Xamarin.Forms

3. Try to build, and observed that it doesn't compile because it can't resolve MvxMasterDetailViewModel in MvvmCross.Forms.Presenter.Core.

### Expected behavior
MvxMasterDetailViewModel should resolve in the MvvmCross.Forms.Presenter namespace in latest Nuget packages, then the project should build and be able to run.

### Actual behavior
The project doesn't compile and theres an error on MvxMasterDetailViewModel reference, in the MainViewModel of the MasterDetailExample.Core project. 

"CS0246	The type or namespace name 'MvxMasterDetailViewModel<>' could not be found (are you missing a using directive or an assembly reference?)"

### Configuration

**Version:** 4.4.0 MvvmCross, MvvmCross.Forms.Presenter, 2.3.3.180 Xamarin.Forms

**Platform:** Core/Android

**Comment by kjeremy** [comment]
PRs welcome.

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/1745
