### ISSUE TITLE
Binding data with headers does not work 

### ISSUE THREAD

**Issue by jonoommen** [MvvmCross/MvvmCross#1702]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1.

2.

3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Version:** 4.x

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by martijn00** [comment]
Please fill in the template to make clear what the problem is. Also post some code so we can see what you do.

**Comment by martijn00** [comment]
Headers is only available in MvvmCross 5.0.
