### ISSUE TITLE
Website: Missing margins between logos

### ISSUE THREAD

**Issue by CayasSoftware** [MvvmCross/MvvmCross#1712]
### Steps to reproduce

1. Open mvvmcross.com in Safari or Chrome on Android
2. Scroll down "Over 5000 companies rely on MvvmCross"

### Expected behavior
I would expect that there is some space between the logo images.

### Actual behavior
Each image sticks right to the next one.

### Configuration

**Platform:** Chrome on Android, Safari on iOS

**Comment by Cheesebaron** [comment]
![screenshot](http://i.imgur.com/RP0dkHY.png)

**Comment by MarcBruins** [comment]
I've added this issue to #1727. Thanks for shooting this in @CayasSoftware
