### ISSUE TITLE
Ratingbar binding broken android after updated to 4.4.0

### ISSUE THREAD

**Issue by Happin3ss** [MvvmCross/MvvmCross#1719]
1. Updated to mvvmcross 4.4.0 ( included MvvmCross.Droid.Support.V7.AppCompat)

2. MvxBind Rating doesn't work anymore for Ratingbar (worked well before) IN RELEASE MODE !! It's still work well in debug mode . 
  I'm using Multidex because of over 64k limit with google play services plus components and not sure it's relate or not.
 I noticed that this kind of broken is happened with edittext/textview and we have to change TextChanged->AfterTextChanged in Linker but I'm still have not figured out any solution for ratingbar
3. Some sample code:
XAML:
```
<RatingBar
      android:id="@+id/ratingbar"
      style="?android:attr/ratingBarStyleSmall"
      android:layout_height="wrap_content"
      android:layout_width="wrap_content"
      android:progressTint="@color/StarColor"
      android:progressDrawable="@drawable/ratingbar_style"
      android:numStars="5"
      android:stepSize="1"
      android:isIndicator="true"
      local:MvxBind="Rating Rating" />
```

Linker attached.
[LinkerPleaseInclude.zip](https://github.com/MvvmCross/MvvmCross/files/953783/LinkerPleaseInclude.zip)
 Thank you for help :)
### Configuration

**Version:** 4.4

**Platform:Android

```

**Comment by Happin3ss** [comment]
Fixed by add this to Linker 👍

```
public void Include(RatingBar ratingBar)
		{
			ratingBar.RatingBarChange += (sender, args) => ratingBar.Rating = 0 + ratingBar.Rating;
		}
```

**Comment by martijn00** [comment]
Added to the default linker now: https://github.com/MvvmCross/MvvmCross/commit/2a1c4fb41aa228946a25f68c35d786f9845e8404
