### ISSUE TITLE
How to Access UI object from ViewModel

### ISSUE THREAD

**Issue by jojinshallar** [MvvmCross/MvvmCross#1728]
I‘m a beginer who uses MvvmCross for the Xamarin.Android.I try to realize the function like 'click the button and show a dialog to say hello'.

    When I use the way which sets ViewModel object to Activity object's DataContext to bind,I can pass UI object directly (or using Interface indirectly).In this way,I can access UI object to show a dialog.  

    In another way likes the offical demo, bing the UI object and ViewModel automatically,how can I show the dialog?The auto bing code like this 

` public class App:MvxApplication
    {
        public App()
        {
            Mvx.RegisterSingleton<IMvxAppStart>(new MvxAppStart<CalculateDemoViewModel>());
        } 
    }`

` [Activity(Label = "MvvmC_TutorialActivity")]
    public class MvvmC_TutorialActivity : MvxActivity<CalculateDemoViewModel>
{
.............
}`

    Hope someone to help me soon!Thanks!

**Comment by Cheesebaron** [comment]
Please use StackOverflow, Xamarin Forums or Slack for questions. Github is for bugs and issues only.

Closing this.
