### ISSUE TITLE
Custom MvxRecyclerViewAdapters don't work anymore

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#1730]
If you create a dummy `MvxRecyclerAdapter` it's `ItemSource` property gets set to an instance of
`MvvmCross.Droid.Support.V7.RecyclerView.ItemSources.MvxRecyclerViewItemsSourceBridgeHeaderFooterDecorator`

and not something reasonable like a list of stuff.

**Comment by kjeremy** [comment]
@thefex 

MvxRecyclerView ctor has the following:
```csharp
var itemTemplateId = MvxAttributeHelpers.ReadListItemTemplateId(context, attrs);
var itemTemplateSelector = MvxRecyclerViewAttributeExtensions.BuildItemTemplateSelector(context, attrs);

adapter.ItemTemplateSelector = itemTemplateSelector;
Adapter = adapter;

if (itemTemplateSelector.GetType() == typeof(MvxDefaultTemplateSelector))
    ItemTemplateId = itemTemplateId;
```

This looks... weird to me.  Why are we checking if the `itemTemplateSelector` is `MvxDefaultTemplateSelector`?  We shouldn't be differentiating based on type.  There's some of this in the source bridges as well.  Can we encapsulate some of this behavior in virtual functions or something?

That `ItemTemplateId` setter will turn around and set the adapter's `ItemTemplateSelector` as well so we're doing the work twice.  I think there may be a bug here.

**Comment by kjeremy** [comment]
Ok some more details so I don't forget...

When you set the custom adapter the items source gets reassigned but if it was an `IList` it now loses that and becomes a `MvxRecyclerViewItemsSourceBridgeHeaderFooterDecorator`.

**Comment by kjeremy** [comment]
so the `MvxFullBinding` sets `MvxRecyclerView.ItemsSource` to the correct value.  By the time the second adapter is set the original one's `ItemsSource` has already been wrapped and it gets all messed up.  I think we need to track the original `ItemsSource` and somehow use that instead.

**Comment by Cheesebaron** [comment]
This sounds like a pretty nasty regression here. If people are not able to use their own Adapter without all sorts of issues, this feature is a no-go.
