### ISSUE TITLE
gitlink isn't adding the correct source information to the pdbs

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#1731]
While debugging an issue in the 5.0 beta I'm running into src lines looking for ex:

>  	0x1F in MvvmCross.Droid.Support.V7.RecyclerView.MvxRecyclerView.set_Adapter at C:\agent\_w\1\s\MvvmCross-AndroidSupport\MvvmCross.Droid.Support.V7.RecyclerView\MvxRecyclerView.cs:98,21	C#

That should be pointing to our github repo.

**Comment by Cheesebaron** [comment]
Do you know whether this is for all symbols or some specific ones?

**Comment by kjeremy** [comment]
Looks like everything:

> >	0xC in EugsClient.Droid.Converters.BatteryLevelToTintedImageConverter.Convert at C:\Projects\EugsClient\EugsClient\EugsClient.Droid\Converters\BatteryLevelToTintedImageConverter.cs:20,13	C#
 	0xB in MvvmCross.Platform.Converters.MvxValueConverter<double,Android.Graphics.Drawables.Drawable>.Convert at C:\agent\_w\1\s\MvvmCross\Platform\Platform\Converters\MvxValueConverter.cs:34,17	C#
 	0x5C in MvvmCross.Binding.Combiners.MvxValueConverterValueCombiner.TryGetValue at C:\agent\_w\1\s\MvvmCross\Core\Binding\Combiners\MvxValueConverterValueCombiner.cs:79,13	C#
 	0x13 in MvvmCross.Binding.Bindings.SourceSteps.MvxCombinerSourceStep.GetSourceValue at C:\agent\_w\1\s\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxCombinerSourceStep.cs:135,13	C#
 	0x1 in MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.GetValue at C:\agent\_w\1\s\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:175,13	C#
 	0x38 in MvvmCross.Binding.Bindings.MvxFullBinding.UpdateTargetOnBind at C:\agent\_w\1\s\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:121,21	C#
 	0x26 in MvvmCross.Binding.Bindings.MvxFullBinding.set_DataContext at C:\agent\_w\1\s\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:57,17	C#
 	0x38 in MvvmCross.Binding.BindingContext.MvxBindingContext.OnDataContextChange at C:\agent\_w\1\s\MvvmCross\Core\Binding\BindingContext\MvxBindingContext.cs:207,21	C#
 	0x12 in MvvmCross.Binding.BindingContext.MvxBindingContext.set_DataContext at C:\agent\_w\1\s\MvvmCross\Core\Binding\BindingContext\MvxBindingContext.cs:193,17	C#
 	0x7 in MvvmCross.Droid.Support.V7.RecyclerView.MvxRecyclerViewHolder.set_DataContext at C:\agent\_w\1\s\MvvmCross-AndroidSupport\MvvmCross.Droid.Support.V7.RecyclerView\MvxRecyclerViewHolder.cs:41,17	C#
 	0xF in MvvmCross.Droid.Support.V7.RecyclerView.MvxRecyclerAdapter.OnBindViewHolder at C:\agent\_w\1\s\MvvmCross-AndroidSupport\MvvmCross.Droid.Support.V7.RecyclerView\MvxRecyclerAdapter.cs:260,13	C#
 	0x14 in Android.Support.V7.Widget.RecyclerView.Adapter.n_OnBindViewHolder_Landroid_support_v7_widget_RecyclerView_ViewHolder_I	C#

**Comment by Cheesebaron** [comment]
OK, good to know. I will hunt it a bit. Maybe we need to provide more settings to GitLink.

**Comment by Cheesebaron** [comment]
Should be fixed in #1734

**Comment by martijn00** [comment]
@kjeremy does it work with beta3?

**Comment by Cheesebaron** [comment]
Some files. Such as MvvmCross.Plugins.Location.Fused.Droid isn't patched correctly. I think this will be solved when GitLink 3.0 is released as it doesn't use an ancient version of bundled MSBuild. We can see this in the warnings we get on build that pdbstr can't load a whole bunch of our projects on build...

**Comment by kjeremy** [comment]
@martijn00  no this still fails with beta 6.

**Comment by Cheesebaron** [comment]
Yeah, loads of projects it cant generate for :( Hopefully GitLink 3.0 fixes this.

**Comment by Cheesebaron** [comment]
GitLink has been replaced by SourceLink. Closing this.
