### ISSUE TITLE
Kill `MvxAllThreadDispatchingObject`

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1750]
This is only used 1 place, inside of DownloadCache. Can we please kill this horrible type off?

**Comment by Cheesebaron** [comment]
Also kill `MvxAsyncDispatcher` while at it

**Comment by willsb** [comment]
Could [this](https://github.com/MvvmCross/MvvmCross/blob/master/MvvmCross-Plugins/DownloadCache/MvvmCross.Plugins.DownloadCache/MvxImageCache.cs#L89) be replaced with a simple `Task.Run` or a lock actually needed?

**Comment by Cheesebaron** [comment]
I don't think a lock is needed. Could probably also be made static.
