### ISSUE TITLE
How to "hook into" and do some post processing after a call to BindingInflate?

### ISSUE THREAD

**Issue by Cybrosys** [MvvmCross/MvvmCross#1769]
Hi,

I'm trying to replace certain View values (colors, etc), the best place to do this would be after a layout has been inflated. Since I don't control all the calls that inflate layouts I was thinking about "hooking into" BindingInflate/MvxLayoutInflater and do some post processing.

I tried creating my own MvxContextWrapper and MvxLayoutInflater, and instantiate the MvxContextWrapper in <BaseActivity>.AttachBaseContext, but when debugging I was never able to get any hits in the MvxLayoutInflater.Inflate override method.

I did get hits in the MvxContextWrapper.GetSystemService method (yes I returned "my" MvxLayoutInflater).

Maybe I missed something...

Before I try and attack the problem again, is there a better/easier/recommended way of doing post processing after BindingLayout has been called?

**Comment by kjeremy** [comment]
Don't do that.

What I would do instead is provide your own implementation of `IMvxLayoutInflaterHolderFactoryFactory`  that returns a custom `IMvxLayoutInflaterHolderFactory` (inherited from `MvxBindingLayoutInflaterFactory`) from the `Create` method.  Your custom `IMvxLayoutInflaterHolderFactory.BindCreatedView` can then call the base class to bind the view after which you can do your custom stuff.

https://github.com/MvvmCross/MvvmCross/blob/bcecb75dbce1914a96b82ab5e501acaa08729f11/MvvmCross/Binding/Droid/Views/MvxLayoutInflater.cs#L50 is where the `BindCreatedView` gets called.

**Comment by kjeremy** [comment]
You can register for that `IMvxLayoutInflaterHolderFactoryFactory` in your app setup by creating a new `MvxAndroidBindingBuilder` and overriding `CreateLayoutInflaterFactoryFactory` to return your custom class.  Return your special `MvxAndroidBindingBuilder` from your setup's `CreateBindingBuilder()`

**Comment by kjeremy** [comment]
```csharp
public class Setup : ...
{
        protected override MvxBindingBuilder CreateBindingBuilder()
        {
            return new MyMvxAndroidBindingBuilder();
        }

    public MyMvxAndroidBindingBuilder : MvxAndroidBindingBuilder
    {
        protected virtual IMvxLayoutInflaterHolderFactoryFactory CreateLayoutInflaterFactoryFactory()
        {
            return new MyMvxLayoutInflaterFactoryFactory();
        }
    }

    public MyMvxLayoutInflaterFactoryFactory : IMvxLayoutInflaterHolderFactoryFactory
    {
        public IMvxLayoutInflaterHolderFactory Create(object bindingSource)
        {
            return new MyMvxBindingLayoutInflaterFactory(bindingSource);
        }
    }

    public MyMvxBindingLayoutInflaterFactory : MvxBindingLayoutInflaterFactory
    {
         public override View BindCreatedView(View view, Context context, IAttributeSet attrs)
        {
            base.BindCreatedView(view, context, attrs);
            if (view != null)
           {
           // Do whatever ...
            }
            return view;
        }
    }
}

**Comment by Cybrosys** [comment]
Excellent, thank you! 😄

**Comment by Cybrosys** [comment]
I'd like to reopen this @kjeremy 

It appears that the BindCreatedView is not always called. For example when I'm creating a AlertDialog it doesn't call BindCreatedView, it does however use the MvxLayoutInflater.

I think it would be better to do post-processing by overriding the MvxLayoutInflater.Inflate method.

Where should I do the wrapping of the MvxLayoutInflater. Maybe by overriding the GetSystemService in my BaseActivity or do you have another recommended way of doing this?

**Comment by kjeremy** [comment]
Can you elaborate on: it doesn't always get called? What gets missed?

**Comment by Cybrosys** [comment]
`MyMvxBindingLayoutInflaterFactory.BindCreatedView` does not get called when I create and show a dialog with similar code as below (:
`var dialog = new Android.Support.V7.App.AlertDialog.Builder(this).SetTitle(title).SetPositiveButton(...).Create();
dialog.Show();`

I know the AlertDialog.Builder uses the MvxLayoutInflater because I did a check regarding what gets returned from the current Activity's `GetSystemService`.

**Comment by kjeremy** [comment]
Right. In the case of alert dialog builder the UI is built dynamically.  In
order for our code to execute you need to pass in a view resource.

**Comment by Cybrosys** [comment]
OK. My goal is to intercept any view inflation, that's why I'm thinking about wrapping the MvxLayoutInflater and override Inflate. 

So going back to my previous question, would overriding GetSytemService in my own BaseActivity suffice, and then return a MyMvxLayoutInflater that inherits from MvxLayoutInflater, or is there a better/safer way?

**Comment by kjeremy** [comment]
I think you misunderstood me.  In the case of `AlertDialog.Builder` the framework generates the view in java so you cannot intercept it.  Now if you are manually inflating views then what I said above should visit every view.

It is incredibly frustrating that Android does not provide this ability out of the box and that's why `MvxLayoutInflater` was created.
