### ISSUE TITLE
Realm and MvvmCross activity lifecycle, collection change notifications on destroyed fragments

### ISSUE THREAD

**Issue by UKDeveloper99** [MvvmCross/MvvmCross#1770]
Creating this issue on the recommendation of @Cheesebaron 

**Repro project to come soon, just trying to isolate the issue again**

Got a rather interesting edge case with Realm and MvvmCross, possibly related to the new NotificationHelper system in the prelease 1.3.0 version of Realm. So I've been using a certain pattern a lot lately where I run a period background task that will pull web data every X minutes. I then map that data in to unmanaged realm objects and marshal it all to the UI thread using a thread dispatcher. Which updates the existing realm objects `_realm.Add(obj, true)`, so that's my standard pattern. The problem seems to be tied more to Android and MvvmCross as I'm finding the memory management and activity lifecycle more of an issue. 

So let's imagine we have activity B with a single fragment that has a recycler view which is databound to a live Realm collection. Activity B is the second activity in the activity stack, after activity A.

I then navigate back and forth repeatedly between A and B using a button and the back button. Activity B is destroyed and recreated each time and every time it is databound to a new query from the realm. Eventually I navigate back at the same time as a Realm transaction is occurring. 

It seems like the bindings are then trying to update on a no longer existing data context because `Realms.NotificationsHelper.NotificationCallbackimpl` is firing `Realms.RealmObject.RaisePropertyChanged` which is then triggering the mvvmcross bindings to update but they can't be updated because the fragment etc has been destroyed or in the process of removing itself.

My first thought was to try and sever the connection between MvvmCross and Realm when the activity destroys itself, . I tried clearing the bindings and setting the datacontext to null. This seems to work in `Fragment.OnPause()` which isn't a solution obviously. But doesn't work in `Fragment.OnStop()`. Once a fragment/actitivity is being destroyed I need to stop Realm from being able to update anything that connects to that activity. I.e. prevent the bindings from being triggered once stuff has gone out of scope.

### Steps to reproduce

1. Navigate repeatedly to and from an activity to create and destroy the activity until the activity is destroyed at the _magic moment_ when Realm is raising a collection change notification

### Expected behavior
Realm should not be able to update bindings that don't exist anymore.

### Actual behavior
Triggers the bindings for what I assume is a destroyed fragment or in the process of being cleaned up.

### Configuration

**MvvmCross Version:**  4.4.0

**Realm Version:**  1.3.0 pre-release nuget (same occurs on previous version)

**Platform:** Xamarin Android latest (Xamarin Studio)

As I said will upload a reproduction project imminently just going to isolate the issue first.

**Comment by UKDeveloper99** [comment]
Stack trace:
```
[EGL_emulation] tid 23393: eglSurfaceAttrib(1165): error 0x3009 (EGL_BAD_MATCH)
[OpenGLRenderer] Failed to set EGL_SWAP_BEHAVIOR on surface 0x93b1f7a0, error=EGL_BAD_MATCH
[Surface] getSlotFromBufferLocked: unknown buffer: 0x943535d0
Thread finished:  #68
Thread started:  #87
[mono-rt] Stacktrace:
[mono-rt] 
[mono-rt]   at <unknown> <0xffffffff>
[mono-rt]   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00012>
[mono-rt]   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x0008f] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12079
[mono-rt]   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeNonvirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x00022] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:41
[mono-rt]   at Android.Widget.TextView.set_TextFormatted (Java.Lang.ICharSequence) [0x0001e] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Widget.TextView.cs:2844
[mono-rt]   at Android.Widget.TextView.set_Text (string) [0x00013] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Widget.TextView.cs:2855
[mono-rt]   at MvvmCross.Binding.Droid.Target.MvxTextViewTextTargetBinding.SetValueImpl (object,object) [0x0000c] in <6a0c851a22864d0993089d65320a630c>:0
[mono-rt]   at MvvmCross.Binding.Bindings.Target.MvxConvertingTargetBinding.SetValue (object) [0x00093] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Target\MvxConvertingTargetBinding.cs:64
[mono-rt]   at MvvmCross.Binding.Bindings.MvxFullBinding/<>c__DisplayClass24_0.<UpdateTargetFromSource>b__0 () [0x00025] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:182
[mono-rt]   at MvvmCross.Droid.Views.MvxAndroidMainThreadDispatcher.RequestMainThreadAction (System.Action) [0x0001f] in <f6aebf863dc84be7b380cfec8d459508>:0
[mono-rt]   at MvvmCross.Binding.Bindings.MvxFullBinding.UpdateTargetFromSource (object,System.Threading.CancellationToken) [0x0004f] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:173
[mono-rt]   at MvvmCross.Binding.Bindings.MvxFullBinding.<CreateSourceBinding>b__20_0 (object,System.EventArgs) [0x00018] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:99
[mono-rt]   at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SendSourcePropertyChanged () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:117
[mono-rt]   at MvvmCross.Binding.Bindings.SourceSteps.MvxPathSourceStep.SourceBindingOnChanged (object,System.EventArgs) [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxPathSourceStep.cs:73
[mono-rt]   at MvvmCross.Binding.Bindings.Source.MvxSourceBinding.FireChanged () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\MvxSourceBinding.cs:35
[mono-rt]   at MvvmCross.Binding.Bindings.Source.Leaf.MvxLeafPropertyInfoSourceBinding.OnBoundPropertyChanged () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\Leaf\MvxLeafPropertyInfoSourceBinding.cs:29
[mono-rt]   at MvvmCross.Binding.Bindings.Source.MvxPropertyInfoSourceBinding.SourcePropertyChanged (object,System.ComponentModel.PropertyChangedEventArgs) [0x00020] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\MvxPropertyInfoSourceBinding.cs:88
[mono-rt]   at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object_object (object,intptr,intptr,intptr) [0x0005b] in <f9aae2b329aa4d8aa76dab4fe82e828d>:0
[mono-rt]   at <unknown> <0xffffffff>
[mono-rt]   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0x00012>
[mono-rt]   at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x00038] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
[mono-rt]   at System.Reflection.MethodBase.Invoke (object,object[]) [0x00000] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/reflection/methodbase.cs:229
[mono-rt]   at MvvmCross.Platform.WeakSubscription.MvxWeakEventSubscription`2<TSource_REF, TEventArgs_REF>.OnSourceEvent (object,TEventArgs_REF) [0x0000a] in D:\git\MvvmCross\MvvmCross\Platform\Platform\WeakSubscription\MvxWeakEventSubscription.cs:77
[mono-rt]   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs) [0x00073] in <8dac28ffb2cb41cba0b572038da86c99>:0
[mono-rt]   at Realms.RealmObject.RaisePropertyChanged (string) [0x00013] in <9ba6abe9fed14b419e177721ea2c65d3>:0
[mono-rt]   at Realms.RealmObject.Realms.NotificationsHelper.INotifiable.NotifyCallbacks (System.Nullable`1<Realms.NotifiableObjectHandleBase/CollectionChangeSet>,System.Nullable`1<Realms.NativeException>) [0x0008d] in <9ba6abe9fed14b419e177721ea2c65d3>:0
[mono-rt]   at Realms.NotificationsHelper.NotificationCallbackImpl (intptr,intptr,intptr) [0x00034] in <9ba6abe9fed14b419e177721ea2c65d3>:0
[mono-rt]   at (wrapper native-to-managed) Realms.NotificationsHelper.NotificationCallbackImpl (intptr,intptr,intptr) [0x00022] in <9ba6abe9fed14b419e177721ea2c65d3>:0
[mono-rt]   at <unknown> <0xffffffff>
[mono-rt]   at (wrapper managed-to-native) object.wrapper_native_0x989470c0 (intptr) <0x00012>
[mono-rt]   at Realms.SynchronizationContextEventLoopSignal/EventLoop/<>c__DisplayClass3_0.<Post>b__0 (object) [0x0001b] in <9ba6abe9fed14b419e177721ea2c65d3>:0
[mono-rt]   at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:35
[mono-rt]   at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36
[mono-rt]   at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Java.Lang.IRunnable.cs:81
[mono-rt]   at (wrapper dynamic-method) object.c924a09d-72e8-4329-a339-c450797a4ad3 (intptr,intptr) [0x00011] in <8c304e4006094a46a7950338a3b3cb5d>:0
[mono-rt]   at (wrapper native-to-managed) object.c924a09d-72e8-4329-a339-c450797a4ad3 (intptr,intptr) [0x00021] in <8c304e4006094a46a7950338a3b3cb5d>:0
```

**Comment by kjeremy** [comment]
It looks like you are not running on the UI thread.  Are you using the default `MvxTaskBasedBindingContext` or `MvxBindingContext`?

This looks suspiciously like the the `MvxRecyclerView` problems we were having with fragments.

**Comment by UKDeveloper99** [comment]
As I mentioned in the Slack channel, I'm 100% using the old binding context on all my Realm Android projects.

**Comment by kjeremy** [comment]
Thanks.  Please do not reference the slack channel as that information is lost after a brief period of time.

**Comment by UKDeveloper99** [comment]
Absolutely, I know that, that's why I salvaged the information before it disappeared! =)

**Comment by UKDeveloper99** [comment]
**For reference:**

_kjeremy_
@buzz_mark did you move back to the regular MvxBindingContext as in: Mvx.RegisterType<IMvxBindingContext, MvxBindingContext>(); in InitializeLastChance?

_buzz_mark_
@kjeremy  I did indeed!

_kjeremy_
my guess is that something with the ViewHolders.   RecyclerView doesn't explicitly destroy them
so you end up with lifetime issues
when a MvxRecyclerview is detached it clears the views which helps in most cases: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.V7.RecyclerView/MvxRecyclerView.cs#L74
it may help if you use you figure out a place to call Dispose on the MvxRecyclerViewHolder

_kjeremy_
@buzz_mark originally I kept a WeakReference to each vh in the recyclerview and ran through the list disposing everything and it helped but ended up not being the right fix.  However you may need to do something similar

**Comment by kjeremy** [comment]
So normally in this case you would hit: `https://github.com/MvvmCross/MvvmCross/blob/4.4.0/MvvmCross/Binding/Droid/Target/MvxAndroidTargetBinding.cs#L40`

Can you bump `MvxBindingTrace.TraceBindingLevel` and see what the output is of the binding messages?

**Comment by UKDeveloper99** [comment]
I set it to warning, is that correct? Doesn't appear to be outputting anything different before the crash. I'll try diagnostic mode.

**Comment by UKDeveloper99** [comment]
Doesn't seem to be giving me that trace that you linked.

**Comment by kjeremy** [comment]
Ok.  If you can get a repro repo up I can take a look.  If you want a fix in 5.0 it will have to be asap.

**Comment by UKDeveloper99** [comment]
Well what do you know! I think that viewholder remove all fix that you linked on develop branch in 'Mvx.RecyclerView' has solved it. I'll need to do a bit more testing but it's looking promising.

**Comment by kjeremy** [comment]
Ohh I thought that was in 4.4.0 but I guess not.  Yes that was the fix for this issue.

**Comment by kjeremy** [comment]
The good thing for you is you can subclass `MvxRecyclerView` and just do that fix until you move to 5.0.

**Comment by UKDeveloper99** [comment]
Yes exactly! That's what I've done. Awesome.. =) will confirm and close when I've tested.

**Comment by UKDeveloper99** [comment]
For clarity the fix for this issue was to override this function in `MvxRecyclerView`
```
        protected override void OnDetachedFromWindow()
        {
            base.OnDetachedFromWindow();

            // Remove all the views that are currently in play.
            // This clears out all of the ViewHolder DataContexts by detaching the ViewHolder.
            // Eventually the GC will come along and clear out the binding contexts.
            // Issue #1405
            GetLayoutManager()?.RemoveAllViews();
        }
```

Which is present on the MvvmCross develop branch but not in the current `MvxRecyclerView` release branch, tagged v4.4.1.

**Comment by Cheesebaron** [comment]
Thanks for the update @UKDeveloper99! Glad you made it work. If you encounter other issues, you are very much welcome to open a new GitHub issue.
