### ISSUE TITLE
Xamarin SideBar Menu Top Margin

### ISSUE THREAD

**Issue by slown1** [MvvmCross/MvvmCross#1773]
![img_0005](https://cloud.githubusercontent.com/assets/2652146/25772311/ca57ad04-3270-11e7-9852-205e04faac14.jpg)

### Configuration

**Version:** 5.0.0-beta0006

**Platform:** iOS

I would like to know how can I set the margin to 0. The picture is self explanatory.

Thanks.

**Comment by Cheesebaron** [comment]
Please use GitHub issues only for actual bugs and issues. Questions go on StackOverflow or on Slack.
