### ISSUE TITLE
Support multiple languages on MvvmCross.StarterPack

### ISSUE THREAD

**Issue by willsb** [MvvmCross/MvvmCross#1774]
Split from #1659

References can be found [here](https://docs.microsoft.com/en-us/nuget/schema/nuspec) (session `Package folder structure `) and [in this blog post](http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html).

This can only be implemented once we migrate our projects to netstandard, which, according to #1415, will only happen for 6.0. 

I have many of the F# files [here](https://github.com/willsb/MvvmCross/tree/improve-starter-pack/nuspec), so VB people are welcome to join and help.

**Comment by martijn00** [comment]
This will probably not be supported anymore:
https://github.com/MvvmCross/MvvmCross/issues/1282#issuecomment-365290201
