### ISSUE TITLE
the mvvmcross.com's Doc isn't too good show in mobile phone

### ISSUE THREAD

**Issue by HeMinzhang** [MvvmCross/MvvmCross#1776]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

![qq 20170507152230](https://cloud.githubusercontent.com/assets/2683269/25778712/1e2f487e-3339-11e7-897a-6e6b72f59608.png)

thanks a million.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Version:** 4.x

**Platform:** iOS/Android/Windows Phone

**Comment by MarcBruins** [comment]
Hello HeMinzHang! Those issues are know: #1727 thanks for reporting however, if you would like to help out resolving these issues that would be great!
