### ISSUE TITLE
Make some methods in MvxWindowsMultiRegionViewPresenter protected

### ISSUE THREAD

**Issue by eL-Prova** [MvvmCross/MvvmCross#1779]
I want to request to make some methods in the (in my case) MvxWindowsMultiRegionViewPresenter protected instead of internal / private.
When you want to create an CustomViewPresenter this methods can be helpful.

Like GetViewType and FindChild<T>. These methods are correct to be scoped of the presenter so public is incorrect. But an override should be able to use this methods too.

**Comment by martijn00** [comment]
Can you make a pull request to fix this?

**Comment by eL-Prova** [comment]
Yep pull is made.
https://github.com/MvvmCross/MvvmCross/pull/1780

**Comment by eL-Prova** [comment]
Merged in master on 8-5-2017

**Comment by Cheesebaron** [comment]
Easier to track if you just add the link to the commit, specifying a date is not sufficient: https://github.com/MvvmCross/MvvmCross/commit/1912a9a2ab796ac28ceff5b67f6795b308a2f7f9
