### ISSUE TITLE
Feature request: Property binding in iOS designer 

### ISSUE THREAD

**Issue by cfl777** [MvvmCross/MvvmCross#1781]
Hi,

Would be great if we could use the designer(property panel etc) to create binding definitions, instead of needing to use the .cs file. Would remove a lot of code. 
e.g 
buttons text, using the title field: {ViewModel.MyPropertyForButtonText}

Possible to parse a .nib/.xib before it is “inflated”, similarly to what is done on Android?

**Comment by willsb** [comment]
Duplicate of #777
