### ISSUE TITLE
Fragmented Lifecycle Management PluginLoaders - MvxSingleton

### ISSUE THREAD

**Issue by ferrydeboer** [MvvmCross/MvvmCross#1782]
To build near complete acceptance tests against ViewModels I want to reload the complete app on every test. The core problem I'm running into at the moment is that public interfaces allow to only partially reset the state of the code that is running in the test process. Plugin implementations impede a full reset forcing me to fall back on dirty reflection solutions.

I will supply an example later, but I don't want to have to have that hold back a discussion about possible solution directions.

### Steps to reproduce
_I use MvvmCross.Wpf to get the necessary MvvmCross classes to run a complete app without a UI. It's the MvxMessenger plugin that made me run into this problem, so add that ass well_

1. Create a TestSetup : MvxSetup 
2. Inject mocks where normally platform specific plugins would be and for the Dispatchers and some other infrastructure.
3. In you test SetUp create an instance of TestSetup and call Initialize on it. 
4. In your TearDown call MvxSingleton.ClearAllSingletons();
5. Have to two tests that for instance call Mvx.IocConstruct for a ViewModel that has a dependency on the IMvxMessenger.

### Expected behavior
Both tests should just run fine.

### Actual behavior
The second test being run which is trying to Mvx.IocConstruct the view model will throw

> MvvmCross.Platform.Exceptions.MvxIoCResolveException : Failed to resolve parameter for parameter messenger of type IMvxMessenger when creating 

### Configuration

**Version:** 4.4.0

**Platform:** Irrelevant

## Analysis
The common approach in plugins is to have a _loaded boolean that is set on a static readonly instance of the PluginLoader. Now the public Mvvm API allows me to reset the state of the container, but that the plugin manages also it's own lifecycle state in a non public api. 

### Possible approach
If the plugin want's to prevent duplicate loading, a Mvx.CanResolve in my opinion has the same semantics, but atleast it's now managed in only one location instead of two.

Now there's also thrid party plugins problably doing the same, the only *fragile* solution possible there is offering a public API on the IMvxPluginManager that allows you to reset or unload plugins. This is fragile since it's based on the assumption that external plugins follow a similar approach and have a boolean that is also names _loaded.

**Comment by willsb** [comment]
Once we got the new plugin architecture merged (Ref #2603), I think we should include an `Unload` method to the `IMvxPlugin` interface and a `UnloadPlugin(Type pluginType)` method to the `IMvxPluginManager` interface. These two, once properly implemented, will  

After making this change, we also communicate clearly that instances of IMvxPlugin shouldn't try to be clever about state, since this is to be handled by the PluginManager instead. This will fix all the problems mentioned in this issue.
