### ISSUE TITLE
In MvxWindowsMultiRegionViewPresenter.FindChild bug

### ISSUE THREAD

**Issue by eL-Prova** [MvvmCross/MvvmCross#1785]
In reviewing the FindChild in the class MvxWindowsMultiRegionViewPresenter I found an bug.

**Reference has no childs?**
An ContentPresenter has no ChildCollection but its content can be. So when the reference (given DependencyObject) is an ContentPresenter it should be added for the nextPhase with his content. (Will make a pull request for that)

But a Frame has also no ChildCollection. You cant check if the reference (given argument) is an FrameworkElement, this will generate a stackoverflow because it checks its own.

**Edit 1**
To clearify myself a bit. My view has a splitview. Windows creates ContentPresenters runtime. I searched for my SplitView which was in the ContentPresenter. It were not found because it has no childs. But the content of the ContentPresenter has it.

**Comment by martijn00** [comment]
Please try again with the new presenter and reopen if still present.
