### ISSUE TITLE
about .NET Standard Class Library

### ISSUE THREAD

**Issue by HeMinzhang** [MvvmCross/MvvmCross#1787]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1.
> Portable Class Library (PCL): You can avoid them now, unless you do need to support legacy platforms. Use .NET Standard is better and future proof.[Which Visual Studio 2017 project type to choose for a cross-platform open-source UI-agnostic C# class library and why?](http://stackoverflow.com/questions/42737406/which-visual-studio-2017-project-type-to-choose-for-a-cross-platform-open-source)

Whether mvvmCross can choose .NET Standard Class Library?

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Version:** 4.x

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by martijn00** [comment]
NetStandard support is part of our roadmap: https://github.com/MvvmCross/MvvmCross/issues/1415

**Comment by HeMinzhang** [comment]
That's great, Thanks a million.
