### ISSUE TITLE
MvxTabBarViewController.VisibleUIViewController throws for tabs without a navigation controller

### ISSUE THREAD

**Issue by DanielStolt** [MvvmCross/MvvmCross#1812]
Problem is on line 115:

    var topViewController = (SelectedViewController as UINavigationController).TopViewController;

This assumes every tab is wrapped in a UINavigationController, which can be disabled using the presentation attribute:

        [MvxTabPresentation(
            TabName = "Targets",
            TabIconName = "TabBarItemTargets",
            WrapInNavigationController = false)]

If we do, the above lines throws an NRE when the selected tab is one without a navigation controller.

**Comment by nmilcoff** [comment]
Thank you for reporting this and for your detailed explanation. Can you please check the PR I made solves the issue?

**Comment by DanielStolt** [comment]
Yep, the PR solves the issue.
