### ISSUE TITLE
Cant install MvvmCross.Forms.Presenter on VS2017

### ISSUE THREAD

**Issue by evgesha14** [MvvmCross/MvvmCross#1818]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

I am trying to build an app that uses MvvmCross plugin for BLE : Android/iOS, so as a part of simple hello world i need to install the MvvmCross.Forms.Presenter plugin.

### Steps to reproduce

1. Create a new Xamarin Forms project (PCL) in VS2017, for Android and iOS.

2. Try to install MvvmCross.forms.presenter package

### Expected behavior
The plugin should have been installed.

### Actual behavior
Error	Could not install package 'MvvmCross.Forms.Presenter 4.4.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Configuration

**Version:** 4.x

4.4.0

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

iOS & Android using Xamarin forms

**Comment by Cheesebaron** [comment]
Your PCL profile isn't compatible. Pick a more sane one.
