### ISSUE TITLE
Remove Inverted converters

### ISSUE THREAD

**Issue by tritter** [MvvmCross/MvvmCross#1838]
Currently there are multiple converters to invert a boolean value. After adding  support(https://github.com/MvvmCross/MvvmCross/pull/1828)  for the inverted ! operator in Tibet there is no need for these inverted classes. Because this will break lots of legacy implementations it is something to keep in mind for a new release.

For example:
`Visibility InvertedVisibility(IsLoading)`

should be:
`Visibility Visibility(!IsLoading)`

**Comment by nmilcoff** [comment]
Can the  `!` operator be used in Fluent binding? Otherwise they're still necessary

**Comment by Cheesebaron** [comment]
This won't work on WPF/UWP/Forms unless you use BindingEx. Not everybody uses that.

**Comment by martijn00** [comment]
I think we merged BindingEx into the main code base. So it should be always available.

**Comment by Cheesebaron** [comment]
You would still need to use `bi.nd="<<expression>>"` instead of built in bindings for that to work on Windows.

**Comment by nmilcoff** [comment]
We can't really remove those inverted converters, as they are still necessary for other binding formats.
