### ISSUE TITLE
PhoneCall Plugin targeting Android Marshmallow

### ISSUE THREAD

**Issue by bazookajoey** [MvvmCross/MvvmCross#1847]
Attempting to utilize the MvxPhoneCallTask from the MvvmCross.Plugins.PhoneCall.Droid project, I found a missing API level check that causes a System.Reflection.TargetInvocationException. The Android level that raises this exception is Marshmallow (API 23). There is an SDK check on Lollipop to use the correct method to format a phone number, but not to get the default Locale. The Locale method attempting to be utilized does not exist until Nougat (API 24).

The SDK check should look like the following:
`if (Buidl.VERSION.SdkInt >= BuildVersionCodes.N)
	phoneNumber = PhoneNumberUtils.FormatNumber(number, Locale.GetDefault(Locale.Category.Format).Country);
if (Build.VERSION.SdkInt >= BuildVersionCodes.Lollipop)
	phoneNumber = PhoneNumberUtils.FormatNumber(number, Locale.Default.Country);
else
	phoneNumber = PhoneNumberUtils.FormatNumber(number);`

I found this bug utilizing this library through the NuGet Gallery on version 5.0.0-beta11.

**Comment by kjeremy** [comment]
Please submit a PR.

**Comment by bazookajoey** [comment]
New to using Github for more than browsing a repo... I'll see if I can figure that out quickly
