### ISSUE TITLE
Create Pull Request template

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1848]
Create a pull request template for people to fill out when submitting a pull request.

This should contain a checklist for requester to help them to remember everything when submitting.

**Comment by MarcBruins** [comment]
I was thinking about this as well. If there is new functionality or if its changing existing behaviour it should be documented, that way we keep up to date with the docs.

**Comment by willsb** [comment]
This PR template is a slightly modified version of one we use internally here at Toggl. We can drop the emoji and the gif part if needed, though I think it adds some fun to the whole process 😄 

The checklist before submitting can probably be improved to best suit the needs of MvvmCross. I can draft a PR if you guys like this template
____

## :star2: What does this PR do?

## :bug: Recommendations for testing

## :memo: Links to relevant issues/docs

## :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Tabs vs spaces and indentation are all correct
- [ ] Relevant documentation was updated
- [ ] Nuspec files were updated (when applicable)

## :speech_balloon: Summarise how you feel about this PR with a gif

**Comment by modplug** [comment]
I like the ReactiveUI one:

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

What is the current behavior? (You can also link to an open issue here)

What is the new behavior (if this is a feature change)?

Does this PR introduce a breaking change?

Please check if the PR fulfills these requirements

 The commit follows our guidelines: mvvmcross.com/guidelines
 Tests for the changes have been added (for bug fixes / features)
 Docs have been added / updated (for bug fixes / features)

Other information:

**Comment by Cheesebaron** [comment]
Thanks for the input, @willsb and @modplug.

**Comment by Cheesebaron** [comment]
Template was added in #1872
