### ISSUE TITLE
Repeated navigation between two viewmodels only returns a result and invokes Initialize() the first time

### ISSUE THREAD

**Issue by MrXemiu** [MvvmCross/MvvmCross#1855]
I've created an app that demonstrates this problem using Xamarin.Android and Fragment-based navigation.  [https://github.com/MrXemiu/XamarinSandbox](https://github.com/MrXemiu/XamarinSandbox)

Give a ViewModels and corresponding fragments A and B, navigating from A to B successfully initializes B with an initialization parameter and receives a result back from B upon `await B.Close(result)` only on the first attempt.  Subsequent attempts to navigate from A to B do not execute `B.Initializer()` and no result is returned upon `await B.Close(result)` nor is any code in scope following `await A.Navigate<B>(initializer)` executed.

### Steps to reproduce

```
public MvxCommand GoToBCommand => new MvxCommand(async () =>
        {
            _navigatedAwayFromCount++;
            NavigatedAwayFrom = $"Navigated to View B {_navigatedAwayFromCount} times";

            var result = await _navigationService.Navigate<ViewModelB, Tuple<string, int>, string>(new Tuple<string, int>(Title, _navigatedAwayFromCount));

            _returnedFromCount++;

            ReturnedFrom = $"Returned from View B {_returnedFromCount} times";
        });
```

1.  Build and deploy the sample [Xamarin.Android app](https://github.com/MrXemiu/XamarinSandbox).  The code above executes is the core navigation 

2. 
![image](https://cloud.githubusercontent.com/assets/4266607/26473118/d56c9100-4166-11e7-9787-4cfd5be102b2.png)
Observe "**Navigated To View B 0 times**"
Obserive "**Returned from View B 0 times**"
Click "**GO TO VIEW B**"

3.
![image](https://cloud.githubusercontent.com/assets/4266607/26473187/49a64af2-4167-11e7-8bac-996195af16a5.png)
Observe "**Navigated to from View A 1 times**"
Click "**CLOSE**"

4.
![image](https://cloud.githubusercontent.com/assets/4266607/26473201/5c6c4fd8-4167-11e7-9abb-84db9cba492f.png)
Observe "**Returned from View B 1 times**"
Click "**GO TO VIEW B**"

5.
![image](https://cloud.githubusercontent.com/assets/4266607/26473219/75619e94-4167-11e7-93af-acce50f89737.png)
Observe "**Navigated to from View A 1 times**" remains unchanged, but an initialization value of 2 was passed (`_navigatedAwayFromCount = 2`: `await _navigationService.Navigate<ViewModelB, Tuple<string, int>, string>(new Tuple<string, int>(Title, _navigatedAwayFromCount));`
Click "**CLOSE**"

6.
![image](https://cloud.githubusercontent.com/assets/4266607/26473285/ccfd83ac-4167-11e7-8caa-655a5938d699.png)
Observe "**Navigated To View B 2 times"**
Observe "**Returned from View B 1 times**"  `_returnedFromCount` was not incremented after second **CLOSE** attempt

### Expected behavior
Repeated calls of `IMvxNavigationService.Navigate<TViewModel,TParameter,TResult>(TParameter)` to a given viewmodel class should return a value every time it's invoked and the target navigation viewmodel subsequently invokes `Close(TResult)`.  

Repeated calls of `IMvxNavigationService.Navigate<TViewModel,TParameter,TResult>(TParameter)` to a given viewmodel class should invoke the target viewmodel's `Initialize(TParameter)` method each time.

### Actual behavior
Repeated calls of `IMvxNavigationService.Navigate<TViewModel,TParameter,TResult>(TParameter)` to a given viewmodel class only return a value the first time it's invoked and the target navigation viewmodel subsequently invokes `Close(TResult)`.  

Repeated calls of `IMvxNavigationService.Navigate<TViewModel,TParameter,TResult>(TParameter)` to a given viewmodel class only invokes the target viewmodel's `Initialize(TParameter)` method the first call.

### Configuration

**Version:** 5.0
**Platform:** Android

**Comment by martijn00** [comment]
It seems one thing that at least fails is you do navigation in `void Start`. Since this is not async Navigation might fail. I'm adding your test cases to our source so we can do some debugging on this.

**Comment by Cheesebaron** [comment]
`Start` can also complete prior to `OnCreate` on Android is finished doing its things.

Constructor, Init and Start should not be used for navigation in the ViewModel.

**Comment by MrXemiu** [comment]
I originally noticed the behavior I described in another app that doesn't perform any sort of initial navigation.  I was unsure how else to automatically load an initial fragment in the case of this demo app.
