### ISSUE TITLE
iOS Missing method CreateNavigationController inMvxIosViewPresenter

### ISSUE THREAD

**Issue by AmandaUrsula** [MvvmCross/MvvmCross#1856]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Create custom presenter and Inherit from MvxIosViewPresenter 

2. No override for CreateNavigationController, which used to be used to create a custom NavigationBar that can animate

**Version: 5.0.0

**Platform:** iOS

**Comment by nmilcoff** [comment]
Hi, thank you for reporting this! Please notice the iOS presenter was completely refactored in MvvmCross 5.0.

The current implementation does not provide a super-easy way to use a custom NavigationController, notice it is created in [this line](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/iOS/iOS/Views/Presenters/MvxIosViewPresenter.cs#L131) so you actually have to override the method `ShowRootViewController` to achieve what you want. I'll make a PR to bring that method back
