### ISSUE TITLE
Presentation bundle parameter in new navigation service

### ISSUE THREAD

**Issue by korzonkiee** [MvvmCross/MvvmCross#1860]
Hey,

I am a little bit confused about new navigation service in MvvmCross 5.0.0.

Previously we could pass `IMvxPresentationBundle` object to `.ShowViewModel()` method in order to perform some specific actions, like appropriate activity stack managing inside our `IMvxAndroidViewPresenter`.

I may be missing something obvious, but how to achieve similar behaviour using new navigation service? Can we somehow pass any `IMvxPresentationBundle` to `IMvxNavigationService.Navigate()` method?

Thanks.

**Comment by martijn00** [comment]
Fix is in https://github.com/MvvmCross/MvvmCross/pull/1863

**Comment by korzonkiee** [comment]
Thank you very much, that was quick!
