### ISSUE TITLE
UWP build error after upgrade to MvvmCross 5.0 and MvvmCross.Forms 5.0 

### ISSUE THREAD

**Issue by andbaciu** [MvvmCross/MvvmCross#1861]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload contains two or more files with the same destination path 'MvvmCross.Uwp\Properties\MvvmCross.Uwp.rd.xml'. Source files: 
C:\Users\andreib\.nuget\packages\MvvmCross.Core\5.0.0\lib\uap10.0\MvvmCross.Uwp\Properties\MvvmCross.Uwp.rd.xml
C:\Users\andreib\.nuget\packages\MvvmCross.Forms\5.0.0\lib\uap10.0\MvvmCross.Uwp\Properties\MvvmCross.Uwp.rd.xml	InspectieApp.Forms.UWP			

### Steps to reproduce

1. update from mvvmcross to 5 (from 4.4)

2. removed mvvmcross.forms.presenter 4.4

3. added mvvmcross forms

### Actual behavior
Wierd part is that the second path does not exists on the drive.
MvvmCross.Forms\5.0.0\lib\uap10.0\MvvmCross.Uwp\Properties\MvvmCross.Uwp.rd.xml
Maybe something wrong with the nuget ?

### Configuration

**Version:** 5.0

**Platform:** Windows UWP

**Comment by Cheesebaron** [comment]
Thanks for letting us know. I'll have a look at this and see if this can make it into 5.0.1 👍

**Comment by MichaelBTR** [comment]
@Cheesebaron still experiencing this problem in 5.0.1. Is this related to #1879 as well?

**Comment by Cheesebaron** [comment]
Yes, will be fixed in 5.0.2
