### ISSUE TITLE
`Start()` not called in ViewModel in iOS

### ISSUE THREAD

**Issue by mrtnkrstn** [MvvmCross/MvvmCross#1862]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Create a ViewModel that extends `MvxViewModel` in an iOS project

2. Override `Start()` in ViewModel

3. Navigate to the ViewModel using `IMvxNavigationService.Navigate<TViewModel>()`

4. Please see [this github project](https://github.com/mrtnkrstn/MvvmCross_5.0.0). For ease of reproduction there are tags for 5.0.0-stable and 5.0.0-beta12 (where the bug exists), as well as 5.0.0-beta11 (working as expected).

### Expected behavior
`Start()`should be called in ViewModel extending `MvxViewModel`. NOTE: this worked in all 5.0.0 beta versions up to 11; only broken in beta 12 and Stable releases

### Actual behavior
`Start()` is not called at all EXCEPT for the startup ViewModel (instantiated by `RegisterAppStart()`)

### Configuration

**Version:** 5.0.0

**Platform:** iOS

**Comment by martijn00** [comment]
This is fixed in https://github.com/MvvmCross/MvvmCross/pull/1853
Note that it is adviced to use Initialize instead of Start because it is async.

**Comment by mrtnkrstn** [comment]
OK switching to using `Initialize()`.

Note that, in 5.0.0, `Initialize()` is not being called in the ViewModel instantiated by `RegisterAppStart()`.

**Comment by martijn00** [comment]
That is also fixed in 5.0.1

**Comment by mrtnkrstn** [comment]
Hi @martijn00 is it the official recommendation to not call `Start()` anymore? I am finding that there a number of cases where `Initialize()` is not being called.

**Comment by martijn00** [comment]
@mrtnkrstn yes, it is recommendation not to use Start or Init anymore. Can you open an issue with the cases Initialize is not called?

**Comment by mrtnkrstn** [comment]
New issue logged at https://github.com/MvvmCross/MvvmCross/issues/1972
