### ISSUE TITLE
Documentation: Search result links are incorrect

### ISSUE THREAD

**Issue by laeckerv** [MvvmCross/MvvmCross#1866]
### Steps to reproduce
1. Go to [www.mvvmcross.com](https://www.mvvmcross.com/search/?query=converter) and search for something e.g. "converter"
2. Click on any result link

### Expected behavior
The link should open the corresponding page (in this case the documentation) and look like this:
https://www.mvvmcross.com/documentation/fundamentals/value-converters

### Actual behavior
The link leads to a 404 and looks like this:
https://www.mvvmcross.com/search/documentation/fundamentals/value-converters

**Comment by MarcBruins** [comment]
Hi @laeckerv,
Thanks for letting us know, i've fixed it in https://github.com/MvvmCross/MvvmCross/commit/757b5dc4a7863030144dadc7cd19848d99620d91

**Comment by MarcBruins** [comment]
Mm the issue might be still there, the url is still wrong. Let's wait a bit and and see if its not a cached result.
