### ISSUE TITLE
Back button navigation with navigation drawer in android not directly go back

### ISSUE THREAD

**Issue by albilaga** [MvvmCross/MvvmCross#1875]
### Steps to reproduce

1. Source is in this repo https://github.com/albilaga/MvvmNavDrawer

2. Click Login 

3. Click back button in android hardware

### Expected behavior
It should be directly going back to login page

### Actual behavior
Instead going back to login page it created empty page with 1 or 2 empty page and then login page

### Configuration

**Version:** 5.0.1

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by tbalcom** [comment]
Remove the `MvxFragment` attribute 3rd parameter from `MenuFragment` and `SearchJourneyFragment`.

**Comment by albilaga** [comment]
Solved by @tbalcom. Thanks. I am forgetting that 3rd parameter but on the v 4.4.0 that works. Anyway it solved
