### ISSUE TITLE
Problem with Visibility plugin

### ISSUE THREAD

**Issue by hugoterelle** [MvvmCross/MvvmCross#1876]
With MvvmCross 4.x, I was using the Visibility Plugin on Android with the following code:

In my ViewModel:

        public bool MustSignIn { get; set; } = true;
        public bool MustLogIn { get; set; } = false;

In my Layout:
        <LinearLayout
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            local:MvxBind="Visibility Visibility(MustSignIn)">
            <Button
                android:textColor="@color/white"
                android:textSize="16dp"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:height="56dp"
                android:layout_marginBottom="16dp"
                local:MvxBind="Text _('SignIn'); Click SignInCommand" />
        </LinearLayout>

        <LinearLayout
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            local:MvxBind="Visibility Visibility(MustLogIn)">
            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:textSize="14dp"
                android:layout_marginTop="8dp"
                android:textColor="@color/accent"
                android:textStyle="bold"
                local:MvxBind="Text _('Username')" />
            <EditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:selectAllOnFocus="true"
                local:MvxBind="Text Username"
                android:inputType="textWebEmailAddress" />
            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:textSize="14dp"
                android:layout_marginTop="8dp"
                android:textColor="@color/accent"
                android:textStyle="bold"
                local:MvxBind="Text _('Password')" />
            <EditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:selectAllOnFocus="true"
                local:MvxBind="Text Password"
                android:password="true"
                android:fontFamily="sans-serif" />
            <Button
                android:id="@+id/login"
                android:textColor="@color/white"
                android:textSize="16dp"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:height="56dp"
                local:MvxBind="Text _('LogIn'); Click LogInCommand" />

It's not working anymore with MvvmCross 5.0.x

I tried to change the bool with MvxVisibility
And the buttons are only displayed if I use this kind of code:

        public MvxVisibility MustSignIn { get; set; } = MvxVisibility.Collapsed;
        public MvxVisibility MustLogIn { get; set; } = MvxVisibility.Collapsed;

If I try to change the value of MustSignIn to MvxVisibility.Visible, the layout disappears.

What is wrong with the update of the visibility plugin?

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template.

This seems to be a regression introduced in https://github.com/MvvmCross/MvvmCross/pull/1839

As you've found out, the workaround is to use MvxVisibility instead of bool.

**Comment by hugoterelle** [comment]
The workaround with MvxVisibility doesn't seems to work as explained in my issue ...

**Comment by mvanbeusekom** [comment]
Not an expert on Android, however I am currently working on an application where I also use the Visibility plugin and MvvmCross 5.0.0 (so not yet the latest version) and I cannot reproduce the error. 

I have the following (simplified) property in my ViewModel:
```
public bool HasItems => false;
```

And in my fragment I have the following code (which is a simple piece of layout which needs to be displayed when no results are found):
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:local="http://schemas.android.com/apk/res-auto"
    local:MvxBind="Visibility InvertedVisibility(HasItems)"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:id="@+id/empty_view"
    android:layout_centerInParent="true"
    android:layout_marginLeft="@dimen/margin_medium"
    android:layout_marginRight="@dimen/margin_medium">
  <ImageView
      android:src="@drawable/ic_launcher"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:id="@+id/no_result_icon"
      android:layout_marginBottom="@dimen/margin_medium"
      android:scaleType="center" />
  <TextView
      android:text="Geen links"
      android:textAppearance="?android:attr/textAppearanceMedium"
      android:id="@+id/no_result_label"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:gravity="center" />
</LinearLayout>
```

I also tried modifying the binding to use `local:MvxBind="Visibility Visibility(HasItems)"` instead of `local:MvxBind="Visibility InvertedVisibility(HasItems)"` and this also works as expected. 

I noticed the properties do not trigger the `RaisePropertyChanged` event, could this be the issue (to me it is not clear if you mean to only bind on the default value of the property)?

Could you maybe supply example code demonstrating the issue you are facing?

**Comment by Cheesebaron** [comment]
Scratch that comment about it being a regression. Just double checked again, had added it to a project I was working on to see whether it worked, but forgot to install the visibility plugin.

It actually seems to work just fine. Just like @mvanbeusekom also points out.

Try reinstalling the package. Make sure the bootstrap is installed or that you register the plugin.

If you are overriding things in your Setup.cs file, make sure you are not doing something that prevents bootstrap to register plugins.

If you are still experiencing issues. Create a minimal reproducible sample repository for us to work with, which you would have known all about if you _actually_ used the issue template.

**Comment by hugoterelle** [comment]
My bad,I doubled checked and it seems my problem comes from an upgrade of Fody.PropertyChanged (for the RaisePropertyChanged behavior).  I need to investigate why but the visibility plugin is working fine.  Sorry for the unnecessary discussion.

**Comment by Cheesebaron** [comment]
Don't be sorry. Sometimes it is good to talk stuff like this through with others. You found your root cause 😄 

Also as pointed out a couple of times now. Please use the issue template next time ❤️

**Comment by hugoterelle** [comment]
Hi again, 

Sorry, I have to reopen the issue (next time, I promise to use the template.  I didn't want to open a new issue)

Please, go and check the simple example I wrote: https://github.com/hugoterelle/MvvmCross.BindingProblem

First, my App.cs creates and initialize the AppStart class.  Inside this AppStart, I use the new NavigationService in order to execute the new "Initialize" of the FirstViewModel.
And that's the problem.  When I use a binding inside the old "Start" method, the binding changes are reflected (Hello & IsVisible properties).  But when I use a binding inside the "Initialize" method, nothing happens (Hello2 & IsVisible2 properties).

For the RaisePropertyChanged, I use Fody (which is working well, after IL decompilation)

**Comment by hugoterelle** [comment]
In fact, it seems that all property changes in the "Intialize" method do not fire the bindings.  I update the sample in order to remove fody and to add other binding examples.

**Comment by Cheesebaron** [comment]
This is a bit odd. Setting `MvxBindingTrace.TraceBindingLevel = MvxTraceLevel.Diagnostic;` reveals that only one of the bools are actually changing its value.

It is like there is no binding between the View and the ViewModel when doing anything with a property to be bound in `Initialize`. Moving the code up, similarly to the other code block you have up in Start, makes it work for both...

It doesn't matter if you use Fody for PropertyChanged or use Mvx's `SetProperty` here, both fail to bind for some reason.

The property is changed so is the backing field for it.

**Comment by Cheesebaron** [comment]
Problem is that what you see in Initialize is a whole other instance of the ViewModel. There is something fishy going on with the NavigationService on Droid.

**Comment by hugoterelle** [comment]
Do you have a (small) idea where the problem is? Is there someone working on it?

**Comment by mvanbeusekom** [comment]
Yes I do have an idea and want to verify with @martijn00 to confirm. I will try to get to it this weekend but no promises. In the meantime I suggest using the old navigation method (using ShowViewModel and the Init/ Start methods

**Comment by daniatic** [comment]
I think my bug [report](https://github.com/MvvmCross/MvvmCross/issues/1880) is related to this issue.
