### ISSUE TITLE
CanExecute does not fire when RaiseCanExecuteChanged() is called.

### ISSUE THREAD

**Issue by jeremy-alley** [MvvmCross/MvvmCross#1877]
### Steps to reproduce

1.  View Model Code

        private string _displayName;
        public string DisplayName
        {
            get
            {
                return _displayName;
            }
            set
            {
                _displayName = value;
                RaisePropertyChanged(() => DisplayName);
                TestCommand.RaiseCanExecuteChanged();
            }
        }
        private MvxCommand _testCommand;
        public IMvxCommand TestCommand
        {
            get
            {
                _testCommand = _testCommand ?? new MvxCommand(OnTest, CanTest);
                return _testCommand;
            }
        }

        private bool CanTest()
        {
            System.Diagnostics.Debug.WriteLine("CanTest Fired");

            return DisplayName.Length > 5;
        }

        private void OnTest()
        {
            System.Diagnostics.Debug.WriteLine("Test Fired");
        }

2.  In the view I bind DisplayName to a UITextField  and TextCommand to a UIBarButtonItem.

### Expected behavior
As text is edited for the DisplayName UITextField,  TestCommand.RaiseCanExecuteChanged() should fire the CanTest() method.

### Actual behavior
I can trace that TestCommand.RaiseCanExecuteChanged() gets called in the DisplayName setter.  I can then see that the getter is called for TestCommand, but CantTest does not get called.  

CanTest does get called when I click on the button that I bound the TextCommand to.

### Configuration

**Version:** 5.0.1

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by mvanbeusekom** [comment]
@jeremy-alley I think you misunderstood the use of the `RaiseCanExecuteChanged` method. This method is called when the `CanExecute` function is updated (so when you change the actual delegate which needs to be called).

In your case you would probably want to call the `CanExecute` method on the `TestCommand` instance. This will indeed call the `CanTest` method on your view model to validate if the command can be executed.

**Comment by jeremy-alley** [comment]
@mvanbeusekom Thanks for the response and help.  You are absolutely correct, CanExecute gave me the desired effect.  Funny thing is I've been using RaiseCanExecuteChanged this way for over a year and it seemed to be working (the way I thought it was) up until I upgraded.

Thanks again!
