### ISSUE TITLE
Error MvvmCross.Uwp.rd.xml does not exist when compiling 5.0.1

### ISSUE THREAD

**Issue by syaifulnizamyahya** [MvvmCross/MvvmCross#1879]
Here are the errors that I get.

> 'C:\Users\username\.nuget\packages\MvvmCross.Core\5.0.1\lib\uap10.0\MvvmCross.Uwp\Properties\MvvmCross.Uwp.rd.xml' does not exist.		

	

### Steps to reproduce

1. Create a new project using this template https://marketplace.visualstudio.com/items?itemName=JimBobBennett.MvvmCrossforVisualStudio.

2. Update MvvmCross nuget to 5.0.1 (Core and UWP).

3. Debug -> Start new instance for UWP projects and get error.

### Expected behavior
Should compile and run without problem

### Actual behavior
Got 1 error.

### Configuration

**Version:** 5.0.1

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [X] UWP

**Comment by Cheesebaron** [comment]
Hmm... I thought I had fixed this in #1870 

I guess compiling it into the library is not good enough. Will fix this for 5.0.2. Thanks for reporting.

**Comment by jimbobbennett** [comment]
Spotted this myself when trying to upgrade the extension to 5.0.1 and was also about to raise an issue.

**Comment by selaromdotnet** [comment]
lol darn i was updating nuget packages and saw 5.0 release official and was like ah wth why not! lol will wait for a fix, thanks for keeping us posted!

**Comment by Bowman74** [comment]
Also encountered this.

**Comment by Cheesebaron** [comment]
Can you guys test out 5.1.0-unstable0086 when the CI build is done?

It should be on myget in 5 minutes or so.

**Comment by selaromdotnet** [comment]
i'd like to help but I don't know how to access this, is there a link where I can learn more?

**Comment by Cheesebaron** [comment]
Add https://www.myget.org/F/mvvmcross/api/v3/index.json as nuget source.

**Comment by selaromdotnet** [comment]
thanks, will try this now!

**Comment by selaromdotnet** [comment]
looks like that did it. I had an error that it couldn't find mvvmcross.windowsuwp, but then I updated the platform package as well and so far so good. I could build, and also run my uwp app, so thanks for the quick fix! let me know if you need more details about my setup or anything else

**Comment by Cheesebaron** [comment]
Just needed it verified. Thanks for your assistance!

**Comment by selaromdotnet** [comment]
is 5.0.2 going to get a release, and soon? or should I continue to use this internal one?

**Comment by Cheesebaron** [comment]
Yes, very soon. Expected tomorrow-ish.
