### ISSUE TITLE
Add Facebook sharing for iOS

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#188]
Extend:

https://github.com/slodge/MvvmCross/tree/vnext/Cirrious/Plugins/Share

and especially

https://github.com/slodge/MvvmCross/blob/vnext/Cirrious/Plugins/Share/Cirrious.MvvmCross.Plugins.Share.Touch/MvxShareTask.cs

with:

http://docs.xamarin.com/guides/ios/platform_features/introduction_to_the_social_framework

Simples :)

**Comment by martijn00** [comment]
@slodge What are the plans here currently? Xamarin has a plugin available called Xamarin.Social: http://components.xamarin.com/view/xamarin.social/ 
Is that sufficient enough?

**Comment by slodge** [comment]
I think this code above could easily be integrated just for sharing...

For larger Facebook integration, I think xam social can help with some scenarios... but I believe (gut feel) that xam.social was written back before xam discovered PCLs so I don't think it's portable (yet)
