### ISSUE TITLE
Navigation Bug introduced in 5.0.1: View.OnCreate reinstantiates existing target ViewModel 

### ISSUE THREAD

**Issue by daniatic** [MvvmCross/MvvmCross#1880]
I'm observing a bug in the navigation since 5.0.1: Find a sample project [here](https://github.com/daniatic/mvvmcross-navigation-bug) 

### Steps to reproduce

1. From a ViewModel navigate to another ViewModel and passing a parameter to it by: `navigationService.Navigate<TargetViewModel,string>("test")`

2. The TargetViewModel gets instantiated and afterwards the Initialize method is invoked passing the parameter. Save that parameter to variable. 

3. Now the TargetViewModel gets instantiated again by its view.OnCreate method. The old instance with the passed parameters gets overridden and the saved variable is gone.

### Expected behavior
The second instantiation shouldn't happen. Like it works in v5.0.0

### Configuration

**Version:** 5.0.1

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by Bowman74** [comment]
I have also encountered this same issue.

**Comment by Bowman74** [comment]
I traced this problem to line 48 in the MvxAndroidViewPresenter:

requestTranslator.RemoveSubViewModelWithKey(instanceRequest.Item2);

I created a custom view presenter that is an exact copy of the 5.0.1 view presenter and corrected the problem by commenting out this line.

@martijn00 I noticed that you added the line as part of commit #1871 . I assume simply removing it will cause a regression for the fragment code?

**Comment by Bowman74** [comment]
@mvanbeusekom I hope someone has a chance to review my PR #1907 before the next release or the solution to this bug will be replaced with a memory leak. @martijn00 was right that the ViewModel needed to be removed from the cache, it was just happening in the wrong spot.

**Comment by arogan** [comment]
Please make sure this is also fixed for iOS.  I was able to reproduce the double viewmodel instance issue both in 5.0.0 and 5.0.1.  Sample code is here:  https://github.com/arogan/HelloMvx5Forms

**Comment by mvanbeusekom** [comment]
Looks like this is a problem when using MvvmCross with Xamarin.Forms. I have not encountered this issue with a Xamarin.iOS application (using the MvxIosViewPresenter)

**Comment by JTOne123** [comment]
The issue is reproducing on 5.0.6 in Forms

Here's example https://github.com/JTOne123/XamFormsMvxTemplate/blob/master/MvxForms/MvxForms.Core/ViewModels/SecondViewModel.cs 

MainPageButtonText property is set in constructor twice

**Comment by martijn00** [comment]
This is fixed in 5.1.0.
