### ISSUE TITLE
mvvmcross 5.0 Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by DmitryNikiforov** [MvvmCross/MvvmCross#1881]
### Steps to reproduce

1.Update mvvmcross to version 5.0.1

2.Add parent field to MvxAdapter methods signature(It was changed, so build failed)

3.Launch application

### Expected behavior
Application should launch without any problems

### Actual behavior
Application crashes during startup with log:
No native Android stacktrace (see debuggerd output).
[mono-rt] Got a SIGSEGV while executing native code. This usually indicates
[mono-rt] a fatal error in the mono runtime or one of the native libraries 
[mono-rt] used by your application.
Fatal signal 11 (SIGSEGV), code 2, fault addr 0xc5c3ff70 in tid 9451 (Thread-5)

### Configuration
Xamarin Android 7.3.1.2
**Version:** 5.0.1

**Platform:** 
- [+ ] Android

**Comment by Cheesebaron** [comment]
Please add actual reproduction steps to your issue. What especially would help, would be to how to exactly reproduce your Adapter.

**Comment by mvanbeusekom** [comment]
Signature of the `MvxAdapter.GetBindableView` method got changes in version 5.0 of MvvmCross (see https://github.com/MvvmCross/MvvmCross/commit/413a480cc567f8fee846d99356b8fe9356d084ee#diff-9a778d80d18fbf2c0fe640de51952478 )

This is on purpose and is indeed a breaking change in MvvmCross 5.0. I suggest you update your adapter.

**Comment by DmitryNikiforov** [comment]
I'm not sure that issue is because of adapter. I've just update mvvmcross to version 5.0.1. After that build failed, because MvxAdapter(adapter for MvxListView, yes, we have some legacy code) has methods CreateBindableView and GetBindableView, their signature were changed. Fix all signatures, from 
`CreateBindableView(object dataContext, int templateId)` to
`CreateBindableView(object dataContext, ViewGroup parent, int templateId)`.

Then try to launch application, and MvxAndroidSetup crash appear

mvx:Diagnostic:  4.50 Setup: CommandCollectionBuilder start
mvx:Diagnostic:  4.50 Setup: NavigationSerializer start
mvx:Diagnostic:  4.51 Setup: InpcInterception start
mvx:Diagnostic:  4.51 Setup: LastChance start
[Mono] Assembly Ref addref LT.App.Health.Droid[0xdd1bbf00] -> MvvmCross.Droid.Support.Design[0xdd1bc800]: 3
[Mono] Assembly Ref addref LT.App.Health.Droid[0xdd1bbf00] -> PCLCrypto[0xdd1bd8e0]: 2
[Mono] Assembly Ref addref PCLCrypto[0xdd1bd8e0] -> mscorlib[0xdd1bbde0]: 107
[mono-rt] Stacktrace:
[mono-rt] 
[mono-rt] /proc/self/maps:
...
[mono-rt] No native Android stacktrace (see debuggerd output).
[mono-rt] 
[mono-rt] 
[mono-rt] =================================================================
[mono-rt] Got a SIGSEGV while executing native code. This usually indicates
[mono-rt] a fatal error in the mono runtime or one of the native libraries 
[mono-rt] used by your application.
[mono-rt] =================================================================
[mono-rt] 
[libc] Fatal signal 11 (SIGSEGV), code 2, fault addr 0xc5c50ef0 in tid 13243 (Thread-6)

**Comment by DmitryNikiforov** [comment]
It's seems something happened with libmonosgen.so. 
Attempted to unregister already unregistered input channel SplashScreen
Logcat contains: Sending message to a Handler on a dead thread. 
backtrace: data/app/Mono.Android.DebugRuntime-1/lib/arm64/libmonosgen-32bit-2.0.so

**Comment by Cheesebaron** [comment]
Did you try uninstall the app completely? Seems unrelated as it doesn't even get to the part where it switches ViewModel.

**Comment by DmitryNikiforov** [comment]
Yes, I uninstall app with adb uninstall, clear all obj folders - no any changes. Yes, crash appears after MvxAndroidSetup.CreateApp invokes, but before IMvxAppStart.Start. 
Strange, I haven't any other changes, except update mvvmcross and related packages, but for mvvmcross 4.4 app launches without any problem

**Comment by DmitryNikiforov** [comment]
Additional investigate: app crashes on MvxAndroidBindingResource class on private constructor
for this lines
 this.ControlStylableGroupId = (int[])SafeGetFieldValue(styleable, "MvxControl", new int[0]);
this.BindingStylableGroupId =  (int[])SafeGetFieldValue(styleable, "MvxBinding", new int[0]);
this.ImageViewStylableGroupId = (int[])SafeGetFieldValue(styleable, "MvxImageView", new int[0]);
this.ListViewStylableGroupId = (int[])SafeGetFieldValue(styleable, "MvxListView");
this.ExpandableListViewStylableGroupId = (int[])SafeGetFieldValue(styleable, "MvxExpandableListView", new int[0]);

It's seems, that app crashes while try GetValue for  array properties. What can cause this?

**Comment by DmitryNikiforov** [comment]
It's seems, something wrong with MvvmCross.Droid.Support.Design.5.0.1. Application crashes in method UpdateIdValues in Resource.Designer.cs, when set this library ids. Something similar described [this](https://github.com/AArnott/PCLCrypto/issues/100) 
Can resources from package conflict with another packages?

**Comment by DmitryNikiforov** [comment]
Mvvmcross 5.0.2 fixed this issue. Thanks!
