### ISSUE TITLE
Documents: Plugins README are old

### ISSUE THREAD

**Issue by jz5** [MvvmCross/MvvmCross#1886]
Plugins README.md are old.

e.g. 
* https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-Plugins/Accelerometer/Readme.md
* latest document: https://www.mvvmcross.com/documentation/plugins/accelerometer

Proposal:
README only contains a link to the document page on mvvmcross.com.
I can PR if approved. 
Or remove them?

**Comment by Cheesebaron** [comment]
Linking to docs would be fine. Docs should be where to find stuff. So go ahead and make a PR.
