### ISSUE TITLE
Feature Suggestion - Side by side Xamarin iOS/Android and Xamarin Forms

### ISSUE THREAD

**Issue by sisterray** [MvvmCross/MvvmCross#1889]
It would be very useful to enable an MvvmCross based application to use both Xamarin iOS/Android and Xamarin Forms in the same application. This would allow a smooth migration for apps which started development before Xamarin Forms was available/stable.

As far as I am aware at the moment this is not possible.

**Comment by MarcBruins** [comment]
I agree that this would be a nice feature to have. There is already some progress made by @munkii see #1415 and https://github.com/munkii/MvxAndXamForms. It would be great if you can help out and make this happen.

**Comment by Cheesebaron** [comment]
This feature is supported in Xamarin.Forms 3.0

**Comment by martijn00** [comment]
The feature of Forms 3.0 is to include forms layouts in native layouts/code. This feature request is a different use case, where we navigate to either a Forms ContentPage or a native view using a MvvmCross presenter.

**Comment by Cheesebaron** [comment]
Well if we can convert a Forms page to a Fragment/ViewController/Framwork Element, then we can just show that. It is not just the native View you get...

**Comment by munkii** [comment]
My "MvxAndXamForms" repo was not very well integrated with MVVMCross. I have Forked 5.0 at https://github.com/munkii/MvvmCross. In there I have created a project called NativeToXF in the TestProjects/Forms area.

I have it working with Android and iOS but have an issue with UWP. I need to better understand how XF integrates with the RootFrame i think

**Comment by MarcBruins** [comment]
Sounds good @munkii. I'll would like top help out on this soon (maybe during our Mvx 5.0 launch party)
