### ISSUE TITLE
Feature suggestion - PictureChooser WPF - Add gif and png files in DialogBox

### ISSUE THREAD

**Issue by mathieumack** [MvvmCross/MvvmCross#1891]
The goal is to be able to select png, gif or tiff files in the picture chooser from the PictureChooser plugin for WPF Platform.

### Actual behavior
We can only select jpg files.

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [ ] Android
- [x] WPF
- [ ] UWP

**Comment by mathieumack** [comment]
I've forked the project to add filters.
I will create the pull request for this issue in next days.

**Comment by Cheesebaron** [comment]
That would be great! Thanks!

**Comment by mathieumack** [comment]
@Cheesebaron For this evolution, I need to use a method available in a nuget package (https://www.nuget.org/packages/PixelFormatsConverter/).
Do you prefer to add a dependency to this package or should I copy the source code Inside the plugin (Only 1 file - https://github.com/mathieumack/PixelFormatsConverter/blob/master/PixelFormatsConverter/PixelFormatsConverter/PixelFormatConverterExtensions.cs)
I am the Creator of this package so it's not a problem to copy the code.

**Comment by Cheesebaron** [comment]
I'd say copy the code over and attribute yourself appropriately.

It is one class that is in the NuGet.
