### ISSUE TITLE
Documentation: ViewModel lifecycle doesn't explain how to deal with tombstoning

### ISSUE THREAD

**Issue by nmilcoff** [MvvmCross/MvvmCross#1892]
[This document](https://www.mvvmcross.com/documentation/fundamentals/viewmodel-lifecycle)  only explains what was introduced in MvvmCross 5.0, but it doesn't have some of the info there was in the old Wiki about how `SaveStateToBundle` and `ReloadFromBundle` work.

If someone can point me out where did all those documents go, I can make a PR to bring back the missing content.

**Comment by MarcBruins** [comment]
Here it is: https://gist.github.com/MarcBruins/7353c7f9b169bda654a2a86aaef8a233
