### ISSUE TITLE
Appearing event called multiple times on Android platform

### ISSUE THREAD

**Issue by Bowman74** [MvvmCross/MvvmCross#1894]
### Steps to reproduce

1. Create a MvvmCross Android project

2. Have an Activity inherit from MvxAppCompatActivity<TypeofViewModel> and a view model that inherits from MvxViewModel

3. Register that view model as the app start view model in the MvxApplication class.

4. Add Debug.WriteLine statements to the view model in the lifecycle events

5. Run the app and view the application output.

### Expected behavior
Appeared event should only be called once when screen is loading (this is how it works in the iOS application)

### Actual behavior
Appeared event called multiple times

Relevant log output:
mvx:Diagnostic:  3.05 Attempting to load new ViewModel from Intent with Extras
CustomerListViewModel: instance: c2d7695d-212b-466e-bc48-6c792bb06d71: constructor
CustomerListViewModel: instance: c2d7695d-212b-466e-bc48-6c792bb06d71: start
CustomerListViewModel: instance: c2d7695d-212b-466e-bc48-6c792bb06d71: appearing
CustomerListViewModel: instance: c2d7695d-212b-466e-bc48-6c792bb06d71: appeared
CustomerListViewModel: instance: c2d7695d-212b-466e-bc48-6c792bb06d71: appeared
CustomerListViewModel: instance: c2d7695d-212b-466e-bc48-6c792bb06d71: appeared

One of the extra appeared calls seems to be tied to issue #1880. One call goes away if I implement the workaround I found, still leaving the appeared event getting called twice.

### Configuration
Debug

**Version:** 5.0.1

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

Solution that shows the problem:
https://github.com/Bowman74/VSLiveMvvmCross/tree/MvvmCrossError/src/Demo2/VsLiveMvvmCross

**Comment by Cheesebaron** [comment]
This is the relevant piece of code where this event is fired: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.V7.AppCompat/MvxAppCompatActivity.cs#L72

**Comment by kjeremy** [comment]
We probably need to check if the vto is alive before firing the event and
unsubscribing.

**Comment by Bowman74** [comment]
I've done some investigation. What I suspect is happening is that when the Android screen is being measured three measurements happen in rapid succession and GlobalLayout events called before the event handler can be unsubscribed.

**Comment by Bowman74** [comment]
OK, I have a candidate fix for this. Let me get together a PR.

**Comment by Bowman74** [comment]
This turned out to be an issue with how Xamarin wraps the native events, particularly with the lifecycle behind unsubscribing.  By switching to the native style event handlers the problem was resolved using the same logic as the original implementation.

**Comment by Danielbahe** [comment]
@nmilcoff Finally the bug is not happening.
I tested the app with another pc, another device and the bug didn't appear.
Then I test again on the same pc and the same device than before and works too.
I explain here that for any people who ends here with the same problem than me.

**Comment by ronenfe** [comment]
This happens also if using native code with content prrovider of call log. It fires three times with no reason.
