### ISSUE TITLE
FloatingActionButton Click event binding not working

### ISSUE THREAD

**Issue by StephenBeirlaen** [MvvmCross/MvvmCross#1896]
### Steps to reproduce

MainActivity:
```
<android.support.design.widget.FloatingActionButton
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom|end"
    android:layout_margin="@dimen/fab_margin"
    android:tint="@android:color/white"
    app:backgroundTint="@color/colorPrimary"
    app:srcCompat="@drawable/ic_add_black_24dp"
    app:MvxBind="Click AddCommand" />
```
MainViewModel:
```
public ICommand AddCommand
{
    get
    {
        return new MvxCommand(() =>
        {
            ShowTimetrackingForm();
        });
    }
}
```
MvxAppCompatSetup:
```
protected override IEnumerable<Assembly> AndroidViewAssemblies {
    get
    {
        var assemblies = base.AndroidViewAssemblies.ToList();
        assemblies.Add(typeof(FloatingActionButton).Assembly);
        return assemblies;
    }
}
```

### Expected behavior
The Click event should bind correctly

### Actual behavior
No click event, instead the following error appears on VM load:
`MvxBind:warning:305,25 Unable to bind: source property source not found Property:AddCommand on MainViewModel`

### Configuration

**Version:** 5.0.1

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
Just to be sure the problem isn't in your code, did you try to bind that command to any other view in that .axml?

**Comment by StephenBeirlaen** [comment]
Oh.. I just tried binding it to a regular Button and it's also throwing that error... Whoops. Now I can't see why it's happening, other bindings in the same VM and XAML work fine...

**Comment by StephenBeirlaen** [comment]
Okay... I cleaned the bin and obj folders of my project and now the binding is working... Great, thanks for your time!
