### ISSUE TITLE
NavigationService: Close all Fragments of parent Activity from within fragment ViewModel

### ISSUE THREAD

**Issue by StephenBeirlaen** [MvvmCross/MvvmCross#1917]
### Steps to reproduce

- The parent activity contains two fragments A and B.
- When opening the activity, fragment A opens from the ViewModel using the NavigationService.
- On fragment A is a button that opens fragment B on top of fragment B (backstack).
- Now on fragment B there is a button which should close the activity and both fragments. (the goal is to open another Activity with completely different content)

The following code:
`_navigationService.Close<ActivityViewModel>();`
... isn't working, the fragment ViewModels remain open. I would like a way to make them close with their parent activity.

### Expected behavior
Child fragments should close with their parent activity.

### Actual behavior
Both fragments remain open.

### Configuration

**Version:** 5.0.1 (edit: updated to 5.0.2 - same behavior)

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
Please update to 5.0.2 and see if this yields same behavior.

**Comment by StephenBeirlaen** [comment]
Okay, I just updated. Unfortunately, same results.
