### ISSUE TITLE
🔥 Kill MvxLinearLayout and the likes🔥 

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1918]
I often see people abusing MvxLinearLayout and other non-Adapter based layouts, to do what they actually would want to do in MvxRecyclerView.

I really want to kill off:

- MvxLinearLayout
- MvxFrameLayout
- MvxRelativeLayout
- MvxTableLayout

These should not be there at all from a memory efficiency perspective

**Comment by nmilcoff** [comment]
Can we maybe document these widgets instead of removing them? They're useful in some situations.

**Comment by kjeremy** [comment]
`MvxLinearLayout` has its uses but I would nuke the rest.

**Comment by willsb** [comment]
So, should them all be 🔥 or should we keep some of them alive?

**Comment by nmilcoff** [comment]
I vote to keep `MvxLinearLayout` alive and remove the rest.
