### ISSUE TITLE
UWP MvxRegion split-view navigation broken in 5.0.2 

### ISSUE THREAD

**Issue by Xciles** [MvvmCross/MvvmCross#1920]
### Steps to reproduce

1. Create MvvmCross & UWP project.

2. Implement split-view MvxRegion based navigation for UWP. (Based on https://github.com/MvvmCross/MvvmCross-Samples/tree/master/XPlatformMenus & #1257)

### Expected behavior
Split screen navigation for UWP. The 'PageContent' should be used by the different pages, 'MenuContent' should stay the same.

### Actual behavior
Application starts and navigates to a menu and PageContent view. However when navigating and entering OnNavigatedTo(e);, both requests end up in a NullRef on IsCompleted in [MvxParser](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Platform/Platform/Parse/MvxParser.cs#L29) (Or the Parse method in [MvxStringDictionaryParser](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Core/Core/Parse/StringDictionary/MvxStringDictionaryParser.cs#L24)) since FullText is (or textToParse was) NULL. 

### Configuration

**Version:** 5.0.2

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [X] UWP

### Problem
When searching for new ways to implement split-view navigation, I came across a similar approaches to the XPlatformMenus example. I started using that approach for all platforms, with some changes of course. When updating from 5.0.1 to 5.0.2 (because of #1879) UWP started throwing NullRefs on navigating to MvxRegion views.

Unfortunately it looks like the changes implemented in #1905 broke MvxRegion based navigation. For MvxRegion the presenter uses a different navigation serializer, MvxRegion uses [IMvxNavigationSerializer](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Windows/Uwp/Views/MvxWindowsMultiRegionViewPresenter.cs#L38) while others use [IMvxWindowsViewModelRequestTranslator](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Windows/Uwp/Views/MvxWindowsViewPresenter.cs#L32). 

For MvxRegion this results in a different _'requestText'_ in the [MvxWindowsViewContainer](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Windows/Uwp/Views/MvxWindowsViewsContainer.cs#L29) where the actual _requestText_ does not contain the _'ExtrasKey'_. This results is a NULL _'serializedRequest'_ and when trying to deserialize and parse NULL you get the NullRef on IsCompleted in [MvxParser](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Platform/Platform/Parse/MvxParser.cs#L29). 

This results in the MvxRegion views not loading. Other views and navigation do not seem to be impacted by this.

### Possible solution
Changing the deserialization of request in the MvxWindowsMultiRegionViewPresenter to use the [IMvxWindowsViewModelRequestTranslator](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Windows/Uwp/Views/MvxWindowsViewPresenter.cs#L32) implementation seems to resolve this issue. After changing and implementing this locally, navigation using split-view and MvxRegions seems to be working again.

I'm not sure if that is the proper fix for this issue. Or if split-view navigation has changed to use something differently. Any thoughts?

Sample UWP app that shows the above (sorry in advance for the name ;) ): 
https://github.com/Xciles/UWPRegion

**Comment by Leechristmas** [comment]
Have faced with the same problem, any updates?

**Comment by Xciles** [comment]
I can create a PR for a possible fix. 

@martijn00, @Bowman74 Is changing the _IMvxNavigationSerializer_ logic to _IMvxWindowsViewModelRequestTranslator_ sufficient?

**Comment by Bowman74** [comment]
@xciles I'd have to view the PR.  Do we have a working example of the MvxRegion split view?

**Comment by Bowman74** [comment]
@xciles looks like we do. Always the problem with answering on a phone. Likely we just need to add a case when evaluating the Load method of the MvxWindowViewsContainer and handle it differently. This is what the Android project does.

**Comment by Xciles** [comment]
@Bowman74 Yeah, I included an example :)
Android uses just the _IMvxAndroidViewModelRequestTranslator_ to translate a request. The UWP _MvxWindowsMultiRegionViewPresenter_ directly uses the _IMvxNavigationSerializer_ when requesting a view with a Region attribute.  

Changing the [MvxWindowsMultiRegionViewPresenter](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Windows/Uwp/Views/MvxWindowsMultiRegionViewPresenter.cs#L38)
``` Csharp
var converter = Mvx.Resolve<IMvxNavigationSerializer>();
var requestText = converter.Serializer.SerializeObject(request);
```
to 

``` Csharp
var requestTranslator = Mvx.Resolve<IMvxWindowsViewModelRequestTranslator>();
var requestText = requestTranslator.GetRequestTextFor(request);
```
seems to resolves this issue. This also follows the implementation currently present in the [MvxWindowsViewPresenter](https://github.com/MvvmCross/MvvmCross/blob/f9f6e2643d2defc6ccc033f899a8ecf599441e67/MvvmCross/Windows/Uwp/Views/MvxWindowsViewPresenter.cs#L31), since both navigate a frame to a certain view/viewmodel. Not sure if a Region request can also be a _MvxViewModelInstanceRequest_, I assume that is not the case right? We might as well just create a protected method for the translation to _requestText_ within the _MvxWindowsViewPresenter_ for all presenters using that as a base.

I think we can't handle this issue within the Load, because of the _requestText_ is in a different format (without the _ExtrasKey_). It is possible to change Load so it can handle this, however I don't think it's the proper way. Checking if the [TryGetValue](https://github.com/MvvmCross/MvvmCross/blob/5.0.2/MvvmCross/Windows/Uwp/Views/MvxWindowsViewsContainer.cs#L29) returns false and DirectLoading the ViewModel might impact more.

**Comment by Bowman74** [comment]
@Xciles I put in a PR that corrects this issue when I upgraded the sample projects you referenced.

**Comment by Xciles** [comment]
Nice thanks!
