### ISSUE TITLE
WPF Navigation Service doesn't work with parameter

### ISSUE THREAD

**Issue by bregol** [MvvmCross/MvvmCross#1921]
### Steps to reproduce

1. Create a WPF project

2. Navigate to new viewmodel passing a parameter using the new Navigation Service 

3. Have that viewmodel you are navigating to try to use the parameter in the Initialize method 

### Expected behavior
The viewmodel should have a single instance created and the parameter passed to it in the Initialize method.

### Actual behavior
Two viewmodels are created.  The first one created runs Initialize with the parameter passed to it.  Then a second version of the viewmodel is created and this one is shown but does not have the parameter passed to it.

This is the same thing for WPF that was happening for UWP here: https://github.com/MvvmCross/MvvmCross/issues/1905

### Configuration

**Version:** 5.0.2

**Platform:** 
- [ ] iOS
- [ ] Android
- [x] WPF
- [ ] UWP

**Comment by Bowman74** [comment]
Likely this is the same issue with UWP and the cache may need to come into play.

**Comment by Bowman74** [comment]
I'll see if I can't grab this in the next few days. Probably similar solution to UWP.

**Comment by Bowman74** [comment]
I'll see if I can't grab this in the next few days. Probably similar solution to UWP.
