### ISSUE TITLE
Fix issues reported by code factor

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1922]
I just added Code Factor to our repository, and it reports a couple of issues (2400+). These are mostly small code style issues, but also duplicate code etc.

See: https://www.codefactor.io/repository/github/mvvmcross/mvvmcross/issues

Would be awesome if we could chip away some of these issues to improve our code quality.

It should also be added to Pull Requests as a hook so it shows whether a PR improves or worsens quality.

**Comment by mvanbeusekom** [comment]
Great initiative! I will invest some time to make some improvements

**Comment by kjeremy** [comment]
:+1:

**Comment by MarcBruins** [comment]
Would be great if we can add this to PR's!

**Comment by Cheesebaron** [comment]
It is already. Just look at: #1923 it has been marked as failed because PR duplicates code 😄

**Comment by martijn00** [comment]
This is an ongoing work.
