### ISSUE TITLE
Navigation Issues UWP after Upgrade

### ISSUE THREAD

**Issue by smokingfish** [MvvmCross/MvvmCross#1940]
I tried upgrading a quite big (mainly) UWP project from 4.x to 5.0.2.
All ShowViewModel calls were replaced by IMvxNavigationService calls.

### Steps to reproduce
I attached a demo program.

### Expected behavior
**NavigationCacheMode = Disabled:**
As in 4.x, create new instance of ViewModel and View on each Navigate() and Close()
I manually managed resources when working like this because 4.x did not clear the cache or disposed the old ViewModels.

**NavigationCacheMode = Enabled**
Close() as it is now. Navigate() should create a new Viewmodel instance (currently does so) and set the DataContext to the new instance if the view is reused.

### Actual behavior
**NavigationCacheMode = Disabled:**
Using the last version Close() would create a new ViewModel instance and set the DataContext. After the Update the DataContext is not set. Callin Navigate with parameter successfully calls Initialize() and the parameter can be used for the newly created view.

**NavigationCacheMode = Enabled**
We wanted to use this to improve loading times and maybe as a workaround for the previous issue. Unexpected behavior: When calling Navigate() (with or without parameter) Initialize() gets called successfully and a new instance of the Viewmodel is created, but the DataContext of the cached view is still the previous copy of the Viewmodel.

### Configuration

Version: 5.0.2

Platform: 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [x] UWP

[WebViewTestApp.zip](https://github.com/MvvmCross/MvvmCross/files/1071310/WebViewTestApp.zip)

**Comment by smokingfish** [comment]
Maybe this helps a little bit: I updated to the latest unstable build (5.1.0unstable0086).

In this version it is even more broken :) 
With cache enabled it will create 2 Viewmodels on first Navigate(), call Initialize() on the version not set as datacontext. After that creates a new instance/calls Initialize() on Navigate(), but still uses cached version. No Action on back navigation using Close() from another view.

With no cache it always creates 2 instances, uses the version not bound to the view and calls Initialize(). On back navigation using Close() from another view creates new instance but does not call Initialize().

**Comment by smokingfish** [comment]
I think it would be helpful if someone could take a look at the sample program and clarify if that is indeed the correct usage.

The sample also demonstrates a problem with disposing Views/Viewmodels. I would expect both to be disposed as soon as the view is no longer at the top of the stack (in the sample meaning, going back to the start page). You can demonstrate it by clicking the youtube button, playing a video with sound and going back. 

I would Destroy() to get called somewhere, but on both scenarios it never fires.

**Comment by Bowman74** [comment]
@smokingfish,
OK, I've dug into this a while. You have mentioned three issues:
- It does not appear the Destroy method is hooked up for UWP, even though there is a logical place for it in the UWP extension methods.
- The reason why you have problems in the NavigationCacheMode is that the loading of the viewmodel to the view is currently initiated by the OnViewCreate event (see MvxWindowsExtensionMethods.cs). Since the view is only created once and the OnViewCreate event not called again in cached scenarios, it always uses the ViewModel it was first given.
- The reason why the no cache page has problems navigating back from the extras page is at that time the view is recreated passing in the original request string. The request string contains the location of the view model in the IMvxChildViewModelCache but we remove that once the view is done loading for the first time. Without finding it in the IMvxChildViewModelCache the page is displayed with the ViewModel being null. Bad things happen from there.

I can see a way through all three of these issues (in theory). I'll see if I can't implement them in reality and get a PR in.

**Comment by smokingfish** [comment]
Thank you so much. I really struggled with explaining what exactly the issue is :)
I did find a few of those reasons too, overriding and copy/pasting the code from the develop or 5.x branch, but had no idea what was actually intended by mvx, if I maybe used it wrong or if there is actually a bug.
I could create a more complex test program, with more levels and cache/nocache mixes if that helps in any way.

**Comment by Bowman74** [comment]
@smokingfish I have a PR in to correct the two navigation issues. I'm not sure the destroyed event is called in other platforms so I left that one off. Probably we shouldn't have one bug with multiple fixes on it anyway.

**Comment by smokingfish** [comment]
Thank you! I will test this later today.
Currently I only target UWP, so I don't know how it is done on other platforms.
But I did have problems with the lifecycle on 4.x too and manually disposed views/viewmodels through a custom presenter, so I can for now just use that solution.

**Comment by smokingfish** [comment]
I tested this and it works just fine in both scenarios!

Still the issue with Destroy(), but it works perfectly well if I add the call in the OnViewDestroy() before the viewmodel is removed.

If I do that, at least my scenarios are working perfectly well with the small exception that UWP also keeps views in cache on back navigation, so you will see a slight delay after the view is loaded and it is updating according to its new datacontext.

So thanks again, I am fine, you can close this if you want :)

**Comment by b099l3** [comment]
Sweet this is working for me too, just came across the same issue today after being on 5.0.0 Upgraded to 5.0.3 and its fixed for me.
