### ISSUE TITLE
Cannot resolve Assembly or Windows Metadata file 'MvvmCross.WindowsUWP.dll'

### ISSUE THREAD

**Issue by selaromdotnet** [MvvmCross/MvvmCross#1952]
I'm not sure how to turn this into something I can share on Git to reproduce, but before I try I wanted to post to see if anyone else has ever seen this exact problem when building a Xamarin Forms app with MvvmCross. The app builds without fail in DEBUG and I can run it on both emulator and device, but when I build as Release the build fails.

### Steps to reproduce

1. Add references to MvvmCross for Xamarin Forms UWP app:
MvvmCross
MvvmCross.Core
MvvmCross.Platform
MvvmCross.Forms.Presenter

2. Build the project in Debug

### Expected behavior
Project should build without error

### Actual behavior
Project builds successfully, but I get this error in the Error List:

> Cannot resolve Assembly or Windows Metadata file 'MvvmCross.WindowsUWP.dll'	

This wasn't a problem for the longest time because I was just testing, but when I built in release I get similar errors and a failed build:

> Error		Type 'MvvmCross.WindowsUWP.Views.IMvxWindowsFrame' was not included in compilation, but was referenced in type 'MvvmCross.Forms.Presenter.WindowsUWP.MvxFormsWindowsUWPPagePresenter'. There may have been a missing assembly.		
> 
> Error		ILT0005: 'C:\Users\josh\.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\x86\ilc\Tools\nutc_driver.exe @"D:\Visual Studio\My Projects\Mobile\My.Mobile\My.Mobile.UWP\obj\x86\Release\ilc\intermediate\MDIL\My.Mobile.UWP.rsp"' returned exit code 1	

### Configuration

**Version:** 5.0.2

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [X] UWP

**Comment by martijn00** [comment]
The package for Forms is not 'MvvmCross.Forms.Presenter' but 'MvvmCross.Forms' since 5.0. Also `WindowsUWP` is not used anymore since then, but  just `Uwp`.

**Comment by selaromdotnet** [comment]
that makes total sense, I wondered why the version of presenter didn't match. i knew it was something dumb i was doing :) changing the package as you instructed resolved the issue, thanks for your help!
