### ISSUE TITLE
ListItemView loses binding during heavy scrolling

### ISSUE THREAD

**Issue by SSElliott** [MvvmCross/MvvmCross#1954]
This is the first bug I have raised for MVVMCross (it has otherwise been excellent) but I appear to have problem using MvxListViews with MvxAdapters, selecting templates and the binding appearing to fail after heavy scrolling. It appears to mainly affect Android 7 devices. Earlier versions do not appear to have the same problem.  I enclose a small project (based on the screen shot) that highlights the problem. I have the problem in more complex areas of my application on ordinary Activities not just the Burger Menu as in the attached example.

This problem is only in MvvmCross 4.4. Is this fixed in 5.* or is this unknown to you.

![img_1409](https://user-images.githubusercontent.com/29478656/27226194-b364a080-5295-11e7-87fc-b1c77ce4a27d.JPG)

### Steps to reproduce

1. Create  MvxListView Bound to List of ViewModels (derived from MvxViewModel). 
2. Connect to MvxAdapter that uses different templates depending on ViewModel values
3. Scroll up and down quickly on the list repeatedly for about 20 seconds.
4. Check List for MvxListItemViews that have lost their binding and gone blank

### Expected behavior
Binding should be kept

### Actual behavior
It looks as if the binding has not been applied on some items. The template is applied but bound items in the template lose their values.

### Configuration

**Version:** 4.4

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

[BindingLost.zip](https://github.com/MvvmCross/MvvmCross/files/1080701/BindingLost.zip)

**Comment by kjeremy** [comment]
Can you reproduce this in the latest version?

**Comment by SSElliott** [comment]
I am unable to upgrade my project because it appears MvxFragmentActivity is missing from 5.0.2 MvvmCross.Droid.Support.Fragment. I use this heavily.

**Comment by Cheesebaron** [comment]
https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.Fragment/MvxFragmentActivity.cs

It is there.

**Comment by SSElliott** [comment]
I have seen that already but then which package do I need? I already have MvvmCross.Droid.Support.Fragment, and I have inspected the dll (ver. 5.0.2.0) and it is not in there.

**Comment by Cheesebaron** [comment]
From what namespace are you trying to get it from?

**Comment by SSElliott** [comment]
I was under the impression that it has moved from MvvmCross.Droid.Support.V4 to 
MvvmCross.Droid.Support.Fragment  as per
https://www.mvvmcross.com/documentation/upgrading/upgrade-to-mvvmcross-50

**Comment by Cheesebaron** [comment]
Yes, it has moved from one NuGet package to another. That does not imply namespace change.

**Comment by SSElliott** [comment]
I am unable to see any reference to MvvmCross.Droid.Support in the new package. I am totally confused by this.

![missing](https://user-images.githubusercontent.com/29478656/27229221-a891798c-52a2-11e7-8cac-d5cc8d00847a.png)

**Comment by SSElliott** [comment]
I think this has something to do with having a much older version of Xamarin (4.2.11 whilst 4.5.9.486 is released).   

I will have to hold off  for the time being. I managed to work around it in the less than satisfactory way of passing null rather than convertView. I have a release just coming up and I do  not want to alter my enviroment just yet and as I have not had any memory issues as a result of this so this will have to do. However there is something amiss in MVVMCross 4.4.

Is there any active bug fixing in the 4.X branch or is this a non starter?

Kind Regards

Steven





Thank you for you help

**Comment by Cheesebaron** [comment]
We are not going to do bugfixes for 4.x.

**Comment by SSElliott** [comment]
I have just tried the latest version of MVVM Cross and I still have the same problem.

**Comment by SSElliott** [comment]
I should add that in MvvmCross 5 (latest), I get the same missing MvxListViewItem problem that I had previously.

**Comment by Cheesebaron** [comment]
Thanks for confirming this. Can you make a repro project and make a repository out of it (we don't want zip blobs).

**Comment by KyawSithuAung** [comment]
I also got this problem in my project, which use mvvmcross 5.0 and run on android nouget and there is no problem in previous android versions.

**Comment by Cheesebaron** [comment]
Can you maybe confirm if this is an issue with RecyclerView too?

**Comment by SSElliott** [comment]
I do not explicitly use the RecyclerView, just the MVXListView and MvxAdapter. I will post a repro project in the next few days with an example of what is happening.

**Comment by SSElliott** [comment]
Please find the attached project. I have kept the styles in, in case they are of importance. To replicate. Simply scroll very quickly up and down on the burger menu MvxListView (with sudden changes of direction). 

Its worth nothing that it uses different templates, picked on the fly, and Fragments.

I look forward to your thoughts.

https://github.com/SSElliott/MVVMCross-BindingLost-MvxListView

**Comment by SSElliott** [comment]
Hi Cheesebaron

Have you any any thoughts or ideas on this problem? 

Kind Regards

Steven

**Comment by Cheesebaron** [comment]
Haven't had time to look at it yet.

**Comment by Cheesebaron** [comment]
Looking at the View Hierarchy dump it appears that the items disappear from the list entirely. Although pressing the item, it seems like the bound Command for the item is still working fine.

![image](https://user-images.githubusercontent.com/249719/28285486-3bd2deca-6b35-11e7-9276-39e2066074e0.png)

I've tried replicating this on a fresh project. Which only uses one ItemTemplate set through the xml attribute. Here I cannot reproduce the issue. 

I tried the same using a _very_ simple adapter

```C#
        public class CustomAdapter : MvxAdapter
        {
            public CustomAdapter(Context context) : base(context)
            {
            }

            public CustomAdapter(Context context, IMvxAndroidBindingContext bindingContext) : base(context, bindingContext)
            {
            }

            public CustomAdapter(IntPtr javaReference, JniHandleOwnership transfer) : base(javaReference, transfer)
            {
            }

            protected override View GetBindableView(View convertView, object dataContext, ViewGroup parent, int templateId)
            {
                var item = (DerpViewModel)dataContext;

                if (item.Count % 2 == 0)
                    templateId = Resource.Layout.list_item;
                else
                    templateId = Resource.Layout.list_item2;

                var v = base.GetBindableView(convertView, dataContext, parent, templateId);
                return v;
            }
        }
```

Here I could reproduce the issue. However, unlike yours, scolling up and down slow after an item disappears, it reappeared fine again.

Need to see if this is also an issue with RecyclerView

**Comment by Cheesebaron** [comment]
I can't reproduce with MvxRecyclerView and MvxTemplateSelector. I highly suggest you use that instead. This way you have no need for a custom adapter either.

**Comment by SSElliott** [comment]
Thank you. I am kind of relieved that  you managed to replicate the problem (I was not going mad), I will try your suggestion. 

Steven

**Comment by Cheesebaron** [comment]
Seems like implementing `GetItemViewType` and `ViewTypeCount` helps. I can't reproduce the issue after overriding those.

Could look something like:

            public override int GetItemViewType(int position)
            {
                var rawItem = GetRawItem(position);
                if (((ItemViewModel) rawItem).Alternative)
                    return 1;
                return 0;
            }

            public override int ViewTypeCount { get; } = 2;

In general though. The ViewHolder pattern gets less usable when using multiple item templates as it will have to throw away ViewHolders when switching between templates for items. So another consideration could be to have one item template and show/hide portions of the view based on some bool or whatever.
