### ISSUE TITLE
Add nested categories to the documentation

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#1958]
We should add something to have nested categories in the documentation menu. This would enable us to split up certain topics and group them in sub-categories.

An idea could be to use a `category` and `parent-category` tag in the documents. The menu would filter out if a doc had a parent or not, and nest it.

**Comment by nmilcoff** [comment]
We definitely need this done to improve the docs on each platform!  We need a separate folder for each platform inside "Platform specifics"

It would be really helpful if any contributor with web skills could work on it!
