### ISSUE TITLE
Order of Initialize call in Android after Navigation service call

### ISSUE THREAD

**Issue by franksweeney** [MvvmCross/MvvmCross#1968]
Hi There, 
I have recently moved to MVVMCross 5.0 and have updated to the latest stable version 5.03.  I have an application that runs on Xamarin.Android  and Xamarin.IOS.  The same code works as expected on Xamarin.IOS but not on Xamarin Android.

### Steps to reproduce

1. Create two Viewmodels and navigate from one to the other using the navigation service passing data parameter
           _navigationService.Navigate<SecondViewModel, NavParam>(param);

2. In the second view model the initialize task is as follows
        public override async Task Initialize(NavParam parameter)
        {
            _navParam = parameter;
        }
3. The initialized value should then be  available in the Appeared method
public override void Appeared()
{
    base.Appeared();

    if (_navParam != null)
    {
        // do something with data (for example show pop-up)
    }
}

### Expected behavior
The second viewmodel will be created and then initialized so that the data passed as an initialization parameter is available in the appeared method call

### Actual behavior
The initialization method is called after the view has already been loaded and after the Appeared method so when Appeared is called the viewmodel has not been initialized.

Just to reiterate the same code works as expected in Xamarin.ios but not in Xamarin.Android.

Also this bug is very similar to #1902 Synchronous view model initialization, that was closed but I believe that only part of the bug was solved, that being the part where the viewmodel was reinstantiated but the viewmodel initialization part was not.

By the way thanks for all the great work on MVVMCross, its a fantastic framework.

### Configuration

**Version:** 5.0.3

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
@martijn00 could it have something to do with these particular two lines of code that are all over the NavigationService:

```Csharp
ViewDispatcher.ShowViewModel(request);
await viewModel.Initialize();
```

ShowViewModel always comes before Initialize, hence Appearing/Appeared always comes before Initialize and they always complete _before_ initialize because they are sync.

**Comment by martijn00** [comment]
Yes, it is definitely because if that. The question is should we do  `Initialize` before showing the request?

**Comment by Cheesebaron** [comment]
To me the logical order would be:

1. Initialize
2. Appearing
3. Appeared
4. Disappearing
5. Disappeared

Some of them may be async

**Comment by BradVause** [comment]
Hi guys, I am not sure what the resolution is here? Please can you help me. I have a problem with this. I am using the MvxNavigationService.Navigate method to show my second Viewmodel, and pass a string parameter. The Initialize method on the second view model is hit, and the parameter is there. I then set set my ViewModel property to the value passed into Initialize, but the view does not show the updated value. If I hard code the view model property in the constructure - it appears on the view. It feels to me like this Initialize method is happening after databinding? I am setting the Viewmodel property and calling RaisePropertyChanged, and just cannot get the view to update with the value I am passing through to the second viewmodel. Any advice would be greatly appreciated.

**Comment by mvanbeusekom** [comment]
@BradVause just to make sure, did you raise the NotifyPropertyChanged event when setting the property?

**Comment by BradVause** [comment]
@mvanbeusekom I am doing this:

        private string _locationText;
        public string LocationText
        {
            get { return _locationText; }
            set
            {
                _locationText = value;
                RaisePropertyChanged(() => LocationText);
            }
        }

The label on the view is bound like this: 
<Label Text="{Binding LocationText, Mode=OneWay}"/>

**Comment by BradVause** [comment]
@mvanbeusekom thanks, my repo is here:
https://github.com/BradVause/Tides

**Comment by mvanbeusekom** [comment]
@BradVause I've looked into the issue and found that the problem is related to the ViewModel is instantiated twice (see also this issue #1979 ). 

On the first instantiation the `Initialize` method is called. However on the second it is not called, but this is the one that the View binds to. As mentioned there is already an issue covering this bug and I assume it will be fixed soon. I don't really have a workaround for you, except for using the old navigation style (using `ShowViewModel`) and not the new MvxNavigationService.

**Comment by BradVause** [comment]
@mvanbeusekom Thanks SO MUCH, I have done so and its working as expected. I will revert back to the new way once the bug is fixed.
