### ISSUE TITLE
Use Android LruCache for DownloadCache?

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1969]
Since API 12 Android has LruCache built into the system and is also part of Support Libraries.

Currently we have our own hacked together Cache for bitmaps, which doesn't seem to work all that well.

We should investigate whether using LruCache along with using HttpClient to download the images would help in terms of performance and in terms of leaning out the code and simplifying it.

I feel that our current DownloadCache implementation is hard to maintain and has so many onion layers.

@MvvmCross/core what do you think?

**Comment by willsb** [comment]
_In theory_ replacing the current `IDictionary<CacheKey, WeakReference<Bitmap>>` should be as simple as:

```csharp
private readonly LruCache _memCache;

public MvxAndroidLocalFileImageLoader(int sizeInMb)
{
    _memCache = new LruCache(sizeInMb * 1024 * 1024);
}

private bool TryGetCachedBitmap(string localPath, int maxWidth, int maxHeight, out Bitmap bitmap)
{
    var key = new CacheKey(localPath, maxWidth, maxHeight);
    bitmap = _memCache.Get(key) as Bitmap;
    return bitmap != null;
}

private void AddToCache(string localPath, int maxWidth, int maxHeight, Bitmap bitmap)
{
    if (bitmap == null) return;

    var key = new CacheKey(localPath, maxWidth, maxHeight);
    _memCache.Put(key, bitmap);
}

private class CacheKey : JavaObject
{
    public override bool Equals(JavaObject obj)
        => Equals(obj as object);
}
```

I, however, defend the idea nuking the current implementation and instead creating a mechanism that allows people to drop native libs like Picasso or SDWebImage, that do downloading and caching very efficiently.
