### ISSUE TITLE
Initialize not called when manually instantiating an MvxViewModel

### ISSUE THREAD

**Issue by mrtnkrstn** [MvvmCross/MvvmCross#1972]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. when manually instantiating an MvxViewModel, I use the following code so that methods of the VM life cycle (`Init()`, `Start()`) are called:

```
var mvxViewModelLoader = Mvx.Resolve<IMvxViewModelLoader>();
var vmRequest = MvxViewModelRequest.GetDefaultRequest(typeof(MyViewModel));
_myViewModel = mvxViewModelLoader.LoadViewModel(vmRequest, null) as MyViewModel;
```

This is typically done in a Parent-Child VM setup (e.g. Tab Bars), where the Parent VM has to instantiate the Children VMs.

### Expected behavior
Using the above method, `Initialize()` should be called in the Child VM so that the vm can be inited (e.g. populated via web services).

### Actual behavior
Using the above method, `Initialize()` is not called on the Child VM, (although `Start()` is).

### Configuration

**Version:** 5.0.3

**Platform:** 
- [x] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by mrtnkrstn** [comment]
Also, `Initialize()` is not called in the VM that is navigated to from `RegisterAppStart()`. See test project at https://github.com/mrtnkrstn/MvvmCross_5.0.0

**Comment by Cheesebaron** [comment]
RegisterAppStart uses ShowViewModel internally if using the default.

**Comment by Cheesebaron** [comment]
IMvxViewModelLoader is not used by the new NavigationService, so you are mimicking ShowViewModel by using it.

IMvxViewModelLoader is kept as is to not break all apps using ShowViewModel.

**Comment by mrtnkrstn** [comment]
@Cheesebaron How Should `RegisterAppStart()` be called in MvvmCross 5? What is the recommended way to "manually" instantiate VMs in MvvmCross 5?

**Comment by Cheesebaron** [comment]
For now use a custom AppStart:

https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Navigation/RoutingExample.Core/AppStart.cs#L7

The manual instantiation really depends on what behavior you want

**Comment by mrtnkrstn** [comment]
Thanks for the custom AppStart code.

Solved the manual VM instantiation by using

`_myViewModel = Mvx.IocConstruct<MyViewModel>();`

in the Parent VM's constructor, and then in the ParentVM:

```
public async override Task Initialize()
{
    await base.Initialize();
    await _myViewModel.Initialize();
}
```

Thanks for the help, feel free to close the ticket.

**Comment by Cheesebaron** [comment]
I think we should keep it open.

To make it easier in scenarios where you want to do manual instantiation of a VM, we should support that by a new ViewModelLoader which handles common lifecycle events for you.

**Comment by Wenfengcheng** [comment]
I have tried to add this code to my project
```
        public override async Task Initialize()
        {
            await base.Initialize();
            await MeetingListViewModel.Initialize(); 
        }
```
but in the MeetingListViewModel.Initialize() method , i called a async method to get data , but it came to 
a deadlock
```
        public async Task<List<MeetingsListItemDto>> GetMeetingsListAsync()
        {
            await Task.Delay(1000);

            return new List<MeetingsListItemDto>
            {
               new MeetingsListItemDto{meetingId = "1234" ,title = "新产品发布会", datePublished = DateTime.Today, timeAndAddress="10:00 —— 12:00|振华企业广场A 1002"},
            };
        }
```
when the breakpoint to await ``` Task.Delay(1000)```,it not go down yet. The application paused like a deadlock. Anyone who can give me a guide?

**Comment by Cheesebaron** [comment]
You are doing a lot of context switching. Try suffix with `.ConfigureAwait(false)`

**Comment by Wenfengcheng** [comment]
I add this suffix , and I also get the data , but the application also interrupted in the splashscreen , never go down to show any view.

**Comment by Cheesebaron** [comment]
It is hard to help you without either a stack trace or a reproducible sample. Just saying it crashes doesn't help us help you unfortunately.

**Comment by Wenfengcheng** [comment]
all right , another problem the same to ```MainViewModel.Initialize()``` method not called when use ```RegisterAppStart<ViewModels.MainViewModel>();``` . When I change RegisterAppStart to RegisterNavigationServiceAppStart , it can be called. But can not show MainViewModel . That's very annoying.Thank you for help me! May be we will not use MvvmCross for serverl problems.

**Comment by sisterray** [comment]
Hi,

I have the same problem Initialize (public override async Task Initialize()) is not getting called in the main view model, although the corresponding view is displayed in the app.

Can someone post what I am supposed to do to get this working.

Thanks

**Comment by Wenfengcheng** [comment]
You can use Start(public override async void Start()) instead of Initialize , or you should register your main view model with RegisterNavigationServiceAppStart<>() instead of RegisterAppStart<>()。
This two worked for me , you can have a try.

**Comment by Wenfengcheng** [comment]
But use RegisterNavigationServiceAppStart<>() may come accross a deadlock when you use async method to get data from the server . I didn't know it cased by MvvmCross or my code.
