### ISSUE TITLE
App crash will null reference exception after cancelling sending email

### ISSUE THREAD

**Issue by DmitryNikiforov** [MvvmCross/MvvmCross#1978]
### Steps to reproduce

1. Try to use MvxPhoneCallTask plugin (IMvxComposeEmailTask)
ComposeEmail(string to, string cc = null, string subject = null, string body = null, bool isHtml = false, string dialogTitle = null)

2. dialog appeared with list of apps, supported emails

3. Click on any place not on the dialog to cancel sending email

### Expected behavior
App should not crash

### Actual behavior
App crashes with object reference exception on MvxComposeEmailTask.ProcessMvxIntentResult. filesToDelete is null

### Configuration

**Version:** 5.0.3

**Platform:** 
- [x] Android

**Comment by jz5** [comment]
This is already fixed in 5.0.6
https://github.com/MvvmCross/MvvmCross/commit/be5c99aa6d1bc2b4a6f3bdb4be3a72bb62cd8304

**Comment by nmilcoff** [comment]
You are right @jz5, thanks! #1996 contains a fix for this.
