### ISSUE TITLE
Binding issue on LinearLayout Activated property in Release mode

### ISSUE THREAD

**Issue by danieleardissone** [MvvmCross/MvvmCross#1982]
Hello,
I have an issue compiling my Android app in Release mode.
I'm using a LinearLayout with its Activated property in binding with a bool property of the related ViewModel to change the background image.

```
<LinearLayout
          android:background="@drawable/ic_tab_selector"
          local:MvxBind="Click RentalTypeSelectedCommand, CommandParameter=0; Activated DeliverySelected"/>
```

```
<?xml version="1.0" encoding="UTF-8" ?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
	<item android:drawable="@drawable/tab" android:state_activated="false" />
	<item android:drawable="@drawable/tab_active" />
</selector>
```

In the ViewModel:

```
private bool _deliverySelected = true;
        public bool DeliverySelected
        {
            get
            {
                return _deliverySelected;
            }

            set
            {
                if (value == _deliverySelected)
                    return;

                SetProperty(ref _deliverySelected, value);
            }
        }
```

```
public IMvxCommand RentalTypeSelectedCommand { get { return new MvxCommand<string>(rentalType => RentalTypeSelected(rentalType)); } }

private void RentalTypeSelected(string rentalTypeString)
{
            RentalTypeEnum rentalType = (RentalTypeEnum)Enum.Parse(typeof(RentalTypeEnum), rentalTypeString);
            if (Enum.IsDefined(typeof(RentalTypeEnum), rentalType))
            {
                switch (rentalType)
                {
                    case RentalTypeEnum.Delivery:
                        {
                            DeliverySelected = true;
                            break;
                        }

                    case RentalTypeEnum.Withdrawal:
                        {
                            DeliverySelected = false;
                            break;
                        }
                }
            }
}
```

When I compile the solution in Debug mode it works, while in Release I can't see the background image of the lynearlayout.
I tried to remove the linker and it works, so I think there's something about it. 
Any ideas?

My MVVMCross version is 5.0.3

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

**Comment by danieleardissone** [comment]
### Steps to reproduce

1. Launch app in Release Mode.
2. Navigate to the view and click on the LinearLayout.

### Expected behavior
Setting the DeliverySelected property via RentalTypeSelectedCommand, I expected that the background image of the LinearLayout changes properly like in the Debug Mode.

### Actual behavior
The background image doesn't appear even if the DeliverySelected property has a value.

### Configuration

**Version:** 5.0.3

**Platform:** 
- [ x] Android

**Comment by Cheesebaron** [comment]
So did you actually try adding something like:

```
public void Include(LinearLayout ll)
{
    var activated = ll.Activated;
    ll.Activated = true;
}
```

in your LinkerPleaseInclude file?

**Comment by danieleardissone** [comment]
It works, thank you @Cheesebaron 
Do you know if there is any documentation about how to add properties to LinkerPleaseInclude?

**Comment by Cheesebaron** [comment]
Well your problem clearly describes a linking issue. To mitigate linking issues, you try to hint the linker that it is not allowed to strip that part away. Why is it linked away in this case? Bindings in MvvmCross rely on reflection, hence the Activated property on a LinearLayout is not invoked directly, but through reflection. Hence, the linker does not see direct usage of the Activated property and links it away.
I don't feel like duplicating the Xamarin docs about making releases and linking, they have excellent coverage on that.
