### ISSUE TITLE
MvxNavigationService.Close is not setting the ViewModel on the NavigateEventArgs

### ISSUE THREAD

**Issue by Qwin** [MvvmCross/MvvmCross#1983]
The MvxNavigationService AfterClose does not have the ViewModel set on NavigateEventArgs. This causing the e.ViewModel == null. See **attachment** for code where the viewmodel isn't set. 

<img width="777" alt="screen shot 2017-06-21 at 2 40 06 pm" src="https://user-images.githubusercontent.com/1026038/27408055-bb895028-568f-11e7-9b51-ff6c21e7ee53.png">

Expected: As per doc: 
https://www.mvvmcross.com/documentation/fundamentals/navigation

```
Mvx.Resolve<IMvxNavigationService>().AfterClose += (object sender, NavigateEventArgs e) => {
    //Do something with e.ViewModel
};

```

### Configuration

**Version:** 5.0.2

**Platform:** 
- [x] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
Please update to 5.0.3 and try again.

**Comment by martijn00** [comment]
This is fixed in: https://github.com/MvvmCross/MvvmCross/pull/1971/files#diff-5aa43563f6179c15a65f310470755492R263

**Comment by Qwin** [comment]
Awesome thanks guys!
