### ISSUE TITLE
Wrong ViewModel data in cached Fragment

### ISSUE THREAD

**Issue by nasibu** [MvvmCross/MvvmCross#1986]
I notice an issue while using the new ```NavigationService```. When I navigate multiple times to a ```ViewModel``` with different parameters, the ```Fragment``` shows every time the values of the first call.

### Steps to reproduce

1. First call: 
```c#
await NavigationService.Navigate<ViewModel, Parameter, Result>(new Parameter{ Text = "one" })
```
2. In ```ViewModel``` the ```Initialize``` method will save the parameter in ```ViewModel``` property.

3. In ```Fragement``` the ```OnCreateView``` method will use the value of the Property from the ```ViewModel```.

4. Next call from other location:
```c#
await NavigationService.Navigate<ViewModel, Parameter, Result>(new Parameter{ Text = "two" })
```

### Expected behavior
The ```Fragment``` shows the text "two".

### Actual behavior
The ```Fragment``` shows the text "one".

### Workaround
While debugging I can get the correct value ("two") of the ```ViewModel``` in the ```OnCreateView``` of the ```Fragment``` on second call. But on the Screen I see "one" from the first call. I think it has to do with retrieving thinks from cache, because when I change the ```ShowFragment``` method of the ```Activity``` to replace every ```Fragment```:
```c#
protected override void ShowFragment(string tag, int contentId, Bundle bundle, bool forceAddToBackStack = false, bool forceReplaceFragment = false)
{
	base.ShowFragment(tag, contentId, bundle, forceAddToBackStack, true);
}
```
Then "two" is shown after the second call.

### Configuration

**Version:** 5.0.3

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
I think this is not related to the new `NavigationService`, but to the Fragments Presenter. It looks similar to #1264. Can you try the workaround I've mentioned there? @nasibu

**Comment by nasibu** [comment]
My workaround does exactly the same as yours in #1264. It sets `FragmentReplaceMode` to `ReplaceFragmentAndViewModel` in `ShowFragment` method. The issue is resolved, but then there is no caching of Fragments.

I used before the old `ShowViewModel` method with anonymous class for paramters and old `Init` method. That worked perfectly. Therefore I think it has to do with the new `NavigationService`.
