### ISSUE TITLE
Fused Location Plugin watcher does not start - Android.Gms.Common.Zzc.IsGooglePlayServicesAvailable' not found

### ISSUE THREAD

**Issue by ThisNetWorks** [MvvmCross/MvvmCross#1989]
After upgrading to Mvvmcross 5.0.3, support libraries 25.3.1, & Xamarin.GooglePlayServices.Location 42.1021.1 my fused location watcher doesn't start with the error Android.Gms.Common.Zzc.IsGooglePlayServicesAvailable' not found

I am successfully using this method in other parts of my app, where I check for google maps etc and install play services if needed.

### Steps to reproduce

```
if (!_watcher.Started) {
	var dispatcher = Mvx.Resolve<IMvxMainThreadDispatcher>();
	dispatcher.RequestMainThreadAction(() => {
        try
        {
            _watcher.Start(locationOptions, OnLocation, OnError);
        } catch (Exception e){
            Logr.Error("Location Watcher could not start e:{0}", e.Message);
        }
	});
}
```

### Expected behavior
Location Watcher should start

### Actual behavior
Location watcher doesn't start with exception Android.Gms.Common.Zzc.IsGooglePlayServicesAvailable' not found

### Configuration

**Version:** 
Mvvmcross 5.0.3
Support libraries 25.3.1
Xamarin.GooglePlayServices.Location 42.1021.1
Device: Lollipop Xamarin Android Emulator (also tested on Moto G4 running Nougat

**Platform:** 
Android

**Comment by Cheesebaron** [comment]
Your play services is newer than compiled against. This will be updated to 42.1021.1 in MvvmCross 5.0.4

In 5.0.3 you need to match 42.1001
