### ISSUE TITLE
iOS - MvxIosViewPresenter throwing KeyNotFoundException via Show()

### ISSUE THREAD

**Issue by Plac3hold3r** [MvvmCross/MvvmCross#1991]
A regression bug causing `KeyNotFoundException` to always be thrown during the `Show` method call on the `MvxIosViewPresenter`. 

Related to https://github.com/MvvmCross/MvvmCross/commit/d4d1d804b2160f212700e58e985cfe5e3df66de5#commitcomment-22742635

### Steps to reproduce

1. Run the [TestProjects/Playground/Playground.iOS](https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Playground/Playground.iOS) app in the repo

2. App crash with KeyNotFoundException 

### Expected behavior
Navigate to respective ViewModel's corresponding view controller

### Actual behavior
KeyNotFoundException 

> The type MvxRootPresentationAttribute is not configured in the presenter dictionary

[Source code line for exception](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/iOS/iOS/Views/Presenters/MvxIosViewPresenter.cs#L97).

### Configuration

**Version:** 5.0.4

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by Plac3hold3r** [comment]
I will submit a PR with a fix soon.

**Comment by Cheesebaron** [comment]
Fix has been merged. Thanks!
