### ISSUE TITLE
SetTitleAndTabBarItem not called on 5.0.5

### ISSUE THREAD

**Issue by luigisaggese** [MvvmCross/MvvmCross#1995]
After upgrade from MvvmCross 5.0.3 to 5.0.5, SetTitleAndTabBarItem method of MvxTabBarViewController is not called

### Steps to reproduce

1.  Use MvxTabBarViewController and SetTitleAndTabBarItem on version  5.0.3

2. Upgrade to 5.0.5

3.Use MvxTabBarViewController and SetTitleAndTabBarItem on version  5.0.5

### Expected behavior
SetTitleAndTabBarItem is called for version 5.0.5

### Actual behavior
SetTitleAndTabBarItem is NOT called for version 5.0.5

### Configuration

**Version:** 5.0.5

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
We added a selected state for that: `protected virtual void SetTitleAndTabBarItem(UIViewController viewController, string title, string iconName, string selectedIconName = null)`which is called now. See https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/iOS/iOS/Views/MvxTabBarViewController.cs#L49

Maybe we should either provide backwards support for this, or remove the method at all.

**Comment by Cheesebaron** [comment]
This can't be scheduled for 5.0.6 if we are going to change the signature of the methods, since it would be a breaking change.

**Comment by nmilcoff** [comment]
Maybe making a method that takes the entire attribute makes more sense... otherwise each time a property is added to the tab attribute we will break every app by changing the method signature

**Comment by Cheesebaron** [comment]
@nmilcoff that would be the better solution, this way the signature stays the same for the method, but the attribute can be extended.

**Comment by mvanbeusekom** [comment]
@Cheesebaron and @nmilcoff how will you handle multilingual applications where the tab titles need to be presented in multiple languages? This is a challenge with the attributes in the current solution I ran into several times.

**Comment by nmilcoff** [comment]
@mvanbeusekom I use resx, therefore a possible solution for me is to set the keys in the attribute and get the resources from the ResourceManager later by overriding [this method](https://github.com/MvvmCross/MvvmCross/blob/c2090b9be084348ce96560c4e66ea7d2bcdc1ca3/TestProjects/Playground/Playground.iOS/Views/TabsRootView.cs#L30)

**Comment by mvanbeusekom** [comment]
True but this won't work for people using the MvxJsonLocalisation plugin and the binding mechanism

**Comment by mvanbeusekom** [comment]
Why not change things around a bit and have the `SetTitleAndTabBarItem(UIViewController viewController, string title, string iconName, string selectedIconName = null)` call the `SetTitleAndTabBarItem(UIViewController viewController, string title, string iconName)` and after that handle the `selectedIconName` situation. 

This way we don't change the signature and don't break existing code. We can keep on doing this with other parameters as well (it will stay backwards compatible). And we can quickly release it in 5.0.6

**Comment by Cheesebaron** [comment]
The overload hides the method without the `selectedIconName`, not pretty at all.

**Comment by mvanbeusekom** [comment]
Not is you don't make the `selectIconName` parameter optional (as done in the related PR)
