### ISSUE TITLE
UWP support for StarterPack package

### ISSUE THREAD

**Issue by Shtong** [MvvmCross/MvvmCross#1999]
### Steps to reproduce

1. Create a new projet of type "Cross Platform App (Xamarin)"

2. In the project creation options, leave everything at the default values (Blank App, Xamarin.Forms technology, Shared Project, no cloud)

3. After the projects have been created, install the MvvmCross.StarterPack in the Universal Windows project

### Expected behavior
A few files should get created in the project (like a setup.cs for example)

### Actual behavior
A new reference is added to the project, but everything else is left unchanged

### Configuration

**Version:** 5.0.5
**Visual Studio:** 15.2
**Xamarin:** 4.5.0.486

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [x] UWP

**Comment by nmilcoff** [comment]
@willsb can you validate UWP is not currently supported by StarterPack? The platform is Forms though, and is marked as done in #1659

**Comment by willsb** [comment]
@nmilcoff UWP is not supported. The mark is for WPF projects, not UWP. The reason is my lack of Windows machine :/
