### ISSUE TITLE
Inline converter creation in WPF

### ISSUE THREAD

**Issue by mgochmuradov** [MvvmCross/MvvmCross#2000]
If `MvvmCross.Platform.Wpf.Converters.MvxNativeValueConverter` was inherited from `MarkupExtension` and simply implement `ProvideValue` as:
```cs
    public override object ProvideValue(IServiceProvider serviceProvider)
    {
        return this;
    }
```
Converters could be created inline in XAML:
```xaml
<Some Property="{Binding Tags, Converter={local:TokenConverter}}"/>
```

**Comment by nmilcoff** [comment]
@mgochmuradov Sounds fair as far as it doesn't introduce breaking changes. Could you create a PR for this?

**Comment by nmilcoff** [comment]
Doing some research, it seems that by using the converters this way an instance is created for each Converter={} clause. I think that's ok only if the other way of using it remains the same.
