### ISSUE TITLE
ViewModel Life cycle events not called properly when bound to an MvxActivity

### ISSUE THREAD

**Issue by cegio** [MvvmCross/MvvmCross#2001]
Hello, I’ve realised that the new life cycle events weren’t called properly on a ViewModel bound to an MvxActivity, i.e: Disappeared and Disappearing are called only if the Activity is destroyed but not if you navigate to another ViewModel/Activity, and Appeared and Appearing are called only when the Activity is newly created, and not if you go back to a previously displayed one. The expected behavior seems fixed if we call ViewModel.Appearing() from OnStart(), Appeared() from OnResume(), Disappearing() from OnPause() and Disappeared() from OnStop, as it’s done in MvxFragment. Is there any reason why it’s not implemented the same way in MvxActivity ?

### Steps to reproduce
repro git : [https://github.com/cegio/Mvx5VMLiveCycleOnMvxActivity](https://github.com/cegio/Mvx5VMLiveCycleOnMvxActivity)

1. Start the repro project and click on the button "Go To Second View" only events from the SecondViewModels are fired, the MainViewModel.Disappearing() and Disappeared() are not fired. On Closing SecondViewModel(), MainViewModel.Appearing() and Appeared() are not fired.

### Expected behavior
MainViewModel.Disappearing and Disappeared should be fired when navigating to SecondViewModel. MainViewModel.Appearing and Appeared should be fired when navigating on ClosingSecondViewModel

### Actual behavior
No MainViewModel life cycle events are fired when 

### Temporary solution
If these events are fired from MvxActivity.OnStart(), OnResume(), OnPause(), OnStop() like in the commented code in ActivityBase in the repro project, the behavior seems correct.

### Configuration

**Version:** 5.0.5

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by orzech85** [comment]
That's right. Current implementation is suitable for fragments - not for Activities. I am just working on PR.
