### ISSUE TITLE
Nuget reference from Newtonsoft 10.x introduced in 5.0.4 creates a dependency for .NET Standard Library

### ISSUE THREAD

**Issue by marcpaes** [MvvmCross/MvvmCross#2008]
### Steps to reproduce
1. Update to 5.0.4 or 5.0.5 on a PCL based project

### Expected behavior
Just a minor update, minor changes :)

### Actual behavior
Lots of dll's are included in your project.

This behavior (of newtonsoft update) was reported too on:

https://forums.xamarin.com/discussion/91208/number-of-packages-just-exploded-with-latest-newtonsoft-json-package-update
https://github.com/JamesNK/Newtonsoft.Json/issues/1252#issuecomment-288943725

If possible, revert the minimum version to 9.0.1 can save some headaches!

Thanks in advance

**Version:** 5.0.4, 5.0.5

**Platform:** 
- [X] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
You fail to mention why this is an issue at all. Please elaborate.

**Comment by marcpaes** [comment]
The issue is the 30+ references included in the project.

Tested now with a blank solution:

References before including MvvmCross
<img width="370" alt="before" src="https://user-images.githubusercontent.com/8385472/27758645-2ea8ca9a-5df0-11e7-9581-597e16eb9c2d.png">

References after including MvvmCross with JSON Plugin
![after](https://user-images.githubusercontent.com/8385472/27758646-35acdc6e-5df0-11e7-87bd-9a63ccccf958.png)

**Comment by mvanbeusekom** [comment]
So there are a lot of references, but why is that a problem?

**Comment by Cheesebaron** [comment]
Those are NET Standard references, nothing to be worried about. This is the future of .NET and you will see these in almost any NuGet package you reference from now on.

I still see no valid reason to downgrade, fact is, MvvmCross builds against latest Newtonsoft.Json, laxing the dependency will just give you headaches in another way.

**Comment by dagostinelli** [comment]
It's a problem because now it's hard to curate our projects.  I would have been better if there were a single line called ".NET Standard", but there isn't.  This is an opportunity NOT to accept an upgrade on that basis until it is fixed.  Closing this isn't helping the problem.

**Comment by Cheesebaron** [comment]
@dagostinelli you are complaining about this to the wrong people. .NET Standard is not something _we_ make, this responsibility lays elsewhere.

We are moving forward, so should you. There are solutions to your problem such as Paket or using the new csproj files and dependencies.
