### ISSUE TITLE
iOS - public override async Task Initialize() throws exception on launch

### ISSUE THREAD

**Issue by benhysell** [MvvmCross/MvvmCross#2009]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
> https://github.com/benhysell/XamarinSidebarSample
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Launch App

2. Exception thrown - Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

3.

### Expected behavior
Tell us what should happen - Application should launch

### Actual behavior
Tell us what happens instead - Exception Thrown

### Configuration

**Version:** 5.0.5

**Platform:** 
- [ X] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

Modified the XamarinSidebarSample sample to show error I was seeing in my own application.  Changed AppStart.cs to use IMvxNavigationService to launch CenterPanelViewModel.  In CenterPanelViewModel I added
```
public override async Task Initialize()
{
            //simulate database lookup
            await Task.Delay(5000);
}
```

Exception is thrown:
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

This is new behavior...I just upgraded from 5.0.3 and started seeing this.

**Comment by Cheesebaron** [comment]
Isn't this expected? iOS doesn't allow you to spend too much time before a root VC needs to be shown or app is nuked.

**Comment by martijn00** [comment]
The problem is in Appstart: https://github.com/benhysell/XamarinSidebarSample/blob/master/MvvmCross.iOS.Support.Core/AppStart.cs#L23

You don't block navigation here, so it will continue before the actual screen was shown.

**Comment by benhysell** [comment]
Tried @martijn00's suggestion...worked as expected.

At first blush the solution, 'didn't feel right'...I had pictures of Stephen Cleary yelling at me for committing  an async/await sin, [https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).

Till I read, [https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html](https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html), basically, if you have to break async/await, break it with a ```GetAwaiter().GetResult()```.

I'm ok with closing this, unless there is more discussion to be had...i.e. is there a better method to do async code in an initialize on app start / is there an improvement to be made to iOS?

**Comment by benhysell** [comment]
Failed to actually try this on the device...solution works in the simulator...hangs when running on the device.

My example on github, https://github.com/benhysell/XamarinSidebarSample, is updated with the latest that hangs when running in debug on device.

**Comment by michelmob** [comment]
@martijn00  What happens if I call from RegisterNavigationServiceAppStart<T>() and my first view Model use it? 

I'm trying to do it and my application crashes. I'm trying to instantiate my abstraction of Http Cliente and when I call

 public override async Task Initialize()
        {
            await base.Initialize();

            var res = await accountService.LogOn("ta", "123", "123");
        }
my application do not respond and crash.

**Comment by michelmob** [comment]
@nickrandolph, forget about the logon method, we can change it for an GetSomethingAsync().

I created the full explanation here: https://stackoverflow.com/q/49824971/319206
