### ISSUE TITLE
When i try to install MvvmCross.Droid.Support.Fragment i am getting the following error.

### ISSUE THREAD

**Issue by Tharan** [MvvmCross/MvvmCross#2013]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. when I try to install MvvmCross.Droid.Support.Fragment. I am getting the following error message

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'MvvmCross.Droid.Shared 5.0.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Please advise
Tharan Ratnam	

2.

3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
Profile 111 contains silverlight. It is _not_ supported by MvvmCross. Change your PCL profile or use NET Standard.

**Comment by Tharan** [comment]
Hi


I am not sure i can reply for this email.


I am having the issue when i create the PCL project. it automatically create the profile 111. See the below screen shot. I did not choose any silverlight. Please advise or let me know how can i change the profile


[cid:39108db5-9385-4c23-8c78-1a6632029021]


Regards
Tharan Ratnam

________________________________

**Comment by Plac3hold3r** [comment]
@Tharan you should not need to install `MvvmCross.Droid.Support.Fragment` or `MvvmCross.Droid.Shared` in to your PCL. These nuget packages are only intended and supported when used in an Android project (i.e. the a platform project). Any package with `Droid` in its name is only intend for inclusion in an Android/Droid platform project
