### ISSUE TITLE
MvvmCross plugin PictureChooser 5.0.5 - profile 259

### ISSUE THREAD

**Issue by mac138** [MvvmCross/MvvmCross#2017]
### Steps to reproduce

1. Click Manage NuGet packages for solution

2. Choose Updates and select MvvmCross.Plugin.PictureChooser and click Install v5.0.5 for all projects

### Expected behavior
Update PictureChooser plugin from 4.4.0 to 5.0.5

### Actual behavior
Could not install package 'MvvmCross.Plugin.PictureChooser 5.0.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Configuration

Profile 259

**Platform:** 
- [x] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

**Comment by mac138** [comment]
I have problem with image rotation on some devices. 
When I take picture with camera picture is properly located in ImageView 
but when I select exaclty same photo which I take before from gallery, the photo is rotated in ImageView.

This problem occurs on 4.4.0 PictureChooser

**Comment by Cheesebaron** [comment]
Profile 259 contains WP Silverlight. This is not supported by MvvmCross. Choose a PCL profile without any Silverlight. Profile 7 is a good choice.
