### ISSUE TITLE
Exception being thrown on fresh app start, OnCreate inaccessible?

### ISSUE THREAD

**Issue by lanceking** [MvvmCross/MvvmCross#2032]
"System.MethodAccessException: Method `MvvmCross.Droid.Support.V7.AppCompat.EventSource.MvxEventSourceAppCompatActivity:OnCreate (Android.OS.Bundle)' is inaccessible from method `Android.Support.V4.App.FragmentActivity:OnCreate (Android.OS.Bundle)'"

I'm getting this error when my app attempts to load the first activity (login screen) from a fresh build/start. I've been building/deploying fine until today with this same project. I seem to remember this error happening once before (last week sometime), but cannot remember what I did to remedy it.

Any assistance / guidance / ideas would be greatly appreciated.

I've tried:
-clean / rebuild / re-deploy (in debug mode)
-rolling back the entire project to previous builds which I know worked (Those builds now throw this same error too)
-resetting my computer, and device I'm deploying to (I've had issues with obj and bin getting locked up and figured a restart might fix it)
-deleting obj and bin folders / clean / rebuild / re-deploy (in debug mode)

Here's the exception being thrown in the stacktrace:

I/MonoDroid(  728): UNHANDLED EXCEPTION:
I/MonoDroid(  728): System.MethodAccessException: Method `MvvmCross.Droid.Support.V7.AppCompat.EventSource.MvxEventSourceAppCompatActivity:OnCreate (Android.OS.Bundle)' is inaccessible from method `Android.Support.V4.App.FragmentActivity:OnCreate (Android.OS.Bundle)'
I/MonoDroid(  728): 
I/MonoDroid(  728):   at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_throw_method_access (intptr,intptr)
I/MonoDroid(  728):   at MvvmCross.Droid.Support.V7.AppCompat.EventSource.MvxEventSourceAppCompatActivity.OnCreate (Android.OS.Bundle bundle) [0x0000d] in C:\projects\mvvmcross\MvvmCross-AndroidSupport\MvvmCross.Droid.Support.V7.AppCompat\EventSource\MvxEventSourceAppCompatActivity.cs:34 
I/MonoDroid(  728):   at MyProject.Droid.Activities.BaseActivity`1[TViewModel].OnCreate (Android.OS.Bundle bundle) [0x0000e] in D:\VS\MyProject\MyProject\MyProject.Android\Activities\BaseActivity.cs:36 
I/MonoDroid(  728):   at MyProject.Droid.Activities.Login.OnCreate (Android.OS.Bundle savedInstanceState) [0x00001] in D:\VS\MyProject\MyProject\MyProject.Android\Activities\LoginActivity.cs:46 
I/MonoDroid(  728):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <27c17fe440cf491ba8255bcefade6e02>:0 
I/MonoDroid(  728):   at (wrapper dynamic-method) System.Object:777defc4-4c26-4569-b9b2-a193aba4d5e7 (intptr,intptr,intptr)
W/art     (  728): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
D/Mono    (  728): DllImport searching in: '__Internal' ('(null)').
D/Mono    (  728): Searching for 'java_interop_jnienv_throw'.
D/Mono    (  728): Probing 'java_interop_jnienv_throw'.
D/Mono    (  728): Found as 'java_interop_jnienv_throw'.
E/mono    (  728): 
E/mono    (  728): Unhandled Exception:
E/mono    (  728): System.MethodAccessException: Method `MvvmCross.Droid.Support.V7.AppCompat.EventSource.MvxEventSourceAppCompatActivity:OnCreate (Android.OS.Bundle)' is inaccessible from method `Android.Support.V4.App.FragmentActivity:OnCreate (Android.OS.Bundle)'
E/mono    (  728): 
E/mono-rt (  728): [ERROR] FATAL UNHANDLED EXCEPTION: System.MethodAccessException: Method `MvvmCross.Droid.Support.V7.AppCompat.EventSource.MvxEventSourceAppCompatActivity:OnCreate (Android.OS.Bundle)' is inaccessible from method `Android.Support.V4.App.FragmentActivity:OnCreate (Android.OS.Bundle)'
E/mono-rt (  728): 
I/TMSDISP (  728): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Enter
I/TMSDISP (  728): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Enter2
I/TMSDISP (  728): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - mSource2
I/TMSDISP (  728): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Exit

I have not tried building an example project to see if it occurs there, I will try that now, and post it if it can be reproduced.

If there's anything else I can provide let me know.

**Version:** 5.0.5

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by lanceking** [comment]
And with no significant changes having been made... the error has disappeared just as strangely as it began.

I had read somewhere that a user had luck eliminating build/deploy related errors by completely *shutting down* as opposed to just restarting their computer, so I tried that and it worked.

Full series of steps I took to fix the issue:
- clean solution
- subsequently clean each project individually (almost literally beating my head against this as you can see)
- delete obj and bin folders from all projects that are in question
- deleted the .vs folder in the solution root directory (this was a new step, I had not previously done this.. maybe this is what fixed it?)
- completely SHUT DOWN (not just restart) the computer
- completely shut down the android device, not just restart
- turn both back on
- once the device was done starting back up, I uninstalled the app in question
- rebuild / redeploy
- cross fingers / pray / hail Mary / whatever suits your fancy

This all did the trick. Might be useful to leave the issue up for other's reference, but aside from that, the issue can be closed.

Thanks for the work guys. Appreciate all you do.

**Comment by nmilcoff** [comment]
Good news that it worked eventually! Closing this to keep things organized.
