### ISSUE TITLE
mvx:Warning:  0.25 No sidemenu found. To use a sidemenu decorate the viewcontroller class with the 'MvxPanelPresentationAttribute' class and set the panel to 'Left' or 'Right'.

### ISSUE THREAD

**Issue by kirillgorbushko** [MvvmCross/MvvmCross#2034]
Tying to implement side menu for my app, but got warning in console like:

> mvx:Warning:  0.25 No sidemenu found. To use a sidemenu decorate the viewcontroller class with the 'MvxPanelPresentationAttribute' class and set the panel to 'Left' or 'Right'.

as result menu not work

### Steps to reproduce

1.Create base class for menu (from sample)

>
>          public class BaseMenuViewController<T> : MvxViewController<T>, IMvxSidebarMenu where T : class, IMvxViewModel
>         {
>         public virtual UIImage MenuButtonImage => UIImage.FromBundle("threelines");
> 
>         public virtual bool AnimateMenu => true;
>         public virtual float DarkOverlayAlpha => 0;
>         public virtual bool HasDarkOverlay => false;
>         public virtual bool HasShadowing => true;
>         public virtual bool DisablePanGesture => false;
>         public virtual bool ReopenOnRotate => true;
> 
>         private int MaxMenuWidth = 300;
>         private int MinSpaceRightOfTheMenu = 55;
> 
>         public int MenuWidth => UserInterfaceIdiomIsPhone ?
>         int.Parse(UIScreen.MainScreen.Bounds.Width.ToString()) - MinSpaceRightOfTheMenu : MaxMenuWidth;
> 
>         private bool UserInterfaceIdiomIsPhone
>         {
>             get { return UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone; }
>         }
> 
>         public virtual void MenuWillOpen()
>         {
>         }
> 
>         public virtual void MenuDidOpen()
>         {
>         }
> 
>         public virtual void MenuWillClose()
>         {
>         }
> 
>         public virtual void MenuDidClose()
>         {
>         }
>     }

2. Implement VisibleView (First one that will be visible)

>
>     [MvxSidebarPresentation(MvxPanelEnum.Center, MvxPanelHintType.ResetRoot, true)]
>     public partial class ContentViewController : BaseViewController<ContentViewModel>
>     {
>         public ContentViewController()
>         : base("ContentViewController", null)
>         {
>         }
> 
>         public override void ViewDidLoad()
>         {
>             base.ViewDidLoad();
> 
>             View.BackgroundColor = UIColor.Purple;
>             this.ViewModel.Show<MenuViewModel>();
>         }
>     }

3. Implement MenuElementViewController (SideMenu)

>
>     [Register("MenuViewController")]
>     [MvxSidebarPresentation(MvxPanelEnum.Left, MvxPanelHintType.PushPanel, false)]
>     public class MenuViewController : BaseMenuViewController<MenuViewModel>
>     {
> 
>         public override void ViewDidLoad()
>         {
>             base.ViewDidLoad();
> 
>             this.View.BackgroundColor = UIColor.Red;
>         }
>     }

4. Add presenter for SideMenu in Setup

>
>         protected override IMvxIosViewPresenter CreatePresenter()
>         {
>             return new MvxSidebarPresenter((MvxApplicationDelegate)ApplicationDelegate, Window);
>         }

### Expected behavior
Should see controller from point 1 with burger button

### Actual behavior
Controller from point1 become visible but without burger button, 
Controller from point2 not initialized, 
Warning in console about missed decoration for class, but as u see they are present (also warnings deprecated and need to be updated - check source code - searching done for correct type, [but warning has old message](https://github.com/MvvmCross/MvvmCross/blob/releases/5.0.0/MvvmCross-iOSSupport/MvvmCross.iOS.Support.XamarinSidebar/Views/MvxSidebarViewController.cs) )

### Configuration
MvvmCross v 5.0.6

MvvmCross
MvvmCross.Core
MvvmCross.Binding
MvvmCross.iOS.Support
MvvmCross.iOS.Support.XamarinSidebar
MvvmCross.Platform
SidebarNavigation

**Version:** 5.x

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by kirillgorbushko** [comment]
Spend 2 days to figure out the reason - the issue related to detection and parsing decorator attributes. 

I have few projects that share codebase between each other, and due to some reason 

`    [MvxSidebarPresentation(MvxPanelEnum.Left, MvxPanelHintType.PushPanel, false)]
`
is not taken in to account if it placed in shared project but not in project itself. In same moment 

```
    [MvxSidebarPresentation(MvxPanelEnum.Center, MvxPanelHintType.ResetRoot, true)]
    [MvxSidebarPresentation(MvxPanelEnum.Center, MvxPanelHintType.ResetRoot, true, MvxSplitViewBehaviour.Master)]
    [MvxSidebarPresentation(MvxPanelEnum.Center, MvxPanelHintType.PushPanel, true, MvxSplitViewBehaviour.Detail)]
```

works as expected.
Workaround -> subclass shared menuClass (with `MvxPanelEnum.Left`) in each project where it should be used.

Not sure if this issue related to mvvmCross lib or to Xamarin.

**Comment by nmilcoff** [comment]
Are you subclassing the shared view in each project @kirillgorbushko? because the attribute is grabbed from the type, not base classes

**Comment by kirillgorbushko** [comment]
Before i add workaround i only subclass `BaseMenuViewController` ([same as here](https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/iOS-Support/XamarinSidebar/MvvmCross.iOS.Support.Sidebar/Views/BaseMenuViewController.cs)) and so without any decoration. 
Subclass was done in same project where `BaseMenuViewController` declared

**Comment by mvanbeusekom** [comment]
Yes the problem is that the Attribute is only detected when the type is directly part of the iOS assembly . In this case the type containing the attribute decoration was not part of the iOS assembly but instead part of a separate referenced assembly (which are not scanned automatically).

**Comment by kirillgorbushko** [comment]
@mvanbeusekom - but why attribute like

`[MvxSidebarPresentation(MvxPanelEnum.Center, MvxPanelHintType.PushPanel, true]
`
detected and recognized correctly, and as result i got my `MenuViewController` pushed from 

`[MvxSidebarPresentation(MvxPanelEnum.Center, MvxPanelHintType.ResetRoot, true]`

**Comment by kirillgorbushko** [comment]
is it possible to perform force scan for attribute decoration?

**Comment by mvanbeusekom** [comment]
Well this is a bit tricky, the sidebar menu views (marked with the `MvxPanelEnum.Left` or `MvxPanelEnum.Right`) are preloaded by the `MvxSidebarController`. So on initialization the sidebar controller actively scans for attributes set with these two values.

The other values are handled by the `MvxSidebarPresenter` when they are being navigated to. In these cases the presenter simply gets an instance of a `UIViewController` class (could be from any assembly) and checks if it has been decorated with the attribute. If so it will attache the preloaded menus to it. 

At the moment there is no way to manually trigger the scan or register the left or right sidebars with the '`MvxSidebarController`.

**Comment by kirillgorbushko** [comment]
@mvanbeusekom thanks for explanation
