### ISSUE TITLE
ViewModel's constructor is called twice when using NavigationService

### ISSUE THREAD

**Issue by biruto05** [MvvmCross/MvvmCross#2038]
### Steps to reproduce

1. Create a project and register custom AppStart.

```
public class App : MvxApplication
{
	public override void Initialize()
	{
		RegisterAppStart(new CustomAppStart());
	}
}
```
2. In Start method of CustomAppStart, navigate to LoadingViewModel using navigation service.

```
public class CustomAppStart : IMvxAppStart
{
	public void Start(object hint = null)
	{
		Mvx.Resolve<IMvxNavigationService>().Navigate<LoadingViewModel>();
	}
}
```
3. Observe that constructor of LoadingViewModel is called twice

### Expected behavior
LoadingViewModel's constructor should be only called once

### Actual behavior
LoadingViewModel's constructor is called once

### Configuration

**Version:** 5.0.6

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
I can't reproduce this. Please provide more details or a Github repo with a sample project.

**Comment by biruto05** [comment]
You are right.

This is actually #1880 Navigation Bug introduced in 5.0.1: View.OnCreate reinstantiates existing target ViewModel.

Thanks for closing the issue.
