### ISSUE TITLE
Navigation to tab bar models seems to be broken for MvvmCross/iOS 5.0.4 onwards

### ISSUE THREAD

**Issue by indexless** [MvvmCross/MvvmCross#2046]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Download Playground sample from https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Playground

2. In ./Playground.Core/ViewModels/TabsRootViewModel.cs, replace command's value with

            new MvxAsyncCommand(() =>
            {
                var nav = Mvx.Resolve<IMvxNavigationService>();
                return Task.WhenAll(nav.Navigate<Tab1ViewModel>(),
                                    nav.Navigate<Tab2ViewModel>(),
                                    nav.Navigate<Tab3ViewModel>());
            });

(The command property's type should also become IMvxAsyncCommand.)

3. In  ./Playground.iOS/Views/TabsRootView.cs, replace

                ViewModel.ShowInitialViewModelsCommand.Execute(null);

with

                ViewModel.ShowInitialViewModelsCommand.ExecuteAsync(null);

4. For each tab view model ./Playground.Core/ViewModels/Tabs#ViewModel.cs declare Initialize() as

        public override Task Initialize() => Task.Delay(9000);
        public override Task Initialize() => Task.Delay(6000);
        public override Task Initialize() => Task.Delay(3000);

for tab view model 1, 2, 3, respectively. Build, run, and select Tabs navigation.

### Expected behavior
All three tabs should appear instantly as they actually do when navigation is performed via deprecated ShowViewModel(). Also that was working for Mvvm from 5.0.0 to 5.0.3, but stopped in 5.0.4 onwards.

### Actual behavior
There is a black screen with no tabs for first three seconds, then third, second, and first (in that order) tabs appear with 3-second intervals.

### Configuration

**Version:** 5.0.4, 5.0.5, 5.0.6

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
Playground project is now updated and uses the new MvxNavigationService. Tabs do work as expected. Maybe the Initialize method with Task.Delays is what makes the issue appear?

**Comment by indexless** [comment]
Nice, thank you for update!

There are no problems because none of sample's Initialize() performs any long asynchronous task. But it looks as a bug (see #2071 for details), and it's reproduced just on the sample you've just updated.
