### ISSUE TITLE
Source for MvvmCross.Plugin.SQLitePCL

### ISSUE THREAD

**Issue by SSElliott** [MvvmCross/MvvmCross#2048]
Whilst I know this plugin (MvvmCross.Plugin.SQLitePCL) is deprecated and did not do a lot, I still have a project that uses it, and I cannot find any reference to the  package source in git hub. Whilst I intend to upgrade my project in the next release it would be useful to be able to look at the source code for this for maintenance purposes. Is it possible to make this available? 

Kind Regards

Steven

**Comment by Cheesebaron** [comment]
https://github.com/MvvmCross/MvvmCross/tree/b830ab5189323b2ff9059e08ba359b4956709889/MvvmCross-Plugins/SQLite-PCL
