### ISSUE TITLE
new LinkerPleaseInclude.cs.pp (ios) does not compile

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2054]
In the develop branch you can read the source:

https://github.com/MvvmCross/MvvmCross/blob/develop/nuspec/iOSContent/LinkerPleaseInclude.cs.pp

Lines 117-120:

        public void Include(MvvmCross.Core.Navigation.MvxNavigationService navigationService)
        {
            navigationService = new MvvmCross.Core.Navigation.MvxNavigationService()
        }

A ";" is missing at the end of the line.

Plus there is no constructor taking 0 argument for MvxNavigationService:

        public MvxNavigationService(IMvxNavigationCache navigationCache, IMvxViewModelLoader viewModelLoader)

**Comment by martijn00** [comment]
Will be fixed in https://github.com/MvvmCross/MvvmCross/pull/2053
