### ISSUE TITLE
Tabs within fragment breaks on navigation

### ISSUE THREAD

**Issue by DaneMackier** [MvvmCross/MvvmCross#2055]
Just some setup for the issue. My app has a MainView, which houses all the fragments. One of the fragments contain a TabLayout setup. When navigating away from the view that has the tab layout in it and coming back to it the pager is not in the same state it was left.

### Steps to reproduce

Download, build and run [this sample](https://github.com/DaneMackier/StackOverflow-FragmentTabNavigation)

1. Tap on the FAB to navigate to the OtherView

2. Press the hardware back button to go back to previous view

### Expected behavior
I expect the pager view to still have the contents as it was when I navigated away from it. Even when contained in a fragment instead of a MvxCachingFragmentCompatActivity.

### Actual behavior
The pager is empty. The items inside are not re-instantiated even though the same code that runs on the first run also runs when you navigate back to it.

### Configuration

**Version:** 5.1

**Platform:** 
- [x] Android

**Comment by DaneMackier** [comment]
So the issue was that I was using the FragmentManager of the Activity that was housing the fragment instead of the ChildFragmentManager within the fragment. 

Helpful information from [this answer](https://stackoverflow.com/a/16683004/1463174)

**Comment by nmilcoff** [comment]
👍 !
