### ISSUE TITLE
Problem with dynamic height table cells on iOS

### ISSUE THREAD

**Issue by fonix232** [MvvmCross/MvvmCross#2057]
### Steps to reproduce

1. Create a custom TableViewCell based on `MvxTableViewCell`, using XIB

2. Add a `Label` and matching constraints, set the `Label` to 0 lines, and word wrap (i.e. dynamic height). Add an outlet to the Label, and bind in the AwakeFromNib override

3. Use the label in an `MvxTableViewController`'s TableViewSource, where the `TableViewController` has the `TableView`'s `RowHeight` set to `UITableView.AutomaticDimension`.

### Expected behavior
The cells take the height of the text contained, using the constraints set between the Label and the cell rootview.

### Actual behavior
Cells are fixed single line, rest of the text is cut off. Automatic height does not work.

### Configuration

**Version:** 5.0.2-5.1.0

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

### Further info

This seems to be the same issue #1442 was supposed to fix. Same thing happens in custom cells where labels have height based on the text they contain, and these cells end up less than half their actual size (and even then, cell height resets to 44f for some reason, even though the content is being drawn over the other cells). Tried the fix from #1409, to no avail, cells are still rendered at 44f
height unless I override `GetHeightForRow` in the `TableViewSource` - which kills the automatic height settings.

**Comment by MarcBruins** [comment]
#1442 fixed the issue back then. There must be some changes in Mvx 5.0 that reintroduced it. Just to confirm you did set the TableView.Rowheight to UITableView.AutomaticDimension?

**Comment by fonix232** [comment]
@MarcBruins that was my exact idea.

Yes, `TableView.RowHeight` is set to `UITableView.AutomaticDimension`, as I said before. Adding the EstimatedRowHeight fixes the somewhat-static height cell items, but not the text cells.

**Comment by MarcBruins** [comment]
Mm ok, can you reproduce a minimal sample? I'm curious how this got re-introduced.

**Comment by Cheesebaron** [comment]
Are you using constraints or a fixed frame for this custom cell?

**Comment by fonix232** [comment]
@MarcBruins I'll try to cook up a sample this weekend.

@Cheesebaron Constraints. Coming from Android, that seemed to be the closest solution.

**Comment by wojtczakmat** [comment]
Hey, I've just got a similar problem. I have a custom `UITableViewCell` which is bound by `this.DelayBind()` in its ctor. On `GetOrCreateCellFor()` I just use `DequeueReusableCell()` like in samples and initialize constraints if the cell has just been created. The issue is that whilst cells laid out instantly with the view were shown correctly, next cells after the scrolling were laid out wrong (i.e. too short or too tall). The wrong cells were fixing themselves when I slowly moved them out and then back onto the screen (but with fast scrolling they were not able to layout correctly). The thing is that if I set data from the VM instantly in `GetOrCreateCellFor()`, then the problem disappears and everything works just fine.

MVVMCross version: 5.1.1

**Comment by fonix232** [comment]
@Cheesebaron  sorry for the late reply, I got no notification. I am using AutoLayout with constraints, dynamically sized cell.

I solved the issue in the meantime, solution was using the RegisterNib call instead of RegisterClass. If the Nib way is used, it works perfectly and DelayBind works just as well.

@wojtczakmat try to use the RegisterNib + DelayBind method, and also do not replace the GetorCreateCellFor() and the other cell creator calls. As long as you supply the proper cell identifier, it will do the rest (incl. the cell datacontext assignment).

**Comment by wojtczakmat** [comment]
@fonix232 Thanks for your interest. I don't use XIBs, I set up constraints with FluentLayout so I need to register classes. Do you think is won't work with programmatically set constraints?

**Comment by nmilcoff** [comment]
I'm using auto-sized, programatically created cells in many apps without issues (I use RegisterClass). A reproducible sample will definitely help us here

**Comment by fonix232** [comment]
The case where this issue happens is when you use XIBs for designing the UI of your cells, and backing code for binding, etc. - if you use RegisterClass then, the flow is different and for some reason the bindings will never work. It might be related to the bindings running BEFORE the XIB is loaded and inflated, thus before populating the outlets with actual values. Measurement might be ran before either the outlets or the datacontext is set, resulting in a nice measurement issue (all labels are nulled, thus zero height, resulting in the exact issue I was having).

So this ticket is only relevant to those who work from XIBs and registered them as cells from Class, not from Nib.

**Comment by nmilcoff** [comment]
I hit this issue on an app that uses xibs for TableView cells. 

So far I've discovered:
- Adding a call to `LayoutIfNeeded();` at the end of the `DelayBind` action block makes the wrong behavior dissapear.
- Adding a call to `cell.LayoutIfNeeded();` inside the TableViewSource.GetOrCreateCellFor method also makes the issue dissapear.

I'll open a PR fixing this.
