### ISSUE TITLE
Cleanup the samples

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#2060]
We've got some great samples in https://github.com/MvvmCross/MvvmCross-Samples and https://github.com/MvvmCross/MvvmCross-Samples/tree/master/OldSamples

Most of them are not up-to-date, so we want to work on fixing them! The common tasks that need to be done:

- Remove WindowsPhone 7 and 8.x
- Remove usage of local dll's, just use nugets
- Update namespaces
- Update LinkerPleaseInclude.cs
- Use the new NavigationService
- General code cleanup
- Make code improvements
- Make sure the samples compile and run on emulator

Here is a list with projects:
- [x] StarWarsSample
- [ ] XPlatformMenus
- [ ] ApiExamples
- [ ] AutoViewExamples
- [ ] Babel
- [ ] DailyDilbert
- [ ] FractalGen
- [ ] InternetMinute (@senorincognito)
- [ ] PictureTaking (@c-lamont)
- [ ] TipCalc (@gdblack)
- [ ] ValueConversion
- [x] WorkingWithCollections (@b099l3 & @tomcurran)
- [ ] BestSellers
- [ ] CirriousConference
- [ ] CompositeControl
- [ ] CrossLight
- [ ] CustomBinding
- [ ] CustomerManagement
- [ ] DialogExamples
- [ ] FirstDemo
- [ ] FirstDemo.Core
- [ ] FirstDemo.Mac
- [ ] Fragments (@daniel-varela)
- [ ] GoodVibrations
- [ ] MonoTouchCellTutorial
- [ ] MoreControls
- [ ] MvxPageDemo
- [ ] MvxPageDemo.Shared
- [ ] MvxPageDemo.Touch
- [ ] Navigation
- [ ] QuickLayout
- [ ] Soba
- [ ] Soba.Core
- [ ] Soba.XamMac.Unified
- [ ] Tutorial
- [ ] TwitterSearch

Some of those need to be consolidated in 1 folder.

**Comment by nmilcoff** [comment]
It would be also nice to have a macOS / UWP version of StarWarsSample. Planned layouts can be found [here](https://github.com/MvvmCross/MvvmCross-Samples/tree/master/StarWarsSample/Artwork)

**Comment by kiliman** [comment]
I'm interested in updating the sample apps for the Summer Hackfest.

**Comment by VenkatsQuest** [comment]
I'm interested in updating the sample apps for the Summer Hackfest @martijn00. 
- Kindly let me know the procedure for the same 
On another note , this link is not working [https://www.mvvmcross.com/summer-hackfest-2017]

**Comment by VenkatsQuest** [comment]
Hello @martijn00 
Inside soba folder itself we've Soba.Core and Soba.XamMac.Unified , I've already cleaned this solution and submitted a pull request for this.
Do you still want to maintain Soba.Core and Soba.XamMac.Unified outside as well ? if not needed , can you just delete those projects ?

Thanks much.

**Comment by mellson** [comment]
I am up for updating some samples during the Summer Hackfest. I'd prefer to do mac samples.

**Comment by Cheesebaron** [comment]
@VenkatsQuest if they are duplicated, just delete them. Also if you could remove the `Unified` suffix that would be great.

Hey @mellson you are very welcome to grab some of the samples and bring them up to speed and improve etc.

I think the easiest way to coordinate here, is when someone starts working on one of the samples, they write a comment in here which one they are working on. Ping @MvvmCross/core if you have any issues or questions or join us on [Slack](https://xamarinchat.herokuapp.com)

**Comment by VenkatsQuest** [comment]
@Cheesebaron I've already deleted as per my discussions with @martijn00 
I really didn't get your comment related to Unified suffix , can you please be more elaborate on the same ? Thanks much.

**Comment by Cheesebaron** [comment]
.Unified just remove that. We don't live in a world with Unified and Non-Unified MacOS/iOS projects anymore.

**Comment by VenkatsQuest** [comment]
Done for Soba project , will do it for the upcoming projects if any @Cheesebaron

**Comment by Vertygo** [comment]
I would like to contribute to this project for the Summer Hackfest. I would like to take some of windows samples.

**Comment by b099l3** [comment]
I would like to update the WorkingWithCollections, started working on it with the MvxExpandableTableViewSource and do the documentation on this too.

**Comment by Cheesebaron** [comment]
@Vertygo that would be most excellent, if you already know which projects you want to contribute to please list them. If you don't know and you want us to find some you can work on we can also arrange that.

@b099l3 I've written your name on the WorkingWithCollections project in the opening post. If you have any questions or run into any issues, don't hesitate to contact us.

**Comment by ehuna** [comment]
Do we have clean Xamarin Forms samples?  I've looked and contributed to https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Forms - but I'm not sure if these are samples or tests projects.

In either case, I would like to contribute to Xamarin Forms samples for the Hackfest - either cleaning up TestProjects/Forms or creating new sample projects for iOS, Android, UWP, and Mac.  

As time permits, I'd like to also work on the documentation for these samples - the goal to make it really easy for someone new to MvvmCross to compile and run the Xamarin Form samples.

**Comment by gdblack** [comment]
I'm also interested in helping clean up the samples during the summer hack_fest!

**Comment by gdblack** [comment]
Dibs on tip calc

**Comment by Prandtl** [comment]
Working on ValueConversion sample

**Comment by kiliman** [comment]
Are there any guidelines for the samples?

What should be the Minimum Target Framework for Android and iOS? One of the samples has iOS 6 as Target and the simulator complained that the app would not be supported. I bumped it to 9 and that seems to have satisfied iOS. For Android, should we continue to use API 15 (Ice Cream Sandwich)?

I upgraded the iOS sample, and it updated first to .NETStandard1.6.1, then it prompted to update to .NETStandard2.0.

Can we move all samples to .NETStandard2.0? And if so, does that mean everyone needs to be on latest Visual Studio 15.3?

**Comment by Cheesebaron** [comment]
What you have proposed seems fairly reasonable @kiliman 

- Android Projects Min target API 15
- .NET Standard 2.0 for the core projects (this will require target fallback and the .NET Portability Support NuGet)
- All MvvmCross references come from NuGet

**Comment by b099l3** [comment]
Working on WorkingWithCollections

**Comment by daniel-varela** [comment]
I'm working on the Fragments Sample.

**Comment by senorincognito** [comment]
I would like to start with a smaller sample to get a feel for the structure. The InternetMinute sample looks easy enough for that.

**Comment by c-lamont** [comment]
I'll take a look at PictureTaking.

**Comment by b099l3** [comment]
Im going to start ApiExamples

**Comment by Qonstrukt** [comment]
I'll do AutoViewExamples

**Comment by tomcurran** [comment]
I'm going to do ValueConversion. I don't have access to a windows environment so won't be able to updated the WindowsStore project.

**Comment by martijn00** [comment]
@tomcurran WindowsStore and Windows 8.x can sort of be removed because we don't support it anymore.

**Comment by Qonstrukt** [comment]
I've removed the AutoView example, moving to Babel now.
