### ISSUE TITLE
Compilation issues with MvvmCross.StarterPack 5.1.0

### ISSUE THREAD

**Issue by catchnaresh** [MvvmCross/MvvmCross#2063]
Hello all,

MvvmCross.StarterPack 5.1.0 is not compiling. 

'LinkerPleaseInclude' has compilation issues in both iOS and Android.

### Steps to reproduce

1. Install MvvmCross.StarterPack 5.1.0 using Nuget

2. Compile the project

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
This is fixed in 5.1.1 in https://github.com/MvvmCross/MvvmCross/pull/2053

**Comment by catchnaresh** [comment]
thanks @martijn00
