### ISSUE TITLE
Is it possible to switch between presenters

### ISSUE THREAD

**Issue by kciesiel** [MvvmCross/MvvmCross#2065]
I would like to create app where I started from LoginViewModel. After that I need to
redirect into MasterDetailPage and change Presenter to MvxFormsDroidMasterDetailPagePresenter to
display burger menu correctly.
Is it possible? Many ideas?  Thanks.

**Platform:** 
-  iOS
-  Android

**Comment by nmilcoff** [comment]
Presenters are not meant to be changed during the app execution. You should consider a making a custom ViewPresenter if any of the provided by MvvmCross fit your app needs. If you need help with that I suggest you to ask a question in StackOverflow or joining #mvvmcross in Xamarin Slack. 

Closing this issue as a question.

**Comment by kciesiel** [comment]
Ok, thanks.
