### ISSUE TITLE
Cannot install the MvvmCross.Forms NuGet package on a fresh/clean Xamarin.Forms project.

### ISSUE THREAD

**Issue by jmiddelkamp** [MvvmCross/MvvmCross#2070]
### Steps to reproduce

1. Create a Xamarin Cross Platform App (Blank App, Xamarin.Forms, Portable Class Library (PCL))

2. Open the NuGet package manager console

3. Select the Core project

4. Execute command: 'Install-Package MvvmCross.Forms'

### Expected behavior
The NuGet package should install.

### Actual behavior
The NuGet package installation returns the error below.

Install-Package : Could not install package 'MvvmCross.Forms 5.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Install-Package MvvmCross.Forms
   + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
   + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

### Configuration

**Version:** MvvmCross.Forms.5.1.0

**Platform:** 
- [ x ] iOS
- [ x ] Android
- [ x ] WPF
- [ x ] UWP

**Comment by jmiddelkamp** [comment]
For people who run into this issue dont worry its still possible to install the package. Just follow the steps below.

1. Unload your project and open the project file as XML.
2. Notate the value of your TargetFrameworkProfile value.
3. Replace the TargetFrameworkProfile node value with the value 'Profile7'.
4. Reload your project.
5. Install the package.
6. Restore the notated value just as you replaced the value before.

**Comment by martijn00** [comment]
You can also select Profile7 through the properties window in VS.

**Comment by jmiddelkamp** [comment]
But don't you agree this should work with an empty out of the box generated Forms project?

**Comment by martijn00** [comment]
The thing is that Forms currently targets more platforms then MvvmCross, like WP8. When we start using .NET Standard this will automatically be resolved.

**Comment by easoftwaresanderson** [comment]
I have this issues and i don't find the TargetFrameworkProfile in my file .csproj to change it.
Where is the property to change it?

**Comment by nickrandolph** [comment]
Are you using .net standard for your libraries?

**Comment by nickrandolph** [comment]
If you're targeting net standard 2.0 you shouldn't have to change the TargetFrameworkProfile, and you should be able to install the mvvmcross packages.
Please make sure you've updated all existing packages to the latest stable before adding the reference to mvvmcross.

**Comment by easoftwaresanderson** [comment]
I find it , I put one project in my solution for read ebook called EpubReader.Cross and it's one output class library, when i tried install I was checked it .
When I unchecked it i got it , and install on others project.
Thank you
