### ISSUE TITLE
Missing StarterPack for MvvmCross.Forms

### ISSUE THREAD

**Issue by jopmiddelkamp** [MvvmCross/MvvmCross#2073]
Just like the MvvmCross.StarterPack I would like to have a MvvmCross.Forms.StarterPack available.

**Comment by Dexyon** [comment]
Is this an issue or are you going to fix this?

**Comment by jmiddelkamp** [comment]
I'm pretty new to Xamarin, MvvmCross and the open source community. So I'm currently not yet planning on contributing other then reporting issues or wishes to try and help to improve the MvvmCross framework. I want to have a bit more feeling and experiance with Xamarin + MvvmCross before I start contributing to the framework.

**Comment by brucewilkins** [comment]
Picking this issue up @ Summer Hackfest 2017.
