### ISSUE TITLE
ViewAppearedFirstTime: ViewAppeared() can be called multiple times on iOS

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2075]
ViewDidAppear on a UIViewController is called multiple times by iOS: 
- when a view first appeared
- after a view opened a child view, and this child view is closed

A workaround in your BaseViewModel:

```
        private bool isInitWhenAppearing;
        public override void ViewAppearing()
        {
            if (!isInitWhenAppearing)
            {
                isInitWhenAppearing= true;
                ViewAppearingFirstTime();
            }
        }

        protected virtual void ViewAppearingFirstTime()
        {
        }
```

Btw, when using interactive transitions, ViewWillAppear is called while in the transition, and ViewDidAppear is called only after the transition is finished. This leads to ViewAppeared() called only after the end of a transition that was actually presenting the full view, which may be uninitialized depending on what's done in ViewAppeared.

**Comment by nmilcoff** [comment]
I'm not sure this is can be considered a bug, because the View is actually appearing more than once. Suppose you were developing just for iOS, without sharing any code, in that case you would have to add the flag to avoid the same problem. 

Adding that flag to the source will lead to unexpected behaviors for users.

Maybe I'm missunderstanding your problem, but otherwise I wouldn't change the way it works now.

**Comment by softlion** [comment]
Well in the head of all devs, the ViewAppearing event is in fact equal to ViewFirstAppearing (which it is not). They will suppose it is called only once per viewmodel. It will work, until they push some other page, and go back.

So it will create insidious bugs. And make mvvmcross harder to learn and use.

**Comment by softlion** [comment]
I agree. So better add a new ViewFirstAppeared event. So devs won't be tempted to use ViewAppear for this same event.

**Comment by nmilcoff** [comment]
Looking at the `ViewAppearing` implementation in other platforms, it seems you're in the right path @softlion, it is never called more than once. I think we should add that flag to all ViewController classes.

**Comment by kvandake** [comment]
Did you mean [it](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs#L72)?

**Comment by softlion** [comment]
YWell if disposed you should not call base.

**Comment by nmilcoff** [comment]
Did you close the issue intentionally? If so, I'm absolutely confused about this 😄. 

If it wasn't intentionally, I honestly got confused in the discussion...  which would be your proposal for `ViewWillAppear` / `ViewDidAppear`?
