### ISSUE TITLE
Aplication is crashed after resume

### ISSUE THREAD

**Issue by kciesiel** [MvvmCross/MvvmCross#2078]
1.  Create new MvvmCross app (using MvvmCross 5 Solution template or not)
2. Add image to first page
3. Run app, added image will be displayed
4. Go to desktop and run app again
5. Application will be crashed (message (something like that): the application will be not working in this thread longer).  This problem only occurs when image is added in first page and that's just for 5.1 version.

**Version:** 5.1

**Platform:** 
- [ ] Android

**Comment by Cheesebaron** [comment]
You need to provide more information about how you are adding this image.

**Comment by kciesiel** [comment]
I can send you sample project later. I have added image using Image control, source property and resources in Droid and iOS project (standard way).

**Comment by kciesiel** [comment]
I checked that after update to 5.1.1. Now it is crashing at the beginning.
Size of sample project is 70 mb and I don't have public repo, so if you want I can send that by email.
Actually, steps:
1. Create new project using Xamarin Forms with MvvmCross 5 Solution Template
2. Add following code to MainPage.xaml:
`<?xml version="1.0" encoding="utf-8" ?>
<mvx:MvxContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ImageIssueTest.Core.Pages.MainPage"
             xmlns:res="clr-namespace:ImageIssueTest.Core.Resources;assembly=ImageIssueTest.Core"
             xmlns:mvx="clr-namespace:MvvmCross.Forms.Core;assembly=MvvmCross.Forms">
  <Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="*"/>
      <ColumnDefinition Width="Auto"/>
      <ColumnDefinition Width="*"/>
    </Grid.ColumnDefinitions>
    <Grid.RowDefinitions>
      <RowDefinition Height="*"/>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="*"/>
    </Grid.RowDefinitions>
    <StackLayout Grid.Row="1" Grid.Column="1">
      <Image Source="Icon.png" Width="100" Height="100"></Image>
      <Label Text="{res:Translate MainPageTitle}"
             VerticalOptions="Center"
             HorizontalOptions="Center"
             StyleId="MainPageTitleLbl" />
      <Button Text="{Binding ButtonText}" Command="{Binding PressMeCommand}" />
      <Button Text="{res:Translate GoToSecondPageText}" Command="{Binding GoToSecondPageCommand}" />
    </StackLayout>
  </Grid>
</mvx:MvxContentPage>`

3. Run app and waiting for popup exception.

**Comment by Cheesebaron** [comment]
Is it also 70 mb if you remove the packages and bin/obj folders?

**Comment by kciesiel** [comment]
I have removed just packages folder. Right now I removed bin/obj folders and it weights only 301 kb. Where can I upload this app?

**Comment by Cheesebaron** [comment]
Create a new repository here on github and link to it.

**Comment by kciesiel** [comment]
https://github.com/kciesiel/MvvmTest/tree/master/ImageIssueTest
