### ISSUE TITLE
MvxException: Could not find plugin loader for type MvvmCross.Plugins.File.PluginLoader

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2082]
When using the file plugin, and when full linking is enabled, the app crashes with:
`MvxException: Could not find plugin loader for type MvvmCross.Plugins.File.PluginLoader`
The same problem happens with the Messenger plugin and the Visibility plugin.

A workaround is to update the bootstraps by adding a Preserve attribute :

    [Foundation.Preserve(AllMembers = true)]
    public class FilePluginBootstrap
        : MvxLoaderPluginBootstrapAction<MvvmCross.Plugins.File.PluginLoader, MvvmCross.Plugins.File.iOS.Plugin>
    {
    }

### Steps to reproduce

1. Create an mvvmcross app

2. Add the File plugin

3. try to resolve Mvx.Resove<IMvxFileStore> interface in the constructor of a viewmodel

4. compile in release mode with full linking enabled

5. run the app

### Expected behavior
don't crash

### Actual behavior
crash
`MvxException: Could not find plugin loader for type MvvmCross.Plugins.File.PluginLoader`

### Configuration

**Version:** 5.1.1

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
Adding preserve flag to the bootstrap wont help here.

You need to add appropriate PluginLoader entries in your LinkerPleaseInclude file.

Something like this may work:

        private readonly List<IMvxPluginLoader> _loaders = new List<IMvxPluginLoader>
        {
            MvvmCross.Plugins.File.PluginLoader.Instance,
        };

        private readonly List<IMvxPlugin> _plugins = new List<IMvxPlugin>
        {
            new MvvmCross.Plugins.File.iOS.Plugin(),
        };

        public void Include(IMvxPluginLoader loader)
        {
            foreach (var l in _loaders)
            {
                loader = l;
                loader.EnsureLoaded();
            }
        }

        public void Include(IMvxPlugin plugin)
        {
            foreach (var l in _plugins)
            {
                plugin = l;
                plugin.Load();
            }
        }

The file plugin may be missing some preserve flags, the above should help you a bit though.

**Comment by softlion** [comment]
Adding the preserve tag does fix the issue without the need to add lines to linker please include.

Xamarin has created a new assembly attribute to mark an assembly as safe for full linking. They don't use any linkerpleaseinclude files. Only preserve tags.

**Comment by Cheesebaron** [comment]
That is strange, because you are essentially just adding a preserve to the bootstrap. The boostrap yet again looks for the `Instance` property and calls `EnsureLoaded` on it, through reflection...

**Comment by softlion** [comment]
The problem is not the plugin itself, it's the plugin loader which gets optimized away

**Comment by willsb** [comment]
What version of Xamarin are you using? I've never had problems with the Plugin loader getting linked away when using Link All, this is really odd.

Maybe we should consider adding `[Preserve]` to the .tt files, since they are only included when the user adds the plugin package.

**Comment by softlion** [comment]
Maybe i'm the only one using Link All without specifying any local exclusion assembly ?
It's on iOS.

Found the attribute: [assembly: LinkerSafe]
https://blog.xamarin.com/howto-partially-linking-monotouch-applications/


Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Xamarin   4.5.0.486 (fec6f88)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   7.3.1.2 (9dbc4c5)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   10.10.0.37 (ad35de4)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by nmilcoff** [comment]
Bootstrap files are gone! (reference: #2603)
