### ISSUE TITLE
MvxTabBarViewController not working anymore without WrapInNavigationController parameter

### ISSUE THREAD

**Issue by DelcoigneYves** [MvvmCross/MvvmCross#2084]
### Steps to reproduce

1. Update Star Wars sample to latest version of MvvmCross (5.1.1)

2. Run on iOS.

### Expected behavior
App shows pages correctly.

### Actual behavior
Crash: MvvmCross.Platform.Exceptions.MvxException: Trying to show a tab without a TabBarViewController, this is not possible!

When adding the the WrapInNavigationController parameter set to true, the app runs (but then we get 2 navigation bars in the sample).

### Configuration

**Version:** 5.1.1

**Platform:** 
- [ x ] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
Thanks for reporting this issue! It is fixed by #2085
