### ISSUE TITLE
PictureChooser doesn't open on Xamarin Forms iOS

### ISSUE THREAD

**Issue by Almis90** [MvvmCross/MvvmCross#2091]
The first time I calling the function it does nothing and the second time I call the function it gives me this messages in the console output `MvxImagePickerTask called when task already active`.

Here is the link to sample: https://github.com/Almis90/MvxForms

### Steps to reproduce
1. Run the iOS project and click the choose picture button

### Expected behavior
I was expecting to see new page that allows me to select image.

### Actual behavior
Doesn't show anything and doesn't crash, it just runs in the background as I understood

### Configuration

**Version:** 5.1.1

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
@Almis90  Can you try to upgrade the sample to latest mvx? I feel confident this was fixed somewhere.

**Comment by martijn00** [comment]
Please reopen if you have more information.
