### ISSUE TITLE
Email Plugin for Wpf not packaged correctly and misses IMvxComposeEmailTaskEx registration

### ISSUE THREAD

**Issue by adaxer** [MvvmCross/MvvmCross#2101]
### Issues
1. Email plugin not packaged correctly for Wpf
2. Plugin class does not register IMvxComposeEmailTaskEx

### Steps to reproduce

1. Create new MvvmCross project (with Mvx 5.1.1) with a Wpf client
2. Add the MvvmCross.Plugin.Email 5.1.1 package
3. Look in the package dir of the solution. The Net45 folder does not contain the MvvmCross.Plugins.Email.Wpf.dll and pdb
4. When manually installing, notice that the IMvxComposeEmailTaskEx cannot be resolved

### Expected behavior
The setup sequence should run through, then the IMvxComposeEmailTaskEx should be resolvable

### Actual behavior
Setup.Initialize throws a PluginLoading exception
(After manual installation of the Wpf component, trying to resolve IMvxComposeEmailTaskEx throws an MvxIoCResolveException)

### Configuration

**Version:** 5.1.1

**Platform:** 
- [ ] iOS
- [ ] Android
- [X ] WPF
- [ ] UWP

### Reason

My own investigation brought up, that there are two things to do that solve the issue:
1. In the Wpf project of the Email plugin, the output path should be set one path higher: ..\\..\\..\\bin\Debug\Mvx\Wpf\ instead of ..\\..\\bin\Debug\Mvx\Wpf\
2. The line Mvx.RegisterType<IMvxComposeEmailTaskEx, MvxComposeEmailTask>(); should be added to the Load method of the Plugin class in the Wpf project

**Comment by Cheesebaron** [comment]
Wpf does not implement the `Ex` interface.

**Comment by adaxer** [comment]
I see. Sorry about that one, Still, the nuget package does not contain the wpf library

**Comment by adaxer** [comment]
After looking into the interfaces - is there a special reason why it is not implemented? (It does not look as if it's technologically impossible). Thanks

**Comment by adaxer** [comment]
Ok, just checked with our architect - I'll try to do an implementation in the plugin, and if that succeeds, I can create a PR to incorporate it into Mvx, if you agree

**Comment by Cheesebaron** [comment]
You are welcome to do a pull request. I don't know why the Ex interface wasn't implemented to begin with. It is probably possible. As to why the nuget doesn't contain the dll beats me, looking at the [nuspec#L24](https://github.com/MvvmCross/MvvmCross/blob/develop/nuspec/MvvmCross.Plugin.Email.nuspec#L24) it seems that it is included.

Also please keep the chatter to a minimum. Use the edit button instead of making 3 posts after another.

**Comment by adaxer** [comment]
(Edited comments for less clutter...) - The wpf project seems to direct the output up one ..\\ too little - we cant explain either why the packaging cmd of nuget does not spit out the error

**Comment by martijn00** [comment]
This is packaged in 6.0
