### ISSUE TITLE
Feedback: (Semantic) Versioning

### ISSUE THREAD

**Issue by aspnetde** [MvvmCross/MvvmCross#2107]
I wrote about my experience while trying (and failing) to upgrade from 4.x to 5.x [here](https://github.com/MvvmCross/MvvmCross/issues/2105). One thing I didn't mention is my surprise when I came along this post:

https://stackoverflow.com/a/44764374/271150

I disagree with those changes as I wrote in my other issue, but that's not the point here. What surprises me (euphemism) is that this change occurs in a _minor update_. 

I know how hard it is to get things right, especially if you're doing all this voluntarily in your spare time. I've been there, and I have been failing my own expectations on this. So I won't judge you.

But maybe you as a team of the active maintainers could take into consideration that MvvmCross has become the foundation of many applications, smaller ones, but also larger ones.

For example I am responsible for a relatively large project using Mvx (almost 100 view models, since more than 2,5 years in active development and still evolving). For projects like this it's just normal not to upgrade to the latest major version of every library and especially for a framework in use. 

But we try to stay as close as possible, so updating minor updates is common. If now those minor updates contain breaking changes which affect basically the whole architecture of our application, that's a problem. A huge problem, because it causes a loss of trust.

Just another 2 cents.

✌🏻

**Comment by martijn00** [comment]
We try to do this already, but sometimes choices are made that reveal to have more impact than thought. Part of the solution is https://github.com/MvvmCross/MvvmCross/issues/2059 where we will update the whole CI system to use the new .NET standard semver packaging system.

**Comment by aspnetde** [comment]
Maybe a good demo app would help, which uses all the important features and which also implicitly provides fast feedback when something is breaking.

**Comment by martijn00** [comment]
We've got a whole folder of TestProjects(https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects) which we use to test the  important features. We've got an issue on the backlog to consolidate these samples so it is easier to test, and you are more then welcome to contribute to that.

**Comment by aspnetde** [comment]
Obviously that didn't prevent things like [that](https://github.com/MvvmCross/MvvmCross/issues/2071) to happen, so there is room for improvement ;-).

**Comment by martijn00** [comment]
There always is room for improvement. This is open source and we are putting a lot of time in where a lot of people are using the benefits of MvvmCross. It would be nice to distribute the heavy lifting of work over more people instead of a few people and everyone relies on them. The first step here is to start contributing to open source projects you use.

**Comment by aspnetde** [comment]
That's what I am doing here.

**Comment by nmilcoff** [comment]
@aspnetde you have a fair point about what has happened with the MvxNavigationService lately, but as Martijn says, that is exactly why ShowViewModel is still supported. You can actually migrate to latest MvvmCross without changing almost any code.

As you can see in #1634, it is not completely finished yet. @martijn00 is working really hard to get it done, and we are trying to support and help him wherever we can. 

We appreciate your feedback and will try to improve as much as we can :), just keep in mind this is an Open Source project.

**Comment by aspnetde** [comment]
> I know how hard it is to get things right, especially if you're doing all this voluntarily in your spare time. I've been there, and I have been failing my own expectations on this. So I won't judge you.

No offense here.
