### ISSUE TITLE
MvxAndroidSetupSingleton remove reflection #enhancement

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2109]
MvxAndroidSetupSingleton uses reflection to find the Setup class.
We could speed up startup a little on all platforms.

We could replace this reflection code with an attribute search, and decorate the Setup class with a SetupAttribute. Or find a way to declare the Startup class statically in android manifest xml, using an automatic xamarin manifest attribute on the Startup class.

### Configuration

**Version:** 5.1

**Platform:** 
- [X] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2710
