### ISSUE TITLE
Renaming all classes

### ISSUE THREAD

**Issue by patsadow2** [MvvmCross/MvvmCross#2123]
Renaming is INSANE !!! If someone use your lib in a big project that cause a lot of errors....

**Comment by Cheesebaron** [comment]
OK. Going to close this one as you fail to back up your argument.

We try to clearly document upgrade paths and stick to the rules of SemVer. If you have a better suggestion, we are very happy to hear it. If you are just here to have a raging fit, then please don't. It is not worth either you or our time.

Closing this issue for now.
