### ISSUE TITLE
Plugin architecture suggestion

### ISSUE THREAD

**Issue by tomcurran** [MvvmCross/MvvmCross#2127]
Looking at some plugins if they were converted to bait and switch they wouldn't actually depend on mvvmcross. I'm proposing that we convert to a xamarin/jamesmontemagno model of having each plugin in its own repo and versioned separately from mvvmcross. This is something we could experiment with in the Hackathon.

**Comment by Cheesebaron** [comment]
We thought about converting to bait and switch at Evolve 2016, but I never finished converting all the plugins. This probably ties in with .NET Standard conversion and whether to do multi-target in .NET Standard.

Either way things to think about here are

- If we convert our plugins to look like James' architecture, we still need a way to register the plugins with our IoC container
    - Attributes?
    - Keep bootstrap files?
    - Naming convention?
- Which plugins do we keep?
    - Do we keep all of them and just have duplicates of already existing plugins?
- Do we keep naming and branding where we prefix with Mvx if the plugins become general use?
- Do we have a separate build and versioning of each plugin if they are not strictly bound to MvvmCross anymore?

**Comment by tomcurran** [comment]
We recently converted some in house plugins, that were following James patterns, from using profile 111 to netstandard 1.0 and it was straight forward. I don't know anything about the multi-targets however. I think we should consider the epic of the plugin architecture and maybe create roadmap as doing all these changes at once would probably take a lot of time. Maybe handle bait and switch first then netstandard then multi-targets?

Do we have to provide a special way or registering with the IoC container? With bait and switch the plugin will work fine without resolving through an interface. I think it should be left to the consumer of the plugin to choose if they want to use IoC or not. We could include the suggested IoC instructions in the docs to encourage that to be used.

Personally I would drop the branding of Mvx if they aren't bound to mvvmcross and if we are trying to treat them as their own things. It might actually cause more confusion if the branding remained.

Yeah I think keeping them all would be great. Im guessing some might use some core functionality and might take longer to separate into their own projects. I say push forward with doing the work for easier plugins even if some need to remain in the main repo.

I would be in favour of separate repositories, building and versioning of each plugin.

**Comment by Cheesebaron** [comment]
> Maybe handle bait and switch first then netstandard then multi-targets?
Bait and switch works with .NET Standard too, so it is whether to do Bait and Switch _or_ Multi-targets

> Do we have to provide a special way or registering with the IoC container? With bait and switch the plugin will work fine without resolving through an interface. I think it should be left to the consumer of the plugin to choose if they want to use IoC or not. We could include the suggested IoC instructions in the docs to encourage that to be used.

That is done through the bootstrap files currently.

> Personally I would drop the branding of Mvx if they aren't bound to mvvmcross and if we are trying to treat them as their own things. It might actually cause more confusion if the branding remained.

In this case we should probably make a _MvvmCross-Plugins_ organization and host plugins each in their individual repository, especially if they have no hard dependency on MvvmCross. Although many have since they implement `IMvxTask` in some form or another. Need to think about how to separate those from the rest of the framework.

**Comment by tomcurran** [comment]
> > Do we have to provide a special way or registering with the IoC container? With bait and switch the plugin will work fine without resolving through an interface. I think it should be left to the consumer of the plugin to choose if they want to use IoC or not. We could include the suggested IoC instructions in the docs to encourage that to be used.
> 
> That is done through the bootstrap files currently.

With bait and switch you can select a platform implementation for an interface without registering it with the IoC system. The bootstrap files currently select a platform implementation for an interface and registers that implementation into the IoC system in one operation. I personally don't think we need put the interface into the IoC system as we'd be splitting the plugins from mvvmcross and any IoC system could be in use now. Best thing is to document what to do to put it into some IoC systems including mvvmcross.

> > Personally I would drop the branding of Mvx if they aren't bound to mvvmcross and if we are trying to treat them as their own things. It might actually cause more confusion if the branding remained.
> 
> In this case we should probably make a MvvmCross-Plugins organization and host plugins each in their individual repository, especially if they have no hard dependency on MvvmCross. Although many have since they implement IMvxTask in some form or another. Need to think about how to separate those from the rest of the framework.

Agreed. Some plugins may take a lot of work in that case - its probably worth reviewing which plugins may be hard to migrate and which would be easier. Does that plugins organisation exist already? Should we start to show how this might be achieved on a banch or fork of this repo?

**Comment by Cheesebaron** [comment]
> With bait and switch you can select a platform implementation for an interface without registering it with the IoC system.

So you suggest to use the Singleton anti-pattern for plugins just like James' plugins do?

**Comment by tomcurran** [comment]
> > With bait and switch you can select a platform implementation for an interface without registering it with the IoC system.
> 
> So you suggest to use the Singleton anti-pattern for plugins just like James' plugins do?

Yes. I'll admit I've not looked at any other options though to achieve a similar goal.

**Comment by martijn00** [comment]
Fixed with using .NET Standard and https://github.com/MvvmCross/MvvmCross/pull/2603

**Comment by tomcurran** [comment]
@martijn00 the original proposal was mostly relating to removing mvvmcross as a dependency of the plugins and maintaining them each separately so I wouldn't say this is closed

**Comment by nmilcoff** [comment]
I'm wondering if plugins like `Visibility` can even exist without a reference to MvvmCross 🤔

**Comment by tomcurran** [comment]
@nmilcoff I'm guessing it probably could. They might need a bit of work to disconnect from mvx and might need something new to connect it back into mvx.

I've seen some developers write a mvx shim for their plugins. Maybe that would be a useful pattern. It would get wider use of the plugins because they don't depend on mvx but still could easily be utilised in mvx as they are now.

Maybe it needs some sort of meet up to gather peoples thought and push forward the potential options?
