### ISSUE TITLE
MvxAppCompatActivity doesn't work with IMvxNavigationService

### ISSUE THREAD

**Issue by kevingoos** [MvvmCross/MvvmCross#2128]
### Steps to reproduce

1. First call a viewmodel using `RegisterAppStart<T>`. (In my sample called `FirstViewModel`)

2. In that viewmodel you use the `IMvxNavigationService `to get to the viewmodel that contains the `FrameLayout `and the activity extending `MvxCachingFragmentCompatActivity<T>`. (In my sample called `MainViewModel`)

3. In this viewmodel a fragment get called in the Init method called in the contstructor. This should show the first view in the `FrameLayout`. 
```
public async void Init()
{
        await _navigationService.Navigate<FirstViewModel>();
}
```

```
[MvxFragment(typeof(MainViewModel), Resource.Id.content_frame, true)]
[Register(nameof(FirstFragment))]
public class FirstFragment : MvxFragment<FirstViewModel>
{
    public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
    {
        base.OnCreateView(inflater, container, savedInstanceState);
        var view = this.BindingInflate(Resource.Layout.FirstView, container, false);
        return view;
    }
}
```

### Sample

I made some samples to show the problem properly. [The github link](https://github.com/kevingoos/FragmentTest). This link contains two samples, the first sample shows the problem I am having. The second sample (is working) shows that if you directly register on the `MvxCachingFragmentCompatActivity` it works. So this proofs that there is something wrong or missing for the `IMvxNavigationService`?

### Expected behavior
When you use the `IMvxNavigationService` to call a fragment, the fragment should show inside the given `FrameLayout`.

### Actual behavior
The fragment initialisation get called, even the `OnCreateView()` is called. But it doesn't show anything inside the given `FrameLayout`. The correct `FrameLayout `is defined by the attribute `MvxFragment`.

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by kevingoos** [comment]
I found an awnser to this, on this github page: https://stackoverflow.com/questions/45856485/mvvmcross-framelayout-doesnt-show-fragment-after-activity/45859196#45859196

**Comment by martijn00** [comment]
Hehe good that you found my answer!
