### ISSUE TITLE
Android PictureChooser may crash when no network connection.

### ISSUE THREAD

**Issue by jz5** [MvvmCross/MvvmCross#2134]
I will send PR for this issue.

### Steps to reproduce

Probably, this is rare case. I encountered it after Android 4.4 device hard reset. 
The device doesn't reproduce this when disconnecting after connecting to the network again.

1. Use PictureChooser with no network connection.
1. Select an online picture.

### Expected behavior
No crash

### Actual behavior
PictureChooser(ActionGetContent intent) works with no network connection using cached images. And it returns file URL. But ContentResolver cannot open the URL (throws FileNotFoundException). As the result App crashed.

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
And you can't catch this exception?

**Comment by jz5** [comment]
@Cheesebaron The exception is Java.IO.FileNotFoundException. So can't catch in PLC project.

**Comment by Cheesebaron** [comment]
OK so this exception needs to be handled in the plugin and surfaced as a `MvxException` of some kind to notify the user that there is no connection or whatever.

**Comment by jz5** [comment]
I checked for more. The exception thrown in ```ProcessMvxIntentResult```. Any exceptions can't be caught in PCL project.

**Comment by nmilcoff** [comment]
The linked PR says it _partially_ solves this issue, should it remain open maybe @Cheesebaron?

**Comment by Cheesebaron** [comment]
@nmilcoff it solves this problem. However, it does not solve the issue of telling the developer why it didn't work though.
