### ISSUE TITLE
Mvx 5.x navigation and TabBarViewController

### ISSUE THREAD

**Issue by fonix232** [MvvmCross/MvvmCross#2137]
In my app, I use an `MvxTabBarViewController` as the root view of my app, loading three views into it using their ViewModels.

We're rebasing our previous 4.x code to 5.x, and ran into a slight issue regarding this transition with the way the tabs are created.

Currently we have a `BaseTabBarView` expanding the `MvxTabBarViewController` with the following function:

```csharp
protected UIViewController CreateTabFor<Tvm>(string title, string imageName) where Tvm : BaseViewModel
{
    var controller = new UINavigationController();
    var screen = this.CreateViewControllerFor(new MvxViewModelRequest<Tvm>()) as UIViewController;
    SetTitleAndTabBarItem(screen, title, imageName);
    controller.PushViewController(screen, true);
    return screen;
}
```

This has worked great before, including the subpages' navigation `Task Init()` method being called. However if I switch to the new NavigationService way of handling stuff,  the new `Task Initialize()` method is never called.

How could I adopt this to the new NavigationService?

### Configuration

**Version:** 5.x

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
Are you using the new MvxIosViewPresenter that comes with MvvmCross 5? I recommend you to look at how it is implemented in [Playground TestProject](https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Playground/Playground.iOS). That sample app uses both the new presenter and the new navigation service. 

Have you read the [documentation](https://www.mvvmcross.com/documentation/platform/ios-view-presenter) pages? That being said, I'll need more details to be able to help you.

**Comment by fonix232** [comment]
Yes, we are using the new MvxIosViewPresenter. However our old method was using the N+1 samples, which was still the old navigation pattern. Using the global NavigationService to push these child views solved the issue. Thanks!
