### ISSUE TITLE
Android RecyclerView.ViewHolder DataContext property change view updates lost depending on RecyclerView item position on screen

### ISSUE THREAD

**Issue by MagneticLlama** [MvvmCross/MvvmCross#2142]
I have a view holder that weak subscribes to view model property changes in OnAttachedToWindow instead of using bindings. If a DataContext property change occurs on an item that is off screen but cached, the change will not make it to the ViewHolder because the DataContext has been set to null within OnDetachedFromWindow in the MvxRecyclerViewHolder. When the user scrolls down to that item, OnBindViewHolder will not be called. I don't know the best practice for handling this issue. Should I just do potentially duplicate work in OnAttachedToWindow applying changes to the view?

### Steps to reproduce

1. Subscribe to DataContext changes in a ViewHolder OnAttachedToWindow

2. Change a DataContext property for an item that is barely off screen, but has a cached view

3. The ViewHolder will not be notified of the property change because DataContext is null

4. Scroll down to the item. OnBindViewHolder will not be called, so changes to the item will not be seen in the view.

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by softlion** [comment]
I suppose you should use bindings instead (custom ones maybe, still bindings).

From what you wrote, you found that OnBindViewHolder is not called before being reattached if it should display the same item ? This seems impossible. Any pointer to the code ?

**Comment by nmilcoff** [comment]
@MagneticLlama any updates based on what @softlion said?

**Comment by MagneticLlama** [comment]
Sorry I missed the initial reply to this. There was a decision in our project not to use bindings on lists, because it seemed to be negatively impacting performance. It has been quite a while since I've looked at this. I don't recall how I worked around the original issue.
