### ISSUE TITLE
MvxRecyclerAdapter NotifyDataSetChanged not called on mainthread

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2144]
When an obserbable collection is changed on a worker thread, MvxRecyclerAdapter.NotifyDataSetChanged is called on the same worker thread instead of switching to the main thread.

Following the same philosophy that drove the introduction of the task based binder which eliminates the need to fire notifypropertychange events on the main thread, it would be better if the MvxRecyclerAdapter test if it is on the main thread and switch to it automatically if not before calling the NotifyXXXX native methods on the base android class, which requires the main thread.

Also, https://github.com/MvvmCross/MvvmCross/blob/master/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.V17.Leanback/Listeners/MvxOnChildViewHolderSelectedListener.cs should use IMvxRecyclerAdapter instead of MvxRecyclerAdapter on line 21.

Also, there should not be any `new MvxRecyclerAdapter()` code in MvxHorizontalGridView.cs or MvxRecyclerView.cs, instead it should use iOC instantiation. It would be much easier to switch the implementation of MvxRecyclerAdapter.

### Configuration

**Version:** 5.1

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
Can you make a pull request to address these issue's?
