### ISSUE TITLE
IMvxPictureChooserTask iOS 10.3 app crash on selecting image from Gallery

### ISSUE THREAD

**Issue by muhammad-azeem-confiz** [MvvmCross/MvvmCross#2149]
IMvxPictureChooserTask iOS 10.3 app crash on selecting image from Gallery option
*working fine on iOS 8.4(12H143)
*I am using this on child view of MvxTabBarViewController

code:
var task = Mvx.Resolve<IMvxPictureChooserTask>();
var stream = await task.ChoosePictureFromLibraryAsync(240, 10);
OnPicture(stream, string.Empty);

application crash after this line:
_modalHost.PresentModalViewController(_picker, true);
from iOS plugin [File](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-Plugins/PictureChooser/MvvmCross.Plugins.PictureChooser.iOS/MvxImagePickerTask.cs).

### Configuration
Xamarin: 6.3
Xcode: 8.3
iOS: 10.3

**Platform:** 
- [ ] iOS

**Comment by Cheesebaron** [comment]
Please provide the full stack trace.

**Comment by muhammad-azeem-confiz** [comment]
Issue is fixed by removing and adding the Privacy - Photo Library Usage Description for iOS 10+.
Also needs to clean the solution and clear the cache from ~\Library

Thanks for your time.
