### ISSUE TITLE
Display MvxAppCompatDialogFragment as a dialog

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross#2152]
MvxCachingFragmentCompatActivity is always displayed as content in a view hierarchy

### Steps to reproduce

1. Implement MvxCachingFragmentCompatActivity

2. Display an instance of MvxAppCompatDialogFragment by calling IMvxNavigationService.Navigate

### Expected behavior
I expect the fragment to be shown as a dialog 

### Actual behavior
The fragment is always displayed as content in a view hierarchy

The function MvxCachingFragmentCompatActivity.ShowFragment will always add the fragment to the backstack instead of calling newFragment.Show().

### Configuration

Version:  5.1.1

Platform:
- [X ] Android

**Comment by martijn00** [comment]
This is fixed in 5.2.

**Comment by erviem99** [comment]
This is great news. I suppose you are referring to #1934 ?

The changes look too complex to merge into my existing project so I guess I will have to wait for version 5.2 :-)
