### ISSUE TITLE
Cleanup MvvmCross simple implementation for Droid

### ISSUE THREAD

**Issue by nmilcoff** [MvvmCross/MvvmCross#2153]
There is a folder named [Simple](https://github.com/MvvmCross/MvvmCross/tree/develop/MvvmCross/Droid/Droid/Simple) inside MvvmCross.Droid, which contains three classes:
- `MvxSimpleAndroidSetup`
- `MvxSimpleBindingActivity`
- `MvxSimpleEmptyAndroidApp`

These were created initially to provide a way for users to use a small set of features from MvvmCross instead of the entire framework. As you can see in the Setup class, it doesn't initialize the ViewLookup and the NavigationSerializer. Also note this only exists for Android, there are no implementations for other platforms.

So I think we have two alternatives here:
1. Kill it 🔥
2. Ensure it works, provide similar implementations for all other platforms, and create documentation for it. 

I personally choose (1).

**Version:** 5.x
Latest source code

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
I vote 🔥 it.

This is a very neglected part of MvvmCross. I think we should focus on getting the full experience right before allowing people to use a watered down version of it.
