### ISSUE TITLE
Add initWithCoder: constructor for MvxView

### ISSUE THREAD

**Issue by KanLei** [MvvmCross/MvvmCross#2156]
### Steps to reproduce

1. Create new `CustomView` class with xib file, connect with File's Owner - Class.

2. Declare _Load nib and add the first view of nib to `CustomView`_  in `MvxView(IntPtr)`.

3. Use `CustomView` in any other `UIViewController` xib file.

4. Run and Crash.

### Expected behavior
`CustomView` should load correctly. 
> Add `initWithCoder:` constructor for MvxView, declare load operation in  `MvxView(NSCoder)` and keep `MvxView(IntPtr)` empty.

### Actual behavior
throw `System.Reflection.TargetInvocationException`

### Configuration

**Version:** 5.1.1

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by mvanbeusekom** [comment]
Good catch, I will have a look at this
