### ISSUE TITLE
Suggested Topics in documentation

### ISSUE THREAD

**Issue by turibbio** [MvvmCross/MvvmCross#2175]
Would be great to have in the documentation a "Suggested Topics" section at the bottom of each page. This could help people to easily find information related to the topic they're reading. A quick sample: in the navigation service page (https://www.mvvmcross.com/documentation/fundamentals/navigation) would be great to have at the bottom a reference on the counterpart implementation in a platform specific project (iOS, Android, etc, etc). This way I could use the first page to implement navigation in my viewmodel and then see right after how to use it in each project.

**Comment by MarcBruins** [comment]
good suggestion turibbio! Can you make such a thing? The website is comes directly from the docs folder in the repository?
