### ISSUE TITLE
Auto-creation of window in MvvmCross Mac now default?

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#2178]
Hi, I just upgraded from MvvmCross 4.4 to 5.1 and notice that my subview is now created in a new window. This seems like new behavior which makes it no longer necessary to create a window in DidFinishLaunching in MvxApplicationDelegate. (For example, in the Mac example here - https://github.com/MvvmCross/MvvmCross-Samples/blob/master/FirstDemo/FirstDemo.Mac/AppDelegate.cs). Can someone who worked on this confirm? If this is expected behavior now, where is it recommended to make changes to the window frame and size?

**Comment by nmilcoff** [comment]
Hey @tofutim, there is a new default ViewPresenter for macOS on MvvmCross 5.1. You can read about it [here](https://www.mvvmcross.com/documentation/platform/mac-view-presenter).

You are right, you don't need to create a window by yourself anymore in DidFinishedLaunching. You can customize the frame/size of your window by using the properties of MvxWindowPresentationAttribute. Also if no attribute is found in your View, then [it might be presented as a window](https://github.com/MvvmCross/MvvmCross/blob/8dd5707ebd8d2158cf0e5197060295bad4ba7f36/MvvmCross/Mac/Mac/Views/Presenters/MvxMacViewPresenter.cs#L239). 

You can see the new presenter in action in [this](https://github.com/MvvmCross/MvvmCross/tree/master/TestProjects/Playground/Playground.Mac) sample.

**Comment by tofutim** [comment]
Thank you!

**Comment by tofutim** [comment]
Do you happen to know if I can use MvvmCross to control the MainMenu options as well? Or is that still separate for now?

**Comment by nmilcoff** [comment]
I'm afraid that isn't supported yet... If you think it's something possible to add, please open a new issue with more details for it (and of course a PR would be more than welcome)

**Comment by tofutim** [comment]
It might be good to add some examples of changing the default window size, I'm still a bit perplexed from the examples how one could do this. Looking into it.

**Comment by tofutim** [comment]
Never mind I figured it out from the samples! Thank you nmilcoff!

**Comment by nmilcoff** [comment]
That is great! :+1: you're very welcome.

**Comment by tofutim** [comment]
@nmilcoff  any thoughts on how to get Toolbar to work with MvvmCross? It typically gets attached to a window instead of a view....

**Comment by nmilcoff** [comment]
@tofutim you can subclass the ViewPresenter, register it in Setup.cs and then override [this method](https://github.com/MvvmCross/MvvmCross/blob/8dd5707ebd8d2158cf0e5197060295bad4ba7f36/MvvmCross/Mac/Mac/Views/Presenters/MvxMacViewPresenter.cs#L105) to take control of a Window creation. If you consider it is a bug, please open a new issue for it.

**Comment by tofutim** [comment]
would it be possible using this technique to still bind with my viewmodel?

**Comment by tofutim** [comment]
Also, if we override the ViewPresenter, would that mean that all future
views would have the toolbar and not the just the main window? It feels
that this might be a limitation of viewcontrollers vs windowcontrollers...
maybe it is not possible to do it in a clean way and still accomplish the
binding.

**Comment by tofutim** [comment]
Or, alternatively, there is something like

[MvxWindowPresentation("NameOfCustomWindowViewController")] ?

but still this does not address binding of the toolbar items to the model

**Comment by nmilcoff** [comment]
Is your app using bindings for items in UIWindows? If so, I suppose you have a custom WindowViewController that implements everything, because before 5.1 MvxWindowViewController didn't even exist. I guess you can use your implementation by overriding [this method](https://github.com/MvvmCross/MvvmCross/blob/8dd5707ebd8d2158cf0e5197060295bad4ba7f36/MvvmCross/Mac/Mac/Views/Presenters/MvxMacViewPresenter.cs#L217).

**Comment by martijn00** [comment]
@tofutim can you make separate issues for the limitations you mention here? We would like to fix them!

**Comment by tofutim** [comment]
Thank you Martijn I'll try to write something up tomorrow.
