### ISSUE TITLE
Some packages still depend on MvvmCross.Droid.Shared

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#2181]
### Steps to reproduce

1. Update or install packages that depend on MvvmCross.Droid.Shared to latest 5.2.0

2. 💥 

### Expected behavior
Should update or install package

### Actual behavior
NuGet complains that the following packages depend on MvvmCross.Droid.Shared 5.2.0 which is not present:
- MvvmCross.Droid.Support.Core.UI
- MvvmCross.Droid.Support.Core.Utils
- MvvmCross.Droid.Support.V7.AppCompat

### Configuration

**Version:** 5.2.0

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
Nevermind. It is just when updating packages the NuGet package manager might complain that it cannot update packages because MvvmCross.Droid.Shared has been removed as a dependency.

I guess the solution is to force remove the MvvmCross.Droid.Shared package, then update the rest.

**Comment by Naveen9453** [comment]
which nuget package we have to use in place of MvvmCross.Droid.Shared package,
I am using MvxFragment in my project and it shows error The Type or Namespace name "MvxFragment" could not find.
I am new to MvvmCross Please Help.

**Comment by JosephDevlin** [comment]
@Naveen9453 
Did you ever solve that issue? I have the same one
