### ISSUE TITLE
Hang when awaiting code in Initialize in 5.2

### ISSUE THREAD

**Issue by jimbobbennett** [MvvmCross/MvvmCross#2182]
### Steps to reproduce

1. Use the Countr.sln solution from https://github.com/jimbobbennett/MvvmCross52_hang

2. Run the Android app using the default Accelerated x86 emulator that ships with a clean install of VS for Mac (haven't tried it on devices/Windows yet)

### Expected behavior
The app should run and show the first view

### Actual behavior
The app hangs when trying to load data from a SQLite database inside CountersRepository.GetAll(). If you downgrade to MvvmCross 5.1.1 (and change Prepare in CounterViewModel to Initialize so that it compiles), the hang doesn't happen and the view is shown correctly.

### Configuration

**Version:** 5.2

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by jimbobbennett** [comment]
Update - it seems to be related to SQLite-Net. I've now managed to reproduce it in another app by making SQLite calls inside Initialize. If I change my initialise to do everything inside a call to Dispatcher.RequestMainThreadAction then everything works.

**Comment by jimbobbennett** [comment]
The issue seems to be related to awaiting async methods. If all method calls use configureawait(false) then the problem goes away. Another workaround is to use Dispatcher.RequestMainThreadAction() or Task.Run().ConfigureAwait(false) to wrap the work done in the Initialize method.

**Comment by Ruddy2007** [comment]
@jimbobbennett I am seeing this exact issue on UWP now running 7.1.2. Very odd.

**Comment by Cheesebaron** [comment]
@Ruddy2007 should be fine except for in the very first ViewModel you present.
