### ISSUE TITLE
Where is that IFactory<T>?

### ISSUE THREAD

**Issue by fabsenet** [MvvmCross/MvvmCross#2186]
I was reading through the [docs on IoC](https://github.com/MvvmCross/MvvmCross/blob/8b79f1804dee7252f4c697c630f007c01bc7f163/docs/_documentation/fundamentals/dependency-injection.md).

the last sample there is

```cs
public class FooSingleton : IFooSingleton
{
    private readonly IFactory<IBar> _barFactory;

    public FooSingleton(IFactory<IBar> barFactory)
    {
        _barFactory = barFactory;
    }

    public void DoFoo()
    {
        var bar = _barFactory.Create();
        bar.DoStuff();
    }
}
```

I really would like to use this in my own code and I seem to need that `IFactory<T>`. I cannot find it anywhere in the code, am I supposed to write it myself?

### Expected behavior
`IFactory<T>` is provided in the library

### Actual behavior
`IFactory<T>` is either not there or well hidden

### Configuration

**Version:** 5.2.0

**Platform:** 
- [X] WPF
- [ ] iOS
- [ ] Android
- [ ] UWP

**Comment by Cheesebaron** [comment]
I think you've misread the documentation. `IFactory<T>` is something _you_ need to provide.
