### ISSUE TITLE
IMvxNavigationService Stack Issue in Xamarin Forms

### ISSUE THREAD

**Issue by anee146** [MvvmCross/MvvmCross#2202]
How can I re-use the same view model without instantiating with new view-model on navigating to same view-model again and again.
The project was created with Xamarin Forms. The Core project contains views & view-models. We're using IMvxNavigationService to navigate view-model to view-model.

### Steps to reproduce

1. Navigate to view-model (A).

2. On Instance of (IMvxNavigationService).Navigate(), new instance of view-model of A is getting created. Is there any way to reuse the same view-model of A again.

### Expected behavior
MvxNavigationService should re-use the existing view-model in the stack

### Actual behavior
A new instance of the view-model is getting created each time and stack is getting added.

### Configuration
**Version:** 
Xamarin Forms 2.3.4.270
MvvmCross 5.2

**Platform:** 
- [x] Xamarin Forms
- [x] iOS
- [x] Android

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

**Comment by anee146** [comment]
Thanks Cheesebaron.

> Note: How can I re-use the same view model without instantiating with new view-model on navigating to same view-model again and again.
The project was created with Xamarin Forms. The Core project contains views & view-models. We're using IMvxNavigationService to navigate view-model to view-model.

### Steps to reproduce

1. Navigate to view-model (A).

2. On Instance of (IMvxNavigationService).Navigate(), new instance of view-model of A is getting created. Is there any way to reuse the same view-model of A again.

### Expected behavior
MvxNavigationService should re-use the existing view-model in the stack

### Actual behavior
A new instance of the view-model is getting created each time and stack is getting added.

### Configuration
**Version:** 5.2

**Platform:** 
- [ ] Xamarin Forms
- [ ] iOS
- [ ] Android

**Comment by anee146** [comment]
How can I solve this issue?

**Comment by martijn00** [comment]
This is how MvvmCross works.
