### ISSUE TITLE
MvxTabLayoutPresentationAttribute title localization

### ISSUE THREAD

**Issue by belhunter** [MvvmCross/MvvmCross#2211]
I'm in progress of switching to new Android presenter. I'm creating a tab like in the Playground sample ([Tab1View.cs](https://github.com/MvvmCross/MvvmCross/blob/8dd5707ebd8d2158cf0e5197060295bad4ba7f36/TestProjects/Playground/Playground.Droid/Views/Tab1View.cs)).

But I see that Title parameter is string for MvxTabLayoutPresentationAttribute, so I don't have possibility to:

- Set title based on .NET resource file
- Set title based on Android string resources

As I understand I can just hardcode title without possibility to set it run-time based on current user's locale. Is it possible to provide custom title for MvxTabLayoutPresentationAttribute without hardcoding it?

### Configuration

**Version:** 5.2

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
What you can do for now is use the `IMvxOverridePresentationAttribute` to retrieve the translation: https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Playground/Playground.Droid/Views/OverrideAttributeView.cs#L27

We might need to look at a better solution for this use case.

**Comment by belhunter** [comment]
I believe that passing string resource id would be best solution here.

**Comment by martijn00** [comment]
That would just solve a tiny bit. Lots of people us the Json and ResxLocaliztion plugins, and those would not work with that.

**Comment by belhunter** [comment]
I'll try to create solution that will cover these cases. At the same time I'm not sure that it is possible to pass not static value as attribute parameter.

**Comment by vurf** [comment]
maybe make as iOS? with interface IMvxTabBarItemViewController?
