### ISSUE TITLE
Xamarin SideBar incorrect width of menu during first time launch

### ISSUE THREAD

**Issue by kirillgorbushko** [MvvmCross/MvvmCross#2215]
### Steps to reproduce

1. Create project with XamarinSidebar

2. Start project within RootPanel  

>     [MvxSidebarPresentationAttribute(MvxPanelEnum.Center, MvxPanelHintType.ResetRoot, true)]

or with

>     [MvxSidebarPresentation(MvxPanelEnum.Center, MvxPanelHintType.ResetRoot, true, MvxSplitViewBehaviour.Master)]

3. Switch to (if started with RootPanel)

>     [MvxSidebarPresentation(MvxPanelEnum.Center, MvxPanelHintType.ResetRoot, true, MvxSplitViewBehaviour.Master)]

4. Observe changing size of 

>     [MvxSidebarPresentation(MvxPanelEnum.Left, MvxPanelHintType.PushPanel, false)]

firstly it's draw with default width 260, after apply width that is set in the IMvxSidebarMenu for public int MenuWidth property, but opened width of panel are still incorrect

5. Close menu

6. Open menu -> now everything is ok
Bug persistent and occurs every time.

###Sample 

[Sample](https://drive.google.com/file/d/0B1GU18BxUf8hbHhmYzVoV1p2LWs/view?usp=sharing
)

###Debug info

Set width to 300, on OpenFirstTime i see

> > (controller as UIViewController).ChildViewControllers[0]
> {<SidebarNavigation_SidebarController: 0x10453d3a0>}
> 	base: {UIKit.UIViewController}
> 	ContentAreaController: {<MvvmCross_iOS_Views_MvxNavigationController: 0x105222600>}
> 	DarkOverlayAlpha: 0
> 	DisablePanGesture: true
> 	Disabled: false
> 	FlingPercentage: 0,5
> 	FlingVelocity: 800
> 	GestureActiveArea: 50
> 	HasDarkOverlay: false
> 	HasShadowing: true
> 	IsOpen: false
> 	MenuAreaController: {<MenuViewController: 0x10453c2c0>}
> 	MenuLocation: SidebarNavigation.MenuLocations.Left
> 	MenuWidth: 260
> 	ReopenOnRotate: true
> 	Non-public members: 
> 	IEnumerator: 
> > 

### Expected behavior
Correct resizing of width for side menu

### Actual behavior
Incorrect  (with latency) resizing of width for side menu

### Configuration

**Version:** 5.1.1 (XamarinSideBar)

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by kirillgorbushko** [comment]
current workaround

```
private void AdjustMenuWidthIfNeeded()
        {
            var controller = Mvx.Resolve<IMvxSidebarViewController>() as UIViewController;
            if (controller != null)
            {
                foreach (var vc in controller.ChildViewControllers)
                {
                    var sideBar = vc as SidebarController;
                    if (sideBar != null)
                    {
                        sideBar.View.BackgroundColor = this.View.BackgroundColor;
                            sideBar.MenuWidth = 300;
                            this.View.LayoutIfNeeded();
                    }
                }
            }
        }
```

**Comment by artmon** [comment]
> current workaround

Where must I call this method?

**Comment by kirillgorbushko** [comment]
I put in in to 

```
        public virtual void MenuWillOpen()
        {
            this.AdjustMenuWidthIfNeeded();
           ...
        }
```

**Comment by artmon** [comment]
Thanks! It works for me.

**Comment by nmilcoff** [comment]
Can you please upload your sample to GitHub? @kirillgorbushko

**Comment by StevenKek** [comment]
@kirillgorbushko 's workaround is almost perfect. I don't experience this issue when opening the sidebar menu by button anymore. However when performing the slide to open gesture for the sidebar menu, the issue persists. Again, only first time the swipe to open is performed.

**Comment by kirillgorbushko** [comment]
a code sample is something like:

```
public class MenuViewController<T> : MvxViewController<T>, IMvxSidebarMenu
        where T : class, IMvxViewModel
    {
        public virtual UIImage MenuButtonImage => null;

        public virtual bool AnimateMenu => true;

        public virtual float DarkOverlayAlpha => 0;

        public virtual bool HasDarkOverlay => false;

        public virtual bool HasShadowing => true;

        public virtual bool DisablePanGesture => true;

        public virtual bool ReopenOnRotate => true;

        public int MenuWidth => DeviceHardware.IsSmallDevice ? Constants.MenuWidthFor5OrEarlier : Constants.MenuWidth;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.View.Hidden = true;
        }

        public virtual void MenuWillOpen()
        {
            this.AdjustMenuWidthIfNeeded();
            this.View.Hidden = false;
        }

        public virtual void MenuDidOpen()
        {
            this.EnablePanGestureIfPossible(true);
        }

        public virtual void MenuWillClose()
        {
        }

        public virtual void MenuDidClose()
        {
            this.View.Hidden = true;

            this.EnablePanGestureIfPossible(false);
        }

        private void AdjustMenuWidthIfNeeded()
        {
            if (Mvx.Resolve<IMvxSidebarViewController>() is UIViewController controller)
            {
                foreach (var vc in controller.ChildViewControllers)
                {
                    if (vc is SidebarController sideBar)
                    {
                        sideBar.View.BackgroundColor = this.View.BackgroundColor;
                        UIView.Animate(0.3, () =>
                        {
                            sideBar.MenuWidth = DeviceHardware.IsSmallDevice ? Constants.MenuWidthFor5OrEarlier : Constants.MenuWidth;
                            this.View.LayoutIfNeeded();
                        });
                    }
                }
            }
        }

        private void EnablePanGestureIfPossible(bool enable)
        {
            if (Mvx.Resolve<IMvxSidebarViewController>() is UIViewController controller)
            {
                foreach (var vc in controller.ChildViewControllers)
                {
                    if (vc is SidebarController sideBar)
                    {
                        sideBar.DisablePanGesture = !enable;
                    }
                }
            }
        }

        private struct Constants
        {
            public const int MenuWidth = 300;
            public const int MenuWidthFor5OrEarlier = 260;
        }
    }
```

**Comment by StevenKek** [comment]
@kirillgorbushko Thank you! If I disable the pan gesture for sidebar opening, then your workaround works always. But yeah, I had to disable the pan gesture :(

**Comment by yyuzyk** [comment]
Is possible to scale CenterViewModel during open sidebar?

**Comment by yyuzyk** [comment]
@kirillgorbushko @martijn00 
Is possible to scale CenterViewModel during open sidebar?
