### ISSUE TITLE
Exception in MvxAppCompatDialogFragment<T>

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross#2220]
An instance of the above class will throw an exception with the new Android View Presenter.

### Steps to reproduce

1. Create a class of type MvxAppCompatDialogFragment<<T>>. Decorate with [MvxDialogFragmentPresentation]

2. Show and await the dialog using the new Navigation Service functions

3. Close the dialog by calling Close(somevaluetoreturn)

### Expected behavior
The "somevaluetoreturn" should be returned to the awaited caller

### Actual behavior
Exception is thrown

No constructor found for Weighin.Android.Views.LoginFragment::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)

### Configuration

**Version:** 5.2

**Platform:** 
- [ x] Android

It would appear to me that the implementation of MvxAppCompatDialogFragment<<T>> is missing the protected constructor  MvxAppCompatDialogFragment (IntPtr javaReference, JniHandleOwnership transfer)

**Comment by martijn00** [comment]
I've fixed this in #2221 but i think as a workaround you can add this ctor to your own FragmentDialog.

**Comment by erviem99** [comment]
Implementing the ctor myself would require that I somehow could call the ctor on AppCompatDialogFragment (above base) directly from my own fragment. I don't think that is possible in c#.
