### ISSUE TITLE
Wrong host activity gets shown

### ISSUE THREAD

**Issue by alexkivikoski** [MvvmCross/MvvmCross#2222]
The new Android presenter has caused me some problems when sharing same TabViewModels in different TabRootViewModels.

### Steps to reproduce

1. Create TabsRootAViewModel and TabsRootBViewModel. Both host Tab1ViewModel and Tab2ViewModel. Other than that the setup is same as the [PlayGround example](https://github.com/MvvmCross/MvvmCross/tree/master/TestProjects/Playground)

2. Navigate to TabsRootBViewModel

3. Navigate to the Tab view models (ShowInitialViewModels)

### Expected behavior
TabsRootBView is shown with Tab1View and Tab2View as fragments

### Actual behavior
TabsRootAView is shown with Tab1View and Tab2View as fragments

### Configuration

**Version:** 5.2

**Platform:** 
- [ ] iOS
- [ x] Android
- [ ] WPF
- [ ] UWP

### The cause

Both TabsRootAView and TabsRootBView use the same Resource Id for the TabLayout and ViewPager.

The new Android presenter runs ShowHostActivity for TabsRootAView when I show the tabs in either TabsRootAView or TabsRootBView.

Seems like that is why TabsRootAView gets shown when I initially navigated to TabsRootBViewModel.

**Comment by martijn00** [comment]
This seems like a bug as it is a use case we try to take in account.
