### ISSUE TITLE
OnStart is not called for a Xamarin Forms iOS application

### ISSUE THREAD

**Issue by MichaelBTR** [MvvmCross/MvvmCross#2223]
### Steps to reproduce
1. Create a new Xamarin Forms project using MvvmCross

2. Derive from the MvxFormsApplication class and override the OnStart method so that there is code that should be executed when the app starts.  

3. Run the app on iOS

**Note**: an example is available from https://github.com/MichaelBTR/MvxForms. I've forked the repo from https://github.com/martijn00/MvxForms, updated to MvvmCross 5.2 and added local notifications to be displayed. I believe the issue also occurred in 5.1.1

### Expected behavior
The statements within the OnStart override is executed

### Actual behavior
The statements within the OnStart override is not executed

### Configuration

**Version:** 5.2

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
The code for OnStart is called from the Xamarin.Forms platform. If it is not called in your case i would think this is a bug on their side. Can you look into that to confirm?

**Comment by MichaelBTR** [comment]
Apologies, I should've clarified that I'm aware it's a Xamarin.Forms platform method and that I've noticed that it works fine when creating a Forms app where the application class doesn't derive from MvxFormsApplication (e.g. using the out of the box Master Detail template in Visual Studio). I've updated the sample that I've forked from your repository to include another folder/projects to demonstrate that it works when not deriving from MvxFormsApplication

**Comment by sergio11** [comment]
I have the same problem for MvvmCross.Forms 5.1.0
