### ISSUE TITLE
IMvxOverridePresentationAttribute not working of any Android view

### ISSUE THREAD

**Issue by Plac3hold3r** [MvvmCross/MvvmCross#2225]
The `IMvxOverridePresentationAttribute` override of the views attribute never gets executed. Effects both droid presenters, `MvxAppCompatViewPresenter` and `MvxAndroidViewPresenter`.

### Steps to reproduce

1. Add `IMvxOverridePresentationAttribute` to a fragment or activity.

2. Implement the interface `IMvxOverridePresentationAttribute`

3. Run app and see `PresentationAttribute` is never executed

### Expected behavior
Adding and implementing `IMvxOverridePresentationAttribute` should according to the [docs](https://www.mvvmcross.com/documentation/presenters/android-view-presenter?scroll=600#override-a-presentation-attribute-at-runtime) allow you to override the current attribute being used.

### Actual behavior
The `PresentationAttribute` of `IMvxOverridePresentationAttribute` is never executed.

### Configuration

**Version:** 5.2

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

### _Additional Investigation Notes_

Looking into the implementation there are multiple issues.

1.  **_Detection_** - The [code](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Droid/Droid/Views/MvxAndroidViewPresenter.cs#L243) that tries to detect if this interface is present is failing and always returns false. The detection of the presence of `IMvxOverridePresentationAttribute` can fixed with the following code: 

`if (attribute.ViewType?.GetInterface(nameof(IMvxOverridePresentationAttribute)) != null)` 

2. **_Instance Required_** - Now that we have detected that the view is using the `IMvxOverridePresentationAttribute` we run into the bigger problem. In order to execute against this interface we require the existence of an instance of the view. At the moment the code is attempting to execute against the [view type](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Droid/Droid/Views/MvxAndroidViewPresenter.cs#L245) which will always fail, as an instance of the type is required.  

**Android architecture difference**

Android architecture differs to that of iOS and Windows in a way that makes the use if `IMvxOverridePresentationAttribute` limited. For example in iOS the view controller can be created up front and then the attribute evaluated to determine where to place the new view controller. Unlike iOS androids view do not share the same type (i.e `MvxFragment`, `MvxAppCompatActivity` or `MvxDialogFragment`). Each type differs in how it get created. The result is that the attribute gets evaluated before the view instance is created. 

I have create a pull request #2226 with a ~~partial~~ full workaround. As suggested by @martijn00 the presenters now create an instance of the class and retrieve the override attribute then continues the normal flows of the various view type.

**Comment by martijn00** [comment]
Thanks for investigating this! We really could use some help improving the new presenter. Some parts like `IMvxOverridePresentationAttribute` are not tested very well and we should find some fixes like the ones you suggest. Also about the shared elements, i think we need a separate issue for that. It's easier to fix little small issue's than one big with everything.

**Comment by Plac3hold3r** [comment]
@martijn00 agreed, I'll move out the shared elements to a separate issue, so that is one just deals with the use of `IMvxOverridePresentationAttribute` in general for Android.

**Comment by martijn00** [comment]
Would it be an idea to instantiate the view using Activator and retrieve the Attribute from it and then just dispose that instance and continue running the presenter code?

**Comment by Plac3hold3r** [comment]
That's a nice idea, as it would solve the Activity issue as well as the timing issue for fragments. I do believe the restriction on the type of attribute being use would still need to apply. I.e. can not switch a fragment attribute with a dialog attribute. They are at the root both fragments so I'm not 100% is it would not be allowed.

**Comment by martijn00** [comment]
Can you update your PR to use this? The restrictions off course apply, but my original intent was never to support custom attributes of complete different types, but rather inherit some attribute and add your own custom properties to it.

**Comment by Plac3hold3r** [comment]
Fixed via PR #2226
