### ISSUE TITLE
MvvmCross 5.x navigation use Prepare and Initialize

### ISSUE THREAD

**Issue by jz5** [MvvmCross/MvvmCross#2228]
### Steps to reproduce

1. Use `ShowViewModel<TViewModel, TParameter>(new TParameter()))` navigation

2. `Prepare` and `Initialize` are called.

### Actual behavior

[Navigation with parameters using complex parameter object](https://www.mvvmcross.com/documentation/fundamentals/navigation#navigation-with-parameters---using-a-complex-parameter-object) (`ShowViewModel<TViewModel, TParameter>(new TParameter())`) use `Prepare` method not `Init` for the parameter receiving. And `Initialize` also called.

Is it by design? Currently this behavior not match for document.

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
I don't really get what the problem is... Are you using ShowViewModel and it is not working with Prepare?

**Comment by jz5** [comment]
About MvvmCross **4.x** navigations

Navigation with simple parameter object:
* Call `ShowViewModel<DetailViewModel>(new DetailParameters() { Index = 2 });`
    *  -> Get prameter by `public void Init(DetailParameters parameters)`

Navigation with anonymous parameter object : 
* Call `ShowViewModel<DetailViewModel>(new { index = 2 });` 
    * ->  Get prarameter by `public void Init(int index)`

There are use ShowViewModel and Init for navigation.
But the following use ShowViewModel and Prepare for navigation.

Navigation with complex parameter object:  
* Call `ShowViewModel<TViewModel, TParameter>(new TParameter());` 
    * -> Get parameter by `public override void Prepare(TParameter parameter)`

>Are you using ShowViewModel and it is not working with Prepare?

It works. But I think that it seems asymmetry. This is the problem I think. If it is OK, document needs update.

**Comment by fonix232** [comment]
@jz5 you're not reading the right part of the documentation. 

Documentation has been updated, but 4.x stuff was kept on the bottom for future reference (not everyone switches to 5.x immediately). 5.x uses the navigation pattern detailed on top of the documentation page you linked:

- Use `Prepare()` for stuff that should happen before the view appears, and for passing arguments. E.g. you can pass a complex object and fill your binding properties on the new VM here

- Use `Initialize()` for heavier tasks, say, network queries, or anything that would run async after the view appears.

**Comment by jz5** [comment]
@fonix232 I think that 5.x includes 4.x navigation for compatibility. Is it wrong?

**Comment by nmilcoff** [comment]
So the problem is that in this case:

    Navigation with complex parameter object:

    Call ShowViewModel<TViewModel, TParameter>(new TParameter());
        -> Get parameter by public override void Prepare(TParameter parameter)

Uses Prepare instead of Init. Am I right? 🤔

**Comment by nmilcoff** [comment]
@jz5 any update about my comment?

**Comment by jz5** [comment]
The problem occurs using the navigation with complex parameter object.
If MvvmCross 5.x should be compatible (should be contains) with 4.x navigation, current 5.x is not compatible.
It should be use `Init`.
If MvvmCross 5.x does not need to be compatible with 4.x navigation, it is no problem.

**Comment by nmilcoff** [comment]
As we're moving forward with the new MvxNavigationService, we are not providing support for mixing navigation systems (ShowViewModel / MvxNavigationService.Navigate).
