### ISSUE TITLE
Android Support Libraries 25.4.0.2 [Question]

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2231]
Are there any plans to update the Android projects to reference the newer Xamarin.Android Support libraries version 25.4.0.2? Are you accepting pull requests to make this change, or is there some issue preventing updating the Xamarin.Android Support libraries to version 25.4.0.2?

**Comment by martijn00** [comment]
The current Android Support library version should just be a minimum requirement and in your own app you can update the libraries to 25.4.0.2, but that is in theory. It could be that there are breaking changes in the signature or behaviour that prevent this, but i haven't seen them yet.
