### ISSUE TITLE
Parameterless Prepare() not called

### ISSUE THREAD

**Issue by domenico-barbieri** [MvvmCross/MvvmCross#2233]
### Steps to reproduce

1. Extend non generic MvxViewModel:
`public class  MyViewModel : MvxViewModel {}`

2. Override Prepare()
`        public override void Prepare()
        {
            base.Prepare();
        }`

3. Navigate to the view model:
`ShowViewModel<MyViewModel>();`

### Expected behavior
Prepare() should be called.

### Actual behavior
Prepare() isn't called.

### Configuration

**Version:** 5.2

**Platform:** 
- [x] iOS
- [x] Android
- [x] WPF
- [x] UWP

**Comment by martijn00** [comment]
If you use the `IMvxNavigationService` this will work as expected.
