### ISSUE TITLE
Can't install MvvmCross 5.2.1 in Xamarin Forms PCL Project

### ISSUE THREAD

**Issue by anee146** [MvvmCross/MvvmCross#2240]
Unable to add MvvmCross latest packages in xamarin forms project.
### Steps to reproduce

1. Created xamarin forms (PCL) project.

2. Updated Xamarin Forms Version to 2.4.0.282

3. Trying to install MvvmCross 5.2.1 package in the following projects PCL, Android & iOS.

### Expected behavior
It should get installed.

### Actual behavior
Could not install package 'MvvmCross.Forms 5.2.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

### Configuration
VS 2017 Enterprise 2017 Ver 15.3.5
Xamarin 4.7.9.45
Xamarin Android SDK 7.4.5.1
Xamarin iOS & Xamarin MAC Sdk 11.0.0.0

**Platform:** 
- [x] iOS
- [x] Android

**Comment by Cheesebaron** [comment]
Use a better PCL profile or switch to NET Standard.
