### ISSUE TITLE
[Android] Dialog doesn't survive screen orientation change

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2246]
Here is a sample demonstrating the issue:
https://github.com/tbalcom/MvxDialogBackButton

### Steps to reproduce

1. Click the "Show Dialog" button.

2. Rotate the device to change the screen orientation from landscape to portrait, or from portrait to landscape.

3. Finish the dialog using the Yes or No button. Look at the result output to the debug window from the following code: `Mvx.Trace($"ConfirmationViewModel navigation returned {confirmationResult}.");`

### Expected behavior
The dialog should remain on the screen after the rotation has finished, and the correct navigation result should be returned to the caller.

### Actual behavior
There are two scenarios:
#### Using `RetainInstance`
If I use `RetainInstance` then the dialog is closed permanently when the device is rotated and the `Task` is left incomplete.

#### Without using `RetainInstance`
If I don't use `RetainInstance` then the dialog is not closed permanently when the device is rotated. However, the navigation result is **always** `null` if the screen orientation changes at least once.

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [ x ] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
Accordingly to [this answer](https://stackoverflow.com/a/44229759/5000213), the rotation problem seems to be fixed by adding this code (I've personally tested it):

```c#
public override void OnDestroyView()
        {
            if (Dialog != null && RetainInstance)
            {
                Dialog.SetDismissMessage(null);
            }
            base.OnDestroyView();
        }
```

That said, I don't think we should include this workaround in the source code...
