### ISSUE TITLE
Xamarin.Forms: TextCell Command does not work in latest update

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2248]
Xamarin.Forms: 2.4.0.282
iOS: 11 / iPhone X Simulator (also tested on iPhone 8 Simultor)
MvvmCross: 5.2.1 (works in 5.1.1, also with latest Xamarin.Forms / iOS)
Project / Repository: https://github.com/Sebastian1989101/OpenGeoDB-App (just update all dependencies to test it if you want)

-----

I'm using a ListView with TextCells in it. In the previous version of MVX it works to use the Commands there. It works in version 5.1.1 but does not in 5.2.1. This is the XAML I use: 

```
        <ListView Grid.Row="1" ItemsSource="{Binding Data}" HasUnevenRows="false" IsGroupingEnabled="true" SeparatorVisibility="Default"
                  GroupDisplayBinding="{Binding Category}" GroupShortNameBinding="{Binding ShortCategory}">

            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextCell Text="{Binding Key}" Detail="{Binding Path=., Converter={StaticResource ZipCodeTextConverter}}"
                              Command="{Binding BindingContext.ShowDetailsCommand, Source={x:Reference Page}}" CommandParameter="{Binding Key}" />
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```

The command is not even triggered.

**Comment by martijn00** [comment]
So what you are saying is that 5.2.1 does not work with Forms 2.4, but 5.2.1 works with Forms 2.3.4? What about 5.1.1 with Forms 2.4?

**Comment by Sebastian1989101** [comment]
I don't know if MVX 5.2.1 works with any Xamarin Forms version (at least for the TextCell Command Binding). But MVX 5.1.1 seems to work with any Xamarin Forms version (for this case).

**Comment by martijn00** [comment]
In terms of changes for Forms, https://github.com/MvvmCross/MvvmCross/pull/2118 is probably what changed most, but i can't see how it affected this.

**Comment by Sebastian1989101** [comment]
The only thing I can say yet is that it works as long as I keep MVX 5.1.1. As soon as I update to 5.2.1 it won't work anymore. I know I have to modify my ViewModels with "void Prepare" instead of "Task Initialize" and I also have to change "RegisterAppStart" to something with Navigation in it's name (at least this is what the compiler tells me todo). I will test it with a custom CommandCell instead of the TextCell (maybe there is any different or something).

**Comment by Sebastian1989101** [comment]
Just did a bit of debugging. Seems like the Command is null (this explains why it is not executed. But I don't understand 100% why it is null because it works fine with MVX 5.1.1).

**Comment by Sebastian1989101** [comment]
Just found the issue... and man I should stop to develop after midnight... Maybe I should use my brain sometimes and use ViewModel and not BindingContext if there is a property with such a name.. 

Command="{Binding BindingContext.ShowDetailsCommand, Source={x:Reference Page}}"

->

Command="{Binding ViewModel.ShowDetailsCommand, Source={x:Reference Page}}"

**Comment by martijn00** [comment]
Hmmm. So also this https://github.com/MvvmCross/MvvmCross/pull/2218 got in. It introduces a MvxListView to bind commands. Is that related?

**Comment by martijn00** [comment]
@Sebastian1989101 Any update on this?

**Comment by Sebastian1989101** [comment]
Still not had the time to try the MvxListView. As mentioned above, it works if I use "ViewModel." instead of "BindingContext." with the default Forms ListView.
