### ISSUE TITLE
Bug with toolbar on android MvvmCross 5.2.1 and Forms 2.4.0.282

### ISSUE THREAD

**Issue by JTOne123** [MvvmCross/MvvmCross#2252]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Create mvvmcross + forms project based on latest sources of both

2. And toolbar item with an icon (without the icon everything is ok)

3. Android should be AppCompact (based on MvxFormsAppCompatActivity)

Here's example 
https://github.com/JTOne123/XamFormsMvxTemplate/blob/mvvmAndoridIconToolbarBug/MvxForms.sln

Page with toolbar
https://github.com/JTOne123/XamFormsMvxTemplate/blob/mvvmAndoridIconToolbarBug/MvxForms/MvxForms.Core/Pages/MainPage.xaml

### Expected behavior
Tell us what should happen

No crash

### Actual behavior
Tell us what happens instead

I have got a crash with next stack trace:

10-06 14:40:58.898 I/MonoDroid(23252): UNHANDLED EXCEPTION:
10-06 14:40:58.962 I/MonoDroid(23252): System.NullReferenceException: Object reference not set to an instance of an object.
10-06 14:40:58.962 I/MonoDroid(23252):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00017] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:202 
10-06 14:40:58.962 I/MonoDroid(23252):   at Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0000e] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:73 
10-06 14:40:58.962 I/MonoDroid(23252):   at Android.Views.ViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00008] in <d278c06ad5684d6882c743a94a93ebc2>:0 
10-06 14:40:58.962 I/MonoDroid(23252):   at (wrapper dynamic-method) System.Object:e6a8147a-75b0-4462-83a1-9b65d9b31f89 (intptr,intptr,bool,int,int,int,int)

PS: If revert back xamarin.forms to 2.3.4, the crash will be disappeared, but the icon is hidden anyway.

### Configuration

**Version:** 5.2.1

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
And this works in an Forms App without MvvmCross?

**Comment by JTOne123** [comment]
Yes, sure

**Comment by Yves-Be** [comment]
I seem to be bumping into the same issue.
Everything is fine in a new Xamarin forms solution, but the Android app crashes after adding MvvmCross.
Removing any icon from the toolbar allows the app to run again.

**Comment by JTOne123** [comment]
My best guess is mvx touching some android object directly but should do it via appcompat wrapper.

I added this file to my proj and use it https://github.com/MvvmCross/MvvmCross/blob/8dd5707ebd8d2158cf0e5197060295bad4ba7f36/MvvmCross-Forms/MvvmCross.Forms.Droid/MvxFormsAppCompatActivity.cs

The exception has disappeared but toolbar icons are invisible until navigating to another page.

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2305
