### ISSUE TITLE
Unable to update nuget packages from version 5.1.1 to version 5.2.1 (ANDROID)

### ISSUE THREAD

**Issue by stefan89** [MvvmCross/MvvmCross#2253]
### Steps to reproduce

1. update MvvmCross nuget packages in an Xamarin Android project from v5.1.1 to 5.2.1

### Expected behavior
Updated to the latest MvvmCross version

### Actual behavior
Cannot update. It seems there is no newer version for the MvvmCross.Droid.Shared assembly

Error:
Unable to resolve dependencies. 'MvvmCross.Core 5.2.1' is not compatible with 'MvvmCross.Droid.Shared 5.1.1 constraint: MvvmCross.Core (= 5.1.1)'.

### Configuration

**Version:** 5.2.1

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by tbalcom** [comment]
The [5.2 release notes](https://www.mvvmcross.com/mvvmcross-52-release/) say you should force remove the MvvmCross.Droid.Shared package before updating.

**Comment by nmilcoff** [comment]
Closing this issue as it was answered by @tbalcom. Please open a new one if you find an issue upgrading to MvvmCross 5.2.1.
