### ISSUE TITLE
MvxViewModel<TParameter>.Init should be removed

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2257]
`MvxViewModel<TParameter>` is calling Prepare and Initialize, which is already called by NavigationService.

The class is now useless and error prones. It should be removed asap.

### Configuration

**Version:** 5.2.1

**Platform:** 
- [X] iOS
- [X] Android
- [X] WPF
- [X] UWP

**Comment by nmilcoff** [comment]
Isn't that class still necessary when using ShowViewModel? Would it be an idea to prevent it from calling Prepare and Initialize until we move 100% to MvxNavigationService?
