### ISSUE TITLE
Crash MvxTabBarViewController ViewWillDisappear

### ISSUE THREAD

**Issue by vurf** [MvvmCross/MvvmCross#2267]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. We have use custom transition animation

2. I attach crash report from hockeyApp

Application Specific Information:
*** Terminating app due to uncaught exception 'System.NullReferenceException', reason: 'System.NullReferenceException: Object reference not set to an instance of an object'

Xamarin Exception Stack:
  at MvvmCross.iOS.Views.MvxTabBarViewController.ViewWillDisappear (System.Boolean animated) <0xa43880 + 0x0007c> in <cc93fc0f0e404b268022d40c600485a2#978fa01e13e3be0fdac4d87bbafb57aa>:0 
  at (wrapper managed-to-native) ObjCRuntime.Messaging:objc_msgSend (intptr,intptr,bool)
  at UIKit.UIViewControllerContextTransitioningWrapper.CompleteTransition (System.Boolean didComplete) <0x5c0988 + 0x0001f> in <efe453a9c69e480faa5cd4d1a0c93b4a#978fa01e13e3be0fdac4d87bbafb57aa>:0 
  at iOS.Custom.Interaction.PresentSwipeTransitionDelegate+<>c__DisplayClass28_0.<AnimatePresentationWithTransitionContext>b__1 (System.Boolean completed) <0x4ee6c8 + 0x0007f> in <66fc9dd6e88d4ba381f3d67f6bccfd34#978fa01e13e3be0fdac4d87bbafb57aa>:0 

And I am thinking that crash called from code and presenter need check on null

public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);

            if (IsMovingFromParentViewController)
            {
                if (Mvx.Resolve<IMvxIosViewPresenter>() is MvxIosViewPresenter presenter)
                {
                    presenter.CloseTabBarViewController();
                };
            }
        }

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Version:** 5.x

**Platform:** 
- [X] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
Thanks for reporting this! Are you using a custom presenter that does not inherit from `MvxIosViewPresenter`?

**Comment by vurf** [comment]
@nmilcoff , I am inherit from MvxBaseIosViewPresenter (: MvxViewPresenter, IMvxIosViewPresenter, IMvxViewPresenter, IMvxCanCreateIosView, IMvxIosModalHost)

**Comment by nmilcoff** [comment]
@vurf how are you creating your ViewPresenter? 
Are you overriding the method `RegisterPresenter` in your Setup without calling the base implementation?

**Comment by nmilcoff** [comment]
Sorry, I didn't mean to really close this issue with that commit (yet).

**Comment by vurf** [comment]
@nmilcoff , i am not override registerPresenter. In AppDelegate i call Setup with (MvxApplicationDelegate applicationDelegate, IMvxIosViewPresenter presenter)

**Comment by nmilcoff** [comment]
Can you please check if the issue still exists in version 5.3?
