### ISSUE TITLE
Xamarin Sidebar doesn't opens at first launch

### ISSUE THREAD

**Issue by DarthRamone** [MvvmCross/MvvmCross#2268]
To be honestly, I'm not sure that it's your problem, but behaviour is very strange. When I'm going through my login view controller and push new one with reseting root, my menu button doesn't open menu. It definitely enabled and there is tap animation on button, but nothing happens. When I restart application - it works. It works with iOS 10, but not 11.

I've tried to add MvvmCross.iOS.Support.Xamarin.Sidebar project to my solution and debug it, and I've found that [action for UIBarButtonItem](https://github.com/MvvmCross/MvvmCross/blob/e4c2e54536a11321ed0a64653866e108a61bb47c/MvvmCross-iOSSupport/MvvmCross.iOS.Support.XamarinSidebar/Extensions/ViewControllerExtensions.cs#L42) doesn't called. And here is the  weirdest thing, I've tried to create UIBarButtonItem with UIButton:

```
var btn = new UIButton();
btn.SetImage(mvxSidebarMenu.MenuButtonImage, UIControlState.Normal);
btn.TouchUpInside += (sender, e) => { the things };
barButtonItem = new UIBarButtonItem(btn);

```
And you know what? It works. I've no idea what's going on, may be you can tell me? 
Thank you. 

### Expected behavior
Menu should open

### Actual behavior
It doesn't

### Configuration
iOS 11

**Version:** 5.x

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by KennethKr** [comment]
Maybe my issue is related: https://github.com/MvvmCross/MvvmCross/issues/2247

**Comment by DarthRamone** [comment]
@KennethKr do you have any workarounds? 

Also, if I go to some screen at first launch, "menu" button changes to back button, and it doesn't work either.

**Comment by KennethKr** [comment]
No workarounds, I've manually added the menu choice for now. However, in my case, the left menu choice sometimes opens the drawer on the right.

**Comment by DarthRamone** [comment]
This one probably somehow related: https://github.com/MvvmCross/MvvmCross/issues/2234

**Comment by DarthRamone** [comment]
First app launch is looks like this:

login/register flow -> reset root -> main flow

after restart it's going to "main flow" directly, so we are not reseting root. I believe, that problem is because of root reseting, but I can't figure out where.

**Comment by DarthRamone** [comment]
Lol, it works, but only with long-tap. What's going on

**Comment by nmilcoff** [comment]
You can leave your Gesture Recognizers there, but you need to configure them not to cancel event touches by setting the property `CancelsTouchesInView` to false. This seems to be a change introduced by iOS 11.
