### ISSUE TITLE
Rotation crashes device

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross#2274]
With MvvmCross 5.3.0 rotating the device will crash when displaying a generic MvxAppCompatDialogFragment on Android.

### Steps to reproduce

1. Create and show an instance of a generic MvxAppCompatDialogFragment using await IMvxNavigationService.Navigate().

2. Rotate the device

### Expected behavior
The dialog should rotate with the device

### Actual behavior
The application crashes.

The awaitable process is terminated (returning null) when the device is rotated and then the dialog is displayed a second time causing an app crash.

The happens both when Cancelable is true or false.

RetainInstance does not make a difference either.

### Configuration

**Version:** 5.3.0

**Platform:** 
- [X ] Android

**Comment by erviem99** [comment]
Is there a known work-around for this bug other that completely rewriting how my modal dialogs are handled?

**Comment by nmilcoff** [comment]
I followed the steps using [Playground.Droid](https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Playground/Playground.Droid) and the app doesn't crash. Also the dialog remains in foreground. Please provide us more details.
