### ISSUE TITLE
MvxIosViewPresenter CloseModalViewController broken in 5.3

### ISSUE THREAD

**Issue by tougher** [MvvmCross/MvvmCross#2276]
Here is a version of the "StarWarsSample" where I updated to 5.3, which then has the issue:
https://github.com/tougher/MvvmCross-Samples/tree/CloseModalViewController-5.3-bug/StarWarsSample (_Please note the branch_).

### Steps to reproduce

1. Get a version of the StarWarsSample with MvvmCross packages updated to 5.3 (see my link above).

2. Run the iOS project.

3. Open the "Menu" tab.

4. Tap on "Statistics" to open a modal.

5. Tap on "Cancel" to close the modal.

6. Tap on "Statistics" again or even any "_Planet_" / "_People_" menu point. Nothing happens.

### Expected behavior
After opening and closing a modal, the _ModalViewControllers_  in the _MvxIosViewPresenter_ should be empty.

### Actual behavior
After opening and closing a modal, the _ModalViewControllers_ in the _MvxIosViewPresenter_ is not empty and most navigation requests will fail with (from the Application Output):

> Warning: Attempt to present <MvvmCross_iOS_Views_MvxNavigationController: 0x7f9eaea00800> on <MvvmCross_iOS_Views_MvxNavigationController: 0x7f9eae2de000> whose view is not in the window hierarchy!

### Workaround
Override _CloseModalViewController(IMvxViewModel toClose)_ in a _MvxIosViewPresenter_ subclass with the 5.2.x code helps.

### Configuration

**Version:** 5.3

**Platform:** 
- [x] iOS

**Comment by nmilcoff** [comment]
Thanks for reporting this issue. I've submitted a PR that will fix this.

**Comment by tougher** [comment]
Thanks! Smallest PR I've seen in a long time :-)

By the way, I love the new 5.x presenter 👍
