### ISSUE TITLE
Nested fragment error

### ISSUE THREAD

**Issue by ornolisvt** [MvvmCross/MvvmCross#2287]
Hello, I am developing an android application with MvvmCross + Xamarin, I need to show three tabs in a tablayout with viewpager, they would be three fragments. Within a tab I need to show three nested fragments and use a bottom navigation view. For that development I relied on the Playground example of the TestProjects folder of the MvvmCross source code. When I try to load the first nested fragment I get this error. 

10-21 20:08:10.119 I/MonoDroid( 5712): System.NullReferenceException: FrameLayout to show Fragment not found
10-21 20:08:10.119 I/MonoDroid( 5712):   at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.ShowFragment (System.Type view, MvvmCross.Droid.Views.Attributes.MvxFragmentPresentationAttribute attribute, MvvmCross.Core.ViewModels.MvxViewModelRequest request) [0x0008b] in C:\projects\mvvmcross\MvvmCross-AndroidSupport\MvvmCross.Droid.Support.V7.AppCompat\MvxAppCompatViewPresenter.cs:228 
10-21 20:08:10.119 I/MonoDroid( 5712):   at MvvmCross.Droid.Views.MvxAndroidViewPresenter.<RegisterAttributeTypes>b__32_2 (System.Type view, MvvmCross.Core.Views.MvxBasePresentationAttribute attribute, MvvmCross.Core.ViewModels.MvxViewModelRequest request) [0x00000] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewPresenter.cs:148 
10-21 20:08:10.119 I/MonoDroid( 5712):   at MvvmCross.Droid.Views.MvxAndroidViewPresenter.Show (MvvmCross.Core.ViewModels.MvxViewModelRequest request) [0x00055] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewPresenter.cs:288 
10-21 20:08:10.119 I/MonoDroid( 5712):   at MvvmCross.Droid.Views.MvxAndroidViewDispatcher+<>c__DisplayClass2_0.<ShowViewModel>b__0 () [0x00000] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewDispatcher.cs:26 
10-21 20:08:10.119 I/MonoDroid( 5712):   at MvvmCross.Droid.Views.MvxAndroidMainThreadDispatcher.RequestMainThreadAction (System.Action action, System.Boolean maskExceptions) [0x00020] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidMainThreadDispatcher.cs:20 
10-21 20:08:10.119 I/MonoDroid( 5712):   at MvvmCross.Droid.Views.MvxAndroidViewDispatcher.ShowViewModel (MvvmCross.Core.ViewModels.MvxViewModelRequest request) [0x00014] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewDispatcher.cs:26 
10-21 20:08:10.120 I/MonoDroid( 5712):   at MvvmCross.Core.Navigation.MvxNavigationService+<Navigate>d__32.MoveNext () [0x0003a] in C:\projects\mvvmcross\MvvmCross\Core\Core\Navigation\MvxNavigationService.cs:179 
10-21 20:08:10.120 I/MonoDroid( 5712): --- End of stack trace from previous location where exception was thrown ---
10-21 20:08:10.120 I/MonoDroid( 5712):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.120 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.120 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.120 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.120 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.120 I/MonoDroid( 5712):   at MvvmCross.Core.Navigation.MvxNavigationService+<Navigate>d__40.MoveNext () [0x00078] in C:\projects\mvvmcross\MvvmCross\Core\Core\Navigation\MvxNavigationService.cs:294 
10-21 20:08:10.121 I/MonoDroid( 5712): --- End of stack trace from previous location where exception was thrown ---
10-21 20:08:10.121 I/MonoDroid( 5712):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.121 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.121 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.121 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.121 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.121 I/MonoDroid( 5712):   at Playground.Core.ViewModels.Tab1ViewModel+<<-ctor>b__1_0>d.MoveNext () [0x00025] in E:\VS\MvvmCross-master\Playground\Playground.Core\ViewModels\Tab1ViewModel.cs:17 
10-21 20:08:10.122 I/MonoDroid( 5712): --- End of stack trace from previous location where exception was thrown ---
10-21 20:08:10.122 I/MonoDroid( 5712):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.122 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.122 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.122 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.122 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.122 I/MonoDroid( 5712):   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<ExecuteConcurrentAsync>d__17.MoveNext () [0x000c6] in C:\projects\mvvmcross\MvvmCross\Core\Core\ViewModels\MvxAsyncCommand.cs:114 
10-21 20:08:10.122 I/MonoDroid( 5712): --- End of stack trace from previous location where exception was thrown ---
10-21 20:08:10.123 I/MonoDroid( 5712):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.123 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.123 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.123 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.123 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.123 I/MonoDroid( 5712):   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<ExecuteAsync>d__16.MoveNext () [0x00040] in C:\projects\mvvmcross\MvvmCross\Core\Core\ViewModels\MvxAsyncCommand.cs:81 
10-21 20:08:10.123 I/MonoDroid( 5712): --- End of stack trace from previous location where exception was thrown ---
10-21 20:08:10.123 I/MonoDroid( 5712):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.124 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.124 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.124 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.124 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.124 I/MonoDroid( 5712):   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<Execute>d__14.MoveNext () [0x00096] in C:\projects\mvvmcross\MvvmCross\Core\Core\ViewModels\MvxAsyncCommand.cs:68 
10-21 20:08:10.124 I/MonoDroid( 5712): --- End of stack trace from previous location where exception was thrown ---
10-21 20:08:10.124 I/MonoDroid( 5712):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.124 I/MonoDroid( 5712):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-21 20:08:10.125 I/MonoDroid( 5712):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <2e14bb2dd93a405e81838369ed72695b>:0 
10-21 20:08:10.125 I/MonoDroid( 5712):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <2e14bb2dd93a405e81838369ed72695b>:0 
10-21 20:08:10.125 I/MonoDroid( 5712):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <2e14bb2dd93a405e81838369ed72695b>:0 
10-21 20:08:10.125 I/MonoDroid( 5712):   at (wrapper dynamic-method) System.Object:40f5fe67-a2f9-46b2-be1e-c2f4a6a62a78 (intptr,intptr)
10-21 20:08:10.262 W/art     ( 5712): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
10-21 20:08:10.342 D/Mono    ( 5712): DllImport searching in: '__Internal' ('(null)').
10-21 20:08:10.342 D/Mono    ( 5712): Searching for 'java_interop_jnienv_throw'.
10-21 20:08:10.342 D/Mono    ( 5712): Probing 'java_interop_jnienv_throw'.
10-21 20:08:10.343 D/Mono    ( 5712): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

10-21 20:08:11.103 E/mono    ( 5712): 
10-21 20:08:11.103 E/mono    ( 5712): Unhandled Exception:
10-21 20:08:11.103 E/mono    ( 5712): System.NullReferenceException: FrameLayout to show Fragment not found
10-21 20:08:11.103 E/mono-rt ( 5712): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: FrameLayout to show Fragment not found`

The code I use is as follows https://github.com/ornolisvt/Playground 
Please, could you help me with these. Thank you very much

**Comment by ornolisvt** [comment]
Any ideas?

**Comment by nmilcoff** [comment]
Please provide us with more information than just the repository. 

Which are the necessary steps to make your app crash? At a first glance it looks like you don't have a FrameLayout on the fragment host of your nested fragment.

**Comment by ornolisvt** [comment]
Thanks for the reply. Yesterday testing some changes by putting 500 millisecond delay before displaying the nested fragments for the first time solves the problem. However now the problem is that when the application has been a while in the background and the host activity is destroyed, when returning to the application does not show the fragments, only the empty tablayout. What I can be doing wrong. This behavior also occurs if you do not maintain activities in the developer options
I'm using Android 7 on a Samsung Galaxy s6 Edge phone and Xamarin Android 7.4

### Steps to reproduce

1. Activate Don´t keep activities on Dev Options

2. Run the app (on Github)

3. Go to the background and after a few seconds return to the application


### Expected behavior
The application should display the tablayout with three fragments and the first tab with three nested fragments

### Actual behavior
Only the tablayout is shown without fragments or tabs

### Configuration

**Version:** 5.3.2

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment]
I could replicate this issue on TestProjects/Playground.Droid

**Comment by ornolisvt** [comment]
Thank you very much, when will version 5.3.3 be available?

**Comment by gvsharma** [comment]
Yes, able to reproduce this issue in a sample app that I did.
