### ISSUE TITLE
Navigation between native and Forms is not correct

### ISSUE THREAD

**Issue by YvesDelcoigne** [MvvmCross/MvvmCross#2292]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Open and run the Playground.Forms.Droid or iOS sample app

2. Press the "Show Override" button

3. Press the "Show second child" button

### Expected behavior
Second child is shown.

### Actual behavior
Override screen is still there, second child screen is added in the backstack (it's visible when you press the back button)

### Configuration

**Version:** 5.3.2

**Platform:** 
- [x] iOS
- [x] Android
- [?] WPF
- [?] UWP

**Comment by martijn00** [comment]
Currently there is no automatic closing or moving forward from a native view to a Forms view. If you manually call close first and then navigate it should work.

**Comment by YvesDelcoigne** [comment]
Okay, so it's actually an improvement and not a bug. Manually closing it does indeed work, but it doesn't feel right.
