### ISSUE TITLE
Lack one constructor inside MvxDialogFragment

### ISSUE THREAD

**Issue by Thetyne** [MvvmCross/MvvmCross#2294]
### Steps to reproduce

1. create a MvxDialogFragment linked to MvxViewModel with parameter (MyDialogViewModel<MyParam>) 

2. display fragment with : _navigationService.Navigate<MyDialogViewModel, MyParam>(param);

3. close fragment

4. android application crash.

### Expected behavior
MvxDialogFragment have two constructors and MvxDialogFragment<TViewModel> have only one.
I can't implement the second constructor and Android crash because it need it.

lack constuctor : 
        protected MvxDialogFragment(IntPtr javaReference, JniHandleOwnership transfer) : base(javaReference, transfer)
        {
        }

you can check here:
[https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Droid/Droid/Views/Fragments/MvxDialogFragment.cs](url)

for your information, MvxAppCompatDialogFragment class implement two constructor.

### Actual behavior
Android application crash after i close dialog because it internal call the second constructor with "(IntPtr javaReference, JniHandleOwnership transfer)" parameter.

if i create manually a class named "MvxCustomDialogFragment" with this two constuctor, it's work fine.

### Configuration

**Version:** 5.3.1

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
I don't get it. I see both have the same constructors.

https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Droid/Droid/Views/Fragments/MvxDialogFragment.cs#L22

https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.Fragment/MvxDialogFragment.cs#L28

**Comment by Thetyne** [comment]
Please check MvvmCross.Droid.Views.Fragments.MvxDialogFragment
[https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Droid/Droid/Views/Fragments/MvxDialogFragment.cs#L22](url)

**Comment by martijn00** [comment]
Aah right you mean the generic version of that fragment. I'll make a fix for that.

**Comment by Thetyne** [comment]
Thanks :)

**Comment by martijn00** [comment]
Added in https://github.com/MvvmCross/MvvmCross/commit/1c8485f2d0e0f4efe703e14ddfe3c818602070df
