### ISSUE TITLE
Inconsistent PCL profile for PictureChooser

### ISSUE THREAD

**Issue by ElteHupkes** [MvvmCross/MvvmCross#2295]
The PCL library created for the PictureChooser plugin targets a profile (`portable-net45+win+wpa81`, https://github.com/MvvmCross/MvvmCross/blob/develop/nuspec/MvvmCross.Plugin.PictureChooser.nuspec#L27) that is inconsistent with the `lib\portable-net45+win+wpa81+wp80` (https://github.com/MvvmCross/MvvmCross/blob/develop/nuspec/MvvmCross.Core.nuspec#L21) of the rest of MvvmCross. PCLs supporting .NET standard 1.0-ish profiles may therefore be able to install all of MvvmCross, but not the PictureChooser. I happen to be developing for such a library right now, which fortunately I can retarget at this point, but it's a bit strange that this is the only package that fails to install.

**Comment by Cheesebaron** [comment]
To be correct it should be portable-net45+win8+wpa81+wp8 for the picturechooser, which matches its Profile259.

**Comment by Cheesebaron** [comment]
This is deprecated by NET Standard.
