### ISSUE TITLE
ViewModel Initialize method not called using MvxViewPagerFragmentInfo

### ISSUE THREAD

**Issue by rrispoli** [MvvmCross/MvvmCross#2297]
When you create a viewpager with MvxViewPagerFragmentInfo, the ViewModel was created, but the Initialize method was not executed.

### Steps to reproduce

1. Create a basic ViewModel with Initialize method.

2. Configure the viewpager in the Android view, inside the OnCreated method:

```
var viewPager = FindViewById<ViewPager>(Resource.Id.simple_view_pager);
var fragments = new List<MvxViewPagerFragmentInfo>
{
	new MvxViewPagerFragmentInfo("Page 1", typeof(FirstFragment), typeof(FirstViewModel)),
	new MvxViewPagerFragmentInfo("Page 2", typeof(SecondFragment), typeof(SecondViewModel)),
	new MvxViewPagerFragmentInfo("Page 3", typeof(ThirdFragment), typeof(ThirdViewModel)),
};

viewPager.Adapter = new MvxCachingFragmentStatePagerAdapter(this, SupportFragmentManager, fragments);
```

### Expected behavior
The ViewModels execute Initialize method when it's instatiated.

### Actual behavior
The ViewModels doesn't execute the Initialize method when it's instatiated.

### Configuration

**Version:** 5.3.0

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by gvsharma** [comment]
@rrispoli  I verified this and able reproduce this issue..

**Comment by Zorpix** [comment]
Also having and reproduced this issue. Are any other methods called when the Fragment ViewModels load?

**Comment by nmilcoff** [comment]
Related to #2287, we need to refactor our ViewPager adapters.

**Comment by jmalczak** [comment]
This is still an issue. I use mvvmcross 7.1.2 and Initialize is not called.
