### ISSUE TITLE
mvx:MvxBind binding structure inconsistant

### ISSUE THREAD

**Issue by c-lamont** [MvvmCross/MvvmCross#2299]
The new binding structure `mvx:MvxBind` that replaces the previous `mvx:Bi.nd` does not work for all types of binding and sometimes crashes the app with a null exception.

Some of the properties that it has failed to bind to include:
`SelectedItem` from ListView, 
`IsPresented` from MasterDetail,
`ItemClick` from MvxListView

They all work with `mvx:Bi.nd`.

### Steps to reproduce

1. In your xaml bind a labels text color with TextColor="{mvx:MvxBind StatusColor}"

2. In your xaml bind a labels text color with mvx:Bi.nd="TextColor StatusColor" 

### Expected behavior
The text color should change to the bound StatusColor

### Actual behavior
Step 1 causes: `System.NullReferenceException: Object reference not set to an instance of an object`
Step 2 works as expected, the texts color is set.

### Configuration

**Version:** 5.3.1

**Platform:** 
- [x] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by c-lamont** [comment]
@martijn00 Still a lot of problems with the bindings. 

I think there might be an issue with binding to a view models parent. For example when I try to bind to the BaseViewModel property IsRefreshing, I get a null exception when using `mvx:MvxBind`.

Here is a typical page using Mvx 5.4
I have tried to use `mvx:MvxBind` where possible.
If that doesn't work I try to use `mvx:Bi.nd`.
If that doesn't work I use the Forms binding.

`<?xml version="1.0" encoding="UTF-8"?>
<views:MvxContentPage x:TypeArguments="viewModels:NewsViewModel"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:mvx="clr-namespace:MvvmCross.Forms.Bindings;assembly=MvvmCross.Forms"
    xmlns:views="clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms"
    xmlns:viewModels="clr-namespace:XabluForms.Core.ViewModels;assembly=XabluForms.Core"
    xmlns:local="clr-namespace:XabluForms.Core.CustomViews;assembly=XabluForms.Core"
    xmlns:refresh="clr-namespace:Refractored.XamForms.PullToRefresh;assembly=Refractored.XamForms.PullToRefresh"
    x:Class="XabluForms.Core.Pages.NewsPage"
    Title="{mvx:MvxBind Title}">
    <views:MvxContentPage.Content>
        <refresh:PullToRefreshLayout mvx:Bi.nd="RefreshCommand ReloadCommand; IsRefreshing IsRefreshing;">
            <views:MvxListView
                Style="{StaticResource CardListView}"
                ItemsSource="{mvx:MvxBind NewsItems}"
                SelectedItem="{Binding SelectedNewsItem, Mode=TwoWay}">
                <ListView.ItemTemplate>
                    <local:NewsItemTemplate />
                </ListView.ItemTemplate>
            </views:MvxListView>
        </refresh:PullToRefreshLayout>
    </views:MvxContentPage.Content>
</views:MvxContentPage>`

**Comment by c-lamont** [comment]
In MvxListView this does not work
'ItemClick="{mvx:MvxBind NewsitemSelectedCommand}"'

This does work
'mvx:Bi.nd="ItemClick NewsitemSelectedCommand"'

**Comment by novatekinno** [comment]
mvx:MvxBind for MvxListView IsRefreshing still throws a null exception:

`IsRefreshing="{mvx:MvxBind IsRefreshing}"` still does not work.

**Comment by Cheesebaron** [comment]
@novatekinno create a new issue, with full description.
