### ISSUE TITLE
Forms Droid navigation bar color can not be changed

### ISSUE THREAD

**Issue by c-lamont** [MvvmCross/MvvmCross#2301]
Starting a forms app on a MvxContentPage results in the Navigation bar remaining default white with black text. This is not a problem on iOS.
Nested navigation views, in a MvxMasterDetailPage for example, show the correct color.

### Steps to reproduce

1. Start your app on a MvxContentPage

2. Set the styling in your Core App class

`    <Style TargetType="views:MvxNavigationPage">
        <Setter Property="BarBackgroundColor"
            Value="{StaticResource PrimaryColor}" />
        <Setter Property="BarTextColor"
            Value="{StaticResource PrimaryWhite}" />
    </Style>`

3.

### Expected behavior
The color of the navigation bar should be as you have set it

### Actual behavior
The navigation bar remains white with black text

### Configuration

**Version:** 5.3.1

**Platform:** 
- [ ] iOS
- [x ] Android
- [ ] WPF
- [ ] UWP

**Comment by jtillman** [comment]
@Cheesebaron I believe I'm still seeing this issue in 5.4.2. Can you confirm the fix with setting the color in App.xaml?

**Comment by jtillman** [comment]
I've discovered the fix that was put in place. It has to do with setting the TabLayoutResource & ToolbarResource before calling base.OnCreate.

https://github.com/MvvmCross/MvvmCross/pull/2361/files#diff-a927b6bc815cee1bbe8cae35baa15b89R19

**Comment by JTOne123** [comment]
I have this issue on android 5.4.2
and also at 5.5.0 in UWP
