### ISSUE TITLE
MvxResourceProvider.GenerateResourceNameFromPath issue

### ISSUE THREAD

**Issue by nicolgit** [MvvmCross/MvvmCross#2302]
### Steps to reproduce
If I have a JSON Resource file with character "-" into the name to read, GenerateResourceNameFromPath replace character "-" with "_".

### Expected behavior
in MvvmCross 4.4 I was able and I have used, many .json files in resources with the characted "-" into the name, so this sounds like a regression.

if the path parameter is "common-us.json", the function returns "common-us.json"

### Actual behavior

if the path parameter is "common-us.json", the function returns "common_us.json"

### Configuration

**Version:** 5.3.2

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment]
Can you make a quick repro sample I can work on to look more into this issue?

**Comment by martijn00** [comment]
Closing because no response or repro sample.
