### ISSUE TITLE
MasterDetailExample.UWP crashes with 'System.NullReferenceException: Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by ehuna** [MvvmCross/MvvmCross#2304]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Clone MvvmCross

2. Open the MvvmCross_All.sln in ViS 2017

3. Compile TestProjects/Forms/MasterDetail/MasterDetailExample.UWP and all of its dependencies - it works, 11 projects.

4. Turn on 'Developer Mode', and set the startup project as TestProjects/Forms/MasterDetail/MasterDetailExample.UWP as the startup project then run.

### Expected behavior
MasterDetailExample.UWP is deployed to the Android Emulator and runs without exceptions

### Actual behavior
MasterDetailExample.UWP is deployed to my local machine but when it runs, it crashes with the following exception -

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.UWP.FormsPresenter.<.ctor>b__0_0(Object s, SizeChangedEventArgs e)`

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [ X ] UWP

**Comment by martijn00** [comment]
UWP is a bit behind the Droid and iOS presenters. When that is updated sometime it should work.
