### ISSUE TITLE
Xamarin.Forms / MasterDetailPage breaks my app because of the slide to open menu gesture

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2306]
While I can disable the swipe to open of the master menu gesture, I cannot find any option for that in MVX. But it breaks my whole application. Here is, how it can be done in classic Xamarin.Forms: https://stackoverflow.com/questions/40515952/xamarin-form-master-detail-page-how-to-disable-swipe-gesture-to-load-the-men

**Comment by martijn00** [comment]
You could do something like this:

```c#
#if __IOS__
if(Xamarin.Forms.Application.Current.MainPage is MasterDetailPage masterDetailPage)
{
    masterDetailPage.IsGestureEnabled = false;
}
else if(Xamarin.Forms.Application.Current.MainPage is NavigationPage navigationPage && navigationPage.CurrentPage is MasterDetailPage nestedMasterDetail)
{
    nestedMasterDetail.IsGestureEnabled = false;
}
#endif
```

**Comment by Sebastian1989101** [comment]
Is this still required for ignoring the swipe gesture? And if so: Will this work with the MVX MasterDetail presenter? Because my page is only a "MvxContentPage" just as in the Playground project.

**Comment by martijn00** [comment]
I don't know, you have to try it yourself if it works.

**Comment by mvcaction** [comment]
simply you can put IsGestureEnabled="False" in RootPage.xaml
