### ISSUE TITLE
Xamarin.Forms / MasterDetailPage: The master menu stays open after navigation

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2307]
While the default Xamarin.Forms master menu page is closed after the navigation, I cannot reproduce this with MVX. The menu stays always open.

**Comment by martijn00** [comment]
You need to trigger it from your navigate method:

```c#
if(Xamarin.Forms.Application.Current.MainPage is MasterDetailPage masterDetailPage)
{
    masterDetailPage.IsPresented = false;
}
else if(Xamarin.Forms.Application.Current.MainPage is NavigationPage navigationPage && navigationPage.CurrentPage is MasterDetailPage nestedMasterDetail)
{
    nestedMasterDetail.IsPresented = false;
}
```

**Comment by djmpnt** [comment]
> 
> 
> While the default Xamarin.Forms master menu page is closed after the navigation, I cannot reproduce this with MVX. The menu stays always open.

Just put this IsPresented = false;
Inside the method.

Example: 

private void GoToPerfil1(object sender ,EventArgs args)
        {
            Detail = new NavigationPage(new Pages.Perfil1());
            
            **IsPresented = false;**
        }
