### ISSUE TITLE
Xamarin.Forms / MasterDetailPage and ModalDialog: Navigation will break, if a page inside a MasterDetail navigation opens a modal dialog

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2311]
After opening a ModalDialog from a MasterDetail-DetailPage, the navigation gets stuck (at least on iOS, Android not tested yet)

**Comment by martijn00** [comment]
I can't reproduce this issue in the playground. Please give more details and fill out the issue template.

**Comment by Sebastian1989101** [comment]
I guess I found a quick way to reproduce it with MVX 5.3.2. A MVX MasterDetail page is my primary page (the first after app launch). Now I navigate to a page with a ModalPresenter and implement a "Close" command in the Modal ViewModel. While the Close method is executed nothign happend.
