### ISSUE TITLE
Issues with binding string that contain any numeric value to a label text

### ISSUE THREAD

**Issue by pakbaz** [MvvmCross/MvvmCross#2316]
### Steps to reproduce

1. Create Property in View Model to return a string like "v1.0.0.0" or any numeric value followed after white space or . in my case

2. Set Bindings in ViewController to a label

3. Run The project

### Expected behavior
Binding Should work

### Actual behavior
MvvmCross.Platform.Exceptions.MvxException has been thrown with Message:
Unexpected character 0 at position 3 in targetProperty text v1.0.0.0

### Configuration

**Version:** 5.3.2

**Platform:** 
- [X] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
Can you post your code that you use for this? Or even better a reproduction repo?

**Comment by pakbaz** [comment]
I can't put the code in repo because of the nature of the code. but weird part is, I uncommented that binding (same exact code) and it is working fine now. It could be related to one of the dependencies being added or removed. other than than I didn't change anything. thanks for response though

**Comment by martijn00** [comment]
Ok, i'll close this, feel free to open again if you hit it again.
