### ISSUE TITLE
Xamarin Forms application not working after upadating MvvmCross from 5.2.1 to 5.3.0 or above.

### ISSUE THREAD

**Issue by anee146** [MvvmCross/MvvmCross#2317]
Initially we're created an xamarin forms application with MvvmCross support 5.2.1 and that was working fine. After the latest update of MvvmCross 5.3.0 arrived, we updated the packages.

### Steps to reproduce

1. Rebuilding the application throws exception saying that MvvmCross.Forms.Core is not present in the packages.

2.  What we understand is, the references belongs to MvvmCross.Forms.Core is moved to MvvmCross.Forms.Platform. So we resolved those errors generated with latest update.

### Expected behavior
Application should be working properly with the latest update because of it was working fine in MvvmCross 5.2.1 version.

### Actual behavior
Applicaiton throwing an error says that "Application window are expected to have a root view controller   at the end of application launch". Issue found in both iOS and Android deployment.

Please helps us to provide a  solution to resolve the issue asap.

### Configuration

**Version:** 5.x
MvvmCross 5.3.0 & above
Xamarin Forms 2.4.0.18342
**Platform:** 
- [X] iOS
- [X] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
This means you are blocking the loading of the app somewhere in your code and not waiting for it to finish so it can return a viewmodel for the first screen.

Check that you return a AppStart viewmodel before the initialize has ended.
