### ISSUE TITLE
How to custom navigation animation?

### ISSUE THREAD

**Issue by Wenfengcheng** [MvvmCross/MvvmCross#2318]
I want to navigate page with a animation push from bottom, what should I do to achieve it?
Anyone have any idea?
Thank you for replying!

**Comment by martijn00** [comment]
Please fill out the template. We don't know where your issue is without details.

**Comment by Wenfengcheng** [comment]
For example, I want to add push from bottom animation when Mainpage navigate to FirstPage, and only this navigation use custom animation, what should I do to achieve it ?
On MvvmCross, I find a way by using Renderer. But it can not be used as paramter when navigate.All navigation achieve this.
Can you give me some suggestions? Thank you!

**Comment by martijn00** [comment]
Questions are more suitable for StackOverflow. Ask there or fill out the issue template if you think this is a bug.

**Comment by Cheesebaron** [comment]
If you figure it out and it is missing from the documentation, you are very welcome to make a Pull Request adding these details.

**Comment by Wenfengcheng** [comment]
OK, I‘m sorry. StackOverflow may suit me！
Thank you!
