### ISSUE TITLE
Need Strong Names for assemblies

### ISSUE THREAD

**Issue by jonstelly** [MvvmCross/MvvmCross#232]
I want to use MvvmCross in a project that needs to have a strong name (signed).  Can't use MvvmCross because assemblies in NuGet packages aren't signed.

**Comment by martijn00** [comment]
Is this still relevant? See https://github.com/octokit/octokit.net/issues/405
And: https://github.com/MvvmCross/MvvmCross/issues/740#issuecomment-62977166

**Comment by Cheesebaron** [comment]
If people need strong naming. Clone the repo and sign it yourself. The code is open source!
