### ISSUE TITLE
MvxTabBarViewController and view resolving problem

### ISSUE THREAD

**Issue by ukod** [MvvmCross/MvvmCross#2328]
### Steps to reproduce

1. Run test project for IOS: https://github.com/ukod/testIosAppWithIssue.git;

2. Look at exception;

### Expected behavior
View has appeared

### Actual behavior
Exception: Default constructor not found for type testapp.iOS.Views.MainView

### Configuration

**Version:** 5.4.0

**Platform:** 
- [x] iOS

It might be my bad, but also seems to me like some bug or not obvious behavior. Linker is off in ios project.

Can someone check it?

**Comment by Cheesebaron** [comment]
Remove the storyboard and designer file and remove the ctor in your MainView.

TabBarViewController doesn't have any content.
