### ISSUE TITLE
Forms - App fails to launch when initial page has WrapInNavigationPage = false

### ISSUE THREAD

**Issue by MaxHampton** [MvvmCross/MvvmCross#2329]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Create FirstPage with presentation attribute [MvxContentPagePresentation(WrapInNavigationPage = false)]

2. RegisterNavigationServiceAppStart&lt;FirstViewModel>() in MvxApplication

3. Launch iOS or Android app

### Expected behavior
App will launch to FirstView, not displayed wrapped in a navigation page.

### Actual behavior
App crashes with output on iOS: 

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

App crashes with output on Android:

[0:] mvx : Diagnostic :   5.70 No view model association found for candidate view {0}, System.Object[]
[0:] mvx : Diagnostic :   5.70 No ViewModel class specified for {0} in LoadViewModel, System.Object[]
[0:] mvx : Diagnostic :   5.71 Null Extras seen on Intent when creating ViewModel - have you tried to navigate to an MvvmCross View directly? Will try direct load, System.Object[]
[0:] mvx : Error :   5.72 Unable to load viewmodel - no type hint provided, System.Object[]
[0:] mvx : Warning :   5.72 ViewModel not loaded for view {0}, System.Object[]

11-01 09:42:31.553 I/MonoDroid( 3667): UNHANDLED EXCEPTION:
11-01 09:42:31.588 I/MonoDroid( 3667): System.InvalidOperationException: Sequence contains no elements
11-01 09:42:31.588 I/MonoDroid( 3667):   at System.Linq.Enumerable.Last[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <b5bd9d990a0b4733885e90ca5ec6c0fb>:0 
11-01 09:42:31.588 I/MonoDroid( 3667):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnAttachedToWindow () [0x00011] in C:\agent\_work\3\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:210 
11-01 09:42:31.588 I/MonoDroid( 3667):   at Android.Views.View.n_OnAttachedToWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <c82a099136944d8aa96281cf061cbc12>:0 
11-01 09:42:31.588 I/MonoDroid( 3667):   at (wrapper dynamic-method) System.Object:386b85c7-53bc-446d-a2d3-6d30b3f857cc (intptr,intptr)

Note: Setting WrapInNavigationPage = true allows the app to launch as expected.

### Configuration

**Version:** MvvmCross v5.4.0 and Xamarin.Forms v2.4.0.18342 (also 2.4.0.38779)

**Platform:** 
- [x] iOS
- [x] Android
- [ ] WPF
- [ ] UWP
- [ ] MacOS
- [ ] tvOS
- [x] Xamarin.Forms

**Comment by cornelha** [comment]
Is there some sort of work around for this right now? I am using 5.4.0 and I am having one hell of a time getting Xamarin.Forms to play nicely with MvvmCross. The sample applications seem to be out of date and I cannot seem to figure out how to get past this.
