### ISSUE TITLE
Forms (iOS): Short UI freeze when navigating to a MvxTabbedPage

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2330]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

Navigate from a side to a MvxTabbedPage where the child pages use Parameters (Prepare-Method)

### Expected behavior
It should navigate and load the child after a successful navigation. 

### Actual behavior
Currently it gets stuck when about the half navigation to the tabbed page is done (also the root page seems to always has a white background which does not match very well with my application so while the app freezes I see the white page coming in before it gets the color of my app).

### Configuration

**Version:** 5.3.2

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP
- [ ] MacOS
- [ ] tvOS
- [ ] Xamarin.Forms

**Comment by Sebastian1989101** [comment]
Still getting the issue. Here is a attached Screenshot, it gets stuck this way for 1-3sec (depending on the device).
![simulator screen shot - iphone x - 2017-11-23 at 21 58 16](https://user-images.githubusercontent.com/25636075/33188354-8cd3f56a-d099-11e7-8d71-5ea133c5c54f.png)

**Comment by martijn00** [comment]
That really sounds like you have something wrong in either Prepare() or Initialize (). Do you not block anything in Prepare? And do you use ConfigureAwait (false) in Initialize?

**Comment by Sebastian1989101** [comment]
Neither the Initialize nor the Prepare method is used by the pages in this TabbedPage. So there should be nothing blocking the thread.

**Comment by Cheesebaron** [comment]
Provide a repro sample and we will look into it.

**Comment by Sebastian1989101** [comment]
Here is a repo with the issue. It will also happen on the Playground example (just change the background color of the pages). https://github.com/Sebastian1989101/MvxTabFreezeNavigation

**Comment by nickrandolph** [comment]
@Sebastian1989101 when you run the playground example are you able to step through and see where the delay is happening? When you say "just change the backgorund color of the pages", is this just to highlight the page transition, or are you saying that changing the color causes the issue to appear?

**Comment by Sebastian1989101** [comment]
@nickrandolph No I did not spent time yet to debug through it with the Playground (because it is not as critical as some other issues I had with my apps). The color change is to make the "Lag" more visible. I don't guess this is related to the "Lag" itself.

**Comment by nickrandolph** [comment]
@Sebastian1989101 I know this issue's a bit old now but are you able to check it against 6/6.1?

**Comment by mkshiblu** [comment]
I have the exact same issue on iOS. MvvmCross 5.6.3.

**Comment by seba47** [comment]
Hi, somebody has found this issue? I am facing the same bug and I have tried several things but it is still there.

Thanks in advance
