### ISSUE TITLE
MvxTabLayoutPresentation not working in Fragment

### ISSUE THREAD

**Issue by vurf** [MvvmCross/MvvmCross#2335]
To help us fix your issue, please provide the information in the below template. 
MvxTabLayoutPresentation working only in Activity, but not working in Fragment.

### Steps to reproduce

1. Make host fragment for tabFragments, make tabFragments, show host fragment with tabFragments and throw exception "The host activity doesnt inherit FragmentActivity"

2. StackTrace 
MvxAppCompatViewPresenter: ShowTabLayout -> ShowViewPagerFragment(view, attribute, request) -> ShowHostActivity(attribute)

### Expected behavior
I am expect that fragment with tabFragments will load and show.

### Actual behavior
Now I get throw exception "The host activity doesnt inherit FragmentActivity"

### Configuration

**Version:** 5.3.2

**Platform:** 
- [ ] iOS
- [X] Android
- [ ] WPF
- [ ] UWP
- [ ] MacOS
- [ ] tvOS
- [ ] Xamarin.Forms

**Comment by martijn00** [comment]
You need to set the Fragment type in the attribute so it uses the ChildFragmentManager.

**Comment by vurf** [comment]
I did set MvxFragmentPresentationAttribute, but it not helped.

**Comment by martijn00** [comment]
`[MvxTabLayoutPresentation(TabLayoutResourceId = Resource.Id.tabs, ViewPagerResourceId = Resource.Id.viewpager, Title = "Tab 1", ActivityHostViewModelType = typeof(TabsRootBViewModel), FragmentHostViewType = typeof(MyFragment))]`

The `FragmentHostViewType = typeof(MyFragment)` is the important bit here.

**Comment by vurf** [comment]
Not helped (MvxException "The host activity doesnt inherit FragmentActivity")

**Comment by martijn00** [comment]
Check if your Activity does that. Do you extend from MvxAppCompatActivity? And did you not update to some later Android support library then we use? (v25.3)

**Comment by vurf** [comment]
I'm using android support library 26.0.2. My activity inherited from MvxCachingFragmentCompatActivity. Maybe you include your ideas in mvvmcross.playground.android and show usecase. In playground android I found tab in activity (not fragment)

**Comment by martijn00** [comment]
Try using our version. Also `MvxCachingFragmentCompatActivity` is deprecated and not available anymore. The Fragment sample uses nested tabs, but not the attribute: https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Android-Support/Fragments/Example.Droid/Fragments/ExampleViewPagerFragment.cs#L23

The Playground shows attributes but on Activity. Try to figure it out from that and contribute your findings to the documentation. If you can't get it done, make a pull request with the changes to show that this is a bug so we can fix it.
