### ISSUE TITLE
MvxObservableCollection:  "Add" and "AddRange" methods generates an event arguments with different structures.

### ISSUE THREAD

**Issue by neminush** [MvvmCross/MvvmCross#2338]
### Steps to reproduce

1. 
```csharp
var questions = new MvxObservableCollection<Question>();
questions.CollectionChanged += Questions_CollectionChanged;
```

2.
```csharp
List<Question> questionsList = new List<Question>(/* some array with Questions */);
questions.AddRange(questionsList);
```

3.
```csharp
void Questions_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
{
  if (e.NewItems != null)
  {
    // ok if we using "Add" method or throws an exception if we using "AddRange" method
    foreach (Question question in e.NewItems) 
    {
      // some logic
    }
  }
}
```

### Expected behavior
`e.NewItems` should contain collection of "Question" items

### Actual behavior
`e.NewItems` contains a collection of collections of "Question" items

### Configuration

**Version:** 5.3.2 - 5.4.0

**Platform:** 
- [x] iOS 11
- [is not tested] Android
- [is not tested] WPF
- [is not tested] UWP
- [is not tested] MacOS
- [is not tested] tvOS
- [is not tested] Xamarin.Forms

**Comment by MKuckert** [comment]
Made the same observation. Fix for this: #2407
