### ISSUE TITLE
Forms: Can not assign MvxListView CachingStrategy in XAML

### ISSUE THREAD

**Issue by c-lamont** [MvvmCross/MvvmCross#2341]
### Steps to reproduce

1. Add an MvxListView to any page

2. Assign the caching strategy `<views:MvxListView CachingStrategy="RecycleElement"/>`

3.

### Expected behavior
The list implements recycling

### Actual behavior
A TargetInvocationException is thrown
`Cannot assign property "CachingStrategy": Property does not exists, or is not assignable, or mismatching type between value and property`

### Configuration

**Version:** 5.4

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP
- [ ] MacOS
- [ ] tvOS
- [x] Xamarin.Forms

**Comment by martijn00** [comment]
Since `CachingStrategy` is internal you need to set this through the ctor.

```c#
<views:MvxListView>
    <x:Arguments>
        <ListViewCachingStrategy>RecycleElement</ListViewCachingStrategy>
    </x:Arguments>
</views:MvxListView>
```

It could look like this.
