### ISSUE TITLE
Forms: Setting Detail in MvxMasterDetailView added to stack and not replacing Detail

### ISSUE THREAD

**Issue by c-lamont** [MvvmCross/MvvmCross#2347]
### Steps to reproduce

1. Open the MvvmCross Playground app in Android
2. Click show mixed navigation.
3. Click login
4. Open side menu navigation
5. Click on Root menu item

### Expected behavior
The Root page should be shown with the hamburger menu on the top left

### Actual behavior
New Root page is added to the stack and not replacing the current detail view. The back button is shown in the navigation bar.

### Configuration

**Version:** 5.4

**Platform:** 
- [x] iOS
- [x] Android
- [ ] WPF
- [ ] UWP
- [ ] MacOS
- [ ] tvOS
- [x] Xamarin.Forms

**Comment by martijn00** [comment]
If you set `NoHistory = true` in 5.4.1 this will be replacing the root.
