### ISSUE TITLE
mvx:MvxBind not setting selected item in MvxListView

### ISSUE THREAD

**Issue by c-lamont** [MvvmCross/MvvmCross#2355]
This works

    SelectedItem="{Binding SelectedNewsItem, Mode=TwoWay}"

These do not

    SelectedItem="{mvx:MvxBind SelectedNewsItem, Mode=TwoWay}"
    SelectedItem="{mvx:MvxBind SelectedNewsItem}"

### Steps to reproduce :scroll:

1. Add a MvxListView to a page

2. Bind its SelectedItem `SelectedItem="{mvx:MvxBind SelectedNewsItem}"`

3. Set the selected item to null so the item is not highlighted

### Expected behavior :thinking:
The selected item becomes unselected.

### Actual behavior :bug:
The selected item remains selected

### Configuration :wrench:

**Version:** 5.4

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2356
