### ISSUE TITLE
MvxTableViewSource CollectionChangedOnCollectionChanged can be executed on a worker thread

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2360]
When using an ObservableCollection with a MvxTableViewSource, the collection changed event is subscribed by MvxTableViewSource but its handler does not check if it is run on the main thread.

### Expected behavior :thinking:
Using the Task based binder, the viewmodel should fire and forget events on any thread.

### Actual behavior :bug:
If the event is received on a worker thread, a UIKit consistency exception occurs.

### Fix

In MvxTableViewSource change the CollectionChangedOnCollectionChanged handler:

        protected override void CollectionChangedOnCollectionChanged(object sender, NotifyCollectionChangedEventArgs args)
        {
            void Action()
            {
                if (!UseAnimations)
                    ReloadTableData();
                else
                {
                    if (TryDoAnimatedChange(args))
                        return;
                    ReloadTableData();
                }
            }

            if (NSThread.IsMain)
                Action();
            else
                InvokeOnMainThread(Action);
        }

### Configuration :wrench:

**Version:** 5.4

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a pull request for this?

**Comment by softlion** [comment]
I'm currently unable to test any of the change i could make to mvvmcross, to see if it could work in my own project. And there is no guide here to enlighten me on the process. And you never answered me in slack on how you organise yourself with the github version of mvvmcross, the plugin dependencies, in order to test it on the real projects you work on.

Also i made a bunch of other changes so it works much more efficiently with bach updates. Which i'm not sure i can share.

**Comment by nmilcoff** [comment]
@softlion we have several TestProjects in the repository, that you can use as a playground.

Thanks for providing us with the fix! I'll make a PR.
