### ISSUE TITLE
Unable to use MvxTabbedPage in MvvmCross 5.4.2

### ISSUE THREAD

**Issue by mgoodfellow** [MvvmCross/MvvmCross#2370]
### Steps to reproduce

I'm trying to get MvxTabbedPage working in MvvmCross and Xamarin.Forms

My previous issue (https://github.com/MvvmCross/MvvmCross/issues/2345) was closed with patches that were merged into 5.4.2 (https://github.com/MvvmCross/MvvmCross/pull/2361) - however, even in my trivial example, this still doesn't seem to work. Really not sure what I could be doing wrong with these tabs.

Thanks!

1. Get latest Xamarin Forms, MvvmCross etc. and start new project. 

2. [Here's one I made earlier](https://github.com/mgoodfellow/MobileTabsTest) - I took most of this code from examples in the Playground project in this repo - this has been updated to MvvmCross 5.4.2

3. Run it on Android

### Expected behavior
I would expect 2 tabs, each with a title, and each to have content in the page.

### Actual behavior
I get 1 mini half-formed tab, and no page content

If I then close the app using the back button on android, and open it again, it now has 2 tabs, neither with any text, and still no page content.

If I then close the app using the back button again, and open again, it now has 3 tabs, still no text etc. 

### Configuration

**Version:** 5.4.2

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP
- [ ] MacOS
- [ ] tvOS
- [x] Xamarin.Forms

**Comment by martijn00** [comment]
Looking at the code quickly i see you set the attribute on the viewmodel. Attributes are a view pattern and should be set on them.

**Comment by mgoodfellow** [comment]
@martijn00 You absolute hero! Thank you - it is all fixed and working now.

Massive thanks for all the work you have done so far on this library! :)

As a quick aside, it wasn't clear to me from the docs or demo, what those attributes where really for, now you have said that it is blindingly obvious. Thanks for the super fast response!
