### ISSUE TITLE
MvxFragmentAttribute not available in MvvmCross 5.4.2

### ISSUE THREAD

**Issue by dlpopescumtk** [MvvmCross/MvvmCross#2372]
### Steps to reproduce :scroll:

1. Remove the MvvmCross.Droid.Shared from the Android project
2. Update MvvmCross to latest version

### Actual behavior :bug:
The MvxFragmentAttribute is no longer available. How to register a fragment with an activity?

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
As described in the blog posts, this is now `MvxFragmentPresentation`

**Comment by dlpopescumtk** [comment]
@martijn00 : I've noticed it just after asking the question.  Thank you!
