### ISSUE TITLE
Resuming app with tabs as root page causes duplicate page to load as new navigation (MvvmCross 5.4.2 / MvxTabbedPage root)

### ISSUE THREAD

**Issue by mgoodfellow** [MvvmCross/MvvmCross#2373]
### Steps to reproduce :scroll:

1. Latest Xamarin.Forms / MvvmCross 5.4.2

2. [Example Repo here](https://github.com/mgoodfellow/MobileTabsTest)

3. When the app first runs, a tabbed root page appears with 2 child tabs appears

### Expected behavior :thinking:
If the app is backgrounded, then when it resumes it appears as it did before

### Actual behavior :bug:
When the app resumes, the [MainPage](https://github.com/mgoodfellow/MobileTabsTest/blob/master/src/MobileTabTest.Core/Pages/MainPage.xaml.cs) is recreated

I've stepped through the code, and when it's recreated [_firstTime](https://github.com/mgoodfellow/MobileTabsTest/blob/master/src/MobileTabTest.Core/Pages/MainPage.xaml.cs) is `false`, and so a new page is created, and the tabs added.

However, the old page is still in the stack, so you end up with a back navigation arrow in top-left of toolbar and that takes you back to the old existing `MainPage`.

I notice that [TriggerFirstNavigate](https://github.com/mgoodfellow/MobileTabsTest/blob/master/src/MobileTabTest.Droid/SplashScreen.cs#L24) from the `SplashScreen` runs again on resume, and I wonder if it is the responsibility of that to check if the page already exists in the stack? I need to dig further into the MvvmCross code base, but I was hoping the issue might be obvious to you guys!

Thanks!

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
https://github.com/MvvmCross/MvvmCross/commit/9fbf73528372506278a32c2f8d91061ea6f7f5bc
