### ISSUE TITLE
A self closing MvxDialogFragment causes an unhandled exception

### ISSUE THREAD

**Issue by sisterray** [MvvmCross/MvvmCross#2389]
### Steps to reproduce :scroll:

1. Navigate using the MvxNavigationService to a MvxDiaglogFragment with the [MvxDialogFragmentPresentation] attribute

2. By calling a command in the dialogs viewmodel, close the dialog using MvxNavigationService.Close 

3. An exception occurs System.NotSupportedException: Unable to activate instance of type<MyDialogView> from native handle

### Expected behavior :thinking:
There should not be an exception raised

### Actual behavior :bug:
Unhandled exception rasised - An exception occurs System.NotSupportedException: Unable to activate instance of type<MyDialogView> from native handle

### Workaround:
Add the following constructor to the dialog
protected MyDialogView(IntPtr javaReference, JniHandleOwnership transfer)
            : base(javaReference, transfer)
        {
        }

I am assuming the issue is that something is accessing the view when it has been disposed. The addition of this constructor enables Android to re-create an instance of the view. I'm assuming the solution is to stop whatever is accessing the disposed view from referencing it.

### Configuration :wrench:

**Version:** 5.4

**Platform:** 
- [x] :robot: Android

**Comment by Cheesebaron** [comment]
What exact version are you using? The ctor you mention was added recently.

**Comment by sisterray** [comment]
I am using MvvmCross v5.4

Stack Trace
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <e975227ac8644a30bb0866117325de0d>:0 
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <e975227ac8644a30bb0866117325de0d>:0 
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <e975227ac8644a30bb0866117325de0d>:0 
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <e975227ac8644a30bb0866117325de0d>:0 
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <e975227ac8644a30bb0866117325de0d>:0 
  at Android.Support.V4.App.Fragment.n_OnPause (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <7e083afc7c9045f59e01d9c14931060d>:0 
  at (wrapper dynamic-method) System.Object:be21ea4e-2647-495a-bb4a-3a5a1db5b21b (intptr,intptr)

**Comment by Cheesebaron** [comment]
You need to provide all 3 segments of the semver.

**Comment by sisterray** [comment]
Sorry, not sure what you mean?

**Comment by sisterray** [comment]
Sorry v5.4.2

**Comment by Cheesebaron** [comment]
In order for someone to figure out whether your issue already has been fixed you need to provide the full version of the NuGet packages you are using. You can't just say 5.4 because all MvvmCross versions are using Semantic Version which have 3 segments, `major.minor.patch`. So if you say 5.4 I assume you are meaning 5.4.0.

**Comment by sisterray** [comment]
v5.4.2

**Comment by Cheesebaron** [comment]
And what is the problem with adding the ctor?

**Comment by sisterray** [comment]
I thought that what this constructor did was if a disposed view was accessed, this constructor would create a new instance of the view. This is almost never what you want. See the answer on this page [Leaky Abstraction](https://stackoverflow.com/questions/10593022/monodroid-error-when-calling-constructor-of-custom-view-twodscrollview)

**Comment by Cheesebaron** [comment]
I think you need to fully understand JonP's answer there.

**Comment by sisterray** [comment]
Hi,

Can you explain your understanding of it. I just want to be on the same page.

**Comment by Cheesebaron** [comment]
Sorry, I don't have time for that right now. You seem to have a good understanding, so maybe you go first and explain the implications and a possible solution.

**Comment by sisterray** [comment]
Ok, going by what jonP says 

No, we shouldn't add that constructor by default, because it will hide bugs. If you're getting a No constructor found... message, that means that the mapped instance was prematurely collected, which means either there's a Dispose() call that shouldn't be there, or there's a GC bug, or something else that's Very Important And Shouldn't Be Hidden™. You need to understand why the exception is occurring lest you cargo cult "fix the problem." – jonp

It seems that we should not be adding this in by default as it is hiding a problem.
