### ISSUE TITLE
UWP crash at launch "Failed to resolve type MvvmCross.Core.Views.IMvxViewPresenter"

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2397]
### Steps to reproduce :scroll:

1. Launch an UWP app with 5.4.2

### Expected behavior :thinking:
The app should launch without any problem like it does on Android and iOS. 

### Actual behavior :bug:
"Failed to resolve type MvvmCross.Core.Views.IMvxViewPresenter" happend when you try to resolve the IMvxViewPresenter in the MainPage.xaml.cs. 

Here is a very slim project to where this is happening: https://github.com/Sebastian1989101/OpenGeoDB-App

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
There are fixes done already for this. It will be released in 5.5.0.
