### ISSUE TITLE
AndroidPresenter: Close all Fragments of Activity when doing CloseActivity()

### ISSUE THREAD

**Issue by dlpopescumtk** [MvvmCross/MvvmCross#2398]
### Steps to reproduce :scroll:

1. Declare, in the class _CertainActivity_, a public static CertainActivity _ActivityToClose_ variable, which would just be = _this_.
1. Start a new activity by doing _NavigationService.Navigate(CertainActivityViewModel)_
2. Call _ChangePresentation(new ReturnToHomeGalleryHint())_ from one of the child fragments
3. Override _ChangePresentation_ in the Android presenter to call _CloseActivity(CertainActivity.ActivityToClose.ViewModel, null)_ when the hint is _ReturnToHomeGalleryHint_

I should mention that the first fragment has _AddToBackStack=true_ in the presentation attribute.

### Expected behavior :thinking:
Child fragments should be closed as well

### Actual behavior :bug:
First fragment of the activity is still shown.

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
@dlpopescumtk any particular reason to close this issue you'd like to share with us?

**Comment by dlpopescumtk** [comment]
@nmilcoff : my issue, in the end, was not related to this but, on the other hand it could raise another issue in MvvmCross. 
Here's my scenario: 
I have a _FragmentToShow_ registered to two activities: the _HomeActivity_ and _SecondActivity_. If I want to start _SecondActivity_, I would just do _Navigate<FragmentToShowViewModel>_, MvvmCross would handle starting _SecondActivity_. But, since _FragmentToShow_ is already registered with _HomeActivity_, it shows _FragmentToShow_ inside _HomeActivity_ and no longer starts _SecondActivity_. If I were to do _Navigate<FragmentToShowViewModel>_ from any other activity that the _FragmentToShow_ is not registered to, it would work just fine.

**Comment by dlpopescumtk** [comment]
@nmilcoff : so closing the activity seems to work, that fragment in particular was not being closed because it was not a part of activity to close.
