### ISSUE TITLE
Android - Activity context not loaded into the Initialize method

### ISSUE THREAD

**Issue by symibsoft** [MvvmCross/MvvmCross#2401]
### Steps to reproduce :scroll:
1.
Refer to the activity context inside the new Initialize method

### Expected behavior :thinking:
The activity is loaded before calling this method by the mvvmcross viewmodel lifecycle.

### Actual behavior :bug:
The activity is loaded asynchronously and if you refer to it, for example in order to show a AlertDialog that requires context, the context refers to the previous activity.

As a workaround I made this in my base viewmodel class:

```
bool isViewAppeared = false;

        public override void ViewAppearing()
        {
            base.ViewAppearing();
            isViewAppeared = true;
        }
        public override async Task Initialize()
        {
            await base.Initialize();

            while (isViewAppeared == false)
            {
                await Task.Delay(100);
            }
        }
```
With this workaround  the initialize method will wait until the activity context is created.

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by dlpopescumtk** [comment]
@symibsoft, with the latest version of MvvmCross, I use the Prepare method and not the Initialize one. 
As for the activity context, maybe you should think about using the ViewCreated method of the viewmodel.

**Comment by symibsoft** [comment]
The prepare method is only for parameter initialization. As in the documentation, the initialize must be used for heavy initialize work.
The prepare method isn't async.
The viewcreated method is not called by uwp apps.
In my opinion the inizialize method must wait until the view is creates, in any platform.

**Comment by nmilcoff** [comment]
Initialize is an agnostic method and shouldn't wait for anything related to platform lifecycles. 

Looks like the problem would be solved if we add lifecycle hooks for UWP.

**Comment by nmilcoff** [comment]
If you can't use ViewAppearing on UWP for your purposes please open a new issue with your problem. As I previously mentioned, Initialize is platform-agnostic.
