### ISSUE TITLE
empty view(xaml page not loading)

### ISSUE THREAD

**Issue by elbonito** [MvvmCross/MvvmCross#2404]
### Steps to reproduce :scroll:

1.went through the uwp platform documentation to get mvvmcross setup in portable library and uwp
2.when i hit deploy i just get a blank empty white screen.. the mainview is not loaded.
app initialise class

```csharp
 public override void Initialize()
        {
            CreatableTypes()
                .EndingWith("Service")
                .AsInterfaces()
                .RegisterAsLazySingleton();

            RegisterNavigationServiceAppStart<MainViewModel>();
        }
```

setup class 

```csharp
public Setup(Frame rootFrame) : base(rootFrame)
        {
        }

        protected override IMvxApplication CreateApp()
        {
            return new AppCore.AppCore();
        }

        protected override MvxLogProviderType GetDefaultLogProviderType()
        {
            return MvxLogProviderType.None;
        }
```

app.xaml.cs class

```csharp
   var setup = new Setup(rootFrame);
                    setup.Initialize();

                    var start = Mvx.Resolve<IMvxAppStart>();
                    start.Start();
```

views folder with mainview.xaml.cs extending MvxWindowsPage
mainview.xaml views:MvxWindowsPage

not errors or warnings in outputs

installed mvvmcross.core, mvvmcross.binding, mvvmcross.platform on pcl and uwp project

uwp project updated to Microsoft.NETCore.UniversalWindowsPlatform v6.0.2
### Expected behavior :thinking:
load mainview

### Actual behavior :bug:
just blank empty white screen no view loaded

### Configuration :wrench:

**Version:** 5.5

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by MartinZikmund** [comment]
I had the same issue after upgrading to 5.5, it has to do with the new UWP ViewPresenter. To fix this, you have to add `[MvxPagePresentation]` attribute to all your view classes.

I would suggest to make this the default. Currently the navigation silently fails with `NullReferenceException`.

**Comment by elbonito** [comment]
adding [MvxPagePresentation] attribute worked thanks!!

**Comment by MartinZikmund** [comment]
Adding the attribute was just a workaround, not a solution. It should be automatic and adding the attribute should not be necessary (same as for other platforms)

**Comment by MartinZikmund** [comment]
Oh sorry, the related PR didn't show up for me, never mind 😂
