### ISSUE TITLE
[Need a help] [XamForms on Droid] Is the following sequence correct for ViewModel calls and the creation of activity?

### ISSUE THREAD

**Issue by JTOne123** [MvvmCross/MvvmCross#2411]
### Steps to reproduce :scroll:

https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Playground/Playground.Core/ViewModels/RootViewModel.cs

https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Playground/Playground.Forms.Droid/MainActivity.cs

1. Set a breakpoint at RootViewModel.Prepare
2. Set a breakpoint at RootViewModel.Start
3. Set a breakpoint at MainActivity.OnCreate
4. F5
5. The sequence is next - Start, Prepare, OnCreate

Is it correct?

How to interact with the interface from RootViewModel.Start?

For example, I want to show alert and my alert service uses current context from IMvxAndroidCurrentTopActivity and IMvxAndroidCurrentTopActivity is splash screen!

What should I do?

------
Previously, I've started IMvxAppStart from MainActivity and everything worked.

### Configuration :wrench:
current mvvmcross master branch

**Version:** 5.5

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Maybe override `ViewAppeared` in your RootViewModel? Anyways, this should go to StackOverflow since it is a implementation question.

**Comment by JTOne123** [comment]
First of all, this question about the sequence.

Is it correct?

Why did you the milestone?

**Comment by martijn00** [comment]
Documentation is available at https://www.mvvmcross.com/documentation/fundamentals/viewmodel-lifecycle

We set milestones on every issue to mark in which release they are closed.
