### ISSUE TITLE
Gyroscope Plugin requested

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#242]
Request via email for GyroScope plugin

Seems fairly self-explanatory - like the Accelerometer plugin up-down aware - will also need `IsSupported`

**Comment by martijn00** [comment]
There is a plugin for this available: https://www.nuget.org/packages/Xam.Plugin.DeviceMotion

**Comment by slodge** [comment]
If Xam have now adopted the plugin idea, maybe we should have a wrapper that allows their plugins to be easily IoC'd into Mvx (maybe this is a new issue if this is a good idea... not looked at xam plugins so don't know if they are just bait and switch things which are just use them rather than them being injectable)
