### ISSUE TITLE
[Android] [MvxRecyclerView] MvxTemplateSelector<TItem> missing ItemTemplateId issue

### ISSUE THREAD

**Issue by Krupishev** [MvvmCross/MvvmCross#2422]
### Expected behavior :thinking:
I recently had to solve the problem of selecting the elements **RecyclerView**. In different parts of the application, I needed to add **Ad** items.
That is, I need a template selector that returns an item specified via the `ItemTemplateId` or an _advertisement_ element.
However, I did not find a way to do this, because if you use `MvxTemplateSelector<TItem>`, you can not get the value of `ItemTemplateId`.

So I need to create custom `AdFoxRecyclerView : MvxRecyclerView`

Like this:
   ```
 public class AdFoxRecyclerView : MvxRecyclerView
    {
       ...
        public AdFoxRecyclerView(Context context, IAttributeSet attrs, int defStyle, IMvxRecyclerAdapter adapter): base(context, attrs, defStyle)
        {
            if (ItemTemplateSelector is AdFoxTemplateSelector adFoxSelector)//thanks to MvvmCross developers
            {
                adFoxSelector.BaseItem = MvxAttributeHelpers.ReadListItemTemplateId(context, attrs);
            }
        }
        ...
    }

 public class AdFoxTemplateSelector : MvxTemplateSelector<IAdFoxViewModel>
    {
        public int BaseItemId { get; set; }

        public override int GetItemLayoutId(int fromViewType)
        {
            return fromViewType;
        }

        protected override int SelectItemViewType(IAdFoxViewModel item)
        {
            if (item.ItemType == Core.Models.AFItemType.Advertisement)
                return Resource.Layout.item_adfox;
            return BaseItemId;
        }
    }

```

### Actual behavior :bug:
There are no way to do it, please add the value of the `ItemTemplateId` to `MvxTemplateSelector<TItem>`

### Configuration :wrench:

**Version:** 5.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
@Krupishev Just to make sure I understand your request... You want `MvxTemplateSelector` to have a default `ItemTemplateId`, and you want to set it through xml using something like `local:MvxItemTemplate="@layout/my_item_template"`? 

If that's what you're after, I personally don't think this provides much value, but at the same time I don't see any reason not to provide this feature.

**Comment by Krupishev** [comment]
@nmilcoff yes, you got it right.

This feature becomes important when you use CustomPresenter, or CustomViewGroup, which allows you to show View for ViewModel without declaring any special view class. So it becomes more difficult to get access to view element in code, and it is more convenient to set the most part of the parameters in xml.
