### ISSUE TITLE
SplitView with MasterDetail keeps the Master menu always open (iOS 9+ / iPad only) 

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2428]
This problem also occurs with the Playground in the MVX repository. So I guess adding a additional repository / project is kinda obsolete. 

**Note**: This is a common problem from Xamarin.Forms. The reported problem there gets ignored since January 2016. So maybe you have some solution for it. More informations here: https://bugzilla.xamarin.com/show_bug.cgi?id=37737

### Steps to reproduce :scroll:

1. Run the Playground.Forms.iOS project on an iPad (iOS 9+)

2. Navigate to the MasterDetail page

3. Enter SplitView, the problem occurs always in Vertical and Horizontal on 50% and less screen space for the MVX app

### Expected behavior :thinking:
The app should still toogle the MasterDetail menu correctly. 

### Actual behavior :bug:
Master menu stays open. 

### Configuration :wrench:

**Version:** 5.5.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@Sebastian1989101 so currently do you see the same behaviour across XF whether you use Mvvmcross or not? 
Additionally, controlling the behaviour of the SplitView should really be the responsibility of the app, rather than any specific framework. You should be able to handle the change in size of the page and use that to determine the master-details behaviour, and whether the master pane is IsPresented or not.

**Comment by Sebastian1989101** [comment]
@nickrandolph thats the point. You are not able to hide the master pane. Even if you set "IsPresented" to false it is still Presented - and it is presented full screen (at least if the View for the app is <60% of the available screen space). I really would like to have this option but it is not working. Before the September update of Xamarin.iOS (for iOS 11 support) it was possible to create a workaround with a custom renderer, but this is no longer possible. 

Here is the workaround from before: 
```
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;
using MyApp.iOS.Renderer;

[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(CustomTabletMasterDetailRenderer), UIUserInterfaceIdiom.Pad)]
namespace MyApp.iOS.Renderer
{
    public class CustomTabletMasterDetailRenderer : TabletMasterDetailRenderer
    {
        public override UITraitCollection TraitCollection => UITraitCollection.FromHorizontalSizeClass(UIUserInterfaceSizeClass.Regular);

        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);
            PreferredDisplayMode = UISplitViewControllerDisplayMode.PrimaryOverlay;
        }
        
        public override void WillRotate(UIInterfaceOrientation toInterfaceOrientation, double duration)
        {
            base.WillRotate(toInterfaceOrientation, duration);
            PreferredDisplayMode = UISplitViewControllerDisplayMode.PrimaryOverlay;
        }
    }
}
```

**Comment by nickrandolph** [comment]
@Sebastian1989101 so just confirming, this is an XF problem, not specific to Mvvmcross?

**Comment by Sebastian1989101** [comment]
@nickrandolph Yes it is a Xamarin.Forms problem and it is reported there since January 2016. I just thought it is maybe possible to avoid this issue with the MVX implementation. Therefore I opened this report.

**Comment by nickrandolph** [comment]
@Sebastian1989101 the MVX implementation just piggybacks on the regular XF implementation of MasterDetails. Whilst there is an MvxMasterDetailsPage, it just extends the base implementation. 
One option you could try is using some sort of Effect, implemented on iOS only, which would force the change of displaymode when the size changes.

**Comment by boris-df** [comment]
Why is this closed? This exact Problem still exists with Xamarin.Forms 4.6 :(
The Custom-Renderer-Workaround will hide the Navigation (Burger-Menu-Button, Back-Button, etc.)

No solution out there?
