### ISSUE TITLE
MvxBottomSheetDialogFragment doesn't forward View events to ViewModel

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2431]
I've observed the navigation `Task` isn't properly signaled when a `MvxBottomSheetDialogFragment` is closed. I believe the reason is `MvxBottomSheetDialogFragment` is missing logic to forward events from the View to the ViewModel. The `MvxAppCompatDialogFragment` source is [forwarding View events to the ViewModel](https://github.com/MvvmCross/MvvmCross/blob/8908502f700c7ae3c8b4cbde4dcc18ce3bad708f/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.V7.AppCompat/MvxAppCompatDialogFragment.cs#L71-L123) but `MvxBottomSheetDialogFragment` [is not forwarding View events to the ViewModel](https://github.com/MvvmCross/MvvmCross/blob/8908502f700c7ae3c8b4cbde4dcc18ce3bad708f/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.Design/MvxBottomSheetDialogFragment.cs).

### Steps to reproduce :scroll:

1. Navigate to a cancelable `MvxBottomSheetDialogFragment`

2. Tap outside the bottom sheet to close it.

3. The `Task` remains active so you can't show the `MvxBottomSheetDialogFragment` again from the same button.

### Expected behavior :thinking:
`MvxBottomSheetDialogFragment` should forward events from the View to ViewModel like `MvxAppCompatDialogFragment` and `MvxDialogFragment` does.

### Actual behavior :bug:
`MvxBottomSheetDialogFragment` closes the dialog but leaves the navigation `Task` active.

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
@tbalcom Are you making a PR out of that commit?

**Comment by tbalcom** [comment]
@martijn00 I've submitted the PR to add MvvmCross 5.0 ViewModel lifecycle support to Android Support Design `MvxBottomSheetDialogFragment` .
