### ISSUE TITLE
Android: drawer + tabs + different drawer menu in each tab

### ISSUE THREAD

**Issue by marchanddesable** [MvvmCross/MvvmCross#2436]
Hi,

What is the best way, on android, with MVVMCROSS, to have a different drawer menu on each tabs ?
For example I have 4 tabs, when I swipe or click on a tab, I need to load a particular menu, if I go back I reload the last menu...

Is there a good way to do that with MVVMCROSS, with good performances ? 

Thanks.

**Comment by nmilcoff** [comment]
GitHub is for issues only, please use StackOverflow, Xamarin Forums or Slack for questions.
