### ISSUE TITLE
The new logger infrastructure should not send null messages to IMvxLog

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2437]
The new logger infrastructure is sending logs to the IMvxLog singleton with null message. Its does this to determine if a specific logging level is enabled. It should not. Or documentation should be updated.

### Steps to reproduce
- Create and register a custom object implementing IMvxLog
- Log a message using the Info extension method of the new IMvxLog system

### Expected behavior 
The Log method from the custom IMvxLog object is called only once.

### Actual behavior
The Log method from the custom IMvxLog object is called twice.
Once to determine if the logging level is enabled, and a second time to log the message.
This is silly.

From https://github.com/MvvmCross/MvvmCross/blob/master/MvvmCross/Platform/Platform/Logging/MvxLogExtensions.cs

        public static bool IsInfoEnabled(this IMvxLog logger)
        {
            GuardAgainstNullLogger(logger);
            return logger.Log(MvxLogLevel.Info, null);
        }

        public static void Info(this IMvxLog logger, string message)
        {
            if (logger.IsInfoEnabled())
            {
                logger.Log(MvxLogLevel.Info, message.AsFunc());
            }
        }

### Configuration

**Version:** 5.4.2

**Platform:** 
- all

**Comment by nmilcoff** [comment]
@softlion what do you think would be a good way to improve this? Maybe adding a method `IsLogEnabled` to `IMvxLog` makes sense? Or we can probably just remove the check? (cc: @willsb)

**Comment by softlion** [comment]
Leave as is but document it either in the code or in the wiki.
