### ISSUE TITLE
MvvmCross Wpf OnExit

### ISSUE THREAD

**Issue by ThomasDallmeier** [MvvmCross/MvvmCross#2445]
Hello, 
how could I react in a viewmodel if the application is closed. The override events are not fired in wpf.

Thnak you for your help

Thomas

**Comment by martijn00** [comment]
Please fill out the issue form

**Comment by nmilcoff** [comment]
Please ask questions in StackOverflow / Xamarin Slack Channel. If you find out there's an issue in the framework, please open a new issue filling out the template.
