### ISSUE TITLE
Preserve.cs

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#2446]
A quick question about Preserve.cs. I noticed that it is included by linking in every Plugin. Why is this? Is there a reason why we don't just call it from somewhere? Do I need to do this on my own plugins?

**Comment by kjeremy** [comment]
It's so that the methods don't get linked out.

See for example https://developer.xamarin.com/guides/android/advanced_topics/linking/#Preserving_Code

**Comment by tofutim** [comment]
Thank you Jeremy, I was wondering if the Preserve.cs had to be linked in or if I can just be referenced from elsewhere, say MvvmCross.Platform.
