### ISSUE TITLE
RegisterNavigationServiceAppStart vs RegisterAppStart

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#2447]
### Steps to reproduce :scroll:

1. Make a MvxViewModel with an IOC argument, but don't register

2. Use RegisterNavigationServiceAppStart<FirstViewModel>

### Expected behavior :thinking:
Tell us what should happen

I should hit an error in the IDE like this

![image](https://user-images.githubusercontent.com/157766/33750474-0fb492ce-db89-11e7-88bb-c10dbf57f76f.png)

### Actual behavior :bug:
Tell us what happens instead

The program hangs.  (If you replace RegisterNavigationServiceAppStart with the deprecated RegisterAppStart, it does hit the usual error.) This hanging makes things hard to debug.

### Configuration :wrench:

**Version:** 5.5.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Thanks for reporting!
