### ISSUE TITLE
WithConversion<...> does not appear do the same as WithConversion(new ...)

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#2449]
### Steps to reproduce :scroll:

1. Write a new converter, I needed a `NotValueConverter`, so I wrote

```csharp
public class NotValueConverter : IMvxValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return !((bool)value);
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return !((bool)value);
    }
}
```
2. In my viewController, 

```csharp
set.Bind(loginButton).For(v => v.Enabled).To(vm => vm.IsLoggedIn).WithConversion<NotValueConverter>();
```

### Expected behavior :thinking:
When `IsLoggedIn` is false, I expect my loginButton to be enabled; which I guess means that I expect that MvvmCross will automatically look for the `NotValueConverter`, create an instance if it doesn't yet exist, and then use that.

### Actual behavior :bug:
loginButton is not enabled, not converter is never called. However, if I use

```csharp
set.Bind(loginButton).For(v => v.Enabled).To(vm => vm.IsLoggedIn).WithConversion(new NotValueConverter());
```
it does do the right thing. Maybe I had to `Mvx.Register` the `NotConverter`? Not sure. I also want to note that I can use `.WithConversion("NotConverter")` if I register using

```csharp
protected override void FillValueConverters(MvvmCross.Platform.Converters.IMvxValueConverterRegistry registry)
{
    base.FillValueConverters(registry);

    registry.AddOrOverwrite("NotConverter", new NotValueConverter());
}
```
When I register as such, `.WithConversion<NotValueConverter>()` still does not work.

### Configuration :wrench:

**Version:** 5.5.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by mvanbeusekom** [comment]
@tofutim sorry for the delay in response, its been a busy few weeks for me. Anyway I found some time to look into it and I am having a hard time on reproducing the problem. 

I have created a reproduction example on my own GitHub fork which can be found here: https://github.com/mvanbeusekom/MvvmCross. The example are part of the `Playground.iOS` and `Playground.Mac` test projects and can be found in the `RootView` class in both projects. I haven't done any additional registration to get the value converters to work.

First I created a simple converter which randomly gets a color and applied the color to a label (on both iOS and MacOS application) and both work fine using the generic `WithConversion<RandomColorValueConverter>` method. 

After that (just to be thourough) I have also added a copy of your `NotValueConverter` to the `Playground.Mac` project and applied it to the `Enabled` property of the "Show Child" button in the `RootView` class. This also seems to behave as expected (you'll manually need to change the boolean value for the `IsLoggedIn` property of the `RootViewModel` class to see both states, but both work as expected).
