### ISSUE TITLE
UIBarButtonItem binding doesn't work

### ISSUE THREAD

**Issue by jz5** [MvvmCross/MvvmCross#2456]
### Steps to reproduce :scroll:

1. Bind UIBarButtonItem to Command

```c#
public override void ViewDidLoad()
{
    base.ViewDidLoad();

    // Add UIBarButtonItem to NavigationBar
    var barButton = new UIBarButtonItem { Title = "Click" };
    NavigationItem.RightBarButtonItem = barButton;

    var set = this.CreateBindingSet<MainView, Core.ViewModels.MainViewModel>();
    set.Bind(barButton).To(vm => vm.ResetTextCommand); // Bind to command
    set.Apply();
}
```
2. Run & Click the UIBarButtonItem

### Expected behavior :thinking:
Binded command is executed.

### Actual behavior :bug:
Binded command isn't executed.
The above code works in Ver 5.5.x 

### Configuration :wrench:

**Version:** 5.6

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Related to https://github.com/MvvmCross/MvvmCross/pull/2413?
