### ISSUE TITLE
Status Bar Style jumps back to default after navigation (iOS)

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2463]
### Steps to reproduce :scroll:

1. Navigate with the latest MVX Version (I navigate within a MasterDetail navigation)

2. After the first navigation, the status bar style returns to "Default" instead of "Light" - even if "Light" is configured in the Info.plist

### Expected behavior :thinking:
The status bar style should be stay untouched (based on the Info.plist file). 

### Actual behavior :bug:
It changes back to default. 

### Configuration :wrench:

**Version:** 5.6.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Sebastian1989101** [comment]
@Cheesebaron @martijn00 is there anything I can do against it? I used the following workaround but it only works if I not use the `Initialize` overwrite in my ViewModel. This is in my `AppDelegate.FinishedLaunching` as current workaround for it: 

`Mvx.Resolve<IMvxNavigationService>().AfterNavigate += (sender, args) => { SetStatusBarStyleLight(app); };`

**Comment by Cheesebaron** [comment]
We don't touch the StatusBar or it's style.

**Comment by Sebastian1989101** [comment]
@Cheesebaron well there must be something what changes this. With MVX 5.5 this was not an issue it only is a problem if you update to the latest version. Also the workaround only works as long as the `Initialize` method is not overwritten by my ViewModels. Within native iOS there is a way to change the style from each ViewController so maybe there is something wrong with it.

**Comment by lassana** [comment]
I've got the same problem.

**Comment by Sebastian1989101** [comment]
Not sure if this might be fixed with MVX 6.0.0 (beta6) but it seems like this problem does not happen anymore (or at least my theme implementation overwrites this problem - not 100% sure).

**Comment by martijn00** [comment]
Yeah please create a new one.

**Comment by CarLoOSX** [comment]
This behavior occurs when you navigate for second time. For example in an iPhone X when you navigate to login screen for first time everything is okay but when you navigate again the status bar style changes and in my case it turns white for ever.  Any temporal fix ? Thank you. Sorry for my English !

**Comment by Sebastian1989101** [comment]
I use this as a workaround on my app: 

AppDelegate.cs (OnActivated(UIApplication)): 
```
IMvxNavigationService navigationService = Mvx.IoCProvider.Resolve<IMvxNavigationService>();
navigationService.AfterNavigate += async (sender, args) =>
    {
        try
        {
            await Task.Delay(100);
            SetStatusBarStyleLight(application);
        }
        catch (Exception ex)
        {
            Crashes.TrackError(ex);
        }
    };

navigationService.AfterClose += async (sender, args) =>
    {
        try
        {
            await Task.Delay(100);
            SetStatusBarStyleLight(application);
        }
        catch (Exception ex)
        {
            Crashes.TrackError(ex);
        }
    };

SetStatusBarStyleLight(application)
```

And within the SetStatusBarStyleLight(UIApplication) I set the style again: 
```
internal static void SetStatusBarStyleLight(UIApplication app)
{
    try
    {
        //Do not move this app or the status bar will be black!!
        app.SetStatusBarStyle(StatusBarStyle, false);
        UINavigationBar.Appearance.BarStyle = BarStyle;
        UIApplication.SharedApplication.SetStatusBarStyle(StatusBarStyle, false);
    }
    catch (Exception ex)
    {
        Crashes.TrackError(ex);
    }
}
```

**Comment by CarLoOSX** [comment]
you could do a page renderer and use this: working for me :)

    UIView statusBar = UIApplication.SharedApplication.ValueForKey(new NSString("statusBar")) as UIView;
    if (statusBar.RespondsToSelector(new ObjCRuntime.Selector("setBackgroundColor:")))
    {
        statusBar.BackgroundColor = color.ToUIColor();
    }
