### ISSUE TITLE
MvxRestClient doesn't throw exception on network error

### ISSUE THREAD

**Issue by peterringset** [MvvmCross/MvvmCross#2465]
### Steps to reproduce :scroll:

The following code crashes:
```
public async Task<MvxRestResponse> MakeRequest()
{
    try
    {
        var request = new MvxRestRequest("http://github.com/asldkjasaljdaslkdj");
        var client = Mvx.Resolve<IMvxRestClient>();
        var task = client.MakeRequestAsync(request);

        var result = await task;

        Debug.WriteLine("done waiting");

        return result;
    }
    catch (WebException webException)
    {
        Debug.WriteLine(String.Format("got exception {0}", webException.Message));
    }
}
```

### Expected behavior :thinking:
I expect the catch block to catch the error, so that I can handle errors in networking code. The url is chosen to provoke a 404.

### Actual behavior :bug:
The debugger catches the exception, which in this case is a 404 WebException.

### Configuration :wrench:

**Version:** 5.6.2

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Doesn't result have a Status Code you can check?

**Comment by peterringset** [comment]
The program never reaches the point where result is assigned, it crashes during the await.

**Comment by Cheesebaron** [comment]
And what is the Exception then?

**Comment by peterringset** [comment]
The exception is of type WebException, and that's what I expect also. The problem is that the catch this code doesn't catch the exception, as you would expect it to.

**Comment by nmilcoff** [comment]
Does this fail if you change combine these two lines:

```c#
var task = client.MakeRequestAsync(request);

var result = await task;
```

into a single one? I mean this:

```c#
var result = await client.MakeRequestAsync(request);
```

Because it could be the case that the exception is thrown before you actually await the call.

**Comment by peterringset** [comment]
But should that really matter? Both alternatives are within the try block, and should be catched..
It gives the same behavior anyway..

I've tried debugging this a bit, and it seems that the main problem lies around line 252 in MvxRestClient.cs, where the statement
```c#
var response = (HttpWebResponse)httpRequest.EndGetResponse(result);
```
causes the exception, and is not executed in a way that let's it be catched.

**Comment by manarhusrieh** [comment]
Any news about this issue?

**Comment by Cheesebaron** [comment]
Nope, focus is on the .NET Standard conversion.

You are welcome to contribute a Pull Request if you have the time.

Otherwise feel free to use another excellent restful client, such as Refit.
