### ISSUE TITLE
MvxWindowsPage cannot navigate to MvxContentPage

### ISSUE THREAD

**Issue by nightsu** [MvvmCross/MvvmCross#2466]
I have some specific controls and references in Uwp Project,.The question is MvxContentPage can navigate to MvxWIndowsPage, but MvxWindowsPage cannot navigate to MvxContentPage via MvvmCross. MvvmCross Version 5.6.2. I am a Chinese,  and English is not good, I am sorry..
Here is  the Code(ViewModel of MvxWIndowsPage):
 ```
public IMvxCommand GoBackCommand
	    {
		    get
		    {
			    return new MvxCommand(() =>
			    {
				    navigationService.Navigate<MainViewModel>();
			    });
		    }
	    }
```

 

I have added a sample in my repository: https://github.com/nightsu/CrossTest
And no matter .net Standard 2.0 or PCL, the MvxWindowsPage cannot navigate to the MvxContentPage
### Steps to reproduce :scroll:

1.Using a Method of MvxWindowsPage: Frame.Navigate(); and it doesn't work.

### Expected behavior :thinking:
Navigate to MvxContentPage

### Actual behavior :bug:
MvxWindowsPage cannot navigate to the MvxContentPage, and no exceptions or errors

### Configuration :wrench:

**Version:** 5.6.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

**Comment by nightsu** [comment]
@Cheesebaron I'm sorry,I'll edit add  a repository soon, Thanks.

**Comment by nightsu** [comment]
@Cheesebaron I have add a repository with a reproduction sample, https://github.com/nightsu/CrossTest.If you are available, I hope you give it a try, thank you

**Comment by nickrandolph** [comment]
@nightsu thanks for the repro sample. I would typically expect to see a call to Close instead of a Navigate method but in either case this sample highlights an issue with UWP support that needs to be addressed. I'll investigate and see if we can get it fixed.

**Comment by Cheesebaron** [comment]
@nickrandolph I've invited you to the MvvmCross org so I can assign you to this.

**Comment by nickrandolph** [comment]
Thanks and done. Feel free to assign away
