### ISSUE TITLE
Remove IMvxIosModalHost

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#2475]
The `IMvxIosModalHost` is not used anymore since the new presenters. We should clean it up.

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Although it isn't very used and the naming looks like old stuff, I think it's the interface used to register the ViewPresenter in our IoC. 

We can maybe remove it and register the ViewPresenter on every platform using a single interface for v6.0?
