### ISSUE TITLE
 how to   Bottom Navigation Bar in MvvmCross.Forms

### ISSUE THREAD

**Issue by guiying521** [MvvmCross/MvvmCross#2479]
### Steps to reproduce :scroll:

1. I want  Bottom Navigation Bar   in MvvmCross.Forms.Android

### Expected behavior :thinking:
Tell us what should happen

### Actual behavior :bug:
Tell us what happens instead

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@guiying521 Unless I've missed something this is a Xamarin Forms question, rather than specifically MVX. Can you please ask it on their forums (https://forums.xamarin.com/categories/xamarin-forms) or on the Slack channel
