### ISSUE TITLE
Question: How to setup MvvmCross with Xamarin.Forms

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross#2491]
I have tried to follow the instructions in https://www.mvvmcross.com/documentation/platform/forms/xamarin-forms?scroll=612
on how to set up MvvmCross 5.6.3 with Xamarin.Forms in Visual Studio 2017 without luck.

Firstly in Visual Studio 2017 it is no longer possible to use a PCL for code sharing strategy. Only .NET Standard is possible.

Secondly when I install MvvmCross.StarterPack I do not get any of the usual Setup.cs files etc. Only the packages are added.

Can someone explain how to get started with a brand new project?

Thanks,
Erik

**Comment by flyingxu** [comment]
Same question here. 
The new VS2017 project does not have packages.config anymore, could it be related?

**Comment by nickrandolph** [comment]
See here https://nicksnettravels.builttoroam.com/post/2017/12/27/Getting-Started-MvvmCross-with-Xamarin-Forms-(Part-2).aspx

Please use Stackoverflow for questions

**Comment by erviem99** [comment]
Thank you for a very thorough walk thru. It worked for me on the first try. I especially like your comment about Android tools being crap. It was spot on for me.

Whether my issue is a comment or a bug (in the MvvmCross.StarterPack) I will leave up to others to decide, but it certainly is not easy getting started with MvvmCross and Xamarin.Forms as things stand at the moment.

**Comment by nickrandolph** [comment]
@erviem99 take a look at this post (https://nicksnettravels.builttoroam.com/post/2017/12/28/Making-MvvmCross-with-Xamarin-Forms-Friction-Free.aspx) and love to hear feedback. There's plenty we can do to improve the getting started experience with MvvmCross!

**Comment by flyingxu** [comment]
@erviem99 Take a look at [Xamarin Forms with MvvmCross 5 Solution Template]( https://marketplace.visualstudio.com/items?itemName=PaulDatsiuk.XamarinFormswithMvvmCross5SolutionTemplate)

**Comment by nickrandolph** [comment]
Closing this question
