### ISSUE TITLE
Documentation missing for Xamarin.Forms ViewPresenter 

### ISSUE THREAD

**Issue by nmilcoff** [MvvmCross/MvvmCross#2497]
### Expected behavior :thinking:
Documentation for Xamarin.Forms ViewPresenter

### Actual behavior :bug:
No documentation for Xamarin.Forms ViewPresenter

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2731
