### ISSUE TITLE
Reason why app crashed MvxSetup.InitializePrimary() called from void?

### ISSUE THREAD

**Issue by sbokatuk** [MvvmCross/MvvmCross#2508]
@I can reproduce issue https://github.com/MvvmCross/MvvmCross/issues/955 
sample is here https://github.com/sbokatuk/mvvmcross955/

But! if we modify this row from `void` [here](https://github.com/sbokatuk/mvvmcross955/blob/master/CrashableTestApp.Droid/Services/TestTimerService.cs#L37) to `async Task` [sample](https://github.com/sbokatuk/mvvmcross955/blob/nocrash/CrashableTestApp.Droid/Services/TestTimerService.cs#L37) app will stop crashing

```csharp
[Service]
    public class TestTimerService : Service
    {
       public override void OnCreate()
        {
            TestStuff();
        }
        //replace void to async Task and you will see a magic
        private void TestStuff()
        {
            Console.WriteLine($"Thread: {System.Threading.Thread.CurrentThread.ManagedThreadId}");
            AndroidMvxInitializer.SafeEnsureInitialized();
        }
    }
```

```csharp
public static class AndroidMvxInitializer
    {
        public static void SafeEnsureInitialized([CallerMemberName]string caller = null)
        {
            System.Console.WriteLine("{0} SafeEnsureInitialized: Trying EnsureInitialized() from {1}", nameof(AndroidMvxInitializer), caller);
            MvxAndroidSetupSingleton.EnsureSingletonAvailable(Application.Context).EnsureInitialized();
        }
    }
```

any thoughts why it's fixed crash? thread ID is same for void and for async Task here == 1. Need to understand how we can improve mvvmcross to not crash in next versions on init check
  
  
### Steps to reproduce :scroll:

1. install app, reboot, wait till recieve notification in notification bar - this means service is running
2. start app, if not crashed goto 3
3. kill app(close app from tasks manager) and faster click on app icon to run - 80% it will crash

### Expected behavior :thinking:
app should not crash on start in MvxAndroidSetupSingleton.EnsureSingletonAvailable()

### Actual behavior :bug:
app crashed 
MvxSetup.InitializePrimary ()
MvvmCross.Platform.Exceptions.MvxException: Cannot start primary - as state already InitializingSecondary

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Please try again on MvvmCross 6.0. We made several improvements for this.
