### ISSUE TITLE
MvxObservableCollection reports wrong index when doing AddRange

### ISSUE THREAD

**Issue by aaaabcv** [MvvmCross/MvvmCross#2515]
### Steps to reproduce :scroll:

1.
Create observable collection using MvxObservableCollection

2.
Add items with AddRange

### Expected behavior :thinking:
NotifyCollectionChangedEventArgs should report the first index where the changed occured  and the items which are inserted

### Actual behavior :bug:
NotifyCollectionChangedEventArgs report the index which is the same as the end of the resulting collection

Fix suggestion:
https://github.com/MvvmCross/MvvmCross/blob/c4cbc21d8417abd16a0cca956f8bee722c8e4faa/MvvmCross/Core/Core/ViewModels/MvxObservableCollection.cs

In line 99 "this.Items.Count" is taken after the items have been inserted. If this value is captured before the imtes are inserted and them reported, behaviour would be ok, i believe.

Also refer to 
https://msdn.microsoft.com/en-us/library/ms653208(v=vs.110).aspx

### Configuration :wrench:

**Version:** 6.2

**Platform:** 
- [x ] :iphone: iOS
- [ x] :robot: Android
- [ x] :checkered_flag: WPF
- [ x] :earth_americas: UWP
- [ x] :apple: MacOS
- [ x] :tv: tvOS
- [ x] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Can you please confirm this issue still exists in v5.6.3? #2455 should have solved it.

**Comment by aaaabcv** [comment]
Yes, it appears to solve the issue, thanks! And sorry, I didn't try 5.6.3 earlier.
I still have concerns about the change of #2455 since the index should indicate the start index where the change occured. The change indicates the index after the end of the list (Items.Count). Apparently the RecylerView Adapter can cope with that but it might be that other lists may have problems with that kind of hint.
I might add that to the change of #2455

**Comment by martijn00** [comment]
@aaaabcv Can you make a PR for that?

**Comment by ctartamella** [comment]
FWIW, I am on 5.6.3 and seeing this issue when calling AddRange() on a previously empty list in the case I'm initially populating it (~1500 items).  Calling ```data.ForEach(d => collection.Add(d));``` alleviates it as a workaround (but looks kinda ugly).
