### ISSUE TITLE
Navigate to viewmodel for tab item on iOS always creates a new tab item

### ISSUE THREAD

**Issue by modplug** [MvvmCross/MvvmCross#2518]
### Steps to reproduce :scroll:

1.
Create an iOS application with Tab navigation

2.
Create tabs for:
FirstViewModel
SecondViewModel
ThirdViewModel

3.
Navigate from FirstViewModel to SecondViewModel using navigationService.Navigate<SecondViewModel>()

### Expected behavior :thinking:
It should navigate to the second tab and provide any navigation parameters to the existing view model for the second tab

### Actual behavior :bug:
It creates a new tab everytime Navigate<SecondViewModel> is called

### Configuration :wrench:

**Version:** 5.6.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
We need an implementation of ChangePresentation for this on iOS since the navigationService is only ment to navigate forwards or backwards.

**Comment by markuspalme** [comment]
This is really needed to make the navigation model complete. 

Would the API surface look something like this?

`mvxNavigationService.ChangePresentation(new ActivateTabHint<Tab1ViewModel>());`

If that's what you had in mind, I can take it up for iOS.

**Comment by nmilcoff** [comment]
Yes, I think that sounds good @markuspalme. Maybe call it something like `MvxSelectTabHint`? Existing hints can be found [here](https://github.com/MvvmCross/MvvmCross/tree/develop/MvvmCross/Presenters/Hints).

**Comment by markuspalme** [comment]
@nmilcoff Thanks, I looked at the existing hints and found `MvxPagePresentationHint`. It is [intended to](https://www.mvvmcross.com/mvvmcross-56-release/) 

> Set the current page in a TabbedPage or CarouselPage that is already open.

It seems like this hint is currently only supported in the `MvxFormsPagePresenter` presenter:(https://github.com/MvvmCross/MvvmCross/blob/76f563af87ec7b3a888e849d7b7e2e01f322ae3d/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L257

Do you agree it would be the right approach to implement support for this hint in the iOSPresenter?

**Comment by nmilcoff** [comment]
@markuspalme Nice! Yes, that sounds perfect 👍

**Comment by markuspalme** [comment]
@martijn00  I think we can now close this issue, can't we? Or do you usually wait until the release?

**Comment by martijn00** [comment]
We should probably also implement this on Android.

**Comment by markuspalme** [comment]
@martijn00 I will give it a show. I can't add the Android label myself to the issue.

**Comment by nmilcoff** [comment]
I think Android currently does this through navigation (if you navigate to a tab which is already there, it is selected). We should add support to the hint and remove the code on the navigation part.

**Comment by markuspalme** [comment]
I tried working on android support, but am blocked because of #3083. Will continue once fixed.

**Comment by markuspalme** [comment]
How that https://github.com/MvvmCross/MvvmCross/pull/3086 is merged, I think we can close this issue, right?

**Comment by andrrrr** [comment]
How would you navigate to tabbed page tab?

**Comment by Cheesebaron** [comment]
@andrrrr please use discussions for questions.
