### ISSUE TITLE
Inconsistency between MvxCommand<T> and MvxAsyncCommand<T> implementing IMvxCommand

### ISSUE THREAD

**Issue by anne-k** [MvvmCross/MvvmCross#2520]
### Steps to reproduce :scroll:

In #1948, generic interfaces were added for IMvxCommand. Previously, I could use a property typed IMvxCommand and back it with an MvxCommand, MvxCommand\<T>, MvxAsyncCommand or MvxAsyncCommand\<T>. After this change, MvxAsyncCommand\<T> no longer implements the non-generic interface IMvxCommand, but MvxCommand\<T> still does.

### Expected behavior :thinking:
MvxCommand and MvxAsyncCommand are synchronous and asynchronous versions of each other and should exhibit the same behaviour as much as possible. Either the generic typed versions of both commands should implement the non-generic interface, or both of them shouldn't.

### Actual behavior :bug:
MvxCommand\<T> implements the interface IMvxCommand as well as IMvxCommand\<T>, whereas MvxAsyncCommand\<T> only implements IMvxCommand\<T>. This is inconsistent.

The best solution in my opinion would be to have MvxCommand\<T> no longer implement IMvxCommand either, though it would force us (and probably others too) into a lot of refactoring (probably for the better). But either way, they should be consistent.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR to fix this? I think we can make this a breaking change for 6.0.

From what i looks like it is fairly easy, just remove the second interface, and add `RaiseCanExecuteChanged` to the `IMvxCommand<T>` interface.

**Comment by softlion** [comment]
I do not agree. The best would be to implement the non generic interface for many reasons:
- AOT compilation size will decrease
- You can create an array of IMvxCommand to store all commands, which has many benefits

**Comment by nickrandolph** [comment]
@softlion thanks for that - I was just about to come back and say something similar

**Comment by anne-k** [comment]
@softlion - your first point: I didn't think of that, how big of a difference do you think it will make?
As for your second point, @nickrandolph said the same thing on the pull request #2536, I replied to it there. I don't understand what advantage a common IMvxCommand interface would have over the existing ICommand interface. You can make an array of ICommands to store all of your commands, that doesn't change.

**Comment by softlion** [comment]
Hi Anne. For 1st point, it will create a new class for each T in your project. With duplicated methods each time. If you have a base class instead, the base methods will be included only once, making your binary size smaller.

For second point, you don't understand the advantage because we don't talk about what we are currently doing with Commands. We have an internal framework managing all commands in a viewModel. So it needs to be a list of, at least, ICommand (maybe not IMvxCommand). I suppose others too have an internal framework like this.

**Comment by anne-k** [comment]
Hmm I think you may have misunderstood me there. I understand the need for there to be a common interface between them. What I don't understand is why that interface has to be IMvxCommand when we already have ICommand available for that purpose. You yourself are now saying it could be either, too. There could be a very good argument in favor of IMvxCommand that I'm missing, but so far I haven't seen it yet.

In the current version of MvvmCross, since 5.0.3, it is not possible to use IMvxCommand in the way you propose if you have an MvxAsyncCommand\<T> anywhere in a ViewModel. That is exactly why I even came across this issue in the first place, we were using IMvxCommand as the highest level interface in a lot of places and the update to 5 broke our code.

As for the other point: I'm afraid I don't understand how this change would impact that... We're talking about interfaces here, not base classes. Interfaces don't implement methods. Unless something happens under the hood that I'm not aware of?

**Comment by nickrandolph** [comment]
The IMvxCommand implements RaiseCanExecuteChanged so you might want to have a collection of IMvxCommand objects (not ICommand). This reason alone should be enough to leave the inheritance as it currently is.

**Comment by softlion** [comment]
@nickrandolph  That's it.

**Comment by anne-k** [comment]
Fair enough. Then we should make it so all commands implement that interface, like they used to before 5.0.3.

I won't get around to it until next week, feel free to edit the pull request, otherwise I'll do it then.

**Comment by martijn00** [comment]
I've merged #2552 instead of this one. Thanks for contributing and helping!
