### ISSUE TITLE
MvxBottomSheetDialogFragment OnDestroy does not consider finsished parameter

### ISSUE THREAD

**Issue by aaaabcv** [MvvmCross/MvvmCross#2525]
The OnDestroy() Method just calls ViewModel?.ViewDestroy().

Compare to MvxAppCompatDialogFragment (which is correct I believe):

ViewModel?.ViewDestroy(viewFinishing: IsRemoving || Activity == null || Activity.IsFinishing);

### Expected behavior :thinking:
Tell us what should happen

### Actual behavior :bug:
Tell us what happens instead

### Configuration :wrench:

**Version:** 6.2
**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Thanks for reporting this issue!
