### ISSUE TITLE
Xamarin.Forms navigation is broken if a page uses MvxContentPagePresentationAttribute.NoHistory = true

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2538]
### Steps to reproduce :scroll:

1. Navigate to a content page with `MvxContentPagePresentationAttribute.NoHistory = true`

### Expected behavior :thinking:
Navigation should happen. 

### Actual behavior :bug:
Nothing happens. It works as soon as I set `NoHistory` to `false`. It works with MVX 5.5.0 so it must be some change after that. **Note**: Only tested on iOS yet.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by suranyig** [comment]
We are using the XF Master Detail navigation with latest stable MvvmCross v5.6.3. We are having more than one detail pages. If we set "NoHistory=true" on a DetailPage then during the navigation from one detail page to another (from master menu) we see an empty gray layout what's flashing between the pages on Android. You can check the bug on Playground project (choose mixed navigation and switch to Tabs menu after login page).

**Comment by CodeMarkram** [comment]
I am experiencing a similar issue when I am using the attribute `(WrapInNavigationPage = false)`.
The navigation works for Android, but for iOS nothing happens when I navigate to the page.
If I set `WrapInNavigationPage`to `true`, then it works.

I am using MvvmCross v5.6.3 and Xamarin Forms v2.5.0.x

**Comment by borbmizzet** [comment]
I've noticed that having 
`[MvxContentPagePresentation(WrapInNavigationPage = true, NoHistory = true)]`
and
`<mvxviews:MvxContentPage xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:mvxviews="clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms"
    xmlns:viewModels="clr-namespace:Test.Core.ViewModels;assembly=Test.Core"
    x:Class="Test.Core.Pages.LoginPage" x:TypeArguments="viewModels:LoginViewModel"
    BackgroundImage="background.png"
    NavigationPage.HasNavigationBar="True" />`
causes the program to crash if LoginViewModel is the starting ViewModel (not sure about when it isnt).
However, it seems to run fine with `NavigationPage.HasNavigationBar="False"`.

**Comment by nickrandolph** [comment]
@Sebastian1989101 do you know whether this is still an issue on 6.1 branch?

**Comment by nickrandolph** [comment]
@Sebastian1989101 can you try this out on v6.2 and confirm if this is still an issue. Are you able to reproduce on the Playground sample?

**Comment by jacob925** [comment]
it's broken in my project. where is the playground sample?

**Comment by juanagu** [comment]
> @Sebastian1989101 can you try this out on v6.2 and confirm if this is still an issue. Are you able to reproduce on the Playground sample?

Same error using v6.2.2.
