### ISSUE TITLE
Different behavior when using HostViewModelType to use a TabbedPage within a MasterDetail navigation (Forms)

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2545]
Android messes it up and it works on iOS. Currently it is an app breaking bug not to be able to use TabbedPages within MasterDetail navigations. 

### Steps to reproduce :scroll:

Use a TabbedPage within a MasterDetail navigation with the following Attrribute configuration: 

- TabbedRootPage: `[MvxMasterDetailPagePresentation(Position = MasterDetailPosition.Detail, WrapInNavigationPage = true, NoHistory = true)]` 
- TabbedChildPage(s): `[MvxTabbedPagePresentation(WrapInNavigationPage = false, HostViewModelType = typeof(TabbedRootViewModel))]`

### Expected behavior :thinking:
Same behavior on Android as on iOS.

### Actual behavior :bug:
With the configuration above: "System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer'."

If I use `[MvxTabbedPagePresentation(Position = TabbedPosition.Root)]` instead of the `MvxMasterDetailPagePresentationAttribute` on the TabbedRootPage instead while the TabbedChildPage(s) still using the `HostViewModelType`, the navigaiton to the TabbedRootPage is triggered over and over and over again (endless loop). 

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@Sebastian1989101 are you able to provide an example of this using the playground sample - please submit via a PR.

**Comment by nickrandolph** [comment]
@Sebastian1989101 would you mind also checking this bug against v6 (develop branch)
