### ISSUE TITLE
IMvxNavigationService does not load all the fragments while initializing a TabLayout

### ISSUE THREAD

**Issue by jandroalvarez** [MvvmCross/MvvmCross#2547]
I've a TabLayout and use a MvxTabLayoutPresentation presenter for every tab. I've followed the code you have for initializing the tabs and I call Navigate() for every tab in the host view model as you do here:

https://github.com/MvvmCross/MvvmCross/blob/a23bdcf42865bf828d8ad44d5781de6150f54d86/Projects/Playground/Playground.Core/ViewModels/MixedNavTabsViewModel.cs

```
var tasks = new List<Task>();
tasks.Add(NavigationService.Navigate<OneViewModel>());
tasks.Add(NavigationService.Navigate<TwoViewModel>());
tasks.Add(NavigationService.Navigate<ThreeViewModel>());
await Task.WhenAll(tasks);
```

### Steps to reproduce :scroll:

1. Create an Android TabLayout and link each fragment tab to a MvxTabLayoutPresentation

2.  In the TabLayout ViewModel host initialize all the tabs calling IMvxNavigationService like you do here:
https://github.com/MvvmCross/MvvmCross/blob/a23bdcf42865bf828d8ad44d5781de6150f54d86/Projects/Playground/Playground.Core/ViewModels/MixedNavTabsViewModel.cs

3. Add a breaking point to every OnCreateView method on the fragment class of every tab. You'll notice that only the views for the first two tabs that you initialized with IMvxNavigationService have been created. 

### Expected behavior :thinking:
All the tabs should be loaded. When you call Navigate() for every ViewModel.

### Actual behavior :bug:
Only the fragments for OneViewModel and TwoViewModel are created and initialized. The third one is loaded only when you tap on it.

Besides, I've detected that it's a matter of order. If you call OneViewModel, then ThreeViewModel and then TwoViewModel, the fragments of OneViewModel and ThreeViewModel are loaded.

### Configuration :wrench:

**Version:** 5.5.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
This is how Android ViewPager's `FragmentStatePagerAdapter` works. It will load 2 fragments as default and will load more as you go. If you need to change that behavior, you will want to modify the ViewPager `OffscreenPageLimit` property (or maybe override the behavior of our Android ViewPresenter to use a custom `PagerAdapter`).

**Comment by jandroalvarez** [comment]
Thanks @nmilcoff ! I've changed the ViewPager property and it's solved
