### ISSUE TITLE
Correct way to register navigation service

### ISSUE THREAD

**Issue by albertofustinoni** [MvvmCross/MvvmCross#2571]
Nowhere in the documentation is explained what is the proper way to register the navigation service. What are we supposed to do?

Calling `RegisterNavigationServiceAppStart<StartVMName>();` keeps failing because IMvxNavigationService is not registered, but trying ` Mvx.ConstructAndRegisterSingleton<IMvxNavigationService, MvxNavigationService>();` also fails.

**Comment by martijn00** [comment]
Please fill out the fill template.
