### ISSUE TITLE
HTML email body doesn't show properly in Android

### ISSUE THREAD

**Issue by g0rdan** [MvvmCross/MvvmCross#2572]
I'm using email plugin and I've noticed that when I have to use html in email body (flag "isHtml" = true) Android does not render body as I'd expect. It seems Android doesn't show `<h>` and `<font>` tags at least. To reproduce the bug, launch iOS and Android version from repo ([https://github.com/g0rdan/MvvmCrossEmailPluginBug](https://github.com/g0rdan/MvvmCrossEmailPluginBug)) and compare the results.

### Steps to reproduce :scroll:

1. Download and launch the test project for iOS

2. Loot at result: 
![image](https://user-images.githubusercontent.com/1484013/35639226-8e0cf1a6-0687-11e8-903b-9e23547e2c8b.png)

3. Launch the test project for Android

4. Look at result: 
![screenshot_2018-01-31-17-29-25](https://user-images.githubusercontent.com/1484013/35639236-960b03d4-0687-11e8-9753-92d54ce63d1a.png)

### Expected behavior :thinking:
The rendering of html bodies should be the same.

### Actual behavior :bug:
They're not the same.

Is this a bug or Android has some specifications for constructing html into email bodies?

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by g0rdan** [comment]
I've used Gmail as email client.

**Comment by nickrandolph** [comment]
@g0rdan if you use a different email client, do you see the same issue? Might be worth looking at the html that is generated and seeing whether it's well formed

**Comment by nickrandolph** [comment]
@g0rdan are you able to use create an email in Android directly and see if you can get it to look the same as the iOS version? We suspect this is an issue with how the email is being rendered, rather than how it's being created

**Comment by g0rdan** [comment]
@nickrandolph Sorry for not answering so long. I'll look at the issue on weekends and will let you know about results.

**Comment by g0rdan** [comment]
I tried many ways to call email intent directly and watched the same result. Generally, I used something like this: 
```
var emailIntent = new Intent(Intent.ActionSend);
emailIntent.SetType("text/html");
var htmlBody = Html.FromHtml(body, FromHtmlOptions.ModeLegacy);
emailIntent.PutExtra(Intent.ExtraText, htmlBody);
StartActivity(emailIntent);
```
I guess we could close the issue.
