### ISSUE TITLE
How to use mvvmcross if using xamarin native embed Xamarin.Forms?

### ISSUE THREAD

**Issue by haohighview** [MvvmCross/MvvmCross#2573]
How to use mvvmcross if using xamarin native embed forms? Now does mvvmcross support this?

**Comment by martijn00** [comment]
Please fill out the issue template. General questions should go on StackOverflow.

**Comment by jamesatgithub** [comment]
@martijn00 just asking for a confirmation as little info found by search about this: does MvvmCross support Forms Embedding with native project?
