### ISSUE TITLE
Shared Project with MvvmCross not worked well

### ISSUE THREAD

**Issue by Wenfengcheng** [MvvmCross/MvvmCross#2574]
I want to embedd MvvmCross into my Xamarin Shared Project, I add a view named **HomePage.xaml**, and add a binding viewmodel named **HomeViewModel**, also I add ```Setup.cs``` file and init code on platform project, but this issue came accross:
```
MvvmCross.Platform.Exceptions.MvxException: Problem seen creating View-ViewModel lookup table - you have more than one View registered for the ViewModels: 2*HomeViewModel (HomeView,HomeView) ---> System.ArgumentException: An item with the same key has already been added. Key: MvxFormsTemplate.ViewModels.HomeViewModel
```
Does MvvmCross support Shared Project? If it worked, any template could be referenced?

**Comment by martijn00** [comment]
Please fill out the issue template. General questions like this should go on StackOverflow.
