### ISSUE TITLE
iOS:  UITextField auto-correct bug. Not updating after auto-correct

### ISSUE THREAD

**Issue by vallgrenerik** [MvvmCross/MvvmCross#2575]
### Steps to reproduce :scroll:

1. Create a UITextField, bind to a simple string

2. Write some misspelled word. (Asd for example, iOS will suggest "Ass" .... :) 

3. Let iOS Autocorrect your text to Ass. Do not write anything after the auto-correction.

4. The string will not be updated with "Ass", it's still Asd.

### Expected behavior :thinking:
The string to be updated with the auto-corrected text.

### Actual behavior :bug:
The string still contains old value before auto-correct.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
So does this mean that the string in the View is `Ass` but the string in the ViewModel is not updated and is `asd`?

**Comment by vallgrenerik** [comment]
@Cheesebaron Exactly

**Comment by Cheesebaron** [comment]
OK, our binding target might need to listen to another event to get triggered by auto-correct. Thank you for reporting this.

**Comment by vallgrenerik** [comment]
@Cheesebaron Thank you! Awesome framework. 👍

**Comment by nmilcoff** [comment]
This was fixed in #2682.
