### ISSUE TITLE
MvvmCross.Forms cannot replace app's MainPage

### ISSUE THREAD

**Issue by vkonst86** [MvvmCross/MvvmCross#2577]
### Steps to reproduce :scroll:

1. Create an app with root page that  is content or navigation page. Add additional page to project with type of MvxTabbedPage and attribute [MvxTabbedPagePresentation(Position = TabbedPosition.Root, WrapInNavigationPage = false)]
2. When root view is loaded try navigate to tabbed page using IMvxNavigatingService.Navigate and await the call, app will crash with exception "Cannot replace MainPage".

3. The reason of the crash is that MvxFormsApplicationDelegate method FinishedLaunching is not calling base.FinishedLaunching, so FormsApplicationDelegate private field "_window" is not initialised, and app crashes at method UpdateMainPage of FormsApplicationDelegate.

### Expected behavior :thinking:
MainPage gets replaced

### Actual behavior :bug:
App crash

### Configuration :wrench:

**Version:** 5.6.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by gunjanddave** [comment]
Facing the same issue. Any fix ?

**Comment by vkonst86** [comment]
I'm using workaround for now.
`private void InitializeInternalWindow(UIWindow window)
        {
            var windowField = typeof(FormsApplicationDelegate).GetField("_window", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            windowField.SetValue(this, window);
        }`
Call this method in FinishedLaunching after you created UIWindow, and pass it there.

**Comment by gunjanddave** [comment]
@vkonst86 - Thanks. Your workaround works like charm.

**Comment by nickrandolph** [comment]
@vkonst86 are you able to reproduce this in the playground sample? If so, can you submit a PR with your changes showing how to reproduce the issue

**Comment by martijn00** [comment]
This is fixed in the playground.

**Comment by tampham1210** [comment]
@martijn00  can you add the reference source code over here?
