### ISSUE TITLE
Pin NuGet package dependencies

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#2581]
After the conversion to .NET Standard, it doesn't seem like there is a neat way to pin `ProjectReference` dependencies to a specific version, like it was possible in a `.nuspec` previously.

### Steps to reproduce :scroll:

1. Install version unstable.157 of MvvmCross
2. Update a plugin to unstable.158
3. MvvmCross is not updated to 158

### Expected behavior :thinking:
Everything should be pinned like it was previously

I see that ReactiveUI does it with https://github.com/cake-contrib/Cake.PinNuGetDependency, we should look into doing something similar.

@ghuntley. @onovotny any advice on this?

**Comment by ghuntley** [comment]
See our build.cake over at ReactiveUI for cake build script usage instructions. AFAIK there's still no other way to do this. Copy our implementation freely. Enjoy.

PPS you definitely want to pin everything.

**Comment by Cheesebaron** [comment]
@ghuntley seems like Cake.PinNuGetDependency doesn't take a list of dependencies to pin. So I would have to run that multiple times. I guess that was not a requirement for ReactiveUI. I guess you accept Pull Requests on the tool?

**Comment by ghuntley** [comment]
Indeed we run the tool multiple times for each package that needs to be pinned.

https://github.com/reactiveui/ReactiveUI/blob/f4e99716ae165a0b89e18a3f68b88f9dc720e20b/build.cake#L304

The package array is the same one we use for pushing NuGet packages. We specifically only push whitelisted packages (for extra safety to prevent against accidental publishing of erroneous packages).

Yeah we would take PRs on the tool to take an array - don't break the existing API though.

**Comment by onovotny** [comment]
@Cheesebaron I'm not exactly sure what you mean by "Pin a specific version" here in this context? What are you trying to pin exactly?

**Comment by Cheesebaron** [comment]
@onovotny So we have some projects that depend on the "main" package MvvmCross and some others that have interdependencies.

In a nuspec file we could pin the version by writing `[version]` for the version number in the nuspec, where `version` was the actual SemVer.

**Comment by onovotny** [comment]
Oh, that looks like this outstanding issue: https://github.com/NuGet/Home/issues/5525

That said, I generally would discourage that as can lead to situations without any workarounds.
