### ISSUE TITLE
MvxAppStart swallows exceptions

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#2586]
@nickrandolph pinged us on Slack that the following was an issue:

### Steps to reproduce :scroll:

1. Make `Start` crash in `MvxAppStart`
2. See exception crash the app, can't be caught from outer scope

### Expected behavior :thinking:
Exception should bubble up to the caller, but doesn't because we use `async void`.

### Actual behavior :bug:
App crash

### Configuration :wrench:

**Version:** 5.x

**Comment by nickrandolph** [comment]
This should be addressed by https://github.com/MvvmCross/MvvmCross/pull/2674
