### ISSUE TITLE
UWP Photo chooser distorts photo on windows phone

### ISSUE THREAD

**Issue by zzhang31** [MvvmCross/MvvmCross#2588]
### Steps to reproduce :scroll:

1. Use the picture chooser plugin for UWP to take a photo using the camera

2. When displaying the stream captured, you should see the photo being distorted.

### Expected behavior :thinking:
Expecting the picture from the stream to not be distorted. This behavior is not seen on Windows laptop or surface pro, only on windows phone.

### Actual behavior :bug:
The photo looks distorted on windows phone, it looks fine on windows laptop or surface pro.

###Current workaround
I loaded the source code and found the problem happens when calling "ResizeJpegStreamAsync". I changed that if my device is a windows phone then I don't call the resize and just return the original stream, and that works.

### Configuration :wrench:

**Version:** 5.2.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@zzhang31 can you add a sample of this to the playground uwp sample (develop branch) and submit via a PR.

**Comment by nickrandolph** [comment]
@zzhang31 I'm going to close this issue as it's raised against an old version, according to your issue it affects windows phone only and you haven't responded to the request for further information. If you're able to provide a PR with a sample showing this, we'll gladly reopen the issue for further investigation
