### ISSUE TITLE
Custom Presentation Hint Handler is ignored

### ISSUE THREAD

**Issue by salvador-guerrero** [MvvmCross/MvvmCross#2589]
### Steps to reproduce :scroll:

Following the instructions on the [docs](https://www.mvvmcross.com/documentation/presenters/view-presenters#requesting-presentation-changes)

1. Create custom presentation hint

```
    public class MyPresentationHint : MvxPresentationHint
    {
    }
```

2. Register handler on Android presenter

```
namespace MyApp.Droid
{
    public class Setup : MvxFormsAndroidSetup
    {

        protected override IMvxAndroidViewPresenter CreateViewPresenter()
        {
            var presenter = base.CreateViewPresenter();
            presenter.AddPresentationHintHandler<MyPresentationHint>(hint => true);
            return presenter;
        }
    }
}
```

3. Call ChangePresentation

```
private async Task ExecuteMyCommand()
        {            
            navigationService.ChangePresentation(new MyPresentationHint());
        }
```

### Expected behavior :thinking:
Func inside AddPresentationHintHandler is executed

### Actual behavior :bug:
Func inside AddPresentationHintHandler is not executed

`[0:] mvx:Warning: 15.44 Hint ignored MyPresentationHint` is logged to console

### Configuration :wrench:

Visual Studio 2017 Community v15.5.2
MvvmCross version 5.6.3
MvvmCross.Forms version 5.6.3
Xamarin.Forms version 2.5.0.122203

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by DavePilks** [comment]
Has the fix for this been released yet?
