### ISSUE TITLE
Platform.Mac startup exception Foundation.You_Should_Not_Call_base_In_This_Method

### ISSUE THREAD

**Issue by sujitp81** [MvvmCross/MvvmCross#2591]
### Steps to reproduce :scroll:

1. Cloned the repo, switch to tag 5.6.3 by git checkout 5.6.3 (note: had the same issue in master)

2. Opened MvvmCross_All.sln in Visual Studio for Mac 7.3.3 (Build12) Xamarin.Mac 4.0.0.216 

3. Removed/Unloaded all iOS and Android-related projects

4. Built and ran Playground.Mac

### Expected behavior :thinking:
Tell us what should happen
The Playground.Mac app should load
### Actual behavior :bug:
Tell us what happens instead
Crash/Exception Foundation.You_Should_Not_Call_base_In_This_Method
Screenshot: 
https://www.dropbox.com/s/ah40si0qmci0i59/MvvmCross.Playground.Mac.Exception.png?dl=0

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [X] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2499
