### ISSUE TITLE
StarterPack does not generate files on vs17

### ISSUE THREAD

**Issue by losmacko** [MvvmCross/MvvmCross#2595]
I' m using vs17 15.5.6 with  xamarin 8.1.5.0
After adding package mvvmcross.starterPack no additional files are added to project.
I try to add nuget to different types of project PCL/Android/.netStandard references are corrected added but no files was generated.
I also try from nuget console and result are the same.
**Version:** every including latest 5.6.3

**Comment by Cheesebaron** [comment]
Sorry we cannot do anything here. This is a change in how NuGet handles content included in NuGet packages.

We are looking into getting templates for VS and VSfM.
