### ISSUE TITLE
Improve/document the getting started experience for developing MvvmCross itself

### ISSUE THREAD

**Issue by buzzware** [MvvmCross/MvvmCross#2608]
I've spent a few hours trying to get the MvvmCross solution, tests etc compiling and have had a lot of problems. Is there a guide for how to clone the repo, run any necessary scripts or whatever, through to building the entire solution?
And what are the assumptions? Can I use VS4Mac? Do I need certain Android SDKs installed? What are the important branches, and what are their purpose?

I get errors when I open the solution relating to these Android projects not being installed. They seem to be the projects for what are normally installed as packages. Is this necessary?

![image](https://user-images.githubusercontent.com/28285/36081102-892f9196-0fd5-11e8-9373-30837b5943d5.png)
![image](https://user-images.githubusercontent.com/28285/36081105-94c8cfa4-0fd5-11e8-8297-e5fdedbf3cc3.png)
![image](https://user-images.githubusercontent.com/28285/36081109-9c56382e-0fd5-11e8-8c2f-9c64ab564c6c.png)

![image](https://user-images.githubusercontent.com/28285/36081080-3026099a-0fd5-11e8-9aaf-66c7c627bc81.png)

Being able to get to first base of being able to build and run the tests and sample projects without pain would greatly increases the chances of contributions to the project.
If necessary, there could be one .sln for core developers, and another for those poking around with the framework.

**Comment by nickrandolph** [comment]
@buzzware are you using the latest preview of VS for Windows? Unfortunately Multi-targetting support within VS is still a work in progress. There's not much we can do about that in the short term.

**Comment by buzzware** [comment]
No, I don't have a Windows machine, or a VS license, but I've been working with Xamarin on Mac for almost 3 years. I also have a Jetbrains Rider license.

**Comment by nmilcoff** [comment]
Unfortunately the solution won't build in the current VS4Mac, as multitarget projects are not yet supported. Best thing I can recommend you is to explore the source code in a previous version (before the netstandard migration was done - or maybe just checkout the 5.6.3 tag)

**Comment by buzzware** [comment]
OK, thats interesting. Is it only certain projects in MVVMCross.sln that require multitarget projects support?
Would it be possible to create a .sln file just for the tests, or just for the tests on Mac?

**Comment by Cheesebaron** [comment]
They are all multi-target sdk projects. Making a sln file for tests wouldn't work since you still need to build everything else.

**Comment by martijn00** [comment]
Some more information in multi-target: https://oren.codes/2017/01/04/multi-targeting-the-world-a-single-project-to-rule-them-all/
And: https://www.bartwolff.com/Blog/2017/03/20/targeting-multiple-net-platforms-in-a-single-nuget-package-w

**Comment by georgikoemdzhiev** [comment]
I am new to MVVM Cross, I have tried to go through the current "Getting Started" page and I found it very outdated and not useful at all. Please improve the getting started guides as this is what people use to check out the framework currently. If they can't get it working fast the chances are they won't try it, speaking from personal experience here.

**Comment by nickrandolph** [comment]
Any thoughts on how to progress this issue? or shall we close it for the moment?
