### ISSUE TITLE
PluginLoaders not found for platform specific plugins

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#2611]
MvxAndroidSetup and the other platform setups look for a specific extension to the plugin assembly. So for Android it expects an assembly that is called `MyPlugin.Useful.Droid` where the Android implementation resides. If it doesn't find that, it doesn't try to fall back to anything else and then just explodes.

This happens due to when switching to Multi-target, the assembly names are now all the same for all assemblies. Platform specific or not.

@AlexStefan was very quick to provide a repro sample https://github.com/AlexStefan/template-app/blob/master/Internationalization/

The Core and Droid projects there point at MvvmCross in the folder `../../mc`

### Steps to reproduce :scroll:

1. Add one of the official plugins
2. Make sure Bootstrap is added
3. Load a ViewModel which uses that plugin
4. 💥 app crashes

### Expected behavior :thinking:
App should run

### Actual behavior :bug:
App crashes

### Configuration :wrench:

**Version:** 6.0.0-beta2

**Comment by nmilcoff** [comment]
Can we close this one now that the new plugins architecture is in?
