### ISSUE TITLE
MvvmCross.Forms version out of sync with Xamarin.Forms Tutorial

### ISSUE THREAD

**Issue by echuck66** [MvvmCross/MvvmCross#2620]
### Steps to reproduce :scroll:

1. Follow steps outlined in Xamarin.Forms tutorial found here: 
https://www.mvvmcross.com/documentation/platform/forms/xamarin-forms?scroll=467

and here:

https://github.com/MvvmCross/MvvmCross/blob/master/docs/_documentation/platform/forms/xamarin-forms.md

2. After completing the steps and adding all of the appropriate Using statements to reference the correct namespaces, there remains one problem: The namespace MvvmCross.Forms.Core is missing.

### Expected behavior :thinking:
The tutorial instructions indicate that we should be able to run the application at this point, but it will not build due to the missing namespace.

### Actual behavior :bug:
App will not build.

### Probable Cause: 
It appears that the MvvmCross.Forms.Core namespace exists in the Develop branch, but not in the master branch. I am thinking that the nuget package has not caught up with the tutorial.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2731
