### ISSUE TITLE
Update documentation based on new namespaces

### ISSUE THREAD

**Issue by nmilcoff** [MvvmCross/MvvmCross#2621]
Now that we have changed the files structure and namespaces for most files we need to update all docs containing links to the source code.

A lot of these links are currently pointing to `develop`, but I think `master` should be used instead for consistency.

**Comment by echuck66** [comment]
I logged an issue earlier today regarding the documentation / tutorial for getting started with Xamarin.Forms and MvvmCross. The documentation source shown is from the master branch, but the code referenced (MvvmCross.Forms.Core) exists only in the develop branch. It would seem that someone promoted the documentation for this part before the actual code was promoted.

**Comment by Cheesebaron** [comment]
And the release branch for 6.0.0, which is where the betas are released from.

**Comment by nickrandolph** [comment]
@echuck66 are you able to start amending the documentation in the places where it's no longer up to date - even if you could highlight areas that need changing/fixing, that'd help with the move to v6

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2731

**Comment by nmilcoff** [comment]
@martijn00 I think this isn't fixed in that PR. This issue is about all links on the docs pointing to source code URLs that were modified

**Comment by nickrandolph** [comment]
Hi all, is someone prepared to pick this up? what's still outstanding?
