### ISSUE TITLE
Xamarin.Forms Android - First page cannot reference Application level StaticResources

### ISSUE THREAD

**Issue by duckwaffle** [MvvmCross/MvvmCross#2622]
Repo for repro: https://github.com/duckwaffle/MvxFormsVmDuplication

### Steps to reproduce :scroll:

1. Add resources (any resource will do, color, converter whatever) to your Xamarin.Forms App.xaml

2. Go to the XAML of your first launched page (whatever page is for RegisterNavigationServiceAppStart<>) and add an element which references the StaticResource

3. Start the app

### Expected behavior :thinking:
Tell us what should happen
The app should start, and the visual element that references the StaticResource will be visible

### Actual behavior :bug:
Tell us what happens instead
App fails to start. Occasionally you will see a TargetInvokationException and something in the output will say that it cannot find the StaticResource for the key you provided, but more often than not you will just see a blank screen because the first navigation never happened.

When running the UWP project, everything works fine, however the Android one should show the behaviour I'm describing.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
I'm hitting this issue too, easy to reproduce. I'll try to dig into it in the next couple of days.
