### ISSUE TITLE
Cleanup "Sidebar" plugin

### ISSUE THREAD

**Issue by nmilcoff** [MvvmCross/MvvmCross#2626]
In #2530 the old iOS Support was moved into the plugins folder and rethought as a plugin, as you can see [here](https://github.com/MvvmCross/MvvmCross/tree/develop/MvvmCross.Plugins/Sidebar).

The problem is that project did not only contain an implementation for a sidebar menu, but also a few more utility methods / classes. 

__We need to cleanup this before 6.0 hits stable!__

**Comment by martijn00** [comment]
This was already done in the upgrade. I moved the util classes to the main library. I just made a PR to clean the last file.
