### ISSUE TITLE
MvvmCross.Plugin.Location.Fused 5.6.3 not compatible with MvvmCross.Droid.Support.v7.AppCompat 5.6.3

### ISSUE THREAD

**Issue by marcfeldman** [MvvmCross/MvvmCross#2633]
### Steps to reproduce :scroll:

1.Using VS2017 NuGet Package Manager:  
MvvmCross.Droid.Support.v7.AppCompat  5.6.3  
depends on  
Xamarin.Android.Support.v7.AppCompat (>=25.3.1)

2. Xamarin.Android.Support.v7.AppCompat  26.1.0.1
depends on
MonoAndroid, Version=**8.0**

3. MvvmCross.Plugin.Location.Fused  5.6.3
depends on
MonoAndroid, Version=**0.0**

### Expected behavior :thinking:
MvvmCross should not require different MonoAndroid versions.

### Actual behavior :bug:
Location.Fused requires exactly 0.0, while AppCompat requires exactly 8.0.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Yeah, this is fixed in 6.0.0. Closing this.

**Comment by marcfeldman** [comment]
Hi,
Is this just a documentation issue, or is the software actually broken until 6.0.0?
Thx,
M.

**Comment by Cheesebaron** [comment]
It is broken until 6.0.0.
