### ISSUE TITLE
Forms iOS TabbedPage - MoreNavigationController

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2634]
When using a TabbedPage with more than 6 pages within, the "More"-Button appears on iPhones. In normal Xamarin.Forms you can use a custom renderer to change the behaviour of the More-Page. But this seems not to work when using MVX. 

Here is my code for the custom renderer (WillShowViewController never gets called): 
```
public class CustomTabbedRenderer : TabbedRenderer
{
    protected override void OnElementChanged(VisualElementChangedEventArgs e)
    {
        base.OnElementChanged(e);
        if (e.OldElement == null)
            MoreNavigationController.Delegate = new CustomMoreNavigationControllerDelegate();
    }
}

internal class CustomMoreNavigationControllerDelegate : UINavigationControllerDelegate
{
    public override void WillShowViewController(UINavigationController navigationController, UIViewController viewController, bool animated)
    {
        viewController.NavigationController.NavigationBarHidden = true;
        viewController.View.BackgroundColor = UIColor.FromRGB(0xb9, 0x9f, 0x65);
        viewController.View.TintColor = UIColor.FromRGB(0x00, 0x00, 0x00);

        if (viewController.View is UITableView tableView)
        {
            tableView.SeparatorColor = UIColor.FromRGB(0x55, 0x49, 0x2e);
            foreach (var cell in tableView.VisibleCells)
            {
                cell.BackgroundColor = UIColor.FromRGB(0xb9, 0x9f, 0x65);
                cell.TextLabel.TextColor = cell.TintColor = UIColor.FromRGB(0x00, 0x00, 0x00);

                if (cell.ImageView?.Image != null)
                {
                    cell.ImageView.Image = cell.ImageView.Image.ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
                    cell.ImageView.TintColor = UIColor.FromRGB(0x00, 0x00, 0x00);
                }
            }
        }
    }
}
```

### Steps to reproduce :scroll:

1. Create a TabbedPage with more than 6 child pages

2. Click on the "More"-Button

### Expected behavior :thinking:
MVX should act like the normal Xamarin.Forms or at least have some kind of option to modify this page. 

### Actual behavior :bug:
It's just not working and therefore the TabbedPage with more than 6 child pages is unusable. 

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Does your renderer get invoked?

**Comment by Sebastian1989101** [comment]
@nickrandolph yes the renderer gets invokes and the `MoreNavigationController.Delegate = new CustomMoreNavigationControllerDelegate();` is executed. But the `WillShowViewController` is never invoked. This construct above is copied from another app of mine with is just using plain Xamarin.Forms and it works there just fine. So it must be a problem with MVX.

**Comment by nickrandolph** [comment]
I’d suggest trying this in the Playground project and see whether you can trace what’s going on. This is the best way you can assist the mvx community resolve this issue

**Comment by Sebastian1989101** [comment]
@nickrandolph I'm already trying to figure it out in the playground but it is not as easy as expected. I hope I can find the reason for it.

**Comment by Sebastian1989101** [comment]
@nickrandolph After now 5 hours of tryin to get MVX compiled I have to give up. The project wont compile (also not on iOS) if the target Android SDK is missing and this stupid SDK Manager always hangs up on "Installing Archives" if I try to install SDK24... I guess the problem with the More-Page occurs in `MvvmCross.Platform.Ios.Views.MvxTabBarViewController` but I have no way to test it for now...

**Comment by nickrandolph** [comment]
Are you looking at develop (v6) or master (v5.6.3)? With the latter I would suggest unloading the Android projects as you don’t need them for iOS.

Nick Randolph | Built to Roam Pty Ltd | Co-Founder, Technical Lead | +61 412 413 425

Written whilst Roaming: Content is subject to oddities
________________________________

**Comment by Sebastian1989101** [comment]
Just tested it with MVX 6.0.0 (beta6) and still the same issue. I will make a small video about the issue when I'm home what the issue is. Maybe I can get the latest version of MVX compile to debug it myself a bit.

**Comment by Sebastian1989101** [comment]
Here is the video with a bit more details and a comparison between a normal Xamarin.Forms Shared App and a Xamarin.Forms MVX 6 App: https://youtu.be/BE_2ZzcoSDk

**Comment by nickrandolph** [comment]
@Sebastian1989101 as v6 is wrapping up we'll be looking to address more bugs like this in next release. Would you be able to submit this as a PR showing how to repro the issue with the playground samples?

**Comment by prcela** [comment]
The delegate variable is weak. It means it will be released immediately after assignment because no one other keeps reference on new CustomMoreNavigationControllerDelegate.

**Comment by nickrandolph** [comment]
@Sebastian1989101 can you submit your changes to the Playground sample that shows this issue as a PR please?

**Comment by SebastianKruseWago** [comment]
@nickrandolph This problem is still present in the latest release of MVX. I think it is exactly as @prcela stated, the `CustomMoreNavigationControllerDelegate` gets immediatly dispossed after the assignment. Strange thing is, that this does not happen in Xamarin.Forms without MVX. It can easily be rebuild, even in the Playground sample, by adding 6 or more pages to a tabbed page on iOS. As soon as there are more than 5 pages, iOS starts to add a "More" Tab at the end and moves the additional tabs into this list which can normally be modified by this delegate.
