### ISSUE TITLE
Using MvvmCross 5.6 NavigationService with autofac IoC

### ISSUE THREAD

**Issue by markbdev** [MvvmCross/MvvmCross#2636]
Struggling on SO for an answer and I have looked through the documentation. Any help would be very much appreciated.

I am undergoing an mvvmcross upgrade from 4.* to 5.6. This is in a Xamarin.Android project.
Autofac is registered as the IoT container and has been since day 1.
During the upgrade I have had to inject IMvxNAvigationService into a bunch of core services. These services are registered in CreateIocProvider in my setup class.
Now at runtime I am receiving the following: 
Cannot resolve parameter 'MvvmCross.Core.Navigation.IMvxNavigationService navService' of constructor 
How do I ensure that the underlying navigation service is registered in time? I cannot find anything in the docs.
I have tried swapping autofac for the Mvx IoC container which seemed to solve the problem but had to revert as it doesn't support registration of abstract classes.

Cheers

### Steps to reproduce :scroll:

1. Create an interface/class which has IMvxNavigationService service injected in its ctor

2. Configure Autofac as the IoC container and register the above interface in CreateIocProvider

3. Inject the above service into a ViewModel ctor

### Expected behavior :thinking:
The navigation service should resolve

### Actual behavior :bug:
Cannot resolve parameter 'MvvmCross.Core.Navigation.IMvxNavigationService navService' of constructor

### Configuration :wrench:

**Version:** 5.6

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Would you be able to provide us with a repro case?

As we discussed in slack, [this](https://github.com/MvvmCross/MvvmCross/blob/5.6.3/MvvmCross/Core/Core/Platform/MvxSetup.cs#L86) is where the nav service is registered. Maybe it worths to override the method and put a try catch block wrapping the call to base. Probably the service isn't registered successfully.

**Comment by markbdev** [comment]
I'll pull something together. I think it occurs because I am calling container builder.registermodule<myCoreModule>  inside of an overridden create IOC method. This means that core services are registered before the navigation service has been in the secondary initialization method. I can't find anyway around this so far for autofac.

**Comment by tougher** [comment]
I also use autofac and haven’t seen any issues at all. Have both Android and iOS.
How does your CreateIocProvider method and MvxApplication subclass look?

**Comment by tougher** [comment]
I’m actually considering changing back to the built-in container because of performance.

**Comment by nmilcoff** [comment]
@martijn00 was this solved by #2674? If not, could you link the PR for future reference?
