### ISSUE TITLE
MvvmCross.Plugins.Location.Fused.Droid.Plugin does not load

### ISSUE THREAD

**Issue by marcfeldman** [MvvmCross/MvvmCross#2637]
### Steps to reproduce :scroll:

1.  Using NuGet Manager, add MvvmCross.Plugin.Location.Fused 5.6.3 to .Droid project.

2.  Attempt to create a singleton service to watch for location changes.

3.  Find this message in the debug output:  
`[0:] ++mvx:Diagnostic:  1.21 Plugin Instance not found - will not autoload MvvmCross.Plugins.Location.Fused.Droid.Plugin`

### Expected behavior :thinking:
Plugin should load

### Actual behavior :bug:
Plugin not found

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [xx ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Can you add a folder named `Bootstrap` to your Droid project and then add [this class](https://github.com/MvvmCross/MvvmCross/blob/develop/nuspec/BootstrapContent/FusedLocationPluginBootstrap.cs.pp)? That should solve the problem.

Bootstrap files won't be necessary starting from v6, but that's still WIP (available in nuget as prerelease though)
