### ISSUE TITLE
get view api

### ISSUE THREAD

**Issue by HeMinzhang** [MvvmCross/MvvmCross#2643]
I think a idea,use api get a view.
For example, mvxwindows and mvxview all can use api get in wpf.
Mvvmcross View Can use api get will give users enough design imagination,Reduce the shackles of the mvvmcross framework.

**Comment by nmilcoff** [comment]
I'm afraid I don't really understand what you're proposing here.

Can you elaborate a bit? Maybe add some code snippets? diagrams?
