### ISSUE TITLE
-	Skipping DigitalWorkReport.Droid.Resource.String.fab_scroll_shrink_grow_autohide_behavior

### ISSUE THREAD

**Issue by marcfeldman** [MvvmCross/MvvmCross#2645]
### Steps to reproduce :scroll:

1.  Install:
-	VS 2017, 15.5.7 with Xamarin Workload
-	MvvmCross for Visual Studio, 2.0.1
-	Android SDK Platform 25
-	MvvmCross 5.2.1
-	Xamarin 25.4.0.2

2.  Build the .Droid project.

3.  I upgraded to MvvmCross 5.6.3.  

### Expected behavior :thinking:
I should get a clean build.

### Actual behavior :bug:
I get two warnings compiling the .Droid project:
-	Skipping DigitalWorkReport.Droid.Resource.String.fab_scroll_shrink_grow_autohide_behavior.  Please check that your Nuget Package Versions are compatible.
-	Skipping DigitalWorkReport.Droid.Resource.String.view_scroll-translation_autohide_behavior.  Please check that your Nuget Package Versions are compatible.

The warnings are the same for 5.6.3.
I found [ https://github.com/martijn00/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.Design/Resources/values/strings.xml](https://github.com/martijn00/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.Design/Resources/values/strings.xml)
but can’t tell if that is part of the problem or part of the solution.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [--] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I think it is because Android deprecated those functions. Can you make a PR to update to the new ones?

**Comment by marcfeldman** [comment]
I appreciate the vote of confidence but I am so new to Android development that I'm not sure where to start.
I'll do some research, and get back to you, maybe with some questions.
Thx,
M.

**Comment by martijn00** [comment]
It is used here: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/Design/Resources/values/strings.xml

The place where those strings are used is:
https://github.com/MvvmCross/MvvmCross/tree/develop/MvvmCross.Android.Support/Design/Behaviors

It is too show and hide a FAB button on scroll
In the newer support packages they replaced it with a new method.

https://github.com/MvvmCross/MvvmCross/issues/1563
https://github.com/ianhanniballake/cheesesquare/commit/5a5c3b29ae684e3a840b095bfca8d90a5a79af46

**Comment by tbalcom** [comment]
@martijn00 My project targeting API27 had 24 of these "Please check that your Nuget Package Versions are compatible" warnings while compiling against MvvmCross 5.6.3. The warnings typically only show up after Clean -> Rebuild All. The resources being mentioned are not found in my code or the MvvmCross code.

I've updated to MvvmCross 6.0.0-beta5 and the 24 "Please check that your Nuget Package Versions are compatible" warnings all went away as long as my project still referenced v26.1.0.1 of the support libraries. 

I then updated to version 27.0.2 of the support libraries still targeting MvvmCross 6.0.0-beta5 and now have 26 of the "Please check that your Nuget Package Versions are compatible" warnings. Reverting back to 26.1.0.1 of the support libraries makes the 26 warnings go away.

Doesn't this prove these warnings are related to the version of support libraries MvvmCross is built with vs the version of support libraries the consuming project is referencing? All the warnings go away when the MvvmCross and consuming app support library versions match.
