### ISSUE TITLE
ParameterValues doesn't set in NavigationService

### ISSUE THREAD

**Issue by Happin3ss** [MvvmCross/MvvmCross#2646]
### Steps to reproduce :scroll:

1. Use Task Navigate<TViewModel, TParameter>(TParameter param, IMvxBundle presentationBundle = null) where TViewModel : IMvxViewModel<TParameter>;

### Expected behavior :thinking:
ParameterValues should be set when create MvxViewModelInstanceRequest

### Actual behavior :bug:
Only PresentationValues was set, so ParameterValues is always null

### Configuration :wrench:

**Version:** 5.x - 6.x (beta)

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Happin3ss** [comment]
In this : 
public virtual async Task Navigate<TParameter>(Type viewModelType, TParameter param, IMvxBundle presentationBundle = null)
		{
			var request = new MvxViewModelInstanceRequest(viewModelType)
			{
				PresentationValues = presentationBundle?.SafeGetData()
			};
			...
		}
I believe It should be include ParameterValues = param?.SafeGetData()

**Comment by nmilcoff** [comment]
Where are you trying to use the parameterValues? It's not being filled because we now use the `TParameter` directly. It wasn't removed on v5 because ShowViewModel wasn't deprecated yet.

**Comment by Happin3ss** [comment]
Hi nmilcoff, currently our implementation is something like this : 
1/ When using navigation service at viewmodel ( It was ShowViewmodel in v4 then I did a migration to v5), we put in a parameter with a "view type"
2/ Then in the View, we overrided `Show ` in `iOSPresenter `and get parameterValues from `request `to handle how to show the View (I'm not sure it's the correct way but there are a lot of things in this so I think just leave it as it is)

**Comment by nmilcoff** [comment]
Using `presentationBundle` is the recommended way to do that. You can always create extension methods or anything similar to get rid of boilerplate code 🙂.

**Comment by Happin3ss** [comment]
Hi nmilcoff,
 Yes, I believe it is due to its flexible. But for now we are stucks at something like this : 
`NavigationService.Navigate<NextViewModel, Param>(new Param()
			{
				Type = ViewType.ContentView
			}, "A bundle with ViewType";`
 Because we need the `parameterValues` at 2 places : in the `Show` of `iOSPresenter` and also in each specific `viewmodel` (which can get by the `Prepare` method )
 So as you see, there is a bit noisy for me because I have to use `TParam` and also `presentationBundle` just for the same data. So do we have any better way to do this one ? 
 Thank you for your time.

**Comment by nmilcoff** [comment]
Yes, that's right... I don't think parameterValues will be back, so you'll have to use both parameters, unfortunately. 

As I previously said though, you can always build your own extension methods, factories, ... 🙂 

Closing this issue, but please reopen it if you think that's necessary.
