### ISSUE TITLE
Generic UWP views break compiled bindings

### ISSUE THREAD

**Issue by albertofustinoni** [MvvmCross/MvvmCross#2653]
### Steps to reproduce :scroll:

1. Follow instructions in [Pages abstraction and ViewModel binding](https://www.mvvmcross.com/documentation/platform/universal-windows-platform-uwp/universal-windows-platform-uwp?scroll=456#pages-abstraction-and-viewmodel-binding) to create views with typed viewmodels (instances of `MvxWindowsPage<TViewModel>`)

2. In the page XAML try to use compiled bindings (`x:bind` syntax)

3. Project does not compile

4. Use non generic views (`MvxWindowsPage` instances) and create a property to expose the viewmodel manually. For example:

```
class MyPage : MvxWindowsPage
{
 TViewModel VM => ViewModel as TViewModel;
}
```

and use x:bind on that property

5. Project compiles.
Seems like the XAML compiler doesn't like the way the ViewModel property is hidden in generic `MvxWindowsPage<T>`

### Expected behavior :thinking:
Project compiles successfully

### Actual behavior :bug:
Build fails with
`Microsoft.Windows.UI.Xaml.Common.targets(351,5): Xaml Internal Error error WMC9999: Object reference not set to an instance of an object.`

### Configuration :wrench:

**Version:** 5.6.3
**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Can you confirm whether this issue is still present in v6 (in the preview that is available)?

I suspect this is because of the new operator being used to exposed a typed VIewModel property and the XAML compiler not being smart enough to identify which property it should be referencing.

**Comment by albertofustinoni** [comment]
I would but my app is targeting .net Standard 1.4 (Windows Phone support) so the new version isn’t going to work for me :(

I also believe the new operator is what’s causing the issue with the Xaml compiler

**Comment by nickrandolph** [comment]
@albertofustinoni I would recommend not using generics for pages in UWP - they really don't play nice and I suspect you're going to be fighting the compiler. 
Before we close this issue as "won't-fix" can you replicate this issue using the playground sample and submit a PR showing the issue. I'll see if we can provide a work around that doesn't break the compilation

**Comment by nickrandolph** [comment]
@albertofustinoni I'm going to close this issue - the work around it to just not use generics and there's not much we can do about the XAML compiler
