### ISSUE TITLE
Suspend / Resume not working for MvvmCross.Forms.Uwp

### ISSUE THREAD

**Issue by flostr** [MvvmCross/MvvmCross#2662]
### Steps to reproduce :scroll:

1. Run Playground.Forms.Uwp from the `5.6.3` tagged: https://github.com/MvvmCross/MvvmCross/tree/5.6.3

2. Set a breakpoint or output a message in RootViewModel.SaveStateToBundle and ReloadFromBundle

3. Suspend the App

4. The breakpoints never get triggered / message never appears

5. [Optional] Comparing it to the working Playground.Uwp I added the following code to App.xaml.cs:

        public App()
        {
            this.InitializeComponent();
            this.Suspending += OnSuspending;
            this.Resuming += OnResuming;
        }

        private async void OnSuspending(object sender, SuspendingEventArgs e)
        {
            var deferral = e.SuspendingOperation.GetDeferral();

            //https://github.com/MvvmCross/MvvmCross/pull/2434/files
            var suspension = Mvx.GetSingleton<IMvxSuspensionManager>() as MvxSuspensionManager;

            if (suspension != null)
                await suspension.SaveAsync();

            // TODO: Save application state and stop any background activity
            deferral.Complete();
        }

        private async void OnResuming(object sender, object e)
        {
            var suspension = Mvx.GetSingleton<IMvxSuspensionManager>() as MvxSuspensionManager;

            if (suspension != null)
                await suspension.RestoreAsync();
        }

6. [Optional] The breakpoints never get triggered / message never appears

### Expected behavior :thinking:
When the app is suspended/resumed - SaveStateToBundle/ReloadFromBundle should be triggered in the ViewModel. 

### Actual behavior :bug:
When suspending the app SaveStateToBundle and when resuming ReloadFromBundle should be called in the ViewModel.

My guess:
The difference between the Native / Forms version is that `SaveFrameNavigationState(frame)` is never called, as there are no `_registeredFrames`. Even if it would be called it probably will not work as `OnNavigatedTo` and `OnNavigatedFrom` don't exist in `MvxContentPage` (Forms) - these exist in `MvxWindowsPage` (UWP):

        public async Task SaveAsync()
        {
            try
            {
                // Save the navigation state for all registered frames
                foreach (var weakFrameReference in _registeredFrames)
                {
                    IMvxWindowsFrame frame;
                    if (weakFrameReference.TryGetTarget(out frame))
                    {
                        SaveFrameNavigationState(frame);
                    }
                }

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by flostr** [comment]
When adding a suspensionManagerSessionStateKey to the constructor base - `SaveFrameNavigationState(frame)` is called, but as guessed this is not forwarded to the ViewModel.

        protected MvxFormsWindowsSetup(XamlControls.Frame rootFrame, LaunchActivatedEventArgs e)
            : base(rootFrame, "Suspension")

**Comment by nickrandolph** [comment]
@flostr can you confirm that this issue is still present in the latest code (develop branch)?

**Comment by flostr** [comment]
@nickrandolph Yes, it's still present. It works for `Playground.Uwp` but not for `Playground.Forms.Uwp`.
