### ISSUE TITLE
MKMapView Crashing on IOS 11.x

### ISSUE THREAD

**Issue by msalmanST** [MvvmCross/MvvmCross#2666]
### Steps to reproduce :scroll:

1.
Use MKMapView in your app.
2.
render on the ui
3.

### Expected behavior :thinking:
Map should display without any issue

### Actual behavior :bug:
App crashes on IOS 11 device with below debug logs
```
Could not inset compass from edges 9
Could not inset scale from edge 9
Could not inset legal attribution from corner 4
```

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [-] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Sorry, but what does this have to do with MvvmCross? MKMapView is a iOS control. Please elaborate.

**Comment by msalmanST** [comment]
Sorry for the confusion may be I should have ask this on Xamarin forums, if you know anything relates with IOS 11 and mapkit than I will be really grateful to you, I will further post my question on Xamarin forums.
