### ISSUE TITLE
App crashes after startup on a Huawei Mate 10 lite

### ISSUE THREAD

**Issue by Macjon** [MvvmCross/MvvmCross#2676]
### Steps to reproduce :scroll:

1. Create a new project with a basic MvvmCross setup

2. Run the app on a Huawei Mate 10 lite

3. App crashes immediately after startup

### Expected behavior :thinking:
The app should start on a Huawei Mate 10 lite

### Actual behavior :bug:
The app crashes after startup with the following stacktrace:

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid]   at MvvmCross.Platform.Mvx.Resolve[TService] () [0x00006] in C:\projects\mvvmcross\MvvmCross\Platform\Platform\Mvx.cs:33 
[MonoDroid]   at MvvmCross.Binding.Droid.BindingContext.MvxAndroidBindingContextHelpers.Current[T] () [0x00000] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\BindingContext\MvxAndroidBindingContextHelpers.cs:23 
[MonoDroid]   at MvvmCross.Binding.Droid.BindingContext.MvxAndroidBindingContextHelpers.Current () [0x00000] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\BindingContext\MvxAndroidBindingContextHelpers.cs:17 
[MonoDroid]   at MvvmCross.Binding.Droid.Views.MvxLayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x00014] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxLayoutInflater.cs:126 
[MonoDroid]   at Android.Views.LayoutInflater.n_Inflate_ILandroid_view_ViewGroup_Z (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 resource, System.IntPtr native_root, System.Boolean attachToRoot) [0x0000f] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.1d011802-c152-41a3-9127-705aa7a28104(intptr,intptr,int,intptr,bool)
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid]   at (wrapper dynamic-method) System.Object.1d011802-c152-41a3-9127-705aa7a28104(intptr,intptr,int,intptr,bool)
[MonoDroid]   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a(intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*)
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00073] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[MonoDroid]   at Android.App.Activity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00031] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[MonoDroid]   at MvvmCross.Platform.Droid.Views.MvxEventSourceActivity.OnCreate (Android.OS.Bundle bundle) [0x0000d] in C:\projects\mvvmcross\MvvmCross\Platform\Droid\Views\MvxEventSourceActivity.cs:33 
[MonoDroid]   at MvvmCross.Droid.Views.MvxActivity.OnCreate (Android.OS.Bundle bundle) [0x00000] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxActivity.cs:117 
[MonoDroid]   at basicMvvmcross.MainView.OnCreate (Android.OS.Bundle bundle) [0x0000e] in /Users/jonah/Desktop/basicMvvmcross/basicMvvmcross/MainView.cs:15 
[MonoDroid]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.2b58cb98-e03b-4736-8b9f-9fac58a61be4(intptr,intptr,intptr)
[mono] 
[mono] Unhandled Exception:
[mono] System.NullReferenceException: Object reference not set to an instance of an object.
[mono]   at (wrapper dynamic-method) System.Object.1d011802-c152-41a3-9127-705aa7a28104(intptr,intptr,int,intptr,bool)
[mono]   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a(intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*)
[mono]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00073] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[mono]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[mono]   at Android.App.Activity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00031] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono]   at MvvmCross.Platform.Droid.Views.MvxEventSourceActivity.OnCreate (Android.OS.Bundle bundle) [0x0000d] in C:\projects\mvvmcross\MvvmCross\Platform\Droid\Views\MvxEventSourceActivity.cs:33 
[mono]   at MvvmCross.Droid.Views.MvxActivity.OnCreate (Android.OS.Bundle bundle) [0x00000] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxActivity.cs:117 
[mono]   at basicMvvmcross.MainView.OnCreate (Android.OS.Bundle bundle) [0x0000e] in /Users/jonah/Desktop/basicMvvmcross/basicMvvmcross/MainView.cs:15 
[mono]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono]   at (wrapper dynamic-method) System.Object.2b58cb98-e03b-4736-8b9f-9fac58a61be4(intptr,intptr,intptr)
[mono] --- End of stack trace from previous location where exception was thrown ---
[mono]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono]   at Java.Interop.JniEnvironment+Strings.NewString (System.Char* unicodeChars, System.Int32 length) [0x0001e] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[mono]   at Java.Interop.JniEnvironment+Strings.NewString (System.String value) [0x00024] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[mono]   at Android.Runtime.JNIEnv.NewString (System.String text) [0x00009] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono]   at Java.Lang.Error..ctor (System.String message) [0x0001f] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono]   at Android.Runtime.JavaProxyThrowable..ctor (System.Exception innerException) [0x00007] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono]   at Java.Lang.Throwable.FromException (System.Exception e) [0x0001d] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono]   at Android.Runtime.AndroidEnvironment.UnhandledException (System.Exception e) [0x00067] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono]   at (wrapper dynamic-method) System.Object.2b58cb98-e03b-4736-8b9f-9fac58a61be4(intptr,intptr,intptr)
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]   at (wrapper dynamic-method) System.Object.1d011802-c152-41a3-9127-705aa7a28104(intptr,intptr,int,intptr,bool)
[mono-rt]   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a(intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*)
[mono-rt]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00073] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[mono-rt]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[mono-rt]   at Android.App.Activity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00031] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono-rt]   at MvvmCross.Platform.Droid.Views.MvxEventSourceActivity.OnCreate (Android.OS.Bundle bundle) [0x0000d] in C:\projects\mvvmcross\MvvmCross\Platform\Droid\Views\MvxEventSourceActivity.cs:33 
[mono-rt]   at MvvmCross.Droid.Views.MvxActivity.OnCreate (Android.OS.Bundle bundle) [0x00000] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxActivity.cs:117 
[mono-rt]   at basicMvvmcross.MainView.OnCreate (Android.OS.Bundle bundle) [0x0000e] in /Users/jonah/Desktop/basicMvvmcross/basicMvvmcross/MainView.cs:15 
[mono-rt]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono-rt]   at (wrapper dynamic-method) System.Object.2b58cb98-e03b-4736-8b9f-9fac58a61be4(intptr,intptr,intptr)
[mono-rt] --- End of stack trace from previous location where exception was thrown ---
[mono-rt]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono-rt]   at Java.Interop.JniEnvironment+Strings.NewString (System.Char* unicodeChars, System.Int32 length) [0x0001e] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[mono-rt]   at Java.Interop.JniEnvironment+Strings.NewString (System.String value) [0x00024] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[mono-rt]   at Android.Runtime.JNIEnv.NewString (System.String text) [0x00009] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono-rt]   at Java.Lang.Error..ctor (System.String message) [0x0001f] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono-rt]   at Android.Runtime.JavaProxyThrowable..ctor (System.Exception innerException) [0x00007] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono-rt]   at Java.Lang.Throwable.FromException (System.Exception e) [0x0001d] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono-rt]   at Android.Runtime.AndroidEnvironment.UnhandledException (System.Exception e) [0x00067] in <9e3ea4062ff24a9eb92486d44f624346>:0 
[mono-rt]   at (wrapper dynamic-method) System.Object.2b58cb98-e03b-4736-8b9f-9fac58a61be4(intptr,intptr,intptr)

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Do you see the same behaviour with the playground droid sample? And can you take a look at the Develop branch and see if the same thing occurs with v6?

**Comment by Macjon** [comment]
After some searching and trail and error I found something. When my minimum android target is set to api level 21 and target android is set to level 27 the app crashes. If I set the minimum level to 15 everything works fine. So the solution is to set your minimum android version to level 15 I think.

**Comment by nickrandolph** [comment]
@Macjon are you able to reproduce this using the playground android sample?
What OS version are you running on the Huawei Mate 10 - I'm asking so that I can create an emulator image that has similar specs so that I can see if I can replicate the issue.

**Comment by Macjon** [comment]
The solution was to set a fixed build target. So I think it's an visual studio for mac bug. Previously I've it was set automatically to oreo. Now I've manually set the build target to oreo and it's working again. So it's a weird error. So I think you can close this issue because it's not related to MvvmCross

**Comment by nickrandolph** [comment]
@Macjon thanks for getting back to us. I'll close this issue
