### ISSUE TITLE
App didn't show the right view after add SplashScreen on WPF

### ISSUE THREAD

**Issue by Happin3ss** [MvvmCross/MvvmCross#2684]
### Steps to reproduce :scroll:
 We can reproduce this issue using the Playground WPF project
1. Add a splash screen to Playground WPF project

2. Build project and start the app. 
   ****IMPORTANT** : DON'T click anything on the screen after you start the app. Otherwise the issue won't happen.

### Expected behavior :thinking:
RootView will show (As it was registered to start first in the Core)
### Actual behavior :bug:
A Blank Window appeared (I believe it's MainWindow). But if you switch to other tab/window (by clicking outside the app and then click on the App again) it will show the right RootView
### Configuration :wrench:

**Version:** 6.0 beta 5

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR to add this to the playground so we can test it?

**Comment by Happin3ss** [comment]
I did it here : https://github.com/MvvmCross/MvvmCross/pull/2716
Thank you !

**Comment by jz5** [comment]
Not fired [MvxApplication.OnActivated](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Wpf/Views/MvxApplication.cs#L19) when using SplashScreen. So not initialized.

How about this? Change playground.
https://github.com/jz5/MvvmCross/commit/b43947f2249da46e188400d70e506f945a7c8ca0

**Comment by nickrandolph** [comment]
@jz5 please check out https://github.com/MvvmCross/MvvmCross/pull/2713 and let me know whether you feel this is a more generic approach to handling this issue
