### ISSUE TITLE
RegisterAttribute doesn't always match the new MvvmCross 6 namespace

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2688]
The `RegisterAttribute` doesn't always match the new MvvmCross 6 namespace.

### Steps to reproduce :scroll:
N/A

### Expected behavior :thinking:
The `RegisterAttribute` should have the correct namespace, or use `[Register(nameof(X))]` if possible to avoid further issues like this.

### Actual behavior :bug:
The `RegisterAttribute` still has the old MvvmCross 5.x namespace in some cases. See [MvxSpinner](https://github.com/MvvmCross/MvvmCross/blob/bd3a438f8acff76657a743da0669d97254b7aaa6/MvvmCross/Platform/Android/Binding/Views/MvxSpinner.cs#L16) for example. The problem also applies to [MvxExpandableListView](https://github.com/MvvmCross/MvvmCross/blob/bd3a438f8acff76657a743da0669d97254b7aaa6/MvvmCross/Platform/Android/Binding/Views/MvxExpandableListView.cs#L16).

### Configuration :wrench:

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Thanks for reporting this! Just being curious, does it make Android apps crash?

**Comment by Cheesebaron** [comment]
@nmilcoff it will if proguard is enabled
