### ISSUE TITLE
MvxViewPagerAdapter and MvxStateViewPagerAdapter ignore the presence of view model instance inside MvxViewPagerFragmentInfo

### ISSUE THREAD

**Issue by wh1t3cAt1k** [MvvmCross/MvvmCross#2718]
### Steps to reproduce :scroll:

1. Use tab layout with a view pager.

2. Use e.g. `MvxViewPagerAdapter` for the view pager. Initialize it with a single-element collection `MvxViewPagerFragmentInfo` object that contains a **view model INSTANCE** which cannot be directly resolved from the IoC container (e.g. it is manually created with parameters from the parent page view model)

3. Try to open that page

4. 💥 

### Expected behavior :thinking:

Both `MvxViewPagerAdapter` and `MvxStateViewPagerAdapter` should check whether the fragment info already contains the view model instance, and if yes, do not try to `Mvx.Resolve` that.

### Actual behavior :bug:

Crash with a dependency resolution exception.

### Configuration :wrench:

**Version:** 5.7.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
This needs to be considered in #2440

**Comment by wh1t3cAt1k** [comment]
I would like to contribute under this issue separately, because I don't yet feel the strength to completely clean-up these adapters in the scop of #2440 . I am currently preparing a PR.
