### ISSUE TITLE
Android app hangs on SplashScreen

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2721]
### Steps to reproduce :scroll:

1. Launch PlayGround.Droid.

2. Press the Back button after the splash screen is done and the `RootViewModel` is active.

3. Click the Playground launcher icon again.

4. Splash screen is shown again and never closed.

### Expected behavior :thinking:
The app should restart showing the `RootViewModel` again after the splash screen finishes.

### Actual behavior :bug:
The app remains in a state where it's doing nothing and the splash screen remains visible forever. Force-quitting the application seems to be the only way to make it work again. This happens with both `MvxSplashScreenActivity` and `MvxSplashScreenAppCompatActivity`.

### Configuration :wrench:

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by tbalcom** [comment]
It looks like some [new code](https://github.com/MvvmCross/MvvmCross/commit/5506d6bf301b8a92321247e90c3812c69b641d2a#diff-bcad03b547b9c650846bd78867b56f48) sets `IMvxAppStart.IsStarted` to `true`. The problem is the value is never cleared when all activities are closed, so the main launcher (splash screen) is shown again then it skips `IMvxAppStart.Start` after the splash screen is done loading.

**Comment by nickrandolph** [comment]
@tbalcom can you review https://github.com/MvvmCross/MvvmCross/pull/2713 and confirm this addresses this issue for Android

**Comment by tbalcom** [comment]
@nickrandolph Yes, the issue is fixed now.

**Comment by stefan89** [comment]
I am encountering the exact same issue for version 5.6.3. Can that be caused by the same bug or was this bug introduced in version 6.0?

**Comment by nickrandolph** [comment]
unfortunately too hard to say as the bug was reported against v6 - if you can upgrade to 6.0.1 to see if it fixes the issue

**Comment by tbalcom** [comment]
This was specific to early MvvmCross 6.0 betas. There were a lot of changes made to startup during that time.
