### ISSUE TITLE
Application restarts after Sleep -> Resume

### ISSUE THREAD

**Issue by rudacs** [MvvmCross/MvvmCross#2723]
### Steps to reproduce :scroll:

1. Create Project Xamarin.Forms;
2. And I added two screens to navigate;
3. Enter the application;
4. Navigate to another page;
5. Send the app to background;
6. Then click on the application to go to the foreground.

### Expected behavior :thinking:
Continue the app from where you paused.

### Actual behavior :bug:
The application returns to the first page (root).
When debugging the SplashScreen is created again when I return to foreground (every time)

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Two questions:
- how are you sending the app to background - pressing home or back button?
- are you able to reproduce this with either 6beta or in the playground sample?

**Comment by nickrandolph** [comment]
@rudacs can you check out https://github.com/MvvmCross/MvvmCross/pull/2713 and see whether this addresses this issue too.

**Comment by martijn00** [comment]
I've tested this in the latest playground and it works there. Please reopen with a reproduction sample if this still happens.

**Comment by nmilcoff** [comment]
If you were bringing the app to foreground by tapping on the launcher icon - then that's the standard behavior and there's no MvvmCross bug involved. You need to modify your Activity flags to effectively manage that.
