### ISSUE TITLE
Soft back button doesn't work in Playground.Android

### ISSUE THREAD

**Issue by closetoyou293** [MvvmCross/MvvmCross#2736]
### Steps to reproduce :scroll:

1.Select Playground.Android as startup project. Change: 
`RegisterAppStart<RootView>();`
to
`RegisterAppStart<SplitRootViewModel>();`
2.Run project:
Click on button on SplitDetailView to navigate to SplitDetailNavView
=> There is no back button.
3. Modify OnCreateView function in SplitDetailNavView

```csharp
public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
{
    base.OnCreateView(inflater, container, savedInstanceState);

    var view = this.BindingInflate(Resource.Layout.SplitDetailView, null);
    _toolbar = view.FindViewById<Toolbar>(Resource.Id.toolbar);
    if (_toolbar != null) {
        BaseActivity.SetSupportActionBar(_toolbar);
        BaseActivity.SupportActionBar.SetDisplayHomeAsUpEnabled(true);
    }
    return view;
}
```

### Expected behavior :thinking:
Soft back button should work

### Actual behavior :bug:
Nothing happens when clicks on soft back button.

### Configuration :wrench:

**Version:** 5.7

**Platform:** 
- [] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@closetoyou293 are you able to confirm that this is still a bug in v6 (current develop branch)?

**Comment by closetoyou293** [comment]
@nickrandolph i've just checked and still happens

**Comment by martijn00** [comment]
I'm looking into this. From what i saw so far this is more of a sample problem than a bug in MvvmCross. Will see if i can fix it soon.
