### ISSUE TITLE
IMvxNavigationService.OnAfterClose may trigger before presentation is changed

### ISSUE THREAD

**Issue by wh1t3cAt1k** [MvvmCross/MvvmCross#2740]
In Android, I have two-thread application architecture.

1. I call `IMvxNavigationService.Close()` from the background thread. 
1. Inside `Close()`, the view dispatcher requests a main thread action from `ViewDispatcher`.

### Expected behavior :thinking:

I expect the `OnAfterClose` event to be triggered after the main thread action has returned.

### Actual behavior :bug:

Immediately `OnAfterClose()` is triggered even though the main thread action may not have even started yet.

It's OK and desirable that `OnBeforeClose` / `OnAfterClose` events are called from the same thread that called `Close()` - this should not change I believe. 

The problem is that we don't wait until the view dispatcher actually changes the presentation. 

Maybe the view dispatcher should also become asynchronous?

### Configuration :wrench:

**Version:** 5.7.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Are you able to either provide a sample app or submit a PR showing how to replicate this using the playground samples?

**Comment by wh1t3cAt1k** [comment]
I will try to find time for a test app (NDA forbids me from posting real code), but in the meanwhile the below samples are enough to demonstrate the pitfall:

From `MvxNavigationService`:

```
        public virtual Task<bool> Close(IMvxViewModel viewModel)
        {
            var args = new NavigateEventArgs(viewModel);
            OnBeforeClose(this, args);
            var close = ViewDispatcher.ChangePresentation(new MvxClosePresentationHint(viewModel));
            OnAfterClose(this, args);

            return Task.FromResult(close);
        }
```

Note that this is called from the background thread.

From `MvxAndroidMainThreadDispatcher`:

```
        public bool RequestMainThreadAction(Action action, bool maskExceptions = true)
        {
            if (Application.SynchronizationContext == SynchronizationContext.Current)
                action();
            else
            {
                Application.SynchronizationContext.Post(ignored => 
                {
                    if (maskExceptions)
                        ExceptionMaskedAction(action);
                    else
                        action();
                }, null);
            }

            return true;
        }
```

It is evident that `OnAfterClose` will be triggered immediately after posting the main thread action, but the action will be executed only some time later in the Android main thread loop.

**Comment by nickrandolph** [comment]
Thanks for the update. There should be enough for us to reproduce the issue. 
I think the suggestion to make the dispatcher async aware or at least have an async option would be good. We’re gradually weeding out areas of mvx where there has been a previous assumption that things will run synchronously

**Comment by nickrandolph** [comment]
@wh1t3cAt1k can you check this against 6.2. Most of the navigation service is now async aware so this should have resolved this issue
