### ISSUE TITLE
NuGet package descriptions are missing from csproj files

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#2742]
Each package should have a `<Description>` tag in the first `<PropertyGroup>` describing the contents of the package.

### Steps to reproduce :scroll:

1. Find a MvvmCross 6.0.0-beta.x package on NuGet.org

2. Look at description

### Expected behavior :thinking:
There should be a description of the package

### Actual behavior :bug:
No description

### Configuration :wrench:

**Version:** 6.0.0-beta.x

**Comment by orzech85** [comment]
I will take it ;)

**Comment by Cheesebaron** [comment]
@orzech85 make sure to do this on the develop branch :)

You can take a look at what we had before in the old nuspec files in the master branch.
