### ISSUE TITLE
WPF Presenter documentation is out of date

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#2743]
### Steps to reproduce :scroll:

1.  Look at the docs.

2.  Try to implement your own presenter.

3.  Notice that it fails.

### Expected behavior :thinking:
Docs should match the code.

```csharp
public class MyCustomViewPresenter
        : MvxWpfViewPresenter
{
    protected virtual void RegisterAttributeTypes()
    {
        //  The following is not valid:
        _attributeTypesToShowMethodDictionary.Add(
            typeof(MyCustomModePresentationAttribute),
            (element, attribute, request) =>
                ShowMyCustomModeView(element, (MyCustomPresentationAttribute)attribute, request));
    }
}
```

There is also no mention of the differences between `MvxSimpleWpfPresenter` and `MvxWpfViewPresenter`

### Actual behavior :bug:
They don't.

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [X] :checkered_flag: WPF

**Comment by nmilcoff** [comment]
`MvxSimpleWpfPresenter` is obsolete and was deleted for v6.

**Comment by hosaka** [comment]
Trying to make a composite wpf application. Very hard to figure out how to configure my own presenter, official docs are out of date, everything else on SO/GitHub uses some other approach that I can't make sense of.
