### ISSUE TITLE
[iOS] Using VS AppCenter "AppCenter.Start" while MvxApplication.Initialize results in deadlock since MVX 6 beta7

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2745]
### Steps to reproduce :scroll:

1. Using VS AppCenter

2. Start the AppCenter within the MvxApplication.Initialize overwrite

### Expected behavior :thinking:
No deadlock like it was with MVX 6.0.0 beta6 and before.

### Actual behavior :bug:
Deadlock without any result (App stays on Splash Screen, there is no exception when debugging as soon as you step over AppCenter.Start nothing happens anymore). Is the MvxApplication.Initialize now in a different thread maybe? 

**Note**: This can be avoided by putting the VS AppCenter code somewhere else but maybe this is affecting other stuff too. 

### Configuration :wrench:

**Version:** 6.0.0.beta7

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by borbmizzet** [comment]
This is a major concern for those of us who use VS App Center for diagnostics.  I was planning on migrating our Vanilla Xamarin.Forms code to MvvmCross v6 as soon as it was released but this regression is a major roadblock.

**Comment by nmilcoff** [comment]
Also initializing AppCenter in the App class is probably too late (and dangerous) if you're using their crash logging feature.

**Comment by Sebastian1989101** [comment]
@Cheesebaron The Xamarin.Forms OnStart() methods seems to be too late when using MVX. The push notifications wont work there. The `MvxApplication.Initialize()` is earlier but it is no longer possible to init VS AppCenter there (app freeze at launch since beta7, works with beta6 and earlier). 

I'm using the `AppDelegateFinishedLaunching()` and the `MvxSplashScreenActivity.RunAppStart()` since beta7 and it seems to work (I just have a few problems with push but I guess this comes from somewhere else). 

I just wanted to mention that some things might result in a freeze since beta7 with the report and not that VS AppCenter does this because you can move the code to another location very easily.

**Comment by fedemkr** [comment]
I know this is closed (and originally was about iOS) but nonetheless I wanted to point out that if you start **AppCenter** on the `SplashScreen`, then it won't work after Android _tombstoning_. I'd recommend to start **AppCenter** (particularly **Crashes**) service on `Application > OnCreate()` as stated in the [official docs](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin#421-xamarinandroid) as a note. 
Doing this you're sure that the initialization takes place early on and the service it's initialized no matter what.
