### ISSUE TITLE
Xamarin Forms Images is not shown on Android when using mvvmcross

### ISSUE THREAD

**Issue by F0rc0sigan** [MvvmCross/MvvmCross#2770]
Here is link to reproduce issue https://github.com/F0rc0sigan/MvvmCrossImageNotLoadingTestApp
 

### Steps to reproduce :scroll:

1. Setup Xamarin.Forms project with mvvmcross

2. Add image on page 
<Image Source="xamarin_logo.png" VerticalOptions="Center" HeightRequest="64" />

3. Image is not shown, though without mvvmcross it is shown as expected

### Expected behavior :thinking:
It should load image and show it on page

### Actual behavior :bug:
It does not show image. In output it write
"FileImageSourceHandler: Could not find image or image file was invalid: File: xamarin_logo.png"  Screenshot of problem: http://take.ms/YJ7aF
If i remove mvvmcross from project, then image is shown as expected

Related to this issue on StackOverflow https://stackoverflow.com/questions/48944590/xamarin-forms-not-displaying-images-in-mvvmcross-mvxcontentpage?noredirect=1#comment86318999_48944590

### Configuration :wrench:
Debug

**Version:** 6.0.0-beta.7

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you PR this sample to the playground?

**Comment by F0rc0sigan** [comment]
@martijn00 Thanks for your quick response. I dont get what you mean. Implement sample in playground or just add my sample to playground folder as separate solution and create pull request?

**Comment by AleOp** [comment]
I had the same problem. The core cause of it is that MvvmCoss Setup's `FormsApplication` property initializes Xamarin.Forms with the wrong assembly for resources. Thus, Xamarin.Form'es `ResourceManager` will resolve `Drawable` and `Resource` class instances from Android.* namespace, not from yours. Hence, Xamarin.Forms will be trying to resolve images not from YourProject.Resources but from Android.Resources. 
However, there is a fast fix for this if you want. In your `MainActivity`, before `base.OnCreate()` call, just initialize `ResourceManager` again like this `ResourceManager.Init(GetType().Assembly)`;

**Comment by orlolro** [comment]
@nickrandolph At develop branch, playground project's RootPage.xaml contains image with MvvmCross logo which is not loaded. I suppose, it already shows the issue

**Comment by nickrandolph** [comment]
Awesome. Thanks will investigate
