### ISSUE TITLE
MvvmCross doesn't work with F# Android app resources

### ISSUE THREAD

**Issue by nosami** [MvvmCross/MvvmCross#2772]
### Steps to reproduce :scroll:

1. Clone this repo [Fsharp Droid project with MvvmCross](https://github.com/willsam100/MvvmFsharpDroid)

2. Build

3. Run

### Expected behavior :thinking:

The application should launch

### Actual behavior :bug:
Tell us what happens instead

```
[mono] MvvmCross.Platform.Exceptions.MvxException: Unable to find resource type - MvvmFormsAppFsharp.Droid.Resource. Please check if your setup class is in your application's root namespace. [mono] at MvvmCross.Binding.Droid.ResourceHelpers.MvxAppResourceTypeFinder.Find () [0x0002a] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAppResourceTypeFinder.cs:23 [mono] at MvvmCross.Binding.Droid.ResourceHelpers.MvxAndroidBindingResource..ctor () [0x0000b] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAndroidBindingResource.cs:31 [mono] at MvvmCross.Binding.Droid.ResourceHelpers.MvxAndroidBindingResource.Initialize () [0x00008] in 
```

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nosami** [comment]
See discussion [here](https://github.com/xamarin/xamarin-android/issues/1513#issuecomment-379444413)

**Comment by nosami** [comment]
I was going to attempt to fix this, but I can't get this solution to build on OSX. To find the resource type for an assembly, you need to do the following.

https://github.com/xamarin/xamarin-android/blob/f071dd61252abe35b63c724467caafd9314c804c/src/Mono.Android/Android.Runtime/ResourceIdManager.cs#L33-L43

**Comment by martijn00** [comment]
@nosami VS4Mac is broken, you need to use the command line to build on Mac. It would be better to do this on Windows where everything works.

**Comment by nosami** [comment]
How do you build on command line? I tried that but the cake script doesn't work (complains about missing netstandard reference)

I got it to partially build by running `dotnet restore` followed by msbuild.

**Comment by martijn00** [comment]
Try this:
`msbuild MvvmCross.sln /t:restore`
`msbuild MvvmCross.sln /p:Configuration=Release`
