### ISSUE TITLE
MvxTabbedPage show double tabbedbar on screen bottom

### ISSUE THREAD

**Issue by xyz20533** [MvvmCross/MvvmCross#2776]
1. I use xaml define MvxTabbedPage in my project but run this project on simulator that has douuble tabbedbar on screen bottom.
2. I use MvxTabbedPage and define title for current page but title occur in tabbedbar.

https://1249808869.visualstudio.com/_git/Zero
 

### Steps to reproduce :scroll:

1.

2.

3.

### Expected behavior :thinking:
Tell us what should happen
I want only occur one tabbedbar on screen bottom 
### Actual behavior :bug:
Tell us what happens instead

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [* ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
We are not authorized to access your vs.com repo. Please put it somewhere public.

**Comment by xyz20533** [comment]
@Cheesebaron https://github.com/xyz20533/MvxTabbedPage

**Comment by martijn00** [comment]
Can you make a PR to change the playground to show this?

**Comment by martijn00** [comment]
@xyz20533 you need to make a new branch on your fork. Make sure to rebase that, and then commit the fix and make the PR.

**Comment by xyz20533** [comment]
@martijn00 I just try PR to https://github.com/MvvmCross/MvvmCross,but occur error code of 403 ,how solve this question thank

**Comment by xyz20533** [comment]
@martijn00 https://github.com/xyz20533/MvvmCross/tree/MvxTabbedPage/MvxTabbedPage

**Comment by xyz20533** [comment]
https://github.com/MvvmCross/MvvmCross/pull/2818  It is OK? @nickrandolph

**Comment by nickrandolph** [comment]
@xyz20533 can reach out to us on Slack and lets see if we can get this fixed
