### ISSUE TITLE
Playground.Droid creates multiple instances of RootViewModel

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2782]
### Steps to reproduce :scroll:

1. Start Playground.Droid
2. Click the "SHOW MASTER/DETAIL" button.
3. A second instance of RootViewModel is displayed. You can see the Master/Detail views after closing the duplicate RootViewModel instance. The bug doesn't repeat itself again until you restart the application.

### Expected behavior :thinking:
RootViewModel should not be displayed a second time when "SHOW MASTER/DETAIL" is clicked.

### Actual behavior :bug:
A second instance of RootViewModel is displayed during the navigation to the Master/Detail ViewModels.

### Configuration :wrench:

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by tbalcom** [comment]
Here is another scenario I've found that also triggers this problem:

1. Click "SHOW MODAL" button.
2. Rotate the screen.
3. A new instance of `RootViewModel` is displayed. FYI, clicking "SHOW MODAL" on the new instance crashes the application.
>  Unhandled Exception:
 System.NullReferenceException: Object reference not set to an instance of an object.
   at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.ShowDialogFragment (System.Type view, MvvmCross.Platforms.Android.Presenters.Attributes.MvxDialogFragmentPresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request) [0x0008a] in E:\src\MvvmCross\MvvmCross.Android.Support\V7.AppCompat\MvxAppCompatViewPresenter.cs:343 
   at MvvmCross.Platforms.Android.Presenters.MvxAndroidViewPresenter.<RegisterAttributeTypes>b__21_4 (System.Type view, MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request) [0x00000] in E:\src\MvvmCross\MvvmCross\Platforms\Android\Presenters\MvxAndroidViewPresenter.cs:125 
   at MvvmCross.Platforms.Android.Presenters.MvxAndroidViewPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request) [0x00001] in E:\src\MvvmCross\MvvmCross\Platforms\Android\Presenters\MvxAndroidViewPresenter.cs:216 
   at MvvmCross.Platforms.Android.Views.MvxAndroidViewDispatcher+<>c__DisplayClass2_0.<ShowViewModel>b__0 () [0x00000] in E:\src\MvvmCross\MvvmCross\Platforms\Android\Views\MvxAndroidViewDispatcher.cs:25 
   at MvvmCross.Base.MvxMainThreadAsyncDispatcher+<>c__DisplayClass0_0.<ExecuteOnMainThreadAsync>b__0 () [0x00001] in E:\src\MvvmCross\MvvmCross\Base\MvxMainThreadAsyncDispatcher.cs:16 
   at MvvmCross.Base.MvxMainThreadAsyncDispatcher+<>c__DisplayClass1_0+<<ExecuteOnMainThreadAsync>b__0>d.MoveNext () [0x0000f] in E:\src\MvvmCross\MvvmCross\Base\MvxMainThreadAsyncDispatcher.cs:27 
 --- End of stack trace from previous location where exception was thrown ---
   at (wrapper dynamic-method) System.Object.9dc36169-1b84-4851-baaf-eecdbd1b85bf(intptr,intptr)


4. Press the hardware back key to close the bogus `RootViewModel` instance.
5. Clicking "SHOW MODAL" button repeats from step 1.

**Comment by tbalcom** [comment]
Are these problems related to #2775 ?

**Comment by angelru** [comment]
@tbalcom the same issue: 
```
018-04-11 04:00:17 [TRACE] (MvxAndroid) Cannot use Android Support Fragment within non AppCompat Activity04-11 16:00:17.495 I/mono-stdout( 5351): 2018-04-11 04:00:17 [TRACE] (MvxAndroid) Cannot use Android Support Fragment within non AppCompat Activity

04-11 16:00:17.495 D/Mono    ( 5351): Assembly Ref addref MvvmCross.Droid.Support.V7.AppCompat[0xe413e740] -> MvvmCross.Droid.Support.Fragment[0xe413e4a0]: 2
04-11 16:00:17.526 W/zygote  ( 5351): JNI RegisterNativeMethods: attempt to register 0 native methods for md5fe5d3cea52656fbb0bd17785191afc95.MvxBottomSheetDialogFragment_1
04-11 16:00:17.534 D/Mono    ( 5351): Assembly Ref addref MvvmCross.Droid.Support.Design[0xe413e260] -> MvvmCross.Droid.Support.Fragment[0xe413e4a0]: 3
Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.

04-11 16:00:19.704 D/Mono    ( 5351): DllImport attempting to load: '/system/lib/liblog.so'.
04-11 16:00:19.704 D/Mono    ( 5351): DllImport loaded library '/system/lib/liblog.so'.
04-11 16:00:19.704 D/Mono    ( 5351): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
04-11 16:00:19.704 D/Mono    ( 5351): Searching for '__android_log_print'.
04-11 16:00:19.704 D/Mono    ( 5351): Probing '__android_log_print'.
04-11 16:00:19.704 D/Mono    ( 5351): Found as '__android_log_print'.
04-11 16:00:19.708 I/MonoDroid( 5351): UNHANDLED EXCEPTION:
04-11 16:00:19.724 I/MonoDroid( 5351): System.NullReferenceException: Object reference not set to an instance of an object.
04-11 16:00:19.724 I/MonoDroid( 5351):   at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.PerformShowFragmentTransaction (Android.Support.V4.App.FragmentManager fragmentManager, MvvmCross.Platforms.Android.Presenters.Attributes.MvxFragmentPresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request) [0x000a4] in <761c6dcc390c4664a8c7435b6eac65ca>:0 
04-11 16:00:19.724 I/MonoDroid( 5351):   at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.ShowFragment (System.Type view, MvvmCross.Platforms.Android.Presenters.Attributes.MvxFragmentPresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request) [0x000a2] in <761c6dcc390c4664a8c7435b6eac65ca>:0 
04-11 16:00:19.724 I/MonoDroid( 5351):   at MvvmCross.Platforms.Android.Presenters.MvxAndroidViewPresenter.<RegisterAttributeTypes>b__21_2 (System.Type view, MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request) [0x00000] in <03121ecd478c47d98660eca6e2fec5d6>:0 
04-11 16:00:19.724 I/MonoDroid( 5351):   at MvvmCross.Platforms.Android.Presenters.MvxAndroidViewPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request) [0x00014] in <03121ecd478c47d98660eca6e2fec5d6>:0 
04-11 16:00:19.724 I/MonoDroid( 5351):   at MvvmCross.Platforms.Android.Views.MvxAndroidViewDispatcher+<>c__DisplayClass2_0.<ShowViewModel>b__0 () [0x00000] in <03121ecd478c47d98660eca6e2fec5d6>:0 
04-11 16:00:19.724 I/MonoDroid( 5351):   at MvvmCross.Base.MvxMainThreadAsyncDispatcher+<>c__DisplayClass0_0.<ExecuteOnMainThreadAsync>b__0 () [0x00000] in <03121ecd478c47d98660eca6e2fec5d6>:0 
An unhandled exception occured.
```

**Comment by tbalcom** [comment]
I tried out Playground with the recent changes. These issues are now fixed. Thanks!
