### ISSUE TITLE
Error installing PictureChooser

### ISSUE THREAD

**Issue by RonakPatel21** [MvvmCross/MvvmCross#2785]
It throws "Could not install package 'MvvmCross.Plugin.PictureChooser 5.6.3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author"

**Comment by nickrandolph** [comment]
What project type are you trying to add the nuget package too?

**Comment by RonakPatel21** [comment]
Portable class library project(in which my all ViewModels are)

**Comment by nickrandolph** [comment]
And what profile do you currently have selected for your PCL - if not Profile259, can you change to that profile (as per the error)?

**Comment by RonakPatel21** [comment]
It's **Profile259**

**Comment by nickrandolph** [comment]
can you try adjusting it to profile 111 and see whether that works for you?

**Comment by nickrandolph** [comment]
unfortunately pcls are just a pain to work with - I'd suggest migrating to .net standard as quickly as you can (even using 5.6.3 of Mvx)

**Comment by RonakPatel21** [comment]
I can't... project don't allowing me to change profile. It auto change it to 259

**Comment by Cheesebaron** [comment]
Sorry, we don't support PCL profiles with Windows Phone 8 in them.

I suggest that you migrate your project to .NET Standard at least profile 1.1, but probably just go with 2.0 since, that is what the future version of MvvmCross is running.
