### ISSUE TITLE
How to properly embed Xamarin.Forms views in Xamarin.Native MvvmCross?

### ISSUE THREAD

**Issue by orestesgaolin** [MvvmCross/MvvmCross#2786]
Please forgive me that I don't adapt a default issue template, but I have a question rather than an issue. I'm still learning Xamarin and MvvmCross and I would love to embed some Forms views in my Native MvvmCross powered app.

I found it rather difficult to achieve such outcome even with some examples [like this one](https://github.com/munkii/MvvmCross/tree/develop/TestProjects/Forms/NativeToXF) or default [Xamarin walkthrough](https://montemagno.com/why-xamarinforms-embedding-matters/) or [examples](https://github.com/jamesmontemagno/app-imagesearch-cogs/).

Specifically, I would like to know whether it is possible to embed Forms views while using MvvmCross 5.7.0 or should I wait for 6.0.0 release? I'd be more than grateful for some working example solutions or list of steps required to implement it based on e.g. default MvvmCross template.

**Version:** 5.7.0 or 6.0.0

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Please use [Slack #mvvmcross](https://xamarinchat.herokuapp.com/) or [StackOverflow](https://stackoverflow.com/questions/tagged/mvvmcross) for questions. Github is meant to be used for bugs and feature requests only.

**Comment by orestesgaolin** [comment]
@Cheesebaron Ok, thanks for guidance! Have a great day!

**Comment by diaconori** [comment]
Did you find a solution to this problem? There have not been a stable demonstration of this concept since 2015 where Michael Ridland released his... That was with MVVMCross version 3 and Xamarin Forms version 1... Lol

**Comment by mjrichards91** [comment]
I am also interested if you found a solution to this @orestesgaolin.

**Comment by orestesgaolin** [comment]
I asked [here](https://stackoverflow.com/questions/49970668/embedding-xamarin-forms-in-native-xamarin-app-with-mvvmcross-6-0) but couldn't find a solution for this :/ I abandoned this idea as the performance impact of XF on MvvmCross and complexity of this task would be too high.

**Comment by Cheesebaron** [comment]
There is always the possibility of using the `CreateViewController()` and `CreateSupportFragment` to embed a Forms page

**Comment by Hackmodford** [comment]
I think I have a working example in iOS and Android. It might be worth adding these to MvvmCross in some official capacity.

https://github.com/dornerworks/Mvx.Forms.PageWrapper.iOS
https://github.com/dornerworks/Mvx.Forms.PageWrapper.Android

There's just one problem I'm having with Android. If I present a fragment and set the second one to add to the back stack (so you can navigate back to the first fragment), the app crashes when you press the back button.

@Cheesebaron Would you be able to look at the `develop` branch of my Android example and see if I'm missing something obvious?

You will need to modify the `Page2Fragment` to get the error.

```C#
[MvxFragmentPresentation(
        ActivityHostViewModelType = typeof(AndroidFragmentHostViewModel),
        FragmentContentId = Resource.Id.fragment_container, 
        AddToBackStack = true)]
public class Page2Fragment : MvxFormsFragment<Page2, Page2FragmentViewModel>
{
}
```

**Comment by Hackmodford** [comment]
Holy crap! I got it working on Android. 

@Cheesebaron This should probably be a new feature request at this point? 

I have working source code that allows you to embed a Xamarin.Forms ContentPage into native `ViewController`/`Activity`/`Fragment` and use the native ViewPresenters :) The result being that you can freely mix Xamarin.Forms and Xamarin.Native views in a MvvmCross project. I had to create a custom `MvxEmbeddedContentPage` to avoid sending duplicate messages to the ViewModel but it looks like Binding works as expected in either the `MvxContentPage` or the native `ViewController`/`Activity`/`Fragment`.

_I will need to update the iOS example to use the MvxContentPage (which will probably mean a new nuget)_
