### ISSUE TITLE
Implement a way to use Mvx Navigation for custom XAML-based modal popup views

### ISSUE THREAD

**Issue by borbmizzet** [MvvmCross/MvvmCross#2794]
It would be really nice to have a built in ViewModel-first replacement for [Rg.Plugins.Popup](https://github.com/rotorgames/Rg.Plugins.Popup) that uses MvvmCross navigation and IoC that would allow XAML-based modals to not take up the whole screen.

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by ueman** [comment]
This would also be a very nice addition for UWP apps. It should be very simple to implement it on UWP with the help of native Popups.

**Comment by martijn00** [comment]
I think this should not be part of MvvmCross itself, but rather be a plugin on top of it.
