### ISSUE TITLE
WPF Support Missing From MvvmCross 6.0.0

### ISSUE THREAD

**Issue by andrewtechhelp** [MvvmCross/MvvmCross#2796]
### Steps to reproduce :scroll:

1. Open Playground Project For WPF (Playground.Wpf)

2. Create a constructor for the App class and add the following code this.RegisterSetupType<MvxWpfSetup<Core.App>>(); (I believe this needs to be added to the Playground sample in general, I may add a pull request with this at some point)

3. Try to build and run the application

### Expected behavior :thinking:
The Application runs as expected

### Actual behavior :bug:

Many errors are thrown, main one being: 
Error	 CS0234:	The type or namespace name 'Wpf' does not exist in the namespace 'MvvmCross.Platforms' (are you missing an assembly reference?)

### Additional Information

This happens with the Playground project (which I know by default references the MvvmCross project in that solution. However, if I remove the reference to MvvmCross from the WPF project and manually add the MvvmCross.dll from 6.0.0 Beta 7 (from C:\Users\username\.nuget\packages\mvvmcross\6.0.0-beta.7\lib\net461), everything works again. Adding the MvvmCross.dll from 6.0.0 (C:\Users\username\.nuget\packages\mvvmcross\6.0.0\lib\net461) breaks again.

I noticed by watching GitHub that just before MvvmCross 6.0.0 was released that WPF was separated into its own project, which means its own DLL. This MvvmCross.Platforms.Wpf.dll file isn't in C:\Users\username\.nuget\packages\mvvmcross\6.0.0\lib\net461 and I can't find a separate NuGet package to install, so I'm not sure if it just got forgotten or if there's a new way to use it now.

### Configuration :wrench:

**Version:** 6.0.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
There should be a WPF nuget package. Using that should make this work.

**Comment by andrewtechhelp** [comment]
What is this NuGet package called? I did search for one with MvvmCross & WPF in the name, but I couldn't find it. 

At https://www.nuget.org/profiles/MvvmCross - There's no package with WPF in the name listed there either.

**Comment by Cheesebaron** [comment]
Thank you for opening this issue.

The csproj was missing from the build script, hence no NuGet package was produced during build. I'll fix this during today and release the missing package.

**Comment by andrewtechhelp** [comment]
Brilliant. Thanks :)

**Comment by andrewtechhelp** [comment]
Package installed and works as expected. Thanks :)
