### ISSUE TITLE
Attribute "MvxBind" has already been defined

### ISSUE THREAD

**Issue by haohighview** [MvvmCross/MvvmCross#2800]
### Steps to reproduce :scroll:

\obj\Debug_AIS_Test\lp\25\jl\res\values\mvxbindingattributes.xml(2): error APT0000: Attribute "MvxBind" has already been defined
\obj\Debug_AIS_Test\lp\25\jl\res\values\mvxbindingattributes.xml(2): error APT0000: Attribute "MvxLang" has already been defined
\obj\Debug_AIS_Test\lp\25\jl\res\values\mvxbindingattributes.xml(2): error APT0000: Attribute "MvxTemplate" has already been defined
\obj\Debug_AIS_Test\lp\25\jl\res\values\mvxbindingattributes.xml(2): error APT0000: Attribute "MvxItemTemplate" has already been defined
\obj\Debug_AIS_Test\lp\25\jl\res\values\mvxbindingattributes.xml(2): error APT0000: Attribute "MvxDropDownItemTemplate" has already been defined
\obj\Debug_AIS_Test\lp\25\jl\res\values\mvxbindingattributes.xml(2): error APT0000: Attribute "MvxGroupItemTemplate" has already been defined

\obj\Debug_AIS_Test\lp\90\jl\res\layout\com_facebook_device_auth_dialog_fragment.xml(20): error APT0000: No resource identifier found for attribute 'cardBackgroundColor' in package
\Debug_AIS_Test\lp\90\jl\res\layout\com_facebook_device_auth_dialog_fragment.xml(20): error APT0000: No resource identifier found for attribute 'cardElevation' in package
\obj\Debug_AIS_Test\lp\90\jl\res\layout\com_facebook_smart_device_dialog_fragment.xml(20): error APT0000: No resource identifier found for attribute 'cardBackgroundColor' in package 
\obj\Debug_AIS_Test\lp\90\jl\res\layout\com_facebook_smart_device_dialog_fragment.xml(20): error APT0000: No resource identifier found for attribute 'cardElevation' in package

### Configuration :wrench:

**Version:** 5.x
VS2017 15.6.6
Xamarin 4.9.0.753
MvvmCross 6.0.0

**Platform:** 
Android

**Comment by Cheesebaron** [comment]
You need to provide more information on how to reproduce this.

Usually these errors appear if you have your own local `MvxBindingAttributes` file, which was deprecated long ago since it is bundled with MvvmCross. In 5.x in the `MvvmCross.Bindings.Droid` assembly.

They can also appear if you are mixing versions of MvvmCross, so multiple of these assemblies are loaded.

From the information you have provided we have no chance to help you, since it lacks any context.

**Comment by haohighview** [comment]
but now MvvmCross.Binding can't update to 6.0.0, The latest version is 5.7.0.

**Comment by Cheesebaron** [comment]
Just remove it. It is not needed anymore in MvvmCross 6.0.0, it is described in the changelog.
