### ISSUE TITLE
MvxFormsIosSetup.CreateViewPresenter called too soon?

### ISSUE THREAD

**Issue by pdonovan** [MvvmCross/MvvmCross#2802]
### Steps to reproduce :scroll:

1. In the Playground.Forms.iOS project, add a Setup.cs containing an implementation of `MvxFormsIosSetup<Core.App, FormsApp>` that overrides `CreateViewPresenter()`, The override should use a custom IMvxFormsPagePresenter for its `FormsPagePresenter` that subclasses `MvxFormsPagePresenter`. See attached Setup.cs for full code.
[Setup.cs.txt](https://github.com/MvvmCross/MvvmCross/files/1918807/Setup.cs.txt)

2. Change AppDelegate to inherit ` MvxFormsApplicationDelegate<Setup, Core.App, FormsApp>`

3. Launch the application on iOS (10.3.3 tested)

### Expected behavior :thinking:
The custom IMvxIosViewPresenter should be used by the app. This worked in version 5.6.3.

### Actual behavior :bug:
MvxIoCResolveException("Failed to resolve type MvvmCross.Views.IMvxViewsContainer")
from MvxAttributeViewPresenter.ViewsContainer
from MvxFormsPagePresenter.ctor()

### Configuration :wrench:

**Version:** 6.0.0

**Platform:** 
- [X ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This is not how Forms is working. You need to use a native presenter like `MvxFormsIosViewPresenter` which contains the shared `MvxFormsPagePresenter` and override it there.

I think we could make it easier to override the `MvxFormsPagePresenter` by making that virtual in the setup.

**Comment by pdonovan** [comment]
Thanks. I have a workaround for now, doing it the way I think you mean. I'll change to the method in #2803 when that's available.
