### ISSUE TITLE
`[MvxContentPagePresentation(WrapInNavigationPage = true, NoHistory = true)] causes crash when NavigationPage.HasNavigationBar="True"

### ISSUE THREAD

**Issue by borbmizzet** [MvvmCross/MvvmCross#2812]
### Steps to reproduce :scroll:

I've noticed that having
`[MvxContentPagePresentation(WrapInNavigationPage = true, NoHistory = true)]`
and
```
<mvxviews:MvxContentPage
xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:mvxviews="clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms"
xmlns:viewModels="clr-namespace:Test.Core.ViewModels;assembly=Test.Core"
x:Class="Test.Core.Pages.LoginPage" x:TypeArguments="viewModels:LoginViewModel"
BackgroundImage="background.png"
NavigationPage.HasNavigationBar="True">
```
causes the program to crash in android with Mvx 6.0 if LoginViewModel is the starting ViewModel (not sure about when it isnt).
However, it seems to run fine with `NavigationPage.HasNavigationBar="False"`.

### Expected behavior :thinking:
Not crashing when NavigationPage.HasNavigationBar="True"

### Actual behavior :bug:
Crashing when NavigationPage.HasNavigationBar="True"

### Configuration :wrench:

**Version:** 6.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Hi @borbmizzet would you be able to reproduce this in the playground sample and submit as PR to demonstrate the issue - we'll look into fixing it on the PR. Thanks

**Comment by borbmizzet** [comment]
@nickrandolph  It works when I remove `<RootViewModel>` from `MainActivity<RootViewModel>`.   No more "No ViewModel for MainActivity" console log either.  I think this can be safely closed.

**Comment by nickrandolph** [comment]
Closing this issue as it is not reproducible in latest code. @borbmizzet reopen this issue if this requires further investigation.
