### ISSUE TITLE
MvxFormsAppCompatActivity.OnBackPressed override is broken.

### ISSUE THREAD

**Issue by borbmizzet** [MvvmCross/MvvmCross#2817]
### Steps to reproduce :scroll:
In  MvxFormsAppCompatActivity and MvxFormsApplicationActivity, the OnBackPressed function should not be overridden and should be up to the app developer to override, due to the following problems in the current implementation
```
        public override void OnBackPressed()
        {
            var page = Xamarin.Forms.Application.Current.MainPage;
            if (page == null || (page?.Navigation?.NavigationStack?.Count <= 1 && page?.Navigation?.ModalStack?.Count == 0))
            {
                MoveTaskToBack(true);
            }
            else
            {
                base.OnBackPressed();
            }
        }
```
1.  If Xamarin.Forms.Application.Current.MainPage is a MasterDetailPage, and the Detail page is the NavigationPage, back navigation using the hard back button doesn't work.

2. If Xamarin.Forms.Application.Current.MainPage is a navigation page, the navigation stack's root page's BackButtonPressed event will never be triggered and if it has a custom ContentPage.OnBackButtonPressed override, it will not be called, even if the page is the top/only page on the stack.

3. This override hides Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnBackPressed() from derived classes.

Current Behavior:
In cases 1 & 2, MoveTaskToBack(true) gets called instead of Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnBackPressed().

### Configuration :wrench:

**Version:** 6.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
This override can't be removed as it's important that MoveTaskToBack is called appropriately. For the scenarios in question, how would you propose we handle them at a framework level?

**Comment by nmilcoff** [comment]
I agree we shouldn't be overriding `OnBackPressed`. The code we have now is a globally accepted workaround some some Android ugliness, which isn't always needed (as the issue mentions - on those cases the current implementation makes it difficult to customize behavior).

**Comment by nickrandolph** [comment]
Yes but it was added for good reason - in nearly every app you’re going to need at least this code. I suggest we handle those scenarios, providing extension points that devs can work with.

Eg master details - we can be much cleverer about the top most navigation stack, like we do with the forms presenter
