### ISSUE TITLE
Master Detail never cancel CloseCompletionSource

### ISSUE THREAD

**Issue by Thetyne** [MvvmCross/MvvmCross#2833]
### Steps to reproduce :scroll:

1. Make a Master detail Forms project on iOS. i haven't test on Android.

2. Add 2 bouton inside the master page who call one view model (with detail page with or without navigation page) like 
`var result = await NavigationService.Navigate<ViewModel, TModel, TResult>(data);`

3. Click on first button then one second button.

4. It appear that TResult CloseCompletionSource is never Canceled.

5. Same thing when i press on back button (with a navigation page on detail page)

### Expected behavior :thinking:
CloseCompletionSource must be canceled when mvvmcross pop View.
Normally, it must be call ViewModel.ViewDestroy method who called by UIViewController.DidMoveToParentViewController.

UIViewController.DidMoveToParentViewController is overrided by mvvmcross
```
public override void DidMoveToParentViewController(UIViewController parent)
        {
            base.DidMoveToParentViewController(parent);
            if(parent == null)
                ViewModel?.ViewDestroy();
        }
``` 

Problem: Maybe a memory leak but also my command is never released.

For test, i have override MvxFormsPagePresenter and the CloseMasterDetailPage method for call 
`ViewModel?.Destroy();` inside and the token is canceled.

### Actual behavior :bug:
it seem MvxFormsPagePresenter, never call UIViewController.DidMoveToParentViewController.

### Configuration :wrench:

**Version:** 6.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Thetyne** [comment]
I have fixed in my code by create my own MvxFormsPagePresenter and change code inside "ReplacePageRoot":


 ```
if (parent is MasterDetailPage rootMasterDetail)
                {
                    if (attribute is MvxMasterDetailPagePresentationAttribute masterDetailAttribute)
                    {
                        if (masterDetailAttribute.Position == MasterDetailPosition.Master)
                        {
                            rootMasterDetail.Master = page;
                        }
                        else if (masterDetailAttribute.Position == MasterDetailPosition.Detail)
                        {
                            rootMasterDetail.Detail = page;
                        }
                    }
                }
```

replace to

```
if (parent is MasterDetailPage rootMasterDetail)
                {
                    if (attribute is MvxMasterDetailPagePresentationAttribute masterDetailAttribute)
                    {
                        if (masterDetailAttribute.Position == MasterDetailPosition.Master)
                        {
                            rootMasterDetail.Master = page;
                        }
                        else if (masterDetailAttribute.Position == MasterDetailPosition.Detail)
                        {
                            if(rootMasterDetail.Detail is NavigationPage navigationPage && navigationPage.Pages != null)
                            {
                                var reversePage = navigationPage.Pages.Reverse();
                                foreach(var pageTmp in reversePage)
                                {
                                    if(pageTmp is MvxContentPage mvxContentPage)
                                    {
                                        mvxContentPage.ViewModel?.ViewDestroy();
                                    }
                                }
                            }

                            rootMasterDetail.Detail = page;
                        }
                    }
                }
```

**Comment by nickrandolph** [comment]
@Thetyne glad you found a solution - we'd love you to submit it as a PR so we can apply it to other scenarios.
