### ISSUE TITLE
stamp $(AssemblyName) ($(TargetFramework)) into builds 

### ISSUE THREAD

**Issue by ghuntley** [MvvmCross/MvvmCross#2836]
Hey folks. 

I stole this pattern from James Monty and Redth. You should totally steal it as well.

https://github.com/reactiveui/ReactiveUI/pull/1604/files

**Comment by martijn00** [comment]
Isn't that what we do: https://github.com/MvvmCross/MvvmCross/blob/develop/Directory.build.props#L14

**Comment by ghuntley** [comment]
👍
