### ISSUE TITLE
Converters for Xamarin.Forms

### ISSUE THREAD

**Issue by MartinZikmund** [MvvmCross/MvvmCross#2847]
I have noticed `MvxValueConverters` are not supported on MvvmCross.Forms. Although they are clearly a bit less useful than with native, there are benefits like being able to reuse existing value converters from native MvvmCross projects and having a strongly typed alternative to `IValueConverter`.

If this is a feature you consider worth being part of MvvmCross.Forms, I will be glad to try to implement it 😀

### Configuration :wrench:

**Version:** vNext

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@MartinZikmund I'd suggest going ahead and implementing one or more of them and submit as a PR. We'll help you with any adjustments that need to be made

**Comment by nickrandolph** [comment]
@MartinZikmund I'm closing this issue now based on your PR
