### ISSUE TITLE
Propose new docs structure

### ISSUE THREAD

**Issue by MarcBruins** [MvvmCross/MvvmCross#2856]
Soon we will be able to support a nested doc structure. I'm currently working on it in my own [fork.](https://github.com/MarcBruins/MvvmCross/tree/master/docs) This has been a long requested feature for MvvmCross. With the ability to nest our docs, how should we nest it? I can make a initial proposition soon but i'd love some help here.

Another thing where i would like some help (for everybody's sake) is the design of the menu. I'm not a webdev and don't have a lot of feeling for beautiful menu structuring. [This is what i have right now](https://ibb.co/eCAmPS)

**Comment by nickrandolph** [comment]
@MarcBruins one of my main concerns with documentation is how do we set it up so that it's maintainable - as we work through issues/PRs, how do we ensure the documentation stays up to date. This may be more of a process question but perhaps if there's a way that we an correlate parts of the MvvmCross namespace with documentation somehow, at least we'd know where in the docs we should be making changes.
Sorry I know this probably isn't that helpful, I'm just raising the concern I have about trying to build and maintain documentation.

**Comment by nickrandolph** [comment]
Another consideration when structuring documentation is that not everything needs to be provided within the MvvmCross documentation. For example where developers have posted articles/blogs about using MvvmCross, perhaps they should be linked to in the docs. This actually helps encourage third party bloggers, because they'll get increased traffic, and shifts the burden of documentation away from the core team.

**Comment by MarcBruins** [comment]
Good question Nick. We've discussed this issue before and my view is that it should be embedded within a PR if it changes existing behaviour or adds new behaviour for the users of mvx. With the current setup of the documentation(using jekyll and hosting it from the docs folder) it's never been easier to change it. I'm not sure how we can correlate namespaces to docs. For me the docs should reflect Mvx on a high level and have some tutorials (that can be a bit behind). If something changes on a high level it can be easily changed and it would be a minor effort to lookup the relevant docs(for the one making the PR and the reviewers).

Third party blogs are already very welcome on the docs if you ask me. If they feel like there blog adds value within a specific piece of documentation, they should feel free to make a PR and add a link to there blog post.

**Comment by nmilcoff** [comment]
We can probably add a document for 3rd party blogs, that can always be helpful.

Other than that maybe we can create a documentation category per platform? So then we can have docs for widgets, platform services ViewPresenter, ... within it.

**Comment by Cheesebaron** [comment]
It is mainly the Platforms and Tutorials sections which need some subsections. Otherwise I would keep the structure as is.

Links to the pages should preferably stay as is.

As for blogs, there could be a separate page for these and we could link to individual relevant posts in relevant docs pages.

**Comment by MarcBruins** [comment]
So this is my proposal for a first doc structure: 
`- item: Getting started
  root: true
  subitems:
    - item: Getting started with MvvmCross
      url: /documentation/getting-started/getting-started
    - item: MvvmCross Overview
      url: /documentation/getting-started/mvvmcross-overview
    - item: MvvmCross Packages
      url: /documentation/getting-started/mvvmcross-packages
    - item: .NET Standard & MvvmCross
      url: /documentation/getting-started/netstandard
    - item: Portable Class Library (PCL)
      url: /documentation/getting-started/portable-class-library-pcl

- item: Fundamentals
  root: true
  subitems:
    - item: Data binding
      url: /documentation/fundamentals/data-binding
    - item: Navigation
      url: /documentation/fundamentals/navigation
    - item: ViewModel Lifecycle
      url: /documentation/fundamentals/viewmodel-lifecycle
    - item: View Presenters
      url: /documentation/fundamentals/view-presenters
    - item: Inversion of Control
      url: /documentation/fundamentals/inversion-of-control-ioc
    - item: Dependency injection
      url: /documentation/fundamentals/dependency-injection
    - item: Diagnostic & Logging
      url: /documentation/fundamentals/logging
    - item: Value converters
      url: /documentation/fundamentals/value-converters
    - item: Value combiners
      url: /documentation/fundamentals/value-combiners
    - item: Testing
      url: /documentation/fundamentals/testing
    - item: Linking
      url: /documentation/fundamentals/linking

- item: Advanced
  root: true
  subitems:
    - item: Customizing App and Setup
      url: /documentation/advanced/customizing-using-App-and-Setup
    - item: Custom Data Binding
      url: /documentation/advanced/custom-data-binding
    - item: Code Analysis
      url: /documentation/advanced/analysis
    - item: Async operations with MvxNotifyTask
      url: /documentation/advanced/mvxnotifytask
    - item: ReSharper Annotations
      url: /documentation/advanced/resharper-annotations
    - item: ViewModel to View Interaction
      url: /documentation/advanced/mvxinteraction

- item: Platforms
  root: true
  subitems:
    - item: Android
      subitems:
      - item: Android MvxLinearLayout
        url: /documentation/platform/android/android-linearlayout
      - item: Android support library
        url: /documentation/platform/android/android-support-library
      - item: Android Swipe to Refresh
        url: /documentation/platform/android/android-swipe-refresh
      - item: Android View Presenter
        url: /documentation/platform/android/android-view-presenter
    - item: iOS
      subitems:
      - item: iOS Tables and Cells
        url: /documentation/platform/ios/ios-tables-and-cells
      - item: iOS UIRefreshControl
        url: /documentation/platform/ios/ios-uirefreshcontrol
      - item: Approaches for iOS UIs
        url: /documentation/platform/ios/ios-user-interfaces-approaches
      - item: iOS View Presenter
        url: /documentation/platform/ios/ios-view-presenter
      - item: Mac View Presenter
        url: /documentation/platform/macos/mac-view-presenter
      - item: Approaches for tvOS UIs
        url: /documentation/platform/tvos/tvos-user-interfaces-approaches
      - item: tvOS View Presenter
        url: /documentation/platform/tvos/tvos-view-presenter
    - item: Xamarin Forms
      subitems:
      - item: Xamarin.Forms Startup Customization
        url: /documentation/platform/xamarin.forms/xamarin-forms-customization
      - item: Xamarin.Forms View Presenter
        url: /documentation/platform/xamarin.forms/xamarin-forms-view-presenter
      - item: MvvmCross for Xamarin.Forms
        url: /documentation/platform/xamarin.forms/xamarin-forms
    - item: UWP
      subitems:
      - item: Universal Windows platform (UWP)
        url: /documentation/platform/uwp/universal-windows-platform-uwp
      - item: WPF View Presenter
        url: /documentation/platform/wpf/wpf-view-presenter
      
- item: Plugins
  root: true
  subitems:
    - item: 3rd party plugins
      url: /documentation/plugins/3rd-party-plugins
    - item: Accelerometer
      url: /documentation/plugins/accelerometer
    - item: Color
      url: /documentation/plugins/color
    - item: Email
      url: /documentation/plugins/email
    - item: FieldBinding
      url: /documentation/plugins/fieldbinding
    - item: File
      url: /documentation/plugins/file
    - item: Getting Started
      url: /documentation/plugins/getting-started
    - item: iOS Sidebar
      url: /documentation/plugins/ios-sidebar
    - item: Json
      url: /documentation/plugins/json
    - item: JsonLocalization
      url: /documentation/plugins/jsonlocalisation
    - item: Location
      url: /documentation/plugins/location
    - item: Messenger
      url: /documentation/plugins/messenger
    - item: MethodBinding
      url: /documentation/plugins/methodbinding
    - item: Network
      url: /documentation/plugins/network
    - item: PhoneCall
      url: /documentation/plugins/phonecall
    - item: PictureChooser
      url: /documentation/plugins/picturechooser
    - item: Plugins development
      url: /documentation/plugins/plugins-development
    - item: ResourceLoader
      url: /documentation/plugins/resourceloader
    - item: ResxLocalization
      url: /documentation/plugins/resxlocalization
    - item: Share
      url: /documentation/plugins/share
    - item: Visibility
      url: /documentation/plugins/visibility
    - item: WebBrowser
      url: /documentation/plugins/webbrowser

- item: Samples
  root: true
  subitems:
    - item: Samples
      url: /documentation/samples/samples

- item: Tutorials
  root: true
  subitems:
    - item: The TipCalc tutorial
      url: /documentation/tutorials/tipcalc/the-tip-calc-tutorial
    - item: The Core Project
      url: /documentation/tutorials/tipcalc/the-core-project
    - item: TipCalc Android Project
      url: /documentation/tutorials/tipcalc/a-xamarinandroid-ui-project
    - item: TipCalc iOS Project
      url: /documentation/tutorials/tipcalc/a-xamarinios-ui-project
    - item: TipCalc WPF Project
      url: /documentation/tutorials/tipcalc/a-windows-universal-app-platform-project
    - item: TipCalc Xamarin.Forms
      url: /documentation/tutorials/tipcalc/a-xamarin-forms-version
    - item: TipCalc - Summary
      url: /documentation/tutorials/tipcalc/tip-calculator-a-recap
    - item: Extra - Views and ViewModels
      url: /documentation/tutorials/tipcalc/a-note-about-views-and-viewmodels
    - item: Extra - Navigation
      url: /documentation/tutorials/tipcalc/the-tip-calc-navigation

- item: Upgrading
  root: true
  subitems:
    - item: Upgrade from 3 to MvvmCross 4
      url: /documentation/upgrading/upgrade-to-mvvmcross-40
    - item: Upgrade from 4 to MvvmCross 5
      url: /documentation/upgrading/upgrade-to-mvvmcross-50
    - item: Upgrade from 5 to MvvmCross 6
      url: /documentation/upgrading/upgrade-to-mvvmcross-60

- item: Contributing
  root: true
  subitems:
    - item: New contributions
      url: /documentation/contributing/contribute
    - item: Style Guide
      url: /documentation/contributing/mvvmcross-docs-style-guide
    - item: Debugging with Symbols
      url: /documentation/contributing/debugging-with-symbols
    - item: References
      url: /documentation/contributing/references
    - item: Licensing
      url: /documentation/contributing/licensing
    - item: Acknowledgements
      url: /documentation/contributing/acknowledgements
    - item: .NET Foundation
      url: /documentation/contributing/dotnet-foundation`

I have this structure working on my branch. Will make a PR soon, are there people willing to check it out/test it? I'll try to host it on my own github.

**Comment by nmilcoff** [comment]
Looks great to me! 👏 

Only one little thing: How about making separate subcategories for tvOS and macOS? Even though we don't have much to add (yet!).
