### ISSUE TITLE
Get-Started documentation needs to be updated

### ISSUE THREAD

**Issue by georgikoemdzhiev** [MvvmCross/MvvmCross#2857]
Please improve the getting started experience. I am new to MvvmCross and I definitely want to consider trying it in my next Xamarin.Forms project. However, the Getting-Started experience is very frustrating. 

### Steps to reproduce :scroll:

1. Go to [Getting-Started page](https://www.mvvmcross.com/documentation/getting-started/getting-started)
2. Try to follow the documentation to get a basic project working

### Expected behaviour:thinking:
I expect to get a basic Xamarin.Forms/Native app working by following the "Getting-Started" documentation as with almost all frameworks out there.

### Actual behavior :bug:
The existing doc just provides theory on how things work in the framework. There is no steps on how to get a basic project setup with the framework which is very important in my opinion for a newcomer who wants to get the thing running to check it out in practice. I am of course excluding "Tips Calculator" project as it is outdated.

### Configuration :wrench:
N/A
**Version:** 6.x
**Platform:** 
N/A

**Comment by andrewtechhelp** [comment]
I've tried to help with this issue with pull request #2858 that I submitted a day or so ago, except from a slightly different angle. That's just for the Readme.txt file that opens up when you install the NuGet package. The ReadMe I've written is designed to be as bare bones as possible though, so this Getting Started Documentation on the website would need to be much more detailed that what I've done with that ReadMe.

I might be able to look at improving this Getting Started Documentation sometime within the next month as I've learnt a bunch from trying to update the ReadMe.

**Comment by georgikoemdzhiev** [comment]
@andrewtechhelp, nice! I will have a look at your PR. As for the doc on the website, I don't think it should be very detailed, imo. Maybe showcase how to create a basic View-ViewModel or 2 of these that utilize the NavigationalService to switch to the other page. Something like that I was suggesting.

**Comment by tstivers1990** [comment]
In fact, the starterpack is not updated for v6. I've looked at all of the templates, and they're all out of date. The only one that's up to date is MvxScaffolding, which isn't listed on the getting started page, and also has errors upon project creation.

I would fix the starterpack package myself and submit a pull request, but it was either deleted from this repo, or the nuget page links to the wrong location, or the files are created through some cryptic build process that isn't clear.

**Comment by nmilcoff** [comment]
Not ideal, but you can always follow the TipCalc tutorial, which has been updated recently.

**Comment by andrewtechhelp** [comment]
As mentioned above (if someone doesn't pick it up sooner), I might be able to submit a pull request with some improvements for this in the future. I would do it this week, but I've got other life things that have to be done first :)

**Comment by nmilcoff** [comment]
@andrewtechhelp do you have any news on this? I would love to help you getting that PR ready!

**Comment by andrewtechhelp** [comment]
@nmilcoff Heya. I haven't looked at any of this for a few months because I've been going through the process of moving house. I do plan to get back to this soon though :)
