### ISSUE TITLE
Address "RequestMainThreadAction is obsolete" build warnings

### ISSUE THREAD

**Issue by nickrandolph** [MvvmCross/MvvmCross#2859]
### Steps to reproduce :scroll:
1. Build solution - note the half dozen or so warnings:
warning CS0618: 'IMvxMainThreadDispatcher.RequestMainThreadAction(Action, bool)' is obsolete:

### Expected behavior :thinking:
No build warnings

### Actual behavior :bug:
Multiple warnings
warning CS0618: 'IMvxMainThreadDispatcher.RequestMainThreadAction(Action, bool)' is obsolete:

**Version:** 6.x

**Platform:** 
All

**Comment by rdorta** [comment]
@martijn00 @nickrandolph  I can work on this one if no one is already.

**Comment by Cheesebaron** [comment]
@rdorta go ahead

**Comment by nickrandolph** [comment]
@rdorta @Cheesebaron I agree these need to be done - just be careful as there are a couple of open PRs that may/will affect this

**Comment by rdorta** [comment]
Yeah sure. I'm helping @martijn00 in another PR, I can look at this right after.

**Comment by Cheesebaron** [comment]
I invited @rdorta to the team. This way we can assign him to issues :)

**Comment by nickrandolph** [comment]
The more the merrier. Welcome @rdorta

**Comment by nickrandolph** [comment]
@rdorta if you're going to tackle this, there are two things we need to do:
- address the warnings by calling the new async methods (see warning)
- remove the obsolete method
I think removing the obsolete method is quite a significant changes, so I think we should raise that on a separate PR.

**Comment by nickrandolph** [comment]
These warnings have been cleared up now, so closing this issue
