### ISSUE TITLE
ViewModel#Destroy does not get called on UWP

### ISSUE THREAD

**Issue by ueman** [MvvmCross/MvvmCross#2860]
The ViewDestroy Method of the MvxViewModel does not get called.

I guess it should be added somewhere here:
https://github.com/MvvmCross/MvvmCross/blob/59809878c68b7e8f3648e54aca1dd921af17fbfe/MvvmCross/Platforms/Uap/Views/MvxWindowsPage.cs#L173

### Steps to reproduce :scroll:

1. Open MvvmCross Playground

2. Override ViewDestroy method of a ViewModel and set a breakpoint.

3. Navigate. The breakpoint is never hit.  

### Expected behavior :thinking:
ViewDestroy should be called.

### Actual behavior :bug:
ViewDestroy is never called.

### Configuration :wrench:

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
What if you navigate backwards? Is OnViewDestroyed then called?

**Comment by ueman** [comment]
Nope

**Comment by ueman** [comment]
Maybe it should also be called in https://github.com/MvvmCross/MvvmCross/blob/59809878c68b7e8f3648e54aca1dd921af17fbfe/MvvmCross/Platforms/Uap/Views/MvxWindowsPage.cs#L38

It seems like that is the last lifecycle method of the page.
However, as per documentation, it also gets called after a user triggered theme change.

**Comment by ueman** [comment]
I would do a PR myself. However I'm not sure which would be the best place to call ViewDestroy.
Should it be in Dispose or in MvxWindowsPage_Unloaded? Or somewhere else?

I guess it could also be called when you close a ViewModel with the NavigationService. However that seems to be a weird place as it has nothing to do with the view.

**Comment by nickrandolph** [comment]
Closing this issue as it is addressed by the merged PR
