### ISSUE TITLE
 cast to parent class

### ISSUE THREAD

**Issue by timothd** [MvvmCross/MvvmCross#2880]
### Steps to reproduce :scroll:

1.

2.

3.

### Expected behavior :thinking:
Tell us what should happen

### Actual behavior :bug:
Tell us what happens instead

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
No information provided
