### ISSUE TITLE
I'ts impossible to use custom MvxSuspensionManager in UWP projects

### ISSUE THREAD

**Issue by qbus00** [MvvmCross/MvvmCross#2882]
### Steps to reproduce :scroll:

1. Create custom MvxSuspensionManager which is implementing IMvxSuspensionManager interface

2. Create it in custom MvxFormsWindowsSetup class by overriding CreateSuspensionManager class 

3. Run application and check in debug MvxApplication OnResuming and OnSuspending classes.

### Expected behavior :thinking:
suspension variable in these methods should not be null

### Actual behavior :bug:
suspension variables in these methods are null because of casting to MvxSuspensionManager instead of IMvxSuspensionManager (this in fact does not resolve an issue as this interface does not contain SaveAsync and RestoreAsync methods.

I don't know an exact MVVMCross architecture but possible solution would be to add these methods  (SaveAsync and RestoreAsunc) to IMvxSuspensionManager and replace casting from MvxSuspensionManager to IMvxSuspensionManager.

### Configuration :wrench:

**Version:** 6.0.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Can you submit a repro scenario using the playground uwp sample as a PR and I will take a look

**Comment by qbus00** [comment]
OK, PR created https://github.com/MvvmCross/MvvmCross/pull/2883

**Comment by qbus00** [comment]
Another simplier demo PR created - https://github.com/MvvmCross/MvvmCross/pull/2885
