### ISSUE TITLE
Feature: Support YamlLocalization as Plugin.

### ISSUE THREAD

**Issue by kvandake** [MvvmCross/MvvmCross#2892]
Hello! I recently added a new kind of localization management via yaml format. The library is available on [github](https://github.com/kvandake/friendly-locale).
I also added the use of localizations in MvvmCross. I wrote a detailed instruction how to add a new type of localization in mvvmcross projects. Instructions are available in the [Wiki](https://github.com/kvandake/friendly-locale/wiki/Support-MvvmCross-Localization). As a bonus, the localization can be changed on the fly!
Can we consider the implementation of yaml localization as a plugin?

**Version:** 5.x, 6.x

**Test Platforms:** 
- [ x] :iphone: iOS
- [ x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I think we could add this as plugin in MvvmCross. Some of the other improvements might be nice in other localization plugins as well.

I see a couple of things that need to be done. First you need to convert your plugin to .NET Standard. Then we can add the code for the MvvmCross plugin to this repo.

After that we should add some test code in the playground and documentation. We would be happy to receive a PR for this.

**Comment by martijn00** [comment]
Closing because of lack of interest.
