### ISSUE TITLE
Status Bar Style jumps back to default after navigation from modal view (iOS)

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2893]
The issue #2463 is back with Xamarin.Forms 3.0 when using MvvmCross. This time only for modal dialogs (at least as far as my testing goes - MasterDetail seems to work same as Tabbed pages). 

### Steps to reproduce :scroll:

1. Close a modal presented view/viewmodel

2. After the navigation, the status bar style returns to "Default" instead of "Light" - even if "Light" is configured in the Info.plist

### Expected behavior :thinking:
The status bar style should be stay untouched (based on the Info.plist file).

### Actual behavior :bug:
It changes back to default.

### Configuration :wrench:

**Version:** 6.0.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@Sebastian1989101 which XF platforms is this on? all? would you be able to submit a PR that repros this in the playground?

**Comment by SebastianKruseWago** [comment]
@nickrandolph This can be reproduced in any Xamarin.Forms (3.0 or newer) with MVX (6.0.0 or newer) without any trouble. Just set this in the info.plist file and then navigate to a modal page: 

```
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleLightContent</string>
```
