### ISSUE TITLE
mvvmcross with Xamarin.Forms

### ISSUE THREAD

**Issue by levin9** [MvvmCross/MvvmCross#2894]
I visited https://github.com/Cheesebaron/Xam.Forms.Mvx. but this project refers to a lot of DLL. The DLL quoted is  older. and cannot be compiled with mvvmcross5.7.

It would be great if someone could provide sample,article.

Thanks in advanced

**Comment by Cheesebaron** [comment]
Our playground project has examples of usage with Xamarin Forms. https://github.com/MvvmCross/MvvmCross/tree/develop/Projects/Playground

**Comment by nickrandolph** [comment]
Please ask these questions like this on stackoverflow or the mvvmcross slack channel

**Comment by levin9** [comment]
thanks,I've  solved it.
https://github.com/martijn00/MvxForms
https://medium.com/@martijn00/using-mvvmcross-with-xamarin-forms-part-1-eaee5815bb8c
