### ISSUE TITLE
MvxTaskBasedBindingContext creates timing issues with autosizing cells

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2898]
MvxTaskBasedBindingContext  but create timing issues in some situations, especially in self sizing cells of table and collection views. 

The workaround is to change the bindingcontext do it runs syncrhonously. This is possible since https://github.com/MvvmCross/MvvmCross/issues/1423#issuecomment-390918127

This should also be set by default in MvxTableViewCell and MvxCollectionViewCell, when the bindingcontext is set or in an initializer.

        if (BindingContext is MvxTaskBasedBindingContext taskBasedBindingContext)
        {
            //Suppose we always use automatic dimension for cells, which requires synchronous sizing, which needs synchronous data.
            taskBasedBindingContext.RunSynchronously = true;
        }

### Steps to reproduce :scroll:

1. Create a UICollectionView and configure it for self sizing cells, then add cells so they go out of sight when scrolling.

2. Scroll the view, so cells are recycled. when recycled, they are rebound by mvvmcross with new data, which may change the cell's sizes.

### Expected behavior :thinking:
cell's autosize correctly

### Actual behavior :bug:
After a couple of recycling, cell's sizes start to change randomly.

### Configuration :wrench:

**Version:** 6.0.1
iOS concerned, Android may be too.

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
In the case of UITableView, I think this was fixed in #2644. Or do you still have issues with that?

**Comment by softlion** [comment]
Will try the fix. Closing for now.
