### ISSUE TITLE
Can I please see the FragmentHostRegistrationSettings.cs source for 4.4.0?

### ISSUE THREAD

**Issue by jsauve** [MvvmCross/MvvmCross#2899]
Not really an issue. More of a request. I had trouble locating the 4.4.0 version of `FragmentHostRegistrationSettings`. The project I'm currently a part of is using 4.4.0 and we're seeing a bunch of null ref exceptions in `FragmentHostRegistrationSettings. GetCurrentActivityViewModelType()` in production. Unable to reproduce.

I trie to locate the source on my own, but was unsuccessful. Can someone please provide a link to the 4.4.0 version of the MvvmCross source code? Thanks.

**Comment by nmilcoff** [comment]
There is a tag for each release. Here you have the source code for 4.4.0 🙂: 

Main repository: https://github.com/MvvmCross/MvvmCross/tree/4.4.0
Android Support repository: https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/4.4.0

**Comment by jsauve** [comment]
Thanks! I tried clicking the 4.4.0 tag while I was in the file, but it appeared I didn't have access. Perhaps the path has changed. Thanks again!

**Comment by jsauve** [comment]
@nmilcoff, this issue sounds very much like what I'm seeing in 5% of my user base:
https://github.com/MvvmCross/MvvmCross/issues/783

Am I correct in my understanding that this is resolved in Mvx 6.x?
