### ISSUE TITLE
Exceptions are swallowed during Android setup

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2903]
### Steps to reproduce :scroll:

1. Associate more than one view with a view model.
2. Start the app.
3. The Android splash screen never closes. There are no exceptions thrown or messages logged. Previous versions of MvvmCross would trigger an exception making it easier to debug these kind of setup problems.

### Expected behavior :thinking:
Exceptions thrown during setup should not be swallowed on Android.

### Actual behavior :bug:
Exceptions during setup are swallowed and nothing is logged.

### Configuration :wrench:

**Version:** 6.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by sergeyyurkov** [comment]
I believe it also applies at least to WPF. I didn't add one of the nuget packages to WPF project so I got a System.Reflection.ReflectionTypeLoadException somewhere in mscorelib that appeared only if I unselect 'Just my code' in the debugger options. With the option enabled (which is a default) the WPF app end up running without any window and absolutely error-clean log.

**Comment by nickrandolph** [comment]
If you enable all exceptions in the exceptions window in visual studio do any get thrown? If so, can you provide a PR that shows how to reproduce this using the playground sample please

**Comment by sergeyyurkov** [comment]
@nickrandolph Unfortunately I can't. Cloned the repo and got a bunch of errors trying to build Playground.WPF. Started with `Error occurred while restoring NuGet packages: The operation failed as details for project MvvmCross.Forms could not be loaded` and continued with dozens of `...\File\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.`
Did I miss something obvious?

**Comment by nickrandolph** [comment]
Can you try the 6.1 branch please - we've had to fix a bunch of build related issues, so please try this branch instead. 
If it doesn't build properly, please do a solution clean, restart VS and try building again (reach me on mvvmcross.slack.com if you need assistance)

**Comment by tbalcom** [comment]
I was able to see a `System.ArgumentException` when I enabled all exceptions.

> Exception:
> 
> System.ArgumentException: An item with the same key has already been added. Key: Playground.Core.ViewModels.RootViewModel occurred
>

The exception is thrown [here](https://github.com/MvvmCross/MvvmCross/blob/bd3a438f8acff76657a743da0669d97254b7aaa6/MvvmCross/ViewModels/MvxViewModelViewLookupBuilder.cs#L29). A PR to reproduce the issue is incoming.

**Comment by tbalcom** [comment]
The [Task](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/MvxSetupSingleton.cs#L176) started using `Task.Run` in `MvxSetupSingleton.StartSetupInitialization` is a fire and forget Task so the exception is retained and never re-thrown because nothing checks the result of the Task using `.Wait` or `await`. 

It looks like we can use a task continuation and at least log the exception to help people debug issues during setup: 
```c#
Task.Run(() =>
{
    _setup.InitializeSecondary();
    lock (LockObject)
    {
        IsInitialisedTaskCompletionSource.SetResult(true);
        var dispatcher = Mvx.GetSingleton<IMvxMainThreadDispatcher>();
        dispatcher.RequestMainThreadAction(() =>
        {
            if (_currentMonitor != null)
            {
                _currentMonitor?.InitializationComplete();
            }
        });
    }
}).ContinueWith((t) =>
{
    if (t.IsFaulted)
    {
        IsInitialisedTaskCompletionSource.SetException(t.Exception);
        MvxLog.Instance.ErrorException("Exception caught during MvvmCross initialization", t.Exception);
    }
});
```

Any other ideas for a solution to prevent the unhandled exceptions thrown during setup from being swallowed? I guess the answer is this should be made async, but I believe that is much easier said than done.

**Comment by nickrandolph** [comment]
I think the issue is that the setup might not have got to the point where logging will work. It maybe that we need to grab the task reference so it can be interrogated later.

Also there may be an issue where the init done in the dispatcher might error also causing I handled exceptions

**Comment by tbalcom** [comment]
The issue has been fixed.
