### ISSUE TITLE
UIApplication.SharedApplication.KeyWindow.GetTopModalHostViewController() is incorrect

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2906]
This code used in most iOS plugins is incorrect:

    UIApplication.SharedApplication.KeyWindow.GetTopModalHostViewController()

If the call is made from when an UIAlertView is opened, UIApplication.SharedApplication.KeyWindow is the window of the alert view.

Instead the code should find a normal key window like this:

    UIApplication.SharedApplication.Windows.LastOrDefault(w => w.WindowLevel == UIWindowLevel.Normal)

Or better, the code should call a method in the AppPresenter to display its viewcontroller as modal, like it was possible in v5.x

**Version:** 6.0.1

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a pull request to fix this?

**Comment by martijn00** [comment]
Sometime in the future it will be possible to include symbols into nuget packages so you can debug locally. To try out new changes in your own project you will always have to run it by replacing nugets locally or get it merged first and update from Myget.

We have the playground where you can add a scenario to reproduce this, and make a fix. That is the best way for now. By doing that we can also add other tests to this.

**Comment by nmilcoff** [comment]
I tried the following code on a random app:

```c#
var firstWindow = UIApplication.SharedApplication.KeyWindow;

//Create Alert
var okAlertController = UIAlertController.Create("Title", "The message", UIAlertControllerStyle.Alert);

//Add Action
okAlertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

// Present Alert
PresentViewController(okAlertController, true, null);

await Task.Delay(5000);

var secondWindow = UIApplication.SharedApplication.KeyWindow;

var sameWindow = firstWindow == secondWindow; 
// sameWindow is true
```

So unless I didn't understand the scenario, I guess this is working just fine. Can you please elaborate or contribute a minimal reproducible sample for the bug @softlion?

**Comment by nmilcoff** [comment]
I'll close this one for now. Please feel free to reopen it if there is actually a problem and something needs to be changed.
