### ISSUE TITLE
Backstack in mvvmcross android working incorrectly

### ISSUE THREAD

**Issue by pablo0219** [MvvmCross/MvvmCross#2913]
### Steps to reproduce :scroll:

1. layout with multiple fragments inline. Ex:
<LinearLayout>
 <fragment1/>
 <fragemtn2/>
 <fragment3/>
 <fragment4/>
 <framelayout/>
</linearlayout>
2. In AcitivityViewModel Navigate to fragment5 to binding inflate that fragment5 in frame layout
            this._navigationService.Navigate(TypeFragment5);

Fragment5:    EditCarDetailsViewModel

    [MvxFragmentPresentation(typeof(EditClassifiedViewModel), Resource.Id.ExtraInfo, false)]
    [Register("rs.droid.views.EditCarDetailsFragment")]
    public class EditCarDetailsFragment : MvxFragment<EditCarDetailsViewModel>

All fragments have AddToBackStack: false

3. The problem is that when back button is pressed the fragment5 is removed from the activity/layout like if it was AddBackStack true. I don't sure if it's being added to back stack because I also attached to
            //SupportFragmentManager.BackStackChanged += (sender, e) =>
            //{

            //};

and it's not being hit. However, the behavior is not ok.

### Expected behavior :thinking:
The behavior expected is the activity should be stop/finish and the previous activity should be shown.

### Actual behavior :bug:
The actual behavior: last fragment (fragment5) is being removed from the layout/activity and the current activity is still active.

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [ ] :iphone: iOS
- [ X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Sorry, we don't provide support for old versions of MvvmCross. Please update to latest stable version if you want help.
