### ISSUE TITLE
What should come after The Core Project in the TipCalc tutorial? It seems wrong.

### ISSUE THREAD

**Issue by dumbledad** [MvvmCross/MvvmCross#2920]
At the end of the second page of the TipCalc tutorial, [The Core Project](https://www.mvvmcross.com/documentation/tutorials/tipcalc/the-core-project), there is a link to the next page. Before the Next! link is the text "The next step is about building a first UI for our MvvmCross application". But instead the Next! link takes us to the Extra - Navigation page ([here](https://www.mvvmcross.com/documentation/tutorials/tipcalc/the-tip-calc-navigation)). That doesn't seem like where it is supposed to go, is it?

**Comment by dumbledad** [comment]
(N.B. I've opened a pull request with the fix in: https://github.com/dumbledad/MvvmCross/pull/1 )

**Comment by nmilcoff** [comment]
Thanks for pointing this our @dumbledad. Can you please open the PR in this repository? Also be sure it targets master instead of develop or any other branch 🙂

**Comment by fedlerner** [comment]
I just had the same problem. 
I did the following Google search: [asd](https://www.google.com.ar/search?ei=vc4eW_CrHsWTsAGc5IzIDA&btnG=Buscar&q=www.mvvmcross.com%2Fdocumentation%2Ftutorials%2Ftipcalc%2F) and I got some results:

- [TipCalc Android Project](https://www.mvvmcross.com/documentation/tutorials/tipcalc/a-xamarinandroid-ui-project)
- [TipCalc iOS Project](https://www.mvvmcross.com/documentation/tutorials/tipcalc/a-xamarinios-ui-project)
- [TipCalc Xamarin.Forms](https://www.mvvmcross.com/documentation/tutorials/tipcalc/a-xamarin-forms-version)
- Other results...
