### ISSUE TITLE
Object reference not set to an instance of an object in MvxChainedSourceBinding.Dispose

### ISSUE THREAD

**Issue by alborzmgm** [MvvmCross/MvvmCross#2922]
I got a crash that happened in MvvmCross.Binding.Bindings.Source.Chained.MvxChainedSourceBinding.Dispose.
The message is "Object reference not set to an instance of an object". It can be something similar to #1414,  I think we need a lock statement for dispose method.

Version: 5.6.3

**Platform:** 
- iPad : iOS

**Comment by nickrandolph** [comment]
@alborzmgm a couple of requests:
- Please use the issue template
- Please can you check this issue against 6.0.1 (latest stable)
- Can you try to reproduce this issue in the playground sample, and if you can, raise it as a PR.

Closing this issue as we require more information before we can investigate (as per issue template)
