### ISSUE TITLE
IMvxNavigationService.Navigate<TViewModel, TParam, TResult> deadlock if the back button is used

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2924]
Is there any workaround or something I can do, so that I can still use this function? I don't like the MvxMessenger way which I use currently as an alternative (because it can easily fail due to lacks). 

### Steps to reproduce :scroll:

1. Use NavigationPage Back Button instead of a Close-Call with the result 

### Expected behavior :thinking:
Should just returns a default value 

### Actual behavior :bug:
Causes a deadlock within the MvxAsyncCommand if the NavigationPage back button is used and no return value is passed. 

### Configuration :wrench:

**Version:** 6.0.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by deepblueday** [comment]
Bump. This remains a problem with MVVMCross 7.0.1.
