### ISSUE TITLE
MvvmCross for Android.Xamarin TipCalc tutorial

### ISSUE THREAD

**Issue by CriRo7** [MvvmCross/MvvmCross#2928]
### Steps to reproduce :scroll:

1. Add MainApplication class step in mvvmcross.android tutorial.
2. trying to use MvvmCross.Platforms library.

### Expected behavior :thinking:
Normal using MvvmCross.Platforms
### Actual behavior :bug:
MvvmCross.Platforms marks as not exist
### Configuration :wrench:

**Version:** 6.01

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
MvvmCross.Core, MvvmCross.Platform and MvvmCross.Binding do not exist in MvvmCross 6.0.0 anymore. You just need the one MvvmCross NuGet package.

So just remove the other packages. If you are using a 3rd party dependency that is not updated to 6.0.0, then ask the author to upgrade.
