### ISSUE TITLE
Few of the examples compile on develop

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#2930]
### Steps to reproduce :scroll:

1. Just try to build any Android project: Playground.Droid, Example.Droid etc.

2.

3.

### Expected behavior :thinking:
Things should build

### Actual behavior :bug:
They don't

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Closing this as all the Playground samples now build
