### ISSUE TITLE
Playground.Droid crashes in nav stack

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#2931]
### Steps to reproduce :scroll:

1. Run it.

2. Click `Show Master/Detail`

3. Click `Show Child`

4. Click `Main Menu`

### Expected behavior :thinking:
Should take us somewhere.

### Actual behavior :bug:

App crashes with:
> System.Collections.Generic.KeyNotFoundException: Could not find view for Playground.Core.ViewModels.MixedNavFirstViewModel

### Configuration :wrench:

**Version:** develop

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@kjeremy is this still an issue on the 6.1 branch?

**Comment by kjeremy** [comment]
I can check tomorrow but it's definitely a problem in develop.

**Comment by kjeremy** [comment]
Yes it crashes on 6.1 branch.

**Comment by Cheesebaron** [comment]
Dupe of #2930 no?

**Comment by nickrandolph** [comment]
@kjeremy are you able to test this on develop and see if it still happening?
