### ISSUE TITLE
IMvxMessenger plugin is not loaded, MvxIoCResolveException

### ISSUE THREAD

**Issue by flyingxu** [MvvmCross/MvvmCross#2937]
### Steps to reproduce :scroll:

1.Make sure Playground.Forms.Uwp can compile and run

2. Add project reference of `MvvmCross.Plugin.Messenger` to `Playground.Core`
Add project reference of `MvvmCross.Plugin.Messenger` to `Playground.Forms.Uwp`
3. In RootViewModel(), add some code
```
        public RootViewModel(IMvxViewModelLoader mvxViewModelLoader)
        {
            _mvxViewModelLoader = mvxViewModelLoader;
            try
            {
                var messenger = Mvx.Resolve<IMvxMessenger>();
                var str = messenger.ToString();
            }
            catch(Exception e)
            {
                Console.WriteLine(e.ToString());
            }
```
4. Run Playground.Forms.Uwp again

### Expected behavior :thinking:
it runs

### Actual behavior :bug:
Exception:
```
MvvmCross.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.Plugin.Messenger.IMvxMessenger
   at MvvmCross.IoC.MvxIoCContainer.Resolve(Type t)
   at MvvmCross.IoC.MvxIoCContainer.Resolve[T]()
   at MvvmCross.IoC.MvxIoCProvider.Resolve[T]()
   at MvvmCross.Mvx.Resolve[TService]()
   at Playground.Core.ViewModels.RootViewModel..ctor(IMvxViewModelLoader mvxViewModelLoader)
```
### Configuration :wrench:

**Version:** build from source code, head of release/6.1.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

I use UWP because it's easier for me to test.

I have set a breakpoint at MvvmCross.Plugins\Messenger\Plugin.cs
```
        public void Load()
        {
            Mvx.RegisterSingleton<IMvxMessenger>(new MvxMessengerHub());
        }
```
the breakpoint is not hit.

**Comment by nickrandolph** [comment]
@flyingxu can you submit your changes to the playground as a PR linked to this issue - it just makes it easier for us to run it up, rather than having to replay your steps.

**Comment by flyingxu** [comment]
Good idea, #2938 is submitted

**Comment by sfmskywalker** [comment]
This commit broke the plugin discovery: 

20b57bc523e2cac105f7608cf1502c2fb8548c51 | Added recursive method to search for referenced assemblies and load them into AppDomain. | Ricardo Dorta | 5/8/2018 8:22:18 PM
-- | -- | -- | --

**Comment by flyingxu** [comment]
@sfmskywalker I will close this issue because #2938 is already merged.

**Comment by sfmskywalker** [comment]
Sure. I totally missed that there was already a PR.
