### ISSUE TITLE
Question related to the IMvxOverridePresentationAttribute interface (5.7.0.0)

### ISSUE THREAD

**Issue by dlpopescumtk** [MvvmCross/MvvmCross#2939]
### Steps to reproduce :scroll:

1. Create a fragment that has two _MvxFragmentPresentationAttributes_ (it's used in two activities)

2. Implement the _IMvxOverridePresentationAttribute_ interface

3. Use the _PresentationAttribute()_ method of the interface to return the customised attribute

### Expected behavior :thinking:

The answer to these questions might be obvious, but help me out here. 

How does the implementation of the interface know which attribute to override? 
Will it be called for each presentation attribute in the fragment? 

In the end, what I would like to know is how I can change, at runtime, the fragmentContentId value of the presentation attribute.

Cheers.

### Configuration :wrench:

**Version:** 5.7.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Thetyne** [comment]
For change PresentationAttribute at runtime , i pass a flag in my view model parameter .

await _navigationService.Navigate<ViewModel, ViewModelParameter>(viewModelParameter);

ViewModelParameter contain presentation flag which change PresentationAttribute type

**Comment by Cheesebaron** [comment]
Please use [Slack #mvvmcross](https://xamarinchat.herokuapp.com/) or [StackOverflow](https://stackoverflow.com/questions/tagged/mvvmcross) for questions. Github is meant to be used for bugs and feature requests only.
