### ISSUE TITLE
Question related to Xamarin.Forms 3.x

### ISSUE THREAD

**Issue by Thetyne** [MvvmCross/MvvmCross#2945]
Is Mvvmcross 6.x compatible with Xamarin.Forms 3.x?

### Configuration :wrench:

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by flyingxu** [comment]
Yes and it's targeting the latest version as #2933

**Comment by Thetyne** [comment]
Ok, thanks
