### ISSUE TITLE
Nightly builds are not updated

### ISSUE THREAD

**Issue by flyingxu** [MvvmCross/MvvmCross#2948]
### Steps to reproduce :scroll:

1. Check the latest version of the nightly build on Myget: https://www.myget.org/F/mvvmcross/api/v3/index.json

### Expected behavior :thinking:
Should see 6.1.0-unstable000 something

### Actual behavior :bug:
Only 6.0.0-unstable.210 is listed

**Comment by Cheesebaron** [comment]
This is fixed. Although we don't have nightly builds but rather CI builds. So everything going into develop should be spat out on MyGet and anything in release/master will go to NuGet.
