### ISSUE TITLE
Custom Presentation Hint Handler is still being ignored

### ISSUE THREAD

**Issue by DavePilks** [MvvmCross/MvvmCross#2950]
I have been looking at a few issues that seem to be closed. Namely:

- [Custom Presentation Hint Handler is ignored #2589](https://github.com/MvvmCross/MvvmCross/issues/2589)

So I have a custom hint and it is set up in my presenter as such

`        public CustomFormsPagePresenter(IMvxFormsViewPresenter platformPresenter) 
            : base (platformPresenter)
        {
			AddPresentationHintHandler<PopToViewModelHint>(HandlePopToHint);
        }`

But when I try to call it 

` NavigationService.ChangePresentation(new PopToViewModelHint(typeof(MyViewModel)));`

I get the following in the logs

> [TRACE] (MvvmCross.Logging.MvxLog) Requesting presentation change
> [WARN]  (MvvmCross.Logging.MvxLog) Hint ignored PopToViewModelHint

The presenter has been working correctly before I tried to set up the hint but my handler for this hint never gets called.

Version: 6.0.1
Platform: iOS

**Comment by nickrandolph** [comment]
Hey is there any chance you can reproduce this in the playground and submit a PR to demonstrate this issue and help us resolve what's going on?
