### ISSUE TITLE
Getting Exception System.ArgumentNullException.

### ISSUE THREAD

**Issue by Naveen9453** [MvvmCross/MvvmCross#2952]
### Steps to reproduce :scroll:

1.Created Project using MvvmCross and setup iOS project, Done changes in AppDelegate, Added ViewModel Class to Core part and Added App.cs file,Added LinkerPleaseInclude.cs file.

2.Created All changes as per this link https://github.com/nickrandolph/MvxPlus1DaysOfMvvmCross

3.Getting exception in ViewController while set.Apply() Line in ViewDidLoad method of ViewController.

           var set = this.CreateBindingSet<LoginViewController, LoginViewModel>();
            set.Bind(valueLbl).To(vm => vm.Value);
            set.Bind(entryTxtField).To(vm => vm.Value);
            set.Apply();

### Expected behavior :thinking:
It should run without exception and should work with data binding from viewmodel property.

### Actual behavior :bug:
It Throwing System.ArgumentNullException.
Please see attached png file of exception.

### Configuration :wrench:

**Version:** 6.1.x

**Platform:** 
- [ ] :iphone: iOS

![screen shot 2018-06-12 at 12 35 30 pm](https://user-images.githubusercontent.com/17539345/41275472-9d3a8732-6e3e-11e8-8bac-6ae8159b76c5.png)

**Comment by nickrandolph** [comment]
Hi @Naveen9453 would you be able to try to reproduce this in the playground sample and issue a PR so that we can investigate?

**Comment by wondercrazy15** [comment]
@nickrandolph  playground sample means this link sample  https://github.com/nickrandolph/MvxPlus1DaysOfMvvmCross   ?

**Comment by Naveen9453** [comment]
Hi @nickrandolph  I am running your sample from this link  https://github.com/nickrandolph/MvxPlus1DaysOfMvvmCross and getting same exception

![screen shot 2018-06-12 at 1 12 35 pm](https://user-images.githubusercontent.com/17539345/41276659-8828aa28-6e42-11e8-8edb-777f46caddf7.png)

**Comment by nickrandolph** [comment]
Sorry I meant the playground sample that's included within the mvvmcross source code (https://github.com/MvvmCross/MvvmCross/tree/develop/Projects/Playground)

**Comment by Naveen9453** [comment]
![screen shot 2018-06-12 at 2 15 13 pm](https://user-images.githubusercontent.com/17539345/41279832-1ea4fb66-6e4b-11e8-96de-d0061b4198d9.png)
I have cloned the projects from below link: https://github.com/MvvmCross/MvvmCross/tree/develop/Projects/Playground 
still getting this errors. I'm not able to build project from this link.

**Comment by nickrandolph** [comment]
@martijn00 @Cheesebaron is the mvvmcross solution buildable on VS Mac yet?

**Comment by Cheesebaron** [comment]
@nickrandolph the build script will most likely run fine. However, not sure how well VSfM handles the solution. We are very much on the bleeding edge here.

**Comment by nickrandolph** [comment]
@Naveen9453 are you able to build mvvmcross using VS (PC not Mac) and submit a PR demonstrating the issue in the playground?

**Comment by jamespettigrew** [comment]
[Refer to my comment here for the solution.](https://github.com/MvvmCross/MvvmCross/issues/2954#issuecomment-398040170)
