### ISSUE TITLE
The app stuck at Splash Screen when using MVVMCross 6.x

### ISSUE THREAD

**Issue by jothedev** [MvvmCross/MvvmCross#2953]
### Steps to reproduce :scroll:

1. Copy the Playground or any other sample solution that using MVVMCross 6
2. Restore Nuget packages and rebuild the solution
3. Run the app.

### Expected behavior :thinking:
The app will navigate to FirstViewModel define in `App.cs` after showing Splash Screen

### Actual behavior :bug:
The app will stuck in Splash Screen (with loading screen). No issue if I'm using MVVMCross version 5.7

### Configuration :wrench:
- Visual Studio 2017 ver. 15.7.3
- Xamarin.Android 8.3.3.2
- MVVMCross ver. 6.x (did try to use 6.0.1 and 6.1.0)

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Divyesh1** [comment]
Same behaviour in Xamarin.iOS project working with storyboard. The same application works properly with MvvMCross version 5.1.1. @jothedev

**Comment by Cheesebaron** [comment]
@divyesh008 please don't comment with "me too" comments, they do not provide any value. Use the reaction feature to add your sentiment.

**Comment by jothedev** [comment]
I've got an update for this problem. If I'm using template given from [MvxScaffolding](https://github.com/Plac3hold3r/MvxScaffolding), the app will run fine. It can go to the FirstViewModel.

However, if I try to replicate the template manually (even follows the `readme.txt` file) the app won't even reach `Initialize` method in `App.cs`. Just stop at the Splash Screen and stays there forever.

I've tried to created `MainApplication` class like the one in Playground project, used the Splash Screen inherited from these class:
- `MvxSplashScreenAppCompatActivity`
- `MvxSplashScreenActivity`
- `MvxSplashScreenAppCompatActivity<MvxAppCompatSetup<Core.App>, <App>>`
- `MvxSplashScreenActivity<MvxApplicationSetup<Core.App>, <App>>`

Nothing is working. But if I modified the `SplashActivity.cs` from the `MvxScaffolding` template, it works just fine.

Since I need to upgrade my current app, using the template is out of option. Did I missed something here?

**Comment by flyingxu** [comment]
What's the difference between your `SplashActivity.cs` and the `MvxScaffolding` template?

**Comment by FournierNico** [comment]
I'm facing the same issue. I try the following : 

- Launch `TipCalc` sample : **freeze** at SplachScreen
- Follow `TipCalc` tutorial from mvvmcross website : **freeze** at SplashScreen
- Lauch `StarWars` sample : **it works** ! 

Strange because StarWars like TipCalc samples use _MvvmCross 6.0_.

**Comment by jothedev** [comment]
@flyingxu there was no different at all. I even copied the codes from the template to my `SplashActivity.cs` and it still freeze there.

**Comment by Cheesebaron** [comment]
Please continue in #2957

**Comment by elucidsoft** [comment]
#3209 #3221
