### ISSUE TITLE
[Android] 6.1 hangs on splash screen

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2955]
### Steps to reproduce :scroll:

1. Run Playground.Droid

2. RootViewModel is never shown. The splash screen remains up forever.

I have to enable all Exceptions in "Exception Settings" to see the following exception:

System.NullReferenceException: Object reference not set to an instance of an object. occurred

The NRE is happening [here](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/MvxSetup.cs#L307) because `assembly` is null.

### Expected behavior :thinking:
The RootViewModel should show.

### Actual behavior :bug:
The splash screen remains on the screen forever.

### Configuration :wrench:

**Version:** 6.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by borbmizzet** [comment]
I'm getting the same issue with my MvxForms Droid app after bumping to 6.1.  The last trace message I get is `[TRACE] (MvvmCross.Core.MvxSetup) Setup: PluginManagerFramework start`, after which it just hangs.

**Comment by Plac3hold3r** [comment]
The issue seems to be with the [`Assembly.GetExecutingAssembly()`](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/MvxSetup.cs#L289).

> The [GetEntryAssembly](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=netframework-4.7.2#System_Reflection_Assembly_GetEntryAssembly) method can return null when a managed assembly has been loaded from an unmanaged application. For example, if an unmanaged application creates an instance of a COM component written in C#, a call to the GetEntryAssembly method from the C# component returns null, because the entry point for the process was unmanaged code rather than a managed assembly.

This is the case with Xamarin Android and iOS. We will need to find an alternative way to get the platform application assembly.

**Comment by Cheesebaron** [comment]
Please continue in #2957
