### ISSUE TITLE
Binding stop working after upgrade from 6.0.1 to 6.1.1 on Xamarin.Forms

### ISSUE THREAD

**Issue by arkadiuszokon** [MvvmCross/MvvmCross#2960]
After upgrading from 6.0.1 to 6.1.1 Bindings stop working in cells, tabs and carousel generally in places where bindings was not declared directly like in viewModel<T> but instead set automatically like collection item in cell or parent view model in MvxCarouselView. It's possible that I use sometimes Binding provided by xamarin.forms instead of mvx:Bind, but after changing - nothing happend. When I set ViewModel property manually - binding works fine. 

### Steps to reproduce :scroll:

1. Create MvxViewModel with associated View with MvxListView. 

2. ViewModel has Property with MvxObservableCollection<T> binded to list and I use MvxViewCell (in separate file) to render it. 

### Expected behavior :thinking:
Binding works like before

### Actual behavior :bug:
Binding not working, I override properties with DataContext, BindingContext, ViewModel in cell class - no getter or setter was called only OnBindingContextChanged several times. 

[TRACE] (MvvmCross.Logging.MvxLog) No view model association found for candidate view MyMvxViewCell
[TRACE] (MvxForms) No ViewModel class specified for MyMvxViewCell in LoadViewModel
[WARN]  (MvvmCross.Logging.MvxLog) ViewModel not loaded for view MyMvxViewCell

### Configuration :wrench:

**Version:** 6.1.1

**Platform:** 

- [x] :monkey: Xamarin.Forms

**Comment by borbmizzet** [comment]
The ViewModel property is now bindable from Xaml.  However, now binding to an MvxForms view's BindingContext in the application layer is now broken (demonstrated [in this PR](https://github.com/MvvmCross/MvvmCross/pull/2959).
@martijn00 I know you were trying to look into this.  Did you come up with anything?

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2959
