### ISSUE TITLE
MvxFormsAppCompatActivity.OnBackPressed assumes the standard Forms page presenter is being used

### ISSUE THREAD

**Issue by pdonovan** [MvvmCross/MvvmCross#2965]
### Steps to reproduce :scroll:

1. Override MvxFormsAndroidSetup.CreateFormsPagePresenter() e.g:

    protected override IMvxFormsPagePresenter CreateFormsPagePresenter(IMvxFormsViewPresenter,viewPresenter)
    {
        IMvxFormsPagePresenter formsPagePresenter = new MyFormsPagePresenter(viewPresenter);
        Mvx.RegisterSingleton(formsPagePresenter);
        return formsPagePresenter;
    }

2. Press the Android back button

3. App crashes

### Expected behavior :thinking:
The app should not throw an exception in `MvxFormsAppCompatActivity.OnBackPressed()`

### Actual behavior :bug:
The app crashes because it assumes that MvxFormsPagePresenter has been registered with the IoC container.

### Configuration :wrench:

**Version:** 6.1.1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

I would have thought that `var presenter = Mvx.Resolve<IMvxFormsPagePresenter>();` would be the change to fix this. As a workaround I will implement my own copy of `OnBackPressed()`

**Comment by CarLoOSX** [comment]
Posible reopened in 6.2.3 ?? 

Having the same behavior.
