### ISSUE TITLE
Xamarin Forms: Android white screen

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [MvvmCross/MvvmCross#2974]
Hi, I installed MvvmCross in the project Xamarin.Forms. UWP works, but Android shows a white screen and nothing more. I can not find the error and men need help.
Here is project: https://github.com/FotalGoncharuk/MvvmCross-Issue

**Comment by FotalGoncharuk** [comment]
Hey, I found a problem or it's just a naming convention
If you delete MainPage.xaml and just create a page with a different name, then the white screen on Android disappears (just try not to create a page called Main) Again, I repeat that this happens only on Android, everything is normal on UWP.
Does anyone know what this is and why it happens?

**Comment by benbishop** [comment]
@FotalGoncharuk Thank you so much for posting this issue and initial solution. I was literally running into this same issue/behavior yesterday. Once I changed my initial screen from MainView to LoginView it worked as expected on Android.

I did a quick look in the view presenter Android and Forms and nothings jumped out at me...

**Comment by benbishop** [comment]
Hi @martijn00 - I saw you closed this. Is there any insight why naming a view "MainView" causes Android to not work?

**Comment by nmilcoff** [comment]
@benbishop Do you also have a ViewModel named `MainViewModel` and a page named `MainPage`? If that's the case, then the problem is caused by the convention rule MvvmCross uses to map ViewModels <-> Views.
