### ISSUE TITLE
Mvvmcross Android ignores IMvxAsyncCommand on some standard control's events

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2977]
When using a command binding in an axml file, if the viewmodel property is an IMvxAsyncCommand, mvvmcross still calls Execute() of IMvxCommand instead of ExecuteAsync().

This happens at least for:
- MvxListView.OnItemClick
- MvxViewClickBinding.ViewOnClick

Sample axml file:

    <Button app:MvxBind="Click SomeCommand" ... />

Sample viewmodel

    IMvxAsyncCommand SomeCommand => ...

**Comment by martijn00** [comment]
Can you make a PR to fix this?

**Comment by martijn00** [comment]
@softlion Can you open a PR for this?

**Comment by softlion** [comment]
After some time experiencing with this issue, you can not fix it for every command binding, as some commands are from Xamarin code and some others can not be asynchronous.

So best bet is to close it.
