### ISSUE TITLE
Xamarin.Forms MvvmCross: Resolve IMvxMessenger in UI project

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [MvvmCross/MvvmCross#2979]
I downloaded the nuget package to display popups: https://github.com/rotorgames/Rg.Plugins.Popup

I have two .NetStandart: Core and UI projects. The UI has a dependency on Core. I need to show a pop-up window by calling it from the ViewModel.

And I create a class to subscribe to my messages:

```
public class PopupService : IPopupService
    {
        private IMvxMessenger _messenger;


        public static void Init()
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                var messenger = Mvx.Resolve<IMvxMessenger>();
                Mvx.RegisterSingleton<IPopupService>(() => new PopupService(messenger));
            });
        }

        public PopupService(IMvxMessenger messenger)
        {
            _messenger = messenger;

            _messenger.Subscribe<AlertPopupMessage>(async (message) => await AlertPopupCallbackAsync(message));
        }


        public async Task AlertPopupCallbackAsync(AlertPopupMessage message)
        {
            var alertPopup = new AlertPopup(message.PopupInfo);
            await PopupNavigation.PushAsync(alertPopup);
        }   
    }
```
Pay attention to the Init method. When I try to resolve IMvxMessenger, I get an MvvmCross.Exceptions.MvxIoCResolveException

UI.App.xaml.cs class:

```
public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

            PopupService.Init();
        }
    }
```
![rg](https://user-images.githubusercontent.com/30652592/41839264-70b30fe0-786b-11e8-9adc-584cdf30bf89.png)

**Comment by flyingxu** [comment]
Your version of MvvmCross ? v6.1 had a bug about the plugins, have a try with the latest version

**Comment by Goncharuk-Nikita** [comment]
MvvmCross version is 6.1.2. I moved the initialization of this service to the class of the first page. I know that it's terrible, but in another way he does not want to receive it

**Comment by nmilcoff** [comment]
@Goncharuk-Nikita Do you have the Messenger plugin also installed in your platform project?

**Comment by Goncharuk-Nikita** [comment]
Yes, I installed it in the Platform and UI projects. The fact is that App.xaml.cs from the UI project is launched first than App.cs from the Platform project

**Comment by nmilcoff** [comment]
I think this is happening because you're trying to resolve `IMvxMessenger` too early on your code, which isn't yet registered on the IoC container - and there is not much we are able to do to improve this.

I would suggest you to replace the line where you register your IPopupService for something like: 

```c#
Mvx.RegisterSingleton<IPopupService>(() => new PopupService(Mvx.Resolve<IMvxMessenger>()));
```

So that `IMvxMessenger` is resolved when the func is invoked.
