### ISSUE TITLE
Mvvmcross v6.1.2 Android - recyclerview custom adapter throwing error on scroll

### ISSUE THREAD

**Issue by nadeemshk** [MvvmCross/MvvmCross#2981]
I am using mvvmcross for xamarin android app. In this app I am using MvxRecyclerView and has created custom adapter for it.

In Activity I am binding this adapter to recycler view as follow - 

    protected override void OnCreate(Bundle bundle)
    {
        base.OnCreate(bundle);
        recyclerview = (MvxRecyclerView)FindViewById(Resource.Id.mvxRVList);
        GridLayoutManager gridLayoutManager = new GridLayoutManager(this, 3);
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
        recyclerview.SetLayoutManager(isLandscape ? (LinearLayoutManager)linearLayoutManager : gridLayoutManager);
        globalRetailItemAdapter = new CustomAdapter(isLandscape, this, (IMvxAndroidBindingContext)BindingContext);
        recyclerview.NestedScrollingEnabled = true;
    }

 **Adapter :**
    
    public class CustomAdapter : MvxRecyclerAdapter //,ISectionIndexer
    {
        Context context;
        bool isLandscape;
        public CustomAdapter(bool isLandscape, Context context, IMvxAndroidBindingContext bindingContext)
            : base(bindingContext)
        {
            this.context = context;
            this.isLandscape = isLandscape;
        }

        public override ViewHolder OnCreateViewHolder(ViewGroup parent, int viewType)
        {
            View itemView;

            if (viewType == 0)
            {
                itemView = LayoutInflater.From(parent.Context).Inflate(Resource.Layout.sectionHeaderTemplate,parent,false);
                return new ItemViewHolderForHeader(itemView, this.BindingContext);
            }
            else
            {
                itemView = LayoutInflater.From(parent.Context).Inflate(Resource.Layout.productlistviewitem, parent, false);
                return new ItemViewHolder(itemView, this.BindingContext);
            }
        }
        public override int GetItemViewType(int position)
        {
            var item = GetItem(position);
            if (item is RetailItemSectionHeader)
                return 0;
            return 1;
        }
        public override void OnBindViewHolder(ViewHolder holder, int position)
        {
            try
            {
                int type = GetItemViewType(position);
                var item = GetItem(position);
                if (type == 0)
                {
                    RetailItemSectionHeader header = (RetailItemSectionHeader)item;//items[position]
                    ItemViewHolderForHeader viewHolder = (ItemViewHolderForHeader)holder;
                    viewHolder.tvItemPrice.Text = header.headerTitle;                   
                }
                else
                {
                    RetailItem retailItem = (RetailItem)item;//items[position]
                    ItemViewHolder viewHolder = (ItemViewHolder)holder;                    
                    viewHolder.tvProductItemName.Text = retailItem.Title;
                    viewHolder.tvItemQuantity.Text = Convert.ToString(retailItem.quantity);
                    viewHolder.tvItemPrice.Text = Convert.ToString(retailItem.Price);                    
                }
            }
            catch(Exception e)
            {

            }
        }
    }

**Viewholders** : 

    public class ItemViewHolder : MvxRecyclerViewHolder
    {
        public TextView tvProductItemName, tvItemPrice, tvItemQuantity;
        public LinearLayout llTemplate;
        public RelativeLayout rlTemplate;
       
        public ItemViewHolder(View itemView, IMvxAndroidBindingContext context)
            : base(itemView, context)
        {
            tvProductItemName = (TextView)itemView.FindViewById(Resource.Id.tvProductItemName);
            tvItemPrice = (TextView)itemView.FindViewById(Resource.Id.tvItemPrice);
            tvItemQuantity = (TextView)itemView.FindViewById(Resource.Id.tvItemQuantity);
            llTemplate = (LinearLayout)itemView.FindViewById(Resource.Id.lvItemTemplate);
            rlTemplate = (RelativeLayout)itemView.FindViewById(Resource.Id.rlItemTemplate);
        }
    }
    public class ItemViewHolderForHeader : MvxRecyclerViewHolder
    {
        public TextView tvItemPrice;

        public ItemViewHolderForHeader(View itemView, IMvxAndroidBindingContext context)
            : base(itemView, context)
        {
            tvItemPrice = (TextView)itemView.FindViewById(Resource.Id.tvItemPrice);
        }
    }

My view is rendering properly but I am getting error when I try to scroll on list. Below is error description that I am getting - 

> Unhandled Exception:

> Java.Lang.IndexOutOfBoundsException: Inconsistency detected.
  Invalid item position 14(offset:14).state:166 mvvmcross.droid.support.v7.recyclerview.MvxRecyclerView{2799f2df VFED.V.. ........ 0,0-434,530 #7f0900f9 app:id/mvxRVList}, adapter:md569c8f30ad557d7c02673e279425d47a7.CustomAdapter@29fb04f0, layout:android.support.v7.widget.GridLayoutManager@111878a2, context:md5a2c5b2e78f64efe650e82df8fe55ec57.HomeView@2c470d5e occurred

Edited
After debugging through each part I found that at one part i.e. at position 14 Itemsource becomes null and GetItem(positon) is returning null. 

If anybody can explain why it is happening?

Any help will be highly appreciated.

**Comment by Strifex** [comment]
This error can happen with a normal MvxRecyclerView if you attempt to "Reset" the collection, even if you don't have a custom adapter.  For example, in my project I have an MvxObservableCollection bound to an MvxRecyclerView (nothing custom).  When I call .ReplaceWith() on my MvxObservableCollection, if I'm scrolling, the underlying recyclerview will crash with the same message.  It appears that "reset" events (clear or replacewith as good examples) trigger a "NotifyDataSetChanged" in the underlying RecyclerView which can cause it to crash during scrolling....if you add/remove/modify individual items in your data-bound collection you should be able to avoid this error, even if you're scrolling because they trigger specific events about what individual item changed.  I wish i had more information, but this is as far as I've been able to dig since I also experienced this issue...

**Comment by nadeemshk** [comment]
Where shall I write NotifyDataSetChanged? Actually I am newbie in Mvvm and dont know much about it. I tried writing NotifyDataSetChanged in OnCreate as - globalRetailItemAdapter.NotifyDataSetChanged(); but it didn't worked. Can you please me by mentioning some more details according to my code and yes thank you so much Strifex for your comment.

**Comment by Strifex** [comment]
You don't need to write that....if you want to know the details of the underlying code just take a look at the mvxrecycleradapter source code.  Personally I don't have a need to write a custom adapter as I just use the default adapter which supports databinding, my viewmodel has mvxobservablecollection which handles signalling collection changed events to the adapter.  I would study the source code if you are going to write a custom adapter built on top....

**Comment by nadeemshk** [comment]
I changed my observablecollections into mvxobservablecollection  but still facing the problem.

I have used custom adapter because I have 2 different types of view. One Group header and another is item itself. Also I have used SpanSizeLookup as below which I forgot to mention in above code.

`       public class MyGridLayoutManagerSpanSizeLookup : SpanSizeLookup
        {            
            public MyGridLayoutManagerSpanSizeLookup(CustomAdapter adapter)
            {
            }
            public override int GetSpanSize(int position)
            {
                if (globalRetailItemAdapter.GetItemViewType(position) == 0)
                {
                    // return the number of columns so the group header takes a whole row
                    return 3;
                }
                // normal child item takes up 1 cell
                return 1;
            }
        }`

And inside OnCreate it is - 

`gridLayoutManager.SetSpanSizeLookup(new MyGridLayoutManagerSpanSizeLookup(globalRetailItemAdapter));`

Thanks a lot Strifrex for your immediate comment.

**Comment by Cheesebaron** [comment]
Instead of using a custom adapter, you can use a ItemTemplateSelector for this.

**Comment by iqbalmineraltown** [comment]
@nadeemshk you can implement multiple types of view using `IMvxTemplateSelector`
then set it as recyclerview's `ItemTemplateSelector` as @Cheesebaron said
no need to create custom adapter and viewholder 😄 

about your error, I've encountered similar messages when trying to lazyload entries
I solved it by calling `NotifyDataSetChanged` on UIThread whenever new entries loaded into `ItemSource` binding

**Comment by nadeemshk** [comment]
Awesome! Great! Thank you all of you guys. Using IMvxTemplateSelector worked for me. I didn't even needed custom adapter for it. 

Thank you all.
