### ISSUE TITLE
Get rid of Framework API versions of Activities, Fragments and Adapters.

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#2990]
## 🏗 Enhancement Proposal
Switch all Activities, Fragments and related parts to Support package versions

### Pitch
I have suggested this previously and now I want to suggest it again. I don't see a reason to keep maintaining multiple versions of Activities, Fragments and Adapters on Android. The majority of Apps will be using Android Support packages anyways since compatibility is so much better and you get rid of all the fragmentation that the Framework API has.
Android is moving even more forward with moving all these things out of the Framework in future versions of Android and their evolution of Android Support packages, AndroidX.

Most of the google tooling assumes that you are using Support packages anyways. So my suggestion is that MvvmCross for Android takes a hard dependency on Support packages and gets rid of some of the redundancy we have in our MvvmCross.Droid.Support packages.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by kjeremy** [comment]
Makes sense to me.

**Comment by nickrandolph** [comment]
I think this sounds reasonable too.

**Comment by kjeremy** [comment]
This may enable some interesting opportunities like simplifying the layout inflater and possibly using `android.arch.lifecycle`

**Comment by projectgoav** [comment]
Any idea when this might be tackled? 

Fragments, Fragmenet managers and other related classes are now all marked as obselete in Xamarin.Android. The official Google API docs also tell of the deprecation of many fragment classes. 

https://developer.android.com/reference/android/app/FragmentManager

**Comment by Cheesebaron** [comment]
I think this will be for a major overhaul of the types in MvvmCross when we also switch to Android X. We are still waiting for some official Android X packages from Xamarin.

**Comment by pkhandelwal-cdl** [comment]
I noticed this was on the [roadmap](https://github.com/MvvmCross/MvvmCross/projects/8#card-33069217) for Mvx 7.0!

Any estimate on when to expect the first pre-release versions for 7.0? We are kicking off a new project in the next 2 weeks and definitely want to be able to take advantage of AndroidX and would love to be able to use MvvmCross as well.

**Comment by martijn00** [comment]
@pkhandelwal-cdl you can always grab the alpha packages from myget.

**Comment by Cheesebaron** [comment]
Github packages and myget have the latest build with this included.
