### ISSUE TITLE
Remove obsolete warning "activity request code may clash with Mvx code for"

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2993]
## 🏗 Enhancement Proposal

In MvvmCross/Platforms/Android/Views/MvxActivityAdapter.cs, method EventSourceOnStartActivityForResultCalled:

```csharp
            var requestCode = MvxValueEventArgs.Value.RequestCode;
            switch (requestCode)
            {
                case (int)MvxIntentRequestCode.PickFromFile:
                    MvxLog.Instance.Warn("Warning - activity request code may clash with Mvx code for {0}",
                                   (MvxIntentRequestCode)requestCode);
                    break;
            }
```

As the picture picker plugin has been removed, this warning should be removed too.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
The PictureChooser plugin is still alive, so there is apparently no reason to remove the warning. Please reopen the issue if you think something needs to be done.
