### ISSUE TITLE
MvxMasterDetailPage menu does not close after navigation

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [MvvmCross/MvvmCross#2995]
## 🐛 Bug Report

If you are using MvxMasterDetailPage menu does not close after navigation

### Expected behavior
When you navigate to another page, the menu page automatically closes

### Reproduction steps
Create your own implementation of MvxMasterDetailPage, as in the project [Playground](https://github.com/MvvmCross/MvvmCross/tree/5.6.3/TestProjects/Playground)

[Stackoverflow Discussion](https://stackoverflow.com/questions/48980485/how-to-create-a-masterdetailpage-using-mvvmcross)

### Workaround
To fix it now you must paste this code in your navigation task before execute the navigation:
I add this code in RootPage.xaml.cs in ChildAdded event handler

```
if(Application.Current.MainPage is MasterDetailPage masterDetailPage)
{
    masterDetailPage.IsPresented = false; 
}
else if(Application.Current.MainPage is NavigationPage navigationPage && navigationPage.CurrentPage is MasterDetailPage nestedMasterDetail)
{
    nestedMasterDetail.IsPresented = false;
}
```

### Configuration

**Version:** 6.1.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@Goncharuk-Nikita would you be able to suggest a fix for this? (perhaps take a look at the implementation in the forms presenter)

**Comment by chinmaybehera** [comment]
Application.Current.MainPage - How to get this in ViewModels places in Core project as Xamarin.Forms not referenced. I have separate UI project
