### ISSUE TITLE
Email plugin doesn't send attachment on Android (Xamarin Forms)

### ISSUE THREAD

**Issue by Rajmund-Kormendi** [MvvmCross/MvvmCross#2999]
## 🐛 Bug Report

In a Xamarin Forms project, when I try to send an email with attachments on Android using MvvmCross.Plugin.Email, the attachments are showing up in the email app, but I don't receive them.

I tried it with a few apps (Gmail, BlueMail, Outlook, Best email) and it only worked with Outlook.
Gmail and Bluemail didn't send the attachments, Best mail sent them, but their sizes were 0 bytes (in the email app they had correct sizes).

### Expected behavior
Receive attached files, which are showing up in the email app used for sending the email.

### Reproduction steps
Call IMvxComposeEmailTaskEx.ComposeEmail with attachments on Android and send the email.
Check the email if it has attachments.
### Configuration

**Version:** 6.0.1, 6.1.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@Rajmund-Kormendi are you saying that the generated email appears in the Android email app, but they just don't send? Can you clarify?

**Comment by Rajmund-Kormendi** [comment]
@nickrandolph the generated email appears in the app with the attachments, but the received email doesn't contain the attached files.

**Comment by Cheesebaron** [comment]
Relates to #2988 
The plugin needs to implement a ContentProvider on Android in order for other apps to get files from it.

**Comment by shaikh123456** [comment]
In a Xamarin Forms project, when I try to send an email with attachments on Android using MvvmCross.Plugin.Email, the attachments are showing up in the email app, but I don't receive them.

**Comment by Cheesebaron** [comment]
Use Xamarin Essentials instead. This plugin is going to get removed.
