### ISSUE TITLE
MvxExpandableTableViewSource issue

### ISSUE THREAD

**Issue by linpake** [MvvmCross/MvvmCross#3000]
## 🐛 Bug Report

Creates iOS app (Single view app). Creates base structure for project, including
 table view source  inherited from MvxExpandableTableViewSource. At view controller, which uses created table view source, during binding next exception is thrown: "System.Reflection.AmbiguousMatchException: Ambiguous match found.". As soon as inheritance is removed from this component - the exception disappears. 

### Expected behavior

I attached a project in which I recreated the error.
[iOS ECL.zip](https://github.com/MvvmCross/MvvmCross/files/2176281/iOS.ECL.zip)

### Reproduction steps
Just run attached project.

### Configuration

**Version:** 11.1 and later.

**Platform:** 
- [x] :iphone: iOS

**Comment by andrechi1** [comment]
The error is produced in this line

_tableViewSource.GetType().GetProperty("ItemsSource");

I do not understand why this error has now occurred, when this is not touched from 2016.

**Comment by rshestakou** [comment]
Same problem here, are there any ideas of when it will be fixed?

**Comment by Cheesebaron** [comment]
I'll have a look later today if I can find the time.

I suspect that it is getting confused about the generic and non generic version of `ItemsSource`

**Comment by rshestakou** [comment]
@Cheesebaron Ok great, thanks, will wait for feedback on this one.

**Comment by anant-kaushik** [comment]
We have similar problem in the MvxAdapter<TItem>. If you want I can open a PR for this. https://github.com/MvvmCross/MvvmCross/blob/ca443597a074859588cc3fc4ea0610c32bd047f5/MvvmCross/Platforms/Android/Binding/Views/MvxAdapter.cs#L257
