### ISSUE TITLE
MvxAutoCompleteTextView PartialText never changes after initial setting

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#3008]
### Expected behavior
PartialText's binding should change when the user types

### Reproduction steps
Create MvxAutoCompleteTextView and bind PartialText.
Type some stuff.

### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Do any of you know the reason why the `ManualResetEvent` was added in the `MvxFilteringAdapter`? Commenting it out makes everything magically work again.

**Comment by kjeremy** [comment]
I think it was left over from an ancient slodge sample
