### ISSUE TITLE
Does MVVMCross have translucent bar?

### ISSUE THREAD

**Issue by carlosmacmar** [MvvmCross/MvvmCross#3010]
## 💬 Questions and Help

Hi, I would like to know if MVVMCross have any kind of method to turn the toolbar translucent, so I can see the picture behind it.

Thank you!

**Comment by Cheesebaron** [comment]
Please use [Slack #mvvmcross](https://xamarinchat.herokuapp.com/) or [StackOverflow](https://stackoverflow.com/questions/tagged/mvvmcross) for questions. Github is meant to be used for bugs and feature requests only.

That being said. Toolbars, navigation bars etc are all View concerns and are all up to you to handle. Turning a toolbar transparent is something you control in your Theme on Android.
