### ISSUE TITLE
Deadlock after configuration change in Xamarin.Forms

### ISSUE THREAD

**Issue by MartinZikmund** [MvvmCross/MvvmCross#3012]
## 🐛 Bug Report

I have discovered a deadlock issue that prevents MvvmCross.Forms from handling configuration changes on Android (but could prove problematic in other places as well, actually even in non-Forms projects).

### Expected behavior

When I put MvvmCross app in split view mode or freeform mode on Android, the app should reinitialize and work as expected.

### Actual behavior

When app is put in split view, initialization starts, but ends with a deadlock in `MvxAppStart` on [this line](https://github.com/MvvmCross/MvvmCross/blob/8c787b2ee6993476948ac3467f4ae839a6f8ccc1/MvvmCross/ViewModels/MvxAppStart.cs#L32).

### Reproduction steps

1. Run the Playground.Forms.Droid project
2. Open Task view on Android, and drag and drop the app into either the splitview mode or freeform mode
3. Observe that execution gets stuck after a few moments
4. Pause debugging and see that it waits on `StartAsync(hint).GetAwaiter().GetResult();` in `MvxAppStart`

### Investigation results

First and foremost - I have used `Forms` and splitview configuration change as an example, but I am quite confident that this issue can appear unexpectedly on other platforms as well.

Using `StartAsync(hint).GetAwaiter().GetResult();` is problematic because as soon as the execution hits an "actual" `await` which runs on different thread, UI thread enters `GetResult()` and waits for the result in blocking fashion. When the other thread finishes running and tries to return to the UI thread, it cannot do so, because `GetResult()` is already blocking it and hence creates a deadlock.

I have stepped through the code several times to pinpoint the actual location where this problem occurs and I have probably found it. In the first run we are okay, we get to [this line](https://github.com/MvvmCross/MvvmCross/blob/c6ef1953d022585df9fb0643d786c7f510c11b15/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L705)and because the `navigationRootPage` is `null`, it is created and the page is synchronously loaded.

The real trouble begins when configuration changes, app is reinitialized and execution again gets to [this line](https://github.com/MvvmCross/MvvmCross/blob/c6ef1953d022585df9fb0643d786c7f510c11b15/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L705). This time the situation is different, as `navigationRootPage` already exists, so we go to [this line](https://github.com/MvvmCross/MvvmCross/blob/c6ef1953d022585df9fb0643d786c7f510c11b15/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L719) and execute `await navigationRootPage.PushAsync(page, attribute.Animated);`. Now if you look into the Xamarin.Forms repo and find the implementation of this method, you can see that it will lead to `NavigationRenderer` and specifically [here where an animation on another thread is started](https://github.com/xamarin/Xamarin.Forms/blob/0b1400a5d852f2d54e0f9bec3ef3a01f5061ad02/Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs#L250) this is the actual cause of the deadlock in our Playground project.

If you want to cause the deadlock much more easily, you can just put `await Task.Delay(1000)` in the `StartAsync` method of `MvxAppStart`. The same situation will happen.

### Possible solutions

Instead of `GetAwaiter().GetResult()` use something like:

```
try
{
    await StartAsync(hint);
}
catch (Exception ex)
{
    MvxLog.Instance.ErrorException(ex.Message, ex);
}
```

The disadvantage here is that the execution of `Start` will no longer wait for the `StartAsync` to complete which can potentially cause issues.

The best solution would probably be to remove the synchronous `Start` method altogether, but that would require to ensure correct functionality on platforms like iOS which expect a `ViewController` to be present immediately after startup.

### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@MartinZikmund can you switch to using RunAppStartAsync added in 
 https://github.com/MvvmCross/MvvmCross/pull/2866
This should be available in the current betas of 6.2 (https://www.nuget.org/packages/MvvmCross/6.2.0-beta.2)

**Comment by MartinZikmund** [comment]
Awesome, will try that and report back

**Comment by MartinZikmund** [comment]
Oh, but it seems this is now only for apps with Splash screen, are there obstacles to implement it for non-splash apps as well?

**Comment by nickrandolph** [comment]
yes, because you need to load the first view synchronously. In the case of a splash screen app, the splash screen is show immediately, which meets the platform requirements for startup time. 
We need to investigate why Reset isn't being called, which would allow the startup sequence to run again.

**Comment by MartinZikmund** [comment]
Understood, that makes sense. I just don't understand which `Reset` are you referring to?

**Comment by nickrandolph** [comment]
https://github.com/MvvmCross/MvvmCross/blob/a12c58d90af10741def51ae84cf1c108b66c0e30/MvvmCross/ViewModels/MvxAppStart.cs#L56
