### ISSUE TITLE
App not starting properly when App is start via Activity

### ISSUE THREAD

**Issue by SOFSPEEL** [MvvmCross/MvvmCross#3014]
## 🐛 Bug Report
I have not been able to reproduce this bug in my development environment, but our production app are generating crash reports that Mvx.Resolve - i.e stuff that should resolve is returning null.

I know in Mvx 6.x the startup logic was changed and in particular I'm referring to this code here:
https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatActivity.cs

 ```
protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            ViewModel?.ViewCreated();

            if(!(this is IMvxSetupMonitor))
            {
                RunAppStart(bundle);
            }
        }

```

The above code to my understanding (from reading documentation etc.) is kind of a catch all to ensure that the app is started properly if not entering the app via Android splash screen, like for example if entering the app via a deep link.

So I have two concerns:

1. Since AppStart only runs **after** ViewCreated, a user of Mvx cannot safely do Mvx.Resolve when overriding VM.ViewCreated, so shouldn't ViewCreated be called after AppStart?

1. And here perhaps I'm not understanding this properly, but the following line of code implies the VM is instantiated, meaning the the VM's constructor has been invoked with ioc parameters, but if AppStart runs after ViewCreated then those ioc parameters won't be available yet. 
 
          `  ViewModel?.ViewCreated();`

### Expected behavior
That when I do an Mvx.Resolve in a vm in Android it should resolve if part of AppStart.

When starting via MvxSplashScreenAppCompatActivity this doesn't seem to be a problem.
But when start via Activity MvxAppCompatActivity, I think there could be problems

### Reproduction steps

Haven't figured this out yet.

### Configuration

**Version:** 6.0.1

**Platform:** 
- [x ] :robot: Android

**Comment by nickrandolph** [comment]
@SOFSPEEL have you been able to reproduce this? Can you try to reproduce it with the playground sample apps and submit a PR demonstrating this?

**Comment by nmilcoff** [comment]
@SOFSPEEL can you please add a stacktrace of the issue you're having in your PRD environment?

To answer your questions, AppStart runs when the framework is already initialized. If Mvx wouldn't be up and running, you wouldn't have a ViewModel attached to your View in the first place :)
