### ISSUE TITLE
Splash Screen Crashes on Android when Hard Back or Hard Home button hit 

### ISSUE THREAD

**Issue by SOFSPEEL** [MvvmCross/MvvmCross#3017]
## 🐛 Bug Report

Get following crash when splash activity is destroyed before MvxAppStart has started.

```
[Mono] Found as '__android_log_print'.
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] MvvmCross.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.ViewModels.IMvxAppStart
[MonoDroid]   at MvvmCross.IoC.MvxIoCContainer.Resolve (System.Type t) [0x00035] in <dcc1f804568a45a5accd2fb0ee5e5ebf>:0 
[MonoDroid]   at MvvmCross.IoC.MvxIoCContainer.Resolve[T] () [0x00000] in <dcc1f804568a45a5accd2fb0ee5e5ebf>:0 
[MonoDroid]   at MvvmCross.IoC.MvxIoCProvider.Resolve[T] () [0x00000] in <dcc1f804568a45a5accd2fb0ee5e5ebf>:0 
[MonoDroid]   at MvvmCross.Mvx.Resolve[TService] () [0x00006] in <dcc1f804568a45a5accd2fb0ee5e5ebf>:0 
[MonoDroid]   at MvvmCross.Platforms.Android.Views.MvxActivityViewExtensions.OnViewDestroy (MvvmCross.Platforms.Android.Views.IMvxAndroidView androidView) [0x00054] in <dcc1f804568a45a5accd2fb0ee5e5ebf>:0 
[MonoDroid]   at MvvmCross.Platforms.Android.Views.MvxActivityAdapter.EventSourceOnDestroyCalled (System.Object sender, System.EventArgs eventArgs) [0x00006] in <dcc1f804568a45a5accd2fb0ee5e5ebf>:0 
[MonoDroid]   at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)
[MonoDroid]   at MvvmCross.Base.MvxDelegateExtensions.Raise (System.EventHandler eventHandler, System.Object sender) [0x00003] in <dcc1f804568a45a5accd2fb0ee5e5ebf>:0 
[MonoDroid]   at MvvmCross.Droid.Support.V7.AppCompat.EventSource.MvxEventSourceAppCompatActivity.OnDestroy () [0x00000] in <29a9f9fbf702429ead5c8d2154990961>:0 
[MonoDroid]   at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatActivity.OnDestroy () [0x00000] in <29a9f9fbf702429ead5c8d2154990961>:0 
[MonoDroid]   at Android.App.Activity.n_OnDestroy (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <263adecfa58f4c449f1ff56156d886fd>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.51d3a767-5b17-4446-a707-44b377e6af70(intptr,intptr)
```

Here's why this happens, the following code in OnViewDestroy in https://github.com/MvvmCross/MvvmCross/blob/8fbc13caa44e08f3fe2eb3732f099ad534803b43/MvvmCross/Platforms/Android/Views/MvxActivityViewExtensions.cs calls Mvx.IoCProvider.Resolve<IMvxAppStart>(); but when the SplashScreen is paused (thereby pausing the app initialization), it is possible that the app is not initialized, and this crashes when the SplashScreen hits the OnViewDestroy

One way to fix this would be to change following Resolve to be a TryResolve.

 ```
var currentActivity = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>()?.Activity;
            if (currentActivity == null && view is Activity destroyedActivity && destroyedActivity.IsFinishing)
            {
                var appStart = Mvx.IoCProvider.Resolve<IMvxAppStart>();
                appStart?.ResetStart();
            }

```

### Reproduction steps

- Launch app from home screen
- Immediately upon seeing home screen select either Hard back or Hard home button
- expected: no crash, actual: crash

### Configuration

**Version:** 6.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
Can you please submit a PR with the proposed fix

**Comment by nickrandolph** [comment]
Can you retest this against 6.2 beta please

**Comment by vinicius-queiroz93** [comment]
Can confirm this is happening in 6.1.2 as well. Crashes if Android app is minimized during the blank screen which appears before the Splash Screen (the blank screen is shown for about 3 seconds in our app).

**Comment by tbalcom** [comment]
This can still be reproduced in the current version of Playground.Droid. To reproduce start spamming the hard home button as soon as you see the splash screen. The suggested fix prevents the crash. Surrounding with `CanResolve<IMvxAppStart>()` condition also fixes it.

**Comment by nmilcoff** [comment]
Same issue as #2810. Is it possible for any of you to kindly raise a PR? It seems like you got it and all that is needed is to actually apply the change in the source code :)
