### ISSUE TITLE
Error building MvvmCross with Cake build script

### ISSUE THREAD

**Issue by asterixorobelix** [MvvmCross/MvvmCross#3022]
## 💬 Questions and Help

I have just cloned the MvvmCross repo to my machine. I am trying to build the project with the Cake script provided but I am experiencing the MSB4057 error: The target "_GetRestoreSettingsPerFramework" does not exist in the project.
![capture](https://user-images.githubusercontent.com/20531795/43038239-0d1a0a50-8d16-11e8-8f4a-eda5cad5ce1b.PNG)
Can anyone point me to how to get the Cake build script to run with debugging symbols attached, so that I can step through the code in Visual Studio 15.7?

**Comment by Cheesebaron** [comment]
That is strange, `_GetRestoreSettingsPerFramework` should be there as long as you use MSBuild, which the cake script does. This Property comes from NuGet.targets

I've just tried building on my own machine running latest stable 15.7 (15.7.180.61344) and preview 15.8 (15.8.139-preview+g5951330944) and have no issues with either of them.

**Comment by asterixorobelix** [comment]
Thanks @Cheesebaron I just got the repo to build on my work machine with the Cake script. So, it must be my environment on the home machine... What I can do about that, I dont know.. I uninstalled and reinstalled visual studio at home and was still getting the same errors

**Comment by Cheesebaron** [comment]
@asterixorobelix if you can show the setup you have in the VS installer, that could help us narrow down the issue.

**Comment by asterixorobelix** [comment]
Thanks @Cheesebaron does anything look incorrect about my environment in the attached pics? I have also installed the .NET Core 2.1 SDK.
![capture](https://user-images.githubusercontent.com/20531795/43147880-646a0242-8f64-11e8-91a8-948dc7c053f1.PNG)
![capture1](https://user-images.githubusercontent.com/20531795/43147900-6d35f9a8-8f64-11e8-87d9-df83c3bb3975.PNG)

**Comment by Cheesebaron** [comment]
Under individual components which .NET Frameworks do you have installed? Is 4.7 installed?

**Comment by asterixorobelix** [comment]
Hi @Cheesebaron yes, Microsoft .NET Framework Version 4.7.02556

I have attached environment setup file, will generate one for work pc tomorrow and will compare them to see if there are differences
[HomeEnvironmentSetup.txt](https://github.com/MvvmCross/MvvmCross/files/2232800/HomeEnvironmentSetup.txt)

**Comment by Cheesebaron** [comment]
Does building in Visual Studio work?

**Comment by nickrandolph** [comment]
@asterixorobelix building in VS should work in both 15.7 and 15.8 (preview), although I've found that the latter seems to be more stable, despite being in preview. Unfortunately often it's not as easy as just opening mvvmcross.sln and hitting F5 to run. I suggest forcing a build on Mvvmcross, the Android AppCompat library, Mvvmcross.Forms and then whichever playground project you want to run.
Also, if you're only looking at one platform, I would suggest adjusting the Directory.build.props to pick which platform you want to build - this will give you a massive perf gain when building projects.

eg to build and run only Android, use the following:
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    
     <TargetsToBuild>Android</TargetsToBuild> 
     
     
  </PropertyGroup>

**Comment by asterixorobelix** [comment]
Thanks for the idea @nickrandolph :exclamation: Ive just installed the 15.8 preview and whichever gremlins were in 15.7 are now no longer in the neighbourhood.. Finally. Many thanks to both of you @nickrandolph  @Cheesebaron :bow:

**Comment by FinHorsley** [comment]
I'm getting the same error on the latest VS4Mac (8.3 build 1805)

`dotnet --version`
2.2.402

![image](https://user-images.githubusercontent.com/10697741/65690099-41fe9480-e066-11e9-829e-ecc6d94234cc.png)

**Comment by Cheesebaron** [comment]
You have an old dotnet version. Get latest 3.0
