### ISSUE TITLE
NavigationService Close doesn't respect Viewmodel Parameter in forms and always pop latest page

### ISSUE THREAD

**Issue by abdomh** [MvvmCross/MvvmCross#3029]
## 🐛 Bug Report

Calling close in navigation service with ViewModel instance always pops the latest page

I did some digging and found out that every call to `ClosePage` in `MvxFormsPagePresenter` sets the expected page to close to null instead of finding the page, which triggers `PopAsync`
[https://github.com/MvvmCross/MvvmCross/blob/6.1.2/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L647](https://github.com/MvvmCross/MvvmCross/blob/6.1.2/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L647)

I could be wrong but this is what I think where the issue is.

### Expected behavior
Close the passed ViewModel instance only or return false if not possible

### Reproduction steps
Add two view models
set ViewModelA to be the default page
Navigate to ViewModelB
Close ViewModelA (will close ViewModelB insted)

### Configuration

**Version:** 6.x
6.1.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@AbdelrahmanGIT are you able to propose a fix as a PR for review?

**Comment by AbdelrahmanGIT** [comment]
I will take a look at it
