### ISSUE TITLE
Have to work out how to make Json.Net import easier

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#304]
Having played with Jabbr and SignalR, it seems like Json.Net versions will be a challenge in the future.

I think the Json plugin is small enough that people can get away with dropping it and implementing their own versions... but I can see that different versions are going might be a challenge in the future :/

It may even just be as simple as giving people guidance about how to force a dll into a UI package.

Looks like Json Nuget support would be good for us

**Comment by martijn00** [comment]
This doesn't seems to be an issue anymore for me: https://www.nuget.org/packages/Newtonsoft.Json/
A separate issue can be made for implementing ServiceStack.Text if needed.
