### ISSUE TITLE
Google Sign in IdToken null with MvxAppCompatActivity

### ISSUE THREAD

**Issue by RomaRudyak** [MvvmCross/MvvmCross#3040]
## 🐛 Bug Report

When integrating GoogleSignin into Android application with `RequestIdToken` configuration for Sign-in and passing `MvxAppCompatActivity` as Context parameter `IdToken` fo GoogleSigninAccount is `null`.
When changing to `AppCompatActivity` IdToken retrieved.

### Expected behavior
IdToken must be retrieved when passing MvxAppCompatActivity as Context for GoogleSignin.

### Reproduction steps
1. Create Android project
2. Create appropriate project for it in [Firebase console](https://github.com/CrossGeeks/GoogleClientPlugin/blob/master/GoogleClient/docs/GoogleFirebaseConsoleSetup.md)
3. Setup project with MvvmCross 6.1.2
4. Configure GoogleSignin to RequestIdToken

### Configuration

**Version:** 6.1.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@RomaRudyak are you able to create a PR that reproduces this issue - please use the Playground sample. Leave a placeholder for where the Firebase account information should be added.

**Comment by RomaRudyak** [comment]
@nickrandolph Please close this issue ass when I was creating sample project for you to reproduce all works, I have issues in my specific project. 
Thank you for your time.
