### ISSUE TITLE
[Android] Setup initialization issue when Xamarin.Forms Android app terminated and resumed

### ISSUE THREAD

**Issue by huszarg** [MvvmCross/MvvmCross#3041]
## 🐛 Bug Report

Usually the MvvmCross setup is initialized during the splash screen on Android. If an app is terminted by the Android OS and after that try to resume the app it will not load and only a white screen will appear so an empty activity.

### Expected behavior
Resume and initialize app when it is foreground again.

### Reproduction steps
The issue can be reproduced with any Xamarin.Forms Android app if you set the "Background process limit" to "No background processes" in Developer options menu on Android.

- Run the app
- Press the home button to send application to background
- Press the recents apps button and select the app
- The app will not load only a white screen will appear

### Configuration

- Xamarin.Forms 2.5.0 or higher
- MvvmCross 5.6.3 or higher

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
I tried to reproduce this issue in the `Playground.Forms.Droid` project but everything worked just fine. 

After the app was sent to background I even tried opening a different app, just to ensure the playground app was tombstoned... Some time later I selected the playground app on the task manager and a white screen appeared for some seconds. But in the end correct content was loaded correctly.

I would say we need more information to be able to tell whether we need to take any action here. Also a minimal reproducible case is highly appreciated.

**Comment by huszarg** [comment]
I also can reproduce this issue in the Playground.Forms.Droid project (release 5.6.3 version). The white screen appeared but the content wasn't loaded.
The important step to reproduce is the Developer options setting on Android: Settings -> Developer options -> Limit background processes -> No background processes.

The basic steps to reproduce after the above settings:

- Run the Playground.Forms.Droid app and wait until the content is loaded
- Press the home button to send it to background
- Open an other app
- Press the home button
- Press the recent apps button and select the Playground.Forms.Droid app
- Only a white screen will appear but the content will not load

**Comment by nickrandolph** [comment]
@vatsalyagoel are you able to investigate this and see if you can reproduce the issue in the playground sample?

**Comment by vatsalyagoel** [comment]
Hi @nickrandolph I was able to reproduce and solve the issue by following the steps above. 

The issue happens because the app is not launching form SplashScreen but rather from MainActivity. This causes Mvx to not know where to go once the main activity is launch since the setup in MainActivity is not defined. I was able to get around this by adding setup in both MvxFormsSplashScreenActivity and MvxFormsAppCompatActivity. This doesn't affect launch times as setup.ensureinitialized() makes it so that the setup isn't called twice. 

another way of fixing the issue is ditching the SplashScreen all together in the app and making MainActivity as the main launcher. If the user still wants to keep the splash screen set the splashscreen theme as the theme for the MainActivity the in the oncreate method reset the theme to the orginal theme.

Sample: 
```
    [Activity(Label = "My Cairns", 
        Icon = "@drawable/icon",
        Theme = "@style/MyTheme.Splash",
        MainLauncher = true,
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation, 
        LaunchMode = LaunchMode.SingleTask)]
  public class MainActivity : MvxFormsAppCompatActivity<Setup, Core.App, FormsApp>
{

protected override void OnCreate(Bundle bundle)
        {
            Window.RequestFeature(WindowFeatures.ActionBar);
            SetTheme(Resource.Style.MyTheme);
            base.onCreate(bundle);
}
}
```

**Comment by goldnarms** [comment]
We are also facing the "White screen of death" issue. Tried ditching splashscreen as suggested which looked promising at first, but led to a crash.

**Comment by Mookker** [comment]
Hi guys, any news about this one?

**Comment by Cheesebaron** [comment]
@Mookker no, but do you want to look at it?
