### ISSUE TITLE
Build error in VS on Windows: The target "GetBuiltProjectOutputRecursive" does not exist in the project.

### ISSUE THREAD

**Issue by markuspalme** [MvvmCross/MvvmCross#3043]
## 💬 Questions and Help

I have cloned the latest revision of the "develop" branch and want to run Playground.iOS. However, I get this build error in various projects and can't make sense of it.

`The target "GetBuiltProjectOutputRecursive" does not exist in the project.`

![build errors](https://user-images.githubusercontent.com/1481801/43357772-f1e739b2-9286-11e8-83ea-e5068c3537d4.png)

I'm on VS 17.7.5 and Xamarin 4.10.10.2.

Any ideas? I would really like to work on https://github.com/MvvmCross/MvvmCross/issues/2518 but this problem keeps me from it.

**Comment by nmilcoff** [comment]
Did you check this? -> https://developercommunity.visualstudio.com/comments/256431/view.html

**Comment by markuspalme** [comment]
@nmilcoff Thanks, that fixed the problem! Didn't find that myself on Google.
