### ISSUE TITLE
Make MvxApplicationCallbacksCurrentTopActivity.cs:_Activities protected to facilitate extension

### ISSUE THREAD

**Issue by daividssilverio** [MvvmCross/MvvmCross#3048]
## 🏗 Enhancement Proposal

It would be nice to have the visibility of backing list of activities used on the `MvxApplicationCallbacksCurrentTopActivity.cs` changed to `protected` to make changes and tweaks 

https://github.com/MvvmCross/MvvmCross/blob/9952752bb98759dce7e05d11dde4dc5ebdf58f69/MvvmCross/Platforms/Android/Views/MvxApplicationCallbacksCurrentTopActivity.cs#L13

### Pitch
This would make easier to extend MvxApplicationCallbacksCurrentTopActivity.cs and add behaviour to a custom implementation.

For example, I could just extend MvxApplicationCallbacksCurrentTopActivity.cs and add a FindActivityByViewModel like I did here: https://github.com/toggl/mobileapp/blob/f6565ab2c58c2d308dee61e0970dfd780788bef6/Toggl.Giskard/Startup/QueryableMvxLifecycleMonitorCurrentTopActivity.cs#L52-L63

#### But why?
The fixes introduced here #2513 didn't fix the problem in the case I was working on. The CurrentActivity is not always updated correctly when closing ViewModels attached to Activities, so having protected property makes it easier and less messy to change the behaviour a bit.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Could you open a PR for this?

**Comment by daividssilverio** [comment]
Yes o/
