### ISSUE TITLE
Consider linking the view assembly registration with the default namespaces

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#306]
Need to be cautious about this - but this idea has just been discussed on jabbr

Could possibly mean one less configuration step for users importing controls

Also consider a bootstrap file to do this stuff too...

I think it's an 'optimisation' I put in
there's a view type cache to make axml inflation quicker
https://github.com/slodge/MvvmCross/blob/v3/Cirrious/Cirrious.MvvmCross.Binding.Droid/MvxAndroidBindingBuilder.cs#L132
Setup listens for that to be registered
https://github.com/slodge/MvvmCross/blob/v3/Cirrious/Cirrious.MvvmCross.Droid/Platform/MvxAndroidSetup.cs#L145
and then fills the cache with those assemblies
https://github.com/slodge/MvvmCross/blob/v3/Cirrious/Cirrious.MvvmCross.Droid/Platform/MvxAndroidSetup.cs#L158
would possibly be good to link the namespace list with the registered assemblies
will log as an issue

**Comment by nickrandolph** [comment]
@martijn00 I think we can close off this issue since we have some detection of view assemblies etc

**Comment by nickrandolph** [comment]
No feedback, so closing this issue
