### ISSUE TITLE
mvvmcross binding not working with android popup window

### ISSUE THREAD

**Issue by nadeemshk** [MvvmCross/MvvmCross#3068]
## 💬 Questions and Help
I am working android native app using **xamarin** and I'm using **mvvmcross** framework for it. My app works good but it is just **Pop window of android which does not bind to viewmodel**. 

Below is my code -

Contentview for popup window - 

*departmentpopupmenulist.axml*

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:local="http://schemas.android.com/apk/res-auto"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
        <FrameLayout
            android:layout_width="match_parent"
            android:id="@+id/departmentpopupview"
            android:layout_height="match_parent">
            <ImageButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="right"
                android:layout_marginRight="40dp"
                android:layout_marginTop="35dp"
                android:id="@+id/deptpopupbtncancel"
                android:background="@drawable/customer_popup_cancel" />
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginLeft="30dp"
                android:layout_marginRight="30dp"
                android:layout_marginTop="70dp"
                android:orientation="vertical">
                <SearchView
                    android:id="@+id/deptpopupsearch_view"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:iconifiedByDefault="false"
                    android:layout_gravity="center_horizontal"
                    local:MvxBind="Text SearchDepartmentParam" />
                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginBottom="50dp"
                    android:orientation="horizontal">
                    <FrameLayout
                        android:layout_width="match_parent"
                        android:layout_height="match_parent">
                        <MvxListView
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            local:MvxBind="ItemClick CategorySelectedCommand"
                            android:id="@+id/mvxLVDeptList" />
                        <LinearLayout
                            android:id="@+id/side_index_departmentList"
                            android:layout_width="20dp"
                            android:layout_height="fill_parent"
                            android:orientation="vertical"
                            android:layout_gravity="right"
                            android:background="@color/gray"
                            android:layout_marginTop="10dp" />
                    </FrameLayout>
                </LinearLayout>
            </LinearLayout>
        </FrameLayout>
    </LinearLayout>

Department popup window opens on button click. Code as below - 

    private void OpenDeptMenu_Click(object sender, EventArgs evtArgs)
    {
        PopupWindow popupWindow = new PopupWindow(this);
        View llFragment_layout = this.BindingInflate(Resource.Layout.departmentpopupmenulist, null);
        ListView lvDept = (ListView)llFragment_layout.FindViewById(Resource.Id.mvxLVDeptList);
        ImageButton ibCancel = (ImageButton)llFragment_layout.FindViewById(Resource.Id.deptpopupbtncancel);
        ibCancel.Click += delegate {
            if (string.IsNullOrEmpty(tvSubDepartmentProductList.Text))
            {

            }
            popupWindow.Dismiss();
        };
        departmentAdapter= new DepartmentAdapter(this.ApplicationContext, Resource.Id.tvItemName, ViewModel.DepartmentViewModel.DepartmentWithHeader.ToList());
        lvDept.Adapter = departmentAdapter;
        lvDept.NestedScrollingEnabled = true;
        lvDept.ItemClick += LvDept_ItemClick;
        popupWindow.ContentView = llFragment_layout;
        popupWindow.SoftInputMode = SoftInput.AdjustNothing;
        popupWindow.Focusable = true;
        Drawable drawable = this.GetDrawable(Resource.Drawable.departmentlistbackground);
        popupWindow.SetBackgroundDrawable(drawable);
        popupWindow.Height = drawable.IntrinsicHeight;
        popupWindow.Width = drawable.IntrinsicWidth;
        popupWindow.OutsideTouchable = false;
        popupWindow.Touchable = true;
        popupWindow.ShowAsDropDown(ibDepartment, 0, -80, GravityFlags.Right);
        LinearLayout linearLayoutSideIndex = llFragment_layout.FindViewById<LinearLayout>(Resource.Id.side_index_departmentList);
        displayIndexDept(linearLayoutSideIndex);
    }

My Viewmodel has **property SearchDepartmentParam as follow in Viewmodel**.
This Viewmodel is inherited with MvxViewModel and other properties in it binds to its control. It is only searchview of popup window not binding to viewmodel..

    public string SearchDepartmentParam
    {
        get { return _searchDepartmentParam; }
        set
        {
            _searchDepartmentParam = value;
            RaisePropertyChanged(() => SearchDepartmentParam);
            FilteredDepartmentResults();

        }
    }

**Comment by martijn00** [comment]
You need to use the `MvxAppCompatDialogFragment`: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatDialogFragment.cs

Also questions like this should go onto Stackoverflow, and therefore i will close it here.
