### ISSUE TITLE
Cannot use any MainWindow type other than MvxWindow

### ISSUE THREAD

**Issue by mgochmuradov** [MvvmCross/MvvmCross#3080]
## 🔙 Regression
I have started a new WPF project, and would like to use a custom Window type (for ex: RibbonWindow), before I had no issues with it, but now it seems that I have to use MvxWindow, for application to work.
I have tried just implementing IMvxWindow, on my MainWindow class, but this doesn't helped.

### Old (and correct) behavior
We could use any type of Window.

### Current behavior
We have to use MvxWindow

### Configuration

**Version:** 6.1.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Old behavior on what version of MvvmCross?
