### ISSUE TITLE
Proper implementation of UWP suspension

### ISSUE THREAD

**Issue by MartinZikmund** [MvvmCross/MvvmCross#3090]
## 🐛 Bug Report

MvvmCross currently does not handle UWP suspension app lifecycle properly.

When app goes into suspension,[ `MvxSuspensionManager` is used in `MvxApplication`](https://github.com/MvvmCross/MvvmCross/blob/bdaa09299714d94cf3f2c548a465d994c20d52f0/MvvmCross/Platforms/Uap/Views/MvxApplication.cs#L121) to store the current state of the app, including navigation:

```
private async void OnSuspending(object sender, SuspendingEventArgs e)
{
    var deferral = e.SuspendingOperation.GetDeferral();

    var suspension = Mvx.IoCProvider.GetSingleton<IMvxSuspensionManager>();
    await Suspend(suspension);
    await suspension.SaveAsync();
    deferral.Complete();
}
```

This behavior was the recommended one before Windows 10 version 1607, but currently the recommendation is to put suspension logic in `EnteredBackground` event handler, [as per docs](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle#app-suspend
):

> When an app is suspended, it invokes the Application.Suspending event. Visual Studio’s UWP project templates provide a handler for this event called OnSuspending in App.xaml.cs. Prior to Windows 10, version 1607, you would put the code to save your state here. Now the recommendation is to save your state when you enter the background state, as described above.

App run suspension in one of two ways - either user closes the app, or the app is either minimized or lock screen is on. In case of app close the app goes through suspension and then is immediately removed from memory by the system. In case of minimize, the documentation says the following:

> When the user minimizes an app Windows waits a few seconds to see whether the user will switch back to it. If they do not switch back within this time window, and no extended execution, background task, or activity sponsored execution is active, Windows suspends the app. An app is also suspended when the lock screen appears as long as no extended execution session, etc. is active in that app.

However, it is key to note, that suspension **does not mean** the app will necessarily be removed from memory. If the user switches back to a minimized app, it will continue running as it was and does not require any restore except for a possible refresh of the UI if the developer so chooses.

Here MvvmCross uses the wrong path - the suspended state is restored **only** when the [`Resuming` event is called in `MvxApplication`](https://github.com/MvvmCross/MvvmCross/blob/bdaa09299714d94cf3f2c548a465d994c20d52f0/MvvmCross/Platforms/Uap/Views/MvxApplication.cs#L136):

```
private async void OnResuming(object sender, object e)
{
    var suspension = Mvx.IoCProvider.GetSingleton<IMvxSuspensionManager>();
    await Resume(suspension);
    await suspension.RestoreAsync();
}
```

This means when the user switches back to the minimized app, it first restores the state. But that is not necessary at all, because the full app state is still in memory and there is no additional work required. Basically, suspension can be seen as a precautionary measure in case the system runs out of resources and needs to kill the app to free some up.

When the system kills a suspended app, when the user launches it or switches back to it, it will now go through the full launch lifetime, which you can [confirm here in docs:](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle#app-launch)

ApplicationExecutionState | Explanation | Action to take
-- | -- | --
Terminated | The app was previously suspended but was then shutdown at some point because the system needed to reclaim memory. | Restore the state that the app was in when the user switched away from it.
ClosedByUser | The user closed the app with the close gesture in tablet mode, or with Alt+F4. When the user closes the app, it is first suspended and then terminated. | Because the app has essentially gone through the same steps that lead to the Terminated state, handle this the same way you would the Terminated state.

In both **Terminated** and **ClosedByUser** execution states it is appropriate to restore the app state from suspended state because user expects to continue where he left off last time.

To fix the current behavior, I suggest the following:

1. **Move the suspension logic to the `EnteredBackground`** event handler to match the recommended approach
2. **Remove the `Resuming` handler** completely as it should be used only in case the developer needs to do some refresh of data or reacquire file handles
3. _Optionally_ implement restore in `OnLaunched` and `OnActivated`. This is optional because the better solution may just be to leave this up to the developer to decide if she wants to restore the state saved in suspension or not. This would give better flexibility to the developers using MvvmCross and would also preserve the current behavior which is that state is not restored.

### Expected behavior

When `EnteredBackground` event is called, `MvxSuspensionManager` is used to save current app state. When user switches to minimized app, no state is restored as the app is already fully in memory. If the app is terminated by the system in the meantime or if the user closes the app, app is restored from suspension manager if the app developer so chooses in `OnLaunched` and `OnActivated`.

For another example refer to [this UWP sample](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/BasicSuspension/cs/App.xaml.cs), which deals with suspension. Note that this is an older sample and does not use `EnteredBackground` yet.

### Reproduction steps

Create a basic MvvmCross UWP app and test different execution states in Visual Studio.

### Configuration

**Version:** 6.2, affects all versions

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Thank you for your comprehensive report @MartinZikmund. It seems like you have a very good idea what needs to be done to fix this issue. Would you be able to contribute a PR fixing this?

**Comment by mmangold7** [comment]
@MartinZikmund If you have any suggested changes beyond what I have done in the PR please let me know, I based it entirely off of what you said in this issue.
