### ISSUE TITLE
Cannot register two managed types

### ISSUE THREAD

**Issue by Corstiaan84** [MvvmCross/MvvmCross#3093]
Hi there,

I have three projects in my (1.5-year-old) solution:

1. Project.Core
2. Project.iOS
3. Project.Droid (not relevant for this issue)

Project.Core builds successfully but when building for device Project.iOS throws:

`/Project.iOS.iOS/MTOUCH: Error MT4116: Could not register the assembly 'Cirrious.MvvmCross.Binding.Touch': error MT4118: Cannot register two managed types ('Cirrious.MvvmCross.Binding.Touch.Views.MvxImageView, Cirrious.MvvmCross.Binding.Touch' and 'MvvmCross.Binding.iOS.Views.MvxImageView, MvvmCross.Binding.iOS') with the same native name ('MvxImageView'). (MT4116) (Project.iOS)`

By the looks of it somehow there is a package version mismatch between the two projects. I have quadruple checked the package versions of MvvmCross.Binding in both projects and both are on 4.4.0.

I also cleared the packages folder in de solution root and ran `restore packages` to no avail.

This is probably a "Doh!" kind of issues but I can't seem to get my finger behind it. Any ideas?

Thanks.

**Comment by Cheesebaron** [comment]
Check your references in the csproj files. Remove anything that is prefixed with Cirrious.
