### ISSUE TITLE
Remove `InternalsVisibleTo` or sign assemblies

### ISSUE THREAD

**Issue by jacodv** [MvvmCross/MvvmCross#3098]
## 🏗 Enhancement Proposal

Currently, the source has some InternalsVisibleTo attributes that expose some of the types only to other members of the solution.  Because these attributes only specify the assembly name you cannot sign the assemblies in the source code.

### Pitch
The suggestions are; either sign all assemblies and update the attributes to include the public key or remove the attributes.  The code is opensource and thus do not really require the internals and would rather have the types as public types

It will allow the signing of the source without any code changes, thus making it easier to keep in line with the master branch

### Platforms affected (mark all that apply)
MvvmCross Core
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
We currently use `InternalsVisibleTo` because of our internal logger classes. We are not going to sign the assemblies. So I guess the solution here would be to make them private instead.

**Comment by jacodv** [comment]
Thank you for the reply.

May I ask why you have an issue with signing the assemblies.  Signed assemblies can be used everywhere, as oppose unsigned assemblies that cannot be used in signed assemblies.  If it is effort vs your priorities on the backlog, then I can assist with a pull request.  The option is to create a signed and unsigned Nuget package.  See RestSharp and RestSharpSigned

In any case, what are the next steps from here?

Regards
Jaco


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nickrandolph** [comment]
> We currently use `InternalsVisibleTo` because of our internal logger classes. We are not going to sign the assemblies. So I guess the solution here would be to make them private instead.

but don't we sign the assemblies within the nuget package?

**Comment by Cheesebaron** [comment]
@nickrandolph ah right. I think the .NET Foundation Sign Client actually does that. I just opened up the new NuGet and I see the dlls are signed now. Not sure if that is enough? @jacodv can you please check with 6.2.0?

**Comment by jacodv** [comment]
Will do, thank you.  Can I revert on this thread with my findings later today?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Cheesebaron** [comment]
Yes, we will keep the issue open. Please do return with your findings 👍

**Comment by Cheesebaron** [comment]
@jacodv any status?

**Comment by jacodv** [comment]
@Cheesebaron , Sorry for the delay.  I got pulled into another project.  

We will be trying the new updates and see if we can get / use the signed assemblies.

**Comment by Cheesebaron** [comment]
Closing this issue as no feedback provided. Open a new issue referring to this one if this is still a problem for you.
