### ISSUE TITLE
MvxAndroidSetup cause Splash Screen crash (MvxAndroidApplication works fine)

### ISSUE THREAD

**Issue by SSElliott** [MvvmCross/MvvmCross#3099]
After a conversion of a Mvvm Cross 4.4.0 project (droid only with .net standard dll) I found it hangs on the splash screen.  To try and diagnose the problem I took the TipCalc project MainApplication.cs to use the same technique and  as my existing project....

 public class Setup : MvxAndroidSetup
    {
        protected override IMvxApplication CreateApp()
        {
            var x = new TipCalc.Core.App();
            return x;
        }

    }

....and got the same result,  it just hangs on the splash screen. I also tried to create a Custom AppStart which it got create, NavigateToFirstViewModel was never called.

It is tricky to move on to  MvxAndroidApplication<MvxAndroidSetup<App>, App> as I am using a Custom Presenter and need to return it in MvxAndroidSetup. 

Steven

**Comment by Cheesebaron** [comment]
Please use the bug report template.
