### ISSUE TITLE
Xamarin.Forms StarWarsSample stuck on SplashScreen after update to v6.2.0

### ISSUE THREAD

**Issue by valentasm1** [MvvmCross/MvvmCross#3104]
## 🐛 Bug Report

I just downloaded https://github.com/MvvmCross/MvvmCross-Samples/tree/master/StarWarsSample
Updated MvvmCross to v6.2.0 and app stoped to work. I use Xamarin.Forms version. It stuck on SplashScreen. Not really shure what is happening, but i think it should be related to log line (MvvmCross.Logging.MvxLog) No view model association found for candidate view RootActivity

Could be related to #3099 
Attached part of Debug

### Expected behavior
StarWarsSample sample runs with v6.2.0

### Reproduction steps
Download sample, update MvvmCross to v6.2.0.

### Configuration
Windows 10, Google Pixel 2, Visual Studio 17

**Version:** 6.2.0

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X ] :monkey: Xamarin.Forms

2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: ViewsContainer start
09-14 20:10:57.855 I/mono-stdout( 7699): 2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: ViewsContainer start
09-14 20:10:57.857 I/mono-stdout( 7699): 2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Views start
2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Views start
09-14 20:10:57.871 D/Mono    ( 7699): Image addref System.Runtime.Serialization[0x7e63cd7f80] -> System.Runtime.Serialization.dll[0x7e47a6a000]: 2
09-14 20:10:57.871 D/Mono    ( 7699): Prepared to set up assembly 'System.Runtime.Serialization' (System.Runtime.Serialization.dll)
09-14 20:10:57.871 D/Mono    ( 7699): Assembly System.Runtime.Serialization[0x7e63cd7f80] added to domain RootDomain, ref_count=1
09-14 20:10:57.873 D/Mono    ( 7699): AOT: image 'System.Runtime.Serialization.dll.so' not found: dlopen failed: library "/data/app/com.mvvmcross.star_wars_sample_forms-m_JmJJrF62bxc6NZPaZp3Q==/lib/arm64/libaot-System.Runtime.Serialization.dll.so" not found
09-14 20:10:57.873 I/Adreno  ( 7699): QUALCOMM build                   : 7bf2852, Ie32bfa6f6f
09-14 20:10:57.873 I/Adreno  ( 7699): Build Date                       : 06/03/18
09-14 20:10:57.873 I/Adreno  ( 7699): OpenGL ES Shader Compiler Version: EV031.24.00.00
09-14 20:10:57.873 I/Adreno  ( 7699): Local Branch                     : googdrp
09-14 20:10:57.873 I/Adreno  ( 7699): Remote Branch                    : 
09-14 20:10:57.873 I/Adreno  ( 7699): Remote Branch                    : 
09-14 20:10:57.873 I/Adreno  ( 7699): Reconstruct Branch               : 
09-14 20:10:57.873 I/Adreno  ( 7699): Build Config                     : S L 4.0.10 AArch64
09-14 20:10:57.873 D/Mono    ( 7699): AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/sdks/out/android-arm64-v8a-release/lib/mono/aot-cache/arm64/System.Runtime.Serialization.dll.so' not found: dlopen failed: library "/data/app/com.mvvmcross.star_wars_sample_forms-m_JmJJrF62bxc6NZPaZp3Q==/lib/arm64/libaot-System.Runtime.Serialization.dll.so" not found
09-14 20:10:57.874 D/Mono    ( 7699): Config attempting to parse: 'System.Runtime.Serialization.dll.config'.
09-14 20:10:57.874 D/Mono    ( 7699): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/sdks/out/android-arm64-v8a-release/etc/mono/assemblies/System.Runtime.Serialization/System.Runtime.Serialization.config'.
09-14 20:10:57.874 D/Mono    ( 7699): Assembly Ref addref Mono.Android[0x7e60873100] -> System.Runtime.Serialization[0x7e63cd7f80]: 2
09-14 20:10:57.874 D/Mono    ( 7699): Assembly Ref addref System.Runtime.Serialization[0x7e63cd7f80] -> mscorlib[0x7e6a625f00]: 63
09-14 20:10:57.876 I/Adreno  ( 7699): PFP: 0x005ff110, ME: 0x005ff066
Loaded assembly: System.Runtime.Serialization.dll [External]
09-14 20:10:57.883 I/ConfigStore( 7699): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
09-14 20:10:57.883 I/ConfigStore( 7699): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
09-14 20:10:57.884 I/OpenGLRenderer( 7699): Initialized EGL, version 1.4
09-14 20:10:57.884 D/OpenGLRenderer( 7699): Swap behavior 1
2018-09-14 08:10:57 [TRACE] (MvvmCross.Logging.MvxLog) No view model association found for candidate view RootActivity
09-14 20:10:57.903 I/mono-stdout( 7699): 2018-09-14 08:10:57 [TRACE] (MvvmCross.Logging.MvxLog) No view model association found for candidate view RootActivity
2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: CommandCollectionBuilder start
09-14 20:10:57.912 I/mono-stdout( 7699): 2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: CommandCollectionBuilder start
09-14 20:10:57.912 I/mono-stdout( 7699): 2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: NavigationSerializer start
2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: NavigationSerializer start
2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: InpcInterception start
2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: InpcInterception start
09-14 20:10:57.913 I/mono-stdout( 7699): 2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: InpcInterception start
09-14 20:10:57.914 I/mono-stdout( 7699): 2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: InpcInterception start
09-14 20:10:57.915 I/mono-stdout( 7699): 2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: LastChance start
2018-09-14 08:10:57 [TRACE] (MvvmCross.Core.MvxSetup) Setup: LastChance start
09-14 20:10:57.938 D/Mono    ( 7699): Assembly Ref addref StarWarsSample.Forms.Droid[0x7e62263400] -> AndHUD[0x7e62263980]: 2
09-14 20:10:57.939 D/Mono    ( 7699): Assembly Ref addref StarWarsSample.Forms.Droid[0x7e62263400] -> MvvmCross.Droid.Support.Design[0x7e6084c200]: 2
09-14 20:10:57.950 D/Mono    ( 7699): Assembly Ref addref StarWarsSample.Forms.Droid[0x7e62263400] -> MvvmCross.Droid.Support.V7.AppCompat[0x7e60842f80]: 3
09-14 20:10:57.961 D/Mono    ( 7699): Assembly Ref addref StarWarsSample.Forms.Droid[0x7e62263400] -> Xamarin.Forms.Platform.Android[0x7e60873300]: 5
09-14 20:10:58.036 D/Mono    ( 7699): Assembly Ref addref MvvmCross.Droid.Support.V7.AppCompat[0x7e60842f80] -> Xamarin.Android.Support.Core.UI[0x7e60865300]: 6
09-14 20:10:58.037 D/Mono    ( 7699): Assembly Ref addref Xamarin.Android.Support.Core.UI[0x7e60865300] -> Java.Interop[0x7e60873980]: 5
09-14 20:10:58.037 D/Mono    ( 7699): Assembly Ref addref MvvmCross.Droid.Support.V7.AppCompat[0x7e60842f80] -> MvvmCross.Droid.Support.Core.UI[0x7e6084c000]: 2
09-14 20:10:58.037 D/Mono    ( 7699): Assembly Ref addref MvvmCross.Droid.Support.Core.UI[0x7e6084c000] -> System[0x7e4c5a9a00]: 9
09-14 20:10:58.041 D/Mono    ( 7699): Assembly Ref addref Mono.Android[0x7e60873100] -> System.Net.Http[0x7e63cd7d80]: 3
09-14 20:10:58.041 D/Mono    ( 7699): Assembly Ref addref Mono.Android[0x7e60873100] -> System[0x7e4c5a9a00]: 10
09-14 20:10:58.057 D/Mono    ( 7699): Assembly Ref addref Mono.Android[0x7e60873100] -> System.Xml[0x7e4a928800]: 3
09-14 20:10:58.057 D/Mono    ( 7699): Assembly Ref addref System.Xml[0x7e4a928800] -> mscorlib[0x7e6a625f00]: 64
09-14 20:10:58.148 D/Mono    ( 7699): Assembly Ref addref MvvmCross.Forms[0x7e6084c500] -> System[0x7e4c5a9a00]: 11
2018-09-14 08:10:58 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Secondary end09-14 20:10:58.157 I/mono-stdout( 7699): 2018-09-14 08:10:58 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Secondary end

09-14 20:10:58.169 D/Mono    ( 7699): DllImport searching in: '__Internal' ('(null)').
09-14 20:10:58.169 D/Mono    ( 7699): Searching for 'java_interop_jnienv_get_static_object_field'.
09-14 20:10:58.169 D/Mono    ( 7699): Probing 'java_interop_jnienv_get_static_object_field'.
09-14 20:10:58.169 D/Mono    ( 7699): Found as 'java_interop_jnienv_get_static_object_field'.
2018-09-14 08:10:58 [TRACE] (MvvmCross.Logging.MvxLog) AppStart: Application Startup - On UI thread
09-14 20:10:58.182 I/mono-stdout( 7699): 2018-09-14 08:10:58 [TRACE] (MvvmCross.Logging.MvxLog) AppStart: Application Startup - On UI thread
Thread finished: <Thread Pool> #10
The thread 0xa has exited with code 0 (0x0).

**Comment by FabriBertani** [comment]
I've submited a PR for this issue: [Star wars sample update to v.6.2.0 #130](https://github.com/MvvmCross/MvvmCross-Samples/pull/130)

**Comment by nmilcoff** [comment]
I'll close this as the sample has been successfully updated (and a fix was applied). 

Please feel free to reopen the issue if the sample doesn't work.

**Comment by xufeipyxis** [comment]
I was curious and checked the code change and found that only this code seemed to make difference:

        protected override void RunAppStart(Bundle bundle)	
        {	                                                
             StartActivity(typeof(RootActivity));	        
             base.RunAppStart(bundle);	           			
        }	                                                
		
		
       protected override Task RunAppStartAsync(Bundle bundle)
       {
             StartActivity(typeof(RootActivity));
             return Task.CompletedTask;
        }


I'm not sure if I missed some other code, but if no, then the code from `RunAppStart` to `RunAppStartAsync` should be clearly documented.

**Comment by Cheesebaron** [comment]
@xufeipyxis you are welcome to make that clearer.
