### ISSUE TITLE
Docs: Navigation is outdated

### ISSUE THREAD

**Issue by nmilcoff** [MvvmCross/MvvmCross#3106]
## 🐛 Bug Report

#3046 introduced quite a few changes and no docs were updated. [This document](https://www.mvvmcross.com/documentation/fundamentals/navigation) is therefore outdated.

Things I've noticed:
- It does not explain how cancellation works.
- The interface `IMvxNavigationService` has changed and the listed methods do not match anymore.

**Comment by Cheesebaron** [comment]
To be honest, I don't think we should list the API there at all, since it is prone to change a lot over time.

However, adding the new changes introduced in 6.2 in the doc is 👍
