### ISSUE TITLE
Documentation: .NET Standard Library instead of PCL?

### ISSUE THREAD

**Issue by markuspalme** [MvvmCross/MvvmCross#3108]
The documentation recommends PCLs for shared code across platforms:
https://www.mvvmcross.com/documentation/getting-started/portable-class-library-pcl

I read the page a couple of times and did not really understand what it's trying to convey. For example, the statement `it is possible to write the MvvM either as a PCL or as a shared project` does not make a lot of sense to me.

Should we a) get rid of the page as it is or b) replace it with a page that recommends .NET Standard libraries for shared code?

As I see it, the current documentation on the subject does recommend an obsolete technology and does not help any newcomers, quite the opposite.

**Comment by nickrandolph** [comment]
We should definitely update this to recommend using .NET Standard library, ideally with multi-targeting now.
See https://nicksnettravels.builttoroam.com/post/2018/08/19/Getting-Started-with-XamarinForms-and-Multi-Targeting-in-Visual-Studio.aspx for setting up a csproj for multi-targeting
