### ISSUE TITLE
Branch for 4.4.0 and 4.4.0 plugins

### ISSUE THREAD

**Issue by SSElliott** [MvvmCross/MvvmCross#3110]
Hi

I have a project using MvvmCross 4.4.0 with 4.4.0 plugins. Is the URL
https://github.com/MvvmCross/MvvmCross/tree/b830ab5189323b2ff9059e08ba359b4956709889/

correct for viewing and downloading the code for this version. I am not in a position to upgrade to the very latest with this project, and want to make sure I have local copy in case I come across any problems.

Steven

**Comment by Cheesebaron** [comment]
Use: https://github.com/MvvmCross/MvvmCross/tree/4.4.0

**Comment by SSElliott** [comment]
Many thanks

Steven
