### ISSUE TITLE
Xamarin.iOS stuck on Launchscreen after update to 6.2

### ISSUE THREAD

**Issue by tatlacas** [MvvmCross/MvvmCross#3111]
## 🐛 Bug Report

Xamarin.iOS stuck on Launchscreen after update to 6.2
### Expected behavior
Show Launchscreen then navigate to firstViewModel
### Reproduction steps
Run any Xamarin.iOS sample projects. App will show Launchscreen and run Initialize of ViewModel but View not shown.
### Configuration

**Version:** 6.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
I tested this on the [StarWarsSample](https://github.com/MvvmCross/MvvmCross-Samples/tree/master/StarWarsSample) on both `traditional` and `Forms` iOS apps and it's working fine.

On which sample did you see this?

**Comment by tatlacas** [comment]
Found the issue. For anyone who get this bug,` NavigateToFirstViewModel()` MUST `return Navigate<YourViewModel>();`. I had a Task running in here and it was working before the 6.2 update. Not anymore.

**Comment by nmilcoff** [comment]
`NavigateToFirstViewModel` should also work if you do something like `await NavigationService.Navigate<YourViewModel>()` within the method. 

I don't think you should have many `await`s at that point, it's has a direct impact on the user UX.

**Comment by matt-ankerson** [comment]
I encountered this issue when upgrading to 6.2 and only overcame it by moving all awaited operations out of `MainViewModel`'s `Initialize` method. Why could this be the case? (my project is modelled after the playground iOS tab bars sample)
