### ISSUE TITLE
iOS App not starting with custom app start

### ISSUE THREAD

**Issue by radioactiveman** [MvvmCross/MvvmCross#3118]
## 🐛 Bug Report

I am trying to update MvvmCross for a Xamarin.Forms application from version 5.7.0 to 6.2.0.
It uses a custom app start which navigates to a different view model if the session is still valid.
This used to work fine on Android and iOS (with 5.7.0), but with 6.2.0 an exception is thrown for iOS:

````
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch
````

Since the documentation [1] is outdated, I am not sure how to use the navigation service properly with version 6.2.0. Is the "GetAwaiter().GetResult()" still required?

My code (adapted to 6.2.0) looks like this. Is there anything wrong?

```c#
public class CoreApp : MvxApplication
{
    public override void Initialize()
    {
        // Registering several singletons
        // ...

        this.RegisterCustomAppStart<CustomAppStart>();
    }
}
```

```c#
public class Setup : MvxFormsIosSetup<CoreApp, App>
{
    protected override IMvxApplication CreateApp()
    {
        return new CoreApp();
    }

    protected override Xamarin.Forms.Application CreateFormsApplication()
    {
        return new App();
    }
}
```

```c#
[Register("AppDelegate")]
public class AppDelegate : MvxFormsApplicationDelegate<Setup, CoreApp, App>
{
    public override bool FinishedLaunching(UIApplication app, NSDictionary options)
    {
        base.FinishedLaunching(app, options);
        
        // Registering for push notifications, 
        // ...

        return true;
    }
}
```

```c#
public class CustomAppStart : MvxAppStart
{
    private readonly ISessionHandler sessionHandler;

    public CustomAppStart(
        IMvxApplication application,
        IMvxNavigationService navigationService,
        ISessionHandler sessionHandler,)
      : base(application, navigationService)
    {
        this.sessionHandler = sessionHandler;
    }

    protected override Task NavigateToFirstViewModel(object hint = null)
    {
        var session = this.sessionHandler.Get();

        var viewModel = session.LoginState == LoginState.LoggedIn
            ? typeof(OverViewViewModel)
            : typeof(LoginViewModel);

        return this.NavigationService.Navigate(viewModel);
    }
}
```

[1] https://www.mvvmcross.com/documentation/advanced/customizing-appstart

### Expected behavior
The app should start without an exception, as before with 5.7.0.

### Reproduction steps
--

### Configuration
--

**Version:** 6.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
In theory the .GetAwaiter().GetResult(); shouldn't be required since the base logic already calls this. You could try adding it to the end of the Navigate method and see if that fixes the issue for you

**Comment by radioactiveman** [comment]
The exception was not related to the custom app start, when using `RegisterAppStart<LoginViewModel>()` instead of `RegisterCustomAppStart<CustomAppStart>()` the same exception was thrown.

The problem was caused by the custom view presenter. Before (with 5.7.0) it was initialized in the iOS Setup class like this:

```c#
protected override IMvxIosViewPresenter CreateViewPresenter()
{
    return new CustomViewPresenter(this.ApplicationDelegate, this.Window, this.FormsApplication);
}
```

With newer versions of MvvmCross the FormsPagePresenter needs to be initialized as well.
```c#
protected override IMvxIosViewPresenter CreateViewPresenter()
{
    var viewPresenter = new CustomViewPresenter(this.ApplicationDelegate, this.Window, this.FormsApplication);
    viewPresenter.FormsPagePresenter = this.CreateFormsPagePresenter(viewPresenter);
    return viewPresenter;
}
```
