### ISSUE TITLE
MvxMultiRegionWpfViewPresenter - Support for multiple windows needs access to _frameworkElementsDictionary

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [MvvmCross/MvvmCross#3121]
## 🏗 Enhancement Proposal

The documentation at https://www.mvvmcross.com/documentation/platform/wpf/wpf-view-presenter states support for multiple windows app. This is true if one is directly using the `MvxWpfViewPresenter`.

We're using a modified version of the `MvxMultiRegionWpfViewPresenter ` from the samples https://github.com/MvvmCross/MvvmCross-Samples/blob/master/XPlatformMenus/XPlatformMenus.WPF/Views/MvxMultiRegionWpfViewPresenter.cs that only supports regions in the initial `ControlControl`.

In order to add support for regions regardless of the window access to the `_frameworkElementsDictionary` in `MvxWpfViewPresenter` is required. I copied the class source to our project and added a protected property `FrameworkElementsDictionary` to the class.

Obviously I would prefer if I hadn't to copy framework code - while I'm happy that I could ;). Is this worth a pull request?

### Pitch

Adding a protected `FrameworkElementsDictionary` property would allow custom presenters - like the `MvxMultiRegionWpfViewPresenter` - to add support for multiple windows without modifying a copy of `MvxWpfViewPresenter`. Also they would no longer - redundantly - require to hold a copy of the `contentControl` constructor argument. 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
A PR would be appreciated.

**Comment by HaraldMuehlhoffCC** [comment]
Any special branch I should fork on? Please bear with me since this would be my first PR ever ;)

**Comment by Cheesebaron** [comment]
@HaraldMuehlhoffCC just branch from develop

**Comment by Cheesebaron** [comment]
Closing this as it was fixed in #3127
