### ISSUE TITLE
Xamarin.Android: KeyListener not working on real devices

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [MvvmCross/MvvmCross#3126]
## 🐛 Bug Report

In the OnCreate fragment method, I get my EditText from the layout and call SetOnKeyListener:
```
Aaa = view.FindViewById<EditText>(Resource.Id.aaaText);
Aaa.SetOnKeyListener(new LocationKeyListener());
```

**Layout declaration:**

```
<EditText 
            android:id="@+id/aaaText"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:imeOptions="actionNext"
            style="@style/LocationEditTextStyle"
            android:hint="AAA"
            app:MvxBind="Text Aaa.Value"/>
```

**EditText styles:**
```
<style name="LoginEditTextTheme" parent="Theme.AppCompat">
        <item name="colorControlNormal">@color/accentColor</item>
        <item name="colorControlActivated">@color/secondaryTextColor</item>
    </style>

    <style name="LocationEditTextStyle" parent="Widget.AppCompat.EditText">
        <item name="android:textAllCaps">true</item>
        <item name="android:inputType">textCapCharacters</item>
        <item name="android:maxLength">3</item>
        <item name="android:gravity">center_horizontal</item>
        <item name="android:textSize">@dimen/location_text_size</item>
        <item name="android:theme">@style/LocationEditTextTheme</item>
    </style>
```

My keyListener:
![uqpyo](https://user-images.githubusercontent.com/30652592/46036594-921ee000-c10e-11e8-89dd-62d1e0058960.png)

The problem is that the LocationKeyListener.OnKey method is not called, when I write in EditText.

### Expected behavior
When I press the button on the Android keyboard on a real device, the OnKey / OnKeyPressed event is called.

### Reproduction steps
You can clone basic sample to reproduce issue: https://github.com/Goncharuk-Nikita/KeyPressIssue
You can also see more information on stackoverflow: https://stackoverflow.com/questions/52474063/xamarin-android-key-listener-not-working

### Configuration
Visual Studio 2017 15.8.5

**Version:** 6.2.0

**Platform:** 
- [x] :robot: Android

**Comment by Cheesebaron** [comment]
I don't see why this has anything to do with MvvmCross. `EditText` is a native Android class, so we cannot do anything about your events not being hit.
