### ISSUE TITLE
NullReferenceException in MvxAppCompatViewPresenter.ShowTabLayout

### ISSUE THREAD

**Issue by michaldudak** [MvvmCross/MvvmCross#3129]
## 🐛 Bug Report

My application's logs tell me a fraction of users of encounter a NullReferenceException thrown when calling MvxAppCompatViewPresenter.ShowTabLayout

Here's the whole stack trace:
```
MvxAppCompatViewPresenter.ShowTabLayout (System.Type view, MvvmCross.Platforms.Android.Presenters.Attributes.MvxTabLayoutPresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request)
MvxAppCompatViewPresenter.<RegisterAttributeTypes>b__3_0 (System.Type view, MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request)
MvxAndroidViewPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request)
MvxAndroidViewDispatcher+<>c__DisplayClass2_0.<ShowViewModel>b__0 ()
MvxMainThreadAsyncDispatcher+<>c__DisplayClass0_0.<ExecuteOnMainThreadAsync>b__0 ()
MvxMainThreadAsyncDispatcher+<>c__DisplayClass1_0+<<ExecuteOnMainThreadAsync>b__0>d.MoveNext ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.41(intptr,intptr)
```

This occurs for about 3% users and is not connected to any particular OS version or phone.

The app contains a main view (TabHostView) that sets its child tabs similarily to how it's shown in the Star Wars sample

The TabHostView's OnCreate has the following:
```
if (_firstTimePresented)
{
	_firstTimePresented = false;
	ViewModel.GoToSchedulesCommand.Execute();
	ViewModel.GoToInfoPagesCommand.Execute();
	ViewModel.GoToNewsCommand.Execute();
}
```

where all these commands show the proper view with the help of NavigationService:

```
public TabHostViewModel(IMvxNavigationService navigationService)
{
	NavigationService = navigationService;
}

public IMvxAsyncCommand GoToSchedulesCommand => new MvxAsyncCommand(() => NavigationService.Navigate<SchedulesViewModel>());

public IMvxAsyncCommand GoToNewsCommand => new MvxAsyncCommand(() => NavigationService.Navigate<NewsViewModel>());

// etc.
```

The actual tab views are decorated with `MvxTabLayoutPresentation` attribute (and a `RegisterAttribute` as they inherit from `MvxFragment`)

### Expected behavior
The NRE is not thrown :)

### Reproduction steps
Unfortunately, it only happens in the wild. I could not reproduce it locally.

### Configuration

**Version:** 6.1.2

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by michaldudak** [comment]
Unfortunately no, I've never been able to reproduce it myself. I'm only seeing error reports on Visual Studio App Center. Soon I'm going to update the app to MVVMCross 6.2 and see if it helps.

**Comment by haohighview** [comment]
MVVMCross 6.1.2: NullReferenceException in MvxAppCompatViewPresenter.ShowDialogFragment
 I've never been able to reproduce it myself. I'm only seeing error reports on Visual Studio App Center. 
MvxAppCompatViewPresenter.ShowDialogFragment (System.Type view, MvvmCross.Platforms.Android.Presenters.Attributes.MvxDialogFragmentPresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request)
MvxAndroidViewPresenter.<RegisterAttributeTypes>b__21_4 (System.Type view, MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request)
MvxAndroidViewPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request)
MvxAndroidViewDispatcher+<>c__DisplayClass2_0.<ShowViewModel>b__0 ()
MvxMainThreadAsyncDispatcher+<>c__DisplayClass0_0.<ExecuteOnMainThreadAsync>b__0 ()
MvxMainThreadAsyncDispatcher+<>c__DisplayClass1_0+<<ExecuteOnMainThreadAsync>b__0>d.MoveNext ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.25(intptr,intptr)

**Comment by michaldudak** [comment]
I finally managed to release a version of my app using MVVMCross 6.2 and I can confirm the issue no longer exists. There's another one with MvxCachingFragmentStatePagerAdapter though, but I need to find out more details and I'll post another issue.

**Comment by nmilcoff** [comment]
Thanks for coming back to us @michaeldaw!

**Comment by michaeldaw** [comment]
attn: @michaldudak
