### ISSUE TITLE
TextLabel.Lines is ignored/overridden if Text is bound

### ISSUE THREAD

**Issue by andresdsep** [MvvmCross/MvvmCross#3130]
## 🔙 Regression

This is extending UITableViewSource in an IOS application. I am registering a custom ViewCell to use with the ViewSource and doing this binding in it's constructor:

```c#
var bindingSet = this.CreateBindingSet<BaseTableViewCell, TableDefaultRowViewModel>();
bindingSet.Bind(TextLabel).For(l => l.Text).To(vm => vm.Text);
bindingSet.Apply();
```

I am also setting this to let the label have as many lines as it needs:
`TextLabel.Lines = 0;`

### Old (and correct) behavior
Text is bound and shown and as many lines as needed are rendered.

### Current behavior
Text is bound and shown, however only up to 2 lines will show. I've actually found that setting the `Lines` property to `1` will indeed produce only up to 1 line.

If I extract the value from the ViewModel myself and assign to the `Text` property, it all works as expected.

### Reproduction steps
In description. (sorry, I don't have a practical way to produce a minimal required repro sample)

### Configuration

**Version:** 6.1.2 (though have also tested with 6.2.0)

**Platform:** 
- [x] :iphone: iOS

**Comment by Cheesebaron** [comment]
We don't do anything with UILabel when binding `Text` other than setting the text: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Ios/Binding/Target/MvxUILabelTextTargetBinding.cs
