### ISSUE TITLE
Give MvxPopToRootPresentationHint a bundle constructor argument so the Body in it's base class can be set.

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [MvvmCross/MvvmCross#3134]
## 🏗 Enhancement Proposal

For my multi-window WPF application I had to create my own `PopToRootPresentationHint` because the constructor of `MvvmCross.Presenters.Hints.MvxPopToRootPresentationHint` doesn't offer a way to pass the bundle to it's root class `MvxPresentationHint`. As holding the `MvxBundle` instance is the main purpose of `MvxPresentationHint` it should be possible to set it for `MvxPopToRootPresentationHint`.

### Pitch

Every class deriving from `MvxPresentationHint` should include a constructor to allow to set the `MvxBundle` instance available via the `Body` property. Otherwise their utility is artificially diminished.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Fixed in #3135
