### ISSUE TITLE
I'm curious how to start app from opening link

### ISSUE THREAD

**Issue by xyashapyx** [MvvmCross/MvvmCross#3138]
## 💬 Questions and Help

I'm trying to implement opening my app from clicking on link in my web site.
So, user clicks on url like https://www.myWebsite.com and if he is having app installed it should opens. 

I was trying to do catch lick in viewModel like 
`[assembly: MvxNavigation(typeof(MyViewModelToOpen), @"https://www.myWebsite.com")]
namespace MyApp.Core.ViewModels.PageViewModels
{
    public class MyViewModelToOpen: MvxViewModel
    {     
    }
}`

and from faced like 
`[assembly: MvxNavigation(typeof(MyViewModelToOpen), @"https://www.myWebsite.com/")]
namespace MyApp.Core.NavigationFacades
{
    public class MyViewModelToOpen: IMvxNavigationFacade
    {
        public Task<MvxViewModelRequest> BuildViewModelRequest(string url, IDictionary<string, string> currentParameters)
        { }
}`

But it is not opening my app.

can you help me to do that, please.

**Comment by Cheesebaron** [comment]
Please use [Slack #mvvmcross](https://xamarinchat.herokuapp.com/) or [StackOverflow](https://stackoverflow.com/questions/tagged/mvvmcross) for questions. Github is meant to be used for bugs and feature requests only.
