### ISSUE TITLE
[Xamarin.Mac] NSPopover fails to render content when run from .app bundle

### ISSUE THREAD

**Issue by projectgoav** [MvvmCross/MvvmCross#3145]
## 🔙 Regression

MvvmCross Mac : Xamarin Native. 

MvvmCross appears to cause NSPopover and NSSheet instances to fail to render their contents on Mac OSX Mojave. This behaviour did not occur on previous Mac OSX versions. 

### Problem

In our application we have an NSPopover with a tableview, some text and a button. Running our application, in any configuration with Visual Studio attached, the popover renders fully and correctly. 

However, if we run the app by clicking the `<AppName>.app` bundle - the popover will not render it's contents. The border around the popover is seen and the contents do exist as you can scroll and click items within it.

If you then run the app via the command line: `path/to/app/<MyAppName>.app/Contents/MacOSX/<MyAppName>` then the popover renders contents correctly, as seen when the debugger is attached. 

### Reproduction

I've created a small sample application using plain Xamarin native with no dependencies. It has a single window with a button. When clicked a popover displays with a table, label and button like that which is found in our application. No matter how you run this application the popover is always fully rendered. A copy is attached to this issue. 

I then took a copy of the **v5.7.0** (See 'Please Note' below) release branch of MvvmCross, modifying the 'Playground.Mac' project. I added an additional button to open the same Xib and using the same code (below) attached to the buttons action outlet. 

``` C#     
partial void ClickMeClicked(NSObject sender)
{
    var popover = new NSPopover();
    popover.Behavior = NSPopoverBehavior.Transient;
    popover.ContentViewController = new PopoverViewController();

    popover.Show(btnChild.Bounds, btnChild, NSRectEdge.MaxYEdge);
}
```

This app now has the same issue that we are seeing. When run with Visual Studio Mac or the commandline the popover displays correctly. Otherwise, all you see is the border. 

**Edit**: This happens on any build configuration (Debug, Release etc)

#### MvxSheetPresentation Has Similiar Issue

When using the 'Playground.Mac' test application the sheet, opened via 'Show Sheet' button, does something similiar. The sheet can be resized but still no content renders. The 'Close' button exists and is clickable. This will also occur when run from inside Visual Studio. 

#### Possible Workaround
We've found that if you open the popover after toggling the system theme the contents will sometimes render. This is not 100% reliable. So far, we've yet to see this work for the sheet view. 

### Please Note
- We are using MvvmCross **v5.7.0**. We are currently unable to move to MvvmCross v6.

- We've tried to reproduce this on the latest release branch. Visual Studio Mac fails to build the project due to an internal error in `Microsoft.Build.Tasks.Git.LocateRepository`. Visual Studio Windows lets us build MvvmCross just fine but wont let us debug the app using a remote Mac. I'm assuming that only iOS apps are supported in this way. We're still trying to work on getting the latest built. 

### Screenshots

An annoated imgur screenshot album showing both my app and the playground app in the various rendering states can be found at the following link: https://imgur.com/a/TYDHPJU

*I'm not sure the policy on linking images to an external service. If you'd rather I post the screenshots directly to Github please just let me know.*

### Configuration

This is our current Visual Studio Mac setup:

```Text
Visual Studio Community 2017
Version 7.6.8 (build 38)
Installation UUID: 15d318c1-0022-470b-8742-ac625e930509
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

Xamarin.Mac
Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

Build Information
Release ID: 706080038
Git revision: f4178f550a4de7c03aa23678041abe4fc388cf72
Build date: 2018-09-28 14:21:41+00
Build branch: release-7.6
Xamarin extensions: 051b653186a95ced1c127dfd8c358df1b9315d0d

Operating System
Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

```

**Version:** 5.7.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

### Attached Files 
[My Demo App -> InvisiblePopover_Minimal.zip](https://github.com/MvvmCross/MvvmCross/files/2445467/InvisiblePopover_Minimal.zip)

**Comment by Cheesebaron** [comment]
Is this reproducible on 6.2.0? We don't support old versions of MvvmCross. However, If you have a fix for this on 5.7.0 we could hotfix that branch.

**Comment by projectgoav** [comment]
I'm currently unable to even build v6.2.0 on Mac. 

Visual Studio for Windows works fine but you can't run/debug Mac apps from a Windows machine like you can with the remote session support for iOS apps. 

Visual Studio for Mac complains about the MSFT Build.Tasks.Git build step and wont proceed. I've tried a complete fresh clone (I had an old one kicking around from v5.0.0) and it still wont work. I've not had much success removing that dependency from the projects either.

I've not found a way to build the Playground application from the provided Cake script.

As MvvmCross 6 moved to .NET Standard I would have expected v5.7.0 to recieve a little support to act as a bridge until .NET Standard is widely adopted. It's a non-trival task for us to upgrade everything while maintaining support for all our platforms.

**Comment by Cheesebaron** [comment]
> I'm currently unable to even build v6.2.0 on Mac.

We are still waiting for the Visual Studio for Mac team to get the IDE ready to consume multi-target projects (it has probably been almost a year ☠️).
You should be able to build using the command-line though invoking `sh build.sh` in the root which will produce nuget packages etc.

As for Build.Tasks.Git, you can try remove the sourcelink dependency in `Directory.build.props`, it is the only thing depending on that.

> until .NET Standard is widely adopted

I think the term `widely adopted` is very subjective. I think almost every nuget, if not every, I consume nowadays is .NET Standard or a multi-target library of some sort. I don't know which packages you are using though.

If you can narrow your issue down to where in MvvmCross we do something to prevent NSPopovers to show, we will be happy to hotfix 5.7.0. However, we are not actively working on it, nor backporting fixes on it.

**Comment by projectgoav** [comment]
> You should be able to build using the command-line though invoking sh build.sh in the root which will produce nuget packages etc.

I had a bit of a fight to get the thing to build (it assumes that you have both the iOS/MAC AND Android SDKs installed among others) but I've now managed to build the release/6.2.0 branch.

I've also been able to build the 'Playground.Mac' application from within Visual Studio. However, when running the application the app icon appears in the statusbar but no window is ever drawn. 

I see the following output in the console (I've suppressed some MvxJsonLocalisation error due to missing localisation files. I doubt that's effecting any of the Mvx initialisation)

```Text
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Primary start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: FirstChance start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: PlatformServices start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: MvvmCross settings start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Singleton Cache start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: ViewDispatcher start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Bootstrap actions
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: StringToTypeParser start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: CommandHelper start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: PluginManagerFramework start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Create App
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: NavigationService
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Load navigation routes
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: App start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Application Initialize - On background thread
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: ViewModelTypeFinder start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: ViewsContainer start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Views start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: CommandCollectionBuilder start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: NavigationSerializer start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: InpcInterception start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: InpcInterception start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: LastChance start
2018-10-05 12:04:11 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Secondary end
2018-10-05 12:04:11 [TRACE] (MvvmCross.Logging.MvxLog) AppStart: Application Startup - On UI thread
2018-10-05 12:04:11 [WARN]  (Playground.Core.ViewModels.RootViewModel) Testing log
2018-10-05 12:04:11 [TRACE] (MvvmCross.Logging.MvxLog) MacNavigation
```

Looking at the debugger it looks like nothing in the `MvxMacSetup<TApp>` is ever called apart from the platform specific constructor in the following class.

```C#
public class Setup : MvxMacSetup<App>
{
    public Setup()
    {
        MvxWindowPresentationAttribute.DefaultWidth = 250;
        MvxWindowPresentationAttribute.DefaultHeight = 250;
    }
}
```

Equally, no method is ever called within the `MvxApplicationDelegate` class. The `DidFinishLaunching` app lifecycle method is never called which I think is why no window is drawn. Will look into this further.

**Comment by projectgoav** [comment]
Update:

I've now got MvvmCross to build and run in Debug mode on Mac (via the docs on the website) and when running 'Playground.Mac' all the various setup methods and Mac Lifecycle methods are called. 

I'm still not seeing any window being displayed.

**Comment by Cheesebaron** [comment]
Maybe you are hitting issues described in: https://github.com/xamarin/xamarin-macios/issues/4509 Xamarin.Mac has some UI issues in Mojave

**Comment by projectgoav** [comment]
Thanks for linking that issue. I'll submit a copy of my screenshots over to them to see if it's something related/they are aware off. 

In the meantime I've still been trying to get a reproducable example with Mvx 6.2 since I've had no luck with the Playground project. Having tried the following I'm still no further forward....

#### MvvmCross Project template for Visual Studio
Using your website there was a link to a number of project templates. None of them would create a Xamarin.Mac project. I used one of them which created me an iOS, Android, iOS, UWP and WPF project and thought I'd manually add a Mac one myself. 

However, the 'Core' project that was created was a PCL project. The latest possible it could upgrade to was v5.7.0 without converting to .NET Standard.

I then tried to convert the PCL to .NET Standard before upgrading MvvmCross. Visual Studio (VS) for Windows didn't have a conversion option when I looked. The best I could find was to create a new .NET Standard project and import the code. 

VS for Mac does have an conversion option but for some reason it's capped at targetting .NET Standard 1.5 which isn't high enough for MvvmCross. 

#### New .NET Standard 'Core' project
VS for Windows allowed me to create a new .NET Standard library targetting 2.0. After adding the MvvmCross v6.2.0 nuget package and creating an `App` class inheriting from `MvxApplication` it happily builds without warnings or errors. 

I then brought this project into VS for Mac. It would not build and said that the namespace MvvmCross.Core.ViewModels could not be found. 

I then created a brand new .NET Standard Library in VS for Mac targetting 2.0. It happily adds MvvmCross v6.2.0 nuget package and I can see the new text document appear explaining how to 
setup projects. I added the same `App` class but it will not build.

Both projects have the same project structure, as shown in the screenshot.
![screenshot 2018-10-08 at 15 31 28](https://user-images.githubusercontent.com/6363155/46615531-4b6ab600-cb10-11e8-9270-0c9f0abb6299.png)

The only way I've been able to get the project to build is to add the MvvmCross.Core nuget package. This appears to have the latest version of v5.7.0 which isn't what I'm wanting. 

#### Manually referencing assemblies
In VS for Mac I tried manually adding the MvvmCross.dll from the downloaded nuget package. This doesn't improve anything and the project still wont build. 


I had a look at the MvvmCross.dll with ILSpy can neither the `netstandard20` or `xamarin.mac20` targets have the `MvvmCross.Core.ViewModels` namespace. How VS for Windows compiles happily is a mystery to me as it'll surely be using the same `netstandard20` dll as I examined....?


Have you ever seen this behaviour before? Have you any ideas of how to get an MvvmCross v6 core project to build in VS for Mac using the latest Nuget? From what I gather, the Playground application I was using previously just references the project directly.

**Comment by projectgoav** [comment]
After posting on that Xamarin issue you'd linked I was given a patch to test out. With this patch the popovers in our application and those in the v5.7.0 playground application appear to be fixed.

Running the v6.2.0 playground on Mac with this patch applied still results in no window being shown. 

While my original issue now appears to be fixed by Xamarin I believe I have encountered a number of other issues relating to MvvmCross on Xamarin.Mac. Should I keep this issue open for reference for these or should I raise them as individual tickets?

**Comment by Cheesebaron** [comment]
Please open new issues. It might just be that the Mac sample needs a loving hand.
