### ISSUE TITLE
Mvx Setup randomly fails if the Android app was kept in the background for 4-5 days

### ISSUE THREAD

**Issue by tejas-ad** [MvvmCross/MvvmCross#3146]
## 🐛 Bug Report

The app has a foreground service and the app is kept running in the background for 4-5 days. After some duration, the MvvmCross references get de-initialized but the foreground services keep running. However, if the app is brought back to the foreground, MvvmCross initialization starts through InitializeFromSplashScreen() but gets stuck after initializePrimary() is completed. Here is the code snippet from MvxAndroidSetupSingleton:

```
public virtual void InitializeFromSplashScreen(IMvxAndroidSplashScreenActivity splashScreen)
        {
            lock (LockObject)
            {
                _currentSplashScreen = splashScreen;

                if (_initializationStarted)
                {
                    if (_initialized)
                    {
                        _currentSplashScreen.InitializationComplete();
                        return;
                    }

                    return;
                }

                _initializationStarted = true;
            }

            _setup.InitializePrimary();

            **ThreadPool.QueueUserWorkItem(ignored =>
            {
                _setup.InitializeSecondary();
                lock (LockObject)
                {
                    _initialized = true;
                    if (_currentSplashScreen != null)
                    {
                        _currentSplashScreen.InitializationComplete();
                    }
                }
            });**
        }
```

The code enqueued in the ThreadPool never seems to get executed if the app gets in this situation. As the foreground services are running, the only option is to force stop the app. We could only reproduce the exact scenario by removing the code segment in bold. Currently, there seems to be no other way to reproduce than to wait for 5 days to reproduce it. We have tried kicking the app out of memory by filling up the memory using a different app. The adb shell commands to put the device/app in doze/deep sleep have also been tried, without any success.
A detailed search on ThreadPool shows people have had problems with it especially with Xamarin and have switched to Task.Run, but the MvvmCross source still seems to be using it even in it's latest version.
P.S. We are using the 3.5.1 version of MvvmCross and there is no scope for upgrading to the latest version as we inherited a legacy code base and have a super tight deadline. 

### Expected behavior
The setup should be completed successfully.
### Actual behavior
The setup never goes past initializePrimary() and the application stays on splashscreen.
### Reproduction steps
Could not reproduce this in any way, other than keeping the app in the background for 4-5 days. Haven't tried this with the PlayGround app.
### Configuration
Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
Xamarin.Android Version: 8.3.0.19
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 27.0.3
Issue observed on Android versions 7.x and 8.x. Phones used: Samsung Galaxy S7, S8/S8+, S9/S9+.

**Version:** 3.5.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
A couple of points here:
- thank you for the quite detailed report- it really helps us identify possible issues
- unfortunately we will only be able to investigate and fix issues that are present in the current release. There are just not enough contributors to back-fill issues from earlier versions
- the next step would be to run the playground sample and see if it has the same issue
- I don't think you're correct with regard to the current code - I just took a quick look and I think we now use Task.Run
- if you're able to assist with the investigation by running up the playground sample that would be awesome.
- in order to address your issue, you should try overriding the setup process and switching to using Task.Run. Hopefully this might unblock your project

**Comment by tejas-ad** [comment]
@nickrandolph Thanks for the quick response! Per your suggestion, I am trying to see if this can be reproduced using the playground sample. I agree, MvvmCross did switch to tasks in the 6.0 release. We did change the ThreadPool and replaced it with a Task.Run and the issue seems to have been fixed. However, we are trying to investigate the "why" behind the issue. Do you know why MvvmCross chose to let go of ThreadPool and went for Task.Run instead? Have other people seen issues with ThreadPool on Xamarin/Android? I found a bunch of articles online, suggesting to go for Tasks instead of ThreadPools, but I don't have a concrete article that says ThreadPools are unreliable for this particular scenario(or in general). We even tried to force the re-initialization of MvvmCross, but it seems to work fine every time. The issue seems to be related to being in background for a long time. We tried to create a similar scenario by putting the device on idle, by putting the app in deep sleep, by filling up the memory(RAM) with a different app, so that our app gets kicked out. The simulations are not able to re-create the scenario.

**Comment by nmilcoff** [comment]
Are we ok closing this issue? It seems the problem has been solved (although there is an open question).
