### ISSUE TITLE
Color plugin converters not working in Xamarin.Forms

### ISSUE THREAD

**Issue by fedemkr** [MvvmCross/MvvmCross#3148]
## 🐛 Bug Report

The converters which use `IMvxNativeColor` don't work in Xamarin.Forms. 

This is because there is no implementation of that interface for Xamarin.Forms (AFAIK). Furthermore, I've debugged it and when it tries to convert the `MvxColor`, the resolved `IMvxNativeColor` returns the one for the platform, e.g. for iOS it returns `MvxIosColor` instead of the one for Xamarin.Forms that can return a `Xamarin.Forms.Color`.

I've workarounded this by implementing the interface and registering it.

Implementation:
```c#
[Preserve(AllMembers = true)]
public class MvxFormsColor : IMvxNativeColor
{
    public object ToNative(MvxColor mvxColor)
    {
        return Color.FromRgba(mvxColor.R, mvxColor.G, mvxColor.B, mvxColor.A);
    }
}
```

Registration:
`Mvx.IoCProvider.RegisterSingleton<IMvxNativeColor>(new MvxFormsColor());`

### Expected behavior

All converters of the Color plugin should work in Xamarin.Forms.

### Reproduction steps

Create a converter based on `MvxColorValueConverter`:

```c#
public class MyColorConverter : MvxColorValueConverter<bool>
{
    protected override MvxColor Convert(bool value, object parameter, CultureInfo culture)
    {
        return value ? new MvxColor(255, 0, 0) : new MvxColor(0, 255, 0);
    }
}
```

Use it in some binding:

`mvx:Bi.nd="BackgroundColor MyColor(MyBoolProperty)"`

### Configuration

**Version:** 6.2.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
We would need to create a separate package for Forms, as there are no TFMs for it. I think this should be a feature request rather than a bug.

**Comment by fedemkr** [comment]
Ok. I'll ammend the docs to state that it does not work on Xamarin.Forms yet and add the reference to this bug so anyone can see the workaround if you think that's fine.
