### ISSUE TITLE
Sort out mess of IMvxTouchPlatformProperties

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#315]
Why is this marked as obsolete?

Do we also need to provide a new improved formfactor attribute - maybe extend it to take multiple form factors?

// some background:

@andyattebery suspect you don't want to know this... but...
6:36:38 PM
the reason that area is confused is because of a problem I hit
6:36:49 PM
basically back in the old interfaces the touch presenter had to be created before Setup.cs
6:37:09 PM
which meant that you had to choose your presenter before you had started IoC
6:37:31 PM
which meant that you couldn't use the IMvxTouchPlatformProperty interface
6:37:58 PM
which started me down the road of making it obsolete...
6:38:08 PM
only then I worked out that I could change the setup structure so that the presenter got created
6:38:31 PM
later - after IoC was availablle
6:38:43 PM
which filled my heart with so much job
6:38:49 PM
joy
6:38:51 PM
that I went out for a drunken party
6:39:03 PM
and never properly cleaned up 100% of the mess....

**Comment by martijn00** [comment]
Is this still an issue?

**Comment by slodge** [comment]
At a code level, yes it could be much neater... especially now we have iPhablet sizes too.

**Comment by martijn00** [comment]
Removed in 5.0
