### ISSUE TITLE
MvvmCross Update 6.2.0 causes NullReferenceException when using MvxCommands in unit tests

### ISSUE THREAD

**Issue by svenbayoo** [MvvmCross/MvvmCross#3152]
## 🐛 Bug Report

After updating our unit test project to MvvmCross 6.2.0 the unit tests vor MvxCommands in ViewModels fail due to an internal error of MvxCommandBase.ctor:

```
System.NullReferenceException: Object reference not set to an instance of an object.
    at MvvmCross.Commands.MvxCommandBase..ctor()
   at MvvmCross.Commands.MvxCommand..ctor(Action execute)
   at MyCompany.MyProject.Core.ViewModels.MainViewModel.get_LogoClickedCommand()
   at UnitTest.Core.ViewModels.MainViewModelTest.MainViewModel_LogoClickedCommand()
```

The code in the ViewModel is the following:
`public IMvxCommand LogoClickedCommand => new MvxCommand(LogoClicked);`

This does not cause any problems when using e.g. MvvmCross 6.0.1.

### Expected behavior

The MvxCommand can be instantiated and executed.

### Reproduction steps

- Update unit test project to MvvmCross 6.2.0
- Create unit test class and method that tries to instantiate a MvxCommand:
`var cmd = new MvxCommand(() => {})`

### Configuration

**Version:** 6.2.0

**Platform:** 
- [X ] :robot: Android

**Comment by Cheesebaron** [comment]
We have loads of tests for Commands in our UnitTests. Parts of MvvmCross require IoC to be initialized among other things. What are you doing to fulfill these requirements?

**Comment by svenbayoo** [comment]
This problem was resolved, using the MvxIoCSupportingTest as base class for the view model tests. An initialization method for unit tests was created:
        ```
[TestInitialize]
        public void Initialize()
        {
            base.Setup();
        }
```

More information can be found here: https://www.mvvmcross.com/documentation/fundamentals/testing
