### ISSUE TITLE
Visual Studio for Mac can't build a 'Core' project with MvvmCross v6+ nuget package

### ISSUE THREAD

**Issue by projectgoav** [MvvmCross/MvvmCross#3155]
## 🐛 Bug Report

1. Create new .NET Standard library in Visual Studio
2. Add `MvvmCross` nuget package to project.
3. Create `App` class which inherits off `MvxApplication`.
4. Build project

### Expected behavior
Both Visual Studio on Windows and Mac should build without errors. 

### Actual behavior
Visual Studio for Windows builds project happily.
Visual Studio for Mac complains about missing namespace `MvvmCross.Core.ViewModels`

Copying the project created in Visual Studio Windows and building with Visual Studio Mac wont build either. 

### Configuration
- Visual Studio Mac 'Stable' channel
- Mac OSX Mojave

**Version:** 6.x

**Platform:** 
I believe this will effect every platform since you should be able to build your 'Core' project anywhere.

**Comment by nickrandolph** [comment]
Can you please confirm that the nuget package has actually been restored. There are plenty of developers using VS for Mac without issue.

**Comment by projectgoav** [comment]
- `Right Click -> Build` to force restore. Issue still occurs
- `Right Click -> Restore Nuget Packages` shows "All packages successfully restored" in the console. No other issues or warnings I can see from the output. Issue still occurs
- `Nuget restore <solution>` on the command line completes with the same output as in Visual Studio. Issue still occurs. 


Please see: https://github.com/MvvmCross/MvvmCross/issues/3145#issuecomment-427873254 a little more info on what I've tried.

**Comment by projectgoav** [comment]
I can also confirm I have the following directory structure:
```Text
project -
   - <projectname>
      - ...
   - <projectname>.sln
   - packages
      - MvvmCross.6.2.0
         - .signature
         - lib
            - (Platform folders: netstandard20, xamarinmac20 + many others)
         - MvvmCross.6.2.0.nupkg
         - readme.txt
```

I have no path overrides and am using the default package location

**Comment by nickrandolph** [comment]
The namespace mvvmcross.core.viewmodels doesn't exist anymore. Please update your code to us mvvmcross.viewmodels.
I think on windows NuGet might be referencing an older version somehow

**Comment by projectgoav** [comment]
I've created the following screenshots showning what I am doing, just to be sure I'm doing the right thing! (I've also noticed this uses v6.2.1 but the issue still happens.)

Create New .NET Standard Project:
![screenshot 2018-10-11 at 15 58 17](https://user-images.githubusercontent.com/6363155/46813666-0bedd500-cd6f-11e8-99d4-a590d1f27934.png)

Ensure it's netstandard 2.0:
![screenshot 2018-10-11 at 15 58 23](https://user-images.githubusercontent.com/6363155/46813690-160fd380-cd6f-11e8-8e91-669fb0862d87.png)

Project created, now to add MvvmCross as a Nuget Package:
![screenshot 2018-10-11 at 15 58 58](https://user-images.githubusercontent.com/6363155/46813711-2162ff00-cd6f-11e8-8a4f-fb401854fe7b.png)

Use the `MvvmCross` package, at the latest version (v6.2.1)
![screenshot 2018-10-11 at 15 59 23](https://user-images.githubusercontent.com/6363155/46813737-2e7fee00-cd6f-11e8-92a7-0ab49daca768.png)

Visual Studio Mac is quite happy and so is the package output:
![screenshot 2018-10-11 at 15 59 57](https://user-images.githubusercontent.com/6363155/46813770-3b9cdd00-cd6f-11e8-87dc-d9fe02a9962d.png)

Add inheritance to MvxApplication. Visual Studio Mac can't resolve the reference:
![screenshot 2018-10-11 at 16 00 29](https://user-images.githubusercontent.com/6363155/46813889-6d15a880-cd6f-11e8-8192-b75fe07ef0de.png)

`Right Click -> Build` and still can't resolve the issue. Fails to compile:
![screenshot 2018-10-11 at 16 00 44](https://user-images.githubusercontent.com/6363155/46813899-769f1080-cd6f-11e8-85a4-f3df1997d41e.png)

**Comment by projectgoav** [comment]
Ok.... I'm now utterly confused. I just tried doing the same thing again, with yet another new project. 

Low and behold, it now correctly decided there is something that should be imported from MvvmCross, added the using and built...

I think this is one of these VS-Mac/Intellisense quirks on Mac!

**Comment by projectgoav** [comment]
Yep. Can confirm that this it all works quite happily now with new projects and the previous project I first saw this issue with. I have no idea what was going on with my VS on Mac.... 

Sorry to have bothered you on this!
