### ISSUE TITLE
Update for ShowNestedFragment fragmentHost.IsVisible 

### ISSUE THREAD

**Issue by Plac3hold3r** [MvvmCross/MvvmCross#3160]
## 🏗 Enhancement Proposal

Remove the [`fragmentHost.IsVisible`](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatViewPresenter.cs#L260) constraint or allow for it to be ignored via a `MvxFragmentPresentationAttribute` property. 

### Pitch

Currently, I have an App that is working fine without this check. I needed to override `ShowNestedFragment` to remove it else it kept throwing the `InvalidOperationException`. I'm not too sure if there is something particularly special about my implementation that it all works fine with `fragmentHost.IsVisible` returning `false`. But it does not seem necessary at least not all the time. It would be nice to not have to create a custom presenter to override and remove this check.

I would like to propose adding an additional property to `MvxFragmentPresentationAttribute` to opt-out of this check, `IgnoreHostVisibility`. 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
If I recall correctly, when we implemented nested fragments we saw some weird exceptions when trying to run the fragment transaction while the fragment host was not visible. Does it work for you in that case?

**Comment by Plac3hold3r** [comment]
It seems at that point in time when navigating the `fragmentHost.IsVisible` is false. However, if I remove the check it does not seem to break the nested fragment navigate and everything works fine.
In terms of the stack, there is one activity with one child fragment initially. I navigate via the fragment's view models, which triggers the creation of the activities view model. Then on the fragments `OnViewCreated` it will call the navigate to the child nested fragment via its view model.

**Comment by Plac3hold3r** [comment]
@nmilcoff I have created PR #3163 which shows an example of this flow. You can see the changes required in the [custom presenter](https://github.com/MvvmCross/MvvmCross/pull/3163/files#diff-413d5ab70aa020cec87c396971ba1ddbR63).

If there are no objections my suggestion would be to create a PR to add a property to the `MvxFragmentPresentationAttribute` allowing for overriding this visibility check. What do you think?

**Comment by nmilcoff** [comment]
@Plac3hold3r Thanks for that PR! I gave it some runs and it always worked fine.

I would propose instead that we leave the check, but log a warning instead of throwing an exception. I don't think it's necessary to provide a customization path for this :)

**Comment by Plac3hold3r** [comment]
I'm happy with that approach as well. I'll remove the exception and rather log a warning.
