### ISSUE TITLE
Change `MvvmCross.Droid.Support.Fragment` root namespace

### ISSUE THREAD

**Issue by Plac3hold3r** [MvvmCross/MvvmCross#3168]
## 🏗 Enhancement Proposal

I'm not sure if it is an issue with my MvvmCross developer environment setup, but I have intellisense issues with `MvvmCross.Droid.Support.Fragment` namespace and `Fragment` types within presenters and playground samples. Everything compiles fine and there are no runtime issues. But at design time I get the following errors

> Error	CS0118	'Fragment' is a namespace but is used like a type'

Looking at what is using this namespace it seems it's only the inherited resources.

![image](https://user-images.githubusercontent.com/13716738/46976089-b6942980-d0c8-11e8-944d-9e542ce66eeb.png)

### Pitch

I purposed to change the root namespace of `MvvmCross.Droid.Support.Fragment.dll` from `MvvmCross.Droid.Support.Fragment` to `MvvmCross.Droid.Support.Fragments`. Initial testing with the playground sample seems to cause no regression. 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
I think the naming was done because it then followed how the Android Support libraries were named.

**Comment by Plac3hold3r** [comment]
@Cheesebaron do you also get the intellisense errors in Visual Studio 2017 15.8?
