### ISSUE TITLE
How to add additional ViewModels to the IOC container

### ISSUE THREAD

**Issue by brainchest** [MvvmCross/MvvmCross#3173]
Hi All,

I wanted to follow the section "Overriding ViewModel Location/Construction" in the online help on the page "Customizing App and Setup".

Unfortunately, there is no TryLoad method in the default ViewModel locator which I can override. Is there an updated way of this doing?

What I want to achieve:
-> Add viewmodels to the IoC container separately from any magic done by MvvmCross. All ViewModels to be added reside in the same Assembly as the AppStart class (Core project).
-> Load every viewmodel only once (as in the example in the docs)

How can I do that?

**Comment by Cheesebaron** [comment]
Please use [Slack #mvvmcross](https://xamarinchat.herokuapp.com/) or [StackOverflow](https://stackoverflow.com/questions/tagged/mvvmcross) for questions. Github is meant to be used for bugs and feature requests only.

ViewModels are not added to the IoC container.
