### ISSUE TITLE
iOS MvxSimpleTableSource constructor ambiguity/Nib not registered for reuse

### ISSUE THREAD

**Issue by CMorooney** [MvvmCross/MvvmCross#3175]
## 🐛 Bug Report

MvxSimpleTableViewSource does not register Nib for reuse if constructor with only TableView and cellIdentifier is used. I didn't see a note for this as a breaking change so I'm assuming it's a bug right now.

### Expected behavior
* using MvxSimpleTableViewSource constructor `MvxSimpleTableViewSource(UITableView tableView, string cellIdentifier)` should try and register a Nib for reuse using the same cellIdentifier name.
* iOS app should not crash when using this constructor for MvxSimpleTableViewSource if the cellIdentifier and Nib name are identical.

### Reproduction steps
Create a TableView and set the source to a new MvxSimpleTableViewSource, only passing the tableView and the cell identifier into the constructor (where the nib name of your cell and your cell identifier are the same)

### Configuration

**Version:** 6.2.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Thanks for reporting this. I assume this was working before, right? What was the latest version this worked for you?

**Comment by nmilcoff** [comment]
Yes, I think it is. Please go ahead 🙂 and don't hesitate to ask if you have any questions while working on it
