### ISSUE TITLE
CustomAppStart methods called twice

### ISSUE THREAD

**Issue by gjrfytn** [MvvmCross/MvvmCross#3177]
## 🐛 Bug Report

_CustomAppStart_ methods is called twice, because splash screen _OnDestroy_ sets _MvxAppStart.IsStarted_ property to **false**, when application _CurrentTopActivity_ is **null**.

### Expected behavior
I expect _CustomAppStart_ methods to be executed only once.

### Reproduction steps
1. When the application starts, a splash screen is displayed and the methods of the _MvxAppStart_ class are executed, in particular, _NavigateToFirstViewModel_, also the _IsStarted_ flag is set to **true**.
2. _NavigateToFirstViewModel_, in turn, shows the login page (_MvxAppCompatActivity_).
3. When any _MvxAppCompatActivity_ is created, a check for _IsStarted_ is performed. If it is **false**, the application start methods mentioned above are executed.
4. When login page Activity is displayed, the _IsStarted_ flag is already set to **true**, so nothing happens.
5. E.g. system dialog for application permissions shows up in front of login page.
6. The same time, the _OnDestroy_ method of the splash screen is called. _MvxActivityViewExtensions.OnViewDestroy_ checks for _MvxAndroidCurrentTopActivity_ which is **null**, so the _IsStarted_ flag is set to **false**.
7. After login, another page is displayed, so the newly created _MvxAppCompatActivity_ checks for _IsStarted_ and calls _MvxAppStart_ methods again.

The same problem can be reproduced by pushing an application to background at right moment, so _MvxAndroidCurrentTopActivity_ is **null**.

### Configuration

**Version:** 6.2.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
This should be fixed by the linked PR. All AppStart code has been removed from `MvxAppCompatActivity` and the likes.

**Comment by gjrfytn** [comment]
Glad to hear, looking forward to merge!

**Comment by follesoe** [comment]
I have the same issue here https://github.com/MvvmCross/MvvmCross/issues/3287

**Comment by sledderGIT** [comment]
I'm using 6.4 mvvmcross but still facing this issue.
