### ISSUE TITLE
[Android] Bringing application to foreground from Android notification using PendingIntent 

### ISSUE THREAD

**Issue by SHuygh** [MvvmCross/MvvmCross#3180]
## 🐛 Bug Report

When clicking the notification when the app is in the background the app is not brought to the foreground using IMvxNavigationService. However, the navigation has occurred (when the app is brought to the foreground manually the correct view is shown). This was working in version 5.6.3.

### Expected behavior
App is brought to the foreground when notification is clicked.

### Reproduction steps
1. Generate notification with NotificationCompat.Builder
2. Generate a service/broadcastreceiver to handle the navigation
3. SetContentIntent to the Service/Broadcastreceiver
4. Resolve IMvxNavigationService and navigate to ViewModel

### Configuration

**Version:** 6.2.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Thanks for reporting this. Is it possible for you to provide us with a repro sample? An option is to open a PR with some reproduction code to the [Playground project](https://github.com/MvvmCross/MvvmCross/tree/develop/Projects/Playground).

**Comment by martijn00** [comment]
Make sure to init MvvmCross when opening an intent.

```c#
var setup = MvxAndroidSetupSingleton.EnsureSingletonAvailable(ApplicationContext);
setup.EnsureInitialized();
```
