### ISSUE TITLE
Cannot await properly when navigate deep on three view models

### ISSUE THREAD

**Issue by symibsoft** [MvvmCross/MvvmCross#3184]
## 🐛 Bug Report

It is not possible to await the navigation result in viewmodel A when navigating on viewmodel B, if the viewmodel B navigate again to viewmodel C.

If I navigate from the viewmodel A to the viewmodel B and I await the result of the viewmodel B, when the viewmodel B navigates to another viewmodel C, the navigation to the viewmodel C starts, buti the await from the viewmodel B in the viewmodel A returns with unexpected null TResult.

### Expected behavior
The await in the viewmodel A must await the viewmodel B to Close explicitly.

### Reproduction steps

Create an application with 3 viewmodels.

- Navigate from viewmodel A to viewmodel B with await the result.
- Navigate again from viewmodel B to viewmodel C and await the result.

### Configuration

**Version:** 6.2.1

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by agarciasempere** [comment]
I noticed same bug in my app, as soon as you navigate from ViewModel B to C, B returns the result to A, in this case null.

**Configuration**
**Version:** 6.2.1

**Comment by xyashapyx** [comment]
+1 to same issue

**Comment by xyashapyx** [comment]
@symibsoft , @agarciasempere , I've found a workaround. You can just yous MvxNavigationViewModel instead of MvxViewModel and it will work.

**Comment by symibsoft** [comment]
@xyashapyx, thank you for the response. I tried your solution but it does not work for me. The issue is the same.

**Comment by xyashapyx** [comment]
@symibsoft have you changed just one viewModel base class or base class of all view models in your three?

**Comment by symibsoft** [comment]
@xyashapyx, I changed all my viewmodels in order to inherit from MvxNavigationViewModel.

I have a base viewmodel class like this:


` public abstract partial class BaseScreenNotify : MvxNavigationViewModel<string, string>, IEditableObject, IBaseScreenNotify
 {
      public BaseScreenNotify(IMvxLogProvider logProvider, IMvxNavigationService navigationService) : base(logProvider, navigationService)
      {
      }
 }`


All my viewmodels are inheriting from that base class.

**Comment by agarciasempere** [comment]
@xyashapyx, Didn't work for me either, just tried same case as @symibsoft did. Same problem persist. I even noticed on Android that if you put the app on background viewmodel returns null too and you are not able to return result anymore.

**Comment by xyashapyx** [comment]
@symibsoft 
I found one more workaround:)
you can override your 2nd view model ViewDestroy like
public override void ViewDestroy(bool viewFinishing = true)
        {
            base.ViewDestroy(false);
        }

**Comment by agarciasempere** [comment]
> @symibsoft
> I found one more workaround:)
> you can override your 2nd view model ViewDestroy like
> 
> ```
> public override void ViewDestroy(bool viewFinishing = true)
>         {
>             base.ViewDestroy(false);
>         }
> ```

Save me day, works perfectly for me.

Thanks.

**Comment by gentilijuanmanuel** [comment]
> @symibsoft
> I found one more workaround:)
> you can override your 2nd view model ViewDestroy like

> public override void ViewDestroy(bool viewFinishing = true)
>        {
>           base.ViewDestroy(false);
>       }

Also for me. Thanks!

**Comment by symibsoft** [comment]
Thank you guys, I solved with your suggestion.

The viewdestroy override solved the problem in windows platform. I leave the android platform without this override.

**Comment by subwizzll** [comment]
> @symibsoft
> I found one more workaround:)
> you can override your 2nd view model ViewDestroy like
> 
> ```
> public override void ViewDestroy(bool viewFinishing = true)
>         {
>             base.ViewDestroy(false);
>         }
> ```

This is a great workaround, I found assigning viewFinishing to property within ViewModel B still allows base.ViewDestroy to execute when Closing ViewModel B.

Here is some code:

`        private bool destroyView = true;
        public bool DestroyView
        {
            get => destroyView;

            set
            {
                destroyView = value;
                RaisePropertyChanged(() => DestroyView);

            }

        }

        public override void ViewDestroy(bool viewFinishing)
        {
            viewFinishing = DestroyView;
            base.ViewDestroy(viewFinishing);
        }

        private async Task ModifySelectedTray()
        {
            DestroyView = false;
            ProductionTraysModel tray = SelectedTray;
            ProductionTraysModel modifiedTray = await _navigationService.Navigate<BulkScanModifySingleViewModel, ProductionTraysModel, ProductionTraysModel>(new ProductionTraysModel(tray));

            if (modifiedTray != null)
            {
                tray = modifiedTray;
            }
            else
            {
                await Application.Current.MainPage.DisplayAlert("", "No changes made.", "OK");
            }
            DestroyView = true;
        }`
