### ISSUE TITLE
Data binding Xamarin Forms

### ISSUE THREAD

**Issue by bkostic** [MvvmCross/MvvmCross#3187]
Hi all,

Hi,

I just started using Xamarin Forms and Mvvmcross and I'm issuing problem with data binding. Here is my code:

<?xml version="1.0" encoding="UTF-8"?>
<mvxViews:MvxContentPage
    x:TypeArguments="viewModels:FileInfoViewModel"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:mvxViews="clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms"
    xmlns:viewModels="clr-namespace:Test.Core.ViewModels;assembly=Test.Core"
    x:Class="Test.Views.FileInfoPage"
    BindingContext="mvxViewModels:FileInfoViewModel">
    <StackLayout Margin="20" BackgroundColor="White">
		<Entry Text="{Binding Detail.VisitDate}"  HorizontalOptions="FillAndExpand"/>
	</StackLayout>
</mvxViews:MvxContentPage>

public class FileInfoViewModel : MvxViewModel<FileInfoDetail>
{
	private FileInfoDetail _detail;
	public FileInfoDetail Detail
	{
		get => _detail;
		set => SetProperty(ref _detail, value);
	}

	private IMvxNavigationService _navigationService;

	public FileInfoViewModel(IMvxNavigationService navigationService)
	{
		_navigationService = navigationService;
		ColorInfo();
	}

	public override void Prepare(FileInfoDetail parameter)
	{
		Detail = parameter;
		RaisePropertyChanged("Detail");
	}
}

    public class FileInfoDetail
    {
        public string REF { get; set; }
        public DateTime VisitDate { get; set; }
        public string LoadingAddress { get; set; }
        public Client Client { get; set; }
        public string Volume { get; set; }
    }

This is an error I get:

[0:] Binding: 'Detail' property not found on 'mvxViewModels:FileInfoViewModel', target property: 'Xamarin.Forms.Entry.Text'
[0:] Binding: 'Name' property not found on 'Test.Core.Models.FileInfoDetail', target property: 'Xamarin.Forms.Entry.Text'

What I'm I doing wrong?

**Comment by agarciasempere** [comment]
Hi bkostic,

I think you should change BindingContext="mvxViewModels:FileInfoViewModel" for BindingContext="viewModels:FileInfoViewModel". Anyway you don't need to setup the viewmodel as Bindingcontext cause you passed as argument of the page here => x:TypeArguments="viewModels:FileInfoViewModel".

Viewmodel is alredy setup as the BindingContext of the page.

Hope it helps.

**Comment by bkostic** [comment]
Hi agarciasempere,

You are right, it was binding issue. Thanks.
