### ISSUE TITLE
upgrading problems from mvvmcross 4 to mvvmcross 6.2

### ISSUE THREAD

**Issue by burimameti** [MvvmCross/MvvmCross#3189]
## 💬 Questions and Help
1. MvvmCross.Plugins.Fingerprint doesnt work on core project 

After upgrade to 6.2.1 the following code doesnt (this, SetContentView,FindViewbyId, ViewModel) not recognized. I bold them on the following code.
```
base.OnCreate(savedInstanceState);
			WebView webview = new WebView(**this**);
			**SetContentView**(Resource.Layout.ATIBlogView);
			webview = **FindViewById**<WebView>(Resource.Id.AtiBlogwebView);
			webview.SetWebViewClient(new WebViewClient());
			webview.Settings.JavaScriptEnabled = true;
			LoadBlog(webview);
		}

		private async Task LoadBlog(WebView webview)
		{
			string url = await **ViewModel**.GetURL();
			webview.LoadUrl(url.ToString());
		}


```
can you  help me hwo in version 6.2.1 i make this code work

**Comment by martijn00** [comment]
You need to fill an issues at the MvvmCross.Plugins.Fingerprint project.

**Comment by burimameti** [comment]
thank you  martin

**Comment by martijn00** [comment]
It is a 3th party plugin: https://github.com/smstuebe/xamarin-fingerprint
