### ISSUE TITLE
NuGet Package does not contain MvxConsoleSetup in netcoreapp project

### ISSUE THREAD

**Issue by MKuckert** [MvvmCross/MvvmCross#3190]
## 🐛 Bug Report

The `MvvmCross` NuGet Package does not contain the `MvxConsoleSetup` type when referencing from a `netcoreapp` project. The type is correctly exposed when referenced from a .Net Framework project.

### Expected behavior

`MvxConsoleSetup` is also available in `netcoreapp` projects

### Reproduction steps

- Create a new .Net Core App project
- Add reference to `MvvmCross` NuGet Package
- Create a new class `Setup` extending from `MvxConsoleSetup`. The type can't be found.

### Configuration

**Version:** 6.2.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms
- [x] 🖥 .Net Core App

**Comment by martijn00** [comment]
I think we need to add a new `netcoreapp` so we can implement specific `netcoreapp` features instead.
