### ISSUE TITLE
First ViewModel being created twice on Android

### ISSUE THREAD

**Issue by slarti-zak** [MvvmCross/MvvmCross#3196]
## 🐛 Bug Report

When using the default `RegisterAppStart<ViewModel>` and the default `MvxActivity<ViewModel>` for the main launcher, that first viewmodel is created twice.

Maybe this is a regression? A similar bugreport was submitted for a previous version here #2038.

### Expected behavior

The first ViewModel should only be created once.

### Reproduction steps

I have created a sample project to reproduce the bug [here](https://github.com/slarti-zak/MvxDuplicateAppStartViewModel).

### Configuration

**Version:** 6.2.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by cristian-szabo** [comment]
I have the same issue. Any workaround solution?
