### ISSUE TITLE
NullReferenceException in MvxCommandBase in unit tests

### ISSUE THREAD

**Issue by MichaelLHerman** [MvvmCross/MvvmCross#3197]
## 🔙 Regression

Application unit tests did not have to inherit from MvxIoCSupportingTest and could create MvxCommands as part of execution of the unit test.   

MvxCommandBase now calls a method on Mvx.IoCProvider without a null check, throwing an ArgumentNullException if MvxIoCProvider has not been created. 

Adding back the null check is less onerous on consumers than requiring that all consumers migrate all their tests to inherit from MvxIoCSupportingTest.

`Mvx.IoCProvider?.TryResolve<IMvxCommandHelper>(out _commandHelper) != true`

### Old (and correct) behavior
Previously Mvx.TryResolve returned false and did not throw if MvxIoCProvider has not been created. 
 https://github.com/MvvmCross/MvvmCross/blob/ac6c6511cb2962d72fa47553dae009c10ef8fa4e/MvvmCross/Mvx.cs#L42

### Current behavior

MvxCommandBase constructor throws NullReferenceException at
if (!Mvx.IoCProvider.TryResolve<IMvxCommandHelper>(out _commandHelper))

### Reproduction steps
Create a unit test that does not inherit from MvxIoCSupportingTest.  Have the test create a ViewModel that creates a MvxCommand

### Configuration

**Version:** 6.x

**Platform:** 
- [ x ] :iphone: iOS
- [ x ] :robot: Android
- [ x ] :checkered_flag: WPF
- [ x ] :earth_americas: UWP
- [ x ] :apple: MacOS
- [ x ] :tv: tvOS
- [ x ] :monkey: Xamarin.Forms

**Comment by MichaelLHerman** [comment]
#3152

**Comment by Cheesebaron** [comment]
Fixed in #3200

**Comment by projectgoav** [comment]
Any idea when this might be released? I've been hitting this quite a lot recently.

**Comment by amirvenus** [comment]
It is still an outstanding issue

**Comment by Cheesebaron** [comment]
You tell me?
