### ISSUE TITLE
Xamarin forms MvxTabbedPage doesn't render correctly on Android when placement set to bottom

### ISSUE THREAD

**Issue by JoshuaLogue** [MvvmCross/MvvmCross#3201]
## 🐛 Bug Report

I have a MvxTabbedPage with 4 tabs.
When I set the placement to Top everything looks great. However, when it is set to bottom the selected image disappears and the selected Tab appears larger than the others.

### Expected behavior
To look like top tab bar
### Reproduction steps
Create tab page and set android:TabbedPage.ToolbarPlacement="Bottom"
### Configuration

**Version:** 6.2.0

**Platform:** 
- [X] :robot: Android
- [X] :monkey: Xamarin.Forms

![20181113_104014](https://user-images.githubusercontent.com/45001142/48409777-b5d8cc80-e734-11e8-8d6f-96a4dd94c315.jpg)

**Comment by nmilcoff** [comment]
Can you please share some code? The first tab is occupying much more space because it is selected. Are you setting titles to your tabs? If there is an issue here, I would say it's more likely on the Xamarin.Forms side.

**Comment by xufeipyxis** [comment]
![image](https://user-images.githubusercontent.com/33150084/49070646-26203b80-f267-11e8-98c9-3f3df0148b4c.png)
I guess this is the default Xamarin.Forms (or even default Android) implementation, see https://github.com/xamarin/Xamarin.Forms/issues/3083
