### ISSUE TITLE
Tibet and Rio binding didn't work in wpf

### ISSUE THREAD

**Issue by RayMMond** [MvvmCross/MvvmCross#3211]
## 🐛 Bug Report

I followed the The TipCalc tutorial and created a wpf project, then try some awesome Tibet and Rio binding, so I modified Core project and wpf project.

First, doc says i need include an additional step in Setup, but when I add these statements, I got a exception.

    protected override void InitializeLastChance()
    {
        base.InitializeLastChance();
    
        var builder = new MvxWindowsBindingBuilder();
        builder.DoRegistration();        
    }

Second, the binding did't work.

In VM, I add:

    public readonly INC<double> Test = new NC<double>(2);

In View:

    <views:MvxWpfView x:Class="TipCalc.WPF.Views.TipView"
          xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
          xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
          xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
          xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
          xmlns:views="clr-namespace:MvvmCross.Platforms.Wpf.Views;assembly=MvvmCross.Platforms.Wpf"
          xmlns:mvx="clr-namespace:MvvmCross.Platforms.Wpf.Binding;assembly=MvvmCross.Platforms.Wpf"
          mc:Ignorable="d" 
          d:DesignHeight="450" d:DesignWidth="800">
        <Grid>
            <StackPanel Margin="12,0,12,0">
                <TextBlock Text="SubTotal" />
                <TextBox mvx:Bi.nd="Text Test" />
                <TextBox Text="{Binding SubTotal, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
                <TextBlock Text="Generosity" />
                <Slider Value="{Binding Generosity,Mode=TwoWay}" 
                        SmallChange="1" 
                        LargeChange="10" 
                        Minimum="0" 
                        Maximum="100" />
                <TextBlock Text="Tip to leave" />
                <TextBlock Text="{Binding Tip}" />
            </StackPanel>
        </Grid>
    </views:MvxWpfView>

Then I run, the Tibet binding

    <TextBox mvx:Bi.nd="Text Test" />

just not work,

but the regular way

    <TextBlock Text="{Binding Tip}" />

 works fine.

So, I am missing something or it is actually a bug? Any help would be appreciated. 

### Expected behavior

Tibet and Rio binding work fine in Wpf.

### Reproduction steps

Add a Rio Field

    public readonly INC<double> Test = new NC<double>(2);

to file "TipViewModel.cs", in TipCalc tutorial solution, project "TipCalc.Core", and add "Mvvmcross.FieldBinding" nuget package.

In project "TipCalc.WPF", file "TipView.xaml" add a TextBox use Tibet Binding:

    <TextBlock Text="SubTotal" />
    <TextBox mvx:Bi.nd="Text Test" />
    <TextBox Text="{Binding SubTotal, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />

### Configuration

**Version:** 6.2.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by RayMMond** [comment]
After some digging around mvx's setup code, It turns out that the field binding and method binding plugins was not loaded correctly.
Thanks to this rely, https://github.com/MvvmCross/MvvmCross/issues/3171#issuecomment-432809001
> I cannot reproduce. Make sure that the MethodBinding plugin is loaded correctly.
> 
> You can try override `LoadPlugins` in your `Setup`:
> 
> ```cs
> public class Setup : MvxWpfSetup<Core.App>
> {
>     public override void LoadPlugins(IMvxPluginManager pluginManager)
>     {
>         base.LoadPlugins(pluginManager);
> 
>         pluginManager.EnsurePluginLoaded<MvvmCross.Plugin.MethodBinding.Plugin>(true);
>     }
> }
> ```

**Comment by Said1996** [comment]
Hey i am sorry i know this was a very long time ago ... can you show me the complete code of your setup file cuz i can't get it to work

**Comment by RayMMond** [comment]
@Said1996  Sorry, I left the last company, so I can't give you that part of code. But you can ask me if you have any questions.
Did you encounter this problem?

**Comment by Said1996** [comment]
I am sorry, I missed your comment and yes I have the same problem, And I got my setup file as your setup file I don't know how to register setup file in App.cs file.

**Comment by Said1996** [comment]
I am very sorry I missed your comment, I got it now working thanks to your post.
