### ISSUE TITLE
(iOS 12.1) PictureChooser crashes when picture in library is tapped more than once

### ISSUE THREAD

**Issue by ElteHupkes** [MvvmCross/MvvmCross#3215]
## 🐛 Bug Report
When using the `Task<Stream> IMvxPictureChooserTask.ChoosePictureFromLibrary(int, int)` method, a crash occurs if the user double taps the image to choose in their Photos gallery.

The error:

```
SIGABRT: An attempt was made to transition a task to a final state when it had already completed.
```

The stack trace:

```
TaskCompletionSource`1[TResult].SetResult (TResult result)
MvxImagePickerTask+<>c__DisplayClass8_0.<ChoosePictureFromLibrary>b__0 (System.IO.Stream stream, System.String name)
MvxImagePickerTask.HandleImagePick (UIKit.UIImage image, System.String name)
MvxImagePickerTask.Picker_FinishedPickingMedia (System.Object sender, UIKit.UIImagePickerMediaPickedEventArgs e)
UIImagePickerController+_UIImagePickerControllerDelegate.FinishedPickingMedia (UIKit.UIImagePickerController picker, Foundation.NSDictionary info)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

The source of the crash is obvious: the `FinishedPickingImage` event is triggered a second time on the second tap, which leads to the task source to be resolved a second time, which is illegal. I'd love for our users to simply not do this, but two dozen people are unfortunately happily double tapping in the past few days if AppCenter is to be believed. 

I can only reproduce this problem on devices / simulator running iOS 12.1, so I suspect it is the result of a new behavior of the `UIImagePickerController` that is causing this. That also explains why this problem has only started to pop up recently.

### Expected behavior
The second tap should be ignored, and the first picture selected.

### Reproduction steps
Start the picture choosing task using the `Task<Stream> IMvxPictureChooserTask.ChoosePictureFromLibrary(int, int)` method on iOS, on a device or emulator running iOS 12.1. Double-tap any picture.

### Configuration

**Version:** 6.x
**iOS Version: 12.1

**Platform:** 
- [ x ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

#### Solution
Resolving the task with `TrySetResult` rather than `SetResult` would prevent the crash and result in the expected behavior as far as I'm concerned. Using one of the other `ChoosePictureFromLibrary` methods where you have this control over the task yourself is my recommended workaround in the mean time.

**Comment by nmilcoff** [comment]
Thanks for reporting this 👌 and also for incluiding this level of details. Would it be possible for you to raise a PR?

**Comment by ElteHupkes** [comment]
You're very welcome, I'm using MvvmCross daily so the least I can do is try to figure out what's causing the issues that come up instead of complaining about them ;). I think I can create a PR, though I'd have to switch to my severely outdated Windows boot to make sure everything works XD. I may do a couple of Windows things tomorrow, I still have some other issues where I need to create a Playground sample to reproduce so maybe I can catch a couple of birds with one stone.

**Comment by ElteHupkes** [comment]
Created PR: https://github.com/MvvmCross/MvvmCross/pull/3216
