### ISSUE TITLE
MvxCachingFragmentStatePagerAdapter:GetItem NullReferenceException

### ISSUE THREAD

**Issue by SOFSPEEL** [MvvmCross/MvvmCross#3225]
## 🐛 Bug Report

Crash reporting in AppCenter has a high incidence of the following crash, and I finally figured out the root cause.
```
MvxCachingFragmentStatePagerAdapter.GetItem (System.Int32 position, Android.Support.V4.App.Fragment+SavedState fragmentSavedState)
System.NullReferenceException: Object reference not set to an instance of an object
```
It is because of the following line in
https://github.com/MvvmCross/MvvmCross/blob/c95e17b86b0ce01fd394fb1086f009be23ec7959/MvvmCross-AndroidSupport/MvvmCross.Droid.Support.Fragment/MvxCachingFragmentStatePagerAdapter.cs

```
Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity.GetType()
```
and more specifically occurs when Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity returns null.

### Expected behavior

GetItem should gracefully handle Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity being null.
I'm considering the following as a patch for this issue:

```
  public override Fragment GetItem(int position, Fragment.SavedState fragmentSavedState = null)
        {
            var fragInfo = FragmentsInfo.ElementAt(position);
            var fragment = Fragment.Instantiate(_context, FragmentJavaName(fragInfo.FragmentType));

            if (!(fragment is IMvxFragmentView mvxFragment))
                return fragment;

            var activity = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>().Activity;
            if (activity != null && mvxFragment.GetType().IsFragmentCacheable(activity.GetType()) && fragmentSavedState != null)
                return fragment;

            var viewModel = fragInfo.ViewModel ?? CreateViewModel(position);
            mvxFragment.ViewModel = viewModel;

            return fragment;
        }
```

### Reproduction steps

* use MvxCachingFragmentStatePagerAdapter as an adapter for an activity.
* Launch this pager activity
* Immediately hit hard back button (i.e. back out of the app), as this will cause the top activity to be null
* Crash will occur

### Configuration

**Version:** 6.2.1

**Platform:** 
- [ *] :robot: Android

**Comment by Cheesebaron** [comment]
I think the result from:

    var activity = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>().Activity.GetType();

Should be cached, such that it is only resolved once. There shouldn't be a change in Activity while the ViewPager is shown.

**Comment by SOFSPEEL** [comment]
Caching of 
```
var type = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>().Activity.GetType();
```
as long as the caching is done in the constructor, the caching should **not** be done in GetItem as by the time the adapter is filled the activity may already be gone.

I will run some tests to cache in the constructor to ensure that Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>().Activity is always non null there and get back to you, **thanks for you quick feedback**.

**Comment by SOFSPEEL** [comment]
@Cheesebaron your suggestion is a good once, it works with no problem, I have put together a PR: https://github.com/MvvmCross/MvvmCross/pull/3226
