### ISSUE TITLE
First Instance of View Model after Navigation is never disposed of in Android

### ISSUE THREAD

**Issue by SSELLIOTTHOME** [MvvmCross/MvvmCross#3243]
I am not sure if this is by design, but I wanted to confirm that this is correct behaviour. If Viewmodels are kept for as long the view exists then, if I explictly dispose of the MvxActivity/MvxFragmentActivity via the Dispose method of IDisposable, then after calling GC.Collect() in the Destroy method.  the View Model should be disposed of as well. 

However I have found that, the first created instance is always kept in memory. This is easily demonstrable by holding some Weak References to view models after they are created and checking what is null/still alive. It goes against the weak reference technique used in MVXMessenging. 

Setting the DataContext of the MvxActivity to null gets around the problem, 

To get around this I find setting the DataContext of the View works quite well, but is this behaviour by design? I have searched the code but cannot see why it would keep the first instance only.

Have tried this against both MvvmCross 4 and the latest 6.2 and they both act the same way.

Kind Regards

Steven

**Comment by SSELLIOTTHOME** [comment]
Steps to reproduce.

A simple MVVMCross Projects with two MvxFragmentActivities (Activity1 and Activity2)

In the Droid application class (derived from MvxAppCompatApplication or however it is setup, mine is called MainApplication) add the following line.

public System.WeakReference<MvxViewModel> test { get; set; }

Activity1 has a button linked to a Command in Activity1ViewModel that Navigates to Activity2. Before Navigate is called, call GC.Collect. No arguments are passed.

In Activity2.cs, add the following code

 if (((MainApplication)this.Application).test != null)
            {
               GC.Collect();
                MvxViewModel t = null;
                ((MainApplication)this.Application).test.TryGetTarget(out t);
                var x = t;
            }

            ((MainApplication)this.Application).test = new WeakReference<MvxViewModel>    ((MvxViewModel)this.ViewModel);


In Activity2.cs, override on destroy and call Dipose(), and put in the /*commented line*/
this.DataContext = null; 

Run the the app, and drill down to activity2 from activity1, go back and then run it again.

With this.DataContext = null uncommented, x is null on the second drill down. 
With this.DataContext = null is commented, x is not null and available to recieve Messages if it were subscribing.

Strictly speaking it is the previous version of the ViewModel, so the title of this issue is a bit misleading.

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

**Comment by SSELLIOTTHOME** [comment]
I would like to close, it was a misunderstanding on my part.  Thank you for your assistance.
