### ISSUE TITLE
`MvxTableViewSource` ignores multi-item animated replace

### ISSUE THREAD

**Issue by ElteHupkes** [MvvmCross/MvvmCross#3245]
## 🐛 Bug Report
When using a collection that sends a multi-item replace (i.e. it issues a `NotifyCollectionChangedEventArgs` [with this constructor](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedeventargs.-ctor?view=netframework-4.7.2#System_Collections_Specialized_NotifyCollectionChangedEventArgs__ctor_System_Collections_Specialized_NotifyCollectionChangedAction_System_Collections_IList_System_Collections_IList_System_Int32_)) in conjunction with `MvxTableViewSource`, only the first item that is part of that replace is actually reloaded in the table. This is because `MvxTableViewSource` only calls `TableView.ReloadRows(...)` [for the index of the event](https://github.com/MvvmCross/MvvmCross/blob/bdaa09299714d94cf3f2c548a465d994c20d52f0/MvvmCross/Platforms/Ios/Binding/Views/MvxTableViewSource.cs#L144). Further rows don't get reloaded.

### Expected behavior
All items that are part of the replace should be reloaded. Alternatively `false` could be returned to force a reload of all items in the table, but this is unnecessary since we can simply ask the table view to reload all items.

### Reproduction steps
Use a `UITableView` with `MvxTableViewSource` and some sort of collection containing two items. Replace those two items by other items  without triggering events, now trigger a `NotifyCollectionChangedEvent` with the args of the aforementioned constructor. The table view will only reload the first item.

### Configuration

**Version:** 6.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

### Solution
The issue can be resolved by replacing:
```
var indexPath = NSIndexPath.FromRowSection(args.NewStartingIndex, 0);
TableView.ReloadRows(new[]
{
    indexPath
}, ReplaceAnimation);
```

with

```
var indexPaths = Enumerable.Range(args.NewStartingIndex, args.NewItems.Count)
    .Select(index => NSIndexPath.FromRowSection(index, 0)).ToArray();
TableView.ReloadRows(indexPaths, ReplaceAnimation);
```

in `MvxTableViewSource`. I can create a PR if this is seems appropriate to you as well.

**Comment by Cheesebaron** [comment]
If you have time, you are welcome to open a Pull Request with a fix.

**Comment by ElteHupkes** [comment]
Thanks @martijn00! This completely slipped my mind.
