### ISSUE TITLE
How to use MvvmCross with two core libraries

### ISSUE THREAD

**Issue by parmendrahsc** [MvvmCross/MvvmCross#3261]
## 💬 Questions and Help
How to use MvvmCross with two core libraries
Is there any mvvmcross sample project available with two core library and few view and vms are in first library and rest in second library.
I got the exception, like view can't be load. We can find the VMs but cant load view

Stackoverfolw: https://stackoverflow.com/questions/54210583/how-to-use-mvvmcross-with-two-core-libraries?noredirect=1#comment95256289_54210583

**Comment by parmendrahsc** [comment]
I am doing same as MvvmCross with two core libraries but unable to build my project. Could you please provide me any code or sample project. I have attached my sample project.

https://drive.google.com/file/d/10Oa3blR2K3f18v-nc2DFPqn2ldc9pNvu/view?usp=gmail

**Comment by RayMMond** [comment]
first let's say you have two core lib, __LibA__ and __LibB__. In __LibA__, you have a __ViewModelX__. In __LibB__ you have a __ViewModelY__.

if you want to use __ViewModelY__ in your view, you should create a custom “Setup.cs", then override the virtual method "GetViewModelAssemblies()"

    public class YourSetupClass : MvxWpfSetup<YourCoreLibApp>
    {
        public override IEnumerable<Assembly> GetViewModelAssemblies()
        {
            return base.GetViewAssemblies().Union(new[]
            {
                Assembly.GetAssembly(typeof(LibB.ViewModelY)),
            });
        }
    }

then register setup in __App.xaml__:

    public partial class App
    {
        public App()
        {
            this.RegisterSetupType<YourSetupClass>();
        }
    }

and there is more info about [Providing additional View and ViewModel Assemblies](https://www.mvvmcross.com/documentation/advanced/customizing-using-App-and-Setup?scroll=320#providing-additional-view-and-viewmodel-assemblies)

**Comment by nickrandolph** [comment]
Thanks @RayMMond

**Comment by parmendrahsc** [comment]
Thanks you @RayMMond 
@nickrandolph, I have two core lib, LibA and LibB. In LibA, I have a ViewModelX. In LibB I have a ViewModelY and ViewModelZ.
ViewModelX is my LoginView (startup) and after that I want to navigate ViewModelY and then navigate ViewModelZ.

When I try to navigate ViewModelX to ViewModelY, I got exception

NOTE: Can I try to create another another Android project which have all views which is related to LibB

**Comment by parmendrahsc** [comment]
Unable to solve my issue please have a look my attached Sample: https://drive.google.com/file/d/0BzYwzj9G2GuwWFkwcmY0S3d5RHhmeVVOVzNyelo5OTN0T1Jz/view?usp=drivesdk

**Comment by nickrandolph** [comment]
Hi, can I ask that you use the Playground sample to repro the issue. You should be able to step through the code and work out why it's not finding your view.
