### ISSUE TITLE
Cannot Resolve current top activity

### ISSUE THREAD

**Issue by zmklark** [MvvmCross/MvvmCross#3274]
## 🐛 Bug Report

ShowViewCommand = new MvxAsyncCommand(async () =>
            {
                var result = await _navigationService
                    .Navigate<FirstViewModel, FirstViewParameter, FirstViewReturnResult>(new FirstViewParameter()
                    {
                        Paras = "test"
                    });
                if(await _navigationService.CanNavigate<SecondViewModel>())
                    await _navigationService.Navigate<SecondViewModel>();//cannot navigate SecondViewModel with [WARN]  (MvvmCross.Logging.MvxLog) Cannot Resolve current top activity
            });
### Expected behavior
 [WARN]  (MvvmCross.Logging.MvxLog) Cannot Resolve current top activity
### Configuration

**Version:** 6.2.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
When does this happen? Can you provide more information on how to reproduce?

**Comment by zmklark** [comment]
first view
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:local="http://schemas.android.com/apk/res-auto"
	android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
	<Button
		android:text="nav to second view"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:minWidth="25px"
		android:minHeight="25px"
		android:id="@+id/button1"
		local:MvxBind="Click ShowSecondViewCommand"
		android:layout_marginTop="54dp" />

</LinearLayout>
```

```
using System.Runtime.CompilerServices;
using MvvmCross.Commands;
using MvvmCross.Navigation;
using StarWarsSample.Core.Models;

namespace StarWarsSample.Core.ViewModels
{
    public class FirstViewModel:BaseViewModel
    {
        private readonly IMvxNavigationService _navigationService;

        public FirstViewModel(IMvxNavigationService navigationService)
        {
            _navigationService = navigationService;

            ShowSecondViewCommand = new MvxAsyncCommand(async () =>
                {
                   var second = await _navigationService.Navigate<SecondViewModel, SecondViewParameter, SecondViewReturnResult>(
                        new SecondViewParameter());

                    //[WARN](MvvmCross.Logging.MvxLog) Cannot Resolve current top activity
                    //cannot nav to ThirdViewModel
                    await _navigationService.Navigate<ThirdViewModel>();
                });

        }

        public IMvxAsyncCommand ShowSecondViewCommand { get; private set; }
    }
}
```

second view
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:local="http://schemas.android.com/apk/res-auto"
	android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
	<Button
		android:text="Close View"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:minWidth="25px"
		android:minHeight="25px"
		android:id="@+id/button1" 
	local:MvxBind="Click CloseViewCommand"
	android:layout_marginTop="54dp"/>

</LinearLayout>
```


```
using MvvmCross.Commands;
using MvvmCross.Navigation;
using StarWarsSample.Core.Models;

namespace StarWarsSample.Core.ViewModels
{
    public class SecondViewModel:BaseViewModel<SecondViewParameter,SecondViewReturnResult>
    {
        private readonly IMvxNavigationService _navigationService;
        public override void Prepare(SecondViewParameter parameter)
        {
            //throw new System.NotImplementedException();
        }

        public SecondViewModel(IMvxNavigationService navigationService)
        {
            _navigationService = navigationService;

            CloseViewCommand = new MvxAsyncCommand(async () =>
                await _navigationService.Close(this,new SecondViewReturnResult()));
        }

        public IMvxAsyncCommand CloseViewCommand { get; private set; }
    }
}
```

third view
```
namespace StarWarsSample.Core.ViewModels
{
    public class ThirdViewModel:BaseViewModel
    {
        
    }
}
```

first view cannot nav to third view when close second view!

**Comment by ornolisvt** [comment]
I have the same issue, if you navigate to a viewmodel that returns response and immediately after the response you navigate to another side or close the current viewmodel, navigation does not occur. I checked the Presenter and it turns out that in the instant of time when you close one view and try to navigate to another or close the current one, CurrentActivity in the CloseActivity method becomes null


            var currentView = CurrentActivity as IMvxView;

            if (currentView == null) 
            {
                MvxLog.Instance.Warn("Ignoring close for viewmodel - rootframe has no current page");
                return Task.FromResult(false);
            };

            if (currentView.ViewModel != viewModel)
            {
                MvxLog.Instance.Warn("Ignoring close for viewmodel - rootframe's current page is not the view for the requested viewmodel");
                return Task.FromResult(false);
            }

            CurrentActivity.Finish();
            return Task.FromResult(true);
        }

To reproduce error:

`
          var navService = Mvx.IoCProvider.Resolve<IMvxNavigationService>();
          var result = await navService.Navigate<ViewModel, RequestModel, ResponseModel>(new RequestModel { Id = 1 });
          await navService.Close(this);
`

**Comment by Cheesebaron** [comment]
@ornolisvt what version of MvvmCross are you on? Latest 6.4.2 has some improvements with regards to reporting of CurrentActivity.

**Comment by ornolisvt** [comment]
I'm in the last 6.4.2

**Comment by Cheesebaron** [comment]
Need better repro steps. Preferably a small sample app.

**Comment by DamienDoumer** [comment]
This issue persists in version 7 of MVVMCross, I still have it.

**Comment by Cheesebaron** [comment]
@DamienDoumer need a reproducible sample, otherwise I cannot help.

**Comment by DamienDoumer** [comment]
@Cheesebaron  ok, 
I have a little question please. I might be using the framework badly. 
When navigating from a normal activity to an activity with multiple fragments. Should I call the navigationtion service and use the type of the mainactivity's viewmodel (the activity containing the fragments) or I should use the type of the child fragment's viewmodel to which I want to navigate ? 

I have this issue in an app which implements login flow ( an authentication activity is displayed, once authentication is completed, a main activity is navigated to, with children fragments in a navigation exactly [as this](https://github.com/MvvmCross/MvvmCross/blob/master/Projects/Playground/Playground.Droid/Activities/RootView.cs)).
