### ISSUE TITLE
Xamarin.Android app startup without splash screen

### ISSUE THREAD

**Issue by IlyaLavrov97** [MvvmCross/MvvmCross#3276]
For android startup we create SplashScreen and navigate to initial VM from it. I want to reduce startup time and use launcher theme method for it (https://plus.google.com/+AndroidDevelopers/posts/Z1Wwainpjhd). Do we have workaround for this?

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This is already possible. Just override https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatActivity.cs#L97 and do a navigate yourself.

**Comment by tsackey** [comment]
> This is already possible. Just override https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatActivity.cs#L97 and do a navigate yourself.
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/3919206?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[MvvmCross/MvvmCross](https://github.com/MvvmCross/MvvmCross)**The .NET MVVM framework for cross-platform solutions, including Xamarin.iOS, Xamarin.Android, Windows and Mac. - MvvmCross/MvvmCross

Hi, I need to do this but getting 404 for your link
