### ISSUE TITLE
Where can i find legacy docs for ver 4? 

### ISSUE THREAD

**Issue by MikhailNatalenko** [MvvmCross/MvvmCross#3277]
## 💬 Questions and Help

I need to make a quick assist for some project, that built on 4 version of MVVM Cross. So I've stucked with this version. and it's pretty difficult to understand MVVM Cross (i didn't learn it before) without actual docs.

Where can i found legacy docs? 
I can't upgrade app for newer versions (partly it's because of QR-code scanner, that needs this version)

**Comment by Cheesebaron** [comment]
There are no docs for version 4. We added docs later.

You can find the code for version 4 here: https://github.com/MvvmCross/MvvmCross/tree/4.4.0
