### ISSUE TITLE
MvxRecycler view must not post NotifyDataSetChanged on MainLooper

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#3295]
## 🔙 Regression

Introduced by the fix for #2144

There may be a delay between the change of the source collection and the calls to NotifyItemXXX methods of the adapter, resulting in desynchronizations of the recycler's view and its datasource, thus generating random crashes when the recyclerview try to load a removed item.

### Old (and correct) behavior

When an ObservableCollection is structurally updated in a viewmodel, and this collection is bound to the ItemsSource of a RecyclerView's adapter, the adapter subscribes to INotifyCollectionChanged and dispatch these events  to NotifyDataSetChanged().

If the viewmodel's collection is changed on a worker thread, the app will crash. But there will be no delay between the change of the collection and the recycler's view notifications.

### Current behavior

To prevent crashes when a viewmodel's collection is changed on a worker thread, the adapter posts the change on the MainLooper. This introduces the delay explained at the start of this bug report and leads to random crashes.

```
            if (Looper.MainLooper == Looper.MyLooper())
            {
                NotifyDataSetChanged(e);
            }
            else
            {
                var h = new Handler(Looper.MainLooper);
                h.Post(() => NotifyDataSetChanged(e));
            }
```

### Reproduction steps

1. Connect an ObservableCollection to an MvxRecyclerView, add lots of items.
2. Remove an item every second in your viewmodel from a worker thread (timer)
3. scroll the list in the app, it will crash at some point.

### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
Thanks for reporting. Can you please submit a PR fixing your feature request (#2144) and this "regression" issue?

**Comment by softlion** [comment]
Well the PR will not fix the issue completly, as i still have random cases where the recyclerview try to fetch an item that has been deleted (most often at the end of the list). But it's less frequent with this fix.

**Comment by softlion** [comment]
Ok I had another different issue that leads to the problem. But this PR is still needed as all changes to the ItemsSource (ie: adapter) must be synchronized with the RecyclerView's layout manager and immediate.

And to be able to do this it must be done on main thread. So this code have to be removed, or updated with a code that test is it's the main thread, and throws a detailed stack trace.
