### ISSUE TITLE
Documentation issues in viewmodel-lifecycle.md

### ISSUE THREAD

**Issue by indyjason79** [MvvmCross/MvvmCross#3301]
You documenation in `viewmodel-lifecycle.md` does not show you need to override the Prepare and Initialize methods. For instance, the example on the page says to use: 

`public async Task Initialize()`

which is not correct in the latest version of MvvmCross (v6.2.3). The `MvxViewModel` class clearly shows it's a virtual method so your documentation should be updated to:

`public override async Task Initialize()`

This is just 1 example of bad information in your documentation. Please see references to the Prepare method as it is also incorrect.

**Comment by martijn00** [comment]
Can you make a PR to fix this?
