### ISSUE TITLE
Xamarin.Forms UWP backnavigation blocks previously pressed button.

### ISSUE THREAD

**Issue by pavloss** [MvvmCross/MvvmCross#3306]
## 🐛 Bug Report

When navigating from one viewmodel to another by way of pressing a button and binding a command to it.
The same button becomes "stuck" or permanently pressed when navigating back to the page using the UWP back button or `await NavigationService.Close(this);` in the second viewmodel.

[Example](https://i.imgur.com/D5HBEqF.png)

### Expected behavior

Button is unobstructed on back navigation.

### Reproduction steps

Navigate to one viewmodel and then back using the UWP back button or `await NavigationService.Close(this);` . Sometimes it works sometimes it doesn't. Was able to reproduce this in a test project in a lower frequency than our main project.

### Configuration

**Version:** 6.2.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by pavloss** [comment]
If needed I can provide a sample project.

**Comment by martijn00** [comment]
@pavloss Please provide the sample in the current playground project and make a PR to it.
