### ISSUE TITLE
How to change the color of the minimize, maximize, close buttons on a MvvmCross.Forms app

### ISSUE THREAD

**Issue by shudson302** [MvvmCross/MvvmCross#3307]
I am setting both this in my styles:

            <Style ApplyToDerivedTypes="true" TargetType="NavigationPage">
                <Setter Property="BarBackgroundColor" Value="{StaticResource Key=AccentColor}"/>
                <Setter Property="BarTextColor" Value="{StaticResource Key=WhiteColor}"/>
            </Style>

and in UWP:

            var appView = Windows.UI.ViewManagement.ApplicationView.GetForCurrentView();
            var formattableTitleBar = appView.TitleBar;
            formattableTitleBar.ButtonBackgroundColor = Color.FromArgb(0,0,127,178);
            formattableTitleBar.BackgroundColor = Color.FromArgb(0, 0, 127, 178);
            formattableTitleBar.ForegroundColor = Colors.White;

But neither is changing the color of the minimize, maximize, close buttons.  They are always black.  Could you please let me know how to change the colors of these buttons?

**Comment by Cheesebaron** [comment]
How would you do it in a non-MvvmCross Xamarin.Forms App?

**Comment by shudson302** [comment]
I figured it out.  On UWP I had to set 

            formattableTitleBar.ButtonForegroundColor = Colors.White;


Thanks!
