### ISSUE TITLE
Navigation not working on iOS

### ISSUE THREAD

**Issue by ShashankSingh234** [MvvmCross/MvvmCross#3309]
Hi, I am trying to navigate back from a SecondViewModel to FirstViewModel and I am getting a warning as (MvvmCross.Logging.MvxLog) Ignored attempt to close the window root (ViewModel type: SecondViewModel in iOS while it is working perfectly on Android.

Here are my ViewModels

**FirstViewModel.cs**

public class FirstViewModel : MvxViewModel
{
    private readonly IMvxNavigationService _navigationService;
    public FirstViewModel(IMvxNavigationService navigationService)
    {
        _navigationService = navigationService;
    }

    private IMvxAsyncCommand _navigateCommand;
    public IMvxAsyncCommand NavigateCommand
    {
        get
        {
            _navigateCommand = _navigateCommand ? ? new MvxAsyncCommand(NavigationMethod);
            return _navigateCommand;
        }
    }

    private async Task NavigationMethod()
    {
        var result = await _navigationService.Navigate<SecondViewModel,
         SecondViewModelArgs, SecondViewReturnArgs>(new SecondViewModelArgs
         {
             TextToSecondViewModel = Text
         });
        Text = result.textToFirstViewModel;
    }
}

**SeconViewModel.cs**

public class SeconViewModel : MvxViewModel<SecondViewModelArgs, SecondViewReturnArgs>
{

    private readonly IMvxNavigationService _navigationService;+
    public ListExampleViewModel(IMvxNavigationService navigationService)
    {
        _navigationService = navigationService;
    }

    public IMvxCommand NavigateBackCommand => new MvxCommand(NavigateBack);

    private void NavigateBack()
    {
        _navigationService.Close(this, new SecondViewReturnArgs { textToHomeViewModel = Text });
    }
}

Please tell me what did I implemented wrong here.

Thanks

**Comment by b099l3** [comment]
From this warning:
> Ignored attempt to close the window root (ViewModel type: SecondViewModel)

It sounds like you are trying to close the root view in iOS. You can see the source for that error [here](https://github.com/MvvmCross/MvvmCross/blob/a51c7648f10a79d9fabee25ff34711b1440fefd2/MvvmCross/Platforms/Ios/Presenters/MvxIosViewPresenter.cs#L357)

iOS needs a root view to navigate to and from, so you cant close this. Its the same as having a single view app and trying to close the view.

To investigate this more we would need to see what you are doing in the iOS views, e.g., Do you have any [PresentationAttributes](https://www.mvvmcross.com/documentation/platform/ios/ios-view-presenter?scroll=539#presentation-attributes) set on the view.

I would assume that your `FirstViewModel` is the root to begin with then you present the `SecondViewModel` and close it. You may want a modal view instead so todo that set [this attribute](https://github.com/MvvmCross/MvvmCross-Samples/blob/c5a01b9f5a32367fe77b2dea34f49442a331cbf3/StarWarsSample/StarWarsSample.iOS/Views/StatusView.cs#L14) on the `SecondView`

Other than that we will need more info.

**Comment by arvindhindyar** [comment]
> From this warning:
> 
> > Ignored attempt to close the window root (ViewModel type: SecondViewModel)
> 
> It sounds like you are trying to close the root view in iOS. You can see the source for that error [here](https://github.com/MvvmCross/MvvmCross/blob/a51c7648f10a79d9fabee25ff34711b1440fefd2/MvvmCross/Platforms/Ios/Presenters/MvxIosViewPresenter.cs#L357)
> 
> iOS needs a root view to navigate to and from, so you cant close this. Its the same as having a single view app and trying to close the view.
> 
> To investigate this more we would need to see what you are doing in the iOS views, e.g., Do you have any [PresentationAttributes](https://www.mvvmcross.com/documentation/platform/ios/ios-view-presenter?scroll=539#presentation-attributes) set on the view.
> 
> I would assume that your `FirstViewModel` is the root to begin with then you present the `SecondViewModel` and close it. You may want a modal view instead so todo that set [this attribute](https://github.com/MvvmCross/MvvmCross-Samples/blob/c5a01b9f5a32367fe77b2dea34f49442a331cbf3/StarWarsSample/StarWarsSample.iOS/Views/StatusView.cs#L14) on the `SecondView`
> 
> Other than that we will need more info.

Thank you very much. After working for hours, I got this answer.
