### ISSUE TITLE
MvvmCross.Platforms.iOS.MvxIosSystem MissingMethosException

### ISSUE THREAD

**Issue by LiamLamb** [MvvmCross/MvvmCross#3313]
Hi all, 

I'm running into an issue setting up an iOS project using MvvmCross **6.2.3**. 
We've been using MvvmCross for Cross mobile development for a while now - but the company's app has been stuck on **4.4.0** for too long. I'm in the process of migrating our apps to the latest version of MvvmCross, and am running into some issues on iOS.

Currently when I build my project, i get the following error:
**Can't resolve the reference 'System.String[] System.String::Split(System.Char,System.StringSplitOptions)', referenced from the method 'System.Void MvvmCross.Platforms.Ios.MvxIosSystem::BuildVersion()' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. (MT2101)**

To test behaviour, i went to project options and set the Linker Behaviour to : **Don't Link**. And the application builds. I still get the same issue when I get to the application delegate though:

```
[Register("AppDelegate")]
    public partial class AppDelegate : MvxApplicationDelegate<Setup, App>
    {
        UIWindow _window;

        public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
        {
            var result = base.FinishedLaunching(application, launchOptions);

           

            return result;
        }
}

```
When hitting the base.FinishedLaunching method, it get the following error:

>  at MvvmCross.Platforms.Ios.MvxIosSystem..ctor () [0x00006] in C:\\projects\\mvvmcross\\MvvmCross\\Platforms\\Ios\\MvxIosSystem.cs:17 \n  at MvvmCross.Platforms.Ios.Core.MvxIosSetup.CreateIosSystemProperties () [0x00000] in C:\\projects\\mvvmcross\\MvvmCross\\Platforms\\Ios\\Core\\MvxIosSetup.cs:85 \n  at MvvmCross.Platforms.Ios.Core.MvxIosSetup.RegisterPlatformProperties () [0x00000] in C:\\projects\\mvvmcross\\MvvmCross\\Platforms\\Ios\\Core\\MvxIosSetup.cs:80 \n  at MvvmCross.Platforms.Ios.Core.MvxIosSetup.InitializePlatformServices () [0x00000] in C:\\projects\\mvvmcross\\MvvmCross\\Platforms\\Ios\\Core\\MvxIosSetup.cs:72 \n  at MvvmCross.Core.MvxSetup.InitializePrimary () [0x00052] in C:\\projects\\mvvmcross\\MvvmCross\\Core\\MvxSetup.cs:74 \n  at MvvmCross.Core.MvxSetupSingleton.StartSetupInitialization () [0x0000a] in C:\\projects\\mvvmcross\\MvvmCross\\Core\\MvxSetupSingleton.cs:181 \n  at MvvmCross.Core.MvxSetupSingleton.EnsureInitialized () [0x00017] in C:\\projects\\mvvmcross\\MvvmCross\\Core\\MvxSetupSingleton.cs:102 \n  at MvvmCross.Platforms.Ios.Core.MvxApplicationDelegate.FinishedLaunching (UIKit.UIApplication application, Foundation.NSDictionary launchOptions) [0x0001d] in C:\\projects\\mvvmcross\\MvvmCross\\Platforms\\Ios\\Core\\MvxApplicationDelegate.cs:45 \n  at Company.Mobile.UK.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication application, Foundation.NSDictionary launchOptions) [0x00001] in /Users/CompanyEngineer/Documents/_git2/Central/Portal/Mobile/Company.Mobile.UK.iOS/AppDelegate.cs:21 \n  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:79 \n  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:63 

This makes me think that project that i am referencing in the launching iOS project has packages that I don't have in the launching application ? But it seems be an issue with Linq. Which i have in the launching application project.

I've successfully migrated our Android, and our core projects over the last week. The only steps left are just the iOS native projects.
We have a few "Native core" projects that hold shared iOS view logic used for different iOS application used for different countries. The structure is as follows:

|- Solution Level:
|-- Application Folder
|--- Mobile.Core.iOS
|--- Mobile.iOS
|--- Mobile.UK.iOS
|--- Mobile.NZ.iOS
|--Mobile.Core
|--Mobile.Data
|--Mobile.Data.iOS
|--Mobile.Alert
|--Mobile.Alert.iOS

The **Mobile.Core** is obviously a shared library. This is where the View Model logic, app start and so on sit.
The **Mobile.Data**, **Mobile.Alert** projects are simple projects exposing interfaces for alerts and SQL setup consumed by platform specific implementations in the **Alert.iOS** and **Data.iOS** projects.

It is my understanding that packages that are used in **any** "plugin" project like **Alert.iOS**, and **Data.iOS** also need referenced in the launching application in order to compile properly. 

Do you have any ideas what this could be ? And if not, can I provide with anymore information in order to replicate this ?

Many thanks for your time guys
Liam

**Update**
Hi all, 
I tracked this issue down to be local to this file:
**https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Ios/MvxIosSystem.cs**

My initial thoughts were that I was somehow missing dlls in my iOS project that were needing for the MvvmCross.Platform.iOS to do it's job.
I then cloned the Samples project and ran the **Star Wars** project on the same simulator. When doing so, I noticed the Start Wars project was running on an earlier version of the MvvmCross packages (**6.2.0**). I ran the app on these packages, and everything works fine.

I then updated the packages to recreate the behaviour in **my** app.
I then built the Star Wars application again using **6.2.3** MvvmCross packages, and I got this same issue as in my app. It seems be local to the **6.2.3** release. 

Any thoughts on this ?

Thanks again,
Liam

**Comment by Cheesebaron** [comment]
I cannot reproduce your issue. What version of the Xamarin tools are you running?

**Comment by LiamLamb** [comment]
Good shout! 

A few updates were needed indeed. Thanks for your help
