### ISSUE TITLE
MvvmCross.Forms - creation of NavigationPage for modal

### ISSUE THREAD

**Issue by jaroslavrehorka** [MvvmCross/MvvmCross#3315]
## 🏗 Enhancement Proposal

Currently, if I have a modal with annotation _WrapInNavigationPage = true_, the NavigationPage is created in place: https://github.com/MvvmCross/MvvmCross/blob/a51c7648f10a79d9fabee25ff34711b1440fefd2/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L519 

Instead of using method CreateNavigationPage:
https://github.com/MvvmCross/MvvmCross/blob/a51c7648f10a79d9fabee25ff34711b1440fefd2/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L148
This has negative consequences in terms of unexpected behaviour of NavigationPage, in case you have your own implementation.

### Pitch

The change would unify the creation of NavigationPage and would bring the same behaviour for NavigationPage created for modal and for other pages. This is especially useful, when you use plugins like Iconize, that provide icon font and require to use NavigationPage provided by the plugin.

Also creation of navigation page in method ShowModal
https://github.com/MvvmCross/MvvmCross/blob/a51c7648f10a79d9fabee25ff34711b1440fefd2/MvvmCross.Forms/Presenters/MvxFormsPagePresenter.cs#L497
cannot be easily overiden.

Proposed change:
`await FormsApplication.MainPage.Navigation.PushModalAsync(new NavigationPage(page)); `

to

`await FormsApplication.MainPage.Navigation.PushModalAsync(CreateNavigationPage(page)); `

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by mkshiblu** [comment]
Hi, do you know how to use a CustomNavigationPage instead of the default NavigationPage which extends the NavigationPage? I just need to expose some additional properties to the subclass.
