### ISSUE TITLE
Tizen 4.0

### ISSUE THREAD

**Issue by GerhardKreuzer** [MvvmCross/MvvmCross#3317]
Hi,
I want to start wit mvvmCross and get the repository into my VS2017. Compilation turns out, that there is some issue with Tizen 4.0 dependencies. The nget package is installed but it doesnt work ou.
Any ideo?

**Comment by martijn00** [comment]
You need to install the SDK that you download from their website i think. Alternatively you can use: https://github.com/MvvmCross/MvvmCross/blob/develop/Directory.build.props#L44 to only compile Android or something
