### ISSUE TITLE
MvxPageViewController race condition

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross#3324]
## 🔙 Regression

In version 6.2.3 there is fix to async MvxViewModel.Initialize where the creation of the ViewController (in IOS) is no longer delayed until after method returns (in case of await).

This introduces the possibility that ViewDidLoad is called on the ViewController before the ViewModel is fully initialized.

MvxPageViewController has a call to InitializePaging in ViewDidLoad and if the ViewModel is not fully initialized then this function call can fail for many reasons in the subsequent call to GetDefaultViewModel.

### Old (and correct) behavior

MvxPageViewController.InitializePaging was always called after the ViewModel was fully initialized.

### Current behavior

MvxPageViewController.InitializePaging is sometimes called before the ViewModel is fully initialized.

### Reproduction steps

It is a race condition but if a long enough await is added to ViewModel.Initialize then it should be possible to reproduce the issue, like

await Task.Delay(5000)

### Configuration

**Version:** 6.2.3

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
I guess the solution here would be to use the MvxNotifyTask which Initialize runs in to figure out whether the ViewModel has finished initializing.

**Comment by martijn00** [comment]
This should be fixed when https://github.com/MvvmCross/MvvmCross/issues/3230 is done i think?

**Comment by erviem99** [comment]
The problem is also present in a standard MvxViewController in ViewDidLoad where Initialize is not always completed when the call to base.ViewDidLoad() returns.
