### ISSUE TITLE
How can we do IntuneMAM Activity inherit to MVX Activity

### ISSUE THREAD

**Issue by sureshbabu4** [MvvmCross/MvvmCross#3327]
### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Duplicate of #3328

**Comment by sureshbabu4** [comment]
@martijn00,Thanks a lot for Good explaination
