### ISSUE TITLE
MvvmCross.Plugin.PictureChooser throws exception with 6.2.3 on device

### ISSUE THREAD

**Issue by markuspalme** [MvvmCross/MvvmCross#3329]
## 🔙 Regression

IMvxPictureChooserTask throws an exception on device after an upgrade to 6.2.3.

### Old (and correct) behavior
Using the `IMvxPictureChooserTask` in iOS with this call brought up the camera:
`mvxPictureChooserTask.TakePicture(1024, 80);`

### Current behavior
With 6.2.3 the same call throws an exception
`missing source event info in MvcWeakEventSubscription. Parameter name: sourceEventInfo`

### Fix
I was able to fix the problem by adding these lines to `LinkerPleaseInclude.cs`:

   ```
public void Include(UIImagePickerController uIImagePickerController)
{
       var x = uIImagePickerController.SourceType;
       uIImagePickerController.FinishedPickingMedia += (s, e) => { };
       uIImagePickerController.FinishedPickingImage += (s, e) => { };
       uIImagePickerController.Canceled += (s, e) => { };
}
```
Should these lines be added to https://github.com/MvvmCross/MvvmCross/blob/master/ContentFiles/iOS/LinkerPleaseInclude.cs?

### Configuration

**Version:** 6.2.3

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR for this to add it?
