### ISSUE TITLE
Clarify onNewIntent in Android

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#334]
From #294 

The onNewIntent is triggered when you have an acitivy attributed with

```
  [Activity(LaunchMode = LaunchMode.SingleTask)]
```

(or SingleTop) and requesting that activity for the second time (eg. by calling ShowViewModel).

My main activity is a single-top activity and I have not experienced any problems since commenting out this exception.

**Comment by nmilcoff** [comment]
The framework has now lived for more than 4 years without modifying how `OnNewIntent` works. 

I think we should not change how this works. We can improve the [current output message](https://github.com/MvvmCross/MvvmCross/blob/6746cc292834628149f23ee0d17e1e9998390b15/MvvmCross/Droid/Droid/Views/MvxActivityViewExtensions.cs#L70) into something more informative and maybe leave a note on the docs.

If nobody disagrees with this within some days, I'll make the change.
