### ISSUE TITLE
Switch over to AndroidX from Android Support packages

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#3344]
## 🚀 Feature Requests

AndroidX is coming and it seems like there is some traction from Xamarin in their components repo.

AndroidX is the next Android Support with different structure, better namespaces and semantic versioning. However, most of the classes are the same old, so the API has probably not changed much.

At some point the Support packages are going to be deprecated, and developers are going to expect us to switch to AndroidX for our support stuff anyways. So this has to be done either way.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by softlion** [comment]
There is a new ViewPager2 class based on RecyclerView

**Comment by wondering639** [comment]
I am just getting started with Xamarin (not Xamarin Forms) and doing some research on the available MVVM frameworks. What is the current status on this issue? Is there any work on it? I fear this could be an issue in the future if it's not worked on? For Xamarin itself, AndroidX is available at least as preview: https://devblogs.microsoft.com/xamarin/androidx-for-xamarin/

**Comment by Cheesebaron** [comment]
We are going to make the switch to Android X. However, we cannot release stable packages as long as we depend on something marked pre-release.

**Comment by wondering639** [comment]
Glad to hear that, thanks for the feedback!

**Comment by cristianvasuica** [comment]
Hello, @Cheesebaron! Is there any work for 7.0 done so far? I would like to use MVVMCross in a Xamarin with AndroidX. 
Maybe you have a branch for the 7.0 version... For migrating to AndroidX there is a NuGet package (Xamarin.AndroidX.Migration) that can be used and Msft said that will also release sometime this year a tool in Visual Studio to help with the migration.

**Comment by softlion** [comment]
The migration package should be used in your final app. So it should also work fine with mvvmcross.

**Comment by wondering639** [comment]
Any news on this? RC1 for the bindings seems to be coming: https://github.com/xamarin/AndroidX/issues/27
