### ISSUE TITLE
How to do the Microsoft Intune Migration or Integration in Xamarin android & iOS with MVVM Cross

### ISSUE THREAD

**Issue by sureshbabu4** [MvvmCross/MvvmCross#3346]
## 💬 Questions and Help

Hi Developer Folks,

I am not able to do the Migration or integration of Microsoft Intune in Xamarin android & iOS with MVVM Cross,Please provide suggested Links, if not able to do in MVVM Cross then what I have been completed project to merge to Xamarin Native because of this.Please help me out.

 I didn't find any suggested documentation in Microsoft web site and supporting MVVM Cross websites also.
Please suggested to me to do the process. in MVVM Cross Xamarin Android/iOS both.

Thanks in Advance.
Suresh.

**Comment by sureshbabu4** [comment]
@martijn00, Thanks a lot for closed this, Could you please help me out to get the Microsoft Intune Integration or Migration for Xamarin Android & iOS with MVVM Cross with brief explanation to do steps wise declaration for all users who have eagerly waiting for this integration.If you don't mind if anything wrong on this,i am just asking to help me to complete this task.

Thanks in Advance,
Suresh.

**Comment by prsreejith** [comment]
Hi Suresh

Please go through the below link
[https://cloudwatching.home.blog/2019/06/01/configure-xamarin-ios-app-intune-sdk-with-adal/](url)
Thank you..
