### ISSUE TITLE
MvxGestureRecognizerBehavior should support sending parameters to Command

### ISSUE THREAD

**Issue by miszu** [MvvmCross/MvvmCross#3347]
## 🏗 Enhancement Proposal

MvxGestureRecognizerBehavior class contains FireCommand base method which is called by various gesture behaviours which inherit from that class (tap, swipe or other custom ones):

  ```
protected void FireCommand(object argument = null)
{
        var command = Command;
        command?.Execute(null);
}
```

As you can see, the method has a parameter which is always ignored in the implementation. In my project I wanted to pass something to the command (popup source position), but because the parameter value was not passed to command I needed to do:

`Command.Execute(bundle);`

instead of :

`FireCommand(bundle)`

### Pitch

Change the FireCommand implementation to pass argument parametr to Command's Execute method. Let me know if you agree about this _small_ change, I'll be happy to create a PR then.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [x] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Seems fine to make this change! Can you open the PR?
