### ISSUE TITLE
System.ArgumentNullException: missing source event info in MvxWeakEventSubscription Parameter name: sourceEventInfo

### ISSUE THREAD

**Issue by mleatherb** [MvvmCross/MvvmCross#3350]
## 🔙 Regression

The code below is crashing when calling `pictureChooser.ChoosePictureFromLibraryAsync()/TakePictureAsync()`. This was working on MVVMCross 5.5.2, but is throwing the below exception on 6.2.3. Also this is only happening with a release build. 

### Old (and correct) behavior
It showed the platform specific photo library or camera.

### Current behavior
Exception is thrown when method is called.
```MvvmCross.WeakSubscription.MvxWeakEventSubscription`2[TSource,TEventArgs]
MvvmCross.WeakSubscription.MvxWeakEventSubscription`2[TSource,TEventArgs]..ctor (TSource_REF source, System.Reflection.EventInfo sourceEventInfo, System.EventHandler`1[TEventArgs] targetEventHandler) <0x105551c98 + 0x0016c> in <c37b5692d2fa4af3a60d754872d8531e#b54cb129e746a29b8d57be60a5ff0229>:0
MvvmCross.WeakSubscription.MvxWeakEventSubscription`2[TSource,TEventArgs]
MvvmCross.WeakSubscription.MvxWeakEventSubscription`2[TSource,TEventArgs]..ctor (TSource_REF source, System.String sourceEventName, System.EventHandler`1[TEventArgs] targetEventHandler) <0x105551c38 + 0x0004b> in <c37b5692d2fa4af3a60d754872d8531e#b54cb129e746a29b8d57be60a5ff0229>:0
MvvmCross.WeakSubscription
MvxWeakSubscriptionExtensions.WeakSubscribe[TSource,TEventArgs] (TSource source, System.String eventName, System.EventHandler`1[TEventArgs] eventHandler)```

### Reproduction steps
call `pictureChooser.ChooseFromLibraryAsync/TakePictureAsync`
```public IMvxAsyncCommand AddPhotoCommand { get { return new MvxAsyncCommand(async () => await AddPhoto()); } }
        async Task AddPhoto()
        {
            var translationService = Mvx.IoCProvider.Resolve<ITranslationService>();
            var appContextService = Mvx.IoCProvider.Resolve<IAppContextService>();
            var deviceService = Mvx.IoCProvider.Resolve<IDeviceService>();
            var dialogService = Mvx.IoCProvider.Resolve<IDialogService>();
            var fileService = Mvx.IoCProvider.Resolve<IFileService>();
            var pictureChooser = Mvx.IoCProvider.Resolve<IMvxPictureChooserTask>();

            Stream stream = null;
            var menu = new List<DialogMenuItem>()
            {
                new DialogMenuItem() {
                    Key = "Library",
                    Caption = translationService.Translate(TranslationKeys.FromLibrary)
                },
                new DialogMenuItem() {
                    Key = "Camera",
                    Caption = translationService.Translate(TranslationKeys.FromCamera)
                }
            };

            var result = await dialogService.ShowMenu(translationService.Translate(TranslationKeys.ChoosePhoto), menu);

            if (result != null)
            {
                if (result.Key == "Library")
                {
                    //TODO: Remove delay onc we refactor dialogService
                    await Task.Delay(500);
                    try
                    {
                        stream = await pictureChooser.ChoosePictureFromLibraryAsync(500, 90);
                    }
                    catch(Exception ex)
                    {
                        Crashes.TrackError(ex);
                    }
                }
                else if (result.Key == "Camera")
                {
                    if (deviceService.IsSimulator)
                    {
                        await dialogService.ShowPopupAsync(translationService.Translate(TranslationKeys.UnableToAccessCameraSimulator));
                        return;
                    }

                    stream = await pictureChooser.TakePictureAsync(500, 90);
                }
```

### Configuration

**Version:** 6.x
6.2.3

**Platform:** 
- [X ] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
It is a linker issue: https://github.com/MvvmCross/MvvmCross/issues/3329
