### ISSUE TITLE
MVVMCross cause VPNService builder.establish to return null

### ISSUE THREAD

**Issue by luqmanhussain** [MvvmCross/MvvmCross#3354]
MVVMCross cause VPNService builder.establish to return null

Expected behavior
builder.establish should not return null

Reproduction steps
See code at https://github.com/luqmanhussain/XamarinAndroidVPNExample
That works fine. However when adding the Setup.cs from MVVMCross the VPN service will no longer start

Please try with emulator as there are seperate issues with Xamarin VPN over debugger.

Configuration
Version: 5.7.0

Platform:
  🤖 Android

**Comment by luqmanhussain** [comment]
Would appreciate if someone can look at this soon as its quite an urgent issue

**Comment by Cheesebaron** [comment]
@luqmanhussain Sorry this is not how Open Source works. Just writing that something is urgent, won't speed anything up. Please refer to the license MvvmCross is distributed under.

If you want better help, provide a failing example too. The reproduction steps:
> adding the Setup.cs from MVVMCross the VPN service will no longer start

are too vague. It is unclear what the exact steps are.

If you want expedited help, refer to our OpenCollective which has paid Support options: https://opencollective.com/mvvmcross
