### ISSUE TITLE
Any supports to WPF on .NET Core 3.0?

### ISSUE THREAD

**Issue by yanxiaodi** [MvvmCross/MvvmCross#3355]
## 🚀 Feature Requests

I'm trying to use .NET Core 3.0 as the framework for WPF. Currently, it is preview but I'm wondering if we can add the WPF .NET Core 3.0 support to MvvmCross? 

### Describe the feature
WPF with .NETCore 3.0 has better performance.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

Thanks all.

**Comment by nickrandolph** [comment]
I haven't started to look at the .NET Core support for WPF - what do you get using the current WPF support from MVvmCross when you attempt to use it? What do you think we need to do to support it? And would you be able to submit a PR with the changes required?

**Comment by yanxiaodi** [comment]
Sorry I'm also just to start WPF on .NET Core 3 and no real project at the moment. Need more investigation.   I still use .NET Framework for my WPF project but I think it's worth to have a try.

**Comment by lmalsch** [comment]
As .NET Core 3.0 is now officially released, I wanted to ask if there are any news regarding the support of WPF under .NET Core 3.0?

**Comment by Cheesebaron** [comment]
We haven't had the time to look at this yet. We want to, but... 🕐
