### ISSUE TITLE
Tabs with MVVMCross 6.2+

### ISSUE THREAD

**Issue by hubocan** [MvvmCross/MvvmCross#3357]
## 🐛 Bug Report

I have created simple Xamarin Android app with MVVMCross 6.2+ and trying to create tab layout properly. Right now I get only one (the last registered tab) on screen, but after rotation (recreation) there are all three of them (as it should be). What's wrong? What have I missed? How to fix it? Thanks in advance for your help.

### Expected behavior

There should be all three tabs.

### Reproduction steps

Unzip, open solution, build and run.

### Configuration

[MvvmCrossTabs.zip](https://github.com/MvvmCross/MvvmCross/files/3050343/MvvmCrossTabs.zip)

**Version:** 6.2.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by softlion** [comment]
I'm pretty sure you can not set the MainLauncher to the activity of your choice, only the special SplashScreen.cs file. Your project don't have this file.

**Comment by hubocan** [comment]
> I'm pretty sure you can not set the MainLauncher to the activity of your choice, only the special SplashScreen.cs file. Your project don't have this file.

If I remember well, when I have added the splash screen, the result was the same.

**Comment by kmiterror** [comment]
@hubocan I downloaded your sample, modified it so the Mvvmcross splashscreen was used and it fixed the problem. I can sent you an updated sample if you wish.

**Comment by hubocan** [comment]
> @hubocan I downloaded your sample, modified it so the Mvvmcross splashscreen was used and it fixed the problem. I can sent you an updated sample if you wish.

Any solution to the problem will be appreciated.

**Comment by kmiterror** [comment]
Below is the fixed project, it all boils down to having a SplashScreen.cs file which is an MainLauncher activity which implements the MvxSplashScreenAppCompatActivity. Nothing more. 
@softlion said in the Slack channel that he is working on a PR which will remove the hard dependency on MvxSplashScreenAppCompatActivity. It should simplify some scenarios.

[MvvmCrossTabs.Working.zip](https://github.com/MvvmCross/MvvmCross/files/3071950/MvvmCrossTabs.Working.zip)

**Comment by hubocan** [comment]
Thanks for your help and clarification. For now this is probably the only solution (to have splash screen). But as you mentioned, probably the real solution is on the way.

**Comment by kmiterror** [comment]
#3376 this is the aforementioned PR that removes the need of splash screen. 
This is still something being discussed by the project maintainers but things are starting to move. 

On the other hand I found another workaround. 
I analized code in MvxSplashScreenAppCompatActivity and basing on this I run this code in MainView activity of my project:
``` csharp 
protected override void OnCreate(Bundle bundle)
{
 var setupSingleton = MvxAndroidSetupSingleton.EnsureSingletonAvailable(this);
 setupSingleton.EnsureInitialized();
 base.OnCreate(bundle);
 // my code here
}
```

Making it this way tabs works as intended without the splash screen.
