### ISSUE TITLE
Xamarin Forms: IMvxInteraction Bind in XAML Markup

### ISSUE THREAD

**Issue by foehammer88** [MvvmCross/MvvmCross#3371]
When implementing IMvxInteraction in a Xamarin Forms app, instead of applying the ViewModel -> View binding in the code behind as mentioned here (https://www.mvvmcross.com/documentation/advanced/mvxinteraction#wiring-up-interaction-between-view-and-viewmodel), can the IMvxInteraction be bound solely in the XAML Markup?

C# lines in the page code behind I'm trying to replace in the XAML:

```
var set = this.CreateBindingSet<OurView, OurViewModel>();
set.Bind(this).For(view => view.Interaction).To(viewModel => viewModel.Interaction).OneWay();
set.Apply();
```

Is there a way to bind the IMvxInteraction strictly in XAML?

**Comment by Cheesebaron** [comment]
@foehammer88 I am not sure that is possible. Will mark this as needs investigation. You simply want to not have to create a binding set and bind a property in your code behind through the XAML if I understand it correctly.

**Comment by Cheesebaron** [comment]
This might be relevant to this issue: https://forums.xamarin.com/discussion/comment/245476/#Comment_245476

**Comment by ehuna** [comment]
> @foehammer88 I am not sure that is possible. Will mark this as needs investigation. You simply want to not have to create a binding set and bind a property in your code behind through the XAML if I understand it correctly.

Yes, in our case that's right - we use MVVMCross so we try to avoid code-behind as much as possible and do everything in the ViewModel and XAML.

We'll see if we can see Behaviors and SetPropertyAction - that might work, thank you!

**Comment by foehammer88** [comment]
@Cheesebaron thanks for providing this info. Yes, I want to move the binding set, that is currently happening in the code behind, to the XAML. I will look into David Britch's Behaviors library and see if it can be done with that.
