### ISSUE TITLE
Why does every `MvxActivity` potentially run app start in `OnCreate`?

### ISSUE THREAD

**Issue by ElteHupkes** [MvvmCross/MvvmCross#3373]
Recently [this particular piece of code](https://github.com/MvvmCross/MvvmCross/blob/618b8e75bd16cae954f1b40a57cf336218f929d3/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatActivity.cs#L91) has been causing me some headaches, mostly in combination with the `AppStart` being incorrectly reset (e.g. #2891, but I have other cases). I have multiple workarounds in place right now, one of which is basically disabling app start from any other place than the splash screen. This seems to work fine, and led me to wonder what the rationale is behind running app start in any other activity than the launching activity (be it a splash screen or something else). It seems to me that if you have any other activity than your launcher open, running app start only incorrectly overlays it with the activity corresponding to the initial view model - as is the case in my headache scenarios. I don't think the code is there for nothing though - so what am I missing?

@martijn00 given that you wrote this particular code (`git blame` is a wonderful thing ;)), could you maybe shed some light on this?

**Comment by vuurbeving** [comment]
I actually ran into the same thing yesterday, switching activity runs appstart again which will in turn navigate to the initial viewmodel.

Isn't the if simply inverted incorrectly? the MvxSplashScreenActivity does implement IMvxSetupMonitor, but MvxActivity does not seem to implement it? (only did a quick search on github, so not 100% sure)
If MvxActivity doesn't implement it, it would simply always call RunAppStart right? that makes no sense?

**Comment by nickrandolph** [comment]
I thought (and apologise as I haven't double checked the code) that RunAppStart was safe to run multiple times - the second+ times it does nothing. The point of it the check is to determine whether startup should be done async (ie in the case of the splash screen) or synchronously (ie the case where there is no splash screen). @softlion as an open PR that's looking to address this issue but I think it's enforcing an application class, which may be the best way to solve this across the board.

**Comment by softlion** [comment]
"the second+ times it does nothing" => When this code was still there in my projects, on app restart it would also restart the splash screen and never hide it, thus hiding the real top activity.

**Comment by vuurbeving** [comment]
thanks for the info @nickrandolph . I didn't realize it should be possible to call runappstart at any time. Somehow the IsStarted must be false then. Also this doesn't happen on all my devices, will try to figure out when this happens.

This PR is interesting too: https://github.com/MvvmCross/MvvmCross/pull/3214

For now i simply overridden the RunAppStart in all my views, that works, but i'm not sure what other side effects this will cause.

**Comment by softlion** [comment]
> For now i simply overridden the RunAppStart in all my views

It will be an issue with tombstoning. You app won't reinitialize Mvx core when it wakes up.
So when your app is backgrounded for 2 hours, your customers won't be able to wake it. They will need to kill it first.

**Comment by ElteHupkes** [comment]
@softlion AFAIK that isn't actually true, AppStart is not responsible for initializing MvvmCross, this is done using an [activity callback](https://github.com/MvvmCross/MvvmCross/blob/c85eaa80cd0d1c88207b61e4fc16029ad7fd5e4e/MvvmCross/Platforms/Android/Views/MvxActivityViewExtensions.cs#L39). 

@nickrandolph Indeed `AppStart` _should_ be safe to run multiple times and it _shouldn't_ do anything the second time because of the `IsStarted` property. Problems arise when (a) that property is no longer in memory (after reloading a tombstoned state) or (b) when `AppStart.ResetStart()` is incorrectly called, [mostly here](https://github.com/MvvmCross/MvvmCross/blob/c85eaa80cd0d1c88207b61e4fc16029ad7fd5e4e/MvvmCross/Platforms/Android/Views/MvxActivityViewExtensions.cs#L79), which is what happens in #2891 and a couple of other cases which I've yet to fully analyse.

My question however is not if it is safe to run `AppStart` multiple times (to which the answer is "it should be but isn't in all cases") but why we would want to do it in the first place. Either you have a splash screen, which runs app start just fine, or you don't, in which case your initial activity is already your initial activity right? I suppose if you have any other logic than "load your initial view model" in app start there might be a reason for running it when `IsStarted = false`, but then again, you can also do that in your `Setup` or your `App` (which I'm doing as a side effect of once having used 4.x anyway). Fact of the matter is that the default function of `AppStart` is to load the initial view model which is definitely not something you want to do anywhere else than in you launching activity.

I actually think that @vuurbeving 's solution (quite some Dutchies here am I right?) is the correct one given an app start that just loads the initial view model - but I have a lot of views, and it's very easy to miss one and introduce a bug that way. I would be in favor of removing the call to begin with, buuuut given that I can't think of a reason as to why it's there to begin with I was hoping to figure that out first, hence this question.

**Comment by thongdoan** [comment]
@ElteHupkes, in Android when memory become slow, the OS will save the "activities stack" of backround processses, then kill it (clear all memrory, instance and static variables), after that if User reopen background app, the OS will restore "activities stack", open the last Activity, at this time all static variables will become null or false, so AppStart is not safe to run multiple times.

@softlion, you don't need wait for 2 hours, you can open Settings App->Developer Options->Limit background processes (not activity)-> 0 background process, after than you can open your app, then open other app and reopen your app again and you can preproduce the issue.

In my project, I remmeber that I override RunAppStart and don't call base.RunAppStart, and it work for me

Just want to help you easier find what happened :), sorry my bad English

**Comment by ElteHupkes** [comment]
@thongdoan Yes, that is exactly what I was saying. 

I like to use [Developer Toolbelt](https://play.google.com/store/apps/details?id=com.tspoon.androidtoolbelt&hl=nl) ([APK to drag onto your emulator](https://apkpure.com/developer-toolbelt-fill-ram/com.tspoon.androidtoolbelt)) to flood the memory, that'll get your background process killed for sure so you can test these scenarios.

**Comment by SSELLIOTTHOME** [comment]
Could I merge this issue that I logged with this thread
https://github.com/MvvmCross/MvvmCross/issues/3308

It covers the same issue, with it being a problem on devices with slow animations (where the app resets). I have a reasonable work around - replacing the MvxTopLevelActivity with another implementation.

**Comment by softlion** [comment]
This pr should fix it https://github.com/MvvmCross/MvvmCross/pull/3376 let me update it.

**Comment by ElteHupkes** [comment]
So for whomever finds it useful, my current workaround entails the following:

- I have an `AppStart` class that is completely NOOP, so it extends `IMvxApStart` but all the implementations are empty. This way I get rid of all the magic, nothing to work around. Because of this, `Mvx[AppCompat]Activity.RunAppStart()` is also not doing anything anymore without me needing to overwrite it anywhere.
- I have a separate class that is just in charge of launching a view model based on a hint. It's essentially stateless.
- I have a custom `IMvxAndroidCurrentTopActivity` which extends `MvxApplicationCallbacksCurrentTopActivity` adding one method: `IsOnlyActivity(Activity activity)`. More on that in the next point.
- I have a single SplashScreen (extending `MvxSplashScreenActivity) which is the main launcher, and intercepts all URLs and push notifications. It's `RunAppStartAsync()` is completely custom. Basically it checks whether either:
    - There is a hint (push notification, deep link), in which case it is handled anyway (my custom presenter will take care of the stack)
    - It is the only current activity (using that `IsOnlyActivity()` method), in which case this must be an app startup and we handle it with or without hint.

I avoid the whole `ResetStart()` can of snakes by not actually deciding whether some activity is the last one but rather checking for the opposite when the main launcher is entered. `MvxApplicationCallbacksCurrentTopActivity` may still have a `null` top activity in some instances but without the `ResetStart()` check I have currently no scenario in which anything requests the current activity at that point.

**Comment by ElteHupkes** [comment]
I think that #3214 properly addresses this question... because it removes the behavior ;). Closing, thanks for the comments everyone.
