### ISSUE TITLE
MvxTapGestureRecognizerBehavior not working for UITextField in iOS 10.3.2

### ISSUE THREAD

**Issue by JPSiller** [MvvmCross/MvvmCross#3381]
## 🐛 Bug Report

The following binding does not work for iOS 10.3.2. It does work in iOS 12.

set.Bind(myUITextField.Tap()).For(t => t.Command).To(vm => vm.MyCommand);

### Expected behavior

Command executes.

### Reproduction steps

Add a UITextField to a view. Create an outlet and the the following binding:
bindingSet.Bind(myUITextField.Tap()).For(t => t.Command).To(vm => vm.MyCommand);

Run the application in a device/simulator running iOS > 12 and the binding will work correctly. 

Run the application in a device/simulator running iOS 10.2.3 (possibly any 10 version) and instead of triggering the command the UITextField gets selected and the keyboard shows up.

### Configuration

**Version:** 6.2.3

**Platform:** 
- [ ] :iphone: iOS (Xamarin)

**Comment by martijn00** [comment]
Does sound a bit like a linker problem. Did you try disabling that?

**Comment by JPSiller** [comment]
Hi @martijn00 - Yes I tried disabling the linker with not success. It doesn't work in iOS 10.2.3 with any linker setting.

In iOS 12 it still works with linker enabled or disabled.

**Comment by JPSiller** [comment]
Also, this only fails with UITextFields, any view that inherits directly from UIView works fine in both iOS versions. 

The only difference I see in UITextField is that it inherits from UIControl (which of course inherits from UIView too) but other than that I cannot find out why UITextField would fail in iOS 10.2.3.

**Comment by JPSiller** [comment]
@martijn00 I was able to find the issue. Honestly I'm not sure what changed in iOS 12 that makes the binding work but UITextFields have a history of issues with Tap gestures. I found a fix in order to make Tap gestures work though and was wondering if I could contribute by making this change in the MVVMCross solution. 

Is there any specifics to request authorization to contribute to the project?

**Comment by martijn00** [comment]
@JPSiller This is open source, so sure you are open to contribute! Just fork the project, make a branch, add the code, commit it, and make a pull request. After that i'll review it and get it merged.
