### ISSUE TITLE
Mvx. namespace shortcut not working in VS2019 16.1 preview2 with D8 and aapt2 enabled

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#3383]
## 🔙 Regression

The "Mvx" namespace shortcut is not working in android projects compiled in VS2019 preview in debug mode when  Dex compiler is set to D8, code shrinker is set to ProGuard and aapt2/multidex are checked (not sure if multidex is an issue here).

For example, this android xml layout code which is working using older xamarin versions does not work anymore. MvxGridView is not found.

```xml
<Mvx.MvxGridView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:MvxBind="ItemsSource Items;ItemClick ItemClickCommand"
 />
```

The cause is the property `ViewNamespaceAbbreviations` in MvxAndroidSetup which is using upper chars in the namespace. Using only lower chars fix this issue.

```csharp
        protected override IDictionary<string, string> ViewNamespaceAbbreviations
        {
            get
            {
                return new Dictionary<string, string>
                {
                    {"Mvx", "mvvmcross.platforms.android.binding.views"}    
                };
            }
        }
```

### Configuration

**Version:** 6.2.3
**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Looks like a valid fix. It should not break anyone, right?

It would make sense to also rename `Mvx` to lowercase because all of Android has this already. Problem is that it would break everybodies apps.

**Comment by softlion** [comment]
You could create 2 properties, mvxBind and MvxBind ;)
Note that i don't know if it works without D8.

**Comment by martijn00** [comment]
@softlion can you check my PR?
