### ISSUE TITLE
Why is Wpf platform tied to App.MainWindow

### ISSUE THREAD

**Issue by MihaMarkic** [MvvmCross/MvvmCross#3384]
I'm currently looking at MvvmCross and for fun trying to have a Login window *before* main window appears and finding it a bit hard to.
Looking at sources I can see that Wpf implementation is quiet tied to App.MainWindow for some reason (MainWindow.xaml by default). I would expect that it depends on Application instance, not the MainWindow and the Wpf application lifetime depends on MvxApplication lifetime, not the other way round.
Anyway, is there a scenario to show MvvmCross driven windows/content before showing main window?
I'm new to MvvmCross, so perhaps I'm missing something.
Cheers

**Comment by RayMMond** [comment]
probably because the Initialization of MvxWpfSetup needs a FrameworkElement root?

https://github.com/MvvmCross/MvvmCross/blob/c139ad204827ba4810ef3266ca77b255cad24634/MvvmCross/Platforms/Wpf/Views/MvxApplication.cs#L15-L22

**Comment by MihaMarkic** [comment]
@RayMMond Yes, but why. I don't know much about internals, but I'd tie the lifetime to WPF app, not to the main window.

**Comment by RayMMond** [comment]
From what i know, the default [WpfViewPresenter](https://www.mvvmcross.com/documentation/platform/wpf/wpf-view-presenter?scroll=1040) needs a FrameworkElement as navigation stack root, so it can not be done now. 
But theoretically, I believe you can create a view presenter depends on MvxApplication by  implement IMvxViewPresenter interface, and replace the default one.

**Comment by LohanSolo** [comment]
This is a WPF thing much rather than related to MVVMCross. Here is a document on what the Application.MainWindow does. 
https://docs.microsoft.com/en-us/dotnet/api/system.windows.application.mainwindow?view=netframework-4.8
