### ISSUE TITLE
Xamarin Forms Hamburger Menu Width Bigger Than Expected

### ISSUE THREAD

**Issue by AcnNuriSezgin** [MvvmCross/MvvmCross#3385]
## 💬 Questions and Help

We are using MvxMasterDetailPagePresentation for showing a hamburger menu. But the hamburger menu width size is much bigger than expected thus a user cannot close menu when tap to the outside of the menu view.

[Here is all description what I have, I wrote to StackOverflow before  but nobody gave a suggestion to me until at this time.](https://stackoverflow.com/questions/55897602/xamarin-forms-android-mvvmcross-hamburger-menu-parent-view)

**Version:** 6.2.3
**Platform:** Android

**Comment by martijn00** [comment]
Isn't this the same in Xamarin.Forms without MvvmCross? Do you have a repo with a reproduction sample?

**Comment by AcnNuriSezgin** [comment]
Hi martjin sorry for late answer, it is not same without MvvmCross it is working properly. Additionally I would like to say UWP project is working fine with MvvmCross. We can close hamburger menu easily.
