### ISSUE TITLE
How to use IoCProvider in a Worker in Android

### ISSUE THREAD

**Issue by MagneticLlama** [MvvmCross/MvvmCross#3387]
I haven't been able to find anyone talking about WorkManager and Workers in Android while using MvvmCross. By the nature of the WorkManager, work might not be done while the main application has been initialized. I have several Workers that use IoCProvider.Resolve to get as services, but they return null if the device has been reset before the Worker was started.

How should we handle any initialization MvvmCross needs within Workers?

Platform: Android

**Comment by martijn00** [comment]
Please use a proper issue template next time.

This is easy:

```c#
var setup = MvxAndroidSetupSingleton.EnsureSingletonAvailable(ApplicationContext);
setup.EnsureInitialized();
```
