### ISSUE TITLE
Bindable CollectionView supplementary views

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#339]
These would be lovely

Just a header or footer that you could bind - maybe just as an example

**Comment by willsb** [comment]
Have I partially closed this with #2021? 😄

**Comment by nickrandolph** [comment]
@martijn00 do we just want to close off this issue now?

**Comment by nickrandolph** [comment]
No feedback, so closing this issue

**Comment by nmilcoff** [comment]
I'm not sure no feedback is a good reason for closing issues like this one. AFAIK We don't support bindings on CollectionView supplementary views... so the feature request is fair.
