### ISSUE TITLE
Init() in ViewModel called twice on Android - Deep Linking

### ISSUE THREAD

**Issue by justinwojo** [MvvmCross/MvvmCross#3394]
## 🐛 Init() Called Twice on Android

When we started to utilize the URI based navigation (deep linking), we noticed that within a ViewModel, if you specify an Init() method to receive your params, the method would get called twice on Android (once on iOS). We also noticed that even if you aren't linking to the page with a URI, Init() is called regardless with any overloads using the default values of your params. 

#### Example nav with ViewModel type
```C#
//From ViewModel1
NavigationService.Navigate<ViewModel2>();

//ViewModel2 class - called with default value for int (0), twice on Android, once on iOS
public void Init(int testid) { }
```

#### Example nav with URI navigation and query params
```C#
//From ViewModel1 
NavigationService.Navigate("mvvmcross-test://deeplink/?testid=123");

//ViewModel2 class - called with testid = 123, twice on Android, once on iOS
//with registered scheme: mvvmcross-test://deeplink/\?testid=(?<testid>[0-9]{1,3})$
public void Init(int testid) { }
```
 The above Init() method in a ViewModel is called every time the ViewModel is navigated to regardless of using a URI deep link or not. On Android, it is called twice. iOS is only called once, but every time as well regardless of having query param data to pass in.

When it's called through a deep link URI with query params, the data is passed correctly. When you're navigating to the viewmodel type directly (not URI) then the method is still invoked, but with just the default values of string and int being passed in.

You can add any number of Init() methods to the class with different overloads and they're all called regardless of using URI nav or ViewModel type nav.

### Expected behavior

1. Android should only call Init() once to match iOS's behavior.
2. Ideally the Init() overloads with params are only called during a URI deep link and not under normal ViewModel nav where it passes default params. I don't know the expected requirements around this though as it's not documented anywhere. Otherwise we end up having to check for default values every time, and if we receive a value that is of the default type (Ex: 0 for integer) that we want to use, then we can't add the ignore default(int) logic.

### Reproduction steps
I have a reproduction project below. I have only added logic to the Droid project to reproduce the double Init() calls. I also added two buttons, one using URI nav with params, one with viewmodel type nav to showcase that Init() with my overloads gets called regardless each time it's navigated to.
[Reproduction Project](https://github.com/justinwojo/XamEssentialsTest)

### Configuration
Visual Studio for Mac (2019 8.0.3)
Xamarin.iOS 12.8.0.0
Xamarin.Android 9.2.0.5
Any Android/iOS device and version. Not dependent upon any OS version from what I can tell.

**Version:** 6.2.3

**Platform:** 
- [?] :iphone: iOS (depending on Expected Behavior above)
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by pinkysek** [comment]
yes I can confirm this problem :) I found this in my app with MvvmCross version 6.4.1. I will probably look at this issue and try find where is problem.
