### ISSUE TITLE
[6.3.0] Using MvvmCross.Platforms.Android not being recognized by Compiler.

### ISSUE THREAD

**Issue by CaulinJones** [MvvmCross/MvvmCross#3403]
### Old (and correct) behavior
When creating a setup.cs in a new Android project, using the MvxAndroidSetup class is recognized by the compiler in release 6.2.3.
### Current behavior
When creating a setup.cs in a new Android project, using the MvxAndroidSetup class is  not being recognized by the compiler.
### Reproduction steps
Create a new MvvmCross project with and Android project -> create a custom app startup for the android project -> assembler wont recoqnise the MvvmCross.Platform namespace.
### Configuration

**Version:** 6.3.0

**Platform:** 
- [ ] :iphone: iOS
- [ x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
This class hasn't been removed or moved namespace-wise.

Make sure all your MvvmCross packages are synced, so you are not mixing versions. Also make sure to clean obj and bin folders.
