### ISSUE TITLE
MvvmCross.Forms.Platforms missing namespace in Android - 6.3.0

### ISSUE THREAD

**Issue by jasonboyda** [MvvmCross/MvvmCross#3412]
## 🔙 Regression

`using MvvmCross.Forms.Platforms.Android.Core;` produces
`The type or namespace name 'Platforms' does not exist in the namespace 'MvvmCross.Forms'`
### Old (and correct) behavior
v6.2.3 works as expected
### Current behavior
Updating to 6.3.0 removes reference
### Reproduction steps
Updating from 6.2.3 to 6.3.0 or removing package and installing 6.3.0 directly
### Configuration

**Version:** 6.3.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by CaulinJones** [comment]
Posted this same issue a few weeks ago. Contributors told me this was improbably and to make sure /bin/ and /obj/ folders were clear, then proceeded to close my issue #3403. This fix did not work for me but it may for you. 
-Cheers

**Comment by jasonboyda** [comment]
> Posted this same issue a few weeks ago. Contributors told me this was improbable and to make sure /bin/ and /obj/ folders were clear, then proceeded to close my issue #3403. This fix did not work for me but it may for you.
> -Cheers

Thanks for the advice, unfortunately that did not work me either. Can confirm this is still an issue.

**Comment by Anil86** [comment]
In Properties  --> Application, set 
**Compile using Android Version: (Target Framework)**  
to  
**Android 9.0 (Pie)**.

I hope this will resolve the issue.
