### ISSUE TITLE
Compile issues after updating to 6.3.0

### ISSUE THREAD

**Issue by danieleardissone** [MvvmCross/MvvmCross#3420]
## 🔙 Regression

Updating to v. 6.3.0 produced some compile issues in my Xamarin Android project.
I've already cleaned obj and bin folders but nothing changes.

`"LinkAssemblies" task fails unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'NovusMobile.Droid, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
Nome file: 'NovusMobile.Droid.dll'
   in Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   in Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
   in Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   in Xamarin.Android.Tasks.LinkAssemblies.Execute()
   in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   in Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()`

`Failed to generate resource table for split '' "Failed to generate resource table for split ''".`

`Attribute "statusBarBackground" already defined with incompatible format.`
`Attribute "layout_anchorGravity" already defined with incompatible format.`
`Attribute "layout_insetEdge" already defined with incompatible format.`
`Attribute "layout_dodgeInsetEdges" already defined with incompatible format.`
`Attribute "layout_dodgeInsetEdges" already defined with incompatible format.`

### Old (and correct) behavior
v6.2.3 works as expected

### Reproduction steps

Update MVVMCross NuGet packages from version 6.2.3 to 6.3.0

### Configuration

**Version:** 6.3

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Do you set your Android target and compile framework to 9.0?

**Comment by danieleardissone** [comment]
@martijn00  Yes, with 8.1 I was not able to update NuGet packages.

**Comment by Cheesebaron** [comment]
None of the attributes it complains about are related to MvvmCross. Make sure you clean your project thoroughly. Try remove all bin and obj folders.

I usually run:

```
git clean -fdx
```

**Comment by danieleardissone** [comment]
Unfortunately `git clean -fdx` didn't help me, compile issues stay the same.
I'm trying to find if there are some packages that could create conflicts with the new version of MvvmCross.
I cannot update to v. 6.3.0 at the moment.

**Comment by Anil86** [comment]
*Steps*:

1. Clean the solution.
2. Build using Visual Studio Build *(not ReSharper build)*

I hope this will resolve the issue.

**Comment by Cheesebaron** [comment]
@danieleardissone dunno. It is hard to help you with the information you provide. I have a couple of apps on 6.3.0 that build just fine.

If you want, we can try set up a session where you show it to me while you share your screen. Send me an e-mail or DM me on twitter and we can find a time to do that.

**Comment by danieleardissone** [comment]
@Cheesebaron thanks for you time! I finally solved it migrating the default package manager format from packages.config to packagemanager. I don't know exacly why but it solved this.
