### ISSUE TITLE
[iOS 13]: Navigation Page Title text is always black

### ISSUE THREAD

**Issue by SebastianKruseWago** [MvvmCross/MvvmCross#3422]
## 🐛 Bug Report

As soon as MVX is used, the title text in the NavigationPage is always black even if set differently. This does not happen when the app uses Xamarin.Forms directly instead.

### Expected behavior

Title text should appear in the same color as the master menu icon and custom icons in the toolbar (as it was prior to iOS 13 or without MVX). 

### Reproduction steps

-

### Configuration

**Version:** 6.3.0

**Platform:** 
- [x] :iphone: iOS 13
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
You are mentioning Xamarin.Forms, is this a Forms issue or a general MvvmCross issue?

**Comment by SebastianKruseWago** [comment]
@Cheesebaron Oh sorry, yes I compared two nearly identical apps - one with bare bone Xamarin.Forms and one with MVX and Forms. Both are nearly identical, we have a master menu icon on the top left (which is displayed in the proper color that we set), a settings gear symbol on the top right (also displayed in the correct color) and then there is the title text in the middle of it which stays black on iOS 13 when MVX is involved.

**Comment by saamerm** [comment]
> You are mentioning Xamarin.Forms, is this a Forms issue or a general MvvmCross issue?

OMG @Cheesebaron , I was wondering why a nuget package I saw in a project yesterday would be named that. Now I know, thanks for that nuget!

**Comment by saamerm** [comment]
@SebastianKruseWago im interested in fixing this. Could you please explain how you tried to change the colour of the Navigation page title? Is this still an issue?
