### ISSUE TITLE
VS 2019 breaks AXML bindings in older MVX

### ISSUE THREAD

**Issue by Ryan-Palmer** [MvvmCross/MvvmCross#3423]
I understand this isn't supported code any more, but I am stuck working with a legacy project which hasn't been upgraded from MVX 4.4 so I am just fishing for ideas really.

When deploying from VS 2017, there are no problems.

When deploying from VS2019 (Windows or Mac which are totally different IDEs of course), none of the Android AXML bindings work. The rest of the system bootstraps ok, just no bindings.

I just wondered if anyone else has seen this or found a workaround?

I am just using VS2017 for now but eventually the build hosts etc will disappear and we are looking at a rewrite if we can't solve it before then.

**Comment by Cheesebaron** [comment]
Do you get anything in the device log/application output which indicates anything being wrong with the bindings?

Are you sure it isn't the linker that is just messing with you?

**Comment by RyanBuzzInteractive** [comment]
I don't think it can be a linker issue as I can build + deploy the same solution in 2017 / 19 and it works in 17 but not 19, same configuration.

One thing I did spot is that if I build in 2019 then try to deploy in 2017 without rebuilding, I get an exception with 
"Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/R$string;"

Maybe 2019 has changed how resources are compiled somehow? I'm clutching at straws tbh.

**Comment by RyanBuzzInteractive** [comment]
Just to confirm, it happens with linking switched off as well

**Comment by RyanBuzzInteractive** [comment]
Picked over debug and Droid logs and can't see anything there either. Very strange. Thanks for your support btw, I know this is probably the least of your worries.

**Comment by Cheesebaron** [comment]
Not sure what is going on. I just opened a old MvvmCross Samples project, which is running 4.4.0. Bindings work fine there.

Is it all bindings that fail for you, or just some?

**Comment by RyanBuzzInteractive** [comment]
Just fired it up to check, its all of them.

**Comment by RyanBuzzInteractive** [comment]
Ah - I can see just after it tries to show the view model I get a whole bunch of these: 
[0:] MvxBind:Diagnostic:  4.03 Abbreviation not found android

Sorry, I would share the entire log but there will be loads of sensitive stuff I'm not authorised to release.

**Comment by Cheesebaron** [comment]
Right, right. Uhm... Abbreviations

Have you overriden `ViewNamespaceAbbreviations` in your Setup.cs file?

The default in MvvmCross 4.4.0 is:

```csharp
protected virtual IDictionary<string, string> ViewNamespaceAbbreviations => new Dictionary<string, string>
{
    {"Mvx", "MvvmCross.Binding.Droid.Views"}
};
```

If you have some custom Views you are adding to your XML layout, a safer thing to do is, for each of these custom views. Make sure to have the `[Register]` attribute on top of them, and provide a name. I usually just do: `fully.qualified.namespace.ViewName` like so:

```csharp
[Register("my.namespace.MyView")]
public class MyView : View
{
}
```

Where the namespace follows the rules package names in Android i.e. lower cased.

Then you can use it in your XML layout like:

```xml
<my.namespace.MyView
  ....
```

And for Views from MvvmCross, I would also consider just using the full namespace for them.

**Comment by RyanBuzzInteractive** [comment]
Hello again :)

Ok, so I think the abbreviations may have been a bit of a red herring - I did try adding the Register attrs to my custom views but it didn't help. However I then ran the project in VS2017 (where it works fine, bindings are ok) and I still see those AbbreviationNotFound messages in the output, so it can't be them.

However, I did pick through the logs to see where they differ and at the point VS2017 starts successfully updating bindings, VS2019 gives me an exception log:

```
[0:] MvxBind:Error:  4.40 Problem parsing binding MvxException: PropertyName must start with letter - position 0 in 0.285 - char 0
	  at MvvmCross.Platform.Parse.MvxParser.ReadValidCSharpName () [0x00016] in D:\git\MvvmCross\MvvmCross\Platform\Platform\Parse\MvxParser.cs:486 
  at MvvmCross.Binding.Parse.Binding.MvxBindingParser.ReadTargetPropertyName () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Parse\Binding\MvxBindingParser.cs:132 
  at MvvmCross.Binding.Parse.Binding.MvxBindingParser.ParseTargetPropertyNameAndDescription () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Parse\Binding\MvxBindingParser.cs:71 
  at MvvmCross.Binding.Parse.Binding.MvxBindingParser.TryParseBindingSpecification (System.String text, MvvmCross.Binding.Parse.Binding.MvxSerializableBindingSpecification& requestedBindings) [0x00015] in D:\git\MvvmCross\MvvmCross\Core\Binding\Parse\Binding\MvxBindingParser.cs:52 
08-16 17:04:32.842 I/MvxBind (10577):   4.41 Failed to parse binding specification starting with 0.285
[0:] MvxBind:Error:  4.41 Failed to parse binding specification starting with 0.285
```

**Comment by Cheesebaron** [comment]
For some reason it tries to bind to `0.285`, which obviously isn't a valid C# property name. Not sure what is going on there. 

Do you have a binding that looks like: `Text 0.285`?

**Comment by Ryan-Palmer** [comment]
Hey dude. I have left the company I was working for this month - I won't need to find the solution to this myself now, I didn't want to be rude and just disappear though. Thanks for your assistance trying to get to the bottom of it.

**Comment by Cheesebaron** [comment]
I will close this for now then. Good luck on your endeavors @Ryan-Palmer

**Comment by PaulAxten** [comment]
@Ryan-Palmer The idiot that let you leave must be full of regrets right about... now :(
