### ISSUE TITLE
.NET Core SDK not supported

### ISSUE THREAD

**Issue by a7ex** [MvvmCross/MvvmCross#3432]
Hi all,
I just downloaded the whole project and tried running the Playground.Droid Project on my Mac (Mac OS 10.14.5). I am using VS 2019 8.0.9 (Build 5).

Unfortunately I get the following error:
Error: The version of the .NET Core SDK currently installed (/usr/local/share/dotnet/sdk/2.2.107/Sdks) is not supported and continuing to use it may result in a broken tooling experience. https://aka.ms/vs/mac/install-netcore (MvvmCross)

I can not find any more details on this, like:
- which version of .NET Core SDK to use
- how to run another version of .NET Core SDK

The link in the error message leads to dotnet-sdk-2.2.107-osx-gs-x64, which is the version I have installed.

What can I do? I just want to check the examples in order to seek guidance on how to accomplish a special navigation using MvvmCross.

What can I do in order to just run the Playground example?

Thanks in advance
Alex

**Comment by Cheesebaron** [comment]
There is still no proper support for Multi-target libraries in VS for macOS (supposedly coming in 8.3 and some of it is already in preview). You could try open it in Rider on mac, but your mileage may vary. 

Still best way to work on the MvvmCross project is on Windows in VS2019.

If you want to spend the time, you could create a separate solution adding the playground stuff and replacing the References with PackageReferences instead, then they would work in VS for macOS.

**Comment by b099l3** [comment]
It looks like 8.3 is [out](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2019-mac-relnotes)? With this in the release notes: 

> We have added improved support for projects that have multi-target frameworks.

Also links out to this [wee gif](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2019-mac-relnotes#multitarget) of what has been added. Most of this was in the preview channel like the baron has said, but if you want to follow along, this is where is work is being done on the [MonoDevelop repo](https://github.com/mono/monodevelop/projects/1) 

I haven't tried running it in a wee while so I'm going to update and give it a go tomorrow. I'll report back.

**Comment by Cheesebaron** [comment]
Ran it fine in VS for Mac today.
