### ISSUE TITLE
MasterDetail Page, Master always open on Tablets?

### ISSUE THREAD

**Issue by SebastianKruseWago** [MvvmCross/MvvmCross#3435]
I'm not sure if I just missed the option to change this or if this is a bug but as soon as I moved my plain Xamarin.Forms app to a MvvmCross Xamarin.Forms app, the master menu (Position = Master) stays always open on tablets and their is no "hamburger"-icon to toggle it or to make it hidden by default / overlay. I know that Xamarin.Forms itself has an issue with SplitView from iOS 9 and newer but this issue also happens on full screen apps and also on Android.

**Comment by fedemkr** [comment]
Have you set `MasterBehavior="Popover"` on your Root page?
I have it like this:

```xaml
<views:MvxMasterDetailPage
    x:Class="Something.UI.Views.MainView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:viewModels="clr-namespace:Something.Core.ViewModels;assembly=Something.Core"
    xmlns:views="clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms"
    x:TypeArguments="viewModels:MainViewModel"
    MasterBehavior="Popover" />
```

Also depending on the version you are using you might want to call this whenever you select an item on the menu, so the menu closes after tapping on it:

```
if (Application.Current.MainPage is MasterDetailPage masterDetailPage)
{
    masterDetailPage.IsPresented = false;
}
else if (Application.Current.MainPage is NavigationPage navigationPage && navigationPage.CurrentPage is MasterDetailPage nestedMasterDetail)
{
    nestedMasterDetail.IsPresented = false;
}
```

**Comment by SebastianKruseWago** [comment]
@fedemkr Yes, MasterBehavior is set to Popover and I already set IsPresented. Still the hamburger icon is missing + the master view stays visible. I didn't had the chance if this is related to this issue: https://github.com/xamarin/Xamarin.Forms/issues/7556 however while the app is in SplitView it still contains the typical bugs (in 1/3 view the master view is always blocking the content).
