### ISSUE TITLE
MvvmCross Binding 

### ISSUE THREAD

**Issue by Enk-AxelZapata** [MvvmCross/MvvmCross#3436]
## 🐛 Bug Report

I have a doubt related to MvvmCross binding configuration.
When  I install MvvmCross Binding library, the current version showed is 5.7.0, but this is not compatible with MvvmCross Fragment v. 6.2 and I am not able to access to latest features.

Is there a step that I am missing?

**Version:** 6.1

**Platform:** 
- [x] :robot: Android

![image](https://user-images.githubusercontent.com/50336922/59807458-9c48c600-92bd-11e9-84eb-b6b938dcd208.png)

**Comment by Cheesebaron** [comment]
You are mixing 5.7.0 and 6.3.1 versions.

In 6.x you only need to add the main MvvmCross NuGet package, the .Core, .Platforms and .Bindings are not needed anymore.

**Comment by Enk-AxelZapata** [comment]
You are right, I mixed all the nuget.

Thank you!!
