### ISSUE TITLE
MvxSpinner classNotFoundException inside fragment

### ISSUE THREAD

**Issue by erlandvr** [MvvmCross/MvvmCross#3454]
## 🐛 Bug Report

When Navigating to a MvxFragment inside a MvxFragmentActivity the MvxSpinner causes an error. It worked fine as a view inside an MvxActivity.
`Java.Lang.ClassNotFoundException: Didn't find class "android.view.MvxSpinner" on path: DexPathList`

I've added `MvxAppCompatSetupHelper.FillTargetFactories(registry);` in the 
`protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)` alas without succes.

I managed to reproduce the problem in a sample project (TipCalc)
[TipCalc.zip](https://github.com/MvvmCross/MvvmCross/files/3355588/TipCalc.zip)

### Expected behavior
The Fragment opens.

### Reproduction steps
No steps needed in the sample project, the fragment gets called automatically.

### Configuration

**Version:** 6.3.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
[TipCalc.UI.Mac.zip](https://github.com/MvvmCross/MvvmCross/files/3355583/TipCalc.UI.Mac.zip)

- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Try using the fully qualified name for MvxSpinner

**Comment by erlandvr** [comment]
Works like a charm. Thank you!
