### ISSUE TITLE
MvxFormsAppCompatActivity is unavailable in Android project

### ISSUE THREAD

**Issue by beylkhanovdamir** [MvvmCross/MvvmCross#3460]
## 🐛 Bug Report

MvxFormsAppCompatActivity and MvxFormsAndroidSetup classes are not visible after installing required MvvmCross and MvvmCross.Forms nuget packages

Compilation error:

>   MainActivity.cs(13, 33): [CS0246] The type or namespace name 'MvxFormsAppCompatActivity<,,>' could not be found (are you missing a using directive or an assembly reference?)
> 
>   MainActivity.cs(13, 59): [CS0246] The type or namespace name 'MvxFormsAndroidSetup<,>' could not be found (are you missing a using directive or an assembly reference?)

![image](https://user-images.githubusercontent.com/7656847/60708499-ddc0ae80-9f16-11e9-80ad-81838504ac13.png)

In addition, I saw [in your documentation ](https://www.mvvmcross.com/documentation/tutorials/tipcalc/a-xamarin-forms-version?scroll=1890#edit-mainactivitycs) that you have 2 _MvvmCross.Forms.Platforms.*_ namespaces, but in fact, these namespaces are not available for me, in particular, *._Platforms_

what's wrong there in my case?

### Expected behavior

Successful build compilation

### Configuration

**Version:** 6.3.1

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ x] :monkey: Xamarin.Forms (3.6.0-sr4)

**Comment by beylkhanovdamir** [comment]
@martijn00 please, review

**Comment by Cheesebaron** [comment]
@beylkhanovdamir we've already been notified when you create an issue. No need to start mentioning people you want to review your issues. Please stop this behavior.

As for your issue. Please make sure all your MvvmCross packages are the same versions, you seem to be mixing these in your project, looking at the screenshot.

The two types that seem to be missing are actually in the MvvmCross.Forms package. So something is most likely messed up with your NuGet package references.

**Comment by beylkhanovdamir** [comment]
@Cheesebaron please, just tell me, what do I need to do, left only MvvmCross package, right or what?

**Comment by beylkhanovdamir** [comment]
oh, I got it, the problem in **Target Android API** which should be 9.0 for Android v28.0.0.1

**Comment by beylkhanovdamir** [comment]
yeah, problem resolved after upgrading to the 9.0 SDK

![image](https://user-images.githubusercontent.com/7656847/60735882-a4f7f800-9f5d-11e9-8c17-37b8ac4e6574.png)
