### ISSUE TITLE
Getting error when using MvxListView in layout

### ISSUE THREAD

**Issue by Qamar-Datasmith** [MvvmCross/MvvmCross#3462]
Hi  
I am new in MVVMCross development.I am getting compile time error when using MvxListView in layout.
Here is the error "Error parsing XML: unbound prefix".
Below is the code

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
  
	<MvvmCross.Platforms.Android.Binding.Views.MvxListView 
		android:id="@+id/listIncidentss"
		android:layout_width="@dimen/_100sdp"
		android:layout_weight="@dimen/_100sdp"
		local:MvxBind="ItemsSource oIncidents"
		local:MvxItemTemplate="@layout/activity_login" 
		>
		</MvvmCross.Platforms.Android.Binding.Views.MvxListView>
</LinearLayout>
Can you please help me regarding this issue.I have spent lot of time to resolve this issue but not succeeded.

Thanks

**Comment by Cheesebaron** [comment]
It is complaining about either the `android:` or the `local:` prefix. You need to define these namespaces somewhere in your layout.
