### ISSUE TITLE
LinkageError: No implementation found for void mono.android.text.TextWatcherImplementor.n_beforeTextChanged

### ISSUE THREAD

**Issue by MauryZ** [MvvmCross/MvvmCross#3478]
## 🐛 Bug Report

After update library MvvmCross i have an issue with Linker

> MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.LinkageError: No implementation found for void mono.android.text.TextWatcherImplementor.n_beforeTextChanged(java.lang.CharSequence, int, int, int) (tried Java_mono_android_text_TextWatcherImplementor_n_1beforeTextChanged and Java_mono_android_text_TextWatcherImplementor_n_1beforeTextChanged__Ljava_lang_CharSequence_2III)
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <29c5811d8dd745f4bbf625de9e9f3cf2>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <29c5811d8dd745f4bbf625de9e9f3cf2>:0 
[MonoDroid]   at Android.Widget.TextView.set_TransformationMethod (Android.Text.Method.ITransformationMethod value) [0x00036] in <d8198fca034449fe94bb7f142e227330>:0 
[MonoDroid]   at XX.Droid.Views.Login.LoginView.InitializeControls () [0x00094] in <f46cda935f414355882af5d7398ca6fd>:0 
[MonoDroid]   at XX.Droid.Views.Login.LoginView.OnCreate (Android.OS.Bundle bundle) [0x00028] in <f46cda935f414355882af5d7398ca6fd>:0 
[MonoDroid]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <d8198fca034449fe94bb7f142e227330>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
[MonoDroid]   --- End of managed Java.Lang.LinkageError stack trace ---
[MonoDroid] java.lang.UnsatisfiedLinkError: No implementation found for void mono.android.text.TextWatcherImplementor.n_beforeTextChanged(java.lang.CharSequence, int, int, int) (tried Java_mono_android_text_TextWatcherImplementor_n_1beforeTextChanged and Java_mono_android_text_TextWatcherImplementor_n_1beforeTextChanged__Ljava_lang_CharSequence_2III)
[MonoDroid] 	at mono.android.text.TextWatcherImplementor.n_beforeTextChanged(Native Method)
[MonoDroid] 	at mono.android.text.TextWatcherImplementor.beforeTextChanged(TextWatcherImplementor.java:41)
[MonoDroid] 	at android.widget.TextView.sendBeforeTextChanged(TextView.java:10892)
[MonoDroid] 	at android.widget.TextView.setText(TextView.java:6220)
[MonoDroid] 	at android.widget.TextView.setText(TextView.java:6170)
[MonoDroid] 	at android.widget.EditText.setText(EditText.java:146)
[MonoDroid] 	at android.widget.TextView.setText(TextView.java:6127)
[MonoDroid] 	at android.widget.TextView.setTransformationMethod(TextView.java:2755)
[MonoDroid] 	at md5964384997be3f2086f58afbb264e9147.LoginView.n_onCreate(Native Method)
[MonoDroid] 	at md5964384997be3f2086f58afbb264e9147.LoginView.onCreate(LoginView.java:31)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7326)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7317)
[MonoDroid] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
[MonoDroid] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
[MonoDroid] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
[MonoDroid] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:214)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:6986)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
[MonoDroid] 
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: xx, PID: 7317
[AndroidRuntime] java.lang.UnsatisfiedLinkError: No implementation found for void mono.android.text.TextWatcherImplementor.n_beforeTextChanged(java.lang.CharSequence, int, int, int) (tried Java_mono_android_text_TextWatcherImplementor_n_1beforeTextChanged and Java_mono_android_text_TextWatcherImplementor_n_1beforeTextChanged__Ljava_lang_CharSequence_2III)
[AndroidRuntime] 	at mono.android.text.TextWatcherImplementor.n_beforeTextChanged(Native Method)
[AndroidRuntime] 	at mono.android.text.TextWatcherImplementor.beforeTextChanged(TextWatcherImplementor.java:41)
[AndroidRuntime] 	at android.widget.TextView.sendBeforeTextChanged(TextView.java:10892)
[AndroidRuntime] 	at android.widget.TextView.setText(TextView.java:6220)
[AndroidRuntime] 	at android.widget.TextView.setText(TextView.java:6170)
[AndroidRuntime] 	at android.widget.EditText.setText(EditText.java:146)
[AndroidRuntime] 	at android.widget.TextView.setText(TextView.java:6127)
[AndroidRuntime] 	at android.widget.TextView.setTransformationMethod(TextView.java:2755)
[AndroidRuntime] 	at md5964384997be3f2086f58afbb264e9147.LoginView.n_onCreate(Native Method)
[AndroidRuntime] 	at md5964384997be3f2086f58afbb264e9147.LoginView.onCreate(LoginView.java:31)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:7326)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:7317)
[AndroidRuntime] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
[AndroidRuntime] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
[AndroidRuntime] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
[AndroidRuntime] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:214)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6986)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

I try to add to LinkerPleaseInclude somethink like:

```
        public void Include(TextView text)
        {
            text.Text = $"{text.Text}";
            text.AfterTextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.TextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.BeforeTextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.Hint = $"{text.Hint}";
        }
        
        public void Include(EditText text)
        {
            text.Text = $"{text.Text}";
            text.AfterTextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.TextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.BeforeTextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.Hint = $"{text.Hint}";
        }
        
        public void Include(Android.Support.Design.Widget.TextInputEditText text)
        {
            text.Text = $"{text.Text}";
            text.AfterTextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.TextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.BeforeTextChanged += (sender, args) => text.Text = $"{text.Text}";
            text.Hint = $"{text.Hint}";
        }

```
It did not help at all.

### Reproduction steps
Add TextInputEditText or TextView to page

### Configuration

**Version:** 6.3.1.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Strifex** [comment]
I believe this is a known issue in Xamarin Android 9.4 that was introduced in VS16.2 update the other day....I don't believe this is an mvvmcross issue.

**Comment by MauryZ** [comment]
@Strifex yes that true, this is the Xamarin Adnroid issue :)
There is the solution
https://stackoverflow.com/questions/57215058/unsatisfiedlinkerror-no-implementation-found-for-void-mono-android-text-textwat
