### ISSUE TITLE
RequestTranslator ignores Presentation/Parameter values

### ISSUE THREAD

**Issue by Prin53** [MvvmCross/MvvmCross#3482]
## 🐛 Bug Report
With new `MvxNavigationService` we always have `MvxViewModelInstanceRequest` while navigation. The Presenter uses `IMvxAndroidViewModelRequestTranslator` which accepts the view model instance only. The current [implementation](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Android/Views/MvxAndroidViewsContainer.cs#L149) creates default `MvxViewModelRequest` without Presentation and Parameter values, but actually we have them in the original `MvxViewModelRequest`.
### Expected behavior
There are should be Presentation and Parameter values in serialized `MvxViewModelRequest`.
### Reproduction steps
None
### Configuration

**Version:** 6.2.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Prin53** [comment]
@Cheesebaron if you agree with this issue, I would like to implement it and open a PR.

**Comment by martijn00** [comment]
@Prin53 go ahead and open a PR. We are happy to review it.
