### ISSUE TITLE
Cant even build Playground.Droid

### ISSUE THREAD

**Issue by fiorcode** [MvvmCross/MvvmCross#3492]
When i try to build/clean projects of the solution i get this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The specified language targets for uap10.0.16299 is missing. Ensure correct tooling is installed for 'uap'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.CSharp.targets'	MvvmCross.Plugin.Accelerometer	C:\Users\Administrator\.nuget\packages\msbuild.sdk.extras\2.0.31\Build\LanguageTargets\CheckMissing.targets	36	

I guess is some trouble with the dependencies.

**Comment by Cheesebaron** [comment]
> targets for uap10.0.16299 is missing
