### ISSUE TITLE
ViewPager ignores Presentation Values

### ISSUE THREAD

**Issue by Prin53** [MvvmCross/MvvmCross#3497]
## 🐛 Bug Report

The current implementation of `MvxViewPagerFragmentInfo` stores `ParameterValuesObject` only, and the Presentation bundle is missing when `MvxViewModelRequest` created: 
- [MvxCachingFragmentStatePagerAdapter](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/Fragment/MvxCachingFragmentStatePagerAdapter.cs#L88)
- [MvxFragmentStatePagerAdapter](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/Fragment/MvxFragmentStatePagerAdapter.cs#L54)
- [MvxFragmentPagerAdapter](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/Fragment/MvxFragmentPagerAdapter.cs#L54)

### Expected behavior
The serialized `MvxViewModelRequest` should have the same values as at the moment of presentation.
### Reproduction steps
None
### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR to fix this?

**Comment by Prin53** [comment]
Yes, sure
