### ISSUE TITLE
Unresponsive camera in iOS PictureChooser due to garbage collection

### ISSUE THREAD

**Issue by ElteHupkes** [MvvmCross/MvvmCross#3517]
## 🐛 Bug Report (could be considered a regression)
As part of my PR #3216 (or the actual merged issue #3220, but there's some context in the other one), `MvxImagePickerTask` was made to weak bind to the control events in `UIImagePickerController`. However, `IMvxPictureChooserTask`s are single-use by design, and depending on the way the task is called there may be no strong references held to it at all while the camera is running. The task may therefore be garbage collected, the weak references invalidated, at which point it is no longer possible to return from the camera. A small example, let's say the picture chooser is invoked like this:

```csharp
var chooser = Mvx.IoCProvider.Resolve<IMvxPictureChooserTask>();
var stream = await chooser.TakePicture(maxDimension, pictureQuality);
SomeStreamProcessingMethod(stream);
```

When control is yielded during the `await` it appears that only the returned task is kept in memory and not `chooser`, which is garbage collected, and with it any hopes of getting out of the `UIImagePickerController`.

### Expected behavior
The camera should be able to return of course.

### Reproduction steps
This is a tricky one, because you have to independently trigger garbage collection while going to the camera and hope it'll collect your object (it's a bit of an enigma to me when that happens). We have a reliable repro in our app from the original bug report (works 9 / 10 times), which is just triggering a bunch of network activity while the camera is being used. Unfortunately I cannot share that code. I have confirmed my explanation above by placing a finalizer in `MvxImagePickerTask` and it is indeed being called using the above pattern. I can also confirm that changing `MvxImagePickerTask` to use strong event bindings solves the problem, and so does keeping a reference to the `MvxImagePickerTask` instance in a containing class (our current workaround). 

My suggested solution would be to use strong event bindings rather than weak ones, I cannot currently think of a scenario where there would be a memory leak because all the return scenarios are covered with unsubscribes, with the exception of a crash, in which case we probably don't care about a memory leak ;).

I might be able to create a PR if that is deemed an acceptable solution.

### Configuration

**Version:** 6.3.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by onurhazar** [comment]
@ElteHupkes @Cheesebaron Hello, we have the same issue plus when user selects "choose from library" view opens but cancel button doesn't work sometimes and user gets stuck in this picker view. We are using a custom picture chooser task and custom image picker controller but we don't get any breakpoint hits in our custom picture chooser task class. ChoosePictureFromLibrary and TakePicture doesn't get called. We are using the latest version of mvvmcross 6.4.2.

== Environment ==
```
=== Visual Studio Community 2019 for Mac ===

Version 8.4.8 (build 2)
Installation UUID: 006ae811-c642-4383-977d-1447328cea34
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000166

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.166 (2019-08/d9001b5ae70) (64-bit)
	Package version: 606000166

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.102/Sdks
SDK Versions:
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.15
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/onur.hazar/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/onur.hazar/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.10
Hash: 2c49a7d
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:25:52 UTC

=== Android Device Manager ===

Version: 16.4.0.32
Hash: 7a5cb8b
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:26:14 UTC

=== Xamarin Designer ===

Version: 16.4.0.479
Hash: 074544417
Branch: remotes/origin/d16-4
Build date: 2020-01-22 22:50:22 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.10.0.21 (Visual Studio Community)
Hash: 02c4b3bdc
Branch: xcode11.3
Build date: 2020-02-18 14:13:32-0500

=== Build Information ===

Release ID: 804080002
Git revision: 4f35aa7e44fb398379e512d0bfd6f8df8d34b5ac
Build date: 2020-02-27 16:16:52+00
Build branch: release-8.4
Xamarin extensions: 4f35aa7e44fb398379e512d0bfd6f8df8d34b5ac

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

**Comment by ElteHupkes** [comment]
@onurhazar So, you're using a custom task with my suggested changes? Where are you registering it? How are you calling it?

I had totally forgotten about this issue, maybe I should create that PR at some point. Problem is we internally have so much custom camera behavior at this point we're not using the picture chooser plugin at all anymore.

**Comment by onurhazar** [comment]
@ElteHupkes I solved the issue by using the picture chooser task as a class variable instead of a local variable. Thanks for the workaround.

`readonly IMvxPictureChooserTask pictureChooserTask = Mvx.IoCProvider.Resolve<IMvxPictureChooserTask>();`

@Cheesebaron Where is the best place to register singleton for the custom picture chooser task? Before I put it in FirstLaunch in Setup.cs but I couldn't get any called method in my custom class. I now put in AppDelegate in FinishedLaunching and it worked.

`Mvx.IoCProvider.RegisterSingleton<IMvxPictureChooserTask>(new CustomPictureChooserTask());`

**Comment by ElteHupkes** [comment]
@onurhazar I'm guessing you're overriding the task before it's initialized and the plugin loader overrides it. I tend to look at the [source for MvxSetup](https://github.com/MvvmCross/MvvmCross/blob/master/MvvmCross/Core/MvxSetup.cs#L108) for these cases, because I can't ever remember the order. From there, it seems like `InitializeLastChance()` would be a decent place.

**Comment by PierreYvesBl** [comment]
Hi
We have the same problem on an iPod 6
We correct it with strong events.
I propose to make a PR with this correction.
Interrested?

**Comment by Cheesebaron** [comment]
Yeah, feel free to open a PR.

**Comment by Cheesebaron** [comment]
This should be fixed.
