### ISSUE TITLE
Is MVVMCross Compatible with Xamarin.Forms Version 4.0 Shell?

### ISSUE THREAD

**Issue by RidaNoor** [MvvmCross/MvvmCross#3523]
I am trying to use Shell of Xamarin.Forms 4.0
I have an existing MVVMCross Xamarin.Forms application. I have updated Xamarin.Forms from 2.0.3 to 4.0 but Shell doesn't work with MVVMCross. Is there any solution?

**Comment by TingtingAn** [comment]
MVVMCross doesn't support Shell now.

**Comment by nickrandolph** [comment]
Correction.... Shell doesn't work with MvvmCross..... MvvmCross was here first :-)

The actual answer is that the Shell team are exposing additional interfaces which will make integration easier for third party frameworks. Unfortunately, the initial design didn't cater for MvvmC frameworks in general. 

If you have an existing MvvmCross based application, just ignore Shell - you'll probably find you don't need it anyhow.

I'm closing this issue as there's probably not much more to add at this stage.
