### ISSUE TITLE
Can't Add MvvmCross 6.4.0 nuget package on VS4mac

### ISSUE THREAD

**Issue by orzech85** [MvvmCross/MvvmCross#3534]
## 🐛 Bug Report
If I am trying to add MvvmCross 6.4.0 nuget package on VS4mac I am getting the following error in Package Console:
`Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json`

### Expected behavior
Adding NuGet should be possible without issue.

### Reproduction steps
Create project (eg. .net standard library) and add MvvmCross 6.4.0 nuget package

### Configuration

**Version:** 6.4.0

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

VS4mac version: 8.2.5 (build 5)

**Comment by Cheesebaron** [comment]
I had that exact same issue. Restart VS4mac and it works again.

**Comment by orzech85** [comment]
Restart didn't help. Only update of VS4mac to preview works for me.
