### ISSUE TITLE
Visibility plugin on tvOS

### ISSUE THREAD

**Issue by diegostamigni** [MvvmCross/MvvmCross#3540]
How to get it working on tvOS platform? 

I see it's supported (it's installable on tvOS targets and lists Xamarni.TVOS in nugets dependencies) but I don't see any class I could use to register it nor use it: https://github.com/MvvmCross/MvvmCross/tree/develop/MvvmCross.Plugins/Visibility

**Comment by Prin53** [comment]
@diegostamigni you can use `MvxVisibilityValueConverter` on tvOS like on other platforms:

```cs
set.Bind(view)
    .For(v => v.BindVisibility())
    .To(vm => vm.IsVisible)
    .WithConversion<MvxVisibilityValueConverter>();
```

Just make sure to install `MvvmCross.Plugin.Visibility` package.

CC @martijn00
