### ISSUE TITLE
Resuming Xamarin.Android app results in Setup failure

### ISSUE THREAD

**Issue by nologinatgit** [MvvmCross/MvvmCross#3545]
## 💬 Questions and Help

My application (that uses **v6.3.1**) has a SplashScreen that has this structure:
```csharp
public class SplashActivity : MvxSplashScreenActivity<BasicAndroidSetup, App>
{  

    protected override void OnCreate(Bundle bundle)
    {
      try
      {
        base.OnCreate(bundle);       
        var currentActivity = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>().Activity);  
      }
      catch (Exception e)
      {
        throw;
      }
    }
}
```
It has a base App class:

```csharp
public class App : MvxApplication
{
  public override void Initialize()
  {
    try
    { 
      IoCInit();
      RegisterCustomAppStart<BasicXamarinAppStart>();
    }
    catch (Exception ex)
    {     
      Alert("error:"+ex);
    }
  }
}
```

Also a custom App start class:

```csharp
public class BasicXamarinAppStart : MvxAppStart
{
  public BasicXamarinAppStart(IMvxApplication application, IMvxNavigationService navigationService) : base(application, navigationService)
  { }

  protected override async Task NavigateToFirstViewModel(object hint = null)
  {
    try
    {
      await NavigationService.Navigate<MainTaskViewModel>();
    }
    catch (Exception ex)
    {       
      throw;
    }
  }
}
```
A custom Android setup, too:

```csharp
public class BasicAndroidSetup : MvxAndroidSetup<App>
{
  protected override void InitializeFirstChance()
  {
    base.InitializeFirstChance();   
    Mvx.IoCProvider.LazyConstructAndRegisterSingleton<ITargetUrlHandler>(() => new TargetUrlHandler());
  }
}
```

When I pause the app, open a few other apps and try to resume, I get the following exception:

> MvvmCross.Exceptions.MvxException: Failed to create setup instance ---> MvvmCross.Exceptions.MvxException: Could not find a Setup class for application
>   at MvvmCross.Core.MvxSetupExtensions.CreateSetup[TSetup] () [0x00019] in <26f1720ed3fc494f941e65b1c3a25809>:0 
>   at MvvmCross.Core.MvxSetup.Instance () [0x00015] in <26f1720ed3fc494f941e65b1c3a25809>:0 
>   at MvvmCross.Core.MvxSetupSingleton.CreateSetup () [0x00000] in <26f1720ed3fc494f941e65b1c3a25809>:0 
>    --- End of inner exception stack trace ---
>   at MvvmCross.Core.MvxSetupSingleton.CreateSetup () [0x00017] in <26f1720ed3fc494f941e65b1c3a25809>:0 
>   at MvvmCross.Core.MvxSetupSingleton.EnsureSingletonAvailable[TMvxSetupSingleton] () [0x00045] in <26f1720ed3fc494f941e65b1c3a25809>:0 
>   at MvvmCross.Platforms.Android.Core.MvxAndroidSetupSingleton.EnsureSingletonAvailable (Android.Content.Context applicationContext) [0x00000] in <26f1720ed3fc494f941e65b1c3a25809>:0 
>   at MvvmCross.Droid.Support.V4.MvxFragmentExtensions.EnsureSetupInitialized (MvvmCross.Platforms.Android.Views.IMvxFragmentView fragmentView) [0x0002e] in <80383b211f1049319c9769f83eb14f81>:0 
>   at MvvmCross.Droid.Support.V4.EventSource.MvxBindingFragmentAdapter.HandleCreateCalled (System.Object sender, MvvmCross.Base.MvxValueEventArgs`1[T] bundleArgs) [0x00006] in <80383b211f1049319c9769f83eb14f81>:0 
>   at MvvmCross.Base.MvxDelegateExtensions.Raise[T] (System.EventHandler`1[TEventArgs] eventHandler, System.Object sender, T value) [0x0000b] in <26f1720ed3fc494f941e65b1c3a25809>:0 
>   at MvvmCross.Droid.Support.V4.EventSource.MvxEventSourceFragment.OnCreate (Android.OS.Bundle savedInstanceState) [0x00014] in <80383b211f1049319c9769f83eb14f81>:0 
>   at MvvmCross.Droid.Support.V4.MvxFragment.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <80383b211f1049319c9769f83eb14f81>:0 
>   at Android.Support.V4.App.Fragment.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <bf16d415aab34555a14e37e34b61be1d>:0 
>   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.29(intptr,intptr,intptr)

According to the source code, the `FindSetup` can't find the necessary assembly when the `MainActivity` tries to use the MvvmCross architecture:

```csharp

protected virtual void CreateSetup(Context applicationContext)
{
   var setupType = FindSetupType();
   if (setupType == null)
   {
       throw new MvxException("Could not find a Setup class for application");
   }
}

protected virtual Type FindSetupType()
{
   var query = from assembly in AppDomain.CurrentDomain.GetAssemblies()
                      from type in assembly.ExceptionSafeGetTypes()
                      where type.Name == "Setup"
                      where typeof(MvxAndroidSetup).IsAssignableFrom(type)
                     select type;

   return query.FirstOrDefault();
}
```
I don't even know if and **how** I could override the `FindSetupType` class to at least hardcode my setup class type...

I found this issue but can't tell if it is the same situation (I don't use Xamarin.Forms): https://github.com/MvvmCross/MvvmCross/issues/3041

Will it really be fixed in version 7.0.0 or should I look for some workaround? Should I reroute somehow to the `SplashActivity` when the resume happens?

**Comment by nologinatgit** [comment]
I try to modify its name then but a question remains: how does it work in the first place if the name is incorrect?

**Comment by Cheesebaron** [comment]
Probably because of `public class SplashActivity : MvxSplashScreenActivity<BasicAndroidSetup, App>`

**Comment by nologinatgit** [comment]
Renaming the class solves the `Setup` problem but I face a new one: some initial code (that was part of the `SplashScreenActivity`) seems to be uninitialized.
 
Can I somehow "rerun" the entire initialization? It looks that jumping in the "middle" skips some required steps and my provider can't work properly. Does the `EnsureInitialized` method create a default and empty provider?

Also, I added an `Application` class to the Android project, but its constructor is never hit (I even added to the Manifest file). How can I tell that the Android should use that instead of the default `Application` class?

```csharp
[Application]
public class AndroidApplication : MvxAndroidApplication<Setup, App>
{
  public AndroidApplication(IntPtr javaReference, JniHandleOwnership transfer)
      : base(javaReference, transfer)
  {
    UserDialogs.Init(() => Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>().Activity); 
    UserDialogs.Instance = new CustomDialogs(() => Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>().Activity); 
  }
}
```

**Comment by softlion** [comment]
This is not the correct implementation of the AndroidApplication class. It must be a default constructor.

The content of the (IntPtr javaReference, JniHandleOwnership transfer) constructor must be empty. It is reserved for xamarin infrastructure.

**Comment by nologinatgit** [comment]
Unfortunately when we used an Application instance, there were unwanted consequences in the default behavior (there were exceptions in navigation) so we dropped it and returned to use the `MainActivity`.

**Comment by softlion** [comment]
No it works fine with an application class. But you must be tripple time more cautious about your pause/resume calls and services.
