### ISSUE TITLE
Failed to resolve type MvvmCross.Plugins.File.IMvxFileStore

### ISSUE THREAD

**Issue by Geekdebabi** [MvvmCross/MvvmCross#3554]
## 🔙 Regression

(Excuse my level of English I am French. I make a little effort to share my problem in English)

Since the update of some packages which I forgot the old versions, I have the problem below.
It should be noted that I did not modify my code.
I took the test project of MvvmCross "TipCal" and I have the same problem as in this project.

The error i have is : 

{MvvmCross.Platform.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.Plugins.File.IMvxFileStore
  at MvvmCross.Platform.IoC.MvxSimpleIoCContainer.Resolve (System.Type t) [0x0001c] in D:\git\MvvmCross\MvvmCross\Platform\Platform\IoC\MvxSimpleIoCContainer.cs:245 
  at MvvmCross.Platform.IoC.MvxSimpleIoCContainer.Resolve[T] () [0x00000] in D:\git\MvvmCross\MvvmCross\Platform\Platform\IoC\MvxSimpleIoCContainer.cs:235 
  at MvvmCross.Platform.Mvx.Resolve[TService] () [0x00005] in D:\git\MvvmCross\MvvmCross\Platform\Platform\Mvx.cs:33 
  at Smarty.Core.Common.JsonDictTextProvider..ctor () [0x00009] in C:\Users\MOKACOU\Source\Workspaces\Projet SAPHIR V3\SaphirV3\SAPHIRV3-DEV\Smarty.Core\Common\JsonDictTextProvider.cs:16 }

### Reproduction steps
the line of my code i have the problem : 

IMvxFileStore fileStore = Mvx.Resolve<IMvxFileStore>();

### Configuration

**Version:** 5.7.0 and higher

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Is this in Release configuration only, or both?

**Comment by Geekdebabi** [comment]
both

**Comment by xmesaj2** [comment]
I've added ``MvvmCross.Plugin.File`` to ``TipCalc.Core`` and ``TipCalc.Droid`` (version 6.2.2, as MvvmCross is also 6.2.2 there), it doesn't throw exception for me on Android 9 phone. Using VS2019 16.3.1.

```c#
using System.Threading.Tasks;
using MvvmCross;
using MvvmCross.Plugin.File;
using MvvmCross.ViewModels;
using TipCalc.Core.Services;

namespace TipCalc.Core.ViewModels
{
    public class TipViewModel : MvxViewModel
    {
        private readonly ICalculationService _calculationService;
        private readonly IMvxFileStore _mvxFileStore;

        public TipViewModel(ICalculationService calculationService)
        {
            _calculationService = calculationService;
            _mvxFileStore = Mvx.IoCProvider.Resolve<IMvxFileStore>();
        }

        private string _nativePath;

        public override async Task Initialize()
        {
            await base.Initialize();

            _nativePath = _mvxFileStore.NativePath("");
            SubTotal = 100;
            Generosity = 10;
            Recalcuate();
        }
```

``_nativePath = "/data/user/0/TipCalc.Droid.TipCalc.Droid/files"``
