### ISSUE TITLE
MvxVisibilityValueConverter opposite value hardware and simulator

### ISSUE THREAD

**Issue by AadGlasbergen** [MvvmCross/MvvmCross#3569]
## 🐛 Bug Report

set.Bind(RegistrationButton).For("Visibility").To(vm => vm.VisibilityRegistrationButton).WithConversion<MvxVisibilityValueConverter>();
gives opposite value in simulator and on hardware.
### Expected behavior
Same behavior on simulator and on hardware
### Configuration

**Version:** 6.3.1

**Platform:** 
- [x ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Use:

```csharp
set.Bind(RegistrationButton).For(v => v.BindVisible()).To(vm => vm.VisibilityRegistrationButton);
```

**Comment by AadGlasbergen** [comment]
The Button is a UIBarButtonItem there is no .BindVIsible() for a UiBarButtonItem

**Comment by Cheesebaron** [comment]
Ehm... UIBarButtonItem does not have a `Hidden` property. You cannot hide these... Only way to hide them is to remove them. Or alternatively you can set `Enable` to false.
