### ISSUE TITLE
Error after updating from 6.3.1 to 6.4.0

### ISSUE THREAD

**Issue by StepanMynarik** [MvvmCross/MvvmCross#3572]
## 🔙 Regression

I did no changes in initialization logic for ages. After updating, the following exception started to appear on launch, during splash screen (thrown when calling base.OnCreate inside override OnCreate method inside a SplashScreen class).

Exception: MvvmCross.Exceptions.MvxIoCResolveException: 'Failed to resolve parameter for parameter viewToViewModelNameMapping of type IMvxNameMapping when creating MvvmCross.ViewModels.MvxViewModelViewTypeFinder. You may pass it as an argument'

### Old (and correct) behavior
App launched like breeze.

### Current behavior
App hangs on splashscreen while resolving various IoC dependencies.

### Reproduction steps
No idea. Creating 1:1 demo project would be rather complicated I'm afraid :(

### Configuration

**Version:** 6.4.0
**Logger:** Serilog

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by StevenKek** [comment]
I noticed 'IMvxNameMapping' is being instantiated and registered in 'MvxSetup.InitializeViewModelTypeFinder'. This is not called in my case, because 'MvxViewModelViewTypeFinder' is being resolved from somewhere before that can happen. No idea why.

**Comment by StevenKek** [comment]
New intel: last log message I get when set to verbose is "Setup: StringToTypeParser start" (from MvxSetup.InitializeSecondary)

**Comment by StevenKek** [comment]
![image](https://user-images.githubusercontent.com/46678816/65518071-02a83a80-dee4-11e9-9634-b9d9048afbd9.png)
I did the following overrides in my custom droid Setup class and found out the exception is thrown when I try to step over the highlighted line of code. The 'InitializeViewModelTypeFinder' override code is just it's base implementation copy/paste for debugging purposes.

The weird thing is the first line above the highlighted line is creating the very thing it can't then resolve.

**Comment by softlion** [comment]
see https://github.com/MvvmCross/MvvmCross/issues/3589

**Comment by c-lamont** [comment]
@StevenKek Thanks for the workaround, it worked for me 👍

**Comment by CYLMos** [comment]
It's very helpful! Thanks!

**Comment by SergioZgz** [comment]
this is still happening (6.4.2)  thanks for the work around

**Comment by UnreachableCode** [comment]
This solved my issue on 6.4.2. Has it been fixed yet? I couldn't tell with softlion's link.
