### ISSUE TITLE
System.InvalidCastException getting `MvxAppCompatActivity<TViewModel>.ViewModel`

### ISSUE THREAD

**Issue by ElteHupkes** [MvvmCross/MvvmCross#3576]
## 🐛 Bug Report
This issue, in all likelihood the same as #1305 and #3018, has been popping up sporadically in our diagnostics for a long time now. Since it was annoying me I figured I'd take a look at how this could possibly happen, and after some thinking it through I solved the puzzle and managed to work out steps to reproduce it. What happens is that a restored view incorrectly concludes that its view model resides in the `IMvxSingleViewModelCache` when this view model is really of a different type. It ends up setting it as its `DataContext`, and the first time something tries to retrieve the view model off the view it tries to cast it and crashes with above exception.

### Expected behavior
No crash, no using of incorrect view model.

### Reproduction steps
To reproduce this any MvvmCross app that can have an activity stack of 2 (or more) activities will do, I'm using a hypothetical app consisting of `ParentView<ParentViewModel>` and `ChildView<ChildViewModel>` in this example, where `ParentView` opens `ChildView`. To reproduce the crash:

1. Launch the app, showing `ParentView`, and open `ChildView` so your activity stack consists of `ChildView` on top of `ParentView`
2. Press the home button to leave the app and flood your memory so it will get purged from memory with only its saved state remaining. I like to use [Developer Toolbelt](https://play.google.com/store/apps/details?id=com.tspoon.androidtoolbelt) ([ApkPure to drop on your emulator](https://apkpure.com/developer-toolbelt-fill-ram/com.tspoon.androidtoolbelt)) for that.
3. Return to your app through the app drawer. The activity stack will be restored as it was before.
4. Press the home button again to suspend the app, _don't flood memory, keep it active_.
5. Return to the app through the app drawer
6. Press the back button to return to `ParentView`. Crash!

Explanation:
When the app is suspended in step 2, `ParentView` stores its view model in the cache with counter ID 1, quickly overwritten by `ChildViewModel` with ID 2. What's important is that `ParentView` has an entry in its bundle stating that counter ID 1 matches its view model. When the app is purged from memory and restored from state in step 3, the view model cache will have its counter starting from 0 again. Suspending the app again (step 4) will have `ChildView` store its view model in the cache with counter ID 1. `ParentView`, not having been restored at all yet, will not do anything. When returning to the app in step 5, `ChildView` is still active and thus will not be recreated, so the view model cache will not be cleared. Pressing the back button will restore `ParentView`, which no gets and clears the view model that's in the cache because it matches its stored counter ID. Since this is a `ChildViewModel`, the app will crash as soon as the `ViewModel` property is used for the first time, which happens somewhere later in `OnCreate`.

### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by ElteHupkes** [comment]
As for solving this, I don't see any obvious solution that keeps the counter. Type checking isn't enough because an activity could be present twice which could lead to the same problem. GUIDs for referencing might be the best option.

I've a question though: does anybody know how often the ViewModel from the cache is actually used? In my experience most of the time the app either stays active or is purged from memory entirely, and in neither case the cache is used. The developer options muddied the waters a bit with that "Don't keep activities" option which has some very specific use cases but is otherwise very unrealistic in the way that Android frees up memory (again, in my experience).

**Comment by ElteHupkes** [comment]
What I'm going to do: I'll register a custom `IMvxSingleViewModelCache` in the next version of our app that uses GUIDs (to get rid of the crash) and also logs an event whenever a view model from the cache is used (i.e. `GetAndClear(Bundle)` returns something non-null). If it turns out that this is a common occurrence I'll submit a PR with the GUID cache, otherwise I'd suggest removing the cache entirely.

**Comment by Cheesebaron** [comment]
It is strange that you run into this issue, none of my Android Apps running MvvmCross show anything similar.

Is `ChildView` an Activity or a Fragment?

**Comment by ElteHupkes** [comment]
An activity.

**Comment by ElteHupkes** [comment]
It's really only a tiny portion of sessions that crashes this way, because it requires such a specific sequence of suspending / reopening the app, but I can't remember it ever _not_ being in our logs.

**Comment by ElteHupkes** [comment]
@rweisert As a workaround, you can override the default single view model cache with this one:

```
    [Preserve(AllMembers = true)]
    public class OverrideSingleViewModelCache : IMvxSingleViewModelCache
    {
        private const string BundleCacheKey = "__mvxVMCacheKey";

        private string _currentCacheKey;
        
        private IMvxViewModel _viewModel;
        
        public void Cache(IMvxViewModel toCache, Bundle bundle)
        {
            if (toCache == null) return;
            
            var guid = Guid.NewGuid();
            _currentCacheKey = guid.ToString();
            _viewModel = toCache;
            bundle.PutString(BundleCacheKey, _currentCacheKey);
        }

        public IMvxViewModel GetAndClear(Bundle bundle)
        {
            var vm = _viewModel;
            _viewModel = null;

            var key = bundle?.GetString(BundleCacheKey, null);
            if (key != null && key == _currentCacheKey && vm != null)
            {
                return vm;
            }

            return null;
        }
    }
```

Register in `Setup.InitializeFirstChance()`. I haven't had a crash with this version so far. My version also logs whether any view models are ever successfully used, that does appear to be the case, although it is very rare. It happens to a fraction of 1% of users, I'm assuming there's specific devices / Android implementations that do indeed kill individual activities. Whether it's worth keeping around for that I'm not sure.
