### ISSUE TITLE
iPhone Simulator always remains black

### ISSUE THREAD

**Issue by RidaNoor** [MvvmCross/MvvmCross#3578]
Hi,

I am developing a Xamarin.Forms application. I try to run it on iPhone Simulator , build is successful but the simulator always remain black and in Visual Studio, its always "Lauching the app on iPhone Xs 12.0 "...
I am using Visual Studio 2019. And I am using MVVMCross in the App.
Any quick help will be really appreciated.

**Comment by Cheesebaron** [comment]
If you Simulator is just showing a black screen, then it sounds like a different problem than MvvmCross being at fault.

**Comment by markuspalme** [comment]
I suggest closing this issue because it has not seen activity and is most likely a Xamarin bug that can be fixed by rebooting the machine (I hade this in MvvmCross and non-Mvx projects).
