### ISSUE TITLE
'Popped page does not appear on top of current navigation stack' error on MvxPopPresentationHint with viewModelToPopTo on iOS.

### ISSUE THREAD

**Issue by agat366** [MvvmCross/MvvmCross#3585]
## 🐛 Bug Report

Project built with Xamarin.Forms.

On calling the following:

            await Navigation.ChangePresentation(new MvxPopPresentationHint(typeof(SeveralStepsDeeperViewModel), true));

an error "System.NotSupportedException: Popped page does not appear on top of current navigation stack, please file a bug." occurs.

The thing also is that my top ViewModel (page) is about 3-4 steps higher than the view I am trying to pop to (if that helps).

The stack:

> at Xamarin.Forms.Platform.iOS.NavigationRenderer.OnPopViewAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00059] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\NavigationRenderer.cs:322 
>   at Xamarin.Forms.NavigationPage.Xamarin.Forms.INavigationPageController.RemoveAsyncInner (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean fast) [0x00081] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:328 
>   at Xamarin.Forms.NavigationPage.PopAsyncInner (System.Boolean animated, System.Boolean fast) [0x0004c] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:308 
>   at Xamarin.Forms.NavigationPage.PopAsync (System.Boolean animated) [0x00140] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:190 
>   at MvvmCross.Forms.Presenters.MvxFormsPagePresenter.PopToViewModel (Xamarin.Forms.INavigation navigation, S
> ystem.Type viewModelType, System.Boolean animate) [0x00078] in D:\a\1\s\MvvmCross.Forms\Presenters\MvxFormsPagePresenter.cs:302 
>   at MvvmCross.Forms.Presenters.MvxFormsPagePresenter.ChangePresentation (MvvmCross.ViewModels.MvxPresentationHint hint) [0x0020a] in D:\a\1\s\MvvmCross.Forms\Presenters\MvxFormsPagePresenter.cs:205 
>   at MvvmCross.Forms.Platforms.Ios.Presenters.MvxFormsIosViewPresenter.ChangePresentation (MvvmCross.ViewModels.MvxPresentationHint hint) [0x00030] in D:\a\1\s\MvvmCross.Forms\Platforms\Ios\Presenters\MvxFormsIosViewPresenter.cs:57 
>   at MvvmCross.Base.MvxMainThreadAsyncDispatcher+<>c__DisplayClass1_0.<ExecuteOnMainThreadAsync>b__0 () [0x00022] in D:\a\1\s\MvvmCross\Base\MvxMainThreadAsyncDispatcher.cs:27 
>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1
> 021 
>   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:178 
> 

Android is fine with that.

### Configuration

**Version:** 6.4.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by Cheesebaron** [comment]
The NotSupportedException comes from Xamarin.Forms. Please open an issue in the Xamarin.Forms repo.

**Comment by agat366** [comment]
Unfortunately, (and as I can spot if from long-long time ago, nothing changes), MvvmCross-related devs don't quite pay attention to details (as well as to the documentation providing).
I've found out what was the cause of the issue. And it's definitely not Xamarin.Forms problem.
The issue appears because MvvmCross doesn't check well what views structure is in the navigation stack. It just considers all the views just have simple NavigationStack, when some of them might have Popups etc.
And obviously, when the "engine" simply tries to pop all the pages to the required ViewModel, XF throws exception as just can't do that. So, I wouldn't blame XF for that (at least).
