### ISSUE TITLE
ViewModel Constructor Dependency Injection when upgrading from 6.3.1 to 6.4.1

### ISSUE THREAD

**Issue by foehammer88** [MvvmCross/MvvmCross#3586]
When upgrading from 6.3.1 to 6.4.1, Dependency Injection in ViewModel constructors is no longer working, and services that are injected into the root ViewModel are not being initialized and are null.

Are there any examples on what needs to be changed for the 6.4.0 upgrade in order for ViewModel constructor injection to continue to work as before?

**Comment by Cheesebaron** [comment]
We added better lookup of which constructor to use in #3491. However, this should not break anything. I've updated to latest 6.4.1 in a couple of Apps and it works fine.

Do you have more information about how to reproduce your issue?

Also, it would be much appreciated if you used the issue templates.

**Comment by nickrandolph** [comment]
@Cheesebaron are you using full linking in your apps - I'm guessing that some of the constructors are being striped out. We should change the registration of some of the core classes to use the factor method overload to call the constructor which would fix this problem, and remove the use of reflection.

**Comment by softlion** [comment]
If you are using full linking, you should add [Preserve(AllMember=true)] on all your viewmodel classes. This will prevent the contructors, public properties and commands from being optimized away (if you use binding in android xml layouts, not in code).

**Comment by MrXemiu** [comment]
I believe I'm having this same issue.  In my setup class I override `CreateIocProvider()` and return a new `AutofacMvxIocProvider` (from Autofac.Extras.MvvmCross).  It was working prior to updating to Mvx 6.4.1, now I get the following exception + stack trace in my splash screen `base.OnCreate()` call:

![image](https://user-images.githubusercontent.com/4266607/67441549-8411ec00-f5ba-11e9-90e8-04ed19964b61.png)
