### ISSUE TITLE
Stuck after updating from 6.3.1 to 6.4.0

### ISSUE THREAD

**Issue by delapiero** [MvvmCross/MvvmCross#3595]
## 🔙 Regression

My app stopped working after upgrade MvvmCross from 6.3.1 to 6.4.0

It is stuck on the splash screen.

// App.cs in core project

    public class App : MvxApplication
    {
        public override void Initialize()
        {
            // this is not called
        }
    }

// MainApplication .cs in droid project

    [Application]
    public class MainApplication : MvxAndroidApplication<Setup, AndroidApp>
    {
        private string[] permissionsList;
    
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
        : base(handle, transer)
        {       
         // this is called     
        }            
    }

// Setup.cs in droid project

    public class Setup : MvxAndroidSetup<AndroidApp>
    {
        protected override IMvxAndroidViewPresenter CreateViewPresenter()
        {
            // this is called
            return new MvxAppCompatViewPresenter(AndroidViewAssemblies);
        }
        public override IEnumerable<Assembly> GetViewModelAssemblies()
        {
            return new[] { typeof(App).Assembly };
        }
        protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            MvxAppCompatSetupHelper.FillTargetFactories(registry);
            base.FillTargetFactories(registry);
        }
    }

// SplashScreen.cs in droid project
   
    [Activity(Label = "SplashScreen", MainLauncher = true, Theme = "@style/AppTheme.Splash", NoHistory = true, ScreenOrientation = ScreenOrientation.Portrait)]
    public class SplashScreen : MvxSplashScreenAppCompatActivity<MvxAppCompatSetup<App>, App>
    {       
         public SplashScreen() : base(Resource.Layout.SplashScreen)
         {
             // this is called
         }
    }

### Old (and correct) behavior
Application is initialized

### Current behavior
Application is not initialized

### Configuration

**Version:** 6.4.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by delapiero** [comment]
EDIT: I traced the exception which I guess is breaking the initialization process:
> Could not resolve type with token 01000015 from typeref (expected class 'System.Drawing.Color' in assembly 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')

**Comment by eriove** [comment]
This seems related to #3614
