### ISSUE TITLE
Binding on MvxTabbedPage not working

### ISSUE THREAD

**Issue by Greenkiller21** [MvvmCross/MvvmCross#3597]
## 🐛 Bug Report

Binding not working on the MvxTabbedPage element but works with the Xamarin bindings.
This works : `SelectedTabColor="{Binding TabColor}"`
This doesn't : `mvx:Bi.nd="SelectedTabColor TabColor"`
### Expected behavior
Changing the color of the current tab
### Reproduction steps
Create a new project with at least one page in the MvxTabbedPage
### Configuration
**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Which type is `TabColor`?

**Comment by Greenkiller21** [comment]
> 
> 
> Which type is `TabColor`?

It's a System.Drawing.Color

**Comment by Cheesebaron** [comment]
You will need a converter to convert it to the platform specific color in the mvx version of the binding.

**Comment by Greenkiller21** [comment]
Okay. Thank you, I hadn't thought of that.
