### ISSUE TITLE
System.Drawing.Color not available on Android

### ISSUE THREAD

**Issue by viktorszekeress** [MvvmCross/MvvmCross#3614]
## 🐛 Bug Report

Since updating to Mvvmcross 6.4.1, `MvxColorValueConverter` implementation changed to use `System.Drawing.Color` instead of `MvxColor`, so changed my converters to return `System.Drawing.Color`. I have several converters inside Android library project and I'm facing a build error:

`'MyColorValueConverter.Convert(MyClass, object, CultureInfo)': return type must be 'Color' to match overridden member 'MvxColorValueConverter<MyClass>.Convert(MyClass, object, CultureInfo)'`

```
Error	CS7069	Reference to type 'Color' claims it is defined in 'System.Drawing.Common', but it could not be found	TransPac.Droid	
```

This error occurs only when converters are placed inside Android library project, not when they are inside .NetStandard project AND only occurs when building from VS 2017, not from VS 2019.

### Expected behavior
No build errors in color converters.

### Reproduction steps
1. Create Android library project
2. Extend MvxColorValueConverter class
3. Build on VS 2017

### Configuration
VS 2017 only

**Version:** 6.4.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by tbalcom** [comment]
Did you try adding a NuGet reference to [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/4.6.0) in the Android project?

**Comment by viktorszekeress** [comment]
Yes, tried that, no effect.

**Comment by Cheesebaron** [comment]
It should add a Framework Reference to OpenTK. Can you check that it is referenced in your project?

**Comment by Cheesebaron** [comment]
Yeah, we don't advertise support for VS2019.

**Comment by viktorszekeress** [comment]
Shouldn't it be mentioned in docs, that MvvmCross.Plugin.Color is not supported by VS2017?

**Comment by Cheesebaron** [comment]
@viktorszekeress it was unknown to us until you pointed the issue out. You are welcome to add it to the docs.
