### ISSUE TITLE
Show MvxTabBarViewController as Modal?

### ISSUE THREAD

**Issue by stefan89** [MvvmCross/MvvmCross#3630]
Since I can't find the answer in the documentation, I ask it here:
Is it possible to show a MvxTabBarViewController (so a page with tabs) as a modal page?(so an overlay page that animates from the bottom into the screen).

A MvxPageViewController show as Modal would also fit our needs if that is possible

If it is not possible out of the box, how could I achieve this?

**Comment by Cheesebaron** [comment]
Have you tried using the modal presentation attribute on it?

**Comment by stefan89** [comment]
Yes,  I tried it using the MvvmCross Playground project:

[MvxModalPresentation(ModalPresentationStyle = UIModalPresentationStyle.OverFullScreen, ModalTransitionStyle = UIModalTransitionStyle.CrossDissolve)]
    public partial class TabsRootView : MvxTabBarViewController<TabsRootViewModel>

The exception I get when I navigate to the page is:
Trying to show a tab without a TabBarViewController, this is not possible!

Thrown in:   at MvvmCross.Platforms.Ios.Presenters.MvxIosViewPresenter.ShowTabViewController

**Comment by Cheesebaron** [comment]
As it is now, the presenter in MvvmCross expects the TabBarViewController to be a root ViewController. So no, it is not possible to get that behavior out of the box.

You would need customize the [MvxIosViewPresenter](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Ios/Presenters/MvxIosViewPresenter.cs) in order to achieve such behavior.

**Comment by stefan89** [comment]
Is there a comprehensive explanation how this works? 
I was looking at: https://www.mvvmcross.com/documentation/platform/ios/ios-view-presenter?scroll=15#extensibility but I am missing a good example how it all comes together

**Comment by Cheesebaron** [comment]
Basically:

1. You put a presentation attribute on your View
2. When you navigate to said View, the MvvmCross presenter reads that presentation attribute
3. From the type of Presentation attribute and properties set on it, it decides how to present said View

You can override which presenter to use in the `Setup.cs` file by overriding the method `CreateViewPresenter` and just returning your own.

**Comment by stefan89** [comment]
Thanks for your help. I know enough for now.

**Comment by warpedgeoid** [comment]
This has been added to the 6.5.0 milestone, so assuming this means the default presenter will be gaining support for tabs in modals? If so, would it be possible to also do this with MvxPageViewController?
