### ISSUE TITLE
Breaking changes when migrate from 5.6.0 to 6.4.1 regarding button commands

### ISSUE THREAD

**Issue by Sonic3R** [MvvmCross/MvvmCross#3635]
## 🐛 Bug Report

Well, I decided to move from MvvmCross 5.6.0 to 6.4.1. I managed to correct errors and classes, used async methods from mvvmcross (`MvxViewModel` especially).

I have a view model, called `LoginViewModel` which is used to `LoginPage` xaml. The link between viewmodel and page (as dictionary) is constructed in `InitializeViewLookup` from `Setup` class.

```cs
public static void Initialize()
 {
      var viewModelLookup = new Dictionary<Type, Type>
      {
        {typeof(LoginViewModel), typeof(LoginPage)},
        ...
      }

      Container = Mvx.IoCProvider.Resolve<IMvxViewsContainer>();
      Container.AddAll(viewModelLookup);
}
```

and then in Setup, I do:

```cs
protected override IMvxViewsContainer InitializeViewLookup(IDictionary<Type, Type> viewModelViewLookup)
{
      MyLookup.Initialize();
      return MyLookup.Container;
}
```

In LoginViewModel class, I have a command:

```
public ICommand LoginCommand => _loginCommand = _loginCommand ?? new MvxCommand(DoLogin, () => CanExecute);
```

and on UI:

```xml
<Button Text="Login" Command="{Binding LoginCommand}"/>
```

I tried to set binding but I got another error described here: https://github.com/MvvmCross/MvvmCross/issues/3634

### Expected behavior
Command should work. I put breakpoint in `DoLogin` method and is not reached in Debug mode.

### Configuration

**Version:** 6.4.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Nickolas-** [comment]
Hi @Sonic3R , 
The problem in  `() => CanExecute` . Try yo delete it and test again. If it works for you , just add this logic in command method.
