### ISSUE TITLE
Freezing UI on iOS 13 with MvvmCross 5.6.3

### ISSUE THREAD

**Issue by RobertMcCoy** [MvvmCross/MvvmCross#3638]
## 💬 Questions and Help

Recently we have begun testing iOS 13 against our MvvmCross 5.6.3 application. We noticed immediately that certain parts of our application just freeze for a myriad of different reasons. We assume there is a root cause that we are just not seeing, and we are kind of stuck on this at the moment. I have created a post out on the Xamarin-Chat Slack, but it has not received any feedback or help, so I am turning to the GitHub issues. We have been deferring the exploration of this issue on our development team as building against iOS 12 does not give us any issues, and we did not have a lot of time to devote to investigating this issue, but we are now dedicating some time to it.

There are some similarities between portions of where the application is freezing, but the different freezing causes do not appear to be the same:
* Freeze #1: When we navigate to an MvxViewModel, there is a binding to a string property in a model that is loaded during initialize. If we comment out this simple string binding, the view continues to work as expected. If we leave the binding in, the application freezes, but breakpoints indicate the rest of the method is invoking correctly. We have tried setting the property we are binding to to be initialized before the binding occurs with a dummy object and we have tried just binding to a property that is on the VIewModel rather than a nested property. None of this appears to fix the freezing. The one caveat here that I _think_ might be causing this, but I can't figure out why is the ViewModel that causes this one to appear is created with the deprecated `ShowViewModel` method, but the ViewModel that is navigated to and freezing is navigated to with the `IMvxNavigationService`. We also do not have any of the presentation attributes on the ViewControllers.
* Freeze #2: We have a ViewModel that is similar to the above navigation wise. There is a ViewModel that gets created with `ShowViewModel`, but it navigates to another ViewModel with `navigationService.Navigate<MyFreezingViewModel, MyFreezingVmArgs>(myArgs)`. *But* this ViewModel is not freezing when the bindings are being created/applied. Instead, this ViewModel renders correctly and does not freeze _until_ the user taps into a text field and enters any character. There is no application output or exception being thrown, and the app doesn't actually crash, it's more of a frozen UI.

We understand we have a large amount of accumulated technical debt given these odd inter-mixed uses of ShowViewModel and the NavigationService, as well as the lack of presentation attributes. Our ultimate goal here is to find the "easiest" way to resolve this issue, but we aren't exactly sure how to identify the root cause correctly since the Framework seems to be swallowing exceptions or looping infinitely somewhere.

**Comment by RobertMcCoy** [comment]
Here is the link to the Xamarin-Chat Slack message: https://xamarinchat.slack.com/archives/C099A1JBA/p1573748008161900

(pasted here in case that message gets swalloed by the Slack limit)

After building on iOS 13 we are beginning to notice weird behavior with our application. There is a certain page in the app that once you open it, the application just freezes. No crash, no specific errors in the log, just freezes up. It works perfectly fine on iOS 12. I have identified the culprit, but I can’t make any sense of why this might be crashing. We are running MvvmCross 5.6.3.
Our application is freezing because of a null string in a binding, which doesn’t make any sense because this hasn’t been an issue in the past. If I comment out the following line, the page loads just fine:
bindingSet.Bind(this.myObjectNameLabel).To(vm => vm.MyObject.Name);
To give a bit more context: We have an object in the ViewModel, let’s say MyObject, and this object has a Name property. This ViewModel only populates MyObject in the Initialize method, so it is possible that when ViewDidLoad is invoked, MyObject could be null.
I tried adding this to the ViewModel:
public string MyObjectName => MyObject?.Name ?? string.Empty and then subsequently updating the binding to just be .To(vm => vm.MyObjectName), but the application is still freezing. Does anyone have any idea why this is happening?

**Comment by Cheesebaron** [comment]
I can tell you it works fine with latest MvvmCross version with iOS 13. So I highly suggest you resolve some of your technical debt and upgrade.

Do you have any Stack Trace or something else to go off from?

**Comment by RobertMcCoy** [comment]
@Cheesebaron We are aware of the issues that are likely to occur as we continue to defer this upgrade. The application is massive and has some seriously complex use cases, and we are attempting to slowly iterate through the codebase to update the navigation pattern we use when possible, but it will take time.

We have absolutely no stack traces. The application just freezes, and can no longer be interacted with, but there are no application output errors. I turned the Binding Log Level to Diagnostic and still did not receive any errors. There was a weird binding error being thrown related to a MvxValueConerter cast for our UITableViewCells, but it appears to be unrelated to the issue we are seeing.

**Comment by RobertMcCoy** [comment]
I have created a basic 5.6.3 MvvmCross project and it does not look like this issue is occuring out of the box with the framework. I have it setup with a Main, Second, and Third ViewModel. Main is the startup VM, second gets navigated to with `ShowViewModel()`, and Third gets navigated to with the NavigationService. No issue there, and also no issues with no presentation attributes.

**Comment by RobertMcCoy** [comment]
Turns out it was a custom control that was infinitely looping in `LayoutSubviews` that was kind of hard to catch, adding a consistent height constraint to this on the ViewController . This probably won't be helpful to anyone that stumbles on this in the future. My recommendation: if you see your application freezing, try and pause the debugger at first and see if you can find where it's looping like that. May not get you what you want, but do it a few times and you will probably find what is wrong with your app specifically. Sorry I can't be more help :(
