### ISSUE TITLE
SearchBar (or other Controls) in the TitleBar?

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#3642]
I just saw your video on the Xamarin YouTube channel about MvvmCross and was instandly wondering, was this made with MvvmCross and if so, how? At about 18:30 in the video here: https://youtu.be/fRo2tW51rWQ?t=1110 it looks like a SearchBar control (and other controls) placed in the NavigationPage NavigationBar. I was trying this before to implement the SearchBar into it and couldn't find a way todo this with MvvmCross in Forms. So is this now possible and if so, how? It would be great to be able to place the SearchBar up there and it will make the app feel more native because nowardsday every native app places such controls up there. Espacially this is also possible with Xamarin.Forms Shell now so I think it would be great to have such options in other frameworks as well.

**Comment by Cheesebaron** [comment]
You can do whatever you want up there, it is just a view. This isn't specific to MvvmCross, but a View concern.
