### ISSUE TITLE
await NavigaionService.Navigate<>(); issue

### ISSUE THREAD

**Issue by MelonStrew** [MvvmCross/MvvmCross#3650]
### 🐛 Bug Report
I have a command that disallow multiple calls 
What i want is to take result from await NavigaionService.Navigate<>(); when navigation is done fully. I mean push page animation on android devices. Cause of it user can do multiple calls to button command and produced more than 1 page as a result

Expected behavior
awaiting NavigationService will ends aftter animation is done

Actual Result 
await NavigaionService.Navigate<>() returns value before page animattion is done

Reproduction steps
await NavigaionService.Navigate<>()

### Platform:
 🤖 Android

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

**Comment by nasibu** [comment]
I have a similar issue with multiple execution from commands with navigation in Android. The simplest example is the navigation from Activity1 (ViewModel1) to Activity2 (ViewModel2).

I bind the following command to a View in Activity1 (`app:MvxBind="Click ToNextCommand"`)


```
private IMvxAsyncCommand _toNextCommand;
public IMvxAsyncCommand ToNextCommand => _toNextCommand ??= new MvxAsyncCommand(ToNext);

private async Task ToNext()
{
     await NavigationService.Navigate<ViewModel2>();
}
```
When I double Tap on the View, then Activity2 will open twice.

**Comment by Nickolas-** [comment]
@nasibu it expectable behaviour ,  two taps , two times commands will invoke Navigate. Use some lock mechanism.
