### ISSUE TITLE
MVVMCross with Xamarin.Forms

### ISSUE THREAD

**Issue by RidaNoor** [MvvmCross/MvvmCross#3652]
I have upgraded the version of Xamarin.Forms to 3.6.0 from 2.3.0. It was initially working fine but now after the upgrade, I get this error in MainActivity.cs file of .Droid project(Please check the image given below):

![image](https://user-images.githubusercontent.com/34579371/70546709-96a7ab00-1b91-11ea-9c42-3cb844514cdf.png)

1. Are there any particular steps to follow while upgrading the xamarin.forms in a MVVMCross app?
2. Which version of MVVMCross is compatible with Xamarin.Forms 3.6.0?
3.  When I upgrade the MVVMCross packages, I need help with changing the setup of the App?

**Comment by markuspalme** [comment]
Did you do a clean of the project before rebuilding it? Xamarin caches a lot of build artefacts to improve the build time and errors like this can be a side effect.

**Comment by Cheesebaron** [comment]
Closing this as invalid, due to not using template and no information about version of MvvmCross used etc.
