### ISSUE TITLE
Android MvxSpinner local:MvxBind not bound?

### ISSUE THREAD

**Issue by zerokewl88** [MvvmCross/MvvmCross#3654]
## 🐛 Bug Report

I am attempting to use the MvxSpiner in a Android Project and unable to use examples / get the bind to work. 

I have the following in my core model, which is populated from a database, and then displays ok in the drop down (when clicked) in the android emulator fine.  But when i select a item, i can't get it to trigger the ICommand using the HandleItemSelected.

ViewModel 

```csharp
        private List<string> _smartCardStatuses;
        public List<string> SmartCardStatuses
        {
            get { return _smartCardStatuses; }
            set
            {
                SetProperty(ref _smartCardStatuses, value);
                RaisePropertyChanged();
            }
        }
```

.axml View

```xml
<Mvx.MvxSpinner
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="15dp"
            local:MvxBind="ItemsSource SmartCardStatuses; HandleItemSelected CountrySelectedCommand" />
```

I am using a similar example which is in the documentation, but can't get it to work trigger the command.

```csharp
private MvxCommand<string> _countrySelectedCommand;
        public ICommand CountrySelectedCommand => _countrySelectedCommand =
            _countrySelectedCommand ?? new MvxCommand<string>(OnCountrySelectedCommand);

        private void OnCountrySelectedCommand(string country)
        {
            // write on country selected logic here
        }
```

Any tips please ? Am i doing something wrong here?

### Expected behavior

The command in the ViewModel should fire when the HandleItemSelected command is changed from the view.

### Configuration

**Version:** 
MvvmCross 6.4.1
MvvmCross.Driod.Support.Core.UI 6.4.1
MvvmCross.Driod.Support.Core.Utils 6.4.1
MvvmCross.Droid.Support.Design 6.4.1
MvvmCross.Droid.Support.V7.AppCompat 6.4.1
MvvmCross.Platform (5.7.0)
MvvmCross.Plugin.FieldBinding 6.4.1

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
First off you should MvvmCross.Platform from your project.

I assume you see items in the spinner, so that part works?

If you subscribe to the `ItemSelected` event on `MvxSpinner` does that one trigger?

**Comment by zerokewl88** [comment]
Thanks, i forgot to remove that MvvmCross.Platform references, its gone now. 

Yes, i can see the items ok in the spinner. 

Do you mean 'SelectedItem' ? I have tried that also as below without it ever firing.

```csharp
private string _smartCardStatusSelectedValue;
        public string SmartCardStatusSelectedValue
        {
            get { return _smartCardStatusSelectedValue; }
            set
            {
                SetProperty(ref _smartCardStatusSelectedValue, value);
                RaisePropertyChanged();

                EvidenceOfTestRowVisibility = value == "Evidence of Test";
                CardExpiryRowVisibility = value != "Evidence of Test";
            }
        }

        public MvxAsyncCommand<string> SmartCardStatusSelectedValueCommand = new MvxAsyncCommand<string>(async (x) =>
        {

        });
```

```xml
<MvvmCross.Platforms.Android.Binding.Views.MvxSpinner
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="15dp"
            android:id="@+id/smartCardStatusesSpinner"
            local:MvxBind="ItemsSource SmartCardStatuses; SelectedItem SmartCardStatusSelectedValue; HandleItemSelected SmartCardStatusSelectedValueCommand"/>
```


Also not sure if this is relevant / has something to do with it, but i'm thinking this shoud already be TargetBound, and this method in the Setup.cs file should actually connect these items. If not i guess here is where to implement the custom binding perhaps to try get it working another way ? 

This is my method inside the Setup.cs file for my 'MvxAppCompatSetup'

```csharp
protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            MvxAppCompatSetupHelper.FillTargetFactories(registry);
            base.FillTargetFactories(registry);

            registry.RegisterFactory(new MvxCustomBindingFactory<SwipeRefreshLayout>("IsRefreshing", (swipeRefreshLayout) => new SwipeRefreshLayoutIsRefreshingTargetBinding(swipeRefreshLayout)));
        }
```

**Comment by zerokewl88** [comment]
Ok, another attempt...

After just using the following without a TargetBinding, and the .axml for the MvxSpinner looks like so

```xml
<MvvmCross.Platforms.Android.Binding.Views.MvxSpinner
            android:layout_width="fill_parent"
            android:layout_height="30dp"
            android:layout_marginBottom="15dp"
            android:id="@+id/smartCardStatusesSpinner"
            local:MvxBind="ItemsSource SmartCardStatuses; HandleItemSelected ItemSelectedCommand"/>
```
After the Activity OnCreate almost ends, i did a check to see if the binding did occur and is still linked, which it is.

![image](https://user-images.githubusercontent.com/5489947/70687395-a6cea000-1ce1-11ea-9d5d-de37af674479.png)

Then as a test, when i remove the .axml MvxSpinner local:MvxBind 'HandleItemSelected' property, i can then see the binding / event handler is not there. (As you can see in the above picture, it has a method, and is not null.

So.. i think i must be linking these incorrectly, as it is never fired when i change a MvxSpinner item after selecting a value.

Looking at the .axml designer, i do see this message, but it actually builds, and displays the contents of my list anyways - just adding this here in case it gives a clue. 

![image](https://user-images.githubusercontent.com/5489947/70687668-658ac000-1ce2-11ea-915c-601d19125f77.png)

So apart from all the above, from what i can tell, i must be linking a wrong type of command, or something, because the HandleItemSelected never fires for my public ICommand ItemSelectedCommand.

Any thoughts / suggestions please ? Thank you.

**Comment by Cheesebaron** [comment]
So I'll try again, since you didn't seem to understand what I mean.

```csharp
var spinner = FindViewById<MvxSpinner>(Resource.Id.smartCardStatusesSpinner);
spinner.ItemSelected += (s, e) => { };
```

Does this event trigger?

**Comment by zerokewl88** [comment]
No, it does not.

```csharp
var spinner = FindViewById<MvxSpinner>(Resource.Id.smartCardStatusesSpinner);
            if (spinner != null)
            {
                spinner.ItemSelected += (s, e) => 
                { 
                    //Breakpoint here never reached.
                };
           }
```

**Comment by zerokewl88** [comment]
Not sure, but also wanted to mention, in case that it may be related, but displaying the current List<string> in this MvxSpinner, doesn't actually display it properly in the view for some reason. Only until i click it, does the menu appear, but until then, no currently selected value is visible - only the carrot drop down symbol. I've tried changing the colors, and foreground text from black / white, and nothing changes. 

![image](https://user-images.githubusercontent.com/5489947/70699953-87913c00-1cfc-11ea-90e6-18985671d3bd.png)


![image](https://user-images.githubusercontent.com/5489947/70699943-8102c480-1cfc-11ea-8e85-3d82548f52db.png)

**Comment by Cheesebaron** [comment]
I'll try to reproduce it on my end.

**Comment by zerokewl88** [comment]
Thank you, please let me know if you need anything - i'm working on this also, and around this for a project and can get back to you ASAP.

**Comment by zerokewl88** [comment]
Good morning, 

So i replicated this in the TipCalc using MvvmCross v6.2.2 for the Droid implementation.

In the TipView.axml i added
```xml
<MvvmCross.Platforms.Android.Binding.Views.MvxSpinner
    android:layout_width="match_parent"
    android:layout_height="50dp"
        local:MvxBind="ItemsSource Items, HandleItemSelected TestCommand"/>
```

Then in the TipViewModel.cs
```csharp
private List<string> _items;
        public List<string> Items
        {
            get { return _items; }
            set
            {
                SetProperty(ref _items, value);
                RaisePropertyChanged();
            }
        }

        public override void ViewAppeared()
        {
            base.ViewAppeared();

            Items = new List<string>();
            Items.Add("test 1");
            Items.Add("test 2");
            Items.Add("test 3");
        }

        public ICommand TestCommand = new MvxCommand<string>(x =>
        {

        });
```

Same behaviour occurs, i can see the items in the Spinner, although the initial items are not displayed until i choose to 'select a item'.

When i setup the HandleItemSelected localMvxBind, it is not triggered.

![image](https://user-images.githubusercontent.com/5489947/70760447-36c12800-1d7c-11ea-8e84-940b200a856b.png)

![image](https://user-images.githubusercontent.com/5489947/70760455-3d4f9f80-1d7c-11ea-9b9a-d2543bd42a9f.png)


Then attempting to see the HandleItemSelected event method bound, and the ItemSelected event trigger using the following, it never fires..

```csharp
[Activity(Label = "Tip Calculator", MainLauncher = true)]
    public class TipView : MvxActivity<TipViewModel>
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            SetContentView(Resource.Layout.TipView);

            var myspinner = FindViewById<MvxSpinner>(Resource.Id.mymvxspinner);
            if (myspinner != null)
            {
                myspinner.ItemSelected += Myspinner_ItemSelected;
            }
        }

        private void Myspinner_ItemSelected(object sender, Android.Widget.AdapterView.ItemSelectedEventArgs e)
        {
            //Never reached
        }
    }
```

![image](https://user-images.githubusercontent.com/5489947/70761289-4d1cb300-1d7f-11ea-937f-ea4012513dea.png)

I hope this information helps.

**Comment by zerokewl88** [comment]
Also in case it helps, using the basic Spinner, not MvxSpinner, i do get desired results. Am i missing any references ? 

![image](https://user-images.githubusercontent.com/5489947/70795983-b4645280-1dd3-11ea-80b0-3f25839947fe.png)

**Comment by zerokewl88** [comment]
Update: I took the APIExamples from the Sample Master, which downloads at 6.1.2, the Spinner works fine. Then updating the core, and the android project to both 6.4.1, the MvxSpinners work fine. I must be doing something else here that is preventing the linking to work properly.

**Comment by zerokewl88** [comment]
So this finally works after i copied over the sample MvxSpinner data model that it was using.

The following when copied across to my project, works for the ItemsSource and SelectedItems, 

```csharp
public class Thing
        {
            public Thing(string caption)
            {
                Caption = caption;
            }

            public string Caption { get; private set; }

            public override string ToString()
            {
                return Caption;
            }

            public override bool Equals(object obj)
            {
                var rhs = obj as Thing;
                if (rhs == null)
                    return false;
                return rhs.Caption == Caption;
            }

            public override int GetHashCode()
            {
                if (Caption == null)
                    return 0;
                return Caption.GetHashCode();
            }
        }

        private List<Thing> _items = new List<Thing>()
            {
                new Thing("One"),
                new Thing("Two"),
                new Thing("Three"),
                new Thing("Four"),
            };

        public List<Thing> Items
        {
            get { return _items; }
            set { _items = value; RaisePropertyChanged(() => Items); }
        }

        private Thing _selectedItem = new Thing("Three");

        public Thing SelectedItem
        {
            get { return _selectedItem; }
            set { _selectedItem = value; RaisePropertyChanged(() => SelectedItem); }
        }
```

However this does not.

```csharp
private List<string> _smartCardStatuses = new List<string>();
        public List<string> SmartCardStatuses
        {
            get { return _smartCardStatuses; }
            set
            {
                SetProperty(ref _smartCardStatuses, value);
                RaisePropertyChanged(() => SmartCardStatuses);
            }
        }

        private string _smartCardStatusSelectedValue = string.Empty;
        public string SmartCardStatusSelectedValue
        {
            get { return _smartCardStatusSelectedValue; }
            set
            {
                SetProperty(ref _smartCardStatusSelectedValue, value);
                RaisePropertyChanged(() => SmartCardStatusSelectedValue);
            }
        }
```

I populate the List<string> after ViewAppeared. After changing and testing using a List<string> collection, and initializing it on Model Creation in the constructor with dummy data, it then displays correctly, and everything then also works after. 

So, conclusion, have i done something wrong, loading data into the ItemSources at ViewAppeared the wrong time to do this?

 Simply changing this populated data to create during the ViewCreated override method, has resolved this issue. !!!!!!
