### ISSUE TITLE
Binding class object of a viewmodel

### ISSUE THREAD

**Issue by Shafaq19** [MvvmCross/MvvmCross#3661]
public class EstateGroupViewModel : MvxViewModel
    {

public Estate myestate
}
how can i use estate properties in android xml for binding? ;like
  <TextView
        app:MvxBind="Text myestate.Number"
        />

**Comment by Shafaq19** [comment]
Also:
If I have a include layout but i need to bind it to another viewmodel how can I do it?

**Comment by Cheesebaron** [comment]
Unclear what you are trying to do. Show your binding expressions.

Also we would prefer you to use StackOverflow for questions, rather than opening issues on GitHub.

**Comment by Shafaq19** [comment]
resolved it was trying to include a viewmodel as a member of another view model
