### ISSUE TITLE
Forms.SetFlags is being called before Forms.Init, but exception says the opposite

### ISSUE THREAD

**Issue by sqrg** [MvvmCross/MvvmCross#3663]
## 🐛 Bug Report

Exception showing that SetFlags must be called before Forms.Init()

### Expected behavior

No exception

### Reproduction steps

Add Forms.SetFlags("SwipeView_Experimental"); on the OnCreate override on RootActivity

### Configuration

**Version:**

* MvvmCross 6.4.1
* Xamarin.Forms 4.4.0.0991265

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by rgarcia-desarrolloweb** [comment]
Yes, I have the same problem :(

**Comment by Cheesebaron** [comment]
Init is not called on the RootActivity, but rather in the Setup.

You can override `FormsApplication` in your setup to change the behavior: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Forms/Platforms/Android/Core/MvxFormsAndroidSetup.cs#L56
