### ISSUE TITLE
Add .NET Core 3.1 support & publish supporting (Beta-) Nuget-Packages

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [MvvmCross/MvvmCross#3664]
## 🚀 Feature Requests

.NET Core 3.0 support for WPF has been added to the MvvmCross develop branch a few weeks ago. Currently there are no supporting Nuget packages as there has been no new MvvmCross version.

.NET Core 3.1 is out as a Long Time Support (LTS) release. As we're planning to migrate to .NET Core 3.1 over the holidays it would be more than helpful to have supporting MvvmCross (beta) Nuget packages.

Of course I'm aware of the coming holiday season & I'm feeling in no way entitled to receive any quick help from you on this issue. I've done a contribution to the project in the past & am more than willing to do whatever I can to support getting this issue resolved.
As a small sign of our appreciation we would also donate US-$100 to the project.

### Describe the feature
From my (maybe limited) understanding adding .NET Core 3.1 support should mainly consist in adding `netcoreapp3.1` to  `<TargetFrameworks>net461;netcoreapp3.0</TargetFrameworks>` in https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Wpf/MvvmCross.Platforms.Wpf.csproj.
Also the release of a new (beta) version including the publication of Nuget packages would be helpful.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
You can grab latest CI packages from here: https://github.com/MvvmCross/MvvmCross/packages

I've set up Azure DevOps to automatically push packages from the develop branch.

As for adding netcoreapp3.1 tfm, you are welcome to open a PR with the change. I'll make sure to process it quickly.

**Comment by HaraldMuehlhoffCC** [comment]
Thank you once again, @Cheesebaron, for your swift & helpful reaction! I had to put out a few other fires - and buy a Christmas tree ;) But now my PR is online.

I kept it very close to the changes that were made to add .NET Core 3.0 support (https://github.com/MvvmCross/MvvmCross/pull/3596).
Hopefully this will help in keeping the review process as straightforward as possible.

**Comment by Cheesebaron** [comment]
@HaraldMuehlhoffCC thank you for the PR. Will review it soon. Also thank you for the donation, much appreciated.
