### ISSUE TITLE
Can't use MVVMCross in a VB.net project without an issue

### ISSUE THREAD

**Issue by GerhardKreuzer** [MvvmCross/MvvmCross#3671]
Hi,
I want to use MVVMCross in a VB.net Project, but I get an error. I have to alter the app.xaml and after that I cant Access some properties of the Project.

Is there some way to let the root node of app.xaml unchanged? I found other mvvm Frameworks, where the app.xaml is changed but the root node is not. I attached a screen shot.

With best regards

Gerhard
![Problem 2019-12-23 174125](https://user-images.githubusercontent.com/4210407/71369623-9f45ab80-25ab-11ea-830f-c3f97fef559b.png)

**Comment by markuspalme** [comment]
It looks like your xaml file does not have the expected root element "application". Would you mind posting the contents of Application.xaml?

**Comment by GerhardKreuzer** [comment]
Hi Markus,

    thats correct!!

    Cause the MVVMCross sample I try to start with dictates a change of the
Application.xaml file. Without this modification, I fails.

    Maybe there is a better way to bring up a MVVMCross project in the
meanwhile.

    Thanks a lot for helping.

    With bes regards

    Gerhard

    Zitat von markuspalme <notifications@github.com>:
>
> It looks like your xaml file does not have the expected root element  
> "application". Would you mind posting the contents of  
> Application.xaml?
>
> —
>    You are receiving this because you authored the thread.
>    Reply to this email directly, view it on GitHub[1], or unsubscribe[2].
>




Links:
------
[1]  
https://github.com/MvvmCross/MvvmCross/issues/3671?email_source=notifications&email_token=ABAD5Z4X3VK27DLWYXM5T2DQ34CE5A5CNFSM4J6WAKY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIAXDVA#issuecomment-570520020
[2]

**Comment by GerhardKreuzer** [comment]
Hi Markus,

any News?

**Comment by markuspalme** [comment]
Please post the contents of your Application.xaml otherwhise it's hard to help.

**Comment by GerhardKreuzer** [comment]
.. I thought I have posted it already, here the (second) try …


[Application Start.zip](https://github.com/MvvmCross/MvvmCross/files/4054745/Application.Start.zip)


Ok, have to .zip the file, cause the site only accepts Images or zip files.

The Problem is, that for correct function of VS201x with an VB Project open, the first line of Application.xaml should be unchanged, so no reference to MVVMCross is allowed here.

Sorry.

With best regards

Gerhard

**Comment by markuspalme** [comment]
This looks like a bug in VisualStudio, not in MvvmCross. VS should allow any tag as long as inhertits from `Application` (or `MvxApplication` in this case).

Suggested workaround: change the tag to `Application` temporarily when you need to edit the project properties.

**Comment by markuspalme** [comment]
I propose to close this issue because it is related to VisualStudio rather than MvvmCross.

**Comment by Cheesebaron** [comment]
Marking this invalid and closing the issue. We can unfortunately not help you with fixing an IDE issue like the one you describe. If you feel this decision is wrong. Please comment here and we will consider reopening this issue.
