### ISSUE TITLE
Using sample file & following the procedure in readme.txt throws runtime exception

### ISSUE THREAD

**Issue by wsigel** [MvvmCross/MvvmCross#3677]
## 💬 Questions and Help

I've been following the suggested steps in the readme.txt of MvvmCross 6.4.1 trying to create a simple solution for Xamarin.iOS using the sample provided [in the content files](https://github.com/MvvmCross/MvvmCross/blob/develop/ContentFiles/). The only difference  is that I used a storyboard (instead of the xib) containing a button and a textfield. Even though the readme.txt says that the solution should run I get a runtime exception in Xamarin.iOS/UIKit/UIApplication.cs:

<img width="858" alt="Screenshot 2019-12-31 at 17 50 45" src="https://user-images.githubusercontent.com/10357745/71628932-f1fe1380-2bfa-11ea-824e-f158c4341cc6.png">

Is there anything missing in the readme.txt to get the sample running?

**Comment by Cheesebaron** [comment]
If you want to use Storyboards you need to use the `MvxFrinStoryboardAttribute` like so:

```csharp
[MvxFromStoryboard("Main")]
public partial class HomeView : MvxViewController<HomeViewModel>
{
    ...
}
```

**Comment by wsigel** [comment]
Besides using that attribute - is there anything else missing in the AppDelegate class here [https://github.com/MvvmCross/MvvmCross/blob/develop/ContentFiles/iOS/AppDelegate.cs.pp](url)? By following the instructions in the readme I just get a blank white screen - there is no button and no textfield even though they are defined in the designer file. Also which entries does one have to provide in the Info.plist for:

- Main interface
- Main storyboard file base name
- UISceneStoryboardFile (in UIApplicationSceneMainfest)?

I'm using macOS Catalina 10.15.2 with Xcode 11.3(11C29) and VS for Mac Community 8.3.11

**Comment by wsigel** [comment]
I was able to solve one problem I had with the TipCalc.iOS sample from the documentation. The sample (using xib) did not work until I deleted some entries in the Info.plist related to storyboard:

<img width="665" alt="Screenshot 2020-01-05 at 15 43 23" src="https://user-images.githubusercontent.com/10357745/71781802-0fecbf00-2fd3-11ea-9991-dbb4971d851e.png">

In addition the Main Interface entry had to be left empty. Maybe this information should be provided in the documentation - it took me several days to figure this out.

**Comment by wsigel** [comment]
I've checked it now using storyboards instead of xibs and found out that they work too if one erases the storyboard entries in the Info.plist (see screenshot above). Si nce I'm fairly new in developing for iOS on the Mac I wasn't sure whether I could just delete entries from the properties list without screwing up. So sorry for the inconvenience. Maybe this information is worthwhile to mention in the documentation.
