### ISSUE TITLE
Make an official release supporting .NET Core 3.0 / 3.1

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [MvvmCross/MvvmCross#3678]
## 🚀 Feature Requests

It's been some time since the release of the 6.4.1 nuget packages and with all the .NET Core 3.0 / 3.1 goodness inside the current develop branch wouldn't it be nice to greet the New Year with a 6.4.2? ;)

### Describe the feature
.NET Core 3.0 has been officially available for a few months now & the LTS release .NET Core 3.1 has been published recently. MvvmCross already has the required changes merged to the develop branch so hopefully the publication of a new version wouldn't be too much of an effort and might even work as a promotional tool (for .NET Core 3.x & MvvmCross).

Happy New Year!

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Thanks for opening an issue @HaraldMuehlhoffCC I've been wanting to release a new version this holiday, but instead I spent my time eating and relaxing 😄 

Will get a new version out for soon!

**Comment by Cheesebaron** [comment]
It is out today 6.4.2 😄

**Comment by HaraldMuehlhoffCC** [comment]
YOU MADE MY DAY! :)
