### ISSUE TITLE
Why is IoCProvider.IoCConstruct() instead of IoCProvider.Resolve() in MvxDefaultViewModelLocator?

### ISSUE THREAD

**Issue by eriove** [MvvmCross/MvvmCross#3685]
## 💬 Why is IoCProvider.IoCConstruct() instead of IoCProvider.Resolve() in MvxDefaultViewModelLocator?

Thanks for a great library!

I have a view model registered as a singleton and when I opened a new view with the [navigation service](https://github.com/MvvmCross/MvvmCross/blob/c730b21dd350f187f32e22b01a289d22df09dd43/MvvmCross/Navigation/MvxNavigationService.cs) I noticed that I got a new instance each time. Looking at the [MvxDefaultViewModelLocator.Load()](https://github.com/MvvmCross/MvvmCross/blob/d82def09aef0d492437871fce04560f3c7ea44c4/MvvmCross/ViewModels/MvxDefaultViewModelLocator.cs#L49) I can see that `IoCProvider.IoCConstruct()` is used instead of `IoCProvider.Resolve()`. It is easy enough to subclass the `MvxDefaultViewModelLocator` and override these methods, but I'm guessing that this was a deliberate choice.

_Hence, what's the reasoning behind always creating a new view model instead of respecting how it is registered?_

My use case is that I in the main view show a condensed version of my view model and then there is a more detailed view of the same data which I navigate to with the navigation service. I could just let the model be be a singleton instead and keep the view models as different instances, but I don't see any advantages of that (except that it happens to be the default). _Am I missing something else that might cause problems down the line if I let a view model be a singleton?_

**Comment by Cheesebaron** [comment]
ViewModels are not registered in the IoC container.

However, we do have a ViewModel cache for child ViewModels on Android, which we should probably ask for an instance of ViewModel prior to running IoCConstruct.

Letting your ViewModels be singletons could be fine for small Apps. However, as soon as you have a lot of ViewModels letting them live in memory is not ideal,

**Comment by eriove** [comment]
Thanks for the quick reply. My mental model have had the view models registered by convention (with a LINQ query or similar) at startup. Looking at them as not registered at all and found by the view model locator makes the current behavior expected :-)

We are only targeting WPF so memory is less of a problem than on other platforms (but it is always good to have in mind). I've been more worried of memory leaks via event handlers when creating new view models listening to changes in the models.

I will have to think some more regarding our architecture, your reply answered my question.
