### ISSUE TITLE
Crash when using MvxTableViewSource UseAnimations

### ISSUE THREAD

**Issue by FinHorsley** [MvvmCross/MvvmCross#3686]
### Overview
We're trying to use `UseAnimations` on a subclass of `MvxTableViewSource`, however when this is set to true we see the following error (this crashes the app)

> Xamarin.iOS: Received unhandled ObjectiveC exception: NSInternalInconsistencyException Invalid update: invalid number of sections. The number of sections contained in the table view after the update (1) must be equal to the number of sections contained in the table view before the update (0), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).

### Expected behavior
Using `UseAnimations` executes the following without crashing the app
https://github.com/MvvmCross/MvvmCross/blob/50935219127b2e068e8985680f58dd4b21d47490/MvvmCross/Platforms/Ios/Binding/Views/MvxTableViewSource.cs#L114-L153

### Reproduction steps
Set `UseAnimations` to true on a `MvxTableViewSource` subclass

```
source = new SettingsViewSource(this.TableView);
source.UseAnimations = true;
```
### Configuration

**Version:** 6.2.3

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

_Update below_ 👇

**Comment by FinHorsley** [comment]
### Update
This is what our tableViewSource subclass looks like. This drives a sectioned tableView
```
//Unrelated fields/methods removed for brevity

public override nint NumberOfSections(UITableView tableView)
       => this.ViewModel.Settings.Count;

public override nint RowsInSection(UITableView tableview, nint section)
       => this.ViewModel.Settings[(int)section].FormRows.Count;

protected override object GetItemAt(NSIndexPath indexPath)
      => this.ViewModel.Settings[indexPath.Section].FormRows[indexPath.Row];
```

**Problem**

The problem is that the MvxTableViewSource is trying to insert new rows into the tableView, where instead it should be inserting a new section. It looks like the crash is being caused by the following 
https://github.com/MvvmCross/MvvmCross/blob/50935219127b2e068e8985680f58dd4b21d47490/MvvmCross/Platforms/Ios/Binding/Views/MvxTableViewSource.cs#L118-L123

**Resolution**

Doing the following prevented the crash

```
case NotifyCollectionChangedAction.Add:
{
      // The args.NewStartingIndex represents the new section that has been added
      // so add this new section into the tableView
      // The rows in the section are then fetched from ` override nint RowsInSection(UITableView tableview, nint section)`

      var newSection = NSIndexSet.FromIndex(args.NewStartingIndex);
      TableView.InsertSections(newSection, AddAnimation);
      return true;
}
```

**_Why don't we see this when `UseAnimations = false`?_**

The default mode is `UseAnimations = false`. In this default implementation, when the collection changes, the entire tableview is reloaded. This means that new sections and rows are added automatically

https://github.com/MvvmCross/MvvmCross/blob/50935219127b2e068e8985680f58dd4b21d47490/MvvmCross/Platforms/Ios/Binding/Views/MvxBaseTableViewSource.cs#L51-L61

**Comment by Cheesebaron** [comment]
It is not a bug. You are asking for a feature here. The current MvxBaseTableViewSource just assumes you are only ever going to have one section. If you want different behavior you need to implement that yourself for now.

Please create a feature request instead.
