### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by huckjulius** [MvvmCross/MvvmCross#3690]
## 🏗 Enhancement Proposal

In the UWP installation guide: `MvvmCross.Core.ViewModels.MvxApplication` should be: `MvvmCross.ViewModels.MvxApplication`

**Comment by Cheesebaron** [comment]
Could you make a PR and fix it?

**Comment by markuspalme** [comment]
@Cheesebaron I think this can be closed now that the PR has been merged.
