### ISSUE TITLE
Binding : Binding Set Creation

### ISSUE THREAD

**Issue by Prin53** [MvvmCross/MvvmCross#3693]
## 🏗 Enhancement Proposal

Simplify `MvxFluentBindingDescriptionSet` creation.

### Pitch

The current binding set creation:

```cs
class SomeView : MvxViewController<SomeViewModel>
{
    public override void ViewDidLoad()
    {
        base.ViewDidLoad();

        var set = this.CreateBindingSet<SomeView, SomeViewModel>();
        set.Apply();
    }
}
```

Could be simplified for Views that inherited from base View classes with generic View Model argument:

```cs
class SomeView : MvxViewController<SomeViewModel>
{
    public override void ViewDidLoad()
    {
        base.ViewDidLoad();

        var set = CreateBindingSet();
        set.Apply();
    }
}
```

With an additional method in base View class, like:

```cs
class MvxViewController<TViewModel> : MvxViewController, IMvxIosView<TViewModel> where TViewModel : class, IMvxViewModel
{
    protected MvxFluentBindingDescriptionSet<MvxViewController<TViewModel>, TViewModel> CreateBindingSet()
    {
        return new MvxFluentBindingDescriptionSet<MvxViewController<TViewModel>, TViewModel>(this);
    }
}
```

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
You are welcome to open a PR adding this.

**Comment by FinHorsley** [comment]
Should the `CreateBindingSet()` extension use use `IMvxIosView` rather than MvxViewController?

```csharp
protected MvxFluentBindingDescriptionSet<IMvxIosView<TViewModel>, TViewModel> CreateBindingSet()
{
    return new MvxFluentBindingDescriptionSet<IMvxIosView<TViewModel>, TViewModel>(this);
}
```

`IMvxIosView` also inherits from `IMvxBindingContextOwner`, so i think the above should work in the same way

https://github.com/MvvmCross/MvvmCross/blob/bdaa09299714d94cf3f2c548a465d994c20d52f0/MvvmCross/Platforms/Ios/Views/IMvxIosView.cs#L11-L14

### Why? 
Not all the MvxControllers inherit off `MvxViewController`. For example [MvxBaseSplitViewController](https://github.com/MvvmCross/MvvmCross/blob/341c3cd909c0462f0afae6c18bb5fa76fd6e6874/MvvmCross/Platforms/Ios/Views/MvxBaseSplitViewController.cs)

**Comment by Prin53** [comment]
Another good reason to extend `IMvxView<TViewModel>`: this forces us to add this new method to each implementing view, so will not forget any of them.

**Comment by FinHorsley** [comment]
@Prin53 do you mean `IMvxView<TViewModel>` or `IMvxIosView<TViewModel>`

**Comment by Prin53** [comment]
@FinHorsley the first one, as there are people who using these fluent bindings on different platforms (at least on Android). If “bindings” is not a concern of this base interface we can extend base platform interfaces, like `IMvxIosView<T>`, `IMvxAndroidView<T>` and so on. What do you think?

**Comment by Cheesebaron** [comment]
Use `IMvxView<TViewModel>`. Fluent bindings are not only for iOS.

**Comment by Prin53** [comment]
We can extend `IMvxPlatformView<T>` only, as we need `IMvxBindingContextOwner` implementation.

**Comment by MarLoe** [comment]
Why was this not implemented in `IMvxView<TViewModel>`?
Just asking out of curiosity.

**Comment by Prin53** [comment]
@MarLoe see my comment above: we need `IMvxBindingContextOwner` to create a binding set.
