### ISSUE TITLE
Failed to create target binding with ArgumentNullException only when deploying for TextInputLayout (probably)

### ISSUE THREAD

**Issue by Lokanath-hue** [MvvmCross/MvvmCross#3694]
## 🐛 Bug Report

Binding to TextInputLayout and Text view inside is failing when i build my Android app in Deploy mode.
I am not exactly sure whats causing this after may be some optimizations done by Compiler omitting some code?
I did not notice the problem with any other control till now.
### Expected behavior
Expected that the binding to work both in Deploy and Debug mode.
### Reproduction steps
Add Flags to *.Droid.csproj and try to bind a TextInputLayout with embedded view model
AndroidUseSharedRuntime= false
EmbedAssembliesIntoApk=true
### Configuration

**Version:** 6.2.3

**Platform:** 
Android
[XXX20200119.log](https://github.com/MvvmCross/MvvmCross/files/4082570/XXX20200119.log)

**Comment by Cheesebaron** [comment]
This is a linker issue. Please refer to https://www.mvvmcross.com/documentation/fundamentals/linking

**Comment by Lokanath-hue** [comment]
Hi ,

Thanks for the input.
I thought LinkerParserInclude was obsolete. After adding TextInputLayout there are no issues.

Thank you
Best Regards
