### ISSUE TITLE
Theme is broken on Android API level 29 for DatePickerDialog and for TimePickerDialog since MvvmCross 6.4.x

### ISSUE THREAD

**Issue by stefan89** [MvvmCross/MvvmCross#3698]
## 🐛 Bug Report
Since we've updated MvvmCross in our app from MvvmCross 6.3.1 to 6.4.1 we're facing issues with the theme we applied for a DatePickerDialog and the TimePickerDialog. The strange thing is that the issue only occurs on API level 29. For lower API levels it still works properly.

See screenshots to see the difference.

**TimePickerDialog on Android API level 29** 
- Button text color is incorrect and therefore you can't see them.
- Title (the selected time) has an incorrect text size
![Screenshot_1579698691](https://user-images.githubusercontent.com/1457137/72897098-653e0580-3d21-11ea-92f9-bc0e902c3dbf.png)

**DatePickerDialog on Android API level 29.**
- Button text is incorrect and therefore you can't see them.

![Screenshot_1579698698](https://user-images.githubusercontent.com/1457137/72897114-70913100-3d21-11ea-8dc0-41a9e557b2d0.png)

### Expected behavior
Below screenshots how it should look like (screenshots made on Android API level 28)

**TimePickerDialog on Android API level 28** 
![Screenshot_1579699096](https://user-images.githubusercontent.com/1457137/72897358-0dec6500-3d22-11ea-8855-cbecbcfa3994.png)

**DatePickerDialog on Android API level 28.**
![Screenshot_1579699090](https://user-images.githubusercontent.com/1457137/72897364-1349af80-3d22-11ea-9698-155106c4d593.png)

### Reproduction steps
Apply a custom theme on a DatePickerDialog or TimePickerDialog and see what happens

### Configuration

**Version:** 6.4.1 but also encountered for 6.4.2

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by radioactiveman** [comment]
I also noticed wrong text colors within Toast messages on Android 10 since the update of MvvmCross from 6.3.1 to 6.4.x.

Library used: https://github.com/aritchie/userdialogs

**Comment by Cheesebaron** [comment]
@radioactiveman userdialogs doesn't have anything to do with MvvmCross, does it?

As for the two dialog types, it might be enough to add missing ctor overloads to MvxDatePicker and MvxTimePicker. I've made a PR trying to fix this...

**Comment by radioactiveman** [comment]
@Cheesebaron: I don't know why but obviously it does since simply downgrading to 6.3.1 fixes this issue. Please see #3701 for more details and a sample project.

**Comment by cjrvdev** [comment]
There are many other theme related problems out there. Some of my textfields which had custom themes (not activity theme, this one works) stopped working after migrating from mvvmcross 5.7 to 6.4.2.

There really must be something going on. Replicated this scenario in Android studio and worked perfectly so it must be something with the latest framework version

**Comment by Cheesebaron** [comment]
I've just tried this live on stream within the Playground.Droid project. The entire world witnessed, that it doesn't seem to be an issue anymore. At least not in HEAD of the develop branch. If I could get some repro steps, that would probably ease the debugging procedure a lot. But, when I tried, the buttons were there and they used the primaryColor defined in resources/values/colors.xml
