### ISSUE TITLE
Didn't Find Class "android.widget.view" error when simple dialog used in MvxActivity

### ISSUE THREAD

**Issue by SSELLIOTTHOME** [MvvmCross/MvvmCross#3700]
## 💬 Questions and Help

I have found since upgrading from VS 2017 to VS 2019 in Android, using a dialog directly within in an MvxActivity, for example the Progress Dialog (I know it is deprecated but it also affected action dialogs as well) with **all** **exception are switched on to be caught**, you get the following 'handled' error. 

![error](https://user-images.githubusercontent.com/45513359/72989339-f5458300-3de5-11ea-98c6-78bac3a6cb9c.png)

It does continue to display the dialog. It does not occur on all devices, emulators seam fine, only a handful of devices including a Samsung SM-T285 with Android 5.1.1 and a Sony Phone running Android 9.

This does not happen with a simple Activity, in the same project. 

I am using MvvmCross 6.4.2.

I provide a git hub repo as an example

https://github.com/SSELLIOTTHOME/Dex_Error

I will happily ignore this if it is not a  problem, is it just a VS thing? or am I doing something wrong?

**Comment by Cheesebaron** [comment]
ProgressDialog is obsolete. Use something else.

I don't have access to those devices, so unless you send them to me, I won't be able to help much here.

**Comment by SSELLIOTTHOME** [comment]
If it is any help, I also found it happening when running the tip calc example from the MVVMCross samples samples, without even using a dialog with those two devices.

**Comment by Cheesebaron** [comment]
Do you have break on all exceptions enabled? Does it crash if you just continue?

**Comment by SSELLIOTTHOME** [comment]
Hi Tomasz

Thank you for your reply. Yes I did have all exceptions on, and it does continue ignoring the exception, it other wise still works.

Steven

________________________________

**Comment by DavidMarquezF** [comment]
The same error happened to me when using `View` in my xml layouts (I used it to create separators)

**Comment by SSELLIOTTHOME** [comment]
@DavidMarquezF I am starting to just think this is an internal thing in VS 2019 to ignore.

**Comment by DavidMarquezF** [comment]
It could be, but the strange thing is that it only happens when inflating with MvvmCross (BindingInflate). The native inflate doesn't throw this error for me.

In the end, I just changed View for TextView because it bothered a lot having it break every time.

**Comment by SSELLIOTTHOME** [comment]
Quick question David, did it happen on a devices or just a specific one?

Steven

________________________________

**Comment by DavidMarquezF** [comment]
For me, it happened on all the devices I tried. Maybe it's just coincidence

**Comment by SSELLIOTTHOME** [comment]
I found this happens even with the basic Tip Calc example on the emulator now, (Pixel 2 Android 9.0) with all exceptions switched on. If I can safely ignore them I will as the application does continue on.

Messages include

**Java.Lang.ClassNotFoundException:** 'Didn't find class "android.widget.View" on path: DexPathList[[zip file "/data/app/TipCalc.Droid.TipCalc.Droid-Y8YtV1rfQMf4qhP2JjpnvQ==/base.apk"],nativeLibraryDirectories=[/data/app/TipCalc.Droid.TipCalc.Droid-Y8YtV1rfQMf4qhP2JjpnvQ==/lib/x86, /data/app/TipCalc.Droid.TipCalc.Droid-Y8YtV1rfQMf4qhP2JjpnvQ==/base.apk!/lib/x86, /system/lib]]'

**Java.Lang.ClassNotFoundException:** 'Didn't find class "android.webkit.View" on path: DexPathList[[zip file "/data/app/TipCalc.Droid.TipCalc.Droid-Y8YtV1rfQMf4qhP2JjpnvQ==/base.apk"],nativeLibraryDirectories=[/data/app/TipCalc.Droid.TipCalc.Droid-Y8YtV1rfQMf4qhP2JjpnvQ==/lib/x86, /data/app/TipCalc.Droid.TipCalc.Droid-Y8YtV1rfQMf4qhP2JjpnvQ==/base.apk!/lib/x86, /system/lib]]'


________________________________

**Comment by sridharsaminathant** [comment]
> The same error happened to me when using `View` in my xml layouts (I used it to create separators)

Any fix for this ?

**Comment by Cheesebaron** [comment]
There is no issue to begin with?

**Comment by sridharsaminathant** [comment]
> There is no issue to begin with?

When we use `com.google.android.material.appbar.AppBarLayout` , `androidx.appcompat.widget.Toolbar` i am still getting this issue

**Comment by Cheesebaron** [comment]
But it doesn't throw all the way up into your code, it is an internal exception. Or is your App crashing?

**Comment by DavidMarquezF** [comment]
The app doesn't crash but it is really annoying because vs stops so you have to press F5 to continue which kind of slows everything down

**Comment by sridharsaminathant** [comment]
> The app doesn't crash but it is really annoying because vs stops so you have to press F5 to continue which kind of slows everything down

yes in my case I need to do some bindings with that. Is there any way to fix that?

**Comment by Cheesebaron** [comment]
Do you have "Enable Just My Code" set in VS debugger options?

**Comment by sridharsaminathant** [comment]
It is already disabled. btw I need to get worked on release mode
