### ISSUE TITLE
Unreadable toast messages on Android API Level 29 and MvvmCross 6.4.x

### ISSUE THREAD

**Issue by radioactiveman** [MvvmCross/MvvmCross#3701]
### Old (and correct) behavior
The text color for toast messages is readable with white color on dark background.
This was the case with MvvmCross versions until 6.3.1.

### Current behavior
The text color for toast messages is unreadable due to black text color on dark background.

### Reproduction steps
A sample application is attached. It uses the library [ACR User Dialogs](https://github.com/aritchie/userdialogs).
Tested on a Google Pixel with Android 10.

### Configuration
**Version:** 6.4.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by radioactiveman** [comment]
![Screenshot_20200123-162447](https://user-images.githubusercontent.com/1301412/72998517-42cdea00-3dfe-11ea-97f4-0cdcc320e4bb.png)

**Comment by radioactiveman** [comment]
[ToastMessageSample.zip](https://github.com/MvvmCross/MvvmCross/files/4103832/ToastMessageSample.zip)

**Comment by Cheesebaron** [comment]
This is not a MvvmCross issue. Downgrading MvvmCross might "fix" the issue, but that is only because the target is lower in older packages. Latest MvvmCross targets Android 10 (API29).

Fix your theme.

**Comment by radioactiveman** [comment]
Increasing the target SDK/framework version to API Level 29 / Android 10.0 fixes this issue. Sorry for the noise.
