### ISSUE TITLE
If I use mvxrecyclerview with a large size observable collection there is huge lag in first time render

### ISSUE THREAD

**Issue by Shafaq19** [MvvmCross/MvvmCross#3710]
## 🐛 Bug Report
If I use mvxrecyclerview with a large size observable collection there is huge lag in first time render

### Reproduction steps
My observablecollection has 700 items when I use my mvxrecyclerview the first time it takes too long to render it. recyclerview shouldn't render all item at once no? but only visible ones?
This only happens the first time...
### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :robot: Android

**Comment by Cheesebaron** [comment]
And if you do exactly the same with RecyclerView and your own Adapter, does it behave the same?

RecyclerView only renders the items on the screen. However, there are many factors that come into place. Such as how expensive the layout you are inflating per row is etc.

**Comment by Shafaq19** [comment]
I am not using adapters at all... I use item source binding.... The thing was it wasnt rendering only the visible items but all 700 of them!. so yesterday I tried fixed height recycler view (i guess to enforce the virtualization we get from adapters and only render visible items ) Its  a tacky hack but fixed the problem...
BTW Can we use adapters and still do binding? I think its not possible since I cant use it in mvxviewmodels?

**Comment by Cheesebaron** [comment]
@Shafaq19 it is to rule out whether it is a MvvmCross issue or not.
