### ISSUE TITLE
MvxCollectionViewCell overrides PreferredLayoutAttributesFittingAttributes

### ISSUE THREAD

**Issue by tboogh** [MvvmCross/MvvmCross#3714]
## 🐛 Bug Report

In MvxCollectionViewCell the method PreferredLayoutAttributesFittingAttributes is overriden and does not implement the base method. This causes autosizing with autolayout to break, I think that there  at least should be a way to opt out of this behaviour. Preferably it should be left out as it touches on something outside MVVM and binding.

### Expected behavior
The cell returns the default implementation

### Configuration

**Version:** 6.x

**Platform:** 
- [X ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
@tboogh can you make a PR?

**Comment by tboogh** [comment]
Sure thing
