### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: 'Could not find view for

### ISSUE THREAD

**Issue by cidsv** [MvvmCross/MvvmCross#3734]
## 🐛 Bug Report
I got error System.Collections.Generic.KeyNotFoundException: 'Could not find view for after update to version 6.4.2. I use custom IOC provider  ( protected override IMvxIoCProvider CreateIocProvider()). If i dont use custom IOC provider its works fine.

### Reproduction steps
deploy to android
crash
### Configuration

**Version:** 6.4.2

**Platform:** 
[ApiExamples.zip](https://github.com/MvvmCross/MvvmCross/files/4323435/ApiExamples.zip)
- [ ] :robot: Android

**Comment by jiberan** [comment]
@martijn00 why this was closed without any explanation?

**Comment by Cheesebaron** [comment]
I would probably have closed it too. It is vaguely described. Although providing a sample, just not enough information to chase this.

@jiberan if you feel like this is still an issue, please open a new one with more information linking to this one.

**Comment by cidsv** [comment]
@Cheesebaron @martijn00 I dont understand.Why more information? Exception is described in the bug report and when you build ApiExample and deploy it to the device, the application crash.
