### ISSUE TITLE
Screen won't navigate back

### ISSUE THREAD

**Issue by cliffconclusion** [MvvmCross/MvvmCross#3735]
## 💬 Questions and Help

I want to navigate back from a screen in MVVMCross. But when I try to do so by using navigationService.Close(this), I see the following log in the logging.

Ignoring close for ViewModel - Matching View for ViewModel instance failed.

I googled and searched everywhere, but I can't find a solution. Can anyone help me to do such a simple thing as navigating back?

**Comment by acuntex** [comment]
@cliffconclusion 
It's been a while since you posted this.
I'm facing the same issue and I'm shocked that neither the docs tell you anything about "Back" (basically as if you trigger the back button) nor did anyone comment on this "simple issue" since March.

Have you figured out a solution?

**Comment by cliffconclusion** [comment]
Nope, we weren't able to get it to work. It's really shameful when you have to tell your customer you can't navigate back 😓

**Comment by Cheesebaron** [comment]
I need a bit more information to help you here.

1. Which platform?
2. You are navigating from what to what? And trying to close it when?
3. Which version?
4. Do you have a repro sample?

**Comment by acuntex** [comment]
@cliffconclusion Made the hard decision to switch to FreshMvvm. FreshMvvm seems to be the right decision for Xamarin.Forms.
Works like charm, less complex (KISS) and faster startup times.
And the best: No ViewPresenters, easy navigation structures.

**Comment by cliffconclusion** [comment]
@acuntex Thanks for the tip!
