### ISSUE TITLE
Async MvxValueConverter

### ISSUE THREAD

**Issue by StepanMynarik** [MvvmCross/MvvmCross#3743]
## 💬 Questions and Help

Hi,

Is it possible to create an async MvxValueConverter?

I have a 'MvxValueConverter<string, NSAttributedString>' converter in our iOS project and need to await NSAttributedString::FromHtmlAsync method that can possibly take up to... tens of seconds, don't know exactly.

Or if I could just create an async binding that uses the converter?

Regards,
Stepan

**Comment by Cheesebaron** [comment]
We don't really have async bindings in MvvmCross. However, you could probably make a custom Target Binding, which creates this NSAttributed string and calls SetImpl in a `ContinueWith` block.
