### ISSUE TITLE
SystemNullException in MvxAppCompatViewPresenter.CloseFragment

### ISSUE THREAD

**Issue by DavidMarquezF** [MvvmCross/MvvmCross#3746]
## 🐛 Bug Report

I'm not really sure if this would be considered a bug or a question, but my app is getting System.NullReferenceException in the close fragment function (at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.CloseFragment). 

I know this is probably caused by the app being in the background (CurrentActivity is null), but at the moment I have been unable to reproduce it.

I know it's not the same, but if navigate is called when the app is in the background, it opens the activity. I don't know if a similar behavior would make sense in CloseFragment (because when you close a fragment you could consider you are navigating to the previous?)

### Expected behavior
A way to call Close that is safe or at least get a more descriptive error (because now it's only a supposition that the activity is null).

### Configuration

**Version:** 6.4.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by DavidMarquezF** [comment]
Is it possible that this has already been fixed in version 6.4.2 with #3665 ?

**Comment by corradopablom** [comment]
Hi! I have the same problem in the same version: 6.4.1.
