### ISSUE TITLE
Binding In XML Is Not Working

### ISSUE THREAD

**Issue by AnthonyUccello** [MvvmCross/MvvmCross#3753]
## 🐛 Bug Report

Binding in XML is not working. The view model property getter is not being called. We have created a sample project which shows binding via XML, binding via code, binding via fluent, and plain old fashioned hard coded value.

https://github.com/AnthonyUccello/MVVMBug

Also please note that XML binding is working in the DashboardViewFragment but not in the SecondViewFragment.

### Expected behaviour
Getter is called from an XML binding and value is displayed

### Reproduction steps
Open the sample project and run. Click the red button and it navigates to a fagment. You will see the 3 text fields from the fluent binding, standard code binding, and hardcode text value working and the 1 textfield which use the XML binding that does not work. The top most red background is for the textview which does not have a value.

Look at the SecondViewLayout.axml file and you will see a textview at the top:

        <TextView
            android:id="@+id/MyId1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="25dp"
            android:gravity="center"
            local:MvxBind="Text TitleLabel"
            android:layout_gravity="center_horizontal"
            android:textAllCaps="true"
            android:background="@android:color/holo_red_dark"/>

This is the binding that is not working properly. 

 Note that this text value is bound to "TitleLabel" and it doesn't work. But when we create another textview and code it to be bound in the SecondViewFragment.cs file it does work:

            var textView = _view.FindViewById<TextView>(Resource.Id.MyId4);
            set.Bind(textView).For(v => v.Text).To(vm => vm.TitleLabel);

Note: To verify the getter on TitleLabel is not being called, just comment out the above code and you will see when the XML is binding to this value the getter is not called.

### Configuration

**Version:** 6.4.2

**Platform:** 
- [ X] :robot: Android

**Comment by Cheesebaron** [comment]
You have a space in your namespace declaration: `xmlns:local="http://schemas.android.com/apk/res-auto "`

**Comment by AnthonyUccello** [comment]
@Cheesebaron Thank you!
