### ISSUE TITLE
Listview With @Drawable Sets Everything To Selected And Does Not Keep Selection

### ISSUE THREAD

**Issue by AnthonyUccello** [MvvmCross/MvvmCross#3757]
## 🐛 Bug Report

All items are highlighted in a listview when an item is clicked and then selected item does not stay selected when click is finished. There is an XML binding to a drawable which sets the background based on selection state. For some reason the "selected" state is being set for all items in the listview when only 1 is clicked and then the selected is not maintained when click is finished.

[In this sample project](https://github.com/AnthonyUccello/MVVMBug) there is only 1 view which does only XML bindings called `DashboardLayout.axml`. Inside there is only a 2 item listview:
```
        <mvvmcross.platforms.android.binding.views.MvxListView
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:drawSelectorOnTop="false"
            android:id="@+id/listView1"
            android:scrollbarStyle="outsideOverlay"
            android:choiceMode="singleChoice"
            android:cacheColorHint="@android:color/transparent"
            android:background="@android:color/transparent"
            android:divider="@android:color/transparent"
            android:dividerHeight="15dp"
            android:listSelector="@android:color/transparent"
            local:MvxBind="ItemsSource Modes; SelectedItem SelectedMode; ItemClick SelectCommand"
            local:MvxItemTemplate="@layout/itemtemplate"
            android:paddingTop="20dp" />
```
The bindings are set:            
`local:MvxBind="ItemsSource Modes; SelectedItem SelectedMode; ItemClick SelectCommand"
`

For the selection colouring behaviour there drawable code in the ListItemBackground.xml where the default and unpressed state uses the normal color, and everything else uses the pressed state.

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:state_checked="true"
        android:drawable="@drawable/ListItemBackgroundPressed" />
  <item android:state_selected="true"
        android:drawable="@drawable/ListItemBackgroundPressed" />
    <item android:state_pressed="true" 
        android:drawable="@drawable/ListItemBackgroundPressed" />
    <item android:state_focused="false" 
        android:drawable="@drawable/ListItemBackgroundNormal" />
    <item android:drawable="@drawable/ListItemBackgroundNormal" />
</selector>
```

So if the state of a listview item is selected the colour is set to "@drawable/ListItemBackgroundPressed" aka red:
```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
android:shape="rectangle" >
   <solid android:color="@color/highlight_color" />
</shape>
```

The setter is being called for the selected item in the `DashboardViewModel`:

```
        public string SelectedMode
        {
            get { return _selectedmode; }
            set
            {
                _selectedmode = value;
                RaisePropertyChanged(() => SelectedMode);
            }
        }
```

But the item does not stay selected, yet both items show as selected when pressing an item.

### Expected behaviour
Only the clicked item is highlighted while being clicked, and it remains selected.

### Reproduction steps
Open the sample project, run, then click on any item. When you click an item you will see both get highlighted (turn red) at the same time and the selected item does not remain selected.

### Configuration

**Version:** 6.4.2

**Platform:** 
- [ X] :robot: Android

**Comment by JagatPanchal** [comment]
Is there any update on this issue?

**Comment by Cheesebaron** [comment]
We don't really do anything in the code behind that should prevent you from doing stuff like this.

Both cells are probably selected because you are using: `duplicateParentState` and setting it to true.

To keep the cell selected I think using `choiceMode`, `singleChoice` along with `listSelector` should be enough. Hard to say exactly what is wrong with all the stuff you have in your XML code. I would probably start here...

**Comment by JagatPanchal** [comment]
Thanks for the suggestion. I will try to apply this and put an update here. 

Thank you,
Jagat

**Comment by JagatPanchal** [comment]
I was able to fix the issue after removing duplicateParentState property and also updated the list selector in item template.
