### ISSUE TITLE
iOS Master page is displayed over the Tabbed Page 

### ISSUE THREAD

**Issue by DaniRvd** [MvvmCross/MvvmCross#3766]
## 🐛 Bug Report

Master page is displayed over the Tabbed Page when navigating back from MasterDetailPage to tabbed page if master page was opened before the navigation page.

### Expected behavior
When back button is pressed the master page should be closed before go back to tabbed page
### Reproduction steps
1) Open MvxFormsMasterDetail demo on iPad with iOS 13 (current page is a TabbedPage)
2) Click on "Go to master detail" (Current page is MasterDetailPage)
3) After master detail page is loaded and the master page is opened, click back.
4) You will see that the master page is displayed approximatively one second over the TabbedPage

If you make the same steps above but you manually close the master page before press Back, you will see that the back navigation is made more smoothly.

### Configuration
iPad 12,9 inch with iOS 13 or iPhoneSimulator with iPadPro 12,9 inch 3rd generation iOS 13.3 as simulated device
[MvxFormsMasterDetailDemo 2.zip](https://github.com/MvvmCross/MvvmCross/files/4550688/MvxFormsMasterDetailDemo.2.zip)

Navigating back with master opened
![Screen Shot 2020-04-29 at 12 11 51 PM](https://user-images.githubusercontent.com/20532118/80579421-ac1f5380-8a12-11ea-828e-29f8ad05dcdb.png)

**Version:** 6.4.2

**Platform:** 
- [ x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ x] :monkey: Xamarin.Forms

**Comment by DaniRvd** [comment]
I can imagine that does not have a quick fix but can anyone help me with a workaround for this problem?

**Comment by Cheesebaron** [comment]
I don't think MvvmCross supports that kind of scenario right now.
