### ISSUE TITLE
Conflict calls to SaveAsync() in MvxSuspensionManager

### ISSUE THREAD

**Issue by yanxiaodi** [MvvmCross/MvvmCross#3772]
## 🐛 Bug Report

I can reproduce it intermittently in **Playground.Uwp** project. When closing the app, there are two methods that call `SaveAsync()` method of `MvxSuspensionManager` in `OnEnteredBackground` and `OnSuspending` of `MvxApplication`. However, `SaveAsync()` has a action to read/write local files so sometimes it throws the exception:
> System.IO.FileLoadException: 'The process cannot access the file because it is being used by another process. The file is in use. Please close the file before continuing.'

### Expected behavior

The app should not throw exceptions when it is closed.

### Reproduction steps

Debug the **Playground.Uwp** project. After the app starts, close it. Sometimes it throws the exception as shown below:

![image](https://user-images.githubusercontent.com/3395915/81780488-b5e4a300-954a-11ea-8df1-6cde640db1ee.png)

I think it is because another process has not completed the operation to the same `_mvxSessionState.xml` file.

When set up a break point at this line:
```csharp
var file = await ApplicationData.Current.LocalFolder.CreateFileAsync(SessionStateFilename, CreationCollisionOption.ReplaceExisting);
```
it happens more frequently.

### Configuration

**Version:** 6.4.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by CaseAlexander** [comment]
I'm getting this exact exception as well upon closing a UWP app (every time).  I'm not doing anything special with SaveAsync() upon app exit.  It just started happening the other day, after I began using Xamarin.Essentials SecureStorage (if that helps)

**Comment by yanxiaodi** [comment]
@CaseAlexander thanks for your comment. I also use Xamarin.Essentials.SecureStorage. I'll do more tests to validate if it is related to this API.

**Comment by yanxiaodi** [comment]
@CaseAlexander  hi, may I know if you have your own overrided `OnSuspending` method in App.xaml.cs? eg:
```
this.Suspending += OnSuspending;
```
I am wondering if it is related to this method. Thanks.

**Comment by CaseAlexander** [comment]
Hi, nope, not overriding suspending at all. I can test removing my use of xam secure storage too and see if that resolves the issue

**Comment by CaseAlexander** [comment]
@yanxiaodi  Hi, Not overriding Suspending in any way (that I can tell). Unfortunately, I don't think it is related to SecureStorage.  I was able to remove all references to it and the issue still persists.  This just started for me a few days ago, so I'll review my commits to see if I can spot anything suspicious.
