### ISSUE TITLE
Custom MvxFormsDroidPresenter：Method not found

### ISSUE THREAD

**Issue by haohighview** [MvvmCross/MvvmCross#3773]
### Expected behavior
MvxAttributeViewPresenter.GetPresentationAttributeAction (MvvmCross.ViewModels.MvxViewModelRequest request, MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute& attribute)
System.MissingMethodException: Method not found: Android.App.Activity MvvmCross.Platforms.Android.Presenters.MvxAndroidViewPresenter.get_CurrentActivity()

```csharp
 public override Task<bool> Show(MvxViewModelRequest request)
        {
            var viewFromXf = request.ViewModelType.GetCustomAttributes(typeof(MvxViewWithXamarinFormsAttribute), false);
            //detect if we want a Forms View 
            if (viewFromXf.Any())
            {
                //get the Forms page from the request 
                var contentPage = MvxPresenterHelpers.CreatePage(request);

                //set DataContext of page to LoadViewModel
                var viewModel = MvxPresenterHelpers.LoadViewModel(request);

                //set the binding context of the content page
                contentPage.BindingContext = viewModel;

                if (!(mvxFormsApp.MainPage is NavigationPage mainPage))
                {
                    // XF application exists but no Root.
                    InitialiseXfActivityStack(contentPage);
                }
                else
                {
                    try
                    {
                        if (CurrentActivity is MvxFormsCustomApplicationActivity == false)
                        {
                            // XF application exists and there is a Root however the TopMostActivity
                            // (this.Activity) is not MvxFormsApplicationActivity. We must be back in Native world
                            // Restart XF stack
                            InitialiseXfActivityStack(contentPage);
                        }
                        else
                        {
                            mainPage.PushAsync(contentPage);
                        }
                    }
                    catch
                    {
                    }
                }
                return Task.FromResult(true);
            }
            else
            {
                return base.Show(request);
            }
        }
```
### Configuration

**Version:** 
6.5.0-alpha.177

**Platform:** 
- [x] :robot: Android

**Comment by haohighview** [comment]
Any updates?

**Comment by haohighview** [comment]
`public class MvxFormsHybridDroidPresenter : MvxAppCompatViewPresenter
    {
        public MvxFormsHybridDroidPresenter(IEnumerable<Assembly> androidViewAssemblies) : base(androidViewAssemblies)
        {
        }

        private MvxFormsApplication mvxFormsApp;

        public MvxFormsApplication MvxFormsApp
        {
            get
            {
                if (this.mvxFormsApp == null)
                    this.mvxFormsApp = new App();
                return this.mvxFormsApp;
            }

            set
            {
                if (value == null)
                {
                    throw new ArgumentException("MvxFormsApp cannot be null");
                }

                this.mvxFormsApp = value;
            }
        }
 public override Task<bool> Show(MvxViewModelRequest request){}
public override Task<bool> Close(IMvxViewModel viewModel){}
}`

**Comment by Cheesebaron** [comment]
Are you building in Release mode or Debug mode. To me it could look like a linker issue. But unsure, because you are being so vague with your description of the issue.

**Comment by haohighview** [comment]
> Are you building in Release mode or Debug mode. To me it could look like a linker issue. But unsure, because you are being so vague with your description of the issue.

Debug mode

**Comment by haohighview** [comment]
` public class Setup : MvxAndroidSetup<MvxApp>{
protected override IEnumerable<Assembly> AndroidViewAssemblies => new List<Assembly>(base.AndroidViewAssemblies)
        {
            typeof(MvxRecyclerView).Assembly
        };

protected override IMvxAndroidViewPresenter CreateViewPresenter()
        {
            var mvxFormsApp = new App();
            var presenter = new MvxFormsHybridDroidPresenter(this.AndroidViewAssemblies)
            {
                MvxFormsApp = mvxFormsApp
            };
            Mvx.IoCProvider.RegisterSingleton<IMvxViewPresenter>(presenter);

            return presenter;
        }


}`

**Comment by Cheesebaron** [comment]
First of all. With AndroidX we've removed `MvxAppCompatViewPresenter`, inherit from `MvxAndroidViewPresenter` instead. It seems like you are mixing versions of MvvmCross packages. This is why you are having issues.

**Comment by haohighview** [comment]
> First of all. With AndroidX we've removed `MvxAppCompatViewPresenter`, inherit from `MvxAndroidViewPresenter` instead. It seems like you are mixing versions of MvvmCross packages. This is why you are having issues.

thanks. now I'm using MvxAndroidViewPresenter, this problem has been solved.
But I have new problems,when I want to show a android native page. Error on line 89 
and now I'm Using this scenario
https://michaelridland.com/xamarin/mixing-xamarin-forms-mvvmcross-nativeviews/
![image](https://user-images.githubusercontent.com/8456671/84729887-5ead7480-afc7-11ea-80a3-3ab09c883537.png)

>Can not find view for ViewModel
06-16 11:51:34.852 E/mono-rt (21094): [ERROR] FATAL UNHANDLED EXCEPTION: System.Collections.Generic.KeyNotFoundException: Could not find view for MvxStandardTemplate.ViewModels.MainViewModel
06-16 11:51:34.852 E/mono-rt (21094):   at MvvmCross.Views.MvxViewsContainer.GetViewType (System.Type viewModelType) [0x00076] in /_/MvvmCross/Views/MvxViewsContainer.cs:69 
06-16 11:51:34.852 E/mono-rt (21094):   at MvvmCross.Platforms.Android.Presenters.MvxAndroidViewPresenter.GetPresentationAttribute (MvvmCross.ViewModels.MvxViewModelRequest request) [0x00000] in /_/MvvmCross/Platforms/Android/Presenters/MvxAndroidViewPresenter.cs:118 
06-16 11:51:34.852 E/mono-rt (21094):   at MvvmCross.Presenters.MvxAttributeViewPresenter.GetPresentationAttributeAction (MvvmCross.ViewModels.MvxViewModelRequest request, MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute& attribute) [0x00000] in /_/MvvmCross/Presenters/MvxAttributeViewPresenter.cs:134 
06-16 11:51:34.852 E/mono-rt (21094):   at MvvmCross.Presenters.MvxAttributeViewPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request) [0x00000] in /_/MvvmCross/Presenters/MvxAttributeViewPresenter.cs:175 
06-16 11:51:34.852 E/mono-rt (21094):   at MvxStandardTemplate.Droid.MvxFormsHybridDroidPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request) [0x000ac] in E:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\MvxFormsHybridDroidPresenter.cs:89 
06-16 11:51:34.852 E/mono-rt (21094):   at MvvmCross.Platforms.Android.Views.MvxAndroidViewDispatcher+<>c__DisplayClass2_0.<ShowViewModel>b__0 () [0x00000] in /_/MvvmCross/Platforms/Android/Views/MvxAndroidViewDispatcher.cs:25 
06-16 11:51:34.852 E/mono-rt (21094):   at MvvmCross.Base.MvxMainThreadAsyncDispatcher+<>c__DisplayClass1_0.<ExecuteOnMainThreadAsync>b__0 () [0x00011] in /_/MvvmCross/Base/MvxMainThreadAsyncDispatcher.cs:27 
06-16 11:51:34.852 E/mono-rt (21094):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.65(intptr,intptr)
06-16 11:51:34.852 E/mono-rt (21094):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.65(intptr,intptr)

**Comment by Cheesebaron** [comment]
You don't need any of this. Just use the built in MvxFormsDroidPresenter, it can present native views...

**Comment by haohighview** [comment]
> You don't need any of this. Just use the built in MvxFormsDroidPresenter, it can present native views...

![image](https://user-images.githubusercontent.com/8456671/84766165-eebcdf80-b002-11ea-8833-9f8346b53b78.png)
Mixing MvvmCross Native Views and Xamarin.Forms Pages, the native views has corresponding activity.
Mixing MvvmCross Native Views  (android activity ) and Xamarin.Forms Pages.
Do I still not need these?

**Comment by Cheesebaron** [comment]
No you can just navigate to an Android Activity. We do it in the [Playground.Forms.Droid](https://github.com/MvvmCross/MvvmCross/tree/develop/Projects/Playground/Playground.Forms.Droid) project. I've just made a PR to update the sample so it runs with the latest AndroidX changes.

See: https://github.com/MvvmCross/MvvmCross/pull/3806

**Comment by haohighview** [comment]
works good, thanks

**Comment by christianaldas** [comment]
Hi, everyone.. I have the same error in AndroidX System.Collections.Generic.KeyNotFoundException: 'Could not find view for FBSMovil.Common.ViewModels.Seguridades.LoginViewModel'
