### ISSUE TITLE
Is MVVMCross Compatible with Xamarin.Forms Version 4.6 Shell?

### ISSUE THREAD

**Issue by KannanKalisamy** [MvvmCross/MvvmCross#3778]
Most of my Xamarin forms projects are using MVVMCross. I Just see mvvmcross has any plans to support Xamarain forms 4.6 shell ?

**Comment by Cheesebaron** [comment]
No Shell support. We don't have a good way to harness Shell navigation and hydration of ViewModels.

**Comment by PureWeen** [comment]
@Cheesebaron as an FYI you don't really have to harness Shell navigation to integrate with it. 

I did a stream here with Dan to help the Prism/Shell story along
https://m.twitch.tv/videos/751841332

All of the INavigation methods work with Shell so if MVVMCross works with a NavigationPage then it should work with Shell

We've also been adding additional APIs to help out some of the life cycle bits
https://github.com/xamarin/Xamarin.Forms/pull/12039

**Comment by themronion** [comment]
@Cheesebaron so i guess shell and mvvmcross are still not compatible?

**Comment by Cheesebaron** [comment]
@themronion I haven't done any work on this no. Taking contributions.
