### ISSUE TITLE
Namespace SPRINGBOARD, Code 0x8badf00d

### ISSUE THREAD

**Issue by smillershout** [MvvmCross/MvvmCross#3780]
## 🐛 Bug Report

A client has recently been reporting crashes on their app for several of their users. I was sent some crash logs which I have symbolicated against the dSYM file and I have attached info from the symbolicated crash log. The crash itself is being caused by the app taking too long to launch thus causing the infamous 'ate bad food' error. Whilst I appreciate there are multiple causes for this crash, the reason for posting here is mainly down to the output from the symbolicated crash report. As you can see from the top of the stack trace, the last call before the app dives into system calls is `MvvmCross_Core_MvxSetupSingleton_EnsureInitialized`. Given the difficulty in reproducing this, it's clear that the issue is not caused specifically by a particular piece of code, but a combination of the code and certain conditions hence the low reproducibility of the issue. I was wondering if anyone could shed any light on the `MvvmCross_Core_MvxSetupSingleton_EnsureInitialized` call and if anything in there could be in such a state which would prevent this function from finishing. We do have a variety of initialising and service setups in the App.css file but nothing out of the ordinary.

I realise this is a shot in the dark but if anyone can help out with the above that would much appreciated.

### Expected behavior

App should complete the `AppDidFinishLaunch` phase

### Reproduction steps

Start the app and wait for app to timeout

### Configuration

**MVVM Cross Version:** 6.2.0
**Xcode:** 11.3
**Xamarin:** 6.6.0
**iOS:** 13.3 >

**Platform:** 
- [ ] :iphone: iOS

[crash.txt](https://github.com/MvvmCross/MvvmCross/files/4663815/crash.txt)

**Comment by Cheesebaron** [comment]
Maybe you are running some piece of code that tries to return to the UI thread which might be blocked somehow. There is not much to this stack trace other than it not returning in the `FinishedLaunching` in a timely manner.

**Comment by smillershout** [comment]
@Cheesebaron Yeah, you're absolutely right. I somehow missed the culprit in a different thread in the stack trace which I did not share. Like I said in my post, I assumed, incorrectly, that it may have been something in the main thread related to MVVM Cross but that is not the case. I will close this issue now.

Thanks for your help! :)
