### ISSUE TITLE
What is the recommended way to share ViewModels with different storyboards for iPhone/iPad/Universal App?

### ISSUE THREAD

**Issue by winstonpang** [MvvmCross/MvvmCross#3801]
I can't seem to find much information on this. There appears to use to be an attribute called MvxFormFactorSpecific. But has been since removed many years ago.

What is the guideline for supporting this? I.e. if you have a MainViewModel and you want to use a different storyboard when you're on iPad vs iPhone?

Any help would be much appreciated.

Thanks.

**Comment by winstonpang** [comment]
@Cheesebaron was there any reason why there isn't some easier process like say being able to decorate the storyboards with the specific platform you want it to be on?

So I'm guessing if I wanted to reuse my MainViewModel for example

I would need to inherit from it

IPadMainViewModel : MainViewModel

And then everytime before we do a a navigate it will be:

var isIpad = DeviceInfo.Platform == DevicePlatform.iOS && DeviceInfo.Idiom == DeviceIdiom.Tablet;

if(isIpad)
{
   _navigationService.Navigate<IPadMainViewModel>();
}
else
{
    _navigationService.Navigate<IPadMainViewModel>();
}

**Comment by Cheesebaron** [comment]
Nothing else than no one has made it.

**Comment by Prin53** [comment]
@winstonpang If I understand the issue correctly, you can 
- create a subclass of `MvxIosViewsContainer`
- override `CreateViewOfType` method
- create two storyboards: `MainStoryboardPad` and `MainStoryboardPhone`
- apply `MvxFromStoryboard(“Main”)` attribute to the view
- use `viewType.GetCustomAttribute<MvxFromStoryboardAttribute>();` in Container
- add needed postfix (Pad or Phone) to the storyboard name depending on the current platform
- load the view from the storyboard

**Comment by winstonpang** [comment]
@Prin53 Thanks for your suggestion, that actually sounds like quite a nice way of doing it. So I take it that the CreateViewOfType is where it usually does the ViewModel<->View lookup. 

I suppose there's a few creative ways to approach this, I can detect the device platform and idiom in this method and check if there are any ViewName[Pad].Storyboard named files and if not just fall back to the default implementation.

Anyways regardless this is a good food for thought for me and I will explore this as an option, thank you again.
