### ISSUE TITLE
IMvxIoCProvider required methods

### ISSUE THREAD

**Issue by Shumigaj** [MvvmCross/MvvmCross#3805]
## 💬 Questions and Help

 I want to create adapter for SimpleInjector but it doesn't support child containers. 

- Do I need to implement all methods from IMvxIoCProvider?
- Does MvvmCross use all methods from IMvxIoCProvider or some of them are created just for host applications?

**Comment by Cheesebaron** [comment]
The child container stuff is for host applications. MvvmCross doesn't use any of that itself, so you could leave it out.
