### ISSUE TITLE
How to read arguments when open app from protocol ?

### ISSUE THREAD

**Issue by Sonic3R** [MvvmCross/MvvmCross#3811]
I have CustomAppStart

```
public class CustomAppStart : MvxAppStart
{
    public CustomAppStart(IMvxApplication application, IMvxNavigationService navigationService) :
      base(application, navigationService)
    { }

    protected override async Task NavigateToFirstViewModel(object hint = null)
    { 
       // if not authenticated then go to LoginViewModel, else to StartPageViewModel
    }
}
```

and Setup in `App.xaml.cs`
```
public abstract class UwpApp : MvxApplication<Setup<Core.App>, Core.App>
{
  ...
}
```

I created custom protocol for application, like `myapp` and I can open it as: `myapp://this-test/item`

How to handle those arguments in Xamarin Forms UWP by using MvvmCross ? I'm stucked.

**Comment by Cheesebaron** [comment]
I guess this was answered here: https://stackoverflow.com/questions/62410816/open-app-from-another-app-with-xamarin-forms-and-mvvmcross-uwp
