### ISSUE TITLE
SettingsView crashes

### ISSUE THREAD

**Issue by wocar** [MvvmCross/MvvmCross#3819]
## 🐛 Bug Report

Related to https://github.com/muak/AiForms.SettingsView/issues/115

Crashes when using settings view library
```
07-03 18:31:07.545 F/DEBUG   (10796): Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI NewString called with pending exception android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object.
07-03 18:31:07.545 F/DEBUG   (10796):   at MvvmCross.Platforms.Android.Binding.Views.MvxLayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x00006] in D:\a\1\s\MvvmCross\Platforms\Android\Binding\Views\MvxLayoutInflater.cs:123 
07-03 18:31:07.545 F/DEBUG   (10796):   at AiForms.Renderers.Droid.SettingsViewRecyclerAdapter.OnCreateViewHolder (Android.Views.ViewGroup parent, System.Int32 viewType) [0x0003d] in <1e41ed7b2758417684675b42060962c6>:0 
07-03 18:31:07.545 F/DEBUG   (10796):   at AndroidX.RecyclerView.Widget.RecyclerView+Adapter.n_OnCreateViewHolder_Landroid_view_ViewGroup_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_parent, System.Int32 viewType) [0x00010] in D:\a\1\s\generated\androidx.recyclerview.recyclerview\obj\Release\monoandroid90\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:470 
07-03 18:31:07.545 F/DEBUG   (10796):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.93(intptr,intptr,intptr,int)
07-03 18:31:07.545 F/DEBUG   (10796):   at androidx.recyclerview.widget.RecyclerView$ViewHolder crc6484fad89fba26ff1d.SettingsViewRecyclerAdapter.n_onCreateViewHolder(android.view.ViewGroup, int) (SettingsViewRecyclerAdapter.java:-2)
07-03 18:31:07.545 F/DEBUG   (10796):   at androidx.recyclerview.widget.RecyclerView$ViewHolder crc6484fad89fba26ff1d.SettingsViewRecyclerAdapter.onCreateViewHolder(android.view.ViewGroup, int) (SettingsViewRecyclerAdapter.java:61)
07-03 18:31:07.545 F/DEBUG   (10796):   at androidx.recyclerview.widget.RecyclerView$ViewHolder androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(android.view.ViewGroup, int) (RecyclerView.java:7078)
07-03 18:31:07.545 F/DEBUG   (10796):   at androidx.recyclerview.widget.RecyclerView$ViewHolder androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(int, boolean, long) (RecyclerView.java:6235)
07-03 18:31:07.545 F/DEBUG   (10796):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int, boolean) (RecyclerView.java:6118)
07-03 18:31:07.545 F/DEBUG   (10796):   at android.view.View androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(int) (RecyclerView.java:6114)
07-03 18:31:07.545 F/DEBUG   (10796):   at android.view.View androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(androidx.recyclerview.widget.RecyclerView$Recycler) (LinearLayoutManager.java:2303)
07-03 18:31:07.545 F/DEBUG   (10796):   at void androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(androidx.recyclerview.widget.RecyclerView$Recycler, androidx.recyclerview.widget.RecyclerView$State, androidx.recyclerview.widget.LinearLayoutManager$LayoutState, androidx.recyclerview.widget.LinearLayoutManager$LayoutChunkResult) (LinearLayoutManager.java:1627)
07-03 18:31:07.545 F/DEBUG   (10796):   at int androidx.recyclerview.widget.LinearLayoutManager.fill(androidx.recyclerview.widget.RecyclerView$Recycler, androidx.recyclerview.widget.LinearLayoutManager$LayoutState, androidx.recyclerview.widget.RecyclerView$State, boolean) (LinearLayoutManager.java:1587)
07-03 18:31:07.545 F/DEBUG   (10796):   at void androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(androidx.recyclerview.widget.RecyclerView$Recycler, androidx.recyclerview.widget.RecyclerView$State) (LinearLayoutManager.java:665)
07-03 18:31:07.545 F/DEBUG   (10796):   at void androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2() (RecyclerView.java:4134)
07-03 18:31:07.545 F/DEBUG   (10796):   at void androidx.recyclerview.widget.RecyclerView.dispatchLayout() (RecyclerView.java:3851)
07-03 18:31:07.545 F/DEBUG   (10796):   at void androidx.recyclerview.widget.RecyclerView.onLayout(boolean, int, int, int, int) (RecyclerView.java:4404)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc643f46942d9dd1fff9.ViewRenderer_2.n_onLayout(boolean, int, int, int, int) (ViewRenderer_2.java:-2)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc643f46942d9dd1fff9.ViewRenderer_2.onLayout(boolean, int, int, int, int) (ViewRenderer_2.java:47)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(int, int, int, int, int, int) (FormsViewGroup.java:37)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_onLayout(boolean, int, int, int, int) (Platform_DefaultRenderer.java:-2)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc643f46942d9dd1fff9.Platform_DefaultRenderer.onLayout(boolean, int, int, int, int) (Platform_DefaultRenderer.java:72)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(int, int, int, int, int, int) (FormsViewGroup.java:37)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc643f46942d9dd1fff9.PageRenderer.n_onLayout(boolean, int, int, int, int) (PageRenderer.java:-2)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc643f46942d9dd1fff9.PageRenderer.onLayout(boolean, int, int, int, int) (PageRenderer.java:72)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(int, int, int, int, int, int) (FormsViewGroup.java:37)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc64720bb2db43a66fe9.NavigationPageRenderer.n_onLayout(boolean, int, int, int, int) (NavigationPageRenderer.java:-2)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc64720bb2db43a66fe9.NavigationPageRenderer.onLayout(boolean, int, int, int, int) (NavigationPageRenderer.java:65)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(int, int, int, int, int, int) (FormsViewGroup.java:37)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc64720bb2db43a66fe9.Platform_ModalContainer.n_onLayout(boolean, int, int, int, int) (Platform_ModalContainer.java:-2)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc64720bb2db43a66fe9.Platform_ModalContainer.onLayout(boolean, int, int, int, int) (Platform_ModalContainer.java:53)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc643f46942d9dd1fff9.PlatformRenderer.n_onLayout(boolean, int, int, int, int) (PlatformRenderer.java:-2)
07-03 18:31:07.545 F/DEBUG   (10796):   at void crc643f46942d9dd1fff9.PlatformRenderer.onLayout(boolean, int, int, int, int) (PlatformRenderer.java:63)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.RelativeLayout.onLayout(boolean, int, int, int, int) (RelativeLayout.java:1103)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.LinearLayout.setChildFrame(android.view.View, int, int, int, int) (LinearLayout.java:1829)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.LinearLayout.layoutVertical(int, int, int, int) (LinearLayout.java:1673)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.LinearLayout.onLayout(boolean, int, int, int, int) (LinearLayout.java:1582)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
07-03 18:31:07.545 F/DEBUG   (10796):   at void com.android.internal.policy.DecorView.onLayout(boolean, int, int, int, int) (DecorView.java:776)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.View.layout(int, int, int, int) (View.java:22826)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6316)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewRootImpl.performLayout(android.view.WindowManager$LayoutParams, int, int) (ViewRootImpl.java:3434)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewRootImpl.performTraversals() (ViewRootImpl.java:2907)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewRootImpl.doTraversal() (ViewRootImpl.java:1934)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.ViewRootImpl$TraversalRunnable.run() (ViewRootImpl.java:8127)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.Choreographer$CallbackRecord.run(long) (Choreographer.java:972)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.Choreographer.doCallbacks(int, long) (Choreographer.java:796)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.Choreographer.doFrame(long, int) (Choreographer.java:731)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.view.Choreographer$FrameDisplayEventReceiver.run() (Choreographer.java:957)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:938)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.os.Looper.loop() (Looper.java:223)
07-03 18:31:07.545 F/DEBUG   (10796):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7523)
07-03 18:31:07.545 F/DEBUG   (10796):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-03 18:31:07.545 F/DEBUG   (10796):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:592)
07-03 18:31:07.545 F/DEBUG   (10796):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:941)
```

### Expected behavior
To display settings view

### Reproduction steps

```
<sv:SettingsView x:Name="SettingsView1" VerticalOptions="CenterAndExpand" HasUnevenRows="true">

               <sv:Section HeaderHeight="100">
                   <sv:TimePickerCell
                       x:Name="TimeCell"
                       
                       Title="Hour" Format="%h:mm tt" Time="{Binding Reminder.Time}" />
                   
                   <sv:PickerCell Title="Day"
                                  x:Name="PickerCell"
                                  SelectionMode="Single"
                                  ItemsSource="{Binding DayList}"
                                  SelectedItem="{Binding Reminder.Day}"
                                  DisplayMember="Name"
                                  KeepSelectedUntilBack="true"
                                  PageTitle="Day" />

               

               
               </sv:Section>
               <sv:Section IsVisible="{Binding ShowDeleteButton}">
                   <sv:ButtonCell
                       Command="{Binding DeleteCommand}" Title="Delete alarm" TitleColor="Red" />
               </sv:Section>

           </sv:SettingsView>
```

### Configuration

- AiForms.SettingsView 1.2.14-pre
- Xamarin.Forms 4.7.0.813-pre2

        <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.2.0.1" />
        <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.2.0.1" />
        <PackageReference Include="Xamarin.Google.Android.Material" Version="1.0.0" />
        <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.1" />
        <PackageReference Include="Xamarin.AndroidX.AppCompat.AppCompatResources" Version="1.1.0.1" />
        <PackageReference Include="Xamarin.AndroidX.AppCompat.Resources" Version="1.1.0.1" />
        <PackageReference Include="Xamarin.AndroidX.MediaRouter" Version="1.1.0.1" />
        <PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.3" />
        <PackageReference Include="MvvmCross" Version="6.4.2" />
        <PackageReference Include="MvvmCross.Forms" Version="6.4.2" />

        <TargetFrameworkVersion>v9.0</TargetFrameworkVersion>

**Platform:** 
- [X] :robot: Android

**Comment by Cheesebaron** [comment]
Not sure what is going on here. The stack trace indicates that `_bindingVisitor` is somehow `null`. But it is a `readonly` field that is only ever created in the ctor of the Layout Inflater.

https://github.com/MvvmCross/MvvmCross/blob/6.4.2/MvvmCross/Platforms/Android/Binding/Views/MvxLayoutInflater.cs#L123

I don't see that library depending on MvvmCross, so you have the reference in your own App it seems.

There might be an issue mixing 6.4.2 with AndroidX RecyclerView. Could you perhaps try the latest alpha from here: https://github.com/MvvmCross/MvvmCross/packages and see if it is still an issue? This has AndroidX support.

**Comment by wocar** [comment]
Thank you very much @Cheesebaron 

SettingsView does this call

`      LayoutInflater layoutInflater = LayoutInflater.FromContext(this._context);
`
thus invoking the this contructor in mvxlayoutinfater

       ```
 public MvxLayoutInflater(IntPtr handle, JniHandleOwnership transfer)
            : base(handle, transfer)
        {
        }

```

making `_bindingVisitor` null

**Comment by Jakar510** [comment]
@wocar Thank you, I've been investigating this for some time, and couldn't find the cause.

**Comment by Cheesebaron** [comment]
Upgrade to MvvmCross 7.0.0. I've made the ctor @wocar pointed out there create a new binding visitor.

**Comment by luisresende247** [comment]
I'm having the same issue with MvvmCross 7 and AndroidX.

`JNI DETECTED ERROR IN APPLICATION: JNI NewString called with pending exception android.runtime.JavaProxyThrowable: System.MissingMethodException: Method not found: Android.Views.View Android.Views.LayoutInflater.CreateView(Android.Content.Context,string,string,Android.Util.IAttributeSet)
java_vm_ext.cc:577]   at MvvmCross.Platforms.Android.Binding.Views.MvxLayoutInflater+PrivateFactoryWrapper2.OnCreateView (Android.Views.View parent, System.String name, Android.Content.Context context, Android.Util.IAttributeSet attrs) [0x00028] in /_/MvvmCross/Platforms/Android/Binding/Views/MvxLayoutInflater.cs:499 
java_vm_ext.cc:577]   at Android.Views.LayoutInflater+IFactory2Invoker.n_OnCreateView_Landroid_view_View_Ljava_lang_String_Landroid_content_Context_Landroid_util_AttributeSet_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_parent, System.IntPtr native_name, System.IntPtr native_context, System.IntPtr native_attrs) [0x0002a] in /Users/builder/azdo/_work/287/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-28/mcw/Android.Views.LayoutInflater.cs:188 
java_vm_ext.cc:577]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.67(intptr,intptr,intptr,intptr,intptr,intptr)
java_vm_ext.cc:577]   at android.view.View mvvmcross.platforms.android.binding.views.MvxLayoutInflater_PrivateFactoryWrapper2.n_onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (MvxLayoutInflater_PrivateFactoryWrapper2.java:-2)
java_vm_ext.cc:577]   at android.view.View mvvmcross.platforms.android.binding.views.MvxLayoutInflater_PrivateFactoryWrapper2.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (MvxLayoutInflater_PrivateFactoryWrapper2.java:32)
java_vm_ext.cc:577]   at android.view.View android.view.LayoutInflater$FactoryMerger.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:237)
java_vm_ext.cc:577]   at android.view.View android.view.LayoutInflater.tryCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:1067)
java_vm_ext.cc:577]   at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:995)
java_vm_ext.cc:577]   at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:657)
java_vm_ext.cc:577]   at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:532)
java_vm_ext.cc:577]   at android.view.View mvvmcross.platforms.android.binding.views.MvxLayoutInflater_PrivateFactoryWrapper2.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (MvxLayoutIn09-16 14:48:42.303 F/247.customerap(23793): java_vm_ext.cc:577]   at void crc64d1ebcebbae0f1266.InitialView.n_onCreate(android.os.Bundle) (InitialView.java:-2)
java_vm_ext.cc:577]   at void crc64d1ebcebbae0f1266.InitialView.onCreate(android.os.Bundle) (InitialView.java:37)
java_vm_ext.cc:577]   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:8000)
java_vm_ext.cc:577]   at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (Layte(android.os.Bundle) (Activity.java:7984)
java_vm_ext.cc:577]   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1309)
java_vm_ext.cc:577]   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:3422)
java_vm_ext.cc:577]   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3601)
java_vm_ext.cc:577]   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:85)
java_vm_ext.cc:577]   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:135)
java_vm_ext.cc:577]   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:95)
[209-16 14:48:42.304 F] java_vm_ext.cc:577]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
java_vm_ext.cc:577]   at void android.os.Looper.loop() (Looper.java:223)
java_vm_ext.cc:577]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7656)
java_vm_ext.cc:577]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
java_vm_ext.cc:577]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:592)
java_vm_ext.cc:577]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:947)
java_vm_ext.cc:577] 
java_vm_ext.cc:577]     in call to NewString
java_vm_ext.cc:577]     from android.view.View mvvmcross.platforms.android.binding.views.MvxLayoutInflater_PrivateFactoryWrapper2.n_onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet)`

**Comment by Cheesebaron** [comment]
@luisresende247 that looks like a different issue

**Comment by luisresende247** [comment]
@Cheesebaron I've tried Android 9 targetting APIs 29 and 30

**Comment by Cheesebaron** [comment]
@luisresende247 dunno. Cannot reproduce. Please open a new issue. This one is different. Thanks!
