### ISSUE TITLE
Plugin obsolete by Xamarin.Essentials

### ISSUE THREAD

**Issue by andres-gimenez** [MvvmCross/MvvmCross#3824]
## 🏗 Enhancement Proposal

With Xamarin.Essential there are some plugins that have become obsolete. Shouldn't we take them off?

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Nah, I say leave them. I don't like how Xamarin.Essentials works and there are no official interfaces for support for IoC containers and DI frameworks. It is good to have some alternatives.
