### ISSUE TITLE
Tibet binding operator precedence 

### ISSUE THREAD

**Issue by et-nowis** [MvvmCross/MvvmCross#384]
There is no precedence of the operators,
`a < b && c < d` will be parsed as
`(a < (b && (c < d)))`
Whereas the precedence in C# is
`(a < b) && (c < d)`
Side-note: The above expression with additional parenthesis works

It may take some work to introduce operator precedence in tibet binding.

**Comment by martijn00** [comment]
Closed for now. Reopen again if relevant in the future.
