### ISSUE TITLE
MvxPopoverPresentationAttribute

### ISSUE THREAD

**Issue by Hackmodford** [MvvmCross/MvvmCross#3840]
## 🚀 Feature Requests

MvxPopoverPresentationAttribute for the iOS view presenter.

### Contextualize the feature
An iOS presentation attribute for popover views.

### Describe the feature
I believe this would be very similar to the MvxModalPresentationAttribute except that the modal presentation style would always be `.popover` and there should should be a way to specify the source rect as well as the arrow direction.

![popover_example](https://user-images.githubusercontent.com/326668/87877475-959eed80-c9ac-11ea-8bba-8b4a4012dd50.png)

If this can already be achieved with the MvxModalPresentationAttribute as is, is there an example of this behavior?

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms
- [ ] :🌍: Blazor

**Comment by Hackmodford** [comment]
Could viewControllers wishing you show popovers implement an interface that the navigation service could use to get the source rect?

**Comment by Cheesebaron** [comment]
There is no real nice way of providing the SourceRect for the popover. Sure you could implement `IMvxOverridePresentationAttribute` and provide it there.

However, we have no built in presentation attribute for presenting popovers currently.

**Comment by Hackmodford** [comment]
Still leaves the problem of obtaining the source rect from the previous view controller.

My thought would be the previous view could implement an interface that claims it would provide a source rect for any popover being presented. When the new view is created, the previous view could be checked to see if it implements the interface and retrieve a source rect. We probably wouldn’t even need a new presentation attribute to do this, just a modification of the iOS presenter. Any thoughts on this approach?

**Comment by Cheesebaron** [comment]
I still think it would be a bit cleaner to have a separate presentation attribute for popovers. This way when they are registered in the presenter, we can easily have a separate method in there to present it, instead of adding to one of the existing ones.

So create: `MvxPopoverPresentationAttribute` and `IMvxPopoverPresentationSourceRectProvider` or something like that.

**Comment by Hackmodford** [comment]
This is proving to be more difficult than I anticipated. I'm not sure how to find the view that implements the sourceRectProvider interface.

Is there a way to get the viewController from the `MvxViewModelRequest`?

I considered crawling the view hierarchy, but that could lead to problems if more than one view implements the interface.

```
var viewHost = ModalViewControllers.LastOrDefault() ?? _window.RootViewController;
            if (!(viewHost is IMvxPopoverPresentationSourceRectProvider))
            {
                throw new MvxException("Could not present popover controller. Host view controller must implement IMvxPopoverPresentationSourceRectProvider");
            }
            var popoverHost = viewHost as IMvxPopoverPresentationSourceRectProvider;
```
