### ISSUE TITLE
Generic.KeyNotFoundException MvxTabLayoutPresentationAttribute

### ISSUE THREAD

**Issue by andres-gimenez** [MvvmCross/MvvmCross#3841]
## 🐛 Bug Report

When migrating to AndroidX, MvxTabLayoutPresentationAttribute is not implemented

`System.Collections.Generic.KeyNotFoundException: 'The type MvxTabLayoutPresentationAttribute is not configured in the presenter dictionary'`

The problem is that TabLayout is now in Xamarin.Google.Android.Material.  Which begs to include it in MvvmCross. Or create an MvxAndroidViewPresenter in MvvmCross.DroidX.Material.

### Reproduction steps

Pulsar Show Tabs in Playground.Drpod

### Configuration

**Version:** 7.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
I think I managed to remove it while migrating to AndroidX. We should add this back. Perhaps where we use ViewPager2 instead.
