### ISSUE TITLE
IMvxLog is not available early enough in the bootstrap process

### ISSUE THREAD

**Issue by Adam-Langley** [MvvmCross/MvvmCross#3845]
## 🏗 Enhancement Proposal

Initialise logging earlier.
Initialise the IoC container earlier, or provide an out-of-band mechanism for accessing IMvxLog that does not depend on the IoC container, such that IMvxLog can be accessed within "UIApplicationDelegate.WillFinishLaunching"

### Pitch

Logging is critical for the diagnostics of issues in production. As such, it's important for logging to commence as early as possible - ideally it should be the very first app code to commence.
In writing a VOIP application for iOS, application launch is absolutely critical to the users ability to answer an incoming call in a timely manner - so it's critical I can capture what is happening during launch. Additionally - Apple introduced scenarios where an app could be terminated if it does not react immediately to VOIP push notifications (which are potentially received during app launch). Logging during this critical startup phase is essential.

Currently, IMvxLog is only available after InitializePrimary has completed - which means that all code to run before "UIApplicationDelegate.FinishedLaunching" cannot be logged without duplicating the logging initialisation.

_potentially affects Android_

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by andrechi1** [comment]
I want to refactor everything related to asynchronous. That allows me to boot into multi tasks. One of the things to do is refactor MvxSingleton. I started working on a thread, which had too many changes. And now I'm doing it little by little. 

I'm waiting to be accepted by the pullrequests I've sent to me, so I can keep working on this.
