### ISSUE TITLE
How to add an unknown number of properties to log that are not part of message format

### ISSUE THREAD

**Issue by bcassell** [MvvmCross/MvvmCross#3847]
## 💬 Questions and Help

Hi all.  Not sure whether to count this as a bug, so much as it is a weird behavior that might be resulting from me not doing something right.  What is the best way to add properties to a trace so that they show up as named properties?  For concreteness, I'm using Serilog, and to add properties to a log statement (that are specific to the log statement) I believe my choices are to either use them in the format string, or use

```
using(logProvider.OpenMappedContext(key, value))
{
   // do some logging
}
```

Now where things get weird is if I have a some sort of enumeration of properties.  I'd love to be able to just use a dictionary, but I don't see functionality for that.  I'd also prefer not to have all of my many usages of the log cluttered up with using statements.  So, I ended up with this:

```
/// parameters is a Dictionary<string, string> 
...
var disposables = Enumerable.Empty<IDisposable>();

try
{
    if (parameters != null)
    {
        disposables = parameters.Select(p => logProvider.OpenMappedContext(p.Key, p.Value)).ToArray();
    }

    // do some logging
}
finally
{
    foreach (var disposable in disposables)
    {
        disposable.Dispose();
    }
}
```

What I read in the Microsoft documents is that 'using(...)' is equivalent to wrapping in a try-finally to make sure the resources get disposed.  But when I use the above code with Serilog and MvvmCross, some (but not all) properties stick around from log statement to log statement, whereas I've never had that problem with putting the OpenMappedContext in a using statement.  So two questions:

1. What is the right way to add named properties that are not part of the formatted message string?
2. Any idea why there is a discrepancy in how these resources are getting cleaned up?

**Comment by bcassell** [comment]
Moving to StackOverflow: https://stackoverflow.com/questions/63274647/mvvmcross-adding-properties-to-an-imvxlog-trace-without-using-them-in-the-messa

**Comment by tougher** [comment]
Did you ever figure out why the properties are not cleared after disposing? I have the same issue and I can't upgrade to MvvmCross 8 yet (shared lib code) where the bunkers `SerilogLogProvider` is gone and I assume the issue will be indirectly fixed.

**Comment by tougher** [comment]
Nevermind, I will just use `Serilog.Extensions.Logging` for my shared lib.
