### ISSUE TITLE
Net5.0-windows, the future TFM 

### ISSUE THREAD

**Issue by andres-gimenez** [MvvmCross/MvvmCross#3851]
## 🏗 Enhancement Proposal

With Net5.0 disappears UAP as TFM and unifies UWP and WPF. Will UAP and WPF be unified in MvvmCross?

Microsoft will differentiate between interfaces. WinForm, WPF, and WinRT can be used. How is this change going to be adapted?

### Pitch

Net5.0 is going to bring a lot of changes to TFMs, and you have to define how MvvmCross will be adapted.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
WPF/WinForms will move to `net5.0-windows`. There is still an open issue about UWP, which they haven't solved yet. But it will most likely look like `net5.0-uwp` or something like that.

**Comment by andres-gimenez** [comment]
It's only going to exist net5.0-windows. The difference between Wpf/WinForms/UWP is the libraries you load.

**Comment by Cheesebaron** [comment]
According to this: https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#window-specific-behavior it is still an Open Issue how this will behave.

**Comment by andres-gimenez** [comment]
Net5.0 for WinRT is this https://github.com/microsoft/CsWinRT

I don't think the TFMs for OS are going to be on net5.0. We'll have to wait for net6.0

**Comment by Cheesebaron** [comment]
It is speculation, I'll wait for the official answer. Either way, it isn't going to be much of a change at most moving some files around.

**Comment by andres-gimenez** [comment]
This isn't to do it now. I just want to comment on it.

When I started to see what net5.0 was. I thought they were going to unify WPF and UWP. But I don't think it's going to be like this.

Unification on iOS and MacOS. With Xcode, you can run App's designed for iOS on MacOS. But for Xamarin I haven't seen anything.

**Comment by Cheesebaron** [comment]
There was a survey recently where they were asking what we wanted to see supported in Xamarin first. Where stuff like catalyst was mentioned. They are working on it, but I guess the priority depends on the survey.

**Comment by enizvk** [comment]
.NET was released. Do you have any estimated TFM for .net 5 support so we can start preparing for migration?

**Comment by Cheesebaron** [comment]
Nothing really needs to be done to use MvvmCross in .NET5 you can use it as is.

**Comment by Cheesebaron** [comment]
NET5 does not have support for iOS, Android, macOS TFMs, we will not be supporting it directly, but rather through NET5 backwards compatbility.

We are waiting for NET6 to move forward.
