### ISSUE TITLE
MacOS application menubar command binding?

### ISSUE THREAD

**Issue by rob-alem** [MvvmCross/MvvmCross#3852]
## 💬 Questions and Help

I want to create a custom application menubar within my MvvmCross MacOS application. Is it currently possible to bind the menuitems to commands inside my ViewModels in order to preserve the ViewModel-first navigation?

**Comment by Cheesebaron** [comment]
I don't think we have bindings for the menu items. However, you can always invoke `ViewModel.SomeCommand.Execute()` from a event handler.

**Comment by Cheesebaron** [comment]
Just dug through the code, there is one Target binding for NSMenuItem here: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Mac/Binding/Target/MvxNSMenuItemOnTargetBinding.cs However, that is for the checked state. If you need something for Click events or whatever, you will have to create your own and register them in setup
