### ISSUE TITLE
Repair Warning in code.

### ISSUE THREAD

**Issue by andres-gimenez** [MvvmCross/MvvmCross#3853]
## 💬 Manage Warnings Repair

Three code analyzers are being used, plus sonar on the server. But he's getting little he caseed. The code generates 2307 Warnings. That should be fixed.

Starting with c# 8, the way null values are treated has changed and would need to be modified.

How is this managed?

I usually fix these problems little by little, when I modify a class, I solve the Warnings that it has.

**Comment by Cheesebaron** [comment]
I would be fine with doing this little by little. When changing a class that is affected by warnings.

However, I would prefer any fixes would be kept in separate commits from the actual changes happening. I.e. if you are solving a bug or something like that. Keep changes for the bug separate from warning fixes.
