### ISSUE TITLE
Why is 5.2.1 the latest version according to GitHub?

### ISSUE THREAD

**Issue by radioactiveman** [MvvmCross/MvvmCross#3855]
## 💬 Questions and Help

According to https://github.com/MvvmCross/MvvmCross/releases/latest 5.2.1 is the latest version, although it should be 6.4.2.
What is the reason for this and could it be fixed please?

**Comment by multinerd** [comment]
Pulls 5.2.1 for me

**Comment by radioactiveman** [comment]
@multinerd: When creating this issue it was definitely 5.3.0, I have no idea why.

**Comment by Cheesebaron** [comment]
And then when you toggle between release and tags, then back to release, it doesn't show it anymore.

Seems broken to me. Latest version is 6.4.2 and [Changelog](https://github.com/MvvmCross/MvvmCross/blob/develop/CHANGELOG.md) is the current source of truth for what has changed.

**Comment by Cheesebaron** [comment]
Fixed now that 7.0.0 is out

**Comment by radioactiveman** [comment]
@Cheesebaron: The issue occurs again. GitHub says 7.0.0 is the latest version, but it should be 7.0.1.

https://github.com/MvvmCross/MvvmCross/releases

**Comment by Cheesebaron** [comment]
I didn't create a release for 7.0.1. There is a tag for it though.

**Comment by multinerd** [comment]
Technically 7.0.0 *is* the latest. 7.0.1 is just a tag. Whether or not GitHub should show it is another issue for GitHub.

**Comment by radioactiveman** [comment]
> I didn't create a release for 7.0.1. There is a tag for it though.

Then please do this in the future.
The latest version from NuGet should match with the info from GitHub. Everything else is just confusing.

See also: https://github.community/t/why-last-release-is-not-marked-as-latest-release/421/5
