### ISSUE TITLE
TextInputEditText inside MvxRecyclerView Hint doesn't animate

### ISSUE THREAD

**Issue by cjrvdev** [MvvmCross/MvvmCross#3874]
## 🐛 Bug Report

He hint moving up when focused doesn't work when focused in certain situations (check Repro steps).

### Expected behavior+

Animation as usual when focused

### Reproduction steps

Suppose you have a MvxRecyclerView with TextInputLayouts and TextInputEditText inside de ItemTemplate. 

```
<MvvmCross.Droid.Support.V7.RecyclerView.MvxRecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        local:MvxItemTemplate="@layout/list_item_view"
        local:MvxBind="ItemsSource Asegurados"/>  
```

```
<!--list_item_view.axml -->
<android.support.design.widget.TextInputLayout
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:layout_marginTop="@dimen/margin_medium_extra"
	android:layout_marginBottom="@dimen/margin_small">
	<android.support.design.widget.TextInputEditText
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:layout_gravity="center"
		android:imeOptions="actionDone"
		android:maxLines="1"
		local:MvxLang="Hint Name"
		local:MvxBind="Text Name"/>
</android.support.design.widget.TextInputLayout>
<!-- Apellidos  -->
<android.support.design.widget.TextInputLayout
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:layout_marginTop="@dimen/margin_extra_large"
	android:layout_marginBottom="@dimen/margin_small">
	<android.support.design.widget.TextInputEditText
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:layout_gravity="center"
		android:imeOptions="actionDone"
		android:hint="Surname"
		local:MvxBind="Text Surname"/>
</android.support.design.widget.TextInputLayout>
```

I went a bit further and found out that if you use  `android:hint="whatever"` it works perfectly and animates as expected. Whereas if you use for example MvxLang to bind to my text resource it will act as a normal EditText without animation. You can see it in the code above with Nombre and Apellidos and in the picture below:

### Configuration

**Version:** 6.4.2

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
The hint should be on `TextInputLayout` not on the `TextInputEditText`.

**Comment by cjrvdev** [comment]
Contradictory to any logic.. as android:hint is in the TextInputEditText and not in the parent but yea I just checked and it now works. Somebody here needs some sleep... You may now close the issue, sorry for the inconvenience

**Comment by Cheesebaron** [comment]
Don't worry. Happy you got it to work :)
