### ISSUE TITLE
Possible memory leak? Views and ViewModels are not collected by the GC

### ISSUE THREAD

**Issue by cristianvasuica** [MvvmCross/MvvmCross#3889]
🐛 Bug Report
---
This bug is reproducing on Android platform (this is the only one I have tried so far). Investigating app crashes, I have seen that used memory increases a lot for my app. I have then profiled the app and noticed that Views and ViewModels are never collected by GC. Also, overriding OnDestroy() in the View, this is never called.

**Expected behavior**
Views and ViewModels should be destroyed and they should not be hanging in memory.

**Reproduction steps**
Created a small test app starting from TipCalculator and did a memory profiling session on it.
This app has only two screens and navigation between them.

In this image you can see the information from Xamarin Profiler:
![image](https://user-images.githubusercontent.com/18456488/90760670-ec208400-e2ea-11ea-8df8-79d9c577bad5.png)

I've create a sample Android Native UI app for this issue. This app starts from TipCalc sample. I have extended it with an extra screen, Details and a navigation between the two screens. 
The navigation part is done via Commands and NavigationService.
This app is available here: https://github.com/cristianvasuica/MvvmCrossMemoryLeakTest

In the git repository there can also be found the memory profiling session data. https://github.com/cristianvasuica/MvvmCrossMemoryLeakTest/blob/master/ProfileTrace.mlpd

**Questions**

1. Did somebody else confronted with this issue?
2. Is there a bad usage of the framework in the provided sample?

**Configuration**
Version: 6.x

Platform:
- [ ] 📱 iOS
- [x] 🤖 Android
- [ ]  🏁 WPF
- [ ]  🌎 UWP
- [ ]  🍎 MacOS
- [ ]  📺 tvOS
- [ ]  🐒 Xamarin.Forms

**Comment by Cheesebaron** [comment]
Looks as per the design. We have this thing called MvxChildViewModelCache which will keep a ViewModel around just in case you will navigate back to it again soon.

You can always override this behavior by implementing a IMvxChildViewModelCache which just returns null for every key. Then override `CreateViewModelCache` in Setup.cs to use your own caching mechanism.
