### ISSUE TITLE
Breaking change when upgrading to Xamarin.Forms 4.8

### ISSUE THREAD

**Issue by PavelRPavlov** [MvvmCross/MvvmCross#3896]
## 🐛 Bug Report

If a Xamarin.Forms application gets updated to Xamarin.Forms 4.8, the navigation menus/tabs get recreated every time the app is resumed. This is not the case with earlier versions of Xamarin.Forms.

The structure of the application is as follows:
- a page configured as root: **MvxTabbedPage** (e.g. RootPage.cs)
- a simple view page 1 configured as tab: **MvxContentPage** (e.g. TipView.xaml)
- a simple view page 2 configured as tab: **MvxContentPage** (e.g DummyView.xaml)

The **ViewAppearing()** method of the RootViewModel is used to initialize the rest of the views like this:

`await navigationService.Navigate<TipViewModel>();`
`await navigationService.Navigate<DummyViewModel>();`

### Expected behavior
The navigation should not be recreated when the application gets resumed. This is not happening when earlier version of Xamarin.Forms is used (e.g. 4.7.*).

### Reproduction steps
1. start the provided app
1. note the number of the created tabs - should be 2
1. pause/minimize the app by pressing the home button
1. resume the app by tapping on its icon
1. note the number of the tabs - they are now 4 instead of 2

### Configuration
Attached is the TipCalc demo, modified to match the described structure.
[TipCalc.zip](https://github.com/MvvmCross/MvvmCross/files/5140454/TipCalc.zip)

**Version:** 6.x & 7.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android 
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Well, we don't target Xamarin.Forms 4.8.x yet. We would greatly appreciate the help getting the code up to date and support it.

**Comment by grandconjuration** [comment]
Is this documented anywhere? Which Xamarin.Forms version is targeted?

**Comment by Cheesebaron** [comment]
See: https://www.nuget.org/packages/MvvmCross.Forms/

![image](https://user-images.githubusercontent.com/249719/101170000-126df380-363e-11eb-8cdf-688b7717b264.png)

We are targeting 4.6.0.847

**Comment by Cheesebaron** [comment]
Fixed with MvvmCross 8
