### ISSUE TITLE
How to use a view as the starting window instead of MainWindow without StartupUri ? 

### ISSUE THREAD

**Issue by Proless** [MvvmCross/MvvmCross#3909]
## 💬 Questions and Help

in a WPF application i want to remove the MainWindow and the StartupUri and use a View as the Startup window instead. is this possible, is it related a ViewPresenter ?

right now two windows are opened the MainWindow and a ShellView which is a MvxWindow. This ShellView is the View for my Start ViewModel registered with ``` RegisterAppStart<ViewModels.ShellViewModel>(); ```
similar issue https://github.com/MvvmCross/MvvmCross/issues/181

If i remove the StartupUri from App.xaml no Window is opened and the Setup process doesn't start at all.

**Comment by Cheesebaron** [comment]
I need more info or a better a sample to determine what to do here.

**Comment by Proless** [comment]
this is the [project repo](https://github.com/Proless/ModGuide) , so far i only followed the [Mvvmcross Overview](https://www.mvvmcross.com/documentation/getting-started/mvvmcross-overview) part of the documentation to create the projects.

**Comment by rftd** [comment]
I have the same problem, how do you resolve ?

**Comment by highspeeder** [comment]
I have the same problem. too
