### ISSUE TITLE
MvvmCross v7.0.0 Release Broke TipCalc.Droid Project

### ISSUE THREAD

**Issue by skinnystick22** [MvvmCross/MvvmCross#3910]
## 🐛 Bug Report

After updating to MvvmCross v7.0.0; I am unable to get the TipCalc project working correctly within the Android project. The namespace, MvvmCross.Platforms.Android.Views, cannot be resolved. 

### Expected behavior
The expected behavior would be for it to be resolving correctly and then the TipView class should be able to resolve from MvxActivity<T>.

### Reproduction steps
Install the latest version of MvvmCross in the TipCalc.Droid project. The following using directives will cause a compile-time error:
```csharp
using MvvmCross.Platforms.Android.Core;
using MvvmCross.Platforms.Android.Views;
```

### Configuration
Here is the MainApplication.cs file from the TipCalc.Droid:
```csharp
using System;
using Android.App;
using Android.Runtime;
using MvvmCross.Platforms.Android.Core;
using MvvmCross.Platforms.Android.Views;
using TipCalc.Core;

namespace TipCalc.Droid
{
    [Application]
    public class MainApplication : MvxAndroidApplication<MvxAndroidSetup<App>, App>
    {
        public MainApplication(IntPtr javaReference, JniHandleOwnership transfer) : base(javaReference, transfer)
        {
        }
    }
}
```
Here is the TipView.cs file that is located in the TipCalc.Droid.Views namespace:
```csharp
using Android.App;
using Android.OS;
using MvvmCross.Platforms.Android.Views;
using TipCalc.Core.ViewModels;

namespace TipCalc.Droid.Views
{
    [Activity(Label = "Tip Calculator", MainLauncher = true)]
    public class TipView : MvxActivity<TipViewModel>
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            SetContentView(Resource.Layout.TipView);
        }
    }
}
```

**Version:** 7.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by dubstepadii** [comment]
This does not only apply only to TipCalc.Droid Project. 
Just tried to upgrade our project to 7.0.0 version and Droid also failed, because it does not see "MvvmCross.Platforms" namespace and everyting that's under it.

**Comment by skinnystick22** [comment]
I started looking through the Source Code and found that the namespace exists in the source code. The problem seems to be that nuget package manager is missing some code.

**Comment by Cheesebaron** [comment]
No as @dubstepadii points out. The App needs to target MonoAndroid10.0. Otherwise it won't find the dll's in the NuGet packages.

See: https://github.com/MvvmCross/MvvmCross-Samples/blob/master/TipCalc/TipCalc.Droid/TipCalc.Droid.csproj#L18

**Comment by Cheesebaron** [comment]
Sample should be fixed.
