### ISSUE TITLE
SearchView query binding not working on mvvmcross 7.0

### ISSUE THREAD

**Issue by gocmenali** [MvvmCross/MvvmCross#3936]
after updating my project mvvmcross 7.0 my searchView not works on, i tried to change searchView namespace with AndroidX, but with 7.0 either android.support.v7.widget.seearchView or androidx.appcompat.widget.searchView are not working.

This is output message and i cant solve this, i think it is about upgrading mvvmcross.
**(MvxBind) Failed to create target binding for binding Query for SearchString**

**Comment by winstonpang** [comment]
I have the same issue as well, the binding does seem to be written for the androidx.appcompat.widget.SearchView though, which is what I am using.

https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Android/Binding/Target/MvxAppCompatSearchViewQueryTextTargetBinding.cs

**Comment by winstonpang** [comment]
On another note I can't find it being registered anywhere in the MvvmCross repo though.

**Comment by winstonpang** [comment]
@gocmenali I found a work around, it appears to be a bug, potentially, that MvxAppCompatSearchViewQueryTextTargetBinding is not registered.

You just need to simply register it yourself under your AppSetup (MvxAndroidSetup).

`    public class AppSetup : MvxAndroidSetup<App>
    {
        /// <summary>
        /// Fill the Binding Factory Registry with bindings from the support library.
        /// </summary>
        protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            base.FillTargetFactories(registry);

            registry.RegisterCustomBindingFactory<View>(
                 "Query",
                  search => new MvxAppCompatSearchViewQueryTextTargetBinding(search));
        }
    }`

**Comment by gocmenali** [comment]
Thanks for your replies, i solved the problem as creating a custom searchview binding, your way is also useful

**Comment by Cheesebaron** [comment]
@winstonpang should be fine. I guess I forgot to move some of the registration from the old Support libraries over when we did the AndroidX migration.

**Comment by greatvova** [comment]
I've faced the same issue but with Click and LongClick bindings. I've tried to fix it with RegisterCustomBindingFactory but it does not help.
