### ISSUE TITLE
Upgrading from 6.4 to 7.0

### ISSUE THREAD

**Issue by romulotil** [MvvmCross/MvvmCross#3937]
I upgraded to version 7.0 but now I have errors on building

I'm getting:

No resource identifier found for  attribute 'MvxBind' in package 'my.app.package'  (APT1000)

and also for MvxLang

Do i have to add something extra to my projects?

**Comment by Cheesebaron** [comment]
Not really.

Just make sure that you:
1. Don't mix with old versions of MvvmCross packages
2. You are targeting Android 10
3. Did all the namespace and type changes. I made a list of what I had to do in one of the Apps I work on here: https://gist.github.com/Cheesebaron/16676992798ccd7f5b8202d94c61d28e

**Comment by awasilik** [comment]
I have a question. What about MvxFragmentActivity? It was deleted but what is my alternative? Should I use MvxActivity now instead?

**Comment by Cheesebaron** [comment]
MvxActivity is the one now 👍

**Comment by sledderGIT** [comment]
And what is analogue for MvxAppCompatSetup now? I found this one 

MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatSetup | MvvmCross.Platforms.Android.Core.MvxAndroidSetup
-- | --
But I don't have `MvvmCross.Platforms` namespace in my android project

**Comment by ivmirx** [comment]
@sledderGIT was recently confused for half an hour with that one and turned out my Android project wasn't targeting Android 10.0 in _Project Options -> General -> Compile using Android version_.

**Comment by sledderGIT** [comment]
Ah in my case I've just deleted MvvmCross package and installed it again

**Comment by saamerm** [comment]
@romulotil did that solve your problem?

**Comment by UnreachableCode** [comment]
> MvxActivity is the one now 👍

Does the same go for MvxAppCompatActivity?
