### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by raihaniqbal** [MvvmCross/MvvmCross#3955]
The TipCalc tutorial needs updating to reflect the latest release. I'm stuck in the TipCalc Android Project section because the MvvmCross package doesnt have a class called **`MvxAndroidApplication`**.

`public class MainApplication : MvxAndroidApplication<MvxAndroidSetup<App>, App>{ ....}`

**Comment by Cheesebaron** [comment]
Get yourself unstuck and check the updated TipCalc sample here: https://github.com/MvvmCross/MvvmCross-Samples/tree/master/TipCalc
