### ISSUE TITLE
Refactoring MvvmCross Mac to remove a memory leak

### ISSUE THREAD

**Issue by ivmirx** [MvvmCross/MvvmCross#3963]
The bugs described in #3579 appeared in the first place because `NSApplication.SharedApplication.Windows` does not remove dismissed/closed windows when called. This property is deprecated and was renamed to `DangerousWindows` because of all the problems it can create:

> NSApplication.SharedApplication.Windows is EVIL. It hooks into the alloc/dealloc of windows, and when you reference it in C# will make bridged objects to everything in the list. Which means if you have windows that are going to dealloc, and then look at the list, you now poked them again to stay alive a bit longer.

[Source](https://forums.xamarin.com/discussion/81199/closed-windows-are-not-releasing-memory), see also the [related issue](https://github.com/xamarin/xamarin-macios/issues/5350) in Xamarin.Mac. For some reason, "a bit longer" has changed since then and now windows stay in the list forever(?) if you make any calls to `NSApplication.SharedApplication.DangerousWindows` while trying to close one.

To see it for yourself, get the slightly modified `MvxMacViewPresenter` from [the attachment](https://github.com/MvvmCross/MvvmCross/files/5412389/MvxMacViewPresenter.cs.txt) and then do the following:
- run the Playground app and click "Show Sheet" -> "Close" multiple times 
- place a breakpoint inside `Close()`
- make an evaluation of `NSApplication.SharedApplication.DangerousWindows`, it should be **2** windows
- continue execution, click "Show Sheet" -> "Close" again
- this time evaluation of `DangerousWindows` will return **3** windows
- you can open-close the sheet a few more times without evaluating and it will not grow the window number either

So, it seems to me that `MvxMacViewPresenter` needs to manage its own list of created windows/controllers. I think it's possible to take advantage of it and keep two separate lists for regular and modal windows to simplify the search of the correct window when showing or closing views.

What are your thoughts on that?

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Interesting. Sounds to me the Presenter tracking the Windows will be a better approach as you suggest yourself. This way we don't poke the `NSApplication.SharedApplication.Windows` list.

Contributions for this are much appreciated.
