### ISSUE TITLE
Failed to resolve type MvvmCross.Views.IMvxViewsContainer

### ISSUE THREAD

**Issue by Stecpoint** [MvvmCross/MvvmCross#3978]
## 🐛 Bug Report
Platform android, mvvmcross 7.1.2
When start app i get error:
10-29 10:27:50.108 E/AppCenterCrashes(21401): MvvmCross.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.Views.IMvxViewsContainer

        protected override IMvxNameMapping InitializeViewModelTypeFinder()
        {
            var viewModelByNameLookup = CreateViewModelByNameLookup();
            var viewModelByNameRegistry = CreateViewModelByNameRegistry();

            //FIXME Problem here
            //var viewModelAssemblies = GetViewModelAssemblies();
            //foreach (var assembly in viewModelAssemblies)
            //{
            //    viewModelByNameRegistry.AddAll(assembly);
            //}

            var nameMappingStrategy = CreateViewToViewModelNaming();
            Mvx.IoCProvider.RegisterSingleton(nameMappingStrategy);
            return nameMappingStrategy;
        }

**Comment by Cheesebaron** [comment]
Needs more info.

Which platform(s)?
Does it happen consistently or only sometimes?
What is the stack trace?

**Comment by Stecpoint** [comment]
Problem solved.

**Comment by DenSchiep** [comment]
How did you solve the issue?
