### ISSUE TITLE
Opening new Window from ViewModel

### ISSUE THREAD

**Issue by GWawrzeniecki** [MvvmCross/MvvmCross#3995]
Hello
How can I open a separate window from ViewModel?

**Comment by Cheesebaron** [comment]
Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

**Comment by GWawrzeniecki** [comment]
But that was a question not an issue.

**Comment by GWawrzeniecki** [comment]
> 
> 
> Thanks for opening this issue. Please use and fill out the issue template as it gives us a better overview of what is going on. If you haven't already added reproduction steps or even better a repository with a reproduction sample, please do so. It speeds up debugging issues a lot.

But that was a question not an issue.

**Comment by Cheesebaron** [comment]
Sure, but how do you expect me to answer anything if you don't provide any information? We have issue templates for questions too.

**Comment by GWawrzeniecki** [comment]
> 
> 
> Sure, but how do you expect me to answer anything if you don't provide any information? We have issue templates for questions too.

I want to open a separate window from ViewModel after pressing the button.
I have tried a navigationService but it shows the window in the current view.

**Comment by Cheesebaron** [comment]
Which platform?

**Comment by GWawrzeniecki** [comment]
> 
> 
> Which platform?
> What have you tried?
> Did you get any error? If so what is the error?
> If it crashed what is the stack trace?

Platform is  WPF.
I have tried ` await _navigationService.Navigate<UserViewModel>();`
I didn't get any error.
Nothing was crashed.
All the time I just want to ask, HOW to open a separate window from ViewModel. Because it's MVVM therefore I cant create new instance of view and use showDialog() method. And I'm asking how to do it in MVVM Cross.

**Comment by Cheesebaron** [comment]
All the time I was asking about details 😄 Had you just provided them to begin with everything would have been fine. But if I have to start digging it is simply not worth my time.

**Comment by Cheesebaron** [comment]
If you use the `[MvxWindowPresentationAttribute]` you should be able to open a specific ViewModel as a Window. See https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Wpf/Presenters/Attributes/MvxWindowPresentationAttribute.cs

Usage:
https://github.com/MvvmCross/MvvmCross/blob/develop/Projects/Playground/Playground.Wpf/Views/WindowView.xaml.cs#L16

And from ViewModel:
https://github.com/MvvmCross/MvvmCross/blob/87a545a2f59eafd2179fdde29fcebef68f171656/Projects/Playground/Playground.Core/ViewModels/MainViewModel.cs#L38

**Comment by GWawrzeniecki** [comment]
> 
> 
> If you use the `[MvxWindowPresentationAttribute]` you should be able to open a specific ViewModel as a Window. See https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Wpf/Presenters/Attributes/MvxWindowPresentationAttribute.cs
> 
> Usage:
> https://github.com/MvvmCross/MvvmCross/blob/develop/Projects/Playground/Playground.Wpf/Views/WindowView.xaml.cs#L16
> 
> And from ViewModel:
> 
> https://github.com/MvvmCross/MvvmCross/blob/87a545a2f59eafd2179fdde29fcebef68f171656/Projects/Playground/Playground.Core/ViewModels/MainViewModel.cs#L38
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/3919206?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[MvvmCross/MvvmCross](https://github.com/MvvmCross/MvvmCross)**The .NET MVVM framework for cross-platform solutions, including Xamarin.iOS, Xamarin.Android, Windows and Mac. - MvvmCross/MvvmCross
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/3919206?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[MvvmCross/MvvmCross](https://github.com/MvvmCross/MvvmCross)**The .NET MVVM framework for cross-platform solutions, including Xamarin.iOS, Xamarin.Android, Windows and Mac. - MvvmCross/MvvmCross

Thank you very much! That's working great. But I have once more question. When I close that new window with 
![obraz](https://user-images.githubusercontent.com/23010883/99771312-304d3b80-2b09-11eb-9891-1727840037c3.png) the application is still working. How should I attach closing with NavigationService to the "X" button?

**Comment by GWawrzeniecki** [comment]
Thank you very much it's working great!

**Comment by asaadawey** [comment]
Hello . How to keep focus on the new opened window ?
