### ISSUE TITLE
Restore from Tombstone not behaving as expected

### ISSUE THREAD

**Issue by waldo-jeffers** [MvvmCross/MvvmCross#4004]
## 🐛 Bug Report

The restoring from tombstoning is not working as expected. It seems to only restore the final view in the hierarchy, rather than the whole hierarchy

### Expected behavior
When restoring I would expect all views in the hierarchy/backstack to be restored 

### Reproduction steps
I have a view (A) from which I can navigate to another view (B)

If I tombstone the app when I am viewing view B

When I restore it I see the following getting called

View B - Constructor
View B - Reload from Bundle
View B - Prepare
View B - Initialize

Only when I then close View B do I see the following

View A - Constructor
View A - Reload from Bundle
View A - Prepare
View A - Initialize

I would have expected when restoring to see the lifecycle events for View A followed by the lifecycle events for View B. 
This is because I thought the complete hierarchy is constructed before restore is complete.

### Configuration

**Version:** 6.4.3

**Platform:** 
- [ ] :robot: Android

**Comment by Cheesebaron** [comment]
Your expectation is not in line with what Android actually does. It is not a bug.

**Comment by waldo-jeffers** [comment]
OK. That was my mistake.  But it does leave me confused. How do we pass data back to View(Model) A from View(Model) B after restore. View(Model) A does not seem to exist until View(Model) B was closed, 
So if I want to pass data back to View(Model) A from View(Model) B, how is that possible ?

I was using an injected Model singleton Object, but this will not work in this case.

**Comment by Cheesebaron** [comment]
Use some kind of database, shared resource or service to do that.
