### ISSUE TITLE
WPF setup file for Rio Binding

### ISSUE THREAD

**Issue by Said1996** [MvvmCross/MvvmCross#4007]
I am very confused and I cannot find this anywhere, can you please show me what your App and Setup file in a WPF app to make Rio binding Work?

Cuz all that setup configuration is giving me too much headache and nothing is working with me.

I just need it to be specific to WPF and to be simple (Not including any IoC) and please represent the whole thing (Don't expect me to understand anything in advance).

Thanks in advance...

**Comment by Cheesebaron** [comment]
You don't need anything. Just use `mvx.Bi.nd=""` instead of regular bindings in your XAML files.

**Comment by Said1996** [comment]
I am using this way of binding all the time...

**Here is my App file in WPF:**

` public partial class App : MvxApplication
    {
        protected override void RegisterSetup()
        {
            this.RegisterSetupType<MvxWpfSetup<Core.App>>();
        }
    }`
   
**and here is my App file in Core:**

`public class App : MvxApplication
    {
        public override void Initialize()
        {
            RegisterAppStart<GuestBookViewModel>();
        }
    }`

Got both NuGet packages for Field and Method Binding ... still can't use rio binding ... Binding works perfectly if I use normal properties like:
`private int myVar;

        public int MyProperty
        {
            get { return myVar; }
            set { myVar = value; }
        }`
but this one doesn't work:

`public INC<string> Name = new NC<string>("NotWorking");`

**Comment by Cheesebaron** [comment]
Ahh this.

You need to add and initialize the FieldBinding plugin: https://github.com/MvvmCross/MvvmCross/tree/develop/MvvmCross.Plugins/FieldBinding

**Comment by Said1996** [comment]
I am very sorry, I am a bit new to MVVM in general and I almost did read all your Documentation on your Website... 

I think by add you mean adding the NuGet package FieldBinding which I did.
But about initializing it ... could you tell me what file, where this init, should occur and what is the exact code, or link me to a place in your website I may have missed...

Thanks again
