### ISSUE TITLE
Why is MvxFragmentPagerAdapter deleted in version 7

### ISSUE THREAD

**Issue by lbhnrg2021** [MvvmCross/MvvmCross#4009]
## 🚀 Add MvxFragmentPagerAdapter, compatible with the old version

AndroidX.Fragment.App.FragmentPagerAdapter cannot be inherited?
Now I want to upgrade mvvmcross 7, but MvxFragmentPagerAdapter does not exist

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms
- [ ] :🌍: Blazor

**Comment by Cheesebaron** [comment]
Use MvxCachingFragmentStatePagerAdapter or MvxCachingFragmentPagerAdapter instead
