### ISSUE TITLE
[Android] running latest mvvmcross on android 7.1

### ISSUE THREAD

**Issue by neyugnluan** [MvvmCross/MvvmCross#4014]
## 💬 Questions and Help

How can i run mvvmcross on android device 7.1? 

Now have a device android running android 7.1
Develop an app using tab view using xamarin android
The tab can create but cant start and crash by runtime. Because of casting mvxfragment v4 abd v7.

Is there anyone had experience work with this version.

XAMARIN.ANDROID target framework android 7.1
MvvmCross 5.6

**Comment by Cheesebaron** [comment]
1. at least provide the crash message and stack trace
2. don't mix fragments and activities that come from different libraries. Sounds like you are mixing something that uses Android.Support.V4 fragments with something that expects a Android.Support.V7 fragment
3. update to latest MvvmCross to ensure compatibility with latest Android versions
