### ISSUE TITLE
TipCalc tutorial on website

### ISSUE THREAD

**Issue by saamerm** [MvvmCross/MvvmCross#4020]
## 🔙 Regression

When you follow the tutorial on the MVVMCross website for TipCalc, the TipView (ViewController) gives you a build error on this line:
The tutorial says to use:
            `var set = CreateBindingSet();`
but it should be
            `var set = this.CreateBindingSet<TipView, TipViewModel>();`
in order to get rid of the build error. This is based on the TipCalc sample that has been updated in the [MvvmCross samples](https://github.com/MvvmCross/MvvmCross-Samples/blob/master/TipCalc/TipCalc.iOS/Views/TipView.cs).

Here's [the file](https://github.com/MvvmCross/MvvmCross/blob/f2ab8fd8c56bf29575ce967db862e2918bd8304d/docs/_documentation/tutorials/tipcalc/a-xamarinios-ui-project.md) that needs to be changed. 

### Old (and correct) behavior

The app used to build

### Current behavior

The app doesn't build anymore.

### Reproduction steps

Just follow the web tutorial 

### Configuration

**Version:** : 6.4.2

**Platform:** 
- [x] :iphone: iOS

**Comment by Cheesebaron** [comment]
If you are using MvvmCross 7.x it should be fine with the generic parameters.

**Comment by saamerm** [comment]
@Cheesebaron It fails on 6.4.2

**Comment by saamerm** [comment]
Let me check

**Comment by saamerm** [comment]
Ah yes it works! Should we close this?
