### ISSUE TITLE
Using MvxMessenger with Blazor null exception

### ISSUE THREAD

**Issue by duskotenkov** [MvvmCross/MvvmCross#4031]
## 🐛 Bug Report

Object Null error on Subrcribe metode from MvxMessenger when using Ninject for DependencyInjection.

   at MvvmCross.Plugin.Messenger.MvxPluginLog.get_Instance()
   at MvvmCross.Plugin.Messenger.MvxMessengerHub.SubscribeInternal[TMessage](Action`1 deliveryAction, IMvxActionRunner actionRunner, MvxReference reference, String tag)
   at MvvmCross.Plugin.Messenger.MvxMessengerHub.Subscribe[TMessage](Action`1 deliveryAction, MvxReference reference, String tag)
   at Mdt.Client.Web.ViewModel.MainLayoutViewModel..ctor() in C:\MES\Equipment\Mdt.CustomFwClient\Mdt.Client.Web\ViewModel\MainLayoutViewModel.cs:line 29
   at Mdt.Client.Web.Shared.MainLayout..ctor() in C:\MES\Equipment\Mdt.CustomFwClient\Mdt.Client.Web\Shared\MainLayout.razor:line 8

The type initializer for 'MvvmCross.Plugin.Messenger.MvxPluginLog' threw an exception.

### Reproduction steps
Ninject Module (.Net standard 2.0)
 **public class CoreInjectionModule : NinjectModule
    {
        public override void Load()
        {
            Bind<IMvxMessenger>().To<MvxMessengerHub>().InSingletonScope();
        }
    }**

ViewModel in Blazor .Net 5.0
**private IMvxMessenger _messenger;
        private readonly MvxSubscriptionToken _token;
      
        public MainLayoutViewModel()
        {
            _messenger = Program.Kernel.Get<IMvxMessenger>();
           _token = _messenger.Subscribe<MvxMessage>(OnUpdateMessage);
        }**

**Version:** MvvmCross.Plugin.Messenger 7.1.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms
- [x] :earth_americas: Blazor .Net Core

**Comment by Cheesebaron** [comment]
Why do you believe this is a bug?

In normal circumstances if you would use it with the MvvmCross IoC container you would also have access to IMvxLog inside of it. It is failing because it cannot resolve it.

See: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Plugins/Messenger/MvxPluginLog.cs#L11

**Comment by duskotenkov** [comment]
> Why do you believe this is a bug?
> 
> In normal circumstances if you would use it with the MvvmCross IoC container you would also have access to IMvxLog inside of it. It is failing because it cannot resolve it.
> 
> See: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Plugins/Messenger/MvxPluginLog.cs#L11
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/3919206?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[MvvmCross/MvvmCross](https://github.com/MvvmCross/MvvmCross)**The .NET MVVM framework for cross-platform solutions, including Xamarin.iOS, Xamarin.Android, Windows and Mac. - MvvmCross/MvvmCross

Not realy a bug if using MvvmCross IoC, but how we can resolve it using external IoC like Ninject for ex. If not it we'll be too heavy to change all the code? Any possible solution?

**Comment by Cheesebaron** [comment]
For this specific case you just need to ensure that you can resolve IMvxLogProvider.
