### ISSUE TITLE
Xamarin.Android Cannot disable a button by binding "Enabled" which has binding "Click"

### ISSUE THREAD

**Issue by hungnguyenepiserver** [MvvmCross/MvvmCross#4046]
## 🐛 Bug Report
Xamarin.Android Cannot disable a button by binding "Enabled" which has binding "Click"

### Expected behavior
Button can be disabled by binding "Enabled" in .axml code, not depends or relate to "Click" event of "Click" Binding

### Reproduction steps
1. Binding Click command and Enabled state variable to a button
2. Click command has logic to change "Enabled" state
3. Run app
4. Click to the button

### Configuration

**Version:** 7.x

**Platform:** 
- Xamarin.Android

Some code:

private async Task ClickEvent()
        {
            this.EnableBtn = !this.EnableBtn;
        }
        
        private bool enableBtn;
        public bool EnableBtn
        {
            get => enableBtn;
            set
            {
                enableBtn = value;
                RaisePropertyChanged(() => EnableBtn);
            }
        }
        
        private MvxAsyncCommand clickCommand;
        public MvxAsyncCommand ClickCommand
        {
            get
            {
                this.clickCommand = this.clickCommand ?? new MvxAsyncCommand(this.ClickEvent);
                return this.clickCommand;
            }
        }

<Button
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
        android:text="test"
        local:MvxBind="Click ClickCommand; Enabled EnableBtn"/>

**Comment by elstringo** [comment]
Are you aware you can get the desired behaviour by using a 'CanExecute' Func/method for your MvxAsyncCommand? 
So something like this...
`private MvxAsyncCommand clickCommand;
public MvxAsyncCommand ClickCommand
{
    get
    {
        clickCommand = clickCommand ?? new MvxAsyncCommand(ClickCommandExecute, ClickCommandCanExecute);
        return clickCommand;
    }
}

private async Task ClickCommandExecute()
{
    EnableButton = !EnableButton;
    await Task.CompletedTask;
}

private bool ClickCommandCanExecute()
{
    return EnableButton;
}

private bool enableBtn;
public bool EnableBtn
{
    get => enableBtn;
    set
    {
        if (SetProperty(ref enableBtn, value))
        {
            ClickCommand.RaiseCanExecuteChanged();
        }
    }
}
`

**Comment by elstringo** [comment]
Are you aware you can get the desired behaviour by using a 'CanExecute' Func/method for your MvxAsyncCommand? 
So something like this...
```

private MvxAsyncCommand clickCommand;
public MvxAsyncCommand ClickCommand
{
    get
    {
        clickCommand = clickCommand ?? new MvxAsyncCommand(ClickCommandExecute, ClickCommandCanExecute);
        return clickCommand;
    }
}

private async Task ClickCommandExecute()
{
    EnableButton = !EnableButton;
    await Task.CompletedTask;
}

private bool ClickCommandCanExecute()
{
    return EnableButton;
}

private bool enableBtn;
public bool EnableBtn
{
    get => enableBtn;
    set
    {
        if (SetProperty(ref enableBtn, value))
        {
            ClickCommand.RaiseCanExecuteChanged();
        }
    }
}

```

**Comment by hungnguyenepiserver** [comment]
Dear @Cheesebaron could you answer me?
Is it a bug from MVVMCross Android

**Comment by hungnguyenepiserver** [comment]
> Are you aware you can get the desired behaviour by using a 'CanExecute' Func/method for your MvxAsyncCommand, and not binding to the Enabled property?
> So something like this...
> 
> ```
> 
> private MvxAsyncCommand clickCommand;
> public MvxAsyncCommand ClickCommand
> {
>     get
>     {
>         clickCommand = clickCommand ?? new MvxAsyncCommand(ClickCommandExecute, ClickCommandCanExecute);
>         return clickCommand;
>     }
> }
> 
> private async Task ClickCommandExecute()
> {
>     EnableButton = !EnableButton;
>     await Task.CompletedTask;
> }
> 
> private bool ClickCommandCanExecute()
> {
>     return EnableButton;
> }
> 
> private bool enableBtn;
> public bool EnableBtn
> {
>     get => enableBtn;
>     set
>     {
>         if (SetProperty(ref enableBtn, value))
>         {
>             ClickCommand.RaiseCanExecuteChanged();
>         }
>     }
> }
> ```

Thanks for your idea. @elstringo 
But I'm considering using Enable because of I also want the button change the color following enable change.

**Comment by o0k4m1** [comment]
I have resolved this by switching places of bind items:

            app:MvxBind="Click AddNewItemCommand;Enabled IsValid"
            
So this might be a temporary solution.
