### ISSUE TITLE
CrossUI.Touch.Dialog.Elements.Section does not respect Visibility

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#407]
`Section`'s Visible property is entirely ignored, whether you set it manually or bind it to a `bool`. The expected result would be that when it is set to `false` the `Section` is hidden and when set to `true` the `Section` is visible. Neither does it help using `Root.Reload()` on that `Section`.

**Comment by kjeremy** [comment]
CrossUI has been removed as of 41f191574d11e6e1a664336e7108cfa1e59a4383
