### ISSUE TITLE
What needs to be done to get MVVM Cross working in an iOS Share Extension?

### ISSUE THREAD

**Issue by winstonpang** [MvvmCross/MvvmCross#4088]
There's another topic about this

https://github.com/MvvmCross/MvvmCross/issues/2426

I've tried following it, seems to semi-work, but something tells me it's not the right way, since it requires starting MVVMCross through the MvxSingleton. 

Are there any guidelines or suggestions on being able to get this to work at all?

**Comment by Cheesebaron** [comment]
It is not a covered use case, you are on your own.
