### ISSUE TITLE
MvxFormsIosViewPresenter(AppDelegate, Window, FormsApp) throws InvalidCastException

### ISSUE THREAD

**Issue by mingxli** [MvvmCross/MvvmCross#4097]
## 🐛 Bug Report

Create a new MvxFormsIosViewPresenter() would throw a InvalidCastException.

### Expected behavior
A MvxFormsIosViewPresenter is created without exception.

### Reproduction steps
Create a new MvxFormsIosViewPresenter() object. A sample project is available [here](https://github.com/mingxli/MvxFormsIosViewPresenterIssue).

### Configuration
Mac OS X 10.15.7
Visual Studio for Mac 8.8.8 (build 12)
Xamarin.Mac 7.4.0.4
Xamarin.iOS 14.10.0.4
MvvmCross 7.1.2
MvvmCross.Forms 7.1.2
Xamarin.Forms 4.8.0.1821

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Why do you even have the type cast? On this line:

    var presenter = new MvxFormsIosViewPresenter((MvxApplicationDelegate)ApplicationDelegate, Window, FormsApplication);

`MvxFormsIosViewPresenter` expects a `UIApplicationDelegate`, so just passing in `ApplicationDelegate` without the cast solves your issue.

Did you just copy/paste from somewhere?

**Comment by mingxli** [comment]
Thanks Cheesebaron!
