### ISSUE TITLE
Add MvxViewModel.OnTrimMemory.

### ISSUE THREAD

**Issue by ronag** [MvvmCross/MvvmCross#410]
Android Api Level 14 has a function called "Activity.OnTrimMemory" (http://developer.android.com/reference/android/content/ComponentCallbacks2.html) which is called when the android device starts running out of memory.

It would be nice if the callback was propagated down to the ViewModel so that we can perform memory management on a ViewModel basis.

**Comment by sabrinemoumni** [comment]
onTrimMemory is used only for API level 14 ,
 I need to detect when app is backgrounded for api level <14
