### ISSUE TITLE
Mvx.IoCProvider.Resolve can't resolve type when internet is on

### ISSUE THREAD

**Issue by SerlokPK** [MvvmCross/MvvmCross#4124]
## 🔙 Regression

When internet is on on my android phone, I get `Failed to resolve type Telexis.TSU.MonitoringService.IMonitoringReportingService'`, and when it's off, everything is fine. After some time even with internet on, it starts working and I don't have this exception anymore.

### Old (and correct) behavior
Type was resolved.

### Current behavior
Exception that type can't be resolved

### Reproduction steps
Class is inheriting `Worker` class from `AndroidX.Work` and I can't use DI inside constructor, so inside `DoWork` method I am doing this `_monitoringReportingService = _monitoringReportingService ?? Mvx.IoCProvider.Resolve<IMonitoringReportingService>();` and get exception.

### Configuration

**Version:** 6.x
6.3.1

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Uhm. What? The IoC container knows nothing about the "internet" state. Not sure how `AndroidX.Work` works. However, if it is in a different process, that might not work for you.

Can you please provide a minimal reproducible sample?

**Comment by tbalcom** [comment]
This can be avoided by calling `MvxAndroidSetupSingleton.EnsureSingletonAvailable(Context).EnsureInitialized()` at the beginning of the `Worker.DoWork` override. Android can restart the process and MvvmCross doesn't (can't?) hook into that, so it's up to us to reinitialize MvvmCross in components that aren't tied to an activity (Service, AndroidX.Worker, etc.).

**Comment by SerlokPK** [comment]
@tbalcom You are right, I was testing this in multiple scenarios and it is working, right now I don't get any exception
