### ISSUE TITLE
Master details page keep resetting the navigation when the orientation changes

### ISSUE THREAD

**Issue by aahmyu** [MvvmCross/MvvmCross#4129]
Hello,

So I followed a few examples on how to create a master details page with mvvm cross and all of them do this in the view model

`public override async void ViewAppearing()
{
            base.ViewAppearing();

            await _navigationService.Navigate<SideNavViewModel>();
            await _navigationService.Navigate<HomeViewModel>();
}`

The issue is if you change the page and rotate the device this will be called again and navigate back to HomeViewModel.

I tried creating `_isFirst` property and setting it to false after the property also resets to true after the orientation changes.

Am I missing something here?

Edit: So I just tried again with an empty project from the MvxScaffolding and added a  label with a text and a button that changes the text, after clicking the button and changing the orientation the label text resets. Is this intended?

Edit: Looks like it is navigating to a new instance of the viewmodel on each orientation change.

BTW using xamarin forms.

Regards

**Comment by Cheesebaron** [comment]
What platform? Please use our issue templates when creating issues: https://github.com/MvvmCross/MvvmCross/issues/new/choose

**Comment by aahmyu** [comment]
The issue happened for me on Android, no idea about other platforms. But yeah just use the template to create a new project and run it:

![image](https://user-images.githubusercontent.com/5700557/111656871-35966a80-880b-11eb-87c5-4d13b1d7d71b.png)

![image](https://user-images.githubusercontent.com/5700557/111656907-3c24e200-880b-11eb-8845-ec887c8b654f.png)

As you can see in the second image it did navigation.

The expected behavior is to stay on the same page.

**Comment by aahmyu** [comment]
Figured it out it has to do with with adding some missing properties in the main activity.

**Comment by isax5** [comment]
@aaerox Can you explain how this problem is solved?
I'm having similar issues

**Comment by Cheesebaron** [comment]
@isax5 you need to listen to configuration changes on Android to prevent the Activity to get recreated. Study the Android lifecycle.
