### ISSUE TITLE
Calling await from an MvvmCross MvxViewModel.Initialize() never returns

### ISSUE THREAD

**Issue by ChristopherPope** [MvvmCross/MvvmCross#4146]
## 🐛 Bug Report
Calling await from MvvmCross MvxViewModel.Initialize() never returns.

I first experienced this when calling out to my REST API in the Initialize() method but I've simplified it and can reproduce it by simply calling await on an async method. The method never returns and no UI is rendered on the emulator, I only see a white screen.

The call to Work() will never return and all I see in the emulator is a blank white screen.

I do know that if I call Work() from a button command after the screen is rendered, it will work. Also, this behavior only happens on the first view model. If I navigate to a second or subsequent view model, I can await an async method from within their Initialize() methods and it returns.

### Expected behavior
The awaited method will return and MvxViewModel.Initialize() continues.

### Reproduction steps
This can be reproduced easily with the TipCalc (https://github.com/MvvmCross/MvvmCross-Samples) sample app. If I add this method to the TipViewModel:

```cs
private async Task Work()
{
    await Task.Delay(5000);
    SubTotal = 500;
    Recalcuate();
}
```

And then add the await call to the bottom of TipViewModel.Initialize():
```cs
public override async Task Initialize()
{
    await base.Initialize();
    SubTotal = 100;
    Generosity = 10;
    Recalcuate();

    await Work();
}
```

### Configuration
**MvvmCross Version:** 7.1.2

**Android Emulator:** Pixel 3 (Android 10 - API 29)
(Note that I have not tried this on an actual android phone, just the emulator)

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
This only happens if you do it in the AppStart ViewModel. In other ViewModels it should work. This is a known issue and already reported.

https://github.com/MvvmCross/MvvmCross/issues/3618
https://github.com/MvvmCross/MvvmCross/issues/3209
https://github.com/MvvmCross/MvvmCross/issues/3114
