### ISSUE TITLE
iOS back button text disappears

### ISSUE THREAD

**Issue by markuspalme** [MvvmCross/MvvmCross#4160]
In a MvvmCross (latest stable) project with iOS the back button *sometimes* behaves likes this. When clicking it, the title text disappears and I have to click on the arrow on the left to go back:

![nav1](https://user-images.githubusercontent.com/1481801/116247371-12949a00-a76b-11eb-9909-1f0095f52498.gif)

I have also observed that holding down on the button (without releasing the mouse/finger) consistently makes the text dissappear:

![nav2](https://user-images.githubusercontent.com/1481801/116247388-16282100-a76b-11eb-86eb-06e997ccbe63.gif)

I'm not sure whether this is a MvvmCross problem or an iOS issue. Has anyone experienced someting similar?

This is a `MvxNavigationController` inside a `MvxTabController`.

**Comment by Cheesebaron** [comment]
I haven't seen this. Is this Xamarin.Forms?

**Comment by markuspalme** [comment]
Xamarin.iOS without forms.

**Comment by Cheesebaron** [comment]
Is this a custom back button, or the one that iOS adds when you navigate to a child?

**Comment by markuspalme** [comment]
It's the default button, no changes whatsoever.

**Comment by Cheesebaron** [comment]
I haven't seen it before. If you find repro steps, I'd be happy to help fix it.

**Comment by markuspalme** [comment]
I think I have found the root cause. I was setting the font attributes in a theme on the `UIBarButtonItem.Appearance` proxy by creating new `UITextAttributes` :

```
var proxyUIBarButton = UIBarButtonItem.Appearance;
proxyUIBarButton.SetTitleTextAttributes(new UITextAttributes { Font = UIFont.FromName(RegularFontName, 20), TextColor = AtxBlue }, UIControlState.Normal);
```

It works when basing the attributes on the default attributes:

```
var attr = proxyUIBarButton.GetTitleTextAttributes(UIControlState.Application);
attr.Font = UIFont.FromName(RegularFontName, 20);
attr.TextColor = AtxBlue;
proxyUIBarButton.SetTitleTextAttributes(attr, UIControlState.Normal);
```

**Comment by Cheesebaron** [comment]
Good to know you found the issue 👍
