### ISSUE TITLE
Undocumented MvxApplication<TMvxUapSetup, TApplication> changes

### ISSUE THREAD

**Issue by alexkivikoski** [MvvmCross/MvvmCross#4199]
## 🐛 Bug Report

After updating from 7.1.2 to 8.1, the way of providing a setup for UWP projects has changed and does not build anymore.

My UWP App class, as demonstrated by the UWP Playground example:

`public abstract class UWPApp : MvxApplication<MvxWindowsSetup<Shared.App>, Shared.App>
    {
    }`

After updating I get the following compile error:

> 'MvxWindowsSetup<App>' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TMvxUapSetup' in the generic type or method 'MvxApplication<TMvxUapSetup, TApplication>'

Please update the documentation to inform how to migrate from 7.x to 8.x.

### Expected behavior
The app compiles

### Reproduction steps
Create an empty UWP application with the setup as demonstrated in the Playground example

### Configuration
Visual Studio 2019

**Version:** 8.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Take a look at https://github.com/MvvmCross/MvvmCross-Samples/pull/159/files there is an upgrade example.

I won't accept this as a bug report. But rather a lack of documentation.

**Comment by Cheesebaron** [comment]
Will track all of these issues in #4201

**Comment by Cheesebaron** [comment]
https://www.mvvmcross.com/documentation/upgrading/upgrade-to-mvvmcross-80
