### ISSUE TITLE
Inconsistent 'TResult' type parameter constraints

### ISSUE THREAD

**Issue by evgenyvalavin** [MvvmCross/MvvmCross#4206]
### Current behavior
Constraint of 'TResult' type parameter in MvxViewModel is 'notnull' (any non-nullable type, so may be struct or class).
Constraint of 'TResult' type parameter in IMvxNavigationService.Close() is 'class' (only reference types allowed, so not structs).

### Expected behavior
'TResult' type parameter in IMvxNavigationService.Close() and 'TResult' type parameter in MvxViewModel have no constraints at all.

**Version:** 8.0.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
I will try to see if I can consolidate this soon. I think I ran into some issues using `notnull` some places instead of `class` which lead to these inconsistencies. However, this should be revisited to fix this.

Thank you for reporting this.

**Comment by Cheesebaron** [comment]
One issue here is that we are returning a generic TResult. In case of something unexpected happening, we are currently returning the `default` value (which can be null if a reference type).

So to fix this we need a breaking change to change `TResult` to something that wraps the result and returns a "Not Set" value or something like that, similar to `Option<T>` from [language extensions](https://github.com/louthy/language-ext#option).

**Comment by evgenyvalavin** [comment]
Hmm... I started wondering.
Why do we even need constraints here? Why do we need to constraint the returning type?

**Comment by Cheesebaron** [comment]
If we don't apply either class or notnull constraints, we cannot check for nullability

**Comment by evgenyvalavin** [comment]
Why can't we? 
MvvmCross assembly only operates with generic types. Any nullability check looks like this: "if (TResult is null)...". TResult, for instance, may be int, int?, string, string?, and so on. "Is" operator will handle all possible cases for us:
- Int - will be never null.
- Int? - might be null.
- string or string? - might be null.

Am I missing something?

**Comment by Cheesebaron** [comment]
Not quite certain I understand your proposal.

In order to mark something can return `null` it needs to be constrained as `class`, that is just how the type system works (this might change in future language versions, but it is like this in C#9).

**Comment by evgenyvalavin** [comment]
What I'm trying to say, is there's no reason to have any TResult type parameter constraints. We're still able to check for nullability (if we need to) without either class or notnull constraints.

P.S. I've updated the expected behavior of the issue; I think that's why you didn't catch my thought right away. Sorry if I confused you.
