### ISSUE TITLE
ResxLocalization not working after update to mvvmcross 8.0.1

### ISSUE THREAD

**Issue by Vintar** [MvvmCross/MvvmCross#4214]
## 🐛 Bug Report

**When I call:**
var view = this.BindingInflate(FragmentId, null);

**I got an exception:**
**MvvmCross.Exceptions.MvxException:** 'Missing text provider - please initialize IoC with a suitable IMvxTextProvider'

On Mvvmcross 7.1.2 works correctly

**Version:** 8.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by tbalcom** [comment]
Looks like this was fixed in #4209.
