### ISSUE TITLE
wpf AppStart - first view not shown

### ISSUE THREAD

**Issue by tuke307** [MvvmCross/MvvmCross#4221]
## 🐛 Bug Report

since 8.x the wpfviews are not shown when viewmodels and views are in the same project.

### Expected behavior
same as 7.x - works perfectly in this version.

### Reproduction steps
use my #4220 PR for that. 
create a viewmodel in the Playground.Wpf.UI project: for example inherit the RootViewModel from core like that;
```c#
namespace Playground.Wpf.UI.ViewModels
{
    public class RootViewModel : Playground.Core.ViewModels.RootViewModel
    {
        public RootViewModel(ILoggerFactory logProvider, IMvxNavigationService navigationService, IMvxViewModelLoader mvxViewModelLoader)
               : base(logProvider, navigationService, mvxViewModelLoader)
        { }
    }
}
```
use the new viewmodel in the view;
```c#
...
[MvxViewFor(typeof(Playground.Wpf.UI.ViewModels.RootViewModel))]
...
```

uncomment the `RegisterAppStart<RootViewModel>();` in the Playground.Core.App

create a custom App that inherits the core.app and use a custom RegisterAppStart;
```c#
namespace Playground.Wpf.UI
{
    public class App : Playground.Core.App
    {
        public override void Initialize()
        {
            RegisterAppStart<Playground.Wpf.UI.ViewModels.RootViewModel>();
            base.Initialize();
        }
    }
}
```

You can use my fork project to reproduce this bug.

### Configuration

**Version:** 8.0.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by eriove** [comment]
Is there a workaround for this other than moving them into different projects?
