### ISSUE TITLE
Error upgrading Xamarin.Forma

### ISSUE THREAD

**Issue by Janek91** [MvvmCross/MvvmCross#4225]
## 🐛 Bug Report

Latest version https://www.nuget.org/packages/Xamarin.Forms/5.0.0.2083 has dependency to Xamarin.Google.Android.Material set for versions (>= 1.2.1.1 && < 1.3.0). It conflicts with MvvmCross dependency Xamarin.Google.Android.Material (>= 1.3.0.1). Therefore we're unable to upgrade Xamarin.Forms package.

### Expected behavior

It should be able to upgrade Xamarin.Forms NuGet package.

### Reproduction steps

Install MvvmCross 8.0.1 and Xamarin.Forms 5.0.0.2012 packages.
Try to upgrade Xamarin.Forms package.

### Configuration

**Version:** 8.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
That is a new thing that Xamarin.Forms is specifying the upper boundary. Complain to the Xamarin.Forms team.

We specify:
- Xamarin.Forms (>= 5.0.0.1931)
