### ISSUE TITLE
IMvxLog does not exists in MvvmCross 8.x

### ISSUE THREAD

**Issue by Sonic3R** [MvvmCross/MvvmCross#4234]
## 🔙 Regression

In previously versions like 6 and 7, the IMvxLog does exist anymore in `MvvmCross.Logging` namespace. After upgrading to 8.0.2, it seems to be removed and I got a lot of errors.

### Old (and correct) behavior
If it is removed intentionally, please add alternative to it in documentation

### Reproduction steps
Update from 6.x or 7.x to 8.0.2 and will got error to any reference to IMvxLog
### Configuration

**Version:** 8.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by ondrejsv** [comment]
It was indeed removed as a breaking change and replaced in favor of the standard `Microsoft.Logging.Abstractions`, see the updated doc: https://www.mvvmcross.com/documentation/fundamentals/logging-new.
