### ISSUE TITLE
Separate out Interactivity dependency on WIndowsPhone assembly

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#425]
The System.Interactivity story from MS is 'complicated'

But it would be good if our MvxEventToCommand classes were in a platform independent library... or maybe we can just set specific version to false? Or maybe something else?

**Comment by martijn00** [comment]
@slodge Isn't this done, as it is in the latest versions?

**Comment by slodge** [comment]
We've not separated it into a separate assembly... but we have updated to the latest version... so OK for now. 

Thanks for closing :+1:
