### ISSUE TITLE
NuGet dependency version issue for Microsoft.Extensions.Logging.Abstractions

### ISSUE THREAD

**Issue by JadeBanks** [MvvmCross/MvvmCross#4252]
## 🐛 Bug Report

Looking at this
https://github.com/MvvmCross/MvvmCross/blob/92621bdb48dc3f3d0c0e1a0630568d662d678e63/Directory.Packages.props#L42-L43

In MvvmCross `Microsoft.Extensions.Logging.Abstractions` is set to 5.0.0 and `Serilog.Extensions.Logging` is set to 3.0.1

However the dependency graph of `Serilog.Extensions.Logging` is
[Serilog.Extensions.Logging](https://www.nuget.org/packages/Serilog.Extensions.Logging/3.0.1) ->
[Microsoft.Extensions.Logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging/2.0.0) ->
Microsoft.Extensions.Logging.Abstractions (>= 2.0.0)

This seems to be causing issues

Get the following error when trying to build
```
Can't resolve the reference 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope Microsoft.Extensions.Logging.Abstractions.Internal.NullScope::get_Instance()', referenced from the method 'System.IDisposable Microsoft.Extensions.Logging.Logger::BeginScope(TState)' in 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

Locally (Windows) it works for iPhoneSimulator and Android but not on iPhone
On build server (Mac) it fails for both iPhone and Android

I've managed to work around by adding specifically versioned references to the intermediate dependencies but I get build warnings and have concerns that I might get runtime errors.

Could the `Microsoft.Extensions.Logging.Abstractions` dependency be set to `>=2.0.0` like `Serilog.Extensions.Logging` or are later features required?

### Expected behavior
Project builds

### Reproduction steps
1. Open [TipCalc](https://github.com/MvvmCross/MvvmCross-Samples/tree/master/TipCalc)
1. Select `TipCalc.iOS` project
1. Set platform to `iPhone`
1. Build

### Configuration

**Version:** 8.x

**Platform:** 
- [ X] :iphone: iOS
- [ ] :robot: Android

**Comment by Cheesebaron** [comment]
Still waiting for author of Serilog.Extensions.Logging to review and accept my PR here: https://github.com/serilog/serilog-extensions-logging/pull/191 That should solve the issue here.

**Comment by JadeBanks** [comment]
Thanks Cheesebaron

**Comment by timahrentlov** [comment]
Any recommendations on how fast to spin up a new 8.02 solution from the native template, and try things out? Currently it fails due to this issue.

**Comment by tbalcom** [comment]
You can temporarily work around the issue by directly referencing Microsoft.Extensions.Logging 5.0.0. That's working for me on Android.

**Comment by Cheesebaron** [comment]
Please open a new issue if this persists in 9.x
