### ISSUE TITLE
I get message in log: "Shared element transition requires Android v21+." on v29 API

### ISSUE THREAD

**Issue by hubocan** [MvvmCross/MvvmCross#4260]
## 🐛 Bug Report

There is definitely some bug as I get "Shared element transition requires Android v21+." warning message in the log on device with Android API 29.

### Expected behavior
No warning message.

### Reproduction steps
Just run the app.

### Configuration

**Version:** 8.0.2

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
The check is:

```csharp
if (CurrentActivity.IsActivityAlive() &&
    CurrentActivity is IMvxAndroidSharedElements sharedElementsActivity)
{
```

Does your activity implement `IMvxAndroidSharedElements`? Is it alive?

Your issue is very scarce with information. Tempted to just close it....

**Comment by hubocan** [comment]
Nope, I don't know what it should be for... I've got casual MvxActivity with MvxActivityPresentation and ViewPager. I didn't find reference to IMvxAndroidSharedElements anywhere in my code.

But, when I search the MVVMCross code for that string ("Shared element transition requires Android v21+."), I have found that previously there was a check "if (Build.VERSION.SdkInt >= BuildVersionCodes.Lollipop)" so this warning did not appear on v21+...

**Comment by Cheesebaron** [comment]
You can safely ignore it.

**Comment by hubocan** [comment]
OK, but if there is nothing to do about it, then it should not appear in the log at all.
