### ISSUE TITLE
Throw ThreadCanceledException when using IMvxNavigationService.Navigate in IMvxNavigationService.Navigate<..., TResult>()

### ISSUE THREAD

**Issue by level120** [MvvmCross/MvvmCross#4261]
### Expected behavior

When open page using IMvxNavigationService.Navigate() in IMvxNavigationService.Navigate<..., TResult>(),
throw ThreadCanceledException. -> In this line, https://github.com/level120/MvvmCrossNavigationTest/blob/main/MvvmCrossNavigationTest/MvvmCrossNavigationTest/RecursionPageViewModel.cs#L34

### Reproduction steps

Please look at this repository, https://github.com/level120/MvvmCrossNavigationTest

After building, click "First Navigation" and "Recursion Navigation" button.

### Configuration

**Version:** 8.0.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
I highly recommend not using this. It is broken by design.

**Comment by Cheesebaron** [comment]
Duplicate of #4262
