### ISSUE TITLE
MvvmCross 8.X.X depends on AndroidX libs incompatible with latest Xamarin Forms 5 SR (5.0.0.2083)

### ISSUE THREAD

**Issue by mgoodfellow** [MvvmCross/MvvmCross#4266]
I know this has been reported in other closed issues:

https://github.com/MvvmCross/MvvmCross/issues/4228
https://github.com/MvvmCross/MvvmCross/issues/4225

But this upper bound has been imposed on the latest Xamarin Forms 5 SR (5.0.0.2083) due to the issues with the AndroidX Fragments 1.3.X which causes a rather severe crash - it seems that this upper bound restriction was their solution to the problem:

https://github.com/xamarin/Xamarin.Forms/issues/14193

Also reported here: https://github.com/xamarin/Xamarin.Forms/issues/13895 - but the above issue describes it better.

I realise that there isn't any easy solution for these issues, but I think it needs to be tracked for visibility

I'm assuming we can't easily downgrade the dependencies of MvvmCross to support the upper library boundaries of Xamarin Forms?

**Comment by Dolphinsimon** [comment]
Trying to update Xamarin.Forms to SR5
