### ISSUE TITLE
Lower bound of Xamarin.Google.Android.Material in 8.0.2 makes unable to compile Xamarin.Forms app

### ISSUE THREAD

**Issue by Janek91** [MvvmCross/MvvmCross#4268]
## 🐛 Bug Report

MvvmCross in version 8.0.2 requires Xamarin.Google.Android.Material to be at least 1.4.0 but this version has known bug https://github.com/xamarin/Xamarin.Forms/issues/14492 preventing app compilation. Is it really necessary to be at least 1.4.0 or can it be downgraded to 1.3.0.1 - which is the latest working version

### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Dolphinsimon** [comment]
Update Xamarin.Forms to [SR5](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr5) will fix this

**Comment by Janek91** [comment]
And what version of Xamarin.Forms is that?

**Comment by Dolphinsimon** [comment]
5.0.0.2125

**Comment by Janek91** [comment]
That solves the problem
