### ISSUE TITLE
Enable multi-dimensional array source binding

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#427]
Following up from http://stackoverflow.com/questions/18776323/how-to-bind-an-array-in-mvvmcross

Currently we don't support multi-dimensional arrays because Xaml doesn't (see Indexer in http://msdn.microsoft.com/en-us/library/cc645024%28VS.95%29.aspx)

As far as I can see there's no reason why we couldn't support this - we'd just need a way of parsing and passing the array of indexers for https://github.com/slodge/MvvmCross/blob/v3/Cirrious/Cirrious.MvvmCross.Binding/Bindings/Source/Chained/MvxIndexerChainedSourceBinding.cs#L29

Putting this in as a low-priority feature request for now...

**Comment by nickrandolph** [comment]
If this is of interest to anyone, please add a comment???

**Comment by nickrandolph** [comment]
No feedback, so closing this issue (@slodge I assume you don't have any input?)
