### ISSUE TITLE
Upgrade to 8.0.2 causes "You cannot create more than one instance of MvxSingleton" exception on startup of iOS instance

### ISSUE THREAD

**Issue by netdevjamie** [MvvmCross/MvvmCross#4327]
## 🐛 Bug Report

Upgrade to 8.0.2 causes "You cannot create more than one instance of MvxSingleton" exception on startup of iOS instance

### Expected behavior
App starts up normally

### Reproduction steps
Build app, splash screen displays, exception thrown

**Version:** 8.0.2

**Platform:** 
- [x] :monkey: Xamarin.Forms

Stack Trace:
```	StackTrace	"  at MvvmCross.Base.MvxSingleton`1[TInterface]..ctor () [0x00012] in /_/MvvmCross/Base/MvxSingleton.cs:59 \n  at MvvmCross.Base.MvxMainThreadDispatcher..ctor () <0x10b921660 + 0x0004a> in <2ba9530bd5854b8dbc0c3ebda9faa82e>:0 \n  at MvvmCross.Base.MvxMainThreadAs…"	string```

Breaks on this line of code:
```var dispatcher = CreateViewDispatcher();```

**Comment by Cheesebaron** [comment]
Forms is not supported anymore. Closing this one.
