### ISSUE TITLE
Update to iOS 15 Preventing Table Cells from Being Reused

### ISSUE THREAD

**Issue by lfeldman65** [MvvmCross/MvvmCross#4330]
## 🔙 Regression

Prior to the iOS 15 release, I had a table that worked fine. Now I’m seeing sporadic cases where cells are populated on initial load (first image) but aren’t being reused after scrolling off and on the screen (second image). Adam Roth and Daniel Higgins are missing from the 2nd image. Your help is appreciated! Thanks.

### Old (and correct) behavior

![image](https://user-images.githubusercontent.com/12520398/143229888-7c73f73d-d0e5-4c6f-8f72-ac17e5dd7a89.png)

### Current behavior

![image](https://user-images.githubusercontent.com/12520398/143230133-97f20d4e-74b9-484c-b7eb-e099f9ed64d1.png)

(Adam Roth and Daniel Higgins are missing).

### Reproduction steps

Some pertinent code:

public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
{
var cell = tableView.DequeueReusableCell(reuseIdentifier, indexPath) as MvxTableViewCell;
if (ItemsSource is ObservableCollection<GroupedObservableCollection<string, T>> observableCollection
            && indexPath.Section < observableCollection.Count
            && indexPath.Row < observableCollection[indexPath.Section].Count
        )
        {
            try
            {
                cell.DataContext = observableCollection[indexPath.Section][indexPath.Row];
                cell.BackgroundColor = ColorConversion.ConvertFromMvxToUIColor(LightOrDarkTheme.BackGroundColor);  // 6529
            }
            catch (Exception)
            {
                return cell;
            }
        }

        return cell;
}

### Configuration

**Version:** MvvmCross 5.6.3

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by VanjaPopovic** [comment]
Is the same issue appearing on MVVMCross 8.0.2?

**Comment by lfeldman65** [comment]
I am using MVVMCross 8.0.2.  Has someone else seen this issue?

Thanks,
Larry

**Comment by VanjaPopovic** [comment]
It appears that your Core project is still using PCL libraries. There's a good tutorial on https://medium.com/@bigoudi/upgrading-from-mvvmcross-5-to-mvvmcross-6-7ded83ecb69d that shows step by step what needs to be done to upgrade the core project.

**Comment by lfeldman65** [comment]
I will follow the tutorial. 

How did you determine that my Core project is using PCL libraries?

Thanks!
Larry

**Comment by Cheesebaron** [comment]
`.NETPortable,Version=v4.5,Profile=Profile78`

**Comment by lfeldman65** [comment]
The first step in the tutorial link says:

"The same is true for projects containing a package.config file. Migrate these “package.config” projects to “PackageReference” projects. VS2017 now includes a wizard for this: right click on the package.config file and migrate."

I see "packages.config" in my Touch, Droid and Core projects, but no option to migrate.

Thanks,
LF

**Comment by Cheesebaron** [comment]
Easiest way is just creating a .NET Standard library and move over the files. Then use PackageReference for the NuGet packages that you may have.

**Comment by lfeldman65** [comment]
I tried this:

https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/net-standard?tabs=macos

But the screen I see isn't the same as the tutorial.  Please see attachment.  Please help when you can.  Thanks!

![net](https://user-images.githubusercontent.com/12520398/145244814-4a9b9c49-f5df-4dbb-9a51-90aac23421c1.png)

**Comment by Cheesebaron** [comment]
It is just a library, if you select Library it will most likely be a netstandard library unless you are using VS2022

**Comment by lfeldman65** [comment]
Got through the tutorial, but unsure how to "Easiest way is just creating a .NET Standard library and move over the files. Then use PackageReference for the NuGet packages that you may have."  Can you point me towards explicit instructions?  Thanks!

**Comment by lfeldman65** [comment]
It seems to me that your suggestion works for VS 2017+, but the procedure for VS Mac is much more tedious. Is this correct? Thanks!

Larry

**Comment by lfeldman65** [comment]
I think I’m very close. Anyone want to help me over the finish line? If it’s not against site rules, I’ll pay for help. Thanks. 

Larry

**Comment by VaniaPopovic** [comment]
Hi Larry,
 
Can you please post on the MVVMCross discord and I will try to help there 1 on 1?

**Comment by lfeldman65** [comment]
What’s the link to the discord? Thanks!

Larry

**Comment by VaniaPopovic** [comment]
https://discord.com/invite/HSuhTyG mvvmcross channel

**Comment by lfeldman65** [comment]
I posted on discord.  What's the next step?  Thanks!

**Comment by Cheesebaron** [comment]
I think we can close this one.

Turns out, MvvmCross 3.5.1 @lfeldman65 is on assigns `null` as the `DataContext` when `CellDisplayingEnded` is called. This races against `GetCell` and in some cases the order of setting `null` or setting the `DataContext` goes wrong, which is why some cells become blank.

We fixed this issue in MvvmCross 4.2.0 in PR #1322
