### ISSUE TITLE
Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>() return Activity null 

### ISSUE THREAD

**Issue by StefanoPaparesta** [MvvmCross/MvvmCross#4331]
In my DialogService when i call

var top = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>();
var act = top.Activity;

act i s null.
In the previous version (7.0.0) it worked correctly, in version 8.0.2 it does not work.

**Comment by Cheesebaron** [comment]
Please use issue template and provide a minimal reproducible sample.
