### ISSUE TITLE
Crash when trying to navigate to a view with MvxRootPresentation from a Button Drop Down Menu

### ISSUE THREAD

**Issue by FinniusFrog** [MvvmCross/MvvmCross#4358]
## 🐛 Bug Report

Simulator crashes when trying to navigate to am MvxRootPresentation attributed view from a button drop down menu.

### Expected behavior
Clicking on Doesnt Work should navigate to Second controller

### Reproduction steps
On the navigation bar are two button. Work and Doesnt Work.  Click on Works first to see the desired behaviour. This uses a button Clicked method to bind back to the vm to open the second view model. Now try with Doesnt Work. This uses the same binding but is called from a drop down menu instead.

You can find an example project here: https://github.com/FinniusFrog/public

### Configuration
**Version:** 8.0.2

**Platform:** 
- [ x ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Provide minimal reproducible steps and a stack trace of the exception. Closing this issue as not enough information provided.

**Comment by FinniusFrog** [comment]
I’ve provided you with a project and the steps to reproduce. It’s the only solution in the above GitHub url.

**Comment by Cheesebaron** [comment]
1. You don't explain where to look in that code, there is a lot of stuff in there and it is not obvious where you put the _minimal_ repro code
2. You don't tell me what the error is, no exception nor stack trace to look at

**Comment by FinniusFrog** [comment]
In MainViewController.cs a command called `OpenSecondViewCommand` is bound with the view model OpenSecondViewModel in the MainViewModel.  The IMvxAsyncCommand in MainViewModel calls a method which uses the mvvmcross navigation service to call SecondViewModel which has the attribute 
`[MvxRootPresentation(WrapInNavigationController = true)]`

the call is `await _navigationService.Navigate<SecondViewModel>();` on line 26 of MainViewModel

In the MainViewController, if the command `OpenSecondViewCommand` is executed by the Clicked event of the button the second view will open correctly  (line 72 MainViewController.cs). If it is called via a UIMenu then it crashes (line 77 MainViewController.cs)

Please see attached stack trace (sorry, I am unable to copy the whole stack trace). Hope this makes sense 

[StackTrace.txt](https://github.com/MvvmCross/MvvmCross/files/7964324/StackTrace.txt)
and helps.

**Comment by Cheesebaron** [comment]
And did you try figure out what this means:

```
Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: UIPreviewTarget requires that the container view is in a window, but it is not. (container: <UIView: 0x7ff4e4156880> => <_UIContextMenuContainerView: 0x7ff4e450e8a0>)
```

This error has _nothing_ to do with MvvmCross. You are using UIMenu wrong/

**Comment by FinniusFrog** [comment]
Nope: no idea what that means. Not much comes up while doing a search. 

I figured that because it worked for a non-root attributed view it would also work for a root view as well. My mistake it would seem. I’ll investigate further but thank you for your useful responses.

**Comment by FinniusFrog** [comment]
@Cheesebaron , had another go with this using standard Xamarin.ios with UIMenu in exactly the same way. It works fine. No crashes. Still think there is an issue with MvvmCross. Should I raise another bug so some actually takes a look at it?

**Comment by Cheesebaron** [comment]
And what do you do there when you switch the ViewController. Are you changing the Root ViewController on the Window?

**Comment by FinniusFrog** [comment]
From the 1st Root View Controller I create a second view controller and set it as the root view controller. 

`UIApplication.SharedApplication.KeyWindow.RootViewController = SecondViewC`
