### ISSUE TITLE
Build errors after updating from 6 to Mvvmcross7

### ISSUE THREAD

**Issue by TimHi** [MvvmCross/MvvmCross#4360]
## 🔙 Regression

After updating to mvvmcross7 a clean rebuild/deploy does not work anymore on the windows vs. In Mac VS there are different errors (I'll add them tomorrow) but the app can be deployed from there. 
I spent a lot of time trying to update packages/resolve dependencies/rebuilding/cleaning I'm lost what else I can try/whats causing this. 
Any help is gladly appreciated.

Here is a list of the installed packages in the droid project, the mvvmcross version in the different projects is the same.
[nugets.txt](https://github.com/MvvmCross/MvvmCross/files/7946590/nugets.txt)

On Windows:  
When doing a clean rebuild I receive the following errors:  
```
52>UI.Droid\Resources\values\styles_Registration.xml(2): error APT2260: style attribute 'attr/MvxItemTemplate (aka app:attr/MvxItemTemplate)' not found.
52>UI.Droid\Resources\values\styles_Registration.xml(2): error APT2260: style attribute 'attr/MvxDropDownItemTemplate (aka app:attr/MvxDropDownItemTemplate)' not found.
52>UI.Droid\Resources\values\styles_Settings.xml(2): error APT2260: style attribute 'attr/MvxItemTemplate (aka app:attr/MvxItemTemplate)' not found.
52>UI.Droid\Resources\values\styles_Settings.xml(2): error APT2260: style attribute 'attr/MvxDropDownItemTemplate (aka app:attr/MvxDropDownItemTemplate)' not found.
52>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Aapt2.targets(157,3): error APT2062: failed linking references.
```
When deploying to a phone I receive the following errors:
```
UI.Droid\Resources\layout\call_out_view.xml(2): error APT2260: resource string/mg_dl (aka net.sinovo.mylife.app:string/mg_dl) not found.
1>UI.Droid\Resources\layout\cGraphContainer.xml(2): error APT2260: resource dimen/graph_container_data_padding_end (aka app:dimen/graph_container_data_padding_end) not found.
1>UI.Droid\Resources\layout\cGraphContainer.xml(2): error APT2260: resource dimen/graph_container_mask_padding_end (aka app:dimen/graph_container_mask_padding_end) not found.
```

### Old (and correct) behavior

App built fine, styles were used correctly

### Current behavior

App fails to build with the errors above.

### Configuration

**Version:** 7.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Sorry, but not sorry. However, I am not going to provide support for an ancient version of MvvmCross.
