### ISSUE TITLE
The command-bound event in TapGestureRecognizer points to page instead of viewmodel

### ISSUE THREAD

**Issue by 491134648** [MvvmCross/MvvmCross#4361]
## 🐛 Bug Report
Why the event of the command binding in TapGestureRecognizer points to page instead of viewmodel？

`   <StackLayout.GestureRecognizers>
                                <TapGestureRecognizer 
                               Command="{Binding GoToolCommand,Source={x:Reference DiscoverVPage}}"
                               CommandParameter="{Binding .}"/>
                            </StackLayout.GestureRecognizers>`
### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ✔] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by 491134648** [comment]
When I changed it to ViewModel.GoToolCommand, it was correct, why?
`
<StackLayout.GestureRecognizers> <TapGestureRecognizer Command="{Binding GoToolCommand,Source={x:Reference DiscoverVPage}}" CommandParameter="{Binding .}"/> </StackLayout.GestureRecognizers>
`

**Comment by Cheesebaron** [comment]
This has nothing to do with MvvmCross.
