### ISSUE TITLE
Xamarin.Android Readme and TipCalc Tutorial don't work

### ISSUE THREAD

**Issue by glopezfrutos** [MvvmCross/MvvmCross#4469]
## 🐛 Bug Report

When you follow the tutorial on the MVVMCross website for TipCalc or the Readme instructions, there is a build error in the Android Proyect on the App.cs class:
Error CS0310 'MvxAndroidSetup<App>' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TMvxAndroidSetup' in the generic type or method 'MvxAndroidApplication<TMvxAndroidSetup, TApplication>'	TipCalc.Droid

### Expected behavior
It should compile properly

### Reproduction steps
Following the readme or the TipCalc Tutorial

### Configuration

**Version:** 8.0.2

**Platform:** 
- [ ] :robot: Android
![image](https://user-images.githubusercontent.com/94074380/189395203-a5b09df5-2224-4b9c-8943-01a28f6ae93f.png)

**Comment by Cheesebaron** [comment]
You need to create your own class and inherit from MvxAndroidSetup. I guess we didn't update the docs.
