### ISSUE TITLE
net6-macos - The type or namespace name `Platforms` does not exist in the namespace `MvvmCross`

### ISSUE THREAD

**Issue by snechaev** [MvvmCross/MvvmCross#4476]
## 🔙 Regression

The UI project targeted to `net6-macos` can't be build with MvvmCross because `Platforms` namespace and all of its contents like a `MvxApplicationDelegate` does not exists.

### Old (and correct) behavior
I was able to build macOS apps with MvvmCross.

### Current behavior
I'm unable to build macOS apps targeting `net6-macos` (or `net6-macos12.3`) with MvvmCross

### Reproduction steps
* create new macos app `dotnet new macos`
* install MvvmCross `dotnet add ./mvvmCrossMacTest.csproj package mmvvmcross`
* change `AppDelegate` to inherit `MvxApplicationDelegate` instead of `NSApplicationDelegate`
* try to build and get the error saying "The type or namespace name `Platforms` does not exist in the namespace `MvvmCross`"

### Configuration

**Version:** 8.0.2 and 9.0.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by snechaev** [comment]
Looks like the problem is here https://github.com/MvvmCross/MvvmCross/blob/61fde5868a137aee6310007587704ebb5369952b/MvvmCross/MvvmCross.csproj#L41 and to fix this a condition should be changed to `$(TargetFramework.Equals('net6.0-macos') ` (replace `net6.0-mac' to the 'net6.0-macos')

**Comment by Cheesebaron** [comment]
@snechaev want to make a PR to fix this?

**Comment by snechaev** [comment]
@Cheesebaron, sure. Here it is https://github.com/MvvmCross/MvvmCross/pull/4480

**Comment by Cheesebaron** [comment]
This is in 9.0.1
