### ISSUE TITLE
MvvmCross 9.0.1 iOS release build crashes on device

### ISSUE THREAD

**Issue by markuspalme** [MvvmCross/MvvmCross#4484]
## 🔙 Regression

A release build (IPA file) of an an app crashes as soon as a MvvmCross package reference is added.

### Reproduction steps

1. Create a new app with `dotnet new ios`
2. Set a valid bundle identifier in `Info.plist`
3. Add a reference to `MvvmCross`, version 9.0.1 or 9.0.0
4. Build an IPA file: `dotnet publish testapp.csproj -f:net6.0-ios -c:Release /p:CodesignKey="Apple Development: Markus Palme (XXXXXX)" /p:CodesignProvision="Test app" /p:ArchiveOnBuild=true -r ios-arm64`
5. Install the IPA file on an iPhone, start the app 
6. The launch screen shows quicky, then the app crashes with this message being visible in the console:

   <img width="1263" alt="image" src="https://user-images.githubusercontent.com/1481801/190670437-280dbba7-da99-497b-a10d-ef29683ed80e.png">

   > error: Failed to load AOT module 'System.Private.CoreLib' while running in aot-only mode: doesn't match assembly.
 
This is the full project file:

```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    <MtouchLink>None</MtouchLink>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MvvmCross" Version="9.0.1" />
  </ItemGroup>
</Project>
```

### Configuration

**Version:** 9.0.0 or 9.0.01

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by markuspalme** [comment]
Addendum: The linker mode does not matter - same happens without any setting.

**Comment by markuspalme** [comment]
As I suspect that this is not a real MvX issue I have also opened a bug in the dotnet runtime repo: https://github.com/dotnet/runtime/issues/75758

**Comment by markuspalme** [comment]
I tried adding a reference to `Microsoft.Extensions.Logging.Abstractions` (the only dependency of MvvmCross) and the resulting app does not crash. So this is not caused by that dependency.

**Comment by markuspalme** [comment]
I have played around with this again, today. I found out that if I delete the bin and obj folders before the build it works and the app does not crash any more.

When you publish the app right after creating the project, then add the package reference and build again without the manual cleanup, you get the crash.

This looks like a bug in the build tools. I would assume that a dotnet publishwould take care of cleaning up its cache itself.

**Comment by Cheesebaron** [comment]
Thanks for the investigative work you've done here!

**Comment by markuspalme** [comment]
@Cheesebaron No, thank you for the hard work on the framework.

I did run into another strange bug (https://github.com/dotnet/runtime/issues/75802) but I think we can safely close this one here.

**Comment by markuspalme** [comment]
@Cheesebaron What's your experience so far with `net6-ios`?

**Comment by Cheesebaron** [comment]
@markuspalme not a lot of experience with net6-ios. Have done a bunch with net6.0-android, which works well.
