### ISSUE TITLE
MvvmCross projects miss SupportedOSPlatformVersion for .NET 6

### ISSUE THREAD

**Issue by evgenyvalavin** [MvvmCross/MvvmCross#4497]
## 🐛 Bug Report

My project targets Android 5 (API 21) as a minimum Android version my app supports.
Platform compatibility analyzer does it's job by showing more than 1k CA1416 warnings in the project. For instance, "This call site is reachable on: 'Android' 21.0 and later. 'MvxIoCContainerExtensions.LazyConstructAndRegisterSingleton<TInterface, TType>(IMvxIoCProvider)' is only supported on: 'Android' 31.0 and later." - is one of them.

[Support older OS versions](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#support-older-os-versions
)
### Expected behavior

SupportedOSPlatformVersion is set to "21.0" (Android 5, API 21)) for all Android projects
SupportedOSPlatformVersion is set to ~~"13.0" (iOS 13)~~ "10.0" (iOS 10) for all iOS projects

**Version:** 9.0.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by entdark** [comment]
I would lower iOS to 10.

**Comment by evgenyvalavin** [comment]
Agree

**Comment by Cheesebaron** [comment]
Thanks I will have a look at this and release a new package soon
