### ISSUE TITLE
Problems with type based parameter serialization/deserialization

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#450]
Problems with type based parameter serialization/deserialization - like in:

http://stackoverflow.com/questions/19058173/passing-complex-navigation-parameters-with-mvvmcross-showviewmodel/19059938#19059938

**Comment by martijn00** [comment]
@slodge Can't we get that example into MvvmCross because this seems quite a commom use case. I would use this too in my apps.

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/1284
