### ISSUE TITLE
ArgumentException seen in output on Android startup regarding MvxViewAssemblyBootstrapAction

### ISSUE THREAD

**Issue by Digifais** [MvvmCross/MvvmCross#4503]
## 🐛 Bug Report

An exception is happening somewhere in the Android startup:

> [Default] [Verbose] Error running startup task MvxViewAssemblyBootstrapAction1 - error ArgumentException: Cannot create an instance of MvvmCross.Platforms.Android.Binding.MvxViewAssemblyBootstrapAction1[TView] because Type.ContainsGenericParameters is true.

This is not a blocking issue, just something I observed in my application output. I don't do anything with `MvxViewAssemblyBootstrapAction` in my own code. This seems to happen between `[MvvmCross.Core.MvxSetup] [Verbose] Setup: Bootstrap actions` and `[MvvmCross.Core.MvxSetup] [Verbose] Setup: StringToTypeParser start`.

### Expected behavior
No exception is seen in the application output.

### Reproduction steps
Not entirely sure what is causing this in my current project.

### Configuration

**Version:** 8.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
So, I've dug into this a bit. It seems like there is no difference in behavior here. Simply the change from MvxLog to Microsoft.Extensions.Logging now surfaces the error.

You can safely ignore this one. Perhaps configure your logger to ignore this log entry.
