### ISSUE TITLE
MvxAppCompatAutoCompleteTextView OnItemClick event fired twice

### ISSUE THREAD

**Issue by Digifais** [MvvmCross/MvvmCross#4507]
## 🐛 Bug Report

`MvxAppCompatAutoCompleteTextView` OnItemClick event is being fired twice.

### Expected behavior
`MvxAppCompatAutoCompleteTextView` OnItemClick event is fired once.
### Reproduction steps
Add a new class which inherits from `MvxAppCompatAutoCompleteTextView` and override `OnItemClick(int position)` and add some custom logic.
### Configuration

**Version:** 8.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Fixed in #4508
