### ISSUE TITLE
MvvmCross9.0.2 throws System.NullReferenceException for Bind

### ISSUE THREAD

**Issue by dingyud** [MvvmCross/MvvmCross#4531]
## 🐛 Bug Report
System.NullReferenceException: "Object reference not set to an instance of an object."
 at MvvmCross.Binding.BindingContext.MvxBaseFluentBindingDescription`1.SourcePropertyPath[TSource](Expression`1 sourceProperty)\n   
at MvvmCross.Binding.BindingContext.MvxFluentBindingDescription`2.To(Expression`1 sourceProperty)

Note:MacOS App migrated from Xamarin.Mac to. NET6

### Expected behavior
MacOS App starts up normally

### Reproduction steps
Create binding set and call bind.
![Screen Shot 2022-12-22 at 16 59 25](https://user-images.githubusercontent.com/121216002/209102417-2ebf94c4-0e84-4d80-b557-54df616050f9.png)

Sample Source Code：
[MvvmCross.NETSample.Mac.zip](https://github.com/MvvmCross/MvvmCross/files/10285670/MvvmCross.NETSample.Mac.zip)

### Configuration
・Visual Studio for Mac 17.5
・MvvmCross 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by entdark** [comment]
Doesn't it have to call `base.ViewDidLoad`? Have you checked which object is `null`? Maybe it's your `TextField`.

**Comment by dingyud** [comment]
After calling base.ViewDidLoad, the following exception will occur：

   at MvvmCross.Logging.MvxLogHost.GetLog(String categoryName)
   at MvvmCross.Logging.MvxLogHost.get_Default()
   at MvvmCross.Platforms.Mac.Views.MvxViewControllerExtensions.LoadViewModel(IMvxMacView macView)
   at MvvmCross.Views.MvxViewExtensions.OnViewCreate(IMvxView view, Func`1 viewModelLoader)
   at MvvmCross.Platforms.Mac.Views.MvxViewControllerAdapter.HandleViewDidLoadCalled(Object sender, EventArgs e)
   at MvvmCross.Platforms.Mac.Views.MvxViewController.ViewDidLoad()
   at MvvmCross.NETSample.Mac.Views.InfoView.ViewDidLoad() in MvvmCross_.NET_Demo/MvvmCross.NETSample.Mac/MvvmCross.NETSample.Mac/Views/InfoView.cs:line 23
![Screen Shot 2022-12-23 at 09 27 22](https://user-images.githubusercontent.com/121216002/209252795-9e5d9f61-73f2-48b4-a1f7-7517a526fa14.png)

**Comment by dingyud** [comment]
TextField has been checked and is not null.
![Screen Shot 2022-12-23 at 09 25 07](https://user-images.githubusercontent.com/121216002/209252969-3b61d5d9-1f31-434b-ab00-20a8bca038f3.png)

**Comment by Cheesebaron** [comment]
You need to call `base.ViewDidLoad()` this is where the ViewModel is instantiated.

As for your stack trace when you do that. Seems like you are missing some setup of the logging. How does your AppDelegate look?

**Comment by dingyud** [comment]
@Cheesebaron @entdark 

The content in AppDelegate is as follows, the problem still exists, the Sample has been uploaded, can you help to check what is wrong, thank you.
Note: MvvmCross is using the latest 9.0.5

![截屏2023-01-10 15 49 19](https://user-images.githubusercontent.com/121216002/211494502-45ff317c-a80c-4b42-bc80-77edc2938f8a.png)

Sample Code:
[MvvmCross.NETSample.Mac.zip](https://github.com/MvvmCross/MvvmCross/files/10380343/MvvmCross.NETSample.Mac.zip)

**Comment by Cheesebaron** [comment]
Yeah, I didn't change anything with regards to macos targets in the new MvvmCross releases. I will have a look at the sample, thanks!

**Comment by Cheesebaron** [comment]
Seems like what is happening is that you have your standard Main.storyboard, which shows the ViewControler before MvvmCross has initialized. So it is not MvvmCross pushing the ViewController.

**Comment by dingyud** [comment]
@Cheesebaron 
According to your hint, I probably know the problem. The code has been corrected, but the screen still cannot be displayed normally. I think there is a problem with the method MvxMacViewPresenter(this). Can you help me to confirm it?  thanks!
![Screen Shot 2023-01-12 at 18 58 17](https://user-images.githubusercontent.com/121216002/212058853-c2308466-0abd-462f-b701-1876b0d721ab.png)

The specific Error is as follows：
![Screen Shot 2023-01-12 at 18 58 34](https://user-images.githubusercontent.com/121216002/212059046-065e4b33-a15a-42c9-b091-2df5fcc95a41.png)




Using the same method, the following Sample can run completely (note: the version of MvvmCross is 6.2.3)
https://github.com/riversx/MvvmCrossExample

**Comment by dingyud** [comment]
@entdark  @Cheesebaron 
Could you confirm this question for me, thank you

**Comment by snechaev** [comment]
@dingyud it looks like you hit by this bug https://github.com/MvvmCross/MvvmCross/issues/4572
Try to set any of presentation attributes (I suppose, the `[MvxWindowPresentation]` will be the best here) explicitly to your view / view controller to workaround this.

**Comment by dingyud** [comment]
Thank you very much, the problem has been perfectly solved
