### ISSUE TITLE
Close<Result> has been removed from IMvxNavigationService

### ISSUE THREAD

**Issue by D-Diyare** [MvvmCross/MvvmCross#4553]
## 🔙 Regression

I've been using MvvmCross since version 7,  most I worked with was version 8, lately wanted to upgrade to version 9, what was strange for me was I noticed that I can't close the ViewModel with return of result like before, after I took a look at the source I saw only one (out of the two) versions of Close method remained and its : 

``` cs
Task<bool> Close(IMvxViewModel viewModel, CancellationToken cancellationToken = default);
```
however, the implementation still exists in MvxNavigationService

``` cs
public virtual async Task<bool> Close<TResult>(
            IMvxViewModelResult<TResult> viewModel, TResult result, CancellationToken cancellationToken = default)
```

### Old (and correct) behavior
Exists:
``` cs
public virtual async Task<bool> Close<TResult>(
            IMvxViewModelResult<TResult> viewModel, TResult result, CancellationToken cancellationToken = default)
```

### Current behavior
Not exists:
``` cs
public virtual async Task<bool> Close<TResult>(
            IMvxViewModelResult<TResult> viewModel, TResult result, CancellationToken cancellationToken = default)
```

### Reproduction steps
bring back the above method so we can't return the result from the closed ViewModel 

### Configuration

**Version:** 9.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
This is not a regression. This is done on purpose.

**Comment by D-Diyare** [comment]
So what is the workaround for this currently? I cannot seem to find it in the documentation, the documentation doesn't cover upgrading to version 9, I understand you guys working so hard on this but when something changes at least it needs to be mentioned somewhere.
Best regards

**Comment by Cheesebaron** [comment]
The workaround is to not use it. You have plenty of options to make something work. I.e. the Parameters for you ViewModel, you could have a callback for backwards navigation. Or you could have some kind of global state. Totally up to you how to tackle it.

**Comment by dsmitchell** [comment]
> The workaround is to not use it. You have plenty of options to make something work. I.e. the Parameters for you ViewModel, you could have a callback for backwards navigation. Or you could have some kind of global state. Totally up to you how to tackle it.

The challenge with this change is that there is no obvious mechanism for waiting for the result of this sub-navigation. Is there a recommended event or something similar where we can then check the modified parameter or the global state, and then act accordingly?

**Comment by entdark** [comment]
Message Bus is the right way.
Subscribe for your messages when a VM with a result gets created. Unsubscribe when it gets destroyed.
From the VM with a result notify about it.
In my projects I made special `IResultAwaitingViewModel`, `IResultSettingViewModel` and extended `IMvxNavigationService` to pass those VMs and they do all the subscribing/unsubscribing logic for me.

**Comment by ggbtvs** [comment]
This in very inconvenient. I literally have hundreds of these calls and logic flows after the awaited results. This is very bad sledgehammer approach to just delete the functionality, when it should have been deprecated and a warning given that this was coming down the line.  @entdark Any chance you could give any example of implementation of your IResultAwaitingViewModel and IResultSettingViewModel?  Thanks

**Comment by entdark** [comment]
@ggbtvs sure thing. I can make a sample project in 2 days. If I forget then poke me here to remind.

**Comment by entdark** [comment]
@ggbtvs here it is, an example with navigation between VMs that awaits and sets results and survives between app restorations on Android: https://github.com/entdark/JKChat/commit/7d66f385aaf77dcf9b1d3112a1cca79da54a8462

**Comment by ggbtvs** [comment]
> @ggbtvs here it is, an example with navigation between VMs that awaits and sets results and survives between app restorations on Android: [entdark/JKChat@7d66f38](https://github.com/entdark/JKChat/commit/7d66f385aaf77dcf9b1d3112a1cca79da54a8462)

@entdark Thanks for doing this.  I like your implementation using default implementations for interfaces.  Currently, I'm not using .net 8 so I cannot use the same concept as you.  However, I had done something  similar as in using mvxmessage to handle things, but it's quite cumbersome.  I do hope @Cheesebaron considers your suggestion.  One thing to ask, how would you handle if you needed multiple view models navigated to based upon result of a previously navigated to view model. I assume implementing multiple interfaces.

**Comment by entdark** [comment]
@ggbtvs Yes, you inherit from multiple `IResultAwaitingViewModel<T>`. And you have to implement multiple `MvxSubscriptionToken IResultAwaitingViewModel<T>.ResultAwaitingToken { get; set; }` and `public bool ResultSet(IResultSettingViewModel<T> sender, T result)` and multiple `(this as IResultAwaitingViewModel<T>).SubscribeToResult();` and `(this as IResultAwaitingViewModel<T>).UnsubscribeToResult();`

Should look like:
```csharp
public class MyViewModel : MvxViewModel, IResultAwaitingViewModel<Result1>, IResultAwaitingViewModel<Result2> {
	public override void ViewDestroy(bool viewFinishing = true) {
		if (viewFinishing) {
			(this as IResultAwaitingViewModel<Result1>).UnsubscribeToResult();
			(this as IResultAwaitingViewModel<Result2>).UnsubscribeToResult();
		}
		base.ViewDestroy(viewFinishing);
	}

	public override void Prepare() {
		base.Prepare();
		(this as IResultAwaitingViewModel<Result1>).SubscribeToResult();
		(this as IResultAwaitingViewModel<Result2>).SubscribeToResult();
	}

	MvxSubscriptionToken IResultAwaitingViewModel<Result1>.ResultAwaitingToken { get; set; }
	MvxSubscriptionToken IResultAwaitingViewModel<Result2>.ResultAwaitingToken { get; set; }

	public bool ResultSet(IResultSettingViewModel<Result1> sender, Filter result) {
		if (sender is Result1ViewModel) {
			//handle Result1
			return true;
		}
		return false;
	}
	
	public bool ResultSet(IResultSettingViewModel<Result2> sender, Filter result) {
		if (sender is Result2ViewModel) {
			//handle Result2
			return true;
		}
		return false;
	}
}
```

Not the best approach since it has duplicates but I couldn't find a better way unfortunately.

**Comment by IainS1986** [comment]
How can that survive during process death?

The code that was 'awaiting' the result will have been destroyed, so you'll have an orphaned view being restored that when closed - nothing happens?

**Comment by IainS1986** [comment]
> This in very inconvenient. I literally have hundreds of these calls and logic flows after the awaited results. This is very bad sledgehammer approach to just delete the functionality, when it should have been deprecated and a warning given that this was coming down the line.  @entdark Any chance you could give any example of implementation of your IResultAwaitingViewModel and IResultSettingViewModel?  Thanks 

To be fair, you're commenting on this over a year after this change appeared

We too had hundreds of uses, and it's a pain (and gutting as it was such a clean way to navigate) but it fundamentally didn't work.

If you REALLY need too, you can just copy the functions into your own implementation of IMvxNavigationService and hook them back. Super easy and quick.

We took the plunge and just ported over 100+ usages. We made our own (similar) system that uses MvxMessages . Not quite the same as suggested here - no need to implement multiple interfaces for multiple return types - but otherwise the concept is the same.

In the end it didn't actually take that long to port everything.

**Comment by entdark** [comment]
> Not the best approach since it has duplicates but I couldn't find a better way unfortunately.

I just thought it could be done as a few abstract classes the implement multiple interfaces like `ResultAwaitingViewModel<Result1, Result2>`, `ResultAwaitingViewModel<Result1, Result2, Result3>` that fixes the duplication.

**Comment by entdark** [comment]
> We took the plunge and just ported over 100+ usages. We made our own (similar) system that uses MvxMessages . Not quite the same as suggested here - no need to implement multiple interfaces for multiple return types - but otherwise the concept is the same.

I wonder what is your solution? Does it survive between Android restorations?

**Comment by IainS1986** [comment]
Yeah it's basically the same approach you took.We use the MvxMessenger service and have view models hookup for 'return' messages and broadcast them on close etcOn 12 Jan 2024 16:13, entdark ***@***.***> wrote:

We took the plunge and just ported over 100+ usages. We made our own (similar) system that uses MvxMessages . Not quite the same as suggested here - no need to implement multiple interfaces for multiple return types - but otherwise the concept is the same.

I wonder what is your solution? Does it survive between Android restorations?

**Comment by Cheesebaron** [comment]
The approach I am using is to provide a callback though the ViewModel parameters. So something like:

```csharp
class MyVm(IMvxNavigationService navigationService) : MvxViewModel<MyVMParams>
{
    public record MyVMParams(Action MyCallback);

    private MyVMParams _p;

    public void Prepare(MyVMParams p)
    {
        _p = p;
    }

    private Task DoCloseCommand()
    {
        _p.MyCallback();
        return navigationService.Close(this);
    }
}
```

But using Messenger can work as well.

**Comment by entdark** [comment]
But it won't survive app restoration on Android, will it? You cannot save delegates.

**Comment by Cheesebaron** [comment]
Right, it will probably have the same issue. So if you want to survive a rehydration, given that the previous ViewModel is also re-created and the subscription is made before you trigger the message, then that might be a better solution. However, that is not a guarantee either.

**Comment by IainS1986** [comment]
No the Action one won't restore in process death, depends how much you really care about that (the previous Task system didn't either, so you'd be no worse off in that regards).

Heres what I went with with regards to a messenging system. Code below might not be 100% right as I'm cherry picking from our repo...


The Result Message (I had, issues, trying to make this a generic T so used ugly object casting instead):

```
    public class ViewModelResultMessage : MvxMessage
    {
        public static ViewModelResultMessage Create(object sender, object result)
            => new ViewModelResultMessage(sender, result);

        public static ViewModelResultMessage Create(object sender, object parameters, object result)
            => new ViewModelResultMessage(sender, parameters, result);

        // The actual result object to return
        public object Result { get; private set; }
        
        // We had instances where we needed to know the parameters used to show the VM in the first
        // place as the result is handled based on extra context.
        public object Parameters { get; private set; }
        
        // Helper to stop multiple VMs handling the same message type.
        public bool IsHandled { get; private set; }

        public ViewModelResultMessage(object sender) : base(sender)
        {
            Result = null;
        }

        public ViewModelResultMessage(object sender, object result) : base(sender)
        {
            Result = result;
        }

        public ViewModelResultMessage(object sender, object parameters, object result) : base(sender)
        {
            Parameters = parameters;
            Result = result;
        }

        // Lets you check the VM that the result is coming from
        public bool IsFrom<TViewModel>() where TViewModel : BaseViewModel
            => Sender?.GetType() == typeof(TViewModel);

        // This allows services, or non VM's to return results. We have instances where we kick off a flow
        // via a service call, not a navigation call, and still want to wait on the result.
        public bool IsFromService<T>()
            => (Sender?.GetType() == typeof(T)) == true || (typeof(T).IsAssignableFrom(Sender?.GetType())) == true;

        public TViewModel SenderAs<TViewModel>() where TViewModel : BaseViewModel
            => Sender as TViewModel;

        public T GetResult<T>()
        {
            IsHandled = true;
            return Result is T value ? value : default(T);
        }

        public T GetParameters<T>()
        {
            return Parameters is T value ? value : default(T);
        }

        public void MarkAsHandled()
        {
            IsHandled = true;
        }
    }
```


The Base ViewModel for the View Model that returns a result:

```
    public abstract class BaseViewModelReturn<TResult> : BaseViewModel
    {
        public TResult Result { get; set; } = default(TResult);

        public bool HasReturned { get; private set; } = false;

        // This allows you to have the return handled either before or after the view has closed
        public virtual bool WaitToFullyClose => true;

        public BaseViewModelReturn(IMvxNavigationService navigationService) : base(navigationService) { }

        public override void ViewDestroy(bool viewFinishing = true)
        {
            if (viewFinishing && !HasReturned)
            {
                DoReturn();
            }

            base.ViewDestroy(viewFinishing);
        }

        protected override async Task Close()
        {
            IsClosing = true;
            await NavigationService.Close(this);

            if (!WaitToFullyClose)
                DoReturn();
        }

        protected Task CloseWithResult(TResult result)
        {
            Result = result;
            return Close();
        }

        private void DoReturn()
        {
            if (HasReturned)
                return;

            HasReturned = true;
            MessengerService?.Publish(ViewModelResultMessage.Create(this, Result));
        }
    }
```
    
    
    
Our BaseViewModel (all our viewmodels can 'handle' results)

```
    public abstract class BaseViewModel : MvxViewModel
    {
        private IMvxMessenger _messengerService;
        public IMvxMessenger MessengerService
        {
            get => _messengerService = _messengerService ?? MvvmCross.Mvx.IoCProvider.Resolve<IMvxMessenger>();
        }
    
        // Override if you want to handle any return results that may get broadcasted
        protected virtual bool DoesListenForReturnResults
        {
            get;
            private set;
        }
        
        private MvxSubscriptionToken _returnResultsToken = null;
        
        public override Task Initialize()
        {
            if (DoesListenForReturnResults)
                StartListeningForReturnResults();

            return base.Initialize();
        }
        
        protected override void SaveStateToBundle(IMvxBundle bundle)
        {
            base.SaveStateToBundle(bundle);

            // Store off if we are currently waiting/interested in VM return messages
            bundle.Data[nameof(DoesListenForReturnResults)] = DoesListenForReturnResults ? bool.TrueString : bool.FalseString;
        }
        
        protected override void ReloadFromBundle(IMvxBundle state)
        {
            base.ReloadFromBundle(state);

            // Restore if we are actively listening for return results
            // This will allow restoring from process death if we turned on
            // listening via StartListeningForReturnResults() if we weren't
            // when initialising.
            var listen = state.Data[nameof(DoesListenForReturnResults)];
            if (string.IsNullOrEmpty(listen) == false &&
                bool.TryParse(listen, out bool result))
            {
                DoesListenForReturnResults = result;
            }
        }
        
        public override void ViewDestroy(bool viewFinishing = true)
        {
            base.ViewDestroy(viewFinishing);
            if (viewFinishing)
            {
                StopListeningForReturnResults();
            }
        }
        
        private async void HandleViewModelResultMessage(ViewModelResultMessage message)
        {
            if (message == null ||
                message?.IsHandled == true)
                return;

            await OnResultReturned(message);
        }
        
        // Override to handle results...
        protected virtual Task OnResultReturned(ViewModelResultMessage message)
            => Task.CompletedTask;
            
            public void StopListeningForReturnResults()
        {
            DoesListenForReturnResults = false;

            if (_returnResultsToken != null)
                MessengerService.Unsubscribe<ViewModelResultMessage>(_returnResultsToken);

            _returnResultsToken?.Dispose();
            _returnResultsToken = null;
        }

        public void StartListeningForReturnResults()
        {
            DoesListenForReturnResults = true;

            if (_returnResultsToken == null)
                _returnResultsToken = MessengerService.Subscribe<ViewModelResultMessage>(HandleViewModelResultMessage);
        }
        
        /// Couldn't copy code here btu we have some logic to Start/Stop listening on Dark mode change
        /// or going from Portrait->Landscape on Android etc....
    }
```
    
    
    Then an example override of OnResultReturned (that handles multiple returns)
    
```
        protected override async Task OnResultReturned(ViewModelResultMessage message)
        {
            if (message.IsFrom<ViewModelA>())
            {
                StopListeningForReturnResults();
    
                if (message.GetResult<bool>())
                {
                   // Do a thing
                }
                else
                {
                    // Do another thing
                }
            }
            
            if (message.IsFrom<ViewModelB>())
            {
                StopListeningForReturnResults();
                var result = message.GetResult<MyObject>();
                var param = message.GetParameters<MyParameters>();
                
                // Do a thing based on the result and param 
            }
        }
```
