### ISSUE TITLE
Java.Lang.ClassNotFoundException after upgrading to version 9.0.8 and only in release

### ISSUE THREAD

**Issue by xavimarquez** [MvvmCross/MvvmCross#4557]
## 🐛 Bug Report

Our app worked like a charm in version 8. We upgraded it to 9.0.8 version. It has been working fine all tests in debug mode but when we moved it to release, we get:

`Java.Lang.ClassNotFoundException: android.view.MvxEmptyRecyclerView`

`MvxEmptyRecyclerView` is a class derived from `MvxRecyclerView`

The thing is that it has been working fine in mvvmcross 6, 7 and 8. In version 9, only works in debug mode, not in release.

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Full stack trace please

**Comment by xavimarquez** [comment]
No, we do not use Linter. Also, this class is contained in the same assembly that the fragments and activities.

```
java.lang.ClassNotFoundException: android.view.MvxEmptyRecyclerView
java.lang.Class.classForName(Native Method)
java.lang.Class.forName Class.java:454
android.view.LayoutInflater.createView LayoutInflater.java:819
android.view.LayoutInflater.createView LayoutInflater.java:780
android.view.LayoutInflater.onCreateView LayoutInflater.java:917
mvvmcross.platforms.android.binding.views.MvxLayoutInflater.onCreateView MvxLayoutInflater.java:67
android.view.LayoutInflater.onCreateView LayoutInflater.java:934
mvvmcross.platforms.android.binding.views.MvxLayoutInflater.onCreateView MvxLayoutInflater.java:59
android.view.LayoutInflater.onCreateView LayoutInflater.java:954
mvvmcross.platforms.android.binding.views.MvxLayoutInflater.onCreateView MvxLayoutInflater.java:75
android.view.LayoutInflater.createViewFromTag LayoutInflater.java:1008
crc649d3568449b44e722.ToolbarFragment_1.onCreateView ToolbarFragment_1.java:40
androidx.fragment.app.Fragment.performCreateView Fragment.java:3104
androidx.fragment.app.FragmentStateManager.createView FragmentStateManager.java:524
androidx.fragment.app.FragmentStateManager.moveToExpectedState FragmentStateManager.java:261
androidx.fragment.app.FragmentManager.executeOpsTogether FragmentManager.java:1899
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute FragmentManager.java:1817
androidx.fragment.app.FragmentManager.execPendingActions FragmentManager.java:1760
androidx.fragment.app.FragmentManager$5.run FragmentManager.java:547
android.os.Handler.handleCallback Handler.java:942
```

**Comment by Cheesebaron** [comment]
OK. 2 questions:

1. How exactly are you ensuring your App is not trimmed/linked?
2. Have you tried specifying the fully registered namespace for your MvxEmptyRecyclerView class in your layout?

For 2. I assume your class looks something like:

```csharp
[Register("my.namespace.MvxEmptyRecyclerView")]
public class MvxEmptyRecyclerView : MvxRecyclerView
{
}
```

In your Android XML you would then do:

```xml
<my.namespace.MvxEmptyRecyclerView
   android:id="@+id/recycler"
   ... />
```

When there is `android.view.` infront, it indicates you didn't specify anything in your layout.

**Comment by xavimarquez** [comment]
1. Sorry, I misread your question. 
2. Yes, I tried '[Register...' and changed the XML, but no success.

Now I have tried to combine both, using the full name and in the manifest, setting off the "Enable triming".

Now the error has changed. At least now it starts and I can navigate to a screen, but a different problem appers:

`MvvmCross.ViewModels.MvxViewModelLoader.LoadViewModel(MvxViewModelRequest request, IMvxBundle savedState, IMvxNavigateEventArgs navigationArgs)
MvvmCross.Exceptions.MvxException: Failed to resolve parameter for parameter messenger of type IMvxMessenger when creating MyApp.ViewModels.PrepareDbViewModel. You may pass it as an argument`

Full stack:
```
MvvmCross.ViewModels.MvxViewModelLoader.LoadViewModel(MvxViewModelRequest request, IMvxBundle savedState, IMvxNavigateEventArgs navigationArgs)
MvvmCross.Navigation.MvxNavigationService.Navigate(Type viewModelType, IMvxBundle presentationBundle, CancellationToken cancellationToken)
MvvmCross.Navigation.MvxNavigationService.Navigate[PrepareDbViewModel](IMvxBundle presentationBundle, CancellationToken cancellationToken)
MyApp.ViewModels.Navigation.NavigationExtensions.NavigateToPrepareDB(IMvxNavigationService navigationService)
MyApp.ViewModels.HouseSelectorViewModel.SelectFarm(Farm db)
```

**Comment by xavimarquez** [comment]
Next step, googling, I found a similar case about `IMvxMessenger `

https://github.com/MvvmCross/MvvmCross/issues/4347

The proposed workaround is to add this code in `App.Initialize()`
```
var pluginManager = Mvx.IoCProvider.Resolve<IMvxPluginManager>();
pluginManager.EnsurePluginLoaded<MvvmCross.Plugin.Messenger.Plugin>(true);
```

Now it seems to work. In any case, I think that these workarounds should not be the solution. It has been working fine in 8 versions and it works fine in debug mode. Why in release for 9 version is different?

**Comment by entdark** [comment]
Again that mysterious bug where `IMvxMessenger` wasn't loaded.
Related: https://github.com/xamarin/xamarin-macios/issues/14938

**Comment by DavidMarquezF** [comment]
The custom MvxEmptyRecyclerView was registered with:

```
 protected override IEnumerable<Assembly> AndroidViewAssemblies => new List<Assembly>(base.AndroidViewAssemblies)
        {
            typeof(MvxRecyclerView).Assembly,
            typeof(MvxEmptyRecyclerView).Assembly
        };
```

which to my understanding, enables me to not have to put the whole qualified name in the front
