### ISSUE TITLE
Android Mvx.IoCProvider.Resolve hitting MvvmCross.Exceptions.MvxIoCResolveException within ListenableWorkers when App is closed

### ISSUE THREAD

**Issue by MagneticLlama** [MvvmCross/MvvmCross#4558]
## 🐛 Bug Report
`Mvx.IoCProvider.Resolve` hits `MvvmCross.Exceptions.MvxIoCResolveException` for all registered services when called in a background worker while the app is closed. The same worker successfully runs when the app is open, but will fail directly after the app is closed on its next execution.

### Expected behavior
`Mvx.IoCProvider.Resolve` should return services that were registered in the overridden `Initialize` method of `MvxApplication` within a background worker while the App is closed.

### Reproduction steps
Create a periodic work request in MainApplication that will continue to run after the app is closed
```
public class MainApplication : MvxAndroidApplication<Setup, App>
{
    public MainApplication(IntPtr javaReference, JniHandleOwnership transfer)
        : base(javaReference, transfer)
    {
    }

    public override void OnCreate()
    {
        base.OnCreate();

        var constraintsBuilder = new Constraints.Builder();
        constraintsBuilder.SetRequiredNetworkType(NetworkType.NotRequired);
        var constraints = constraintsBuilder.Build();
        var workRequest = new PeriodicWorkRequest.Builder(typeof(DummyWorker), new TimeSpan(0, 1, 0))
            .SetConstraints(constraints)
            .Build();
        WorkManager.GetInstance(ApplicationContext).EnqueueUniquePeriodicWork(nameof(DummyWorker), ExistingPeriodicWorkPolicy.Replace, workRequest);
    }
}
```

Register a service in the Initialize method of App
```
public class App : MvxApplication
{
    public override void Initialize()
    {
        base.Initialize();
        Mvx.IoCProvider.LazyConstructAndRegisterSingleton<IDummyService, DummyService>();
    }
}
```

Create a worker that uses the registered service via Mvx.IoCProvider.Resolve
```
public class DummyWorker : ListenableWorker, CallbackToFutureAdapter.IResolver
{
    public DummyWorker(IntPtr javaReference, JniHandleOwnership transfer) : base(javaReference, transfer)
    {
    }

    protected DummyWorker(Context context, WorkerParameters workerParams) : base(context, workerParams)
    {
    }

    public override IListenableFuture StartWork()
    {
	var dummyService = Mvx.IoCProvider.Resolve<IDummyService>();
	if (dummyService == null) {
	{
	    throw new NullReferenceException("dummyService is null in DummyWorker StartWork");
	}
        return CallbackToFutureAdapter.GetFuture(this);
    }

    public Java.Lang.Object? AttachCompleter(CallbackToFutureAdapter.Completer completer)
    {
        completer.Set(Result.InvokeSuccess());
        return string.Empty;
    }
}
```

### Configuration

**Version:** 9.0.9
net7.0-android

**Platform:** 
- [x] :robot: Android

**Comment by MagneticLlama** [comment]
```
var setup = MvxAndroidSetupSingleton.EnsureSingletonAvailable(ApplicationContext);
setup.EnsureInitialized();
```
within the Worker constructors fixes the `MvvmCross.Exceptions.MvxIoCResolveException` when trying to resolve services with `Mvx.IoCProvider.Resolve` when the app is closed.

I'm not sure if this is something I should be doing within the background workers or if there is something else wrong with my app initialization.

**Comment by Cheesebaron** [comment]
As I wrote in your other question, there is a pending PR which will do the setup from a MvxAndroidApplication class. However, that is not in yet. So yes, for now you need to manually call EnsureInitialized() in your worker when the Process gets torn down and your worker gets invoked.
