### ISSUE TITLE
Can IMvxValueCombiner be simplified to IMultiValueConverter?

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#456]
The latest evolution of `IMvxValueCombiner` is much simpler following the removal of failed values (using UnsetValue and DoNothing).

I'm wondering if this could be simplified further if we adopt something like an `IMvxMultiValueConverter` pattern for the internal combiner logic? Like in http://www.codeproject.com/Articles/328978/Introduction-to-multi-binding-and-multi-value-conv

**Comment by nickrandolph** [comment]
Is this of interest to anyone? Please add a comment if it is

**Comment by nickrandolph** [comment]
No feedback, so closing this issue (@slodge I assume you don't have anything to add?)
