### ISSUE TITLE
"System.InvalidCastException: Specified cast is not valid." during Android RestoreInstanceState

### ISSUE THREAD

**Issue by evgenyvalavin** [MvvmCross/MvvmCross#4600]
### Reproduction steps
1. Start an Android app with MvvmCross.
2. Use any app to fill all of the RAM.
3. Return to the App with MvvmCross.
4. Get a crash by calling MvxFragment`1.get_ViewModel()
```
System.InvalidCastException: Specified cast is not valid.
MvvmCross.Platforms.Android.Views.Fragments.MvxFragment`1.get_ViewModel()
```

[An explicit cast to cause the exception](https://github.com/MvvmCross/MvvmCross/blob/330c6bd580db61ce2f84a9016f0eac290bd117c9/MvvmCross/Platforms/Android/Views/Fragments/MvxFragment.cs#L128)

I've figured out the type of ViewModel via DataContext in non generic [MvxFragment](https://github.com/MvvmCross/MvvmCross/blob/330c6bd580db61ce2f84a9016f0eac290bd117c9/MvvmCross/Platforms/Android/Views/Fragments/MvxFragment.cs#L45). DataContext's type is MvxNullViewModel

### Expected behavior
No crash.
ViewModel's type is TViewModel of generic MvxFragment<TViewModel>

### Configuration

**Version:** 9.0.9

**Platform:** 
- [ ] :robot: Android

**Comment by evgenyvalavin** [comment]
Found similar issue https://github.com/MvvmCross/MvvmCross/issues/4584

**Comment by evgenyvalavin** [comment]
It has something to do with this line https://github.com/MvvmCross/MvvmCross/blob/4181288ea4bbd4397015a76313592993ace182af/MvvmCross/Views/MvxViewExtensions.cs#L44

For some reason the condition is false.

Could it be fixed in https://github.com/MvvmCross/MvvmCross/pull/4546?

**Comment by evgenyvalavin** [comment]
Found the reason the condition is false - Mvx.IoCProvider is null

**Comment by evgenyvalavin** [comment]
@Cheesebaron when do you plan to release new version with #4546 fixing the current issue?

**Comment by Cheesebaron** [comment]
I'll see if I can get it done today or tomorrow
