### ISSUE TITLE
Do Plugins need a new home?

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#462]
We want to make it easy for others to contribute plugins.

We want to make it easy for others to find plugins.

Currently:

- there are some 'official' plugins in this repo
- there are some 3rd party plugins listed at the bottom of https://github.com/MvvmCross/MvvmCross/wiki/MvvmCross-plugins#other-plugins

How could we make this situation better/easier/more successful?

**Comment by martijn00** [comment]
New repo has been up for a while: https://github.com/MvvmCross/MvvmCross-Plugins
