### ISSUE TITLE
Platforms.iOS not found error in MVVMCross 7.1.2, 8.0.2 with .Net6.0-iOS

### ISSUE THREAD

**Issue by devikarna** [MvvmCross/MvvmCross#4624]
**Platform:** 
- [ ] :iphone: iOS

**Comment by evgenyvalavin** [comment]
.NET 6 is supported from [MvvmCross 9.0.0](HttpClient)

**Comment by Cheesebaron** [comment]
Not enough information to go from here. Update to MvvmCross 9 if you want to have support for the new NET6+ bits.

**Comment by Cheesebaron** [comment]
Closing as author hasn't responded
