### ISSUE TITLE
net6.0 or .net7.0 - The type or namespace name Platforms does not exist in the namespace MvvmCross

### ISSUE THREAD

**Issue by SprengerS** [MvvmCross/MvvmCross#4656]
## 🐛 Bug Report

A console project targeted  to net6.0 or .net7.0 can't be build with MvvmCross because Platforms namespace and all of its contents like a MvxConsoleSetup does not exists.

### Expected behavior
I was able to build Console Application with MvvmCross.

### Reproduction steps
* create new console app with rider and the following csproject file content
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MvvmCross" Version="9.0.10" />
    </ItemGroup>

</Project>

```
* install MvvmCross version 9.0.10
* try to inherit `MvxConsoleSetup` from `MvvmCross.Platforms.Console.Core`

 ### Configuration
Version: 9.0.10

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
It is right here: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Console/Core/MvxConsoleSetup.cs

**Comment by Cheesebaron** [comment]
OK after looking more closely, it seems like it is not included in the csproj. That should be easy to fix. I will have a look. Thank you for the report.

**Comment by Cheesebaron** [comment]
I will try to make a release this week, I have a bunch of other stuff in the pipeline.

**Comment by Cheesebaron** [comment]
OK, it is released https://www.nuget.org/packages/MvvmCross/9.1.0
