### ISSUE TITLE
MvxViewModel<TParameter> is instantiated twice and Prepare(TParameter) is not being invoked

### ISSUE THREAD

**Issue by evgenyvalavin** [MvvmCross/MvvmCross#4659]
## 🐛 Bug Report

I have an Activity which linked to an instance of `MvxViewModel<TParameter>`.
While navigating to the ViewModel this happens:
1. An instance of the ViewModel is created in `IMvxNavigationService.Navigate<ViewModel, TParameter>`
2. `MvxViewModel<TParameter>.Prepare(TParameter... )` is invoked to save the parameter
3. Second instance of the ViewModel is created in Activity.OnCreate(Bundle...)
4. `MvxViewModel<TParameter>.Prepare(TParameter... )` is **not invoked** which breaks the ViewModel

### Expected behavior
1. Only single instance of a `MvxViewModel<TParameter>` is instantiated.
2. `MvxViewModel<TParameter>.Prepare(TParameter... )` is a must to invoke.

### Reproduction steps
I'll update here as I figure out

### Configuration

**Version:** 9.1.0

**Platform:** 
- [ ] :robot: Android

**Comment by evgenyvalavin** [comment]
Could the bug be caused by #4650 ?

**Comment by Cheesebaron** [comment]
Could be, I will have to investigate what is up.

**Comment by evgenyvalavin** [comment]
> Are you implementing `IMvxOverridePresentationAttribute` on this one?

Nope, the Activity doesn't even have an Mvx Presentation attribute
```
[2023-08-01 06:48:57,621] VERB [1] - MvvmCross.Platforms.Android.Presenters.MvxAndroidViewPresenter
                                     PresentationAttribute not found for "CameraActivity". Assuming Activity presentation
[2023-08-01 06:48:57,687] VERB [1] - MvvmCross.Platforms.Android.Views.MvxAndroidViewsContainer
                                     Attempting to load new ViewModel from Intent with Extras
[2023-08-01 06:48:57,753] INFO [1] - WaiterAndroid.UI.Pages.Camera.CameraActivity
                                     CameraActivity: OnCreate invoked
```

**Comment by Cheesebaron** [comment]
You can work around this by adding this in Setup.cs `InitializeLastChance` override:

```csharp
iocProvider.RegisterType<IMvxSingleViewModelCache, MvxSingleViewModelCache>();
```

**Comment by Cheesebaron** [comment]
Yeah it is that PR that messed up the navigation for Activities if you have parameters. I will revert it and release a new version and rethink how I can solve this caching thing 🤔

**Comment by Cheesebaron** [comment]
I've release 9.1.1 which reverts my changes for removing the caching. Can you perhaps give it a spin and check if it fixes it? In my little sample in the Playground it seemed to fix the issue.

**Comment by evgenyvalavin** [comment]
Yup! I confirm it's been fixed
