### ISSUE TITLE
Changelog for 9.1.0. #4546 was actually fixed in 9.0.10

### ISSUE THREAD

**Issue by evgenyvalavin** [MvvmCross/MvvmCross#4660]
## 🐛 Bug Report

[9.1.0 Changelog](https://github.com/MvvmCross/MvvmCross/blob/develop/CHANGELOG.md#910-2023-07-27) lists a breaking change:
- Move Setup to MvxAndroidApplication +semver:breaking https://github.com/MvvmCross/MvvmCross/pull/4546 ([Cheesebaron](https://github.com/Cheesebaron))
which is confusing because the change was released in 9.0.10

### Expected behavior
Move the change to 9.0.10 version in the changelog.

**Comment by evgenyvalavin** [comment]
> I think for next release I will use the built in releases on GitHub instead.

Cool! I took time for me to remember to not open GitHub releases because there're no new releases there, haha.
So, using standard GitHub releases is a more straightforward way of doing a changelog than a changelog file in a Git (at least for me).

**Comment by Cheesebaron** [comment]
Just released 9.1.1 using Github Releases for this one 😎
