### ISSUE TITLE
[Android] SetIcon from ResourceId of Tab in TabLayout does not work

### ISSUE THREAD

**Issue by sewautztje** [MvvmCross/MvvmCross#4687]
## 🐛 Bug Report

While initialising the tab layout when setting the tab icons:
```
public TabLayout Tabs; // Tabs has already been initialised and is not null

Tabs.GetTabAt(int position).SetIcon(int resId);
```

the following exception occurs:

```
Java.Lang.NoSuchMethodError: no non-static method "Lcom/google/android/material/tabs/TabLayout$Tab;.setIcon(I)Lcom/google/android/material/tabs/TabLayout$Tab;"
   at Java.Interop.JniEnvironment.InstanceMethods.GetMethodID(JniObjectReference type, String name, String signature) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 11481
```

### Expected behavior
The expected behaviour is that the resource is set as an icon for the tab in the TabLayout. If one uses the method
```
Tabs.GetTabAt(int position).SetIcon(Drawable drawable);
```
an icon is set, but unfortunately I cannot use this method for my application.

In version 9.0.9 it still works perfectly. My guess is that it is a problem in the `Xamarin.Google.Android.Material`-Package, this was updated from `1.8.0.1` to `1.9.0.2` with the update to `MVVMCross 9.1.1`, due to a dependency.

### Configuration

**Version:** 9.1.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
This doesn't seem to be an error in MvvmCross code. Can you please provide more information of where you believe the error is in MvvmCross? Do you have a stack trace to which method in MvvmCross is setting the icon?

If you are setting it yourself, then where is MvvmCross at fault?

**Comment by sewautztje** [comment]
I also see that the bug is probably not in the MVVMCross code but in the Xamarin package, I'm just not able to downgrade the package because the version of MVVMCross uses it.... Is there a way to use the older version of the Xamarin.Google.Android.Material package anyway?

**Comment by Cheesebaron** [comment]
This happens both in debug and release mode for you?

If it doesn't happen in debug config, then it could be R8 stripping out the symbols.

As for downgrading, not sure NuGet will allow you to do so.
You could attempt to build MvvmCross yourself by checking out the repo, downgrading the one package in `Directory.Packages.props` and running `dotnet tool restore` then `dotnet cake`. It will produce nuget packages in the `artifacts` folder.

**Comment by sewautztje** [comment]
Many thanks for the quick feedback and successful help! The problem was indeed R8 stripping, after I added the corresponding classes to `proguard.cfg` it works again.
