### ISSUE TITLE
Sample project with XAML views on net6.0 and MvvmCross 9

### ISSUE THREAD

**Issue by ehuna** [MvvmCross/MvvmCross#4700]
Our team is ready to upgrade our current Xamarin Forms app currently on MvvmCross 8.0.2 to net6.0 and MvvmCross 9.

We typically like to start with a sample MvvmCross solution and project and then add our own ViewModels, Views, Services, etc.

- We started looking for a sample project in https://github.com/MvvmCross/MvvmCross-Samples
- We found https://github.com/MvvmCross/MvvmCross-Samples/tree/master/Starter but it does not contain any XAML views.
- We found https://github.com/MvvmCross/MvvmCross-Samples/tree/master/TipCalc which has multiple projects on net6.0 and MvvmCross 9, except we see no examples with XAML views.  We see the TipCalc.Forms.* projects are still on MvvmCross 8, as expected.

Does an example of a project on net6.0 and MvvmCross 9 with XAML views exist?

Or could TipCalc include such an example?

Our app has over 100 XAML views and is currently used on Production.  Although it will take some work, we feel that upgrading is worth it, and continuing to use MvvmCross for dependency injection, viewmodel navigation, binding, some of its plugins, and more is worth it - we have a lot of code that would need to be changed if we switched frameworks at this point.

**Comment by ehuna** [comment]
@Cheesebaron if needed we can maybe help with this work, we'll just need some guidance - not sure what is needed for have a couple of sample XAML views in the latest TipCalc projects on MvvmCross 9.

**Comment by Cheesebaron** [comment]
Forms support was discontinued, since Xamarin.Forms does not support .NET 6 or it didn't when I migrated. So decided at that time to remove it. Currently there is no MAUI support, so there is no migration path for your Forms App, except for redoing the ViewModel, DI and Navigation parts of your App.

**Comment by ehuna** [comment]
@Cheesebaron got it, we love MvvmCross, sad this is the end.

Do you have any recommendations for such a migration?  Should we use MAUI shell navigation or do you recommend another MVVM framework that would work with .NET 6/7/8 and would lower the migration effort?

Is a sample PR of such a move from Forms/MvvmCross to MAUI or some other framework available?  It could be some very simple project with just a couple of Views/ViewModels and DI & navigation migration.

I think on the DI we can handle - we'll switch to whatever is needed.  Not too sure about the XAML binding, converters, etc.

In MvvmCross the navigation is ViewModel based, but we are not sure then how would we work wit h

**Comment by ehuna** [comment]
> @Cheesebaron:
> [...] since Xamarin.Forms does not support .NET 6 or it didn't when I migrated.

A new .NET MAUI project today (.NET 6/7/8) does support XAML views out of the box - they look very similar to XAML views we see in Xamarin Forms 5.

**Comment by Cheesebaron** [comment]
It is not just about XAML and navigation support for MAUI. But it wouldn't integrate nicely at all with the hosting mechanism MAUI has.

So either way it has to wait for #4437 to get done. I've been working on it on and off, but it just has so many things it affects. So in the short term no MAUI UI framework support. Perhaps in the long term.

**Comment by ehuna** [comment]
@Cheesebaron Got it, thank you so much for everything you've done over the years on MvvmCross, our whole team appreciates it!
