### ISSUE TITLE
Language files are not loaded in iOS project / Degration #2678

### ISSUE THREAD

**Issue by muak** [MvvmCross/MvvmCross#4706]
## 🐛 Bug Report

JsonLocalication is throwing an exception "Failed to resolve type MvvmCross.Base.IMvxJsonConverter" in the LoadResources method and the Json dictionary is not created.

### Expected behavior

Load dictionaly from json

### Configuration

**Version:** 9.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

### Workaround

the same as #2678:

```cs
Mvx.IoCProvider.RegisterSingleton<IMvxJsonConverter>(new MvxJsonConverter());
```

**Comment by Cheesebaron** [comment]
Please try with 9.2.0
