### ISSUE TITLE
MvxImageView - loading local images more efficiently using expected width and height

### ISSUE THREAD

**Issue by gentledepp** [MvvmCross/MvvmCross#471]
I recently looked into your MvxImaveView to see if it is able to load local images, which it is.
However, it does not seem to follow the recipe "Load Large Bitmaps Efficiently" from Xamarin (http://docs.xamarin.com/recipes/android/resources/general/load_large_bitmaps_efficiently)

Everything that I would need to do, is to additionally pass in the width and height of an MvxImageView if its size is fixed. On other platforms these parameters could just be omitted.

Therefore I would need to add overloads for:

IMvxImageHelper.ImageUrl

which had to look like the following

IMvxImageHelper.SetImageUrl(string path, double width, double height)

as well as

IMvxLocalFileImageLoader.Load(string localPath, bool shouldCache);

and

MvxImageView.ImageUrl

the code that I would like to introduce seems pretty simple, to get through these two simple parameters I'd need to change the interfaces quite a bit.

Would it be ok, if I added that functionality in some MvvmCross branch on github?
If so - is there any guide for contributors like me? I am new to github. :/

**Comment by roubachof** [comment]
@Cheesebaron @gentledepp seems to me that it will work if you set MaxWidth and MaxHeight on the ImageView.

```
android:maxHeight="100px"
android:maxWidth="250px"
```

If you look at:

https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/DownloadCache/MvvmCross.Plugins.DownloadCache.Droid/MvxAndroidLocalFileImageLoader.cs#L79

You will see that it implements the recipe.

**Comment by gentledepp** [comment]
I guess that even is my implementation ;-)
so you can close this issue

**Comment by roubachof** [comment]
Added documentation on this to [mvvmcross DownloadCache Plugin doc](http://mvvmcross.com/docs/downloadcache)

**Comment by pedrofmvcmartins** [comment]
The documentation seems misleading now. The recipe only applies to MvxAndroidLocalFileImageLoader, which is only called if the URI is not Http. I can't find where it is applying the scale if you request a remote image.

A remote image uses MvxImageCache, which doesn't have size information and then only calls Parse which uses MvxAndroidLocalFileImageLoader with loader.Load(path, false, 0, 0) so no resizing here.

How do we add resizing to a remote (not local image)?
