### ISSUE TITLE
MvxApplication.Initialize runs on main thread

### ISSUE THREAD

**Issue by NoahSurprenant** [MvvmCross/MvvmCross#4716]
### Old (and correct) behavior
MvxApplication.Initialize is called on background thread

### Current behavior
MvxApplication.Initialize is called on main thread

### Reproduction steps

1. Fork Mvvm-Cross samples.
2. Update TipCalc app to 9.0.10.
3. Update the SplashScreen's base class from MvxSplashScreenActivity to MvxStartActivity.
4. App.Initialize now runs on the main thread

Example:
https://github.com/NoahSurprenant/MvvmCross-Samples

### Configuration

**Version:** >=9.0.10

**Platform:** 
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :iphone: iOS
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
It doesn't have anything to do with the naming change of MvxSplashScreenActivity to MvxStartActivity.

It is because instead of calling `EnsureInitialized` from the Splash/Start Activity this is now done through `MvxAndroidApplication` in `OnCreate`.

What is the _issue_ you are having?

**Comment by NoahSurprenant** [comment]
Closing this issue. Recommended path forward is to not use MvxStartActivity to draw to the screen
