### ISSUE TITLE
Crash on mapping 2 views to same view model in iOS

### ISSUE THREAD

**Issue by pranavtiwa** [MvvmCross/MvvmCross#4717]
## 🐛 Bug Report

Crash on mapping 2 views to same view model 
exception:Message	"Problem seen creating View-ViewModel lookup table - you have more than one View registered for the ViewModels	

### Expected behaviour
App should not crash and accept 2 different views (1 for iPad ,1 for iPhone )
### Reproduction steps
Create 2 views with different name and map them to same view model 
### Configuration

.net 7 Net for iOS 

**Version:** 6.x
MVVMCross -9.1.1
**Platform:** 
- [ ] :iphone: iOS

**Comment by Cheesebaron** [comment]
This has always been like this, not a bug. Rather a limitation of the ViewModel to View mapper.

**Comment by pranavtiwa** [comment]
No we have a way to implement it and I was using it till 8.0 .. anyways I
was able to resolve it thanks
