### ISSUE TITLE
MvvmCross.Plugin.Visibility not working in .NET 7.0 Android Project

### ISSUE THREAD

**Issue by codeanees** [MvvmCross/MvvmCross#4736]
## 🐛 Bug Report

We are porting existing Xamarin.Android project to .NET 7.0 Android Project.  Everything went smooth until we face an issue with MvvmCross.Plugin.Visibility plugin.  The controls are not hiding/visible using the plugin from xml layout file.
### Expected behavior
Controls should hide from xml layout using Mvx Binding
Eg: 
local:MvxBind="Visibility Visibility(MyViewModelProperty)"

### Reproduction steps
1. Download the attached zip folder below(TestMvvmCrossVisibility.zip)
2. Run and click on the "hide" button.
3. The code should hide the label below but it is not hiding.
### Configuration

**Version:** 7.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Sample Project to Reproduce the Issue:**
[TestMvvmCrossVisibility.zip](https://github.com/MvvmCross/MvvmCross/files/13030995/TestMvvmCrossVisibility.zip)

**Comment by codeanees** [comment]
@Paul-N no luck :-) Same issue persists after loading the plug-in.  I see the plugin in LoadPlugins() method. Please refer the screenshot attached.

<img width="968" alt="Screenshot 2023-10-19 at 7 05 27 PM" src="https://github.com/MvvmCross/MvvmCross/assets/16783086/91e9f0f0-4ae5-4cb8-a68d-ad5f231bee0c">

**Comment by Paul-N** [comment]
´´´
using System;
using System.Reflection;
using Android.Util;
using Microsoft.Extensions.Logging;
using MvvmCross.Converters;
using MvvmCross.Platforms.Android.Core;
using MvvmCross.Plugin;
using Serilog;
using Serilog.Extensions.Logging;

namespace TestMvvmCrossVisibility
{
    public class Setup : MvxAndroidSetup<App>
    {
        protected override ILoggerProvider CreateLogProvider()
        {
            return new SerilogLoggerProvider();
        }

        protected override ILoggerFactory CreateLogFactory()
        {
            // serilog configuration
            Serilog.Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.AndroidLog()
                .CreateLogger();

            return new SerilogLoggerFactory();
        }

        public override IEnumerable<Assembly> GetPluginAssemblies() 
            => base.GetPluginAssemblies().MergeWith(typeof(global::MvvmCross.Plugin.Visibility.MvxVisibilityValueConverter));

        protected override void FillValueConverters(IMvxValueConverterRegistry registry)
        {
            base.FillValueConverters(registry);
            registry.AddOrOverwrite("Visibility", new global::MvvmCross.Plugin.Visibility.MvxVisibilityValueConverter());
        }
    }

    internal static class Utils
    {
        public static IEnumerable<Assembly> MergeWith(this IEnumerable<Assembly> assemblies, params Type[] types)
        {
            var result = assemblies.ToList();
            result.AddRange(types.Select(t => t.Assembly));
            return result;
        }
    }
}

´´´
This workaround fixed the problem. Something wrong with both plugin loading and value converter loading. I don´t even see code for value converter registering in the Visibility Plugin. May be I missing something, I dunno

**Comment by codeanees** [comment]
@Paul-N Thanks a lot!  You saved my day!  The workaround fixes the problem with Visibility Plugin.  

However, I have the same issue with Color Plugin.  I tried the workaround and ensure both Color plugin and Value converters loading.  Still it doesn't work. Could you please help me on this?

Updated the sample with Color plugin example.

[TestMvvmCrossVisibility_withColorPlugin.zip](https://github.com/MvvmCross/MvvmCross/files/13045670/TestMvvmCrossVisibility_withColorPlugin.zip)

**Comment by Paul-N** [comment]
```csharp
using System.Reflection;
using Android.Views;
using Microsoft.Extensions.Logging;
using MvvmCross.Binding.Bindings.Target.Construction;
using MvvmCross.Converters;
using MvvmCross.Platforms.Android.Core;
using MvvmCross.Plugin.Color;
using MvvmCross.Plugin.Color.Platforms.Android.BindingTargets;
using MvvmCross.Plugin.Visibility;
using Serilog;
using Serilog.Extensions.Logging;

namespace TestMvvmCrossVisibility
{
    public class Setup : MvxAndroidSetup<App>
    {
        protected override ILoggerProvider CreateLogProvider()
        {
            return new SerilogLoggerProvider();
        }

        protected override ILoggerFactory CreateLogFactory()
        {
            // serilog configuration
            Serilog.Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.AndroidLog()
                .CreateLogger();

            return new SerilogLoggerFactory();
        }

        public override IEnumerable<Assembly> GetPluginAssemblies()
            => base.GetPluginAssemblies().MergeWith(typeof(MvxVisibilityValueConverter),
                                                    typeof(MvxColorValueConverter));

        protected override void FillValueConverters(IMvxValueConverterRegistry registry)
        {
            base.FillValueConverters(registry);
            registry.AddOrOverwrite("Visibility", new MvxVisibilityValueConverter());
            registry.AddOrOverwrite("CurrentStatusText", new CurrentStatusTextValueConverter());
        }

        protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            base.FillTargetFactories(registry);
            registry.RegisterFactory(new MvxCustomBindingFactory<View>(
                "BackgroundColor",
                view => new MvxViewBackgroundColorBinding(view)));
        }
    }

    internal static class Utils
    {
        public static IEnumerable<Assembly> MergeWith(this IEnumerable<Assembly> assemblies, params Type[] types)
        {
            var result = assemblies.ToList();
            result.AddRange(types.Select(t => t.Assembly));
            return result;
        }
    }
}

```
Please use github for source code

**Comment by codeanees** [comment]
@Paul-N Thanks a lot for your time and help. It works! 
@Cheesebaron  Please check the issue details and workaround.  May be we need to find actual issue and resolve it.

**Comment by codeanees** [comment]
@Cheesebaron In which version I can test this? Please advise

**Comment by Cheesebaron** [comment]
Building 9.2.0-beta.3 now
