### ISSUE TITLE
MAUI App that uses existing MVVMCross ViewModels - Fails with mismatch in Dependencies for Android as Target

### ISSUE THREAD

**Issue by revred** [MvvmCross/MvvmCross#4759]
## 🐛 Bug Report

I have an existing WPF application where the view models are borrowed from a Plugin Architecture. The ViewModels are all derived from MvxViewModel. This is a dependency that cannot be easily removed. 

On creating a vanilla MAUI Application using Visual Studio 2022 (Version 17.7.6), there is a conflict in the dependencies of MAUI project and the plugin central framework that uses MVVMCross and MVVMCross.Plugin.Messenger. 

To isolate the problem, I have created a simple Visual Studio solution [here](https://github.com/revred/MAUI.Cross).

The conflict is related to the mismatch in versions of a deeper dependency which results in a message that is shown below

```
2>D:\code\TestMaui\MAUI.Cross\MAUI.Cross\MAUI.Cross.csproj : error NU1605: Warning As Error: Detected package downgrade: Xamarin.Google.Android.Material from 1.9.0.2 to 1.7.0. Reference the package directly from the project to select a different version. 
2>D:\code\TestMaui\MAUI.Cross\MAUI.Cross\MAUI.Cross.csproj : error NU1605:  MAUI.Cross -> MVCX.Model -> MvvmCross 9.1.1 -> Xamarin.Google.Android.Material (>= 1.9.0.2) 
2>D:\code\TestMaui\MAUI.Cross\MAUI.Cross\MAUI.Cross.csproj : error NU1605:  MAUI.Cross -> Xamarin.Google.Android.Material (>= 1.7.0)
2>D:\code\TestMaui\MAUI.Cross\MAUI.Cross\MAUI.Cross.csproj : error NU1605: Warning As Error: Detected package downgrade: Microsoft.WindowsAppSDK from 1.3.230724000 to 1.2.221209.1. Reference the package directly from the project to select a different version. 
2>D:\code\TestMaui\MAUI.Cross\MAUI.Cross\MAUI.Cross.csproj : error NU1605:  MAUI.Cross -> MVCX.Model -> MvvmCross 9.1.1 -> Microsoft.WindowsAppSDK (>= 1.3.230724000) 
2>D:\code\TestMaui\MAUI.Cross\MAUI.Cross\MAUI.Cross.csproj : error NU1605:  MAUI.Cross -> Microsoft.WindowsAppSDK (>= 1.2.221209.1)
2>Done building project "MAUI.Cross.csproj" -- FAILED.
```
I have tried upgrading/downgrading MAUI Nuget Package but this was not resolved. I have also tried to check if I can change the framework to use a specific version of Xamarin.Google.Android.Material but there is no option to do this.

If I remove the .NET7 android target framework, then the application builds with no issues.

### Expected behavior

I would expect the MAUI application with target as android to work with MVVMCross view models just like it behaves with Mac or Windows.

### Reproduction steps

Create a .NET MAUI App in Visual Studio
Create a viewModel in a separate C# dotNET library that is derived from MvxViewModel. Install the nuget packages of MVVMCross and MVVMCross.Plugin.Messenger in that C# library. 
Use this viewModel for a page that is rendered in MAUI. 

Build and check the errors.

### Configuration
MVVMCross Version 9.0.*
MVVMCross.Plugin.Messenger Version 9.0.*

### Platform

Application created on a windows machine with target as android.
Visual Studio 2022 - Version 17.7.6

**Comment by Cheesebaron** [comment]
When you write MAUI. What do you mean? Is it an App with the MAUI UI framework, or is it an App that targets `net7.0-android` and you are using MAUI Essentials?

On .NET 7 targets, MAUI and MAUI Essentials are referenced implicitly and won't work with MvvmCross as we are not using the same versions of AndroidX packages and in some cases newer.

In .NET 8 how MAUI and MAUI Essentials is pulled in is happening through NuGet packages, which will fix these downgrade conflicts.

We have no official support for MAUI UI Framework and you mileage may vary with MAUI Essentials on .NET 7 targets.

**Comment by revred** [comment]
> When you write MAUI. What do you mean? Is it an App with the MAUI UI framework, or is it an App that targets `net7.0-android` and you are using MAUI Essentials?
> 
> On .NET 7 targets, MAUI and MAUI Essentials are referenced implicitly and won't work with MvvmCross as we are not using the same versions of AndroidX packages and in some cases newer.
> 
> In .NET 8 how MAUI and MAUI Essentials is pulled in is happening through NuGet packages, which will fix these downgrade conflicts.
> 
> We have no official support for MAUI UI Framework and you mileage may vary with MAUI Essentials on .NET 7 targets.

It is the standard MAUI app that is created by using MAUI app template on visual studio. It target's all platforms including android.

**Comment by Cheesebaron** [comment]
That is not officially supported. It may work if you target .NET 8.

**Comment by revred** [comment]
> That is not officially supported. It may work if you target .NET 8.

I can live with a workaround if that is something the mvvmcross community can look to provide. There is a link to a simple VS solution in the question to reproduce.

**Comment by Cheesebaron** [comment]
If you are targeting desktop you are better off using WPF or WinUI.

**Comment by revred** [comment]
> If you are targeting desktop you are better off using WPF or WinUI.

If the target I require is android, then WPF is out. Hope the question is clear. There is a dependency conflict specific to android as the target platform.

**Comment by Cheesebaron** [comment]
You can use `net7.0-android` or `net8.0-android` without adding the MAUI UI framework. See: https://github.com/MvvmCross/MvvmCross/blob/develop/Projects/Playground/Playground.Droid/Playground.Droid.csproj
