### ISSUE TITLE
MvxModalPresentationControllerDelegate closes a ViewController when the ViewController is not actually dismissed by a user

### ISSUE THREAD

**Issue by evgenyvalavin** [MvvmCross/MvvmCross#4781]
## 🐛 Bug Report
There is a change when to call the MvxIosViewPresebnter.CloseModalViewController() #4554 
Calling the method in UIAdaptivePresentationControllerDelegate.WillDismiss() is not appropriate, because WillDismiss() can be called multiple times and, most importantly, a UIAdaptivePresentationControllerDelegate.DidDismiss() could not be called after all because a user can stop dragging or prevent dismissal of a ViewController. Calling CloseModalViewController() in WillDismiss() causes the ViewController to close which is not desired UX.
![image](https://github.com/MvvmCross/MvvmCross/assets/35497422/afd80230-295e-4bcb-bcb7-d3a4494a70c3)
[WWDC 2019.](https://developer.apple.com/videos/play/wwdc2019/224) Start from 17:15

### Expected behavior
Do not close a ViewController when a user stopped playing (dragging up-down) the ViewController without dismissing it.

**Version:** 9.1.1

**Platform:** 
- [ ] :iphone: iOS

**Comment by evgenyvalavin** [comment]
The solution seems to be pretty easy. I'll get to it a little bit later

**Comment by Cheesebaron** [comment]
Released in: https://github.com/MvvmCross/MvvmCross/releases/tag/9.2.0-beta.5
