### ISSUE TITLE
Plugins not working on Android in 9.2.0-beta5

### ISSUE THREAD

**Issue by greg73** [MvvmCross/MvvmCross#4797]
## 🔙 Regression

Color and Visibility plugins are no longer working on Android in release/9.2.0 branch

### Old (and correct) behavior

Binding color and visiblity possible

### Current behavior

Bind color and visiblity has no effect

### Reproduction steps

Pull release/9.2.0 branch
Run Playground.Droid in emulator
Converters - Toggle visibility or Toggle color
No effect

Working in develop branch

### Configuration

Android emulator on Windows running API 33

**Version:** 9.2.0-beta5

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Update to 9.2.0-beta.6 should work there

**Comment by greg73** [comment]
Thank you for the quick fix. Do you have an ETA for 9.2.0 full release?

**Comment by Cheesebaron** [comment]
Not really, does it matter much to you whether the version has -beta at the end or not?

**Comment by Cheesebaron** [comment]
@EtienneDuport create a new issue please.
