### ISSUE TITLE
MvxColorValueConverter not working on Android in 9.2.0

### ISSUE THREAD

**Issue by greg73** [MvvmCross/MvvmCross#4803]
## 🔙 Regression

I may be missing something, but it appears that MvxColorValueConverter is not working on Android in 9.2.0

### Reproduction steps

Pull https://github.com/greg73/MvvmCross.git
Checkout branch color-converter-issue
This has been modified to bind to the string property ColorText

Run Playground.Droid
Click on converters
Color text is not visible and doesn't change color when clicking the button

### Configuration

9.2.0-beta6
Android SDK 33

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
In the CollectionView sample in Playground.Droid it works fine. The favorite color is bound to a color in the VM.

![Screenshot_1706097909](https://github.com/MvvmCross/MvvmCross/assets/249719/bccc517d-9977-4d2d-b523-c40b41dafa0b)

Also works fine in the original Converters sample.

https://github.com/MvvmCross/MvvmCross/assets/249719/854ae543-8a9d-4143-9a06-80a14e571ee9

I need a bit more info.

**Comment by greg73** [comment]
Hi @Cheesebaron 

I've created a value converter derived from MvxColorValueConverter which is trying to bind the string in the VM to a native color.

```
    public class TextToColorValueConverter : MvxColorValueConverter
    {
        protected override Color Convert(object value, object parameter, CultureInfo culture)
        {
            switch (value.ToString())
            {
                case "I am green!":
                    return Color.Green;
                case "I am yellow!":
                    return Color.Yellow;
                case "I am brown!":
                    return Color.Brown;
                case "I am orange!":
                    return Color.Orange;
                default:
                    return Color.Black;
            }
        }
    }
```

Setup

```
        protected override void FillValueConverters(IMvxValueConverterRegistry registry)
        {
            registry.AddOrOverwrite("TextToColor", new TextToColorValueConverter());
        }
```
Layout activity_converters.xml

```
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        local:MvxBind="Text ColorText; TextColor TextToColor(ColorText)"/>
```

Text shows in white as the value converter is not being called
![image](https://github.com/MvvmCross/MvvmCross/assets/20475959/9927ede3-9274-49ad-815a-c72d3ceae408)

**Comment by Cheesebaron** [comment]
```csharp
        protected override void FillValueConverters(IMvxValueConverterRegistry registry)
        {
            registry.AddOrOverwrite("TextToColor", new TextToColorValueConverter());
        }
```

This is probably your issue. You are not calling `base.FillValueConverters(registry);`

**Comment by greg73** [comment]
Workaround is to use a normal value converter (i.e. derived from MvxValueConverter not MvxColorValueConverter) and then to wrap in NativeColor as per your suggestion above.

**Comment by Cheesebaron** [comment]
I Will dig into the issue. Thanks for the extra info 😀

**Comment by Cheesebaron** [comment]
This should be fixed in beta.7. Can you please try that?

**Comment by greg73** [comment]
Thanks, that's fixed it

**Comment by ivmirx** [comment]
Hmm, same problem for me while moving from Xamarin and MvvmCross 8  to .NET 8 and MvvmCross 9.2: `FillValueConverters()` is called before `LoadPlugins()`, and then this code in `OnCreateView()` without a custom color value converter

    var nativeColorConverter = new MvxNativeColorValueConverter();
    set.Bind(_view).For(v => v.BindBackgroundColor()).To(vm => vm.Theme.Background).WithConversion(nativeColorConverter);

…leads to:

    Failed to create target binding for binding BackgroundColor for Theme.Background
    Problem seen during binding execution for Theme.Background - problem MvxIoCResolveException: Failed to resolve type MvvmCross.UI.IMvxNativeColor
           at MvvmCross.IoC.MvxIoCContainer.Resolve(Type type) in /_/MvvmCross/IoC/MvxIoCContainer.cs:line 256
       at MvvmCross.IoC.MvxIoCContainer.Resolve[IMvxNativeColor]() in /_/MvvmCross/IoC/MvxIoCContainer.cs:line 247
       at MvvmCross.IoC.MvxIoCProvider.Resolve[IMvxNativeColor]() in /_/MvvmCross/IoC/MvxIoCProvider.cs:line 64
       at MvvmCross.Plugin.Color.MvxColorValueConverter.<>c.<.ctor>b__3_0() in /_/MvvmCross.Plugins/Color/MvxColorValueConverter.cs:line 13
       at System.Lazy`1[[MvvmCross.UI.IMvxNativeColor, MvvmCross, Version=9.2.0.0, Culture=neutral, PublicKeyToken=null]].ViaFactory(LazyThreadSafetyMode mode)
       at System.Lazy`1[[MvvmCross.UI.IMvxNativeColor, MvvmCross, Version=9.2.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
       at System.Lazy`1[[MvvmCross.UI.IMvxNativeColor, MvvmCross, Version=9.2.0.0, Culture=neutral, PublicKeyToken=null]].CreateValue()
       at System.Lazy`1[[MvvmCross.UI.IMvxNativeColor, MvvmCross, Version=9.2.0.0, Culture=neutral, PublicKeyToken=null]].get_Value()
       at MvvmCross.Plugin.Color.MvxColorValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in /_/MvvmCross.Plugins/Color/MvxColorValueConverter.cs:line 20
       at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.ApplyValueConverterSourceToTarget(Object value) in /_/MvvmCross/Binding/Bindings/SourceSteps/MvxSourceStep.cs:line 94

At the same time, trying to call `Mvx.IoCProvider.Resolve<IMvxPluginManager>().EnsurePluginLoaded<MvvmCross.Plugin.Color.Platforms.Android.Plugin>();` before `FillValueConverters();` also does not work and gets a warning "No binding registry available - so color bindings will not be used".

A bit of a vicious circle here, I guess. I've verified all the `base` calls in `Setup` and `App`, but at the same time it worked before, so not sure if I'm doing something wrong.

**Comment by Cheesebaron** [comment]
@ivmirx In the RecyclerView sample in the Playground I have color plugin working just fine. There I simply ensure the plugin is loaded in `LoadPlugin`:

https://github.com/MvvmCross/MvvmCross/blob/develop/Projects/Playground/Playground.Droid/Setup.cs#L36-43

Do you have other overrides in your `Setup.cs` that might impact any of the loading?

**Comment by ivmirx** [comment]
@Cheesebaron I managed to reproduce it in a test project, pretty close to how I do things in the big app (there I have almost no customizations during the launch, aside from registering singletons and creating a custom view presenter):

[ColorTest.zip](https://github.com/user-attachments/files/15797993/ColorTest.zip)

In `FragmentView`, the binding to the `TitleColor` throws the same exception I posted earlier.

**Comment by Cheesebaron** [comment]
Thanks @ivmirx I will have a look at what is going on

**Comment by Cheesebaron** [comment]
> @Cheesebaron I managed to reproduce it in a test project, pretty close to how I do things in the big app (there I have almost no customizations during the launch, aside from registering singletons and creating a custom view presenter):
> 
> [ColorTest.zip](https://github.com/user-attachments/files/15797993/ColorTest.zip)
> 
> In `FragmentView`, the binding to the `TitleColor` throws the same exception I posted earlier.

So in this sample. If in `Setup.cs` I add:

```csharp
    public override void LoadPlugins(IMvxPluginManager pluginManager)
    {
        base.LoadPlugins(pluginManager);
        pluginManager.EnsurePluginLoaded<MvvmCross.Plugin.Color.Platforms.Android.Plugin>();
    }
```

Then it works just fine:

![Screenshot_1718263899](https://github.com/MvvmCross/MvvmCross/assets/249719/4ae4f3f6-b0a6-4ce9-8fe3-435996674ed9)

**Comment by entdark** [comment]
Don't they suppose to get loaded automatically?

**Comment by ivmirx** [comment]
@Cheesebaron damn, I was sure I've tried it at some point, but apparently not. My app managed to load the plugin too and I fixed `Plugin.Visibility` the same way. Thank you!

**Comment by Cheesebaron** [comment]
> Don't they suppose to get loaded automatically?

They were, but Assembly scanning doesn't work properly on all platforms.
