### ISSUE TITLE
[Bug]: Failed to register an instance of MvxValueConverter with no default constructor

### ISSUE THREAD

**Issue by evgenyvalavin** [MvvmCross/MvvmCross#4836]
### Description

```
MvxBind Failed to register "BoolValueToColor" from "BoolValueToColorConverter"
System.MissingMethodException: Arg_NoDefCTor, WaiterAndroid.UI.Converters.ColorConverters.BoolValueToColorConverter
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at MvvmCross.Binding.Binders.MvxNamedInstanceRegistryFiller`1[[MvvmCross.Converters.IMvxValueConverter, MvvmCross, Version=9.2.0.0, Culture=neutral, PublicKeyToken=null]].FillFrom(IMvxNamedInstanceRegistry`1 registry, Assembly assembly)
```

```
public class BoolValueToColorConverter(int colorForTrue, int colorForFalse) : MvxValueConverter<bool, Color?>
{
    protected readonly int _colorForTrue = colorForTrue;

    protected override Color? Convert(bool value, Type? targetType, object? parameter, CultureInfo? culture)
        => Platform.CurrentActivity?.CompatGetColor(value ? _colorForTrue : colorForFalse);
}
```

The issue did not break anything because an instance of such classes is created manually in the code. The only thing is the error message started to appear in logs which confuses everyone.

### Steps to Reproduce

1. Add a ctor with parameters to a class derived from MvxColorConverter
2. Start the app.
3. The issue will be logged.

### Version with bug

9.2.0

### Is this a regression from previous behavior?

Yes, this used to work in a previous version

### Last version that worked well

8.0.0

### Affected platforms

Android

**Comment by Cheesebaron** [comment]
I think it is just surfacing the Exception, while previously it would just squelch it. In 8.0.0 it wouldn't register the ValueConverter either to use in bindings if it had ctor parameters as we rely on `Activator.CreateInstance` to create the instance of the value converter.

So the change is just we now log the message. If you are not interested in that, configure your logger to ignore these.
