### ISSUE TITLE
MvvmCross.Platforms.Ios namespace is missing in 9.2.0 & 9.2.0-beta

### ISSUE THREAD

**Issue by viswanath-pamarthi** [MvvmCross/MvvmCross#4837]
### Description

iOS namespace is missing under MvvmCross.Platforms, below is the screenshot of build errors:

![image](https://github.com/MvvmCross/MvvmCross/assets/24984365/a7322ec8-d628-4186-869f-8f5da3ab9b38)

### Steps to Reproduce

1. Download MvvmCross-Starter project from mvvmcross  samples repo,
2. Either upgrade mvvmcross nuget packages to latest stable version 9.2.0 from 9.2.0-beta7 or run as is.
3. Build the project for iOS and you will see build errors stating "ios" namespace is missing under MvvmCross.Platforms

### Link to public reproduction project repository

https://github.com/MvvmCross/MvvmCross-Samples/tree/master/Starter

### Version with bug

9.2.0

### Is this a regression from previous behavior?

Yes, this used to work in a previous version

### Last version that worked well

8.0.0

### Affected platforms

iOS/MacCatalyst

**Comment by Cheesebaron** [comment]
Update your dotnet workloads.

This was also asked here: https://github.com/MvvmCross/MvvmCross/discussions/4831

**Comment by viswanath-pamarthi** [comment]
Thanks for the quick response, I was able to get it work.
