### ISSUE TITLE
Make Android view inflation more customisable

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#491]
Currently we don't really use IoC much during View inflation. We should make interception of View creation more customisable.

This is "just refactoring" (TM).

http://stackoverflow.com/questions/19938718/im-trying-to-use-a-layoutinflator-factory-with-mvvmcross-but-it-isnt-working/19948295#19948295

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross/pull/1022
