### ISSUE TITLE
Support Nullable types in Navigation parameters

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#505]
To get `DateTime?` working we had to add:

        public class ExtraParser : MvxStringToTypeParser.IExtraParser
        {
            public bool Parses(Type t)
            {
                return (t == typeof (DateTime?));
            }

            public object ReadValue(Type t, string input, string fieldOrParameterName)
            {
                if (string.IsNullOrEmpty(input))
                    return null;
                return DateTime.Parse(input);
            }
        }

        protected override Cirrious.MvvmCross.Platform.MvxStringToTypeParser CreateStringToTypeParser()
        {
            var toReturn = base.CreateStringToTypeParser();
            toReturn.ExtraParsers.Add(new ExtraParser());
            return toReturn;
        }

Would be "nice" if we could support this in the default?

Also linking this to https://github.com/MvvmCross/MvvmCross/issues/450

**Comment by martijn00** [comment]
https://github.com/MvvmCross/MvvmCross/pull/1284
