### ISSUE TITLE
Feature Requests: MultiLine TextEdit and Double button element for ios dialog

### ISSUE THREAD

**Issue by wayne-o** [MvvmCross/MvvmCross#522]
Is there any chance we could have a multiline text element and also an element where there are 2 buttons side by side?

I have tried doing both with no luck.

Here is my multiline element - the model never reflects the value in the field though: 
http://pastebin.com/DSyWYxaD

and here is my start of the double button element - though this is miles off - not sure how I would detect which button was clicked:

http://pastebin.com/xSFNjPhp

Any help would be really really appreciated.

**Comment by kjeremy** [comment]
CrossUI/Dialog were removed in 41f191574d11e6e1a664336e7108cfa1e59a4383
