### ISSUE TITLE
CallerMemberAttribute

### ISSUE THREAD

**Issue by xperiandri** [MvvmCross/MvvmCross#536]
As MVVMCross moves to Profile158 with Microsoft.BCL.Build usage, is it possible to add a method to use CallerMemberAttribute instead of lambdas in MvxNotifyPropertyChanged? 

Like it is done in PRISM for WinRT.
```C#
protected virtual bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null)
{
    if (object.Equals(storage, value)) return false;

    storage = value;
    this.OnPropertyChanged(propertyName);

    return true;
}
```

Will this work on iOS and Android?

**Comment by martijn00** [comment]
I see the current profile is Profile 259 does that change anything?

**Comment by Cheesebaron** [comment]
It has been implemented: https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross/ViewModels/MvxNotifyPropertyChanged.cs#L87
