### ISSUE TITLE
MvxGridView: can not set gravity of child items because of proxied FrameLayout

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#539]
This may be an improvement more than a bug.

MvxGridView template items are inflated and put as child of a FrameLayout derived class. In a gridview, the child size and position is controlled by the android:gravity property on direct child items.

Because of the proxy FrameLayout, direct childs are not the templated elements but the FrameLayout elements.

There are 3 solutions here:

1) set android:gravity on the MvxGridView: all direct childs will inherit this property. This is currently the only way to make MvxGridView work.

2) In MvxGridView, after inflating, copy the inflated view's LayoutParameters in the proxy FrameLayout. Well this is a hack :) But better than nothing.

3) Remove the FrameLayout proxy. To store the item's data, use the Tag on the inflated view (Settag("somename", itemDataObject).

**Comment by MarcBruins** [comment]
This bug/feature is almost the same as #1451 and has been resolved in this PR #1465 (option 3 is used)
