### ISSUE TITLE
Bluetooth BLE Support

### ISSUE THREAD

**Issue by Rainburst** [MvvmCross/MvvmCross#543]
Are you guys planning to add cross platform BLE API? Though it is not simple (there are at least 2 SDKs android), I guess it'd be great to have one.

**Comment by georgeedwards** [comment]
It would be great to see this. It might also be worth noting the Monkey.Robotics project that Xamarin started, but now seems to have been dropped. It contains a cross-platform solution for Bluetooth LE on iOS and Android (as far as I know).

**Comment by martijn00** [comment]
We have no plans to develop this. You can as you point out use the external plugin: https://github.com/xabre/MvvmCross-BluetoothLE/
