### ISSUE TITLE
Allow Json Language resources to be loaded from EmbeddedResource files

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#55]
Following up from this StackOverflow post (http://stackoverflow.com/questions/13455635/mvvmcross-localization-switch-at-runtime) one thing that occurred to me is that we don't really need to load Mvx Json text files from UI projects any more.

Instead I think we could quite happily use EmbeddedResource files within the Core/ViewModel project.

To make this work, we'd need to change GetTextResource so that it can use the EmbeddedResource code instead of Resource (Asset/Content based code).

Should be easy enough to do.... obviously would want to make it switchable so that old code carries on working...

**Comment by AhmedWarreth** [comment]
Can i now use JSON files in the PCL for localisation? any examples? cheers

**Comment by martijn00** [comment]
This is already possible.
