### ISSUE TITLE
Update ToDo-MvvmCross text files in NuGet packages

### ISSUE THREAD

**Issue by dsplaisted** [MvvmCross/MvvmCross#562]
The "getting started" / ToDo text files in MvvmCross.HotTuna.StarterPack don't exactly match up with what you actually need to do.  For example, in a PCL project, the first step listed is to create a ViewModels folder and add a ViewModel to it.  However, this is already added automatically by the NuGet package.  Likewise for a lot of the other steps.

**Comment by martijn00** [comment]
Todo files seems good enough to me. Closing this for now.
