### ISSUE TITLE
Can't pass decimal type in ViewModel Init function

### ISSUE THREAD

**Issue by RanaInside** [MvvmCross/MvvmCross#564]
This is with passing values in .Init; consider the following code:

```
var balance = result.Result.ToString("F");
ShowViewModel<TopupCompletedViewModel>(new { completedType = TopupCompletedViewModel.TopupCompletedType.PromoCode, balance });
```
- so to my viewModel, I am passing an enum value, and a decimal value (converted to string here); with my .Init(TopupCompletedType cType, string balance), I get the correct value.

But if my code is like:

```
var balance = result.Result;
ShowViewModel<TopupCompletedViewModel>(new { completedType = TopupCompletedViewModel.TopupCompletedType.PromoCode, balance });
```
- and this time my viewModel has .Init(TopupCompletedType cType, decimal balance), I get balance = 0

For the time being, I am passing it as string, but that feels kind of ugly :)

**Comment by alxbog** [comment]
Is it still an issue? Current we use `decimal` manual serialization/deserialization and it looks terrible.

**Comment by martijn00** [comment]
Currently you can use a the `ShowViewModel<SomeViewModel, SomeObject>(TheObject);`to pass in complex object types to a new viewmodel.

**Comment by alxbog** [comment]
@martijn00 Thanks for your reply.

Is `ShowViewModel<SomeViewModel, SomeObject>(TheObject);` documented anywhere? As I see we should use Json plugin to use it. And the main problem is that you should implement `IMvxViewModelInitializer<TInit>` with `Init(string)` method.

Why `Init(string)`, not `Init(TInit)`?

I also see this `Init` should return `Task`. We can you async/await with `Init` method now, right? Is it documented?

**Comment by martijn00** [comment]
More information can be found here: https://github.com/MvvmCross/MvvmCross/pull/1284

`Task Init(TInit)` is available. Just make sure that your ViewModel inherits `MvxViewModel< SomeObject>`
