### ISSUE TITLE
Network plugin rest client could support aborting the request

### ISSUE THREAD

**Issue by dalewking** [MvvmCross/MvvmCross#569]
MakeRequest would simply need a return value that had a reference to the httprequest and a cancel method that called abort on it.

**Comment by willsb** [comment]
The [`MakeRequest`](https://github.com/MvvmCross/MvvmCross/blob/master/MvvmCross-Plugins/Network/MvvmCross.Plugins.Network/Rest/IMvxRestClient.cs#L20) method returns an `IMvxAbortable`, so I guess this should be closed, right?

**Comment by Cheesebaron** [comment]
You are right. Lets close this.
