### ISSUE TITLE
Make MvxImageView more informative

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#588]
MvxImageView already supports a `DefaultImagePath`, `ImageUrl` and `ErrorImagePath`. However, in order to show a progress indicator or similar you need to know when it has finished trying to load an image or failed. No such events are subscribe-able right now.

So I see two approaches to this:
- Create a couple of events, which fires when it starts loading and ends loading
- Create a message which is published when certain events happen.

Then it will be possible to listen for these where ever needed.

**Comment by nmilcoff** [comment]
MvxImageView was removed in #2706. Marking this as deprecated.
