### ISSUE TITLE
AddHeader\AddFooter methods in MvxListView

### ISSUE THREAD

**Issue by enterpredator** [MvvmCross/MvvmCross#602]
> idea once about maybe setting the adapter in XML (#146) - perhaps this or something like it might be possible.

MvxListView does not allow header/footer views.
https://github.com/MvvmCross/MvvmCross/issues/331

**Comment by dbeattie71** [comment]
Would this change to MvxListView fix the problem?

public new IMvxAdapter Adapter
		{
			get
			{
				var adapter = base.Adapter as HeaderViewListAdapter;
				if (adapter != null)
					return adapter.WrappedAdapter as IMvxAdapter;

				return base.Adapter as IMvxAdapter;
			}
			set
			{
				var existing = Adapter;
				if (existing == value)
					return;

				if (value != null && existing != null)
				{
					value.ItemsSource = existing.ItemsSource;
					value.ItemTemplateId = existing.ItemTemplateId;
				}

				base.Adapter = value;
			}
		}

**Comment by djrocksmith** [comment]
Thanks dBeattie, this worked really well for me and solved the issue of crashing.

The error comes in the MvxListView at this line:-

var item = Adapter.GetRawItem (position);

Due to the way the Adaptor is referenced I gather from your answer.  You saved my bacon!

**Comment by martijn00** [comment]
This is already possible by implementing yourself, or as part of the RecyclerView.
