### ISSUE TITLE
Can a general Close/Back event be added to MvxViewModel?

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#609]
An example where this is useful is when the viewmodel started a service thread to call some webservice, which awakes and tries to call ShowViewModel. Which will mess up ios with unbalanced errors.

**Comment by MarcBruins** [comment]
In MvvmCross 5.0 there is going to be [lifecycle support](https://www.mvvmcross.com/documentation/fundamentals/viewmodel-lifecycle) which gives you a `Disappearing` event in the viewmodel.

**Comment by softlion** [comment]
This isn't not enough and won't resolve these business cases:

- close: a view can disappear because a new view is pushed on top of it. It won't be closed though. You now understand easily that the close event is missing in mvvmcross 5.
- close can be triggered by a hardware back button, which can be cancelled on android. On iOS close can be triggered by the navigation bar back button and can not be cancelled.

Closing this thread means you don't understand this.

**Comment by Cheesebaron** [comment]
This could be, because it is not very well described to begin with. Feel free to open a new issue, where there is a better explanation of what is needed + use cases where it would be useful.
