### ISSUE TITLE
Location Plugin missing for WPF project.

### ISSUE THREAD

**Issue by AlanYost** [MvvmCross/MvvmCross#630]
When you nuget the Location Plugin for a WPF based mobile project the LocationPluginBootstrap.cs file is not auto created.  If you manually create this then there is no underlying plugin to support this and the application will fail to create the plugin.

I have written a plugin for this but I am unsure how to get this back into the open source community as github is new to myself and I am unsure of the process. 

I am very keen to flesh out the area on the WPF front - but would really appreciate some guidance to make this happen.  

Kind regards

Alan.

**Comment by martijn00** [comment]
Not sure if this integrated yet. Reference to the code: https://github.com/AlanYost/MvvmCross/commit/0354ce6406f31ad50afcb0840db6edf3855c639c

@Cheesebaron do you know more about this one?

**Comment by Cheesebaron** [comment]
I don't know much more about this than presented in this issue. So no.

**Comment by martijn00** [comment]
Checked now. This already is integrated.
