### ISSUE TITLE
Setting ViewModel property on a Fragment is not correct

### ISSUE THREAD

**Issue by dustin-graham** [MvvmCross/MvvmCross#636]
Hello,
I'm just getting into MvvmCross and coming from several years of professional Android development. I noticed a pattern that is used in the fragging plugin and in almost all the other examples from the community I've seen thus far on Fragments which is incorrect as far as Android development is concerned. It has to do with the way the correct ViewModel for a fragment is found and then set to the ViewModel property on the fragment. Something like:

var viewModelLoader = Mvx.Resolve();
fragment.ViewModel = viewModelLoader.LoadViewModel(request, null);

This is incorrect because Fragments are managed by a FragmentManager and each Fragments lifecycle is at the mercy of that manager and Android. At any time your Fragment may be destroyed and the FragmentManager's job is to recreate it. When it gets recreated it will no longer have the ViewModel you gave it and this will cause problems in the program. This pattern works in ideal situations but will break in many others. The way around this sort of a thing in native development is to provide the Fragment what it needs to operate inside of an argument Bundle and then the Fragment can then request all other resources from the environment. I've been prototyping some things along this line with a bit of success but I'd like to see what your thoughts are on this. The partial solution that I've put together so far is to have an interface on my Activity called IFragmentHost which has a method for getting the MvxViewModel for a fragment tag. Then on my ViewModel, I have a dictionary of "Sub" ViewModel's keyed by the same tags. So my Activity will obtain the proper SubViewModel from it's ViewModel and give return it to the Fragment when the Fragment requests it during it's initialization phases of it's lifecycle (currently during onResume works best). This isn't terribly cross-platform yet but this should guarantee that a fragment, dynamic or static, will be able to get it's appropriate ViewModel no matter what Android decides to do. Thoughts?

**Comment by martijn00** [comment]
This is fixed in the MvxCachingFragmentActivity. See this sample: https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/master/Samples

**Comment by andresdsep** [comment]
Has this been updated in the nuget package?

**Comment by martijn00** [comment]
You need to add the MvvmCross Android-Support Fragging package to be able to use this in beta7.

**Comment by andresdsep** [comment]
This is what I have installed https://www.nuget.org/packages/Cirrious.MvvmCross.Droid.Support.Fragging/4.0.0-beta7/.

Am I doing something wrong?

**Comment by martijn00** [comment]
The sample is a bit further then the beta7 package. On the next nuget update this will be aligned again. For now you can look at the commit history to see the previous sample.

**Comment by andresdsep** [comment]
Thanks man :)
