### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by geedsen** [MvvmCross/MvvmCross#646]
V3.1 zip, opened solution MvvmCross_All.sln
Rebuild:

Error	105	'Android.Views.InputMethods.ImeAction' does not contain a definition for 'Previous'	D:\Projects2\xamarin\MvvmCross-3.1\CrossUI\CrossUI.Droid\Dialog\Elements\EntryElement.cs	110	87	CrossUI.Droid

**Comment by martijn00** [comment]
Issue is outdated i think. Closing for now.
