### ISSUE TITLE
Re-add the Generics :)

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#648]
Following on from these tweets yesterday:

<blockquote class="twitter-tweet" lang="en"><p>Woo! “<a href="https://twitter.com/paulcbetts">@paulcbetts</a>: Wait, you can create generic subclasses of NSObject in Xamarin.iOS &gt;= 7.2.1? 😻”</p>&mdash; Greg Shackles (@gshackles) <a href="https://twitter.com/gshackles/statuses/448985790111318016">March 27, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

We can now re-add:

- MvxActivty<TViewModel>
- MvxViewController<TViewModel>
- etc

Should still leave the non-generic's in place too - but these are nice options for people to have

**Comment by martijn00** [comment]
Can't this one be closed?
