### ISSUE TITLE
Success or error not firing in IMvxLocationWatcher (Location PlugIn)

### ISSUE THREAD

**Issue by IVisualDev** [MvvmCross/MvvmCross#655]
Hi,

i've added the Location PlugIn to my Android project. When i wanted to inject the IMvxGeoLocationWatcher in my ViewModel i got a message, that the interface is obsolete and i have to use the new IMvxLocationWatcher.

But...

When i use the new one, the implementation of MvxAndroidLocationWatcher never fires success or error.

With the old interface everything works fine...

I also noticed on the phone that location searching is running...

Do i need to use the new implementation other than the old one? Other options?

Kind regards,
Sandro

**Comment by descorp** [comment]
IMvxLocationWatcher  works perfect on genymotion emulator, but not on a real device (we tried several model). 
While debugging from the office I can see that OnSuccess fires constantly, but in real environment (while walking or driving) - It fires only one time and then you have to go "Home" and reopen app.
Sometimes it stuck in 0,0 coordinate with no coordinates at all.

I've implemented it like this
https://github.com/MvvmCross/MvvmCross/wiki/mvvmcross-plugins#location

Saddest part is that I have GoogleMap implemented too and I can see how blue dot move on map in realtime while my Mvvmcross location stuck on same point ..

**Comment by Cheesebaron** [comment]
Google Map uses the Fused provider. The one in MvvmCross is using the default one in Android, which isn't that good. Afaik it only uses GPS, so it takes a long time for it to get a fix for the satellites, and you need to be able to see the sky before it gets a fix.

I have an old sample showing how to use the Fused one in MvvmCross:
https://github.com/Cheesebaron/MvxGeoLocationSample

**Comment by thongdoan** [comment]
On my device, if I turn off Location Service and start MvxAndroidLocationWatcher it will not raise any success, error events, I have decompile  source and debug and I see that when Location Service is turn off:
_locationManager.GetBestProvider alway return LocationManager.PassiveProvider
I have added below statement to fix (Mvvmcross 3.5.1):
_bestProvider = _locationManager.GetBestProvider (criteria, true);
if (_bestProvider == LocationManager.PassiveProvider) {
	var realBestProvider = _locationManager.GetBestProvider (criteria, false);
	if (realBestProvider != LocationManager.PassiveProvider)
		_bestProvider = realBestProvider;
}
---------------------------------------------------------------------------------------------------------------------------------
https://www.dropbox.com/s/ftjt9bh76s6yk5c/AndroidLocationWatcher.cs?dl=0

**Comment by Cheesebaron** [comment]
Please use gists or github repositories to host code if you want people to review it. I don't trust random files on dropbox or similar.

**Comment by thongdoan** [comment]
@Cheesebaron  Sorry and Thanks for your recommend, I have updated

**Comment by Cheesebaron** [comment]
This can be closed. There is a Fused location provider plugin now.
