### ISSUE TITLE
MvvmCross.Dialog.Droid Dialog Views not opening with ART Runtime

### ISSUE THREAD

**Issue by Nexus2k** [MvvmCross/MvvmCross#667]
With the most recent Xamarin Update (4.12.3) our Apps finally run on the ART Java VM Runtime from Android 4.4 OS. Unfortunately MvvmCross seems to have issues launching MvxDialogFragments with the ART Runtime.

The log doesn't show anything useful just the usual Xamarin remapping Notices. As it would open the dialog...

**Comment by martijn00** [comment]
This has been addressed here: https://bugzilla.xamarin.com/show_bug.cgi?id=25368
