### ISSUE TITLE
Suspect RaiseCanExecuteChanged MvxCommand weak reference not sufficient on Android

### ISSUE THREAD

**Issue by rb1234** [MvvmCross/MvvmCross#668]
On Android 2.3.3 with MvvmCross NuGet package v3.1.1, I have a fragment View ("AView") and associated ViewModel ("AViewModel"). There is some nesting with further Views and ViewModels within these such that a child ViewModel "BViewModel" is hosted within "AViewModel" as a property, which is associated with the child fragment "BView" hosted within "AView". In "AView" there is a Button bound with ```local:MvxBind="Click BViewModel.SomeCommand"```, which is an MvxCommand. When "BView" _finishes_ resuming, code is triggered which hooks up "BViewModel" and sets the CanExecute state of SomeCommand (potentially enabling it) and when "BView" _begins to_ pause the same code is triggered and ultimately sets CanExecute to false.

Unfortunately sometimes when I RaiseCanExecuteChanged the event handler within the Click binding is not called. This is predominantly triggered by pausing the view and then resuming it - at which point the button is unresponsive to changes in CanExecute until a new binding is created.

I have been using a CustomClick binding to add a lot of logging around the CanExecute status and using a strong reference to the command, being careful to ensure I have not requested that the event handler is unhooked - this did not help. Consequently, having seen #623, I suspect the weak referencing in MvxCommand is the issue. I will now attempt to use MyStrongCommandHelper from #623 and report back.

As my changes to CanExecute are actually posted back to the UI thread I have also checked there are no issues (including exceptions) due to views being accessed outside the usual resume-pause lifecycle. I am fairly confident that is not the cause of the issue.

**Comment by canbilgin** [comment]
I'm seeing this same issue on Xamarin.Forms implementation on iOS Application. Once you replace the MvxCommand with a derivative that uses a MvxStrongCommandHelper, the CanExecuteChanged is fired and the UI behaves properly.

What is interesting is that if you use MvxCommand and subscribe to the CanExecuteChanged an eventhandler just to trace the even, the event is being fired properly but the action for the canexecute is never called by the UI.

In the replacement version with the strongcommandhelper, this does not happen.
