### ISSUE TITLE
Annoyance when using Converter

### ISSUE THREAD

**Issue by telemat** [MvvmCross/MvvmCross#697]
This is a minor issue but fixing it will go a long way towards improving the user experience.

With reference to Api Examples, CovertThisView demo, in the first text box, input any number starting with 0, e.g 0123, you will notice that the 0 disappears (which is expected) but the cursor moves to the front, so you end up typing 231 instead of 123.

**Comment by guillaume-fr** [comment]
You can workaround this bug by binding the input on focus change instead of text change.
http://stackoverflow.com/questions/19216585/mvvmcross-change-update-source-trigger-property-of-binding-on-monodroid
