### ISSUE TITLE
Xamarin.Forms integration

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#703]
See: https://xamarin.com/forms

**Comment by martijn00** [comment]
This is covered by @Cheesebaron http://blog.ostebaronen.dk/2014/07/xamarinforms-and-mvvmcross.html
and: http://stackoverflow.com/questions/24171670/mvvmcross-with-xamarin-forms/27326182#27326182

**Comment by slodge** [comment]
I'd quite like to reopen this one...

I still hear a lot of comments that xam forms isn't exactly perfect and that the api changes a bit too often, but as it matures, I'd be very open to seeing an alternative starter pack added to Mvx (either here or in another repo - e.g. in Cheesebaron's) which allows users to use forms more easily (e.g. within a few nuspec clicks). Once that's done then I think it makes @asudbury's job easier too with his NinjaCoder plugin.

So sorry... but reopening for now.... I think this is a good place to centralise ideas/input...

**Comment by asudbury** [comment]
The NinjaCoder plugin has a 'just about complete' version that allows Mvx and Xamarin Forms to co exist - if anyone wants to take a look let me know I will point you to a 'pre public' installer.

**Comment by martijn00** [comment]
Fixex with new repo: https://github.com/MvvmCross/MvvmCross-Forms

**Comment by Laumania** [comment]
Cool, I'll follow that project, as I'm starter up on a app soon that I plan to build with Xamarin.Forms and MvvmCross :)
