### ISSUE TITLE
CommandParameter binding expression

### ISSUE THREAD

**Issue by PedroLamas** [MvvmCross/MvvmCross#704]
Following the information [here](http://stackoverflow.com/questions/22778749/mvxtabsfragment-failed-to-create-target-binding-for-binding-command-for/22779090#22779090), I have a binding looking like this:

    local:MvxBind="Click CommandParameter(MyCommand, MyProperty)"

I get the following error

>344.12 Problem parsing binding MvxException: Must follow binding option CommandParameter with an '=' in Click CommandParameter(MyCommand, MyProperty)

Am I doing something wrong?

**Comment by martijn00** [comment]
@slodge has this been tested since you made that fix?

**Comment by slodge** [comment]
I think so... but `Dunno!` for sure... will add it to the long todo list :)
