### ISSUE TITLE
ICommand binding on iOS not working with CanExecute

### ISSUE THREAD

**Issue by JCKodel** [MvvmCross/MvvmCross#720]
I made a project for all platforms, except Mac, where a textbox enables or disables a submit button. Works fine for all platforms, except for iOS (the button is never enabled).
The view has a label bound to the bool property (and reflects the changes), so I debugged the MvxUIControlTouchUpInsideTargetBinding class and indeed the RefreshEnabledState is called only once at startup (the _canExecuteSubscription = _command.WeakSubscribe(_canExecuteEventHandler); line IS executed, but there is no effect. The event is never caught).
The workaround "bind Enabled to bool property" work as intended.

**Comment by martijn00** [comment]
@ahopper-soltech did you create that repo, or is this issue fixed now?

**Comment by Cheesebaron** [comment]
Closing this. Super stale. Reopen if you believe this is still an issue.
