### ISSUE TITLE
Re-used MvxImageViews show old image before new one is loaded in ListViews and TableViews

### ISSUE THREAD

**Issue by ChuckPinkert** [MvvmCross/MvvmCross#725]
I have a listview on Android that has a MvxImageView in each cell, they look great on first load but as you start to scroll, the re-used cells / items show the old image before the new image url is loaded. These should reset to being empty and be updated to the new image url when the cell is re-used. I have only seen this recently on Android Listview, but I think I remember also seeing it on UITableViews in iOS.

**Comment by martijn00** [comment]
Closing this for now since a solution is present. Please reopen when needed.
