### ISSUE TITLE
Droid Button click binding affects Enabled property

### ISSUE THREAD

**Issue by scastria** [MvvmCross/MvvmCross#729]
It took me a little while to find out what was going on.  I had a Droid button with MvxBind set to:  "Enabled CanSend; Click SendCommand"  As you can see, I am using a separate boolean to control the enabled state instead of CanExecute on the Command *maybe I shouldn't be doing this??).  Anyway, Since bindings are handled in order, the Enabled binding was handled which set my button to disabled at runtime, but when the Click command binding was handled, the method MvxViewClickBinding.RefreshEnabledState would override the enabled state of my button by asking the CanExecute of the command that was just bound.  This set my button back to enabled at runtime.  My quick fix for this is to change the order of my binding string to bind the command first and then bind the enabled boolean.  Not sure what the long term fix should be.  Either I shoudl use CanExecute and stop using a separate boolean property or RefreshEnabledState shoud somehow check if the Enabled Button property has already been bound before asking the CanExecute of the Command?

**Comment by martijn00** [comment]
@kjeremy did your changes go back into the main branch?

**Comment by martijn00** [comment]
I think this was the change: https://github.com/MvvmCross/MvvmCross/commit/29636904e780ddc946f79475aa58ffaf7abba3e4#diff-efc9592e378c5c2f37f236884883d66e

**Comment by kjeremy** [comment]
@martijn00 I'm not sure if they did or not.  I know that I had slodge merge a bunch of stuff for me at one time.
