### ISSUE TITLE
MvxListItemView not measuring correctly?

### ISSUE THREAD

**Issue by scastria** [MvvmCross/MvvmCross#774]
I already have a bindable list adapter for Android that supports groups or sections such that my section headers have a different templateId then my standard rows.  This has been working fine for almost a year.  However, now I would like to have pinned section headers like iOS where scrolling keeps the section header visible until the next section header takes its place. 

This sounded like hard work so I went looking with Google and found `PinnedSectionListView` on GitHub from beworker. What is nice about it is that the `ListAdapter` only need to implement a simple interface.  That means I don't have to mess with my bindable `ListAdapter` that supports sections that already extends `MvxAdapter`. 

However, my problem is that I must use beworker's `PinnedSectionListView`. Therefore, I tweaked the `PinnedSectionListView` code to inherit from `MvxListView` instead of the standard `ListView` and made a few other tweaks to get it to compile. Anyway, `PinnedSectionListView` does some magic with `MeasureSpecs` and it is calculating the wrong measured size for my section headers. 

Debugging further, I notice that my using an `MvxAdapter`, `GetView` returns an `MvxListItemView` that wraps the real View hierarchy I specified in my template. My real View hierarchy has a fixed height of 50dp in the `LayoutParams`. However, when it is wrapped inside an `MvxListItemView`, `Measure` returns a very large number for height instead of 50dp. 

I will continue to investigate, but I thought I would post this in case anyone has any ideas.  Even better would be a pinned section header list view that already works with MvvmCross.

**Comment by Cheesebaron** [comment]
Related to #1465
