### ISSUE TITLE
declare binding in IB

### ISSUE THREAD

**Issue by andreinitescu** [MvvmCross/MvvmCross#777]
Any plans for being able to declare binding string in Interface Builder? 
I'm sure someone else thought about it already. 
I've been experimenting it but I'm facing an weird issue. 
I'm obtaining the NSObject instance of the UIView for which the user runtime attribute is being set and I'm trying to create a Mvx binding on it (I'm using the current top view controller as binding context owner), 
For testing I have a UILabel and UITextFIeld connected to Hello view-model property (like in the generated FirstView)
The 'Hello' is displayed fine in both label and text-field when screen is loaded, but as soon as I type in the UITextField it crashes the app.
What's weird is that if I'm using the view instances obtained from the view-controller, it works fine.
Code:

```
static void AddBinding(object o, string binding)
{
    var bindingCtxOwner = FindBindingContext (o);
    if(bindingCtxOwner != null)
    {
        //bindingCtxOwner.AddBindings (o, binding);
        bindingCtxOwner.DelayBind (() => {

            if(o is UITextField)
            {
                // weird, unless I am either referencing or using the reference from the view-controller, this doesn't work, it's crashing
                //var view = (UITextField)(bindingCtxOwner as MvxViewController).View.Subviews[1];
                bindingCtxOwner.AddBindings((UITextField)o, binding);
            }
            else if(o is UILabel)
            {
                //var view = (UILabel)(bindingCtxOwner as MvxViewController).View.Subviews[0];
                bindingCtxOwner.AddBindings((UILabel)o, binding);
            }
        });
    }
}
```

I haven't yet spent too much time on this, before I do I thought it's wise to ask around of any work \ plans in this direction.
It would be very handy to be able to declare the bindings in IB (much like on Windows and Android) without having to create outlets and write the C# code.
I know many iOS developers create UI by hand but it's still useful I think because you can design many of the simple screens easier in IB.
Also I know there are some challenges to make this work completely but even if it covers simple cases    it's still very useful as it will cover a lot of the scenarios.

**Comment by Cheesebaron** [comment]
I guess this could be possible with Mvx types, if they register themselves and export a binding description property like:

```
[Register("MvxView")]
[DesignTimeVisible(true)]
public class MvxView : UIView
{
    [Export("Binding"), Browsable(true)]
    public string Binding { get; set; }
}
```

Then at run time grab that binding description for that view and make the binding set and bind it.

Although, this would require _all_ views that you want to bind inherit from `MvxView` and implement this in order to work.

Not sure if in the end it will be super useful.

**Comment by nickrandolph** [comment]
@andreinitescu is this still of interest?

**Comment by andreinitescu** [comment]
@nickrandolph I think it would still be an interesting and handy feature, but it's not ideal without tooling support, without being able to know at design time that the binding string you wrote is valid. I think this also could be done using a custom build step? Hmm, actually I think the bindings code could be emitted at compile time, just how XAMLC works in Xamarin Forms. But maybe I'm aiming too high?

**Comment by nickrandolph** [comment]
@andreinitescu happy to keep the issue open but it'd be good for you to prototype something out to give it a shot. Raise a PR with [WIP] in the title to get feedback from other contributors .

**Comment by andreinitescu** [comment]
4 years ago when I was working on this I was hoping to get some feedback, since I hit a problem.
Unless nobody else is interested, I am fine if this gets closed.
