### ISSUE TITLE
IMvxAndroidCurrentTopActivity Activity doesn't always return the correct top activity

### ISSUE THREAD

**Issue by andreinitescu** [MvvmCross/MvvmCross#783]
I have an activity with 'Theme.Holo.Light.Dialog' theme which makes the activity look like a dialog, hovering an activity.

as you know MvxAndroidLifeTimeMonitor (which implements IMvxAndroidCurrentTopActivity) uses different activity lifetime events to set the IMvxAndroidCurrentTopActivity:Activity 

https://github.com/MvvmCross/MvvmCross/blob/e6d10972b5c28e00e80acc3d9e8910961aa813d6/Cirrious/Cirrious.MvvmCross.Droid/Views/MvxAndroidLifeTimeMonitor.cs

In the case of the dialog however, if I reorient the device, what happens is the dialog activity gets first all the lifetime events, from destruction to creation, followed by the hovered activity.
This makes the hovered activity become the top activity reported by IMvxAndroidCurrentTopActivity.

My specs:
latest stable MvvmCross from NuGet
testing on Nexus 10, Android 4.3
app target Android version is Automatic

I stumbled on this because I have a Close button on dialog which calls MvxViewModel.Close() and because of incorrect top activity reported by IMvxAndroidCurrentTopActivity, it gives this very useful warning:

<code>
mvx:Warning: 71.15 Ignoring close for viewmodel - rootframe's current page is not the view for the requested viewmodel
</code>

https://github.com/MvvmCross/MvvmCross/blob/e6d10972b5c28e00e80acc3d9e8910961aa813d6/Cirrious/Cirrious.MvvmCross.Droid/Views/MvxAndroidViewPresenter.cs#L73

I haven't found for an exact solution for this.
I will make a sample app if that's helpful.
In my app, a dirty & temporary solution is to add ConfigurationChanges attribute for both the activity dialog and for the activity below it.

**Comment by martijn00** [comment]
@andreinitescu Is this still relevant, and do you have that sample app so we can reproduce this?

**Comment by dazinator** [comment]
I am hitting this..

**Comment by dazinator** [comment]
I have managed to fix this by implementing an `IMvxAndroidCurrentTopActivity` that also implements `IActivityLifecycleCallbacks` and is then registered with the application using `Application.RegisterActivityLifecycleCallbacks()`. It then gets notified about activity lifecycle events for all activities. and uses that information to calculate which activity is currently at the top.

So in my `Setup.cs`

```csharp

                var viewLifecycleManager = new DroidViewLifecycleManager();
                var app = MainApp.Current;
                app.RegisterActivityLifecycleCallbacks(viewLifecycleManager);                
                Mvx.RegisterSingleton<IMvxAndroidCurrentTopActivity>(viewLifecycleManager);
```

and here is the implementation:

```csharp
  /// <summary>
    /// This class implements IActivityLifecycleCallbacks and is registered on application startup to 
    /// listen for activity lifecycle events - which it then uses to track the Activities, including which Activity is Current.
    /// </summary>
    public class DroidViewLifecycleManager : Java.Lang.Object, global::Android.App.Application.IActivityLifecycleCallbacks, IMvxAndroidCurrentTopActivity
    {

        public event EventHandler<ViewLifetimeEventArgs> LifetimeChanged;

        public DroidViewLifecycleManager()
        {

        }

        private ConcurrentDictionary<string, ActivityInfo> _Activities = new ConcurrentDictionary<string, ActivityInfo>();

        protected string GetActivityName(Activity activity)
        {
            return activity.Class.SimpleName;
        }

        public Activity GetCurrentActivity()
        {
            if (_Activities.Count > 0)
            {
                var e = _Activities.GetEnumerator();
                while (e.MoveNext())
                {
                    var current = e.Current;
                    if (current.Value.IsCurrent)
                    {
                        return current.Value.Activity;
                    }
                }

                // var key = _Activities..;
            }

            return null;
        }

        #region IActivityLifecycleCallbacks

        public void OnActivityCreated(Activity activity, global::Android.OS.Bundle savedInstanceState)
        {
            _Activities.GetOrAdd(GetActivityName(activity), new ActivityInfo() { Activity = activity, IsCurrent = true });
            OnLifetimeChanged(activity, LifecycleEventType.Created);
            // throw new NotImplementedException();
        }

        public void OnActivityDestroyed(Activity activity)
        {
            ActivityInfo removed;
            _Activities.TryRemove(GetActivityName(activity), out removed);
            OnLifetimeChanged(activity, LifecycleEventType.Destroyed);
        }

        public void OnActivityPaused(Activity activity)
        {
            ActivityInfo forAdd = new ActivityInfo { Activity = activity, IsCurrent = false };
            _Activities.AddOrUpdate(GetActivityName(activity), forAdd, (key, existing) =>
            {
                existing.Activity = activity;
                existing.IsCurrent = false;
                return existing;
            });
            OnLifetimeChanged(activity, LifecycleEventType.Paused);
        }

        public void OnActivityResumed(Activity activity)
        {
            ActivityInfo forAdd = new ActivityInfo { Activity = activity, IsCurrent = false };
            _Activities.AddOrUpdate(GetActivityName(activity), forAdd, (key, existing) =>
            {
                existing.Activity = activity;
                existing.IsCurrent = true;
                return existing;
            });
            OnLifetimeChanged(activity, LifecycleEventType.Resumed);
            //lock (_Lock)
            //{
            //    _CurrentActivity = activity;
            //}
        }

        public void OnActivitySaveInstanceState(Activity activity, global::Android.OS.Bundle outState)
        {
            // throw new NotImplementedException();
        }

        public void OnActivityStarted(Activity activity)
        {
            ActivityInfo forAdd = new ActivityInfo { Activity = activity, IsCurrent = false };
            _Activities.AddOrUpdate(GetActivityName(activity), forAdd, (key, existing) =>
            {
                existing.Activity = activity;
                existing.IsCurrent = true;
                return existing;
            });
            OnLifetimeChanged(activity, LifecycleEventType.Started);
        }

        public void OnActivityStopped(Activity activity)
        {
            ActivityInfo forAdd = new ActivityInfo { Activity = activity, IsCurrent = false };
            _Activities.AddOrUpdate(GetActivityName(activity), forAdd, (key, existing) =>
            {
                existing.Activity = activity;
                existing.IsCurrent = false;
                return existing;
            });
            OnLifetimeChanged(activity, LifecycleEventType.Stopped);
        }

        #endregion

        protected virtual void OnLifetimeChanged(Activity activity, LifecycleEventType eventType)
        {
            if (LifetimeChanged != null)
            {
                var args = new ViewLifetimeEventArgs(activity, eventType);
                LifetimeChanged(this, args);
            }
        }

        #region Nested Helper Class

        /// <summary>
        /// Used to store additional info along with an activity.
        /// </summary>
        private class ActivityInfo
        {
            public bool IsCurrent { get; set; }
            public Activity Activity { get; set; }
        }

        #endregion

        public Activity Activity
        {
            get { return GetCurrentActivity(); }
        }
    }
```

**Comment by dazinator** [comment]
Let me know if you would prefer a PR?

**Comment by martijn00** [comment]
A PR would be better for sure!

**Comment by dazinator** [comment]
Just to shed some more light on this..

When you have an activity using the 'Theme.Holo.Light.Dialog'  theme - and you switch orientation, the sequence of events on Android is:

1. `Pauses` --> `Stops` --> `Destroys` --> `Creates` --> `Starts`--> `Resumes` the dialog activity.
2. `Stops` --> `Destroys` --> `Creates` --> `Starts` --> `Resumes` --> `Pauses` the parent activity.

The parent activity is already in a "Paused" state when the dialog is displayed which is why 1 and 2 above look different, as Android has to put it back into a "Paused" state again after it has been re-created. 

This means for MvvmCross to correctly detect the current top activity it needs to keep references to all activities ( Activity 1 and Activity 2 in this instance) so that it can track the status per activity.  

When I get around to submitting a PR - it will be based on tidying up the code posted above and amending the `MvxAndroidLifetimeMonitor` appropriately.

**Comment by dazinator** [comment]
This is labelled as more info required - please can you specify what else is required as I am happy to provide further clarity / detail

**Comment by martijn00** [comment]
I think the 'Needs more info' label might be incorrect by now. A PR would still be highly appreciated!

**Comment by MostafaGazar** [comment]
A workaround would be to write a custom ViewModelCloser and override the Close functionality to get the top activity using reflection instead of getting it using `IMvxAndroidCurrentTopActivity`.

A transparent activity was the cause of this issue in our case because when the device orientation was to change, Android would destroy the transparent activity then recreates it (*topActivity is still correct*) then it destorys the activity behind it and recreate it (*topActivity is not correct any more*).

Workaround using reflection:

Add `IViewModelCloser ` to your Core project:

	public interface IViewModelCloser
	{
	  void RequestClose(IMvxViewModel viewModel);
	}
	
Add `AndroidViewModelCloser` to your Droid project:

	public class AndroidViewModelCloser : IViewModelCloser
	{
	  public void RequestClose(IMvxViewModel viewModel)
	  {
	    var topActivity = Mvx.Resolve<IMvxAndroidCurrentTopActivity>();
	
	    var activity = topActivity.Activity;
	    var currentActivityViaReflection = GetCurrentActivityByReflection ();
	    if (currentActivityViaReflection != activity)
	    {
	      activity = currentActivityViaReflection;
	    }
	    var view = activity as IMvxAndroidView;
	
	    if (topActivity.Activity == currentActivityViaReflection)
	    {
	      if (view == null)
	      {
	        MvxTrace.Trace("request close ignored for {0} - no current activity", viewModel.GetType().Name);
	        return;
	      }
	
	      if (view.ViewModel != viewModel)
	      {
	        MvxTrace.Trace("request close ignored for {0} - current activity is registered for a different viewmodel of type {1}", viewModel.GetType().Name, view.ViewModel.GetType().Name);
	        return;
	      }
	    }
	
	    MvxTrace.Trace("request close for {0} - will close current activity {1}", viewModel.GetType().Name, view.GetType().Name);
	    activity.Finish();
	  }
	
	  public static Activity GetCurrentActivityByReflection() 
	  {
	    Class activityThreadClass = Class.ForName("android.app.ActivityThread");
	    Java.LangObject activityThread = activityThreadClass.GetMethod("currentActivityThread").Invoke(null);
	    Field activitiesField = activityThreadClass.GetDeclaredField("mActivities");
	    activitiesField.Accessible = true;
	    HashMap activities = (HashMap) activitiesField.Get(activityThread);
	    foreach (Java.LangObject activityRecord in activities.Values()) 
	    {
	      Class activityRecordClass = activityRecord.Class;
	      Field pausedField = activityRecordClass.GetDeclaredField("paused");
	      pausedField.Accessible = true;
	      if (!pausedField.GetBoolean(activityRecord)) 
	      {
	        Field activityField = activityRecordClass.GetDeclaredField("activity");
	        activityField.Accessible = true;
	        Activity activity = (Activity) activityField.Get(activityRecord);
	        return activity;
	      }
	    }
	
	    return null;
	  }
	}
	
In `YOUR_PROJECT.Droid/Setup.cs`:

	protected override void InitializeLastChance()
	{
		var closer = new AndroidDroidViewModelCloser();
		Mvx.RegisterSingleton<IViewModelCloser>(closer);
		
		base.InitializeLastChance();
	}
	
In `YOUR_PROJECT.Core/BaseViewModel.cs`:
	protected new void Close (IMvxViewModel viewModel)
	{
	  var closer = Mvx.Resolve<IViewModelCloser>();
	  closer.RequestClose(this);
	}
	
**Refs**:

* http://stackoverflow.com/questions/11411395/how-to-get-current-foreground-activity-context-in-android/28423385#28423385
* https://github.com/MvvmCross/MvvmCross-Tutorials/blob/6f76d41c8f5b3555f3ed5d76f0c0fd8d2c929a79/Sample%20-%20CustomerManagement/CustomerManagement%20-%20AutoViews/CustomerManagement.Droid/SimpleDroidViewModelCloser.cs

**Comment by dazinator** [comment]
@MostafaGazar - Thanks for the suggestion! Am i right in thinking that the ViewModelCloser workaround only solves the problem of allowing the view to close though? It does not solve the issue of `IMvxAndroidCurrentTopActivity` reporting the wrong top activity - and so if you have other dependencies that need access to the current top they will still be wrong - i.e:

```

public class AndroidModalProvider
{
    public AndroidModalProvider(IMvxAndroidCurrentTopActivity currentTop)
    {
    ....
    }
}

```

This class would still have the same issue - i.e the wrong top activity is being reported.

So I am guessing, you could put the same bit of reflection into all of these other components too (nasty in my opinion), or you could just fix the problem at it's source by registering a custom `IMvxAndroidCurrentTopActivity` which at the moment is my preferred solution.

Let me know if I have misunderstood something!

**Comment by MostafaGazar** [comment]
@dazinator That is correct, I also agree with you, fixing the the problem at it's source is better. I think DroidViewLifecycleManager you posted before is logically correct yet it did not work in our case, will check it again.

**Comment by dazinator** [comment]
@MostafaGazar - Ah yes - I remember there was a bug in that implementation that I originally posted. I think it was flagging an activity as the top one in one of the lifecycle methods when it shouldn't have been! I remember fixing something like this later on in my app. I'll repost the most current version tomorrow.

**Comment by Dexyon** [comment]
Found this issue again @dazinator . Maybe you can still post the solution to solve this issue. Or maybe you have some time for a PR.

**Comment by dazinator** [comment]
I appreciate this is late...

```
 public class DroidLifetimeMonitor : MvxAndroidLifetimeMonitor, IMvxAndroidCurrentTopActivity
    {
        private IDroidViewLifecycleManager _lifecycleManager;

        public event EventHandler<MvxLifetimeEventArgs> MvxLifetimeChanged;

        protected void FireMvxLifetimeChange(MvxLifetimeEvent which)
        {
            var handler = MvxLifetimeChanged;
            if (handler != null)
                handler(this, new MvxLifetimeEventArgs(which));
        }

        public DroidLifetimeMonitor(IDroidViewLifecycleManager lifecycleManager)
        {
            _lifecycleManager = lifecycleManager;
        }

        public override void OnCreate(Activity activity)
        {
            _lifecycleManager.OnActivityCreated(activity, null);
            if (_lifecycleManager.ActivityCount == 1)
            {
                FireMvxLifetimeChange(MvxLifetimeEvent.ActivatedFromDisk);
            }
        }

        public override void OnDestroy(Activity activity)
        {
            _lifecycleManager.OnActivityDestroyed(activity);
            if (this._lifecycleManager.ActivityCount == 0)
            {
                FireMvxLifetimeChange(MvxLifetimeEvent.Closing);
            }
            // base.OnDestroy(activity);
        }

        public override void OnPause(Activity activity)
        {
           // _lifecycleManager.OnActivityPaused(activity);
            // base.OnPause(activity);
        }

        public override void OnRestart(Activity activity)
        {
          //  _lifecycleManager.OnActivityStarted(activity);
            // base.OnRestart(activity);
        }

        public override void OnResume(Activity activity)
        {
           // _lifecycleManager.OnActivityResumed(activity);
            // base.OnResume(activity);
        }

        public override void OnStart(Activity activity)
        {
           // _lifecycleManager.OnActivityStarted(activity);
            // base.OnStart(activity);
        }

        public override void OnStop(Activity activity)
        {
           // _lifecycleManager.OnActivityStopped(activity);
            //  base.OnStop(activity);
        }

        public override void OnViewNewIntent(Activity activity)
        {
            // base.OnViewNewIntent(activity);
        }

        public new Activity Activity
        {
            get
            {
                return _lifecycleManager.GetCurrentActivity();
            }
        }

        public IDroidViewLifecycleManager LifecycleManager { get { return _lifecycleManager; } }
    }

```

```
    /// <summary>
    /// This class implements IActivityLifecycleCallbacks and is registered on application startup to 
    /// listen for activity lifecycle events - which it then uses to track the Activities, including which Activity is Current.
    /// </summary>
    public class DroidViewLifecycleManager : Java.Lang.Object, IDroidViewLifecycleManager
    {

        public event EventHandler<ViewLifetimeEventArgs> LifetimeChanged;

        public DroidViewLifecycleManager()
        {

        }

        private ConcurrentDictionary<string, ActivityInfo> _Activities = new ConcurrentDictionary<string, ActivityInfo>();

        protected string GetActivityName(Activity activity)
        {
            return activity.Class.SimpleName;
        }

        public Activity GetCurrentActivity()
        {
            if (_Activities.Count > 0)
            {
                var e = _Activities.GetEnumerator();
                while (e.MoveNext())
                {
                    var current = e.Current;
                    if (current.Value.IsCurrent)
                    {
                        return current.Value.Activity;
                    }
                }

                // var key = _Activities..;
            }

            return null;
        }

        public int ActivityCount
        {
            get { return _Activities.Count; }
        }

        #region IActivityLifecycleCallbacks

        public void OnActivityCreated(Activity activity, global::Android.OS.Bundle savedInstanceState)
        {
            var activityName = GetActivityName(activity);
            _Activities.GetOrAdd(activityName, new ActivityInfo() { Activity = activity, IsCurrent = true });
            FireLifetimeChanged(activity, LifecycleEventType.Created);
            Mvx.Trace(MvxTraceLevel.Diagnostic, "CREATED Activity: {0} - CURRENT", activityName);
        }

        public void OnActivityDestroyed(Activity activity)
        {
            ActivityInfo removed;
            var activityName = GetActivityName(activity);
            _Activities.TryRemove(activityName, out removed);
            FireLifetimeChanged(activity, LifecycleEventType.Destroyed);
            Mvx.Trace(MvxTraceLevel.Diagnostic, "DESTROYED Activity: {0} - REMOVED", activityName);
        }

        public void OnActivityPaused(Activity activity)
        {
            ActivityInfo forAdd = new ActivityInfo { Activity = activity, IsCurrent = false };
            var activityName = GetActivityName(activity);
            _Activities.AddOrUpdate(activityName, forAdd, (key, existing) =>
            {
                existing.Activity = activity;
                existing.IsCurrent = false;
                return existing;
            });
            FireLifetimeChanged(activity, LifecycleEventType.Paused);
            Mvx.Trace(MvxTraceLevel.Diagnostic, "PAUSED Activity: {0} - CURRENT", activityName);
        }

        public void OnActivityResumed(Activity activity)
        {
            ActivityInfo forAdd = new ActivityInfo { Activity = activity, IsCurrent = true };
            var activityName = GetActivityName(activity);
            _Activities.AddOrUpdate(activityName, forAdd, (key, existing) =>
            {
                existing.Activity = activity;
                existing.IsCurrent = true;
                return existing;
            });
            FireLifetimeChanged(activity, LifecycleEventType.Resumed);
            Mvx.Trace(MvxTraceLevel.Diagnostic, "RESUMED Activity: {0} - CURRENT", activityName);
        }

        public void OnActivitySaveInstanceState(Activity activity, global::Android.OS.Bundle outState)
        {
            // throw new NotImplementedException();
        }

        public void OnActivityStarted(Activity activity)
        {
            ActivityInfo forAdd = new ActivityInfo { Activity = activity, IsCurrent = true };
            var activityName = GetActivityName(activity);
            _Activities.AddOrUpdate(activityName, forAdd, (key, existing) =>
            {
                existing.Activity = activity;
                existing.IsCurrent = true;
                return existing;
            });
            FireLifetimeChanged(activity, LifecycleEventType.Started);
            Mvx.Trace(MvxTraceLevel.Diagnostic, "STARTED Activity: {0} - CURRENT", activityName);
        }

        public void OnActivityStopped(Activity activity)
        {
            ActivityInfo forAdd = new ActivityInfo { Activity = activity, IsCurrent = false };
            var activityName = GetActivityName(activity);
            _Activities.AddOrUpdate(activityName, forAdd, (key, existing) =>
            {
                existing.Activity = activity;
                existing.IsCurrent = false;
                return existing;
            });
            FireLifetimeChanged(activity, LifecycleEventType.Stopped);
            Mvx.Trace(MvxTraceLevel.Diagnostic, "STOPPED Activity: {0} - NOT CURRENT", activityName);
        }

        #endregion

        protected virtual void FireLifetimeChanged(Activity activity, LifecycleEventType eventType)
        {
            if (LifetimeChanged != null)
            {
                var args = new ViewLifetimeEventArgs(activity, eventType);
                LifetimeChanged(this, args);
            }
        }

        #region Nested Helper Class

        /// <summary>
        /// Used to store additional info along with an activity.
        /// </summary>
        private class ActivityInfo
        {
            public bool IsCurrent { get; set; }
            public Activity Activity { get; set; }
        }

        #endregion


    }
```

```
 public interface IDroidViewLifecycleManager : IViewLifecycleManager, Application.IActivityLifecycleCallbacks
    {
        event EventHandler<ViewLifetimeEventArgs> LifetimeChanged;
        Activity GetCurrentActivity();
        int ActivityCount { get; }
    }
```

```
 public interface IViewLifecycleManager
    {
        
    }
```

Then register these on app startup:

```

            var monitor = new DroidLifetimeMonitor(new DroidViewLifecycleManager());
            var app = MainApp.Current;
            app.RegisterActivityLifecycleCallbacks(monitor.LifecycleManager);
       
            Mvx.RegisterSingleton<IViewLifecycleManager>(monitor.LifecycleManager);
            Mvx.RegisterSingleton<IDroidViewLifecycleManager>(monitor.LifecycleManager);
            Mvx.RegisterSingleton<IMvxAndroidCurrentTopActivity>(monitor);

```

**Comment by martijn00** [comment]
@dazinator can you make a PR for this?

**Comment by Cheesebaron** [comment]
Wouldn't it be sufficient to do exactly what this plugin does: https://github.com/jamesmontemagno/CurrentActivityPlugin

**Comment by dazinator** [comment]
That plugin looks like it has the same bug i have dscribed in this post. The plugin is using the same approach as what I have posted above, to track lifetime events, but it assumes a " last one wins" approach when tracking which activity is current. This doesnt work when displaying dialogs because the child activity (the dialog) is transitioned through its lifecycle events (i.e is started) and then after it is displaying, the parent is transitioned again through its lifecycle events but ending in a paused state. I would expect that plugin to report the parent activity as the current activity when a child modal is displayed.

**Comment by dazinator** [comment]
The difficulty with making a PR out of this is that it requires the developer to add some code to their main android application class in order to register the lifetime monitor with android. Thats a manual thing, which woukd be a breaking change.

**Comment by purrmiaw** [comment]
Hi, sorry for asking this here. I'm trying Dazinator's solution but I couldn't find out the namespace for ViewLifetimeEventArgs and LifecycleEventType and googling is also giving me blank. Do I need to reference something else in my Droid project? (Using MVVMCross 5.0.6)

**Comment by nmilcoff** [comment]
Now that there is a `MvxAndroidApplication` class (#2027), would you consider getting this into the source? Or do you still think it's a bad idea @dazinator?

**Comment by kjeremy** [comment]
I'm not sure we should be imposing our own android application class.

**Comment by nmilcoff** [comment]
@kjeremy but it isn't imposed. If you want to use it, you need to subclass it and mark it with the `[Application]` attribute. That's not done "by default"

**Comment by kjeremy** [comment]
Cool.  I thought it might be required.

**Comment by dazinator** [comment]
Yep I think this could be put in the new application class - the new application class seems to register itself for lifecycle callbacks but not do anything with them at the moment based on that PR.
