### ISSUE TITLE
Upgrading MvvmCross via NuGet sometimes wants to overwrite files

### ISSUE THREAD

**Issue by yozzozo** [MvvmCross/MvvmCross#790]
I recently upgraded MvvmCross to 3.2.1 via NuGet inside of Xamarin Studio on a Mac.  I have an established project with source code currently using MvvmCross.  When I updated the packages, I noticed that it tries to create a new MvvmCross structure.  This includes:

(iOS project)
AppDelegate.cs.txt  (I have an AppDelegate.cs already and it's customized)
LinkerPleaseInclude.cs (I have one already)
Setup.cs (I have one already and it's customized)
Views/FirstView.cs (this is not needed and just gets deleted)

(Core project)
App.cs (I have one already and it's customized)

Since I don't know if the updated versions of these files contains changes, I usually back up my versions of these files, update them, and compare the new changes to my existing versions, line by line.  This is ok, but it would be nice to detect if the files exist, and instead of trying to overwrite them, save them similarly to AppDelegate.cs.txt (.txt at the end).  This way I can just compare them without having to back up the files first.

I'm not sure if this is possible, or if it requires scripts within the NuGet package (I think I sometimes see warnings on Mac Xamarin Studio that says "this package contains PowerShell scripts that won't be run") but if it is, it would be a nice addition.

**Comment by Cheesebaron** [comment]
That is how NuGet works when having stuff in a content folder. Newer versions now ask whether the developer wants to overwrite the files, so maybe this isn't that critical?

**Comment by yozzozo** [comment]
The problem is, I never know when a file has been updated, and if I should merge my file's local modifications with the newer content.  For example, the LinkerPleaseInclude.cs file might have changed, but the FirstView.cs rarely ever does.

**Comment by Dexyon** [comment]
@yozzozo That why you use version control right? I do have to agree with @Cheesebaron this is how nuget works so I don't really see the (directly) added value of this issue.

**Comment by slodge** [comment]
You can always remove the "starter pack" type packages from the list - just stick with the "libraries" - then only assemblies get updated

**Comment by yozzozo** [comment]
Stuart - that's what I was looking for.  Thanks!
