### ISSUE TITLE
Binding android title gets stripped by linker

### ISSUE THREAD

**Issue by mgjhl** [MvvmCross/MvvmCross#803]
So I discovered an issue when trying to bind the title of my activities to a string in my viewmodel, similar to how i do it without issues in iOS with the title of my viewcontroller. The title remains the title of the very first screen being shown, the splashscreen.

Steps to reproduce:
- Create an MvxActivity
- Bind its title to a string in the VM, like so: set.Bind(this).For("Title").To(vm => vm.ViewTitle);
- Build and run it with "No linking" (debug) and see that it works as expected
- Build and run it with "Link SDK assemblies" (release) and see that the binding is no longer effective

**Comment by adsi1407** [comment]
This code work for me. Thanks!
