### ISSUE TITLE
Picture chooser does not work, 3.2.1 WinRT(8.1) Cirrious.MvvmCross.Plugins.PictureChooser.WindowsCommon

### ISSUE THREAD

**Issue by gklappe** [MvvmCross/MvvmCross#810]
When using MvvMCross 3.2.1 and Win81, when using the PictureChooser plugin it searches for Cirrious.MvvmCross.Plugins.PictureChooser.WindowsCommon, however picture is still listed as Cirrious.MvvmCross.Plugins.PictureChooser.WindowsStore. Now on application initialize it will fail and display the error message file not found/assembly could not be loaded because it cannot find Cirrious.MvvmCross.Plugins.PictureChooser.WindowsCommon.

**Comment by martijn00** [comment]
Please reopen if the problem still exists in 4.0
