### ISSUE TITLE
OnNavigatedTo Event Throwing Error in Windows 10 Preview

### ISSUE THREAD

**Issue by toolboc** [MvvmCross/MvvmCross#816]
When invoking OnNavigatedTo from MVXWindowsPage in a Windows Store Universal App running on Windows 10 Preview the following error is displayed when deploying with the debugger attached:

(Note: this error is not present when building on Windows 8.1)

An unhandled exception of type 'System.AccessViolationException' occurred in Cirrious.MvvmCross.WindowsCommon.DLL

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by martijn00** [comment]
@toolboc How is this going now Win 10 is final?
