### ISSUE TITLE
Handling async work with MvxCommand

### ISSUE THREAD

**Issue by molinch** [MvvmCross/MvvmCross#821]
This is related to the old task #374 

The idea is to handle asynchronous code with MvxCommand and not with a new class.
There would be a new constructor and some extra handling for Tasks. Then .NET would automatically resolve the correct constructor, ie: the one accepting a Task.

1st benefit: same class for all usages, sync or non async
2nd benefit: we can await the given Task and have a correct CanExecute implementation

Do you think this would make sense?
If yes I will do it and make a PR.

**Comment by guillaume-fr** [comment]
Tried something : https://github.com/MvvmCross/MvvmCross/compare/3.5...guillaume-fr:3.5-asynccommand

How should we handle exceptions ? Last exception in a property, an event or maybe leave it unhandled ?
Should it implement INPC if it has properties like LastError, IsRunning... ?
Use ConfigureAwait(false), when https://github.com/MvvmCross/MvvmCross/issues/954 is fixed ?

**Comment by lothrop** [comment]
Very nice. About the exceptions: I'm wondering if it would be a good idea to expose the `Task`(s) through a getter. That way the caller could retrieve the `AggregateExceptions` from there. Or `await` that `Task` and use try/catch.

**Comment by guillaume-fr** [comment]
We may consume too much memory if we keep a list of completed tasks. I preffer the event over all other solutions (including the one I implemented ;) ).

I'm starting to experiment Cancellation, I'll commit soon.

**Comment by dbeattie71** [comment]
Mytoolkit has asyncommand, might look and see how it handles exceptions.

**Comment by guillaume-fr** [comment]
@dbeattie71 it doesn't handle exceptions https://mytoolkit.codeplex.com/SourceControl/latest#MyToolkit/Command/AsyncRelayCommand.cs

**Comment by dbeattie71** [comment]
Ah, nm, I was thinking of the runasync in the vm base.
