### ISSUE TITLE
Xamarin.Forms?

### ISSUE THREAD

**Issue by Michael-DST** [MvvmCross/MvvmCross#826]
Sorry for the silly question and if this is the wrong place to put it, but does this project support Xamarin.Forms?  Looks like it supports everything but it (no mention of it in the documentation -- at least a search turns up empty, and the front page doesn't mention it), so just wanted to check and see.

Thanks for any insight/answers,
Michael

**Comment by Michael-DST** [comment]
FWIW, I opened your sample project and I got the latest version of both Xamarin.Forms and MvvMCross and it is completely beschnockered. (read: broken) :)

**Comment by Michael-DST** [comment]
Re-opening to see if anyone else can help me with this.

**Comment by Cheesebaron** [comment]
Some new stuff has been pulled into MvxPlugins with forms. There are samples too.

**Comment by Michael-DST** [comment]
Hmmm... you will have to provide a link, if you can.  I poked around and cannot find anything obvious.

**Comment by Cheesebaron** [comment]
https://github.com/Cheesebaron/Cheesebaron.MvxPlugins/tree/master/FormsPresenters

**Comment by Michael-DST** [comment]
OK... I misunderstood which plugins you were talking about... I thought you mean this repository.  Thank you!
