### ISSUE TITLE
Mac and XamMac nugets

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#856]
Hey Stuart, will you or have you posted the Mac and XamMac nugets? I couldn't find them.

**Comment by lothrop** [comment]
Should we do this before the 3.5 release? I'm not sure of the implications.

**Comment by lothrop** [comment]
@tofutim I'm going to give this another go. Do you have any information on why the previous attempt failed?

**Comment by lothrop** [comment]
@slodge Can you tell me which puzzle piece was missing?

**Comment by lothrop** [comment]
Fixed in #1209.
