### ISSUE TITLE
Can't resolve logger in MvxSetup.CreateDebugTrace

### ISSUE THREAD

**Issue by anjdreas** [MvvmCross/MvvmCross#862]
I want to resolve my logger for Mvx logging and am getting a NullReferenceException on Mvx.Resolve(). It seems the IoC container is not yet initialized until after calling MvxSetup.Initialize(), but CreateDebugTrace() is called before that. I am running a WPF application.

Am I off track here or is this a limitation?

```csharp
public class Setup : MvxWpfSetup
{
	protected override IMvxTrace CreateDebugTrace()
	{
	    // NullReferenceException on Resolve()
	    ILogEx logger = Mvx.Resolve<ILogExFactory>().GetLogger("Mvx");
	    return new MvxTraceToPortableLoggingAdapter(logger);
	}
}
```

**Comment by Cheesebaron** [comment]
`CreateDebugTrace` gets called here: https://github.com/MvvmCross/MvvmCross/blob/3.2/Cirrious/Cirrious.MvvmCross/Platform/MvxSetup.cs#L57
So you are right, it could seem like it is a limitation right now.

**Comment by anjdreas** [comment]
Thanks, I guess that answers my question. I'll close this since I will just live with it for now.
