### ISSUE TITLE
NSDate Link Error

### ISSUE THREAD

**Issue by twografx** [MvvmCross/MvvmCross#864]
Hey,
i created a blank iOS-Project (Unified API) and added the MVVMCross-Nuget (3.5.0beta2). I'm getting this error when trying to deploy on my phone:
`Failed to resolve "Foundation.NSDate Foundation.NSDate::op_Explicit(System.DateTime)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"`

Can anybody help?

**Comment by lothrop** [comment]
If you're on the stable channel (Xamarin.iOS 8.4) you should be using beta1. If you're on beta or alpha (Xamarin.iOS 8.6) you should be using beta2 for Unified API.

**Comment by lothrop** [comment]
Xamarin.iOS 8.6 is now on the stable channel. There's no need to use beta1 anymore.
