### ISSUE TITLE
Can't add Microsoft HTTP Client Libraries to a project with MvvmCross 3.5.0-beta2

### ISSUE THREAD

**Issue by alexrainman** [MvvmCross/MvvmCross#866]
First message:
Error CS1703: An assembly `System.IO' with the same identity has already been imported. Consider removing one of the references (CS1703).
Same message for `System.Runtime' and `System.Threading.Tasks'.
After removing the references then you get this message:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets: Error: Error executing task DetectSigningIdentityTask: Required property 'AppManifest' not set.

**Comment by lothrop** [comment]
What type of project are you adding the library to? The PCL?

See also http://motzcod.es/post/78863496592/portable-class-libraries-httpclient-so-happy
