### ISSUE TITLE
Windows Phone - MvxWindowsPage layout issues

### ISSUE THREAD

**Issue by raketenhunddev** [MvvmCross/MvvmCross#868]
Hi there!

I started using MVVMCross a couple of days ago. I used it for my first W8/WP8 Universal App. I wondered about some layout issues but thought that there were changes between WP8 and WP8.1 I didn't pay attention to. Everything looked fine in Blend and the VS Designer. But when I started the app on a device or emulator some controls have moved.

Today there was another strange layout problem and I tried to find the reason for it. At least I found out that when I copy the content of my MvxWindowsPage to a view with the default Page class, the controls also moved in the designer like it looked on my device. So i placed the controls to their right positions, copied the Content of the Page based view (where everything looks fine) to the MvxWindowsPage based view and finally the layout looked "destroyed" in blend. But when I deploy it on a device it looks like it should!

EDIT: While I was creating a sample for you I found out that this error occurs when using the BottomAppBar

Here is a sample page where this layout issue occurs. Change it's base class (and also the Page.BottomAppBar) to views:MvxWindowsPage and you'll see, that the third row of the root grid is missing.

````XML
<Page
    x:Class="Test.Universal.Views.BlankPage1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Test.Universal.Views"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    xmlns:views="using:Cirrious.MvvmCross.WindowsCommon.Views"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    
    <Page.BottomAppBar>
        <CommandBar>
            <AppBarButton Icon="Back" Label="Previous Month" Command="{Binding PreviousMonthCommand}"/>
            <AppBarButton Icon="Forward" Label="Next Month" Command="{Binding NextMonthCommand}"/>
        </CommandBar>
    </Page.BottomAppBar>

    <Grid>
        <Grid.Background>
            <SolidColorBrush Color="DarkGray"/>
        </Grid.Background>
        
        <Grid.RowDefinitions>
            <RowDefinition Height="50"/>
            <RowDefinition/>
            <RowDefinition Height="50"/>
        </Grid.RowDefinitions>
        
        
        <Grid Margin="0,0,0,0" Grid.RowSpan="1">
            <Grid.Background>
                <SolidColorBrush Color="Gray"/>
            </Grid.Background>
            <TextBlock Margin="10,10,10,0" TextWrapping="Wrap" Text="Dummy" 
                       Style="{StaticResource BodyTextBlockStyle}" VerticalAlignment="Top"/>
        </Grid>
        
        <ListView Margin="10,10,10,10" Grid.Row="1"/>

        <Grid Grid.Row="2" Margin="0,0,0,0">
            <Grid.Background>
                <SolidColorBrush Color="Gray"/>
            </Grid.Background>
            <TextBlock Margin="10,10,10,0" TextWrapping="Wrap" Text="I get lost when using MvxWindowsPage" 
                       Style="{StaticResource BodyTextBlockStyle}" VerticalAlignment="Top"/>            
        </Grid>

    </Grid>
</Page>
````
Here is a screenshot of the designer with Page class:
![screen1](https://cloud.githubusercontent.com/assets/10413980/5697582/2277a28a-99f5-11e4-96bc-62f6dd2dd666.png)

This is how it looks like when using MvxWindowsPage:
![screen2](https://cloud.githubusercontent.com/assets/10413980/5697587/50b8ee2e-99f5-11e4-8ebb-2d4d574aba42.png)

In the designer the third row is missing but when I deploy it to my device it looks as it should!

**Comment by slodge** [comment]
Hmmmm... if this is a designer only issue then it might be that Microsoft hard-coded something in Blend.

Afaik `MvxWindowsPage` just inherits from `Page` and there's nothing we've done that should fool `Blend`.

I wonder what the best way of contacting the Microsoft dev team/Blend team is?

**Comment by slodge** [comment]
PS Thanks for the fab report including screenshots :+1: Is the sample code on github as a project anywhere?

**Comment by raketenhunddev** [comment]
Hello Stuart,

thanks for your response! 

Well now I'm realy confused! I tried to create a sample project for you on a different machine ... On this machine it works ... 

I think I'll try completely reinstall VS on my first machine where the error occured. I'll give you Infos if it worked!

Hope i didn't waste anyones time :S

**Comment by raketenhunddev** [comment]
After hours of un/-installing, testing, debugging, etc. I suddenly found a workaround!

As a test I created a dummy class that inherits from Page. Just a blank class with no content. I took this as base class for my Page and the Designer displayed everything fine! Then I modifed the MvxWindowsPage from the "Cirrious.CrossCore.WindowsCommon" project and removed everything so I only had the blank class with it's inheritance. However this still did'nt work until I removed the "abstract".

My workaround for now is that I created a dummy "MvvmPage" class (also no content) that inherits from MvxWindowsPage and use this in my pages.

Is there any reason why MvxWindowsPage is abstract? The default "Windows.UI.Xaml.Controls.Page" class is not abstract.

**Comment by slodge** [comment]
I think it's abstract because it used to have an abstract method... and because it's still never instantiated directly - it's always inherited.

I've never heard any issues about it being abstract before... but things change...

If you wanted to change it to non-abstract, I think we could happily accept the pull
