### ISSUE TITLE
iOS Project Fails to Compile

### ISSUE THREAD

**Issue by MaximRikel** [MvvmCross/MvvmCross#869]
When compiling basic iOS project with MvvmCross version 3.5 I get the following error:
 
Failed to resolve "Foundation.NSDate Foundation.NSDate::op_Explicit(System.DateTime)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"

**Comment by slodge** [comment]
From #870 is this solved?

**Comment by lothrop** [comment]
Could you please have a look at #864?

**Comment by MaximRikel** [comment]
Thank you. Will try #864.

**Comment by MaximRikel** [comment]
I get:
Unable to find version '3.5.0-beta1' of package 'MvvmCross'
when trying to install with Nuget Console.

**Comment by lothrop** [comment]
Xamarin just released Xamarin.iOS 8.6 on the stable channel. It's probably best to update your Xamarin platform and use 3.5.0-beta2. 3.5.0 final should be out soon.

**Comment by MaximRikel** [comment]
Found it.
The bug is in the method:
public void Include(UIDatePicker date)
in LinkerPleaseInclude class.
Trying to pass DateTime as NSDate.

**Comment by lothrop** [comment]
OK, thanks. I suppose that was already resolved and will be part of the final release.

https://github.com/MvvmCross/MvvmCross/commit/e56ba2cfa79018216693fcff4095d8d090fdcaf1
