### ISSUE TITLE
[HowTo][IoC] Using MvvmX from Background Tasks

### ISSUE THREAD

**Issue by sescandell** [MvvmCross/MvvmCross#871]
Hi everyone,

In our application, we use MvvmX IoC to resolve our dependencies. For that, when the application starts, we configure (manually) all our dependencies using the Mvx.Resolve and friends functions. This is working pretty well... except for Background Tasks. I would like to use Mvx.Resolve function from a Background Task (on a Windows Phone for example). How could we do that?

For now, it seems that MvvmX is not initialized into a background Tasks. Any clue on that point please?

Many thanks,

**Comment by jonstoneman** [comment]
Just had a look at an old Win8 project with a background task - I think the only thing that's done differently is that the MvxSimpleIocContainer.Initialize() static method is called before types are registered.

**Comment by slodge** [comment]
:+1: for what jon just said :)

Also, if you look at StackOverflow, then there are a few questions on this sort of thing already - e.g. the top hit here on https://www.google.co.uk/#q=site:stackoverflow.com+MvvmCross+BackgroundAgent+ is http://stackoverflow.com/questions/24959903/how-to-setup-mvvmcross-in-the-context-of-a-winrt-background-agent

There are also a few articles around for other platforms - e.g. for Android ContentProviders see https://www.google.co.uk/#q=site:stackoverflow.com+MvvmCross+ContentProvider which leads to http://stackoverflow.com/questions/15862980/using-mvvmcross-from-content-providers-and-activities

**Comment by sescandell** [comment]
Hi 

Thank yo both,

@jonstoneman I didn't know about this method. I'll test it, many thanks.

@slodge yes, I've made some searches about ANdroid and so on, but didn't really find a simple anwser or thing saying "this is hwo you should do"... So I was making a try here hoping you have a definitive answer.

Many thanks for your contribution,

Regards,
