### ISSUE TITLE
Error: The type 'MvxEventToCommand' from assembly 'Cirrious.MvvmCross.Wpf' is built with an older version of the Blend SDK

### ISSUE THREAD

**Issue by gregberns** [MvvmCross/MvvmCross#873]
This issue looks a lot like this StackOverflow Q/A, but its from a year ago, not sure whether there's been a fix/change somewhere to get this working...
http://stackoverflow.com/questions/20566243/set-commandparameter-to-currently-tapped-item-on-a-listbox-wp7

Quick steps:
1. Create new project with Ninja
2. Set "MvxTest.WPF" as startup project
3. Go to the WPF project references, and add "System.Windows.Interactivity" 4.5.0.0
4. Open MainView.xaml, replace the contents with this (see below)

```xml
<i:Interaction.Triggers>
  <i:EventTrigger EventName="Tap">
    <commandbinding:MvxEventToCommand Command="{Binding DoSomething}" />
  </i:EventTrigger>
</i:Interaction.Triggers>
```
Error:
The type 'MvxEventToCommand' from assembly 'Cirrious.MvvmCross.Wpf' is built with an older version of the Blend SDK, and is not supported in a Windows Presentation Framework 4 project.	

Full Steps:
1. Open VS2013 (so no projects/solutions should be open)
2. Make sure Ninja coder plugin is installed using 3.2.0
3. Go to Tools > Ninja Coder... > Add Projects
4. On 'Build Options' screen, click Next
5. On Framework, click next
6. On Project Details, add project name 'MvxTest', click Next
7. On View Models, click Next
8. On Plugins, click Next
9. On Nuget, click Next
10. Click Finish
11. Let everything get created
12. Set "MvxTest.WPF" as startup project
13. Go to the WPF project references, and add "System.Windows.Interactivity" 4.5.0.0
13. Open MainView.xaml, replace the contents with this

```xml
<views:BaseView x:Class="MvxTest.Wpf.Views.MainView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:views="clr-namespace:MvxTest.Wpf.Views"
               
             xmlns:i="clr-namespace:System.Windows.Interactivity;assembly=System.Windows.Interactivity"
             xmlns:commandbinding="clr-namespace:Cirrious.MvvmCross.Wpf.Commands;assembly=Cirrious.MvvmCross.Wpf"
    
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
    <StackPanel>
        <TextBox Text="{Binding MyProperty, Mode=TwoWay}" FontSize="30" />
        <TextBox Text="{Binding MyProperty, Mode=TwoWay}" FontSize="30" />

        <ListBox ItemsSource="{Binding DashboardCollection}">
            <i:Interaction.Triggers>
                <i:EventTrigger EventName="Tap">
                    <commandbinding:MvxEventToCommand Command="{Binding DoSomething}" />
                </i:EventTrigger>
            </i:Interaction.Triggers>

            <ListBox.ItemTemplate>
                <DataTemplate>
                </DataTemplate>
            </ListBox.ItemTemplate>
        </ListBox>
        
    </StackPanel>

</views:BaseView>
```

Error:
The type 'MvxEventToCommand' from assembly 'Cirrious.MvvmCross.Wpf' is built with an older version of the Blend SDK, and is not supported in a Windows Presentation Framework 4 project.

**Comment by slodge** [comment]
Thanks

Here's what it's built against - https://github.com/MvvmCross/MvvmCross/blob/3.2/Cirrious/Cirrious.MvvmCross.Wpf/Cirrious.MvvmCross.Wpf.csproj#L39

       <Reference Include="System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" />

Is this out of date now? Has it been out of date for long? Will this break people's existing apps if we update it to 4.5? If it is a breaking issue, we could drop the EventToCommand from the assembly and just let people code it themselves...

**Comment by slodge** [comment]
Thanks - I've bitten the bullet and updated the 3.5 branch to use 4.5.. let's see who screams about this breaking their 4.0 dependent projects...
