### ISSUE TITLE
The type or namespace name 'Touch' does not exist in the namespace 'Cirrious.MvvmCross'

### ISSUE THREAD

**Issue by mbelfer** [MvvmCross/MvvmCross#874]
if Unified build option selected for IOS, the project cannot be compiled since all refereces to mvvmcross packages dlls are pointing to "portable-win+net45+wp8+win8+wpa81+MonoTouch+MonoAndroid" folder. Should they be pointing to "MonoTouch" instead?

**Comment by mribbons** [comment]
I think I have a similar issue.

Have just updated Xamarin:

From VS2013 Help -> About
Xamarin 3.9.236
Xamarin.iOS 8.6.0.0
Xamarin.iOS Unified Migration 1.0

Create a new iOS project (iPhone, Unified)

Add MvvmCross Libraries - nuget setup script seems to detect the project as a Core PCL project, we get App.cs, ViewModels/ etc

Remove MvvmCross Libraries

Try adding MvvmCross.HotTuna.Touch.Dialog, we get the error below:
"Could not install package 'MvvmCross.HotTuna.Touch.Dialog 3.2.2'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

This thread seems similar, but both my PC and my co worker's already have the file in the manual solution as well as the nuget VSIX they seem to refer to.

http://forums.xamarin.com/discussion/24976/xamarin-ios-mvvmcross

**Comment by slodge** [comment]
See #813 and give 3.5 a try. Also on http://slodge.blogspot.co.uk/2014/12/350-beta2-mvvmcross-unified-beta-release.html

**Comment by mribbons** [comment]
3.5-beta2 works with one small issue, I'll post it up now.

**Comment by mribbons** [comment]
OK, looks like the issue is fixed:

https://github.com/MvvmCross/MvvmCross/commit/ca375e527efb374d529345a5460c3cbb65d328a3
