### ISSUE TITLE
duplicate references to System.IO,System.Runtime and System.Threading

### ISSUE THREAD

**Issue by mbelfer** [MvvmCross/MvvmCross#875]
I am getting error with duplicate references to dlls when  trying to compile freshly generated project for IOS. During options selection for Core Nuget packages I only choose HTTP and Json plugins (just Json works fine).

here is 5 minutes video:
https://dl.dropboxusercontent.com/u/96783283/ShareX/2015/01/2015-01-14_10-29-04.mp4

I am using mvvmcross 3.5 beta-2, xamarin.IOS 8.6.0.0. and Unified option

Looked at all closed issues that could be possibly related to mine but do not understand what is it that I am missing. 

The errors I get are coming from Microsoft.Bcl.1.1.9 package which I did not include.
2>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>c:\TEST\Test1\packages\Microsoft.Bcl.1.1.9\lib\portable-net40+win8\System.IO.dll : error CS1703: An assembly with the same identity 'System.IO, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.
2>c:\TEST\Test1\packages\Microsoft.Bcl.1.1.9\lib\portable-net40+win8\System.Runtime.dll : error CS1703: An assembly with the same identity 'System.Runtime, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.
2>c:\TEST\Test1\packages\Microsoft.Bcl.1.1.9\lib\portable-net40+win8\System.Threading.Tasks.dll : error CS1703: An assembly with the same identity 'System.Threading.Tasks, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.

**Comment by slodge** [comment]
I'm afraid I've no idea what this is either :/

Looks like possible nuget or project/linker issue.

Will label it as a bug here - although I don't quite know where to look to fix it right now..

**Comment by JonDouglas** [comment]
Perhaps this will help? https://forums.xamarin.com/discussion/comment/99989/#Comment_99989

**Comment by AndresCRGrecia21** [comment]
As you solved it? It gives me the same error

**Comment by martijn00** [comment]
Did you read what is in the link: http://stackoverflow.com/questions/15551953/how-to-use-the-microsoft-bcl-async-right

I think this is not an issue, but just the app project configured wrong.

**Comment by AndresCRGrecia21** [comment]
Oh thank you, I'll see it!
