### ISSUE TITLE
PictureChooser plugin 3.2.2 memory leak on iOS

### ISSUE THREAD

**Issue by vzsg** [MvvmCross/MvvmCross#876]
The iOS implementation of the IMvxPictureChooserTask interface fails to release the picker view controller along with the raw image data. This leads to erratic camera behavior after taking around three photos on an iPhone 6 (e.g. the camera preview is completely black, though the capture succeeds), and crashing the application in a few more tries.

Instruments shows the increasing memory usage on every take.

AFAICT there is a strong reference cycle there: the task -> picker view controller -> implicitly created Delegate -> the task's delegate methods (hence the task itself). I found with some trial and error that setting the picker's Delegate to null after the capture alleviates this issue.

See: [MvxImagePickerTask.cs](https://github.com/MvvmCross/MvvmCross/blob/3.2/Plugins/Cirrious/PictureChooser/Cirrious.MvvmCross.Plugins.PictureChooser.Touch/MvxImagePickerTask.cs). Lines 118 and 140 are suitable points for the setting.

Also, the CameraDelegate nested class seems to be dead code.

**Comment by slodge** [comment]
Thanks for this.

I guess this might have always leaked - or It might be a compiler/linker change somewhere...

Will leave this open as a "bug" for now - definitely looks like something that needs fixing if anyone wants to use this a lot in an app.

**Comment by vzsg** [comment]
This PR fixed it in my work project as mentioned.

- - -

For the time being and for the lack of a better idea, I'm using my modified version through a proxy service on iOS, and the stock plugin on Android and WP.
