### ISSUE TITLE
Possible need for more binding auto-conversion for new unified numeric types

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#878]
Question seen on jabbr

FabienM
Hi guys
10:26:03 AM
Question: in a unified app that has nint, nfloat, ... all this
10:26:20 AM
if you have some mvx bindings on iOS
10:26:41 AM
like :
10:26:50 AM
set.Bind(_pageControl).For(p => p.CurrentPage).To(vm => vm.ImageIndex);
10:27:21 AM
here the CurrentPage is a nint
10:27:31 AM
and my existing code ImageIndex is an int
10:27:39 AM
so at runtime it fails

Could suggest we need to add code to automatically convert between int and nint

**Comment by lothrop** [comment]
I'm wondering if we should provide a value converter or do some implicit conversions.

**Comment by softlion** [comment]
Should be implicit, or use the default .NET TypeConverter class and register a typeconverter from int to nint, and use TypeConverter in the binding code (like WPF does).

**Comment by softlion** [comment]
public class MvxIntToNIntTargetBinding<T> : MvxTargetBinding
    {
        private PropertyInfo _targetPropertyInfo;

        public MvxIntToNIntTargetBinding(object target, PropertyInfo targetPropertyInfo) : base(target)
        {
            _targetPropertyInfo = targetPropertyInfo;
        }

        public static void Register(IMvxTargetBindingFactoryRegistry registry)
        {
            //Must add all target types and properties here ....
            registry.RegisterFactory(new MvxSimplePropertyInfoTargetBindingFactory(typeof(MvxIntToNIntTargetBinding<UILabel>), typeof(UILabel), "Lines"));
            registry.RegisterFactory(new MvxSimplePropertyInfoTargetBindingFactory(typeof(MvxIntToNIntTargetBinding<UIView>), typeof(UIView), "Tag"));
        }

        public override void SetValue(object value)
        {
            //Convert int to nint
            var target = Target;
            if (target != null && value != null)
            {
                try
                {
                    _targetPropertyInfo.SetValue(target, (nint) (int) value);

                }
                catch (Exception)
                {
                    Mvx.Error("Can not convert {0} to {1} in {2}.{3}", value.GetType().Name, _targetPropertyInfo.PropertyType.Name, typeof(T).Name, _targetPropertyInfo.Name);
                }
            }
        }

        protected override void FireValueChanged(object newValue)
        {
            //Convert nint to int
            base.FireValueChanged((int)newValue);
        }

        public override Type TargetType
        {
            get { return typeof(T); }
        }

        public override MvxBindingMode DefaultMode
        {
            get { return MvxBindingMode.TwoWay; }
        }
    }

**Comment by slodge** [comment]
I was wondering if it might somehow get into `MakeSafeValue` https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Binding/ExtensionMethods/MvxBindingExtensions.cs#L57 - that way the existing code should somehow carry on working...

**Comment by ggirard-distech** [comment]
What about the AutoValueConverters used into `MakeSafeValue`?
Just implemented it that way in my project by overriding the `MvxTouchBindingBuilder` and registering an autoconverter to convert from float to nfloat in bindings... Are you interested in a PR?

**Comment by martijn00** [comment]
@ggirard-distech always interested in pr's and contributors! Bring it on.

**Comment by ggirard-distech** [comment]
Maybe this one should be closed as #1131 has been merged?
