### ISSUE TITLE
Failed to resolve System.Void UIKit.UIGestureRecognizer::set_Delegate reference

### ISSUE THREAD

**Issue by MaximRikel** [MvvmCross/MvvmCross#880]
In new MvvmCross version I get:

Failed to resolve "System.Void UIKit.UIGestureRecognizer::set_Delegate(UIKit.UIGestureRecognizerDelegate)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"

**Comment by lothrop** [comment]
What's your version of Xamarin.iOS?

**Comment by MaximRikel** [comment]
Xamarin.iOS 8.6.0.0

**Comment by lothrop** [comment]
Are you actually using UIGestureRecognizer?

**Comment by MaximRikel** [comment]
Yes. We use it extensively.

**Comment by lothrop** [comment]
I don't see that property being called from MvvmCross. I'm guessing this is a problem either in your code or in Xamarin.iOS.

**Comment by lothrop** [comment]
Closing this for now until more information is provided.
