### ISSUE TITLE
BindableViewPager leaking

### ISSUE THREAD

**Issue by danielcweber** [MvvmCross/MvvmCross#886]
Hi there,

first of all, I know that this issue might as well be raised within the original BIndingViewPager repository (https://github.com/Cheesebaron/Cheesebaron.MvvmCross.Bindings). Since the PagerAdapter used for the BindableViewPager is similar to the Adapters used within MvxListView and I know that @Cheesebaron is a co-owner of this repo, I raise this issue here.

I set up a demo app (https://github.com/danielcweber/BindableViewPagerLeak) to demonstrate a leak in the great BindableViewPager component. If you compile and start the app, and keep clicking on "Navigate" and "Navigate back" (effectively switching between an activity with a BindableViewPager and one without), DDMS shows leaking instances of BindableViewPager, MvxBindablePagerAdapter and SecondView (which is the activity containing the Pager).

I am looking into it as well at the moment. Note that the project uses our fork of BindableViewPager (https://github.com/ExRam/Cheesebaron.MvvmCross.Bindings), but the issue is present in the original code as well. Upon checking out, make sure to init the MvvmCross-Binaries submodule of the Cheesebaron.MvvmCross.Bindings submodule as well.

**Comment by Cheesebaron** [comment]
Since this issue concerns something external of MvvmCross, I think the issue should be raised in the external repo.

**Comment by danielcweber** [comment]
Yeah, probably. Just read on another issue that you're busy with your M.Sc. so I did not want to distract you. I did some further research on this and it turns out that it might not even be an issue, but that Xamarin Android GC kicks in very lazily, sometimes never (causing unneccessary memory pressure on Android). Calling GC.Collect() manually helps.
