### ISSUE TITLE
Not possible to use MvxCachingFragmentActivity with ActionBarActivity

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#887]
I've got an app which uses the appcompat package. To use this package in my activity i need to set ActionBarActivity as my base class. I think it is a pretty common pattern to have an actionbar together with fragments in on activity, but that seems not possible currently. How can this be fixed?

**Comment by IlSocio** [comment]
https://github.com/Cheesebaron/MvxFragmentsAndHamburger/issues/1

**Comment by Cheesebaron** [comment]
Create a new project, rip out all the stuff from FullFragments and change the types to the ones from AppCompat.

**Comment by martijn00** [comment]
@Cheesebaron is this something that should go back into Mvx or do you see this as a separate project?

**Comment by Cheesebaron** [comment]
I think we discussed in some of the other issue threads that we wanted to drop support for the support packages. However, that is always up to reevaluation. 

However, maybe we could think of a generic way to pick which activity you are using? Not sure how that would work, or if it is even possible.

**Comment by martijn00** [comment]
Why would you want to drop support for those packages? I think they are widely used in the Android apps. And if you would ignore the support packages how would someone be able to use a toolbar with fragments in Mvx?

**Comment by kjeremy** [comment]
:+1:

**Comment by martijn00** [comment]
It's possible to use this now since #988 is merged in. See https://gist.github.com/martijn00/fde1c018453bedf096bf for an example of a Compat caching activity.
