### ISSUE TITLE
MvxFrameControl does not expose the protected constructor with IntPtr...

### ISSUE THREAD

**Issue by azchohfi** [MvvmCross/MvvmCross#890]
MvxFrameControl should expose:

protected MvxFrameLayout(IntPtr javaReference, JniHandleOwnership transfer)
:base(javaReference, transfer)
{}

Shouldn't it?

**Comment by Cheesebaron** [comment]
I think it should. Especially when using it in AXML, this will be called first before calling the other ctors. Or so has been the case previously when subclassing a Android type.

**Comment by slodge** [comment]
Y - want to do a Pull Request @azchohfi ? (If you do, you get never-ending fame as a contributor!)

**Comment by azchohfi** [comment]
Ok, sure. I just wasn't sure if it was another problem, but since I was thinking right, preparing PR.
