### ISSUE TITLE
Configurations Issues in iPAD Classic Api Project

### ISSUE THREAD

**Issue by waqas-idrees-confiz** [MvvmCross/MvvmCross#891]
Hi, @slodge  

I am using Xamarin Studio 5.7 (Build 661) and Xamarin.iOS Version: 8.6.0.51 (Trial Edition)

I add core solution and install MVVMCross 3.5.5 in it and It do the right configuration means it add app.cs and firstviewmodel.cs and others files

Then I am adding iOS -> Classic Api -> iPad Empty Project and install MVVMCross 3.5.5 but in this project it will again add app.cs and FirstViewModel but not adding setup.cs and FirstView and Other files of UI Project.

Whats the Issue

**Comment by slodge** [comment]
3.5 does not support the classic api.

new projects should use the unified api

3.2 was our last classic api platform - you can still use that by specifying the version in nuget.

**Comment by waqas-idrees-confiz** [comment]
@slodge How can we install 3.2.2 version in Xamarin Studio Mac I am unable to find any Package Manager on Console

**Comment by lothrop** [comment]
Not sure why you'd want to start a new Classic API project. You'd have to submit it to the App Store no later than January 31.
