### ISSUE TITLE
Consider adding OnLoseFocus Text binding for Android

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#894]
Geir is cool - https://gist.github.com/geirsagberg/8c1a2f6d4596f054dfcb

**Comment by slodge** [comment]
And https://gist.github.com/geirsagberg/aec53838136aba1d6631 for iOS too

Just checking on license

**Comment by martijn00** [comment]
@geirsagberg Is it approved by you if i intergrated your code?

**Comment by geirsagberg** [comment]
@martijn00 Absolutely, go ahead! I'm not 100% satisfied with the name "FocusText" for the binding, maybe "Blur" would be better?

**Comment by martijn00** [comment]
Blur would have another different meaning for me. What about "LoseTextFocus"?

**Comment by martijn00** [comment]
Just named it "TextFocus" now
