### ISSUE TITLE
IMvxCombinedPictureChooserTask for iOS

### ISSUE THREAD

**Issue by habermeier** [MvvmCross/MvvmCross#896]
I'm looking to add IMvxCombinedPictureChooserTask for iOS.  To do it I'd need to add a UIButton to the standard interface that allows a user to switch back and forth between active camera and picture chooser.  

Because there are no default icons I could use to represent camera / picture chooser toggle, I'd likely need to allow the caller to pass in the name of an image asset that would be used for those controls, but that's kind of messy.

Would there be interest in adding IMvxCombinedPictureChooserTask to the PictureChooser plugin for iOS, and if so, would you have any suggestions on how to extend the API to accommodate the UI elements?  One idea would be to add optional arguments to ChooseOrTakePicture(), with default nulls for the image names.

Alternatively maybe there would be a way to get a handle back to the iOS / touch part for the pictureChooserTask object that the view code could address and assign UIButtons to by hand.

Thoughts?

**Comment by martijn00** [comment]
@habermeier It seems you have put some thoughts into this. Could you make a PR so we can review the changes you propose here?

**Comment by habermeier** [comment]
I didn't get around to implementing this yet, but still have interest.  Overall, I don't think it would be that difficult to do, given iOS does allow you to "roll your own" view on the lower section.

**Comment by nickrandolph** [comment]
@habermeier do you think you might have time to put forwards a PR covering this? Even if it's unpolished a basic implementation would help us considerably.

**Comment by Cheesebaron** [comment]
We've removed this plugin long ago. Not applicable anymore.
