### ISSUE TITLE
MvvmCross SQLite.Net-PCL wrapper

### ISSUE THREAD

**Issue by gilbertopavanelli** [MvvmCross/MvvmCross#899]
I started a new universal app using vs 2015 ctp 5, mvvmcross 3.5.0 + sqllite plugin 3.5.0.

I am using the famous N=.... serie of vídeos, especificaly n=12 Collect A Bull as a reference.

I created a new pcl Project as a core and a universal app Project(3 projects), added nuget packages to core , wp8.1 and to w8.1, everything good so far.

Then i copied the service folder from N=12 sample, added related nuget packages.

My trouble is: at this line _connection = factory.Create("collect.sql"); on repository i've got a exception : 

A first chance exception of type 'System.DllNotFoundException' occurred in Cirrious.MvvmCross.Plugins.Sqlite.WindowsCommon.DLL

Additional information: Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

The message is pretty clear cannot found sqlite3.dll i've seen some articles to add file and reference manually, but i did not see nothing on the vídeo, and the N-12 sample runs ok?

How the sample can access the mentioned sqlite dll, it could be related to universal app?

By comparison i found a missing reference in wp project: Community.CsharpSqlite.WP7 i added manually but does not solve.

**Comment by erviem99** [comment]
Hopefully I'm not out of line here, but I very recently moved from the MvvmCross Community SQLite Plugin to SQLite.Net-PCL since there does not seem to be much work going on with the Community SQLite Plugin anymore.

I do not know if that will help you anything though, but IMHO it could be worth a shot.

**Comment by pkl728** [comment]
I just submitted a pull request to the Community SQLite Plugin that updates it to unified iOS API last night.  That being said.  How well does the SQLite.Net-PCL work?  It would be great if we didn't even need to manage a separate project.

**Comment by erviem99** [comment]
It is a bit early to tell how well it works. I just finished up my iOS version and it "just worked". The Android version is next (but it will take a few weeks yet).

I do not use anything fancy though, and all of my SQL code is contained in one singleton class inside a PCL.

All I did was to write a small MvvmCross plugin to pass in the platform specific instance of ISQLitePlatform, and in the same plugin I added a simple function to return the full path of where to store the database file.

I did not find a way to specity what format to use to store the DateTime values though, but I'm happy with just using ticks.

**Comment by slodge** [comment]
@pkl728 I can't remember... do you have admin rights on the SQLite repo? Very keen to make it as easy as possible for those who are using that repo to get it working

**Comment by pkl728** [comment]
@slodge I don't think I am... At least I'm not able to accept pull requests or close out issues.  Although now I'm wondering if it would be better to use something like SQLite.Net-PCL and then the Community SQLite project is just a MVVMCross wrapper around that?

**Comment by slodge** [comment]
The original intention of SQLite-net here was a placeholder... waiting for https://github.com/praeclarum/sqlite-net/issues/135 (and then waiting for PCL)

If SQLite-net now supports PCL - and if it can be wrapped at a factory level using interfaces (don't need interfaces lower down, although they can help for testing sometimes) - then yyyyyyyyYYYYYY - would be fab to use the `main repo` instead.

**Comment by pkl728** [comment]
Ah I see.  I'm not as up to date on [SQLite.Net-PCL](https://github.com/oysteinkrog/SQLite.Net-PCL) by oysteinkrog.

On the surface it looks like this is using a profile 259 PCL as a major goal is to "avoid the use of #if-based conditional code and use platform-specific code injection."

@erviem99 Can you share how easy it was to set up your plugin?

**Comment by gilbertopavanelli** [comment]
Actually, i install the sqllite from sqlite.org and add reference manually and it solved my issue.

Should i close this issue?

**Comment by erviem99** [comment]
I have put together a [gist here](https://gist.github.com/erviem99/2a8943c93b9d6afbb5c2) of how I did it.

Nothing fance at all.

**Comment by benschi11** [comment]
Is there a plugin for SQLite.Net-PCL by oysteinkrog for MvvmCross available on github? 
I worked with this lib on my current windows 8.1 app and it got a lot improvments over the other sql.net lib.

**Comment by MatthewSannes** [comment]
Should I refactor the the SQLite plugin to use SQLite.NET-PCL since it seems the community project isn't getting much traction? SQLite.NET-PCL has been pretty solid in the projects I've used it in.

**Comment by martijn00** [comment]
@MatthewSannes It would be great if you could do that! If you make a PR i'll review it as soon as possible.

**Comment by pkl728** [comment]
I'm a big fan of SQLite.Net-PCL by oysteinkrog.  I found it very easy to create my own plugin and wrap everything up in it.  What hindered me from progressing is the fact that neither @oysteinkrog nor @praeclarum have pulled composite key changes into their projects yet.  These are supported in the current source code for the MvvmCross SQLite Community plugin.  So this will be a breaking change for that.

**Comment by MatthewSannes** [comment]
Hmmm. Your right @pkl728. I haven't had the use case yet to store a composite key in any of my mobile projects. Should I hold off in order to prevent a breaking change?

**Comment by pkl728** [comment]
@MatthewSannes I'm fine with you continuing as I'm using a forked version of MvvmCross Community SQLite since we were never able to get the back into a proper nuget package after I converted it to 3.5.1.

**Comment by martijn00** [comment]
Added here: https://github.com/MvvmCross/MvvmCross-Plugins/pull/1
