### ISSUE TITLE
RadioButton tinting using appcompat v21 doesn't work

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#904]
I inherit from ActionBarActivity and do the following:

```
        public override void SetContentView(int layoutResId)
        {
            var view = this.BindingInflate(layoutResId, null);
            this.SetContentView(view);
        }
```

That's ```MvxBindingContextOwnerExtensions.BindingInflate``` which instantiates a layout factory of type ```MvxBindingLayoutInflatorFactory```.  If I'm reading this right then the view is created via ```Activator```.

Per https://chris.banes.me/2014/10/17/appcompat-v21/ some widgets won't tint properly if this happens.  If I use a standard (non-mvx aware ```ActionBarActivity```) I get the correct colors.

**Comment by kjeremy** [comment]
I think I've figured this out.  See my gist at https://gist.github.com/kjeremy/5b76cb2eb82ff6caa046

**Comment by slodge** [comment]
Thanks :)

Is this something we need to document better :) Or something we could improve some other way?

**Comment by kjeremy** [comment]
I think at the least it should be documented on the wiki.  I'm guessing anyone who uses ```ActionBarActivity``` with AppCompat 7 v21 will need this to get their controls rendering properly.  I'm not sure how we can incorporate that in a plugin.

**Comment by slodge** [comment]
We could add a hook into the standard `CreateView` in `MvxAndroidViewFactory` which allowed interception of requests - i.e. something that allowed registering of objects implement `IMvxViewFactory`like:

      public interface IMvxViewFactory
      {
           bool TryCreateView(string name, Context context, IAttributeSet attrs, out View view);
      }

They could then easily be registered from plugins - e.g. using `Mvx.CallbackWhenRegistered`

**Comment by roubachof** [comment]
The gist code is a nice workaround, but it doesn't work for progressbar accent color.
Also, I think this issue is related to this: https://github.com/MvvmCross/MvvmCross/issues/491

**Comment by kjeremy** [comment]
Progress doesn't tint.  For that you have to use custom drawables.

**Comment by roubachof** [comment]
You're right. But what about MvxSpinner for example ? The tint will fail on this I guess.

**Comment by kjeremy** [comment]
@roubachof I just updated the gist.  What I had to do is make a custom ```MvxTintSpinner``` that derives from ```MvxSpinner``` and swap that out in the inflation.

**Comment by kjeremy** [comment]
With AppCompat 22 it may make sense to see if we can somehow inherit from the new tinting classes or figure out how to use MvvmCross's inflater in a more seamless way.

**Comment by martijn00** [comment]
Fixed by https://github.com/MvvmCross/MvvmCross/pull/1022
