### ISSUE TITLE
Problems with `set only` properties

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#907]
Reported by @gshackles and @ad1dima

I think it might be related to these lines:

https://github.com/MvvmCross/MvvmCross/commit/d12cd86d351ed1c538263f39556670a8e54ff57f#diff-5689ecd1fe0e5ac2a43e64f387a05011R99

If there's no `GetMethod` available then I guess they null reference exception...

**Comment by slodge** [comment]
Discussion chain is https://twitter.com/ad1Dima/status/563653387510874112

**Comment by lothrop** [comment]
I remember this used to work, too. With fluent syntax, however, you couldn't use the type-safe lambda syntax since `vm => vm.MyProperty` didn't compile.

**Comment by evnik** [comment]
@slodge I guess there are should be similar changes in the MvvmCross/CrossUI/CrossUI.Core/ReflectionExtensions.cs.
