### ISSUE TITLE
MvxFragments auto-creating their ViewModels causes crashes in 3.5 when restored from saved state

### ISSUE THREAD

**Issue by davidschwegler** [MvvmCross/MvvmCross#908]
We need a way to opt-out MvxFragments from auto-looking up/creating their ViewModels.

**Bug**
Previously, you could do something like this:

```
var fragment = new MyFragment();
fragment.ViewModel = myViewModel;

// show the fragment
...
```

However, this crashes in 3.5 when the fragment is restored from saved state.

**Cause**
In 3.5, new code in the MvvmCross system looks for/creates a ViewModel for MvxFragments when OnCreate is called. If there is not one, it will crash. This appears to happen if there are any arguments supplied or if the fragment is restoring from saved state: https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Droid.Fragging/Fragments/MvxBindingFragmentAdapter.cs#L37

You currently cannot override this behavior as the parent/host of the fragment, AFAIK, because the child fragment viewmodel lookup is executed when you call base.OnCreate(), and your own ViewModel is not yet set at that point.

**Requested Change**
Opting out from this most simply, I believe, would just involve skipping the calls to HandleCreateCalled() and HandleSaveInstanceStateCalled(). This would restore the pre-3.5 behavior and allow apps to continue using manual viewmodel assignments. 

I'd be fine with [MvxUnconventional] opting out, though that might be a stretch of it's meaning.

That said, it would also be nice to put some additional thought into how to tweak the 3.5 system to support things like fragment pagers, eg by adding an additional option to support saving/reloading but not caching &#91;or initially creating? ... not sure&#93; (since there will be many of the same type).

**Rationale**
In addition to things like #846, there are many scenarios where fragments are used to host or divide up the screen as part of the Android-specific view, where there is no applicable distinct viewmodel, as well as scenarios where the viewmodel must be programmatically set (eg fragment pagers, which are currently broken in 3.5).

**Comment by martijn00** [comment]
Wouldn't it be possible to override protected override InitializeViewLookup so it doesn't include your Fragment to lookup a viewmodel?

void InitializeViewLookup()
    {
        var viewModelViewLookup = new Dictionary<Type, Type>()
        {
            { typeof (FirstViewModel), typeof(FirstView) },
            { typeof (SecondViewModel), typeof(SecondView) }
        };

        var container = Mvx.Resolve<IMvxViewsContainer>();
        container.AddAll(viewModelViewLookup);
    }

**Comment by davidschwegler** [comment]
Hi Martin,

That lookup is only used by Activities when creating an Intent for a MvxViewModelRequest (MvxAndroidViewsContainer line 124).

Setting [MvxUnconventional] something similar to what you're thinking of, I think, bypassing the search for a ViewModel. However, the viewmodel is already being not found -- whether or not it tries to look for it has no difference -- it just returns null:
https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross/ViewModels/MvxViewModelViewTypeFinder.cs#L35 which then crashes when it tries to load a viewmodel of type null.

You can repro this by creating and showing a subclassed MvxDialogFragment, for example, then save/restore the owning activity from state, eg.

	[MvxUnconventional] // optional, doesn't change behavior
	public class TempDialog : MvxDialogFragment
	{
		public override void OnResume()
		{
			base.OnResume();

			Dialog.SetTitle("MY TITLE");
		}
	}


02-11 13:04:03.424: I/mvx(1519):  86.61 No ViewModel class specified for TempDialog in LoadViewModel
02-11 13:04:03.460: I/mono-stdout(1519): mvx:Diagnostic: 86.61 No ViewModel class specified for TempDialog in LoadViewModel
02-11 13:04:03.528: D/Mono(1519): DllImport attempting to load: '/system/lib/liblog.so'.
02-11 13:04:03.532: D/Mono(1519): DllImport loaded library '/system/lib/liblog.so'.
02-11 13:04:03.540: D/Mono(1519): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
02-11 13:04:03.552: D/Mono(1519): Searching for '__android_log_print'.
02-11 13:04:03.556: D/Mono(1519): Probing '__android_log_print'.
02-11 13:04:03.568: D/Mono(1519): Found as '__android_log_print'.
02-11 13:04:03.572: I/MonoDroid(1519): UNHANDLED EXCEPTION:
02-11 13:04:03.600: I/MonoDroid(1519): Cirrious.CrossCore.Exceptions.MvxException: Failed to construct and initialize ViewModel for type  from locator MvxDefaultViewModelLocator - check InnerException for more information ---> System.NullReferenceException: Object reference not set to an instance of an object
02-11 13:04:03.608: I/MonoDroid(1519):   at Cirrious.MvvmCross.ViewModels.MvxDefaultViewModelLocator.Load (System.Type viewModelType, IMvxBundle parameterValues, IMvxBundle savedState) [0x00000] in <filename unknown>:0 
02-11 13:04:03.632: I/MonoDroid(1519):   at Cirrious.MvvmCross.ViewModels.MvxViewModelLoader.LoadViewModel (Cirrious.MvvmCross.ViewModels.MvxViewModelRequest request, IMvxBundle savedState, IMvxViewModelLocator viewModelLocator) [0x00000] in <filename unknown>:0 
02-11 13:04:03.632: I/MonoDroid(1519):   --- End of inner exception stack trace ---
02-11 13:04:03.668: I/MonoDroid(1519): at Cirrious.MvvmCross.ViewModels.MvxViewModelLoader.LoadViewModel (Cirrious.MvvmCross.ViewModels.MvxViewModelRequest,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.IMvxViewModelLocator) <0x0012b>
02-11 13:04:03.668: I/MonoDroid(1519): at Cirrious.MvvmCross.ViewModels.MvxViewModelLoader.LoadViewModel (Cirrious.MvvmCross.ViewModels.MvxViewModelRequest,Cirrious.MvvmCross.ViewModels.IMvxBundle) <0x0005b>
02-11 13:04:03.688: I/MonoDroid(1519): at Cirrious.MvvmCross.Droid.Fragging.Fragments.MvxFragmentExtensions.LoadViewModel (Cirrious.MvvmCross.Droid.Fragging.Fragments.IMvxFragmentView,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.MvxViewModelRequest) <0x00106>
02-11 13:04:03.688: I/MonoDroid(1519): at Cirrious.MvvmCross.Droid.Fragging.Fragments.MvxFragmentExtensions/<>c__DisplayClass1.<OnCreate>b__0 () <0x00027>
02-11 13:04:03.688: I/MonoDroid(1519): at Cirrious.MvvmCross.Views.MvxViewExtensionMethods.OnViewCreate (Cirrious.MvvmCross.Views.IMvxView,System.Func`1<Cirrious.MvvmCross.ViewModels.IMvxViewModel>) <0x00047>
02-11 13:04:03.688: I/MonoDroid(1519): at Cirrious.MvvmCross.Droid.Fragging.Fragments.MvxFragmentExtensions.OnCreate (Cirrious.MvvmCross.Droid.Fragging.Fragments.IMvxFragmentView,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.MvxViewModelRequest) <0x001e7>
02-11 13:04:03.688: I/MonoDroid(1519): at Cirrious.MvvmCross.Droid.Fragging.Fragments.MvxBindingFragmentAdapter.HandleCreateCalled (object,Cirrious.CrossCore.Core.MvxValueEventArgs`1<Android.OS.Bundle>) <0x00353>
02-11 13:04:03.688: I/MonoDroid(1519): at Cirrious.CrossCore.Core.MvxDelegateExtensionMethods.Raise<Android.OS.Bundle> (System.EventHandler`1<Cirrious.CrossCore.Core.MvxValueEventArgs`1<Android.OS.Bundle>>,object,Android.OS.Bundle) <0x00054>
02-11 13:04:03.688: I/MonoDroid(1519): at Cirrious.MvvmCross.Droid.Fragging.Fragments.EventSource.MvxEventSourceDialogFragment.OnCreate (Android.OS.Bundle) <0x00047>

**Comment by slodge** [comment]
paging @Cheesebaron - any ideas?

MvxUnconventional could be a workaround... or maybe some other more specialised attribute? Because things are done in extension methods, I guess we can't do overrides as simply... if only we had multiple inheritance (we'd have loads more issues!)

**Comment by Cheesebaron** [comment]
Now it was my initial idea that the new `Fragment` system had to be thoroughly tested in various scenarios, but I never got to do that due to my Masters Thesis took much attention. The initial test for the Fragment system was only the case of having a Hamburger menu swapping out Fragments and in that specific scenario validating that they got restored correctly, which they did.

I did post here that more samples were needed: https://github.com/MvvmCross/MvvmCross/pull/771#issuecomment-53850566

No one created any hence many use cases were not covered :cry: So this is probably why we are getting bit now that it has just been released to the public and people are actually using Fragments in those use cases described in that link, which is nice. However, now we have to fix that it breaks for them (oops!).

How this exactly needs to be done, must be thought through. I am almost tempted to say that we temporarily implement some kind of measure to disable the new stuff. Implement it properly and then remove the temporary measure.

**Comment by davidschwegler** [comment]
> I am almost tempted to say that we temporarily implement some kind of measure to disable the new stuff. Implement it properly and then remove the temporary measure.

I agree and have done this locally -- I've submitted pull request #915 

It's not like the entire system needs to be disabled app-wide -- there are some cases where the 3.5 functionality is nice. However, to avoid causing crashes in existing fragments and forcing a ton of code (in our case) to be rewritten, it makes much more sense for this to be an opt-in thing in the few cases we want the 3.5 functionality.
