### ISSUE TITLE
Fragment regression since 3.5

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#910]
I have a viewpager which works below 3.5 but breaks with 3.5 and up.  If you clone https://github.com/kjeremy/FragmentStatePagerAdapterCrash and swipe the viewpager over to the end and then back it will crash when trying to set the viewmodel.  Note that if you remove the ChildFragment assignment it won't crash.

Maybe a fix for #908 would help this.

**Comment by davidschwegler** [comment]
Yes, this is the same bug AFAIK. If you decide to work around it, I'd be curious on your solution.

**Comment by kjeremy** [comment]
I'm not sure how I should work around it.  I've tried a number of things that don't work.

**Comment by davidschwegler** [comment]
#915 has been merged in, which will fix this problem for you. I think this case can be closed.
