### ISSUE TITLE
About the MvxWpfFileStore.cs

### ISSUE THREAD

**Issue by antasis9** [MvvmCross/MvvmCross#912]
Hello developers,

Today I found some issue where 'MvvmCross/Plugins/Cirrious/File/Cirrious.MvvmCross.Plugins.File.Wpf/MvxWpfFileStore.cs'
This class has FullPath method which returns roaming folder. 

But roaming folder is shared with other computer that is signed same windows id.
So it isn't suitable save big data of applications.

So I think it may be changed to 'local' folder instead of 'roaming'.

How about your opinion?

**Comment by wenyonk** [comment]
I agree with the proposed solution, or maybe an enum of special folders…? That corresponds to the enum folder path?

**Comment by slodge** [comment]
I guess we could add this as a configuration option for the plugin. I think we'd happily accept a pull that did this.

I'd be unsure about changing the default setting as people are relying on it...
