### ISSUE TITLE
Various solutions

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#917]
Hi, there are four solutions in the repository

_Windows
_Mac
_All
_All_Including_Mac

Is there someplace that describes what each of these are for?

**Comment by tofutim** [comment]
(Now that XamMac.Unified is in the mix, it does not appear that we can compile _All_incl_Mac in Windows, so I am trying to build in OS X using TeamCity)

**Comment by lothrop** [comment]
I've been wondering the same. The problem with a solution that contains both Mac and Windows is that there's no platform/IDE combination that supports all project types supported by MvvmCross.

**Comment by tofutim** [comment]
I've been working on this and believe I have come up with a good solution. You can have unsupported project types, but they need to be removed from the Build sequence. The annoying thing is that you cannot remove them from the Xamarin Studio or Visual Studio IDE if you cannot load the project. However, you can toggle them by editing to the sln. 

Currently I am using _All_Incl_Mac for both VS and XS. However, I have excluded Unified from the Mixed Platforms configuration. I have added a new configuration called Unified that just has Unified and the necessary PCLs. Using an OSX agent in TeamCity, I compile the Unified dlls, copy them over to a Windows agent, and compile the Mixed Platforms dlls, and will use the Windows agent to package the nuget. Still working on it, but I think it will work fine.

**Comment by slodge** [comment]
I'm happy to see this cleaned up.

I only use the "_All" solution - as I'm not an active Mac developer.

I'm really not a build engineer... I'm happy for someone else to really push forwards in this area to clean up Mvx to make it cleaner and more usable... **but** I do insist that what I release as Mvx has to be buildable simply from a single PC... I guess the challenge here is that the Windows projects need Windows, and the Mac projects need Mac.... :/

**Comment by tofutim** [comment]
With Xamarin Unified, everything can no longer be built from a single PC or
a single Mac. Sadly.

**Comment by lothrop** [comment]
Wasn't the problem there before Xamarin.Mac Unified? It was never possible to build Xamarin.Mac or MonoMac on Windows. And it was never possible to build WPF, Windows Store or Windows Phone on Mac.

**Comment by tofutim** [comment]
I always built Xamarin.Mac and MonoMac on Windows. You can bring the
XamMac.dll and MonoMac.dll from Mac onto the Windows machine and it works
fine. The problem is that the nuget doesn't work so you have to create
separate nuget chains for XamMac and MonoMac. I was able to use Windows
compiled dlls for these with no problems.

It has never been possible to build WPF, Windows Store and Windows Phone on
Mac.


On Wed, Feb 25, 2015 at 11:55 AM, Kerry W. Lothrop <notifications@github.com

**Comment by lothrop** [comment]
Interesting, I didn't know that. I assume you couldn't deploy or execute anything (unlike iOS)?

So copying Xamarin.Mac.dll to your Windows machine doesn't do the trick?

**Comment by tofutim** [comment]
It doesn't work this time because Xamarin placed a special identifier in
XamMac.Unified projects that does not allow it to open in Visual Studio, or
in Xamarin Studio in Windows. If not for this identifier it could work.
This thing:

     <ProjectTypeGuids>
{A3F8F2AB-B479-4A4A-A458-A89E7DC349F1};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}
</ProjectTypeGuids>

You couldn't deploy or execute anything, but the end results could be
compiled into nuget and used on the Mac side. I've been looking at the
XamMac Unified code (did you write this?), it looks like we just need to
transfer a bunch of stuff from XamMac to this. I wonder if we should just
remove MonoMac and XamMac (classic) ultimately.

For a while I thought that XamMac.Unified could be used for both Mac and
iOS, but I guess they just mean there is overlap in the way functions are
called, and that x32/x64 are both compiled. I have to do some more cleaning
of the nuget.

**Comment by tofutim** [comment]
I think ultimately we should drop MonoMac and XamMac (Classic) and make
XamMac.Unified just .XamMac or even .Mac.

**Comment by martijn00** [comment]
@tofutim How is the current state? Can we make your suggested change and remove MonoMac and XamMac (Classic)?

**Comment by tofutim** [comment]
I think it is possible, but I need to review everything again. I believe it
is possible to do that though.

**Comment by tofutim** [comment]
I'll take a look at this in the next couple weeks. With Mac supported by
.iOS, it should become very clean.

**Comment by martijn00** [comment]
This has been cleaned up.
