### ISSUE TITLE
3.5.0 Dispose MvxViewClickBinding carshing in release mode

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#919]
E/mvx     (11339):  98,80 Domain Exception from  System.AppDomain: ArgumentException: 'jobject' must not be IntPtr.Zero.
E/mvx     (11339): Parameter name: jobject
E/mvx     (11339):        at Android.Runtime.JNIEnv.CallV
E/mvx     (11339): oidMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue[] parms) [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Android.Views.View.SetOnClickListener (IOnCli
E/mvx     (11339): ckListener l) [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Android.Views.View+<>c__AnonStorey7.<>m__0 (IOnClickListener __v) [0x00000] in <filename unknown>:0
E/mvx     (11339):   at
E/mvx     (11339): Java.Interop.EventHelper.RemoveEventHandler[IOnClickListener,IOnClickListenerImplementor] (System.WeakReference& implementor, System.Func`2 e
mpty, System.Action
E/mvx     (11339): `1 unsetListener, System.Action`1 remove) [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Android.Views.View.remove_Click (System.EventHandler value) [0x00000] in <file
E/mvx     (11339): name unknown>:0
E/mvx     (11339):   at Cirrious.MvvmCross.Binding.Droid.Target.MvxViewClickBinding.Dispose (Boolean isDisposing) [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Cirrious
E/mvx     (11339): .MvvmCross.Binding.Bindings.MvxBinding.Dispose () [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Cirrious.MvvmCross.Binding.Bindings.MvxFullBinding.ClearTargetBinding
E/mvx     (11339): () [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Cirrious.MvvmCross.Binding.Bindings.MvxFullBinding.Dispose (Boolean isDisposing) [0x00000] in <filename unknown>:0
E/mvx     (11339):
E/mvx     (11339):  at Cirrious.MvvmCross.Binding.Bindings.MvxBinding.Dispose () [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Cirrious.MvvmCross.Binding.BindingContext.MvxBindingContex
E/mvx     (11339): t.ClearAllDirectBindings () [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Cirrious.MvvmCross.Binding.BindingContext.MvxBindingContext.ClearAllBindings () [0x00000] in
E/mvx     (11339):  <filename unknown>:0
E/mvx     (11339):   at Cirrious.MvvmCross.Droid.Views.MvxBindingActivityAdapter.EventSourceOnDestroyCalled (System.Object sender, System.EventArgs eventArg
E/mvx     (11339): s) [0x00000] in <filename unknown>:0
E/mvx     (11339):   at (wrapper delegate-invoke) <Module>:invoke_void_object_EventArgs (object,System.EventArgs)
E/mvx     (11339):   at Cirrious.CrossCore.Cor
E/mvx     (11339): e.MvxDelegateExtensionMethods.Raise (System.EventHandler eventHandler, System.Object sender) [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Cirrious.CrossCore.Droid.Vi
E/mvx     (11339): ews.MvxEventSourceActivity.OnDestroy () [0x00000] in <filename unknown>:0
E/mvx     (11339):   at Android.App.Activity.n_OnDestroy (IntPtr jnienv, IntPtr native__this) [0x00000]
E/mvx     (11339): in <filename unknown>:0
E/mvx     (11339):   at (wrapper dynamic-method) object:f948f30c-58f7-4da4-b2f7-303af0fac468 (intptr,intptr)

**Comment by slodge** [comment]
Thanks.

Please try to put yourself in the position of someone who might want to help with this.

It's great that you've given them a stack trace.

Is there any additional information you can think of that might help?

For example:
- maybe some information about what was happening in the app at the time?
- maybe some information about whether this is new in 3.5? (Did the same code work in older versions?)
- maybe some information about what version of Android and Xamarin.Android is being used? And some information about whether you are building in VS or XS (and whether on a Mac or on a PC)
- maybe a repro sample? (Or at least some snippets of sample code)

If it helps, I'm happy for people to publish issues in whatever language they feel happiest working in (I can use g translate to get the gist of some things).

Thanks

**Comment by softlion** [comment]
Ok it is reproductible everytime.
You have views A, B and C. Open A => B => C. In C, showviewmodel A. In custom presenter, it opens view A with a CLEAR_TOP flag which reopens the existing A and closes B and C. At this the moment  the exception is thrown. I suppose views B and C are disposed by the system, and the bindings are also disposed. The binding seems to come from a menu button inserted using this code:

    <item android:id="@+id/action_done" android:showAsAction="always" android:actionLayout="@layout/menuitem_done" />

and layout:

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:local="http://schemas.android.com/apk/res-auto"
    android:orientation="horizontal"
    android:layout_width="wrap_content"
    android:paddingRight="10dp"
    android:gravity="center_vertical"
    android:layout_height="wrap_content">
    <FrameLayout
        android:layout_width="wrap_content"
        android:layout_height="@dimen/BtnRadius">
        <Button
            android:id="@+id/done"
            android:text="DONE"
            local:MvxBind="Text [DONE]"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAppearance="@style/TextFont3Bold"
            android:background="@drawable/btns_action"
            android:textColor="#fff" />
    </FrameLayout>
    </LinearLayout>

**Comment by softlion** [comment]
this is new in 3.5

**Comment by softlion** [comment]
Problem is not related to the option menu. Happens in debug and release mode. Searching.

**Comment by softlion** [comment]
It is related to MvxListView. When the layout of screen C contains an MvxListView, it crashes. If it does not contain an MvxListView, no crash.

**Comment by softlion** [comment]
I installed 3.5.1-alpha1 and the crash is gone. Thank you for the release note (where it it ? ;) )

**Comment by Cheesebaron** [comment]
https://github.com/MvvmCross/MvvmCross/tree/3.5.1-alpha1

**Comment by slodge** [comment]
http://slodge.blogspot.co.uk/2015/02/351-alpha-release.html

If 3.5.1 fixed it, then my guess is that it wasn't a bug or change in 3.5 - it was a change in GC within xam...

**Comment by softlion** [comment]
Oh you are right, i already switched to alpha1 on ios. Missed it on Android. What a looser ...
