### ISSUE TITLE
Missing stylable field MvxExpandableListView

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#921]
In android 3.5.1 alpha1:

   ExpandableListViewStylableGroupId =
    71                      (int[])SafeGetFieldValue(styleable, "MvxExpandableListView", new int[0]);
    72                  GroupItemTemplateId =
    73                      (int)SafeGetFieldValue(styleable, "MvxExpandableListView_GroupItemTemplate");

The style attributes are not defined withing mvvmcross. This generates errors in my app. They should be defined in attrs.xml

Missing stylable field MvxExpandableListView
Missing stylable field MvxExpandableListView_GroupItemTemplate
Softlion
  
Adding these lines to attrs.xml should fix the issue:

    <declare-styleable name="MvxExpandableListView">
      <attr name="GroupItemTemplate" format="reference"/>
    </declare-styleable>

**Comment by slodge** [comment]
Wondering if this is just an issue in the nuspec copy of the file...

Seems to be ok in:

https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Binding.Droid/ResourcesToCopy/MvxBindingAttributes.xml

**Comment by softlion** [comment]
Why don't you leave this resource as a resource in the Android lib ? It work perfectly IF AND ONLY IF your android lib is marked as a lib in the csproj file. 

    <OutputType>Library</OutputType>

**Comment by slodge** [comment]
Why?

**History** - that option wasn't available back when we wrote this part of Mvx (and when it did become available it sucked for quite a few months!).

https://github.com/MvvmCross/MvvmCross/issues/112

I know @Cheesebaron has talked about this recently too.

**Comment by softlion** [comment]
Well this works since 9 months at least. But it was working for both Android app projects converted to libs. Now it works only with libs.

**Comment by slodge** [comment]
I've fixed the out of date file in the DroidContent folder.

If anyone wants to fix/change the way the file is linked and to then QA it, then I'd accept the pull.

But for now, I'm closing this as fixed

**Comment by milky-la** [comment]
What about MvxExpandableListView_GroupItemTemplate? I can't run when building form sources due to it.

**Comment by Cheesebaron** [comment]
Runs fine here. You need to provide more information about what does not run, what errors you get etc.
