### ISSUE TITLE
MvxNSDatePickerDateTargetBinding timezone issues

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#924]
Probably some of you don't see it because you are at GMT, but there are some wretched timezone issues when setting dates back and forth between DateTime and NSDatePicker in Mac. :P

**Comment by tofutim** [comment]
Ok, I think i sorted this out, will send a PR later.

**Comment by lothrop** [comment]
Thanks

**Comment by martijn00** [comment]
@tofutim Is there already a PR available for this? Then i could close this issue.
