### ISSUE TITLE
Could not install package 'MvvmCross.PortableSupport 3.5.0'

### ISSUE THREAD

**Issue by Tohnmeister** [MvvmCross/MvvmCross#925]
When trying to add the MvvmCross Getting Started package in my Visual Studio PCL project for Xamarin iOS and Android only, I'm getting the following error

> Could not install package 'MvvmCross.PortableSupport 3.5.0'. You are trying to install this package into a project that targets 'portable-net45+sl50+Xamarin.iOS10+MonoAndroid10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I've already tried changing the profile to 259, as described [here](http://stackoverflow.com/questions/26068750/could-not-install-package-mvvmcross-portablesupport-3-2-1-at-visual-studio-2013), but the error persists.

I've also tried using the Ninja Coder tool, by only selecting iOS and Android, but at some point during the creation of the project the tool gives me exactly the same error.

I'm using Visual Studio 2013 update 3.

Any clues on what I'm doing wrong or should change to be able to use MvvmCross in my project?

**Comment by slodge** [comment]
`MonoTouch10` is pre-Unified.

3.2 was our last non-Unified release

See release notes on http://slodge.blogspot.com

**Comment by Tohnmeister** [comment]
Thanks for the quick answer.

Not so much related to MvvmCross, but any idea on how I can remove MonoTouch10 from the targets of the PCL? As far as I know, I'm using the unified API only in the iOS projects that reference the PCL. Next to that, I can't find any occurrences of the word monotouch in any of the files or filenames in my solution.

**Comment by Cheesebaron** [comment]
> Any idea on how I can remove MonoTouch10 from the targets of the PCL?

You can't.

Your problem is this:

> sl50

Ew silverlight...

**Comment by Tohnmeister** [comment]
You're right. The problem was that Visual Studio 2013 update 3 kept adding silverlight 5 as a target, although I didn't select it. After upgrading to update 4 the problem seems solved. 

Thanks for the help.
