### ISSUE TITLE
Presenter for Tabbar based on MvxModalNavSupportTouchViewPresenter not possible

### ISSUE THREAD

**Issue by xleon** [MvvmCross/MvvmCross#927]
I´m trying to write a presenter based on "MvxModalNavSupportTouchViewPresenter" with support for tabbar root view and also modal "popups" with its own navigation. My "HomeView" is the tabbar and I need to set a reference to "_currentModalViewController" [(now it´s actually private)](https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Touch/Views/Presenters/MvxModalNavSupportTouchViewPresenter.cs#L18) in order to do that.

The reason for this would be to do something like the following:

```c#
public override UINavigationController MasterNavigationController
		{
			get
			{
				if (_currentModalViewController != null)
				{
					UINavigationController modalNavigationController = _currentModalViewController.ParentViewController as UINavigationController;
					return modalNavigationController;
				}
				else
				{
					var navController = homeView.ViewControllers[homeView.SelectedIndex];
					return (UINavigationController)navController;
				}
			}
		}
```

So I just need the "_currentModalViewController" to be protected instead of private if you think that´s correct

**Comment by slodge** [comment]
I wouldn't support making any field protected - the OO purists would be too upset ;)

If you wanted to make it work some other way - e.g. using a protected property or using some other refactoring which enabled you to share logic across classes (e.g. maybe introducing some new base class for the family of modals) then I think we'd be open to that.

The modal presenter itself is pretty limited - it's one that people often have to replace/extend - so you might not want limit yourself to it...

**Comment by xleon** [comment]
After some work I realized the presenter is so tightly coupled to the project needs that I understand now why the built in presenters are limited. Thanks anyway!
