### ISSUE TITLE
Missing constructors (JniHandleOwnership, mono)

### ISSUE THREAD

**Issue by JanZeman** [MvvmCross/MvvmCross#928]
Hello, our MvvmX based app is crashing on freshly updated Android Lollipop with this exception: http://stackoverflow.com/questions/26573627/no-constructor-found-for-system-intptr-android-runtime-jnihandleownership

I've forked MvvmX and added these constructors to the corresponding classes - will create a pull request. Thank you, Jan

**Comment by JanZeman** [comment]
PR created: https://github.com/MvvmCross/MvvmCross/pull/929

**Comment by Cheesebaron** [comment]
This has been merged, thanks :+1:
