### ISSUE TITLE
MvxCommand constructor exception

### ISSUE THREAD

**Issue by tbitowt** [MvvmCross/MvvmCross#930]
I have created new project(MvvmCross + Xamarin.Forms) with MvvmCross addon to VS.
I have added new ICommand to MainViewModel and binded it to Button in xaml like this:

I'm running this project on Android

ViewModel:

    using System.Diagnostics;
    using System.Windows.Input;
    using Cirrious.MvvmCross.ViewModels;

    namespace XamarinFormsMvvm.Core.ViewModels
    {
        public class MainViewModel : BaseViewModel
        {
            private string sampleText = "Hello from the Ninja Coder!";

            private string sampleText2 = "Hello2";

            public MainViewModel()
            {
            
            }

            public string SampleText
            {
                get { return this.sampleText; }
                set { this.SetProperty(ref this.sampleText, value); }
            }

            public string SampleText2
            {
                get { return this.sampleText2; }
                set { this.SetProperty(ref this.sampleText2, value); }
            }

            public ICommand StartStopCommand
            {
                get
                {
                    return new MvxCommand(() => Debug.WriteLine("Test"));
                }
            }
        }
    }

View:

	<?xml version="1.0" encoding="utf-8" ?>
	<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
				 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
				 x:Class="XamarinFormsMvvm.Forms.Views.MainView"
				 xmlns:viewModels="clr-namespace:XamarinFormsMvvm.Core.ViewModels;assembly=XamarinFormsMvvm.Core"
				 Title="MainView Page"
				 >
	  <ContentPage.BindingContext>
			<viewModels:MainViewModel />
		</ContentPage.BindingContext>
	  <ContentView>
		<StackLayout>
			<Label Text='{Binding SampleText}' VerticalOptions='Center' HorizontalOptions='Center'/>
			<Label Text='{Binding SampleText2}' VerticalOptions='Center' HorizontalOptions='Center'/>
			<Button Command="{Binding StartStopCommand}" Text="asd" VerticalOptions="Center" HorizontalOptions="Center"/>
			
		</StackLayout>
	  </ContentView>
	</ContentPage>

In runtime I'm getting exception:

	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
	03-05 18:32:16.898 I/MonoDroid( 2699):   at Cirrious.CrossCore.Mvx.TryResolve[IMvxCommandHelper] (IMvxCommandHelper& service) [0x00000] in <filename unknown>:0 
	03-05 18:32:16.898 I/MonoDroid( 2699):   at Cirrious.MvvmCross.ViewModels.MvxCommandBase..ctor () [0x00000] in <filename unknown>:0 
	03-05 18:32:16.898 I/MonoDroid( 2699):   at Cirrious.MvvmCross.ViewModels.MvxCommand..ctor (System.Action execute, System.Func`1 canExecute) [0x00000] in <filename unknown>:0 
	03-05 18:32:16.898 I/MonoDroid( 2699):   at Cirrious.MvvmCross.ViewModels.MvxCommand..ctor (System.Action execute) [0x00000] in <filename unknown>:0 
	03-05 18:32:16.898 I/MonoDroid( 2699):   at XamarinFormsMvvm.Core.ViewModels.MainViewModel.get_StartStopCommand () [0x00001] in c:\Users\Tomasz\Documents\Visual Studio 2013\Projects\XamarinFormsMvvm\XamarinFormsMvvm.Core\ViewModels\MainViewModel.cs:49 
	...........

Seems that there is Null Refference somewhere in IoC? How should I fix that?

**Comment by slodge** [comment]
What Setup has run? what IoC is initialized? Is there an IMvxCommandHelper registered?

**Comment by tbitowt** [comment]
Does not Ninja Coder set it up by default? I have created a project with Ninja Coder with MvvmCross and Xamarin.Forms support and all other properties left as default.

BTW. I have set a breakpoint on `InitializeCommandHelper` method in `Setup` but it's not even getting there (seems that exception is fired before that)

You can find it here: https://github.com/tbitowt/MvvmCrossXamarinForms

**Comment by slodge** [comment]
Closing as I think this has been moved elsewhere (think I saw it on StackOverflow)
