### ISSUE TITLE
PictureChooser - Save image to gallery

### ISSUE THREAD

**Issue by Iggda** [MvvmCross/MvvmCross#936]
By default Android saves the image taken with PictureChooser to gallery (not the apps Application folder), but iPhone does not.

It would be great to have a setting on the TakePicture-action to decide wether the image should also be saved on the phone or not, so that we don't have different behaviors between the platforms. 

Does this already exist?

**Comment by slodge** [comment]
If you have code you think could be integrated as an option, then the project would be happy to consider the pull request

**Comment by mohibsheth** [comment]
If I am not wrong, the plugin does not do anything to save the captured image to the gallery. It's the camera app which does this and if required on iOS, the user can easily add the feature to his own app, since adding to core does not make sense here.

**Comment by randragon42** [comment]
So how would one prevent the camera app on Android from saving the photo to the gallery?

**Comment by mohibsheth** [comment]
@randragon42 I don't think there is a way to prevent it. You would have to delete the copy yourself after the image has been captured. There should be ways on how to do this on SO.
