### ISSUE TITLE
[Xamarin + Android] Finishing the activity using a MvxPresentationHint - Cast Context to Activity fails

### ISSUE THREAD

**Issue by tweek82** [MvvmCross/MvvmCross#937]
Hi,
I'm trying to create a neat solution for the following situation:

I've build an app that requires credentials to authenticate the user. Whenever the API wants to reauthenticate the user I would like to force the user back to the login-view. This functionality works great, but when the user presses the back button on the device, the previous view is shown. I would like to see that when the user presses the back button the application exits.

I know that you should call Finish(); on an activity to prevent the backbutton to navigate back to the unauthenticated view. But casting the applicationContext to throws an exception.

        public CustomAndroidViewPresenter(Context context)
        {
            _context = context;
        }

        public override void ChangePresentation(MvxPresentationHint hint)
        {
            if (hint is LoginOnlyBackStackHint)
            {
                var context = Application.Context;
                if (context is Activity)
                {
                    // Context is NOT activity
                }
                try
                {
                    Activity x = (Activity) context;
                    x.Finish();
                    // Exception is thrown
                }
                catch (Exception ex)
                {

                }
            }
            base.ChangePresentation(hint);
        }

Does someone have any ideas how to achieve this?

Many thanks in advance.

**Comment by slodge** [comment]
I think this might be best asked on StackOverflow.

MvvmCross has some hints it can provide - e.g. it tries to keep track of the top activity - but the larger Android community on StackOverflow may have better solutions
