### ISSUE TITLE
ShowViewModel Twice when i click fast

### ISSUE THREAD

**Issue by benhaben** [MvvmCross/MvvmCross#942]
I use mvx in my project and i dig into the code, i find one issue is hard to fix. When I bind one command to button and click very fast in my simulator(or phone), the view will show twice and i need to return twice to my original view. if you repeat more than one time, the view will become black and crash, log's output is print "Finishing up a navigation transition in an unexpected state. Navigation Bar subview tree might get corrupted.". I fix crash by set animated = false, see below in the file /Cirrious/Cirrious.MvvmCross.Touch/Views/Presenters/MvxTouchViewPresenter.cs                MasterNavigationController.PushViewController(viewController, false /*animated*/);
but the view still show twice, could you have a look at it?

**Comment by slodge** [comment]
If this is an issue in your app because of asynchronous paths, then you could dampen the behaviour using a custom presenter.

Greg Shackles' blog has some recent posts about how to do this in iOS
