### ISSUE TITLE
about MvvmCross 3.5.0 in Visual Studio 2015 errorlist

### ISSUE THREAD

**Issue by dearsherlock** [MvvmCross/MvvmCross#943]
Hi dear sir:
I saw the following development tools error message, but did not actually perform problem, the other is to change how I use the tools built-in nuget instead of performing in hidden directories nuget executable file? Thank you!
https://farm8.staticflickr.com/7615/16238889364_e299d27158_o.png

p.s.  I try it work well in mac xamarin studio and add nuget package MVVMCross 3.5.0 .

**Comment by slodge** [comment]
This looks like a general PCL setup issue - maybe try "Clean".

If that doesn't help, maybe try on stackoverflow - there's a bigger audience there for people who can help with issues and questions.

Thanks

Stuart
