### ISSUE TITLE
After updating an existing app to the unified API in Xamarin, Failed to resolve "System.Boolean

### ISSUE THREAD

**Issue by bertct** [MvvmCross/MvvmCross#946]
After update existing app to the Unified API, and update the mvvmCross libraries to 3.5, when I try to compile in Iphone the nex error is show:

Failed to resolve "System.Boolean Cirrious.VvvmCross.ViewModels.MvxNavigatingObject::ShowViewModel(Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.MvxBundle,Cirrious.MvvmCross.ViewModels.MvxRequestedBy)" reference from "Cirrious.MvvmCross, Version=1.0.0.0, Culture=neutral, PublickKeyToken = e16445fd9b451819" (MT2002)

Archive: MTOUCHTASK

And if I double click in the error, then I get the message:

File not found: /User/Admin/Desktop/Project/iPhoneProject/MTOUCHTASK

What I'm missing? I have to update somthing else?

P.D.: I Updated Xamarin as well.

**Comment by pkl728** [comment]
If you just updated everything I would highly recommend you go and redownload all of the packages you are using.  But prior to doing that, verify you are on a compatible PCL Profile.  The newest MvvmCross is using profile 259.

**Comment by bertct** [comment]
Hi @pkl728 sorry but I don't know how to verify if I'm on a compatible PCL Profile, or what it means that MvvmCross is using profile 259.

**Comment by pkl728** [comment]
If you open your "Core" solution you should see a line like this:  
<TargetFrameworkProfile>Profile259</TargetFrameworkProfile>

You'll need to open your .csproj in a text editor to see it.  Basically Profile259 means that it supports .NET Framework 4.5 or later, Windows Phone 8.1 or later, Windows 8, Windows Phone Silverlight 8, Xamarin.Android, Xamarin.iOS Classic, Xamarin.iOS Unified and Xamarin.Mac Unified.

**Comment by bertct** [comment]
Thanks @pkl728 but I don't know if I'm unedestanding you. I'm not using this libraries in a pcl, I'm using this libraries on a iPhone project.

If I go to the properties of this project (or I open the .csproj in a txt editor) I see no options to change the profile or the frameworks.

I have updated all my packages, but the error remains...

Do I have to add some other library that it's PCL?... I think I'm missing somthing.

**Comment by pkl728** [comment]
You are doing your SQLite calls in the iOS project?  That should typically be done in your core logic.  I do not believe profile 158 is compatible with the newest MvvmCross.

**Comment by bertct** [comment]
We are using LexDb, so we make the calls depending on the plataform, do you know why Profile158 is not compatible with the newest MvvmCross? it's too restrictive?

**Comment by pkl728** [comment]
Sorry I had the SQLite project in my mind, ignore my previous comment.  

The core project your iOS project references is the project that you are attempting to update to the newest MvvmCross.  All of the MvvmCross libraries as of the latest point are compiled in profile 259.  As to why you can find that here:  http://slodge.blogspot.com/2014/09/321-released-one-windows-support.html 

Particularly this comment from Stuart:
*The support means you now must use a "new profile" like Profile 259 or Profile 78 to get working... don't blame me for this... blame Microsoft ;)*

**Comment by bertct** [comment]
Hi @pkl728 Thanks! it was this, when I changed ALL of my PCL to have Profile 78, then the app compiled, now I have to look why the httpclient throws an exception when it's executed, but that's just another topic.
