### ISSUE TITLE
Command execute many times

### ISSUE THREAD

**Issue by benhaben** [MvvmCross/MvvmCross#948]
Hi 
I find when i click a button which bind to a mvxcommand, the command will execute many times.
I add the code int the ControlOnTouchUpInside, but it's not fix the issue, any body know how to fix the issue?
           control.UserInteractionEnabled = false;
            _command.Execute(null);
            Foundation.NSTimer.CreateScheduledTimer(3, (t) => {
                control.UserInteractionEnabled = true;
            });

private void ControlOnTouchUpInside(object sender, EventArgs eventArgs)
        {
            if (_command == null)
                return;

            if (!_command.CanExecute(null))
                return;

            _command.Execute(null);
        }

**Comment by Cheesebaron** [comment]
I don't see an actual binding.

**Comment by benhaben** [comment]
it's a bug of my app. i bind a command in a callback function, but the function was called many times, so the command bind many times, and then when i click it, it execute many times. i am sorry to waste your time.
