### ISSUE TITLE
Add License headers to Fragging stuff

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#950]
https://github.com/MvvmCross/MvvmCross/tree/3.5/Cirrious/Cirrious.MvvmCross.Droid.FullFragging/Presenter

https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Droid.FullFragging/MvxCachingFragmentActivity.cs

Ooops, I forgot to add headers. The files are of course ~~MIT~~ MS-PL licensed.

**Comment by slodge** [comment]
MIT license?

Really....

not MS-PL like the rest of MvvmCross :(


I'm not precious about this. I picked MS-PL because.... well, because it looked "free" and "open" and because I got bored reading through the options... but I would like all of the project to be one license if we can :)

**Comment by Cheesebaron** [comment]
Ah sry, MS-PL :)

**Comment by slodge** [comment]
Phew :)
