### ISSUE TITLE
Unable to install mvvmcross using nuget in vs2015 ctp6

### ISSUE THREAD

**Issue by binoypatel** [MvvmCross/MvvmCross#951]
Hi there,

I have a PCL project targeting to Windows 8.1 and Windows Phone 8.1 only. I am trying to add MvvmCross (beta 3.5.1 beta 1 and stable 3.5.0) and getting following error:
Install-Package : Value cannot be null.
Parameter name: zipArchiveEntry
At line:1 char:1
+ Install-Package MvvmCross -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCom
mand

Is it possible to look into this issue and rectify it?

Thanks,
Binoy

**Comment by Cheesebaron** [comment]
Maybe wait for a stable version? Or you could use the Binaries instead meanwhile. There is no sense in fixing something that might be a problem because you are using a preview version of something...

**Comment by monesprit54** [comment]
Successfully using MvvvmCross with vs2015 ctp6.
