### ISSUE TITLE
iOS IMvxPictureChooserTaskpictureAvailable Action is just called once

### ISSUE THREAD

**Issue by roubachof** [MvvmCross/MvvmCross#952]
private readonly IMvxPictureChooserTask pictureChooser;

    this.pictureChooser.ChoosePictureFromLibrary(
                maxPixelDimension, 
                percentQuality, 
                pictureAvailable, 
                assumeCancelled);

First call to ChoosePictureFromLibrary will call pictureAvailable on image selection, following ones won't invoke the callback.

It was working a month ago. I don't know if it's linked to a Xamarin update or the new beta.

**Comment by slodge** [comment]
Is it related to https://github.com/MvvmCross/MvvmCross/commit/9d6cf7c38cc74778e9ad3f07f42fa35bebbeea5a ?

I'm not sure if we've had any other changes in this area here

**Comment by barbualexxa** [comment]
I recently updated MVVM Cross to version 3.5.1 and I encountered the same "bug" in my app. The camera works great the first time, but the second time, even though the picture is taken, the callback function is not called anymore. Is there any fix available regarding this item?

**Comment by barbualexxa** [comment]
It is related to the 9d6cf7c commit. When setting the delegate to null, you also lose the event handlers set in the constructor.
Since the plugin is registered as a singleton, in order to work you need to create a new instance of the MvxImagePictureTask.

**Comment by martijn00** [comment]
@barbualexxa Could you make a PR to fix this issue?
