### ISSUE TITLE
Explicitly use `[Register]` flags on all classes referencable from AXML

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#958]
As the title says, Xamarin.Android 5 series add a new requirement of explicitly using `[Register]` on all classes that can be used in AXML. So we need to do that.

http://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#Android_Callable_Wrapper_Naming

https://forums.xamarin.com/discussion/37277/alpha-release-xamarin-android-5-1-0-new-features-and-bug-fixes

**Comment by andyci** [comment]
https://forums.xamarin.com/discussion/comment/118422/#Comment_118422 for more info

**Comment by jamie94bc** [comment]
This can be closed now - was merged yesterday.
