### ISSUE TITLE
Factoring out MvxNotifyPropertyChanged

### ISSUE THREAD

**Issue by runarj** [MvvmCross/MvvmCross#959]
I think it would make sense to factor out MvxNotifyPropertyChanged ( https://github.com/MvvmCross/MvvmCross/blob/c306ba37afd9024f68b7a4f1fedcaf4cf7d01b8d/Cirrious/Cirrious.MvvmCross/ViewModels/MvxNotifyPropertyChanged.cs ) and its superclasses, so that they were held in a separate component. If this was done, it would be possible to use notification in the domain layer without referring the entire MvvmCross library.

**Comment by lothrop** [comment]
You could always use INotifyPropertyChanged directly or create your own class with similar notification functionality in your project. MvxNotifyPropertyChanged references and inherits from other classes, too.

**Comment by runarj** [comment]
I am aware of the possibility, and have already created my own functionality by copying out parts of MvxNotifyPropertyChanged. I also added the ability to easily subscribe the notifications from Stylet ( https://github.com/canton7/Stylet/wiki/Listening-to-INotifyPropertyChanged ). But I still would prefer to just reuse MvxNotifyPropertyChanged **and the functionality found in the  superclasses**.

**Comment by lothrop** [comment]
How about submitting a pull request?

**Comment by lothrop** [comment]
Any other opinions on this? I'm not entirely happy with introducing yet another project and Nuget package with just a handful of classes.

**Comment by slodge** [comment]
Sorry... Just catching up after (yet more) skiing :)

I'm a bit worried about factoring out yet another assembly too - I don't often get asked about having too free assemblies.

I guess we could use shared projects to let people do their own assemblies?

What classes would people want in this new assembly? Is it really just this one class (what are the other classes?). If so it might be easier just to fork the classes out of this code?

**Comment by runarj** [comment]
Thanks for taking time to look at this. I think we should close this issue... I currently have no real projects that need this functionality. I fully respect the need to keep the complexity of MvvmCross under control.

My initial though was to factor out MvxNotifyPropertyChanged and the functionality found in the superclasses, but frankly I have too little knowledge to tell whether that makes sense.

My code to support notifications in the domain layer is just copy and paste from MvvmCross and Stylet. It does not make sense to integrate this with MvvmCross. I will continue playing with it, and if I see any use for it I will present my thoughts and code to you.
