### ISSUE TITLE
Visible view converter doesn't work on <include> tag

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#961]
```
<include layout="@layout/TaskProgressPersonnelHolder"
              android:layout_width="fill_parent"
              android:layout_height="wrap_content"
              android:layout_below="@id/personnel"
              app:MvxBind="Visible ShowPerson" />
```

Doesn't work.

**Comment by Stephanvs** [comment]
There is no property called `Visible` or something like that on an Android View object (see: http://developer.android.com/reference/android/view/View.html#attr_android:visibility). Try the `Visibility` binding.

`app:MvxBind="Visibility ShowPerson"`

**Comment by slodge** [comment]
afaik `include` isn't really a standard view either...

you can override the layout parameters - http://developer.android.com/training/improving-layouts/reusing-layouts.html#Include - but I'm not sure you can do visibility.

Best I can think of is that you can set the visibility within your included layout instead

**Comment by slodge** [comment]
Oops - only meant to hit comment... not "close and comment"

One other option is you could use `MvxFrameControl` instead (or you could use the source as a guide for your own control).

Really not sure if it is going to be possible to do anything with `include` - I think it's compile-time-processed, not run-time

**Comment by slodge** [comment]
@Stephanvs - `Visible` is a custom binding in Mvx - it allows `bool` to be used on the VM property instead of the `MvxVisibility` enum

**Comment by slown1** [comment]
Hello, does it work?

Thanks.

**Comment by slown1** [comment]
For me it worked.
![pasted image at 2016_06_12 11_23 pm](https://cloud.githubusercontent.com/assets/2652146/15993621/d79a5d82-30f4-11e6-9ad5-01d43d361f79.png)
