### ISSUE TITLE
Q: Why does MvxAndroidViewsContainer force ActivityFlags.NewTask?

### ISSUE THREAD

**Issue by davidschwegler** [MvvmCross/MvvmCross#962]
https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Droid/Views/MvxAndroidViewsContainer.cs#L143

Is it a convenience for... something? Or something more sinister?

I've had to exclude that flag when launching my share activity, because otherwise it messes up the Android back stack (i.e. if I share a link from the browser, when the sharing activity finishes, it won't necessarily go back to the browser, because it's in a separate task). 

Just wondering if there's something I should be concerned about that I'm not thinking of.

**Comment by munkii** [comment]
I came up against this issue too and spoke about it on SO, https://stackoverflow.com/questions/25524972/android-activity-is-not-displayed-after-previously-shown-with-activityflags-newt. As I remember Stuart (slodge) said he wrote that code, to add NewTask, when he was first getting to grips with the crazy world of Android and Activity Tasks. He invited me to submit a change to github but I chickened out and kept my change local. I can send you over my custom Container if you like

**Comment by slodge** [comment]
That's just about it - perfect summary @munkii :) It is there because... it was there in v1... and that's it... happy to change it via contribution, although apps just currently assume it's there so the contribution would have to make it the default...

Make any sense?

:)

**Comment by davidschwegler** [comment]
I'd be interested in hearing feedback on whether there's a default use-case for this I'm missing.

NewTask is generally only used in rare cases where the calling app wants to switch to a completely different activity task (eg a different app's activity stack), rather than placing the called activity on top of your own stack. Eg. launchers, notifications (system always sets it there), maybe launching google maps navigation to an address, etc. http://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_NEW_TASK 

You'd only ever want it if you really knew what you were doing, from my experience. We've developed about a dozen native java applications over the last 5 years, and the few cases where we've used it are for very specific/unusual situations.

I understand it's the "default" currently, but it honestly seems like a bug. It shouldn't affect any in-app navigation behavior, so it's primary affect is creating unexpected user experiences when an MvvmCross app calls out to other apps, which is concerning to me particularly since many MvvmCross developers will be coming from iOS, and not notice they're creating incorrect behavior.

**Comment by slodge** [comment]
I'm not bothered whether we call it a bug or not.

There are lots of apps out there which are written on the existing code and we generally try to avoid breaking changes - especially subtle ones which might cause developers pain. From my 5 years with Android, I've often found mastering the Android back stack quite frustrating - and I fear that Mvx changing its activity launch flags might cause some developers tears and pain. My memories of Android 1.6 and 2.x are thankfully fading, but I know that this flag dates back to me getting my first apps running there and especially to me trying to get backstack clearing working.

As I tried to say before (including to @munkii  way back), I'm open to change on this - but I do try to encourage the project to have sympathy to existing apps where possible.

**Comment by martijn00** [comment]
@munkii We are making many breaking changes for the new 4.0 version of MvvmCross. I am thinking we might want to make this change now too. Could you make a PR, or open a Gist with your change so i could review and test that?

**Comment by munkii** [comment]
I've only just seen this sorry. Do you still want a Gist?

**Comment by martijn00** [comment]
Yes sure.

**Comment by munkii** [comment]
We worked around the issue in a custom MvxAndroidViewsContainer rather than change MVVMCross. Here is the Gist of what I did FWIW, https://gist.github.com/munkii/2304f9a90eea81257e08
