### ISSUE TITLE
MvxCachingFragmentActivity.ShowFragment loading the same cached fragment even with a different bundle

### ISSUE THREAD

**Issue by cyrilcathala** [MvvmCross/MvvmCross#966]
Hello,

**Problem :** 

I first load a fragment X within a container Y and a navigation parameter (id=1). Then I want to load the same fragment Y within the same container Y but with another navigation parameter (id=2). This request loads my cached fragment with data from parameter id=1.

**Cause :** 

The `MvxCachingFragmentActivity.ShowFragment()` method tests if a fragment is already loaded, based on the request parameters tag + contentId. It never tests if the bundle is the same or not.

**Solution (proposals) :** 

1. Provide a way to override `IsContentIdCurrentyShowingFragmentWithTag` and inject some conditions. 
  * Set `IsContentIdCurrentyShowingFragmentWithTag` to protected virtual => low impact
2. Provide a way to register a `Fragment` with a parameter to bypass the test and instantiate a new `Fragment` ignoring the cache. 
  * Modify the `FragmentInfo` and `RegisterFragment` signature => medium impact
3. Store and test if the `Bundle` is different from the one in the current `Fragment`
  * Modify the `_currentFragments` to store the `bundle` => medium impact

What do you think ?

**Comment by Cheesebaron** [comment]
I edited your question (using some more markdown :wink: ) Hope you don't mind.

**Comment by cyrilcathala** [comment]
Sure no problem, I'll use it next time :)

**Comment by slodge** [comment]
From your impact assessment, I like 1.

Which of the 3 gives you the best functionality?

**Comment by cyrilcathala** [comment]
I think option 3 would better match the expected behavior, but I would be fine with option 1 :)
