### ISSUE TITLE
BindinEx wpa8.1

### ISSUE THREAD

**Issue by ryanherman** [MvvmCross/MvvmCross#967]
I can't add bindingex to my wpa81 windows store app.  Any work arounds or is thiis being added in the near future?

**Comment by slodge** [comment]
It's not currently under development - it should be a fairly easy copy and paste from the winrt implementation into the windows common/universal space - open to a contribution/pull request on this

**Comment by ryanherman** [comment]
I have tried to add it, even compiling the DLL and adding it but it doesn't recognize it in XAML when I start typing mvx:Bi.nd

**Comment by ryanherman** [comment]
When I try to add the reference to my WPA8.1 Project I get "Unable to add a reference to project 'Cirrious.MvvmCross.BindingEx.Wpf

**Comment by ryanherman** [comment]
Ok I did it and its all working! @slodge

**Comment by morrisonbrett** [comment]
Sweet!

**Comment by slodge** [comment]
Cooooool :+1:

Now stop teasing and show us the code :)

**Comment by ryanherman** [comment]
How would you like me to show it to you?  I'll work on it tomorrow.

**Comment by ryanherman** [comment]
I'm having an issue w/ the image source conversions, I set a breakpoint in the Convert so I know its hitting it and the value is correct...  The error is below.
        <Image Grid.Row="0" x:Name="HeaderImage" mvx:Bi.nd="Source HeaderModel.BannerUri,Converter=LocalImage" Stretch="Fill"/>

namespace Incroud.Mobile.Phone.NativeConverters
{
    public class LocalImage : IMvxValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value == null)
                return null;

            var x = value as string;

            if (x.Length > 0 && x.Contains("res:"))
            {
                x = x.Replace("res:", "ms-appx:///Assets/");
                return x + ".png";
            }
           
            return x;
        }
}
}

MvxBind:Error:  4.93 Problem seen during binding execution for binding Source for HeaderModel.BannerUri - problem COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
	   at Windows.UI.Xaml.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Cirrious.MvvmCross.BindingEx.WindowsShared.MvxBinding.Target.MvxDependencyPropertyTargetBinding.SetValueImpl(Object target, Object value)
   at Cirrious.MvvmCross.Binding.Bindings.Target.MvxConvertingTargetBinding.SetValue(Object value)
   at Cirrious.MvvmCross.Binding.Bindings.MvxFullBinding.UpdateTargetFromSource(Object value)

**Comment by martijn00** [comment]
It's in this PR i supose: https://github.com/MvvmCross/MvvmCross/pull/973

**Comment by Cheesebaron** [comment]
WindowsCommon implementation is there.
