### ISSUE TITLE
Sometime CrossUI.Touch Elements don't repaint until rotated

### ISSUE THREAD

**Issue by munkii** [MvvmCross/MvvmCross#977]
I am using StyledStringElement and StyledMultilineElement in iOS and they do not always populate after the ViewModel has been populated.

However if I rotate the device (or simulator) the Elements are repainted. Obviously the rotation forces a redraw but this obviously should not be needed. An example of our binding is this 

```
 var inlineBindingsSet = this.CreateInlineBindingTarget<ClinicianHubViewModel>();

RootElement rootElement = new RootElement
{
      new Section("Next Appointment")
                      {
                          this.CreateNextAppointmentTimeAheadElement(inlineBindingsSet),
                          this.CreateNextAppointmentPatientElement(inlineBindingsSet)
                      },
      this.BottomSection(inlineBindingsSet)
};

private StyledStringElement CreateNextAppointmentTimeAheadElement(MvxInlineBindingTarget<ClinicianHubViewModel> bindings)
{
            this.nextAppointmentTimeAheadElement = new StyledStringElement()
                                 { 
                                    BackgroundColor = Colors.FromHex(Colors.OurColors.Blue2), 
                                  }
                                 .Bind(bindings, "Caption", "NextAppointmentTimeAhead");
            return this.nextAppointmentTimeAheadElement;
}

```

It is worth mentioning that we are mixing an MvxDialogViewController with an MvxViewController like so rather than creating a RootElement straight off of this.Root.

```
this.rootElementDvc = new DialogViewController(UITableViewStyle.Grouped, rootElement);
this.AddChildViewController(this.rootElementDvc);
this.View.AddSubview(this.rootElementDvc.View);
this.rootElementDvc.DidMoveToParentViewController(this);
```

**Comment by slodge** [comment]
It might be worth checking to see if the MT.D main project has any fixes for this.

If not, then someone will need to dig into the Styled code and see why it's not forcing through the repaint.

**Comment by munkii** [comment]
I spent almost a whole day looking at this and stepping through the StyledStringElement, ValueElement and Element code. I tried many things and could not get it to update when the update was the result of a background data change after they originally painted.

In the end I call this after the ViewModel has finished

this.rootElementDialogViewController.ReloadTableView();

This meant it repainted but it does seem a bit heavyweight

**Comment by kjeremy** [comment]
CrossUI has been removed as of 41f191574d11e6e1a664336e7108cfa1e59a4383
