### ISSUE TITLE
Installing AppCompat 22.1.1 causes inflation of Mvx classes to fail

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#981]
I just installed AppCompat 22.1.1 (up from latest 21.x) and now my MvvmCross views don't inflate from XML.  

It throws an exception when inflating the views at: https://github.com/MvvmCross/MvvmCross/blob/c306ba37afd9024f68b7a4f1fedcaf4cf7d01b8d/Cirrious/Cirrious.MvvmCross.Binding.Droid/BindingContext/MvxAndroidBindingContext.cs#L85

Now the java inflater thinks that ```MvxGridView``` is ```android.views.MvxGridView```.  If I use ```Mvx.MvxGridView``` then it tries to inflate ```Mvx.MvxGridView```.  If I use the full class name in the axml: ```Cirrious.MvvmCross.Binding.Droid.Views.MvxGridView``` then it seems to work.

**Comment by kjeremy** [comment]
See https://bugzilla.xamarin.com/show_bug.cgi?id=29434

**Comment by kjeremy** [comment]
Also this could be taking in the new view naming logic and might be the root cause: https://bugzilla.xamarin.com/show_bug.cgi?id=29471

**Comment by kjeremy** [comment]
So I now have 22.1.1.1 and it still fails.

According to https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate.html#installViewFactory%28%29 it looks like if you're using your own ```LayoutInflater.Factory``` then you shouldn't call ```installViewFactory```.  In fact if I do this in my custom activity then it doesn't crash in ```MvxAndroidBindingContext.CommonInflate```'s inflater anymore.

If that is the case then we can't use ```AppCompatActivity``` or ```AppCompatDialog``` or any other third party activity/fragment that will ultimately call ```AppCompatDelegate.InstallViewFactory``` unless someone can think of a workaround.  I'm pretty lost at this point.  Maybe @Cheesebaron, or @gshackles has an idea.

**Comment by Cheesebaron** [comment]
I think we need to look at how others do it. Calligraphy does it here: https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyLayoutInflater.java

They had a similar issues:
https://github.com/chrisjenx/Calligraphy/issues/84
https://github.com/chrisjenx/Calligraphy/issues/92

We need to modify our `LayoutInflator.Factory` to call [`onCreateView`](https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate.html#createView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet)) with the correct signature, when using AppCompat stuff. https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Binding.Droid/Binders/MvxBindingLayoutInflatorFactory.cs#L65

**Comment by kjeremy** [comment]
If I use my own implementation of ```MvxAndroidBindingContext``` I can use ```LayoutInflaterCompat.SetFactory```:

```
public class AndroidBindingContext : MvxAndroidBindingContext
    {
        private readonly Context _droidContext;

        public AndroidBindingContext(Context droidContext, IMvxLayoutInflater layoutInflater, object source = null)
            : base(droidContext, layoutInflater, source)
        {
            this._droidContext = droidContext;
        }

        public override View BindingInflate(int resourceId, ViewGroup viewGroup, bool attachToRoot)
        {
            return this.CommonInflate(resourceId, viewGroup, this.FactoryFactory.Create(this.DataContext), attachToRoot);
        }

        protected override View CommonInflate(int resourceId, ViewGroup viewGroup, IMvxLayoutInfactorFactory factory, bool attachToRoot)
        {
            using (new MvxBindingContextStackRegistration<IMvxAndroidBindingContext>((IMvxAndroidBindingContext)this))
            {
                using (LayoutInflater layoutInflater = this.LayoutInflater.LayoutInflater.CloneInContext(this._droidContext))
                {
                    using (factory)
                    {
                        if (factory != null)
                        {
                            LayoutInflaterCompat.SetFactory(layoutInflater, (ILayoutInflaterFactory)factory);
                            //layoutInflater.Factory = (LayoutInflater.IFactory)factory;
                        }
                        View view = layoutInflater.Inflate(resourceId, viewGroup, attachToRoot);
                        if (factory != null)
                            this.RegisterBindingsWithClearKey((object)view, (IList<IMvxUpdateableBinding>)factory.CreatedBindings);
                        return view;
                    }
                }
            }
        }
    }

private class BindingLayoutInflatorFactory : MvxBindingLayoutInflatorFactory, ILayoutInflaterFactory
        {
            public BindingLayoutInflatorFactory(object source)
                : base(source) {}

            public View OnCreateView(View parent, string name, Context context, IAttributeSet attrs)
            {
                if (name == "fragment")
                    return (View)null;
                
                View view = this.AndroidViewFactory.CreateView(name, context, attrs);

                if (view != null)
                    this.Binder.BindView(view, context, attrs);
                return view;
            }
        }
```

And this seems to mostly work.  Unfortunately it doesn't work on my fragments because MvvmCross hardcodes them to use ```MvxAndroidBindingContext```.

**Comment by kjeremy** [comment]
The above allows me to use ```AppCompatActivity``` without removing the ```installViewFactory``` call.  So I think we need an extension point somewhere or need to use ```LayoutInflaterCompat.SetFactory``` in ```MvxAndroidBindingContext``` and pull in the dependency on Support v4.  I can't figure out how to make this work in my existing application without a new version of MvvmCross.

**Comment by kjeremy** [comment]
Pull request #983 installs the factory in the right way.  It does mean we need to use Support v4 in MvvmCross but I think that's okay since everyone else in the world uses it and we can avoid some of the platform bugs that have cropped up in this area.

**Comment by kjeremy** [comment]
#988 is an alternate approach to this that basically reimplements ```LayoutInflaterCompat``` in MvvmCross.  I didn't realize that google's github mirror was not up to date which is why I missed the huge workaround for 11 =< API < 21.  As wary as I am about making Support.V4 a dependency for MvvmCross I think #988 shows why there may be a compelling reason to do so.
