### ISSUE TITLE
MvxFragment fails to get instantiated with Xamarin.Android 5.1

### ISSUE THREAD

**Issue by ericgreenmix** [MvvmCross/MvvmCross#984]
With the changes from the latest Xamarin.Android release, the way fragments are getting instantiated fails due to the new naming conventions that were introduced.

http://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#Android_Callable_Wrapper_Naming

The following is the function that currently generates the names that break with the new convention.

https://github.com/MvvmCross/MvvmCross/blob/2b1e44e5837acb7e4f9c12019df0369abf33e384/Cirrious/Cirrious.MvvmCross.Droid.Fragging/MvxCachingFragmentActivity.cs#L245

**Comment by julianpaulozzi** [comment]
I'm having the same problem in my custom controls. I get View type not found - md5...

**Comment by azchohfi** [comment]
So I'm not the only one! My workaround was to use abbreviations.

**Comment by julianpaulozzi** [comment]
#azchohfi excuse my lack of knowledge, how to use it?
My controls worked previously only by override in Setup the "AndroidViewAssemblies", adding the returned base list the GetType().Assembly.

**Comment by julianpaulozzi** [comment]
I saw how. This worked. 
Thank you

**Comment by ericgreenmix** [comment]
How did you do it @julianpaulozzi ?

**Comment by slodge** [comment]
Is this just https://github.com/MvvmCross/MvvmCross/pull/965 ?

**Comment by rafaelfukuda** [comment]
Had the same problem. Thanks for the abbreviation tip, worked for me :)
Here's the link: http://blog.ostebaronen.dk/2012/12/adding-view-namespace-abbreviations-in.html

**Comment by julianpaulozzi** [comment]
I used the some tip from blog posted by rafaelfukuda above. This worked.

**Comment by kjeremy** [comment]
If you are using an activity based on ```ActionBarActivity``` or ``AppCompatActivity``` you could be hitting #981 which shows up in a similar fashion.  This one also fails to inflate Mvx and other classes because our factory doesn't get installed correctly.  You can also work around this issue by using the full name (but other things still fail).

**Comment by ericgreenmix** [comment]
The abbreviations worked for me. 

I also found that using the [Register(yournamespace)] on every fragment class solves the issue. This seems to be how Xamarin is recommending you fix this issue, so I am going to close this because it appears to be not be on the MVX side.
