### ISSUE TITLE
Xamarin.Android 5.1 changes how classes are named in Java, breaking bindings in AXML

### ISSUE THREAD

**Issue by adamcogx** [MvvmCross/MvvmCross#987]
Please see http://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#Android_Callable_Wrapper_Naming from an explanation of the changes.

The result is that BindingInflate complains that it cannot find bindings for components, because the names are now mdXXXXXXXXXXXXXXXXXXXXXXx.Button instead of Button.

**Comment by adamcogx** [comment]
Ok, this is interesting.  I had an AXML that represented the view for a fragment that was bound to the ViewModel and the Fragments were in a ViewPager, and they stopped working.  But I have a AXML that represents the item template in a MvxListView and they worked fine.

**Comment by martijn00** [comment]
The ACW naming for MvvmCross stuff has been fixed in #965 . The reason for what you experience lays within issue #981 and issue #984 . A quick fix is to add `[Register("app.namespace.FragmentName")] ` on every fragment.
