### ISSUE TITLE
Xamarin.Android.Support.v4 version 22.1.1.1 seems to break Fragment data binding

### ISSUE THREAD

**Issue by smoy** [MvvmCross/MvvmCross#990]
My current setup is using Xamarin.Android 5.1. I have a subclass of MvxFragment that I can instantiate and add to a MvxFragmentActivity. The fragment shows up on screen but data binding is not happening. When I downgrade Xamarin.Android.Support.v4 to 22.0.0.0, the data binding works again. 

I am using MvvmCross 3.5 with MvvmCross.HotTuna.Droid.Fragging at 3.5 as well. Since I can instantiate the fragment, I am not sure if I am bitten by the ACW changes in Xamarin 5.1.  I can isolate only to Xamarin.Android.Support.v4 v 22.0.0.0 works whereas Xamarin.Android.Support.v4 v 22.1.1.1 breaks my fragment data binding.

**Comment by ertay** [comment]
+1 to this, same problem here.

**Comment by slodge** [comment]
Is there a sample anywhere for people to look at? - e.g. a github repo?

**Comment by TWhidden** [comment]
+1 - Same here.

**Comment by slodge** [comment]
Is there a sample anywhere for people to look at? - e.g. a github repo?

**Comment by smoy** [comment]
Gonna work on a standalone sample to illustrate this problem now. Hopefully get it done this afternoon.

**Comment by smoy** [comment]
Good news! With the mvvmcross 3.5.1 and fragging support 3.5.1, everything is working again with the latest Xamarin Android Support v4 v.22.1.1.1

MvvmCross++

(Sorry, i have been dragging my feet to write the standalone app)
