### ISSUE TITLE
MvxOwnerViewModelFragment missin

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross#992]
In the release notes ```MvxOwnerViewModelFragment``` is mentioned but I'm not seeing it in the sources.

**Comment by slodge** [comment]
https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Droid.Fragging/MvxOwnedViewModelFragmentAttribute.cs ?

**Comment by kjeremy** [comment]
Ah. Spelling mistake :)
