### ISSUE TITLE
MvxModalNavSupportTouchViewPresenter constructor does not match IUIApplicationDelegate signature

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#995]
public MvxModalNavSupportTouchViewPresenter(UIApplicationDelegate applicationDelegate, UIWindow window)

should be 

    public MvxModalNavSupportTouchViewPresenter(IUIApplicationDelegate applicationDelegate,  UIWindow window)

**Comment by Cheesebaron** [comment]
Pull request?

**Comment by softlion** [comment]
well to generate a pull request you should have a github clone of mvvmcross. I use the nuget version.

**Comment by slodge** [comment]
Thanks :)

(just for info) you can do a quick branch, edit and pull using the edit button within the browser (some pictures in https://github.com/blog/905-edit-like-an-ace) - however, this definitely isn't recommended for big changes!

**Comment by Cheesebaron** [comment]
Welcome to GitHub @softlion as @slodge mentioned you can edit the file directly here on GitHub. Whoa! Crazy, huh?!
