### ISSUE TITLE
Does SubscribeOnMainThread enables the subscriber to receive messages published on the main thread?

### ISSUE THREAD

**Issue by theofanis** [MvvmCross/MvvmCross#999]
What the title says, since I don't see my `OnMessage()` firing when using `SubscribeOnMainThread()` and the messenger publishes on the main thread. `Subscribe()` works ok for this case.

I'm not sure I understand it correctly from the provided documentation, so don't mind me asking. :)

EDIT: To add to my question, if I want to handle messages published both on the main threads and on background threads, depending on the publisher's action, should I use both subscriptions? Or just use subscribe and make sure that all published happen on the main thread using, in my case (`Xamarin.Mac`), `InvokeOnMainThread()`?

**Comment by slodge** [comment]
There are times when my docs can be criticised.... this isn't one of them :) See https://github.com/MvvmCross/MvvmCross/wiki/MvvmCross-plugins#messenger which includes:

> SubscribeOnMainThread - any message published on a background thread will be marshalled to the main UI thread. This type of subscription is ideal if your message handler needs to perform some resource-unintensive task which involves interacting with the UI.

For general questions, please use stackoverflow or forums or ... - trying to keep Github for bugs and for issues please :)
